sdcm/nemesis.py

set_current_disruption() is missing in MemoryStress Monkey.

fix(nemesis): set current disruption for MemoryStress Monkey

---

sdcm/nemesis.py

Cluster health checker warned about schema disagreement because of it wasn't finished
after Scylla start. Added function to wait for schema agreement

fix(disrupt_kill_scylla): wait for schema agreement after disrupt_kill_scylla

---

cdc_replication_test.py
jenkins-pipelines/feature-cdc-replication-gemini-postimage.jenkinsfile
jenkins-pipelines/feature-cdc-replication-gemini-preimage.jenkinsfile
test-cases/cdc/cdc-15m-replication-postimage.yaml
test-cases/cdc/cdc-15m-replication-preimage.yaml

The original test uses delta entries in the CDC log to replicate changes to another cluster.
This PR adds an option to use preimages or postimages.
With postimages it's pretty much the same as with deltas, except that we don't compare timestamps of cells in the master and replica cluster. They might change when we overwrite an entire row.
With preimages it's trickier. The test will work as follows: instead of checking consistency with scylla-migrate, we will use the replicator itself. As before, the replicator will use CDC log's delta entry to write to the replica cluster. However, before it performs the write, it will query the replica cluster, and compare the results with the CDC log's preimage.
In preimage and postimage modes we use gemini with a single thread to perform the writes. …

Extend CDC replication test with pre/post-image modes.

---

jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile

Due to issue 6925, it looks like internode_compression not working at all.
Setting this parameter to 'none' for now.

fix(rolling-upgrade): Removing internode_compression 'all' from upgrades

---

internal_test_data/multi_region_dc_test_case.yaml
sdcm/cluster_aws.py
test-cases/cdc/cdc-15m-replication-gemini.yaml
test-cases/cdc/cdc-15m-replication-postimage.yaml
test-cases/cdc/cdc-15m-replication-preimage.yaml
test-cases/cdc/cdc-15m-replication.yaml
test-cases/features/dns-cluster-5min.yaml
test-cases/features/enospc-30mins.yaml
test-cases/features/ics_space_amplification_test.yaml
test-cases/load/admission_control_overload_test.yaml
test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
test-cases/manager/manager-regression-ipv6.yaml
test-cases/manager/manager-regression-multiDC-set-distro.yaml
test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml
test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
test-cases/performance/perf-regression-latency-1TB.yaml
test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
test-cases/performance/perf-regression-latency-500gb-30min.yaml
test-cases/performance/perf-regression-latency-lwt-big.yaml
test-cases/performance/perf-regression-latency-lwt-small.yaml
test-cases/performance/perf-regression-throughput-cdc-mixed-poll-batching.yaml
test-cases/performance/perf-regression-throughput-lwt-big.yaml
test-cases/performance/perf-regression-throughput-lwt-small.yaml
test-cases/performance/perf-regression-write-latency-cdc.yaml
test-cases/performance/perf-regression-write-throughput-cdc.yaml
test-cases/performance/perf-regression.100threads.30M-keys.yaml
test-cases/performance/perf-row-level-repair-1TB.yaml
test-cases/upgrades/manager-upgrade.yaml

c4 instance type is not available in some regions, moving to c5 instead.

fix(instance_type): using c5 type instead of c4

---

sdcm/cluster.py
sdcm/nemesis.py

the function wait_db_down had too large wait between
the tries, so we missed the time window where
the port stopped replying, and the test got stuck
on waiting for db down, when it was already up.
Reducing the time between tries will give us better
coverage for the time the port stops listening

fix(killscylla): wait_db_down has too large wait

---

vars/runSctTest.groovy

In byo longevity job, the assigned update_db_packages can't be used to
replace scylla in AMI.
This patch added an export to pass the value to test.

fix(runSctTest): export SCT_UPDATE_DB_PACKAGES

---

sdcm/tester.py

fix(tester.py): Disabling set_system_auth_rf function for Siren cloud

---

sdcm/nemesis.py

https://trello.com/c/HBdL4eoB/2276-k8s-drainermonkey

fix(sdcm/nemesis.py): enable DrainerMonkey for kube

---

test-cases/longevity/longevity-counters-multidc.yaml
test-cases/longevity/longevity-lwt-24h-multidc.yaml

Enabling internode_connection for multi-dc longevity jobs.
For now set to "all".
There is a trello task to support also other options "rack, dc".
Then, one should be change to "dc".

Set multi-dc jobs to use server encryption (internode_encryption)

---

sdcm/cluster.py
sdcm/nemesis.py

https://trello.com/c/7Q9ec813/2277-k8s-corruptthenrepairmonkey

fix(sdcm/nemesis): enable CorruptThenRepairMonkey for kube

---

sdcm/nemesis.py

- [ x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)

fix(sdcm/nemesis): enable ModifyTableMonkey for kube

---

jenkins-pipelines/manager-backup.jenkinsfile
jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
vars/managerPipeline.groovy

following scylladb/scylla-pkg#1405 , we want
to trigger all SCT jobs only once a day. Since the jobs configured in
Jenkins are still free-style and not pipeline, we are setting a default
for SCT jobs so they will start only once a day regardless to number of
new commits

manager pipeline: set default value for SCT jobs

---

sdcm/cluster.py
sdcm/tester.py

feature(scylla-bench): support not stopping a test when the tool failed

---

jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile

f3f607f9546046fdca2142bfdefba39ef6d4d9da introduced a some trailing-whitespaces
in some files

fix(whitespaces): manager pipeline: set default value for SCT job

---

sdcm/cluster.py

was failing with the following exception:
```
requests.exceptions.InvalidURL: Failed to parse: 2a05:d018:eb8:3100:b8c9:4e23:966c:c8c1:10001
```
since we didn't escape the address correctly

fix(is_manager_agent_up): ipv6 support

---

jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
vars/managerPipeline.groovy

Adding defaults to latest for `target_scylla_mgmt_server_repo` and for
`target_scylla_mgmt_agent_repo`, so master should need to be triggered with
specific versions
Also renamed `centos-manager-upgrade.jenkinsfile` to match other pipeline files.
TODO:

refactor(manger-upgrade): add defaults targets repos

---

performance_regression_row_level_repair_test.py
sdcm/cluster.py
sdcm/db_stats.py
sdcm/results_analyze/__init__.py
sdcm/tester.py
sdcm/utils/common.py

Trello: https://trello.com/c/XGIdgOvF/1676-make-updatetestdetails-more-stable

improvement(db_stats): make update_test_details more stable

---

sdcm/cluster.py

since we already running ycsb from docker images,
installing it on the loader is a waste of our time and money

refactor(ycsb-install): remove ycsb installation from docker

---

sdcm/cluster.py

It happens from time to time that resharding is finished before Scylla init completed.
Because of we can run nodetool and check if the resharding has been started just after the
Scylla is up, we can't recognize that resharding was started.
This commit added searching into the log to cover this case

fix(recognize resharding): recognize resharding in case it was finished before Scylla init completed

---

sdcm/nemesis.py

https://trello.com/c/P5OW0lbe/2283-k8s-scyllakillmonkey-and-majorcompactionmonkey

fix(sdcm/nemesis.py): enable ScyllaKillMonkey and MajorCompactionMonkey for kube

---

sdcm/nemesis.py

Enable ValidateHintedHandoffShortDowntime, SnapshotOperations, NoOpMonkey and
TopPartitions nemesis for kubernetes

test(enable nemesis for kubernetes): Enable nemesises for kubernetes

---

sdcm/nemesis.py

https://trello.com/c/eSbrDbjx/2296-k8s-adddropcolumnmonkey

fix(sdcm/nemesis): enable AddDropColumnMonkey for kube

---

sdcm/nemesis.py

https://trello.com/c/7QKd52Vy/2294-k8s-deletebypartitionsmonkey-and-deletebyrowsrangemonkey

fix(sdcm/nemesis): enable DeleteByPartitionsMonkey and DeleteByRowsRangeMonkey for kube

---

sdcm/nemesis.py

https://trello.com/c/Roq15ziJ/2285-k8s-nocorruptrepairmonkey

fix(sdcm/nemesis.py): enable NoCorruptRepairMonkey for kube

---

sdcm/nemesis.py

https://trello.com/c/pPjzwjao/2278-k8s-corruptthenrebuildmonkey

fix(sdcm/nemesis.py): enable CorruptThenRebuildMonkey for kude

---

sct.py
sdcm/sct_config.py
sdcm/sct_events.py
sdcm/sct_events_analyzer.py
sdcm/tester.py
test-cases/PR-provision-test-docker.yaml
test-cases/PR-provision-test.yaml
test-cases/load/admission_control_overload_test.yaml
test-cases/longevity/longevity-10gb-3h.yaml
unit_tests/test_cluster.py
unit_tests/test_decode_backtrace.py
unit_tests/test_events.py
vars/getJobTimeouts.groovy
vars/longevityPipeline.groovy

https://trello.com/c/kSXVTnzl/2070-stop-the-test-gracefully-when-the-jenkins-job-stopped-by-timeout
1. Make event analyzer fail test by timeout
2. Fix test duration for some tests
4. Fix pipeline to get steps timeout from test yaml

Improve timeout handling

---

sdcm/nemesis.py

https://trello.com/c/fBXDcYBU/2321-k8s-noderestartwithresharding

fix(sdcm/nemesis): enable NodeRestartWithResharding for kube

---

sdcm/sct_config.py
sdcm/utils/common.py
unit_tests/test_config.py

now that we have unified debain package for a while, and relang introduced
latest list/repo for all of them
we can now search by branch (i.e. 'master:latest', 'branch-4.2:latest')
like we are doing for AMIs

feature(sdcm.utils.common): `find_scylla_repo()` for branch version

---

jenkins-pipelines/manager-backup.jenkinsfile
jenkins-pipelines/manager-sanity.jenkinsfile
test-cases/manager/manager-regression-ipv6.yaml
test-cases/manager/manager-regression-multiDC-set-distro.yaml
test-cases/upgrades/manager-upgrade.yaml

And cause of the the default of 60min kicked in togther
with recent changes to timeout control, and tests are
timing out before ending.

fix(manager-timeouts): manager test-cases missing `test_duration`

---

sdcm/cluster_aws.py

If disrupt_restart_then_repair_node nemesis is run with ip_ssh_connections='public'
replacement node procedure should be initiated also, not like for private
[Task](https://trello.com/c/X1uyyhS6/2316-change-disruptrestartthenrepairnode-nemesis-to-be-able-to-run-it-when-ipsshconnectionspublic)

fix(replacement node with public): replacement node procedure fix when ip_ssh_connections is public

---

sdcm/nemesis.py
unit_tests/test_nemesis.py

https://trello.com/c/ntRf3tMj/2300-fix-complex-nemesis-to-pick-kubernetes-nemesis-on-non-kubernetes-run
Currently complex monkeys pick only non-kubernetes Nemesis on non-kubernetes tests.
It will address this issue.

fix(sdcm/nemesis): don't filter out kubernetes nemesis if it is running on other backend

---

sdcm/nemesis.py

https://trello.com/c/XhvqEvq3/2297-k8s-toggletableicsmonkey

fix(sdcm/nemesis): enable ToggleTableIcsMonkey for kube

---

sdcm/cluster.py
sdcm/nemesis.py
sdcm/remote/base.py

https://trello.com/c/VoFswDGm/2286-k8s-refreshmonkey

fix(scdm/nemesis): enable RefreshMonkey for kube

---

cdc_replication_test.py
jenkins-pipelines/feature-cdc-replication-longevity.jenkinsfile
test-cases/cdc/cdc-replication-longevity.yaml

This is yet another CDC replication test. The previous tests worked as follows:
1. start cluster
2. run workload for 15 minutes, bootstrap a node in the middle
3. check consistency
This test is a longevity test, supposed to run over the period of several hours. The test works in rounds; each round consists of generating workload for about 30 minutes and checking consistency after. The test performs 12 rounds which should result in about 6 hours of testing.
The purpose of splitting the test into rounds and not just checking consistency after a total of 6 hours of workload is to catch any occurring inconsistencies earlier.
The test also runs the ChaosMonkey nemesis during the rounds.

Add a CDC replication longevity test

---

cdc_replication_test.py
sdcm/remote/kubernetes_cmd_runner.py

fix(kubernetes_cmd_runner.py): fix run for 'sudo -u scylla' case

---

sdcm/cluster.py
sdcm/cluster_k8s.py
sdcm/nemesis.py

https://trello.com/c/66QkGnEn/2331-k8s-hardrebootnodemonkey

fix(sdcm/nemesis): enable HardRebootNodeMonkey for kube

---

sdcm/cluster_k8s.py
sdcm/utils/remote_logger.py

https://trello.com/c/39kTqNGY/2334-scylla-k8s-node-logs-are-not-streamed-when-pods-are-restarted

Fix operator loggging

---

sdcm/nemesis.py

ChaosMokneys calls descrupt methods with no arguments, because of that disrupt_nodetool_refresh is getting failed since it requires big_sstable argument

fix(nemesis): fix disrupt_nodetool_refresh failing when chaosmonkey invokes it

---

sdcm/cluster.py
sdcm/nemesis.py

Per original issue reported by the customer:
https://github.com/scylladb/scylla-enterprise/issues/1350
We need to extend 'disrupt_snapshot_operations' to run 'nodetool snapshot' more options including
multiple tables. Random choose between:
- create snapshot of all keyspaces
- create snapshot of one keyspace
- create snapshot of few keyspaces
- create snapshot of few tables, including MVs

feature(snapshot multiple tables): extend disrupt_snapshot_operations nemesis

---

jenkins-pipelines/longevity-alternator-200gb-48h.jenkinsfile
jenkins-pipelines/longevity-alternator-3h-multidc.jenkinsfile
test-cases/longevity/longevity-alternator-200GB-48h.yaml
test-cases/longevity/longevity-alternator-3h-multidc.yaml

Increase alternator test duration to avoid job aborting.

fix(test_duration_alternator): Fix test duration for alternator tests

---

jenkins-pipelines/feature-cdc-replication-gemini-postimage.jenkinsfile
jenkins-pipelines/feature-cdc-replication-gemini-preimage.jenkinsfile
jenkins-pipelines/feature-cdc-replication-gemini.jenkinsfile
jenkins-pipelines/feature-cdc-replication-longevity.jenkinsfile
test-cases/cdc/cdc-15m-replication-gemini.yaml
test-cases/cdc/cdc-15m-replication-postimage.yaml
test-cases/cdc/cdc-15m-replication-preimage.yaml

Fix test duration for all cdc replication tests.

fix(cdc_repl_tests): Fix test timeouts for cdc replication tests

---

sdcm/logcollector.py

seem like some of the code in the collector isn't take ipv6 into
account
failing test like that:
```
Port could not be cast to integer value as 'd018:eb8:3100:e9c6:8ec0:7c58:22'
```

fix(logcollector): support of ipv6 in grafana urls

---

sdcm/cluster.py

Since the is_port_used check was unnecessary,
I removed it from is_manager_server_up and is_manager_agent_up

fix(manager): Got rid of port check in wait_manager_up

---

test-cases/longevity/longevity-5000-tables.yaml

Enable sequentially node adding to cluster with bootstrap.
Due to issue 7165, when repair_based_operations is enabled 
the default behavior for scylla master and 4.2,
Add node takes more time for each node to bootstrap with 5000 tables 
and when we're not waiting for the other nodes to join 
their bootstrap get stuck.

fix(longevity_5000_tables): Enable sequentially init cluster

---

test-cases/manager/manager-regression-gce.yaml

And cause of the the default of 60min kicked in togther
with recent changes to timeout control, and tests are
timing out before ending.

fix(manager-timeouts): manager gce test-case missing `test_duration`

---

sdcm/nemesis.py

`disrupt_remove_node_then_add_node` code was shadowing the node variable
in a for loop, cause the `target_node` to be assigned to `node`
hence failing randomly
```
26ce06ee-8 [13.48.133.167 | 10.0.2.189] (seed: False) duration=594
error=Unable to run "nodetool  status ": failed connecting to "10.0.2.189" during 60s
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2317, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2584, in disrupt
self.call_random_disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 759, in call_random_disrupt_method
disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1822, in disrupt_remove_node_then_ad …
```

fix(nemesis): nemesis running nodetool status on a dead node

---

sdcm/cluster.py
sdcm/utils/common.py

https://trello.com/c/k9nSQKGh/2315-k8s-enospcmonkey-and-enospcallnodesmonkey

fix(sdcm/nemesis): enable EnospcMonkey on kube

---

mgmt_upgrade_test.py
sdcm/mgmt.py

Added a test that starts repairs with the following flags:
'--host', '--with-host' and '--token-ranges'
using manager 2.1, upgrades manager to a specified version (where those flags don't exist anymore)
and start the tasks again, expecting them to succeed

test(manager-upgrade): Rerunning repairs that use legacy flags

---

jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile

by mistake we changes all the debian base upgrade pipeline to start
from the wrong versions

fix(manger-upgrade-pipelines): update to start upgrades from manager-2.1

---

sdcm/nemesis.py

seem like in the code we are expecting to get `invoke.UnexpectedExit`
but insted we are getting `sdcm.remote.libssh2_client.exceptions.UnexpectedExit`
this is a temporary fix, since `UnexpectedExit` is used in more places that
need to be checked if that the correct one.

fix(ToggleICS): catching the wrong UnexpectedExit

---

sdcm/utils/common.py
sdcm/utils/remotewebbrowser.py

In manager ipv6 I've seen failures like this, coming from `DockerClient.__init__`:
```
2020-09-08 21:27:53.828: (TestFrameworkEvent Severity.ERROR),
source=MgmtCliTest.update_test_with_errors() message=update_test_with_errors
(silenced) failed with:
exception=Port could not be cast to integer value as 'd018:eb8:3100:fa28:ae78:d480:22'
```

fix(DockerClient): support ipv6 when passing base_url

---

jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile

fix typo in f6a33e9d94cf6ce5876c4f145a2ae216d00bc615

fix(manager-pipeline): typo in ubuntu18-manager-upgrade.jenkinsfile

---

test-cases/longevity/longevity-10gb-3h.yaml
test-cases/longevity/longevity-lwt-basic-3h.yaml
test-cases/upgrades/rolling-upgrade.yaml

due to test failures, I lengthened the test_duration value of those tests

fix(longevity): enlarged the test_duration of some longevities

---

test-cases/scylla-operator/longevity-scylla-operator-3h.yaml

The purpose of the test is to check Scylla operator but not stress Scylla.
We need to improve the c-s command, probably by decreasing the number of threads
to some more soft number, so that we don't receive a lot of 'CassandraStressWriteTooSlow'

fix(stress in operator test): decrease threads in the operator test

---

sdcm/nemesis.py

Wait for target node is up and normal after reboot to prevent failure due the node during
the start and in DN status

fix(wait for node up): wait for the target node up after reboot

---

vars/operatorPipeline.groovy

Set 'latest' as default Scylla version for operator job

fix(operator job scylla version): Set 'latest' as default Scylla version for operator job

---

sdcm/cluster.py

https://trello.com/c/QL5fUshy/2353-tests-failing-on-stopscyllaserver

fix(sdcm/cluseter): fix retrying logic

---

sdcm/tester.py

https://trello.com/c/aBggs5ML/2351-expose-alive-threads-and-processes-left-alive-at-the-end-of-teardown

fix(sdcm/tester): expose threads and processes alive at the end of the teardown

---

sdcm/utils/common.py
sdcm/utils/remotewebbrowser.py

eccef5cebab131dd69b9e475a91626b0b7a022a1 wasn't enough to fix the issue
since a bug in docker package https://github.com/docker-library/python/issues/517

fix(DockerClient): support ipv6 when passing base_url with port

---

vars/runSctTest.groovy

When run job basde on byopipeline with empty update_db_packages
jenkins job failed with error:
line 30: conditional binary operator expected
example : https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/BYO-abykov-staging/23/
Change to check empty string

fix(runscttest.grovy): Fix if condition for updatedbpackages

---

sct.py
sdcm/sct_runner.py

even that we pass down `timeout=100` the `connect_timeout` default to
60s, and since it's a newly created machine, it's not always enoguh
time for it to be ready and available.
```
File "./sct.py", line 812, in create_runner_instance
result = remoter.run("true", timeout=100, verbose=False, ignore_status=True)
File ".../sdcm/remote/remote_base.py", line 601, in run
result = _run()
File ".../sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File ".../sdcm/remote/remote_base.py", line 591, in _run
self._run_pre_run(cmd, timeout, ignore_status, verbose, new_session, log_file, retry, watchers)
File ".../sdcm/remote/remote_cmd_runner.py", line 106, in _run_pre_run
raise SSHConnectTimeoutError(
sdcm.remote.base.SSHConnectTimeoutError: Unable to run "true":
failed …
```

fix(sct_runner): overwrite connect_timeout, 60s wasn't enough

---

test-cases/longevity/longevity-alternator-3h-multidc.yaml

current c-s commands use SizeTieredCompactionStrategy that is incompatable
with multi dc case. In multi dc case we need to use NetworkTopologyStrategy.
Per our discussion with Roy and Israel decided to remove the c-s command
since it is less important for Alternator test case.

fix(alternator-3h-multidc-yaml): remove c-s commands

---

sdcm/cluster.py

Currently we only output the major version (eg: 4.1.2), the full version
(contains the build data and commit prefix) of each node won't be
outputed.
This patch changed to output detailed version by info level, then we can see it
early in jenkins log.

feature(get_scylla_version): output scylla full version

---

sdcm/cluster.py

Old scylla won't create /var/lib/data directory if it doesn't exist,
the service will fail to start.

fix(clean_scylla_data): don't delete the data directory

---

test-cases/longevity/longevity-100gb-4h.yaml

Since we changed the test to use 3 seed nodes instead of 1 the setup phase fails.
Changing the bootstrap mode to start sequentially should solve the problem.

fix(longevity-100gb-4h): Trying to bootstrap the cluster in sequential mode

---

test-cases/longevity/longevity-large-collections-12h.yaml

Jobs with longevity-large-collections-12h-test failed
with issues: 7140, 7222; with no space left on devices
Change the instance type from i3.4xlarge to i3en.3xlarge
to use lager disks.

fix(large_collection_12h): Change instance type to i3en

---

sdcm/logcollector.py
sdcm/tester.py

https://trello.com/c/5s6JaFuY/2363-write-left-threads-and-processes-information-to-the-file

fix(sdcm/tester.py): store left threads into separate file

---

test-cases/longevity/longevity-lwt-500G-3d.yaml

Test was configured to run 1,5 day for debug purposes.
Test duration has been changed to 3 days

fix(test_lwt_3d): Set test duration 3 days for lwt-500g-3d

---

defaults/aws_config.yaml
sdcm/cluster_aws.py
sdcm/ec2_client.py
sdcm/sct_config.py
sdcm/utils/common.py
vars/byoLongevityPipeline.groovy
vars/longevityPipeline.groovy
vars/managerPipeline.groovy
vars/runSctTest.groovy

There are the changes in this commit:
1. Verify test duration on the early stage, when test started
2. Use "floor" operator instead of "round" when calculate spot duration
because of "floor" round float to lower.
Example:
if we have test duration 350, we will get round(350/60)*60+60 > 360, but the maximum is 360
3. fall back (if possible depend on test_duration) to spot_duration when regular spot failed
due to errors. If can't create spot_duration instance, create on_demand
4. Add handling of price-too-low, capacity-not-available errors
5. If spot fleet creation fails - doesn't try to request the other type of instance

fix(improve spot request): Improve spot duration request time calculation

---

sdcm/utils/scylla_args.py

Workaround for https://github.com/scylladb/scylla-enterprise/issues/1473

fix(scylla_args): workaround for doubled scylla options

---

mgmt_upgrade_test.py
sdcm/mgmt.py

The backup force param of manager 2.1 is not supported on version 2.2
so an upgrade where a backup task uses it, should be removed and rerun ok.

improvement(mgmt_upgrade_test.py): Test backup force param removal on 2.2 upgrade

---

mgmt_cli_test.py

since https://github.com/boto/boto3/issues/2596 we got the following error:
```
ImportError: cannot import name 'docevents'
```

fix(manager-restore): pindown awscli version

---

sdcm/tester.py

When alternator test failed because of can't receive the instances, email body failed to be created
with exception: 'NoneType' object has no attribute 'nemesis'
It happened when the test is not save the stats (store_results_in_elasticsearch: false)

fix(alternator email failure): check if cluster object was created

---

jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile

This reverts commit 9527209f3d650bab3353e0d205b9a1709510ff63.
Issue #6925 was fixed, reverting the change that removed internode_compression.

Revert "fix(rolling-upgrade): Removing internode_compression 'all' from upgrades"

---

test-cases/upgrades/rolling-upgrade.yaml

The test started failing often with the error:
"Other bootstrapping/leaving/moving nodes detected, cannot bootstrap
while consistent_rangemovement is true"

fix(rolling-upgrade): Change rolling upgrade to use sequential boot

---

gemini_test.py

If loader was not created (on failed to get spot, for example) email creation failed
with exception: 'NoneType' object has no attribute 'gemini_version'
[Task](https://trello.com/c/Y9PVhXPP/2377-email-is-empty-because-of-exception-nonetype-object-has-no-attribute-geminiversion)

fix(get gemini version): email creation fails if loaders were not created

---

defaults/test_default.yaml
test-cases/PR-provision-test.yaml
test-cases/artifacts/amazon2.yaml
test-cases/artifacts/ami.yaml
test-cases/artifacts/oel76.yaml

According to https://github.com/scylladb/scylla-cluster-tests/pull/2538
change default instance provision type to 'spot'

fix(remove spot_low_price): remove hard coded using of spot_low_price provision

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/operator_monitoring.py

1. ScyllaOperatorLogMonitoring - monitor log for ERROR messages and raise ScyllaOperatorLogEvent
2. ScyllaOperatorStatusMonitoring - monitor operator node status and raise ScyllaOperatorRestartEvent if it was restarted

fix(sdcm/cluster_k8s): implement scylla operator monitoring

---

test-cases/gemini/gemini-1tb-10h.yaml

https://trello.com/c/TxFVMgcR/2370-duration-for-sct-runner-is-set-incorrectly
Also fixes - https://github.com/scylladb/scylla-cluster-tests/issues/2661

fix(gemini-1tb-10h): tune test_duration to meaningfull value

---

sdcm/nemesis.py

The sub-command `scrub` had been implemented.

fix(scrub nemesis): switch to use nodetool scrub from API

---

sdcm/sct_config.py

Do not check Scylla version for 'k8s-gce-minikube' backend.
It'll take the docker for selected version

fix(scylla version for k8s): not check scylla version parameter

---

sdcm/cluster.py
sdcm/mgmt.py

fix(manager): deleting automatic repair when adding cluster by default

---

sdcm/nemesis.py

[Task](https://trello.com/c/J2hnub1J/2170-nodetool-refresh-resharding-before-uploading)
[Scylla commit](https://github.com/scylladb/scylla/commit/94634d9945064d7be41b21ac2af0ae36cef37873)
Refresh procedure is:
put the db files for refresh in the "upload" folder
run "nodetool refresh"
refresh command will start resharding
files after resharding are placed into "upload" folder
move resharded files from "upload" to main folder
Add the validation to make sure the resharding is performed in the "upload" folder, not main.

feature(resharding before uploading): nodetool refresh - check resharding before uploading

---

sdcm/mgmt.py

Due to clarification from the manager team, changed the status
the wait_for_uploading_stage function waits for, from 'uploading schema' to 'uploading data',
since 'uploading schema' isn't resumable

fix(manager): fixed wait_for_uploading_stage

---

sdcm/cluster.py

When cluster setup create the nodes in parallel, may happens that one node setup is completed
and run node status validation for all nodes in time the another node is not UN yet. 
In this case ClusterHealthValidator critical error will be raised and fails the test

fix(wait node up and normal): wait when node setup is completed

---

sdcm/cluster.py

When node setup is performs in parallel and there are non-seed nodes, verification
for seed nodes may fail if verification node is not defined and non-seed node
was selected randomly

fix(add verification node): set verification node when call wait_for_nodes_up_and_normal

---

vars/operatorPipeline.groovy

As we can't use 'latest' in scylla_version (issue
https://github.com/scylladb/scylla-operator/issues/180) change default version
to 4.1.7

fix(k8s defaul scylla_version): set default scylla_version to 4.1.7

---

sdcm/remote/__init__.py

Two network errors are missed in the exception_retryable:
SSHConnectTimeoutError, RetryableNetworkException
NETWORK_EXCEPTIONS is defined in the sdcm.remote.init.py and collect exception_retryable
values from sdcm/remote/remote_libssh_cmd_runner.py and sdcm/remote/remote_cmd_runner.py.
It used as allowed_exceptions in retrying for get_core_pids.
The coredump thread in the test from description failed because of got SSHConnectTimeoutError.
Because of this exception is not allowed (that is wrong), the exception was raised and
failed the thread.

fix(network exception): add missed network exceptions

---

sdcm/cluster.py

https://trello.com/c/kr7qqiaf/2359-handle-c-s-java-crashes

fix(sdcm/cluster.py): enable coredump collecting on loaders

---

sdcm/sct_config.py

Fix mistake in partition_range validation

fix(partition range validation): fix mistake in partition_range validation

---

sdcm/sct_config.py
unit_tests/test_config.py

Not search scylla_repo for loader for 'k8s-gce-minikube' backend.

fix(k8s scylla_repo_loader): not search scylla_repo for loader

---

sdcm/cluster.py

Throw event in the resharding Nemesis instead of logging error in the log
when reshardin nemesis fails
[Task](https://trello.com/c/UwbOteMi/2318-throw-event-in-the-resharding-nemesis-instead-of-logging-error-in-the-log)

improvement(resharding nemesis): throw event in the resharding Nemesis instead of logging error in the log

---

test-cases/longevity/longevity-100gb-4h.yaml

It is currently set to unrealistic 4hours 20 minutes, jobs are unually running for 5hours - 5hours 40 minutes.

fix(test-cases/longevity/longevity-100gb-4h.yaml): set test_duration to 6 hours

---

mgmt_cli_test.py
mgmt_upgrade_test.py
sdcm/cluster.py
sdcm/mgmt.py
test-cases/upgrades/manager-upgrade.yaml

* Create new "remote_scylla_manager_yaml" function under "ScyllaManagerBase" class
* Create new "remote_manager_yaml" function under "BaseNode" class
* Remove "mgmt_port" variable from "manager-upgrade.yaml" and use
"manager_prometheus_port" variable
* Change the "mgmt_port" to "12345" and "prometheus_port" to "10091"
* Trello URL: https://trello.com/c/NiSj7KwE

test(mgmt_upgrade_test.py): Upgrading manager with non default port

---

test-cases/upgrades/rolling-upgrade.yaml

Increase timeout due to the test failures
Failed test example:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04-test/63/

fix(rolling upgrade): increase test_duration to 250m

---

docker/env/hydra.sh

Fixes issue: #2691.
Sometimes it happen that AWS creates a SCT Runner instance
with the same public IP address that was used for other
SCT Runner instance past. In this case Hydra won't start
on that SCT Runner since when running Docker on remote host
we can pass SSH options. Hence we need to clean the known
hosts file.
Example of the error message that we get:
```
15:51:45  docker: error during connect: Post http://docker/v1.40/containers/create?name=c2953363-6dfd-44c6-8d0e-2b6dccc3fd9c_1600865481: command [ssh -l ubuntu -- 13.53.69.113 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
15:51:45  @    WARNING: REMOTE HOST …
```

fix(hydra): clean know hosts when running on SCT Runner

---

sdcm/cluster.py

Fixed https://github.com/scylladb/scylla-cluster-tests/issues/2756

fix(sdcm/cluster.py): fix reference before assigment in get_grafana_screenshot_and_snapshot

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_baremetal.py
sdcm/cluster_docker.py
sdcm/nemesis.py

Reverting commit 7b58c4d3 that added a flag to control db_up waiting.
The change caused the nemesis to miss the new node addition because it
didn't wait for the node to complete the bootstrap.

fix(wait_for_init): Reverting the change to control wait for db_up

---

defaults/test_default.yaml
sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/sct_config.py
test-cases/longevity/longevity-counters-multidc.yaml
test-cases/longevity/longevity-lwt-24h-multidc.yaml

Ticket: https://trello.com/c/8L1hyiKd/2273-support-more-serverencrypt-internode-encryption-options
Currently we always use 'all' for internode_encryption when server encrypt is enabled.
This PR added support to set it, and set 'dc' internode_encryption for two multiple dc longevity jobs.

Support to set internode_encryption for server encrypt

---

sdcm/cluster.py
sdcm/cluster_k8s/__init__.py
sdcm/remote/__init__.py
sdcm/remote/base.py
sdcm/remote/remote_file.py
unit_tests/test_remoter.py

Address the latest changes in [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI) about usage of ternary operator.

refactor(remote): get rid of unconventional ternary operators

---

corrupt_then_rebuild_test.py
destroy_data_then_repair_test.py
grow_cluster_test.py
longevity_lwt_test.py
mgmt_cli_test.py
sdcm/cluster.py
sdcm/nemesis.py

The start_nemesis() function now clears the Event responsible for
telling nemesis threads to stop.
`BaseScyllaCluster.termination_event` was renamed to `BaseScyllaCluster.nemesis_termination_event` since it's only being used to notify nemesis threads to terminate.
Fixes #2724.

Make nemesis restartable

---

sdcm/cluster.py
sdcm/nemesis.py

After node drained, stopping scylla server could cause an issue https://github.com/scylladb/scylla/issues/7332.
But if stopping scylla sever failed, the next start could successuly
executed.
Added workaround: not fail nemesis just report the error

fix(stop_scylla_server): Added workaround for stop scylla server

---

defaults/aws_config.yaml

https://trello.com/c/fnElfYAu/2397-c-s-fails-with-cannot-initialize-optimized-memory-deallocator-some-data-both-in-memory-and-on-disk-may-live-longer-due-to-garbag
c-s fails with "Cannot initialize optimized memory deallocator. Some data, both in-memory and on-disk, may live longer due to garbage collection"
This issue happens because we migrated to java11, but did not brign it cassandra-stress.sh and jvm11-client.options to the loader.

fix(loaders): fix c-s issue with ssl certificates

---

sdcm/nemesis.py

Some times the 200 seconds is not enough to detect that
streaming(repair) process started during
"break_streaming_task_and_rebuild" execution method.
This happened during one of latest 7d-1tb job, when
due to race between streaming_task_thread and waiting
streaming started
nodetool rebuild was executed twice and faile the job
Job: https://jenkins.scylladb.com/job/scylla-4.2/job/longevity/job/longevity-1tb-7days-test/14/

fix(is_streaming_started): timeout to wait streaming started increased

---

sdcm/sct_runner.py

Set soft limit on SCT Runner to 4096. Opened FDs limit could be a reason, why the job with 5000
tables failed on during attempt to connect to Scylla server

improvement(increase fd limit): Increase limit of open FDs on SCT runners

---

sdcm/cluster.py

we found out that without passing this, `cpuset.yaml` isn't getting
updated, and it have dire effect on performance on cases we install
from packages

fix(scylla_setup): pass '--setup-nic-and-disks' to scylla_setup

---

sdcm/cluster.py
sdcm/utils/version_utils.py

Trello: https://trello.com/c/t7H1OopH/2211-in-sct-override-scylla-serverservice-finalkillsignal-to-sigabrt-so-we-can-get-a-core-in-such-cases
This feature supported since systemd v240+ (Debian 10 and Ubuntu 20.04 for now)

improvement(config_setup): set FinalKillSignal to SIGABRT

---

vars/artifactsPipeline.groovy
vars/cdcReplicationPipeline.groovy
vars/managerPipeline.groovy
vars/perfRegressionParallelPipeline.groovy
vars/rollingUpgradePipeline.groovy
vars/runSctTest.groovy

In discussion with @dkropachev, we found a better way to perform check "params.x is null or empty string".
The problem that `params` is unmodifiable Map and call `params.get(key, default_value)` will throw exception if there is no such key:
```groovy
>>> ["x": ""].asUnmodifiable().get("y", "")
java.lang.UnsupportedOperationException
at Script1.run(Script1.groovy:1)
```
This PR demonstrates two ways around this issue:
1. Just check (unfortunately, `x as Boolean` will return `null` if `x` is `null`):
```groovy
>>> def map = ["x": "", "y": "foo"].asUnmodifiable()
>>> println(map.z || false)
false
>>> println(map.x || false)
false 
>>> println(map.y || false)
true
```
2. Emulate .get() with default value:
```groovy 
>>> def map = ["x": "", "y": "foo"].asUnmodifiable()
>>> println(map.z ? …
```

refactor(runSctTest): simplify 'params.x is null or empty string' case

---

vars/artifactsPipeline.groovy

fix(artifacts): remove redundant closing parenthesis in .groovy

---

defaults/aws_config.yaml
sdcm/cluster.py

https://trello.com/c/fnElfYAu/2397-c-s-fails-with-cannot-initialize-optimized-memory-deallocator-some-data-both-in-memory-and-on-disk-may-live-longer-due-to-garbag
Somewhere on the way to new loader we have introduced cassandra-driver jars into to the lib directory on the loader.
As result c-s started to use cassandra-driver instead of scylla-driver and we lost shard awarness due to that.
This PR is to bring it back.

fix(loader): bring shard awarness back

---

longevity_test.py
sdcm/logcollector.py
test-cases/longevity/longevity-ycsb-a-10M.yaml
test-cases/longevity/longevity-ycsb-a-1B.yaml
test-cases/longevity/longevity-ycsb-a-1M.yaml

This PR adds support to a YCSB workload A scenario for Scylla.
It also extends the functionality to support:
- multi statements keyspace preparation
- log collection for ycsb

Support ScyllaDB YCSB workload

---

test-cases/longevity/longevity-5000-tables.yaml

Increase nemesis interval to 60 min. We need it to low nemesis impact on the test.
Fix instead of PR #2405 .

fix(5000 tables test): increase nemesis interval

---

mgmt_cli_test.py
mgmt_upgrade_test.py
sdcm/cluster.py
sdcm/mgmt.py

refactor(manager): Removed Enum from TaskStatus

---

test-cases/scylla-operator/kubernetes-scylla-upgrade-gke.yaml
test-cases/scylla-operator/kubernetes-scylla-upgrade-minikube.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-minikube.yaml

Need this because of `message=Cluster.name must be less than 40 characters` error

fix(operator): make user_prefix shorter for GKE

---

test-cases/longevity/longevity-ycsb-a-10M.yaml
test-cases/longevity/longevity-ycsb-a-1B.yaml
test-cases/longevity/longevity-ycsb-a-1M.yaml

The number of core connections must match number of vCPU (16) on a db node - 2.
The number of threads must be divisible by the number of core connections.
Specifically `i3.4xlarge` has 16 vCPU on 8 cores.
- set 14 core connections per node to match number of shards per node
- set number of threads to be 6 * core_conns
- reduce amount of overall ops

effecient YCSB requires explicitly stating connections number

---

sct.py
sdcm/utils/common.py

Should fix fails like this: https://jenkins.scylladb.com/job/scylla-master/job/reproducers/job/byo-throughput-test-clang/6/console

fix(get_branched_ami): split by first colon only

---

jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
mgmt_cli_test.py
sdcm/mgmt.py
test-cases/manager/manager-repair-intensity-multiple-repaired-nodes.yaml
test-cases/manager/manager-repair-intensity-single-repaired-nodes.yaml

Added 2, albeit very similar, new test scenarios which consists of the following loop:
The test starts a new cluster with ~100 GB of data per node and starts a loop,
in it a fault in the data is created and a manager repair is started with certain
--intensity and --parallel parameter values, in order to view the effect of the repair
on the cluster.
The difference between the two scenarios is the amount and location of the fault:
In one scenario all of the files of the test keyspace is being deleted from a pre selected node
and in the second scenario an additional C-S is being ran in such a way that almost
every node has missing rows that require repair

test(manager): tests for intensity and parallel repair options

---

sdcm/utils/prepare_region.py

fix(prepare_region): Added Prometheus Alert Manager port

---

sdcm/utils/common.py
unit_tests/test_utils_common.py

Keep it almost real except getting files content over the network. Just touch files on local side.

improvement(unit_tests): speed up update_db_packages tests

---

sdcm/nemesis.py

fix(disrupt_nodetool_enospc): fix to work on kubernetes, except minikube

---

sdcm/nemesis.py

https://trello.com/c/wbzEvLCX/2420-qualify-nemesis-to-run-on-gke

fix(disrupt_nodetool_decommission): Make it work on kubernetes all the times

---

sdcm/nemesis.py

fix(disrupt_nodetool_enospc): raise UnsupportedNemesis instead of logging

---

test-cases/artifacts/centos7.yaml
test-cases/artifacts/centos8.yaml
test-cases/artifacts/debian10.yaml
test-cases/artifacts/debian9.yaml
test-cases/artifacts/rhel7.yaml
test-cases/artifacts/rhel8.yaml
test-cases/artifacts/ubuntu1604.yaml
test-cases/artifacts/ubuntu1804.yaml

Regression since https://github.com/scylladb/scylla-cluster-tests/pull/2540, caused artifact tests to fail

fix(artifact_tests): set gce_image_db

---

sdcm/nemesis.py
sdcm/tester.py

we have seen IOExceptions raised by c-s as error
failing the whole test when a nemesis kills Scylla
process (hence the exception is expected) and the
load doesn't stop, so, lowering the severity of the
event during the specific nemesis.
Also, had to change in verify_stress_thread not to
fail the test when this IOException is found in the
loader's log, as we are already raising an event
if it is found (so this became redundant).

fix(scyllakillmonkey): reduce severity of event

---

sdcm/cluster.py
sdcm/cluster_docker.py

When backend of the longevity is docker, it should be able to run
scylla-bench load. Add scylla-bench installation in the docker

improvement(install scylla-bench): support scylla-bench when running test in docker

---

sdcm/sct_config.py
sdcm/tester.py

If test is running with PasswordAuthenticator, scylla-bench failed to start
because of authentication required.
It relevant for TruncateLargeParititionMonkey nemesis as well

feature(scylla-bench authentication): add username and password to scylla-bench command

---

defaults/k8s_gce_minikube_config.yaml
defaults/k8s_gke_config.yaml
vars/operatorPipeline.groovy

Trello: https://trello.com/c/V9mCEP2a/2467-operator-change-defaults-to-scylla-420
Since now, set defaults for `scylla_version` and `scylla_mgmt_agent_version` in .yaml only.

fix(operator): switch to Scylla 4.2.0

---

sdcm/fill_db_data.py

* Replace old chahing value (string) to dict value (
https://github.com/scylladb/scylla/issues/6435)

fix(fill_db_data.py): Changing "caching" value to dict

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/gke.py

fix(k8s-gke): wait for clusters readiness

---

sdcm/sct_config.py
unit_tests/test_config.py

fix(sct_config): don't use scylla_repo_loader for AWS

---

defaults/test_default.yaml
test-cases/cdc/cdc-15m-replication-gemini.yaml
test-cases/cdc/cdc-15m-replication-postimage.yaml
test-cases/cdc/cdc-15m-replication-preimage.yaml
test-cases/cdc/cdc-15m-replication.yaml
test-cases/cdc/cdc-replication-longevity.yaml
test-cases/features/scale-cluster.yaml
test-cases/longevity/longevity-100gb-4h.yaml
test-cases/longevity/longevity-5000-tables.yaml
test-cases/upgrades/rolling-upgrade.yaml

Since there is more than one seed, the longevity fail on startup
since  the seeds fail to communicate with eachother. To pervent this issue,
I disabled the parallel node setup

fix(1tb-longevity): Added use_legacy_cluster_init flag to the config

---

sdcm/cluster_aws.py

Since scylla_create_devices fails if var-lib-scylla.mount already exists during its execution,
I moved var-lib-scylla.mount from its regular location

fix(cluster_aws): moved var-lib-scylla.mount away after restart

---

sdcm/cluster.py

https://trello.com/c/Fcf0SWEe/2483-k8s-stop-matching-json-encoded-logs-to-general-regex
Messages that come from sidecar are in json format and are getting mixed with textual logs from scylla.
Some patterns we have, like 'std::runtime_error', 'stream_exception' are comes from seastar, and are generated by both scylla and api server.
Those that generated by api servers are getting leaked thrue sidecar framework and endup in sidecar logs.
Since api server errors are not critical we should avoid them to be matched by same patterns we have for textual scylla logs.
PR pre-checks (self review)

fix(_read_system_log_and_publish_events): stop matching json-encoded logs to the patterns

---

sdcm/nemesis.py

Fix issue #2561  with in multidc configuration GrowShrinkCluster nemesis
could add node to one dc and remove node in another.
This configuration fail test because in some dc not enough replicas
for local quorum
Trello: https://trello.com/c/2J0iEFQ8

fix(set_target_node): allow to set target node in specific dc

---

docker/scylla-sct/Dockerfile
sdcm/cluster_k8s/__init__.py

Workaround for scylladb/scylla#7560

fix(docker): workaround for scylladb/scylla#7560

---

sdcm/cluster.py
unit_tests/test_cluster.py

since master version are now `4.4-dev` and such,
seems like we are looking for 4.4 version on monitoring when
using `hydra invesigate show-monitor`, which doesn't yet exists.
we should default to 'master' in those cases.

fix(show-monitor): monitor missing dashboards on master

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_gce.py

when image setup is finished SMI touches /etc/scylla/machine_image_configured file.
So the the correct way to wait the image setup to be finished is to check if
the file exists.
Fixes: #2855

improvement(cluster): wait for Scylla Machine Image setup to be done

---

defaults/test_default.yaml
internal_test_data/complex_test_case_with_version.yaml
test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml

upgrading the calls (that were not necessary anymore)
to use the one is being upgraded (test_default.yaml).

fix(bump manager version): manager 2.2 was released

---

docs/configuration_options.md
sdcm/sct_config.py

changed the config parameters to be linkable with anchors
so we can send link directly to the specific parameter in where we need it

fix(sct_config): Update of the help markdown

---

sdcm/cluster.py

Now the default limit in grafana API is 100, which mean we extract only 100 of the last events
and when we use `hydra investigate show-monitor` we have last 100 events available.
In longer runs like 48h and more, this isn't helpful, and we are the context like that.

fix(get_grafana_annotations): make the limit much larger

---

sdcm/sct_runner.py

For long runs moving to r5.large since it has 32GB RAM.
Checked all regions, this instance type should be available there:
```
16:49 $ aws ec2 describe-instance-type-offerings --location-type availability-zone  --filters Name=instance-type,Values=r5.large --region eu-north-1 --output table
--------------------------------------------------------
|             DescribeInstanceTypeOfferings            |
+------------------------------------------------------+
||                InstanceTypeOfferings               ||
|+--------------+---------------+---------------------+|
|| InstanceType |   Location    |    LocationType     ||
|+--------------+---------------+---------------------+|
||  r5.large    |  eu-north-1c  |  availability-zone  ||
||  r5.large    |  eu-north-1b  |  availability-zone …
```

fix(sct-runner): workaround for OOM issue #2859

---

artifacts_test.py

amazon2 artifact test doesn't use prepared ami that set cluster name in user-data.
Cluster name validation checks that cluster is named according to the user data, so
this check can't be performed for amazon2 artifact test

fix(amazon2 check): not check cluster name during amazon2 artifact test

---

sdcm/cluster_k8s/operator_monitoring.py

https://trello.com/c/qU4Hn5Bc/2554-k8s-address-nonetype-object-has-no-attribute-containerstatuses

fix(operator_monitoring.py): operator_pod_status can be None

---

test-cases/longevity/longevity-cdc-100gb-4h.yaml

* Reduction from `240`m to `200`m because the JOB failed timeout error
https://github.com/scylladb/scylla-cluster-tests/issues/2885

fix(longevity-cdc-100-gb-4-h.yaml): Reduction stress duration

---

sdcm/cluster_k8s/__init__.py

https://trello.com/c/ZIYbDtLJ/2555-k8s-adding-pod-can-fail-due-to-the-timeout

fix(cluster_k8s): increase scylla readiness timeout

---

sdcm/cluster.py

Issue https://github.com/scylladb/scylla-cluster-tests/issues/2854
RestartThenRepairNode failed after machine restarted with new public IP.
SCT does not handle this IP change and node fail to restart.

fix(multidc test): configure remoter with new public IP after reboot

---

sdcm/cluster.py

https://trello.com/c/cqXGCeM8/2559-k8s-fix-getpeersinfo-issue

fix(get_peers_info): cover case when run_cqlsh returns malformed output

---

sdcm/nemesis.py

https://trello.com/c/qLfZOweU/2551-k8s-stopwaitstartmonkey-make-it-wait-scylla-instead-of-starting-it-up

fix(StopWaitStartMonkey): on k8s it should not start scylla, but wait till s-o bring it up

---

vars/getJobTimeouts.groovy

https://trello.com/c/VHHvfSqW/2499-incorrect-keep-alive-time-for-sct-runner

fix(vars/getJobTimeouts.groovy): Fix timeouts

---

sdcm/cluster.py
sdcm/cluster_gce.py
sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/gke.py
sdcm/nemesis.py

This nemesis is currently failing on the GKE due to the scylla-operator issue - https://github.com/scylladb/scylla-operator/issues/215

fix(disrupt_terminate_and_replace_node): make it valid for gke

---

sdcm/cluster_k8s/__init__.py

fix(minikube): initialize api rate limiter

---

unit_tests/test_remoter.py

fix(test_remoter): stop running long running tests

---

test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml

the time between the main stress to the timeout was
only 20min, this doesn't cover the time it take for
the prepare stress, I've added 1h for the timeout of
the test

test(200gb_48h): timeout too close to the stress size

---

upgrade_test.py

follow_system_log() compiles string to regex with re.IGNORECASE flag,
the simple 'idx_token' pattern would wrongly match feature log (eg:
CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX).
This patch changed to use strict pattern.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/2868

fix(upgrade_test): use strict pattern for idx_token error

---

sdcm/cluster_k8s/__init__.py
sdcm/utils/k8s.py

https://trello.com/c/2DELCtof/2561-investigate-test-failure-on-nodetool-repair-when-cluster-was-just-started

fix(rollout_restart): Make it wait till rollout is completed

---

sdcm/cluster_k8s/__init__.py
sdcm/utils/k8s.py

https://trello.com/c/TeU2BT76/2576-k8s-make-updatescyllaconfig-tolerate-when-config-is-already-there

fix(update_scylla_config): Make it flush changes before feeding yaml file to kubectl

---

sdcm/cluster_k8s/__init__.py
sdcm/remote/kubernetes_cmd_runner.py
sdcm/utils/k8s.py

https://trello.com/c/RrOCzny0/2578-k8s-make-k8scorev1api-cached-on-kubernetescluster

fix(sdcm/utils/k8s.py): make _k8s_core_v1_api cached on KubernetesCluster

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_baremetal.py
sdcm/cluster_docker.py
sdcm/cluster_gce.py
sdcm/cluster_k8s/__init__.py
unit_tests/test_cluster.py
unit_tests/test_seed_selector.py

https://trello.com/c/sTYOxsGO/2582-k8s-make-ip-address
Whenever node name is printed we are making two api calls to get private and public ip addresses.
To avoid hitting api rate limit we need to make these ip's cached.

fix(sdcm/cluster_k8s/__init__.py): Make ip_address properties cached

---

sdcm/nemesis.py
unit_tests/test_nemesis.py

A monkey that executes disruptions according to the provided categorical
distribution (https://en.wikipedia.org/wiki/Categorical_distribution):
"""Randomly picks disruptions to execute using the given categorical distribution.
Each disruption is assigned a weight. The probability that a disruption D with weight W
will be executed is W / T, where T is the sum of weights of all disruptions.
The distribution is passed into the monkey's constructor as a dictionary.
Keys in the dictionary are names of the disruption methods (from the `Nemesis` class)
e.g. `disrupt_hard_reboot_node`. The value for each key is the weight of this disruption.
You can omit the ``disrupt_'' prefix from the key, e.g. `hard_reboot_node`.
A default weight can be passed; it will be assigned to each disruption that is …

Introduce CategoricalMonkey

---

jenkins-pipelines/longevity-counters-multidc.jenkinsfile
longevity_test.py
test-cases/longevity/longevity-counters-multidc.yaml

With multidc tests ip_ssh_connections "public" should be use.
Also fix LongevityTest.test_custom_time method to use
config params pre_create_keyspace if prepare_write_cmd is not set

fix(counter_multidc_test): Fix counter multidc test to use public ip

---

test-cases/longevity/longevity-ycsb-a-100M.yaml
test-cases/longevity/longevity-ycsb-a-10M.yaml
test-cases/longevity/longevity-ycsb-a-1B.yaml

a few additions to the YCSB executions
--target must be set to have correct latency results for const throughput - see coordinated omission avoidance problem
16 vCPU per node = 14 shards per node =>
we need high concurrency per shard to at least somewhat load request queues
14 vCPUs * 20 parallelism factor = 280 connections per host
840 threads = 280 conns / host * 3 nodes = 840 total threads
ops count 300 * 10^6 * / 60 = 40 minutes for workload
ycsb workloads use zipfian distribution so we will use a single loader with 32 vCPUs
fix framework to support custom CL: -p scylla.readconsistencylevel=ONE -p scylla.writeconsistencylevel=ONE
or at least-p scylla.readconsistencylevel=QUORUM -p scylla.writeconsistencylevel=ONE
$ $ bin/ycsb run scylla -P workloads/workloada -target 120000 -threads …

100M and correct YCSB usage

---

cdc_replication_test.py
defaults/aws_config.yaml
defaults/gce_config.yaml
defaults/test_default.yaml
gemini_test.py
grow_cluster_test.py
longevity_large_partition_test.py
longevity_test.py
mgmt_cli_test.py
mgmt_upgrade_test.py
performance_regression_alternator_test.py
performance_regression_row_level_repair_test.py
performance_regression_test.py
performance_regression_user_profiles_test.py
sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_gce.py
sdcm/db_stats.py
sdcm/gemini_thread.py
sdcm/logcollector.py
sdcm/nemesis.py
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/common.py
sdcm/utils/data_validator.py
test-cases/longevity/longevity-5000-tables.yaml
test-cases/longevity/longevity-multi-keyspaces.yaml
unit_tests/test_config.py
upgrade_test.py

Because of most of defaults are stored in the default yamls
and to prevent adding defaults in code it's better to remove
this parameter.

improvement(remove default from get method): Remove 'default' parameter from params.get() method

---

sdcm/utils/auto_ssh.py

the docker autossh docker we were using had a new release (v2.0)
https://github.com/jnovack/autossh/commit/1cb6609c60eca7ed22467cb0c1361a762f69ae2b
this release changed all the envirment variable names, breaking all the places
we are using autossh for streaming rsyslog (i.e. multi dc test cases)
all manager sanity test failed like that:
```
2020-11-25 21:48:48.772: (TestFrameworkEvent Severity.ERROR), source=MgmtCliTest.SetUp()
exception=No db log from node [Node manager-regression-master-db-node-fe9672c2-1 ...
```

fix(autossh): pin down to jnovack/autossh:1.2.2

---

.pre-commit-config.yaml
sct.py
sdcm/utils/k8s.py
unit_tests/test_nemesis.py

make sure we show the diff on case on failures in pre-commit in CI
this would be more helpful the verbose of autopep8, which is very
very hard to read and figure what was changed

feature(pre-commit): show diff on failure

---

sdcm/cluster.py
sdcm/cluster_k8s/__init__.py
sdcm/utils/k8s.py

https://trello.com/c/KaqlGBoV/2552-k8s-fix-restartnodewithresharding

fix(restart_node_with_resharding): make it work on k8s all the time

---

sdcm/tester.py

If scylla_encryption_options is None ot '', ignore it, don't add to table
creation command

fix(scylla_encryption_options): fix condition in create_table

---

defaults/test_default.yaml
sdcm/cdclog_reader_thread.py
sdcm/cluster.py
sdcm/nemesis.py
sdcm/utils/cdc/__init__.py
sdcm/utils/cdc/options.py

CDC feature is moved to GA status on v4.3.
Added 2 new nemesis which allow to check the functionality
of cdc feature during longevity jobs:
- ToggleCDCMonkey: nemesis can enable/disable the cdc for user created tables and enable/disable additional cdc options
- CDCStressorMonkey: nemesis run cdc stressor tool, which read cdc log table during random time
Trello: https://trello.com/c/dkPmTBSe

feature(nemesis): New nemesis to work with cdc feature

---

cdc_replication_test.py
jenkins-pipelines/feature-cdc-replication-longevity.jenkinsfile
sdcm/logcollector.py
test-cases/cdc/cdc-replication-longevity.yaml

While running the test on Jenkins (https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/feature-cdc-replication-longevity/) for a couple of weeks I've been doing some adjustments on my branch that improved the test.
In this PR I'm trying to upstream the adjustments.

Improve the CDC replication longevity test

---

artifacts_test.py
ics_space_amplification_goal_test.py
sdcm/cluster.py
sdcm/logcollector.py
sdcm/sct_config.py
sdcm/utils/common.py
sdcm/utils/remote_logger.py
vars/artifactsPipeline.groovy

Trello: https://trello.com/c/uQpbi8EI/399-offline-installer-artifact-test
The latest offline installer uses unified pacakge, currently the nonroot
install will fail for known issue.

feature(artifact test): support offline installer

---

sdcm/k8s_configs/operator.yaml

https://trello.com/c/6sM77VSL/2629-k8s-lack-of-webhook-readiness-probe-needed-to-be-addressed

fix(operator.yaml): add readiness check

---

sdcm/cluster_aws.py
sdcm/nemesis.py

fix(restart): supply a random node as provider when restarting a seed

---

sdcm/cluster.py

https://trello.com/c/ZAVuSCq7/2628-nodes-peer-exists-in-the-systempeers-but-missed-in-gossip-after-restartthenrepairnode

fix(get_peers_info): fix it to match only peers records

---

sdcm/logcollector.py

https://trello.com/c/sRWXFL3s/2625-sct-collect-logs-does-not-pick-up-loader-logs

fix(logcollector): make loader-set pick up inactive nodes logs

---

sdcm/k8s_configs/raid-daemonset.yaml

https://trello.com/c/su8VWLSI/2626-gke-fix-raid-daemonsetyaml-to-setup-raid-same-way-as-we-do-that-in-scyllasetup

fix(raid-daemonset.yaml): make it deploy raid same way we do that in scylla_raid_setup

---

ics_space_amplification_goal_test.py
sdcm/cluster_k8s/gke.py
sdcm/utils/common.py
test-cases/scylla-operator/kubernetes-scylla-upgrade-gke.yaml
test-cases/scylla-operator/kubernetes-scylla-upgrade-minikube.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-minikube.yaml

https://trello.com/c/9FM9iwmr/2581-gke-make-it-truncate-name-automatically
GKE does not allow to deploy cluster with name more than 40 chars long. 
Currently we solve it by squashing prefix in test-case yaml file
Let's Implement automated cluster name truncation for GKE so that any test could be ran on GKE backend.

fix(sdcm/cluster_k8s/gke.py): Make it automatically truncate cluster name

---

longevity_test.py
performance_regression_test.py
sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/mgmt.py
test_lib/compaction.py

Get rid of those ugly warnings we have on the output:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```

fix(yaml.loads): replace with yaml.safe_load

---

jenkins-pipelines/perf-regression-cdc-mixed-latency-60min.jenkinsfile
performance_regression_cdc_test.py
test-cases/performance/perf-regression-latency-cdc-mixed-poll-batching.yaml
test-cases/performance/perf-regression-write-latency-cdc.yaml

Performance test for latency for cdc feature generate too large cpu payload.
Decrease number of threads to reach constant cpu load during load

test(performance): Change number of threads for perf cdc latency test

---

sdcm/logcollector.py
sdcm/nemesis.py

https://trello.com/c/9xfqhtZH/2589-rollingrestartcluster

K8s add rolling restart

---

sdcm/nemesis.py

fix for logs description of disrupt_add_drop_column
disrupt_add_drop_column not having correct description
Signed-off-by: Shoshan Dagany <shoshan.dagany@scylladb.com>

fix(disrupt_add_drop_column) add missing _set_current_disruption

---

sdcm/cluster.py

Issue: https://github.com/scylladb/scylla-bench/issues/40
During tear down scylla-bench processes were stopped using SIGTERM and it causes
to the process finish with status -1.
Instead, a SIGINT signal should be sent to scylla-bench - it handles that signal
and tries to stop gracefully.

improvement(scylla-bench): stop scylla-bench gracefully

---

test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-minikube.yaml

https://trello.com/c/tVrWEnph/2636-limit-c-s-pps-to-make-s-o-pipeline-green

fix(longevity-scylla-operator-3h-gke.yaml): set throttle to c-s, so that cluster won't be overloaded

---

defaults/docker_config.yaml
defaults/k8s_gce_minikube_config.yaml
defaults/k8s_gke_config.yaml
sdcm/cluster_k8s/minikube.py
sdcm/k8s_configs/cluster-gke.yaml
sdcm/k8s_configs/cluster-minikube.yaml
sdcm/k8s_configs/gke-loaders.yaml
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/version_utils.py

https://trello.com/c/wBYJibpu/2641-k8s-make-it-possible-to-run-on-enterprise

fix(cluster_k8s): make it work with enterprise scylla

---

unit_tests/test_cluster.py
unit_tests/test_seed_selector.py

This unittest uses a scylla.yaml inside ./test_data directory, it's fine
to access it by the given path.
If is_nonroot_install() returns False, the config path won't be changed.

fix(unit_tests/test_seed_selector.py): add a is_nonroot_install() to DummyNode

---

jenkins-pipelines/longevity-alternator-3h-multidc.jenkinsfile
test-cases/longevity/longevity-alternator-3h-multidc.yaml

* Increases the running time of the JOB, because it lasts more than 3 hours
and failed because of timeout.

fix(longevity-alternator-3h-multidc.yaml): Increase the running time to 8H

---

sdcm/utils/k8s.py

https://trello.com/c/48ubKQPz/2648-k8s-add-timeout-for-api-calls

fix(k8s.py): retry on api calls

---

sdcm/cluster_gce.py

Previous fix (#2840 ) was wrong.
If spot creation fails with message 'Instance failed to start due to preemption',
check if preempted instance still exists and destroy it if needed.
Then create on_demand

fix(gce failing spot): Instance failed to start due to preemption

---

sdcm/cluster.py

https://trello.com/c/swyZGuww/2651-k8s-reduce-severity-for-nestedexception

fix(cluster.py): reduce severity for empty nested_exception

---

sdcm/remote/kubernetes_cmd_runner.py

https://trello.com/c/2WA4yd3k/2654-k8s-add-threadexception-to-retryable-exception-list-of-the-remoter

fix(kubernetes_cmd_runner): add threadexception to the list of retryable exceptions

---

test-cases/longevity/longevity-lwt-24h-multidc.yaml

during prepare, there were 1000 threads,
exhausting the nodes memory and running
the load avg very high.
reducing it to try to make the test to
pass.

fix(lwt-24h-multidc-test): reduce stress

---

sdcm/cluster_k8s/__init__.py

https://trello.com/c/6aC89cwT/2652-k8s-add-timeouts-to-reboot-method

fix(cluster_k8s): add timeout on reboots

---

sdcm/utils/docker_utils.py

Add verification that webdriver container is not started before start it
for prevention of 'Re-run container' log message in case the container
is running. Now we print it always even when the container is running
and start shouldn't be run ('start' command nothing performs in case the
container is running)

fix(webdriver container): prevent unnecessary printouts in the log

---

sdcm/nemesis.py

https://trello.com/c/boz1ia28/2655-ssl-server-certificate-hot-reload-messages-missed-by-sct-nemesis-mechanism-2962

fix(SslHotReloadingNemesis): make it less pron to fail

---

sdcm/remote/kubernetes_cmd_runner.py
sdcm/remote/remote_base.py

Kubernetes retries only 3 times and fails, which is pretty low, given that GKE has API rate limit issue.

fix(kubernetes_cmd_runner): increase default retry

---

sdcm/nemesis.py

Issue [#2874](https://github.com/scylladb/scylla-cluster-tests/issues/2874)
Snapshot nemesis for few tables failed because of table parameter was empty:
`nodetool snapshot system -cf `
It happened because tables were searched in the wrong list with keyspaces
Bug in PR #2620

fix(snapshot nemesis): nemesis looks into wrong list

---

defaults/severities.yaml
sdcm/sct_events/system.py
sdcm/tester.py

https://trello.com/c/jFgHDvv8/2396-some-times-timeout-message-does-not-appear-in-the-logs-and-it-takes-time-to-investigate-reason-of-the-test-got-stopped

fix(tester): publish critical exception instead of killing test

---

sdcm/nemesis.py
sdcm/sct_events.py
sdcm/tester.py

https://trello.com/c/jFgHDvv8/2396-some-times-timeout-message-does-not-appear-in-the-logs-and-it-takes-time-to-investigate-reason-of-the-test-got-stopped

fix(_init_test_timeout_thread): make it raise critical event, not killing the test

---

sdcm/sct_config.py
unit_tests/test_config.py

since we are not passing down AMI or a version for SCT in this case
we can't pass this verification anyhow, so let skip it

fix(aws-siren): remove multi-region verification

---

sdcm/cluster.py

In some cases when trying to start scylla service, a timeout of 300s
isn't long enough for scylla to complete startup. It happens due to
the reshaping that happens every time node boots and detect work that
need to be done on the sstables.

fix(cluster.py): Increase timeouts of scylla start

---

jenkins-pipelines/perf-regression-latency-250gb-with-nemesis.jenkinsfile
performance_regression_test.py
sdcm/cluster.py
sdcm/db_stats.py
sdcm/nemesis.py
sdcm/report_templates/results_latency_during_ops.html
sdcm/results_analyze/__init__.py
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/decorators.py
sdcm/utils/es_queries.py
sdcm/utils/latency.py
test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml

Added a function that will calculate all the performance
latency we want to show.
Created a decorator, and added it to the parts of the
nemesis we want to measure the latencies.
Few of those parts were added to local functions
created inside their own nemesis functions.

improvement(nemesis.py): calculate latency for perf

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/gke.py
sdcm/cluster_k8s/minikube.py

https://trello.com/c/PC8hgmFb/2677-k8s-fix-timeout-issues

fix(cluster_k8s): fix timeout routines

---

sdcm/stress_thread.py

This thing prevent to collect stats for c-s in longevity-large-collections-12h-test because of:
```
...
Cannot create metrics gauge: Invalid label metric name: cassandra_stress_-Xmx8033M
...
```
https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/longevity/job/longevity-large-collections-12h-test/3/

fix(cs_thread): set stress_operation to next word after c-s

---

sdcm/utils/gce_utils.py

--min-expiry= is in seconds, while we assume that it is in minutes

fix(GcloudTokenUpdateThread): recalc --min-expiry= as seconds

---

mgmt_cli_test.py
sdcm/cluster_aws.py
sdcm/fill_db_data.py
sdcm/results_analyze/test.py

Trello: https://trello.com/c/oBLoE6ak/2466-versionutilspy-add-support-for-xydev

fix(version): add support for x.y.dev

---

sdcm/utils/common.py
unit_tests/test_clean_cloud_resources_func.py

Trello: https://trello.com/c/CaKm3eja/1785-make-testcleancloudresourcesfuncpy-less-dangerous

fix(unit_tests): mocks for clean_cloud_resources

---

data_dir/complex_schema.yaml
test-cases/upgrades/rolling-upgrade.yaml

Current complex schema workload doesn't use second index.
Roy asked to add this in upgrade test.

feature(upgrade_test): add second index in complex schema

---

jenkins-pipelines/rolling-upgrade-ami.jenkinsfile

The new rolling upgrade starts from AMI base version, the jobs will be
triggered only with new_scylla_repo, it will be same as original jobs.

feature(upgrade): add pipelines for rolling upgrade of AMI

---

sdcm/nemesis.py

Ticket: https://trello.com/c/iPWbW9OJ/2166-drop-table-during-repair
There is a new change in scylla to ignore the error of removed table
during repair, this new nemesis covered this case.

feature(nemesis.py): extend no_corrupt_repair

---

sdcm/cluster.py

Ticket: https://trello.com/c/nYm2F8c0/2191-debug-rpms-test-with-longevity
scylla-debug packages has same name with regular scylla package, it's
failed to replace the regular packages by `rpm -URvh --replacepkgs
--replacefiles /tmp/scylla/*.rpm`, because the packages are already
exist.
This patch added a `--replacepkgs' option to rpm cmdline, the packages
will be reinstalled even they are already present.
```
[scyllaadm@longevity-10gb-3h-master-db-node-f0321570-1 ~]$ ls /tmp/scylla/
scylla-4.4.dev-0.20201210.e4b55f40f.x86_64.rpm
scylla-conf-4.4.dev-0.20201210.e4b55f40f.x86_64.rpm
scylla-debuginfo-4.4.dev-0.20201210.e4b55f40f.x86_64.rpm
scylla-kernel-conf-4.4.dev-0.20201210.e4b55f40f.x86_64.rpm
scylla-server-4.4.dev-0.20201210.e4b55f40f.x86_64.rpm …
```

fix(update_scylla_packages): reinstall the packages even they are present

---

jenkins-pipelines/upgrade-scylla-k8s-gke.jenkinsfile
jenkins-pipelines/upgrade-scylla-k8s-minikube.jenkinsfile
vars/getJobTimeouts.groovy
vars/rollingOperatorUpgradePipeline.groovy
vars/runCleanupResource.groovy
vars/runCollectLogs.groovy
vars/runSctTest.groovy
vars/runSendEmail.groovy

https://trello.com/c/SPcGhigl/2670-deprecate-withenv-in-the-upgrade-pipeline

fix(rollingOperatorUpgradePipeline): remove withEnv and make it use routines

---

sdcm/report_templates/results_issue_template.html
sdcm/send_email.py

1. Does not show config file link for Siren tests
2. Ignore value 'N/A' in the config files

fix(issue template): fix config file link

---

sdcm/cluster.py
sdcm/sct_events/base.py

fix(sct_events): publish events w/o backtrace when backtrace decoding is enabled

---

jenkins-pipelines/nonroot-offline-install/artifacts-centos8.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-debian10.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-debian9.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-oel76.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu1604.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu1804.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2004.jenkinsfile

This added pipeline files for nonroot offline install, they will be used
to create jobs.
CentOS7 doesn't support nonroot offline install.

feature(jenkins-pipelines): add pipeline for nonroot_offline_install

---

vars/perfRegressionParallelPipeline.groovy

Changing the defaults of perf regressions jobs for branch-perf-v10 onwards.
Email recipients is scylla-perf-results and not QA.
destroy cluster is default behaviour.

refactor(perfRegressionParallelPipeline.groovy): Change pipeline defaults for perf jobs

---

jenkins-pipelines/perf-regression-cdc-mixed-latency-60min.jenkinsfile

Fix sub test for cdc latency performance test.

fix(cdc_perf): Fix wrong sub test for cdc latency performance

---

sdcm/cluster.py

mikefarah/yq updated to v4 which is not backward compatible.
Example of failure: https://jenkins.scylladb.com/job/scylla-4.3/job/longevity/job/longevity-cdc-100gb-4h-test/25/

fix(monitoring): fix usage of mikefarah/yq

---

sdcm/nemesis.py

_prepare_test_table() uses cassandra-stress to create the table and fill
data, the table name isn't configurable, it's always `standard1'.
This patch changed to use multiple keyspaces for test tables.

fix(disrupt_no_corrupt_repair): put test tables in multiple keyspaces

---

test-cases/longevity/longevity-alternator-3h-multidc.yaml

fix(longevity-alternator-3h-multidc.yaml): Adding "maxexecutiontime" to YCSB stress commands

---

sdcm/cluster.py

Addresses following WARNING:
```
SCT internal warning] (ClusterHealthValidatorEvent Severity.ERROR): type=NodeStatus subtype=ERROR node=sct-cluster-us-east1-b-us-east1-0 error=Current node 10.3.254.247. The node 10.3.254.97 exists in the gossip but doesn't exist in the nodetool.status has not been published or dumped, maybe you missed .publish()
```

fix(check_node_health): mark not published events

---

sdcm/logcollector.py

Example of failure: https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-centos7-test/306/console

fix(jepsen): add a check for empty nodes list for log collector

---

sdcm/sct_events/group_common_events.py

* https://github.com/scylladb/scylla/issues/7817
- [] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~

fix(group_common_events.py): Ignoring "Could not retrieve CDC streams" error

---

upgrade_test.py

* https://github.com/scylladb/scylla/issues/7817

fix(group_common_events.py): Ignoring "Could not retrieve CDC streams error"

---

sdcm/sct_events/group_common_events.py

fix(group_common_events.py): Ignoring "seastar::nested_exception" error

---

sdcm/cluster.py
sdcm/sct_config.py
test-cases/longevity/longevity-5000-tables.yaml

due to scylladb/scylla#7609 i added more memory to the
jmx java process, and it solved the issue.
now, do we want to do this to every run, or try to
do it only for the 5000 tables (or other tests that might
be failing with the same error)?

fix(increase jmx memory): on 5k tables test jmx was crashing

---

sdcm/nemesis.py

Ignore errors like this during this nemesis:
```
(DatabaseLogEvent Severity.ERROR): type=RUNTIME_ERROR
regex=std::runtime_error line_number=54404
scylla: [shard 0] init - Startup failed: std::runtime_error (This node
was decommissioned and will not rejoin the ring unless
override_decommission=true has been set,or all existing data is
removed and the node is bootstrapped again)
```
Fixes: #3015, #3016

fix(DecommissionStreamingErr): ignore  "Startup failed" logs

---

sdcm/cluster_aws.py

After revert of Amazon Linux 2 node configuration was changed and
IPV6_AUTOCONF and IPV6_DEFROUTE parameters is not set to 'yes' that cause to failure
of multiDC test with IPv6.
Relevant issue [#5179](https://github.com/scylladb/scylla/issues/5179)

fix(ipv6 config): add IPV6_AUTOCONF and IPV6_DEFROUTE to sysconfig

---

test-cases/gemini/gemini-3h-cdc-postimage-write.yaml
test-cases/gemini/gemini-3h-cdc-preimage-write.yaml
test-cases/gemini/gemini-3h-cdc-write.yaml

During tests cdc_gemini_(preimage/postimage) gemini only use
write operations. Cdc enabled for test tables. And these could
trigger error: No space left on device
Type of instance increased from i3.large -> i3.4xlarge

fix(gemini_cdc): Fix instance type for gemini_cdc tests

---

sdcm/results_analyze/__init__.py

fix(results_analyze): filter results without a stats_avarage

---

test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml

In recent runs the timeout of 2940 wasn't enough, extending to 3100.
If it's still not enoguh one will need to dig into it and check why.

fix(longevity-200GB-48h): Extend test timeout to 3100 minutes

---

jenkins-pipelines/longevity-scylla-operator-3h-gke-replace.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-decommission-add.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-recover.jenkinsfile
sdcm/cluster.py
sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/gke.py
sdcm/cluster_k8s/minikube.py
sdcm/k8s_configs/operator.yaml
sdcm/nemesis.py
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-replace.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-decommission-add.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-recover.yaml

https://trello.com/c/00UvGVne/2691-k8s-operatornodeterminateandreplace

feature(nemesis): add OperatorNodeTerminateAndReplace

---

data_dir/scylla-dash-per-server-nemesis.master.json

Since the section and panels "Cassandra-Stress latency"  on sct dashboard
display latency result of c-s, scylla-bench, ycsb tools name should be
changed

improvement(stress_latency_panel_name): Change name of panel for c-s latency on sct dashboard

---

sdcm/nemesis.py

Commenting a nemesis class does NOT disables it as one may have think.
The ChaosMonkey collects all the nemesis that starts with "disrupt_".
It means that these nemesis weren't disabled.
Moreover we know they work.

fix(nemesis): Uncommenting nemesis classes that were wrongly commented out

---

sdcm/cluster.py

SSH session might establish before user-runtime-dir@1000.service is
ready. Nonroot offline install will fail if XDG_RUNTIME_DIR is empty.
This patch reconnect the ssh session before nonroot offline install,
then the latest env variables(includes XDG_RUNTIME_DIR) will be loaded.

fix(offline_install_scylla): reload env variables by SSH reconnect

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/utils/remote_logger.py

ticket: https://trello.com/c/B9Ld2Xdw/2741-address-track-offline-install-fails
Scylla-server log was redirected to ~/scylladb/scylla-server.log after
scylladb/scylla@0f786f0.
So current 'journalctl' cmdline can't fetch the scylla-server log, the 
log file in test result is empty.
This patch changed to fetch scylla-server log from different source for 
nonroot offline install.
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/3066

Fix NonRoot offline install

---

sdcm/cluster.py
sdcm/nemesis.py

On step removing cdc_log_suffix to get base table name
incorrectly used function strip(). if keyspace or
table starts or finished with chars from cdc_log_suffix
such chars removed and list contains wrong name of keyspace.table
Instead that, using the slicing

fix(get_all_tables_with_cdc): Fix removing cdc_log_suffix

---

test-cases/longevity/longevity-ycsb-a-100M.yaml
test-cases/longevity/longevity-ycsb-a-10M.yaml
test-cases/longevity/longevity-ycsb-a-1B.yaml
test-cases/longevity/longevity-ycsb-a-1M.yaml
test-cases/longevity/longevity-ycsb.txt

I have added new header description.
I have added guide on selecting benchmark numbers: test-cases/longevity/longevity-ycsb.txt
I have rewrote loaders to match 3 nodes cluster.
I have wrote a comment about loader sizes.
I have removed stress cmds into comments because they always manual in my case.

More improvements to the YCSB test examples and documentations

---

defaults/severities.yaml
sdcm/sct_events/database.py
unit_tests/test_sct_events_database.py

since scylladb/scylla@b8f7fb35e149ee6eb1bdbbc5cf9b4aa55772ac45, in scylla
there is a diffrent type of print being raised, we want to demote it to warning
Ref: https://github.com/scylladb/scylla/issues/5661

fix(event_filters): change BROKEN_PIPE to CLIENT_DISCONNECT

---

sdcm/utils/monitorstack.py

Print log error message if after extracting the archive with
monitoringstack data stays empty.
Trello: https://trello.com/c/WW44d4Up

fix(monitoringstack): Add Error messages if data dir is empty

---

vars/byoLongevityPipeline.groovy
vars/runSctTest.groovy

Add to BYO longevity job 2 new parameters ORACLE VERSION and GEMINI SEED
which allow to run BYO job for gemini test with specific seed number
for reproduce purposes

feature(byo-job): Run gemini test with specific seed number

---

jenkins-pipelines/rolling-upgrade-centos7-ldap-authorization.jenkinsfile

rolling upgrade when there is LDAP authorization enabled
in the base_version.
This is to be used for enterprise, as this feature
is not available for OSS.

test(rolling_upgrade with ldap): added a new test

---

jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile

Currently we only enabled internode_compression for rolling upgrade test
of CentOS8, Ubuntu18 and Ubuntu20.
This patch enabled internode_compression for rolling upgrade test of
CentOS7 and AMI as required by Roy.

feature(rolling-upgrade): enable internode_compression for more tests

---

sdcm/loader.py
sdcm/tester.py
upgrade_test.py

seem like in some cases the `time.sleep(60)` wasn't enoguh
for the stress command to start, and then upgrade would start
during the init of the stress casuing it to fail on
schema agreement
Ref: https://github.com/scylladb/scylla/issues/6867

fix(upgrade_tests): wait until stress is starting

---

test-cases/scylla-operator/longevity-scylla-operator-3h-gke-add-remove-rack.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-cluster-rolling.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-grow-shrink.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-replace.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-stop-start.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-decommission-add.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-recover.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-replace.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
test-cases/scylla-operator/longevity-scylla-operator-basic-3h-gke.yaml

After recent changes test initialization started taking approximately 1 hour, which makes tests been stopped by timeout.

fix(scylla-operator-tests): increase test_duration to avoid test failures

---

sdcm/nemesis.py

In setup of three nodes cluster it does not allow to pick any node if node is already occupied

fix(nemesis): unset node nemesis before getting list of nodes

---

jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
test-cases/upgrades/rolling-upgrade.yaml
vars/rollingUpgradePipeline.groovy

The trigger rolling-upgrade-ami-test failed for lacking of jenkins pipeline.
- https://jenkins.scylladb.com/job/enterprise-2020.1/job/rolling-upgrade/job/rolling-upgrade-ami-test/3/console
Currently we pend https://github.com/scylladb/scylla-cluster-tests/pull/3086, because it enabled internode_compression for some rolling upgrade tests, we want to backport it to 2020.1 after 2020.1.6 release.
This PR only backport commits to support rolling upgrade ami to 2020.1, (internode compression isn't enabled).

backport rolling upgrade ami to 2020.1

---

jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile

we are not currently testing the current version
under test to be upgraded from latest released.
adding what should be `2020.1:latest`.
THIS IS TO BE MERGED TO `branch-2020.1`

fix(versions): latest released to version under test

---

sdcm/db_stats.py
sdcm/nemesis.py
sdcm/nemesis_publisher.py
utils/migrate_nemesis_data.py

since we want to track better which nemesis code has been run/failed
using elasticsearch and kiband dashboard.
we are sending each nemesis result, stright away in a flatter data structure

feature(nemesis_publisher): report each nemesis result into elastic

---

sdcm/nemesis.py

these events went missing, probably during conflict
solving before the original PR was merged.
This is about `disrupt_run_unique_sequence` steady state
sleep time for compare latency during management
operations.

fix(perf regression): add steady state info events

---

test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml

increasing the c-s time, as the test (load) is finishing before
the last nemesis is done.

fix(increase c-s time): perf-regression-latency-250gb-with-nemesis

---

sdcm/mgmt.py

fix(manager): Added 'Aborted' task status

---

sdcm/report_templates/results_latency_during_ops.html
sdcm/utils/decorators.py
sdcm/utils/latency.py

fix(perf latency with nemesis): fix mixed workload metrics
the original work considered taking read and write metrics
from both c-s and Scylla, where in c-s there is a 3rd
metric, "mixed" for mixed workloads.
changed a bit the format of the stored data, as there
is no more meaning to have the kind of workload that
was originally introduced to deal with mixed workloads,
so now the read and write metrics from Scylla will
appear one after the other in the result table, for mixed
workloads.

fix(perf latency with nemesis): fix mixed workload metrics

---

sdcm/sct_events/filters.py
sdcm/sct_events/group_common_events.py

https://trello.com/c/V9Vm043V/2762-rolling-upgrade-failed-with-reerror-nothing-to-repeat-at-position-0
Fixed test failing with following error:
```
12:09:30  Exception in thread Thread-2:
12:09:30  Traceback (most recent call last):
12:09:30    File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
12:09:30      self.run()
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/grafana.py", line 44, in run
12:09:30      for event_tuple in self.inbound_events():  # pylint: disable=no-member; pylint doesn't understand generics
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_processes.py" …
```

fix(ignore_ycsb_connection_refused): wrong regex caused evalutaion error

---

vars/perfRegressionParallelPipeline.groovy

Performance tests are sending email from the test.
While sending email step from the pipeline generates misleading "ABORTED: ..." email

fix(perfRegressionParallelPipeline): send no email from pipeline

---

sdcm/cluster_k8s/__init__.py
sdcm/k8s_configs/cluster-gke.yaml
sdcm/k8s_configs/cluster-minikube.yaml
sdcm/k8s_configs/operator.yaml
sdcm/k8s_configs/provisioner/values.yaml

https://trello.com/c/BBFkfUHO/2787-k8s-update-operator-scheme

fix(cluster_k8s): make scheme inline with current operator scheme

---

mgmt_cli_test.py

Manager sanity: ignoring repair errors and removing clusters at the end of each test

---

sdcm/nemesis.py

Due to the terminated node, the first repair after the termination is a 'best effort repair'.
Because of that, the first repair will cause repair error events to rise, and as such I ignored such
events in this pr.

fix(TerminateAndRemoveNodeMonkey): added event filter for repair errors

---

sdcm/nemesis.py

Error "Can't find a column family with UUID" is DatabaseLogEvent.DATABASE_ERROR,
not LogEvent. Due this the error was not filtered and fails the test.
This error appears in the https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/54/ and reported as error

fix(restart_then_repair_node): change event in filter

---

sdcm/nemesis.py

Filter 'Fail to send STREAM_MUTATION_DONE' warning when killing the rebuild
during rebuild_streaming_err nemesis

fix(rebuild_streaming_err): filter 'Fail to send STREAM_MUTATION_DONE' warning when killing the rebuild

---

test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml

seen in one of the latest jobs that the time
between c-s finished, and the last part of the
nemesis sequence ended, there was 51 minutes
difference.
hence increasing it to allow the test to run
all the nemesis sequence during c-s runtime.

fix(latency during ops): increase cs runtime

---

configurations/audit.yaml

This patch added a config file of audit, it will only be used for
scylla-enterprise.
The audit is only enabled for the default keyspaces and tables of
cassandra-stress and scylla-bench.
I will backport this commit to enterprise and use this config file
for some longevity jobs.

feature(configurations): add audit.yaml

---

sdcm/cluster.py

run with:
use_mgmt=true
ip_ssh_connections=public
Are failing with becaise ip_address use intra_node_comm_public to decide on using public or private:
```
< t:2021-01-12 07:53:27,378 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2021-01-12 07:53:27,378 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/mnt/linux-drive-1/java/scylla/scylla-cluster-tests/sdcm/tester.py", line 121, in wrapper
< t:2021-01-12 07:53:27,378 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2021-01-12 07:53:27,378 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/mnt/linux-drive-1/java/scylla/scylla-cluster-tests/sdcm/utils/decorators.py", line 110, in inner
< t:2021-01-12 …
```

fix(cluster): AWS or GCE runs with public connectivity and use_mgmt=true are failing

---

gemini_test.py
sdcm/gemini_thread.py
sdcm/tester.py

If gemini exits with exit code != 0, then executed gemini
command is not displayed in report. Fix by adding the
executing gemini command to gemini result before gemini start
Also fixed the missing screenshots and snapshots for gemini jobs

fix(gemini): Fix missing gemini command, screenshots in report

---

data_dir/c-s_lwt_big_data_multidc.yaml

1. for 2_column_update view - there is so small amount of rows for this view, so during update
chance to update them is very small, and they are not updated.
2. for immutable view - also lack of data.
This commit fixes those problems
[Task](https://trello.com/c/2WAhWm8p/2757-adjust-c-slwtbigdatamultidcyaml-to-collect-enough-data-for-validation)

fix(c-s_lwt_big_data_multidc): Adjust c-s_lwt_big_data_multidc.yaml to collect enough data for validation

---

sdcm/nemesis.py

on current running jobs (4.3.rc's) this function is always
returning empty.
Checked on a monitor stack recreated from latest test with
network nemesis, and this changes are now properly working.

fix(get_rate_limit_for_network_disruption): metric is not working

---

vars/rollingUpgradePipeline.groovy
vars/supportedUpgradeFromVersions.groovy

Currently we estimate if the new scylla is enterprise or not by
parsing the git branch suffix. It doesn't work if we test with a
private branch in BYO job.
This patch changed to estimate it by checking 'enterprise' word
in the new_scylla_repo url.

fix(supportedUpgradeFromVersions): don't estimate enterprise from branch suffix

---

defaults/test_default.yaml

moveing to branch-3.6, it has passed the tests:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/byo-longevity-test/124
the email was o.k. and the we could retrive the monitoring data
from job id `fa479eb7-a912-4177-a6c3-ac568560fbf5`

feature(monitoring): moving the new vesrion of scylla-monitoring

---

sdcm/fill_db_data.py

This query is supported in 4.4 only meanwhile and fails on 4.2.
So all rolling upgrade tests fail.
We will run this query when will test 4.5

fix(fill_db_data): don't run filter by NULL query for now

---

jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile
jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile

Since 4.3.0 was released, we should use it as the base version for master upgrades.

refactor(rolling-upgrades): Change base versions of all upgrade jobs to 4.3

---

sdcm/nemesis.py

https://trello.com/c/v5T6rj46/2788-serversslhotreloadingnemesis-investigate-why-it-can-trigger-error-gnutls-34-base64-decoding-error
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/3119

fix(SslHotReloadingNemesis): mask out 'error GnuTLS:-34, Base64 decoding error' error

---

vars/rollingUpgradePipeline.groovy

Fix for https://github.com/scylladb/scylla-cluster-tests/pull/3105
All rolling upgrde tests on master failed.
new_scylla_repo value in 'pipelineParams' is empty. Get it from 'params'

fix(rolling upgrade pipeline): use new_scylla_repo from $params

---

sdcm/loader.py

Prometheus sort labels names. Due to that, label name "keyspace"
is not displayed on popup on panel. Rename label name to _keyspace
Trello: https://trello.com/c/HJS4eTdL

improvement(stress_exporter): rename keyspace to _keyspace

---

defaults/severities.yaml
sdcm/gemini_thread.py
sdcm/sct_events/base.py
sdcm/sct_events/loaders.py

If Gemini only prints some output to stderr but otherwise finishes
(with exit code != 0), we report this fact as a WARNING event instead of
CRITICAL which resulted in stopping the test.
For example, during the reboot nemesis Gemini would report (to stderr)
that it cannot connect to the rebooted node but it would still continue
running workload by sending its requests to the other nodes.
Fixes #2748.

don't interpret Gemini's stderr as CRITICAL failure

---

defaults/severities.yaml
sdcm/sct_config.py
sdcm/sct_events/base.py
sdcm/sct_events/system.py
sdcm/utils/version_utils.py
unit_tests/test_config.py
unit_tests/test_sct_events_system.py

Trello: https://trello.com/c/71kw0Fy9/2412-check-that-latest-symlink-points-to-the-latest-deb-in-the-repo
There is a behavior change: ScyllaDB repo links (`scylla_repo`, `scylla_repo_loader`, and `new_scylla_repo`) are resolving to actual builds to be consistent during the test run (imagine if there is a new build published during the test run, especially cluster setup)
I.e., ` https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/branch-4.2/latest/scylla.repo` will be resolved to something like `https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/branch-4.2/2020-12-17T01:20:51Z/scylla.repo`

improvement(sct_config): resolve latest repo symlinks

---

jepsen_test.py
test-cases/jepsen/jepsen.yaml

Trello: https://trello.com/c/P7UMeV17/2710-jepsen-change-jepsenscyllarepo-to-upstream
**NB:** it depends on https://github.com/scylladb/jepsen/pull/8

fix(jepsen): switch to Jepsen Scylla upstream repo

---

sct.py
utils/build_system/create_test_release_jobs.py

new that we have offline installer job and directory we
should add them to the command that create the jobs for new
releases

feature(sct.py): add support for creating offline install

---

sdcm/loader.py

PR https://github.com/scylladb/scylla-cluster-tests/pull/3153/
brake the rolling upgrade by renaming label, which is used
in rolling upgrade tests to validate metrics.
Revert renaming because require functionality already
supported by Grafana

fix(create_metrix_gauge): Revert renaming of c-s latency metric label

---

test-cases/longevity/longevity-lwt-24h-multidc.yaml

Now prepare stage time takes about 12 hours. It's too long.
Change db node instance type to stronger and increase threads for the
c-s command
Prepare stage - 1.5 hour:
select/update c-s runs - CPU  is 65-85, ops almost 20K:

fix(lwt multidc): decrease prepare stage time

---

sdcm/utils/common.py
unit_tests/test_config.py

about a month ago the paths were change by scylla-pkg, and we
were testing the same version in rolling upgrades since than.
Ref: scylladb/scylla-pkg#1871

fix(s3_paths): fix the paths to look from latest repo/list files

---

jenkins-pipelines/rolling-upgrade-centos7-ldap-authorization.jenkinsfile

it was backported from master, but did not work, as
it needs few changes to adapt to branch-2020.1

fix(rolling upgrade centos 7): make fit to branch-2020.1

---

defaults/severities.yaml
sdcm/cluster_k8s/operator_monitoring.py
sdcm/sct_events/base.py
sdcm/sct_events/operator.py
unit_tests/test_sct_events_base.py
unit_tests/test_sct_events_operator.py

https://trello.com/c/WhqWzw7S/2925-k8s-reduce-severity-for-s-o-mutation-errors
Errors example:
```
20:41:03  < t:2021-01-18 13:41:02,967 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 2021-01-18 13:41:02.937: (ScyllaOperatorLogEvent Severity.ERROR) Zje4sRB9TQya1MS68UYjZQ cluster-controller/scylla/sct-cluster: An error occurred during cluster reconciliation, wait pvc deletion: failed to update pvc: Operation cannot be fulfilled on persistentvolumeclaims "data-sct-cluster-us-east1-b-us-east1-2": the object has been modified; please apply your changes to the latest version and try again
```

fix(operator_monitoring): mask out some operator events to reduce severity

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/gke.py
sdcm/utils/k8s.py

https://trello.com/c/Tx1cYWWM/2924-gke-mark-api-unstable-when-node-is-added
Idea to reduce time on starting cluster up:
```
Without fix:
13:54:21  Started by user Dmitry Kropachev
15:08:03  < t:2021-01-18 08:08:01,383 f:tester.py       l:492  c:LongevityTest        p:INFO  > change RF of system_auth to 3
Initialization done in 72 minutes
With fix:
17:29:50  Started by user Dmitry Kropachev
18:16:23  < t:2021-01-18 11:16:16,225 f:tester.py       l:492  c:LongevityTest        p:INFO  > change RF of system_auth to 3
Initialization done in 47 minutes
```
Tested on:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dmitry/job/dmitry-operator-byo-4/7/console

fix(cluster_k8s): make it wait till API is not operational first

---

defaults/severities.yaml
sdcm/db_stats.py
sdcm/sct_events/system.py
unit_tests/test_sct_events_system.py
unit_tests/test_tester.py

Trello: https://trello.com/c/Jq3MTbWh/2409-sct-should-be-tolerant-to-elasticsearch-errors
Fixed #2759

improvement(tester): don't fail on ES errors

---

sdcm/gemini_thread.py
sdcm/sct_events/__init__.py
sdcm/sct_events/base.py

To avoid warnings like 
```
...
< t:2020-12-24 04:31:26,798 f:base.py         l:152  c:sdcm.sct_events.base p:WARNING > [SCT internal warning] (GeminiLogEvent Severity.CRITICAL): type=geminievent line_number=0 node=None
< t:2020-12-24 04:31:26,798 f:base.py         l:152  c:sdcm.sct_events.base p:WARNING > None is not ready to be published
< t:2020-12-24 04:31:26,798 f:base.py         l:152  c:sdcm.sct_events.base p:WARNING > [SCT internal warning] (GeminiLogEvent Severity.CRITICAL): type=geminievent line_number=0 node=None
< t:2020-12-24 04:31:26,798 f:base.py         l:152  c:sdcm.sct_events.base p:WARNING > None is not ready to be published
...
```
These warnings are expected because gemini log contains some lines not in JSON format (e.g., at the beginning)

fix(gemini): don't warn for unparsable log messages

---

sdcm/remote/remote_base.py

fixing a typo with a function name.
strange is that pre-commit should have raised it.
@fruch FYI.

fix(typo fix): duck typing typo

---

sdcm/nemesis.py

all nodes now. Previously filter was ononly the 1st
node to run repair, but the same error was seen on
several (if not all) nodes.
Hence removing the filter on specific node, and now
having this "warning" message filtered out for all
nodes.
It is kind of enhancement for #3109.

fix(TerminateAndRemoveNodeMonkey): filter error on

---

sdcm/cluster_k8s/__init__.py
sdcm/k8s_configs/cert-manager-test.yaml

https://trello.com/c/Hj70Xle2/2712-k8s-address-cert-manager-issue
https://cloudius-jenkins-test.s3.amazonaws.com/8e05f3e5-94a2-40e2-a318-3515c41ad4eb/20201214_090614/sct-runner-8e05f3e5.zip
Addressed issue when build fails due to the no operational cert-manager:
```
2020-12-14 09:05:56.914: (TestFrameworkEvent Severity.ERROR), source=LongevityTest.SetUp()
exception=Encountered a bad command exit code!
Command: 'kubectl apply -f <(envsubst</jenkins/slave/workspace/operator-master/longevity-scylla-operator-3h-gke-cluster-rolling/scylla-cluster-tests/sdcm/k8s_configs/operator.yaml)'
Exit code: 1
Stdout:
namespace/scylla-operator-system created
customresourcedefinition.apiextensions.k8s.io/scyllaclusters.scylla.scylladb.com created
mutatingwebhookconfiguration.admissionregistration.k8s.io/scyl …
```

fix(cluster_k8s): check if cert-manager is actually operational

---

sdcm/scylla_bench_thread.py

Use node IP according to test ip_ssh_connections in scylla-bench command
Support IPv6 as well: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/yulia/job/staging-10gb-3h/116/

fix(scylla bench): run scylla-bench wuth correct ssh connection type

---

sdcm/remote/remote_base.py

The typo had been fixed in master by commit 88b45ff9f,
the commit contains many changes, this patch only backport
the typo fix.

Backport debug typo fix to 2020.1

---

sdcm/cluster.py

fix(monitoring_prereqs): specifing python3.6 in installation

---

sdcm/nemesis.py

Filter repair error for all normal nodes for repair during remove_node_then_add_node
nemesis

fix(remove_node_then_add_node): filter repair error for all normal nodes

---

longevity_test.py
sdcm/cluster.py
sdcm/tester.py

During validate_partitions cqlsh command sends select from partition.
If the command fails the test shouldn't be stopped

fix(validate partitions): not stop the test when cql command fails

---

jenkins-pipelines/longevity-scylla-operator-3h-gke-add-remove-rack.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-backup.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-cluster-rolling.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-grow-shrink.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-repair.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-replace.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-stop-start.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-decommission-add.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-recover.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-replace.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-gke.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-3h-minikube.jenkinsfile
jenkins-pipelines/longevity-scylla-operator-basic-3h-gke.jenkinsfile
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-add-remove-rack.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-backup.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-cluster-rolling.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-grow-shrink.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-repair.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-replace.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-stop-start.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-decommission-add.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-recover.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-replace.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
test-cases/scylla-operator/longevity-scylla-operator-3h-minikube.yaml
test-cases/scylla-operator/longevity-scylla-operator-basic-3h-gke.yaml

This is needed since after we added manager deployment test initialization time increased and started to ran over testduration limit

fix(k8s jenkins jobs): add +20 to testduration and +40 to pipeline timeout

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/gke.py
sdcm/nemesis.py

https://trello.com/c/3Esbh4ag/2932-gke-find-way-to-recover-cluster-after-k8s-node-instance-is-deleted-terminated

fix(cluster_k8s/gke): add code that will recover GKE cluster after node is deleted/terminates

---

sdcm/cluster_k8s/__init__.py
sdcm/tester.py
sdcm/utils/common.py

https://trello.com/c/XVbJThWU/2966-k8s-fix-monitoring-installation-logic-to-match-recent-change-in-s-o

fix(cluster_k8s): fix monitoring setup process to be inline with current s-o repo

---

test-cases/longevity/longevity-ycsb.txt

Scylla-native Token Aware driver is capable of automatically pick the
right amount of connectionts per shard.

[ycsb/doc] scylla binding don't require stating connections count

---

sdcm/kcl_thread.py
sdcm/ycsb_thread.py

Now that Nadav figure out how older AWS code can be used
with a client load balancing code, we are moving to use
that for the `hydra-kcl` stress tool
Ref: https://github.com/scylladb/alternator-load-balancing/pull/6
Ref: https://github.com/fruch/hydra-kcl/pull/3

feature(hydra_kcl): Use alternator client load balancer

---

sdcm/nemesis.py

fix invalid passing tuple to assert statement

fix(nemesis_toggle_cdc_feature): fix SyntaxWarning for assert

---

sdcm/utils/data_validator.py

fix(data validator): fix wrong assert syntax

---

sdcm/remote/base.py
sdcm/ycsb_thread.py
test-cases/longevity/longevity-ycsb.txt
unit_tests/conftest.py
unit_tests/lib/events_utils.py
unit_tests/test_ycsb_thread.py

Seem like we weren't raising error event when error verification was happening
for some reason the `FailuresWatcher` was raising only the first encountered
error (match for the regex), and not others, now it would raise any match as
error event

fix(ycsb_thread): raise error on verification errors 

---

defaults/test_default.yaml

Some of Jepsen tests are not fine with default concurrency (5). Set it to 10 x {num_of_nodes}.

fix(jepsen): increase default concurrency

---

sdcm/cluster.py
sdcm/db_stats.py

Store in ES in setup_details output of sysctl -a
Trello: https://trello.com/c/FbpVauDC

improvement(db_stats): Store in ES output sysctl -a

---

sdcm/cluster.py
sdcm/tester.py

Currently we are still using very old scylla-bench for testing, so
scylla-bench failed in tls jobs. Because tls support of scylla-bench was
added recently.
When we prepare the new loader image, scylla-bench won't be updated by
`go get github.com/scylladb/scylla-bench'.
[centos@longevity-tls-1tb-7d-4-4-loader-node-223f91b5-1 ~]$ ls -lh go/bin/
total 6.3M
-rwxrwxr-x. 1 centos centos 6.3M Jan 24  2019 scylla-bench
[centos@longevity-tls-1tb-7d-4-4-loader-node-223f91b5-1 ~]$ md5sum go/bin/scylla-bench
5cbd2c3e9faff3feab171f89d87d1da8  go/bin/scylla-bench
This patch added a `-u' option to go cmdline, it will upgrade existing
scylla-bench to latest.
Related SCT issue: https://github.com/scylladb/scylla-cluster-tests/issues/2850

fix(install_scylla_bench): reinstall scylla-bench if it exists

---

.gitignore

vim text editor creates 'linux swap'-kind of temporary files.
So, add it to the '.gitignore' to avoid mistaken merge of these files.

improvement(.gitignore): ignore linux swap files (tmp of vim)

---

sdcm/nemesis.py
sdcm/sct_events/group_common_events.py

ticket: https://trello.com/c/JTlE1RYu/1687-nodetool-scrub-implement-validation-and-the-skip-corrupted-flag
Load sstables with invalid fragment by refresh, the sstables were generated by
scylla unittest (test/boost/sstable_datafile_test.cc:sstable_scrub_test).
Then try rebuild the sstables by scrub, the invalid sstable will be skipped if
`--skip-corrupted` option is used.
fix(CorruptThenScrubMonkey): fix and renable scrub nemesis
The updated nemesis tries to rebuild sstables of all test keyspaces by
scrub, the corrupted partitions will be skipped.

fix(CorruptThenScrubMonkey): fix and renable scrub nemesis

---

sdcm/tester.py

scylla: [shard 2] cql_server - exception while processing connection:
std::system_error (error GnuTLS:-10, The specified session has
been invalidated for some reason.)
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/3219

fix(fullscan): pass credentials for cql connection

---

sdcm/sct_runner.py

My 1TB-longevity failed in collecting logs because of ENOSPC on sct
runner. I know it's not a common case, but when it occurs we might lost
the test logs.

fix(sct_runner.py): use larger disk for long longevity

---

sdcm/cluster.py
sdcm/nemesis.py

Fix seed flag in log prefix and decommission bug

---

sdcm/fill_db_data.py

On master branch for centos7 upgrade tests failed during creating
truncate_table. Added timeout after each cql command execution
to allow sync schema between nodes
Failed job: https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/rolling-upgrade/job/rolling-upgrade-centos7-test/

fix(db_fill_data): Add timeout after simple table creation

---

mgmt_cli_test.py
sdcm/mgmt/cli.py

Manager 2.3 suspend and resume tests

---

sdcm/nemesis.py
sdcm/utils/docker_utils.py

this is for enterprise only, and the idea is to
see how Scylla behaves when it loses its connection
to the LDAP server.

test(nemesis.py): added nemesis that will toggle LDAP connection

---

sdcm/nemesis.py
sdcm/utils/docker_utils.py

this is for enterprise only, and the idea is to
see how Scylla behaves when it loses its connection
to the LDAP server.
this is a backport only, as #3230 had conflicts.

[branch-2020.1] test(nemesis.py): added nemesis that will toggle LDAP connection

---

sdcm/results_analyze/__init__.py
sdcm/tester.py
sdcm/utils/es_queries.py

Add parameter to query for filtering result
for last year from current performance run
Trello: https://trello.com/c/XIHDxPL8

fix(perf_query): Filter performance tests for last year

---

sdcm/cluster_k8s/__init__.py
sdcm/utils/common.py

https://trello.com/c/VxbvobTi/2996-k8s-address-addremoverack-nemesis-failure
Nemesis fails with following error:
```
2021-02-07 09:10:40.549: (DisruptionEvent Severity.ERROR): type=GrowCluster subtype=end node=Node sct-cluster-us-east1-b-us-east1-2 [10.11.241.54 | 10.11.241.54] (seed: False) duration=25 error='ResourceField' object does not support item assignment
File "/jenkins/slave/workspace/scylla-operator/operator-master/longevity-scylla-operator-3h-gke-add-remove-rack/scylla-cluster-tests/sdcm/nemesis.py", line 2831, in wrapper
result = method(*args, **kwargs)
File "/jenkins/slave/workspace/scylla-operator/operator-master/longevity-scylla-operator-3h-gke-add-remove-rack/scylla-cluster-tests/sdcm/nemesis.py", line 2905, in disrupt …
```

fix(AddRemoveRackNemesis): switch it to use plain values

---

test-cases/artifacts/amazon2.yaml
test-cases/artifacts/ami.yaml
test-cases/artifacts/centos7.yaml
test-cases/artifacts/centos8.yaml
test-cases/artifacts/debian10.yaml
test-cases/artifacts/debian9.yaml
test-cases/artifacts/gce-image.yaml
test-cases/artifacts/oel76.yaml
test-cases/artifacts/oel81.yaml
test-cases/artifacts/rhel7.yaml
test-cases/artifacts/rhel8.yaml
test-cases/artifacts/ubuntu1604.yaml
test-cases/artifacts/ubuntu1804.yaml
test-cases/artifacts/ubuntu2004.yaml

when 'spot' instances are not available.
https://trello.com/c/7yxsmuZd/2979-set-fallback-to-on-demand-when-spot-failed-for-all-artifact-tests

improvement(artifacts test cases): enable fallback as 'on demand'

---

mgmt_cli_test.py

Since test_client_encryption activates ssl in the cluster and manager, I rearanged
the test order and made it the last test in the sanity

fix(manager): Changed the order of the sanity tests

---

sdcm/kcl_thread.py

Update of the hydra_kcl trying to test if it's the root cause of
scylladb/scylla#8012
Ref: https://github.com/scylladb/scylla/issues/8012
Ref: https://github.com/fruch/hydra-kcl/pull/4

feature(hydra_kcl): Adding time based checkpoints, and retries

---

sdcm/sct_events.py

it is failing tests, but it shouldn't, so adding this
message to default_filter to not fail the test, when
it is not supposed to fail.

fix(sct_events.py): default filter warning from DB log

---

jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile
jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile
sdcm/fill_db_data.py

Change base version for rolling upgrade tests in master.
Enable filter by NULL query in rolling upgrade tests.

feature(rolling upgrade): change base version for rolling upgrade

---

vars/byoLongevityPipeline.groovy
vars/runSctTest.groovy

Current handling of 'gce_image_db' option is broken.
In case it is not set groovy code sets it as empty value.
And then test runner fails on consequent problem not having
image set. But we expect explicit failure when it is not set.

fix(gce-byo-longevity): fix gce_image_db option handling

---

sdcm/cluster.py

Fix type issue and replace `node.remote` to `node.remoter`

fix(cluster.py): Fixing remote typo error

---

sdcm/cluster.py
sdcm/cluster_k8s/__init__.py
sdcm/nemesis.py

Add support of 'rollout_restart' method for all backend classes.
With this change it is now possible to run 'ClusterRollingRestart'
nemesis on any backend.

feature(rollout_restart): implement for all backends

---

sdcm/nemesis.py
sdcm/tester.py

this is for enterprise only, and the idea is to
disable the LDAP configuration on the go, and
then re-enable it.
Nothing should stop, and although all nodes must
be restarted, it shouldn't affect workload.

test(nemesis.py): add test that will toggle LDAP configuration

---

sdcm/cluster.py
sdcm/cluster_k8s/__init__.py

random is common variable name and often it is very convinient to use it as argument name.
in such case it overrides library name that can't be used inside such functions
Also if fixes two bugs in restart_scylla implementation done here:
https://github.com/scylladb/scylla-cluster-tests/commit/11d34603aa336e88d0609dadedff84df83f12e39

fix(sdcm/cluster): rename random library to librandom

---

sdcm/report_templates/results_issue_template.html

Events and screenshouts were added to the results_base_custom template
by PR #3244 . Remove them from result_issue_template

fix(issue_template): don't print events and screenshots in the result_issue_template

---

sdcm/nemesis.py
sdcm/report_templates/results_issue_template.html

Add note for the "disable_disrupt_validate_hh_short_downtime" nemesis method
describing the reason it is disabled.

Add note for "disable_disrupt_validate_hh_short_downtime" method

---

sdcm/cluster.py

it was added, and backported to branch-perf-v10
but it is still using hydra image with python
3.8, so the tests are failing because of it.

fix(cluster.py): unsupported python3.9 feature

---

sdcm/nemesis.py

while testing enterprise-2020.1 job (that uses
limited chaos monkey) we were not able to test
these new LDAP nemesis, hence adding it to this
class, and in any case, they will not be executed
on non-enterprise jobs, as LDAP will not be able
to be configured.

test(nemesis.py): add LDAP nemesis to limited chaos monkey

---

sdcm/results_analyze.py
sdcm/tester.py

Backport pr: 2e717baa feature(es_queries): Filter perf
result by dashboard query
use queries link in es dashboards to filter performance results

feature(perf_query): Use wide queries to get results from ES

---

sdcm/cluster.py
upgrade_test.py

Fixes: https://github.com/scylladb/scylla-pkg/issues/1922
Same fix was done for install: https://github.com/scylladb/scylla-cluster-tests/pull/3247

fix(upgrade cluster): Remove apt-get install deprecated option of --force-yes

---

sdcm/sct_events.py

the code was sent, but was not functioning as
expected, because it was supposed to have .* in
the beginning of the regex pattern (as it is
using match() and not search() regex function).

fix(sdcm/sct_events.py): regex pattern missed .*

---

sdcm/nemesis.py

In the nemesis RestartThenRepairNode the DATABASE_ERROR 'Can't find a column
family with UUID' is filtered out, but not backtrace of this error. So the
test fails on this error. Added filter on DatabaseLogEvent.BACKTRACE

fix(restart_then_repair): filter out 'Can't find a column family with UUID' backtrace

---

sdcm/fill_db_data.py
upgrade_test.py

schema workload.
Added a new test to be performed during rolling upgrade
tests, that will execute paged queries before and after
upgrading the cluster.

test(upgrade_test.py): adding paged query to complex

---

data_dir/scylla-dash-per-server-nemesis.3.1.json
data_dir/scylla-dash-per-server-nemesis.3.2.json
data_dir/scylla-dash-per-server-nemesis.3.3.json
data_dir/scylla-dash-per-server-nemesis.4.0.json
data_dir/scylla-dash-per-server-nemesis.master.json

The units in this graph should be nano-seconds and not ops.
Fixes #3277

Nemesis dashboard: wrong units in materialized view FC delay graph

---

defaults/test_default.yaml
docs/configuration_options.md
jepsen_test.py
sdcm/report_templates/results_jepsen.html
sdcm/sct_config.py
vars/jepsenPipeline.groovy

Trello: https://trello.com/c/WtMjbApE/3055-exclude-mv-workload-from-jepsen-regular-runs
Run all workloads except `mv` as separate `test-all` commands.

improvement(jepsen): allow multiple test commands

---

install-hydra.sh

Step1:
user1 installs hydra
/usr/local/bin/hydra -> /home/user1//scylla-cluster-tests/docker/env/hydra.sh
Step2:
user2 installs hydra
/usr/local/bin/hydra -> /home/user1/scylla-cluster-tests/docker/env/hydra.sh
user2 will use the install from user1.
To fix create the link with -f option and unconditionally.
To make it even better, we'd better create the link under ~/.local/bin not /usr/local/bin.

install-hydra.sh: Fix install when the /usr/local/bin/hydra exists

---

test-cases/longevity/longevity-multi-keyspaces.yaml

Set loader ami to scylla-qa-loader-ami-lwt-v5 for multiks test, region eu-north-1

fix(loader ami v5): set scylla-qa-loader-ami-lwt-v5 for multiks test

---

sdcm/fill_db_data.py

* According to `Cassandra` version 4.0, the order of the "result" variable should be `[['Tom'], ['Bob']]`.
* Github issue https://github.com/scylladb/scylla/issues/8207
- [] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~

fix(fill_db_data.py): Fixing "Tom Bob" query result

---

sdcm/nemesis.py

The DecommissionStreamingErr nemesis in scylla-4.4/longevity/longevity-10gb-3h-test#20 failed for rejoin error.
This PR fixed the problem.
2021-02-25 09:19:06.000: (DatabaseLogEvent Severity.ERROR): type=RUNTIME_ERROR regex=std::runtime_error line_number=11363 node=Node longevity-10gb-3h-4-4-db-node-598fff6e-2 [13.49.57.113 | 10.0.0.164] (seed: False)
2021-02-25T09:19:06+00:00  longevity-10gb-3h-4-4-db-node-598fff6e-2 !ERR     | scylla: [shard 0] init - Startup failed: std::runtime_error (This node was decommissioned and will not rejoin the ring unless override_decommission=true has been set,or all existing data is removed and the node is bootstrapped again)

Fix DecommissionStreamingErr nemesis

---

sdcm/tester.py

created after the nemesis destroyed the original LDAP
cluster, and created a new LDAP container.
This fix is to include all the `add_ldap_entry()` to
the tester.py function that will configure LDAP.

fix(ldap_toggle_config): the entries in LDAP were not

---

sdcm/cluster.py
sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/gke.py
sdcm/cluster_k8s/minikube.py
sdcm/k8s_configs/gke-cluster-chart-values.yaml
sdcm/k8s_configs/minikube-cluster-chart-values.yaml
sdcm/tester.py

We use monitoring out of K8S cluster (but in the same VPC) and, for now, we have as endpoints IP addresses of "k8s services" dedicated for Scylla DB nodes, but it has K8S-only availability. So, switch to the node IPs which serve it too and available VPC-wide.

Make monitoring node have proper DB node endpoints installing on K8S

---

test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml

Use 'KubernetesScyllaOperatorMonkey' nemesis in the
'test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml' file
instead of inexistent 'OperatorMgmtBackup' one.

fix(test-cases): Use proper nemesis in longevity-scylla-operator-3h-gke

---

test-cases/longevity/longevity-lwt-500G-3d.yaml

Test runs with round-robin. Prepare stage start just one c-s command with 1000
threads. After 6 hours the load was interrupted. I found 'zombie' c-s
processes that do nothing.
Separate prepare command to 3 and decrease threads amount

fix(longevity-lwt-500G-3d): fix prepare stage

---

sdcm/utils/data_validator.py

If same user profile is called in parallel, the same MVs will be included few time in the list and
test data will be copied a few times. Return list of unique MVs to prevent to duplicate
of copying test data

DataValidator - take unique MV names from user profile

---

sdcm/fill_db_data.py

was fully propagated.
very clear in the logs that insert started, but the schema is
not fully sync'ed. Adding `wait_for_schema_agreement()` should
ensure we will have the schemas fully sync'ed before we start
inserting data into that new table.

fix(fill_db_data.py): paged query test did insert before table schema

---

sdcm/cluster_k8s/__init__.py
sdcm/tester.py

When all GKE node pools are created in a row then GKE cluster goes into "repair" state for about 5 minutes.
And during this time range API server is not available.
So, to avoid such problem, install apps specific to default-pool between cluster creation and additional node pools creation to win about 3 minutes which is enough to avoid "cluster repair".

Fix gke deployment

---

sdcm/cluster.py
sdcm/tester.py

the credentials for stress tools were not taken correctly
because the flag set when LDAP is finally configured did
not exist in the load_set, so it was using the "superuser"
credentials instead (that works, but wasn't the intention
of the feature).

fix(ldap credentials): everything gets right credentials

---

jenkins-pipelines/upgrade-major-scylla-k8s-eks.jenkinsfile
jenkins-pipelines/upgrade-scylla-k8s-eks.jenkinsfile
sdcm/tester.py
vars/rollingOperatorUpgradePipeline.groovy

https://trello.com/c/6QLhDfY7/3102-eks-fix-upgrade-pipelines
Fix node group provision to ignore provision type from pipeline and use "on demand" instead.

fix(rollingOperatorUpgradePipeline.groovy): fix eks code to make pipeline succeeded

---

jenkins-pipelines/longevity-twcs-3h.jenkinsfile
jenkins-pipelines/longevity-twcs-48h.jenkinsfile
longevity_twcs_test.py
sdcm/scylla_bench_thread.py
test-cases/longevity/longevity-twcs-3h.yaml
test-cases/longevity/longevity-twcs-48h.yaml

Add two new tests longevity-twcs-bench-3h.yaml, longevity-twcs-bench-48h.yaml
longevity-twcs-bench-3h.yaml revealed https://github.com/scylladb/scylla/issues/8030
IO drop after adding node to cluster with TWCS strategy.
other run ended with no errors but had IO drop too with nemesis DestroyDataThenRebuild,

Longevity twcs tests 3h, 48h.

---

sdcm/scylla_bench_thread.py

add veriable and comment for read gap

refactor(scylla_bench_thread.py) _run_stress_bench

---

sdcm/nemesis.py
sdcm/scylla_bench_thread.py

Current disruption event is missed for `CorruptThenScrubMonkey`. As result
`ChaosMonkey` is printed in the log instead of real nemesis name

fix(corrupt_then_scrub): set current disruption event

---

defaults/k8s_eks_config.yaml
defaults/k8s_gke_config.yaml
sdcm/cluster.py
sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py
sdcm/cluster_k8s/gke.py
sdcm/cluster_k8s/minikube.py
sdcm/tester.py

Changes:
fix(k8s mgmt version): bump mgmt and agent version where #2453 fixed
feature(cluster_k8s): generalize mgmt deployment fix eks to use s3 buckets
fix(k8s monitoring): fix bug with ip format intoduced by e60144e

fix(cluster_k8s): fix mgmt deployment for EKS

---

sdcm/tester.py

Remove explicit call of 'deploy_minio_s3_backend' method because
it is called implicitely as part of the recently updated
'deploy_scylla_manager' method.

fix(k8s-gke): Fix deployment of minio storage for scylla-manager

---

cdc_replication_test.py

In Scylla commit f0950e023 the format of CDC client stream tables has
changed and new clusters require an updated client to use CDC correctly.
This commit updates the link to the CDC replicator and the script that
executes it. The new replicator understands the new table and contains
additional improvements.

improvement(cdc_replication_test): update replicator

---

gemini_test.py

gemini_result dict should be correctly updated. Overwise,
Exception happened during generating the email report:
(TestFrameworkEvent Severity.ERROR), source=GeminiTest.save_email_data()
message=save_email_data (silenced) failed with: exception='cmd'
Job example:
https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/gemini-/job/gemini-1tb-10h/79/console

fix(gemini_test): Fix updating gemini_result dict

---

jenkins-pipelines/longevity-2tb-4days-1Dis-2NonDis-Nemesises.jenkinsfile
test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml

The test has been aborted because the preapre time now takes a bit
longer than previosuly due to known write throughput degradation.
Also, the user profile stress duration wasn't configured correctly
(longer than the timout).

fix(longevity-2tb-48h): Fixing timeout issue and stress duration

---

sdcm/nemesis.py

As of now we don't have complete support for running
'terminate k8s host' and 'terminate k8s node' disruptions.
So, do not run these while full support is not added.

fix(k8s-gke): reduce number of used k8s terminate methods

---

defaults/test_default.yaml
docs/configuration_options.md
sdcm/cluster.py
sdcm/nemesis.py
sdcm/report_templates/results_base.html
sdcm/report_templates/results_issue_template.html
sdcm/report_templates/results_longevity.html
sdcm/sct_config.py
sdcm/send_email.py
sdcm/tester.py

Test Asymmetric clusters:
- bootstrapping an asymmetric cluster
- adding asymmetric nodes to cluster
SMP selection:
- minimum SMP should be calculated as 50% of max SMP
- max SMP as it is calculated now by default
- new parameter: db_nodes_shards_selection (default | random)
Add 2 new longevities to use it:
1. That will be based on the large-paritions-8h but to be shortened to 3 hours and will be run
daily (like all others).
2. another longevity that will be based on 200gb-48h but to be shorten to 12h.
Task:
https://trello.com/c/WYdqMLgp/2672-test-asymmetric-clusters-bootstrapping-an-asymmetric-cluster-adding-asymmetric-nodes-to-cluster-customer-issue
Email body changes:
Issue template changes:

feature(asymmertic cluster): add support of asymmetric cluster

---

jenkins-pipelines/gemini-1tb-10h.jenkinsfile
test-cases/gemini/gemini-1tb-10h.yaml

Switch gemini 1tb test to run with nemesises for
test complexity increasing

fix(gemini-1tb): Run test gemini 1tb with nemesis

---

sdcm/fill_db_data.py

4.4.rc0 is smaller than 4.4 (4.4.0) in parse_version(), actually the feature
had been supported from 4.4.rc0
So null_support_test_old_version will be executed with 4.4.rc4
unexpectedly, but null_support_test won't be executed with 4.4.rc4
unexpectedly.
* Currently
>>> parse_version('4.4.rc4') >= parse_version('4.4')
False
>>> parse_version('4.4.0') >= parse_version('4.4')
True
* Correct
>>> parse_version('4.4.0') >= parse_version('4.4.rc0')
True
>>> parse_version('4.4.rc4') >= parse_version('4.4.rc0')
True
This patch corrected the version to correct point (rc0).

fix(fill_db_data.py): correct the support version with rc suffix

---

defaults/k8s_eks_config.yaml
defaults/k8s_gce_minikube_config.yaml
defaults/k8s_gke_config.yaml

Branch 'operator-1.1' must not use latest versions,
it must use 1.1 specific. So, pin it to the rc version
which is going to be promoted to 1.1

ci(kubernetes): pin scylla-operator chart version

---

sdcm/cluster_gce.py

Fixes following error that was introduce in #3280 :
```
02:52:43  < t:2021-03-22 23:52:42,332 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 2021-03-22 23:52:42.327: (TestFrameworkEvent Severity.ERROR), source=ArtifactsTest.save_email_data() message=save_email_data (silenced) failed with:
02:52:43  < t:2021-03-22 23:52:42,332 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > exception=On GCE, VPC networks only support IPv4 unicast traffic. They do not support IPv6 traffic within the network.
02:52:43  < t:2021-03-22 23:52:42,332 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
02:52:43  < t:2021-03-22 23:52:42,332 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File …
```

fix(gce-ipv6-property): return empty string for IPv6 address in GCE

---

configurations/manager/debian10.yaml
configurations/manager/debian9.yaml
configurations/manager/ubuntu16.yaml
configurations/manager/ubuntu18.yaml
configurations/manager/ubuntu20.yaml
jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile
jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
sdcm/cluster.py
sdcm/mgmt/cli.py

Also: alligned scylla_repo_m to be 2021.1 accross the board,
since there's no earlier version for focal

Changed scylla BE of manager to 2020, and added (disabled) config files for buster and focal

---

jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile
jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile

The base versions vector for the jenkins upgrade jobs included only 4.4
which is not correct. This is probably because the 2021.1 SCT version
was branched out of the master branch.
We change the base versions vector to be: 2020.1, 4.3 and 2021.1

rolling upgrade: align base versions in jenkins jobs

---

configurations/db-nodes-shards-random.yaml
jenkins-pipelines/longevity-large-partition-asymmetric-cluster-3h.jenkinsfile
test-cases/longevity/longevity-large-partition-3h.yaml

This test based on large-paritions-8h. New test will run 3h on cluster where
Scylla starts with random SMP on every node

test(asymmetric cluster): Add new longevity-large-partition-asymmetric-cluster-3h test

---

sdcm/cluster_docker.py
sdcm/cluster_k8s/__init__.py

Fixes problem with `save_email_data()` on docker backend introduced by https://github.com/scylladb/scylla-cluster-tests/pull/3280
Example of failed test run: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-docker-test/256/
Successful run with the fix: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/evgeniy/job/artifacts-docker/13/

fix(save_email_data): no IPv6 address for Docker

---

sdcm/cluster_aws.py

After the RestartThenRepair nemesis, we only comment the
replace_address_first_boot option, so the next RestartThenRepair won't
add replace_address_first_boot option for the wrong grep.

fix(RestarThenRepair): strictly check the valid replace_address_first_boot option

---

jenkins-pipelines/longevity-50gb-asymmetric-cluster-12h.jenkinsfile
test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml

This test based on longevity-200gb-48h. New test will run 12h on cluster where
Scylla starts with random SMP on every node

test(12h with asymmetric cluster): Add new longevity-50gb-asymmetric-cluster-12h test

---

sdcm/cluster.py
sdcm/nemesis.py

Transfer nemesis name in 'decommission' method that called by ShrinkCluster
nemesis. This info will be printed in the email for terminated nodes list
in the column 'Terminated by nemesis'"

fix(shrink cluster): transfer nemesis name in 'decommission' method

---

sdcm/report_templates/results_issue_template.html
sdcm/report_templates/results_longevity.html
sdcm/tester.py

There are scale tests with a lot of nodes. It will be so big list of nodes to print it in the
email. Don't print nodes info if test cluster has more then 20 nodes (live and terminated)
issue template:
email body:

fix(nodes list in email): not print nodes list in the email if more then 20 nodes

---

sdcm/nemesis.py

after `removenode` command is triggered generates a
message that is interpreted by SCT as an error, and
we try to ignore during the `disrupt_remove_node`
as one of the nodes is down. Filter was applied, but
there might be a delay between the executions, logging
and the SCT detecting these errors, so few tests were
still failing event with the filter in place. There
is still a need to add some extra grace period after
the "filter" is ended to not fail the test by late
logs.

fix(removenode_filter_issue): the repair running

---

sdcm/cluster_k8s/__init__.py

It was broken in 2 places:
- incorrect chart config options were used for setting custom operator image
- usage of "latest" image was incorrectly mapped to the operator git branches

fix(kubernetes): fix usage of custom operator image

---

jenkins-pipelines/longevity-twcs-3h.jenkinsfile

fix(jenkins-pipelines/longevity-twcs-3h.jenkinsfile) test name.
Correct name is: longevity_twcs_test.TWCSLongevityTest.test_twcs_longevity

fix(jenkins-pipelines/longevity-twcs-3h.jenkinsfile) test name

---

test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml

The KMIP server of cryptsoft isn't stable, we have our hytrust KMIP
server for testing. The unstable KMIP config won't be overwrote in
EaR-longevity-local-200gb-6h-test, and scylla will fail to start.
The encryption configure will be loaded from additional configure files.
This patch removed the unstable & unused KMIP config from
longevity-encryption-at-rest-200GB-6h.yaml.

fix(longevity-encryption-at-rest-200GB-6h.yaml): remove unstable KMIP config

---

defaults/test_default.yaml
docs/configuration_options.md
jepsen_test.py
sdcm/sct_config.py
test-cases/jepsen/jepsen.yaml

Another attempt to stabilize Jepsen tests without modification of the Clojure code. 
I've added two parameters:
1. `jepsen_test_count`: possible number of single test (re)runs
2. `jepsen_test_run_policy`: what we want to consider as passed for a single test
Possible values for latter are `most` (i.e. > 50% passed), `any` (i.e., at least one pas), and `all` (all passed.)
And I want to use 5 runs with `any` policy for our regular Jepsen job. 
Also we need to merge https://github.com/scylladb/jepsen/pull/12 for better stability.

improvement(jepsen): add test count and run policy options

---

jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile

This PR backported the following PRs to branch-2020.1:
- https://github.com/scylladb/scylla-cluster-tests/pull/2966
- https://github.com/scylladb/scylla-cluster-tests/pull/2989
- https://github.com/scylladb/scylla-cluster-tests/pull/3085

Backport: enable Internode compression for 2020.1

---

data_dir/scylla-dash-per-server-nemesis.2021.1.json
jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile
jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile
unit_tests/test_utils_common.py

Create Grafana Nemesis Dashboard for branch 2021.1 and add 'SLA per user'
graphs for Workload prioritisation feature analysis
[Task](https://trello.com/c/rs6Z3Lql/3154-create-2021-graphana-dashboard)

[branch-2021.1] test(nemesis dashboard): nemesis dashboard for branch 2021.1

---

sdcm/cluster.py

In case the update_db_packages url contains rpms that are tar.gz,
this command will untar them before trying to install them.

improvement(cluster.py): Supporting update_db_packages that are supplied as tar.gz

---

sdcm/fill_db_data.py

Currently we assume the two features are supported by all enterprise,
actually they aren't support in 2021.1 unstable, two tests will fail the
upgrade jobs.
The two commits only exist in enterprise branch (2021.2 prepare), but
not branch-2021.1
- https://github.com/scylladb/scylla/commit/2342b386f467770b93238239332ccf45c9c33021
Fix for #7443, adjusted SI result order
- https://github.com/scylladb/scylla/commit/4bb11076525df443d155e45331c82a3f34e2e649
Add support of null query

fix(fill_db_data.py): correct the support version of enterprise

---

sdcm/fill_db_data.py

This PR backported some fixes to branch-2021.1, which solves the fail in rolling upgrade test of 2021.1

Upgrade backport 2021.1

---

jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile

Scylla 2020.1 doesn't support centos8, debian10 and ubuntu20.04.

fix(upgrade): disable unsupported upgrade test

---

longevity_lwt_test.py

Filter system.paxos mutation errors in LWT test (Roy's request)

fix(lwt longevity): filter out mutation errors on system.paxos

---

sdcm/utils/health_checker.py

during latest master CDC 4h job, after nemesis
DecommissionStreamingErr one of the nodes continued
to see the new node as UJ for a while, as it was
most likely busy with background tasks, and the 5
seconds sleep might be not enough.

fix(health_checker.py): increase retry sleep time

---

sdcm/fill_db_data.py

removing it as "invalid query" because from
4.5 it is valid, hence master jobs (upgrading
from 4.5) are now able to run this query without
any issues.

fix(fill_db_data): null as condition

---

sdcm/nemesis.py

Disable disrupt_corrupt_then_scrub nemesis in 2021.1 version due the issue
https://github.com/scylladb/scylla-enterprise/issues/1688 (Roy's request)

fix(scrub nemesis): disable scrub nemesis

---

defaults/test_default.yaml

base image, hence need to update the default manager agent
to the correct repo.

fix(manager default): scylla now uses Focal Fossa as default

---

sdcm/utils/health_checker.py

Prevent failure 'TypeError: argument of type 'NoneType' is not iterable'
Found in branch-2020.1:
https://jenkins.scylladb.com/job/enterprise-2020.1/job/rolling-upgrade/job/rolling-upgrade-debian9-test/23
```
13:52:14  < t:2021-04-09 10:52:08,649 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > exception=[Node rolling-upgrade-2020-1-debian-stret-db-node-c438bee6-0-3 [34.73.110.226 | 10.142.0.141] (seed: False)] NodeSetupFailed: argument of type 'NoneType' is not iterable
13:52:14  < t:2021-04-09 10:52:08,649 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > Traceback (most recent call last):
13:52:14  < t:2021-04-09 10:52:08,649 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  >   File "/jenkins/slave/workspace/enterprise-2020.1/rolling-upgrade/rolling-upgrade-debian …
```

[branch-2020.1] fix(check_nodes_status): check if remove nodes list is None

---

defaults/aws_config.yaml
vars/rollingUpgradePipeline.groovy

Rolling upgrade ami test consistently fails in the branch-2020.1 with
error at rollingUpgradePipeline.call(rollingUpgradePipeline.groovy:90):
`java.lang.NullPointerException: Cannot invoke method get() on null object`
Fix getting this parameter.
This issue fixed in master/branch-2021.1

fix(rolling upgrade ami): fix getting 'provision_type' parameter

---

configurations/ldap-authenticator.yaml
configurations/ldap-authorization-and-authentication.yaml
jenkins-pipelines/longevity-100gb-4h-ldap-auth.jenkinsfile
jenkins-pipelines/longevity-10gb-3h-ldap-auth.jenkinsfile
sdcm/cluster.py
sdcm/nemesis.py
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/common.py
sdcm/utils/ldap.py

Ticket: https://trello.com/c/qr1W8k1A/2292-ldap-sasl-authentication
This PR added support of running SaslauthdAuthenticator test, and extended an existing nemesis to switch Authenticator.

Ldap SaslauthdAuthenticator test

---

sdcm/sct_events/group_common_events.py
unit_tests/test_cluster.py
upgrade_test.py

There are two kinds of event need to be ignored, it's only needed in
upgrade test from 2020.1(cdc experimental) to 2021.1 (cdc GA)
Ignored by Oren:
!ERR     | scylla: [shard 0] cdc - Could not retrieve CDC streams with
timestamp {2021/04/06 04:41:50} upon gossip event. Reason: "std::runtime_error
(Could not find CDC generation with timestamp 2021/04/06 04:41:50 in
distributed system tables (current time: 2021/04/06 05:27:30), even though
some node gossiped about it.)". Action: not retrying.
Replied by Dmitry:
!ERR     | scylla:  [shard 0] cdc - Could not retrieve CDC streams with
timestamp {2021/01/01 04:31:29} upon gossip event. Reason:
"exceptions::invalid_request_exception (unconfigured table
cdc_generation_descriptions)". Action: not retrying.
Signed-off-by: Amos Kong …

fix(upgrade): ignore both runtime_err and exception of cdc

---

sdcm/cluster.py

The code was part of _scylla_install method that was
called only when Scylla is installed but we need to disable
the daily triggered services in any case (when we use
Scylla image like AMI or GCE Image Scylla is preinstalled)
```
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\napt-get install -y scylla-manager-agent\nsed -i \'s/# auth_token:.*$/auth_token: 4ea94ed9-708e-4317-8789-01306a70a611/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nscyllamgr_ssl_cert_gen\nsed -i \'s/#tls_cert_file/tls_cert_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#tls_key_file/tls_key_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#prometheus: .*/prometheus: :5090/\' …
```

fix(node-setup): disable daily triggered services for Ubuntu

---

jenkins-pipelines/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.jenkinsfile

the yaml for this test was updated, but the pipeline file
wasn't.
Also, increasing the pipeline timeout with an extra 60 minutes
to allow the extra stages of the pipeline to work without
reaching the timeout incorrectly (stress should finish graceful
before reaching the pipeline timeout).

fix(parallel nemesis test): rename the pipeline

---

sdcm/tester.py

Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/3400
NameError: name 'boto3' is not defined

branch-2021.1: fix boto3 import error

---

sdcm/cluster_k8s/__init__.py
sdcm/nemesis.py

By doing 2 things:
- avoid remoter calls when decommissioned node already absent
- fix setting of current nemesis for k8s decommission node operation.

fix(kubernetes): fix terminate_decommission_add_node_kubernetes nemesis

---

test-cases/artifacts/centos7.yaml
test-cases/artifacts/centos8.yaml
test-cases/artifacts/debian10.yaml
test-cases/artifacts/debian9.yaml
test-cases/artifacts/oel76.yaml
test-cases/artifacts/oel81.yaml
test-cases/artifacts/ubuntu1604.yaml
test-cases/artifacts/ubuntu1804.yaml
test-cases/artifacts/ubuntu2004.yaml

scylla_mgmt_repo is for installing scylla manager server.
scylla_mgmt_agent_repo is for installing scylla manager agent.
Currently the default scylla_mgmt_agent_repo is for Ubuntu 20.04,
this patch added special repo for different distros.

fix(artifact-test): assign scylla_mgmt_agent_repo for different distros

---

sdcm/cluster.py
sdcm/utils/common.py

Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/3395
- only prepare saslauthd when it's enabled in config
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/3396
- add support to setup saslauthd of ubuntu distro
The PR fixes two issues in artifact-test, after merged https://github.com/scylladb/scylla-cluster-tests/pull/3120

Saslauthd fix: optionally prepare saslauthd and add support of Ubuntu

---

sdcm/cluster.py

This PR fixed a bug introduced by https://github.com/scylladb/scylla-cluster-tests/commit/afef6f9debfd4015513d4510ea10517ac022ab79 (Related PR (https://github.com/scylladb/scylla-cluster-tests/pull/3393))
- distro.uses_systemd is a bool type
- additional fix: try to disable/stop apt-daily services

Apt daily services fix

---

sdcm/logcollector.py

Added output of dmesg command to collection logs for
scylla node

fix(logcollector): Added dmesg output to collecting logs

---

test-cases/artifacts/debian10.yaml
test-cases/artifacts/debian9.yaml
test-cases/artifacts/ubuntu1604.yaml
test-cases/artifacts/ubuntu1804.yaml
test-cases/artifacts/ubuntu2004.yaml

This patch removed the redundant comma in the end, and correct the
directory name in the repo path, the latest paths were verified
manually.

fix(disable_daily_triggered_services): fix typo in repo path

---

sdcm/sct_events/base.py

Scylla-bench use different time format. Example:
2021/04/06 13:03:28 Operation timed out for scylla_bench.test - received only ..
For this error the event time in the log is '2021-04-06 00:00:00' because the date
only is taken.
This fix cover different time formats:
- 2021/04/06 13:03:28
- 2021-04-06 13:03:28
- 2021-04-06T13:03:28

fix(scylla-bench): log time inconsistency

---

defaults/k8s_eks_config.yaml
defaults/k8s_gke_config.yaml
docs/configuration_options.md
sdcm/cluster_k8s/gke.py
sdcm/sct_config.py
sdcm/tester.py

GKE has release channels for K8S versions.
Add additional option that allows to specify release channel that must be used.
Also, set 'rapid' as default and specify k8s 1.19 version which is needed in our testing.

feature(k8s-gke): add possibility to specify k8s release channel

---

sdcm/sct_events/nemesis.py

Currently the target node name is added in the prefix of
DisruptionEvent. It's easy to misunderstand that the error occurred in
this node. eg: the nodetool error
2021-02-01 22:01:29.916: (DisruptionEvent Severity.ERROR): type=Decommission
subtype=end node=Node longevity-large-collections-12h-mas-db-node-c6a4e04e-2
[13.49.80.212 | 10.0.2.230] (seed: False)
duration=37427 error=Encountered a bad command exit code!
Command: '/usr/bin/nodetool  cleanup large_collection_test'
Actually the nodetool error occurred in another node (db-node-1).

fix(event log): use clear target_node in DisruptionEvent log

---

sdcm/sct_events/group_common_events.py
unit_tests/test_cluster.py

The ignored CDC error only occurs in upgrading from old scylla with
experimental CDC to scylla with CDC (GA).
CDC is already GA from Scylla 4.3, this error should not occur in
upgrade test.

fix(upgrade): don't ignore CDC error in upgrade

---

sdcm/cluster.py
sdcm/nemesis.py
sdcm/utils/ldap.py

creating a new LDAP docker container and running
commands against it. Adding here a command that will
wait for the container `wait-process`, giving us time
to start adding entries to it when the LDAP server is
ready to get it.

fix(configure_ldap): there is a race condition between

---

defaults/severities.yaml
sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/operator_monitoring.py
sdcm/sct_events/operator.py
sdcm/utils/remote_logger.py
unit_tests/test_sct_events_operator.py

Add following new operator events:
- 'TLS_HANDSHAKE_ERROR' is used to test regressioin of
https://github.com/scylladb/scylla-operator/issues/308
- 'OPERATOR_STARTED_INFO' is used to test regressioin of broken operator events, it is kind of indicator of operator events workability. It must appear just once.
Also, Do following changes to make operator events work:
- Run operator log threads which mistakenly were not triggered.
- Use proper reference to the scylla manager and operator pods. It was incorrectly refered and logs were not taken.
- Process operator event patterns correctly using "add_info" method, without it events do not get published.

feature(operator): add new operator events

---

defaults/test_default.yaml
sdcm/sct_events/database.py

Since we changed the stall detector backtraces to one-liner and we
have much better tooling around grepping all these backtraces and
build them in a tree graph, it's about time to decrease the stall
detector to 100ms for all test runs.

improvement(test_default): Decreasing the stall detector to 100ms

---

sct.py
sdcm/cluster.py
sdcm/logcollector.py
sdcm/monitorstack/__init__.py
sdcm/monitorstack/ui.py
sdcm/utils/remotewebbrowser.py

Add panels locator and functionality to wait
while defined panels on grafana page will be
loaded and after that get screenshot and snapshot
Trello: https://trello.com/c/OMPRDfd4

feature(grafana): wait grafana page loading by panels

---

data_dir/large_collections.yaml

Adds testing of c-s user profile for a static column.
It also adds coverage for https://github.com/scylladb/scylla/issues/6780
#6780 - Scylla records large data cells in the system.large_rows table. If such a large cell was part of a static rows, Scylla would crash.
The important goal is testing a static column, especially with large data size. the duplication of 2 columns just comes to get more data range covering, triggering the 2 different large-cell detectors ( 'cell' and 'row').
This enhancement adds 2 static columns to "table_with_large_collection". i think once this is tested and verified to run stable, we can consider turning one of the static column from blob to a set type if supported. (thus also testing another type of collection).
Trello task: https://trello.com/c/sDViRTCQ

improvement(large_collections.yaml): Added a static column to c-s user-profile

---

test-cases/artifacts/amazon2.yaml

scylla_mgmt_repo is for installing scylla manager server.
scylla_mgmt_agent_repo is for installing scylla manager agent.
Currently the default scylla_mgmt_agent_repo is for Ubuntu 20.04,
this patch added special repo for amazon2.

fix(artifact-test): assign scylla_mgmt_agent_repo for amazon2

---

defaults/test_default.yaml

New version of monitorstack was released.
Switched sct to use the monitorstack version 3.7

fix(monitoring): Switch monitoring branch to 3.7

---

jenkins-pipelines/perf-regression-latency-250gb-with-nemesis.jenkinsfile
vars/perfRegressionParallelPipeline.groovy

this branch is used to releases and master, so
this workaround is to enable it to work for both
cases, adding a new paramenter to the pipeline
(defaults to master support), but enabling to use
the same job to releases as well.
This until @ShlomiBalalis adds his general fix
for the manager versions/distros support.

fix(mgmt agent repo): workaround to new base image

---

jenkins-pipelines/EaR-longevity-kmip-50gb-4d.jenkinsfile
jenkins-pipelines/EaR-longevity-local-50gb-4d.jenkinsfile
jenkins-pipelines/EaR-longevity-replicated-50gb-4d.jenkinsfile
jenkins-pipelines/ics-longevity-50gb-4days.jenkinsfile

The longevity-50GB-4days-authorization-and-tls-ssl.yaml had been rename
in commit 7a44d813196d64290a416c230c998b3b4462ae31. It causes the EaR
jobs failed for FileNotFoundError.
This patch corrected the pipeline file name.

fix(EaR pipeline): correct the pipeline file name

---

sdcm/cluster.py

we are getting multiple jobs failing with apt install
lock issue:
Could not get lock /var/lib/dpkg/lock-frontend.
It is held by process 10738
Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend),
is another process using it?

fix(apt install lock): since moved to Ubuntu base image

---

jenkins-pipelines/operator/eks/longevity-scylla-operator-basic-3h-eks.jenkinsfile

It is required option and must be set to run any EKS job correctly.
So add it to the only EKS job that doesn't have it.

fix(k8s-eks): add aws_region option to basic k8s-eks job

---

sdcm/logcollector.py

All the logs we have for K8S are stored on a runner machine,
but current logic of k8s log collector assumes that we depend on a list of nodes.
So, reuse logic from "SCT log collector" that has the same approach for storing logs
and fix set of files to be searched in a log dir.

fix(k8s-logs): fix k8s log collector

---

jenkins-pipelines/perf-regression-latency-250gb-with-nemesis.jenkinsfile
vars/perfRegressionParallelPipeline.groovy

it missed the part that connects the pipeline to the job
in Jenkins.
this new change will do it.
previous PR (#3425) missed the most important part, that is to connect the option in the Jenkins job.
this current change will do it (previous PR now allows to run jobs with Scylla master, but without the ability to change it).

fix(mgmt agent repo): make the URL entry connect to the job

---

sdcm/tester.py

because the change in system_auth was the very first
thing running after configuring LDAP and changing SCT
to use LDAP users, it possible was not yet sync'ed on
all nodes, making nodetool commands to fail.
I think this change will resolve this small issue.

fix(system_auth and ldap): possible race condition

---

sdcm/db_stats.py

On Ubuntu based distribution we have
- scylla-server-dbg-4.6.dev-0.20210409.305372820-1
- scylla-server-4.6.dev-0.20210409.305372820-1
previous regex identified scylla version as dbg-4.6.dev instead of 4.6.dev
To fix this created more specific regex

fix(get_scylla_versions): inaccurate regex for scylla-server

---

sdcm/cluster.py
upgrade_test.py

* [PATCH] fix(apt install): remove unused --force-confdef/--force-confold
The test instances are always clean, the force options aren't necessary.
* [PATCH] fix(apt install): remove unused --allow-unauthenticated
Latest scylla packages are all signed, we don't need `--allow-unauthenticated'.
* [PATCH] fix(apt install): remove harmful --allow-overwrite option
This option might ignore the real scylla install bug.

cleanup apt install options

---

defaults/severities.yaml
sdcm/cluster_aws.py
sdcm/sct_events/database.py
unit_tests/test_cluster.py
unit_tests/test_data/power_off.log
unit_tests/test_sct_events_database.py

In scylla/issues#8016, we touched a strange Power off of db nodes,
SpotTermination isn't watched, maybe it's just some unexpected power off
in aws.
This patch added a POWER_OFF event, it's helpful to address the problem.
We also ignored this event in general restart() of aws instance, restart()
of gce is implemented by soft reboot().

feature(sct event): add POWER_OFF event

---

sdcm/nemesis.py
test-cases/longevity/longevity-10gb-3h.yaml

1. if nemesis failed, print failure message. Now we always get successful message
2. Add Disruption event when Grow cluster part is finished

improvement(grow_shrink_cluster): few small improvements

---

sdcm/cluster.py

Right now, if we disable 'backtrace_decoding' then scylla-version doesn't get calculated and, as a result, email report doesn't have that value.
So, fix it by running 'get_scylla_version' method without regards to the 'backtrace_decoding' configuration.

fix(email-report): fix calculation of scylla-version for email reports

---

sdcm/tester.py

Right now we have 'instance type' in an email report only using "aws" and "gce" backends.
Fix it making all the backends be correctly identified during the data gathering in the email report logic.

fix(email-report): Fix getting instance type for all the backends

---

defaults/severities.yaml
sdcm/sct_events/database.py
unit_tests/test_sct_events_database.py

improvement(db-events): add scylla server stop event

---

data_dir/scylla-dash-per-server-nemesis.master.json

if metric is missing then some prometheus query return empty
result and panel has no data.
Scylla issue: https://github.com/scylladb/scylla/issues/8497

fix(prometheus): Don't return empty result if metric is missing

---

sdcm/nemesis.py

fix(disrupt_memory_stress): use is_rhel_like, is_ubuntu as properties

---

sdcm/cluster.py
sdcm/nemesis.py

No functional change, just a cleanup.
Suggested by Fabio.

fix(SaslauthdAuth): read config by remote_scylla_yaml helper

---

defaults/k8s_gke_config.yaml

Do 2 changes:
- switch to the 'static' k8s release channel, as it is preferred  due to possibility to disable autoupgrade.
- bump k8s version to the supported '1.19.9-gke.1400'. '1.19.9-gke.100' is not available anymore.

fix(k8s-gke): use existing k8s version

---

sdcm/nemesis.py

the current name was not super intuitive, hence after requested
by @asias we are renaming the function name to have more clear
report.

improvement(perf with nemesis): rename function to have better report

---

sdcm/nemesis.py

If 'UnsupportedNemesis' error is raised before current disruption was set,
the skipped nemesis is reported without its name.
Move 'UnsupportedNemesis' error after current disruption setting.
Example:
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-large-partition-asymmetric-cluster-3h/6/

fix(kubrnetes nemesis): set current disruption for kubernetes nemesis

---

sdcm/scylla_bench_thread.py
sdcm/utils/common.py
unit_tests/test_utils_common.py

Task https://trello.com/c/iY1FHM8k/3231-conversion-to-float-fails-during-scylla-bench-run
1. Fix metric convertion to float. Support different formats like:
8.592961906s
18.120703ms
5.963775µs
9h0m0.024080491s
1m0.024080491s
546431
2. Ignore line with 'EOF' substring

fix(convert s-b metrics): fix metric conversion to float

---

sdcm/logcollector.py

The KCL stress logging configuration is enhanced.
now it is usefull to collect it for Alternator Streams test analysis.

improvement(kcl-stress): collect logs at the end of the test

---

sdcm/cluster_k8s/__init__.py
sdcm/utils/k8s.py

Due to existing bug in the scylla operator: https://github.com/scylladb/scylla-operator/issues/496
we can face situation where 2 from 3 scylla-manager related pods may get scheduled anywhere taking valueable node resources.
It may cause situation where 1 or 2 loader pod(s) may not be scheduled at all just because scylla manager may take resources dedicated for it on loader nodes.

fix(kubernetes): workaround wrong scheduling of scylla-manager

---

defaults/severities.yaml
sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/operator_monitoring.py
sdcm/sct_events/operator.py
unit_tests/test_sct_events_operator.py

scylla-operator v1.2 started having 2 pod instances where one is leader and second is replica trying to acquire lock.
And that replica may be restarted from time to time.
So, such change makes 'ScyllaOperatorRestartEvent' event become useless and, even more, harmful, because it is going to be triggered all the time and mark our tests as failed without real reason for it.
So, just delete it.

improvement(events): delete ScyllaOperatorRestartEvent event

---

vars/getJobTimeouts.groovy

Cleanup may take longer than 15 minutes.
So, increase it up to 30 minutes for now.

ci(getJobTimeouts): increase timeout for cleanup

---

defaults/k8s_gke_config.yaml

It must be enabled if possible.
So, enable it because we do not do huge load on this backend.

ci(k8s-gke): enable backtrace_decoding

---

sdcm/nemesis.py

Update list of disruption methods in ScyllaOperatorBasicOperationsMonkey
nemesis by adding one missing element and removing another one unneeded.
Missing is 'disrupt_terminate_decommission_add_node_kubernetes'.
Unneded is 'disrupt_terminate_and_recover_node_kubernetes'.
The unneeded one is duplicate of other existing method called 'disrupt_terminate_and_replace_node_kubernetes'.

fix(kubernetes): Update ScyllaOperatorBasicOperationsMonkey

---

sdcm/cluster.py

ticket: https://trello.com/c/wfxdAsFz/3239-20211-longevity-5000-tables-test
In commit 2074826ef7bf78e015aaa9bd8e29fbe8625521a1, we updated go from
1.9.2 to 1.13 to avoid the scylla-bench install error.
But go in prepared AMI loader won't be updated, which caused
scylla-bench update fail.
This patch tried to clean the old go, and update the go for prepared AMI
loader.

fix(AMI loader): update both go and scylla-bench

---

upgrade_test.py

yum started to match the package name strictly from CentOS8.
This patch changed the downgrade command to use strict pattern.
Related: https://github.com/scylladb/scylla-enterprise/issues/1707

fix(upgrade_test/yum): downgrade package with strict pattern

---

sdcm/mgmt/cli.py

Since wait.wait_for does not throw exception when a timeout is reached by default,
I changed all of the wait_for function calls in sdcm.mgmt.cli to indeed throw
exception on timeout.

fix(manager): internal wait functions to throw error on timeout

---

sdcm/cluster_k8s/__init__.py
sdcm/utils/k8s.py
unit_tests/test_utils_k8s.py

Current approach for installation of K8S monitoring uses two different 'values' files for Helm chart.
And it is problem just because Helm doesn't merge those and uses just one of it.
So, fix it by using one single set of values combined ourselves before applying it.

fix(k8s-monitoring): use just one values file for Helm chart

---

defaults/k8s_eks_config.yaml

We should test latest stable Scylla versions if possible.
So, bump it to '4.4.1'

fix(k8s-eks): bump scylla version for the EKS backend

---

vars/runCleanupResource.groovy
vars/runCollectLogs.groovy
vars/runSctTest.groovy
vars/runSendEmail.groovy

When we use EKS backend we create AWS runner, but do not use it.
The reason is that file vars/runSctTest.groovy uses wrong value for checking the backend.
So, fix it using proper value and making EKS really use AWS runner.

fix(k8s-eks): fix usage of aws runner for EKS

---

sdcm/nemesis.py

fix(k8s-eks): enable terminate and replace nemesis

---

sdcm/k8s_configs/dns-resolver-pod.yaml

Nothing else except system and scylla pods must be scheduled on the scylla K8S nodes.
So, add node affinity rules for dns pod resolver the way that it will try to be scheduled on the default/auxiliary pool first and if cannot then on a loader or monitoring ones.

fix(kubernetes): add node affinity rules for dns resolver pod

---

defaults/severities.yaml
performance_regression_lwt_test.py
sdcm/cluster.py
sdcm/nemesis.py
sdcm/sct_events/nodetool.py
unit_tests/test_sct_events_nodetool.py

Add new event for `nodetool` command run.
Filter out this event for cluster health checker
Examples of events
```
2021-04-22 10:33:37.480: (NodetoolEvent Severity.NORMAL): type=repair subtype=start node=longevity-10gb-3h-add-node-db-node-fa7aa624-1
2021-04-22 10:33:40.018: (NodetoolEvent Severity.NORMAL): type=repair subtype=end node=longevity-10gb-3h-add-node-db-node-fa7aa624-1 duration=2.5371911910001472s
2021-04-22 10:43:51.717: (NodetoolEvent Severity.NORMAL): type=flush subtype=start node=longevity-10gb-3h-add-node-db-node-fa7aa624-1
2021-04-22 10:43:54.723: (NodetoolEvent Severity.NORMAL): type=flush subtype=end node=longevity-10gb-3h-add-node-db-node-fa7aa624-1 duration=3.00542277999989s
2021-04-22 10:43:57.575: (NodetoolEvent Severity.NORMAL): type=cfstats subtype=start …
```

feature(nodetool event): add event for nodetool command

---

sdcm/cluster.py

We should reserve those options for upgrade only.

fix(upgrade_mgmt): skip interactive in upgrading scylla-manager

---

jenkins-pipelines/operator/upgrade/upgrade-major-scylla-k8s-eks.jenkinsfile
jenkins-pipelines/operator/upgrade/upgrade-scylla-k8s-eks.jenkinsfile

fix(k8s-eks): use latest scylla versions in upgrade CI jobs

---

defaults/k8s_eks_config.yaml
defaults/k8s_gce_minikube_config.yaml
defaults/k8s_gke_config.yaml

Current latest is "2.3.0", so reuse it.

improvement(kubernetes): use latest versions for mgmt and mgmt-agent

---

test-cases/artifacts/ubuntu2004.yaml

In collect-logs and clean-resources of artifacts-ubuntu2004-test,
ScyllaRepoEvent warnning are always raised, it's harmless.
(ScyllaRepoEvent Severity.WARNING):
url=http://downloads.scylladb.com/deb/unstable/unified/master/latest/scylladb-master/scylla.list
error=http://downloads.scylladb.com/deb/unstable/unified/master/latest/scylladb-master/scylla.list
doesn't point to the latest repo (http://downloads.scylladb.com/deb/unstable/unified/master/2020-12-17T18:51:16Z/scylladb-master/scylla.list)
Actual latest build is 2020-12-17T18:51:16Z, not 2020-12-08T19:40:17Z
Actually we already moved to new directory:
- old: http://downloads.scylladb.com/deb/unstable/unified/master/latest/
- new: http://downloads.scylladb.com/unstable/scylla/master/deb/unified/latest/
This patch changed the default …

fix(ubuntu2004): switch to new unified source

---

vars/rollingOperatorUpgradePipeline.groovy

Current 'rollingOperatorUpgradePipeline' doesn't work with EKS just
because EKS backend expects that SCT runner exists and such step is just
absent and runner doesn't get created.
So, add such step to make it work for EKS.

fix(k8s-eks): create SCT runner in rollingOperatorUpgradePipeline

---

defaults/test_default.yaml

Since we switched to Ubuntu AMI instead of CentOS AMI, the manager
agent we need to install on the db nodes is ubuntu package.
For enterprise 2021.1 we will use latest released  manager version
which is 2.3 both for agent and server.

fix(test_defaults scylla_mgmt_agent_repo): Changing default manager

---

sdcm/cluster.py

Change signal for kill gemini process to SIGINT, to avoid
gemini garbage printed to log.
Prevously, used signal SIGQUIT, and gemini on termination
print a lot of debug and trace information to jenkins log

fix(kill_gemini_thread): Switch signal for kill gemini process

---

sdcm/utils/cdc/options.py

if cdc property was disabled with off, in table options
it stored with value false.
Current:  {'delta': 'full', 'enabled': True, 'preimage': False, 'postimage': True, 'ttl': '86400'} 
expected: {'delta': 'full', 'enabled': True, 'preimage': 'off', 'postimage': True, 'ttl': '86400'}

fix(cdc.options): Fix assertion of cdc properties

---

defaults/severities.yaml
sdcm/sct_events/loaders.py
unit_tests/test_sct_events_loaders.py

Errors like:
- Operation x10 on key(s) [343638324b34504e3231 should stop the test immediately.
- Too many hints in flight
should raise critical event
Task: https://trello.com/c/kGply3WI/2718-stress-failure-should-stop-the-test-immediately

fix(cassandra stress): Stress failure should stop the test immediately

---

sdcm/cluster_k8s/gke.py

We use K8S 1.19 and going to use only newer versions later.
Then, basic authentication is deprecated in GKE and has been removed in GKE 1.19 and later.
So, stop using basic auth specifying "--no-enable-basic-auth" option.
Also, remove uage of "--username" one which is mutually exclusive with the above mentioned one.
Link: https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#legacy-auth

fix(k8s-gke): disable basic auth for K8S

---

sdcm/db_stats.py

we see in 4.5 jobs that it is not finding the results
because in the version i looked at, it had version as:
`scylla-server-4.5~rc1-0.20210429.b8a502fab0-1` and the
"~" wasn't being recognized in this case.

fix(get_scylla_versions): add to regex corner case

---

sdcm/cluster.py
upgrade_test.py

Operator upgrade job fails with following error:
```
WARN  13:58:44,341 Unable to read cassandra-rackdc.properties
error: DC or rack not found in snitch properties,
check your configuration in: cassandra-rackdc.properties
```
Using scylla 4.4.1 docker image on K8S backends.
So, workaround it by copying 'cassandra-rackdc.properties' file to "/etc/scylla/cassandra" dir.
Also, handle "run_nodetool" method's exceptions correctly and calculate latest available sstable format automatically isntead of using hardcoded version.

fix(k8s-eks-upgrade): make scylla upgrade on EKS be workable

---

defaults/k8s_eks_config.yaml

Right now it is not defined and manager backup tests fail.
So, define this option using one of the existing S3 buckets.

fix(k8s-eks): define 'backup_bucket_location' for manager tests

---

test-cases/artifacts/centos7.yaml
test-cases/artifacts/centos8.yaml
test-cases/artifacts/debian10.yaml
test-cases/artifacts/debian9.yaml
test-cases/artifacts/gce-image.yaml
test-cases/artifacts/oel76.yaml
test-cases/artifacts/oel81.yaml
test-cases/artifacts/ubuntu1604.yaml
test-cases/artifacts/ubuntu1804.yaml
test-cases/artifacts/ubuntu2004.yaml

…sions to 2.3
In official branches we should use latest released versions of manager.
Changing the manager agent version from master to 2.3.

Update manager agent from master to 2.3 in 2021.1

---

sdcm/cluster.py

Cloud instance stopper stops GCE instances if
they are 11 hours old and untagged, and for AWS
the value is set to 12 hours. So selecting the min
between those to make sure our instances are not
stopped prematurely.

improvement(keep_alive): set to 11 hours

---

test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml

scylla_rsyslog_setup is not supported in branch-2021.1.
Disable it

fix(scylla_rsyslog_setup): disable scylla_rsyslog_setup in branch-2021.1

---

sdcm/cluster.py

It will fail to install package by apt when Ubuntu AMI is ready. This
patch changed to update repo cache at the beginning stage.

fix(node_setup): update repo cache for db nodes

---

jenkins-pipelines/artifacts-amazon2.jenkinsfile

Removed unnecessary scylla_mgmt_repo from the pipeline file
and added proper scylla_mgmt_agent_repo default value to it.
This change was necessary due to the recent change to the default of scylla_mgmt_agent_repo
to contain a debian repo, instead of a centos one

fix(amazon2 artifact): changed manager repo defaults

---

jenkins-pipelines/artifacts-debian10.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-debian10.jenkinsfile
test-cases/artifacts/debian10.yaml

Since the released repo,
http://downloads.scylladb.com.s3.amazonaws.com/deb/debian/scylladb-manager-2.3-buster.list,
is currently malformed, we deceided to change the agent repo to the latest unstable release.

fix(artifact debian10): changed scylla_mgmt_agent_repo

---

sct.py

Lack of a comma after 'focal', then 'focal' and 'jessie' are connected
unexpectedly.
Error: Invalid value for "-v" / "--dist-version": invalid choice: focal.
(choose from xenial, trusty, bionic, focaljessie, stretch, buster)

fix(option parse): fix a typo in choise list of --dist-version

---

sdcm/nemesis.py

stress-ng install failed with error:
"No apt package 'stress-ng', but there is a snap with that name.
Try snap install stress-ng"

fix(disrupt_memory_stress): stress-ng install

---

sdcm/sct_events/group_common_events.py

Eliran suggested to ignore the error when the first node gets upgraded
to enterprise until all nodes have the service_levels table propagated
to them.
Related issue: https://github.com/scylladb/scylla-enterprise/issues/1698
[only for branch-2021.1]

fix(upgrade test): ignore "Can't find column family" err

---

sdcm/cluster.py

The purpose of this 4.3.x fix is to workaround the load drop alert,
that is triggered folowing abort-repair nemesis.
this is caused by: https://github.com/scylladb/scylla/issues/7840
The 4.3.3 failed test is: scylla-4.3/longevity/longevity-cdc-100gb-4h-test#51: 2021-04-07 17:05:16
The error is:
```
2021-04-07 20:19:17.712: (PrometheusAlertManagerEvent Severity.ERROR): alert_name=CassandraStressWriteTooSlow type=start start=2021-04-07T20:19:09.591Z end=2021-04-07T20:22:09.591Z description=Cassandra Stress write latency more than 1000ms updated=2021-04-07T20:19:10.636Z state=active fingerprint=14499e4f82cd948a labels={'alertname': 'CassandraStressWriteTooSlow', 'cassandra_stress_write': '0', 'cpu_idx': '0', 'instance': '10.0.0.4', 'job': 'sct_metrics', 'loader_idx': '1', 'monitor': …
```

fix(alert manager): decrease alert CassandraStressWriteTooSlow severity to "warning"

---

sdcm/report_templates/results_base.html

Links of snapshots/screenshors are not according to its names.
It should be by this order:
```
base_grafana_dashboards = [
monitoring_ui.OverviewDashboard(),
monitoring_ui.ServerMetricsNemesisDashboard(),
]
```

fix(email): correct snapshot links according to name

---

sdcm/fill_db_data.py

fix(scylla-upgrade): make fill_db_data module use proper queries

---

sdcm/logcollector.py

"k8s-eks" backend is new one and it is missing in the monitoring logs gathering logic.
So, fix it by making backend checks be "k8s-eks"-aware.

fix(k8s-eks): gather monitoring set data correctly

---

sdcm/nemesis.py

There are 2 nemesises that expects repair failure and this error is filtered.
Don't publish Nodetool event in this case
- [x ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)

fix(nodetool event): don't pusblish nodetool event when failure expected

---

sdcm/sct_events/loaders.py
sdcm/stress_thread.py
unit_tests/test_sct_events_loaders.py

Two changes:
1. fix 'hints in flight' regex as we have different messages
2. Stop iterating patterns to avoid creating two events for one line of the log

fix(cassandra-stress event): change regex to recognise 'hint in flight' message and event publish mechanism 

---

configurations/local-ear.yaml

The file in /tmp/ might be deleted after reboot, this patch moved the
secret keyfile to a safe place.

fix(local-ear config): moving secret key from /tmp to /etc/scylla/encrypt_conf/

---

sdcm/utils/common.py

Needed at least by 'gcloud' when deleting GKE clusters.
Without it we get following error during above operation:
ERROR: (gcloud.container.clusters.delete)
Could not create directory [/~/.kube]: Permission denied.

fix(kubernetes): define KUBECONFIG running cleanup resources

---

sdcm/cluster_k8s/__init__.py

Deploying minio service we get 2 pods created:
- Permanent one that serves as S3-like object storage
- Temporary one that creates predefined buckets
It happens that waiting for all the pods be in "Ready" state
timeout is reached just because second pod becomes "Completed"
and then gets deleted.
So, update waiter to wait for permanent pod only to avoid races.

fix(k8s-gke): wait for minio app pod correctly

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/gke.py
sdcm/logcollector.py
sdcm/tester.py
sdcm/utils/k8s.py

For the moment we have too few data kept after test run and we need alive cluster to debug when something goes wrong.
So, add logs gathering to be able to find failure root causes in most cases without a need to reproduce problems.

feature(kubernetes): gather K8S logs after test ends

---

sdcm/utils/k8s.py

When custom cache dir is not set for kubectl it uses '~/.kube/http-cache' dir as default one.
And we faced issue with this approach when default '.kube' dir had unexpected permissions and couldn't be accessed.
Impossibility to write cache caused significant slow down of interaction with K8S API server.
So, use the same dir for cache as we use for storing kubeconfig.
This dir is autocreated by test runner and won't have described problem.

improvement(kubernetes): use custom cache dir for kubectl

---

jenkins-pipelines/feature-ldap-authorization-and-audit-longevity-100gb-4h.jenkinsfile

it was never tested the combination between LDAP
and audit, and this test is the first of its kind.
the test will have regular LDAP authorization config
in addition to audit config.

test(ldap with audit features): add new pipeline job

---

vars/artifactsPipeline.groovy

fix(artifactsPipeline): Added scylla_mgmt_agent_repo parameter

---

jenkins-pipelines/rolling-upgrade-ubuntu-ami.jenkinsfile
upgrade_test.py
vars/rollingUpgradePipeline.groovy

Currently 2021.1 in base_version switched to Ubuntu AMI, we should pass
different kind of new_scylla_repo to the subtests.
This patch split the tests to two jobs. I will create a new jenkins job,
and asked rel-eng to trigger it with Ubuntu AMI.

feature (ami upgrade): split ami upgrade to two jobs

---

sdcm/logcollector.py

instead of raising 'NotImplementedError' exception.

fix(logcollector): log warning using DirLog class on remote nodes

---

vars/artifactsPipeline.groovy

job https://jenkins.scylladb.com/job/scylla-master/job/
artifacts/job/artifacts-ami-test/387/consoleFull
was run with ami(centos). scylla_manager_agent_repo was set to use rpm packages,
but pipeline logic export provided parameter value only if scylla_repo was set.
Job failed because invalid deb link was written to yum repo conf file.
Move export parameter to use them independently

ci(artifactsPipeline): always export scylla_manager* params

---

sdcm/cluster.py
sdcm/db_stats.py
sdcm/nemesis_publisher.py
sdcm/report_templates/results_latency_during_ops.html
sdcm/results_analyze/__init__.py
sdcm/utils/version_utils.py
unit_tests/test_cluster.py

there were many cases where the emails with report had
Scylla version, but without build-id. During perf jobs
while we bisect many issues and regressions, we had to
download either sct.log or db logs to find the build-id,
because if there were more than one build in the same day
the only way to identify the relocatable packages is using
the build-id.

improvement(build-id on reports): adding Scylla build-id

---

test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml

Since we introduced the critical event for stress failures, the
stress commands of compressed tables fails this longevity.
I decided to remove them from this longevity and added them to
a new longevity that will handle only compressed tables.

refactor(longevity-50gb-3d): Remove stress commands of compressed tables

---

data_dir/scylla-dash-per-server-nemesis.master.json

Accedintly the function being used wasn't replaced from $func to sum.

fix(scylla-dash-per-server-nemesis.master.json): change query func

---

vars/artifactsPipeline.groovy

We already covered the scylla-manager tests in general artifact-tests,
and scylla-manager doesn't support offline installation right now.
Evgeniy disabled mgmt test for artifact test of Ubuntu 20.04 in commit
872e7962c. But use_mgmt is enabled by default by Fabio in commit d1ae0d063.
Currently we didn't pass scylla_mgmt_repo in trigger artifact-tests,
use_mgmt will be disabled after this change. When scylla_mgmt_repo is
assigned in executing the jenkins job, mgmt test will be enabled automatically.

fix(offline install): disable scylla-manager for offline artifact-tests

---

sdcm/tester.py

In order to test real duration measurements, a random value for TIMEOUT
is added to the full-scan query, ranges from 2 minutes to 5 hours.
Testing description:
SCT has a ‘full-scan’ nemesis-like operation that reads an entire table.
An optional ‘timeout’ parameter can be added to this query, that gets a randomized value between several minutes - to several hours.
During the time processing this query TIMEOUT threshold, the DB nodes are having other disruptive nemesis as well.
The idea is to challenge this new cql timeout mechanism and to generally verify there are no unexpected results. that means its queries either succeed or fail for the timeout threshold expected error message. it doesn't validate that the timeout did measure the correct time duration (that is covered in Dtest).
The …

improvement(fullscan): Add CQL TIMEOUT parameter to full-scan query

---

sdcm/nemesis.py

Nemesis TerminateAndRemoveNode fails on nodetool remove node
and could leave cluster with nodes in status DN Issue #3173.
if command `nodetool removenode` failed, remove node from
dead list allowing HealthValidator to terminate test with
critical event

fix(TerminateAndRemoveNode): remove node from dead list

---

sdcm/report_templates/results_latency_during_ops.html
sdcm/utils/latency.py

improvement(results_latency_during_ops.html): color lines
when the average value for the line will be greater
or equal to 3 times the steady state, the line will
be marked as read, to bring more attention to the
biggest latency increases.

improvement(results_latency_during_ops.html): color lines

---

jenkins-pipelines/perf-regression-throughput-125gb.jenkinsfile
performance_regression_test.py
test-cases/performance/perf-regression-throughput-125gb.yaml

added new performance test that is not 100% cached data

test(perf-test): new performance test with not 100% cached

---

configurations/ms-ad-ldap-authenticator.yaml
configurations/ms-ad-ldap-authorization-and-authentication.yaml
configurations/ms-ad-ldap.yaml
jenkins-pipelines/longevity-100gb-4h-ldap-authorization-authenticator-ms-ad.jenkinsfile
jenkins-pipelines/longevity-10gb-3h-saslauthd-authenticator-ms-ad.jenkinsfile
sdcm/cluster.py
sdcm/nemesis.py
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/common.py
sdcm/utils/ldap.py

ticket: https://trello.com/c/7zOM6mFa/3205-ldap-sasl-authentication-with-ms-ad
When saslauthdAuthenticator is used, the ldap server connected with
saslauthd service can be Microsoft Active Directory(MS AD), docker ldap
server is another option.
The MS AD server we used is in AWS us-east-1, the LDAP users
(cassandra/scylla-qa/qa-user/dummy) had been added in the server.
- CN=cassandra,OU=People,DC=scylla-qa,DC=com
- CN=scylla-qa,OU=People,DC=scylla-qa,DC=com
- CN=qa-user,OU=People,DC=scylla-qa,DC=com
- CN=dummy,OU=People,DC=scylla-qa,DC=com

feature(MS AD): test saslauthdAuth with MS AD

---

sdcm/results_analyze/__init__.py

When getting events during prepare email report for performance
tests with compared results, next error happened:
File: sdcm/tester.py", line 2461, in check_regression
results_analyzer.check_regression(self._test_id, is_gce,
File "sdcm/results_analyze/__init__.py", line 576, in check_regression
last_events, events_summary = self.get_events()
File "sdcm/results_analyze/__init__.py", line 116, in get_events
event_severity.append(event.name)
AttributeError: 'NoneType' object has no attribute 'append'

fix(results_analyze.get_events): Set correct variable type

---

test-cases/upgrades/rolling-upgrade.yaml

For now, as an easy and quick fix until we pass correctly mgmt agent
repo to each rolling upgrade test, I'm disabling the usage of manager
in rolling upgrade tests.

fix(rolling-upgrade): Disable usage of manager in rolling upgrades

---

sdcm/cluster.py
sdcm/nemesis.py

In the [#3415](https://github.com/scylladb/scylla-cluster-tests/pull/3415)
critical Poweroff event was introduced. In some Nemesis like GrowShrink we
terminate the nodes that were previously created and that is not critical.
Need to add DBevents filter when we terminate nodes.
(this event is useful when the nodes was shut down not by the test)
https://trello.com/c/EeKXDIw3/3400-power-off-event-should-be-filtered-when-we-terminate-nodes-in-our-code

fix(poweroff-event): filtering when terminate is run

---

sdcm/sct_events/filters.py

Needed to investigate - https://trello.com/c/Qr4KlZ1l/3401-repair-error-events-were-not-filtered-during-terminateandremovenodemonkey

improvement(filters.py): Add extra parameters to printout for filters

---

test-cases/gemini/gemini-1tb-10h.yaml
test-cases/gemini/gemini-3h-with-nemesis.yaml
test-cases/gemini/gemini-basic-3h.yaml

Most of jobs for master, branch-4.5 for gemini which are run with gemini
oracle cluster are failed, because used old scylla version 3.3.2 for
oracle cluster. The reason, is that ami of 3.3.2 doesn't have
user scyllaadm for ssh.
Another reason, is that scylla 3.3.2 is a quite old.
Version is changed to 4.3.3

fix(gemini-tests): Change gemini oracle cluster scylla version to 4.3.3

---

test-cases/performance/perf-regression-throughput-125gb.yaml

To run for older version disk and cache performance
test use_mgmt should be disabled

fix(performance): Disable use_mgmt for disk and cache

---

sdcm/tester.py

if db_type set as mixed, sct will configure 2 clusters: test and oracle
this mode is mostly used with gemini tests. Oracle cluster uses
older version of scylla and older ami(Centos). to avoid installing
scylla-manager-agent on oracle cluster, disalbe it during initialization
of oracle cluster.

fix(get_cluster_aws): disable use_mgmt for oracle cluster

---

defaults/k8s_eks_config.yaml

We run EKS tests in eu-north-1 region and need to use it's S3 bucket.
So, specify S3 bucket from eu-north-1 region in our EKS configuration

fix(mgmt-backup): use proper bucket on EKS backend

---

sdcm/report_templates/results_latency_during_ops.html
sdcm/results_analyze/__init__.py
sdcm/tester.py

the tables have results of latency, and to be sure
every reader is in the same page, this commit will
be adding a legend to the tables, that the latency
results are displayed in ms (miliseconds).

improvement(results_latency_during_ops.html): add legend to table result

---

sdcm/tester.py
sdcm/utils/common.py

fix(tester): make all threads daemonic by default

---

test-cases/upgrades/generic-rolling-upgrade.yaml

Due to several issues lately with manager agent installation,
I'm disabling the uage of manager in the rolling upgrades tests
for now.

fix(generic-rolling-upgrade): Disabling the usage of manager

---

sdcm/cluster.py

Iptables service is enabled in OEL8 of aws market, it only allows to
access a few tcp ports (eg: 22) from external host. This patch disabled
iptable service for rhel8 like distros.
Iptable service doesn't exist in rhel7 like distros. The problem doesn't
exist with CentOS8 of GCP, iptable should already been disabled in it.
Fixes #3502

fix(node_setup): disable iptables service

---

sdcm/cluster.py

Fabio already fix the apt lock problem around install scylla manager.
But The problem may also occur in installing other packages, especial in the
early phase of node setup. We can run wait_apt_not_running() before
installtion to avoid the apt lock, but it's not convenient to change all
related codes.
This patch tried to disable unattended-upgrade by removing the package
and config.
Ref: https://linoxide.com/enable-disable-unattended-upgrades-ubuntu-16-04/

improvement(disable_daily_triggered_services): remove unattended-upgrades and its config

---

upgrade_test.py

'get_scylla_version()' method of a "scylla node" started returning
detailed scylla version [1] and upgrade test started failing on K8S
backends.
Fix it by making proper version check there.
[1] https://github.com/scylladb/scylla-cluster-tests/commit/7bdb0e60

fix(upgrade-on-K8S): perform proper check for scylla version

---

jenkins-pipelines/nonroot-offline-install/artifacts-centos8.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-debian10.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-debian9.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-oel76.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu1604.jenkinsfile
jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu1804.jenkinsfile
vars/artifactsPipeline.groovy

We shared test config (test-cases/artifacts/*.yaml) for general
artifact-tests and root-offline artifact-tests. So `scylla_mgmt_repo`
can't be set to empty in the shared configs.
This patch changed the upgrade groovy to always disable use_mgmt for all
(root & nonroot) offiline artifact-tests.

fix(offline install): disable scylla-manager for all offline artifac-tests

---

sdcm/cluster.py
sdcm/cluster_k8s/minikube.py
sdcm/remote/kubernetes_cmd_runner.py
sdcm/tester.py

https://trello.com/c/zLsCi1KE/3407-create-an-infra-using-pytest-to-run-a-basic-set-of-operator-funcitonal-tests
Part of changes that targets scylla operator functional tests
This particular peace is addressing following problems:
1. Wrong number of nodes for k8s monitoring, needed to be hardcoded to 1
2. send_files and receive_files are not working on kubernetes remoter
3. Teardown and Setup on ClusterTester are not completing if no unittest envolved
4. wait_for_nodes_up_and_normal by default should wait all nodes in the cluster

Number of small fixes to get operator functional tests running

---

sdcm/tester.py
sdcm/utils/decorators.py

https://trello.com/c/zLsCi1KE/3407-create-an-infra-using-pytest-to-run-a-basic-set-of-operator-funcitonal-tests
Part of changes that targets scylla operator functional tests
This particular peace is addressing ability to run tests in the environment where there is no loaders and monitoring stack provisioned

fix(tester.py): fix it for cases when no loader and monitor cluster deployed

---

sdcm/cluster.py
sdcm/cluster_k8s/__init__.py
sdcm/utils/common.py
sdcm/utils/properties.py

https://trello.com/c/zLsCi1KE/3407-create-an-infra-using-pytest-to-run-a-basic-set-of-operator-funcitonal-tests
Part of changes that targets scylla operator functional tests
This particular peace is bringing cassandra rack property that is needed in particular test

feature(sdcm/cluster): implement remote_cassandra_rackdc_properties

---

mgmt_cli_test.py

In each test function of the manager, we have log messages to indicate the start
and the end of the test function. Added missing end log message to test_enospc_during_backup

fix(manager): Added ending message to test_enospc_during_backup

---

defaults/test_default.yaml

The parameter was falsly removed from test default, reinstating it

fix(manager): reinstated mgmt_segments_per_repair

---

sdcm/fill_db_data.py
test-cases/upgrades/rolling-upgrade.yaml
upgrade_test.py

Enable cdc for each table in FillDatabaseData and verify changes in appropriate cdc log tables.
Run gemini with cdc and cdc stressor during ugrade

test(upgrade_test): Adding cdc feature to rolling upgrade test

---

sct.py
sdcm/utils/cloud_monitor/__init__.py
sdcm/utils/cloud_monitor/cloud_monitor.py
sdcm/utils/cloud_monitor/report.py
sdcm/utils/cloud_monitor/templates/per_qa_user.html

New command added to sct. It allow to generate report with cloud resources
usage only for qa + timer and build report with instances
older than 3 days, 5 days, 7 days.
to run command for all qa team:
hydra cloud-usage-qa-report -e qa@scylladb.com
to run command for specific user
hydra cloaud-usage-report -e <email> -u <user>

feature(cloud-monitor): Report with resources older 3,5,7 days for qa

---

sdcm/utils/distro.py
unit_tests/test_utils_distro.py

~~- [x] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
Added is_debian_like() property to distro.py and extended unit tests for the is_debian_like() property.
Trello link: https://trello.com/c/EfZ9N6IG/3342-add-debianlike-property-to-distropy

improvement(distro.py): add debian-like property

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py

We have 2 monitorings, one is outside of an EKS cluster and second is inside.
So, make prometheus in K8S be available to test runner node by doing following:
- Apply EKS main security group to EKS monitoring nodes
- Set up nodePort service for prometheus pod
- Reuse node IP for connection as it will use nodePort for traffic   redirection.

fix(k8s-eks): make K8S prometheus be reachable by test runner

---

sdcm/fill_db_data.py

'get_scylla_version()' method of a "scylla node" started returning detailed scylla version [1].
And 'parse_version' function always calculates 'detailed' scylla version as lower than any short scylla version.
So, when we use '4.4.rc0' scylla version or newer one as a base in upgrade jobs we fail because improper queries are picked up.
So, fix it by making version comparison use short scylla versions always.
[1] https://github.com/scylladb/scylla-cluster-tests/commit/7bdb0e60

fix(sdcm/fill_db_data.py): use short scylla versions in comparisons

---

defaults/k8s_eks_config.yaml
sdcm/cluster_k8s/eks.py

To be able to use real S3 service in our tests we need either to use creds or add full public access to a bucket.
Later one is not acceptable.
First one requires update of secret for scylla manager agent with creds. If we use constant creds we have security vulnerability
because we will need to specify creds in K8S secrets which may be mistakenly shared as part of K8S logs for debugging.
Last option is to use temporary creds. But, it's generation requires special permissions on test runner account which are absent as of now.
So, since none of possible ways is suitable reuse 'MinIO' service the same way we do it for GKE and 'minikube' backends.

fix(mgmt-backup-on-k8s-eks): use minio as S3 backend

---

sdcm/tester.py

For the moment 'monitor' instance type is used for deployment of loader nodes. It is incorrect.
So, reuse appropriate config option for creation of loader nodes on EKS.

fix(k8s-eks): use proper instance type for loader nodes

---

sdcm/cluster.py

The firewalld was introduced as a replacement for the previous iptables
service from RHEL7. The iptables service is still enabled in our OEL8 AMI,
it doesn't allow to ping scylla-manager server by the public ip.
So we need try to stop both iptables service or firewalld service. the
exception should be ignored if the service doesn't exist.
refs:
- https://oracle-base.com/articles/linux/linux-firewall-firewalld
- https://linuxize.com/post/how-to-configure-and-manage-firewall-on-centos-8/

fix(node_setup): try to disable iptables and firewalld services

---

sdcm/sct_config.py

ami for wrong version may return.
Example:
if we ask version '4.0' it returns ami for 4.4.0.
It happens because of we search if the ami name includes the version number.
Version name '4.4.0' includes '4.0'
ami name format example: 'ScyllaDB 4.4.0'
rolling-upgrade-ami test in branch-2020.1 run on '4.4.0' when base_version is '4.0'

fix(sct configuration): ami for wrong version may return

---

test-cases/gemini/gemini-1tb-10h.yaml

Since gemini has failed several times in the past due to running out of memory
(as described here https://github.com/scylladb/gemini/issues/228),
I changed the loader instance type to m5.xlarge

fix(gemini-1tb-10h): Changed loader instance type to m5.xlarge

---

jenkins-pipelines/rolling-upgrade-ami.jenkinsfile

AMIs in branch 2019.1 have no 'user_data_format_version' tag and it cause to
test failure.

fix(rolling-upgrade-ami-test): remove 2019.1 from base versions

---

sdcm/sct_events/base.py

https://trello.com/c/tmppHeqY/3449-fix-del-of-sctevent
Stop it from throwing:
```
Call stack:
File "/extra/scylladb/scylla-cluster-tests/dkropachev2/sdcm/sct_events/base.py", line 218, in __del__
LOGGER.warning(
Message: '[SCT internal warning] %s has not been published or dumped, maybe you missed .publish()'
Arguments: (<sdcm.sct_events.loaders.CassandraStressLogEvent.TooManyHintsInFlight object at 0x7fcf31f3fb50>,)
Exception ignored in: <function SctEvent.__del__ at 0x7fcf3854d040>
File "/extra/scylladb/scylla-cluster-tests/dkropachev2/sdcm/sct_events/base.py", line 218, in __del__
File "/usr/lib/python3.8/logging/__init__.py", line 1446, in warning
File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
File …
```

fix(sctEvent): fix __del__ to do not raise when hit race condition with dealloc of LOGGER

---

sdcm/tester.py

https://trello.com/c/mWkn1q2s/3439-start-timeout-thread-after-resources-were-created

fix(tester.py): move starting timeout thread to the end of setup

---

sdcm/cluster.py
test-cases/features/scale-cluster.yaml

Changing the scale test to use m5d instance type instead of i3,
increases dramatically the chances of getting 200 spot instances
for the entire test period.
However, m5d instances aren't officially optimized for scylla,
hence the node_setup will fail for them.
In order to start them it requires to either run scylla_io_setup
(iotune) or to workaround it by adding "fake" io.conf files
the workaround).
Another required refactor is changing the test to use only one
seed. Otherwise, the test can hang waiting for the seeds to start
and it seems like we no longer need it since scylla removed the
seed concept.

refactor(scale test): Switching to m5d instance and one seed

---

defaults/test_default.yaml
docs/configuration_options.md
sdcm/cluster.py
sdcm/sct_config.py

Since the 'segments_per_repair' config option was removed in manager 2.3,
we removed it entirely from SCT.

fix(manager): removed segments_per_repair config option entirely

---

test-cases/features/repair-based-operations/longevity-100gb-4h-ReplaceNode.yaml

longevity-100gb-4h-ReplaceNode.yaml: Make each replace takes longer
- Reduce the nodes from 6 to 4
- Increase dataset from 100GB to 300GB

longevity-100gb-4h-ReplaceNode.yaml: Make each replace takes longer

---

test-cases/features/repair-based-operations/longevity-100gb-4h-Decommission.yaml
test-cases/features/repair-based-operations/longevity-100gb-4h-RemoveNode.yaml
test-cases/features/repair-based-operations/longevity-100gb-4h-ReplaceNode.yaml
test-cases/features/repair-based-operations/longevity-50GB-12h-RemoveNode.yaml
test-cases/features/repair-based-operations/longevity-50GB-12h-ReplaceNode.yaml
test-cases/features/repair-based-operations/longevity-cdc-100gb-4h-Decommission.yaml
test-cases/features/repair-based-operations/longevity-cdc-100gb-4h-RemoveNode.yaml
test-cases/features/repair-based-operations/longevity-cdc-100gb-4h-ReplaceNode.yaml

The default nemesis_during_prepare is true, but we don't expect the
nemesis to run too early in rbno tests.
Suggested by Asias.

fix(repair-based-operations conf): disable to run nemesis during prepare write

---

sdcm/cluster_k8s/__init__.py
sdcm/k8s_configs/minio/Chart.yaml
sdcm/k8s_configs/minio/templates/_helper_create_bucket.txt
sdcm/k8s_configs/minio/templates/_helpers.tpl
sdcm/k8s_configs/minio/templates/clusterroles.yaml
sdcm/k8s_configs/minio/templates/configmap.yaml
sdcm/k8s_configs/minio/templates/deployment.yaml
sdcm/k8s_configs/minio/templates/post-install-create-bucket-job.yaml
sdcm/k8s_configs/minio/templates/pvc.yaml
sdcm/k8s_configs/minio/templates/rolebindings.yaml
sdcm/k8s_configs/minio/templates/secrets.yaml
sdcm/k8s_configs/minio/templates/securitycontextconstraints.yaml
sdcm/k8s_configs/minio/templates/service.yaml
sdcm/k8s_configs/minio/templates/serviceaccount.yaml
sdcm/k8s_configs/minio/values.yaml

Upstream Helm chart we used was removed from public helm charts and appropriate github repo was archived.
It was replaced with the new approach where minio operator and console must be deployed. 
Then, with it's help we will be able to deploy MinIO server.
If we do it this way we will have 2 redundant pods (minio-operator and minio-console) and more complicated logic not having any gain of it.
So, fork and simplify old helm chart and continue using it for our simple MinIO deployment which will use the same minio docker images which 'minio-operator' uses.

fix(k8s-minio): install MinIO using local chart files

---

sdcm/cluster_k8s/eks.py
sdcm/tester.py

EKS networking is designed to have cached/reserved IP addresses on each
EC2 instance which is part of an EKS cluster.
Each network interface of an EC2 instance has limit for number of IPs.
For example, we use 'i3.4xlarge' instance type for our 4 scylla nodes.
Each of these nodes will have 2 network interfaces where each one
contains 30 IP addresses (1 for itself and 29 reserved).
So, our 4 scylla nodes take out 240 IP addresses from a subnet that is
used for deployment. In our case it is /22 subnet which is <1024 IPs.
And we also have other nodes such as loader, monitor and default ones.
In summary one our EKS cluster reserves about 321 IP address from a
subnet. So, using /22 subnet we can run just 3 EKS clusters at once
assuming there are no other significant usages of IP addresses in …

improvement(k8s-eks): reduce number of reserved IP addresses by nodes

---

sdcm/utils/cloud_monitor/report.py
sdcm/utils/cloud_monitor/templates/per_qa_user.html

Remove from report instances with owner qa

fix(qaonlytimedistreport): add filter out qa user

---

unit_tests/test_tester.py

https://trello.com/c/he5IS00P/3444-subtestassertandteardownfailstest-unit-test-failure

fix(test_tester.py): fix ClusterTesterForTests to sleep before stopping event devices to reduce possibility to swallow events

---

.pre-commit-config.yaml

'pre-commit' checks do not understand substitution parts
of yaml templates used in Helm charts.
So, exclude recently added 'minio' yaml templates the same way
as it is excluded for another existing local helm chart - 'provisioner'

fix(pre-commit-checks): exclude minio chart template yaml files

---

sdcm/nemesis.py

if cluster configured with single seed node, then terminateandreplace nemesis
could fail if this node set as target and fail the test.

fix(nemesisterminatereplace): Skip nemesis if target node is single seed node

---

sdcm/cluster.py

Artifact ami test failed during scylla_image_setup with error:
`ValueError: invalid literal for int() with base 16: '/var/lib/scylla/data doesnot
exist - skipping\n000000ff'`
In the master branch only files under data folder are removed.
Change 'clean_scylla_data' function accordingly
[Failed job](https://jenkins.scylladb.com/job/enterprise-2020.1/job/artifacts/job/artifacts-ami-test/411/console)

fix(artifact ami test): does not remove scylla data dir during scylla_image_setup

---

artifacts_test.py
sdcm/cluster_aws.py
sdcm/tester.py

Moved the snitch test to artficarts tests with the addition of running the node health check in artifacts testing and a small refactor for get_endpoint_snitch() method.
Change list:
- moved and refactored one test from snitch_test.py to artifacts_test.py The original test was written for GCE images specifically, so it required some generalization to make it work with AMI and GCE images. The test is now one of the artifacts_test verification methods
- added a new verification method in artifacts_test.py for running node health checks with the artifacts tests
- added a Backends NamedTuple in artifacts_test.py to avoid using magic strings in test methods
- added get_describecluster_info() method in tester.py with an associated NamedTuple for capturing nodetool describecluster output
- …

refactor(snitch_test)-move-snitch-test-to-artifacts-tests

---

sdcm/cluster.py

RestartNodeWithResharding nemesis used `nodetool compactionstats` and searched the results of calling that command to assert if resharding has taken place. This PR silences the publishing of the `NodeToolEvent` associated with the `nodetool compactionstats` call to the logs.
Trello task: https://trello.com/c/3RL23Yp9
"Before" jenkins pipeline run (208 "compactionstats" log lines): https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-restart-with-resharding/6/
"After" jenkins pipeline run (0 "compactionstats" log lines): https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-restart-with-resharding/7/

improvement(restart_with_resharding): don't publish compactionstat event

---

sdcm/cluster.py

Sometimes the go get command fails for timeouts or unclear error.
This will add the verbosity required to understand it.

fix(install_scylla_bench): Add verbose option and retrying

---

sct.py
vars/longevityPipeline.groovy
vars/runSctTest.groovy

https://trello.com/c/zLsCi1KE/3407-create-an-infra-using-pytest-to-run-a-basic-set-of-operator-funcitonal-tests
Part of changes that targets scylla operator functional tests
This particular peace is addressing ability to run tests pytest-based tests

feature(sct.py): add run-pytest

---

sdcm/cluster_k8s/__init__.py
sdcm/tester.py
sdcm/utils/k8s.py

We deploy lots of pods in our K8S clusters which, if not defined,
may be scheduled unexpectedly onto scylla nodes taking it's resources.
And those pods may be victims of nemesis disruptions we do with scylla K8S nodes.
So, schedule properly following apps:
- cert-manager
- scylla-manager
- kube-dns (coredns)

improvement(kubernetes): schedule pods on proper nodes

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py

This PR consists of following parts:
1) Use same scrape interval and timeout in K8S prometheus as in the SCT one
2) Make K8S grafana be accessible out-of-cluster
3) Simplify K8S monitoring health checker removing redundant parts.

Improve K8S monitoring usefulness

---

commitlint.config.js

Reason:
The number 72 comes from the fact that 80 characters is the widely
accepted industry standard for readable character length of one
line, git automatically adds a padding of 4 characters to the left
of the commit message body, and to keep everything centered
and looking nice, 4 characters should be padded to the right.

improvement(commitlint): restrict header to be at max 72 symbols long

---

sdcm/logcollector.py

Trello: https://trello.com/c/zD8aXzzb
At the end of the job, during collecting email data,
on stage getting grafana screenshot and snapshot,
monitoring node was killed or connection lost.
These cause that Snapshot could n't get the monitoring version,
because could n't connect to monitor node and raise the exception
'exception=Unable to run "ls /home/scylla-test/sct-monitoring | grep scylla-monitoring-src":
failed connecting to "10.142.15.192" during 60s'
and these exception failed to save_email_data and email report is not save to file.

fix(get_monitoring_version): don't fail save_email_data if monitor node were killed

---

test-cases/features/repair-based-operations/longevity-100gb-4h-ReplaceNode.yaml
test-cases/features/repair-based-operations/longevity-1TB-12h-GrowShrink.yaml

- Limit QPS for stress_cmd
- Disable HH for replace ops
- Use 3 seed nodes
-  Set stall detector to 20ms

Update conf for rbno tests

---

artifacts_test.py

Our artifacts tests were checking for the correct snitch according to the backend used. When we are not using a preinstalled Scylla version, the snitch is not set to the backend-specific version, so the tests fail. This PR adds a simple `if`-check for the `use_preinstalled_scylla` param: if we're not using a preinstalled Scylla, we skip the snitch check altogether.
Jenkins jobs:
- with skip (without preinstalled scylla): https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-artifacts/job/mc-artifacts-centos-7/14/
- without skip (without preinstalled scylla): https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-artifacts/job/mc-artifacts-centos-7/13/

fix(artifacts_test): skip snitch test when not using a preinstalled version

---

upgrade_test.py

In the issue https://github.com/scylladb/scylla-enterprise/issues/1698
Eliran suggested to ignore the error when the first node gets upgraded
to enterprise until all nodes have the service_levels table propagated
to them.
For branch-2020.1 only.
Similar to fix in branch-2021.1:
https://github.com/scylladb/scylla-cluster-tests/pull/3520

[branch-2020.1] fix(upgrade test): ignore "Can't find column family error"

---

sdcm/utils/aws_utils.py

Got situation when waiting 60 seconds to get public ip was not enough
Increaing timeout up to 15 minutes

fix(ec2_instance_wait_public_ip): increase waiting timout up to 15 minutes

---

sdcm/utils/scylla_args.py

Reverts scylladb/scylla-cluster-tests#2686
Original issue https://github.com/scylladb/scylla-enterprise/issues/1473 was fixed.

Revert "fix(scylla_args): workaround for doubled scylla options"

---

defaults/severities.yaml
sdcm/sct_events/base.py
sdcm/sct_events/loaders.py
sdcm/stress_thread.py
unit_tests/test_sct_events_loaders.py

Convert CassandraStressEvent to be continuous event and report when it begins and ends.
[Task](https://trello.com/c/bOEw6JcD/3467-convert-cassandrastressevent-to-be-continuous-event)
[Test with event](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/yulia/job/staging-10gb-3h/lastBuild/console)

refactor(cassandra-stress event): define c-s event as continuous event

---

sdcm/cluster.py

Related to https://github.com/scylladb/scylla-monitoring/issues/1445
Tested here: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/byo-longevity-test/149/consoleFull
Failure:
```
19:39:31  < t:2021-06-20 16:39:30,960 f:tester.py       l:132  c:sdcm.tester          p:ERROR >     raise UnexpectedExit(result)
19:39:31  < t:2021-06-20 16:39:30,960 f:tester.py       l:132  c:sdcm.tester          p:ERROR > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
19:39:31  < t:2021-06-20 16:39:30,960 f:tester.py       l:132  c:sdcm.tester          p:ERROR > 
19:39:31  < t:2021-06-20 16:39:30,960 f:tester.py       l:132  c:sdcm.tester          p:ERROR > Command: 'bash -ce \'\ncd -P /home/centos/sct-monitoring/scylla-monitoring-src\nmkdir -p …
```

fix(monitoring): removing unnecessary backslash

---

defaults/severities.yaml
sdcm/gemini_thread.py
sdcm/sct_events/loaders.py
unit_tests/test_sct_events_loaders.py

Convert GeminiEvent to be continuous event and report when it begins and ends.
Events:
```
2021-06-20 15:39:21.213: (GeminiStressEvent Severity.NORMAL) period_type=begin event_id=a22ce53d-4f63-404d-bdcb-4aa0e2337e4f: node=Node gemini-basic-3h-event-re-loader-node-9bbd40a9-1 [54.217.52.215 | 10.0.2.53] (seed: False) gemini_cmd=/$HOME/gemini -d --duration 6000s --warmup 1800s -c 100 -m mixed -f --non-interactive --cql-features normal --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --async-objects-stabilization-attempts 5 --async-objects-stabilization-backoff 500ms --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --oracle-replication-strategy "{'class': …
```

fix(gemini event): Convert GeminiEvent to be continuous event

---

sdcm/logcollector.py

Zip does per-file compression and tar does it per-dir.
And we compress directories with lots of files then upload it to S3.
Compression example of the same K8S logs set:
- 36Mb using zip
- 2.9Mb using tar.gz
So, make our 'logcollector' compress files using 'tar' and not 'zip'
to be able to reduce the used S3 storage and reduce download time
significantly.

improvement(logcollector): make tar.gz archives instead of zip ones

---

sdcm/nemesis.py

The issue that if we have one seed node, we first terminate it and
then try to add new node, but it will failed, because no seeds left in cluster.
As a solution,
1.check if node is single seed
2.if yes, then choose random node and set it as seed
3.terminate target seed node and replace with new one.
4.leave cluster as is with seed node choosen on step 2
related to
https://github.com/scylladb/scylla-cluster-tests/pull/3651

fix(terminateandreplace): choose new seed before termination old one

---

defaults/test_default.yaml
sdcm/logcollector.py
sdcm/monitorstack/ui.py

Next versions of scylla-monitoring is going new grafana versions,
which require authentication for getting grafana livesnapshots.
Added new class to monitoring.ui, which allow to logged in to
grafana and get access to grafana livesnapshots functionality.

feature(grafana_snapshot): Add ability to login to grafana

---

sdcm/cluster.py
sdcm/scylla_bench_thread.py

We are not installing s-b if it is not present in stress commands definitions
But there are cases when we still need it,
for example disrupt_truncate_large_partition still can fire
To cover such cases we need to install it by request

fix(scylla_bench_thread): auto install s-b if not installed

---

sdcm/sct_config.py

fix(list_of_stress_tools): make it work when command is a list

---

configurations/manager/debian10.yaml
configurations/manager/debian9.yaml
configurations/manager/ubuntu16.yaml
configurations/manager/ubuntu18.yaml
configurations/manager/ubuntu20.yaml
defaults/test_default.yaml

Since 2021 has a build for both debian 10 and ubuntu 20,
I changed scylla_repo_m to use scylla enterprise 2021 across the board

refactor(manager): advanced the manager's scylla backend to 2021.1

---

defaults/k8s_gke_config.yaml

Right now we use specific K8S version on GKE which are build specific.
Example, currently used one: '1.19.9-gke.1400'
This one became obsolete and not available anymore for usage.
So, instead of providing one another specific version, use 'major'
one to forget such problem as regular sudden GKE cluster creation
failures caused by non-supported versions.

fix(k8s-gke): specify major K8S version for GKE cluster creation

---

sdcm/k8s_configs/loaders.yaml

For the moment we set fixed limit for resource utilization by loader pods.
For example, if we have 4 CPU cores then only 3 of them will be used by a loader pod.
Such restriction directly influences performance measurement.
So, remove upper limit and use only lower one for loader pods allowing K8S provide more when there are free resources.
And there must be free resources because laoder pods run on dedicated nodes where nothing else resource-consuming is going to run.
Running latency-read test I got following results for latency 99th percentile on my setup:
- 5.1ms with fix
- 5.7ms without fix

fix(k8s-loaders): remove upper limits for loader pods

---

sdcm/nemesis.py

Due to multiple known issues like https://github.com/scylladb/scylla/issues/5080
I decided to disable this nemesis for now, until we get a fix for these issues.

refactor(nemesis): Disable RestartThenRepairNodeMonkey

---

test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml

Each local_ssd disk size is 375 GB, using only 6 disks is not enough
for this dataset and during a rebuild a node is running out of space.
I set it to 10 to match the size of i3.4xlarge (3.8 TB).

fix(longevity-1TB): Fix the number of local_ssd_disk needed for 1TB

---

artifacts_test.py

fix(artifacts_test.py): fix string formatting in log calls

---

configurations/manager/debian9.yaml
configurations/manager/ubuntu16.yaml
configurations/manager/ubuntu18.yaml

Current scylla_repo_m in ubuntu 16, 18 and debian 9 urls are erroneous,
restored them to previous, correct, urls
Fixes an error I made in #3674

fix(scylla_repo_m): Fixed scylla db 2020 manager backend url

---

data_dir/scylla-dash-per-server-nemesis.master.json

Adding new panels to `data_dir/scylla-dash-per-server-nemesis.master.json` to handle NdBench metrics. 
New panels:
Trello task: https://trello.com/c/wD5IGegP/226-explore-netflix-data-store-benchmark

test(longevity_ndbench): add Grafana panels with ndbench metrics

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py
sdcm/cluster_k8s/gke.py
sdcm/nemesis_publisher.py

We have 2 skipped nemesises for termination of K8S nodes:
- terminate_k8s_node
- terminate_k8s_host
Both of these have implementation bugs such as attempt to get inexistent variable or using wrong one.
So, fix those bugs now. And later only uncomment it's usage when [1] is fixed.
[1] https://github.com/scylladb/scylla-operator/issues/643

fix(k8s-nemesis): fix logic of terminate_k8s_node nemesis

---

sdcm/sct_runner.py

Adding the `kubectl` binary to our base SctRunner classes `prereqs_script` so that we have an additional tool for kubernetes deployments debugging.
- ~~[ ] I added the relevant `backport` labels~~

feature(SctRunner): add kubectl bin

---

defaults/severities.yaml
sdcm/cluster.py
sdcm/sct_events/__init__.py
sdcm/sct_events/database.py
sdcm/utils/scylla_args.py
unit_tests/test_utils_scylla_args.py

https://trello.com/c/EPQYaUeU/3537-investigate-enterprise-version-running-on-sct-master-failure
When scylla help mentions any variable twice, scylla node fails to start.
This fix will publish error event instead.
TIme to time enterprise scylla have doubled help message and it blocks us from running tests on it.

Fix double args

---

sdcm/monitorstack/__init__.py

https://trello.com/c/Jg9uGvTj/3550-fix-investigate-show-monitor-issue
Somehow we started pack monitoring stack into tar, while extracting them as zip

feature(monitoringstack): make it extract from tars

---

sdcm/cluster.py
sdcm/sct_events/base.py
sdcm/sct_events/loaders.py
sdcm/sct_events/nodetool.py
unit_tests/test_events.py
unit_tests/test_sct_events_loaders.py
unit_tests/test_sct_events_nodetool.py

Convert NodetoolEvent to be continuous event and report when it begins and ends.
Event example:
```
2021-06-23 14:43:10.490: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=b25368e9-5091-4fc9-aaa6-44da583025e7: nodetool_command=flush node=longevity-10gb-3h-nodetool-db-node-34a51554-1
2021-06-23 14:43:20.001: (NodetoolEvent Severity.NORMAL) period_type=end event_id=b25368e9-5091-4fc9-aaa6-44da583025e7 duration=9s: nodetool_command=flush node=longevity-10gb-3h-nodetool-db-node-34a51554-1
```
raw events:
```
{"base": "NodetoolEvent", "type": null, "subtype": null, "timestamp": 1624459390.4906101, "severity": "NORMAL", "event_id": "b25368e9-5091-4fc9-aaa6-44da583025e7", "log_file_name": null, "errors": …
```

refactor(nodetool event): Convert NodetoolEvent to be continuous event

---

sdcm/sct_events/database.py
sdcm/sct_events/health.py
sdcm/sct_events/system.py
unit_tests/test_sct_events_database.py
unit_tests/test_sct_events_health.py
unit_tests/test_sct_events_system.py

[Task](https://trello.com/c/JeaRyS0N/3541-convert-all-remained-informational-events)

refactor(info events): convert all one-time events to informational

---

sdcm/cluster.py
sdcm/cluster_k8s/__init__.py
sdcm/tester.py
sdcm/utils/aws_utils.py
sdcm/utils/common.py
sdcm/utils/k8s.py
sdcm/wait.py
unit_tests/test_wait.py

We've decided to change the default of throw_exc to True,
since when the function is used with throw_exc=False, and it reaches timeout,
there is next to no indication, other than a print message, that the wait_for has failed.
Also, this change aligns the default with the parallel function in dtest.

refactor(wait_for): Changed throw_exc default to True

---

defaults/k8s_eks_config.yaml

The reason for it is that EKS uses too old minor version for 1.19
Scylla Operator v1.4-alpha requires at least v1.19.10, but EKS has only 1.19.8
So, switch to usage of v1.20.x because all of these have required bugfix [1].
[1] https://github.com/kubernetes/kubernetes/pull/98732

fix(k8s-eks): use K8S v1.20 instead of v1.19 in EKS

---

docker/cdcstressor/image
sdcm/cdclog_reader_thread.py

https://trello.com/c/al4mEwqU/3597-cdc-stresser-changed-its-command-line-arguments-requirements
https://github.com/scylladb/scylla-cluster-tests/issues/3720
Test-id: 80fa4825-41a0-4634-ae74-53b65604e128
cdc-stressor fails with argument error
```
stress_cmd=cdc-stressor -username cassandra -password cassandra -duration 2h -stream-query-round-duration 30s -keyspace ks1 -table table1_scylla_cdc_log                             -nodes 10.142.0.122,10.142.0.10,10.142.0.125,10.142.0.127 -group-size 8                             -worker-id 0 -worker-count 1
errors:
flag provided but not defined: -username
Usage of cdc-stressor:
-backoff-max duration
maximum time to wait on backoff (default 1s)
-backoff-min duration
minimum time to wait on backoff (default 1s)
-backoff-multiplier float
multiplier …
```

Fix update cdc stressor

---

test-cases/gemini/gemini-1tb-10h.yaml
test-cases/gemini/gemini-3h-cdc-postimage-write.yaml
test-cases/gemini/gemini-3h-cdc-preimage-write.yaml
test-cases/gemini/gemini-3h-cdc-write.yaml
test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-3h-with-nemesis.yaml
test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-8h-large-num-columns.yaml
test-cases/gemini/gemini-basic-3h-ics.yaml
test-cases/gemini/gemini-basic-3h.yaml

To avoid cluster overloading number of concurrent threads
was decreased from 100 to 50

fix(gemini_cmd): Reduce gemini threads in test

---

jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile

fix(manager): changed default post behavior in all jobs to destroy

---

mgmt_cli_test.py
test-cases/manager/manager-regression-multiDC-set-distro.yaml

New in manager 2.4
When a manager backup task is stopped midway through its upload stage,
or in other similar situations, the files that were already uploaded to
the destination bucket will unnecessarily remain there. Those kind of files
are nicknamed 'orphan files'.
In manager 2.4, a new check was added to the backup task precedure, so that
during the task's run, the manager will detect all of the cluster's existing
orphan files, and will remove them from the destination bucket.
The test, test_backup_purge_removes_orphan_files, checks this exact situation,
and verifies that the orphan files are indeed removed.
Due to the new tests, I extended manager regression test job timeout.
Successful run: f580b7b4-be02-485c-9872-dec73ffaf57e

test(manager): Backup purge removes orphans files

---

sdcm/cluster.py

Don't need NodetoolEvent when waiting for space_node_threshold before start the nemesis, not publish it
[Task](https://trello.com/c/8L8hlG4t/3624-not-publish-nodetoolevent-when-waiting-for-spacenodethreshold)

fix(cfstat event): not publish NodetoolEvent when waiting for space_node_threshold

---

sdcm/nemesis.py
sdcm/sct_events/base.py
sdcm/sct_events/nemesis.py
unit_tests/test_events.py
unit_tests/test_nemesis.py

Messages examples:
```
2021-07-05 07:01:43.993: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=a383c335-e448-4c67-bd6e-929ba6ba88aa: nemesis_name=DeleteByRowsRange target_node=Node longevity-10gb-3h-event-re-db-node-46d0b056-2 [13.49.222.216 | 10.0.3.54] (seed: False)
2021-07-05 07:02:29.515: (DisruptionEvent Severity.NORMAL) period_type=end event_id=a383c335-e448-4c67-bd6e-929ba6ba88aa duration=45s: nemesis_name=DeleteByRowsRange target_node=Node longevity-10gb-3h-event-re-db-node-46d0b056-2 [13.49.222.216 | 10.0.3.54] (seed: False) skipped skip_reason=This nemesis can run on scylla_bench test only
2021-07-05 07:05:10.089: (DisruptionEvent Severity.NORMAL) period_type=begin …
```

refactor(nemesis event): convert nemesis event to be continuous

---

test-cases/gemini/gemini-1tb-10h.yaml

fix issue #3739 by changing the duration + warmup = 10h

fix(gemini-1tb-10h): Change test duration to 10h

---

sdcm/fill_db_data.py

https://github.com/scylladb/scylla-cluster-tests/issues/3721
https://trello.com/c/kJCdDZb7/3598-make-upgrade-tests-report-in-details-step-it-done-and-time-it-took
Upgrade tests time to time is running slow
It is hard to identify where exactly delay is
Let's log everything between upgrades to see what is running slow

feature(fill_db_data): log every step in between updates

---

sdcm/cluster_k8s/__init__.py
sdcm/k8s_configs/monitoring/scylla-manager-service-monitor.yaml
sdcm/k8s_configs/monitoring/scylla-service-monitor.yaml
sdcm/k8s_configs/monitoring/values.yaml
sdcm/tester.py

For the moment we parse operator helm chart version for getting git tag and picking up monitoring helm chart values file.
Such approach doesn't work when operator helm chart doesn't contain any info related to tags such as developer custom charts.
So, knowing above, start storing values.yaml file for monitoring helm chart locally with all the data we were adding separately.
It will allow us to achieve following:
- We do not depend anymore on the helm chart versions parsability.
- Python code for deployment of K8S monitoring becomes simplier because all the configuration is stored in local yaml files.

feature(k8s-monitoring): store K8S monitoring config in local yaml files

---

docs/configuration_options.md
jenkins-pipelines/operator/upgrade/upgrade-operator-k8s-eks.jenkinsfile
jenkins-pipelines/operator/upgrade/upgrade-operator-k8s-gke.jenkinsfile
sdcm/cluster_k8s/__init__.py
sdcm/sct_config.py
sdcm/utils/k8s.py
test-cases/scylla-operator/kubernetes-operator-upgrade.yaml
test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml
upgrade_test.py
vars/rollingOperatorUpgradePipeline.groovy
vars/runSctTest.groovy

Add test case which allows us to run scylla operator upgrade.
Following new config options are added:
- **k8s_scylla_operator_upgrade_helm_repo**
It can be empty. In such case will be used value
from the main 'k8s_scylla_operator_helm_repo' option.
- **k8s_scylla_operator_upgrade_chart_version**
It can be '' (empty), 'latest' or specific like "v1.3.0"
- **k8s_scylla_operator_upgrade_docker_image**
It can be empty or be like 'scylladb/scylla-operator:latest'

feature(kubernetes): add operator upgrade test

---

functional_tests/scylla_operator/conftest.py
functional_tests/scylla_operator/libs/auxiliary.py

Currently if cwd is different from sct path it fails

fix(functional_tests): make it work for all cwd

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/mini_k8s.py

https://trello.com/c/iCmqi4N2/3622-investigate-functional-tests-issues
Make kind cluster to be deleted if no SCT_REUSE_CLUSTER is set

k8s-local-kind: kill old cluster if REUSE_CLUSTER is not set

---

sdcm/cluster_k8s/mini_k8s.py
sdcm/tester.py

https://trello.com/c/iCmqi4N2/3622-investigate-functional-tests-issues
Do following things:
1. Speedup kind cluster initialization by pushing scylla image into the workers
2. FIxes problem with unavialability of kind networks from userspace
Fixes:
https://github.com/scylladb/scylla-cluster-tests/issues/3750

k8s-local-kind: give from userspace to kind networks and speedup cluster init

---

sdcm/nemesis.py

Added an additional mode to to backup nemesis.
The Cloud manager command is used for a cloud-cluster.

improvement(manager backup): Added cloud manager backup to nemesis

---

defaults/test_default.yaml
docs/configuration_options.md
sdcm/results_analyze/__init__.py
sdcm/sct_config.py
sdcm/tester.py

Limit number of events for perf emails. In case of large number
of events, screenshots could be out of visible part of email.

fix(check_regression): Limit number of events for perf email

---

sdcm/cluster_k8s/mini_k8s.py

Small issue when cluster is reused image is in the cache `kind load docker-image` fails

Fix k8s local reuse

---

sdcm/sct_events/base.py
unit_tests/test_sct_events_continuous_events_registry.py

Added a singleton class ContinuousEventRegistry with some utility methods for filtering different events registered in it. Plus some unit tests.
Trello task: https://trello.com/c/b3NhuY6V/3260-enhancement-of-the-event-types

improvement(sct_events): add singleton ContinuousEventsRegistry

---

sdcm/cluster_k8s/__init__.py

Operator v1.4.x switched to usage of seedless approach for scylla and now we should not fail test run if no seed nodes are found.
So, make it be smart enough and do not fail when seed nodes are not defined, but still allow it to be set.
It will allow us to run old and new operator versions using the same code.

fix(kubernetes): make SCT support seedless scylla using operator

---

sdcm/cluster.py
sdcm/tester.py

Trello: https://trello.com/c/HnI978Y9
_self._get_common_email_data() could fail during getting the scylla shard or when Tester.db_cluster is not set if test failed during setup.
Added appropriate checks to avoid failing _self._get_common_email_data()

Fix na email report data

---

jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile

Since 2.4 has been released, I changed the base version of manager from 2.3
to 2.4 in all of the upgrade tests.
Also, since there was no 2.3 release for ubuntu 20 and debian 10,
their upgrade tests were disabled. Now that the base version is 2.4, which
has releases for both of those distributions, I enabled their upgrade tests

refactor(manager-upgrade): change base version to 2.4

---

sdcm/logcollector.py
sdcm/tester.py

during job scylla-master/longevity-200gb-48h/126/
email_data.json file was not saved correctly due to
error:
t:2021-07-11 04:34:51,531 f:send_email.py l:643 c:sdcm.send_email
p:WARNING > Error during collecting data for email Circular reference detected
And when this file was read durin email_send stage it failed with error:
t:2021-07-11 04:34:51,742 f:send_email.py l:625 c:sdcm.send_email p:WARNING >
Error during read email data file /home/ubuntu/sct-results/20210709-030744-525604/email_data.json:
Expecting value: line 1 column 97262 (char 97261)
the main error happened during dumping email_data object to json file:
json.dump(email_data, json_file)

fix(sctlogcollector): Add email_data.json file to sctlog arch

---

functional_tests/scylla_operator/test_functional.py
sdcm/cluster_k8s/__init__.py

--listen-address flag description says 'Never specify 0.0.0.0; it is always wrong.'
which isn't true as using 0.0.0.0 is valid when using explicit --broadcast-address
Issues:
https://github.com/scylladb/scylla-operator/issues/484
https://github.com/scylladb/scylla/issues/8381
[Task](https://trello.com/c/MYF0CO7a/3578-check-that-scylla-listens-on-0000)

test(listen address): Let scylla listen on 0.0.0.0

---

sdcm/nemesis.py

fix(disrupt_nodetool_refresh): make it wait for resharding log messages

---

sdcm/cluster.py

If exception happens during nodetool run and this exception is expected (exception type is in
warning_event_on_exception parameter value), this event should be WARNING and the exception
should not be raised to prevent catching it in the '__exit__' and changing severity to ERROR.
Actually in this case the exception has no value for the test.
Example when expected failure was reported as ERROR and failed the test
(disrupt_repair_streaming_err nemesis nemesis):
https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-3h-with-nemesis-test/240

fix(nodetool): prevent reporting event as error if it should be warning

---

sdcm/cluster_k8s/mini_k8s.py
sdcm/utils/common.py

https://trello.com/c/CxYG4RQ3/3647-fixfunctional-fix-kubectl-proxy-starting-logic-to-cover-reuse-cluster-case
kubectl can be running from priviouse run when reuse_cluster=1
For remote run it is okay to kill it,
since one node can be used only for one run
While it is not okay for local runs, since it is possible
that kubectl proxy is ran by user for it's purpose.
So for local run let's find free port and feed it to kubectl proxy

fix(k8s-local*): fix kubectl proxy issue with reuse cluster

---

functional_tests/scylla_operator/test_functional.py

Add test case to cover following fixed bug:
https://github.com/scylladb/scylla-operator/issues/447

feature(k8s-functional-test): cover creation of invalid ScyllaClusters

---

sdcm/kcl_thread.py

Per Core request, use: "scylladb/hydra-loaders:kcl-jdk8-20210526-ShardSyncStrategyType-PERIODIC"
This will be probably needed to all Alternator Streams related Longevities.
See Core explanation in:
https://github.com/scylladb/scylla/issues/8012#issuecomment-847846088
Docker KCL is based on: https://github.com/fruch/hydra-kcl

improvement(kcl_thread.py): New KCL docker for periodic-shard-sync strategy
