sdcm/cluster_k8s/__init__.py, sdcm/utils/remote_logger.py
https://trello.com/c/gli32k8V/2535-k8s-add-event-logger-for-scylla-cluster
It will help investigate s-o issues, you will be able to see what is kubernetes doing on the cluster.
=> improvement(k8s): add event logger thread

defaults/k8s_gce_minikube_config.yaml, defaults/k8s_gke_config.yaml, sdcm/cluster_k8s/__init__.py, sdcm/k8s_configs/cluster-gke.yaml, sdcm/k8s_configs/cluster-minikube.yaml, sdcm/k8s_configs/operator.yaml
Trello: https://trello.com/c/8uczk7NE/2549-switch-to-scylla-operator-nightly-builds
=> improvement(operator): switch to nightly builds

sdcm/nemesis.py
* Nemesis failed because the message we were looking for in the log file did not found.
The changes:
* The number of attempts was relatively small, and now the value is changed to
`30` instead of `3` attempts.
* The expected message was changed from `Reloaded` to the
`messaging_service - Reloaded {file_path}`
=> fix(nemesis.py): Fixing 'disrupt_hot_reloading_internode_certificate'

sdcm/cluster_k8s/__init__.py
https://trello.com/c/X298xmfP/2556-k8s-waitforpodsreadiness-does-not-respect-node-count
=> fix(wait_for_pods_readiness): make it actually respect nodes count

sdcm/remote/kubernetes_cmd_runner.py
https://trello.com/c/1YqcUBJz/2558-k8s-runner-issue
KubernetesCmdRunner does not retry on api level errors like ConnectionError:
```
3:36:22  < t:2020-11-18 16:36:19,282 f:nemesis.py      l:2485 c:sdcm.nemesis         p:ERROR >   File "/jenkins/slave/workspace/scylla-staging/dmitry/dmitry-operator-byo-2/scylla-cluster-tests/sdcm/nemesis.py", line 2475, in wrapper
23:36:22  < t:2020-11-18 16:36:19,282 f:nemesis.py      l:2485 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
23:36:22  < t:2020-11-18 16:36:19,282 f:nemesis.py      l:2485 c:sdcm.nemesis         p:ERROR >   File "/jenkins/slave/workspace/scylla-staging/dmitry/dmitry-operator-byo-2/scylla-cluster-tests/sdcm/nemesis.py", line 3205, in disrupt
23:36:22  < t:2020-11-18 16:36:19,282 f:nemesis.py      l:2485 …
```
=> fix(kubernetes_cmd_runner.py): rebase it from RemoteCmdRunnerBase to fix retrying issue

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/gke.py, sdcm/remote/kubernetes_cmd_runner.py, sdcm/utils/k8s.py, unit_tests/test_remoter.py
https://trello.com/c/BEShkYKV/2548-ratelimiter-for-gke-k8s-api-requests
=> K8S: Rate limiter

sdcm/utils/remote_logger.py
When CommandLoggerBase restart command it feed all log records including those that are already read and stored
This PR will tackle this problem
=> fix(remoter_logger): fix kubernetes logger to prevent old and new log mixing on restart

configurations/rolling-upgrade-alternator.yaml, jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile, sdcm/group_common_events.py, sdcm/sct_config.py, sdcm/tester.py, sdcm/utils/alternator/api.py, sdcm/utils/alternator/enums.py, sdcm/utils/alternator/schemas.py, sdcm/ycsb_thread.py, upgrade_test.py, vars/rollingUpgradePipeline.groovy
* alternator - Create basic YAML for Alternator tests
* alternator-rolling-upgrade-without-LWT.jenkinsfile - Create new JOB 
for alternator upgrade test
* Adding new SCT config variables:
* alternator_write_stress_during_entire_test
* alternator_verify_stress_after_cluster_upgrade
* alternator_prepare_write_stress
* test_alternator_upgrade_without_lwt - Create test for
Alternator upgrade like `test_generic_cluster_upgrade` test
* Trello URL: https://trello.com/c/GSq4fuWv
=> improvement(test_rolling_upgrade.py): Creating upgrade rolling for Alternator

sdcm/cluster_k8s/gke.py, sdcm/tester.py, sdcm/utils/common.py, sdcm/utils/gce_utils.py, sdcm/utils/k8s.py
https://trello.com/c/UHYFqiHo/2553-gke-stop-using-gcloud-all-the-time
https://trello.com/c/oXnHoieT/2557-k8s-shared-kubectl-config-issue
=> fix(cluster_k8s): make kubectl config local

sdcm/utils/health_checker.py
https://trello.com/c/Uc6xfeoM/2627-fix-checkschemaversion
=> fix(check_schema_version): cover case when node is absent in gossip_info

sdcm/nemesis.py
=> fix(terminate_node): set last node as target for kubernetes case

sdcm/cluster_k8s/__init__.py
https://trello.com/c/wfGTqtmG/2600-deploy-sidecar-as-part-of-all-the-test-randomly-no-need-to-check-sidecar-is-working
=> fix(k8s_configs): add sidecar to both gke and minikube

sdcm/cluster_gce.py, sdcm/keystore.py, sdcm/utils/docker_utils.py
=> improvement(cluster_gce): block project-wide SSH keys

get-qa-ssh-keys.sh
https://trello.com/c/QJOF0VK2/2643-update-scylla-test-ssh-key-to-make-docker-backend-works-again
=> improvement(hydra): sync SSH keys with keystore

sdcm/cluster.py
https://trello.com/c/RJIRJwsG/2624-verifystressthread-fails-with-valueerror-substring-not-found
=> fix(verify_results): don't fail when get malformed result string

test-cases/features/ics_space_amplification_goal_test.yaml
since master loader ami now works ok with ICS.
=> improvement(ics_space_amplification_goal_test.yaml): Removed loader ami

jenkins-pipelines/upgrade-scylla-k8s-gke.jenkinsfile, jenkins-pipelines/upgrade-scylla-k8s-minikube.jenkinsfile, test-cases/scylla-operator/kubernetes-scylla-upgrade-gke.yaml, vars/getJenkinsLabels.groovy, vars/rollingOperatorUpgradePipeline.groovy
https://trello.com/c/2U7Q3e39/2637-upgrade-major-version
=> improvement(upgrade-scylla-k8s): move them to new pipeline

sdcm/remote/remote_base.py
=> fix(remoter_base): fix missprint

test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
https://trello.com/c/VVgsttgV/2671-gke-reduce-throttle-to-1000
=> fix(longevity-scylla-operator-3h-gke.yaml): reduce throttle to 1000 due to scylla low performance on gke

test-cases/upgrades/rolling-upgrade.yaml, vars/rollingUpgradePipeline.groovy
base_version list will be converted to scylla_repo (gce backend) or ami_id for
AWS backend.
=> feature(upgrade): support to upgrade with AMI

test-cases/scylla-operator/kubernetes-scylla-upgrade-minikube.yaml, vars/rollingOperatorUpgradePipeline.groovy
=> fix(vars/rollingOperatorUpgradePipeline.groovy): make new_version pass

sdcm/report_templates/results_issue_template.html, sdcm/send_email.py, sdcm/tester.py
Create an issue template constant information and attach to result email
- [x ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
=> improvement(issue template): Create an issue template constant information

sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/cluster_baremetal.py, sdcm/cluster_docker.py, sdcm/cluster_gce.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/gke.py, sdcm/cluster_k8s/minikube.py, sdcm/nemesis.py
=> fix(cluster_k8s): add rack feature

sdcm/cluster.py, sdcm/sct_events/base.py
Trello: https://trello.com/c/1tAkre3b/2660-sct-issues-warnings
=> fix(sct_events): ignore unpublished DB log events

sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/nemesis.py, test-cases/scylla-operator/longevity-scylla-operator-3h-minikube.yaml
https://trello.com/c/6Tztcf6A/2680-k8s-addremoveracknemesis-add-rack
=> feature(nemesis): add AddRemoveRackNemesis

jenkins-pipelines/longevity-scylla-operator-3h-gke-add-remove.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-cluster-rolling.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-grow-shrin.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-stop-start.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-replace.jenkinsfile, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-add-remove.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-cluster-rolling.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-grow-shrin.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-stop-start.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-replace.yaml
https://trello.com/c/CJZxYba0/2644-scyllaoperatorbasicoperationsmonkey
=> feature(gke-pipelines): add per base nemesis pipeline

data_dir/scylla-dash-per-server-nemesis.master.json, sdcm/cluster.py, sdcm/logcollector.py, sdcm/utils/common.py
Add test name to the dashboard tag and dashboard name
=> improvement(nemesis dashboard): dashboard should contain the test name

jenkins-pipelines/longevity-scylla-operator-3h-gke-add-remove-rack.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-grow-shrink.jenkinsfile, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-add-remove-rack.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-cluster-rolling.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-grow-shrink.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-stop-start.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-replace.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
https://trello.com/c/IyYICI3z/2701-gke-rename-jobs-and-add-extra-k8s-node
=> fix(scylla-operator): add extra node and rename yamls and pipelines

sdcm/utils/decorators.py
https://trello.com/c/zp6NJimT/2703-fix-lcd-issue
=> fix(latency_calculator_decorator): return actual value

sdcm/cluster_k8s/gke.py, sdcm/utils/gce_utils.py
=> fix(GcloudTokenUpdateThread): set expirity time to it's max and add timeout on token waiting

sdcm/utils/k8s.py
https://trello.com/c/HFwJAZMa/2705-k8s-make-rate-limiter-work-for-multiprocessing
=> fix(ApiCallRateLimiter): make it support multiprocessing

jenkins-pipelines/longevity-scylla-operator-basic-3h-gke.jenkinsfile, sdcm/nemesis.py, test-cases/scylla-operator/longevity-scylla-operator-basic-3h-gke.yaml
https://trello.com/c/CJZxYba0/2644-scyllaoperatorbasicoperationsmonkey
=> feature(ScyllaOperatorBasicOperationsMonkey): add the nemesis and create related jobs

sdcm/cluster_k8s/__init__.py
=> fix(cluster_k8s): add_nodes for multirack case

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/minikube.py, sdcm/k8s_configs/cluster-gke.yaml, sdcm/k8s_configs/operator.yaml
=> feature(cluster_k8s): infrastructure for OperatorNodeReplace, OperatorNodeTerminateAndReplace, and new style upgrade

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/minikube.py, sdcm/k8s_configs/operator.yaml
https://trello.com/c/TNtx8EYY/2704-k8s-adopt-upgrade-to-the-new-logic
Depends on https://github.com/scylladb/scylla-cluster-tests/pull/3007
=> K8s no reboot on upgrade

sdcm/nemesis.py
=> fix(set_last_node_as_target): fix it for rack case

jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile, mgmt_cli_test.py, sdcm/mgmt.py, test-cases/manager/manager-repair-control.yaml
=> test(manager): Test manager repair control

jenkins-pipelines/jepsen.jenkinsfile, jepsen_test.py, sdcm/logcollector.py, sdcm/remote/remote_base.py, sdcm/send_email.py, sdcm/utils/common.py
Trello: https://trello.com/c/Kuxv3DRf/2619-jepsen-collect-logs
=> test(jepsen): collect Jepsen logs

sdcm/report_templates/results_upgrade.html, sdcm/send_email.py, upgrade_test.py
Trello: https://trello.com/c/mglPChYW/2413-upgrades-include-the-target-version-to-email-report
=> improvement(upgrade_test): add new_version/new_scylla_repo to email

vars/operatorPipeline.groovy
=> fix(vars/operatorPipeline.groovy): tweak defaults

sdcm/utils/remotewebbrowser.py
https://trello.com/c/6IrK5eh4/2725-address-badhostkeyexception-issue
=> fix(web_driver_docker_client): don't fail on BadHostKeyException

sdcm/k8s_configs/operator.yaml
https://trello.com/c/NTEPnatZ/2729-k8s-minor-major-upgrades-endup-in-panic-invalid-memory-address-or-nil-pointer-dereference
=> fix(operator.yaml): update it with modern CRD

sdcm/report_templates/results_issue_template.html
Add placeholder for issue description
=> fix(issue template): Improve issue template

jenkins-pipelines/upgrade-major-scylla-k8s-gke.jenkinsfile
=> feature(k8s-upgrade-pipelines): Add major upgrade pipeline and add defaults

sdcm/report_templates/results_issue_template.html, sdcm/report_templates/results_upgrade.html
Error: inja2.exceptions.TemplateSyntaxError: unexpected '}'
Also small adjustment in results_issue_template.html
=> fix(report template): rendering of results_upgrade.html failed

sdcm/cluster.py
=> Offline install fix

sdcm/nemesis.py
https://trello.com/c/WAdc8VYw/2742-addremoveracknemesis-address-cant-allocate-node-from-rack-1-to-run-nemesis-on
=> fix(AddRemoveRackNemesis): make it decommission seed nodes

sdcm/cluster_k8s/gke.py, sdcm/utils/k8s.py
https://trello.com/c/IXgcl7D0/2730-gke-address-gke-api-connection-resets
=> fix(cluster_k8s): workaround GKE api proxy resets on node add/remove

sdcm/nemesis.py
=> fix(nemesis): tune method name to disable it

sdcm/nemesis.py
Working on kubernetes terminate/replace nemesis I have lost last commit during rebase.
As result some of nemesis are not working properly.
=> fix(nemesis): recover lost commit, fixing operator nemesis

vars/artifactsPipeline.groovy
Currently we have a timeout 30 minutes for artifact-test, the time to
wait the available builder is also included.
This patch moved the original time only for the test itself, and add
30 minutes for waiting builder.
18:33:56  Timeout set to expire in 30 min
18:33:56  [Pipeline] {
18:33:56  [Pipeline] stage
18:33:56  [Pipeline] { (Run SCT stages) (hide)
18:33:56  [Pipeline] script
18:33:56  [Pipeline] {
18:33:56  [Pipeline] parallel
18:33:56  [Pipeline] { (Branch: )
18:33:57  [Pipeline] node
18:34:12  Still waiting to schedule task
18:34:12  Waiting for next available executor on ‘gce-sct-builders’
18:46:10  Running on gce4-qavpc in /jenkins/slave/workspace/scylla-4.3/art...
11:51:11  [Pipeline] {
11:51:11  [Pipeline] timeout
11:51:11  Timeout set to expire in 1 hr 0 min
11:51:11 …
=> fix(artifactsPipeline.groovy): extend the timeout to wait the builder

test-cases/longevity/longevity-ycsb-a-100M.yaml, test-cases/longevity/longevity-ycsb-a-10M.yaml, test-cases/longevity/longevity-ycsb-a-1M.yaml
=> fix(trailing-whitespace): on ycsb test cases

sdcm/nemesis.py
saw a case where BlockNetwork finished, and immediately after
it ClusterHealthValidator run (and failed) because it takes
few seconds to gossip to mark the node as UN again, making the
test to fail.
Now, this nemesis will wait for all nodes to be UN before
finishing the nemesis, and allowing ClusterHealthValidator
to run on a clean cluster.
=> improvement(network nemesis): wait nodes UN before end of nemesis

sdcm/cluster.py
=> Backport 4.3: Offline install fix

sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/utils/remote_logger.py, vars/artifactsPipeline.groovy
=> Additional Backport: Offline install fix 4.3

sdcm/logcollector.py
logs collected by SCT.
It was asked in by a developer about this value, but
we didn't save it, hence improving logcollector.
=> improvement(logcollector): add io-properties.yaml to

corrupt_then_rebuild_test.py, docs/new-hydra-commands.md, docs/new-test-configuration.md, install-prereqs.sh, mgmt_cli_test.py, multiple_dc_test.py, performance_regression_test.py, performance_regression_user_profiles_test.py, sdcm/tester.py, sdcm/wait.py, sla_per_user_system_test.py, test_lib/sla.py
=> fix(trivial cleanup): cleanup remaining avocado words

sdcm/sct_config.py, sdcm/tester.py, sdcm/utils/common.py
This backend if for supporting running SCT ontop of scylla-cloud in GCP.
Ref: https://trello.com/c/jTyatafX
=> feature(gce-siren): introducing a new backend

jenkins-pipelines/longevity-scylla-operator-3h-gke-add-remove-rack.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-cluster-rolling.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-grow-shrink.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-replace.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-stop-start.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-decommission-add.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-recover.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-replace.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-gke.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-minikube.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-basic-3h-gke.jenkinsfile
=> fix(scylla-operator jenkins): increase timeout

configurations/audit.yaml, jenkins-pipelines/longevity-10gb-3h.jenkinsfile, jenkins-pipelines/longevity-200gb-48h.jenkinsfile, jenkins-pipelines/longevity-50gb-4days.jenkinsfile, jenkins-pipelines/longevity-counters-3h.jenkinsfile
Ticket: https://trello.com/c/hw2VjCaj/2746-enable-auditing-in-the-regular-longevities-of-enterprise
Enabled audit for 2 short and 2 long longevity jobs.
=> enabled audit for 4 longevity jobs

sdcm/nemesis.py
Due to the terminated node, the first repair after the termination is a 'best effort repair'.
Because of that, the first repair will cause repair error events to rise, and as such I ignored such
events in this pr.
Github URL: https://github.com/scylladb/scylla-cluster-tests/pull/3109
=> fix(TerminateAndRemoveNodeMonkey): added event filter for repair errors

sdcm/nemesis.py
nemesis to be fixed by https://trello.com/c/Ru0T9Nmu/1239-fix-validatehintedhandoff-nemesis
Signed-off-by: Shoshan Dagany <shoshan.dagany@scylladb.com>
=> fix(nemesis) disable ValidateHintedHandoffShortDowntime until fixed

defaults/k8s_gke_config.yaml
=> fix(k8s_gke_config): update gke cluster version

jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile
=> Rolling upgrade ubuntu 18 with ldap enabled 2020.1

jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile, sdcm/tester.py, sdcm/utils/ldap.py, vars/rollingUpgradePipeline.groovy
the file was created on master, and once backported
to branch-2020.1, it didn't work.
here fixing it to make it work.
=> fix(rolling upgrade file): fit it branch-2020.1

sdcm/utils/latency.py
a similar issue was fixed recently, and this is
the same case of #3132.
=> fix(latency): prometheus using public ip is failing

defaults/k8s_gce_minikube_config.yaml, defaults/k8s_gke_config.yaml, defaults/test_default.yaml, jenkins-pipelines/longevity-scylla-operator-3h-gke-repair.jenkinsfile, mgmt_cli_test.py, mgmt_upgrade_test.py, sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/gke.py, sdcm/cluster_k8s/minikube.py, sdcm/k8s_configs/manager.yaml, sdcm/mgmt/__init__.py, sdcm/mgmt/cli.py, sdcm/mgmt/common.py, sdcm/mgmt/operator.py, sdcm/nemesis.py, sdcm/sct_config.py, sdcm/tester.py, sdcm/utils/remote_logger.py, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-repair.yaml, test-cases/scylla-operator/longevity-scylla-operator-basic-3h-gke.yaml
https://trello.com/c/M1sCKVWL/2590-k8s-mgmtrepairkubernetes
=> K8s repair task

defaults/k8s_gce_minikube_config.yaml, defaults/k8s_gke_config.yaml, jenkins-pipelines/longevity-scylla-operator-3h-gke-backup.jenkinsfile, sdcm/cluster_k8s/__init__.py, sdcm/nemesis.py, sdcm/tester.py, test-cases/scylla-operator/longevity-scylla-operator-3h-gke-backup.yaml
https://trello.com/c/Kxd88yYc/2682-k8s-mgmtbackupkubernetes
Depends on https://github.com/scylladb/scylla-cluster-tests/pull/3012
=> K8s mgmt backups

sdcm/cluster.py
=> fix(wait_for_init): update db binary/package before node setup

defaults/k8s_gce_minikube_config.yaml, defaults/k8s_gke_config.yaml, defaults/severities.yaml, defaults/test_default.yaml, docs/configuration_options.md, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/gke.py, sdcm/sct_config.py, sdcm/sct_events/health.py, sdcm/tester.py, sdcm/utils/k8s.py
https://trello.com/c/gNpWJWu8/2663-k8s-monitoring-stack-testing-automation
=> feature(cluster_k8s): deploy test monitoring in k8s

sdcm/cluster.py, test-cases/artifacts/docker.yaml
=> Two trivial fixes: a version update and a typo fix

sdcm/nemesis.py
since it terminates node in disruptive manner.
=> fix(nemesis.py): Set TerminateAndRemoveNodeMonkey disruptive

sct.py, vars/artifactsPipeline.groovy, vars/byoOperatorPipeline.groovy, vars/operatorPipeline.groovy, vars/rollingUpgradePipeline.groovy
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/3185
=> fix(clean-resources): assign backend

test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml
=> fix(50gb-3days): fixed the value of the user_prefix

sdcm/cluster_k8s/__init__.py
https://trello.com/c/TEUib76b/2975-k8s-checkkubernetesmonitoringhealth-can-fail-the-nemesis-thread-if-remote-ip-is-not-accessible
=> fix(check_kubernetes_monitoring_health): make it don't fail the test if it can't reach prometheus

jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
=> refactor(manager-upgrade): changed base version to 2.2

configurations/alternator/streams-with-nemesis.yaml, sdcm/cluster.py, sdcm/kcl_thread.py, test-cases/longevity/longevity-alternator-streams-100gb-4h.yaml
=> Stream with nemesis

sdcm/cluster_k8s/__init__.py
Stopping and starting of Scylla in containers must be done
using "supervisorctl" bin, not "systemctl".
The reason is absence of the "d-bus".
Without this fix we get following error trying to run "stop-start scylla" test cases:
```
2021-02-07 09:13:20.775: (DisruptionEvent Severity.ERROR): type=StopStartService subtype=end node=Node sct-cluster-us-east1-b-us-east1-2 [10.67.242.178 | 10.67.242.178] (seed: False) duration=11 error=Encountered a bad command exit code!
Command: 'systemctl stop scylla-server.service'
Exit code: 1
Stdout:
...
Stderr:
Failed to get D-Bus connection: Operation not permitted 
```
=> fix(scylla-stop-start-on-k8s): improrer commands were used

sct.py, sdcm/report_templates/results_jepsen.html, sdcm/utils/jepsen.py
Trello: https://trello.com/c/fWX2Og0o/2721-jepsen-add-command-for-hydra-investigate-to-run-web-server-with-jepsen-results
=> feature(jepsen): add hydra command to run web server with Jepsen results

sct.py, sdcm/microbenchmarking.py, sdcm/report_templates/results_base.html, sdcm/report_templates/results_base_custom.html, sdcm/report_templates/results_base_new.html, sdcm/report_templates/results_gemini.html, sdcm/report_templates/results_issue_template.html, sdcm/report_templates/results_latency_during_ops.html, sdcm/report_templates/results_microbenchmark.html, sdcm/report_templates/results_performance.html, sdcm/results_analyze/__init__.py, sdcm/send_email.py, sdcm/tester.py
improvement(test_latency_with_nemesis): display events to email report
to improve understanding the email report, adding now
the events (like we have in the longevity tests) to
be able to identify easier failures or potential issues
in the test from the email report.
=> improvement(test_latency_with_nemesis): display events to email report

sdcm/logcollector.py, sdcm/utils/common.py
Trello: https://trello.com/c/BhTRvVkR/2216-collect-logs-from-cloud-manager
Open this PR instead of #3169
=> feature(siren): collect Siren Manager logs

sdcm/ycsb_thread.py
since we are working with docker, we should be using docker's
`--cpuset-cpu` flag for pinning the stress command to one cpu
=> fix(ycsb_thread): taskset is broken when using `stress_multiplier`

sdcm/cluster.py
fixes https://github.com/scylladb/scylla-pkg/issues/1922
Note: possibly more similar fixes may be required for other used apt commands like for upgrades.
=> fix(cluster.py): Remove apt-get install deprecated option of --force-yes

defaults/test_default.yaml, docs/configuration_options.md, sdcm/cluster.py, sdcm/sct_config.py
Trello: https://trello.com/c/cvxqFlb1/2989-7589-the-setup-utility-can-now-configure-rsyslog-this-integrates-with-scylla-monitoring-and-is-lighter-weight-than-most-log-coll
=> feature(monitoring): add scylla_rsyslog_setup parameter

test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
Trello: https://trello.com/c/cvxqFlb1/2989-7589-the-setup-utility-can-now-configure-rsyslog-this-integrates-with-scylla-monitoring-and-is-lighter-weight-than-most-log-coll
=> feature(rsyslog): enable scylla_rsyslog_setup for 200gb job

sdcm/report_templates/results_base.html, sdcm/report_templates/results_issue_template.html, sdcm/send_email.py, sdcm/tester.py
To the base html report and issue template.
https://trello.com/c/gnUnGMFb/2956-add-kernel-version-to-the-email-report-and-the-issue-template
=> improvement(send_email): add kernel version info

sdcm/nemesis.py
https://github.com/scylladb/scylla/commit/d3a5814f4fd0ef80f3dbfde4095eb11feb05745a
New nemesis: perform schema recalculation by running 'nodetool resetlocalschema'
'resetlocalschema' option was enabled by the 
https://github.com/scylladb/scylla-tools-java/commit/142f517a232f7536eaa95ce1a8f6dd3435f9f990
But it's still not in the ami. This is the reason that this PR is not ready for review - I need to test it
=> feature(resetlocalschema): run 'resetlocalschema'

jenkins-pipelines/feature-ldap-authorization-longevity-50gb-3days.jenkinsfile
will run longevity-50gb-3days test with
LDAP authorization enabled.
=> test(ldap authorization): add new test

sdcm/tester.py
=> fix(email-report): show correct GCE instance type in the email

sdcm/utils/common.py
=> feature(k8s logs): Add k8s logs to the email report

sdcm/nemesis.py
in this PR, wasn't taken into account the
"new remoter" feature of accessing a remote
file (that is not part of branch-2020.1).
this current commit changes that commands
that are not present.
Fixes #3273
=> fix(nemesis.py): fix backport PR-3253

sdcm/cluster_gce.py
Failure of GCE instance creation with error 'Instance failed to start due to preemption' may happen
when spot instance has been created but was preempted. In this case the instance is stopped, not
destroyed. We check if the instance in the resources list. If the instance is still in the list -
destroy it. But we received situation when destroying was called, the instance already was removed.
So destroying failed with ResourceNotFoundError: notFound
Add 'try - except' to destoy call
=> fix(gce create instance): cover destroy gce instance failure in case preemption

mgmt_cli_test.py, sdcm/cluster.py
=> config the monitor to show data in the manager dashboard

defaults/test_default.yaml, docs/configuration_options.md, internal_test_data/multi_region_dc_test_case.yaml, mgmt_upgrade_test.py, sdcm/cluster.py, sdcm/sct_config.py, test-cases/manager/manager-regression-gce.yaml, test-cases/manager/manager-regression-ipv6.yaml, test-cases/manager/manager-regression-multiDC-set-distro.yaml, test-cases/manager/manager-repair-control.yaml, test-cases/manager/manager-repair-intensity-multiple-repaired-nodes.yaml, test-cases/manager/manager-repair-intensity-single-repaired-nodes.yaml, test-cases/upgrades/manager-upgrade.yaml
=> Fixing manager upgrade failures

jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile, jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
=> refactor(manager): changed scylla version to 4.3

jenkins-pipelines/longevity-scylla-operator-3h-eks-add-remove-rack.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks-backup.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks-cluster-rolling.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks-grow-shrink.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks-repair.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks-replace.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks-stop-start.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks-terminate-decommission-add.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks-terminate-recover.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks-terminate-replace.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-3h-eks.jenkinsfile, jenkins-pipelines/longevity-scylla-operator-basic-3h-eks.jenkinsfile
=> fix(eks pipelines): Set default parameters

jenkins-pipelines/manager/centos-manager-backup-gce-1tb.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
=> refactor(manager): Changed post behavior to destroy

sdcm/fill_db_data.py
For the moment upgrade tests work only if base version is 4.4+
But scylla-operator cannot use latest scylla versions due to following
issue:
- https://github.com/scylladb/scylla/issues/8032
So, handle version diff correctly for the 'null values' and
'sorting order using secondary indexes' features adding additional
set of queries for old versions with proper skip condition.
=> fix(upgrade): Allow upgrade on versions older than 4.4

sdcm/cluster.py
SnapshotOperation failed during longevity-multikeyspaces-60h test on snapshot validation.
The issue that in this test there are a 1000 ks and
'sdcm.cluster.BaseCluster.get_any_ks_cf_list' method didn't fetch all data.
Need to change session.execute to PageFetcher.fetch_all
=> fix(get_any_ks_cf_list): use PageFetcher.fetch_all instead session.execute

sdcm/cluster.py
Fixes following error that was introduce in #3280 :
Failed to receive SMP from SCYLLA_ARGS when test runs with nonroot user:
Command: 'grep ^SCYLLA_ARGS= /etc/sysconfig/scylla-server'
Exit code: 2
Stdout:
Stderr:
grep: /etc/sysconfig/scylla-server: No such file or directory
=> fix(nonroot user tests): get SMP from SCYLLA_ARGS

unit_tests/test_utils_common.py
Line assert os.path.exists(os.path.join(update_db_packages, text.txt))
depended on the existance of the text.txt
Fixes:
```
19:15:31  =================================== FAILURES ===================================
19:15:31  _________________ TestDownloadDir.test_update_db_packages_gce __________________
19:15:31  
19:15:31  self = <unit_tests.test_utils_common.TestDownloadDir testMethod=test_update_db_packages_gce>
19:15:31  
19:15:31      def test_update_db_packages_gce(self):
19:15:31          sct_update_db_packages = 'gs://scratch.scylladb.com/sct_test/'
19:15:31      
19:15:31          self.clear_cloud_downloaded_path(sct_update_db_packages)
19:15:31      
19:15:31          def touch_file(**kwargs):
19:15:31              Path(kwargs["destination_path"]).touch()
19:15:31 …
```
=> fix(test_update_db_packages_gce): remove dependency on the remote bucket contents

mgmt_upgrade_test.py
Due to https://github.com/scylladb/scylla-manager/issues/2492,
we've decided to rearrange the order of the tests, so that the snapshots of
the paused backup snapshots would not be purged (deleted) while said backup
is paused.
=> fix(manager-upgrade): changing test order

vars/getCloudProviderFromBackend.groovy
since on the first time some of the jobs are trigger, it doesn't have a backend define
and this new code doesn't let the whole pipeline to be loaded.
```
18:40:49  java.lang.NullPointerException: Cannot invoke method trim() on null object
18:40:49  	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
18:40:49  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
18:40:49  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
18:40:49  	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
18:40:49  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
18:40:49  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCa …
```
=> fix(getCloudProviderFromBackend): not fail with there no backend defined

sdcm/cluster.py, sdcm/cluster_docker.py, sdcm/db_stats.py, sdcm/remote.py, sdcm/results_analyze.py
=> Fixes and backports for perf-v8 branch

sdcm/logcollector.py
=> improvement(scylla-bench): collect logs at the end of the test

longevity_lwt_test.py
Data validator has to be run when no nemesis running
In case parallel nemesis test it maybe that when one nemesis is finished, another nemesis
continues to run. Don't run data validator in case parallel nemesis.
=> fix(data validator): Disable DataValidator for LWT test with parallel nemesis

longevity_lwt_test.py
Issue represented by https://github.com/scylladb/scylla-cluster-tests/pull/3375:
longevity-lwt-3h-test failed in branch-2020.1 as 'ignore_mutation_write_errors'
function doesn't exist in this branch.
https://jenkins.scylladb.com/job/enterprise-2020.1/job/longevity/job/longevity-lwt-3h-test/28/:
```
021-04-09 11:32:57.820: (TestFrameworkEvent Severity.ERROR), source=LWTLongevityTest.test_lwt_longevity (longevity_lwt_test.LWTLongevityTest)() message=Traceback (most recent call last):
File "/home/jenkins/slave/workspace/enterprise-2020.1/longevity/longevity-lwt-3h-test/scylla-cluster-tests/longevity_lwt_test.py", line 56, in test_lwt_longevity
with ignore_mutation_write_errors():
NameError: name 'ignore_mutation_write_errors' is not defined
```
=> [branch-2020.1] fix(lwt longevity): 'ignore_mutation_write_errors' function doesn't exist in 2020.1

sdcm/nemesis.py
These 2 methods have very little difference in it's logic.
So, remove such code duplication by squashing these 2 methods into the single method adding one more parameter.
=> refactor(kubernetes): squash set_target_node and set_last_node_as_target

test-cases/artifacts/centos7.yaml, test-cases/artifacts/centos8.yaml, test-cases/artifacts/debian10.yaml, test-cases/artifacts/debian9.yaml, test-cases/artifacts/oel76.yaml, test-cases/artifacts/oel81.yaml, test-cases/artifacts/ubuntu1604.yaml, test-cases/artifacts/ubuntu1804.yaml, test-cases/artifacts/ubuntu2004.yaml
=> backport scylla_mgmt_agent_repo fix to branch-4.5

sdcm/nemesis.py
=> improvement(memory_stress): support stress-ng installation on Ubuntu

unit_tests/test_cluster.py
The unittest can't pass sometimes because of the delay in writing events
to the log file.
This patch added a 0.1s sleep before checking the events to make it
pass.
=> fix (unittest): workaround the fail in test_search_cdc_invalid_request_2021_1

data_dir/scylla-dash-per-server-nemesis.master.json, sdcm/logcollector.py, sdcm/nemesis.py, sdcm/report_templates/results_reactor_stall_events_list.html, sdcm/results_analyze/__init__.py, sdcm/sct_events/__init__.py, sdcm/sct_events/database.py, sdcm/sct_events/file_logger.py, sdcm/utils/latency.py, unit_tests/test_events.py, unit_tests/test_sct_events_database.py
=> Latency tracker fix report values

data_dir/scylla-dash-per-server-nemesis.master.json, sdcm/logcollector.py, sdcm/nemesis.py, sdcm/report_templates/results_reactor_stall_events_list.html, sdcm/results_analyze/__init__.py, sdcm/sct_events/__init__.py, sdcm/sct_events/database.py, sdcm/sct_events/file_logger.py, sdcm/utils/latency.py, unit_tests/test_events.py, unit_tests/test_sct_events_database.py
=> Branch perf v10 ubuntu base image

jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile, jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
=> refactor(manager-tests): changed scylla_version from master:latest to 4.4

test-cases/artifacts/oel81.yaml
=> fix(artifact oel81): fix user prefix

vars/perfRegressionParallelPipeline.groovy
didn't pay attention, previous PR is missing quotes
and if failed.
=> fix(typo on pipeline): missed quotes in the pipeline params

configurations/manager/debian10.yaml, configurations/manager/debian9.yaml, configurations/manager/ubuntu16.yaml, configurations/manager/ubuntu18.yaml, configurations/manager/ubuntu20.yaml, jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile , jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile , jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile, sdcm/cluster.py, sdcm/mgmt/cli.py
(backport of https://github.com/scylladb/scylla-cluster-tests/pull/3297)
=> Moving to 2020

sdcm/nemesis.py
An 4.3.x workaround for issue:
https://github.com/scylladb/scylla/issues/6155
filtering out this message:
"Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE."
+ fix previous backported commit compatibility issue: (db_event=DatabaseLogEvent.RUNTIME_ERROR)
=> refactor(nemesis.py): Filter out paxos operation timeout on node restart

sdcm/cluster.py, sdcm/nemesis.py, sdcm/utils/ldap.py
creating a new LDAP docker container and running
commands against it. Adding here a command that will
wait for the container `wait-process`, giving us time
to start adding entries to it when the LDAP server is
ready to get it.
THIS IS A BACK PORT PR TO branch-2020.1 FROM ORIGINAL PR #3313
=> fix(configure_ldap): there is a race condition between

configurations/ldap-authenticator.yaml, configurations/ldap-authorization-and-authentication.yaml, jenkins-pipelines/longevity-100gb-4h-ldap-auth.jenkinsfile, jenkins-pipelines/longevity-10gb-3h-ldap-auth.jenkinsfile, sdcm/cluster.py, sdcm/nemesis.py, sdcm/sct_config.py, sdcm/tester.py, sdcm/utils/common.py, sdcm/utils/ldap.py
Ticket: https://trello.com/c/qr1W8k1A/2292-ldap-sasl-authentication
This PR backport sasl-authentication patches, it contains two PRs.
- https://github.com/scylladb/scylla-cluster-tests/pull/3120
- https://github.com/scylladb/scylla-cluster-tests/pull/3399
=> Saslauth backport 2021.1

jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
=> refactor(manager-upgrade): changed base manager version from 2.2 to 2.3

sdcm/nemesis.py
if prepare_saslauthd is not set, we should not even start the
nemesis, but to skip it with "UnsupportedNemesis".
The skip was already in there, but after few decisions were
taken, and few commands were run.
=> fix(skip nemesis before running part of it): when no prepare_saslauthd

gemini_test.py, jenkins-pipelines/gemini-3h-ics-cdc-with-nemesis.jenkinsfile, test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
Added new test to run gemini with enabled cdc and ics
Additionaly, run cdcreader used to read cdc log table
=> test(gemini-ics-cdc): New test gemini + cdc + ics

defaults/k8s_eks_config.yaml, sdcm/tester.py
Also, fix setting of monitoring nodes number for this backend.
=> improvement(k8s-eks): enable K8S monitroing installation

sdcm/utils/k8s.py
Right now, if we try to recreate K8S scylla node we fail on the attempt to create already existing K8S LB service which just doesn't get deleted when it's target node/pod gets deleted.
So, consider this situation and delete such services if exist prior to creation of new one.
=> fix(k8s-eks): delete K8S LB service if exists recreating scylla nodes

sdcm/utils/latency.py
while we are seeing in some reports the avg being
bigger than the max of a sequence, we made few
changes to the collect_latency function, as few
things were changed around (SCT, Scylla core and others).
=> improvement(latency.py): improved the collect_latency

vars/rollingOperatorUpgradePipeline.groovy
=> fix(k8s-eks): add send_email step in rollingOperatorUpgradePipeline

test-cases/longevity/longevity-5000-tables.yaml, test-cases/longevity/longevity-multi-keyspaces.yaml
=> Change loader for 5k tables test - newest loader doesn't work for this test

sdcm/cluster.py
Right now we get "/bin/bash: ss: command not found" error in some cases
running tests on K8S backends with scylla 4.4.x which doesn't have "iproute" package preinstalled.
So, check "ss" binary presence before using it and install if absent.
=> fix(port-availability-checks): make sure that ss binary is installed

sdcm/cluster_k8s/__init__.py
It happens that minio takes more than 5 minutes and we already have
10m as part of cmd call, but our 'kubectl' wrapper has 5m timeout.
So, align these 2 for the minio deployment.
Also, define minio namespace in one place.
=> fix(k8s-gke): use 10m timeout for minio pod readiness kubectl call

vars/perfRegressionParallelPipeline.groovy
the url was changed today, hence tests stopped working
and now updating the url in SCT to have tests
running again.
=> fix(mgmt_agent_repo): url changed

jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile, jenkins-pipelines/rolling-upgrade-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile
=> fix(rolling upgrade): Change base version of 4.5 to 4.4

jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile, jenkins-pipelines/rolling-upgrade-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile
=> fix(rolling upgrade): Change base version for master to 4.5

defaults/test_default.yaml, test-cases/artifacts/amazon2.yaml, test-cases/artifacts/ami.yaml, test-cases/artifacts/centos7.yaml, test-cases/artifacts/centos8.yaml, test-cases/artifacts/debian10.yaml, test-cases/artifacts/debian9.yaml, test-cases/artifacts/docker.yaml, test-cases/artifacts/gce-image.yaml, test-cases/artifacts/oel76.yaml, test-cases/artifacts/oel81.yaml, test-cases/artifacts/rhel7.yaml, test-cases/artifacts/rhel8.yaml, test-cases/artifacts/ubuntu1604.yaml, test-cases/artifacts/ubuntu1804.yaml, test-cases/manager/manager-backup-1TB-gce.yaml
Changing to last promoted release
=> refactor(manager): Changed all manager repos to 2.3

jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-scylla-enterprise.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-basic-3h-eks-scylla-enterprise.jenkinsfile, jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-scylla-enterprise.jenkinsfile, jenkins-pipelines/operator/gke/longevity-scylla-operator-basic-3h-gke-scylla-enterprise.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-latency-eks.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-throughput-eks.jenkinsfile, sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/minikube.py, sdcm/tester.py, test-cases/performance/perf-regression-latency-500gb-30min.yaml, test-cases/performance/perf-regression.100threads.30M-keys.yaml, vars/perfRegressionParallelPipeline.groovy
Also add 'latency' and 'throughput' pipelines for EKS backend.
=> improvement(perf-tests): add possibility to run perf tests on K8S

sdcm/cluster.py, sdcm/tester.py
=> Fix check order sasl

sdcm/cluster_k8s/eks.py
ELB service is used now to allow monitoring and test runner nodes
access scylla nodes. It is not needed because we already use
host networking on scylla nodes/pods in addition to single region,
zone and VPC.
So, stop using ELB service and add security group to each network
interface of each scylla node that allows connections among
EKS nodes and any other node from the same VPC.
=> improvement(k8s-eks): stop using ELB service

upgrade_test.py
Copy to /etc/scylla dir require root previligies.
Change to sudo.
=> fix(upgrade_test): copy to /etc/scylla dir require sudo

sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/nemesis.py, sdcm/remote/local_cmd_runner.py, sdcm/utils/k8s.py, unit_tests/test_utils_k8s.py
https://trello.com/c/8rQRn4F1/3425-make-local-minikube-kind-cluster
=> Set of patches to make local minikube/kind work

sdcm/cluster_k8s/__init__.py
https://trello.com/c/8rQRn4F1/3425-make-local-minikube-kind-cluster
=> Set of patches to make local minikube/kind work #2

test-cases/longevity/longevity-5000-tables.yaml
ticket: https://trello.com/c/wfxdAsFz/3239-20211-longevity-5000-tables-test
The patchset reduced the workloads and switched to use SisyphusMonkey.
=> Configure adjust for longevity-5000-tables

jenkins-pipelines/createTestJobs.jenkinsfile, sct.py, utils/build_system/create_test_release_jobs.py, vars/artifactsPipeline.groovy, vars/createTestJobPipeline.groovy, vars/rollingUpgradePipeline.groovy
New job which allow to create test jobs
on jenkins for any branch and scylla version
=> ci(jenkins-pipeline): Create test jobs

sct.py, sdcm/sct_config.py, sdcm/sct_events/base.py, sdcm/tester.py, sdcm/utils/common.py, sdcm/utils/version_utils.py, unit_tests/test_config.py, utils/lint_test_cases.sh
https://trello.com/c/6GPbC7n6/3445-lint-test-cases-fails
This fix address following problems:
1. Linting instability due to the network issue
2. Poor performance. I.e. test takes 11-15 minutes to complete
3. Some linting failure due to the sending tuple to ParallelObject
4. Default max_events_severities results in Exception
Yaml lint test before fix: 11-15m, after fix: 40s
=> Fix linting

defaults/test_default.yaml, jenkins-pipelines/longevity-1tb-7days-gce.jenkinsfile, sdcm/cluster.py
=> Align manager master

README.rst
https://trello.com/c/bkXuOX2T/3514-add-readme-that-explains-how-to-run-a-k8s-functional-test-and-how-to-develop-and-debug-one
=> improvement(function_test): add information to README.rst

mgmt_cli_test.py, sct.py, sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/cluster_docker.py, sdcm/cluster_gce.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/gke.py, sdcm/cluster_k8s/iptables.py, sdcm/cluster_k8s/mini_k8s.py, sdcm/db_stats.py, sdcm/nemesis.py, sdcm/sct_config.py, sdcm/sct_events/events_analyzer.py, sdcm/test_config.py, sdcm/tester.py, sdcm/utils/rsyslog.py, test-cases/PR-provision-test-docker.yaml, test-cases/PR-provision-test.yaml, unit_tests/lib/events_utils.py, unit_tests/test_decode_backtrace.py, unit_tests/test_seed_selector.py
https://trello.com/c/K9BLCYcp/688-refactor-separate-provision-logic-from-test-logic
=> Set of changes to prepare tester.py to move provision code out 

artifacts_test.py, defaults/aws_config.yaml, defaults/gce_config.yaml, defaults/k8s_eks_config.yaml, defaults/k8s_gce_minikube_config.yaml, defaults/k8s_gke_config.yaml, defaults/test_default.yaml, docs/configuration_options.md, jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile, mgmt_cli_test.py, mgmt_upgrade_test.py, sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/keystore.py, sdcm/logcollector.py, sdcm/mgmt/cli.py, sdcm/mgmt/operator.py, sdcm/nemesis.py, sdcm/paths.py, sdcm/remote/remote_file.py, sdcm/sct_config.py, sdcm/tester.py, sdcm/utils/common.py, unit_tests/test_microbenchmarking.py, vars/managerPipeline.groovy
Trello: https://trello.com/c/QsEXbwdg/2939-manager-24-test-backup-with-azure
=> [manager-2.4] feature(backup): azure blob backend

sdcm/nemesis.py
When sct publishes data to elastic search, there's the possibility that
an exception will occur (namely a timeout). When such error takes place
the nemesis thread will fail, and no new nemeses will start in this run
(see fde13648-baf4-4e37-b401-97e5a2d658f2).
Therefore, I surrounded the elastic search publishing in sct with a try clause.
=> fix(nemesis.py): Surround elasticsearch publishing with a try clause

sdcm/nemesis.py
Backport fix "fix(removenode_filter_issue): the repair running"
from master to filter the repair issue during disrupt_remove_node_then_add_node
=> fix(nemesis.py): Backport fix for filter repair issue

sdcm/nemesis.py
The issue that if we have one seed node, we first terminate it and
then try to add new node, but it will failed, because no seeds left in cluster.
As a solution,
1.check if node is single seed
2.if yes, then choose random node and set it as seed
3.terminate target seed node and replace with new one.
4.leave cluster as is with seed node choosen on step 2
related to
https://github.com/scylladb/scylla-cluster-tests/pull/3651
=> fix(terminateandreplace): choose new seed before termination old one

performance_regression_row_level_repair_test.py, sdcm/cluster.py, sdcm/cluster_docker.py, sdcm/cluster_k8s/__init__.py, sdcm/sct_config.py, test-cases/performance/perf-row-level-repair-1TB.yaml
Addresses following problems:
1. Stop installing scylla-bench when it is not needed
2. Fix scylla-bench installation issue
3. Prop up golang version
=> Fix scylla bench

sdcm/nemesis.py
Ticket: https://trello.com/c/lFhSinLV/1790-redefine-limited-monkey-using-an-attribute
Currently we have a fixed list of nemesis in LimitedChaosMonkey. This
patch changed it to filter the nemesis by the 'limited' attribute.
=> refactor(LimitedChaosMonkey): add an attribute to filter the nemesis

sdcm/cluster_k8s/__init__.py
For the moment we exclude more than 2 full CPU cores on scylla nodes explicitely and lion part of it stays idle forever.
So, calculate resource limits for scylla pods more accurate to reuse more resources.
=> fix(k8s-perf): reuse idle resources on scylla nodes

sdcm/cluster.py
Hard code s-b version and stop updating dependancies
=> fix(install_scylla_bench): get deps exact version as defined

sdcm/cluster_k8s/__init__.py
Currently, we have typo in ScyllaCluster CRD definition
where name for 'configmap' object which must store scylla config
is specified incorrectly:
- must be: scylla-config
- we have: scylla-confing
So, it leads to the situation where deployed Scylla Cluster just doesn't use our data.
So, fix it by making all the consumers use single global var to be sure there is no typo like this.
=> fix(kubernetes): reuse scylla-config we create

sdcm/logcollector.py, sdcm/monitorstack/ui.py
By default grafana dashboard reload data with 30s interval.
Sometimes it could bring that while panel has been loading
previous data, it starts load new version. The loadign element
continue to stay in Panel DOM structue and cause exception by timeout
1. Added ot dashboard url qs parameter &refresh=1d to avoid often
page refreshing
2. Added more panels to OververDashboard, to validate dashboard loading
3. Added additional exception by timeout, to get snapshot if some panel
don't have data loaded.
=> fix(GrafanaSnapshot): get snapshot even panel is not fully loaded

pylintrc, sdcm/sct_runner.py
=> Increase SCT Runner disk to 120gb for long runs

sdcm/utils/version_utils.py, unit_tests/test_version_utils.py
Addresses https://github.com/scylladb/scylla-cluster-tests/issues/3723
=> Fix get branch version

defaults/aws_config.yaml
=> fix(backup): use one bucket for multi-DC

sdcm/cluster_k8s/__init__.py
Operator-1.4 removes all custom changes to the Scylla statefulsets on each reconcile operation.
So, stop doing any custom updates to sub-ordinate objects of a ScyllaCluster and update it itself
if really needed.
=> [K8S] Do not make direct scylla statefulset updates

sdcm/utils/cloud_monitor/templates/base.html
=> improvement(cloud-monitor): add procedure link to cloud resources email

sdcm/k8s_configs/eks/scylla-node-prepare.yaml
Use the most recent image from proper docker hub repo.
=> fix(eks-k8s): update image for node-setup daemonset

sdcm/cluster.py, sdcm/monitorstack/__init__.py
=> fix(monitor): clearing UA.sh before the monitor starts

README.rst
https://trello.com/c/ZkKyPGKE/3612-fix-functional-test-docs
=> fix(README.rst): fix functional test docs

vars/byoLongevityPipeline.groovy
=> fix(byoLongevityPipeline): Added scylla_mgmt_agent_repo parameter

vars/byoLongevityPipeline.groovy
=> fix(byoLongevityPipeline): removed default scylla_mgmt_agent_repo

functional_tests/scylla_operator/conftest.py, sdcm/cluster_k8s/__init__.py
https://trello.com/c/Lr0Ebhy3/3644-fixfunctional-recover-nodes-number-properly
https://github.com/scylladb/scylla-cluster-tests/pull/3770
=> fix(functional): recover nodes number properly

defaults/test_default.yaml, docs/configuration_options.md, sct.py, sdcm/logcollector.py, sdcm/sct_config.py
=> Sct logs download separately

sdcm/cluster_k8s/__init__.py
Default log level for operator is '2'.
It is not enough for complex debug cases.
So, set it to '4' to have full set of details needed for
debugging of complex problems in operator.
=> improvement(kubernetes): use logLevel=4 for operator

jenkins-pipelines/artifacts-centos8-arm.jenkinsfile, jenkins-pipelines/artifacts-debian10-arm.jenkinsfile, jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile, sdcm/cluster.py, test-cases/artifacts/arm/centos8.yaml, test-cases/artifacts/arm/debian10.yaml, test-cases/artifacts/arm/ubuntu2004.yaml, vars/artifactsPipeline.groovy
ticket: https://trello.com/c/jUFWpe9G/3545-artifact-test-for-arm-centos8-ubuntu20-and-deb10
=> artifact-tests for arm

longevity_twcs_test.py, sdcm/kcl_thread.py, sdcm/mgmt/cli.py, sdcm/stress_thread.py, sdcm/utils/cloud_monitor/report.py
https://trello.com/c/TXLBplVY/3667-fix-linting-issues
=> Fix linting2

sdcm/cluster.py
https://trello.com/c/mqAc8Znc/3669-prometheus-data-not-collected
https://jenkins.scylladb.com/view/scylla-4.5/job/scylla-4.5/job/longevity/job/longevity-cdc-100gb-4h-test/33/consoleFull
```
06:42:15  'request': Number of retries exceeded!
06:42:18  Create prometheus snapshot [try #1]
06:42:55  'request': Number of retries exceeded!
06:43:03  Create prometheus snapshot [try #2]
06:43:41  'request': Number of retries exceeded!
06:43:49  'create_prometheus_snapshot': Number of retries exceeded!
06:43:49  Create prometheus snapshot failed 500 Server Error: Internal Server Error for url: http://13.48.26.227:9090/api/v1/admin/tsdb/snapshot.
06:43:49  Use prometheus data directory
06:43:49  /home/centos/sct-monitoring/scylla-monitoring-data
06:43:49 …
```
=> Prometheus data not collected on branch-4.5

sdcm/utils/distro.py
=> fix(distro): add support ubuntu 21.04

functional_tests/scylla_operator/conftest.py
s-o does not allow to remove racks
that is why cluster recover fails after test that creates a rack
fix cluster recover logic to preserve rack, but set members to 0
https://trello.com/c/bbqcfUyX/3684-functional-fix-cluster-recover-logic-for-cases-when-extra-rack-is-added
=> fix(conftet.py): fix cluster recover

sdcm/cluster_k8s/__init__.py
https://trello.com/c/sOeBi0sJ/3664-k8s-occasional-failure-on-installation-of-iproute
yum install -y iproute can fail due to the network issues
but if we download package first with retries and install it aterwards
it should not have such issue
=> fix(cluster_k8s): make iproute installation more stable

sdcm/cluster_k8s/mini_k8s.py
https://trello.com/c/RUTokIIb/3515-dont-download-kind-when-the-test-is-rerun-on-the-same-machine-useful-for-developing
Download kind and minikube into /var/tmp of the host file system
to make them persistent and use them from that path
=> fix(mini_k8s): make kind and minikube be persistent

sdcm/cluster_k8s/gke.py, sdcm/utils/k8s.py
https://trello.com/c/2hSNiP4j/3696-fix-gcloud-token-update
=> Fix gcloud

configurations/manager/200gb_dataset.yaml, jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile, mgmt_cli_test.py, sdcm/mgmt/cli.py, test-cases/manager/manager-regression-multiDC-set-distro.yaml
=> Manager backup feature with large dataset

sdcm/logcollector.py
This reverts commit f209c7ddea2365fe5afdeb1934a241758300332e.
=> Revert "fix(logcollector.py): Fixing collect logs for Sirenada run"

sdcm/utils/cloud_monitor/resources/instances.py
=> feature(cloud_monitor): use CloudTrail to find an owner of the instance

sdcm/nemesis.py, sdcm/utils/toppartition_util.py
nodetool toppartitions has new api, which allow to get toppartitions
data for several keyspaces or keyspaces and tables.
Add support for new syntax and api
Trello: https://trello.com/c/9Nyba2N0
=> feature(show_toppartition): Add check for new api of toppartition

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py
Trello: https://trello.com/c/tyKTNN3i/3703-tag-eks-pool-instances-with-relevant-sct-tags
=> improvement(tagging): add tags to k8s *NodePool objects

docker/env/hydra.sh, unit_tests/test_hydra_sh.py
https://trello.com/c/dbbXhevO/3714-implement-hydra-unittests
=> feature(hydra-tests): implement unitests for hydra

jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
=> fix(manager): switched mgmt repo to bionic file in bionic scenarios

sdcm/utils/docker_utils.py
=> improvement(build_container_image): log errors when build failed

defaults/severities.yaml, sdcm/cluster.py, sdcm/sct_events/health.py, unit_tests/test_sct_events_health.py
Trello: https://trello.com/c/8jqoo98f/3570-extend-checknodehealth-using-cluster-server-analysis-cli-diagnostic-command
=> New event type for Scylla Cloud server diagnostic

sdcm/cluster_k8s/__init__.py
For the moment, we always specify scylla agent config in the
ScyllaCluster CRD. But appropriate 'secret' gets created only when
Scylla manager gets installed. If not, we get following errors in
Scylla operator logs:
"Event occurred" object="scylla/sct-cluster" kind="ScyllaCluster"
apiVersion="scylla.scylladb.com/v1" type="Warning"
reason="InvalidManagerAgentConfig"
message="Can't gent agent token: can't get agent token:
can't get secret scylla/scylla-agent-config:
secret \"scylla-agent-config\" not found"
So, create this secret always properly populating it based on the
Scylla manager presence.
=> fix(kubernetes): always create scylla agent config

sdcm/sct_events/nodetool.py
=> fix(sdcm.sct_events.nodetool): pylint issue

sdcm/scylla_bench_thread.py
https://trello.com/c/9JKOduBs/3755-s-b-result-parsing-issue
S-b changed it's output we need to fix way we parse it to reflect these changes
=> fix(parse_bench_summary): fix result parsing

vars/jepsenPipeline.groovy
For the moment we run jepsen tests on GCE builder not using SCT-runner,
but all other steps such as 'collect logs' and 'cleanup resources'
are used from common groovy files which expect SCT runner presence.
It leads to constant failures of jepsen jenkins jobs.
So, just start using SCT runner for jepsen tests making whole job work correctly after it.
=> fix(jepsenPipeline): use SCT runner

sdcm/cluster_gce.py
We want our GCE cluster code to retry creating a node in case of bumping into resource limitations. The goal is to retry up to 3 times, with a 15 minutes backoff between retries. This PR abstracts the previous try / catch / retry code into a separate method in the `cluster_gce` module, and uses the `retrying` decorator for the retry logic. 
Trello task: https://trello.com/c/Xb4Aalnz
Jenkins run with 2 db nodes being created on GCE: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-byo-longevity-test/178/
=> improvement(cluster_gce): retry on create node error

jenkins-pipelines/longevity-100gb-4h-ebs-gp3.jenkinsfile, jenkins-pipelines/longevity-50gb-3days-ebs-gp3.jenkinsfile, jenkins-pipelines/longevity-large-partition-8h-ebs-gp3.jenkinsfile
Added new short,medium,long longevity tests with ebs volumes
=> test(longevity-4h-ebs): New longevity test with ebs volumes

functional_tests/scylla_operator/test_functional.py
Task: https://trello.com/c/WL1OT3DA/3583-check-that-startup-probe-must-exist-for-scylla-pods
Cover the issue: https://github.com/scylladb/scylla-operator/issues/476
Test verifys that Scylla pods have an startup probe
=> test(functional test): Check that Startup probe must exist for Scylla pods

sdcm/cluster.py
=> fix(cluster.py): fix annotation

sct.py, sdcm/cluster.py, sdcm/cluster_k8s/mini_k8s.py, sdcm/keystore.py, sdcm/remote/remote_file.py, sdcm/utils/docker_utils.py, unit_tests/test_remoter.py
Trello: https://trello.com/c/TJOJDWwC/3759-sometimes-sct-tests-dont-start-due-to-docker-toomanyrequests
To prevent toomanyrequests error login to the Docker Hub as scyllaqatest user.
=> improvement(docker): login to Docker Hub

jenkins-pipelines/operator/upgrade/upgrade-platform-k8s-eks.jenkinsfile, jenkins-pipelines/operator/upgrade/upgrade-platform-k8s-gke.jenkinsfile, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/cluster_k8s/mini_k8s.py, test-cases/scylla-operator/kubernetes-platform-upgrade.yaml, unit_tests/test_remoter.py, upgrade_test.py
Add upgrade k8s platform support for EKS and GKE backends.
=> feature(kubernetes): add upgrade k8s platform test

functional_tests/scylla_operator/libs/helpers.py, functional_tests/scylla_operator/test_functional.py
Fix 'test_orphaned_services_multi_rack' test by doing this:
- Add waiter for the services absence to avoid races of
absence assertion and service deletion.
- Add just one new member in a new rack instead of two because
we have just one additional K8S node for Scylla and one is
completely sufficient.
Fix 'test_orphaned_services_after_shrink_cluster' test by using
the same waiter as for 'test_orphaned_services_multi_rack'.
Remove 'test_orphaned_services_after_drain' as redundant.
This test doesn't cover the use case where we need to check svc absence
after scylla pods deletion. It performs check when pods exist.
Remove 'test_grow_shrink_cluster' test as duplicate of the
'test_orphaned_services_after_shrink_cluster' one.
=> fix(k8s-functional-tests): correctly check orphaned operator resources

functional_tests/scylla_operator/libs/helpers.py, functional_tests/scylla_operator/test_functional.py
Make 'test_ha_update_spec_while_rollout_restart' do not do redundant
Scylla cluster pods rollout by removing all the scylla-operator pods when we update Scylla spec.
Without redundant rollout test takes about 30 seconds, with the
redundant rollout test takes about 10 minutes and leaves DB cluster in rolling out state for other tests.
=> fix(k8s-functional): do not do redundant scylla rollouts

defaults/severities.yaml, defaults/test_default.yaml, docs/configuration_options.md, jenkins-pipelines/longevity-10gb-3h-nosqlbench.jenkinsfile, sdcm/nosql_thread.py, sdcm/sct_config.py, sdcm/sct_events/loaders.py, sdcm/stress_thread.py, sdcm/tester.py, test-cases/longevity/longevity-nosqlbench-3h.yaml
https://github.com/scylladb/scylla-cluster-tests/pull/3688
=> Introduce nosqlbench

.pre-commit-config.yaml
=> fix(pre-commit): excludes are regexps

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/mini_k8s.py
=> improvement(k8s-local): cache images to speed up cluster creation

functional_tests/scylla_operator/libs/helpers.py, functional_tests/scylla_operator/test_functional.py
Implements functional test for https://github.com/scylladb/scylla-operator/issues/718
=> test(k8s-functional): cover operator#718

sdcm/utils/gce_utils.py, vars/artifactsPipeline.groovy, vars/byoLongevityPipeline.groovy, vars/cdcReplicationPipeline.groovy, vars/getJenkinsLabels.groovy, vars/jepsenPipeline.groovy, vars/longevityPipeline.groovy, vars/managerPipeline.groovy, vars/perfRegressionParallelPipeline.groovy, vars/rollingUpgradePipeline.groovy, vars/runCleanupResource.groovy, vars/runCollectLogs.groovy, vars/runSctTest.groovy, vars/runSendEmail.groovy
https://trello.com/c/rxP8drlL/3501-support-1-more-region-in-gce-with-new-gce-runner
New sct builder had been created and registered to Jenkins.
This patch added support for artifact-test and upgrade-test to
use new GCE region.
=> feature(gce): support new region: us-west1

sdcm/nosql_thread.py
https://trello.com/c/3aK9uD0X/3895-add-documentation-for-nosqlbench
Add documentation for NoSqlBench
=> feature(nosqlbench): add documentation

jenkins-pipelines/hydra-show-jepsen-results.jenkinsfile
=> feature(Jenkins): a job for show-jepsen-results

sdcm/sct_runner.py
Trello: https://trello.com/c/Sf2IMrhM/3957-fix-gce-sct-runners-cleanup
=> fix(sct_runner): handle empty launch_time

sdcm/provision/scylla_yaml/auxiliaries.py
=> feature(scylla-yaml): support GoogleCloudSnitch

functional_tests/scylla_operator/test_functional.py
Add new K8S functional test where we check that all the operator images
in lots of places are of the same tag.
If it is not the same then we can get unexpected behavior which can
cause very tricky issues.
=> test(k8s-functional): make sure that operator images are of the same tag

sdcm/sct_runner.py
Trello: https://trello.com/c/tjnheBn3/4057-fix-cleanup-of-gce-sct-runners
- clean SCT runners w/ empty launch_time tag
- clean SCT runners w/ unparsable launch_time tag
- don't clean SCT runners w/ keep_action tag != terminate
=> fix(sct_runners): improve cleaning of GCE and Azure instances

sdcm/cluster_docker.py, unit_tests/test_utils_common.py
=> fix(pylint): Making pylint happy (and quiet)

performance_regression_test.py, sdcm/db_stats.py, sdcm/utils/latency.py
=> Latency with nemesis new index

sdcm/report_templates/results_latency_during_ops_short.html, sdcm/results_analyze/__init__.py
=> Latency during ops shorter report

sdcm/parallel_timeline_report/generate_pt_report.py, sdcm/parallel_timeline_report/templates/pt_report_template.html
Generator creates HTML report with parallel timeline chart based on data from raw_events.log file.
https://trello.com/c/gAa9R7B1/3235-events-timeline-poc
https://trello.com/c/o90EgAUn/3963-add-system-events-to-parallel-timelines-report
=> feature(parallel_timeline_report): implement pt report generator

jenkins-pipelines/longevity-200gb-48h-network-monkey.jenkinsfile
=> fix(network monkey longevity): set ip_ssh_connections to public

sdcm/utils/common.py
Without this change deleting each GKE cluster we leave orphaned
two following kinds of disks:
- 10Gb, created for MinIO service
- 10Gb, created for a Scylla which is dedicated for a Scylla Manager
These stay undeleted because it gets created dynamically and Google
doesn't delete it with deletino of a cluster.
So, do it ourselves, and delete all detached disks in the zone of
a deleted GKE cluster. 'All', because we cannot filter disks per
GKE cluster name.
=> improvement(gke-cleanup): delete orphaned disks deleting GKE clusters

mgmt_cli_test.py
https://github.com/scylladb/scylla-cluster-tests/issues/4096
=> fix(mgmt_cli_test): ubuntu fix

sdcm/nemesis.py
=> improvement(nemesis): run resharding nemesis on K8S

functional_tests/scylla_operator/test_functional.py
Task:
https://trello.com/c/OkmLsxou/3579-check-that-clusterfirstwithhostnet-dnspolicy-is-used-by-
scylla-operator
Check that 'ClusterFirstWithHostNet' DNSPolicy is used by Scylla cluster
=> test(functional): validate pods dnsPolicy

sdcm/provision/aws/provisioner.py, sdcm/provision/common/provisioner.py, sdcm/sct_provision/aws/cluster.py
https://trello.com/c/SL9O0bqD/4111-rename-guaranteed-nad-nonguaranteed
=> fix(provision): redo parameters naming

data_dir/scylla-dash-per-server-nemesis.master.json
Our dashboard format is two major version old, let's update it
It will enable to use annolist for "SCT Events" panel
https://trello.com/c/WPxXX1yF/3994-use-new-widget-panel-annotationlist-for-sct-events
=> Fix sct events panel

vars/longevityPipeline.groovy
Recently was added "provision resources" stage to the 'longevity'
pipeline. This stage silently fails if we use any non-AWS backend.
In such a case stage gets marked as 'SUCCESS', but silently marks
whole build as "FAILURE".
So, check the backend explicitely and skip this step completely avoiding
false negative results using non-supported backends.
Also, update post actions with more info about completed stages for better visibility.
=> fix(longevity-pipeline): do not run provision resources stage on non-AWS

docker/env/hydra.sh, sdcm/prometheus.py, unit_tests/test_hydra_sh.py
Fixes - https://github.com/scylladb/scylla-cluster-tests/issues/4068
https://trello.com/c/Zo8yKsWx/4150-rolling-upgrade-tests-are-failing-with-no-results-from-prometheus
=> prometheus.py: fix local ip calculation

sdcm/cluster_aws.py, sdcm/sct_provision/aws/instance_parameters_builder.py, sdcm/tester.py
=> Fix oracle

upgrade_test.py
https://trello.com/c/z2WCnCHa/4156-fixtesterpy-ignore-cdc-stream-errors
=> fix(tester.py): ignore cdc stream errors

defaults/test_default.yaml, sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/localhost.py, sdcm/provision/common/utils.py, sdcm/sct_config.py, sdcm/test_config.py, sdcm/tester.py, sdcm/utils/log_time_consistency.py, sdcm/utils/rsyslog.py, sdcm/utils/syslogng.py, unit_tests/test_cluster.py, unit_tests/test_scylla_yaml_builders.py, unit_tests/test_utils_common.py
=> introduce syslog-ng

sdcm/prometheus.py, sdcm/sct_events/base.py, sdcm/sct_events/continuous_event.py, sdcm/sct_events/database.py
https://trello.com/c/a9Nd8Jau/4225-fix-bugs-in-events
=> Fix events

sdcm/argus_test_run.py
=> fix(argus): make it work offline

docker/env/hydra.sh, sct.py, sdcm/sct_runner.py, sdcm/utils/docker_utils.py, utils/mocks/aws_mock.py
- Add 'hydra create-aws-mock' command
- Add 'hydra clean-aws-mocks' command
- Add '--aws-mock' option
- Do few optimizations of hydra.sh
=> feature(hydra): AWS Mock integration

sdcm/cluster_aws.py
=> fix(cluster_aws): remove unsed code

sct.py, sdcm/send_email.py, sdcm/utils/cloud_monitor/cloud_monitor.py, sdcm/utils/cloud_monitor/report.py
=> feature(cloud-monitor): last 7 days report for non qa users

install-prereqs.sh
=> fix(install-prereqs): add ubuntu support

sdcm/cluster_k8s/__init__.py
Latest Helm versions wrap values of "appVersion" field into quotes
to make yaml parser consider it always as string to avoid ambiguity.
Example 1: 1.0 may be considered as float
Example 2: 1234e10 as scientific notation.
Details: https://helm.sh/docs/topics/charts/#the-appversion-field
And operator-1.6-rc.0 started using Helm version that does it.
So, add support for it in our "get_operator_image" method which
we use in our K8S functional tests.
=> fix(helm-charts): add support for new format of appVersion fields

sdcm/cluster_k8s/__init__.py
Operator v1.6.0-rc.0 introduces changes to CRDs.
But Helm applies CRDs only if it is absent and not when
it is "update". So, to make operator work after upgrade
we should upgrade CRDs first before we run 'helm upgrade' command.
=> fix(operator): do proper upgrade using newest versions

sdcm/db_log_reader.py, sdcm/sct_events/database.py
=> Fix continues

jenkins-pipelines/artifacts-amazon2.jenkinsfile, jenkins-pipelines/artifacts-centos8-arm.jenkinsfile, jenkins-pipelines/artifacts-debian10-arm.jenkinsfile, jenkins-pipelines/artifacts-oel76.jenkinsfile, jenkins-pipelines/artifacts-oel81.jenkinsfile, jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile, jenkins-pipelines/nonroot-offline-install/artifacts-oel76.jenkinsfile
=> fix(artifacts): rename region_name to region

artifacts_test.py
Trello: https://trello.com/c/4idqXjdD/4283-xxxx-the-scyllasetup-script-now-supports-disabling-the-nvme-write-back-cache-on-disks-that-allow-it-this-is-useful-to-reduce-lat
New tests added:
- Verify that write back cache is disable for Scylla GCE image
- Verify that NVMe devices are properly configured
=> test(artifacts_test): verify write cache

defaults/severities.yaml, sdcm/db_log_reader.py, sdcm/sct_events/base.py, sdcm/sct_events/continuous_event.py, sdcm/sct_events/database.py, sdcm/sct_events/file_logger.py, sdcm/sct_events/grafana.py, sdcm/sct_events/health.py, sdcm/sct_events/monitors.py, unit_tests/test_sct_events_continuous_events_registry.py, unit_tests/test_sct_events_monitors.py
https://trello.com/c/oKpA8e88/4343-improvements-to-continuous-events
Reduce repair/compaction events severity.
Log continues events only into raw_events.
=> Fix continues events

sdcm/nemesis.py
Fixes - https://github.com/scylladb/scylla-cluster-tests/issues/4211
=> fix(resetlocalschema): make it wait some time

jenkins-pipelines/longevity-many-clients-4h.jenkinsfile, sdcm/cluster.py, test-cases/longevity/longevity-many-clients-4h.yaml
Longevity many client tests
Jenkins staging job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/longevity-many-clients-4h-test/
trello: https://trello.com/c/HZPKYzt9/705-scale-longevity-test-case-with-many-clients
=> test(longevity): Many client with big cluster

jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile, jenkins-pipelines/rolling-upgrade-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos7-ldap-authorization.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile, jenkins-pipelines/rolling-upgrade-multidc.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile, test-cases/upgrades/generic-rolling-upgrade.yaml
jenkinsfile of this test was missing some of
the required parameters, that are being added
to be able to run the test (job doesn't exist
on master, so for now will run on 4.6).
=> fix(rolling-upgrade-with-null-inserts): add missing params

sdcm/sct_events/group_common_events.py
=> fix(mutation_write filter): make it work

sdcm/cluster.py, sdcm/provision/common/utils.py, sdcm/sct_provision/aws/instance_parameters_builder.py
Make it work if network is unstable
Make it verbose
=> fix(provision): fix syslog-ng installation script

sdcm/nemesis.py
In case of any event generated after nemesis (but still inside
DisruptionEvent context manager), it will appear in events.log before
nemesis event.
This may happen especially when check_cluster_health() finds any node
down. This leads to wrong events order in event.log confusing problem
investigation.
Fix is about moving post-nemesis steps outside of DisruptionEvent
context manager.
tested in job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/mini-longevity/
=> fix(nemesis.py): fix order of events after nemesis

sdcm/sct_events/base.py, sdcm/sct_events/database.py, sdcm/sct_events/file_logger.py
Introduce class attribute that would control weather even is getting logged into a file.
https://trello.com/c/x9H4lh7m/4363-add-an-option-to-events-that-will-allow-us-to-control-whether-to-save-event-to-log-or-not
=> Add log event

add_new_dc_test.py, jenkins-pipelines/features-add-new-dc.jenkinsfile, test-cases/features/add-new-dc.yaml
trello: https://trello.com/c/v0fwzr67 and https://trello.com/c/DNqa9ddm
jankins job (staging): https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/add-new-dc/
=> test(add-new-dc): Add new dc test

defaults/severities.yaml
=> fix(severity): set it NORMAL for repair and compact

sdcm/utils/sstable/load_utils.py, sdcm/utils/version_utils.py, unit_tests/test_version_utils.py
As of now it doesn't transform '%s:latest' Scylla version to something more precise and leads to the false nemesis skips.
So, consider this case and pick up Scylla version from a cluster node when cluster's version ends with the ':latest' substring.
For the moment it will allow us to trigger following nemesis:
- disrupt_load_and_stream
- disrupt_show_toppartitions
=> fix(version_utils): make scylla_versions work for latest Scylla versions

test-cases/longevity/longevity-twcs-3h.yaml, test-cases/longevity/longevity-twcs-48h.yaml
=> TWCS longevities workload refactor

configurations/arm/debian10.yaml
=> fix(debain10-arm): Changed ami id to free community ami

vars/artifactsPipeline.groovy, vars/byoLongevityPipeline.groovy, vars/cdcReplicationPipeline.groovy, vars/longevityPipeline.groovy, vars/managerPipeline.groovy
=> fix(manager): Added 2.6 to the pipeline comments

sdcm/cluster_gce.py
Creating the tags we have in AWS also as labels in GCE.
Till now we created them only as metadata for instances, but this
information can't be use in other places like billing.
The reason we did not create them as labels is that the label format
is very restricting, allowing only lower case, numbers, dash and
underscore. Hence, the labels aren't going to replace the metadata
and are going to be opportunistic. It means that only if the values
match the format, the labels will be created. Otherwise there is a
warning but the test continues.
=> improvement(GCE create_instance): Create GCE lables for instances

configurations/arm_instance_types/Is4gen_4xlarge.yaml, configurations/arm_instance_types/im4gn_4xlarge.yaml, configurations/arm_instance_types/is4gen_4xlarge.yaml, jenkins-pipelines/longevity-100gb-4h-arm.jenkinsfile, jenkins-pipelines/longevity-200gb-48h-arm.jenkinsfile, jenkins-pipelines/longevity-50gb-3days-arm.jenkinsfile, jenkins-pipelines/longevity-large-partition-4days-arm.jenkinsfile
=> Fix arm longevities

Jenkinsfile, docker/env/hydra.sh, functional_tests/mocked/__init__.py, functional_tests/mocked/conftest.py, functional_tests/mocked/test_aws_region.py
Trello: https://trello.com/c/2ijG1dHb/4229-20-task-create-cloud-integration-tests-based-on-aws-mock
Add minimal mocked tests which configures AWS region.
=> feature(Jenkinsfile): add mocked tests

sdcm/sct_provision/aws/cluster.py
=> fix(provisioner): cover multidc case

sdcm/sct_config.py, sdcm/utils/aws_utils.py, sdcm/utils/common.py
Get architecture from instance type and look at the image of this architecture
=> Feature get arch from instance

defaults/test_default.yaml, sdcm/cluster.py
=> Fix sb shardawarness

defaults/aws_config.yaml
Introduce loader with c-s from `master` ([b1e09c8b8ffeb8ab9a30612693869405dd41b15c](https://github.com/scylladb/scylla-tools-java/commit/b1e09c8b8ffeb8ab9a30612693869405dd41b15c)) of [scylla-tools-java](https://github.com/scylladb/scylla-tools-java) and `3.10.2-scylla-1` scylla-driver-core
=> fix(aws_config): new loader ami

sdcm/sct_provision/aws/instance_parameters_builder.py
=> fix(provisioner): pick first az

sdcm/nemesis.py
'toppartitions' API is available starting with Scylla 4.6
So, make appropriate nemesis be smart enough to not run new API
when it is not supported.
Also, make this nemesis run both APIs - old and new ones when running
on Scylla 4.6+
=> fix(nemesis): use proper toppartitions APIs based on Scylla versions

defaults/k8s_eks_config.yaml, defaults/k8s_gke_config.yaml, defaults/k8s_local_kind_config.yaml
Set actual versions by default which are supported by latest operator
versions.
=> improvement(operator): update default mgmt and scylla versions for K8S

sdcm/utils/sstable/load_utils.py
This fix handle 2 problematic cases:
- If load_and_stream process is not finished very fast, we won't be able to recognize that
load_and_stream was started.
- If load_and_stream process was not finished we will report that the process was not
started
It happens because of system_file_follower is generator and every repeate cycle won't start
from first position. So we should lost beginning of the load_and_stream process
=> fix(load_and_stream): change validation function

sdcm/cluster.py
https://trello.com/c/oyVqoA0S/4549-fix-scylla-bench-installation
=> fix(install_scylla_bench): make it work

vars/createSctRunner.groovy
=> fix(createSctRunner): make it work for EKS pipelines having multiple AZs

sdcm/sct_provision/aws/cluster.py
https://trello.com/c/qys53Ipx/4579-fix-node-provisioning-form-ultidc
Currently we are trying to deploy in all regions, if one of the region does not have nodes,
we are still trying to deploy it, which leads to error.
=> fix(provisioner): fix node calculation

sdcm/provision/common/utils.py
=> fix(install_syslogng_service): retry install

sdcm/cluster.py
=> fix(scylla-bench): install missing 'unzip' package

vars/perfRegressionParallelPipeline.groovy
=> fix(perf-pipeline): do not export variable with 'null' value

jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile, jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile, sdcm/cluster.py, test-cases/artifacts/centos8-selinux.yaml, test-cases/artifacts/centos8.yaml
=> Centos 8 new gcp repo

vars/rollingUpgradePipeline.groovy
cause of recent changes in 31c5a77d5eddcb1bf8199ac52d2656891e6fe873
the creation of sct runner in GCE was failing for one of the rolling
upgrade split
```
21:27:37  libcloud.common.google.ResourceExistsError: {'message':
"The resource 'projects/skilled-adapter-452/zones/us-east1-c/
instances/sct-runner-1-5-instance-780f2359' already exists",
'domain': 'global', 'reason': 'alreadyExists'}
```
=> fix(rolling_upgrades): SCT_ID was overrun

sdcm/nemesis.py
When there's timeouts on the DROP TABLE part, we don't join the thread,
and the repair would continue running. failing the next nemesis if it's
manager repair.
Fixes: #4422
=> fix(disrupt_no_corrupt_repair): not leave running repairs behind

longevity_test.py
Add tighter duration based on cs_duration, and not on the
test whole duration
=> fix(5000-tables): add a duration for each stress command

sdcm/cluster.py
Since NemesisThread is responsible for tracking argus nemeses objects if
it is terminated at the end of the test, then any nemesis it was running
during that termination event will not get its information stored in
argus and will still show "In Progress" status there. This corrects that
by introducing a termination routine into BaseScyllaCluster which will
set every currently running nemesis status to "Terminated" and append
each NemesisThread stack trace into that nemesis stack trace.
[Trello](https://trello.com/c/eeLFaug8/4567-create-terminated-state-for-nemesis)
=> improvement(sdcm/cluster.py): Clean up argus nemeses during tearDown

sdcm/cluster_k8s/__init__.py
For debugging purposes we may want to have various configuration files
created in Scylla containers.
So, gather those as part of the K8S logs.
=> feature(operator): gather scylla-specific files from Scylla containers

sdcm/cluster_k8s/__init__.py, upgrade_test.py
ServiceAccount creation was automated in the operator 1.7
It led to the bug where the update of operator was causing
removing custom annotations from service accounts used by Scylla
clusters. In operator 1.7.2 it was fixed.
So, cover this case in upgrade jobs.
=> feature(operator-upgrade): make sure that SA annotations stay

sct.py, sdcm/sct_config.py, sdcm/utils/common.py
was back ported to this branch a fix that uses
new Python features, that are not present in this
old branch (with an old Python version).
=> fix(common.py): remove Literal as Python is old

utils/split_sct_log.py
=> feature(split-sct-log): small util for split sct log by nemesis

configurations/operator/1tb-7days-no-tls.yaml, configurations/operator/50GB-no-tls.yaml, configurations/operator/cdc-3d-400gb.yaml, configurations/operator/large-partition-200k-pks-4days.yaml, jenkins-pipelines/operator/eks/longevity-scylla-operator-1tb-7days.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-50gb-3days.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-cdc-3d-400gb.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-large-partition-200k-pks-4days.jenkinsfile
List of new jobs:
- 1tb-7days
- 50gb-3days
- cdc-3d-400gb
- large-partition-200k-pks-4days
=> ci(operator): add new long longevity jobs

jenkins-pipelines/longevity-cdc-8h-multi-dc-large-cluster.jenkinsfile, test-cases/longevity/longevity-cdc-100gb-8h-multi-dc-large-cluster.yaml
Added new test to check cdc behavior with large cluster
in case of verifying commit scylladb/scylla: 5f84848
Trello: https://trello.com/c/USmkUK46
=> test(cdc-large-cluster): Multidc with cdc and large cluster

mgmt_cli_test.py, mgmt_upgrade_test.py, sdcm/cluster.py, sdcm/mgmt/cli.py, sdcm/mgmt/common.py, sdcm/mgmt/operator.py
=> refactor(manager): Rewritten the manager code to use the new 3.0 cli

jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
=> refactor(manager upgrade): changed base version to 2.6

configurations/arm/centos8.yaml, configurations/arm/debian10.yaml, configurations/arm/ubuntu2004.yaml, jenkins-pipelines/artifacts-centos8-arm.jenkinsfile, jenkins-pipelines/artifacts-debian10-arm.jenkinsfile, jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile, vars/artifactsPipeline.groovy
=> refactor(artifact-arm): set manager 2.6 agent installation for arm tests

sdcm/logcollector.py, sdcm/sct_config.py
PR https://github.com/scylladb/siren-tests/pull/957 should be merged first
=> fix(cloud manager): collect manager logs

jenkins-pipelines/perf-regression-alternator-latency-30min.jenkinsfile, jenkins-pipelines/perf-regression-alternator-throughput-30min.jenkinsfile, performance_regression_alternator_test.py, sdcm/report_templates/results_performance.html, sdcm/report_templates/results_performance_baseline.html, sdcm/results_analyze/__init__.py, sdcm/utils/es_queries.py, sdcm/ycsb_thread.py, test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml, test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
=> fix(alternator_perf): getting it to working state

sdcm/nemesis.py
In disrupt_terminate_and_replace_node nemesis,
there is a problem when new node is getting the same IP addres as
replaced one - in that case assertion is failing. This happens often on
Azure platform.
Solution is about verifying if old node first is in DN state after
removal and later if it was removed or state is UN (in case when
new node gets the same IP address)
https://trello.com/c/LtjVuLu5
=> fix(nemesis): fix verification in disrupt terminate and replace node

sdcm/logcollector.py, sdcm/utils/remote_logger.py
Task: https://trello.com/c/EkPg2rht/4381-gether-scylla-houskeeping-log-and-check-for-errors-of-the-
houskeeping-service
Collect scylla-housekeeping logs
=> fix(housekeeping): gether scylla-houskeeping log

sdcm/logcollector.py
Use the same procedure to get manager instance for AWS and GCE backends
Merge with https://github.com/scylladb/siren-tests/pull/968
=> improvement(cloud longevity): change get manager for both backends

defaults/severities.yaml, sdcm/sct_events/database.py, unit_tests/test_sct_events_database.py
Trello: https://trello.com/c/sqqxYeU5
Added new event to inform about disk errors
=> fix(dababase_log_event): New disk error event

sdcm/sct_events/database.py, unit_tests/test_sct_events_continuous_events_registry.py
Task https://trello.com/c/Mu3lGc7C/4828-disable-compaction-and-repair-continuous-events
=> fix(events): disable compaction and repair events

vars/managerPipeline.groovy
=> fix(managerPipeline.groovy): added missing curly bracket

sdcm/cluster_aws.py, sdcm/cluster_gce.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/wait.py
Trello: https://trello.com/c/HR3L3657/4918-duplicate-code-instancewaitsafe
```python
************* Module sdcm.utils.cloud_monitor.report
sdcm/utils/cloud_monitor/report.py:1:0: R0801: Similar lines in 2 files
==sdcm.cluster_aws:[555:573]
==sdcm.cluster_gce:[89:105]
def _instance_wait_safe(self, instance_method, *args, **kwargs):
"""
Wrapper around AWS instance waiters that is safer to use.
Since AWS adopts an eventual consistency model, sometimes the method
wait_until_running will raise a botocore.exceptions.WaiterError saying
the instance does not exist. AWS API guide [1] recommends that the
procedure is retried using an exponencial backoff algorithm [2].
:see: [1] http://docs.aws.amazon.com/AWSEC2/latest/APIReference/que...
:see: [2] …
```
=> fix(pylint): remove code duplication

jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, vars/managerPipeline.groovy
=> refactor(manager): Moved scylla version to 4.6

jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-gce-1tb.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile, jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
=> (Manager): Revert pipeline timeout

sdcm/provision/azure/provisioner.py, sdcm/utils/common.py
Azure cleaner was bound to test_id which was not provided when
cleanup-resources was triggered for given user causing an error.
This fix enables cleanup user related resources.
It also fixes cleanup of whole Resource Group when all instances get
terminated.
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/4546
=> fix(cleanup-resources): azure clean by user

configurations/arm_instance_types/Is4gen_4xlarge.yaml, configurations/arm_instance_types/im4gn_4xlarge.yaml, configurations/arm_instance_types/is4gen_4xlarge.yaml, defaults/test_default.yaml, jenkins-pipelines/longevity-100gb-4h-arm.jenkinsfile, jenkins-pipelines/longevity-200gb-48h-arm.jenkinsfile, jenkins-pipelines/longevity-50gb-3days-arm.jenkinsfile, jenkins-pipelines/longevity-large-partition-4days-arm.jenkinsfile, sdcm/cluster.py, vars/longevityPipeline.groovy, vars/runSctTest.groovy
=> Backport arm support branch 2021.1

test_lib/compaction.py
In order to test the compatibility with this legacy compaction strategy.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4632
=> fix(compaction.py): Added DateTieredCompactionStrategy to list

sdcm/argus_test_run.py
[Trello](https://trello.com/c/Filaar8E/4958-add-azure-support-in-argus)
=> improvement(sdcm.argus_test_run): Azure resources config support

requirements.in
[Trello](https://trello.com/c/dVm53UuB/4412-move-argus-project-to-poetry)
=> improvement(argus): Download argus from pypi

unit_tests/test_cluster.py, unit_tests/test_decode_backtrace.py, unit_tests/test_utils_common.py
Task:
https://trello.com/c/sFG8mzOe/4077-refactor-remove-duplicated-code-for-dummynode
=> refactor(unit_tests): remove duplicated code for DummyNode

sct.py, sdcm/utils/version_utils.py, unit_tests/test_base_version.py, utils/get_supported_scylla_base_versions.py, vars/rollingUpgradePipeline.groovy, vars/supportedUpgradeFromVersions.groovy
This PR is a port of the changes introduced in master with: https://github.com/scylladb/scylla-cluster-tests/pull/4603
=> refactor(rolling_upgrade): logging and faster pipeline exit

mgmt_upgrade_test.py, sdcm/mgmt/cli.py
=> Upgrade detail comparison

sct.py
Trello: https://trello.com/c/uwlkJuDf/4985-create-scylla-operator-compatability-job-for-20221-50
=> test(release): add operator functional job to list of release jobs

sdcm/db_stats.py
Running performance tests we write lots of data to ElasticSearch
and pretty often get following error which fails test runs:
elasticsearch.exceptions.RequestError: RequestError(
400,
'illegal_argument_exception',
'Limit of total fields [1000] has been exceeded')
It happens because in some cases when we gather sysctl configs from
DB nodes we get hundreds of records for each node.
And in summary it exceeds 1000 of keys in the data we write.
So, update the code where we gather sysctls removing some huge sets
of data which are unlikely to be used by us.
=> fix(es-upload): reduce amount of data in docs we uplaod to ES

sdcm/sct_config.py
Reason: different DB clusters will need it's own commands.
=> improvement(k8s-multitenant): allow to use list of lists for stress cmds

sdcm/monitorstack/__init__.py
since #4627 the dashboard files now has random part to them
and the `show-monitor` command was failing
this fix only getting the first dashboard and doesn't handle
the case of restoring multiple dashboards (for operator multi
tenant runs)
=> fix(monitoring): restore was failing to file dashboard file

sct.py, sdcm/cluster_azure.py, sdcm/provision/azure/provisioner.py, sdcm/provision/azure/utils.py, sdcm/provision/azure/virtual_machine_provider.py, sdcm/provision/provisioner.py, sdcm/sct_config.py, sdcm/sct_provision/azure/azure_instance_request_definition_builder.py, sdcm/sct_provision/instances_provider.py, sdcm/sct_provision/instances_request_definition_builder.py, sdcm/tester.py, unit_tests/provisioner/__init__.py, unit_tests/provisioner/azure_default_config.yaml, unit_tests/provisioner/conftest.py, unit_tests/provisioner/fake_azure_service.py, unit_tests/provisioner/test_azure_instance_request_builder.py, unit_tests/provisioner/test_azure_provisioner.py, unit_tests/provisioner/test_provision_sct_resources.py, vars/longevityPipeline.groovy, vars/provisionResources.groovy
Enables provisioning instances before test.
Also implements fallback on demand.
https://trello.com/c/k50TBG0Q
=> feature(azure): provision in separate step

jenkins-pipelines/perf-regression-alternator-latency-30min.jenkinsfile, jenkins-pipelines/perf-regression-alternator-throughput-30min.jenkinsfile
make sure we are sending to `scylla-perf-results@scylladb.com`
=> fix(alternator_perf): send mail to correct mailing list

artifacts_test.py
=> fix(artifacts): skip XFS mount test for non-root install

functional_tests/scylla_operator/test_functional.py, sdcm/mgmt/cli.py, sdcm/mgmt/operator.py
=> Cover scylla-manager v3 in operator functional tests

mgmt_cli_test.py
As of late, the db node's comes with the gsutil dependencies pre-installed,
so I removed the installation from the test flow
=> fix(manager-gce): removed gsutil dependencies installation

sdcm/utils/common.py
Trello: https://trello.com/c/BZ7B0Ydd/4735-gemini-oracle-db-node-was-not-cleaned-by-the-pipeline-4503
Remove oracle-db and cs-db node types in addition to scylla-db.
Fixes #4503
=> fix(common): cleanup different db node types

defaults/test_default.yaml, sdcm/cluster.py, sdcm/monitorstack/__init__.py
New monitor release is coming and need to be tested with.
=> refactor(defaults monitor_branch): Setting monitor branch to 4.0

functional_tests/scylla_operator/test_functional.py
=> test(k8s-func): skip drain_terminate_decommission_add_node_kubernetes

jenkins-pipelines/perf-regression-latency-ycsb-100M-rows.jenkinsfile, jenkins-pipelines/perf-regression-latency-ycsb-10M-rows.jenkinsfile, jenkins-pipelines/perf-regression-latency-ycsb-1B-rows.jenkinsfile, jenkins-pipelines/perf-regression-latency-ycsb-1M-rows.jenkinsfile, performance_regression_operator_multi_tenant_test.py, performance_regression_test.py, sdcm/remote/base.py, sdcm/report_templates/results_performance.html, sdcm/results_analyze/__init__.py, sdcm/utils/docker_remote.py, sdcm/ycsb_thread.py, test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml, test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml, test-cases/performance/ycsb/perf-base.yaml, unit_tests/conftest.py, unit_tests/dummy_remote.py, unit_tests/lib/fake_remoter.py, unit_tests/test_ycsb_thread.py, vars/perfRegressionParallelPipeline.groovy, ycsb_performance_regression_test.py
A test running each of YCSB workloads for 30min
Trello: https://trello.com/c/6HtK30nC
=> test(ycsb_performance_regression_test.py): YCSB latency test

sdcm/provision/common/utils.py
Reverts scylladb/scylla-cluster-tests#4774
=> Revert "fix(syslog-ng): wait for APT locks in more reliable way"

sdcm/cluster.py
because of issue https://github.com/scylladb/scylla/issues/10442
we need to add here this workaround, as the
base versions patches don't include the fix
for this issue.
=> fix(install_scylla): adding workaround to JDK

test-cases/PR-provision-test-docker.yaml, test-cases/PR-provision-test.yaml
* use newer scylla version, since older ones uses centos as base.
* stop installing manager, since we are not really having a monitor node
=> fix(docker_backend): fix docker provision

functional_tests/scylla_operator/test_functional.py
during the life-cycle of a pod, the results of the io_tune
should be cached, and not run on every restart of the pod.
Ref: https://github.com/scylladb/scylla-operator/issues/146
Trello: https://trello.com/c/kFSyujoc
=> test(io_tune): verify io_tune is only called once

stop_compaction_test.py
Due wrong default value the same test was executed twice.
Also because reshape already happened, the second test didn't
run reshape at all.
Fix is setting proper default value and change compaction strategy
for reshape_on_boot test.
=> fix(test_stop_compaction): fix for reshape tests

artifacts_test.py, sdcm/utils/common.py
Add verification the latest docker tag is equal to the latest
(according to AMIs) release image.
Trello: https://trello.com/c/w56kLlvq
=> test(docker): compare latest tag to official release image

sdcm/monitorstack/__init__.py
When we recreate the monitor stack locally for investigations
we need to clear the targets, otherwise prometheus keep "banging"
on those addresses and ports (and might hit a new running test,
or all kind of other devices that might be using the same ports
as we do)
Fixes: #4835
=> fix(monitorstack): clean prometheus configuration from real ips

utils/backport.sh
to backport multiple commits wrap with quotes
and separate with space, for example:
./backport.sh "1abcd 2abcd"
Feel free to improve it!
=> feature(backport-script): added a script that helps to backport commits

sdcm/cluster.py
For some reason, after c-s command is killed by request or at failed, the java -server with c-s parameter is restarted and continue send traffic. this could bring, that job perf-latency-with-nemesis is aborted by timeout.
Use several commands to search the c-s processes and kill them with checking that it was not restarted
Add list of commands to kill c-s threads
=> fix(kill_cs_thread): Use different commands to kill c-s threads

build_cluster_test.py, jenkins-pipelines/features-dns-cluster-5min.jenkinsfile, test-cases/features/dns-cluster-5min.yaml
ScyllaYaml put "none" as listen_address and rpc_address. This fixes the issue. Also, increased test duration to prevent unwanted timeouts.
=> fix(build_cluster_test): Use remote_scylla_yaml to edit the yaml file

sdcm/utils/aws_region.py
=> fix(aws_region) Enable DNS hostnames

sdcm/cluster_aws.py, sdcm/provision/aws-cloud-init.txt, sdcm/provision/helpers/cloud_init.py, sdcm/provision/user_data.py, unit_tests/test_base_version.py
Porting commit https://github.com/scylladb/scylla-cluster-tests/commit/e0b8d71760191a5119f81a2b72d50ee665a5a659 into branch-5.0
=> feature(provision): use cloud-init for ssh config

artifacts_test.py
In the artifact test, we have a test that checks that one (and only one)
time synchronization service active. However, if the check fails and the number
of time sync services does not meet our expectations (either zero or more than one)
the error message is not enough to understand the issue. So, I added a log message
of all of the services in the node under test that is printed when the check fails,
so error will be clearer.
=> fix(time synchronization check): Added full service print

defaults/k8s_eks_config.yaml, defaults/k8s_gke_config.yaml, defaults/k8s_local_kind_config.yaml, functional_tests/scylla_operator/test_functional.py, test-cases/scylla-operator/functional.yaml
=> improvement(k8s): use mgmt 3.0.0 in K8S

sdcm/nemesis.py
Fix for https://github.com/scylladb/scylla-cluster-tests/issues/4867: we need to cleanup after scrub operations.
=> fix(nemesis): clear all snapshots after scrub

configurations/arm/amazon2.yaml, jenkins-pipelines/artifacts-amazon2-arm.jenkinsfile
=> test(artifact test): added amazon linux 2 arm artifact test

sdcm/remote/remote_file.py, unit_tests/test_remoter.py
Since in some cases we've seen `scylla_yaml` was used to read at
the same time it was used to change the yaml, and the read operation
was writting over the file
with the following sequence:
```
1.recv file for modify
2.recv file for reading
3.send back file for modify
4.send back file for reading
```
this PR doesn't handle the case if there are two modifications at
the same time, just lower the damage readonly usage can do.
Fixes: #4915
=> fix(remote_file): if content wasn't changed, don't copy back the file

sla_per_user_system_test.py
In ideal expected ratio between two users in the test test_read_throughput_1to5_ratio is 5.0.
Based on reality change it to 3.5
https://github.com/scylladb/scylla-cluster-tests/pull/4943#issuecomment-1168507500
http://13.48.103.68/test/71402aa7-051b-4803-a6b4-384529680fb7/runs?additionalRuns[]=1adf34d1-15cf-4973-80ce-9de130be0b09
=> fix(sla test): change expected shares ratio to 3.5

sdcm/cluster.py
manual backport of https://github.com/scylladb/scylla-cluster-tests/pull/4293
trello: https://trello.com/c/iHja9FVm
=> feature(events): Add a new WARNING event

sdcm/nemesis.py
Since multiple backup nemesis cannot run at the same time, I
deleted all running backups and those that are about to run before
the backup task the nemesis creates starts
=> fix(backup nemesis): deleting all backup tasks before nemesis run

sdcm/cluster_k8s/__init__.py, sdcm/tester.py
=> Fix k8s multitenant setup for 3 and more clients

jenkins-pipelines/manager/enterprise-ami-manager-sanity.jenkinsfile, jenkins-pipelines/manager/enterprise-ami-manager-upgrade.jenkinsfile
=> test(manager): added manager tests that use enterprise ami

sct.py, sdcm/provision/azure/provisioner.py
This commit adds support for Azure in list-resources hydra command.
https://trello.com/c/4v0o8PiP
=> feature(azure): support list-resources command

sdcm/cluster_k8s/__init__.py
As of now, we specify only node affinity rules for Scylla pods.
It is ok while we install only one Scylla cluster.
But when we install 2 and more in parallel then we get some of
a Scylla cluster pods be scheduled on a single K8S node.
This situation may lead to improper results measuring performance.
So, fix it by specifying pod anti-affinity rules making all the pods
of a Scylla cluster be scheduled only on different nodes.
=> fix(k8s-multitenant): make Scylla pods be sched only on different nodes

Jenkinsfile, test-cases/PR-provision-test.yaml
This will help us easily check that specific PRs are not
breaking the k8s provisioning
=> feature(Jenkinsfile): add option to run k8s functional in PRs

Jenkinsfile, vars/getJenkinsLabels.groovy, vars/runCleanupResource.groovy, vars/runCollectLogs.groovy
Commit adds Azure backend to SCT pipeline provision tests.
=> feature(Azure): support Azure in SCT provision test

upgrade_test.py
Rolling upgrade test email often does not contain info about upgraded
Scylla version. Also Argus is missing this information.
This commit fixes email issue and sends upgraded Scylla version to
Argus.
=> fix(upgrade-test): Fix new version in mail and argus

sdcm/mgmt/common.py
=> improvement(TaskStatus): Added SKIPPED task status

defaults/manager_versions.yaml, defaults/test_default.yaml, sdcm/cluster.py, sdcm/mgmt/cli.py
=> Backport manager 3 support

sdcm/cluster.py
=> fix(cluster.py): skipping scylla bench installation

jenkins-pipelines/features-google-cloud-snitch-mutli-dc.jenkinsfile, sdcm/sct_config.py, sdcm/send_email.py, snitch_test.py, test-cases/features/google-cloud-snitch-multi-dc.yaml, utils/lint_test_cases.sh, vars/getJenkinsLabels.groovy, vars/runCleanupResource.groovy, vars/runCollectLogs.groovy, vars/runSctTest.groovy
=> reinstated and fixed multi dc gce snitch test

sdcm/cluster_azure.py
Added spot termination monitoring support for Azure.
It can be tested with command:
`az vm simulate-eviction --resource-group <rg_name> --name <vm_name>`
https://trello.com/c/iyuIoudK
=> feature(spot-termination): Support SpotTerminationEvent on Azure

sdcm/nemesis.py
Running 'disrupt_nodetool_flush_and_reshard_on_kubernetes' nemesis
we may get new IP addresses for some pods. So, refresh it intentionally
after each CPU count change to make sure we do not use old cached value.
Without it following error may appear:
Get nodes statuses. Failed to find a node in cluster by IP: 10.0.1.5
And then, each nemesis that uses such a node as a target gets networking
issues trying to connect to inexistent IP address.
=> fix(k8s): refresh IP addresses after flush and reshard nemesis

sdcm/cluster_k8s/__init__.py
For the moment, specifying scylla-operator chart as `latest` we get the oldest version in the family - `1.8.0-alpha.0`
But it should be something like this - `v1.8.0-alpha.0-47-g161d249`.
It leads to the situation that we use very old helm chart and newest scylla-operator image. This situation is a bug.
So, fix it by ignoring all the versions which contain 1,2 and 4+ `-` symbols. 
Also, check that we have the same `v` prefix all the time.
=> fix(k8s): pick up really latest operator helm chart

sdcm/stress_thread.py
Up until now, we've used only the first node as the coordinator.
However, if the first node is down for any reason (like a nemesis), the
stress is DOA. Therefore, I included all of the nodes as coordinators.
=> fix(cassandra-stress): include all nodes as coordinators

configurations/operator/perf-regression-latency-and-throughput-multitenant-14-clients.yaml, configurations/operator/perf-regression-latency-and-throughput-multitenant-2-clients.yaml, configurations/operator/perf-regression-latency-and-throughput-multitenant-7-clients.yaml, configurations/operator/perf-regression-latency-multitenant-14-clients.yaml, configurations/operator/perf-regression-latency-multitenant-2-clients.yaml, configurations/operator/perf-regression-latency-multitenant-7-clients.yaml, jenkins-pipelines/operator/performance/perf-regression-latency-and-throughput-eks-multitenant-14-clients.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-latency-and-throughput-eks-multitenant-2-clients.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-latency-and-throughput-eks-multitenant-7-clients.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-latency-eks-multitenant-14-clients.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-latency-eks-multitenant-2-clients.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-latency-eks-multitenant-7-clients.jenkinsfile, test-cases/performance/perf-regression-latency-k8s-multitenant.yaml
=> ci(k8s): add jobs to run K8S multi-tenant tests with 2, 7 and 14 clients

sct.py, sdcm/utils/common.py
This PR introduces `list-images` to SCT commands that allows to list machine images from both AWS and GCE. The command options allow to filter the results by: cloud backend, architecture, region (for AWS results only), branch.  Additionally it also allows to list the images by version. This combines the previously available `list-ami-branch`, `list-gce-branch`, `list_gce_images_versions` and `list_aws_images_versions`  into one command.
Trello task: https://trello.com/c/DHZ7mE3u
Asciinema screencast with sample usage:
https://asciinema.org/a/v2LuoLh2o93ekRcOFDmsLXljU
=> refactor(list-images): consolidate image listing

sdcm/tester.py
This fixes an issue where since offline artifacts tests do not use a
system package manager to install scylla, the argus_collect_packages
method would not be able to locate packages for reporting. The new
behaviour now tries to 'generate' a scylla-server package by first
requesting a node to report its scylla_version, then by parsing it into
a PackageVersion container, which is then given to collect_packages for
reporting.
=> improvement(sdcm.tester): Generate scylla-server package in offline test

functional_tests/scylla_operator/test_functional.py
Add test that cover disrupt_rolling_config_change_internode_compression nemesis logic
=> test(functional): add rolling change internode compression test

sct.py, sct_ssh.py, sdcm/sct_runner.py
This PR aims to modify the way we clean SCT runner instances. We clean SCT runners close to the end of most of our pipelines. The requested logic was to:
- extend the runners `keep` tag to `now()`  +6 hours if the test failed and logs were collected
- allow runners to be removed at the end of the test on demand --> I set them to be removed by default if the test passed with "SUCCESS" and logs were collected
As an additional goal this PR removes logic from `list_sct_runners`, since part of the logic for keeping or cleaning the runner was placed there, modifying the listed representations of instances. IMHO a `list_*` method should not modify these representations at all.
Trello tasks: https://trello.com/c/2ypkHwF7, https://trello.com/c/6Lr0Rowm
GCE run with a failure before the test …
=> Adjust SCT runner lifespans based on test failure and collect_logs status

sdcm/nemesis.py
During different nemeses the target pod (and not only target) is recreated and
private IP is changed.
Run 'refresh_ip_address' and 'reconfigure_scylla_monitoring' after pod recreation.
This change solves node status valudation as old IP can not be found in the
`nodetool status` output
Test [test](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/operator/job/yulia-longevity-scylla-operator-basic-12h-eks/14/) passed.
=> fix(k8s nemeses): update nodes' IPs after node recreation

jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile, test-cases/manager/manager-regression-azure.yaml, utils/lint_test_cases.sh, vars/managerPipeline.groovy
=> Modify the azure manager backup test to use an azure cluster

configurations/manager/debian10.yaml, configurations/manager/ubuntu18.yaml, defaults/manager_versions.yaml, defaults/test_default.yaml, test-cases/scale/longevity-many-clients-4h.yaml, unit_tests/test_sdcm_mgmt_common.py, vars/artifactsPipeline.groovy, vars/byoLongevityPipeline.groovy, vars/cdcReplicationPipeline.groovy, vars/longevityPipeline.groovy, vars/managerPipeline.groovy
=> Bumped scylla manager backend to 2022 and removed unsupported versions

ics_space_amplification_goal_test.py, sdcm/db_stats.py
Prometheus queries related methods were not organized
and were located in a specif test and not a common related file.
Trello: https://trello.com/c/OvVNXBMi
=> fix(db_stats.py): Reorganize Prometheus query methods

sdcm/provision/azure/utils.py
Recently build_id tag value became date string. This caused exception
when converting it to int.
To fix, parse date string to timestamp when int conversion fails.
fixes issue mentioned in https://github.com/scylladb/scylla-cluster-tests/pull/5150
=> fix(azure): fix list images when build id is a date

sdcm/provision/azure/utils.py
When scylla image is built manually, build_id gets date
as build_id (could be also something else). In that case
we don't want to use this image in SCT when specifying
Scylla version.
Fix by skipping images when we cannot parse build_id as int.
fixes issue from comment: https://github.com/scylladb/scylla-cluster-tests/pull/5151#discussion_r951042994
=> fix(azure-list-images): skip manually created images

test-cases/longevity/longevity-harry-2h.yaml
This reverts commit 739da0c255ab489444b15a9c4dc2d542c3856156.
=> Revert "fix(HACK): remove nemeis from harry case"

sdcm/report_templates/results_latency_during_ops_short.html, sdcm/utils/latency.py
=> Perf with ops add more statistics

.github/workflows/auto_assign.yaml
allow running on PRs from forks
=> feature(github-actions): add auto assign action

defaults/k8s_local_kind_config.yaml, test-cases/scylla-operator/functional.yaml
bump the version to v0.14.0, so we'll get improvments
and bug fixes
=> feature(k8s-local-kind): bump kind version

defaults/test_default.yaml, docker/ycsb/Dockerfile, docker/ycsb/image
creating ycsb image that includes:
https://github.com/scylladb/YCSB/pull/1
=> feature(ycsb): [dynamodb] add support for TTL

defaults/test_default.yaml, docker/ycsb/Dockerfile, docker/ycsb/image
Reverts scylladb/scylla-cluster-tests#5221
=> Revert "feature(ycsb): [dynamodb] add support for TTL"

sdcm/cluster_k8s/__init__.py
For the moment, if we run
'disrupt_nodetool_flush_and_reshard_on_kubernetes' nemesis with existing clsuter then we fail to read info from the 'calculated_cpu_limit' attribute which is not initialized.
So, init it always.
=> fix(k8s): always calculate cpu and memory limits

test-cases/longevity/longevity-100gb-4h.yaml, test-cases/longevity/longevity-cdc-100gb-4h.yaml
=> Add tls short longevity

defaults/test_default.yaml, docker/ycsb/image
build with latest YCSB from scylladb fork:
* scylladb/YCSB#4
=> feature(ycsb): [Dynamodb] add support for updating TTL

artifacts_test.py
Recently cqlsh broke cause of a packaing issue, dropping python2.
it was only noticed on longevity nemsis that use is, we should catch it much earlier.
Also, we are working on repackging cqlsh, and it would be importent that we verify it's working across the artifact tests
Ref: https://github.com/scylladb/scylla-pkg/issues/3094
Ref: https://github.com/scylladb/qa-tasks/issues/800
=> feature(artifacts): verify cqlsh is working

sdcm/nemesis.py
During testing of 2022.2 we've found more places we need to ignore `Connection refused` errors when nodes restarts
```
[Thread-13] ERROR site.ycsb.db.DynamoDBClient -com.amazonaws.SdkClientException:
Unable to execute HTTP request: Connect to alternator:8080 [alternator/10.4.3.78]
failed: Connection refused (Connection refused)
```
spotted on:
* `remove_node_then_add_node`
* `disrupt_repair_streaming_err`
=> fix(alternator): cover more places with ignore_ycsb_connection_refused

defaults/test_default.yaml, docker/ycsb/Dockerfile, docker/ycsb/README.md
* https://github.com/scylladb/YCSB/pull/5
=> fix(ycsb): fix ttl to be sent as number, and not as string

test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml
=> fix(longevity-50GB-3days-authorization...): Adjust instance type

sdcm/cluster.py, sdcm/utils/health_checker.py, unit_tests/test_utils_health_checker.py
Reverts scylladb/scylla-cluster-tests#5272
=> Revert "fix(schema-agreement): print proper error messages"

sdcm/nemesis.py
prevent pre-commit failure with 'Unreachable code' error.
Now all commits' validation fail with this error
=> fix(nemesis): prevent pre-commit failure with 'Unreachable code' error

sdcm/cluster_gce.py
=> improvement(GCP): Add a general label for GCE instances

.pre-commit-config.yaml, internal_test_data/complex_test_case_with_version.yaml, internal_test_data/minimal_test_case.yaml, sdcm/sct_config.py, sdcm/sct_events/group_common_events.py, sdcm/utils/common.py, unit_tests/test_base_version.py, unit_tests/test_config.py, unit_tests/test_utils_common.py
This PR includes a few commits cherry-picked from master and a small fix to imports in order to fix the CI checks on `branch-5.0`. 
Part of the effort in: https://github.com/scylladb/qa-tasks/issues/813
=> Fix CI checks

sdcm/cluster.py
On https://github.com/scylladb/scylladb/pull/8867, we changed directory structure of unified package, and increment it's
relocatable_package_version to 3.0.
We need to support it on SCT to run offline tests.
=> feature(cluster.py): support new directory structure of unified package

sdcm/nemesis.py, unit_tests/test_nemesis.py
When running multiple classes of nemesis, seems like
we are wrapping the distrupt function twice, which leads
to multiple nemesis running multiple times on each
call
=> fix(nemesis): move wrapping code from __new__ to __init__

sdcm/nemesis.py
since #4912 lint is complaining.
=> fix(nemesis.py): make lint happy

sdcm/tester.py
This corrects an issue where argus_get_scylla_version would fail if BaseNode.get_scylla_binary_version() returns None. In this case it logs a warning instead.
=> fix(sdcm/tester.py): Check if version_str is non-empty

jenkins-pipelines/perf-regression-scylla-gradual-throughput-grow-gauss-lcs.jenkinsfile, jenkins-pipelines/perf-regression-scylla-gradual-throughput-grow-gauss.jenkinsfile, jenkins-pipelines/perf-regression-scylla-gradual-throughput-grow-uniform.jenkinsfile, performance_regression_alternator_test.py, performance_regression_gradual_grow_throughput.py, performance_regression_operator_multi_tenant_test.py, performance_regression_test.py, sdcm/cluster.py, sdcm/logcollector.py, sdcm/report_templates/results_incremental_throughput_increase.html, sdcm/results_analyze/__init__.py, sdcm/sct_config.py, sdcm/stress_thread.py, sdcm/tester.py, sla_per_user_system_test.py, test-cases/performance/cs-compaction-strategy-lcs.yaml, test-cases/performance/cs-gauss-distribution.yaml, test-cases/performance/cs-uniform-distribution.yaml, test-cases/performance/perf-regression-gradual-throughput-grow.yaml
Added new test to run performance with incremental increasing throughput on each stage and find the best results by latency
New test with c-s tool which is used uniform distribution
=> feature(performance): New perf tests for scylla (gradual throughput increase)

sdcm/remote/kubernetes_cmd_runner.py, sdcm/scylla_bench_thread.py
=> fix(k8s): make scylla-bench work using dynamic K8S loader pods

functional_tests/scylla_operator/test_functional.py
Looks like each of the manager versions is affected by the following bug: https://github.com/scylladb/scylla-manager/issues/3156
So, run manager tests before ones with the K8S nodes drain operations.
=> improvement(k8s-functional): run mgmt tests before K8S node drain ones

configurations/azure/azure_rolling_upgrade.yaml, jenkins-pipelines/rolling-upgrade-azure-image.jenkinsfile, sdcm/sct_config.py, vars/createSctRunner.groovy, vars/getCloudProviderFromBackend.groovy, vars/rollingUpgradePipeline.groovy
Porting PR https://github.com/scylladb/scylla-cluster-tests/pull/5337 from master branch
=> Azure rolling upgrade 5.1

configurations/azure/azure_rolling_upgrade.yaml, jenkins-pipelines/rolling-upgrade-azure-image.jenkinsfile, sdcm/sct_config.py, vars/createSctRunner.groovy, vars/getCloudProviderFromBackend.groovy, vars/rollingUpgradePipeline.groovy
Porting PR https://github.com/scylladb/scylla-cluster-tests/pull/5337 from master branch
=> Azure rolling upgrade 2022.2

jenkins-pipelines/perf-search-throughput-best-config.jenkinsfile, performance_regression_test.py, performance_search_max_throughput_test.py, sdcm/report_templates/results_search_best_throughput_config.html, sdcm/results_analyze/__init__.py, sdcm/sct_config.py, sdcm/tester.py, test-cases/performance/perf-search-best-throughput-config.yaml, vars/perfSearchBestConfigParallelPipeline.groovy
Added new Perf test  with job, which run and detect best throughput for specified configuration
=> Detect best throughput config

test-cases/longevity/longevity-multi-keyspaces.yaml
this are very old ami, some of them are already deleted all the issue mentioned in those are alread long fixed time to remove those and test again
=> fix(multi-keyspaces): remove loader ami overrides

sdcm/cluster.py, unit_tests/test_cluster.py
For the moment BaseNode's property called `cpuset` only supports one or two ranges of cores.
It will fail with IndexError if only one core is used. 
It will show wrong number of cores having more than 2 ranges (17+ cores instance type).
So, make it parse the possible values correctly and add unit tests coverage for it.
=> fix(cluster.py): properly parse cpuset node info

sdcm/cluster.py, sdcm/nemesis.py
Trello: https://trello.com/c/5OpkxxlQ
Changing TWCS window size with next reshape
could bring significant write amplicification.
New nemesis will change the window size and
restart the node
=> feature(nemesis): Change TWCS unit size and check reshaping

sdcm/tester.py
=> improvement(k8s-multitenancy): process all monitors in parallel

sdcm/sct_runner.py
seem like since we move to the using the new gcp project our cleanup logic doesn't cover cleanup of sct-runner in the older project (i.e. old branches that uses that)
now we list all the gce project, before we move to cleanup of them.
=> fix(clean-runner-instances): run cleanup on all gcp project

sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/results_analyze.py, sdcm/utils/distro.py, test-cases/performance/perf-regression-latency-1TB.yaml, test-cases/performance/perf-regression.100threads.30M-keys.yaml
=> Branch perf v8

sdcm/nemesis.py
=> Fix resharding nemesis for k8s

sct.py, sdcm/cluster_k8s/__init__.py, sdcm/k8s_configs/ingress-controller/10_haproxy-kubernetes-ingress.svc.yaml, sdcm/utils/common.py, unit_tests/test_clean_cloud_resources_func.py
since we are now creating the new AWS resources
we should tag them correctly for cleanups and billing
=> feature(k8s-ingress): tag load ingress balancers

test-cases/performance/perf-regression-latency-500gb-30min.yaml, test-cases/performance/perf-regression.100threads.30M-keys.yaml
we have moved email recipient, but for some reason this branch wasn't fully updated.
this commit will change to use the group related
to performance subject from now on.
=> fix(perf_jobs): move to correct email recipient

defaults/test_default.yaml
=> improvement(monitor_branch): Switch monitor to branch-4.1

configurations/scale/scale-40-60.yaml, jenkins-pipelines/raft/gemini-8h-large-num-columns.jenkinsfile, jenkins-pipelines/raft/jepsen-with-raft.jenkinsfile, jenkins-pipelines/raft/longevity-150gb-asymmetric-cluster-12h.jenkinsfile, jenkins-pipelines/raft/longevity-1tb-7days.jenkinsfile, jenkins-pipelines/raft/longevity-200gb-48h-network-monkey.jenkinsfile, jenkins-pipelines/raft/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.jenkinsfile, jenkins-pipelines/raft/longevity-5000-tables.jenkinsfile, jenkins-pipelines/raft/longevity-50gb-asymmetric-cluster-12h.jenkinsfile, jenkins-pipelines/raft/longevity-alternator-200gb-48h.jenkinsfile, jenkins-pipelines/raft/longevity-cdc-3d-400gb.jenkinsfile, jenkins-pipelines/raft/longevity-counters-6h-multidc.jenkinsfile, jenkins-pipelines/raft/longevity-large-collections-12h.jenkinsfile, jenkins-pipelines/raft/longevity-large-partition-200k-pks-4days.jenkinsfile, jenkins-pipelines/raft/longevity-large-partition-4days.jenkinsfile, jenkins-pipelines/raft/longevity-large-partition-8h.jenkinsfile, jenkins-pipelines/raft/longevity-lwt-24h-1dis-2nondis.jenkinsfile, jenkins-pipelines/raft/longevity-lwt-24h-multidc.jenkinsfile, jenkins-pipelines/raft/longevity-lwt-500G-3d.jenkinsfile, jenkins-pipelines/raft/longevity-multi-keyspaces-60h.jenkinsfile, jenkins-pipelines/raft/longevity-mv-si-4days.jenkinsfile, jenkins-pipelines/raft/longevity-twcs-48h.jenkinsfile, jenkins-pipelines/raft/scale-40-60-cluster-test.jenkinsfile, test-cases/jepsen/jepsen_with_raft.yaml
Add new jobs for testing raft feature.
=> feature(raft): new jobs with raft enabled

sdcm/remote/kubernetes_cmd_runner.py
For now, if we run more than 1 loader command on the same dynamic loader pod class and call `send_files` method in both cases with a same destination mount path then we get duplication failure.
To make it work start using a mapping object where we store paths.
New behaviour steps:
- Return from the method not doing anything if pair src/dst already exists.
- Raise ValueError if 'dst' exists with some different 'src'.
=> fix(k8s): make dynamic loader 'send_files' work correctly

Jenkinsfile, functional_tests/scylla_operator/test_functional.py, sdcm/cluster.py, test-cases/scylla-operator/functional.yaml
* add the option to use the cloud bundle if available for
connecting with cqlsh
* added a functional test to cover it
=> feature(k8s-serverless): cloud connectivity support for cqlsh

test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
=> feature(k8s-cloud-bundle): enable for multi tenant test

jenkins-pipelines/operator/eks/longevity-scylla-operator-12h-multitenant-eks.jenkinsfile, sdcm/logcollector.py, test-cases/scylla-operator/longevity-scylla-operator-12h-multitenant-14-clients.yaml
=> ci(k8s): add new K8S longevity multitenant job with 14 clients

defaults/test_default.yaml
Use scylla-bench v0.1.14 as retry/timeout configuration issue was fixed there
=> fix(scylla-bench): Use newest version [2022.1]

test-cases/gemini/gemini-3h-with-nemesis.yaml
Former version AMI's were deleted. Have to set an updated version.
=> fix(gemini): Update Oracle version

sdcm/stress_thread.py
`CSHDRLogger` was trying to access the hdr logs, even if it's not configured to generate them at all.
generating logs full of errors, and filling sct.log with logs line like:
`Reading Scylla logs from 2022-12-25 02:37:38`
Also breaking k8s runs, cause of too many call to k8s apis
Fix: #5598
=> fix(stress_thread): disable CSHDRLogger when not needed

sdcm/cluster.py, unit_tests/test_cluster.py
we should break the logic and not try to query any table we are going to skip from adding to the returned result
Ref: https://github.com/scylladb/scylladb/issues/7186
Ref: https://github.com/scylladb/scylladb/issues/12239
=> refactor(get_any_ks_cf_list): stop fetching data from system tables

sdcm/monitorstack/__init__.py
Restore monitor for multi-tenant cluster.
Now Nemesis dashboard of every cluster is point to the last cluster.
Task: https://github.com/scylladb/scylla-cluster-tests/issues/5458
=> fix(show-monitor): support multi-tenant cluster

sdcm/remote/local_cmd_runner.py, unit_tests/conftest.py, unit_tests/test_cassandra_stress_thread.py, unit_tests/test_version_utils.py
during working on #5585, we needed to run those test on a weaker machines, and those
are the result of that work
=> fix(integration-test): fixes to stabilize integration tests

defaults/test_default.yaml
- https://github.com/scylladb/scylla-bench/pull/117
=> test(scylla-bench): version with fix for memory leak

sdcm/cluster.py
the version check didn't took enterprise into account, and assumed that for any enterprise version cqlsh supports cloud bundle, which wasn't correct.
=> fix(k8s-cqlsh): cqlsh --cloudconf check for enterprise version

functional_tests/scylla_operator/test_functional.py
seems like our `db_cluster` cluster fixture doesn't really gureently the whole cluster is up and running and we get into a state a pod isn't fully up when
we start the next test.
when running in EKS, any test that runs after `test_nodetool_flush_and_reshard` is failing, since the pod it's trying to communicate with isn't fully up yet
=> fix(k8s-functional): move resharding test to the end

jenkins-pipelines/longevity-100gb-4h-ebs-gp3.jenkinsfile
Removed newline in the jenkinsfile since it causes the pipeline to fail:
'''anyconfig.common.errors.UnknownFileTypeError: No parser found for file: file extension=yaml"]'''
=> fix(longevity-100gb-4h-ebs-gp3): Remove newline in test_config

data_dir/nemesis.yml, data_dir/nemesis_classes.yml, defaults/severities.yaml, jenkins-pipelines/workload-prioritization/longevity-sla-system-24h.jenkinsfile, sdcm/db_stats.py, sdcm/nemesis.py, sdcm/sct_events/system.py, sdcm/sla/libs/sla_utils.py, sdcm/sla/sla_tests.py, sdcm/utils/common.py, sdcm/utils/loader_utils.py, test-cases/enterprise-features/workload-prioritization/longevity/longevity-sla-system-24h.yaml, test_lib/sla.py, unit_tests/test_nemesis_sisyphus.py, unit_tests/test_sla_utils.py
Add new tests two tests for workload prioritization feature:
1. update service level using alter while load - increase shares
2. update service level using alter while load - decrease shares
3. attach another service level while load - increase shares
4. replace service level usig drop while load
5. replace service level usig detach while load
6. create 7 service levels with max shares and run load with it
Add nemeses with those tests
Task: https://github.com/scylladb/qa-tasks/issues/876
=> test(sla nemeses): add new tests for update SL

sdcm/utils/loader_utils.py
Fix for #5677 along with small refactor:
- removed `_parse_stress_cmd` as it wasn't parsing, it was hiding
- removed redundant code
=> fix(LoaderUtilsMixin): fix bugs and small refactor

test-cases/scylla-operator/kubernetes-platform-upgrade.yaml
=> fix(k8s-eks): use K8S v1.23 as basis for K8S platform upgrade

defaults/test_default.yaml
=> test_default.yaml set the monitoring bracnh to 4.2

sdcm/nemesis.py
because we have to change target node in case we
run decommission seed node, we are probably messing with the `is_seed` property, and making this nemesis fail/break when called.
Fixes: #5433
=> fix(nemesis.py): move decommission nemesis to a function

defaults/test_default.yaml
Switch mananager version to 3.0
=> fix(test_default.yaml): Switch manager version to 3.0

docs/configuration_options.md, sdcm/sct_config.py, sdcm/utils/common.py, unit_tests/test_base_version.py, upgrade_test.py, utils/get_supported_scylla_base_versions.py
=> base version multiple fixes

sdcm/nemesis.py
if removing node is alive or marked as alive in gossiper, removenode
operation have to be rejected
=> fix(removenode_nemesis): Rerun removenode if operation rejected

sct.py, sdcm/sct_runner.py, vars/createSctRunner.groovy
=> fix(sct_runner): added tags to sct runners

unit_tests/test_base_version.py
=> fix(unit-test): fix version in unit tests

data_dir/cs_multidc_mv_lcs.yaml, data_dir/cs_multidc_si_lcs.yaml, data_dir/cs_mv_si_keyspace1.yaml, internal_test_data/nemesis_selector_list.yaml, internal_test_data/nemesis_selector_list_of_list.yaml, jenkins-pipelines/longevity-double-cluster-with-schema-changes.jenkinsfile, jenkins-pipelines/longevity-multidc-network-schema-changes-12h.jenkinsfile, jenkins-pipelines/longevity-multidc-schema-topology-changes-12h.jenkinsfile, jenkins-pipelines/longevity-schema-changes-3h.jenkinsfile, jenkins-pipelines/longevity-schema-topology-changes-12h.jenkinsfile, jenkins-pipelines/longevity-topology-changes-3h.jenkinsfile, jenkins-pipelines/raft/longevity-double-cluster-with-schema-changes-with-raft.jenkinsfile, jenkins-pipelines/raft/longevity-multidc-network-schema-changes-12h-with-raft.jenkinsfile, jenkins-pipelines/raft/longevity-multidc-schema-topology-changes-12h-with-raft.jenkinsfile, jenkins-pipelines/raft/longevity-schema-changes-3h-with-raft.jenkinsfile, jenkins-pipelines/raft/longevity-schema-topology-changes-12h-with-raft.jenkinsfile, jenkins-pipelines/raft/longevity-topology-changes-3h-with-raft.jenkinsfile, sdcm/cluster.py, sdcm/nemesis.py, sdcm/sct_config.py, sdcm/tester.py, test-cases/longevity/longevity-change-cluster-size-by-2-times.yaml, test-cases/longevity/longevity-multidc-parallel-network-schema-changes-12h.yaml, test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml, test-cases/longevity/longevity-parallel-schema-changes-12h.yaml, test-cases/longevity/longevity-schema-changes-3h.yaml, test-cases/longevity/longevity-topology-changes-3h.yaml, unit_tests/test_config.py, unit_tests/test_nemesis.py, utils/lint_test_cases.sh
Trello: https://trello.com/c/JGUC6Y7Q
Adding tests and jenkins jobs for initial testing of new feature - raft
=> Raft longevities jobs

sdcm/mgmt/common.py, sdcm/utils/distro.py
Added support for linux mint 21.
=> fix(distro): added support for linux mint 21

sdcm/nemesis.py
This PR introduces commits related to the issue https://github.com/scylladb/scylla-cluster-tests/issues/5506 and should fix the failures we've been seeing in relation to `DecommissionStreamingErr` and other `*StreamingErr` nemesis. The failures came about after a `ParallelObject` timed out. This `ParallelObject` is used to run 2 functions in parallel - a trigger function and a log watching function that should interrupt the process started by the trigger function. Timeouts have been caused by the fact that the trigger functions use `nodetool` remoter commands and since the process started by these commands gets interrupted, these functions did not return to the caller before the `ParallelObject`'s own timeout kicked in. 
This PR's commits address this and an additional potential source of …
=> Fix streaming err raciness

sdcm/cluster_k8s/__init__.py, sdcm/nemesis.py, sdcm/utils/k8s/__init__.py
Add improvements for the exclusive K8S nemesis which are needed in multitenant setups.
=> Stabilize exclusive K8S nemesis

data_dir/scylla-dash-per-server-nemesis.master.json
Changed warning to false and critical to true
=> improvement(monitor): Change default annotations

sct.py
=> improvement(sct.py): Add nemesis jobs to the create_test_release_jobs

sdcm/tester.py
Truncate queries can now have an optional USING TIMEOUT parameter. This commit adds the timeout as an optional argument to the truncate_cf() method in our Tester class.
=> refactor(tester): add support for truncate timeout

sdcm/scan_operation_thread.py, unit_tests/test_scan_operation_thread.py
according to qa-task https://github.com/scylladb/qa-tasks/issues/1004 the following changes were made in full aggregation scan operations 1 remove randomizing from the aggregation scan
2 as a result - make more ERROR evens instead of WARNING
3 put a big timeout for the aggregation scan(30min by default) 
4 detect different failure reasons
5 update unit tests. coverage of sdcm/scan_operation_thread.py: 88%
=> refactor(full aggregation scan): rework full aggregation scan according  to task https://github.com/scylladb/qa-tasks/issues/1004

sdcm/tester.py
Since there are cases when we might start the YCSB stress before all nodes would be synced with the created role, and we might error like:
```
ERROR site.ycsb.db.DynamoDBClient
-com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException:
User not found: alternator (Service: AmazonDynamoDBv2; Status Code: 400;
Error Code: UnrecognizedClientException; Request ID: null; Proxy: null)
```
we now add the role with `ConsistencyLevel.ALL`, to avoid those races
Fix: #5805
=> fix(alternator): create role with ConsistencyLevel.ALL

sdcm/utils/aws_utils.py
After merge of the https://github.com/scylladb/scylla-cluster-tests/pull/5658 we create OIDC providers running on EKS backend. 
And the problem with it is that we do not cleanup created OIDC providers. 
It doesn't get automatically deleted with an associated EKS cluster too.
So, delete it explicitly to avoid limits violations.
=> improvement(k8s-eks): cleanup OIDC providers

sdcm/scan_operation_thread.py
in case of no ""Dispatching forward_request to \d* endpoints"" in query_trace events
event severity will be WARNING instead of ERROR
=> fix(FullScanAggregatesOperation): fixing forward_request validation 

sdcm/nemesis.py
For the Scylla Machine images built after https://github.com/scylladb/scylla-machine-image/commit/3ab18c9e6b09580611ab73626d4fb37c3f503b3b we need to install iptables for networking nemeses.
=> fix(cluster.py): ensure iptables is installed on DB node

sdcm/cluster_azure.py, sdcm/sct_runner.py, sdcm/tester.py
as we have gathered resources of v4, and we
don't have enought of V3, tests were failing with
lack of resources.
=> fix(azure instance type): change to use V4

test-cases/performance/perf-regression-latency-125gb.yaml, test-cases/performance/perf-regression-throughput-125gb.yaml
Use ssh transport for logs for disk-and-cache
performance tests
=> fix(disk-and-cache): use ssh transport for logs

sdcm/cluster.py
`get_nodes_status` generates (n, n*n) requests to cloud api which leads
to errors in `find_node_by_ip`.
Reduce number of cloud api calls by creating node_ip->node map and
reuse it for all nodes in `get_nodes_status` method.
refs: #5812
=> fix(nodetool_status): reduce number of api calls

sdcm/nemesis.py
In some cases, _destroy_data_and_restart_scylla will fail because there aren't enough data file to delete from non-system keyspaces. I added an except clause so that the method will continue in such cases all the same.
=> fix(_destroy_data_and_restart_scylla): continue inspite of lack of files

sct.py, sdcm/provision/azure/utils.py, sdcm/utils/version_utils.py
we now sync Azure images to multiple regions,
so now we added support to running Azure tests in multiple regions.
=> improvement(sct.py): add support to list azure images

data_dir/cs_multidc_si_lcs.yaml
=> fix(cs_multidc_si_lcs.yaml): fix create query

jenkins-pipelines/nemesis/longevity-5gb-1h-PauseLdapNemesis-aws.jenkinsfile, jenkins-pipelines/nemesis/longevity-5gb-1h-PauseLdapNemesis-azure.jenkinsfile, jenkins-pipelines/nemesis/longevity-5gb-1h-SwitchBetweenPasswordAuthAndSaslauthdAuth-aws.jenkinsfile, jenkins-pipelines/nemesis/longevity-5gb-1h-SwitchBetweenPasswordAuthAndSaslauthdAuth-azure.jenkinsfile, jenkins-pipelines/nemesis/longevity-5gb-1h-ToggleLdapConfiguration-aws.jenkinsfile, jenkins-pipelines/nemesis/longevity-5gb-1h-ToggleLdapConfiguration-azure.jenkinsfile, test-cases/nemesis/longevity-5gb-1h-SlaDecreaseSharesDuringLoad.yaml, test-cases/nemesis/longevity-5gb-1h-SlaIncreaseSharesByAttachAnotherSlDuringLoad.yaml, test-cases/nemesis/longevity-5gb-1h-SlaIncreaseSharesDuringLoad.yaml, test-cases/nemesis/longevity-5gb-1h-SlaReplaceUsingDetachDuringLoad.yaml, test-cases/nemesis/longevity-5gb-1h-SlaReplaceUsingDropDuringLoad.yaml, test-cases/nemesis/longevity-5gb-1h-SlaSevenSlWithMaxSharesDuringLoad.yaml
=> Fix enterprise individual nemesis features missing

utils/get_supported_scylla_base_versions.py
since enterprise is based on a more frequent cadence of releases of OSS, and we have LTS and short term versions, we need to support upgrade from both last LTS and last short term versions to current LTS, and for short term, we need to upgrade only from last LTS (keeping previous behavior).
=> fix(get base version): LTS vs short term versions

sdcm/nemesis.py
since Azure can schedule the restart up to 15-18min into the
future, we need to wait more time for it to finish.
Fix: #5608
=> fix(azure): add more timeout for hard reboots

sdcm/nemesis.py
as we use in different tests (like operator),
different Scylla versions, we need to check that
we are not trying to use invalid syntax for that version, because `USING TIMEOUT` for `TRUNCATE` commands
are supported from 5.2 and 2023.1.
Fixes: #5903
=> fix(nemesis.py): truncate using timeout check versions

sdcm/cluster.py
Fix wait_for_init to fail fast on scylla boot failures
this PR introduced the following changes into waiting-for node Up algorithm (wait_for_init_wrap wrapper):
by default:
1) Change Max severity for all SYSTEM_ERROR_EVENTS to CRITICAL (via add_severity_limit_rules)
2) Create a New filter *Startup failed* for all SYSTEM_ERROR_EVENTS events via EventsSeverityChangerFilter
3) yield - perform node boot
4) Remove  a New filter from  SYSTEM_ERROR_EVENTS 
5) Change Max severity for all SYSTEM_ERROR_EVENTS back to the previous (via add_severity_limit_rules)
you can pass the "critical_node_setup_events" keyword argument in the method  that wrapped by  wait_for_init_wrap
to change events and patterns  to your own one : [{'event': EventType, 'regex': r'REXEX'} or pass [] to back to the previous …
=> fix(wait_for_init): fail fast on boot failure

sdcm/sct_events/events_analyzer.py
We may get flooded with the `CRITICAL` events and each of them will trigger call of `kill_test` method where we send SIGUSR2 signal to python main thread.
At first, we should call this method only once.
At second, we will fall into endless loop of failures where we catch following old python bug: https://bugs.python.org/issue24283
So, run `kill_test` method only once to avoid endless failure loop.
=> fix(event_analyzer): call 'kill_test' only once

sdcm/nemesis.py, sdcm/utils/nemesis_utils/indexes.py
In order to avoid complicated filtering and lists of tables,
explicitely check if CF is a view or not.
This fix should help optimizing process of selecting user-tables in a nemesis.
And also fix error encountered on TWCS longevity 
[argus](https://argus.scylladb.com/test/3c965e5e-a758-4f96-9a5d-2ad5a58921bb/runs?additionalRuns[]=8d946a46-2c05-4ff2-9325-ffa6ee79ed96)
```
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4342, in wrapper
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2601, in disrupt_toggle_table_ics
self.toggle_table_ics()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2369, in toggle_table_ics
raise unexpected_exit
File …
```
=> fix(ToggleTableIcsMonkey): check if selected CF is a view

sla_per_user_system_test.py
Query 'scylla_scheduler_runtime_ms' from prometheus may return empty data despite the data exists.
It may happen if there are 'holes' in the graph. Solution is to increase the step. So if no data returned, try to increase the step and run query again.
=> fix(db stats): query scheduler runtime with different irate step

sdcm/sla/libs/sla_utils.py
Use same solution as represented in:
https://github.com/scylladb/scylla-cluster-tests/pull/6032/commits/384c334661dcef8b8e5791c7bd4aee4619cf6892
In the future we need to change feature test (sla_per_user_system_test.py) to use `sdcm/sla/libs/sla_utils.py`
=> fix(longevity): query scheduler runtime with different irate step

sdcm/nemesis.py, sdcm/utils/nemesis_utils/indexes.py
fix(indexes MV): correct filtering of primary key an collections
1. If no column found -> nemesis is skipped.
2. collection-columns cannot be used for MV so they are filtered out.
3. All columns of a primary-key should be included, when creating MV.
4. Start a stopped node, in case of getting a nemesis exception.
Fixes errors encountered in add_remove_mv nemesis.
=> Filter out collection types & get all columns for a primary-key

jenkins-pipelines/longevity-1tb-3days-STCS.jenkinsfile, test-cases/longevity/longevity-1TB-3days-authorization-and-tls-ssl.yaml
compaction strategy to Size-tiered Compaction Strategy
Based on task: https://github.com/scylladb/qa-tasks/issues/976
=> test(Longevity 1TB): Add 2 files for longevity-1TB shorten to 3 days and change to 3 nodes

sdcm/sct_runner.py
During collect-logs step in jenkins, all sct-runners are printed to the console. Because there's usually quite a lot of them, link to logs are not shown after expanding this step in jenkins job panel. This forces user to open another page to get links to logs wasting time.
Reduce verbosity of listing sct-runners in collect-logs step.
=> fix(logs): reduce verbosity for listing runners when updating tags

sdcm/nemesis.py
since we are not waiting for the node to fully
restart, we are experiencing some issues when
we try to run `nodetool` commands, and hence
adding here a proper way to make sure all the
required Scylla modules have started, before
calling next commands on the node that just
restarted.
Fixes: #6085
=> fix(nemesis): stream error wait full restart

sdcm/utils/common.py
Poller instance created on each iteration and
file registered  each time. If line is None or
not end on "\n" file is not unregistered and
Poller object could conitnue to eat memory while
will not be removed by garbage collector.
Create 1 Poller object and register/unregister
file in Poller object only per iteration
Thanks to @dkropachev for help and providing solution
=> fix(FileFollower): refactor iterator

defaults/k8s_eks_config.yaml, defaults/k8s_gke_config.yaml
=> improvement(k8s): bump the K8S version

sdcm/cluster_k8s/eks.py
For the moment we update EC2 nodes with our tags and security groups for each of the Scylla pods.
When we run just 1 Scylla cluster everything is ok. But when we run multitenant setup we duplicate these calls by number of tenants. And highest number of tenants we use is 14.
So, remove that redundancy just by memoizing the completed updates.
=> improvement(k8s-eks): Update K8S node tags and SGs only once

docs/microbenchmarking.md, jenkins-pipelines/perf-simple-query.jenkinsfile, microbenchmarking_test.py, sdcm/report_templates/results_perf_simple_query.html, sdcm/send_email.py, sdcm/utils/microbenchmarking/perf_simple_query_reporter.py, test-cases/microbenchmarking/amazon_perf_simple_query.yaml
introduse perf-simple-query Microbenchmarking test in SCT
=> test(Microbenchmarking): introduse perf-simple-query

functional_tests/scylla_operator/test_functional.py
It covers the https://github.com/scylladb/scylla-enterprise/issues/2808 case.
=> test(k8s): add 'nodetool drain' K8S functional test

sdcm/utils/remote_logger.py
For the moment when SCT calls 'stop' method of the `K8sClientLogger` class instance used for getting DB pod logs it may hang up to the `read timeout` which is `20m` now.
The same happens for each DB pod because they get processed serially. And it is very easy to get this stream hanging just because DB pod logs may not have any new data.
So, use `socket` python library to close the 'read' and 'write' channels then close stream's file descriptor.
Statistics:
In case of EKS it saves us about `20m` from max possible 60m (20m * 3 pods). 
In case of KinD (local K8S) it saves us about `40m`.
=> fix(k8s): make 'stop' close K8sClientLogger's log stream fast

sdcm/tester.py
Querying number of rows or partition may fail
if it is non paged.
Fixes: #6146
Fixes: #6146
=> fix(large partitions): use paged-queries in collect_partitions_info

sdcm/cluster.py, unit_tests/test_cluster.py
Read `/etc/scylla.d/cpuset.conf` file contents and parse it in python
instead of using 'grep' command which returns exit code '1' when no match is found.
It will allow us to avoid following false error messages:
> Command: 'grep "^CPUSET" /etc/scylla.d/cpuset.conf'
>
> Exit code: 1
>
> Stdout:
>
>
>
> Stderr:
>
>
>
=> fix(cluster.py): do not print false errors not finding 'cpu_set' value

docker/env/hydra.sh, docker/env/version, mgmt_cli_test.py, requirements.in, requirements.txt, sct.py, sdcm/cluster.py, sdcm/cluster_gce.py, sdcm/cluster_k8s/gke.py, sdcm/logcollector.py, sdcm/sct_config.py, sdcm/sct_runner.py, sdcm/send_email.py, sdcm/tester.py, sdcm/utils/azure_utils.py, sdcm/utils/cloud_monitor/resources/instances.py, sdcm/utils/cloud_monitor/resources/static_ips.py, sdcm/utils/common.py, sdcm/utils/gce_builder.py, sdcm/utils/gce_utils.py, snitch_test.py, test-cases/features/google-cloud-snitch-multi-dc.yaml, test-cases/manager/manager-regression-multiDC-gce.yaml, unit_tests/test_clean_cloud_resources_func.py, unit_tests/test_config.py, unit_tests/test_hydra_sh.py, unit_tests/test_utils_common.py
since we have feature we want to use that aren't supported
by libcloud for gce, we want to remove all usages of it.
=> fix(libcloud) - remove libcloud out of the code

sdcm/db_log_reader.py
For the moment if the `scylla debug info` cannot be taken then the appropriate SCT event doesn't get published.
But such errors are valuable to us.
So, publish 'CoreDump' events in any case.
=> fix(K8S): make coredump events be published in any case

data_dir/cs_mv_si_keyspace1.yaml, test-cases/longevity/longevity-change-cluster-size-by-2-times.yaml
Fix syntax errors in profile and c-s command parameters
=> fix(yaml): set correct c-s commands parameters

docs/faq.md
it's a command thing, that people aren't aware how to get a hold of thier SCT machines, now
we'll have a place to direct them with instructions
=> docs(faq): How can I connect to test machines in AWS ?

vars/jepsenPipeline.groovy, vars/longevityPipeline.groovy, vars/managerPipeline.groovy
commit 1: update jepsen pipeline
cover Jensen pipeline by fail faster pipeline logic
commit 2: report to argus in post
added additional reporting to Argus in post pipeline section in case an Exception happened in the pipeline itself
=> Update jepsen pipeline

sct.py, sdcm/utils/aws_utils.py, sdcm/utils/common.py
=> Revert new releng images tags checks fix

sct.py, sdcm/utils/aws_utils.py, sdcm/utils/common.py
re-introducing work done on #6249 and reverted on #6269
=> New releng images tags checks fix v2

sdcm/utils/common.py
since we started working on adding support
to images created on the releng account,
this `ami_built_by_scylla` function was
experiencing same failure as we saw on
PR #6279, but in a different function call.
I have made a small refactor on the function
`get_ami_tags`, so now it will include the
`owner_id`, and we don't need to repeat
code in `ami_built_by_scylla` call as well.
=> fix(releng account images): check owner_id

upgrade_test.py
Add "try .. except" in" truncate_entries" method. It is for preventing of stop the test on request timeout.
We have seen request timeout in rolling-upgrade tests. Example:
https://jenkins.scylladb.com/job/enterprise-2023.1/job/rolling-upgrade/job/rolling-upgrade-with-sla-test/23/
=> fix(upgrade test): not stop test on execute session timeout

sdcm/cluster.py, sdcm/db_stats.py, sdcm/sct_config.py, sdcm/utils/common.py
store ami_name_db_scylla in elastic
=> fix(elastic): store ami name

sdcm/logcollector.py
Since sometimes the yaml is sometimes required for manager related investigations, I added it to the collected log entities of the scylla node log collector
=> improvement(ScyllaLogCollector): Added scylla-manager-agent.yaml

sdcm/nemesis.py
In case the manager repair task does not finish by the time it reaches timeout, We will stop the task at the end of the nemesis, so it won't continue past it.
=> fix(disrupt_mgmt_repair_cli): stop task in case of timeout

jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min-i4i-enterprise.jenkinsfile, jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min-i4i.jenkinsfile, test-cases/performance/perf-regression.100threads.30M-keys-i4i-enterprise.yaml, test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
Add 2 new jenkins files and config yaml files for master and enterprise performance i4i testing
=> feature(perf-i4i): New perf throughput non-shard aware i4i tests

mgmt_cli_test.py
=> Multiple fixes to test_enospc_before_restore in mgmt_cli_test.py

defaults/test_default.yaml, unit_tests/test_config.py
New Gemini version was released.
Let's use it to see if it helps.
=> fix(gemini): update version to 1.8.6

sdcm/cluster_k8s/__init__.py
configuring operator with the minium/maxium of keys to pregenerate, which is x10 the number of tenants we are gonna setup.
Ref: https://github.com/scylladb/scylla-operator/pull/1202
=> feature(k8s): raise the number of Pregenerate RSA keys

sdcm/mgmt/cli.py
wait_for_status does not return task status on failure, which makes it hard to investigate where task is stuck
=> fix(cli.py): make wait_for_status be verbose

mgmt_cli_test.py
Addresses https://github.com/scylladb/scylla-cluster-tests/issues/6372
Problem with test is that it is waiting for wrong timeout event `RetryError` instead of `WaitForTimeoutError`.
It is also possible to not to wait `1200` seconds to check if task status moved
=> fix(mgmt_cli_test): make test_suspend_and_resume work properly

defaults/test_default.yaml, sdcm/monitorstack/ui.py
- feature(monitoring): test_default.yaml set monitoring branch to 4.4
- fix(monitorstack/ui): Adjust Panel locator for branch-4.4
Task: scylladb/qa-tasks#1377
Closes #6109
=> Update monitoring node branch to 4.4 and fix grafana screenshots

sdcm/tester.py
Repairing `system_auth` keyspace after altering replication strategy during node setup takes very long, making multi-dc tests to fail due timeout.
Lets add `-pr` parameter to repair and do it in parallel as advised by developers (and similar to Scylla Manager does).
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6395
=> fix(system_auth): speed up repair system_auth during node setup

jenkins-pipelines/perf-regression-throughput-shard-aware-30min-gce.jenkinsfile, jenkins-pipelines/perf-search-throughput-best-config-gce.jenkinsfile, sdcm/db_stats.py, test-cases/performance/perf-regression.100threads.30M-keys.yaml, test-cases/performance/perf-search-best-throughput-config.yaml
add perf GCE throughput test case
=> test(test): perf GCE throughput test

sct.py, sdcm/provision/azure/utils.py, sdcm/utils/aws_utils.py, sdcm/utils/common.py, unit_tests/test_base_version.py
=> Images releng account perf jobs

sdcm/scan_operation_thread.py
This PR removes implicit' tracing at FullScanAggregatesOperation
and all verification operations that use it
issue: https://github.com/scylladb/scylla-cluster-tests/issues/6368
=> fix(scan_operation_thread): Disable tracing

sdcm/scan_operation_thread.py, unit_tests/test_scan_operation_thread.py
Implement full aggregation scan verification via prometheus metric: scylla_forward_service_requests_dispatched_to_other_nodes
=> fix(scan_operation_thread): Implement full aggregation scan verification via prometheus metric

sdcm/cluster.py
After merge of the https://github.com/scylladb/scylla-enterprise/pull/3032 with instance profiles utilization the AWS creds get pulled automatically
and the workaround is not needed anymore.
Also, this workaround is not compatible with the fix for the `p11-kit-trust.so` binary fix from the `scylla-enterprise` side.
So, remove the workaround code from the SCT.
=> fix(kms): remove tmp workaround for AWS creds

artifacts_test.py, jenkins-pipelines/artifacts-ubuntu2004-fips.jenkinsfile, sct.py, sdcm/cluster.py, test-cases/artifacts/ubuntu2004-fips.yaml
=> test(artifacts): Added an ubuntu 20 with FIPS enabled scenario

sct.py, utils/get_supported_scylla_base_versions.py, vars/rollingUpgradePipeline.groovy, vars/supportedUpgradeFromVersions.groovy
=> Azure base version backend fix

sdcm/cluster_k8s/__init__.py
Scylla-operator's actions may cause the Scylla logs have following in logs:
```
sidecar/controller.go:141] syncing key 'scylla/sct-cluster-0' failed: \
can't decommision a node: \
can't decommission the node: \
agent [HTTP 500] std::runtime_error (Operation decommission is in progress, try again)
```
It is expected message but the `DatabaseLogEvent.RUNTIME_ERROR` SCT event considers it as DB error.
So, filter this kind of error events while we do decommission on K8S.
Closes: #6119
=> fix(k8s): make decommission not raise false negative errors

data_dir/nemesis.yml, data_dir/nemesis_classes.yml, sdcm/nemesis.py, sdcm/utils/context_managers.py, unit_tests/test_nemesis_sisyphus.py
=> test(1238): added a disable binary and gossip nemesis

defaults/gce_config.yaml, jenkins-pipelines/rolling-upgrade-ami-arm.jenkinsfile, jenkins-pipelines/rolling-upgrade-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-azure-image.jenkinsfile, test-cases/artifacts/centos7.yaml, test-cases/artifacts/centos8-selinux.yaml, test-cases/artifacts/centos8.yaml, test-cases/artifacts/debian10.yaml, test-cases/artifacts/debian11.yaml, test-cases/artifacts/gce-image-persistent-disk.yaml, test-cases/artifacts/gce-image.yaml, test-cases/artifacts/rhel7.yaml, test-cases/artifacts/rhel8.yaml, test-cases/artifacts/rocky8.yaml, test-cases/artifacts/rocky9.yaml, test-cases/artifacts/ubuntu2004.yaml, test-cases/artifacts/ubuntu2204.yaml, test-cases/longevity/longevity-10gb-3h.yaml, test-cases/upgrades/generic-rolling-upgrade.yaml, test-cases/upgrades/rolling-upgrade.yaml, unit_tests/test_config.py
=> Fix preinstalled scylla gce

sdcm/nemesis.py
Running `disrupt_drain_kubernetes_node_then_replace_scylla_node` nemesis we get following false error event:
```
2023-08-21 15:10:21.838: (DatabaseLogEvent Severity.ERROR) \
period_type=one-time event_id=<foo-id>: type=DATABASE_ERROR \
regex=(^ERROR|!\s*?ERR).*\[shard.*\] line_number=19827 \
node=sct-cluster-2-us-east1-b-us-east1-0
ERROR 2023-08-21 15:09:17,271 [shard 0] \
init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```
It is expected because we `replace` a Scylla pod which is in the `init` phase after disruption.
So, just filter this error event out in this nemesis.
=> fix(k8s): make `replace` op after disruption not raise false errors

mgmt_cli_test.py
Following the addition of the restore nemesis, the structure of defaults/manager_persistent_snapshots.yaml has changed drastically, but the mgmt_cli_test file wasn't adjusted to the new structure. I modified mgmt_cli_test to read the yaml properly.
=> fix(mgmt_cli_test): properly read the persistent manager snapshot yaml

microbenchmarking_test.py, sdcm/report_templates/results_performance.html, sdcm/report_templates/results_performance_baseline.html, sdcm/results_analyze/__init__.py, sdcm/utils/microbenchmarking/perf_simple_query_reporter.py
1 appends the backend and node type to the existing subject of Perf Emails that support
differend backends
2 move Prometheus stats to the bottom of perf emails body
=> refactor(performance): Perf emails

functional_tests/scylla_operator/test_functional.py
Operator `v1.10` runs cleanups [1] on each of the old nodes after adding a new one like it is recommended by the Scylla documentation [2]. So, cover this functionality with the functional test.
[1] scylladb/scylla-operator/pull/1294
[2] https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-node-to-cluster.html
=> test(k8s): add new functional test to cover DB node cleanups

defaults/test_default.yaml, sdcm/logcollector.py, sdcm/monitorstack/ui.py, sdcm/utils/docker_utils.py
- test(test_default.yaml): set monitoring version to 4.5
- fix(monitorstack/ui.py): Fix panel name for 4.4/4.5 monitoring
Closes #6408
=> Update monitoring branch and Fix Overview screenshot

configurations/manager/manager_operations.yaml, data_dir/nemesis.yml, data_dir/nemesis_classes.yml, jenkins-pipelines/manager/longevity-50gb-ManagerOperationsMonkey-3days.jenkinsfile, jenkins-pipelines/manager/longevity-alternator-ManagerOperationsMonkey-3h.jenkinsfile, jenkins-pipelines/manager/longevity-cdc-100gb-ManagerOperationsMonkey-4h.jenkinsfile, jenkins-pipelines/manager/longevity-counters-ManagerOperationsMonkey-3h.jenkinsfile, jenkins-pipelines/manager/longevity-large-partition-ManagerOperationsMonkey-8h.jenkinsfile, jenkins-pipelines/manager/longevity-large-partition-asymmetric-cluster-ManagerOperationsMonkey-3h.jenkinsfile, jenkins-pipelines/manager/longevity-mv-si-ManagerOperationsMonkey-24h-gce.jenkinsfile, sdcm/nemesis.py, unit_tests/test_nemesis_sisyphus.py
=> Manager longevities and corrupt then manager repair nemesis

data_dir/nemesis.yml, data_dir/nemesis_classes.yml, unit_tests/test_nemesis_sisyphus.py
One nemesis was missed in data_dir/nemesis.yml.
It caused to failure of `test_list_all_available_nemesis`
=> fix(unit test): test_list_all_available_nemesis missed nemesis

sdcm/nemesis.py
This change fixes an issue where switching a compaction strategy on an
already existing table would result in the new compaction strategy
attempting to use old compaction values, which could be completely
incompatible with said compaction strategy. Now the strategies contain
default values for each per scylla docs.
Fixes #6153
=> fix(sdcm/nemesis.py): Provide default values for compaction strategies

data_dir/nemesis.yml, unit_tests/test_nemesis_sisyphus.py
=> fix(unittests): align `test_list_all_available_nemesis` with actual list

sdcm/stress_thread.py
when `stop_test_on_failure=False` is used by nemesis code, it was affecting only the return value check to not raise critical events, but if any log line that was raising critical events would still be raised and stop the test in the middle.
this change propgates the `stop_test_on_failure` into the log parsing code to act inlined with the rest of the error handling logic
Ref: #6543
=> fix(stress_thread): `stop_test_on_failure` affect log parsing

sdcm/sct_config.py, sdcm/utils/common.py
since we load a lot of configuration files in test case linting we can easily get into request limit of AWS
and failing like the following:
```
12:24:01  Traceback (most recent call last):
12:24:01    File "..././sct.py", line 765, in _run_yaml_test
12:24:01      config = SCTConfiguration()
12:24:01    File ".../sdcm/sct_config.py", line 1655, in __init__
12:24:01      self[key] = convert_name_to_ami_if_needed(param, self.region_names)
12:24:01    File ".../sdcm/utils/common.py", line 1951, in convert_name_to_ami_if_needed
12:24:01      if images := sorted(
12:24:01    File ".../boto3/resources/collection.py", line 81, in __iter__
12:24:01      for page in self.pages():
12:24:01    File ".../boto3/resources/collection.py", line 171, in pages
12:24:01      for page in pages:
12:24:01 …
```
=> fix(test-case-lint): add cache to convert_name_to_ami_if_needed

sct.py, sdcm/utils/common.py
extend sct.py 'list-resources', 'clean-resourses'
to support AWS placement groups
=> feature(sct.py): list/delete aws palecement groups

sdcm/nemesis.py
since `KillNemesis` was reporting any currently running nemesis during teardown as skipped, reporting looks like it passes regardless if the teardown was cause of end of the test, of cause of critical even stopping the test.
this change would report the nemesis as failure if there are any critical events, and otherwise it would be reported as skipped.
=> fix(KillNemesis): report killed nemesis based on critical events

configurations/scale/scale-180-200.yaml, configurations/scale/scale-40-60.yaml, configurations/scale/scale-450-500.yaml, jenkins-pipelines/scale-40-60-cluster-test.jenkinsfile, jenkins-pipelines/scale-450-500-cluster-test.jenkinsfile, jenkins-pipelines/scale-base-test-15-25-cluster-test.jenkinsfile, longevity_test.py, test-cases/scale/scale-cluster.yaml
=> refactor scale test

README.md
add a paragraph explaining how to use OKTA
created aws profile
Closes: #6609
=> fix(README.md): explain AWS OKTA usage

configurations/kms-ear.yaml, jenkins-pipelines/EaR-longevity-kms-20gb-6h-multidc.jenkinsfile, jenkins-pipelines/EaR-longevity-kms-50gb-1d.jenkinsfile, jenkins-pipelines/perf-regression-latency-30min-with-ear-kms.jenkinsfile, jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min-i4i-enterprise-with-ear-kms.jenkinsfile, test-cases/longevity/longevity-encryption-at-rest-20GB-6h-multidc.yaml, test-cases/longevity/longevity-encryption-at-rest-50GB-1day-authorization-and-tls-ssl.yaml
Commits:
- `ci(kms): add 1d longevity CI job for running EaR+KMS features`
- `ci(kms): add 6h multiDC longevity CI job for running EaR+KMS features`
- `ci(kms): add perf CI jobs for running EaR+KMS features`
=> Add new EaR+KMS CI jobs

sdcm/fill_db_data.py, upgrade_test.py
This reverts commit 33d277df841551ab9eba7e4cf0fc2174b9cf719e. Getting node stats was taking too much time causing failing tests due to timeout.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6623
=> Revert "fix(upgrade): not fail on truncated entries timeouts"

jenkins-pipelines/perf-regression-latency-650gb-grow-shrink.jenkinsfile, sdcm/nemesis.py, test-cases/performance/perf-regression-latency-650gb-grow-shrink.yaml
This commit adds a new performance test for GrowShrinkClusterNemesis
=> improvement(performance): add perf growShrink test multi-AZ

configurations/disable_cluster_health_check.yaml, jenkins-pipelines/perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile, performance_regression_test.py, sdcm/report_templates/results_latency_during_ops_short.html, sdcm/results_analyze/__init__.py, sdcm/send_email.py, sdcm/tester.py, test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml, upgrade_test.py, vars/perfRegressionParallelPipeline.groovy
=> Backport latency performance during rolling upgrade

sdcm/cluster.py, sdcm/nemesis.py, sdcm/utils/sstable/sstable_utils.py
=> improvement(kms): add check for KMS encryption fact

sdcm/nemesis.py
Running the KMS nemesis we may get following error in one of the scylla-bench stress commands:
```
Stress command completed with bad status 1: 2023/10/03 16:01:04 \
Error during truncate: seastar::rpc::remote_verb_error (filesystem error: stat f
```
And following one in DB logs:
```
sstable - Error while linking SSTable: /var/.../tmp_encrypted_table.*.db \
to /var/.../tmp_encrypted_table-.*/snapshots/.*.db: \
std::filesystem::__cxx11::filesystem_error (error system:2, \
filesystem error: stat failed: No such file or directory \
[/var/.../tmp_encrypted_table-.*.db])
```
It started happening after addition of the `-validate-data` flag to the `write` stress command which does `truncate` in this case.
The addition of the `-validate-data` flag is required to make the data validation also work …
=> fix(kms): reduce severity for possible `scylla-bench` failures in KMS nemesis

configurations/gce/z3-highmem-88.yaml, jenkins-pipelines/artifacts-ubuntu2204-gcp-z3-preview.jenkinsfile, sdcm/utils/gce_utils.py, vars/artifactsPipeline.groovy, vars/getJenkinsLabels.groovy
Ref: http://goto.google.com/z3-user-guide
=> test(artifacts): new case for gcp z3-highmem-88 instance type

sdcm/cluster_k8s/mini_k8s.py
=> improvement(k8s-local-kind): cache chaos-mesh docker images

sdcm/cluster_k8s/mini_k8s.py
Before this change the host machine of the `KinD` tool had connectivity only to the `service` K8S IP addresses.
For testing of the `scylla-operator-v1.11.0` new features we need to have the network connectivity also to pod IPs.
So, do following things to satisfy it:
- Remove old route which was using wrong subnet and wrong gateway.
- Add new routes for pod IP subnets per kind K8S node.
- Delete redefinition of the `_refresh_instance_state` method which was needed only to mitigate the pod network unavailability.
- Start using the `start_scylla_pods_ip_change_tracker_thread` thread for local K8S setups because it becomes needed when we use pod IPs.
=> improvement(k8s-local-kind): make pod network be available for host

configurations/gce/preview_instance.yaml, jenkins-pipelines/artifacts-ubuntu2204-gcp-preview.jenkinsfile, sdcm/utils/gce_utils.py, vars/artifactsPipeline.groovy, vars/getJenkinsLabels.groovy
=> New artifact test for GCP

vars/perfRegressionParallelPipeline.groovy
since we now have a performance regression test that does latency test during upgrade nodes operation,
we had the need to add an automatic calculator to get the base version, based on the repository URL passed as a parameter to the test.
=> improvement(perf regression pipeline): add base version calculator

sdcm/cluster_k8s/__init__.py
For the moment we use 'required' podAntiAffinity rules in the ScyllaCluster objects to make sure Scylla pods of a same DB cluster get scheduled on separate nodes.
The problem is that `Scylla cleanup` pods get scheduled using the same affinity rules making it require at least one K8S Scylla node be without Scylla pods.
Also, our functional test for checking that `cleanup` functionality is not stable due to it, because it utilizes all 4 K8S Scylla nodes.
So, allow `Scylla cleanup` pods be scheduled anytime by using the `preferred podAntiAffinity rules` in single-tenant test runs. Keep old `required` way only for the multi-tenant test runs because, in this case, Scylla pods use less than 50% of K8S Scylla nodes resources.
=> fix(k8s): use `preferred podAntiAffinity rules` in `ScyllaCluster` K8S objects

functional_tests/scylla_operator/test_functional.py, sdcm/utils/k8s/__init__.py
The `test_add_new_node_and_check_old_nodes_are_cleaned_up` K8S functional test
creates additional DB pod and cleans it up in the end of itself in any case.
So, make it save logs in case of failure for ease of debugging.
Also, stop `ParallelObject` threads which may run till the end of the test run, which is not expected thing to happen.
=> improvement(k8s): make `check Scylla cleanups` K8S func test save logs

functional_tests/scylla_operator/test_functional.py
The `v1.11.0*` scylla-operator allows to configure manual multiDC DB cluster
using the new `externalSeeds` config option where we can specify IP addresses of the nodes from another DC/cloud.
So, cover it's basic functionality in the `quasi-multidc` functional K8S test by making a DB cluster out of the 2 separate `ScyllaCluster` K8S resources created by the same Scylla-operator.
=> test(k8s-func): add func test with quasi multiDC setup

vars/jepsenPipeline.groovy
like we have for almost all other pipelines,
first build is kind of a dry run to load
the pipeline's parameters.
doing the same in Jepsen, since the job
being now created by the `create_test_release_jobs` function does trigger the 1st build, and
in Jepsen case, it fails.
=> improvement(jepsenPipeline): not run first build

jenkins-pipelines/longevity-custom-d1.jenkinsfile, test-cases/longevity/custom_d1.yaml
PR for tracking tested workflows
See specific commits messages for details and results link
=> Custom workflow d

upgrade_test.py
ignoring those unsuppressed exceptions,
till both ends of the upgrade would have scylladb/scylladb#14681
Ref: scylladb/scylladb#14681
Ref: scylladb/scylladb#14882
=> fix(rolling-upgrade): ignore RPC `unknown exception`

sdcm/utils/common.py
in #6734 `filter_gce_by_tags` was broken and reverted the work done in d2a6d0742eb5562cab692ef4b38902e32d8d14a1
this commit merges them both into something that can work a bit better
=> fix(clean-resources): fix `filter_gce_by_tags`

sdcm/nemesis.py
Recently merged PR (https://github.com/scylladb/scylla-cluster-tests/pull/6773) add support to the multiple K8S clusters and updated the way how the `flush and reshard` nemesis works on K8S. For now it broken with the following error:
```
File "%path%/sdcm/nemesis.py", line 5069, in wrapper
File "%path%/sdcm/nemesis.py", line 1381, in disrupt_nodetool_flush_and_reshard_on_kubernetes
self._verify_resharding_on_k8s(current_cpus, dc_idx)
File "%path%/sdcm/nemesis.py", line 1293, in _verify_resharding_on_k8s
for node in reversed(qualified_nodes):
TypeError: 'generator' object is not reversible
```
So, fix this typo.
Also, reduce the required number of needed Scylla cores to be 7 to cover more instance types such as …
=> fix(k8s): fix `flush and reshard` nemesis for K8S

sdcm/cluster.py
Packages installation fail from time to time during node setup.
Decided to add retrying for that.
Refs: https://github.com/scylladb/scylla-cluster-tests/issues/6317
=> fix(install packages): retry install when fail

data_dir/large_collections.yaml, defaults/test_default.yaml, longevity_test.py, sdcm/provision/scylla_yaml/scylla_yaml.py, sdcm/sct_config.py, sdcm/sct_events/group_common_events.py, test-cases/longevity/longevity-large-collections-12h.yaml, unit_tests/test_scylla_yaml.py
This PR changes some parameters for testing large collections and adds verification methods for them. Also some filters for warnings were added.
=> [QA-894] Change large collections parameters and add validations

upgrade_test.py
since in older versions i.e. 2023.1 and lower, we
can use `scylla sstable` tools yet, we should revert to use the old `sstabledump` tool
=> fix(upgrade-test): enable back the usage of sstabledump

upgrade_test.py
change in #6828 has got the logic of version selection wrong, and was choosing the wrong tool for any OSS version
=> fix(rolling-upgrade): fix version logic of sstabledump usage

sdcm/db_stats.py
this function is broken when offline installer test are run and we don't have the version in Argus,
with this change, skip getting the version from RPMs/DEBs and use the scylla command line only
Fixes: #6388
=> fix(get_scylla_versions): handle offline installer case

Jenkinsfile, defaults/k8s_eks_config.yaml, defaults/k8s_gke_config.yaml, defaults/k8s_local_kind_config.yaml, sdcm/cluster_k8s/__init__.py
=> improvement(defaults): use latest `5.2.x` as default scylla version

cql_test.py
The thing is broken and doesn't succeed when run
Also, while at it, make it log its result in a nicer way
=> Fix cql_test sample test

sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/tester.py
With current code we won't get K8S logs gathered in case of any failure in `deploy_k8s_eks_cluster` or `deploy_k8s_gke_cluster` functions which get called by the Tester class.
So, to make K8S logs gathered in all cases split those `deploy_*` functions into two: `init_*` and `deploy_*`.
Then use both in the Tester class.
The `init` ones will be used for saving objects to `k8s_clusters` attr and the `deploy` ones will be used for resources provisioning and setup.
It will allow the `tearDown` method find `k8s_clusters` and trigger gathering of K8S logs.
=> fix(k8s): guarantee K8S logs gathering

configurations/tablets.yaml
The tablets feature also needs consistent-topology-changes to be enabled
=> feature(tablets_config): Add config file for tablets experimental

sdcm/tester.py
ALTER the test system tables with encryption, only if `user_info_encryption` isn't being use, when it used all the test table would be using EaR out of the box.
Ref: https://github.com/scylladb/scylla-enterprise/issues/3684
=> refactor(alter_test_tables_encryption): use only when really needed

sdcm/utils/k8s/__init__.py
Current code copies the `scylla-operator` binary used for running the `must-gather` command from a K8S pod.
The problem with it is that if we use Arm arch on K8S then that binary won't work on the SCT runner which is always x86-based.
So, copy needed binary from a local tmp container created only for the `copy binary` operation.
As a result, we will be able to run the `must-gather` binary using any possible arch on K8S.
=> improvement(k8s): copy `must-gather` binary from local docker container

configurations/kms-ear.yaml
those are generating too much logs for us, we could introduce them as need to investigate specific things
=> fix(kms-cases): remove kms logging

sdcm/cluster.py
Seems like by doing so SCT code was masking an issue the scylla docker was wrongly configured the setup needed for cqlsh to work with specifying host and port
Ref: https://github.com/scylladb/scylladb/issues/16329
=> fix(run_cqlsh): stop specifying host and port on call to cqlsh

.github/issue_template.md, .github/pull_request_template.md
* remove some unneeded checks
* restructe issue to be similar to Argus template
=> fix(templates): update issues and pull-requests templates

sdcm/nemesis.py
instend of pop nemesis of of the list, and assuming we'll have enough of them for the run, we are now cycling ontop of that list for ever.
all the other parameters, like `nemesis_seed` and `nemesis_multiply_factor` still apply for making the list, but now we don't need to fine tune cases base on the length they are running
=> fix(nemesis): cycle the nememsis_list

jenkins-pipelines/artifacts-ubuntu2204-gcp-preview.jenkinsfile
=> fix(preview_instance.yaml): Fix typo in file name

sla_per_user_system_test.py
PR https://github.com/scylladb/scylla-cluster-tests/pull/6999 was not enough. Missed there a fix name in workload result
=> fix(sla test): fix SL batch name

unit_tests/test_base_version.py, utils/get_supported_scylla_base_versions.py
update the code, for the OSS upgrade path for 2024.1
=> fix(get_supported_scylla_base_versions): OSS upgrade version for 2024.1

test-cases/scale/scale-cluster.yaml
=> Scale test - reduce the load also during prepare

sdcm/utils/nemesis_utils/indexes.py
change the code to using execute parameters, and stop converting the values given from the driver to strings since in the process we are generating wrong values like for example in timestamp, extra precision digits which scylla fails on.
we should be using named placeholder as much as we can (same as we tell our users to do)
Fixes: #7032
Ref: https://python-driver.docs.scylladb.com/stable/getting-started.html#passing-parameters-to-cql-queries
=> fix(verify_query_by_index_works): pass values as is

sct.py, sdcm/utils/compaction_ops.py, unit_tests/provisioner/conftest.py
for getting the nemesis list that `SisyphusMonkey` is going to create you can use the following command:
```
hydra nemesis-list --backend aws --config test-cases/PR-provision-test-docker.yaml
```
and it would print out the list of nemesis, base on the configuration files that was used
=> feature(hydra): introduce `nemesis-list`

sdcm/cluster.py
In case a node very busy, it fails to open connection. As result fail to receive the keyspaces list.
Add retry for nodetool call.
Also increase session connect timeout and session default request timeout
=> fix(get keyspaces):  add retry on 'nodetool cfstat'

sdcm/commit_log_check_thread.py
fix(jepsen): run commit_log_check_thread in jepsen
to run commit_log_check_thread
in jepsen pipleine need to perform
seastar-cpu-map.sh via sudo
=> fix(jepsen): run commit_log_check_thread in jepsen

sdcm/cluster_k8s/__init__.py
Starting with the `v1.11.0` version of the scylla-operator the TLS feature gets enabled by default.
At first, we do not need it.
At second, it makes the scylla-manager operations fail [1].
So, disable it explicitly if we do not expect it to overwrite the default setting.
[1] https://github.com/scylladb/scylla-manager/issues/3679
- https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-eks-mgmt-restore/10
=> fix(k8s): Always define `AutomaticTLSCertificates` with bool value in K8S

sdcm/provision/scylla_yaml/scylla_yaml.py, unit_tests/test_scylla_yaml.py
The option had been recently added to scylla and it's good to be able to have it in append_scylla_yaml
=> fix(scylla_yaml): Add tablets_initial_scale_factor

sdcm/cluster_k8s/eks.py
For the moment we set tags only those which will be applied to VMs which will use a specific launch template.
But it is also possible to set tags for the a launch template itself. 
In our case it will allow to filter exisitng launch templates for the purpose of the resource cleanup.
So, set tags to launch templates.
=> improvement(k8s-eks): set tags to K8S-EKS launch templates

sdcm/utils/common.py
Recently we started using `launch template` resources in EKS deployments.
And we don't delete it after test runs.
So, add cleanup code for that kind of resources.
=> improvement(k8s-eks): cleanup AWS launch templates created by EKS

sdcm/commit_log_check_thread.py
according to issue https://github.com/scylladb/scylladb/issues/17069 cylla_commitlog_disk_total_bytes can exceed the limit during/after replay. For a short bit. added gate for 1 min per shard, per request for 10 min range  with 1 sec discreteness
- pass run https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/longevity-10gb-3h-test/58/execution/node/163/log/
failed_ run (to test calculation logic ) https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/longevity-10gb-3h-test/59/execution/node/163/log/
=> fix(commit log): add exceeding time gate

sdcm/utils/cloud_monitor/resources/instances.py
Cloud resources report shows wrong state of Azure instances when are stopped.
Fix by showing real status instead of hardcoded one.
=> fix(cloud-report): fix Azure's instances state

upgrade_test.py
Issue: https://github.com/scylladb/scylla-enterprise/issues/3804 
Workaround for this issue - try to retry query count of rows after upgrade/rollback if it failed and check if it solves the issue.
Another change - session timeout.
Now it is defined:
`session.default_timeout = 60.0 * 5`
But actually the query failed after 60 sec.
I added timeout in the query and want to check if it will have an impact. May be we have a problem with `session.default_timeout `
=> improvement(upgrade): retry on count from truncated table

README.md
Updare README according to network configuration change, presented here https://github.com/scylladb/scylla-cluster-tests/pull/6575
=> improvement(readme): add info about using of AWS network configuration

sdcm/sla/sla_tests.py
Current workaround with restarting binary protocol to update connections' scheduling group couldn't be done on all nodes because of running nemeses, which resulted in problems like https://github.com/scylladb/scylla-enterprise/issues/2572
This patch changed the method to use recently created REST API endpoints https://github.com/scylladb/scylla-enterprise/pull/3242 (`/service_levels/switch_tenants` and `/service_levels/count_connections`) to trigger scheduling groups update and to validate them.
**This PR to run correctly requires https://github.com/scylladb/scylla-enterprise/pull/3242 to be in scylla and none of the 2023.x 2024.x have that PR.**
=> sla_tests: use SL REST API instead of binary protocol on/off workaround

utils/build_system/create_test_release_jobs.py
the introduction of reconfiguring jenkins job, had a side effect of dropping the pipeline arguments from the job configuration. since the template we were using is mostly empty, and assume the the first run of the job would update the pipeline parameters (and thier defaults).
so now the code that the configuration, and merge it with the suggest template from the code, so the needed part that should be updated would be updated as expected.
=> fix(create_test_release_jobs): reconfig_job shouldn't drop data

artifacts_test.py
noticed the typo of "Passable" when reading the logging message. and take the opportunity to revise this warning to be more readable.
=> improvement(artifacts_test.py): revise the error message

sdcm/nemesis.py, sdcm/tester.py, sdcm/utils/replication_strategy_utils.py
=> Fixing manager restore nemesis region issue

sdcm/cluster.py
Ref: https://github.com/scylladb/scylla-enterprise/issues/3896
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-10gb-3h-test/63
=> improvement(kms): disable encryption fact check

upgrade_test.py
Ref: https://github.com/scylladb/scylladb/issues/17659
Ref: https://github.com/scylladb/scylla-tools-java/issues/338
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-rolling-upgrade-azure-image-test/7
=> fix(azure): make upgrade work on Azure

sdcm/utils/issues.py
since we are hitting the rate-limit of the API calls too often we are doing the following things:
* stop all retries - since on rate limit it would just gonna hang for us
* import the call sequence - so it would be one api call per issue, and not 3
* cache the client at the class level, so we won't be doing login multiple times
it don't handle all the issue we might have with it, but it can elivate some of the hanging it cause for our tests
=> fix(issues): handle call to github api a bit better

sdcm/utils/issues.py
since we are still running out of our limits alot, we shouldn't raise error events on those
=> fix(issues): don't raise errors from rate-limit failure

functional_tests/scylla_operator/test_functional.py
Do following changing to the K8S functional tests:
- `test_deploy_helm_with_default_values`
Use selector for scylla pods filtering out the cleanup ones.
Catch namespace deletion timeouts and suppress raising error.
Enable this test for ARM setup.
- `test_scylla_yaml_override`
Add 5s sleeps between configmap updates and triggers of rollout restart.
It will allow us to avoid concurrency when configmap is not yet updated at rollout trigger moment.
=> fix(k8s): stabilize K8S functional tests

.github/pull_request_template.md
=> Typo in PR template

jenkins-pipelines/oss/tablets/longevity-multi-keyspaces-60h.jenkinsfile, jenkins-pipelines/oss/tablets/scale-5000-tables.jenkinsfile
- [scylla-staging/valerii/vp-longevity-5000-tables-with-tablets#5](https://argus.scylladb.com/test/13e30d7f-1fed-44f0-b26c-1a96fdb23564/runs?additionalRuns[]=2458e37b-ef6c-4f25-806e-fd96c8da9b95)
- [scylla-staging/valerii/vp-longevity-multi-keyspaces-with-tablets#3](https://argus.scylladb.com/test/7fd0596d-6ee0-4ecb-ad9f-43b168205f4e/runs?additionalRuns[]=792ab8f1-0a58-484b-b293-d22338cd6b8d)
=> ci(tablets): add scale (multi-ks, multi-cf) CI jobs for testing tablets

sdcm/utils/remote_logger.py
Closes: #6191
- [scylla-staging/valerii/vp-longevity-scylla-operator-3h-gke#157](https://argus.scylladb.com/test/d9adf1f6-d051-4f88-bc59-59d6fb07bfa7/runs?additionalRuns[]=aab50f3a-7028-47f5-b7f4-d2d53a42282b)
=> fix(k8s): catch "'NoneType' object has no attribute 'fileno'" errors

jenkins-pipelines/performance/scylla-enterprise/perf-regression-throughput-shard-aware-gce-z3-enterprise.jenkinsfile, sdcm/cluster.py, sdcm/utils/gce_utils.py, test-cases/performance/perf-regression.100threads.100M-keys-z3-enterprise.yaml, vars/perfRegressionParallelPipeline.groovy, vars/perfSearchBestConfigParallelPipeline.groovy
Including most important changes done in order to run Z3 tests.
=> test(perf): add GCE Z3 instance test

configurations/scale-up/c3-standard-22-lssd.yaml, configurations/scale-up/c3-standard-44-lssd.yaml, configurations/scale-up/c3-standard-8-lssd.yaml, configurations/scale-up/c3-standard-88-lssd.yaml, configurations/scale-up/scale-up-base.yaml, jenkins-pipelines/scale-up-c3-standard-lssd.jenkinsfile, performance_scale_up_test.py, sdcm/report_templates/results_scale_up.html, sdcm/send_email.py
We want to test write and rebuild operations time for different sizes of the same instance type.
(modify config files param to select proper instance type test)
=> test(scale-up): test write and rebuild perf

jenkins-pipelines/oss/longevity/longevity-gce-custom-d1-worklod2-hybrid-raid.jenkinsfile, sdcm/stress/latte_thread.py, test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml
=> test(customd1): add `custom_d1/workload2` test

artifacts_test.py, sdcm/logcollector.py, utils/scylla_doctor.py
Add scylla-doctor to artifact test, run it and validate json output file.
Task:
https://github.com/scylladb/qa-tasks/issues/1617
=> improvement(artifact): add scylla-doctor

utils/scylla_doctor.py
Fixes of failures in the docker artifact test after
Scylla Doctor run:
1.  error: 'Unable to locate package wget'
Fix: update 'apt repo' before installation
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7418
2. one collector failed due to missed 'ethtool' package - install it during 
Scylla Doctor installation
3. Scylla Docker does not collect Scylla cluster logs. Skip assert of existing
'scylla_cluster.tar.gz' file
4. Ignore failure of 2 collectors: StorageConfigurationCollector and 
PerftuneSystemConfigurationCollector.
Looks like it should be skipped for docker backend - issue
https://github.com/scylladb/field-engineering/issues/2288
- Add unit tests to cover my changes (under `unit-test/` …
=> fix(scylla doctor): few fixes in docker artifact test

sdcm/cluster.py, sdcm/cluster_docker.py, sdcm/cluster_k8s/__init__.py, sdcm/commit_log_check_thread.py, sdcm/tester.py
In order to speed up test setup, made setup of db cluster, loaders,
monitors and oracle cluster to configure in parallel.
Verification and Argus related work was put into one-off background
thread.
Removed dependency to db_cluster for loaders as was not used in code (if needed we can add it in different place).
refs: https://github.com/scylladb/scylla-cluster-tests/issues/7242
=> improvement(setup): Parallelize setup

.github/search_commits.py, .github/workflows/add-label-when-promoted.yaml
Similar to Scylla-dtest adding the logic of labeling PRs when merged, and adding/removing the backport labels
=> feature(github action): add-label-when-promoted to manage backport labels

sdcm/utils/docker_utils.py, unit_tests/test_utils_docker.py
in cases there a problematic internet connection, or other issues that might slow down the build, it's not clear to a user what's going on during that time.
with this change we'll have progress on the sct.log
Closes: #7334
=> feature(docker-backend): log progress of building/pulling

sdcm/utils/alternator/api.py
since we are looking on multiple keyspaces, it wasn't enough to handle the case of non-existing keyspaces, but also on existing keyspace and table, and empty responses
=> fix(alternator): improve the lookup logic of `salted_hash`

.github/mergify.yml
now that we have backports opertional with mergify for scylla based releases branches,
adding also those branches for the process
=> feature(mergify): add perf and manager branches

sdcm/cluster_aws.py
in some cases the API for identify there spot termination might retutn empty result, the code should keep on try to call it an not break from the thread
=> fix(cluster-aws): handle spot termination better

sdcm/utils/aws_kms.py
Number of the aliases is limited by the AWS quota. It happens that running lots of CI jobs in parallel we get following error:
```
An error occurred (LimitExceededException) when calling \
the CreateAlias operation: Aliases per key quota \
for this account in this region is 50, current usage is 60.
```
So, reduce it's probability by making KMS logic pick up the next key for rotation based on the number of aliases.
Related: #7611
=> improvement(kms): use KMS keys for rotation with fewer aliases

sdcm/db_log_reader.py
so far we picked the build-id from the current running scylla executable in some cases this fails, since the backtrace we are reading might be from diffrent version of scylla.
instead we start reading it from the same log file we are reading the backtrace from, so it would be in sync and remove the room for getting the wrong one
Ref: scylladb/qa-tasks#951
=> fix(db_log_reader): take build-id from logs

jenkins-pipelines/qa/hydra-cleanup-cloud.jenkinsfile, sct.py, sdcm/utils/aws_kms.py
=> feature(aws): add sct command for cleaning up old AWS KMS aliases

vars/byoScylladb.groovy
=> fix(byo): use proper github user for scylla-pkg repository

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
Loaders latency are high and loader looks stuck while running reads with validate data in [longevity-large-partition-200k-pks-4days-gce-test](https://argus.scylladb.com/test/ 66ff9e4a-0655-4bba-89f4-e4eb2d78691d/runs?additionalRuns[]=d6a65fc4-e495-47bb-a9f4-a4534a40f264) S-b docker command failed with exit status 137:
```
t:2024-06-13 12:57:30,940 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG Killed
t:2024-06-13 12:57:30,941 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR
Error executing command:
'sudo  docker exec scylla-bench -workload=sequential -mode=read ... -validate-data ';
Exit status: 137
```
This commit changes loader instance type to stronger 'e2-standard-16' type
- Add unit tests …
=> fix(loader): increase loader type in large-partition gce test

.github/workflows/cache-issues.yaml
so we can trigger as needed manually from github action UI adding `workflow_dispatch` to the workflow
Ref: https://docs.github.com/en/actions/using-workflows/
=> feature(cache-issues.yaml): add way to manually trigger workflow

vars/longevityPipeline.groovy, vars/rollingUpgradePipeline.groovy
=> ci(byo): make `byo_scylla_repo` param description be more informative

.github/mergify.yml
=> improvement(mergify): add support for the new `branch-2024.2` branch

jenkins-pipelines/master-triggers/sct_triggers/no_tablets_weekly_trigger.xml
Weekly trigger some jobs of 'no_tablets' folder.
refs: #7655
refs: #7655
=> test(no-tablets jobs): add no-tablets jobs weekly trigger

sct.py
When there's no result after longevity/performance tests it often fails to send email at all. This is very unconvinient as there's no information about failed test in user's email inbox - missing it.
Fix by always sending an email when there's no results file.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7309
=> fix(email): send email for failed tests

vars/perfRegressionParallelPipeline.groovy
- BYO: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/perf-regression-latency-30min-with-ear-kms/7
- no BYO: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/perf-regression-latency-30min-with-ear-kms/8
=> ci(perf): add BYO ScyllaDB support for the perf pipeline

jenkins-pipelines/performance/branch-perf-v15/Perf-Regression/scylla-release-perf-regression-latency-shard-aware-1TB-test.jenkinsfile, jenkins-pipelines/performance/branch-perf-v15/Perf-Regression/scylla-release-perf-regression-throughput-non-shard-aware-test.jenkinsfile, jenkins-pipelines/performance/branch-perf-v15/Perf-Regression/scylla-release-perf-regression-throughput-shard-aware-test.jenkinsfile, jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-throughput-shard-aware-i4i.jenkinsfile, jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml, jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml, utils/build_system/create_test_release_jobs.py
some of the merged tests, they names wasn't matching the orignal jobs name.
also the code for reconfiguring jobs seem to be causing issues and doesn't really update the triggers or jobs as intended.
now it's just overide every job configuration when it's running
=> fix(perf-tests): fix names and triggers of jobs

defaults/test_default.yaml
=> defaults/test_default.yaml: update Manager default to use 3.3.0

vars/createTestJobPipeline.groovy
by mistake there was comment left, hence breaking the if statment, and failing the pipeline.
=> fix(createTestJobPipeline): uncomment closing of an if

utils/build_system/create_test_release_jobs.py
when reconfiguring pipeline jobs, if we don't copy those over, the next run, would run without the properites and would fail on all bunch of reasons, running without the default configuration it expected
it was broken recently, when trying to make sure free style jobs are getting updated, and the pipeline based one were recreated from scratch as well, on every update.
=> fix(create_test_release_jobs): copy over actions/properties

.github/mergify.yml
now that we have branch-6.1 available,
we should be able to backport into with mergify
=> feature(mergify): add support for branch-6.1

sdcm/reporting/tooling_reporter.py
=> fix(sdcm/reporting): ruff ignore broad exception

vars/byoScylladb.groovy, vars/longevityPipeline.groovy, vars/perfRegressionParallelPipeline.groovy, vars/rollingUpgradePipeline.groovy
=> ci(byo): use defaults specific to branch-6.1

sct_ssh.py
when using this command before monitoring stack is ready it suggest the user too soon a url, that isn't ready.
this change introduced by default a check for connectivity and the user would see a progress indication until the port is open.
this change also fixes the usage of the correct ssh keys matching the current ones used (it was wrongly hard-code before)
Fixes: scylladb/scylla-cluster-tests#7336
=> fix(hydra-tunnel): wait for connectivity

README.md
Update the SCT readme with explanation how to config AWS using OKTA in the local SCT git repo
=> improvement(documentation): config AWS locally

sdcm/utils/common.py
so far this function was look just into the main account, and not into the scylla image account, now that we want to use this feature, to lookup monitor images, it need to be checking both to find an AMI by its name.
=> fix(convert_name_to_ami_if_needed): lookup on both accounts

jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-simple-query-weekly-microbenchmark_arm64.jenkinsfile
cause of this missing comma the pipeline is running
=> fix(enterprise-perf-simple-query): add missing comma

README.md, install-prereqs.sh
- clearer instructions for `clean-resources`
- add missing env var export for gce
- fixes for `install-prereqs.sh`
=> improvement(documentaion): update readme and prereqs

sdcm/cluster.py
Dashboard json remains in the git repo after a test run. This removes it after it is no longer needed.
- tested locally
=> improvement(monitoring): remove dashboard json after upload

sdcm/cluster_gce.py
since we are creating the instances with retries, we sometimes
get into case the first attempt failed cause of api quota issues
and on the retry we fail to create since instance already exists
this change is remove the limit to retry delete instance only when it's spot
and it delete any type of instance on case of failures related to spot or
to quota issues.
Fixes: #7261
=> fix(gce): delete instance in cases of retries

unit_tests/test_cassandra_stress_thread.py
since we run into issues c-s around snappy compression we should have a set of tests that can help us identify those kind of issues
=> test(integration): add compression tests for c-s

jepsen_test.py, test-cases/jepsen/jepsen.yaml
=> [branch-2024.1] Fix jepsen

sdcm/utils/csrangehistogram.py
When c-s load runs without fixed/throttle, the histogram data with WRITE-rt/READ-rt (latency) tags is not created in the HDR file.
In this case all statistics will be reported with WRITE-st/READ-st (throughput) tags. It is according to the cassandra-stress code.
So if rows with the hdr_tag is not found - try to find data with another tag
=> fix(hdr file): latency from HDR file for untrottled load

sdcm/provision/aws/capacity_reservation.py
`nemesis_grow_shrink_instance_type` was introduced, but on the capacity_reservation logic we didn't took it into account
Fixes: #8514
=> fix(capacity_reservation): take `nemesis_grow_shrink_instance_type` into account

sdcm/cluster.py
cause of it missing, offline installer test ontop of it failed
=> fix(oel8): new oel8 image was missing tar

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml, jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml, jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml, jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml
Start triggering tablets tests every third week
=> test(trigger): trigger tablets performance tests

unit_tests/test_config.py, unit_tests/test_config_get_version_based_on_conf.py
=> fix(tests): fix integration tests

.github/mergify.yml
also remove it for scylla 5.2, since it's out of support
=> ci(.github/mergify.yml): start backports process for scylla 6.2

vars/byoScylladb.groovy, vars/longevityPipeline.groovy, vars/perfRegressionParallelPipeline.groovy, vars/rollingUpgradePipeline.groovy
=> fix(byo): use proper BYO `scylla-6.2` defaults after branching from master

multiple_dc_test.py, pyproject.toml, sdcm/audit.py, sdcm/cluster_k8s/mini_k8s.py, sdcm/coredump.py, sdcm/node_exporter_setup.py, sdcm/provision/aws/instance_parameters.py, sdcm/provision/common/builders.py, sdcm/provision/scylla_yaml/scylla_yaml.py, sdcm/sct_events/handlers/__init__.py, sdcm/sct_events/handlers/schema_disagreement.py, sdcm/snitch_configuration.py, sdcm/utils/adaptive_timeouts/__init__.py, sdcm/utils/adaptive_timeouts/load_info_store.py, sdcm/utils/benchmarks.py, sdcm/utils/common.py, sdcm/utils/k8s/__init__.py, sdcm/utils/k8s/chaos_mesh.py, sdcm/utils/raft/__init__.py, sdcm/utils/remote_logger.py, sdcm/utils/sstable/sstable_utils.py, unit_tests/test_alternator_streams_kcl.py
Enable following rules:
- F821, `undefined-name` -> `Undefined name {name}. {tip}`
- F823, `undefined-local` -> `Local variable {name} referenced before assignment`
=> improvement(ruff): enable `F821` and `F823` rules

sdcm/stress/latte_thread.py
Current code prints first 2 lines of the stderr when a latte stress command fails.
It is always useless lines because latte writes a lot of stuff into the stderr.
So, change error parsing the following way:
- print out "last" 2 lines in a common case with failures
- print out full "panic" message if it appears.
- [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload1-hybrid-raid#25](https://argus.scylladb.com/test/2f38fb93-05bb-4949-8822-31707d5d9e76/runs?additionalRuns[]=ba8feab1-50ef-41b8-b0a2-dc93157bba02)
=> improvement(latte): improve latte errors parsing

docker/env/hydra.sh
In order to be able to run hydra docker on MacOS using docker desktop, there is a need to mount the docker.sock differently and not trying to impersonate the running user to be able to run inside the docker. This is a problem with the macOS permissions. instead we run as 'root' and mouting the homedir of the user as HOME.
=> feature(hydra on MacOS): Add support to run hydra on MacOS

sct.py
This commit adds a flag to the `show-logs` command which allows it to
update Argus with links that have not been submitted to it, either by
network error or other issue preventing `store_logs_in_argus` from
running. The function has been updated to support `update` parameter,
which will fetch the run from Argus and look for missing log links.
Fixes #7583
=> improvement(sct.py/show-logs): Add --update-argus argument

mgmt_cli_test.py
Related to https://github.com/scylladb/scylla-manager/issues/4087
Due to the issue with error message for enospc restore case, message verification check should be skipped until the issue is resolved.
=> fix(manager): skip error msg verification for test_enospc_before_restore

defaults/test_default.yaml, docker/latte/README.md
=> ci(latte): bump latte version to `0.28.0-scylladb`

sct.py
Hydra list-resources show resources by test-id or user for all backend supported by sct. Usually the only one backend type is used. Searching on another backends could take time.
Added support to provide to hydra list-resources optional parameter backend-type which specify on which backend search resources and list them.
by default backend-type is all, and run as previously, list resources from all backends
if provide specific backend type [aws, gce, azure, eks, docker] list resources display resources only on specific backend
=> feature(list_resources): list resources per backend

sdcm/cluster.py, utils/scylla_doctor.py
changes in 1568a5a51886199affe308c2b90f3c9ae159a63b, by mistake broke few minor logic with installation of java for offline installers and with setup of scylla doctor.
this commit addresses those, and fix the logic around both
=> fix(artifacts): fixes around amazon 2 support removel

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml, jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-tablets.jenkinsfile
Add Jenkins pipeline for predefined throughput steps test with tablets
=> test(gradual): add pipeline for gradual test with tablets

sdcm/scan_operation_thread.py, unit_tests/test_scan_operation_thread.py
This reverts commit ab00b95f3d4bf925dad0f2a2b5058034ae372eea. This change is not part of enterprise branch.
=> Revert "fix(FullScan): rename forward_service to mapreduce_service"

vars/perfRegressionParallelPipeline.groovy
this pipeline was never used for multidc cases, and was missing multiple feature that exists on longevity pipeline, like handling correctly the regions, and quoting correctly possible space seperated pipeline parameters
Fixes: #9278
=> fix(perfRegressionParallelPipeline): add correct support for multidc

mgmt_cli_test.py
While we currently have a test for `restore` benchmarking, the configurations are set up in such a way that the results from different runs are not comparable. Ideally, restoring 1TB of data should take twice as long as restoring 0.5TB. However, due to the use of different instance types in each manager configuration, this expectation is not met. Additionally, ScyllaDB's autocompaction can interfere with the restore process, so the test should explicitly disable it to ensure more consistent and deterministic results.
Argus results
[500GB run](https://argus.scylladb.com/tests/scylla-cluster-tests/33b6f7ab-1221-44f2-9b98-e9d2327b10e2)
|  | restore time [s] | download bandwidth [MiB/s/shard] | l&s bandwidth [MiB/s/shard] | repair time [s] | total [s] |
| --- | --- | --- | --- | --- | --- |
| …
=> Make `test_restore_benchmark` results comparable

.github/CODEOWNERS
=> Create CODEOWNERS for manager code/folders

jenkins-pipelines/qa/devops-cloud-resources-report.xml
Adding Maciej from operations to mail recipients.
=> fix(devops-cloud-resources-report): Add Maciej to email recipients

sdcm/cluster_k8s/__init__.py
Issue for Operator scylladb/scylla-operator#989 was fixed here scylladb/scylla-operator#1613. There is no need anymore to patch scylla cluster. Moreover, patching was causing additional rollout of the cluster which was taking extra execution time. Discussion here: scylladb/scylla-operator#2223
=> fix(cluster_k8s): Added scylla args to helm instead of patching cluster

configurations/t3_micro.yaml
=> fix(configurations/t3_micro.yaml): fix pre-commit line ending

commitlint.config.js
=> feature(commitlint.config.js): add `chore` to the context list

renovate.json
- update it to run weekly
- enable scan of github actions workflows
=> chore(renovate): update to renovate.json 

artifacts_test.py, upgrade_test.py
raise errors where it should be raised but don't
=> fix(sct): raise errors where it should be raised

sdcm/cluster.py
This commit brings updated argus client version that supports storing dc and rack information, and a change to submit it.
Fixes scylladb/qa-tasks#1657
(cherry picked from commit a7e68c8c571b3056341e386993c9cc0d60ca32dc)
=> [Backport 2023.1] improvement(sdcm/cluster): Store dc and rack information in argus

sdcm/utils/loader_utils.py
since counters are not supported with tablets we should skip it, and error out if such test is using counters
Ref: https://github.com/scylladb/scylladb/issues/18180
=> fix(_run_all_stress_cmds): skip and warn about using counters

test-cases/artifacts/azure-image.yaml, test-cases/artifacts/centos7.yaml, test-cases/artifacts/centos9-selinux.yaml, test-cases/artifacts/centos9.yaml, test-cases/artifacts/debian11.yaml, test-cases/artifacts/debian12.yaml, test-cases/artifacts/gce-image-persistent-disk.yaml, test-cases/artifacts/gce-image.yaml, test-cases/artifacts/rhel7.yaml, test-cases/artifacts/rhel8.yaml, test-cases/artifacts/rocky8.yaml, test-cases/artifacts/rocky9-selinux.yaml, test-cases/artifacts/rocky9.yaml, test-cases/artifacts/ubuntu2004.yaml, test-cases/artifacts/ubuntu2204.yaml, test-cases/artifacts/ubuntu2404.yaml
Switch GCE and Azure based artifacts tests from ssh to syslog-ng logs transport.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/8532
=> improvement(artifacts): switch to syslog-ng logs transport

utils/cloud_cleanup/aws/clean_aws.py
In case of pipeline failure where CR's are used (or any other failure in CR cleanup within the test) we need to cancel them as soon as possible.
Rule:
There never should be active capacity reservations without allocated machines that are older than 15 minutes
(it's enough time to create machines with it).
Added CR cancellation to our periodic cleanup scripts.
refs: https://github.com/scylladb/qa-tasks/issues/1846
=> improvement(cleanup): add capacity reservation cleanup

data_dir/scylla-dash-per-server-nemesis.master.json
Combine cassandra-stress, cql-stress and latte metrics in single panels based on the metrics types.
- [scylla-staging/valerii/vp-perf-regression-latency-650gb-during-rolling-upgrade#19](https://argus.scylladb.com/tests/scylla-cluster-tests/8965fe98-4564-4c05-bd7c-6d3c20ffd546)
=> improvement(monitor): refactor benchmarking tools panels

sdcm/tombstone_gc_verification_thread.py, sdcm/utils/sstable/sstable_utils.py, test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml, test-cases/longevity/longevity-large-partition-8h.yaml
Assuming some deletion nemeses ran on these tests,
The tomstone-gc-verification thread can validate its deletion.
=> improvement(tomstone-gc): Added a verification to large-partitions tests

jenkins-pipelines/oss/tier1/longevity-150gb-asymmetric-cluster-12h.jenkinsfile, jenkins-pipelines/oss/tier1/longevity-1tb-5days-azure.jenkinsfile, jenkins-pipelines/oss/tier1/longevity-50gb-3days.jenkinsfile, jenkins-pipelines/oss/tier1/longevity-large-partition-200k-pks-4days-gce.jenkinsfile, jenkins-pipelines/oss/tier1/longevity-multidc-schema-topology-changes-12h.jenkinsfile, jenkins-pipelines/oss/tier1/longevity-mv-si-4days-streaming.jenkinsfile, jenkins-pipelines/oss/tier1/longevity-schema-topology-changes-12h.jenkinsfile, jenkins-pipelines/oss/tier1/longevity-twcs-48h.jenkinsfile
- They were wrongly moved, instead of copied in 0d17ca5f49d778fa6fbe231d1c7519e7259592c7
- Completely my mistake :/
=> fix(tier1): Reintroduce tier1 tablet tests

sdcm/nemesis.py
Scylla stopped taking snapshots of MVs when snapshotting a base table - presented in commit https://github.com/scylladb/scylladb/pull/21433/commits/9645a0414dbf4f41e0ce612b485b09c16a408f42. But in the nemesis we expect that the snapshot will include the MVs of base table. Change SCT according to Scylla.
Fixes: https://github.com/scylladb/qa-tasks/issues/1860
=> fix(nemesis): disrupt_snapshot_operations expects MV in snapshot

upgrade_test.py
some part was using `decorate_with_context` and some part of the test were using `with` statements.
for clarity, and less indentation, switch most of them to use `decorate_with_context`
some were left in the main body of the test, no to create now too complex backports (since we have many small changes in this test for the upcoming 2025.1 version, don't want to complex it further)
also add using `ignore_raft_topology_cmd_failing`, since those error can happen every time a node is stopped, and we do see those from time to time:
```
raft_topology - topology change coordinator fiber got error std::runtime_error
(raft topology: exec_global_command(barrier) failed with seastar::rpc::closed_error
(connection is closed))
```
Ref: https://argus.scylladb.com/tests/scylla-cluster-tests/b9778057-a255 …
=> refactor(upgrade_test): align filter events into decorators

sdcm/nemesis.py
Nemesises DecommissionNode, TerminateAndReplace and TerminateAndRemoveNode remove node and then add new node - the node is data token node. Fix the nemesises to add same token type node do restore same number of appropriate token type nodes
- [Passed job 1](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/ZeroNodes/job/Nemesises/job/longevity-5gb-1h-DecommissionMonkey-aws-test/4/) - job marked as failed by Kill Nemesis
- [Passed job 2](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/ZeroNodes/job/Nemesises/job/longevity-5gb-1h-DecommissionStreamingErrMonkey-aws-test/5/) Nemesis are passed.
- Update the Readme/doc folder …
=> fix(nemesis): add node with same token type after topology operation

configurations/performance/latte-perf-regression-latency-650gb-upgrade.yaml, jenkins-pipelines/performance_staging/perf-regression-latency-650gb-during-rolling-upgrade-latte.jenkinsfile, sdcm/loader.py, sdcm/stress/latte_thread.py, unit_tests/test_latte_thread.py
- [scylla-staging/valerii/vp-perf-regression-latency-650gb-during-rolling-upgrade#25](https://argus.scylladb.com/tests/scylla-cluster-tests/fe762ffb-6b00-40a6-9876-660ab9c111b2)
=> feature(latte): add support for HDR histograms

sdcm/cluster.py
Simplified the function a bit:
- Documented (well, CoPilot did)
- No need to check all nodes, bail on the first node that isn't OK
- Better exception message - which node is not UN
Saw in some SCT run the exception and thought it'd be a good idea to improve it. It was:
```
2025-02-26 21:22:02.102: (DisruptionEvent Severity.ERROR) period_type=end event_id=00e1cff5-3848-4836-bf83-cd1ad350b743 duration=3m31s: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-2025-1-db-node-48848648-1 [18.235.56.139 | 10.12.26.152] errors=Not all nodes joined the cluster
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5515, in wrapper
File …
```
=> refactor(check_nodes_up_and_normal) - return a better exception message

test-cases/longevity/longevity-100gb-4h.yaml, test-cases/longevity/longevity-10gb-3h.yaml
* This was 100GB-4h AWS run, I just used different pipeline name
* Failed on unrelated issue, but racks are clearly visible in Argus
=> improvement(sanity): Use virtual racks

sdcm/cluster.py
Refactor methods `check_nodes_up_and_normal`, `get_nodes_up_and_normal` `get_node_status_dictionary` by building dictionary where key is node ip address and value is dict with node status. This allow get node status by ip from new dict and remove extra iterations by dcs
- [Test is done](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-100gb-4h-test/7/), test marked as failed due to coredump, all changed functionality was passed
- [Test 2 is done](https://argus.scylladb.com/tests/scylla-cluster-tests/99a83df3-31c3-4a06-a1c2-907831221c0d) - test marked as failed due to add_remove_dc nemesis issue, all changed functionality was passed …
=> fix(check_up_normal): refactor check_nodes_up_and_normal

configurations/performance/cql-stress-6gb-8-col-i4i-mini-test-throughput.yaml, defaults/test_default.yaml, test-cases/features/elasticity/elasticity-90-percent-with-nemesis.yaml, test-cases/features/limit-streaming-io.yaml, test-cases/features/repair-based-operations/longevity-1TB-12h-GrowShrink.yaml, test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml, test-cases/longevity/longevity-cdc-100gb-4h.yaml, test-cases/longevity/longevity-cdc-100gb-8h-multi-dc-large-cluster.yaml, test-cases/longevity/longevity-change-cluster-size-by-2-times.yaml, test-cases/longevity/longevity-counters-multidc.yaml, test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml, test-cases/longevity/longevity-topology-changes-3h.yaml, test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml, test-cases/performance/perf-regression-latency-650gb-elasticity.yaml, test-cases/performance/perf-regression-latency-650gb-grow-shrink.yaml, test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Related to #10241 
* Remove default values from testcases
* No need to specify option that is the same as in default
=> improvement(test_default): Set nemesis_add_node_cnt to 3

.github/workflows/build-docker-image.yaml, requirements.in
this new action can build a docker image when requirements are changed and push this new docker image information back into the PR
=> feature(hydra): action to build docker image automatically

docs/configuration_options.md, jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-simple-query-weekly-microbenchmark_arm64-write.jenkinsfile, jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-simple-query-weekly-microbenchmark_x86_64-write.jenkinsfile, jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml, microbenchmarking_test.py, sdcm/provision/aws/instance_parameters.py, sdcm/sct_config.py, test-cases/microbenchmarking/amazon_perf_simple_query_ARM.yaml, test-cases/microbenchmarking/perf_simple_write_option.yaml
since we are trying to bisect issue with write path, it's a good time to start running those cases on a weekly basis as well
=> feature(perf-simple-query): add write path configurations

data_dir/nemesis.yml, data_dir/nemesis_classes.yml
These lists were not updated with recent changes.
Updated them by running unit tests.
=> fix(nemesis.yml, nemesis_classes.yml): update the list

unit_tests/test_kafka.py
Run test_01_kafka_cdc_source_connector test with tablets disabled in the test keyspace, until the CDC is supported with tablets.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10387
=> fix(unit-tests): run kafka cdc connector test with tablets disabled

artifacts_test.py, defaults/test_default.yaml, utils/scylla_doctor.py
This commit refactors the scylla_doctor.py module, making it use
official `scylla-doctor` package from the repo file in case of normal
installation and also adding non-root installation option to the module.
The offline-nonroot installation has following flow:
* Get latest scylla-doctor package from s3
* Download it to the node
* Update the config
* Run it as usual after updating paths
Fixes scylladb/qa-tasks#1682
=> refactor(artifacts_tests): Refactor scylla-doctor install

docs/configuration_options.md
=> improvement(docs): update sct config opts doc

defaults/docker_images/scylla-bench/values_scylla-bench.yaml
=> fix(scylla-bench): use older version of scylla-bench

vars/longevityPipeline.groovy
This PR modifies `longevityPipeline.groovy` to better organize and document pipeline parameters.
- Grouped parameters into logical sections  using separator for better UI.
- Existing pipeline functionality remains the same.
- Added few missing description part.
- Added separator for following sections headers. Cloud Provider Configuration,Stress Test Configuration,ScyllaDB Configuration,Provisioning Configuration,Post Behavior Configuration,SSH Configuration,Manager Configuration,Email and Test Configuration,Kubernetes Configuration,Miscellaneous Configuration,BYO ScyllaDB Configuration
The difference between existing UI and UI can be found in below screenshot.  Job UI itself can be found in below URL
- [x ] https://jenkins.scylladb.com/job/scylla-staging/job/LakshmipathiGanapathi/job/test …
=> improvement(vars/longevityPipeline.groovy): Make use of separator plugin

sdcm/nemesis.py
=> improvement(nemesis): Remove deprecated Nemesis

.github/actions/run-validation/action.yml, .github/workflows/check-generated-code-updates.yaml, configurations/nemesis/longevity-5gb-1h-nemesis.yaml, data_dir/nemesis.yml, data_dir/nemesis_classes.yml, docs/configuration_options.md, jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithIptableRuleNemesis-docker.jenkinsfile, jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithProcessSignalNemesis-docker.jenkinsfile, sdcm/sct_config.py, templates/test_config/template-longevity-5gb-1h-base.yaml.j2
since we have multiple part of configuration and documentation which need to be updated via code generation tools this new workflow would be executing the tools, and updating the user on top of the PR, if they are not up-to-date
=> feature(actions): check generated code is up-to-date

.pre-commit-config.yaml, pyproject.toml
Extract the configuration from precommit into project wide configuration
=> improvement(pyproject): Add autopep8 configuration

jenkins-pipelines/performance/branch-perf-v15/scylla-master/daily-master-performance-aws-sanily-trigger.xml
Create trigger for shor performance tests that will be triggered with everu new ami
=> test(trigger): trigger for daily short performance tests

test-cases/performance/perf-regression-latency-650gb-upgrade.yaml, test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Run operations and upgrade performance tests with cassandra-stress 3.17.5 version
=> fix(performance): use docker with 3.17.5 in operations/upgrade

sdcm/remote/kubernetes_cmd_runner.py
The change adds check to ensure that the watcher process object exists, before accessing its 'closed' attribute. This prevents potential "NoneType object has no attribute 'closed'" exceptions when the process is not yet initialized.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10562
=> fix(k8s-pod-watcher): check for uninitialized watcher in conditionals

cluster_configuration_tests.py, sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/cluster_azure.py, sdcm/cluster_baremetal.py, sdcm/cluster_docker.py, sdcm/cluster_gce.py, sdcm/provision/scylla_yaml/cluster_builder.py, sdcm/sct_provision/aws/cluster.py
=> improvement(cluster): Remove pylint disables

sdcm/nemesis.py
=> improvement(nemesis): Remove pylint disables

artifacts_test.py, sdcm/logcollector.py, sdcm/sct_events/base.py, sdcm/tester.py, sdcm/utils/action_logger.py, sdcm/utils/log.py, upgrade_test.py
Introducing `actions` log for tracking testing process: what actions SCT does to cluster. This will help to quickly find out test steps taken by SCT e.g. restarting, corrupting data, aborting etc.. It will also log all error/critical events (basic details only: event type, severity, event_id and node). This log should contain only the most important actions, not to blurry test flow with too much information.
It works by appending JSON lines to `actions.log` and also to `sct.log` (in simpler, textual form). Intention of JSON lines is to be easily parsable for further visualisation, AI integration and still keeping human-readable form.
This commit introduces it only in limited scope - with intention to expand it to other test cases and threads (like Nemesis, full scan thread etc.)
refs: …
=> improvement(logging): added 'actions' log

vars/artifactsPipeline.groovy, vars/byoLongevityPipeline.groovy, vars/managerPipeline.groovy, vars/rollingUpgradePipeline.groovy
Make use of separator to group related options under specific sections.
Following pipeline are updated:
artifactsPipeline,byoLongevityPipeline,managerPipeline and
rollingUpgradePipelines
=> improvement(Pipeline): Make use of separator plugin

defaults/docker_images/cql-stress-cassandra-stress/values_cql-stress-cassandra-stress.yaml
This version contains fix for coordinated omission latency measurement.
refs: https://github.com/scylladb/qa-tasks/issues/1861
=> chore(cql-stess): update to 0.2.3

test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml, test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml, test-cases/longevity/longevity-parallel-schema-changes-12h.yaml, test-cases/longevity/longevity-twcs-48h.yaml
* From 3 to 6 and lower instances to keep the workload similar
* Also lower instances for cases where number of nodes while introducing racks
=> fix(tier1): Increase number of nodes for tier 1 tests

pyproject.toml, sdcm/cluster_k8s/__init__.py, sdcm/mgmt/cli.py, sdcm/nemesis.py, sdcm/remote/libssh2_client/__init__.py, sdcm/results_analyze/__init__.py, sdcm/utils/common.py, sdcm/utils/sstable/sstable_utils.py, upgrade_test.py, utils/cloud_cleanup/aws/clean_aws.py, utils/cloud_cleanup/azure/clean_azure.py, utils/cloud_cleanup/gce/clean_gce.py, uv.lock
introducing those mainly for PLW0211
also includes fixes for PLC0206, PLR1714, PLW1508
Ref: https://docs.astral.sh/ruff/rules/#warning-plw
Ref: https://docs.astral.sh/ruff/rules/bad-staticmethod-argument/
Ref: https://docs.astral.sh/ruff/rules/invalid-envvar-default/
Ref: https://docs.astral.sh/ruff/rules/dict-index-missing-items/
Ref: https://docs.astral.sh/ruff/rules/repeated-equality-comparison/
=> feature(ruff): enable pylint Warning (PLW) checks

sdcm/provision/scylla_yaml/auxiliaries.py, sdcm/sct_provision/aws/cluster.py
those there since we moved to pydantic v2, but we didn't noticed them
=> fix(PydanticDeprecatedSince20): left over from pydantic upgrade

.pre-commit-config.yaml
=> improvement(pre-commit): Add create-nemesis-yaml and create-nemesis-pipelines

sdcm/utils/common.py
since #11229 was merged, the reported urls into Argus, are not direct links to s3 objects, and this code part now need to figure out how to download them, when a test needs that (for example resotre of a monitor stack).
this commit introduce a way for the download to identify it's not s3 url, and follow the redirect to get the correct url to use for the actual s3 download
=> feature(S3Storage): support downloading via Argus links

utils/cloud_cleanup/aws/clean_aws.py
we reach a point we hit the limits of those in on region we found out lot of them that were create long ago, and no one it tracking them.
this commit will new clear those up from all region, only ones tagged `keep:alive` or currently attached to a network interface won't be touched, all other would be deleted
=> feature(cloud_cleanup): cleanup unattached security groups

sdcm/sct_config.py, sdcm/utils/aws_peering.py, sdcm/utils/common.py, utils/copy_ami_to_all_regions.py, vars/getJenkinsLabels.groovy
this commit introduce more supported region in AWS:
- eu-west-3
- ca-central-1
we need them so we can spreate some specific tests across region, to avoid capacity issue, amond other things.
Ref: scylladb/scylla-cluster-tests#11198
=> feature(aws): add more supported regions

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
They were wrongly decreased in d2c75580b88ce15cb9db515dbebf3e12c01f1919
=> fix(longevity): Increase back node size in longevity-large-partition-200k_pks-4days.yaml

defaults/docker_images/scylla-bench/values_scylla-bench.yaml
- [BUGFIX] `-help` flag now prints to `stdout` instead of `stderr`
- No testing needed as this changes only the output
=> chore: upgrade s-b to 0.2.5

defaults/docker_images/latte/values_latte.yaml
Main change is following:
- Use latest `scylla-rust-driver` version - `1.3`
=> ci(latte): bump latte version to `0.31.1-scylladb`

sdcm/utils/decorators.py
When adding a node on GCE, it is possible to fail with a ServiceUnavailable error.
Example:
https://argus.scylladb.com/tests/scylla-cluster-tests/5250ec8a-9da2-42d1-ba14-59ea9b197d75
```
2025-07-18 15:11:40.759: (DisruptionEvent Severity.ERROR) period_type=end event_id=525892bd-4f1e-4bdb-99e9-61dc90ff2994 duration=44m54s: nemesis_name=ReplaceServiceLevelUsingDropDuringLoad target_node=Node longevity-10gb-3h-master-db-node-5250ec8a-0-4 [35.231.22.170 | 10.142.0.73] (rack: RACK1) errors=503 POST https://compute.googleapis.com/compute/v1/projects/sct-project-1/zones/us-east1-c/instances/longevity-10gb-3h-master-db-node-5250ec8a-0-11/setLabels: Internal error. Please try again or contact Google Support. (Code: '63A3581DD0D87.8F51A3B.2830B271')
File …
```
=> feature(skip_on_capacity_issues): check for gce ServiceUnavailable errors

utils/copy_ami_to_all_regions.py
when copying image in other accounts, we need to make sure premissions are copied as well, otherwise we can't use them from our main testing account
=> feature(copy_ami_to_all_regions): support copy permissions

configurations/performance/latency-decorator-error-thresholds-steps-ent-tablets.yaml, configurations/performance/latency-decorator-error-thresholds-steps-ent-vnodes.yaml
Set manually max throughput for throughput tests.
Task: https://github.com/scylladb/qa-tasks/issues/1934
=> improvement(performance): set max throughput

defaults/docker_images/latte/values_latte.yaml
Main changes are following:
- Add support for the `SERIAL` and `LOCAL_SERIAL` consistency types needed for testing `LWT` feature.
- Use latest scylla-rust-driver version - `1.3.1`
=> ci(latte): bump latte version to `0.32.0-scylladb`

vars/provisionResources.groovy, vars/rollingUpgradePipeline.groovy, vars/runSctTest.groovy
seems like we forgot this stage for the upgrade tests this should speed them up a bit, and align it with the rest the test in SCT
=> fix(rollingUpgradePipeline): add missing provision stage

sdcm/coredump.py
If coredumpctl fails for whatever reasson, `_get_core_by_pid` will return `None` and updating the core info will fail.
Add extra logging.
Fixes https://argus.scylladb.com/tests/scylla-cluster-tests/dca84a90-29fb-4c72-8414-b8f5eff01a66
```
2025-07-24 23:58:31.514: (ThreadFailedEvent Severity.ERROR) period_type=one-time event_id=9c1c2fbe-22a6-45b6-b66d-552452d8b500: message='NoneType' object has no attribute 'get'
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/coredump.py", line 120, in run
self.main_cycle_body()
~~~~~~~~~~~~~~~~~~~~^^
File "/home/ubuntu/scylla-cluster-tests/sdcm/coredump.py", line 133, in main_cycle_body
new_cores = …
```
=> improvement(coredump): add logging if coredumpctl fails

vars/perfRegressionParallelPipelinebyRegion.groovy
This change fixes two issues introduced in PR https://github.com/scylladb/scylla-cluster-tests/pull/11574 that caused test failures.
1.  Rolling Upgrade Test: The 'scylla_ami_id parameter was being passed incorrectly. It should be 'null' to ensure the test uses the correct AMI.
2.  Microbenchmark AMD Test: The wrong image ('x86') was being used for this test. The fix ensures the correct AMD image is used.
Additionally, since the microbenchmark test is short, it no longer needs to wait for another run to complete and can now be started directly with 'master:latest'.
=> fix(trigger): correct job parameters for rolling upgrade and microbenchmark tests

sct.py
For 'unit-tests' and 'integration-tests'. Useful for debugging dependencies within tests.
=> feature(sct.py): Allow multiple tests to be specified

vars/createTestJobPipeline.groovy
Add support for creating performance jobs for branch-perf-v17 in createTestJobPipeline.groovy
- Added trigger and job creation logic for branch-perf-v17.
- Updated parameterizedCron schedule to include branch-perf-v17.
=> improvement(create job): add branch-perf-v17 to create job pipeline

sdcm/utils/sstable/sstable_utils.py
run_tombstone_gc_verification_thread overloads db node cache by dumping and loading large sstable dump. This causes scylla errors like scylladb/scylladb#23743. Fixing it by dumping on local disk (/var/tmp) instead of memory (/tmp). And by using jq instead of grep, to avoid extensive memory consumption.
Fixes: #10937
To apply this fix, the pull-request of https://github.com/scylladb/scylla-cluster-tests/pull/10993 should be reverted.
It should be verified that the issues found in https://github.com/scylladb/scylladb/issues/23743 and in https://github.com/scylladb/scylladb/issues/25104 are not reproduced.
- Testing reproduction in [longevity-large-partition-200k-pks-4days-gce-test](https://argus.scylladb.com/tests/scylla-cluster-tests/3ba730a4-df07-4af1-b1ee-2d43554431e7)
- Add New …
=> fix(sstable_utils): Use local disk instead of memory for sstable dump

sdcm/remote/remote_cmd_runner.py
we have some situation where we need to connect to ssh server that doesn't have none auth (i.e. no password or key setup)
fabric or paramiko are not handling it out of the box, but there an issue in paramiko that show few example of how to get it working
this change is overriding `fabric.Connection.open` to apply this change when ever we identify it's needed
Ref: https://github.com/paramiko/paramiko/issues/890
=> feature(fabric): support connection to ssh server with none auth

jenkins-pipelines/master-triggers/sct_triggers/tier1-custom-time-trigger.xml
- None, it is a trigger, it is hard to test
=> fix(tier1-trigger): Fix longevity-harry name

defaults/docker_images/ycsb/values_ycsb.yaml, sdcm/ycsb_thread.py
this commit also update the entrypoint and the command to point to the helper script now available inside the images
=> feature(ycsb): update offical scylla dockerhub build

renovate.json
make sure only the needed updated gets the `New Hydra Version` labels
=> fix(renovate): fix labeling

sdcm/provision/aws/capacity_reservation.py, unit_tests/provisioner/conftest.py, unit_tests/provisioner/test_azure_region_definition_builder.py, unit_tests/test_clean_cloud_resources_func.py, unit_tests/test_config.py, unit_tests/test_config_get_version_based_on_conf.py, unit_tests/test_hydra_sh.py, unit_tests/test_scylla_yaml_builders.py, unit_tests/test_utils__operator__multitenant_common.py
without it, it might have some situation it would be missing
=> fix(unittests): make sure test_id is define for a test

defaults/manager_versions.yaml, unit_tests/test_sdcm_mgmt_common.py
=> fix(manager): up SM DB version to the latest 2025.3

defaults/docker_images/latte/values_latte.yaml
It's main change is addition of a possibility to define the type of the serial consistency for conditional queries (LWT).
Usage:
```
--serial-consistency=LOCAL_SERIAL --consistency=LOCAL_QUORUM
```
=> ci(latte): bump latte version to `0.33.0-scylladb`

unit_tests/dummy_remote.py, unit_tests/test_config_get_version_based_on_conf.py, unit_tests/test_ycsb_thread.py
=> Fix integration tests 

vars/perfRegressionParallelPipelinebyRegion.groovy
Adds alternator-daily trigger.
Connect alternator performance regression test to this trigger.
=> Add alternator-daily trigger

AGENTS.md
For better Copilot/LLM Agents experience, adding AGENTS.md file with codebase basic description and common development commands.
=> feature(copilot): added AGENTS.md

README.md, docs/install-local-env.md
at some point we moved to use uv insted of pyenv or other and we never documented the way to setup it up correctly
closes: #11902
=> feature(readme): update instructions for setup local dev env

sdcm/tester.py
Improve the decision logic so that it is clear that kms configuration is done when none of the skip conditions are present, and that the config option `scylla_encryption_options` only overwrites the default values.
- added debug logging to explain decision
- added early return for each check
- added error handling: if parsing version fails, raise an error event
closes: #12030
with a ami previously built by BYO, it send an error event, but does not crash
> 2025-09-26 12:56:23.500: (InfoEvent Severity.ERROR) period_type=not-set event_id=9cbed718-a368-4c49-8138-88f19e000080: message=Wanted to enable AWS KMS, but version check raised an error: Cannot parse provided 'null-null' scylla_version for the comparison. Transformed scylla_version: null-null
with an ami from an official build, but with …
=> fix(tester.py): improve checking kms enabling conditions
