scylladb/scylla-cluster-tests

defaults/severities.yaml, sdcm/cluster.py, sdcm/sct_events/base.py, sdcm/sct_events/database.py, unit_tests/test_cluster.py, unit_tests/test_sct_events_continuous_events_registry.py, unit_tests/test_sct_events_database.py
Added 2 new types of ContinuousEvents for the start / stop of bootstrapping and start / stop of the Scylla Server. I also modified the base ContinuousEvent class to register a new event in the ContinuousEventRegistry at init time and added the creation of the ContinuousEventRegistry to the BaseNode class.
Trello tasks: https://trello.com/c/IeNjhxSu, https://trello.com/c/NYDtUaH9
Jenkins job with debug logs showing the ContinousEventsRegistry being populated and new events being logged: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-artifacts/job/mc-artifacts-ubuntu-20.04/54/
=> improvement(sct_events): add scylla server and boostrap events

sdcm/cluster_k8s/mini_k8s.py
Do following fixes:
- Separate docker installation from other prerequisites installation such as installation fo required 'conntrack' package.
- Add creation of /etc/ssh/ssh_host_ecdsa_key if it is absent. It is needed at least for the minikube and installation of scylla for manager service.
- Remove usage of 'change_context=True' arg in 'node.remoter.sudo()' method, because it just doesn't have it.
'LocalCmdRunner' class is different than the one used for remote sudo calls.
Error that exists not fixing it:
TypeError: sudo() got an unexpected keyword argument 'change_context'
This error happens when some prerequisite is not installed.
So, local K8S works for people who already have correct requirements setting.
- Add also possibility to run tests on 'debian', not only 'ubuntu'. …
=> fix(k8s-minikube): install prerequisites correctly

functional_tests/scylla_operator/test_functional.py
https://trello.com/c/cwiO3WH9/3662-fixtestlistenaddress-one-error-reported-twice
=> fix(test_listen_address): one error reported twice

functional_tests/scylla_operator/test_functional.py
https://trello.com/c/PBs2P5pI/3661-disable-testrackdcprops-and-fix-decomission-test
Do two things:
1. disable test_cassandra_rackdc since it is failing
2. fix test_drain_terminate_decommission_add_node_kubernetes
=> Polish functional tests

test-cases/longevity/longevity-5000-tables.yaml
in https://github.com/scylladb/scylla-cluster-tests/pull/3643 the number
of cmds in batch was decreased by 2 but timeout less, this caused the job
to be aborted since not all c-s commands have time to finish.
=> fix(longevity-5000-tables): increase timeout

README.rst, docker/env/hydra.sh, sct.py, sdcm/cluster.py, sdcm/sct_runner.py, sdcm/utils/common.py, sdcm/utils/docker_utils.py, sdcm/utils/gce_utils.py, vars/createSctRunner.groovy, vars/getJenkinsLabels.groovy, vars/runCleanupResource.groovy, vars/runCollectLogs.groovy, vars/runSctTest.groovy, vars/runSendEmail.groovy
ticket: https://trello.com/c/slJI6CAQ/2222-sct-runner-for-gce
Currently we only support sct runner on AWS. This patch added support of
sct runner for GCE.
The gce images are available for all regions, so we don't need to copy
images. Actually we only use 'us-east1' in test.
=> feature(sct runner): support sct runner for gce

jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile, vars/managerPipeline.groovy
To prevent triggering the manager upgrade and feature jobs unnecessarily,
I modified the manager pipeline as such that the upstream job will
be triggered by the matching sanity, and only when it passes successfully.
The rest of the jobs, like backup feature and upv6 sanity, will be triggered
by the centos sanity
=> feature(manager): sanities trigger upgrade and downstream jobs

sdcm/nemesis.py
During stage shrink-cluster of GrowShrinkCluster nemesis,
sct could decommission more nodes than configured. Example:
cluster init size 3, nemesis_add_node_cnt: 5, during grow cluster stage,
only 3 nodes were added  for some reasons, and cluster size become 5
but during decommission stage, sct going again remove 5 nodes, and as
result cluster size will 1 node.
Choose min (current number of nodes - init size, nemesis_add_cnt)
=> fix(grow_shrink_cluster): Decommission nodes to initial cluster state

defaults/test_default.yaml, docs/configuration_options.md, sdcm/logcollector.py, sdcm/sct_config.py
https://trello.com/c/8aJ6BXmR/3673
PR: https://github.com/scylladb/scylla-cluster-tests/pull/3734
itroduced collect_single_archive to collect sct logs files by file
this makes sense only if sct files are too big.
Let's remove the option and just check weather sct log files are
big enough to turn such behavior on.
=> fix(logcollector): remove collect_single_archive

functional_tests/scylla_operator/libs/helpers.py, functional_tests/scylla_operator/test_functional.py
Issue: https://github.com/scylladb/scylla-operator/issues/514
This commit presents tests that cover the issue when services were not cleaned after 
the member removing"
- [x ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
=> test(operator functional): new functional tests cover orphaned services issue

sdcm/logcollector.py
* Trello: https://trello.com/c/5w9nGofd/3688-sct-collect-longevity-run-failed-because-manager-resource-does-not-found
=> fix(logcollector.py): Fixing collect logs for Sirenada run

sdcm/utils/k8s.py
https://trello.com/c/6In6nihU/3659-k8s-gke-fails-ocassionaly-on-parsing-of-kubectltoken-file
=> fix(TokenUpdateThread): update token safely

defaults/severities.yaml, sdcm/sct_events/database.py
We want the JMX service start and end to be logged as a continuous event. This PR introduces a JMXServiceEvent that does just that, using the previously added ScyllaDatabaseContinuousEvent class.
Example log lines:
```
[2021-07-23T15:10:24.463Z] < t:2021-07-23 15:10:23,836 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-07-23 15:10:23.829: (JMXServiceEvent Severity.NORMAL) period_type=begin event_id=06c887a5-543c-427a-a9c8-307d1a39fb67 node=artifacts-ubuntu2004-jenkins-db-node-db08c5ed-0-1
[2021-07-23T15:10:24.463Z] < t:2021-07-23 15:10:23,865 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-07-23 15:10:23.862: (JMXServiceEvent Severity.NORMAL) period_type=end event_id=06c887a5-543c-427a-a9c8-307d1a39fb67 duration=0s …
```
=> improvement(sct_events): jmx event

docker/env/hydra.sh
https://trello.com/c/G6yl1exE/3666-hydra-parse-command-line-properly
Parse hydra and command arguments properly to address siren-test issue on gce, which is related to problem with gcloud token synchronization due to the inability to identify gce backend in hydra.
=> fix(hydra.sh): parse arguments properly

docker/env/hydra.sh
siren-test uses sct arguments in it's pipelines, currently
hydra fail to recognize them and throw an error, as result
siren pipelines are failing.
=> fix(hydra.sh): add sct arguments

sdcm/logcollector.py
due to: https://github.com/scylladb/scylla-cluster-tests/issues/3816
=> revert(logcollector.py): Disable cloud manager log collection

sdcm/nemesis.py
Create a separate nemesis list for cloud_limited_chaos_monkey.
used in siren-tests new CloudLimitedChaosAndOperationsMonkey.
The siren-tests part of this PR is: https://github.com/scylladb/siren-tests/pull/656
Trello: https://trello.com/c/6K3yRaoX
=> improvement(cloud nemesis): a list for cloud_limited_chaos_monkey

sdcm/nemesis.py, sdcm/sct_events/setup.py
in order to fix issue ##3705 and avoid annoying error messages which confuse
next were done:
1. Added to global filter list with reduction severity error message
for cdc: "cdc - Could not update CDC description table with generation"
2. disrupt method multiple_hard_reboot_node was updated to check
if generation was succesfully update after node reboot
=> fix(multi_hard_reboot): add to global filters and cdc generation check

sdcm/sct_events/base.py, sdcm/test_config.py, sdcm/utils/metaclasses.py
Moving the Singleton metaclass definition to `sdcm/utils/common.py` and making TestConfig be a singleton class (since we don't want to have at most one instance of the test config at a given time).
Trello task: https://trello.com/c/BvTku0Iq
Example Jenkins run: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-byo-longevity-test-2/2/
=> refactor(TestConfig): convert to Singleton

sdcm/monitorstack/ui.py
Dashboard server metrics nemesis was updated with new panels
Need new resosultion for get full screenshot
=> fix(servernemesisdashboard): set new resolution

defaults/severities.yaml, sdcm/cluster.py
so far we were able only to update RPM packages,
but as for now we have by default Ubuntu builds
we need to be able to update to .deb too.
=> improvement(update_db_binary): add support to ubuntu packages

sdcm/mgmt/cli.py
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/3818
When running sdcm.nemesis.MgmtBackup with cloud manager it doesn't have
the awkward meaningless stderr as in original manager.
it is needless to check and raise for this if stdout returns the expected value -
that's just manager design.
=> fix(mgmt/cli.py): Remove unneeded manager backup command stderr check

mgmt_cli_test.py, sct.py, sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/cluster_docker.py, sdcm/cluster_gce.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/gke.py, sdcm/cluster_k8s/iptables.py, sdcm/cluster_k8s/mini_k8s.py, sdcm/db_stats.py, sdcm/sct_events/events_analyzer.py, sdcm/test_config.py, sdcm/tester.py, unit_tests/test_decode_backtrace.py, unit_tests/test_seed_selector.py
Converting TestConfig class usages to instance usages where possible. This also involved some light refactoring, i.e. adding a `self.test_config` attribute in some classes to avoid unnecessary instantiation calls to the test `TestConfig` class and for readability.
=> refactor(TestConfig): convert usages to instance

sdcm/cluster.py
Initialization of clusters in sct is complex thing, BaseCluster init
usually is called when all other inits are done. If/when attribute that is
initiated in BaseCluster is used before BaseCluster.__init__ is called we get into
issue of unknown attrubute, test_config is good example of such problem.
It is always better to either go with property or with class attribute in such case
fixes regression after 0cd4862f0880e351bb1d163297ec9177855766ce :
```
06:08:57  < t:2021-07-30 03:08:56,429 f:tester.py       l:132  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
06:08:57  < t:2021-07-30 03:08:56,429 f:tester.py       l:132  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 125, in wrapper
06:08:57  < t:2021-07-30 03:08:56,429 …
```
=> fix(BaseCluster): make property of test_config

sdcm/sct_events/database.py
Adding an "Failed to start Scylla Server" pattern to the stop patterns:
```
2021-07-26T03:16:36+00:00  longevity-lwt-3h-master-db-node-5fd7f1e0-1 !INFO    | systemd[1]: Starting Scylla Server...
2021-07-26T03:16:36+00:00  longevity-lwt-3h-master-db-node-5fd7f1e0-1 !INFO    | systemd-udevd[240]: Network interface NamePolicy= disabled on kernel command line, ignoring.
2021-07-26T03:16:36+00:00  longevity-lwt-3h-master-db-node-5fd7f1e0-1 !NOTICE  | systemd[1]: scylla-server.service: Control process exited, code=exited, status=1/FAILURE
2021-07-26T03:16:36+00:00  longevity-lwt-3h-master-db-node-5fd7f1e0-1 !WARNING | systemd[1]: scylla-server.service: Failed with result 'exit-code'.
2021-07-26T03:16:36+00:00  longevity-lwt-3h-master-db-node-5fd7f1e0-1 !ERR     | systemd[1]: Failed to start …
```
=> improvement(ScyllaServerStatusEvent): catch service failures to start

functional_tests/scylla_operator/test_functional.py, sdcm/mgmt/operator.py
https://trello.com/c/L5aBRsYs/3718-fix-sct-operator-part-to-find-active-manager-node
s-o create temporarily task_id and when pass it down to scylla-manager changing this id to task id that scylla-manager assign to it.
This fix will make sct wait till concreate task is created on scylla-manager side to make sure that task_id is not temporary one.
=> Fix k8s mgmt

sdcm/cluster_k8s/__init__.py, sdcm/utils/k8s.py
https://trello.com/c/FwcrygA9/3726-scylla-operator-fix-pods-readiness-timeout-on-deployscyllaoperator
Currently we are waiting for 5 hours
=> fix(deploy_scylla_operator): fix pod readiness timeout

sct.py, sdcm/send_email.py, sdcm/utils/common.py, sdcm/utils/gce_utils.py, test-cases/longevity/longevity-ndbench-12-nodes-multidc-4h.yaml, test-cases/longevity/longevity-ndbench-192-nodes-4h.yaml, vars/artifactsPipeline.groovy, vars/byoLongevityPipeline.groovy, vars/byoOperatorPipeline.groovy, vars/cdcReplicationPipeline.groovy, vars/cleanSctRunners.groovy, vars/jepsenPipeline.groovy, vars/longevityPipeline.groovy, vars/managerPipeline.groovy, vars/perfRegressionParallelPipeline.groovy, vars/rollingOperatorUpgradePipeline.groovy, vars/rollingUpgradePipeline.groovy, vars/runCleanupResource.groovy, vars/runSendEmail.groovy
Adding a separate pipeline step to remove the sct runnner instance the test was using if the test has successfully completed it's run.
Trello task: https://trello.com/c/OubAbKOP
GCE run: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-byo-longevity-test/167/
AWS run: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-byo-longevity-test/172/
=> improvement(sct): remove runner on test success

defaults/test_default.yaml, sdcm/cluster.py, sdcm/nemesis.py, sdcm/sct_config.py, sdcm/scylla_bench_thread.py
https://trello.com/c/eE4dRKSE/3724-prop-up-scylla-bench-version-on-sct
s-b got a new tag - https://github.com/scylladb/scylla-bench/releases/tag/v0.1.3
Let's prop version number up on sct, also we need to add additional options that were introduced by following commits:
https://github.com/scylladb/scylla-bench/commit/5662afcdd7ac81a5660679e87de3accf3ccf018e
https://github.com/scylladb/scylla-bench/commit/d1644082c188494a031eddb710ecf588b3913f44
=> fix(scylla_bench_thread): prop up s-b version

sdcm/utils/remotewebbrowser.py
=> fix(remotewebbrowser.py): hardcode selenuim backend

vars/artifactsPipeline.groovy
Fixing the issue with `artifactsPipeline` falining on 'Clean SCT Runners' stage. artifactsPipeline uses shell scripts wrapped in `sctScript` rather than calls to the scripts themselves, so I'm moving the script inside the artifactesPipeline to align it with the other stages defined there.
Test run of the improved Jenkins pipeline: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-artifacts/job/mc-artifacts-centos-7/24/
=> fix(artifactsPipeline): fix cleanSCTRunners step

sdcm/sct_events/database.py
During a local scylla operator run @juliayakovlev found that the "Started Scylla JMX" line is not being logged (but the JMX service seems to have been started). I'm expanding the regex for startign the JMX service to include the "Starting the JMX server" line as an alternative event trigger.
=> improvement(sct_events): modify 'begin' for JMX

vars/byoOperatorPipeline.groovy, vars/rollingUpgradePipeline.groovy, vars/runCleanupResource.groovy, vars/runSctTest.groovy
https://trello.com/c/vqvXXbHw/3747-fix-issue-with-k8s-post-behavior-on-k8s-pipelines
https://jenkins.scylladb.com/view/scylla-operator/job/scylla-operator/job/operator-1.4/job/upgrade/job/upgrade-major-scylla-k8s-eks/6/console
```
09:35:01  < t:2021-08-06 06:35:01,024 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Traceback (most recent call last):
09:35:01  < t:2021-08-06 06:35:01,024 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1072, in <module>
09:35:01  < t:2021-08-06 06:35:01,024 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     cli()
09:35:01  < t:2021-08-06 06:35:01,024 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/site-packages/click/core.py", …
```
=> fix(pipelines): make them tollerate if no params.post_behavior_k8s_cluster

sdcm/cluster_k8s/mini_k8s.py, sdcm/tester.py
For the moment logs are saved in dirs named like "-e4ad3ad7".
Where prefix is missing.
Fix it by providing missing "user_prefix" to the appropriate classes.
After doing it, the "user_prefix" config option will be used correctly for K8S cluster names running it using "kind" and "minikube" backends on local machines.
=> fix(functional-tests-logs): fix naming of local K8S clusters logs

functional_tests/__init__.py, functional_tests/scylla_operator/libs/__init__.py, functional_tests/scylla_operator/libs/helpers.py, sdcm/cluster.py, sdcm/nemesis.py, sdcm/sct_config.py, sdcm/tester.py, utils/__init__.py, utils/build_system/__init__.py, utils/build_system/create_test_release_jobs.py
By adding missing '__init__.py' files.
=> fix(pylint): address false import-error pylint errors

sct.py, sdcm/cluster_k8s/mini_k8s.py
For the moment, running functional tests, we see only list of tests
and it's status. But there is no info about prerequisites installation.
So, enable details output by using "-s" flag for pytest.
Also, make bunch of "debug" log messages be "info" ones.
=> improvement(functional-tests): print test run details

vars/jepsenPipeline.groovy
Commenting out the `Clean SCT Runners` stage in the Jepsen pipeline, since we're not running a runner there at the moment.
=> fix(jepsen): comment out clean sct runners step

sdcm/full_scan_thread.py, sdcm/tester.py
FIxes https://github.com/scylladb/scylla-cluster-tests/issues/3851
=> make full scan stop when test completed

sdcm/sct_events/base.py, sdcm/sct_events/nodetool.py, unit_tests/test_sct_events_continuous_events_registry.py
In `test_add_event` we were getting a new instance of a NodetoolEvent (via a fixture) and then explicitly adding it to the registry. This however doubled the event in the registry: the event got registered on instantiation (in the fixture) and then the second time in the test. Since `test_get_event_by_id` randomly chooses an event from the registry and attempts to find it with the `get_event_by_id()` method, it sometimes chose the doubled event and triggered an error (since the method throws if there are multiple events with the same id).
I also moved the uniqueness check into the `add_event()` method in `ContinuousEventsRegistry`. It makes more sense to run the check on event registration than in the getters.
Trello task: https://trello.com/c/UzZDXnwj/3766-check-why-testgeteventbyid-is-fl …
=> fix(unit_tests): fix flaky event registry test

functional_tests/scylla_operator/conftest.py, functional_tests/scylla_operator/test_functional.py, sdcm/cluster_k8s/__init__.py
In operator v1.4.0 was added possibility to recreate all Scylla
pods by changing string value in 'spec.forceRedeploymentReason' field.
So, reuse this field instead of Scylla statefulsets roll out,
because the latter one causes additional redundant rollout by update
of annotations.
=> improvement(kubernetes): restart scylla pods using proper API

sdcm/keystore.py
Credentials are required in order to query a cloud gcp cluster
for the purpose of opening ssh access to its nodes.
=> improvement(DBaas GCP): Get credentials for opening ssh access

sdcm/sct_events/base.py, sdcm/sct_events/nodetool.py, unit_tests/test_sct_events_nodetool.py
After the recent refactor of the NodetoolEvent class, the `to_json()` method of `SctEvent` started throwing `ValueError: Circular reference detected`. This was caused by the refactor, as:
1. The refactor introduced a dataclass as one of the attributes of NodetoolEvent.
2. NodetoolEvent inherits from SctEvent, which calls `json.dumps()` with the default `JSONEncoder` as its encoder and uses a `**self.__getstate__()`, a method which returns all public attributes of the event class for jsonification. `self.__getstate__()` returns a simple dict of the attributes, so when we use composition, the attribute used will not be serializable by `JSONEncoder` out of the box.
The solution for this is to create a custom encoder class for dealing with the troublesome value type. This PR introduces a …
=> Fix circular reference in nodetool event to json

sdcm/scylla_bench_thread.py
https://trello.com/c/9JKOduBs/3755-s-b-result-parsing-issue
ScyllaBenchThread._parse_bench_summary fails if value is absent:
```
event_id=d192f1d9-f6da-49b3-9b59-dfa3cf260258, source=LongevityTest.test_custom_time (longevity_test.LongevityTest)() message=Traceback (most recent call last):
23:56:55  < t:2021-08-06 20:56:55,633 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-3860/scylla-cluster-tests/longevity_test.py", line 193, in test_custom_time
23:56:55  < t:2021-08-06 20:56:55,633 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self.run_prepare_write_cmd()
23:56:55  < t:2021-08-06 20:56:55,633 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File …
```
=> fix(scylla_bench_thread): make it tollerate empty value

sdcm/cluster.py, sdcm/cluster_docker.py, sdcm/cluster_k8s/__init__.py, sdcm/scylla_bench_thread.py
https://trello.com/c/gkrn14EX/3780-unknown-flag-when-running-scylla-bench
s-b is not getting installed in some cases.
Currently we relay on s-b existance, but since default loaders have
outdated version of it this approach does not work.
Also go does not have ability to check on it too.
=> fix(is_scylla_bench_installed): make flag out of it

sdcm/tester.py, sdcm/utils/threads_and_processes_alive.py
https://trello.com/c/94P1SEZ4/3770-investigate-why-test-is-not-killed-after-teardown
https://jenkins.scylladb.com/view/scylla-4.5/job/scylla-4.5/job/Reproducers/job/longevity-50gb-3d-reproducer/6/
teardown errros:
```
< t:2021-08-09 16:18:17,180 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > exception=Critical Error has failed the test
< t:2021-08-09 16:18:17,275 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > exception=Critical Error has failed the test
< t:2021-08-09 16:18:17,375 f:cluster.py      l:4654 c:sdcm.cluster         p:WARNING > Cluster longevity-tls-50gb-3d-repro-wi-loader-set-eafe2044 (AMI: ['ami-08516c9b78d5d6d1e'] Type: c5.2xlarge): failed to kil
l stress-command on [Node longevity-tls-50gb-3d-repro-wi-loader-node-eafe2044-3 [34.201.9.104 …
```
=> Address test do not stop

sdcm/cluster.py
Due to recent changes in the manager package, the manager cannot be installed by
simplpy installing the 'scylla-manager' package, but instead one must install
both 'scylla-manager-server' and 'scylla-manager-client'.
=> fix(manager): separating manager installation to server and client

vars/rollingUpgradePipeline.groovy
Remove it for following reasons:
- This CI job doesn't create SCT runner, so such step becomes redundant.
- Jenkins fails with following error:
```java.lang.NoSuchMethodError: No such DSL method 'steps' found among steps [addEmbeddableBadgeConfiguration, ...]```
When it tries to run 'cleanSCTRunners' step.
=> fix(rollingUpgradePipeline): remove cleanSCTRunners step

sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/fill_db_data.py, sdcm/utils/decorators.py, unit_tests/test_cluster.py, upgrade_test.py
Trello: https://trello.com/c/mfHdGjxO/3300-convert-getscyllaversion-to-scyllaversion-property
- Add `optional_cached_property` decorator
- Introduce a method to clean cached Scylla version
- `node.scylla_version` always should be a short (like `4.4.dev`)
=> refactor(cluster.py): convert scylla_version to the property

sdcm/cluster_docker.py, sdcm/cluster_k8s/__init__.py
"scylla" service was renamed to "scylla-server" in 4.6
So, we should support both now in places where we touch it.
=> fix(scylla-service-name): in 4.6 it was renamed to scylla-server

jenkins-pipelines/longevity-10gb-3h-gce.jenkinsfile
Pipeline that is used by "longevity-10gb-3h-gce" CI job doesn't
specify region for GCE backend and it leads to the situation where
default name from AWS backend gets picked up.
It leads to the following error:
AssertionError: only `us-east1' region is supported
So, specify correct and supported GCE backend to make this job work.
=> fix(longevity-10gb-3h-gce): specify proper region

defaults/test_default.yaml, sdcm/sct_config.py
another commit missed this back port.
this commit is a specific back port to branch-4.5
as it broke the get_scylla_bench on all 4.5 jobs.
=> fix(scylla_bench_version): adding to test_default.py

sdcm/remote/remote_cmd_runner.py
Do it to avoid following error:
File ".../site-packages/invoke/config.py", line 176, in _get
value = self._config[key]
KeyError: 'gateway'
=> fix(remote-runner): define 'gateway' field explicitely

sdcm/cluster_k8s/operator_monitoring.py, sdcm/sct_events/operator.py, sdcm/utils/file.py, unit_tests/test_sct_events_operator.py
Operator 1.4 changed it's logging fix log monitoring
to match new style
=> fix(operator_monitoring): fix log parsing

defaults/severities.yaml, sdcm/cluster.py, sdcm/prometheus.py, sdcm/sct_events/base.py, sdcm/sct_events/continuous_event.py, sdcm/sct_events/database.py, sdcm/sct_events/loaders.py, sdcm/sct_events/monitors.py, sdcm/sct_events/nemesis.py, sdcm/sct_events/nodetool.py, sdcm/sct_events/stress_events.py, unit_tests/test_sct_events_continuous_events_registry.py, unit_tests/test_sct_events_monitors.py
Convert PrometheusAlertManagerEvent to be continuous event.
1. Add 'node' paameter to PrometheusAlertManagerEvent to do it compatible
with other events, despite maybe the event won't have a node information always.
In this case 'N/A' will be printed.
2. PrometheusAlertManagerEvent has 'stars_at' and 'alert_name' parameters that
are not supported by other events. Due this fact and for prevent the failures,
added possibility to filter all registered events by its base name
('PrometheusAlertManagerEvent' for example).
[Test](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/yulia/job/staging-longevity-100gb-4h/62/console) passed
=> improvement(continuous event): convert PrometheusAlertManagerEvent

test-cases/upgrades/rolling-upgrade.yaml
Currently the default maxPendingPerConnection of cassandra-stress
doesn't match with driver v3. The default value had been removed from
cassandra-stress in scylla-master, but the fix isn't backported to 4.5
This patch set a bigger maxPending to cs workloads to avoid a
BusyPoolException in upgrade test.
=> fix(upgrade conf): set maxPending=1024 to increase the requests limit

docker/env/hydra.sh, sct.py, sdcm/monitorstack/__init__.py, sdcm/utils/common.py
Trello: https://trello.com/c/jnwsZVHb/2658-hydra-show-monitor-on-sct-runner
- Add new option for hydra: `--execute-on-new-runner`
- Refactor `get_free_port()`
- Try to use default ports for monitoring stack first
- Export `SCT_RUNNER_IP` env variable
New runner region, AZ and duration can be controlled using env variables `RUNNER_REGION`, `RUNNER_AZ` and `RUNNER_DURATION` correspondingly.
=> improvement(hydra.sh): show monitor on SCT Runner

vars/rollingOperatorUpgradePipeline.groovy
Move out the "SCT runners cleanup" logic out of the "parallel tasks"
and place it in the end of main set of stages to avoid following jenkins
error:
java.lang.NoSuchMethodError: No such DSL method 'steps' found among
steps [...]
=> fix(rollingOperatorUpgradePipeline): Run SCT runners cleanup correctly

sdcm/utils/common.py
When SCT log files are too big, we create archive per file and uploading them separately
(introduced by PRs: https://github.com/scylladb/scylla-cluster-tests/pull/3734 and
https://github.com/scylladb/scylla-cluster-tests/pull/3795).
In the Jenkins console we see all logs, but in the email just part of them.
This commit adds printing of all SCT logs in the email.
=> fix(send email): separate uploaded SCT logs print

docker/env/hydra.sh, sct.py, sdcm/monitorstack/__init__.py, sdcm/utils/common.py, sdcm/utils/jepsen.py, vars/cdcReplicationPipeline.groovy, vars/cleanSctRunners.groovy, vars/jepsenPipeline.groovy, vars/managerPipeline.groovy, vars/runCleanupResource.groovy, vars/runCollectLogs.groovy, vars/runSctTest.groovy, vars/runSendEmail.groovy
Trello: https://trello.com/c/jnwsZVHb/2658-hydra-show-monitor-on-sct-runner
Second attempt to put this code into SCT. Tested more carefully this time.
- Add new option for hydra: --execute-on-new-runner
- Refactor `get_free_port()`
- Rename `SCT_RUNNER_IP` to `RUNNER_IP`
- Export `RUNNER_IP` env variable
- Modify `show-monitor` and `show-jepsen-results` commands to use the new feature
- Try to use default ports for monitoring stack and Jepsen results server first
=> improvement(hydra.sh): create a new runner and run command

sdcm/nemesis.py, sdcm/utils/sstable/load_inventory.py, sdcm/utils/sstable/load_utils.py, unit_tests/test_data/load_and_stream.log, unit_tests/test_utils_common.py
Issue:
https://github.com/scylladb/scylla/commit/df3ef800c20c60d7929ffa600649793aa6c73064
Task:
https://trello.com/c/nwktmFqq/3478-dtest-7831-the-load-and-stream-feature-has-been-merged-this-allows-nodetool-refresh-to-split-loaded-sstables-into-owned-and-non
This feature extends the nodetool refresh to allow loading arbitrary sstables
that do not belong to a node into the cluster. It loads the sstables from disk
and calculates the owning nodes of the data and streams to the owners
automatically.
New nemesis runs refresh with 'load_and_stream' parameter and validate by the log that 
load_and_stream has been started and finished successfully.
=> feature(load-and-stream): add nemesis

sct.py, sdcm/sct_config.py, sdcm/utils/common.py, unit_tests/test_config.py
Trello: https://trello.com/c/CSz9X3uB/3030-support-selecting-scylla-version-for-gce-image
This is SCT part of https://github.com/scylladb/scylla-machine-image/pull/169
- Add 2 new functions to sdcm.common.utils:
- get_scylla_gce_images_versions()
- get_branched_gce_images(scylla_version)
- Refactor get_scylla_ami_versions() and get get_branched_ami()
- Add support for selecting GCE image by Scylla branch or version
(e.g., `master:latest` or `4.4.0`)
- Refactor handling of scylla_version and oracle_scylla_version (AMI part)
- Add 2 new hydra commands: list-gce-images-versions and list-gce-images-branch
- Refactor list-ami-versions and list-ami-branch hydra commands
=> improvement(config): select Scylla version for GCE image

sdcm/sct_config.py
Do not verify config options values that are related to package repos
on the backends which do not use these options such as "K8S" and "siren"-based.
So, it will allow us to avoid false negative results of checks.
=> improvement(sdcm/sct_config.py): perform repo checks for proper backends

defaults/severities.yaml, sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/sct_events/health.py, unit_tests/test_sct_events_health.py
Convert ClusterHealthValidator event to be continuous events and subevents to
Informational.
Example:
```
2021-08-29 16:22:47.408: (ClusterHealthValidatorEvent Severity.NORMAL) period_type=begin event_id=8ef83194-fc37-4a62-ba28-bb4734ae4f69
2021-08-29 16:24:42.450: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=4891e18d-a199-4aed-b920-1164e2798c16: type=NodeStatus node=longevity-10gb-3h-convert--db-node-e5ac27be-1 error=Current node 10.0.1.129. Node with 10.0.2.23 (not target node) status is DN
2021-08-29 16:26:40.718: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=10756144-7fb1-4836-a5ff-c181ff0d5518: type=NodeStatus node=longevity-10gb-3h-convert--db-node-e5ac27be-2 error=Current node 10.0.3.254. Node with 10.0.2.23 (not …
```
=> improvement(events): convert ClusterHealthValidator to continuous

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/mini_k8s.py
Do it to be able to test things which require developer mode be disabled
Also, increase dedicated memory for Scylla pods from 2Gi to 2.5Gi
to satisfy 1Gi requirement per 1 lcore (2Gi was enough for dev mode).
2.5Gi is the minimum we can set, if we set 2.4Gi then
following error appears:
ERROR <time> [shard 0] init - Only 920 MiB per shard;
this is below the recommended minimum of 1 GiB/shard;
terminating.Configure more memory (--memory option) or
decrease shard count (--smp option).
=> improvement(local-k8s): run scylla with disabled developer mode

defaults/severities.yaml, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/sct_events/filters.py, sdcm/sct_events/operator.py, sdcm/utils/remote_logger.py, unit_tests/test_sct_events_operator.py
We have fixed a lot of bugs related to the wrong scheduling of non-Scylla pods on K8S.
Main problem: we can get some non-Scylla pods be scheduled onto Scylla nodes and it may
lead to unpredictable errors when we run different nemesis'.
So, we should not only fix but also keep an eye on the non-Scylla pods that must not be placed
on Scylla nodes.
As a result, need to create event(s) that will periodically check pods on Scylla nodes and verify
that there are only allowed ones.
This commit introduce an error event.
Task: https://trello.com/c/cqx1W4c6/3359-k8s-add-events-for-catching-wrong-scheduling-of-non-scylla-pods
=> feature(scylla operator): add event for catching pods wrong scheduling

test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml
The previous stress duration of 7000 minutes is too long to fit
the 7200 timeout including the prepare phase.
=> fix(longevity-1tb): Decrease stress duration in order to meet timeout

docker/env/hydra.sh
Before:
```sh
$ hydra --help
Unknown argument '--help'
```
After:
```sh
$ hydra --help
Docker version 20.10.8, build 3967b7d
There is scylladb/hydra:v0.93 in local cache, use it.
Obtaining QA SSH keys...
QA SSH keys obtained.
Making sure the ownerships of results directories are of the user
Going to run './sct.py --help '...
Obtaining QA SSH keys...
QA SSH keys obtained.
Usage: sct.py [OPTIONS] COMMAND [ARGS]...
Options:
--install-bash-completion       Install completion for the current shell.
Make sure to have psutil installed.
--install-package-from-directory PATH
Install paths for extra python pacakges to
install, scylla-cluster-plugins for example
--help                          Show this message and exit.
...
```
=> fix(hydra.sh): allow to run hydra --help

sdcm/nemesis.py
If nemesis raises the exception during disrupt methond,
in disrupt_method_wrapper, adding such exception to
log_info["error"] dict sometimes add as py object
and not converted to str. This could trigger 'Circular reference detected'
exception during save email data with test result to json file
convert Exception object to string.
The issue reproduced during job: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/133/
Testid : 9c20da8f-f455-4c3a-b333-3ef70ee52c66
=> fix(disrupt_method_wrapper): Convert exception to str

sdcm/cluster.py
on latest job for 4.5.rc7 offline installer failed
because Centos8 image doesn't have iptables service.
Job: https://jenkins.scylladb.com/job/scylla-4.5/job/artifacts-offline-install/job/artifacts-centos8-nonroot-test/119/execution/node/48/log/
Add ignore status to command execution
=> fix(node_setup): ignore status of iptables stop

sdcm/cluster_k8s/__init__.py, sdcm/tester.py
Deploying Scylla cluster on EKS or GKE backends we don't want to have
unexpected pods be placed onto Scylla K8S nodes (scylla-pool).
'kube-system' namespace has some platform-specific apps which,
by default, get deployed onto any node in a cluster.
So, specify nodeSelector field for all deployments in this namespace
explicitly to make it be deployed on proper nodes.
=> fix(kubernetes): place kube-system's deployments in default node pool

sdcm/cluster_k8s/__init__.py, sdcm/utils/k8s.py
In operator-1.5 was added separate helm chart option for affinity rules
of webhook-server pods. So, to make it be scheduled as expected,
specify additional helm chart option with affinity rules for it.
=> fix(kubernetes): specify affinity rules for webhook-server pods

sdcm/cluster_k8s/gke.py, sdcm/tester.py
Deploy 2 nodes of 'n1-standard-2' type instead of
1 node of 'n1-standard-4' type running tests on GKE backend.
The prices will be equal, so expanses will stay the same.
The reason to do so is to have more than 1 node for HA pods such
as 'scylla-operator' and 'webhook-server' which better to schedule
on different nodes.
=> improvement(k8s-gke): deploy 2 nodes in the default node pool

sdcm/mgmt/common.py
Small fix for `get_distro_name` compatibility with our artifact jobs. We're using OEL7/8 and AMAZON2 distros there, so we need to pair them with the correct manager repo (centos in this case).
=> fix(mgmt.common.py): add OEL and Amazon2 defaults

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/mini_k8s.py, sdcm/k8s_configs/minio/values.yaml, sdcm/tester.py
We need to have dedicated K8S nodes for Scylla pods to be able
to perform various disruptions not making other services suffer
and provide unexpected failures.
So, configure kind nodes the way that we will have following set:
- 1 control plane node for K8S pods
- 2 default nodes for operator, manager and cert manager pods
- x (n_db_nodes + 1) scylla nodes for scylla pods
Also, fail early running with 'minikube' backend while we do not
add multi-node support for it.
It is low priority having 'kind' backend working.
=> feature(k8s-local-kind): separate K8S nodes for db and common types

functional_tests/scylla_operator/conftest.py, sdcm/cluster_k8s/__init__.py
In operator 1.4 was changed the approach for reconciliation and
now spec update of a ScyllaCluster CRD causes rollout restart
automatically. So, having this new logic we have redundant rollouts
in our restore cluster for functional tests.
So, update it to be compatible with lateset operator logic avoiding
redundant restarts.
=> fix(k8s-functional-tests): correctly wait for the restored cluster state

sdcm/sct_config.py
I've slightly changed the logic of AMI selection in https://github.com/scylladb/scylla-cluster-tests/commit/01bcc064624508177a591fa11133118d75e5ade5
This change caused failures of https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/
This PR will return ability to use versions like 4.5 or 2020.1
=> fix(sct_config.py): return back support for 2-digit versions

docker/env/hydra.sh, vars/longevityPipeline.groovy, vars/runSctTest.groovy
In hydra we have "run-pytest" command which is used for K8S functional
tests. And we may want to provide different set of options for it
from time to time. So, add such possibility to provide pytest options
by adding new pipeline parameter called 'pytest_addopts'.
Under the hood it utilizes 'PYTEST_ADDOPTS' env var.
=> improvement(run_pytest): allow to provide additional pytest params in CI

sdcm/results_analyze/test.py
In certain cases inability to connect to the elasticsearch can
bring down the entire thread where it is not necessary, this pr
addresses those cases by adding a catch all exception to elasticsearch
calls
[Trello link](https://trello.com/c/anRlwIIL/3366-elasticsearch-updates-shouldnt-fail-tests)
=> fix(elasticsearch): handle elasticsearch connection exceptions

jenkins-pipelines/operator/upgrade/upgrade-major-scylla-k8s-gke.jenkinsfile, jenkins-pipelines/operator/upgrade/upgrade-operator-k8s-gke.jenkinsfile, jenkins-pipelines/operator/upgrade/upgrade-scylla-k8s-gke.jenkinsfile, vars/rollingOperatorUpgradePipeline.groovy
For the moment 'rollingOperatorUpgradePipeline' pipeline uses
'aws_region' var for both backends - 'k8s-eks' and 'k8s-gke'.
But it doesn't allow to specify k8s-gke specific ones.
So, fix it by removing 'choice' and adding possibility to set any
region.
=> ci(k8s-gke): fix region setting for the k8s-gke backend

functional_tests/scylla_operator/libs/helpers.py
=> fix(k8s-functional-tests): refer to correct object with scylla namespace

sdcm/utils/cloud_monitor/resources/static_ips.py
Currently we only display the used instance ID, it's difficult to know
the purpose of the ip when the ip'name is empty. This patch changed to
display the instance name additionally.
=> fix(static_ips): display instance name if ip's name is empty

configurations/web_install.yaml, defaults/test_default.yaml, docker/env/hydra.sh, jenkins-pipelines/artifacts-centos8-web.jenkinsfile, jenkins-pipelines/artifacts-ubuntu2004-web.jenkinsfile, sdcm/cluster.py, sdcm/sct_config.py, sdcm/utils/install.py
Currently we always passed the unstable scylla_repo to artifacts-test
jobs. But the web installer won't use it.
web_install_scylla() tries to use install the latest unstable build for
the current test branch, generally it should install same version as the
unstable scylla_repo.
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-web-test/
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2004-web-test/
=> feature(artifacts test): add test for web installer

sdcm/utils/data_validator.py
Cover the case when there are 2 MVs in the profile with same prefix in the name. After replacing of
SUFFIX_FOR_VIEW_AFTER_UPDATE from the name, two views with same names will be in the list.
In this case creation table failure will be received.
Example:
blogposts_update_one_column_lwt_indicator AND blogposts_update_one_column_lwt_indicator_after_update
Error:
AlreadyExists: Table 'cqlstress_lwt_example.blogposts_update_one_column_lwt_indicator_expect'
already exists
Failed test:
https://jenkins.scylladb.com/job/scylla-4.4/job/longevity/job/longevity-lwt-500G-3d-test/3/
=> fix(data validator): prevent creation tables with same name

sdcm/sct_events/continuous_event.py
Now __exit__ finction 'return self' that prevent raising of errors
=> fix(continuous event): __exit__ should not return

unit_tests/test_events.py
There is regression in tests after fa5c1b4ae103088282447d208ecbb4110eba623e
Amend tests to match new behavior
https://trello.com/c/6EwNnFKB/3898-unit-tests-fix-testeventsscteventstests
=> fix(test_events): fix continues event tests

sdcm/tester.py
The `populate_data_parallel` method is currently broken - it calculates the `keys_per_node` value as a float and inserts it into a cassandra-stress command string, which causes c-s to error out. This PR fixes that. It also adds the option to change the replication factor when using this command, as it was previously hardcoded to rf=3.
Trello task: https://trello.com/c/Zy1JIset
=> Fix populate data parallel

sdcm/utils/common.py
Recently a debug prefix was introduced for images that are not "production" and used for debugging.
We need to ignore them for all the cloud providers (AWS, GCP)
Trello: https://trello.com/c/EUlhMsPK
=> fix(common:get_branched_ami): filter out debug-image AMIs

sdcm/sct_events/filters.py, sdcm/tester.py
=> fix(typos): use correct info in some typo'ed log messages

defaults/test_default.yaml, sdcm/logcollector.py, sdcm/monitorstack/ui.py
Fix logcollector to support scylla-monitoring branch-3.9
Grafana was upgraded to v8, UI was changed.
Xpath was updated to support new UI elements
Added method to search dashboards by title. The reason
was that grafana v8. doesn't allow to get dashboard by
uri only by URL.
=> fix(monitoring_ui): support monitoring branch-3.9

test-cases/longevity/longevity-lwt-parallel-24h.yaml
during release tests for 4.5 this test failed with
timeout (test timed out 3 minutes before c-s finished).
Hence here increasing the timeout in 30 minutes
to allow the test to finish gracefully.
=> fix(longevity-lwt-parallel-24h.yaml): increase timeout

sdcm/nemesis.py
Feature new toppartition api was disabled on branch-4.5
Left only old toppartition api
Trello: https://trello.com/c/71AMcRLj
=> fix(show_top_partition): disable new toppartition api

jenkins-pipelines/hydra-show-monitor.jenkinsfile
Trello: https://trello.com/c/xhpATopG/3883-jenkins-self-service-job-for-running-hydra-investigate-show-monitor-command
The new job has following parameters:
And at the bottom of the Console Output of a build you will see the links to Grafana:
=> feature(Jenkins): a job for show-monitor

sct.py, sdcm/sct_runner.py, vars/createSctRunner.groovy, vars/runCleanupResource.groovy, vars/runCollectLogs.groovy, vars/runSctTest.groovy, vars/runSendEmail.groovy
Also, update vars/createSctRunner.groovy with the logic
where we reuse this feature and set non-default instance types
for the "k8s-local-kind-aws" and "k8s-local-kind-gce" backends.
=> feature(sct-runner): allow to define instance type

tox.ini
Just having this config it is possible to run SCT in the venv just using
following command:
tox -e py39 -- ./sct.py %other-options%
This command will also propagate all SCT_* and PYTEST_* options
to the env from the current shell.
Details about 'tox' python env manager:
https://tox.readthedocs.io/en/latest/install.html
=> feature(py-env-manager): add config for the 'tox' python env manager

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/mini_k8s.py
Set CPU=200m and RAM=100M for the scylla manager agent containers
as one additional step for scylla performance improvement.
Default values are CPU=50m and RAM=10m and not limited.
=> improvement(mgmt-agent-on-k8s): set dedicated resources explicitely

sdcm/utils/common.py
Recently a debug prefix was introduced for images that are not "production" and used for debugging.
We need to ignore them also for GCP
Trello: https://trello.com/c/EUlhMsPK
=> fix(list-gce-images-branch): filter out debug-images for GCP

defaults/severities.yaml, sdcm/cluster.py, sdcm/nemesis.py, unit_tests/test_cluster.py
https://trello.com/c/OXsjoWby/3779-events-missing-when-monitoring-stack-is-restored
Make poweroff event WARNING, instead of CRITICAL.
Also get rid of poweroff filters and fix tests accordingly.
=> Fix poweroff

vars/artifactsPipeline.groovy
The test duration of artifacts-test jobs are always very short, the
test isn't heavy, and the problems are easy to reproduce.
It's waste of resource to use SCT runner for artifacts-test jobs.
This patch disabled it.
Signed-off-by: Amos Kong <kongjianjun@gmail.com>
Reported-by: Bentsi Magidovich <bentsi@scylladb.com>
=> fix(artifacts pipeline): disable sct runner

vars/getCloudProviderFromBackend.groovy
'aws-siren' and 'gce-siren' values were added as new backends.
Thus it should be adjusted when cloud-provider value is requested.
siren-tests corresponding PR is: https://github.com/scylladb/siren-tests/pull/713
Trello: https://trello.com/c/MAjHqcc3
=> fix(siren backends): Adjust siren backens for sct cloud-provider option

vars/perfRegressionParallelPipeline.groovy
Remove it for following reasons:
- This CI job doesn't create SCT runner, so such step becomes redundant.
- Jenkins fails with following error:
java.lang.NoSuchMethodError: No such DSL method 'steps' found among
steps [addEmbeddableBadgeConfiguration, ...]
When it tries to run 'cleanSCTRunners' step.
=> fix(perfRegressionParallelPipeline): remove cleanSCTRunners step

sdcm/cluster_k8s/__init__.py
After merge of [1] K8S deployment started failing with following error:
AssertionError: We should have at least one selected seed by now
The reason for it is that operator-1.4+ stopped using seed nodes and
reuses seedless approach. So, check for seeeds is not relevant to K8S
backends.
So, fix it by redefining 'seed_nodes_ips' and 'seed_nodes' properties
with empty values.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/3882
=> fix(kubernetes): suppress absence of seed nodes

sdcm/cluster_k8s/__init__.py
There are cases when we may want to see all logs of containers that were restarted/recreated.
For the moment we get logs of only current instances of containers.
"kubectl logs" supports getting logs of previous containers using "--previous=true" flag. So, use it when we gather pods logs.
=> improvement(k8s-logs): gather also logs for previous containers in pods

sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/k8s_configs/eks/scylla-node-prepare.yaml
To improve Scylla's performance we should run it's pods dedicating CPUs
to it exclusively ('Guaranteed' QoS class).
So, to be able to do it define 'cpuManagerPolicy=static' option
for kubelet on K8S nodes which are going to host Scylla.
Details: https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies
=> improvement(k8s-eks-perf): allow Scylla pods to get guaranteed CPU bind

functional_tests/scylla_operator/libs/helpers.py, functional_tests/scylla_operator/test_functional.py
=> improvement(functional): make webhook-server rollout test more stable

sdcm/cluster.py
Loaderset uses same wrapper for waiting node initialization.
And parallel initialization is used with same timeout 120 seconds
for Loaderset and scylladb set.  In this case, loader nodes wait not
needed 2 minutes to start next node setup.
Use timeout with 2 minutes only for scylla db nodes
Trello: https://trello.com/c/MWv3aKlQ
=> fix(wait_for_init_wrap): wait timeout only for scylla db nodes

defaults/severities.yaml, sdcm/db_stats.py, sdcm/report_templates/results_base.html, sdcm/sct_events/loaders.py, sdcm/send_email.py, sdcm/stress_thread.py, sdcm/tester.py, unit_tests/test_sct_events_loaders.py
Using prometheus query and parsing c-s log file check
whether c-s use shared-aware driver or not and add info
to summary email
Trello: https://trello.com/c/VrpxJLr4
=> feature(cs_driver): Check is shared awarnes or not driver is used

sdcm/sct_config.py
When running sct with 'nemesis_filter_seeds' set to true and when 'n_db_nodes' count is equal to 'seeds_num'
nemesis cannot find node to run causing errors.
Change prevents from setting n_db_nodes equal to seeds_num when nemesis_filter_seeds is set to true
trello card: https://trello.com/c/5rp4gDLq
=> fix(sct_config): fail fast when no available non-seed nodes for nemesis

defaults/severities.yaml, jenkins-pipelines/longevity-harry-2h.jenkinsfile, longevity_test.py, sdcm/cassandra_harry_thread.py, sdcm/cluster.py, sdcm/db_stats.py, sdcm/loader.py, sdcm/sct_events/base.py, sdcm/sct_events/loaders.py, sdcm/tester.py, test-cases/longevity/longevity-harry-2h.yaml
Ticket: https://trello.com/c/tFSmBovn/2395-explore-cassandra-harry-new-fuzzing-tool-from-cassandra
This patchset added a new kind of workload.
/usr/bin/cassandra-harry on loader points a wrapper script CLI, it accepts
`-node` and `-run-time` arguments.
=> feature(cluster.py): support a new fuzzing tool: cassandra-harry

sdcm/provision/scylla_yaml/cluster_builder.py, sdcm/provision/scylla_yaml/scylla_yaml.py, sdcm/tester.py, unit_tests/test_scylla_yaml_builders.py
Recently was merged feature with new logic for handling of the Scylla foncfiguration [1].
It changed the behavior of "hinted_handoff" option from
'"disabled" is False and all other mean True' to
'only "disabled" and "enabled" values are allowed'.
The problem with it is that scylla.yaml file that SCT reads from
cluster created by siren-tests returns boolean-like value, not 'disabled' or 'enabled' ones.
So, add support for such values too to unblock usage of ScyllaCloud clusters.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/3882
=> fix(ScyllaYaml): support values defined in ScyllaCloud's yaml config

vars/artifactsPipeline.groovy
We don't want to use the SCT runner in artifact-tests, but the old
sct_runner_ip file might effect the tests.
This patch changed to clean the old sct_runner_ip file before running
the artifact-tests.
createSctRunner() was called for many pipelines, it's also helpful to
clean the old sct_runner_ip all the time.
Signed-off-by: Amos Kong <kongjianjun@gmail.com>
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/3988
=> fix(artifactsPipeline): clean the old sct_runner_ip

vars/artifactsPipeline.groovy
Our SCT parameter of aws region is region_name (SCT_REGION_NAME), but we
used aws_region in yaml config and some vars functions.
Artifacts Pipeline and yaml configs use matched region_name, but it
called the shared functions (eg: runCollectLogs).
The grace change should change all the parameter in yaml config and
vars functions to `region_name`, but it's too big change.
This patch only changed the parameter name in artifacts pipeline to
match with runCollectLogs().
Signed-off-by: Amos Kong <kongjianjun@gmail.com>
=> fix(artifactsPipeline): make region parameter to be matched

sdcm/cluster.py
Trello: https://trello.com/c/5TyHBmbP/3968-processscyllaargs-failed-when-seastar-arguments-were-split-to-help-seastar-option
Fixes #4000
=> fix(cluster.py): process args from --help-seastar

sct.py
When empty az is provided create_runner_instance fails
```
(sct) ✘-2 ~/devel/scylladb/scylla-cluster-tests [master ↑·976|…23⚑ 4] 
20:34 $ hydra create-runner-instance -r us-east-1 -t bentsi -d 2
Docker version 20.10.8, build 3967b7d
There is scylladb/hydra:v0.96 in local cache, use it.
Obtaining QA SSH keys...
QA SSH keys obtained.
Making sure the ownerships of results directories are of the user
Going to run './sct.py  create-runner-instance -r us-east-1 -t bentsi -d 2'...
Obtaining QA SSH keys...
QA SSH keys obtained.
Docker daemon is already logged in as `scyllaqatest'.
New directory created: /home/bentsi/sct-results/20211004-173507-418744-create-runner-instance
Creating SCT Runner instance...
File …
```
=> fix(create_runner_instance): check az for AWS even if not provided

vars/perfRegressionParallelPipeline.groovy
fix(perf pipelines): changing region didn't take effect 
happened that changing in the job's pipeline call
the region did not take effect.
after this change, there is a running job with
the correct region (see PR's previous comment).
=> fix(perf pipelines): changing region didn't take effect 

functional_tests/scylla_operator/conftest.py, functional_tests/scylla_operator/test_functional.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/mini_k8s.py
For the moment, we have 2 different methods which update
'scylla-config' configMap that is used to store 'scylla.yaml'
and 'cassandra-rackdc.properties' files. Their logic is not
aligned with each other and one of them doesn't consider changes from
another and make inconsistent changes.
We didn't face such problem just because the only place where we update
'cassandra-rackdc.properties' file is K8S functional test, which is
skipped now due to the bug in operator.
So, refactor the approach with update of mentioned configs files on K8S
backends making both be consistent.
Also, update related K8S functional test (test_cassandra_rackdc)
by doing following:
- Add waiters for the 'UN' status of scylla members calling 'nodetool
status' command. It will allow us to fail test correctly
when we …
=> refactor(k8s-rackdc-update): make rackdc props file be updated correctly

functional_tests/scylla_operator/conftest.py, functional_tests/scylla_operator/pytest.ini, functional_tests/scylla_operator/test_functional.py
Apply following fixes for the pytest fixtures used for operator testing:
- Use "fixture_" prefix in functions names which are defined as
fixtures to avoid following pylint rule violation:
W0621: Redefining name %r from outer scope (line %s)
It appears if we reuse fixtures in scope of one single module.
- Split 'skip_if_cluster_requirements_not_met' function that
must have been defined as fixture into 2 new functions and
define both as fixtures with 'autouse=True' argument which makes
it run against each relevant test.
- Add 'autouse=True' key for the "change_test_dir" fixture to make it
be applied for each of the tests. Without it is not used at all.
- Rename 'require_mgmt' marker to the 'requires_mgmt'
to be more grammatically correct.
- Rename 'require_node_terminate' marker
to the …
=> fix(k8s-functional): define and use fixtures properly

sdcm/cluster_k8s/__init__.py
=> fix(k8s-remote-scylla-yaml): reuse proper parent_cluster attributes

sdcm/remote/remote_base.py, sdcm/utils/common.py
Fixed following doubles:
sdcm.remote.base:[93:104] vs sdcm.remote.remote_base:[570:597]
sdcm.utils.common:[2231:2241] vs sdcm.utils.k8s:[865:874]
(cherry picked from commit a5fe3ac4531b952f8bd4b80ba9d23d1c36c76610)
=> fix(sdcm/*.py): fix duplicated code to make pylint happy

sdcm/utils/pricing.py
Osaka-Local was renamed to Osaka
Fixes:
```
10:23:07 Found total of 353 instances.
10:23:07 Traceback (most recent call last):
10:23:07   File "/jenkins/slave/workspace/devops-cloud-resources-report/./sct.py", line 1279, in <module>
10:23:07     cli()
10:23:07   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
10:23:07     return self.main(*args, **kwargs)
10:23:07   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
10:23:07     rv = self.invoke(ctx)
10:23:07   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
10:23:07     return _process_result(sub_ctx.command.invoke(sub_ctx))
10:23:07   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
10:23:07     return …
```
=> fix(pricing): ap-northeast-3 renamed to Osaka

tox.ini
To be able to run "git" commands in virtual environment we need to
have "HOME" env var be defined. So, pass through it to the tox
environment.
With this change following command starts working:
$ tox -e py310 -- git commit
Such a command is needed to avoid skipping of pylint checks for
some of the files when we have default python version be incompatible.
=> improvement(tox-venv-mgr): pass through 'HOME" env var needed by git

sdcm/provision/scylla_yaml/scylla_yaml.py, unit_tests/test_data/scylla_yaml_update.yaml, unit_tests/test_scylla_yaml.py
* small naming bug in _update_dict()
* added enable_sstables_md_format default
* unit test for updating ScyllaYaml with a dict
=> fix(scylla_yaml): append_scylla_args parsing

jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile, jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
=> refactor(manager tests): manager tests use scylla 4.5 instead of 4.4

sdcm/utils/common.py, sdcm/utils/k8s.py
'walk_thru_data' function located at sdcm/utils/common.py module
has the same logic as 'HelmValues.get' method in the sdcm/utils/k8s.py
So, update the first one to be compatible with the needs of the second
one and reuse it to remove code duplication.
Also, add docstring to the reused function with the description of it's
usage.
=> fix(duplication): reuse walk_thru_data func in HelmValues.get method

sdcm/parallel_timeline_report/generate_pt_report.py, sdcm/sct_events/database.py
[Trello Task](https://trello.com/c/TV5a3akj/3944-jmxserviceevent-should-have-end-pattern-that-is-logged-when-the-service-is-stopped)
=> fix(JMXServiceEvent): fix evaluation of the end timestamp

test-cases/longevity/longevity-10gb-3h.yaml
`longevity-10gb-3h.yaml` is used on both AWS and GCP
tests, and in most of the cases, GCP tests are failing
with timeout, so increasing very little the timeout
to be able to get it passing flawlessly.
=> fix(longevity-3h): increase test timeout

test-cases/longevity/longevity-alternator-3h.yaml
Time to time teardown takes 40 minutes and test setup takes 1h
in such case test is running out of time and getting killed
Example killed runs:
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-alternator-3h-test/313/
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-alternator-3h-test/309/
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-alternator-3h-test/306/
=> fix(alternator-3h): increase test_duration by 60 minutes

functional_tests/scylla_operator/conftest.py, functional_tests/scylla_operator/test_functional.py
Add a functional test that checks the ability to override scylla.yaml
Task: https://trello.com/c/ZgzgdjD5/3941-create-a-functional-test-that-checks-the-ability-to-
override-scyllayaml
Tested:
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/yulia-functional-k8s-local-kind-aws/11/
=> test(function): override scylla.yaml

jenkins-pipelines/hydra-clean-runner-instances.jenkinsfile
Trello: https://trello.com/c/9sKBqVL0/4094-clean-forgotten-gce-runner-instances
New job: https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-clean-runner-instances/
Plan to run it every 3h
=> improvement(Jenkins): add job for removing SCT runners

sdcm/mgmt/cli.py, sdcm/nemesis.py
The status string of a manager task, when splited based on spaces, can
be two items long (like 'ERROR (1/4)'). As such, when we examine if
the manager status is ERROR_FINAL ('ERROR (4/4)') we need to examine
the entire list, and not just its first value.
Also, broadened Nemesis._mgmt_backup to look for ERROR_FINAL status at the
end of the backup task.
Fixes #3902
=> fix(ManagerTask.status): Added considation for 'ERROR (4/4)' status

docker/ycsb/Dockerfile, docker/ycsb/image, sdcm/utils/docker_remote.py, sdcm/ycsb_thread.py, unit_tests/test_ycsb_thread.py
build new docker image that has https://github.com/brianfrankcooper/YCSB/pull/1507
and enable shard aware by default
=> improvement(YCSB_docker): introduce version support scylla command

jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile, jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile, vars/managerPipeline.groovy
Before, setting scylla_version in manager test scenarios required a change
in each scenario's jenkinsfile separately. Since all of the tests use the
same version anyway, I've removed all previous definitions and set the
default in manager pipeline, instead.
Also, set scylla version to master.
=> refactor(manager): set scylla_version as master in the managerPipeline

sdcm/prometheus.py, sdcm/sct_events/database.py
prevent tons of warnings that appear in console log. Example:
Found 5 events of type <class sdcm.sct_events.database.RepairEvent>
with period begin. Will apply the function
=> fix(events): set debug level when more than 2 events found

README.rst, docker/env/hydra.sh, install_argus.sh, sct.py, sdcm/argus_test_run.py, sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/db_stats.py, sdcm/monitorstack/ui.py, sdcm/nemesis.py, sdcm/sct_config.py, sdcm/test_config.py, sdcm/tester.py, sdcm/utils/ci_tools.py, sdcm/utils/common.py, sdcm/utils/git.py, sdcm/utils/net.py, unit_tests/test_tester.py, utils/build_system/__init__.py, vars/jepsenPipeline.groovy, vars/longevityPipeline.groovy, vars/managerPipeline.groovy, vars/rollingOperatorUpgradePipeline.groovy
This PR adds argus test run tracking, intended to track changes to
test runs in real-time - Resource allocation/deallocation, status
changes, nemeses starts/successes/failures, and to track test
information such as test name, group, release name and test
configuration
[Trello link](https://trello.com/c/J7XlShSk/3956-integrate-argusdb-with-sct)
=> feature(sct): Argus test run tracking

sdcm/report_templates/results_base.html, sdcm/report_templates/results_base_new.html, sdcm/report_templates/results_issue_template.html, sdcm/report_templates/results_jepsen.html, sdcm/send_email.py, sdcm/tester.py
This commit will improve our issues and do a life easier to developers.
Add to the issue link to the job that restore the monitor with it's parameters.
Task: https://trello.com/c/nHVX473v/3993-email-template-add-link-to-the-job-that-recreate-a-monitor
=> improvement(email): add link to the job that recreate a monitor

sdcm/sct_provision/common/layout.py, sdcm/test_config.py
With current logic we create folder with test_id in it
As result in the pipelines where both provision step and test run step
exists, all steps that are using get_testrun_dir are getting two folder
fixes (https://github.com/scylladb/scylla-cluster-tests/issues/4100)
=> fix(provision): do not create test_id

sdcm/utils/threads_and_processes_alive.py
inspect routines we are using can raise Exceptions in some cases
lets catch and log them, and return placeholder in such case
https://trello.com/c/oRgLrYqm/4069-showalivethreads-can-fail-with-source-code-not-available
=> fix(show_alive_threads): make it safe

jenkins-pipelines/operator/performance/perf-regression-latency-eks.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-throughput-eks.jenkinsfile, vars/getJobTimeouts.groovy, vars/perfRegressionParallelPipeline.groovy
For the moment we use one single timeout for whole performance
pipeline. It is not really correct because we can get successfully
finished test in time but timed out logs collection. Such a situation
leads to the false negative job results.
So, use separate timeouts for different stages in performance pipeline
the same way as we do it in longevity ones.
=> ci(perf-pipeline): use separate timeouts for different stages

sdcm/nemesis.py
from the logs it is not clear how much we will wait
(sleep), and the message could include it very easily
hence changed the log message to include the "random"
time to sleep.
=> improvement(nemesis.py): improve logs RebuildStreamingErr

defaults/manager_versions.yaml
Since individuals packackes are not created for different deb distributions,
I modified all of the master urls in manager_versions.yaml to the unified deb build.
=> fix(manager_versions): changed master_latest deb urls to unified build

docker/cdcstressor/image, sdcm/db_stats.py, sdcm/results_analyze/__init__.py, sdcm/utils/es_queries.py
PR contains 3 commits.
1. Retry to create/update document if Readtimeouterr happened for ES.
2. Update docker image for cdc stressor tool
3. Switch to use wide query for cdc performance tests
=> Fix missing emails for cdc performance tests

sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/utils/docker_remote.py
Fix following exception:
```    
File "%path%/sdcm/cluster.py", line 295, in
provider=self.parent_cluster.cluster_backend,
AttributeError: 'LocalKindCluster' object has no attribute 'cluster_backend'
```
By adding missing 'cluster_backend' attribute for K8S classes.
then, fix following exception:
```
File "%path%/sdcm/cluster.py", line 294, in
instance_details = CloudInstanceDetails(public_ip=self.public_ip_address,
File "<string>", line 10, in __init__
File "%path%/pydantic/dataclasses.py", line 99, in
raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for CloudInstanceDetails
region
none is not an allowed value (type=type_error.none.not_allowed)
```
By making RemoteDocker and LocalNode provide non-empty strings as values
for the 'region' attribute instead …
=> fix(argus): make it be compatible with K8S backends

sdcm/provision/aws/provisioner.py, sdcm/provision/common/provision_plan.py, sdcm/provision/common/provision_plan_builder.py, sdcm/provision/common/provisioner.py, sdcm/sct_provision/aws/cluster.py, sdcm/sct_provision/common/layout.py
Based on: https://github.com/scylladb/scylla-cluster-tests/pull/4098
Purpose is to localize logic regarding provisioning and generalize it.
Preparation for https://trello.com/c/EyP2J8ig/1290-microsoft-azure-as-a-new-backend
=> Provision: localize provisioner plan and plan builder

sdcm/cluster_k8s/eks.py
Calling super's method with the same attributes from 2 different
child classes is not a code duplication, but not for pylint.
So, update code in the 'sdcm/cluster_k8s/eks.py' a bit to avoid following
occassional pylint error:
************* Module sdcm.utils.remotewebbrowser
sdcm/utils/remotewebbrowser.py:1:0: R0801: Similar lines in 2 files
==sdcm.cluster_k8s.eks:[68:80]
==sdcm.cluster_k8s.gke:[55:67]
):
super().__init__(
k8s_cluster=k8s_cluster,
name=name,
num_nodes=num_nodes,
disk_size=disk_size,
disk_type=disk_type,
image_type=image_type,
instance_type=instance_type,
labels=labels,
is_deployed=is_deployed,
) (duplicate-code)
=> fix(pylint): remove the basis for the duplicate-code error

vars/perfRegressionParallelPipeline.groovy
Performance pipeline doesn't reuse value for
the post_behavior_k8s_cluster config option provided via parameters.
It leads to usage of default value always.
So, fix it by making it consider params the same way as it is done
for other post behaviour options.
=> fix(perf-pipeline): use post_behavior_k8s_cluster value from params

jenkins-pipelines/hydra-clean-runner-instances.jenkinsfile
Recently the job was stuck due to some builder connectivity issues. Hence added a timeout.
```
13:44:28  Docker version 19.03.11, build 42e35e61f3
13:44:28  Pull version v0.99 from Docker Hub...
19:26:02  Cannot contact gce4-qavpc: java.lang.InterruptedException
```
=> improvement(clean-runner-instances): add timeout to the pipeline job

sdcm/cluster.py
Based on https://github.com/scylladb/scylla-cluster-tests/pull/4115
Make endpoint_snitch be always present in scylla_yaml to make `/usr/bin/nodetool upgradesstables -a` work
=> Fix rolling upgrade

sdcm/tester.py
https://trello.com/c/YHyn6Dur/4154-testtimeoutevent-start-time-is-drifted
test_id: 8000967e-91e8-4ed9-ad47-ffabc4b1d3aa
```
< t:2021-11-08 20:53:46,391 f:tester.py       l:346  c:LongevityTest        p:INFO  > Test start time 2021-11-08 20:53:45, duration is 240 and timeout set to 2021-11-09 00:53:45
< t:2021-11-09 00:53:46,394 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 2021-11-09 00:53:46.392: (TestTimeoutEvent Severity.CRITICAL), Test started at 2021-11-08 21:27:57, reached it's timeo
ut (240 minute)
```
Test start time **2021-11-08 20:53:45**, duration is 240 and timeout set to 2021-(TestTimeoutEvent Severity.CRITICAL), Test started at **2021-11-08 21:27:57**, reached it's timeout (240 minute)
=> fix(test_timeout): make start_time to be in sync

mgmt_cli_test.py, mgmt_upgrade_test.py, sdcm/cluster.py, sdcm/mgmt/common.py
New in manager 2.6
'max_timeout' is new parameter in the scylla manager yaml. It decides the maximum
amount of time the manager healthcheck function will wait for a ping response before
it will announce the node as timed out.
The new test in the manager sanity, test_healthcheck_change_max_timeout, sets the
timeout as such that the latency of the nodes that exist in the
local region (us-east-1) will not be longer than the set timeout, and therefore
will appear as UP in the healthcheck, while the latency of the node that is the
distant region (us-west-2) will be longer than the set timeout, and therefore the
healthcheck will report it as TIMEOUT.
The test makes sure that the healthcheck reports those statuses correctly.
=> test(manager): testing healthcheck's max_timeout parameter

sdcm/utils/es_queries.py
this is an information is meant to help analyze
performance jobs, and understand if we are having
more than usual `reactor stalls` when for example,
decreasing the `blocked-reactor-notify-ms` parameter
=> improvement(perf report): add `append_scylla_args` to email report

sdcm/sct_events/base.py, sdcm/sct_events/database.py, sdcm/sct_events/file_logger.py, unit_tests/test_sct_events_base.py
Now log level of all events is INFO. It cause to problem when a lot of
events are printed on the console. Even those that we son't need to see them there.
This commit add possibility to set log level for every event separately.
To change log level: set 'self.log_level' to wished value:
logging.DEBUG, logging.WARNING..
Default is INFO
Changed log level to DEBUG for:
- CompactionEvent
- RepairEvent
```
< t:2021-11-14 17:04:10,925 f:file_logger.py  l:85   c:sdcm.sct_events.file_logger p:DEBUG > 2021-11-14 17:04:10.921: (RepairEvent Severity.NORMAL) period_type=begin event_id=38d56eaa-9dd6-421e-8fa9-571928dca3f6 node=longevity-10gb-3h-compacti-db-node-a7af6e98-1 shard=0
```
```
< t:2021-11-14 17:04:10,920 f:file_logger.py  l:85   c:sdcm.sct_events.file_logger p:DEBUG > 2021-11-14 …
```
=> improvement(events): set log level per event

sdcm/cluster.py
we were lately failing while waiting for
`dpkg` (like we had for yum and apt), so
here there are other cosmetic changes and
few improvements.
=> fix(update_scylla_packages): ubuntu package

sdcm/cluster.py, sdcm/logcollector.py
from Avi's patch on Seastar, now we will get the stack traces
from the kernel for our reactor stall back traces.
this is only an experiment to see if we will indeed get
the desired results, but we might want to place this
command somewhere else (or only for perf jobs), or even
to add a new parameter on sct_config, to control it
from test .yaml configuration file.
=> feature(perf_event_paranoid): changing value to get kernal stack

sdcm/full_scan_thread.py
The fullscan parameter has an option to get 'random' as the ks.cf for
the full scan query.
However, this one got broken as part of the previous changes.
In runs of  4.5  and 2021.1 I see the followings errors when running fullscan for "random" option:
(I don't know how people didn't see it before or maybe we just recently backported this breakage)
FullScanEvent Severity.ERROR): type=finish select_from=random on db_node=10.0.3.217 message=Error from server: code=2200 [Invalid query] message="No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename"
=> fix(FullScanThread): Fix bad handling of 'random' option for fullscan

sdcm/utils/cdc/options.py
https://docs.scylladb.com/using-scylla/cdc/cdc-intro/
Per documentation true|false|full are the only that supported
Recently the test failed with the following:
```
< t:2021-11-08 21:19:53,199       p:INFO  > sdcm.nemesis.ChaosMonkey: Apply new cdc settigs for table cdc_test.test_table: {'delta': 'full', 'enabled': True, 'preimage': 'on', 'postimage': False, 'ttl': '600'}
< t:2021-11-08 21:19:53,200       p:DEBUG > sdcm.nemesis.ChaosMonkey: Alter command: ALTER TABLE cdc_test.test_table WITH cdc = {'delta': 'full', 'enabled': True, 'preimage': 'on', 'postimage': False, 'ttl': '600'};
...
< t:2021-11-08 21:20:24,505       p:DEBUG > sdcm.nemesis.ChaosMonkey: Verify new cdc settings on table cdc_test.test_table
< t:2021-11-08 21:20:24,506       p:DEBUG > Running command "cqlsh --no-color …
```
=> fix(cdc-options): update supported values for preimage

sdcm/tester.py
* The problem:
The `pre_create_alternator_tables` creates the tables needed to run alternator tests.
The problem that the method is called several times during the rolling upgrade test. 
To avoid this problem does not happen again, I change the method to "call" one time in the
session.
* Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4133
=> fix(upgrade_test.py): Create Alternator tables once in all session

sct.py, sdcm/sct_config.py, unit_tests/test_config.py
Follow to https://github.com/scylladb/scylla-cluster-tests/pull/4013.
This commit present two fixes:
1. not verify aws multi region params for siren tests. 'ami_id_db_scylla' is mandatory for not
siren tests and it causes to failure of siren tests
2. check backend defaults for siren tests. Siren tests has its own default mandatory variables
and we need to validate them before running the test
=> fix(verify config): mandatory variables for siren tests

docker/scylla-sct/ubuntu/Dockerfile
PR #3865 changed the default docker to be
ubuntu (instead of centos), but ubuntu has
no `/etc/bashrc` and instead it has
`/etc/bash.bashrc`, so last runs for
4.6 are failing due to this sed command
failing.
=> fix(ubuntu Dockerfile): wrong call to bashrc

sdcm/nemesis.py
disrupt_terminate_and_replace_node now assigns the new node as seed whenever the
target node is a seed, and it updates the scylla.yaml files in all of the nodes
after the replacement has concluded.
=> fix(terminate_and_replace): changed to be able to replace a seed

sdcm/monitorstack/__init__.py
Having 'dashboard.id' field be set we get following error:
Error message {"message":"Dashboard not found","status":"not-found"}
So, unset it to make Grafana understand that we create dashboard from
scratch and not update "existing' one.
=> fix(show-monitor): unset dashboard.id field for the restored dashboard

artifacts_test.py, sdcm/cluster.py, sdcm/cluster_docker.py, sdcm/utils/housekeeping.py, sdcm/utils/net.py
Add housekeeping stats test to artifact tests
Tested on configurations:
- ami
- amazon2
- ubuntu2004
- docker
=> feature(housekeeping stats): add housekeeping stats test to artifact tests

sct.py
since we use it only in the collect logs we don't want this
import happen every time we run other sct.py commands
=> improvement(sct.py): move ArgusTestRun import to the func that uses it

sdcm/report_templates/results_reactor_stall_events_list.html
after the new events were added, they are now
flooding the DEBUG events and hence emails are not
able to be sent (there is a limit, and we might not
be able to change it, or we don't want to change it).
with this change, the kernel callstacks will not be
shown in the email attachment (that now is called
`reactor_stall_events_list`, and maybe a new
attachment file will be added with these kernel
events, but for now, removing it to have the test
passing (and sending the emails).
=> fix(kernel callstack) remove from email attachment:

sdcm/monitorstack/ui.py
Grafana changed the header element attributes.
This was found in branch-3.9 (monitoring version 3.9.1)
Fix xpath for searching panel on dashboard
=> fix(monitorstack/ui): change xpath for panel searching

sdcm/utils/health_checker.py, unit_tests/test_utils_health_checker.py
Due to https://github.com/scylladb/scylla-enterprise/issues/1419 being resloved, I removed
the changes that were inserted in https://github.com/scylladb/scylla-cluster-tests/pull/2383
As of now, ANY node that will not appear as UN during the health check will
trigger a critical event
=> revert(health_checker): removing removed_nodes_list check

longevity_test.py, sdcm/sct_events/group_common_events.py
on branch 4.4 alternator tests usually set as failed due
paxos/errors messages described in issue #8706.
Ingore this messages for alternator tests globally.
=> fix(longevity_test): Skip paxos error/warning messages (#8706)

defaults/k8s_gke_config.yaml, defaults/test_default.yaml, docs/configuration_options.md, jenkins-pipelines/operator/performance/perf-regression-latency-eks.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-throughput-eks.jenkinsfile, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/cluster_k8s/mini_k8s.py, sdcm/k8s_configs/eks/scylla-node-prepare.yaml, sdcm/k8s_configs/loaders.yaml, sdcm/k8s_configs/node-config-crd.yaml, sdcm/sct_config.py, sdcm/utils/k8s.py, vars/perfRegressionParallelPipeline.groovy
Operator release 1.6 will have 2 new CRs (Custom Resources) for
handling of the K8S nodes performance tuning.
So, add support for it.
Following new configuration options are introduced:
- k8s_enable_performance_tuning. This one defines whether we should
enable K8S nodes tuning or not.
- k8s_scylla_utils_docker_image. This one defines the Scylla docker
image to be used as utils image for the tuning of K8S nodes.
If not specified then the default value from the operator will be
used.
=> feature(operator): Add possibility to configure K8S perf tuning

sdcm/cluster_k8s/__init__.py
Fixes regression after https://github.com/scylladb/scylla-cluster-tests/commit/a321ad252865ea3988ad10335003a667200b70f7
https://trello.com/c/Gs7ZRFB5/4215-make-syslog-ng-work-on-k8s-backends
=> fix(k8s): skip logging configuration

artifacts_test.py, sdcm/cluster.py
Task:
https://trello.com/c/IkBtoQIi/4207-investigate-the-artifacts-tests-failures-related-to-housekeeping
According to https://github.com/scylladb/scylla/blob/965ea4a3facc50f337733349eba316e9e8b9b9ae/dist/common/scripts/scylla_setup#L371 and https://github.com/scylladb/scylla/blob/965ea4a3facc50f337733349eba316e9e8b9b9ae/install.sh#L293
housekeeping is not supported for nonroot installation
Test passed:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/yulia/job/yulia-artifacts-centos8-nonroot-test/6/
=> fix(artifact test): nonroot install not support housekeeping

sdcm/sct_events/database.py
If begin event for database continuous event is not found, exception is raised,
that caused to db log reader crash.
Publish TestFrameworkEvent instead.
Task: https://trello.com/c/qfnjQOD5/4174-continues-events-can-cause-db-log-reader-to-crash
=> fix(event): not raise exception when begin event not found

data_dir/scylla-dash-per-server-nemesis.master.json
Set $test_name template parameter to use test/job name for
scylla-dash-per-server-nemesis dashboard
=> fix(dashboard): Use $test_name template for grafana dashboard

mgmt_cli_test.py, sdcm/mgmt/cli.py
In certain circumstances, during manager suspension tests, the cluster can
remain suspended at the end of the function.
To remedy this, I made sure that the manager is resumed in the end.
DO NODE: the option to resume an already resumed cluster was introduced
only in manager 2.6. Using it in earlier versions will result in errors.
=> fix(manager suspension tests): make sure to resume after suspending

jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile, jenkins-pipelines/rolling-upgrade-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile
as there are patches for this minor version of
this branch `scylla-4.5`, then we want to also
test upgrades from the previous patches to the
current RC (and not only from previous minors.
=> fix(rolling upgrade): add another base version

sdcm/cluster.py, sdcm/cluster_k8s/mini_k8s.py
K8S functional tests do not work on local K8S backend anymore after
merge of the [1] change where was added configuration of logging
sub-system.
It must not run on any part of the K8S test run, including host
machine for a local K8S cluster.
So, stop configuring logging on K8S backends.
[1] https://github.com/scylladb/scylla-cluster-tests/commit/a321ad25
=> fix(k8s-functional): disable logging configuration as redundant

jenkins-pipelines/operator/performance/perf-regression-latency-eks.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-throughput-eks.jenkinsfile, sdcm/sct_config.py, vars/perfRegressionParallelPipeline.groovy
We have main monitoring being deployed in a standalone VM which is used
for debugging and dev needs. The K8S one is used, as of now, only to test general possibility to deploy it.
So, disable unneeded K8S-based monitoring on the K8S performance jobs
to reduce amount of noise and spent time for provisioning of redundant nodes and pods.
=> ci(k8s-perf): do not deploy K8S monitoring running performance jobs

sdcm/cluster.py
Amos's PR (https://github.com/apache/cassandra-harry/pull/10) to
cassandra-harry was merged, so we can change this to the official
repo.
=> fix(install_cassandra_harry): Change from Amos fork to official

jenkins-pipelines/features-nodetool-stop-compaction.jenkinsfile, sdcm/cluster.py, sdcm/nemesis.py, sdcm/provision/scylla_yaml/scylla_yaml.py, sdcm/rest/remote_curl_client.py, sdcm/rest/rest_client.py, sdcm/rest/storage_service_client.py, sdcm/utils/common.py, sdcm/utils/compaction_ops.py, stop_compaction_test.py, test-cases/features/stop-compaction.yaml, test-cases/longevity/longevity-10gb-3h.yaml
The PR introduces a set of new tests and related nemesis methods for starting and stopping different types of compaction. The general flow of these is:
1. Meet the prerequisites for a given compaction type.
2. Trigger a given compaction type.
3. Watch the logs for a line informing about the compaction type being run.
4. Stop the compaction with a `nodetool stop <COMPACTION TYPE>` command.
5. Grep the logs for lines informing of the compaction being stopped.
There are 6 compaction types covered in total: MAJOR, SCRUB, CLEANUP, VALIDATION, UPGRADE, RESHAPE. There are relevant nemesis classes, methods and test cases for each of them.
Due to the fact that I trigger the compactions via API, I introduced a general RestClient class and subclasses for running the REST calls on a remoter via …
=> Nodetool stop nemesis

sdcm/cluster.py
It should be called as a property without parenthases.
=> fix(cluster.py): fix a call to scylla_packages_installed()

unit_tests/test_base_version.py
Pylint fails with import-error, probably due to the module naming
```
15:52:21  ************* Module unit_tests.test_base_version
15:52:21  unit_tests/test_base_version.py:17:0: E0401: Unable to import 'utils.get_supported_scylla_base_versions' (import-error)
```
=> fix(test_base_version): make pylint happy

unit_tests/test_base_version.py
Fixes following error:
```
20:24:46  
20:24:46  self = <unit_tests.test_base_version.TestBaseVersion testMethod=test_master>
20:24:46  
20:24:46      def test_master(self):
20:24:46          scylla_repo = self.url_base + 'unstable/scylla/master/rpm/centos/2021-08-29T00:58:58Z/scylla.repo'
20:24:46          linux_distro = 'centos'
20:24:46          version_list = general_test(scylla_repo, linux_distro)
20:24:46  >       self.assertEqual(version_list, ['4.5'])
20:24:46  E       AssertionError: Lists differ: ['4.6'] != ['4.5']
20:24:46  E       
20:24:46  E       First differing element 0:
20:24:46  E       '4.6'
20:24:46  E       '4.5'
20:24:46  E       
20:24:46  E       - ['4.6']
20:24:46  E       ?     ^
20:24:46  E       
20:24:46  E       + ['4.5']
20:24:46  E       ?   
```
=> fix(test_master): master is on 4.6

sdcm/cluster.py, sdcm/provision/common/utils.py, sdcm/test_config.py
Fix syslog-ng installation on Debian.
=> fix(syslog-ng): wait for dpkg lock before install

sdcm/cluster_k8s/__init__.py
We need to increase RAM that we provide for Scylla manager agents,
because we get it OOMkilled lots of times.
Observed peak value is about 400Mb.
So, increase it to be 500Mb instead of 100Mb to make sure we do not
exceed it.
=> fix(k8s-mgmt): increase RAM for manager agent container

sdcm/k8s_configs/minio/values.yaml
Testing Scylla manager backups on K8S fails with following error:
We encountered an internal error, please try again.:
cause(mkdir /export/.minio.sys/buckets/minio-bucket/\
scylla-manager-agent-826638828: no space left on device)
On EKS manager utilizes about 47Gb making 28 backups.
GKE uses less than EKS.
So, increase the storage size making it be 60Gb instead of 10Gb
to satisfy backups needs.
=> fix(s3-minio): increase size of the storage used by minio service

sdcm/cluster_k8s/__init__.py
It happens that running 'restart_scylla' method on K8S may
face race condition where we do not wait for the restart to happen.
And it causes incorrect behavior of the 'test_scylla_yaml_override'
functional test.
So, fix it by adding additional sleep between restart operation
and attempt to wait for it's rollout tracking resource appearence.
=> fix(k8s-functional): avoid races restarting Scylla pods

sdcm/cluster_k8s/__init__.py
Do it using latest operator versions to avoid possible failures
of setup-node pods which will cause Scylla pods failures.
=> fix(k8s-eks): use --setup-disks option for scylla-machine-image pods

artifacts_test.py, sdcm/utils/housekeeping.py
Task:
https://trello.com/c/v204rFpm/4339-attributeerror-artifactstest-object-has-no-attribute-housekeeping
Failed test:
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2004-arm-test/61/execution/node/52/log/
Test failed because failed to create the node and actually the tes was not started.
As result the 'housekeeping' attribute wasn't created.
The fix is to check if the attribute exists
=> fix(artifact test): verify that 'housekeeping' attribute exists

sdcm/sct_events/group_common_events.py
'Connection refused' YcsbStressEvent is filtered in upgrade test when an upgraded node is
restarted and it's unable to connect to alternator.
In the test https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-alternator-test/63/ another wording of this error was received:
```
Unable to execute HTTP request: Connect to alternator:8080 [alternator/10.142.0.127] failed: Connection refused (Connection refused)
```
Change the regex for the filter accordingly
=> fix(upgrade test): change regex in ignore_ycsb_connection_refused filter

sdcm/cluster.py
It's a kind of backport of https://github.com/scylladb/scylla-cluster-tests/pull/4188 to branch-perf-v8
=> [branch-perf-v8] fix(cluster.py): set prometheus_address to 0.0.0.0

sdcm/cluster.py
It's a kind of backport of https://github.com/scylladb/scylla-cluster-tests/pull/4188 to branch-perf-v10
=> [branch-perf-v10] fix(cluster.py): set prometheus_address to 0.0.0.0

mgmt_cli_test.py
In some of the tests in the mgmt_cli_test, the tests wait for the manager
task to reach the status of 'DONE' alone. And if there was an error,
the wait_for function will just wait until timeout is reached.
As such, I used wait_and_get_final_status instead
=> fix(mgmt_cli_test): wait for any final task status instead of DONE

jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, test-cases/manager/manager-regression-gce.yaml, vars/managerPipeline.groovy
Since SCT can't detect scylla db images when choosing scylla_version,
I modified the default in manager tests to use scylla 4.5.2 for gce_image_db
and set use_preinstalled_scylla to true, so sct will not try to install scylla
on the existing image.
=> fix(manager pipeline): Added the option to use gce scylla image

jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile
=> fix(centos-manager-backup-gce): Removed duplicated scylla_version param

artifacts_test.py
There is no perftune.yaml on Docker image, so, return None (unset) for
write_back_cache setting in that case.
=> fix(artifacts_test): ignore absence of perftune.yaml

sdcm/argus_test_run.py
There is a possibility sct_config.region_names can be an empty list,
this ensures an out of bounds access doesn't happen
=> fix(sdcm/argus_test_run.py): Check list length before usage

sdcm/cluster.py
Task: https://trello.com/c/MyT25VCr/4263-cloud-longevity-fail-to-get-scyllaargs
To find 'SMP' property we read 'scylla-server' file. When a test run on AWS this file
has read permission for root user only. Use sudo
- [x ] I didn't leave commented-out/debugging code
=> fix(base node): read scylla-server file with sudo

sdcm/sct_events/filters.py, sdcm/sct_events/group_common_events.py
following commit in #4195 the failure
described in there kept happening,
and it seemed that there was a mismatch
between the event filter being called
and the supported types.
=> fix(ycsb filter): added to EventsFilter

sdcm/cluster.py, sdcm/sct_events/filters.py
Trello: https://trello.com/c/pigJaXBg/4379-event-filters-use-node-name-instead-of-strnode
Fixes #4217
=> fix(filters): use node name for filtering

sdcm/utils/cdc/options.py
Support of the 'on' and 'off' values for the 'preimage' CDC option
was recently removed [1].
So, switch to the documented 'true' and 'false' values to make
'ToggleCdcFeaturePropertiesOnTable' nemesis work.
[1] https://github.com/scylladb/scylla/pull/9639
=> fix(nemesis): Use proper values for the 'preimage' CDC option

configurations/rolling-upgrade-with-null-inserts.yaml
the user profile path/name had a typo (it was missing
the "s" in the end of the file.
=> fix(rolling-upgrade-with-null-inserts): typo user profile

sdcm/utils/pricing.py
since i4 is still no generally available there are
no prices for i4 family in AWS pricing API
=> fix(aws_pricing): price i4 as i3

sdcm/cluster.py
In https://github.com/scylladb/scylla-pkg/pull/2622 we started to use
the new gpg keys in master and 4.6
makeing sure artifact tests will use the new keys as well
=> fix(cluster.py):add new gpg public key

sdcm/utils/sstable/load_utils.py
Starting with Scylla 4.7 the log lines for 'Resharding' has changed
and existing pattern here doesn't match it anymore.
So, update it to make it work on both log variants - old and new ones.
=> fix(nemesis): use proper pattern for searching resharding log lines

jenkins-pipelines/artifacts-debian10-arm.jenkinsfile, jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile, jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile
After backporting the artifacts tests of ARM to 2021.1, I need this PR Since manager doesn't support arm instances yet.
=> fix(artifacts): Remove manager agent from arm artifacts

sdcm/utils/common.py
Task: https://trello.com/c/4PeL1Tke/4199-link-to-sctlog-is-missing-in-the-email
If sct.log size is big, we create logs archive not as single archive but per file.
In this case the link for sct.log archive can be found on the job run console, but missed in the email
and issue template.
Example of fixed email:
```
Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/c63a6913-6253-45a0-b5cf-d553f713fe81/20211222_101240/grafana-screenshot-overview-20211222_101240-longevity-10gb-3h-archive--monitor-node-c63a6913-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/c63a6913-6253-45a0-b5cf-d553f713fe81/20211222_101240/grafana-screenshot-overview-20211222_101240-longevity-10gb-3h-archive--monitor-node-c63a6913-1.png)
grafana - …
```
=> fix(email): print link for archive of sct.log

sct.py, sdcm/logcollector.py
This commit presents 2 fixes for case when a log archive is created per file:
1. add test_id to archive name how it's done for all other archives
2. when list of archive links is printed on console, set link name according to the
log file, like:
`warning` for link of warning.log (and not 'sct-runner' like it is printed now)
Test result:
```
14:27:57  +---------------------------------------------------------------------------------------------------------------------------------------------------------+
14:27:57  |                                             Collected logs by test-id: a656ccff-c8d0-4fb1-9204-4a9100d8d127                                             |
14:27:57  +----------------+------------------------------------------------------------------------------------------------- …
```
=> fix(logcollector): fix names in case archive per file

sdcm/argus_test_run.py
Multi-DC configuration uses strings for specifying node amounts, which
is not supported by Argus' CloudNodesInfo. For now, those amounts will
be summed into a single number and saved this way.
[Trello](https://trello.com/c/dUaQq5nc/4438-argusdb-failed-to-setup-connection)
=> fix(argus_test_run.py): Fix multi-dc node amounts

defaults/test_default.yaml, sdcm/sct_config.py, test-cases/gemini/gemini-1tb-10h.yaml, test-cases/gemini/gemini-3h-with-nemesis.yaml, test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml, unit_tests/test_config.py, unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml, unit_tests/test_scylla_yaml_builders.py
Change Oracle version for gemini tests to 4.4.7
=> fix(gemini-yaml): change oracle version

sdcm/nemesis.py
seen an issue where test is stuck in one of the
LDAP nemesis for an OSS cluster.
adding a verification and will skip the nemesis
if it is not enterprise.
fixes #4261
=> fix(ldap nemesis): skip if cluster is not enterprise

defaults/test_default.yaml
Manager mastr isn't stable and changes aren't communicated well to
the QA team. Hence, I decided to test scylla master with a "Fixed"
latest released manager version.
=> refactor(test_default): Set master branch to use manager 2.5

sdcm/utils/cloud_monitor/templates/base.html
Removing the word resourcers from the link description.
=> fix(base cloud_monitor report template): Change link description

test-cases/artifacts/debian10.yaml, test-cases/artifacts/debian11.yaml, test-cases/artifacts/debian9.yaml, test-cases/artifacts/ubuntu1604.yaml, test-cases/artifacts/ubuntu1804.yaml, test-cases/artifacts/ubuntu2004.yaml
* Adding `5E08FBD8B5D6EC9C` to run scylla4.7 with manager2.5
* Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4272
=> fix(defaults): Fixing artifacts jobs to work with manager2.5

unit_tests/test_cluster.py
=> fix(unit_tests/test_cluster.py): Fixing test_search_power_off test

sdcm/utils/common.py, unit_tests/test_utils_common.py
gce Bucket returned with first element as dir, and this break
downloading files.
Example of failed job:
https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/job/longevity-1tb-7days-gce-test/10/execution/node/142/log/
=> fix(gce_download): skip first element in bucket

mgmt_cli_test.py
Since test_healthcheck_change_max_timeout requires a multi dc cluster,
and sct can't create an ipv6 multi dc cluster, I skipped the test for
ipv6 runs.
=> fix(manager sanity): skip test_healthcheck_change_max_timeout for ipv6

sdcm/provision/aws/instance_parameters.py, sdcm/provision/aws/provisioner.py, sdcm/provision/aws/utils.py, sdcm/sct_config.py, sdcm/sct_provision/aws/cluster.py, sdcm/sct_provision/aws/instance_parameters_builder.py
https://trello.com/c/P7Eo1SdE/4446-provision-fix-issue-with-ipv6
Reason why IPV6 did on work on provisioned instances was that user-data was not executed on them.
There are two reasons for that :
1. We used scylla-based user data for loaders, which was wrong
2. Something in the scripts did not allow it to be executed properly
=> fix(provision): make it work for ipv6

test-cases/longevity/longevity-nosqlbench-3h.yaml
Small fix for the nosqlbench longevity test case.
=> fix(nemesis): add 'limited' filter for nosqlbench test case

defaults/manager_versions.yaml, defaults/test_default.yaml
Manager 2.6.0 is released and should be used for master and scylla
v4.6.
=> refactor(test_default): Set master branch to use manager 2.6

vars/managerPipeline.groovy
It was decided to use the latest released scylla version for manager tests,
so I set scylla_version for all manager tests.
Also, since the default manager_version is now the latest released version,
I set it to be manager_latest for manager tests.
=> fix(manager tests): set manager:master_latest and scylla_version:4.5

unit_tests/test_sct_events_operator.py
Since year is getting from `.now()` and not from the log print itself
the hardcoded numbers in the test are not valid anymore, now that
we are at 2022.
test was failing like this in PRs CI:
```
12:14:06  >       assert event.timestamp == 1624896463.572294
12:14:06  E       AssertionError: assert 1656432463.572294 == 1624896463.572294
12:14:06  E         +1656432463.572294
12:14:06  E         -1624896463.572294
```
=> fix(test_sct_events_operator): remove hard-coded dates for test

sdcm/sct_events/database.py
As result of https://github.com/scylladb/scylla-cluster-tests/pull/4245 log level for
Repair and Compaction events is back to INFO instead of DEBUG and those events are
printed out on the job console. It's a lot of events and we don't want to see them
on the console
=> fix(print on console): change log level for repair and compaction events

sdcm/sct_events/group_common_events.py
In recent jobs of branch-4.6, we run into those line which was raised
as error events:
```
ERR |  [shard 2] commitlog - Could not delete segment /var/lib/scylla/
hints/2/10.142.0.61/HintsLog-2-36028797022305996.log: std::filesystem::
__cxx11::filesystem_error (error system:2, filesystem error: stat
failed: No such file or directory [/var/lib/scylla/hints/2/
10.142.0.61/HintsLog-2-36028797022305996.log])
```
those are failure on files that were failing to be written cause of
there is no space on the device, hence we can also ignore those errors.
=> fix(nemesis_enospc): ignore "No such file or directory" log

jenkins-pipelines/artifacts-ami-arm.jenkinsfile, vars/artifactsPipeline.groovy
Since arm instances cannot be currently created in our default availability zone (a)
I created a seperate jenkinsfile for the artifact ami of arm processors
which uses the proper availability zone.
=> fix(arm ami test): set availability_zone to c

defaults/test_default.yaml, test-cases/longevity/longevity-10gb-3h.yaml, test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml, test-cases/manager/manager-regression-gce.yaml, unit_tests/test_config.py, unit_tests/test_data/test_scylla_yaml_builders/longevity-10gb-3h.yaml
we are seeing in both `branch-4.5` and `branch-4.6` failures
(c-s getting stuck too long after duration is finished)
and is causing failures in GCE tests.
bumping the version might give us the chance to surpass
these failures, as they are most likely to be
already fixed in an later version of it.
have [a job running](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/4.6/job/3h-gce-4.6/2/) in my staging folder to confirm it fixes the issue
=> fix(bump loader repo): there might be old issues with previous version

test-cases/longevity/longevity-large-partition-4days.yaml
Adjusted scylla-bench params in order to get a better load.
=> improvement(large-partition-4days.yaml): s-b tuning for better workload

jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile, test-cases/artifacts/ubuntu1604.yaml
Since ubuntu 1604 LTS is finished, moving to use ubuntu pro images.
which should be available until April 2026
Ref: https://cloud.google.com/compute/docs/images/os-details#ubuntu_pro
=> fix(rolling_upgrade): use pro images for ubuntu 1604

configurations/arm_instance_types/Is4gen_4xlarge.yaml, jenkins-pipelines/longevity-100gb-4h-arm.jenkinsfile, jenkins-pipelines/longevity-200gb-48h-arm.jenkinsfile, jenkins-pipelines/longevity-50gb-3days-arm.jenkinsfile, vars/longevityPipeline.groovy, vars/provisionResources.groovy, vars/runSctTest.groovy
Since arm is only supported in specific availability zones across different
aws regions, I set the availability_zone of all arm jobs to 'c' by default,
since it is supported both in us-east-1 and eu-west-1.
=> test(arm support): Created new arm longevities

jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile, jenkins-pipelines/rolling-upgrade-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos7-ldap-authorization.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian11.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile, jenkins-pipelines/rolling-upgrade-multidc.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile, test-cases/upgrades/generic-rolling-upgrade.yaml, test-cases/upgrades/multi-dc-rolling-upgrade.yaml, test-cases/upgrades/rolling-upgrade.yaml, vars/rollingUpgradePipeline.groovy
Rolling upgrade jobs keep timeing out during log collection or
sending mails out, this change aligns the pipeline timeout are handled
to the same method as longevity pipelines are doing that
=> fix(rolling-upgrades): Remove total pipeline timeout

sdcm/scan_operation_thread.py, test-cases/longevity/longevity-100GB-48h-cloud-CloudLimitedChaosMonkey-tls.yaml, test-cases/longevity/longevity-10gb-3h.yaml, test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml, test-cases/longevity/longevity-200GB-48h-network-monkey.yaml, test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml, test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml, test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml, test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml, test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml, test-cases/longevity/longevity-in-memory-36GB-1day.yaml, test-cases/longevity/longevity-multi-keyspaces.yaml, test-cases/longevity/longevity-mv-si-4days.yaml
1. 	Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4304
2. Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4306
Added a missing commit from reversed-queries PR:
- fix(full scan): Update new format of run_fullscan params in yaml
-     
-             Following the enhancement of reversed-queries new scan thread,
-             The yaml parameter of run_fullscan has a new format.
=> fix(scan_operation_thread.py): Wait for table to be created before running a scan thread

add_new_dc_test.py, jenkins-pipelines/features-add-new-dc.jenkinsfile, test-cases/features/add-new-dc.yaml
New dc test required some modifications per comments in https://github.com/scylladb/scylla-cluster-tests/pull/4206
Most important: removing dc, so we start off with one.
trello: https://trello.com/c/v0fwzr67
=> fix(add-dc-test): remove unnecesary dc

sdcm/logcollector.py, sdcm/utils/log.py
Save all argus messages in the separate argus.log file and collect it within sct-runner.tar.gz
=> improvement(argus): send argus's output to a separate log

artifacts_test.py, docker/alternator-dns/dns_server.py, sdcm/cluster_k8s/__init__.py, sdcm/coredump.py, sdcm/db_log_reader.py, sdcm/remote/libssh2_client/__init__.py, sdcm/remote/libssh2_client/session.py, sdcm/remote/remote_libssh_cmd_runner.py, sdcm/sct_events/continuous_event.py, sdcm/tester.py, sdcm/utils/common.py, sdcm/utils/k8s.py, sdcm/utils/remote_logger.py, unit_tests/test_tester.py
https://trello.com/c/d7RlVP0u/4480-fix-test-failing-procedure-on-critical-event
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/4309
We raise `AssertionError` in the event handler to stop the test.
Python is taking this exception and throw it at the current execution point of the MainThread.
The problem is that if current execution point in the MainThread is running inside 
```
try:
...
except Exception:
... 
```
this exception will be caught and test won't stop.
Solution is to probably raise something derived not from `Exception`, but from `BaseException`, which will make it through the except filter unless it is bare exception:
```
except:
```
So, in total, solution is to go over code and convert `except:` to `except Exception:`
And fix `critical_failure_handler` to use …
=> Fix critical error handling

data_dir/cdc_profile.yaml, data_dir/cdc_profile_multidc.yaml, data_dir/cdc_profile_multidc_postimage.yaml, data_dir/cdc_profile_multidc_preimage.yaml, data_dir/cdc_profile_multidc_preimage_postimage.yaml, data_dir/cdc_profile_postimage.yaml, data_dir/cdc_profile_preimage_postimage.yaml, jenkins-pipelines/longevity-cdc-8h-multi-dc-topology-changes.jenkinsfile, sdcm/nemesis.py, test-cases/longevity/longevity-cdc-100gb-8h-multi-dc-topology-changes.yaml, unit_tests/test_nemesis.py
Starting from branch-4.6 new system_distributed_everywhere keyspace was added. 
Data of this keyspace replicated to each node in cluster. First consumer of the keyspace
is cdc. It stores there new cdc_generation_description table. It is system table and not 
should be used by user. Regular tests for cdc + multi dc should be enough for testing.
Add new job for testing cdc in multi dc cluster configuration with new nemesis
Update c-s profiles for cdc to support multi dc.
Change replication class to NetworkTopology
Trello: https://trello.com/c/3xwu3ugW
=> feature(cdcmultidc): New job 8h-cdc-multidc-topology-changes

sdcm/sct_runner.py
Since Cloud instance stopper supports only tags/labels
we need to set the instance keep tag to alive.
This is needed to prevent Cloud instance stopper script
to kill the SCT Runner
=> fix(gce-sct-runner): keep instance alive

sdcm/utils/syslogng.py
Fixes problem when ssh-tunnel is used for logging.
It eats 2-4 connections per host, as result we reach limit of connections quickly.
=> fix(syslog-ng): raise connection limit

test-cases/longevity/longevity-counters-3h.yaml, test-cases/longevity/longevity-lwt-1loader-3h.yaml
=> fix(3h-test-cases): fix timeouts

sdcm/utils/aws_utils.py, sdcm/utils/common.py
Fix get_branched_ami and get_scylla_ami_versions to respect architecture
ARM image was released and tagged same way we where doing that for x64.
Since SCT ignores architecture flag, we pick it up and run test on it.
=> feature(aws utils): make them respect arch

sdcm/sct_events/continuous_event.py, sdcm/sct_events/database.py
It will prevent events with different classed to have same hash
Also it adds hash to the RepairEvent body
=> fix(continuous): add event type to hash

sdcm/provision/aws/configuration_script.py, sdcm/provision/common/configuration_script.py
Currently we wait for cloud-init on GCE, which should not be the case.
=> fix(boot script): wait cloud-init only on aws

vars/perfRegressionParallelPipeline.groovy
to performance jobs.
it was partially done to other jobs, but not for
performance jobs.
=> fix(arm support): allow setting availability zone

sdcm/nemesis.py
During the stream, a restart is starting, and therefore the following error messages may appear:
```
2022-01-15 00:49:05.632 <2022-01-15 00:47:02.000>: (DatabaseLogEvent Severity.ERROR)
period_type=one-time event_id=5d8f8270-b1b3-4e6a-bf45-8dbb3eb77f57: type=RUNTIME_ERROR
regex=std::runtime_error line_number=492793 node=alternator-48h-4-6-db-node-1e00ab80-4
2022-01-15T00:47:02+00:00 alternator-48h-4-6-db-node-1e00ab80-4 ! WARNING |  [shard 11]
repair - repair id [id=4, uuid=4a70db2c-4a05-45a6-afb1-4c07e5695290] on shard 11,
keyspace=alternator_usertable, cf=usertable, range=(-8471296100733622237, -8454395072449928136],
got error in row level repair: std::runtime_error (get_full_row_hashes: Peer failed to process
```
=> fix(nemesis.py): Ignoring "got error in row level repair" error during repair

data_dir/lwt_builtin_functions.yaml, test-cases/longevity/longevity-lwt-500G-3d.yaml, test-cases/longevity/longevity-lwt-basic-3h.yaml
Issue: https://github.com/scylladb/scylla/issues/8604
Task: https://trello.com/c/N9mTs8tp/4382-sct-using-non-deterministic-functions-in-partition-
keys-issue-8604
When type of PK column is non-determenistic function (like, uuid, currentTimestamp), LWT queries
sporadic fail.
Run this queries with multiple threads and long time to increase chance to get failure 
Fix: https://github.com/scylladb/scylla/commit/0876248c2b4296295fbd28c536b606bb0398c3fa
=> test(lwt longevity): using non-deterministic function in PK

sdcm/cluster.py, sdcm/utils/housekeeping.py
Issue: https://github.com/scylladb/scylla/issues/9683
Artifact test on OEL81 fails with error:
`Permission denied: '/etc/yum.repos.d/scylla-manager.repo'`
Read permissions for this file are for 'root' user only:
`rw-------. 1 root root  206 Nov 24 15:12 scylla-manager.repo`
This fix change the permission to allow to read scylla-manager.repo from
scylla user.
Test passed
It also fixed https://github.com/scylladb/scylla-enterprise/issues/2062
=> fix(oel81): set permissions to scylla-manager.repo

vars/rollingUpgradePipeline.groovy
in almost all upgrade jobs in last master, this
stage called "get test duration" was timing out,
failing the whole test.
it could be a problem with Jenkins load (as
all the jobs are running in parallel), an issue
with GitHub or either some networking issue.
now, the `checkout scm` will be done in a
different stage, letting enough time to get
the test's duration.
=> fix(get test duration): separate it from `checkout scm`

sdcm/cluster.py, sdcm/sct_config.py, sdcm/scylla_bench_thread.py, test-cases/longevity/longevity-twcs-3h.yaml, test-cases/longevity/longevity-twcs-48h.yaml, unit_tests/test_config.py
Scylla-bench with workload=timeseries in read mode should use
start timestamp from scylla-bench command in write mode.
In case of fix Issue 4241 to scylla_bench_thread was added
file log reader which parse output from write command with
timeserieis workload and pass it to read command
=> fix(scylla-bench-thread): Run sb read cmd with timestamp from sb write

sdcm/cluster.py, test-cases/longevity/longevity-harry-2h.yaml
The command contained the full path of the command and not just
the "tool" name. Thus, the "cassandra-harry" is not installed
because the following "if" returned a False value.
```
if 'cassandra-harry' in self.params.list_of_stress_tools:
if not node.is_cassandra_harry_installed:
node.install_cassandra_harry(node)
```
The second problem was that the POM file contained
a failed dependency.
Thus, this dependency to remove as Amos did in his branch.
Add a new test to verify the installation of
`cassandra-harry` is working.
=> fix(sdcm/cluster.py): Fixing install_cassandra_harry method

test-cases/longevity/longevity-nosqlbench-3h.yaml
Follow-up PR after https://github.com/scylladb/scylla-cluster-tests/pull/4236 This should make the longevity avoid bumping into disruptive nemesis events.
=> fix(nosqlbench): set nemesis class to NonDisruptive

vars/rollingUpgradePipeline.groovy
because in some cases we have upgrade running
for multiple different base versions, we are
seen stages with the same name (like the latest
splitted "checkout"), so adding the base version
to the stage name (as all other stages) will
make it much clearer.
following #4338 , now we see twice "Checkout" (where is one for each base version), but it is a bit misleading.
=> fix(upgrade pipeline): add version to stage

sct.py
This makes store_logs_in_argus always use log filename in the url
instead of using cluster_type value as provided by log collector, as it
can provide duplicate values in case when sct-runner logs are split into
multiple parts due to size. Type can be further inferred from said
filename by splitting by the dash symbol down the line.
[Trello](https://trello.com/c/XviyVMoq/4510-argus-use-file-name-instead-of-log-type-in-logs-tab)
=> fix(sct.py): Always use log filename instead of cluster_type value

jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-add-remove-rack.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-backup.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-cluster-rolling.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-grow-shrink.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-repair.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-replace.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-scylla-enterprise.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-stop-start.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-terminate-decommission-add.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-terminate-replace.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-basic-3h-eks-scylla-enterprise.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-basic-3h-eks.jenkinsfile, jenkins-pipelines/operator/functional/functional-eks.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-latency-eks.jenkinsfile, jenkins-pipelines/operator/performance/perf-regression-throughput-eks.jenkinsfile, jenkins-pipelines/operator/upgrade/upgrade-major-scylla-k8s-eks.jenkinsfile, jenkins-pipelines/operator/upgrade/upgrade-operator-k8s-eks.jenkinsfile, jenkins-pipelines/operator/upgrade/upgrade-platform-k8s-eks.jenkinsfile, jenkins-pipelines/operator/upgrade/upgrade-scylla-k8s-eks.jenkinsfile
Recently was added 'availability_zone' parameter to pipelines
which started getting default value from it instead of the default
config files. It leads to the situation where it has wrong value making
EKS test runs fail on the start.
So, set correct value for the EKS jobs explicitely.
=> fix(k8s-eks): set availability_zone in pipelines

defaults/k8s_eks_config.yaml, defaults/k8s_gke_config.yaml, defaults/k8s_local_kind_config.yaml, defaults/test_default.yaml, docs/configuration_options.md, sdcm/cluster_k8s/__init__.py, sdcm/sct_config.py
Mostly we do not need big size for the backup storage of Scylla manager
But we have CI jobs which run Scylla with huge data.
So, make MinIO storage be configurable to be able to increase it's size
for some specific CI jobs.
=> feature(operator): make MinIO storage be configurable

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/eks.py, sdcm/utils/common.py
As of now we set tags only to node groups of an EKS cluster.
The problem with it is that it doesn't propagate it further to
the nodes.
So, set it explicitly ourselves to make logic based on the tags work
for nodes deployed by EKS clusters.
=> fix(operator): add 'keep' tag for EKS cluster nodes

sdcm/utils/version_utils.py, unit_tests/test_version_utils.py
If scylla_version is empty in the cluster params (test uses scylla_ami for example),
the nemesis will be skipped with 'version is not supported' reason because cluster
version won't be recognized
=> fix(version_util): get scylla version

vars/longevityPipeline.groovy, vars/rollingOperatorUpgradePipeline.groovy, vars/runSctTest.groovy
Longevity pipelines call bunch of other groovy functions and
in some cases it is needed to get option from the pipelineParams
which must not be exposed in user-facing 'params' dictionary.
So, update runSctTest groovy func to accept one more argument.
=> improvement(pipelines): propagate pipelineParams to runSctTest

functional_tests/scylla_operator/test_functional.py, sdcm/nemesis.py
=> fix(nemesis): make various nemesis consider operator specifics

configurations/operator/200GB-no-tls.yaml, configurations/operator/large-collections-12h.yaml, configurations/operator/lwt-basic-24h.yaml, configurations/operator/twcs-basic-48h.yaml, jenkins-pipelines/operator/eks/longevity-scylla-operator-200gb-48h.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-large-collections-12h.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-lwt-24h.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-twcs-48h.jenkinsfile
List of new jobs:
- 200gb-48h
- large-collections-12h
- lwt-24h
- twcs-48h
=> ci(operator): add long longevities CI jobs

Jenkinsfile
=> fix(Jenkinsfile): add 10s sleep after start of a mock server

test-cases/jepsen/jepsen.yaml
Trello: https://trello.com/c/1ypTcfNo/4568-jepsen-run-on-master-ends-up-with-repository-content-has-invalid-line-4362
The issue was introduced by #4299.
Fixes #4362
=> fix(jepsen.yaml): set scylla_repo_loader

configurations/operator/200GB-no-tls.yaml
Disable auth on the loader side correctly for the "200Gb-48h" CI job
that runs for operator to avoid following errors:
An authentication challenge was not sent, this is suspicious
because the driver expects authentication
(configured authenticator = PlainTextAuthenticator)
=> fix(config): do not enable auth on client side correctly

sdcm/nemesis.py, test-cases/longevity/longevity-200GB-48h-network-monkey.yaml
=> Fix sisyphus checking for empty list of disruptions

jenkins-pipelines/features-nodetool-stop-compaction.jenkinsfile, sdcm/nemesis.py, stop_compaction_test.py
Fix for: https://github.com/scylladb/scylla-cluster-tests/issues/4248
Trello task: https://trello.com/c/WAMaLJBv
=> fix(nemesis): remove wait for no compactions running

configurations/raid/raid5.yaml, defaults/test_default.yaml, docs/configuration_options.md, jenkins-pipelines/longevity-10gb-3h-gce-raid-5.jenkinsfile, sdcm/cluster_aws.py, sdcm/cluster_gce.py, sdcm/provision/common/user_data.py, sdcm/sct_config.py, sdcm/sct_provision/aws/user_data.py
scylla-4.6 have support to create 2 kind of
raid configuration: RAID0 and RAID5.
Scylla: https://github.com/scylladb/scylla/commit/42fd73d0332d034809c6cd228785bff82e1845aa
Feature: https://github.com/scylladb/scylla/pull/9093
=> feature(raid_support): Support raid configuration

sct.py, sdcm/logcollector.py, sdcm/parallel_timeline_report/generate_pt_report.py, sdcm/report_templates/results_base.html, sdcm/send_email.py, sdcm/utils/common.py, vars/longevityPipeline.groovy, vars/runGeneratePTReport.groovy
Integration of the parallel timelines generator with SCT. The generator creates HTML-reports for the graphical representation of the SCT events. Currently, it works only for Longevities (4 hours and shorter).
Trello tasks:
- [3962-integrate-parallel-timelines-with-sct](https://trello.com/c/oC3GruWg/3962-integrate-parallel-timelines-with-sct)
- [4124-add-compaction-events-to-the-parallel-timeline-chart](https://trello.com/c/6S3ga9KY/4124-add-compaction-events-to-the-parallel-timeline-chart)
=> feature(longevity tests): integrate parallel timelines report

sdcm/cluster_k8s/__init__.py
Upgrading a Scylla cluster on K8S we check Scylla pod info update.
It's 'status.image' field must start containing new value.
And right now we check equality of expected and actual values.
But there may be 2 variants of it like following:
- scylladb/scylla:4.5.3
- docker.io/scylladb/scylla:4.5.3
So, to avoid false negative errors make it perform checks considering
both cases.
=> fix(operator): do proper image path check for the Scylla upgrades

sdcm/cluster_k8s/__init__.py, sdcm/nemesis.py
We should not run 'decommission_streaming_err' nemesis on K8S due to
the following reasons:
- 'decommission_streaming_err' nemesis uses 'nodetool decommision'
command which will make K8S Scylla pod be in 'NotReady' state
but exist all the time. Instead we should decomission it by reducing
number of Scylla cluster members via the ScyllaCluster CR update.
- The approach for the node number increase checks the workability of
all the pods and will fail on that 'NotReady' pod.
- Increate of pod number will exclude decommissioned pod from the
list of nodes increase it by 1 and the resulting value will be
equal to the pod count. So, nothing will change.
So, skip this nemesis as it is not expected to work.
=> fix(nemesis): skip decommission_streaming_err on K8S

sdcm/nemesis.py, sdcm/utils/replication_strategy_utils.py
fix for https://github.com/scylladb/scylla-cluster-tests/issues/4300
Seems problem was occurring when e.g. system_traces keyspace is using SimpleStrategy and we switch it to NetworkStrategy with changed replication factor.
This fix makes we don't change rf when switching to Network Replication Strategy (unless `system_auth`, it requires to be replicated across all the nodes). Also added repair for each switched keyspace (I'm not sure if required).
This fix should also resolve problem of leaking garbage from `get_nodetool_status` - as we're not relying on it that much
=> fix(add-remove-dc-nemesis): fix switch replication strategy

defaults/gce_config.yaml, unit_tests/test_config.py
Since the logic was depended on `gce_image_db` to be empty for doing
the lookup for gce images, we should make the default empty.
the rest of the test like rolling upgrade and partners already select
thier images as needed.
=> fix(longivites): ability to use scylla_version for gce longevities

sdcm/cluster.py
Task: https://trello.com/c/TFF1z6sk/4587-nodestatus-nonetype-has-no-attribute-stdout
If node is down, run_nodetool function will return None object in result variable.
When we try to fetch stdout from result it will fail  with not correct message:
'NoneType' object has no attribute 'stdout'
And real error will be hide.
As result of this fix real error will be raised
=> fix(nodetool status): raise real error when node is not up

configurations/operator/200GB-no-tls.yaml
For the moment CI job with the "200gb-48h" config has MinIO disk
size be equal to 4Tb. It is not enough for 3 mgmt backups which happen
there. Each backup takes about 1,3-1,4Tb. So, increase it by 500Gb
to make sure we can place 3 mgmt backups on this disk having such
huge set of data - 200Gb (basis) + ~140Gb ongoing load.
=> fix(config): increase minio disk size for the "200gb-48h" on K8S

defaults/test_default.yaml
Currently we use v0.1.6 version of the "scylla-bench" tool.
And it uses to much memory starting with v0.1.4 version.
Bug: https://github.com/scylladb/scylla-bench/issues/84
It was fixed in the v0.1.7
So, switch to that new version to make "scylla-bench" use normal amount of memory avoiding OOMKills.
=> fix(scylla-bench): use newer version with fixed memory consumption

sdcm/cluster.py, sdcm/utils/health_checker.py
This commit presents fix for a case when there is a node with non-UN status (was removed during
decommission, for example) and this node does not exist in the cluster.
Bug from commit:
https://github.com/scylladb/scylla-cluster-tests/pull/4375/commits/5784ba340fc6770b73df2e63e00185b6aadcf223
=> fix(health checker): fix case when node was removed from cluster

sdcm/db_stats.py, sdcm/results_performance.html
as running from this old branch (`branch-perf-v8`)
the report is missing the `build-id`, although it
is being collected, but not added to the report.
This commit is meant to specific branch only, and
if still not fixed in master (or newer branches),
another PR will be sent to fix it.
=> improvement(results_performance.html): add build-id to report

sdcm/cluster.py
Since recently centos8 is EOL, and moved to a diffent mirror site,
we can't yum install on it, until patching the repo files.
Fix: #4393
=> fix(centos8): Centos8 is EOL, need to change mirrors

upgrade_test.py
while working for few weeks now on upgrade tests,
feels super miserable to find what is happening in
the logs, as we have a well organised `events.log`,
but the "steps" of the upgrade tests are only printed
in the logs, making very hard to follow after errors
for example, as the errors will appear in the events,
but the stage of the test itself won't.
with this fix, it will be all in one place, and it
will allow to follow much easier after where each
error or failure happened.
the task in trello is here:
https://trello.com/c/Ps3ZUcgl/4172-in-rolling-upgrade-test-convert-all-selfloginfo-to-infoevent
=> improvement(upgrade_test): create InfoEvent instead of log.info

sdcm/cluster.py
Recently was added common VMs-specific code into the
'sdcm/cluster.py' module -> 'cql_ip_address' property.
And this property doesn't work for K8S for 2 reasons:
- On K8S we never have 'broadcast_rpc_address' be setup.
- On K8S we do not use ScyllaYaml class, because it's work
is done by Operator itself.
So, detect that we are on the K8S in this property and return expected
value for it.
=> fix(cluster.py): make K8S work again

sdcm/send_email.py
EKS nodes never have 'Name' tag because it gets created automatically by
the autoscaler which doesn't allow to set names.
So, fix the code that expect the presence of the name making it
set 'N/A' instead.
=> fix(send_email): pick up AWS nodes names properly

defaults/severities.yaml, sdcm/sct_events/database.py
There are lines which are warning level, and we treat them as error
only cause the word `exception` is part of the print
we have those a lot in 2021.1, and we should put them into warning
events as they should.
```
2022-01-04T06:36:22+00:00  ip-10-0-1-54 !WARNING | scylla:  [shard 0]
workload prioritization - update_from_distributed_data: failed to
update configuration for more than  90 seconds :
exceptions::read_timeout_exception (Operation timed out for
system_distributed.service_levels - received only 0 responses
from 1 CL=ONE.)
```
=> feature(events): Add a new WARNING event

utils/build_system/create_test_release_jobs.py
Since we can't predict the time jenkins would pick the job and
actully finish excectuing 2min wasn't enough, and only slowing
down this job it's enough for us just to trigger the job, see
it's in the quoue and continue to the next job
CI would fall with the following:
```
16:47:09  tenacity.RetryError: RetryError[Wait for: Check
job is finished: timeout - 120 seconds - expired]
```
Ref: https://jenkins.scylladb.com/job/QA-tools/job/create-sct-test-jobs-for-branch/12/console
=> fix(create_test_release_jobs): stop waiting for the jobs to finish

configurations/arm/centos8.yaml
CentOS 8 is EOL hence we need to change the AMI.
Using official from https://wiki.centos.org/Cloud/AWS
tested: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/bentsi-staging/job/bentsi-artifacts-centos8-arm-test/2/console
=> fix(centos8-arm): using official CentOS Stream 8

sdcm/cluster.py
Hoping to fix with it the issue we are having with getting connection
disconnected after a few secoands with fabric based remoter
Fix: #4301
=> fix(nodetool): make nodetool command work with their own libssh2 remoter

docker/env/hydra.sh
Trello: https://trello.com/c/5uSYHfzA/4570-end-hydra-script-execution-when-a-command-in-bash-pipe-failed
End hydra script execution when a command in bash pipe failed.
And, because grep can fail a whole pipeline, replace env parsing commands with single sed invocation.
=> improvement(hydra.sh): add pipefail bash option

unit_tests/test_base_version.py
Fix for failing PR checks:
```python
_________________________ TestBaseVersion.test_master __________________________
self = <unit_tests.test_base_version.TestBaseVersion testMethod=test_master>
def test_master(self):
scylla_repo = self.url_base + 'unstable/scylla/master/rpm/centos/2021-08-29T00:58:58Z/scylla.repo'
linux_distro = 'centos'
version_list = general_test(scylla_repo, linux_distro)
>       self.assertEqual(version_list, ['4.6'])
E       AssertionError: Lists differ: ['5.0'] != ['4.6']
E       
E       First differing element 0:
E       '5.0'
E       '4.6'
E       
E       - ['5.0']
E       + ['4.6']
unit_tests/test_base_version.py:36: AssertionError
```
=> fix(test_base_version): master is 5.1

defaults/test_default.yaml, docs/configuration_options.md, jepsen_test.py, sdcm/cluster.py, sdcm/sct_config.py, test-cases/jepsen/jepsen.yaml
Trello: https://trello.com/c/7dJvsZ56/4586-allow-setup-of-bare-loader-node
For some tests (e.g., Jepsen) we don't need anything to be installed by default on loaders nodes.
=> improvement(sct_config): add bare_loaders option 

defaults/gce_config.yaml
Monitor instance on gce uses slow instance type.
for large/long jobs sometimes it doesn't have
enough performance. Set better instance type
=> fix(gce-config.yaml): increase gce monitor instance type

test-cases/longevity/longevity-nosqlbench-3h.yaml
Set the nemesis class to `NonDisruptiveMonkey`. 
Jenkins job (with 4.6.rc5) passed without issues: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-nosql-jobs/169/
=> fix(nemesis): set nemesis class name to NonDisruptiveMonkey

sdcm/sct_events/base.py
Trello: https://trello.com/c/0ntvupKX/4637-runtimeerror-you-should-create-default-eventsprocessregistry-first
Stop printing traceback of RuntimeError in case of not started
EventsDevice.  It confuses people when there is something wrong
with the latest repo URL.
=> improvement(sct_events): no traceback in publish_or_dump

sdcm/utils/data_validator.py
Since the stress command on long runs, can delete all the
keys in range the `_deletion` view can end empty and that
should be acceptable.
Fixes: #4421
=> fix(DeletedRowsValidator): actual_result can be an empty list

sdcm/nemesis.py
log message have incorrect format in log:
...message=Cluster shrink finished. Current number of nodes %s
fix log messages
=> fix(_shrink_cluster): valid format for log messages

sdcm/logcollector.py, test-cases/longevity/longevity-harry-2h.yaml
logs weren't collected so far, and got lost
=> fix(cassandra-harry): collect cassandra-harry logs

longevity_test.py
56857ba522b9c7de9406d38c296ecc61994a09a2 add a duration, but the
calculation of it was wrong, and multipled twice by 60
=> fix(5000-tables): added duration too big

jenkins-pipelines/hydra-show-monitor.jenkinsfile, sdcm/tester.py
Trello: https://trello.com/c/SYxKDlMH/4211-restore-monitoring-stack-job-should-use-relevant-release-branch
Add sct_branch parameter to hydra-show-monitor job.
Also try to auto-detect SCT branch for email report.
=> improvement(show-monitor): add sct_branch parameter

mgmt_cli_test.py, sdcm/mgmt/cli.py, sdcm/mgmt/operator.py
since manager 1.4 there the whole ssh based connection to nodes
was removed and replace by manage-agents
we don't need this code anymore
Ref: https://trello.com/c/kW8f1Qk3
=> fix(manager): Remove manager ssh-related code

sdcm/logcollector.py
Trello: https://trello.com/c/61PP5n8O/4569-collect-systemd-unit-files-status-at-the-end-of-the-test
Don't think we need to collect it for loader and monitoring nodes.
=> improvement(logcollector): collect systemd status for DB nodes

sdcm/sct_runner.py
Per our conversation with Roy let's use the improved r5 instance type.
https://aws.amazon.com/blogs/aws/new-amazon-ec2-r5b-instances-providing-3x-higher-ebs-performance/
=> improvement(sct-runner): using new instance type for long runs

sdcm/cluster.py
master/enterprise version types were previously ignored by the parsing for scylla_version
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4389
Trello: https://trello.com/c/32Bk1HGx
=> fix(cluster.py): Fix web install parsing for master/enterprise version

sdcm/utils/common.py
Since the builders that use the perf-v8 branch have an older python version (3.6.8)
it does not recognize the self-documenting expression in fstring ( {scylla_version=} ) and the job
fails as a result. This fix should amend that.
=> fix(get_branched_ami): removed removed self-documenting expression in fstring

sdcm/stress_thread.py
since we built on our own the cassandra-stress it's running
with debug enabled by default, for some test cases which use lot of
cassandra stress this is a killer.
this is moving the configuration file into the direcotry the stress
is running from, which case c-s to respect that configuration.
(and only show WARN level and up)
=> fix(cassandra-stress): disable debug output

jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-nodetool-flush-and-reshard.jenkinsfile, jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-nodetool-flush-and-reshard.jenkinsfile, sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/nemesis.py, test-cases/scylla-operator/longevity-scylla-operator-3h-nodetool-flush-and-reshard.yaml
Operator got #894 issue fixed.
In this issue scylla pods were considered down
by operator's liveness probe when Scylla members were running
resharding.
So cover it with nemesis where we populate enough data to make
resharding long more than 2 minutes.
=> feature(nemesis): verify liveness probe doesn't fail during resharding

sdcm/nemesis.py
Port blocking logic of couple of nemesis is not compatible as is
with the K8S approach.
So, skip it while it's support is not implemented for K8S.
=> fix(operator): skip networking nemesis for K8S backends

test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml, test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml
Trello: https://trello.com/c/gUWgHHdb/4560-check-if-scyllarsyslogsetup-interferes-with-syslog-ng-rsyslog
There are two jobs with enabled scylla_rsyslog_setup, but we can't use it with syslog-ng log transport.
=> fix(longevity): use rsyslog log transport for some tests

jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile, jenkins-pipelines/rolling-upgrade-ami.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos7-ldap-authorization.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile, jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian11.jenkinsfile, jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile, jenkins-pipelines/rolling-upgrade-multidc.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile, jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile, vars/rollingUpgradePipeline.groovy
allowing the base_versions to be set in the jobs parameter.
for now, it was only in the .pipeline files, and when need
to re-run jobs that failed from a single base version, we
need to either change code to be able to do it, or to re-run
all of the base_versions.
this improvement will allow to change it from the Jenkins'
job's parameters page.
running it in [here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/upgrade_base_version/job/upgrade-debian10-base-version-parameter/) to test it
=> improvement(rollingUpgradePipeline.groovy): base_versions to Jenkins

docs/configuration_options.md, longevity_large_partition_test.py, sdcm/nemesis.py, sdcm/sct_config.py, test_lib/scylla_bench_tools.py
In order to cover testing of both options of table configuration.
** READY FOR MERGE **
This PR is dependant in merging the reversed-queries PR from task:
https://trello.com/c/TWqm0bE5
https://github.com/scylladb/scylla-cluster-tests/pull/4147
Refs #1413 - The internal layer for managing queries now supports reversed queries natively. This lays the groundwork for reversed reads in memtables, cache, and sstables, so that reversed queries will perform efficiently.
=> improvement(large partitions): Set random clustering order for s-b table

sdcm/nemesis.py
MINOR FIX:
the nemesis description is missing an important
step, that was misleading when quickly reading it
(instead of the code).
=> fix(nemesis.py): disrupt_remove_node_then_add_node description

sdcm/fill_db_data.py
Changed the default CL for the CQL session in paged_query test.
Now data are being inserted into table and both select queries are running with the same CL - QUORUM
This change is supposed to prevent issues like https://github.com/scylladb/scylla/issues/10049
[Trello task](https://trello.com/c/ONhKubC4/4650-reproduce-pagedquery-failure-scylla-issue-10049)
=> fix(fill_db_data.py): change session consistency level in paged_query

test-cases/longevity/longevity-lwt-24h-multidc.yaml
On 4.6 runs we saw cases there no enough CPU for Nemesis creating
new keyspaces and tables
=> fix(longevity-lwt-24h-multidc): enlarge db instances 

test-cases/longevity/longevity-counters-multidc.yaml, test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml, test-cases/longevity/longevity-large-partition-4days.yaml, test-cases/longevity/longevity-twcs-48h.yaml
scylla-bench latest version of 0.1.8 is not stable.
Therefore downgrading it on large-partitions relevant longevities.
Trello: https://trello.com/c/8U4dGEEI
=> fix(scylla-bench large-partitions): Downgrade scylla-bench to a stable version

jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile, vars/rollingUpgradePipeline.groovy
previous commit had a typo in one of the jobs, that created
a list of 2 strings, instead of a single string.
this PR is only a fix for that typo.
=> fix(rollingUpgradePipeline.groovy): base_versions to Jenkins

jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
following this comment https://github.com/scylladb/scylla/issues/10110#issuecomment-1046825309
we are removing the support in this job to start the
upgrade test from 4.3.
=> fix(upgrade centos8): remove support to upgrade from 4.3

sdcm/nemesis.py
Small commit to reduce logs pollution at INFO level by sisyphus nemesis
=> fix(sisyphus-nemesis): reduce logs pollution

sdcm/sct_events/database.py
seem like fac5ac21a6944fb4639777cfe9fef672434dcbbf wasn't enough
of a fix, and log line level have changed a bit since then.
changing the regex of the event to catch both cases
Fixes: #4478
=> fix(WarningEvent): make warning event regex work as expected

sdcm/monitorstack/__init__.py
When a monitoring data older than 15 days in investigated using:
'sct investigate show-monitor' , prometheus will compact the data
away. This will appear to the user as if the data disappeared after
some that prometheus was running. The reason is that the default
retention configuration is 15 days.
Here we add a parameter that will increase the monitoring data retention
time to 100 years which is effectively infinite in our time resolution.
Note: This change also exploits a "bug" in the newer monitoring system where,
flags added using the '-b' option and starts with one '-' sign will be
prefixed with a '-' sign two (making it a '--' option). This is
convenient because on older monitoring version the parameters were
prefixed with '-' unconditionally.
This means that in both versions adding …
=> sct show-monitor: restore stack with effectively infinite retention

sdcm/utils/version_utils.py, unit_tests/test_base_version.py, unit_tests/test_version_utils.py, utils/get_supported_scylla_base_versions.py
Version 5.0/4.6 aren't released yet, hence we don't want to set them
as a base version for rolling upgrades. we do this by getting all the versions
from a repo, and filtering out the release canidate to see if we are
left with anything.
=> fix(UpgradeBaseVersion): filter repos which has only RCs

sdcm/utils/ssh_agent.py
Running sct.py list/clean-resources from commandline (not inside hydra),
yielded the following error, only for a warning print.
```
File "/home/fruch/Projects/scylla-cluster-tests/sdcm/utils/common.py"
SSHAgent.start(verbose=verbose)
File "/home/fruch/Projects/scylla-cluster-tests/sdcm/utils/ssh_agent.py"
os.environ["SSH_AUTH_SOCK"], os.environ["SSH_AGENT_PID"])
File "/home/fruch/.pyenv/versions/3.10.0/lib/python3.10/os.py"
raise KeyError(key) from None
KeyError: 'SSH_AGENT_PID'
```
=> fix(sct.py): list-resources for docker failed for no `SSH_AGENT_PID`

artifacts_test.py
As described in https://github.com/scylladb/scylla/issues/8339, if the systemd-timesyncd
service is already installed in the machine, Scylla should not install a different time
synchronization service (ntpd or chronyd) as well. The subtest I added in the artifact
test will make sure of that.
=> test(artifact): scylla doesn't use ntp/chrony with systemd-timesyncd

sdcm/sct_events/file_logger.py, unit_tests/test_sct_events_file_logger.py
Trello: https://trello.com/c/Xl7JvNlP/4670-too-many-critical-events
In usual case it should be no more than 1 event with CRITICAL severity, but in case such events raise during teardown they push out the initial one from the report. Limiting them to the first 100 instead of last 100 like for other severities will solve this problem.
=> fix(file_logger): limit CRITICAL events to first N instead of last

defaults/severities.yaml, sdcm/sct_events/database.py
this PR is a back port of fac5ac21a6944fb4639777cfe9fef672434dcbbf and eb6e05ae007a97045e4d8abda948bb97aafdfd0f
=> Warning events backport

test-cases/upgrades/rolling-upgrade.yaml, unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.yaml, upgrade_test.py
seen that the performance was affected since it was
added to the upgrade tests (reported on issue
https://github.com/scylladb/scylla/issues/9744), there was
a decision to remove the CDC Stressor from this test,
as we seen that, tests started timing out when running it
and it can take several hours in addition to the current
test run.
=> fix(upgrade test): remove cdc stressor from test

test-cases/upgrades/rolling-upgrade.yaml, upgrade_test.py
back port of 2 PRs:
294c856e8406c6402062dd895e4408094d748561 and 8268fabbe94b9d566a1c081bec387fb7e932217d
=> Backport upgrade cdc stressor branch 4.5

sdcm/cluster.py
'lsof /var/lib/dpkg/lock' command return code is 1 when no process is
reffering to tested file (in our case no apt is running). Current logic is
inverted. That's why we can see in most of our runs log message:
'Wait for: Checking if package manager is free: timeout - 60 seconds -
expired'
Fix ensures rc==1 - it happens when apt lock is free
=> fix(cluster.py): fix is_apt_lock_free method

artifacts_test.py
=> fix(artifact timesync check): skip the test for docker runs

functional_tests/scylla_operator/libs/helpers.py, functional_tests/scylla_operator/test_functional.py, sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/utils/k8s.py
Cover more than 1 supported Scylla manager versions in the operator functional tests.
It will allow to uncover possible compatibility bugs if it appears.
=> test(operator): run multiple mgmt versions in backup and repair tests

sdcm/logcollector.py, sdcm/tester.py
Collect and upload siren manager logs  for AWS cluster
Related Siren PR:
https://github.com/scylladb/siren-tests/pull/941
AWS passed test:
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/siren-tests/job/scylla-cloud-longevity-small-data-set-1h/208/
=> fix(cloud_longevity): collect cloud manager logs for AWS cluster

unit_tests/test_base_version.py, utils/get_supported_scylla_base_versions.py
we noticed a case the two last base versions (i.e. 4.6, 5.0) don't
have a release yet, the logic for handling master/enterprise branches
was to pick only one base version, and the check was only the last
one, so it filter 5.0 but didn't check if 4.6 is suitable and return
it stright. leading to upgrade base being 4.6.rc5
=> fix(filter_rc_only_version): last 2 base version don't have release

defaults/test_default.yaml, docs/configuration_options.md, docs/node_benchmarks.md, jepsen_test.py, sdcm/cluster.py, sdcm/sct_config.py, sdcm/utils/benchmarks.py, sdcm/utils/git.py
This PR adds the ability to perform node benchmarks on our Ubuntu db nodes. The 2 benchmarks added are `sysbench` for cpu tests and `cassandra-fio` for storage benchmarking. More info can be found in the readme doc added by this PR.
Trello tasl: https://trello.com/c/BmhZ5DN2
Example longevity job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-byo-new-test/115
Elasticsearch index for collected benchmark stats: `node_benchmarks`
=> Scylla node benchmarks

vars/getJobTimeouts.groovy
Some of recent jobs failed to collect logs in 70min, and succeeded stages took amount of time pretty close to the limit.  Add  another 20min to try to avoid such aborts.
Example of jobs: 
* https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/
* https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/
=> fix(getJobTimeouts): +20min to collect logs timeout

longevity_test.py, test-cases/longevity/longevity-5000-tables.yaml
This case is using a very old versions of cassandra stress (loaders),
trying the newest versions
=> fix(5000_tables): use lastest AWS loaders AMIs

sdcm/rsyslog_daemon.py
docker port return
```
0.0.0.0:49159
:::49159
```
after code stripped and splitted by ':',
listen_port become: 49159\n
in this case the rsyslog.conf has wrong config line:
```
$IncludeConfig /etc/rsyslog.d/*.conf
action(type="omfwd" Target="172.30.0.119" Port="49159
" Protocol="tcp")
```
add additional strip()
=> fix(rsyslog_daemon): strip rsyslog listen_port

sdcm/logcollector.py
When cloud longevity test runs on GCE we do not need manager id for getting
manager instance. Remove redundant code
Test passed: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/siren-tests/job/yulia-scylla-cloud-longevity-small-data-set-1h-gcp/55/
=> fix(logcollector): not need cloud manager id for log collection on GCE

sdcm/nemesis.py
Have to always choose a DESC order to get high clustering-key value
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4320
Trello: https://trello.com/c/I3UcJeNO
=> fix(disrupt_delete_by_rows_range): Fix choose_partitions_for_delete

sdcm/argus_test_run.py, sdcm/tester.py
This commit changes the way argus will track SCT runs. Previously, it
would use a list of whitelisted SCM branches and organize it this way:
branch, module name, test name (from JOB_NAME url). Now, it will refuse
to run locally (any time get_job_name returns "local_run"), but for any
build system run it will submit the runs into the database - by first
parsing the JOB_NAME environment provided by Jenkins into three
components. This function will also handle certain corner cases (like
releng-testing folder for example), and arbitrary nesting.
[Trello](https://trello.com/c/aDyI6n3Y/4257-add-group-and-test-name-to-all-test-yamls)
=> improvement(sdcm.argus_test_run): Parse JOB_NAME instead of branch names

mgmt_cli_test.py
=> fix(manager sanity): removed unnecessary suspend command

jenkins-pipelines/repair-based-operation/longevity-100gb-4h-Decommission.jenkinsfile, jenkins-pipelines/repair-based-operation/longevity-100gb-4h-RemoveNode.jenkinsfile, jenkins-pipelines/repair-based-operation/longevity-100gb-4h-ReplaceNode.jenkinsfile, jenkins-pipelines/repair-based-operation/longevity-1tb-12h-GrowShrink.jenkinsfile, jenkins-pipelines/repair-based-operation/longevity-200gb-48h-Decommission.jenkinsfile, jenkins-pipelines/repair-based-operation/longevity-50gb-12h-RemoveNode.jenkinsfile, jenkins-pipelines/repair-based-operation/longevity-50gb-12h-ReplaceNode.jenkinsfile, jenkins-pipelines/repair-based-operation/longevity-cdc-4h-Decommission.jenkinsfile, jenkins-pipelines/repair-based-operation/longevity-cdc-4h-RemoveNode.jenkinsfile, jenkins-pipelines/repair-based-operation/longevity-cdc-4h-ReplaceNode.jenkinsfile, test-cases/features/repair-based-operations/longevity-100gb-4h-Decommission.yaml, test-cases/features/repair-based-operations/longevity-100gb-4h-RemoveNode.yaml, test-cases/features/repair-based-operations/longevity-100gb-4h-ReplaceNode.yaml, test-cases/features/repair-based-operations/longevity-1TB-12h-GrowShrink.yaml, test-cases/features/repair-based-operations/longevity-200GB-48h-Decommission.yaml, test-cases/features/repair-based-operations/longevity-50GB-12h-RemoveNode.yaml, test-cases/features/repair-based-operations/longevity-50GB-12h-ReplaceNode.yaml, test-cases/features/repair-based-operations/longevity-cdc-100gb-4h-Decommission.yaml, test-cases/features/repair-based-operations/longevity-cdc-100gb-4h-RemoveNode.yaml, test-cases/features/repair-based-operations/longevity-cdc-100gb-4h-ReplaceNode.yaml
Adding several longevities to test RBNO feature.
Four types of nemesis are being used to test it:
1. Remove Node and bootstrap new node instead.
2. Replace a dead node.
3. Decommission and add new node.
4. Grow cluster by adding nodes then shrink it back with decommission
=> test(rbno): Add longevities for repair based node operations

artifacts_test.py, defaults/severities.yaml, sdcm/cluster.py, sdcm/cluster_docker.py, sdcm/sct_events/database.py
This commit introduce two changes:
1. Add HousekeepingServiceEvent
2. Check that housekeeping service is running and validate its status
Task: https://trello.com/c/EkPg2rht/4381-gether-scylla-houskeeping-log-and-check-for-errors-of-the-houskeeping-service
Tested with:
- ubuntu 20.04
- oel81
- docker
- amazon2
- gce-image
- debian10
- oel76
- ubuntu2004-arm
=> test(artifact): validate housekeeping service

unit_tests/test_base_version.py, utils/get_supported_scylla_base_versions.py
stop filtering rc only base version when running on master
or enterprise branches
=> fix(filter_rc_only_version): don't filter on master branch

utils/lint_test_cases.sh
the linting expect every signal yaml in test-cases folder
to be complate, the new configuration inside `repair-based-operations`
folder breaks that, for now we'll ignore them insted of moving them
into configuration folder
=> fix(test-case-lint): ignore the RBO partial test yamls

jepsen_test.py, sdcm/utils/git.py
Jepsen test failed due a change presented in the commit
https://github.com/scylladb/scylla-cluster-tests/commit/8a7c665f041b0f4315ee313a4d4fc8ed07e3faa3
Tests failed to start because jepsen-scylla repo folder was cloned with root.
This fix allow to clone repository with non-root user
=> fix(jepsen test): change owner of jepsen-scylla folder

sdcm/results_analyze/__init__.py
alternator perf jobs was failing to generate the report with the
following error
```
elasticsearch.exceptions.RequestError: RequestError(400,
'search_phase_execution_exception', 'failed to create query: field
expansion for [*] matches too many fields, limit: 1024, got: 2748')
```
removing the multiple matches to the `job_name` using `use_wide_query`
flag fixed the issue.
=> fix(check_regression_with_subtest_baseline): use use_wide_query=True

sdcm/cluster.py
Commit
https://github.com/scylladb/scylla-cluster-tests/commit/8a7c665f041b0f4315ee313a4d4fc8ed07e3faa3
changed clone cassandra-harry repo from non-root to root user. Fix it
=> fix(cassandra-harry): clone repo as non-root user

sdcm/cluster.py, sdcm/nemesis.py
get_user_keyspaces method got duplicated.
Replaced implementation of this method to easier one.
It also shall remove issue when user calls keyspace as
'test_system' which would be not returned by old implementation.
https://trello.com/c/CS9YUrSM
=> refactor(get-user-keyspaces): remove duplication

jenkins-pipelines/perf-regression-alternator-latency-30min.jenkinsfile, jenkins-pipelines/perf-regression-alternator-throughput-30min.jenkinsfile, test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml, test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
Also moving to c5.2xlarge instance types for loaders
=> fix(alternator-pref): move to us-east-1

jenkins-pipelines/artifacts-azure-image.jenkinsfile
Artifact tests don't use sct-runner. Because jenkins builder belongs to
different virtual network, ssh connection over internal ip is not
possible - that's why it required to use public ip for ssh.
There's some instability in tests - sometimes test hangs after
restarting scylla-server. Logs don't show any reason of that and timeout
stops forcefully the test. When that happens there's no way to get
reasoning what is causing this. Increasing timeout of run might help -
maybe we'll see python traceback that possibly will lead us to the
cause.
=> fix(azure-image-test): use public ssh connection

sdcm/nemesis.py
Added wait_jmx_up() before running the nodetool command.
Sometimes JMX server starts up with some delay after Scylla server
and nodetool command is executed when JMX server is not actually
ready.
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/4539
=> fix(break_streaming_task_and_rebuild): wait for JMX server to be up

test-cases/longevity/longevity-alternator-200GB-48h.yaml
Since the default of YCSB is to take the test_duration as the
`maxexecutiontime` command line paramameter, it was running
longer then the test duration (since the prepare command takes
7h in this test case)
=> fix(alternator-200GB-48h): add time limit to the main stress cmds

sdcm/nemesis.py
Since we can't actully stop the thread while it's working, the timeout
was only used to error once the thread finished, regardless 120s
wasn't enough for the repair on long longevity.
if ever this would be getting stuck, we'll need to
timeout the command inside the thread and maybe use coredump_on_timeout
param.
Fixes: #4540
=> fix(disrupt_no_corrupt_repair): remove timeout from thread result

sdcm/cluster.py, sdcm/sct_events/database.py, unit_tests/test_decode_backtrace.py
* since lines are are now `.strip()` the regex for backtraces expected `\n`
* `copy_scylla_debug_info` was expecting a node object, but since the
dbreader is moved to be a process, it's sending only the node name
failure was like the following:
```
Node perf-ycsb-latency-nemesis-ycsb-per-monitor-node-1bbc1102-1
[100.26.248.120 | 10.0.0.70] (seed: False):
failed to decode backtrace 'str' object has no attribute 'parent_cluster'
```
=> fix(backtrace_decoding): decoding wasn't done

sdcm/logcollector.py, sdcm/monitorstack/__init__.py
- Fail if only all expected dashboards are not loaded
- Add traceback for failed snapshot message
=> fix(sdcm.monitorstack): tolerate absence of some dashboard

vars/managerPipeline.groovy
The manager_version was hardcoded as master_latest. Now the pipeline
will fetch the value from the jenkinsfile.
=> fix(managerPipeline): fetched the value of manager_version

sdcm/monitorstack/__init__.py
when monitoring doesn't have dashboards for the scylla version we
are using, revert to use the master dashboard
=> fix(monitoring_download): revert to master dashboard if not available

unit_tests/test_base_version.py
in test `test_enterprise` we expected to find 2021.1,
but now we are getting 2022.1 (probably 1st RC was promoted).
=> fix(test_base_version.py): bump enterprise version

sdcm/report_templates/results_latency_during_ops.html, sdcm/report_templates/results_latency_during_ops_short.html, sdcm/report_templates/results_reactor_stall_events_list.html, sdcm/results_analyze/__init__.py
emails lately are not being sent, as they are
oversized for the allowed by the suite.
so about half of the runs are not sending correctly
the emails, because the attachments sizes are above
25MB. with this fix, i'm removing unnecessary
WARNING events, and also limiting the amount of
reactor stall events, and also removing the new
kernel callstack events, as their amount is huge.
Fixes #4376
=> fix(perf with nemesis): reduce email size

sct.py
If test_id is missed, does not try to save logs in argus (no logs in this case)
because of collection logs step fails and cause to failure of next steps
=> fix(argus): do not save logs in argus when no test id

sdcm/logcollector.py, sdcm/sct_config.py
If cloud cluster was not created, empty email is sent (or is not sent at all).
Raising exception when cluster id is not found is added by PR
https://github.com/scylladb/siren-tests/pull/982 and it causes to creation of critical error
on SCT step. So user will receive the email with message that cluster was not created.
Task:
https://trello.com/c/kXcQCS5Z/4264-cloud-longevity-if-cluster-wasnt-found-empty-email-is-sent
=> fix(email): send email when cloud cluster is not created

sdcm/sct_provision/aws/user_data.py
=> fix(aws_user_data): make sure logs_transport is being passed

artifacts_test.py
This commit addresses changes
in scylladb/scylla@546e4adf9e1d560cbb99932925b13e30200c0d3a,
adding a sub test to artifacts test that verifies said settings are
applied to the resulting docker image.
[Trello](https://trello.com/c/nCCilfJY/4778-9570-the-locale-is-now-set-to-use-utf-8-encoding-in-the-container-image-so-cqlsh-works-correctly-when-displaying-non-ascii-data)
=> improvement(artifacts_test.py): Verify docker image locale settings

sdcm/cluster_gce.py
When fixing topology changes nemesis for Azure, some unintended change
got leaked to GCE.
Fix is about reverting this change.
https://trello.com/c/5kL3Dipd
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4547
=> fix(gce-reboot): fix hard_reboot method for gce

sdcm/utils/housekeeping.py
Trello: https://trello.com/c/81NEOYcp/4890-artifacts-docker-test-failed-to-query-housekeeping-db-while-running-on-azure-builder
The root cause is a problem with a link, but it requires more investigations.
=> fix(housekeeping): workaround for the issue w/ Azure builder

sdcm/cluster.py
Trello: https://trello.com/c/Vurz5AYd/4870-start-grafana-ip-command-not-found
Full path to `ip` command on CentOS 7 is `/usr/sbin/ip` which is a problem for our code.  Modify PATH variable to include required directory.
=> fix(cluster.py): modify PATH for monitoring start

longevity_test.py
If cluster creation failed (for example, I got it in the siren-test), got error while saving email data:
`Error: 'NoneType' object has no attribute 'get_node_benchmarks_results'`
If cluster was not created, we do not need to collect benchmarks results and nemesis stats
Task:
https://trello.com/c/cgvXHxPs/4910-cloud-error-while-saving-email-data-error-nonetype-object-has-no-attribute-getnodebenchmarksresults
=> fix(email data): do not collect data if cluster was not created

jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-gce-1tb.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile, jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
=> fix(manager jobs): Removed unnecessary timeout param in pipeline files

sdcm/mgmt/cli.py
Previously, the arguments property executed the task progress command directly,
without considering the manager version beforehand. I changed it so it will
use the progress_string command instead, which does consider the manager version
before executing the progress command
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/4527
=> fix(ManagerTask.arguments): switched to using progress_string function

sdcm/utils/benchmarks.py
For now, we get following error:
KeyError: 'cassandra_fio_lcs_64k_read'
getting all the previous data in ElasticSearch.
And the problem with it is that in some cases SCT may fail to find
data for some fields. And it leads to the incomplete set of data.
So, tolerate it instead of failing with 'KeyError' exception.
fixes https://github.com/scylladb/scylla-cluster-tests/issues/4586
=> fix(node_benchmarks): make it tolerate when some data is absent

defaults/severities.yaml, sdcm/sct_events/database.py
compaction of sstables can now be stopped,
and we are raising error events for these messages
(when in fact, they are just a message to the user and cause no harm):
```
Compacting of 2 sstables interrupted due to: sstables::compaction_stopped_exception
(Compaction for keyspace1/standard1 was stopped due to: user-triggered operation)
```
there is a long term fix proposed, but not yet merged.
=> fix(database.py): lower event severity

sct.py
The test_id is not updated in case it wasn't supplied, but if a test_id
was located via other means, this caused argus to never submit logs due
to it using a null value
=> fix(sct.py): Use collector.test_id instead of test_id

vars/rollingUpgradePipeline.groovy
seems like the backport wasn't completely done (or partially
broken).
the main function was being called twice, instead of
using the result of the 1st run of the funtion
`supportedUpgradeFromVersions`.
=> fix(rollingUpgradePipeline): make backported commit work

configurations/raft/enable_raft_experimental.yaml
Added new config file which enable the raft feature in experimental mode.
New jenkins file doesn't need. longevity pipeline supports several config files configuration parameter. 
So only several jenkins job will be copied and run with additional config file to test with raft experimental
=> feature(raft_config): Add config file for raft experimental

sdcm/provision/azure/provisioner.py, sdcm/provision/provisioner.py, unit_tests/provisioner/fake_azure_service.py, unit_tests/provisioner/test_azure_provisioner.py
Currently Azure provisioning tests are disabled because they involved real Azure service.
This commit makes tests to use fake Azure service that operates on files instead of real resources.
=> test(azure): enabled fast azure provision tests

defaults/test_default.yaml
Need to update monitoring version because 3.10 doesn't support 2022.1
=> fix(monitoring): bump monitoring version to 3.11

sdcm/nemesis.py
`cdc_success_msg` variable was redefined during the nemesis: initially it was a list
of patterns, but lately result of `follow_system_log()`` was assigned to it.
=> fix(sdcm.nemesis): redefinition in disrupt_multiple_hard_reboot_node

defaults/aws_config.yaml, docs/new_loader_ami.md
latest loader AMI's don't support ICS in c-s.
New AMI's with c-s from enterprise package was created.
This PR updates AMI's.
Also created basic manual for updating loader AMI's
New AMI's were created according to this manual.
trello: https://trello.com/c/lkxKuWgM
=> fix(loader): fix missing ICS in c-s

test-cases/upgrades/rolling-upgrade.yaml
The randomness of gemini cause the rolling-upgrades to be very flaky
since some workloads are heavier than others and the tests fail due
to timeouts.
This commit sets the gemini_seed to be "66" (a seed we know that
should pass according to previous runs).
=> fix(rolling-upgrade): Set a fixed gemini_seed for rolling-upgrades

sdcm/cluster.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/mini_k8s.py, sdcm/nemesis.py, sdcm/tester.py
Task:
https://trello.com/c/vUpBYtA6/4877-do-not-start-stress-load-thread-if-not-all-nodes-in-the-cluster-are-up
If stress command is starting when one node under disruptive nemesis (DOWN or terminated), stress
command fails and fail the test. To prevent it we will wait when all nodes are UP and then will
start the load
=> fix(stress load): start stress command when all nodes are UP

docker/env/hydra.sh, jenkins-pipelines/hydra-show-monitor.jenkinsfile, sct.py, sdcm/sct_runner.py
The idea is to distinguish SCT runners with restored monitoring from others.
Task:
https://trello.com/c/V8nikgXa/4744-name-sct-runners-that-are-use-to-restore-monitoring
=> fix(runner): name of SCT runners that are use to restore monitoring

commitlint.config.js
we can have scope k8s, gcp, aws that are 3 letters length
=> ci(commitlint): decrease scope min length to 3

sdcm/cluster_docker.py
This fixes an issue with argus where a docker node would fail to
instantiate argus resource because of BaseNode.region not being
implemented
[Trello](https://trello.com/c/4OFrS2q9/4951-init-argus-not-implemented-exception)
=> fix(cluster_docker.py): Implement region property

sdcm/nemesis.py
In order to test multiple overlapping range-tombstones.
Tests the fix of: https://github.com/scylladb/scylla/commit/c3f17ea0a34346223d90e4955f21b1047442a375
Trello: https://trello.com/c/jN5WRPkL
=> test(range tombstones): Add a new nemesis: DeleteOverlappingRowRangesMonkey

test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
Some of the tests keep timing out before reaching the dynamodb phase
=> fix(alternator_perf): extend throughput test test duration

sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/tester.py
To be able to support multi-tenant Scylla setups we should run
K8S Scylla node prepare tools just once per node.
So, make it true here.
=> improvement(kuber): run scylla node prepare just once for a K8S cluster

sdcm/cluster_k8s/__init__.py, sdcm/k8s_configs/eks/scylla-node-prepare.yaml, sdcm/k8s_configs/gke/scylla-node-prepare.yaml, sdcm/k8s_configs/provisioner/templates/provisioner.yaml, sdcm/k8s_configs/provisioner/values.yaml
To support multi-tenant approach of Scylla clusters on K8S we should be
able to create more than 1 PV on local raid disks.
So, add such possibility to both of the supported managed-K8S
platforms (EKS, GKE).
Signed-off-by: Israel Fruchter <fruch@scylladb.com>
Signed-off-by: Valerii Ponomarov <valerii.ponomarov@scylladb.com>
=> improvement(kuber): support creation of multiple K8S PVs on a local disk

performance_regression_test.py, sdcm/cluster.py, test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
During performance test with running nemesis, when nemesis ends
we want to prevent from starting another Nemesis cycle to not spoil
the results.
Also there's no need for running the load anymore.
This fix is about stopping nemesis in perf test after one cycle
and aborting load to finish the test quicker.
https://trello.com/c/SD5IN13F
=> fix(perf-test): stop after one nemesis cycle

sct.py, unit_tests/test_base_version.py, utils/get_supported_scylla_base_versions.py, vars/rollingUpgradePipeline.groovy, vars/supportedUpgradeFromVersions.groovy
A recent failure of the rolling upgrades tests was caused by with the path creation for enterprise releases in scylla-pkg. It was unclear to releng folks looking at the output of the job if the issue is with their code or in SCT. This PR:
- adds logging to the methods used when querying, filtering and listing valid versions for the rolling upgrade
- adds a try / catch in the rollingUpgradePipeline to allow for the pipeline to abort upon failing to retrieve an upgrade versions list
The downside is that we'll see ~10 new log lines in the output per upgrade run, but it should be worth it for the additional troubleshooting context.
Trello task: https://trello.com/c/76FOtld4
Original (closed) issue: https://github.com/scylladb/scylla-cluster-tests/issues/4581 
Example Jenkins run: …
=> Rolling upgrade base version discovery - add logging and faster pipeline exit

sdcm/nemesis.py
Nemsis was failing with:
```
snap: command not found
```
when trying to install stress-ng
we now install snapd before installing stress-ng
Fixes: #4622
=> fix(MemoryStressMonkey): install snap

sdcm/cluster.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py
Provisioning SCT monitoring we add there our custom dashboard.
And this dashboard updates the json file stored in the source code
and then uploads it to a monitoring node.
So, if we want to substitute it with different values for different
monitoring nodes then it is not possible as of now.
So, update this logic by copying source file first and only then update
it and upload.
Also, add DB cluster names to the dashboard name, so we could
distinguish monitorings in case of multi-tenant setup just its by title.
=> improvement(monitoring): support K8S multi-tenant case

sdcm/cluster.py
=> Cleanup code in the sdcm/cluster.py module

sct.py
when running few `hydra` commands, seen failures:
```
File "/home/fabio/git/scylla-cluster-tests/./sct.py", line 1411, in <module>
cli()
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
return __callback(*args, **kwargs)
File …
```
=> fix(sct.py): `list_ami_branch` more resilient

test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
it was misleading, so fixed it to reflect
what the job is really doing (it was wrong
most likely due to historical changes, that
didn't reflect in the prefix naming).
=> fix(longevity-2tb job): `user_prefix` was wrong

jenkins-pipelines/longevity-cdc-8h-multi-dc-large-cluster.jenkinsfile
Jenkins file for jenkins-pipelines/longevity-cdc-8h-multi-dc-large-cluster.jenkinsfile
has wrong yaml file.
=> fix(cdc-8h-multi-dc): set correct config yaml file

sdcm/scan_operation_thread.py, test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml, test-cases/longevity/longevity-large-partition-3h.yaml, test-cases/longevity/longevity-large-partition-4days.yaml, test-cases/longevity/longevity-large-partition-8h.yaml
A followup of: https://trello.com/c/xnqJRs4n - 
In order to compare full-partition-scan data of reversed and normal queries, need to add this enhancement, saving queries output to files and comparing it.
The best practise may be saving each query result page fetch to a file accumulatively, then compare the 2 generated files of reversed and normal queries.
Trello: https://trello.com/c/kZHjbVqC
=> improvement(reversed queries): Added reversed queries data validation

sdcm/provision/scylla_yaml/scylla_yaml.py, unit_tests/test_scylla_yaml.py
=> fix(scylla_yaml): add missed EaR options

sdcm/utils/net.py
Since the actual requests call was outside of a try/except
clause, any connection error would be raised and won't
be moving to try the next service
=> fix(4628): handle connection errors in `get_my_public_ip()`

sdcm/utils/cloud_monitor/resources/instances.py
Gce instance state was returned as enum from libcloud
jinja 2 for some reason wasn't able to cast enum to str
hence we had missing state for gce instances
=> fix(cloud_monitor): cast str for GCE instance state

test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
CI job called 'gemini-3h-ics-cdc-with-nemesis-test' uses
enterprise Scylla for oracle node which doesn't have 'scyllaadm'
user. So, switch this particular configuration to usage of the 'centos'
user.
=> fix(gemini): use proper user for the oracle node

sdcm/nemesis.py
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/4602
Check if rebuild process runs already, do not start nodetool('rebuild')
on the new node during disrupt_rebuild_streaming_err.
Task:
https://trello.com/c/GbLuxgrV/4948-operation-rebuild-is-in-progress-try-again
=> fix(nemesis): not start nodetool rebuild if another rebuild runs

jenkins-pipelines/features-nodetool-stop-compaction-ics.jenkinsfile, stop_compaction_test.py, test-cases/features/stop-compaction-ics.yaml
Testing nodetool stop when using ICS in Scylla Enterprise.
test job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/features-nodetool-stop-compaction-ics-test/
trello: https://trello.com/c/fMrUUoxc
=> test(nodetool-stop): test nodetool stop for ICS

sdcm/provision/common/builders.py
Somehow pylint: disable=duplicate-code didn't work.
Found simple workaround that does the job.
https://trello.com/c/B4kt0L8v
=> fix(pylint): duplicate code in instance_parameters

sdcm/cluster_k8s/mini_k8s.py
Fix bug implemented in https://github.com/scylladb/scylla-cluster-tests/pull/4610 where we call `super()` not having
class instance in var scope. Without this fix following error gets
raised:
File "sdcm/cluster_k8s/mini_k8s.py", line 495, in _wait_for_nodes_up_and_normal
super().check_nodes_up_and_normal(nodes=nodes, verification_node=verification_node)
RuntimeError: super(): no arguments
=> fix(k8s): make kind setup be workable again

sdcm/cluster.py
Since python 3.6 installation is not required if the machine uses ubuntu 20,
I seperated the prerequisites installation script of older versions
(ubuntu 16 and 18) between the newer ones (20 and forwards)
=> fix(monitor install): Fix ubuntu monitor installation prerequisites

sdcm/nemesis.py
Task:
https://trello.com/c/mH3w1kNZ/4504-enable-disruptremovenodethenaddnode-for-cloud-longevities
=> fix(nemesis): skip message for cloud in TerminateAndRemoveNodeMonkey

sdcm/cluster_k8s/__init__.py
After merge of [1] we get following error running any test which calls
'run_stress_thread' method of the 'tester' class instance:
>   File "scylla-cluster-tests/sdcm/cluster_k8s/__init__.py", \
>       line 2130, in wait_for_nodes_up_and_normal
>     self.wait_for_pods_readiness(\
>       pods_to_wait=len(nodes), total_pods=len(self.nodes))
> TypeError: object of type 'NoneType' has no len()
The reason for it is unsafe coding of the K8S' part.
So, make it be safe enough by replacing 'None' with 'empty list' before
calling 'len()' function.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/4610
=> fix(k8s-stress): make 'run_stress_thread' work on K8S

sdcm/ycsb_thread.py
cause of this usage on each line of stats being used, we copy
back and forth the scylla.yaml of the loader, for no good reason
blowing up the logs, and taking lots of cpu from the test runner
(which is shared in perf test anyhow)
=> fix(ycsb): remove usage of cql_ip_address from YcsbStatsPublisher

functional_tests/scylla_operator/test_functional.py
Trello: https://trello.com/c/uwlkJuDf/4985-create-scylla-operator-compatability-job-for-20221-50
=> test(operator): cover only 2 latest manager versions in functional tests

sdcm/cluster.py
Fixes an issue where a suffixed password would be returned even if said
password wasn't changed yet - leading to authentication failures
=> fix(sdcm/cluster.py): Only return suffixed password if it was changed

sdcm/cluster_k8s/mini_k8s.py
One of the recent changes [1] where we stop depending on the host networking in K8S deployments changed the default IP addresses taken as "private".
So, change it for the local K8S case which must use "service IP" for connection as it was before.
Reason for it is that "KinD" tool has docker-wide network connectivity using exactly service IPs.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/4635
=> fix(k8s-local): use proper IP addresses for network connectivity

defaults/k8s_local_kind_config.yaml, test-cases/scylla-operator/functional.yaml
Trello: https://trello.com/c/uwlkJuDf/4985-create-scylla-operator-compatability-job-for-20221-50
Update it to have actual versions of apps and make it use stable operator version by default.
=> improvement(k8s-config): update config for operator functional tests

sdcm/nemesis.py, test_lib/compaction.py
Added a nemesis to modify table tombstone_gc.
In order to test the new gc-mode of 'repair'.
Testing commit: https://github.com/scylladb/scylla/commit/a8ad385ecd3e2b372db3c354492dbe57d9d91760
Trello: https://trello.com/c/Fli77TDn
scylla open issue: https://github.com/scylladb/scylla/issues/10309
The nemesis basically works but currently using a (fishy) workaround for the above issue.
=> test(tombstone gc mode):Added a new nemesis - ToggleGcModeMonkey

sdcm/cluster_k8s/__init__.py
In all K8S runs we get lots of following warning messages:
We don't support IPv6 for k8s-* backends
These make no sense. So, remove such logging to make logs be more cleaner.
=> improvement(k8s): stop spamming logs with non-supported ipv6

functional_tests/scylla_operator/test_functional.py
Do it also for the `test_mgmt_repair` test.
Additional fix: use 2.5.3 instead of 2.5.4 due to the following bug: https://github.com/scylladb/scylla-manager/issues/3147
=> test(k8s): cover only 2 latest mgmt versions in functional tests. Part2

mgmt_cli_test.py, mgmt_upgrade_test.py, test-cases/upgrades/manager-upgrade.yaml
As part of the upgrade test, we create a backup (of the system keyspaces) and
stop it mid-run, with the intention of continuing it in a later stage of the test.
The problem is that backup only the system keyspaces is causing the task to end
way too fast, so we don't have a chance to stop it.
As such, I added the ability in the _generate_load function to create a new, larger
keyspace and changed the task to backup only it so it will last longer.
=> fix(manager upgrade): no longer only backup up system keyspaces

sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/db_log_reader.py, sdcm/nemesis.py, sdcm/scan_operation_thread.py, sdcm/sct_events/base.py, sdcm/sct_events/events_device.py, sdcm/sct_events/file_logger.py, sdcm/test_config.py, sdcm/utils/distro.py, sdcm/utils/docker_utils.py, sdcm/utils/health_checker.py, sdcm/utils/log.py, sdcm/utils/syslogng.py, unit_tests/test_sct_events_base.py
The output to jenkins is becoming incressincly big, it's hard to
track what's an ongoing job is doing, and there an history
of too much output slows down jenkins, and even fills the
jenkins master drive.
lot of those info messages was added for development of new
features, but never remove or reduced to debug level
=> fix(logging): reduce the usage of info level logging

longevity_test.py
Since in those test we are starting c-s multiple time, while nemesis
might be working, we should pass all the nodes to the c-s command
so it won't get into a state the one being conneted is down during
a nemesis
Fixes: #4682
=> fix(batched_tests): make sure we configure c-s with all nodes in cluster

install_argus.sh
installation of argus is failing on old branches,
because changes done in Argus, making the early
stages of the test to fail, so the tests are not
even starting.
=> fix(argus): workaround arguns installation in an old branch

sdcm/mgmt/cli.py
Previously, in the SCTool.run method we expected that either invoke.exceptions.UnexpectedExit
and invoke.exceptions.UnexpectedExit would rise as a result of the sctool command's failure,
but it seems that on certain occasions a sdcm.remote.libssh2_client.exceptions.Failure would
rise instead.
Therefore, I added this exception to the except clause
=> fix(SCTool.run): Excepting sdcm.remote.libssh2_client.exceptions.Failure

sdcm/sct_events/grafana.py, sdcm/tester.py, unit_tests/test_sct_events_grafana.py
For the moment we support only one grafana endpoint for publishing of
annotations. It leads to the situation that in case of multi-tenant
setup with multiple monitorings we post events only to one of them.
So, add support for multiple grafana endpoints.
Known side-effect: all monitorings will store all the info, even
not related to them. It is considered ok for now.
=> improvement(grafana): support K8S multi-tenant case

vars/getJenkinsLabels.groovy
Since `supported_regions` was define inside the context of
an if statment, later when it was needed it wasn't available.
Fixes: #4712
=> fix(random-region): define supported_regions in right context

sdcm/cluster.py, sdcm/sct_events/base.py, unit_tests/test_decode_backtrace.py
Events from the thread processing the queue weren't published
and backtraces weren't reported as events.
* `task_done()` isn't on multiprocessing.Queue, but on `queues.Quere`
we move to use multiprocessing since the thread reading the log
moved into it's own process
* events clone via multiprocessing lost thier `_ready_to_publish`
flag set by `add_info` on a differnt process, so we need to
out it back, so publish can work.
* unittest wasn't changed and was still using `queues.Quere`,
hence not catching this.
=> fix(backtrace_decoding): make sure event are published

test-cases/manager/manager-regression-gce.yaml, test-cases/manager/manager-regression-ipv6.yaml
The number of rows written in most manager test cases was boosted to 4000000, but
some test cases, namely the ipv6 sanity test and the gce backup feature test, were left
out of this change, because they use different config files. This commit amends that for them.
=> fix(manager): enlarged data size in gce feature and ipv6 sanity tests

sdcm/cluster.py, sdcm/nemesis.py
* Don't waste time on filtering empty tables
* make sure the `wait.for` call raises exception
Fixes: #4679
=> fix(_destroy_data_and_restart_scylla): remove slow code from thread

docker/docker_mocked_as_podman, docker/env/hydra.sh, sdcm/monitorstack/__init__.py, sdcm/utils/docker_utils.py, unit_tests/test_hydra_sh.py
this now is working with podman
```bash
HYDRA_TOOL=podman bash -x ./docker/env/hydra.sh list-ami-versions
HYDRA_TOOL=podman ./docker/env/hydra.sh investigate show-monitor c9c0400f-637d-445e-a47f-e047783fcf11
```
=> feature(hydra): Support running with podman

sdcm/cluster.py, test-cases/longevity/longevity-harry-2h.yaml
Now that https://github.com/apache/cassandra-harry/pull/12 is
merged, we can install and run from master branch.
=> fix(cassandra-harry): install from upstream master branch

defaults/k8s_eks_config.yaml, defaults/k8s_gke_config.yaml, defaults/k8s_local_kind_config.yaml, docs/configuration_options.md, sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/cluster_gce.py, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/eks.py, sdcm/cluster_k8s/gke.py, sdcm/logcollector.py, sdcm/sct_config.py, sdcm/tester.py
1. Add new integer option called `k8s_n_loader_pods_per_cluster`.
Make it define the number of loader pods per loader cluster.
It is different than the existing `n_loaders` option which defines
number of nodes dedicated for loader pods.
As an example - for 2 tenants we may create 6 nodes and 2 clusters
with 3 pods in each of them.
2. Add support for the multi-tenancy in EKS and GKE backends.
3. Add 'monitor_id' tag for each monitoring we deploy per Scylla
cluster to distinguish it during provisioning. It is needed because
previously we used 'test_id' for it, which is the same in current case.
4. Run creation of Scylla and Loader clusters in parallel.
=> improvement(tester.py): support multitenancy for K8S

sdcm/mgmt/operator.py
We should not have spaces in the name of backup to avoid following
errors:
$ sctool -c %uuid% progress backup/Default backup task name
Error: accepts 1 arg(s), received 4
=> fix(k8s-mgmt): make backup work using mgmt-3.0

functional_tests/scylla_operator/conftest.py, functional_tests/scylla_operator/pytest.ini, functional_tests/scylla_operator/test_functional.py, sdcm/utils/version_utils.py
There is open bug in Scylla [1] which blocks several actions with
Scylla pods deployed by Scylla-operator. Such actions are 'upgrade'
and 'force-restart'.
So, detect situation that reproduces [1] and skip tests affected by it.
[1] https://github.com/scylladb/scylla/issues/9543
=> fix(k8s): skip some K8S functional tests if scylla is not semver-like

performance_regression_operator_multi_tenant_test.py, sdcm/db_stats.py
Add performance test for testing the K8S multi-tenant setup.
=> test(k8s): add multi-tenant perf test

sct.py
since in #4729 no default values defined.
the following error raise when no `arch` was define in
the commandline:
```
Invalid type for parameter Filters[1].Values[0], value:
None, type: <class 'NoneType'>, valid types: <class 'str'>
```
=> fix(sct.py): default for arch values

sdcm/utils/gce_utils.py
Since zone 'b' frequently fails allocating resources.
Example failure of zone `b`:
2022-05-10 09:15:14.905: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=1f8ebacd-aed1-4a17-a8cf-6af3622c1723, source=ArtifactsTest.SetUp()
exception="The zone 'projects/skilled-adapter-452/zones/us-east1-b' does not have enough resources available to fulfill the request.  '(resource type:compute)'."
=> fix(gce availability zones): Remove zone 'b' from us-east1 list

functional_tests/scylla_operator/test_functional.py
The reason for skip is the following bug:
https://github.com/scylladb/scylla-manager/issues/3156
=> fix(k8s): skip functional tests which use mgmt 2.6.3

sdcm/cluster.py, sdcm/utils/version_utils.py, unit_tests/test_version_utils.py
seems like we must pass an extra param to the
web-installation jobs, when it is enterprise.
Fixes: https://github.com/scylladb/scylla-web-install/issues/32
=> fix(web installation): if `is_enterprise` code is missing param

sdcm/cluster_docker.py, sdcm/utils/distro.py
since build context path was base on `scylla_linux_distro`
which can be: `centos` or `ubuntu-focal`, hence we need to split it.
default `scylla_linux_distro` was changed `ubuntu-focal`
and since then the docker backend was failing like this:
```
TypeError: You must specify a directory to build in path
```
=> fix(cluster_docker): wrong path to build context

functional_tests/scylla_operator/conftest.py, functional_tests/scylla_operator/libs/auxiliary.py, sdcm/report_templates/results_functional.html
skipped test were reported as errors and failed the whole job
* needed to add a global tester object, since when skipping a
test by `pytest.mark.skip` no fixtures are called to collect
this test report, and we need to report stright to the test
object inside the hook, and not as done before inside the a
fixture
=> fix(k8s_functional): add support for reporting skipped tests

sdcm/cluster_k8s/__init__.py
Addition of the multi-tenant support broke the possibility to reuse
existing K8S cluster.
It was broken the way that it tried to create new namespace `scylla-2`
instead of reusing existing `scylla` one as expected.
=> fix(k8s): make "reuse_cluster" work again

docker/scylla-sct/centos/Dockerfile, docker/scylla-sct/ubuntu/Dockerfile
since we are now defaulting to syslog-ng, it's quicker and
less error prune to install it at the Dockerfile we have
for docker backend
=> fix(docker_backend): pre-install syslog-ng

sdcm/nemesis.py
Verification load for add-remove-dc nemesis was intended to be run on
one loader only. With current setup, it was executed on all loaders and
sometimes it happens that 2 loaders start load in almost exact time.
This possibly was causing this nemesis to fail.
Fix makes verification load to happen only on one loader and also
prevents failing whole test due any error with it.
https://trello.com/c/ejIOTBBe
should fix: https://github.com/scylladb/scylla-cluster-tests/issues/4668
=> fix(add-remove-dc): make verification c-s run on one loader

sdcm/tester.py
Recently merged refactor of the LDAP init (https://github.com/scylladb/scylla-cluster-tests/pull/4705) broke the K8S deployment.
Following error gets raised:
AttributeError: 'dict' object has no attribute 'authenticator'
The reason for it is that new context manager called `temp_authenticator` gets run always.
This context manager does 2 restarts of the first node.
At first, it is redundant in most of the cases.
At second, it is not compatible with the K8S deployment.
So, make the new context manager be called only if it is needed.
=> fix(ldap-init): do not run ldap code if ldap is disabled

jenkins-pipelines/features-sla-workload-types.jenkinsfile, sdcm/cluster.py, sdcm/report_templates/results_sl_workloads.html, sdcm/send_email.py, sdcm/stress_thread.py, sdcm/tester.py, sla_per_user_system_test.py, test-cases/features/sl-workloads-test.yaml, test_lib/sla.py
This PR introduces a number of changes that allow testing the new Service Level attributes in SCT, as well as a new test using the Service Level infrastructure. The new test's goal is to allow us to see how "interactive" and "batch" workload types perform when running in parallel. In addition to adding the test itself I've also added a custom e-mail report and ES upload (to allow comparing results across multiple runs, db instance types).
Scylla commit: https://github.com/scylladb/scylla/commit/e8e4456ec73c16ad223b173119829277bb3e2fee
Trello task: https://trello.com/c/gFygxKqG
=> Sla workload type tests

sdcm/provision/scylla_yaml/cluster_builder.py, unit_tests/test_scylla_yaml_builders.py
we are seeing many warning/error messages in
SCT, because it tried in some cases to
run `prepare_and_start_saslauthd_service` when
running on OSS, but it is not supported by it.
Fixes: #4502
=> fix(sasl setup): only prepare sasl when `is_enterprise`

vars/artifactsPipeline.groovy
Seem like in #4730, by mistake the timeout was put on all
of the parallel task, which include log collection phase.
this started failing on master, cause 30min wasn't enough
for the whole sequence (including log/email phases)
=> fix(artifactPipeline): put the timeout on the test stage

sdcm/provision/azure/ip_provider.py, sdcm/provision/azure/network_interface_provider.py, sdcm/provision/azure/provisioner.py, sdcm/provision/azure/virtual_machine_provider.py
Makes provisioning for Azure in parallel by triggering all resources creation,
and then waiting for creation one by one. No threading used.
No API change, nor unit-tests had to be adapted. 
This change saves quite a lot of time, lowers test cost and improves dev experience.
=> feature(azure): make Azure provision in parallel

sct.py, sdcm/cluster_azure.py, sdcm/provision/azure/provisioner.py, sdcm/provision/azure/virtual_machine_provider.py, sdcm/provision/provisioner.py, sdcm/sct_config.py, sdcm/sct_provision/azure/azure_instance_request_definition_builder.py, sdcm/sct_provision/instances_provider.py, sdcm/sct_provision/instances_request_definition_builder.py, sdcm/sct_runner.py, unit_tests/conftest.py, unit_tests/provisioner/fake_azure_service.py, unit_tests/provisioner/test_azure_instance_request_builder.py, unit_tests/provisioner/test_azure_provisioner.py, unit_tests/provisioner/test_provision_sct_resources.py
Currently we had separate logic for provisioning step in jenkins
and for provisioning during sct test execution (e.g. adding new nodes).
This commit reuses logic from provisioning stage so there's no
duplication. It also refactors for better clarity of code.
Most notable changes:
- reuse provision logic during test
- keep ssh credentials info in tags so VmInstance has full ssh info
- prepare for multi-dc scenarios (not tested)
=> feature(azure): reuse provision logic in test

sct.py, sdcm/cluster_azure.py, sdcm/provision/azure/provisioner.py, sdcm/provision/azure/virtual_machine_provider.py, sdcm/provision/helpers/cloud_init.py, sdcm/provision/provisioner.py, sdcm/provision/user_data.py, sdcm/sct_provision/azure/azure_instance_request_definition_builder.py, sdcm/sct_provision/instances_provider.py, sdcm/sct_provision/instances_request_definition_builder.py, sdcm/sct_provision/user_data.py, sdcm/sct_provision/user_data_objects/__init__.py, sdcm/sct_provision/user_data_objects/scylla.py, sdcm/sct_provision/user_data_objects/sshd.py, sdcm/sct_provision/user_data_objects/syslog_ng.py, sdcm/sct_runner.py, unit_tests/conftest.py, unit_tests/lib/fake_remoter.py, unit_tests/provisioner/conftest.py, unit_tests/provisioner/test_azure_instance_request_builder.py, unit_tests/provisioner/test_azure_provisioner.py, unit_tests/provisioner/test_provision_sct_resources.py, unit_tests/provisioner/test_user_data_builder.py
Introduced concept of UserDataObjects that each define packages to install,
script to execute, and possibly changes in scylla user-data json
(acceptable by scylla-machine-image). Provisioners will be building
cloud-init compatible yaml out of these objects and provide it in
user-data (custom_data in Azure) parameter for instances creation.
Current solution will work only for Azure, as Azure uses custom-data for
cloud-init yaml (or script) and user-data for user purpose (which is
used by scylla-machine-image). Azure provider makes use of this behavior.
On AWS/GCE scylla-machine-image will fail on loading cloud-init
compatible yaml. Adding this feature is planned to be added, so users
will be able still using both cloud-init and scylla-machine-image.
Json generation for scylla-machine-image …
=> Azure user data implementation

vars/createSctRunner.groovy
Pretty often running state-changing functional tests SCT runners
get overloaded which may affect stability of testing.
So, increase instance types for AWS and GCE backends.
=> ci(k8s): use more powerful instance types for local K8S SCT runners

sdcm/cluster_k8s/mini_k8s.py, sdcm/k8s_configs/cni-calico.yaml
The main goal of this switch is ability to get random IP addresses for
Scylla pods and services. Whereas the default networking always provides
incremental IPs. Usage of the single IP address for new and
old Scylla nodes makes a problem for Scylla
because it uses IP addresses for differentiating nodes.
=> feature(k8s-local): use Calico networking instead of the default one

sdcm/report_templates/results_functional.html
=> fix(k8s-func): make stacktraces have proper indentation in email reports

sdcm/cluster.py
package is being called with wrong architecture name,
and it is consistently failing Ubuntu20 ARM artifacts
jobs.
with this fix, we will be able to run both ARM and
regular artifacts without any issue.
Fixes: #4769
=> fix(cluster.py): add architecture to package call

sdcm/provision/common/utils.py
Trello: https://trello.com/c/kXD88YtP/4947-db-node-log-lines-are-printed-twice-in-the-sctlog
Found that sometimes syslog-ng setup failed to install the package because of APT locks.  In result, rsyslog used and we can see log message duplicates in SCT log.
Also, add rsyslog forward action conditionally.
Fixes #4606
=> fix(syslog-ng): wait for APT locks in more reliable way

test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml, test-cases/gemini/gemini-basic-3h-ics.yaml
ICS is enterprise-only feature, so we should use enterprise Scylla
for oracle Scylla cluster too.
So, overwrite the default '4.4.7' value with the '2020.1.7' version
which is used in other ICS CI jobs.
=> fix(gemini-ics): use enterprise Scylla for oracle Scylla cluster

docker/env/hydra.sh
Hydra has code to avoid even trying to pull the docker image if it
knows that the desired version is already available locally.
However, this check simply doesn't work -
It turns out that the syntax docker.io/scylladb/hydra works with
"docker pull" but not with "docker images". The syntax scylladb/hydra
works with both, so in this patch we switch to use it.
On my machine, this reduces "hydra" run time by about 2.5 seconds.
Fixes #4783
Signed-off-by: Nadav Har'El <nyh@scylladb.com>
=> hydra.sh: fix check for already-available docker image

defaults/severities.yaml, sdcm/sct_events/database.py, sdcm/sct_events/setup.py, sdcm/utils/remote_logger.py, sdcm/utils/syslogng.py, unit_tests/test_cluster.py, unit_tests/test_data/system.log
Since we keep on hitting on case exception is in the log text
but it's o.k., we should start looking at the log level insted to
identify error happend.
=> fix(database_error): stop using `exception` and use log level

sdcm/cluster.py, unit_tests/test_cluster.py
Current nodetool status regexp didn't work properly for ipv6.
Fix is about correcting this regex to work with ipv6.
fixes https://github.com/scylladb/scylla-cluster-tests/issues/4780
=> fix(cluster.py): fix nodetool status for ipv6

jenkins-pipelines/operator/eks/longevity-scylla-operator-basic-12h-eks-scylla-enterprise.jenkinsfile, jenkins-pipelines/operator/eks/longevity-scylla-operator-basic-12h-eks.jenkinsfile, jenkins-pipelines/operator/gke/longevity-scylla-operator-basic-12h-gke-scylla-enterprise.jenkinsfile, jenkins-pipelines/operator/gke/longevity-scylla-operator-basic-12h-gke.jenkinsfile, test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml
Task:
https://trello.com/c/63gWQAl5/4566-increase-time-of-operator-basic-3h-to-12h
=> improvement(operator): Increase time of operator basic 3h to 12h

test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml, test-cases/gemini/gemini-basic-3h-ics.yaml
Recently was changed [1] Scylla type for oracle nodes in ICS jobs.
And such a switch needed also switch of a username.
So, do it here the same way as it was done for other ICS jobs [2].
[1] https://github.com/scylladb/scylla-cluster-tests/pull/4788
[2] https://github.com/scylladb/scylla-cluster-tests/pull/4658
=> fix(gemini): use proper user for the oracle nodes in ICS jobs

sdcm/cluster_k8s/mini_k8s.py
It is follow-up for this PR: https://github.com/scylladb/scylla-cluster-tests/pull/4762
=> fix(k8s-local): exclude calico pods from not-allowed list

docker/env/build_n_push.sh
Since the path of the input file appear in the output requriements.txt
multiple times, it shouldn't be a full path, since it's generating
lots of diffs every time new image created
=> fix(build_n_push): requirement.in relative when calling pip-compile

vars/artifactsPipeline.groovy, vars/perfRegressionParallelPipeline.groovy, vars/rollingUpgradePipeline.groovy
since we are using that, each one of those jobs are holding
one executer on jenkins master(built-in) worker, that worker
is becoming busy with lot of SCT jobs (and others)
improves #4434
=> fix(parallel-pipelines): stop using `built-in` label

sdcm/logcollector.py, sdcm/provision/common/utils.py
Since after we collect those files, we compress it yet again
into a tar.gz for the whole cluster/set, like db-cluster-**.tar.gz
Closes: #4793, #1820
=> fix(log_collector): stop compressing files remotely

sdcm/results_analyze/__init__.py
somewhere it got mixed up, and we were
trying to slice a dictionary rather than
a list, making the code to fail.
=> fix(perf report): unhashable slice

test-cases/longevity/longevity-harry-2h.yaml
now we proven the the nemesis mostly works,
beside scylladb/scylla#10598 that still under
investigation
This reverts commit 820d561986ea70de573b5bc41793f3a24e1694ad.
=> Revert "fix(cassandra-harry): disable nemesis"

sdcm/nemesis.py, sdcm/utils/common.py, sdcm/wait.py
This PR reworks our streaming_err nemesis methods. The initial inspiration for the changes came about through issue https://github.com/scylladb/scylla/issues/10549 where it turned out we're performing rebuild actions repeatedly on a new node when running `DecommissionStreamingErr` nemesis.
All of the nemesis in question had timing issues, making them a bit flaky. Adding to that, the code for 3 of these nemesis was in one method with a branching logic and multiple log watchers working at the same time. This PR aims to:
- make `DecommissionStreamingErr` work as expected, i.e. interrupt the decommission process on a node **before** it is decommissioned
- decouple the logic for the 3 cases (decommission, rebuild, repair) - this introduces a bit of code repetition, but should improve …
=> refactor(nemesis): refactor decommission, repair, rebuild streaming err nemesis

sdcm/cluster.py, sdcm/fill_db_data.py
because of issue https://github.com/scylladb/scylla/issues/10442
we need to add here this workaround, as the
base versions patches don't include the fix
for this issue.
=> fix(install_scylla): adding workaround to JDK

sdcm/cluster.py, sdcm/fill_db_data.py
the original commit includes the change, but seems it
went back in the backport to this branch.
fixing to have the job working.
=> fix(fill_db_data.py): during backport something went wrong

configurations/arm/centos8.yaml, configurations/arm/debian10.yaml, configurations/arm/ubuntu2004.yaml
Moving the default instance type for arm artifacts tests
from r6gd.large to im4gn.xlarge
=> fix(artifacts): change instance_type_db to im4gn.xlarge

data_dir/cassandra-stress-custom.yaml, data_dir/cs_profile_background_reads_overload.yaml, internal_test_data/complex_test_case_with_version.yaml, internal_test_data/simple_test_case.yaml, sdcm/fill_db_data.py, sdcm/nemesis.py, test-cases/PR-provision-test-docker.yaml, test-cases/PR-provision-test.yaml, test_lib/compaction.py, unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
We still use for some tests DTCS which is deprecated.
Especially it generates many warnings in rolling-upgrade tests,
which obscures other warnings.
Fix is about removing DTCS and replacing it with TWCS wherever possible.
https://trello.com/c/zEPZB5wR
=> fix(DTCS): remove DTCS as is deprecated

longevity_test.py, longevity_twcs_test.py, test-cases/longevity/longevity-twcs-48h.yaml
Method write_prepare_write_cmd execute the post_prepare_cql_cmds
from config yaml. But twcs yaml doesn't use the 'prepare_write_cmd".
And it is a reason, why post_cql_cmd are not applied. This
cql commands are important to change gc and ttl for twcs tests.
these 2 parameters should decrease number of sstables and
should avoid sb read errors.
=> fix(longevity_twcs_test): Apply post_prepare_cql_commands

vars/perfRegressionParallelPipeline.groovy
we seen very often, lately, the function that
calculates the pipeline timeout (called
`get_test_duration`) timing out itself,
making the whole run to fail, as next
stages that require a timeout value will
get `None` and will fail.
=> fix(perfRegression): `get_test_duration` timeout increase

sdcm/provision/azure/virtual_machine_provider.py
When creating sct-runner on Azure there's iterating over None error.
=> fix(azure): fix user-data error when creating runner

sdcm/scylla_bench_thread.py
It's printed with `-start-timestamp=SET_WRITE_TIMESTAMP`:
```
2022-05-31 11:19:56.217: (ScyllaBenchEvent Severity.NORMAL) period_type=begin event_id=aa0029e8-ba64-4f8c-82c4-e3118c8ffd35: node=Node longevity-twcs-3h-2022-1-loader-node-425600b6-1 [13.53.167.151 | 10.0.2.254] (seed: False)
stress_cmd=scylla-bench -workload=timeseries -mode=write -replication-factor=3 -partition-count=400 -clustering-row-count=10000000 -clustering-row-size=200 -concurrency=100 -rows-per-request=100 -start-timestamp=SET_WRITE_TIMESTAMP -connection-count 100 -max-rate 50000 --timeout 120s -duration=170m -error-at-row-limit 1000
```
Change to real write timestamp, as it's running:
```
< t:2022-05-31 11:19:48,695 f:scylla_bench_thread.py l:160  c:sdcm.scylla_bench_thread p:DEBUG > Replaced stress command: …
```
=> fix(event): print scylla-bench event stress_cmd

sdcm/cluster_aws.py
the fallback was only catching `CreateSpotInstancesError` which
is raise by SCT code only after the `request_spot_instances` API
call returned, if any exception was raised during the API call
itself, it was rasing it stright away.
=> fix(spot_failure_fallback): catch all ClientError

test-cases/scale/longevity-many-clients-4h.yaml
Currently we use ChaosMonkey in many-clients test.
This is bad when we want to reproduce the test flow.
Let's change it to SisyphusMonkey with random seed,
so in case we want to reproduce issue we have option for that.
=> test(many-clients test): use sisyphus monkey

sdcm/cluster_azure.py
self.params attribute was used before creation causing an error.
`definition_builder` cannot be instantiated in BaseCluster as not all
backends support it yet.
=> fix(azure): fix missing params attribute in AzureCLuster

sdcm/utils/auto_ssh.py
Hydra runs "autossh" in separate docker instances, and the way it passes
the SSH key to this image is by bind-mounting the outside host's file
$HOME/.ssh/scylla-qa-ec2.
Unfortunately, on hosts which use SELinux, directories cannot be mounted
into docker without "relabeling" the mounted file to be readable from
docker. Without relabeling, autossh complains that it can't find the SSH
key file - even though it does exist. So in this patch we add the "z"
option to the mount, which relabels the file as required.
Signed-off-by: Nadav Har'El <nyh@scylladb.com>
=> fix(autossh): fix bind mount on hosts with selinux

sdcm/utils/syslogng.py
Hydra runs "syslog-ng" in separate docker instances, and the way it passes
the config file to this image and extracts log files from it is by bind-
mounting the outside host's files.
Unfortunately, on hosts which use SELinux, files cannot be mounted
into docker without "relabeling" the mounted file to be usable from
docker. Without relabeling, the syslog-ng silently doesn't do what it's
supposed to do, and hydra mysteriously doesn't work (the autossh dockers
can't connect to it).
So in this patch we add the "z" option to the mount, which relabels the file
as required when selinux is in enforcing mode.
Fixes #4843
Signed-off-by: Nadav Har'El <nyh@scylladb.com>
=> fix(syslog-ng): fix bind mount on hosts with selinux

sdcm/provision/aws/utils.py
since the name of the network device isn't always eth0
the workaround wasn't working in some cases
=> fix(ipv6_workaround_script): find the network device

sdcm/cluster_aws.py, sdcm/provision/aws-cloud-init.txt, sdcm/provision/helpers/cloud_init.py
This PR adds support for running our SCT tests with `cloud-init`-compatible `UserData`. The current implementation makes the usage conditioned on the `use_preinstalled_scylla` param being set to `false` to avoid impacting jobs that use AMIs (interfering with their `UserData`).
=> feature(provision): use cloud-init for ssh config

sdcm/argus_test_run.py
This fixes an issue for azure tests where region_name property can be a list of strings already.
=> fix(sdcm/argus_test_run.py): Only split regions property if it's str

sdcm/logcollector.py
It was not working properly due to overwriting collection instead
of appending.
I removed `k8s` nodes as this tag is not used anyway.
When we get with unified provisioning to k8s, we'll add proper stuff.
=> fix(collect-logs): fix wrong way of nodes collection

sct.py
Since SCT is built on running only one test method, we should
be more clear about and fail early on, if user by mistake selected
more then one test method
now we he does that, this is the error that would be presented:
```
AssertionError: SCT expect only one test case to be selected, found 3:
['test_batch_custom_time', 'test_custom_time', 'test_user_batch_custom_time']
```
Fixes: #4840
=> feature(run-test): make sure we don't select multiple test methods

utils/backport_sct.sh
This is similar to `backport.sh`, but it's using `gh` commandline
to get the commit from a PR, and also to label the PR is cheery-pick
was o.k.
```
./utils/backport_sct.py PR#1234
./utils/backport_sct.py 4838312c
```
depend on `gh` and `jq` to be installed
Ref: https://cli.github.com/manual/installation
Ref: https://stedolan.github.io/jq/
=> feature(backport_sct.sh): helper script for backporting

sdcm/provision/provisioner.py, unit_tests/provisioner/test_provisioner.py
For the moment, if we run any test with local K8S backend then we get
following error on the 'collect logs' stage:
```
File "sdcm/provision/provisioner.py", line 177, in discover_provisioners
return provisioner.discover_regions(test_id, **config)
AttributeError: 'NoneType' object has no attribute 'discover_regions'
```
It happens for any backend that doesn't register provisioner.
So, fix this unsafe coding and add unit test to cover this case.
=> fix(log-collector): raise expected exception for unsupported backend

sdcm/cluster_gce.py
PR complimentary of https://github.com/scylladb/scylla-cluster-tests/pull/4844 The basic idea is: if we run with `use_preinstalled_scylla`, we'll use the usual, legacy-style `UserData`; if not, we can use `cloud-init`-compatible `UserData`.
Sanity jobs:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/artifacts-2004/13/  [ PASSED]
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/artfiacts-centos-8/6/ [PASSED]
Trello task:
https://trello.com/c/ChdoRZBV
=> feature(cloud-init): add cloud-init user-data for gce

sdcm/sct_config.py, unit_tests/test_config.py
Make sure we don't fail when trying to get paramters from
`regions_data` structure,
saying this isn't a supported region:
```
...
raise ValueError(f"{region} isn't supported, use: {list(regions_data.keys())}")
ValueError: us-east-2 isn't supported, use: ['us-east-1', 'us-west-2',
'eu-west-1', 'eu-west-2', 'eu-north-1', 'eu-central-1']
```
fix: #4864
=> fix(sct_config): take care of unsupported aws regions

sdcm/logcollector.py
currently on on k8s we collect this file, this commit
add the collection of `cassandra-rackdc.properties`
Trello: https://trello.com/c/Lh9wUT4j
=> fix(logcollector): collect the cassandra-rackdc.properties file

unit_tests/test_base_version.py, utils/get_supported_scylla_base_versions.py
Quick fix for missing oss base version for rolling-upgrade test for
scylla-enterprise 2022.1
=> fix(rolling-upgrade): add oss base version for 2022.1 test

test-cases/features/ics_space_amplification_goal_test.yaml
It had an underscore that is not valid for a hostname.
=> fix(ics goal test): Fix invalid user prefix characters

sdcm/sct_config.py, unit_tests/test_config.py
seem like the change in #4847 was breaking gce backend
for siren, since the default is `use_preinstalled_scylla: false`
and it didn't fallback into using also `cloud_cluster_id`
Ref: #4847
=> fix(sct_config): make sure siren is handled correctly

sdcm/cluster.py
cql_ip_address is looking into scylla.yaml to get broadcast_rpc_address.
To prevent unessesary downloading and uploading of scylla.yaml every time that we need to get
cql_ip_address, change it to be 'cached_property' instead of 'property'
=> fix(cql_ip_address): change to be @cached_property

sdcm/cluster.py
Resharding may be started during Scylla startup.
Beginning from 4.2 version, startup can't be completed and has to wait until
resharding done. Change 'restart_node_with_resharding' function according to that
=> fix(resharding): recognize resharding during restart

sdcm/cluster.py, sdcm/nemesis.py
1. Do not create cql connection every time that select from table
2. Stop Scylla after checking is the table has data
=> fix(destroy_data_and_restart_scylla): two small fixes

vars/rollingOperatorUpgradePipeline.groovy
since in platorm upgrade test we are not upgrade between two
version of scylla, we should title is a bit more clear to
avoid confusion
Trello: https://trello.com/c/1aypWH9P
=> fix(rollingOperatorUpgradePipeline): better handle platform upgrade

defaults/test_default.yaml
job: scylla-master/longevity/longevity-100gb-4h-test#462,
failed:
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3511, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4210, in node_setup
if self.is_additional_data_volume_used():
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4470, in is_additional_data_volume_used
return self.params.get("data_volume_disk_num") > 0 or self.params.get('gce_pd_standard_disk_size_db') > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'
it happened because gce_pd_standard_disk_size_db is not defined for aws job.
Related to this PR: fix(gce-image-persistent-disk): make sure we run `scylla_io_setup`
=> fix(test_default): Add default value for gce_pd_standard_disk_size_db

functional_tests/scylla_operator/conftest.py, functional_tests/scylla_operator/libs/auxiliary.py
in k8s functional tests, we don't have any event with the result
of the test. in longevity test we almost always have error or
critical event.
it should be helping investigation of k8s-functional in argus
Trello: https://trello.com/c/CIfZmTDL
=> fix(k8s): make sure we have an event for the test outcome

defaults/manager_versions.yaml, defaults/test_default.yaml
New release of scylla-manger released 3.0. Switch sct-master and
scylla-master to use relase 3.0
=> feature(manager-3.0): Switch default to scylla manager-3.0

sdcm/mgmt/cli.py
Since some of the arguments of a manager task can contain colon
we have to limit the split to the first occurrence only
Solves https://github.com/scylladb/siren-tests/issues/1005
=> fix(manager task arguments): Restricted split with maxsplit

jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2204.jenkinsfile
Follow up to https://github.com/scylladb/scylla-pkg/pull/2935 Adding Nonroot Offline Install pipeline for Ubuntu 22.04, which I missed in the previous PR.
=> test(artifacts): add nonroot offline for ubuntu 22

defaults/k8s_eks_config.yaml, defaults/k8s_gke_config.yaml, defaults/k8s_local_kind_config.yaml, sdcm/cluster_k8s/__init__.py
We can define arguments for a scylla binary in K8S
via 'scyllaArgs' option of the 'scyllacluster' custom resource
defined by scylla-operator.
So, make values of the 'append_scylla_args' SCT option be used
as 'scyllaArgs' in K8S if it is defined.
=> improvement(k8s): make 'append_scylla_args' option work in K8S

mgmt_cli_test.py, sdcm/mgmt/cli.py, sdcm/mgmt/common.py
=> test(manager 3.0): Added test for on-resume-start-tasks flag

artifacts_test.py
According to Avi, the scylla offline installation does not include any timesync service
installation with it. As such, the time synchronization service check should only
run on online installations.
=> fix(artifact_test): Skip timesync test on offline installation scenarios

configurations/aws/i4i_2xlarge.yaml, configurations/aws/i4i_4xlarge.yaml, jenkins-pipelines/longevity-50gb-3days-aws-i4i.jenkinsfile, jenkins-pipelines/longevity-large-partition-200k-pks-4days-aws-i4i.jenkinsfile, jenkins-pipelines/longevity-large-partition-8h-aws-i4i.jenkinsfile, jenkins-pipelines/longevity-large-partition-asymmetric-cluster-3h-aws-i4i.jenkinsfile
the new i4i family seems to have twice as performance in the
same price, testing out  some of the performance sensitive use
cases with it.
Testing those out with 5.0.rc8:
similar timeout as the master runs, also the CPU usage seems similar to the i3 based runs, I don't think we need to touch the load.
=> feature(longevity-large-partition): clone cases with i4i.2xlarge

defaults/k8s_local_kind_config.yaml, sdcm/cluster_k8s/__init__.py, sdcm/cluster_k8s/mini_k8s.py, sdcm/k8s_configs/provisioner/values.yaml, sdcm/tester.py
We should use static local volume provisioner to avoid possible
strange failures of operator and scylla interactions when we
remove/replace/decommission a Scylla pod.
Having static local volume provisioner we do not lose data removing
pod, but using dynamic provisioner we do lose data removing a Scylla pod.
=> improvement(k8s-local): use static local volume provisioner

jenkins-pipelines/raft/longevity-100gb-4h-with-raft.jenkinsfile, jenkins-pipelines/raft/longevity-50gb-3days-raft.jenkinsfile, jenkins-pipelines/raft/longevity-cdc-8h-multi-dc-topology-changes-raft.jenkinsfile, jenkins-pipelines/raft/longevity-lwt-parallel-schema-changes-with-disruptive-24h-raft.jenkinsfile
Add new jobs based on regular longevities with enabled raft
=> feature(longevity-with-raft): New regular longevities with raft enabled

sdcm/tester.py
In cloud runs, when setting the encryption mode to 'both', we still use non encrypted communication.
However, the BaseNode.is_client_encrypt function still identifies the cluster as strictly encrypted,
which causes the cassandra stress thread to fail.
As such, I made sure that in those runs the cassandra stress thread will not use encryption.
=> fix(cassandra stress): disabling client encryption for cloud runs

sdcm/cluster_k8s/__init__.py
In K8S multi-tenant setups we use separate Scylla clusters with unique
names. So, fix the variable we use setting the scylla binary args.
=> fix(k8s): make append_scylla_args not break multi-tenant setup

sdcm/nemesis.py, sdcm/sct_events/group_common_events.py
Issue https://github.com/scylladb/scylla/issues/10217
Expected error, we need to ignore it (Roy's request):
http://13.48.103.68/test/e924afae-c3b6-4e75-b4f2-05d5ead176aa/runs?additionalRuns[]=1bb24db5-ff03-42fb-b3c5-595d885b91f2
=> fix(error): ignore view update gate_closed_exception during reboot

vars/longevityPipeline.groovy, vars/runSctTest.groovy
Since in k8s longevity we want to be able to control the
source dockerhub project source to pull the scylla image from
=> fix(longevityPipeline): add support for passing down `docker_image`

sdcm/mgmt/common.py
from previous work, seems like ubuntu 22 was still
missing from this function, and artifacts test was
failing because of it.
=> fix(common.py): add ubuntu 22 to `get_distro_name`

sdcm/cluster_k8s/__init__.py, sdcm/nemesis.py
since in both cases we delete a pod, the next pod
replacing it won't have the same addresses anymore,
and we need to update our node cache of them.
since it's breaking the healthcheck code, and compares
to wrong address
covering all the places inside nemesis that are calling
`node.restart()` or `node.reboot()`
=> fix(k8s): refresh ip addresses on hard/soft reboot

sdcm/nemesis.py
In the disrupt_decommission_streaming_err nemesis the target node is decommissioned and then new
node is join instead of descommissioned one. Then by scenario rebuild should be started on the new
node. But rebuild is started on the decommissioned node then the nodetool fails with:
```
Command: /usr/bin/nodetool -u cassandra -pw 'cassandra'  rebuild
Stdout:
Stderr:
Failed to connect in 60 seconds, last error: (ConnectError)Error connecting to host
'10.0.3.79:22' - No route to host
```
=> fix(decommission_streaming_err): run rebuild on a new node

configurations/operator/1tb-7days-no-tls.yaml, configurations/operator/200GB-no-tls.yaml, configurations/operator/50GB-no-tls.yaml, configurations/operator/cdc-3d-400gb.yaml, configurations/operator/large-collections-12h.yaml, configurations/operator/large-partition-200k-pks-4days.yaml, configurations/operator/lwt-basic-24h.yaml, configurations/operator/twcs-basic-48h.yaml, sdcm/nemesis.py, test-cases/scylla-operator/longevity-scylla-operator-3h.yaml, test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml
Since almost all longvity moved to use SisyphusMonkey, moving
also the k8s ones, so we can get predictible ordering of nemesis.
* removed `KubernetesScyllaOperatorMonkey` since it's just
using the `kubernetes` flag which `SisyphusMonkey` supports.
* add correct `nemesis_include_filter` to all longevity overwide
configurations.
=> feature(k8s_nemesis): move to use SisyphusMonkey for longvity

sdcm/nemesis.py, sdcm/sct_events/group_common_events.py
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4936
Trello task: https://trello.com/c/kvaQ4PTB
=> fix(nemesis): ignore STREAM_MUTATION_FRAGMENTS during decommission

sdcm/cluster_aws.py
since in #4923 we move to use `get_all_ip_addresses`, it was
implemented in a way it's working for all backends beside AWS one
and was causing the following errors:
```
'get_gossip_info': failed with 'NotImplementedError()', retrying [#3]
```
Ref: #4923
=> fix(get_gossip_info): implement `_refresh_instance_state` for AWSNode

sla_per_user_system_test.py
By deviation percent we decide if the test result is as expected or not.
In ideal expected ratio between two users is 5.0.
It was decided to allow 10% deviation (from 4.1 to 5.0 ratio)
Based on reality change it to 32% (from 3.4 to 5.0 ratio)
Accroding to Roy's request:
http://13.48.103.68/test/71402aa7-051b-4803-a6b4-384529680fb7/runs?additionalRuns%5B%5D=1adf34d1-15cf-4973-80ce-9de130be0b09
=> fix(sla deviation): change deviation percent

sdcm/nemesis.py
Currently the code in `_check_pod_stats` assumed that the name of the
image repo ends with `scylla`, it's not always true, since we have
nightly and enterprise repos.
switching to checking the pod name equals `scylla`
Fixes: #4941
=> fix(flush_and_reshard_on_k8s): identify the scylla pod base on it's name

configurations/aws/i3en_2xlarge.yaml, jenkins-pipelines/perf-regression-latency-250gb-with-nemesis-i3en.jenkinsfile, jenkins-pipelines/perf-regression-latency-250gb-with-nemesis.jenkinsfile
we want to start benchmarking runs on i3en.2xlarge
instances, and we aim to do in a separated test.
Adding the needed files in here, so we can create
a new job in Jenkins to call it.
=> test(perf_with_ops): add new test to run on i3en

jenkins-pipelines/artifacts-amazon2-arm.jenkinsfile, jenkins-pipelines/artifacts-centos8-arm.jenkinsfile, jenkins-pipelines/artifacts-debian10-arm.jenkinsfile, jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile, jenkins-pipelines/artifacts-ubuntu2204-arm.jenkinsfile
Since manager 3.0 supports arm installation, we can now enable
manager agent installation in arm artifact tests.
=> fix(arm artifact tests): Enabled manager agent installation

stop_compaction_test.py
Disable stop upgrade compaction test as it's unsupported.
To be reenabled when https://github.com/scylladb/scylla/issues/10676 is
fixed.
=> test(stop-upgrade): disable stop upgrade compaction test

.pre-commit-config.yaml, sdcm/utils/common.py, unit_tests/test_config.py, unit_tests/test_utils_common.py
Some tests started to fail after a cleanup in eu-west-1 region.
Also, releng created some mess with changing tag `build-id` to `build_id`.
Plus, fix problem with commitlint pre-commit check and old glibc.
=> fix(unit-tests): update AMI ids in the tests

sdcm/nemesis.py, sdcm/sct_events/group_common_events.py
Added a fix for the issue https://github.com/scylladb/scylla-cluster-tests/issues/4936 in the nemesis `disrupt_rebuild_streaming_err`.
The follow-up for the PR https://github.com/scylladb/scylla-cluster-tests/pull/4940
=> fix(RebuildStreamingErr): ingore STREAM_MUTATION_FRAGMENTS errors

configurations/operator/1tb-7days-no-tls.yaml, configurations/operator/200GB-no-tls.yaml, configurations/operator/50GB-no-tls.yaml, configurations/operator/cdc-3d-400gb.yaml, configurations/operator/large-collections-12h.yaml, configurations/operator/large-partition-200k-pks-4days.yaml, configurations/operator/lwt-basic-24h.yaml, configurations/operator/twcs-basic-48h.yaml, sdcm/nemesis.py, sdcm/sct_config.py, test-cases/gemini/gemini-1tb-10h.yaml, test-cases/gemini/gemini-3h-with-nemesis.yaml, test-cases/gemini/gemini-8h-large-num-columns.yaml, test-cases/longevity/longevity-100GB-48h-cloud-CloudLimitedChaosMonkey-tls.yaml, test-cases/longevity/longevity-200GB-48h-network-monkey.yaml, test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml, test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml, test-cases/longevity/longevity-cdc-100gb-8h-multi-dc-large-cluster.yaml, test-cases/longevity/longevity-cdc-100gb-8h-multi-dc-topology-changes.yaml, test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml, test-cases/scylla-operator/longevity-scylla-operator-3h.yaml, test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml, unit_tests/test_nemesis.py
Since there are cases we want to exclude nemesis by it's flag
now we can use `nemesis_selector` like this:
```
nemesis_selector: !disabled
```
it would remove any nemesis class tagged like this:
```python
class Monkey(Nemesis):
disabled = True
def disrupt():
self.disrupt_something_100()
```
* Also fixes a bug in the filter, that ignroe nemesis methods
that has numbers in thier name
=> feature(SisyphusMonkey): negative flag for `nemesis_selector`

defaults/severities.yaml, sdcm/sct_events/database.py
following issue on https://github.com/scylladb/scylla-enterprise/issues/2183
we are experiencing multiple jobs failing, so for now,
and until this issue will be fixed, we are reducing the
event from ERROR to WARNING, so we will save
in investigation times for this silly error.
=> fix(database event): reduce severity ScyllaHelpErrorEvent

sdcm/sct_events/group_common_events.py
The follow-up for https://github.com/scylladb/scylla-cluster-tests/pull/4955
It turned out we must use the name of the event class instead of the event class itself to make `EventsSeverityChangerFilter` work properly.
`LogEvent` does not define the real events, and we never have the event with the name `LogEvent` in practice.
Hence we cannot use it while calling `EventsSeverityChangerFilter`.
This commit changed values passing to `event_class` to more appropriate ones.
=> fix(group_common_events): don't use LogEvent in SeverityChangerFilter

sdcm/cluster.py, sdcm/nemesis.py
In some cases nodetool command retried after node reboot during *StreamingErr nemeses.  Try to avoid such cases by disabling retrying.
Addressing https://github.com/scylladb/scylla-cluster-tests/issues/4954
=> fix(nemesis): avoid retrying after interrupt

sdcm/sct_events/group_common_events.py
SCT started having following pylint error:
sdcm/sct_events/group_common_events.py:19:0: \
W0611: Unused LogEvent imported from sdcm.sct_events.base (unused-import)
It was caused by the merge of 2 parallel PRs [1][2] which removed usage
of the 'LogEvent' object. So, each of them separately had no pylint
error, but both merged caused it.
So, just remove redundant import to make the pylint work.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/4955
[2] https://github.com/scylladb/scylla-cluster-tests/pull/4956
=> fix(group_common_events.py): delete unused import making pylint be happy

sdcm/nemesis.py
Increase the timeout in the `disrupt_decommission_streaming_err` nemesis
from 10 to 20 minutes because it happens that repair takes more than 10
minutes (current timeout).
=> fix(nemesis): increase timeout in 'disrupt_decommission_streaming_err'

sdcm/nemesis.py
Increase the timeout in the `disrupt_repair_streaming_err` nemesis
from 10 to 20 minutes because it happens that repair takes more than 10
minutes (current timeout).
=> fix(nemesis): increase timeout in the 'disrupt_repair_streaming_err'

defaults/aws_config.yaml
Trello: https://trello.com/c/t4c3uWxg/5226-copy-loader-images-from-us-east-1-to-required-regions-and-update-sct-branches-with-new-ami-ids
these loaders were removed by mistake
making all the runs using them (specifically
`branch-perf-v8`) to fail, as loader
images couldn't be found.
=> fix(aws_config): re-created loader v9

defaults/aws_config.yaml
Trello: https://trello.com/c/t4c3uWxg/5226-copy-loader-images-from-us-east-1-to-required-regions-and-update-sct-branches-with-new-ami-ids
these loaders were removed by mistake
making all the runs using them (specifically
`branch-perf-v12`) to fail, as loader
images couldn't be found.
=> fix(aws_config): re-created loader v16

sdcm/scylla_bench_thread.py
Since in some cases when the stress command start, one of the
nodes might be down, and we need to make sure the stress command
can connect to any of the available nodes and start the stress.
Fixes: #4386
=> fix(scylla_bench_thread): add all available node to command

defaults/test_default.yaml, sdcm/nemesis.py, sdcm/sct_config.py, unit_tests/test_nemesis.py
This new parameter allows filtering out all 'disabled' Nemeses by default.
The default value could be overridden as 'false' in a specific test so that
'risky' disabled Nemeses will be used carefully only there.
This is a complementary PR, following https://github.com/scylladb/scylla-cluster-tests/pull/4902 .
It should be used, for example, in the new nemesis settings of https://github.com/scylladb/scylla-cluster-tests/pull/4755
=> feature(SisyphusMonkey): Introduce nemesis_exclude_disabled

sdcm/cluster_gce.py
When running tests with GCE there's flood of warning messages like:
`On GCE, VPC networks only support IPv4 unicast traffic...`.
It is enough to have only one warning about it.
=> fix(gce): fix warning flood in GCE tests about ipv6

longevity_test.py
recently we started getting empty emails, and the logs
were not enough to figure out why the email data collection
was breaking
```
Error in gathering common email data: Error:
list index out of range
```
=> fix(get_email_data): add trackbacks to log in case of failure

sdcm/nemesis.py
since recently `k8s_n_scylla_pods_per_cluster` was introduced,
the nemesis was reading `n_db_nodes` to assume the inital number of
nodes, for k8s the number is now set in `k8s_n_scylla_pods_per_cluster`
it was failing like this, and the next time there a nemesis that
need to add a node, there's no room for it on the k8s cluster.
```
2022-07-10 00:24:02.644: (DisruptionEvent Severity.ERROR) period_type=end
event_id=4010e8f4-4cd2-4a4a-ba99-b6f0aad39e28 duration=13m32s:
nemesis_name=GrowShrinkCluster target_node=Node sct-cluster-us-east1-b-us-east1-2
[10.0.1.52 | 10.0.1.195] (seed: False) errors=Not enough nodes for decommission
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3599, in wrapper
result = method(*args, **kwargs)
File …
```
=> fix(GrowShrinkClusterNemesis): use `k8s_n_scylla_pods_per_cluster`

sct.py, sdcm/test_config.py
to avoid `hydra clean-resources` from cleaning a user instances
which aren't created by hydra/sct commands.
it's still preferable to clean the resources by test_id
but we still want this safe guard in place
=> feature(tags): add `CreatedBy: SCT` tag

sdcm/nemesis.py
we need to filter SI/MV since we can't take
snapshots of those kind of tables:
```
nodetool: Scylla API server HTTP POST to URL '/storage_service/snapshots' failed:
std::invalid_argument (Do not take a snapshot of a materialized view or a
secondary index by itself. Run snapshot on the base table instead.)
```
since this nemesis is randomlly select which snapshot
to take (and not all of our cases has SI/MV), we rarly seen this
happening
Fixes: #4775
=> fix(SnapshotOperations): filter out SI/MV tables

performance_regression_test.py, sdcm/cluster.py, sdcm/nemesis.py
In some cases we want to run certain number of nemesis cycles.
This is the case in e.g. perf test where we run just once.
This commit parametrize number of nemesis cycles to be executed during
the test.
task: https://trello.com/c/Xp2q7SfX
=> feature(nemesis): parametrize nemesis cycles count

sdcm/cluster_k8s/mini_k8s.py
e3a6cc5d78761823a25a790722a6badfbadbbeb5 seperated the logic
of number of pods into `k8s_n_scylla_pods_per_cluster`
while `n_db_nodes` is the number of k8s node
`start_k8s_software()` was still appending one extra node
ontop of `n_db_nodes`, which casuse 5 node to be created,
while the code was waiting for 4.
```
> Wait for 4 node(s) in pool scylla-pool to be ready... [try #12]
> Running command "kubectl --cache-dir=...
wait --timeout=10m -l minimal-k8s-nodepool=scylla-pool
--for=condition=Ready node"...
> node/kind-worker condition met
> node/kind-worker2 condition met
> node/kind-worker3 condition met
> node/kind-worker5 condition met
> node/kind-worker7 condition met
> Command "kubectl --cache-dir=...
wait --timeout=10m -l minimal-k8s-nodepool=scylla-pool
--for=condition=Ready node" …
```
=> fix(mini_k8s): `start_k8s_software()` was creating extra db node

performance_regression_operator_multi_tenant_test.py, sdcm/tester.py
By default, ParallelObject allows to run n+4 parallel threads
where 'n' is number of CPU cores.
In common case we have 2 cores on SCT runners.
So, using default values we are limited by 6 parallel threads
using 'ParallelObject' class.
And in case of measuring the K8S multitenant performance we
must run all the measures in parallel.
So, make all the multitenant threads run all at once specifying
the number of parallel workers explicitely.
=> fix(k8s-multitenant): run 7+ DB cluster really in parallel

sdcm/cluster_k8s/__init__.py
It happens that pod which is going to be used for running
`fstrim` command may be temporary unavailable and fail a `kubectl` call.
So, decrease the probability of the false failure by making it run with the retry mechanism.
=> improvement(k8s): run fstrim command with retry

performance_regression_operator_multi_tenant_test.py
For now we have following values:
4fbe38d0-e78c-4105-be68-5e70c56574a6-k8s-perf-7-tenants_write-prepare
4fbe38d0-e78c-4105-be68-5e70c56574a6-k8s-perf-7-tenants_read
4fbe38d0-e78c-4105-be68-5e70c56574a6-k8s-perf-7-tenants_write
4fbe38d0-e78c-4105-be68-5e70c56574a6-k8s-perf-7-tenants_mixed
Stored in ES as the test names in case of K8S multitenant setups.
But we need to have it be non-unique.
So, remove the UUID part from it.
=> fix(k8s-multitenant): use non-unique values for storing test names

sdcm/cluster_gce.py
In case of error during getting logs from gce logging api, next logs
fetch is done immediately. In case of too many queries/min error, this
will fail even more.
This commit fixes this behavior by not making immediate logs fetch
again. Also if there was a failure, make next query to ask for logs from
failed period too.
=> fix(gce-spot-termination): prolong wait time on logs fetch error

sdcm/sct_provision/user_data_objects/scylla.py, unit_tests/provisioner/test_scylla_machine_image_payload.py
Currently for unified provisioner SMI payload was hardcoded.
This commit parametrizes it according to SCT configuration.
https://trello.com/c/k4C1quCP
=> fix(SMI): parametrize smi payload for unified provisioning

sdcm/nemesis.py
`disrupt_terminate_and_replace_node` was getting `Connection refused`
which is to be excpected since the dynamodb client isn't node aware
and we don't have loadblancers
=> fix(nemesis): ignore ycsb `Connection refused` on terminating a node

upgrade_test.py
Autobackup config files are not recovered on RHEL system. This causes
error when upgrading from OSS to Enterprise.
Fix is correcting files recover command.
fixes https://github.com/scylladb/scylla-cluster-tests/issues/4987
=> fix(upgrade-test): fix recover backup config files

sdcm/db_log_reader.py, unit_tests/test_cluster.py
log reader thread read a file every 30sec, so in case it finished
reading exactly at the end of a line, it would have started reading
from the 2nd char in the line.
Fixes: #5016
=> fix(log_reader): off by one error when saving offset in log file

sdcm/nemesis.py
a2d988688a1be6b69f953e1a66572a2f6736347a assumed `get()` has default
argument, and failed like this:
```
initial_db_size = self.tester.params.get("k8s_n_scylla_pods_per_cluster", initial_db_size)
TypeError: SCTConfiguration.get() takes 2 positional arguments but 3 were given
```
=> fix(GrowShrinkClusterNemesis): don't assume `params.get()` has default

sdcm/cluster.py
Since python 2.7 doesn't support fstrings
=> fix(cluster.py): replaced fstring with format

vars/createTestJobPipeline.groovy
Today when QA adding new jobs to master it is not automatically updated under `scylla-master/releng-testing` and `enterprise` , this is causing failures in the daily process and releng debug sessions which we can avoid.
Setting this job to run once a week and update the SCT jobs
=> Trigger job updates createTestJobPipeline:add automatic update for releng-testing and enterprise

sdcm/cluster.py
This command fails frequently and is
not a must to use.
Fixes: #4977
=> fix(cluster.py): Remove command of yum makecache

defaults/test_default.yaml, sdcm/cluster.py, sdcm/sct_config.py, test-cases/performance/perf-regression-2mv.yaml, test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml, test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml, test-cases/performance/perf-regression-latency-125gb.yaml, test-cases/performance/perf-regression-latency-1TB.yaml, test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml, test-cases/performance/perf-regression-latency-500gb-30min.yaml, test-cases/performance/perf-regression-latency-cdc-mixed-poll-batching.yaml, test-cases/performance/perf-regression-latency-in-memory.yaml, test-cases/performance/perf-regression-latency-lwt-big.yaml, test-cases/performance/perf-regression-latency-lwt-small.yaml, test-cases/performance/perf-regression-throughput-125gb.yaml, test-cases/performance/perf-regression-throughput-cdc-mixed-poll-batching.yaml, test-cases/performance/perf-regression-throughput-lwt-big.yaml, test-cases/performance/perf-regression-throughput-lwt-small.yaml, test-cases/performance/perf-regression-user-profiles.yaml, test-cases/performance/perf-regression-write-latency-cdc.yaml, test-cases/performance/perf-regression-write-throughput-cdc.yaml, test-cases/performance/perf-regression.100threads.30M-keys.yaml, test-cases/performance/perf-row-level-repair-1TB.yaml, unit_tests/test_cluster.py
if flag will be set to `True`, then kernel callstack
will be printed in Scylla logs, otherwise (the default)
will be to NOT print it.
=> improvement(print_kernel_callstack): add new flag

jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-gce-1tb.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile, jenkins-pipelines/manager/centos-manager-backup.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile, jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile, jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian11-manager-sanity.jenkinsfile, jenkins-pipelines/manager/debian11-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/enterprise-ami-manager-sanity.jenkinsfile, jenkins-pipelines/manager/enterprise-ami-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile, vars/managerPipeline.groovy
=> fix(manager tests): removed unnecessary timeout jenkinsfile param

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml, test-cases/longevity/longevity-large-partition-3h.yaml, test-cases/longevity/longevity-large-partition-4days.yaml, test-cases/longevity/longevity-large-partition-8h.yaml
In order to decrease connection requests load on cluster by scan thread.
Intervals of 4 large-partitions longevities are increased to 5 minutes.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4960
Notes:
1) I'm not sure whether this should be backported or not (not a must).
2) The interval unit is not changed from seconds to minutes in order to keep future ability to test this lower granularity if needed.
That is since it is an important feature to an important customer (Discord) and scylla-bench doesn't have a stable supporting version for that.
https://trello.com/c/U3bhzNUL
=> fix(Full-Partition-Scan): Increase scan interval

jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile, vars/rollingUpgradePipeline.groovy
This PR switches the rolling-upgrade for Ubuntu 20.04 from installing Scylla from package to using a GCE machine image.
Trello task: https://trello.com/c/DdGNfOXx
Jenkins job using the GCE images for db nodes: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/ubuntu-20-machine-image/22
=> refactor(rolling_upgrade): machine image as base for ubuntu 20.04

unit_tests/test_base_version.py, utils/get_supported_scylla_base_versions.py
It was decided to use 5.0 as a base version for rolling-upgrade test for
2022.1 instead of 4.6:
https://github.com/scylladb/scylla-enterprise-machine-image/issues/50
This commit adapts upgrade test to this decision.
=> fix(upgrade): fix base version for 2022.1

vars/rollingUpgradePipeline.groovy
Since either of those params can be null in a rolling upgrade run,
the pipeline must be prepared to ignore either of them if their value is
indeed 'null'.
=> fix(rollingUpgrade): gce_image_db use_preinstalled_scylla can be null

configurations/aws/i3en_2xlarge.yaml
we saw that the amount of load we were producing was
not enough, so here we are doubling the load for
the test using instances i3en, so the results
could be comparable (as CPU utilisation was too low).
EDIT:
here are the commands we will use on `i3en` instances (as they are much stronger than the `i3.2xlarge` we use for the regular test:
```
stress_cmd_w: "cassandra-stress write no-warmup cl=QUORUM duration=600m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=80 throttle=9000/s' -col 'size=FIXED(128) n=FIXED(8)' -pop 'dist=gauss(1..250000000,125000000,12500000)' "
stress_cmd_r: "cassandra-stress read no-warmup  cl=QUORUM duration=600m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=80 throttle=8000/s' -col 'size=FIXED(128) …
```
=> improvement(perf during ops): increase load for i3en test

sdcm/cluster.py, sdcm/utils/remote_logger.py
seem like on some distro we don't have python3 installed by
default anymore, so we need to make sure we installed it
before we start using it for the logger.
we would be able to remove this once we user cloud-init
configuration across the board, and we'll be able to make sure
this package is installed there.
Fix: #5043
=> fix(SSHScyllaSystemdLogger): install python3 to remove if needed

defaults/azure_config.yaml
Since in real azure clusters customers will most likely use azure as the backup backend
as well, our scenarios should match it.
=> refactor(azure config): Changed backup backend to azure instead of s3

sct.py, sdcm/provision/azure/provisioner.py, sdcm/provision/azure/resource_group_provider.py, sdcm/provision/azure/virtual_machine_provider.py, sdcm/provision/provisioner.py, unit_tests/lib/fake_provisioner.py, unit_tests/provisioner/test_provisioner.py
Azure does not provide a way of retrieving creation time of resources.
We often need to see when were created, including list-resources
command.
This commit adds `creation_time` tag to VM's and RG's on Azure. Extended
also `VmInstance` class with this information for `list-resources` use.
=> feature(azure): add creation time to rg and vm's

sdcm/rest/compaction_manager_client.py, sdcm/sct_events/group_common_events.py, sdcm/utils/compaction_ops.py, stop_compaction_test.py
This PR introduces a few changes to the `StopCompaction` test:
- new REST API command for stopping a compaction on a given ks / cf is added
- new tests are added to cover the above API changes (mirroring the previous tests for stopping compaction)
- email reporter is switched to `FunctionalTestReporter`
- a decorator is added to collect subtest results for the functional tests template
- previously created tests are also decorated with the new decorator
Trello task: https://trello.com/c/onlJj6Nm
Jenkins runs:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-byo-new-test/265
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-byo-new-test/266
=> Refactor stop compaction feature tests

test-cases/longevity/longevity-10gb-3h.yaml
Due low quota limit we cannot use stronger machines on Azure in
longevity-10gb-3h test. Currently we use equivalent of i3.2xlarge, while
aws test uses i3.4xlarge.
To reduce load, which now hits 80-100% most of the test time, lets try
using new generation of Ls machines and make Azure test a bit easier.
=> feature(azure): use new Ls generation instance for 10gb test

sdcm/utils/version_utils.py
If we call `transform_non_semver_scylla_version_to_semver` function
with `latest` tag then we get following error:
new_scylla_version = f"{version_parts[0]}.{version_parts[1]}.0-{'.'.join(version_parts[2:])}"
IndexError: list index out of range
So, make it be safer by checking the length of the `version_parts` var
The improper behavior was introduced here: https://github.com/scylladb/scylla-cluster-tests/pull/4746
=> fix(version_utils): make semver transformation function be safer

longevity_test.py
Before, stress_cmd was treated as a string, when in reality it could be either a string or a list.
I modified the method to be able to handle stress_cmd whether it's a list or a string.
=> fix(_run_stress_in_batches): treat stress_cmd as a list or a string

sdcm/utils/common.py
Following the changes in https://github.com/scylladb/scylla-machine-image/pull/383 , need to update the filter with new prefix
**to merge only after https://github.com/scylladb/scylla-machine-image/pull/383**
=> fix(common:get_branched_ami): filter out debug-* AMIs

sdcm/sct_events/group_common_events.py, upgrade_test.py
According to https://github.com/scylladb/scylla/issues/10447#issuecomment-1194155163,
we should ignore all 'abort requested' error messages we see during the upgrade or
rollback procedures.
=> fix(rolling upgrade): ignored all 'abort requested' messages

sdcm/cluster_k8s/__init__.py
Setting of 7 CPU cores from each 8 available must be done always
not only when the performance tuning is enabled.
=> fix(k8s): always set proper number of CPUs for Scylla pods

sdcm/utils/version_utils.py
seem like since the last few days the image in dockerhub doesn't
show the layers and thier digest anymore, switching
to more crude way of getting the correct version/tag
to use.
Ref: https://github.com/scylladb/scylla-pkg/issues/3009
=> fix(get_specific_tag_of_docker_image): tag doesn't have images anymore

vars/managerPipeline.groovy
Since scylla 5.0 is now promoted, we will use it as the deafult version in all
manager test scenarios
=> improvement(manager tests): using scylla 5.0 instead of 4.6

sdcm/report_templates/results_latency_during_ops_short.html, sdcm/utils/latency.py
we were requested to improve the report, but improving
the colors of the lines, when the difference between
steady state and the avg cycle will be bigger than
10ms it will be marked in red, else, if it will be
bigger than 5ms it will be marked as yellow, and
in any other case, it will not be colored.
=> improvement(latency during ops): report colors

sdcm/stress_thread.py, sdcm/tester.py, unit_tests/test_stress_thread_functions.py
Sometimes we face freeze of c-s thread blocking the test flow.
This commit adds automatic timeout to stress threads (c-s, sb and
gemini) when duration in stress cmd is specified. 
Timeout is calculated as this:
warmup + duration + 600 (all in seconds).
https://trello.com/c/wZoe5pd3
=> feature(stress-thread): set timeout based on duration

sdcm/keystore.py, vars/getJenkinsLabels.groovy
now that we have a new project up and running, we want
to switch all of the running jobs to it.
=> feature(gce_project): switch the default project for gce

sdcm/utils/cloud_monitor/resources/__init__.py, sdcm/utils/cloud_monitor/resources/instances.py, sdcm/utils/cloud_monitor/templates/per_qa_user.html, sdcm/utils/cloud_monitor/templates/per_user.html
now that we have multiple project for GCE, we need to show and report
them all
New project column for GCE instances:
=> feature(cloud_monitor): add support for showing multiple projects

sdcm/provision/azure/utils.py, sdcm/utils/version_utils.py, unit_tests/provisioner/fake_azure_service.py, unit_tests/provisioner/test_azure_get_scylla_images.py, unit_tests/provisioner/test_data/SCYLLA-IMAGES/azure_images_list.json, unit_tests/test_version_utils.py
Due changes in Scylla build jobs, ordering by build-id is not working
correctly.
This commit fixes ordering by sorting by build date (and build id when
date is the same) taken from ScyllaVersion tag.
fixes: #5041
=> fix(azure-list-images): fix scylla master latest images list

sdcm/cluster.py
This reverts commit 4aa15e3b43c4b2bfe4cdc0df01cbc0c77c1d804c.
the fix was released in all supported based versions, hence
this workaround is not necessary anymore.
=> Revert "fix(install_scylla): adding workaround to JDK"

sdcm/nemesis.py
After the node reboot, it's possible it would take a little longer than previously expected for
the CDC desctiption to be updated. As such, I added a short retry after the reboot so that the
nemesis will wait for the CDC generation to be updated a short time after scylla is UN.
https://github.com/scylladb/scylla/issues/10973#issuecomment-1193986759
=> fix(disrupt_multiple_hard_reboot_node): waiting for cdc success messages

sdcm/cluster_aws.py, sdcm/cluster_gce.py, sdcm/provision/azure/utils.py, sdcm/provision/common/configuration_script.py, sdcm/provision/common/utils.py, sdcm/sct_config.py, sdcm/sct_provision/aws/cluster.py, sdcm/sct_provision/aws/user_data.py, sdcm/sct_provision/user_data_objects/sshd.py, sdcm/utils/gce_utils.py, unit_tests/test_config.py
after scylladb/scylla-machine-image#363 is a while now in master
we want to be able to utilized it, to seperate our boot scripts
from the scylla-machine-image into cloud-init script.
running some of those scripts in the context of
scylla-machine-image are causing use issue like repo/list of apt/yum
not being correct, since we are doing it before cloud-init
finish all it's work. waiting for cloud-init to finish is also
problemtic, since scylla-machine-image it's is holding it
for getting to it's final stage.
=> feature(multi-part): centerlize the creation of user-data for AWS

unit_tests/test_base_version.py, unit_tests/test_config.py
now that 2022.1 was released, we would get it as a base
version for 2022.1 runs
=> fix(unit-tests): add 2022.1 to base versions

sdcm/cluster_aws.py
for some reason, that import disappeared
from that file, and when we had a fallback
from `spot` to `on_demand`, test failed
with syntax error.
=> fix(cluster_aws): added missing import

docker/env/hydra.sh, sct_ssh.py
since we didn't pass that explicitly, the defaults were used
and terminal size was smaller then the acutal terminal being
used, and problematic to use
=> fix(hydra_ssh): pass down tty lines/cols to the ssh command

sct.py, sdcm/utils/cloud_monitor/resources/instances.py, sdcm/utils/common.py, sdcm/utils/gce_utils.py
now that we can use multiple gce project, we want to make sure we
list and clean resouces on all the available projects.
=> feature(list/clean-resources): support multiple gce project

sdcm/utils/common.py, sdcm/utils/sstable/load_utils.py
The issue was represented  by https://github.com/scylladb/scylla-cluster-tests/pull/4968
NodetoolRefresh nemesis failed with error:
```
File '/home/ubuntu/scylla-cluster-tests/sdcm/utils/sstable/load_utils.py', line 68,
in upload_sstables
node.remoter.sudo(f'tar xvfz {test_data.sstable_file} -C {tmp_folder.folder_name}/', user='scylla')
tar: /tmp/tmp.wUtrdYx7bd: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
```
Temporary folder was created as root, but run untar is run as 'scylla'.
Also temporary folder shouldn't be owned by root.
Use temporary folder in case when schema should be created.
=> fix(load utils): untar snapshot

jenkins-pipelines/manager/debian11-manager-sanity.jenkinsfile, jenkins-pipelines/manager/enterprise-ami-manager-sanity.jenkinsfile
since vpc-peering for AWS was merged we should be using public
network for multi-dc test cases,
those case were merge after the work in vpc-peering was done, hence
they were missing this change
=> fix(manager-sanity): stop using public networking

sdcm/nemesis.py
We know that the `disrupt_nodetool_flush_and_reshard_on_kubernetes`
nemesis makes some Scylla pods change IP addresses.
So, call `reconfigure_scylla_monitoring` method after we refresh IP
addresses.
=> fix(k8s): run reconfigure_scylla_monitoring in flush and reshard nemesis

defaults/k8s_eks_config.yaml, defaults/k8s_gke_config.yaml
For the moment we have 2 monitorings - main one on VMs and additional one on K8S.
So, the latter one is not used now, takes some time for installation and may cause test run failures.
So, just disable it for all K8S jobs.
=> improvement(k8s): disable k8s monitoring as redundant

defaults/k8s_eks_config.yaml, defaults/k8s_gke_config.yaml, defaults/k8s_local_kind_config.yaml
For the moment we have default value for the `k8s_n_loader_pods_per_cluster`
option be defined to 1 without regards to the `n_loaders`.
It leads to the situation that in each CI job that was not updated
like the multi-tenant ones we get only 1 loader pod.
But in lots of cases we have 2 or 4.
So, fix it by removing default value, in such a case SCT will use
value of the `n_loaders` option which is exactly what we need.
=> fix(k8s): use proper number of loaders in K8S with single DB cluster

sdcm/cluster.py, sdcm/cluster_k8s/__init__.py
For the moment, if we run `_refresh_instance_state()` method,
the `cql_ip_address` property won't be updated like
the `public_ip_address` and `private_ip_address` ones.
This is the problem because `cql_ip_address` stops refering
to really existing IP address.
As of now, it makes all the consumer classes/functions of this
attribute fail in a strange way. One of the directions is the
`scylla-bench load nemesis's` which run after
`disrupt_nodetool_flush_and_reshard_on_kubernetes` one.
=> fix(k8s): make cql_ip_address not be cached forever

data_dir/scylla-dash-per-server-nemesis.master.json
for some reason, `Normal` and `Warning` events
are being listed automatically, and it is
distubring the usage of Grafana, showing many
information in the charts while not required
(specially during screenshots).
disabling these options so we will have a clean
dashboard when opening it, as the ability
to re-set it, is in there.
giving it a try [in here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/grafana_changes/job/longevity-10gb-3h/4/)
=> fix(grafana_sct_dashboard): clear default list flags

sdcm/cluster_aws.py
in 05e3544b43ce0c99e2bcaa88d6a6588d6ec093f7 the user-data for AWS
was centelized, but the support for sending user-data for node
other then the db was broken, and SMI user-data was sent to all
of them, breaking some test cases which depends on it, ipv6 cases
for example
=> fix(loader_user_data): bring back user-data for loader nodes

sdcm/nemesis.py
The case of the `disrupt_restart_with_resharding` nemesis is covered
with the K8S-specific nemesis called `disrupt_nodetool_flush_and_reshard_on_kubernetes`.
So, just skip `disrupt_restart_with_resharding` when running on K8S.
=> fix(nemesis): skip 'disrupt_restart_with_resharding' nemesis for K8S

sdcm/cluster.py
As part of the apt-key deprecation [0], we need to use gpg to consume the repo key and
change the repo file (scylla.list) to explicitly point to the key,
This is a chick-and-egg change because the repo file should be changed on pkg repo and
once it changed, the gpg command (added on this commit) is required,
For this reason we'll start with adding the gpg aside of apt-key and later we'll remove the
apt-key refs.
Ref https://github.com/scylladb/scylladb/issues/11186
[0] https://wiki.debian.org/DebianRepository/UseThirdParty
=> feature(cluster): consume scylla key by gpg instead of apt-key

sdcm/cluster.py, sdcm/cluster_aws.py, sdcm/cluster_gce.py, sdcm/provision/common/configuration_script.py, sdcm/provision/common/utils.py
PR #5035 started using `user_data_format_version=3` and was
working both on artifacts test and other tests, when specificed
exactly which version to use
later on that series reading of the value of `user_data_format_version`
from the images was introduced, and the default there was version=2
for competibility with older versions that missing the tagging
that was breaking the ubuntu22, since they need the patch for
enabling ssh rsa protocol.
this commit default `user_data_format_version=3` on cases
use don't have scylle pre-installed.
Fix: #5105
=> fix(user-data): user_data_format_version=3 when scylla isn't preinstall

unit_tests/test_base_version.py
Unit test will fail because we have a newer version of enterprise than 2022.1. Bumping the version in `test_enterprise()` to 2022.2
=> fix(unit_test): bump current enterprise version to 2022.2

sdcm/utils/common.py
when threads are raising exceptions, currently only the
string of the exception is printed to the log, and it's not
really helpful in most situations
code is changed to pring a full backtrace of the exception
=> fix(ParallelObject): log a full tracebacks on failures

sdcm/cluster_k8s/__init__.py
If we run K8S functional tests with `SCT_REUSE_CLUSTER=1` config option then we get following error:
```
sdcm/cluster_k8s/__init__.py:2532: in prefill_cluster
SstableLoadUtils.run_refresh(node, test_data=test_data[0])
sdcm/utils/sstable/load_utils.py:113: in run_refresh
system_log_follower = node.follow_system_log(patterns=[r'Resharded.*'])
sdcm/cluster.py:1454: in follow_system_log
stream = File(self.system_log)
sdcm/utils/file.py:48: in __init__
self._io = self._open()
...
E  FileNotFoundError: [Errno 2] No such file or directory: '%path-to%/system.log'
```
The failed part must not even run when we already have populated data.
So, fix the pre-fill data logic by making it end as soon as possible.
=> fix(k8s-functional): make prefill_cluster not run when we reuse cluster

sdcm/nemesis.py
This commit is part of support operator multi-tenant longevity.
Longevity test should be run on every tenant in parallel threads.
In the current realization a disrupt wrapper is applied on the class level. As result the wrapper
will be applied a few times (as much as clusters amount)
To solve it save all wrappered disrupt methods in the list to prevent double applying
=> improvement(nemesis): add wrapper to disrupt method during init

jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/enterprise-ami-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile, jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Since manager 3.0 is released, it needs to be the base version of the manager upgrade test
=> refactor(manager upgrade): bump base manager version to 3.0

sdcm/cluster_k8s/gke.py, sdcm/sct_runner.py
Currently, the GKE provisioning is broken in 2 places.
1) `GKE monitoring node label setting`
If we run a test on GKE backend then we get following error creating monitoring node:
```
sdcm.cluster.NodeError: Timeout while running 'ex_set_node_labels' method on GCE instance '3260019724311279728'
```
So, fix it by adding the required 'monitorid' label to the 'tags' attribute that will be added
by the common code and remove the failing part from the GKE's monitoring class.
2) `GKE cluster creation`
For the moment, if we try to create a GKE cluster we get following error:
```
ERROR: (gcloud.container.clusters.create) ResponseError:  code=403, message=Request had insufficient authentication scopes.
```
The root cause for it is absence of enabled `cloud-platform` scope for the SCT runner …
=> Fix gke provisioning

sdcm/cluster.py
This fixes an issue where an exception occuring in argus client during
shard reporting would propagate to the events system and fail the test.
=> fix(sdcm/tester.py): Fix test stoppage on shard reporting failure

test-cases/scylla-operator/kubernetes-operator-upgrade.yaml, test-cases/scylla-operator/kubernetes-platform-upgrade.yaml
After implementation of the `k8s_n_scylla_pods_per_cluster` config
option the following 2 config files started being wrong:
- test-cases/scylla-operator/kubernetes-operator-upgrade.yaml
- test-cases/scylla-operator/kubernetes-platform-upgrade.yaml
So, fix it by making the `n_db_nodes` config option have `4` value
instead of `3`. It will allow the operator and K8S platform tests
pass through the step where 4th Scylla member(pod) gets created.
=> fix(k8s-upgrade): provision 4 K8S Scylla nodes

sdcm/cluster_k8s/gke.py
The one we currently use - `--enable-stackdriver-kubernetes` is deprecated already.
So, replace with with the actual following analog:
'--logging=SYSTEM,WORKLOAD --monitoring=SYSTEM'
Info: https://cloud.google.com/stackdriver/docs/solutions/gke/installing#deprecated_configuration_parameters
=> fix(gke): use non-deprecated config option for the logging

defaults/k8s_eks_config.yaml
According to the docs [1] we should use much newer `vpc-cni` version
for our EKS clusters of currently supported K8S versions.
So, as of now it must be `v1.11.3-eksbuild.1`
[1] https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html
=> improvement(eks): bump vpc-cni version

sdcm/cluster.py, sdcm/provision/scylla_yaml/cluster_builder.py, unit_tests/test_scylla_yaml_builders.py
The 'role_manager' Ldap property was missed in past refactor.
Trello: https://trello.com/c/pf2BS8G8
=> fix(ldap authorization): add missing ldap property of role_manager

sdcm/sct_runner.py
update_sct_runner_tags() should not raise an error
when no runners are found, it should just print out
the warning. We call this method after collecting
logs, which we also do for artifact jobs, which run
on builders, so there are no runners for these tests.
=> fix(sct_runner): reduce error to warning for no runners

sdcm/provision/common/utils.py, sdcm/utils/syslogng.py
Seem like when running older versions of scylla 4.6 and lower
which we still use as oracles for gemini tests.
we fail to install syslog-ng, and fallback to using rsyslog
the way we configure rsyslog isn't comptible with syslog-ng
rsyslog driver.
we need to maybe put it behind a configuration option,
or invest in removing the rsyslog support completly
and fixing the install issues syslog-ng had, across the board
This reverts commit a11dbb24f9e9754872b1c47138aed5fe4badae85.
=> Revert "fix(syslog-ng): add support for multi-line logs"

sdcm/tester.py, vars/runCleanupResource.groovy, vars/runCollectLogs.groovy, vars/runSctTest.groovy
After merge of the [1] the `gce_datacenter` may now be also list.
So, make the GKE logic in 'tester.py' be smart enough to handle
both possible types of that option - 'str' and 'list'.
Also, fix the groovy files which incorrectly handle the `gce_datacenter`
pipeline parameter when the GKE backend is used.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/4978
=> fix(gke): make longevity CI jobs work

sdcm/utils/common.py
After the merge of the `vpc-peering` feature [1] the GCE backend's cleanup
started working incorrectly.
The `get_security_groups_ips` function, which gets called in the middle
of all the cleanup functions, removes `NodeType` tag from the shared
dictionary object and it leads to the situation that all of the test run
nodes including SCT runner get deleted as part of the `DB nodes` cleanup.
As a result, the connection to the SCT runner, obviously, gets lost
and job always fails on the `cleanup-resources` stage.
So, fix it by making the mentioned function not change the shared
dictionary object with tags.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/4742
=> fix(gce): make cleanup work correctly

sdcm/sct_config.py, sdcm/utils/version_utils.py
Scylla-operator behaves incorrectly when non semver-like docker image
tag is used for Scylla pods.
So, if 'latest' Scylla version was provided and SCT fails to find
appropriate specific tag for the digest from it then fail fast
to avoid unpredictable behavior and errors.
=> improvement(k8s): fail fast if latest tag not translated to specific one
