- README.rst
- scylla_longevity.py
- scylla_longevity.py.data/scylla-longevity.yaml
- sdcm/cluster.py
- sdcm/remote.py
- sdcm/tester.py
Add the ability to run tests with Cassandra as well.
> Run tests with cassandra

- scylla_maintainance.py
- scylla_maintainance.py.data/scylla-longevity.yaml
- scylla_maintainance.py.data/scylla-maintainance.yaml
- scylla_maintainance.py.data/scylla.repo
- sdcm/nemesis.py
This nemesis will do the following scenario:
drain a node, stop it then start it.
> nemesis: Add the DrainMonkey nemesis

- sdcm/nemesis.py
> DrainerMonkey: Make it really non periodic

- scylla_longevity.py
- scylla_maintainance.py
- sdcm/data_path.py
- sdcm/nemesis.py
- sdcm/tester.py
Make Nemesis functionality more flexible.
> Refactor nemesis functionality

- sdcm/cluster.py
> sdcm.cluster: Update AMI user

- sdcm/nemesis.py
The later is simple and shorter, not sure why I missed
that the first time I was writing the code.
> sdcm.nemesis: Rename node_to_operate -> target_node

- sdcm/cluster.py
> sdcm.cluster: Log cleanups

- sdcm/cluster.py
> sdcm.cluster: Fix Node.restart()

- README.rst
> README.rst: Update with latest suite status

- LICENSE.AGPL
- README.rst
- big_cluster.py
- grow_cluster_test.py
- longevity_test.py
- maintenance_test.py
- query_limits.py
- sdcm/cluster.py
- sdcm/data_path.py
- sdcm/log.py
- sdcm/nemesis.py
- sdcm/remote.py
- sdcm/tester.py
- sdcm/wait.py
Cleanup information logging, by using the python `logging` module, instead of `print`.
> Logging changes

- sdcm/cluster.py
> cluster: Install scylla-gdb before getting the traces

- sdcm/cluster.py
Since AWS adopts an eventual consistency model, sometimes the method
wait_until_running will raise a botocore.exceptions.WaiterError saying
the instance does not exist. AWS API guide [1] recommends that the
procedure is retried using an exponencial backoff algorithm [2].
[1] http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency
[2] http://docs.aws.amazon.com/general/latest/gr/api-retries.html
> sdcm.cluster.Node: Make .wait_until_running safer

- sdcm/cluster.py
- sdcm/remote.py
- sdcm/tester.py
A few touches on scylla log collection.
> Improve scylla log collection

- cql_test.py
- sdcm/cluster.py
- sdcm/tester.py
Add support to CQL queries to sdcm.
> CQL connection

- sdcm/cluster.py
- sdcm/remote.py
Improve backtrace collection, and fix an issue we saw sparingly on master ssh connections start.
> Better backtrace collection

- README.rst
> README.rst: Update requirement list for cassandra-driver

- README.rst
> README.rst: Small markup fix

- sdcm/nemesis.py
Let's better handle nodetool command errors by handling
their exceptions and logging them appropriately.
Signed-off-by: Lucas Meneghel <lmr@localhost.localdomain>
> sdcm.nemesis: make nodetool nemesis functions more secure

- sdcm/nemesis.py
Do a little refactor and put the code that executes nodetool
on a node on its own 'private' method. Also, just log error
messages instead of throwing exceptions, because it's often
interesting to see how things play out instead of straight
out blow the nemesis method.
Signed-off-by: Lucas Meneghel <lmr@localhost.localdomain>
> sdcm.nemesis: Handle nodetool command errors systematically

- longevity_test.py
- sdcm/cluster.py
- sdcm/nemesis.py
Make nemesis interval configurable in all tests.
> Make runs configurable

- big_cluster.py
- grow_cluster_test.py
- query_limits.py
Small fixes I found going over the available tests once again.
> Small fixes

- sdcm/cluster.py
- sdcm/tester.py
> sdcm.tester: Move nemesis report from destroy step

- data_dir/scylla.yaml
- sdcm/tester.py
A few more tweaks to the test suite.
> Tweaks 2016 03 14

- grow_cluster_test.py
- sdcm/nemesis.py
A few improvements on the chaos monkey.
> Improvements chaos monkey

- sdcm/cluster.py
> sdcm.cluster: Save c-s plots in svg

- reduce_cluster_test.py
- sdcm/cluster.py
- sdcm/nemesis.py
Can be used to shrink a cluster size from X nodes to Y nodes.
> Introduce reduce_cluster_test

- grow_cluster_test.py
- longevity_test.py
- reduce_cluster_test.py
- sdcm/cluster.py
- sdcm/tester.py
Before we growing or shrinking the cluster, wait until cluster is filled with data.
> Wait for cluster is filled with data

- sdcm/nemesis.py
Add an operation log to nemesis and fix a silly nemesis reporting bug
> Operation log

- reduce_cluster_test.py
It is faster than 5 to 3 tests.
> Add test_reduce_4_to_3

- data_dir/scylla.repo.upgrade
- sdcm/nemesis.py
- upgrade.py
The real version that don't break havok everything :)
> Create a way to test upgrades

- sdcm/cluster.py
> sdcm.cluster: Fix upgrading bin functionality

- grow_cluster_test.py
Do not estimate how long the adding node will take, instead stop
c-s when all of the adding node opeation is done.
> grow_cluster_test: Kill c-s when adding node is done

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/remote.py
- sdcm/tester.py
This PR adds nemesis event visualization in c-s generated graphs.
An example of the end result can be seen on the attached png files:
> Nemesis timeline work

- grow_cluster_test.py
- reduce_cluster_test.py
- sdcm/cluster.py
- sdcm/nemesis.py
Some changes to grow and reduce nemesis tests.
> Grow cluster use nemesis

- grow_cluster_test.py
Replace the old one test_grow_3_to_4_while_filled with new one test_grow_3_to_4.
> Test grow 3 to 4

- grow_cluster_test.py
- reduce_cluster_test.py
- sdcm/cluster.py
Let's fix that typo across the codebase.
> cluster suite: Fix typo treshold -> threshold

- sdcm/cluster.py
When using cassandra AMIs with longevity tests, currently
we'll see one error message in the logs:
2016-06-02 06:32:14,311 remote L0192 DEBUG| [54.173.211.61] [stderr] sudo: journalctl: command not found
So let's fix that by using the heuristic:
* AMI has journalctl - Scylla, let's use journalctl
* AMI doesn't have journalctl - Cassandra, let's use /var/log/syslog
Since currently our target cassandra version used for comparison
is 2.1, we should be OK. In the future, we can always revise
that rule.
> sdcm.cluster: Get DB services log on cassandra AMIs

- sdcm/cluster.py
Run tcpdump on nodetool cfstats. This is mostly to provide
extra debugging info on scylla issue:
https://github.com/scylladb/scylla/issues/1306
And we can turn it into a configurable option.
> sdcm.cluster: Run tcpdump on lo during nodetool cfstats commands

- sdcm/cluster.py
> Fix tcpdump .pcap file capture

- sdcm/cluster.py
> sdcm.cluster: Copy pcap file even on nodetool cmd error

- data_dir/scylla.repo.downgrade
- data_dir/scylla.repo.upgrade
- data_dir/scylla.yaml
- partial_upgrade_downgrade_test.py
New tests for 1.2
-Update image and target repo file.
-Add partial upgrade then downgrade test asked by Shlomi.
> Upgrade downgrade

- data_dir/scylla.repo.upgrade
> data: Upgrade 1.2 Scylla repository

- README.rst
Remove the reference to an old avocado version's bug.
> README.rst: Remove outdated piece of information

- README.rst
Document the specifics relative to the newly added
libvirt backend.
> README.rst: Update to reflect new Libvirt backend

- custom_cs_test.py
- data_dir/cassandra-stress-custom.yaml
- sdcm/cluster.py
Make it simple to run a custom cassandra-stress YAML using scylla-cluster-tests.
> Custom cassandra-stress (YAML) test

- data_dir/break_scylla.sh
- data_dir/scylla-maintenance.yaml
- maintenance_test.py
- sdcm/tester.py
New, rebased version of @slivne's patchset.
> Repair Test Upgrades

- sdcm/cluster.py
- sdcm/tester.py
- tests/repair.ec2_i2-8x.cpu_25.data_100G.profile_write.yaml
Slightly corrected version of #134, by @slivne.
> [V2] slivne repair test

- data_dir/scylla.yaml
- sdcm/cluster.py
- sdcm/tester.py
Introduce prometheus [1] monitoring support to scylla-cluster-tests.
[1] https://prometheus.io/
> Monitoring support

- tests/repair.ec2_i2-8x.cpu_25.data_100G.profile_write.yaml
Signed-off-by: Shlomi Livne <shlomi@scylladb.com>
> Update repair test to use monitor server

- README.rst
Now that the suite uses prometheus and grafana
for DB Node monitoring, let's document the relevant
bits on the README file.
> README.rst: Update with monitoring information

- sdcm/nemesis.py
Version of #146, with small needed fixes.
> sdcm.nemesis: Add stop start with wait

- data_dir/scylla.yaml
- sdcm/cluster.py
- sdcm/tester.py
Few corrections to s-c-t behavior.
> Dont use keepalive

- README.rst
- requirements.txt
- sdcm/cluster.py
- setup.py
- setup_venv
Since the two features go hand in hand, I've decided to join #135 and #126 into a single PR.
> Better cleanup and easier install

- sdcm/cluster.py
Refactor the code for LoaderSet, also, separate latency graphs into each latency type, for #122.
> Graph improvements

- sdcm/cluster.py
- sdcm/tester.py
Improvements to coredump reporting and test failing
> Coredump report improvements

- data_dir/scylla.yaml
- sdcm/cluster.py
- sdcm/tester.py
* Fix a problem in the new grow cluster test with large partition test where c-s ends before we try to terminate it
* Update grafana used in monitoring nodes
* Make it possible to disable monitoring nodes, per @asias's request
> Miscellaneous fixes/changes

- sdcm/cluster.py
- sdcm/tester.py
Some fixes I found while working on Noam's changes.
> Bugfixes 2016-08-18

- data_dir/scylla.yaml
- grow_cluster_test.py
- longevity_test.py
- reduce_cluster_test.py
- sdcm/cluster.py
- sdcm/tester.py
Changes requested by one of our team members, implemented here.
> Noam changes

- sdcm/cluster.py
If you are installing from libvirt, the base centos image
won't have scylla-tools installed (provides cassandra-stress).
So let's explicitly install scylla-tools on libvirt loader
nodes.
> sdcm.cluster: Explicitly install scylla-tools on libvirt loader nodes

- sdcm/cluster.py
- sdcm/remote.py
Add shortcuts to Node.remoter functions and improve update binary DB
> sdcm.cluster: Add shortcuts to Node.remoter functions and improve update binary DB

- performance_regression_test.py
This pull request contains a small patch to introduce mixed test, it's very similar as read test, almost only rename 'read' as 'mixed'.
Thanks.
> Introduce Mixed test

- README.rst
> README.rst: Update packages needed to install cassandra-driver

- big_cluster_test.py
- grow_cluster_test.py
- query_limits_test.py
- reduce_cluster_test.py
- sdcm/cluster.py
- sdcm/collectd.py
- sdcm/loader.py
Add cassandra stress monitoring
> Collectd for cs

- build_cluster_test.py
- data_dir/scylla-dash-io-per-server.json
- data_dir/scylla-dash-per-server.json
- data_dir/scylla-dash-timeout-metrics.json
- data_dir/scylla-dash.json
- sdcm/cluster.py
* Small fix to NoMonitorSet objects
* Print Prometheus UI URL
* Rename Grafana dashboards
* Refactor Grafana data source and dashboard registration
* Add a new Grafana dashboard with timeout metrics
> Grafana dashboard improvements

- data_dir/scylla.yaml
Also take care of updating the obsolettes
comments.
> monitor: Enable monitoring with Cassandra

- data_dir/scylla.yaml
- grow_cluster_test.py
- longevity_test.py
- maintenance_test.py
- partial_upgrade_downgrade_test.py
- reduce_cluster_test.py
- sdcm/cluster.py
- sdcm/collectd.py
- sdcm/nemesis.py
- upgrade_test.py
A few fixes on top of @benoit-canet's original PR #203.
> [V2] Fixes for grow_cluster_test.py

- data_dir/scylla.yaml
- requirements.txt
- sdcm/cluster.py
- sdcm/collectd.py
- sdcm/remote.py
- sdcm/tester.py
Make it possible to run sct tests on OpenStack. The support to this backend is on its early stages, so lots of polish will be needed.
> [WiP] OpenStack support

- README.rst
- data_dir/scylla.yaml
- performance_regression_test.py
- sdcm/cluster.py
- sdcm/tester.py
Add initial support for GCE (Google Compute Engine). With this, it's possible for SCT to create resources and run tests in this new cloud provider.
> GCE initial support

- sdcm/cluster.py
- sdcm/collectd.py
- sdcm/loader.py
Few fixes I've got after looking at bug reports and talking to colleagues that have been using the suite.
> Random fixes

- data_dir/scylla.yaml
- sdcm/cluster.py
- sdcm/tester.py
A few patches to make GCE cluster setup more reliable from machines that are not inside the GCE network (example, your own laptop), and to speed it up a bit.
> Optimize gce setup

- sdcm/collectd.py
The default behavior is 'N' (Not install) and return error.
> yum: assume yes to confirm the ca upgrading

- sdcm/cluster.py
Grafana snapshot gives us quick and visual impression,
it's not convenient to load prometheus data from test
result. This patch supports to take monitor snapshot
at the end of test.
> feature: take snapshot for grafana monitor

- data_dir/scylla-dash-io-per-server.master.json
- data_dir/scylla-dash-per-server.master.json
- data_dir/scylla-dash.master.json
sync changes from scylla-grafana-monitoring project.
TODO: get the dashboard file from scylla-grafana-monitoring repo in runtime
> data_dir: update master dashboard

- build_cluster_test.py
1) Build a Scylla cluster with params defined in data_dir/scylla.yaml
2) Stop cluster.
3) Replace IPs for seeds, listen_address & broadcast_rpc_address on public dns names
4)The cluster works properly.
> add test_use_public_dns_names

- sdcm/cluster.py
Right now if the coredump is less than 5G, we will upload it directly
without compressing. This patch removed the size checking before spliting
and compressing. Then coredump will be compressed all the time, then
try to split if it's bigger than 5G.
> sdcm/cluster: always compress the coredump file

- sdcm/cluster.py
> use apt-get to install git when launch from ubuntu

- sdcm/cluster.py
before the performance scenarios update the cluster
with the packages located in update_db_packages folder(yaml conf parameter)
> add update_db_packages feature for gce perf tests

- performance_regression_test.py
test_details.packages_updated - true when folder 'update_db_packages' exists and not empty,
in the opposite case it's false(believe that there is nothing to update)
test_details.start_host - host name where test started
> add new stats in test_details: packages_updated & start_host

- performance_regression_test.py
we can exclude the following json stats from gce runs(they related aws instances):
'/run', 'instance_type_loader',
'/run', 'instance_type_monitor',
'/run/databases/scylla', 'instance_type_db'
> exclude aws instances types from gce report

- performance_regression_test.py
- sdcm/nemesis.py
print nodetool status(on every node) before and after every nemesis
> nodetool statuses after every nemesis

- performance_regression_test.py
- sdcm/tester.py
added new stats in ES:
results.stats_total.(op rate/Total errors)
test_details.prometheus_report
test_details.grafana_snapshot
+
upload prometheus data in s3 bucket: cloudius-jenkins-test.s3.amazonaws.com
> new stats in ES + post prometheus data in s3

- sdcm/cluster.py
[amos@cent0s7vm ~]$ scylla --version
666.development-0.20170507.9a1aa6c
> fix a typo of master version

- sdcm/cluster.py
Current snapshot looks like a phone view, it's not tolerant.
See latest wide snapshot:
> Monitor: take wide snapshot for easily inspect

- refresh_test.py
- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/tester.py
- sdcm/utils.py
- tests/gce-refresh-1.7-30mins.small.yaml
- tests/gce-refresh-1.7-30mins.yaml
Nodetool refresh after uploading lot of data to a cluster with running load in the background.
Current space_node_threshold is 6442450940, it decides the wait time before refreshing.
> Introduce nodetool refresh test

- data_dir/corrupt_sstables.sh
- sstable_corrupt.py
- tests/aws-sstable-1.7.yaml
> sstable corruption test

- sdcm/cluster.py
- sdcm/utils.py
We only add dashboard for release version, let's use master for pre-release version.
> monitor: use master dashboards for pre-release version

- multiple_dc_test.py
- tests/gce-multiple-dc-shutdown-30mins.yaml
Add multiple datacenter tests
The test is based on multi-dc support.
- https://github.com/scylladb/scylla-cluster-tests/pull/301
- https://github.com/amoskong/scylla-cluster-tests/tree/multi-dc-dev
> Multi dc test

- sdcm/cluster.py
- sdcm/tester.py
If version info isn't set, sct will load master dashboard by default.
> aws/openstack/libvirt: update version info after node setup

- tests/gce-longevity-1.7-small-7days.yaml
> increase longevity dataset to 100GB

- grow_cluster_test.py
- sdcm/tester.py
- tests/aws-grow-cluster-200nodes.yaml
> grow cluster test: support for custom node number

- sdcm/nemesis.py
if get_node_info_list trows exception(decommission already started) we get
that disrupt_nodetool_decommission method is not able to complete properly:
node is not desttroyed, new node is not added
> handle exception in disrupt_nodetool_decommission

- tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- tests/longevity-1TB-7days.yaml
- tests/longevity-50GB-4days.yaml
replaces all loader machine type in longevity to n1-standard-4 at GCE
> replaces all loader machine type in longevity to n1-standard-4 at GCE

- janus_graph_test.py
https://github.com/scylladb/scylla/issues/2497
>=2 nodes in cluster, 1 loader
> run Janus Graph integration tests against scylla

- performance_regression_test.py
- sdcm/cluster.py
- sdcm/tester.py
add scylla-bench https://github.com/pdziepak/scylla-bench in SCT
to run the tests with scylla-bench, loader nodes need separate setup: install goland and build scylla-bench. to do it we need set in config yaml file the following parameter:
bench_run: 'true'
as example I added 1 test: performance_regression_test.py:PerformanceRegressionTest.test_uniform_counter_update_bench
further we should discuss with the team what scenarios/loaders we want to see
> Scylla bench

- sdcm/cluster.py
Some of options doesn't exist in default scylla.yaml,
we can just append new parameters at the end of scylla.yaml
Example:
`append_conf: "\nenable_keyspace_column_family_metrics: true\nexperimental: true\n"`
Note: enable latency metrics and experimental features.
> conf: add a general way to append parameters to db config

- sdcm/nemesis.py
> cast nemesis error to string with no conditions to prevent

- performance_regression_user_profiles_test.py
- sdcm/results_analyze.py
get stress cmd from the profile yaml
> perf regression with user profile:

- longevity_test.py
- tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- tests/longevity-1TB-7days.yaml
- tests/longevity-50GB-4days.yaml
We want to have mixed workload in longevity, so we writ with populations
number to prepare the data.
> longevity: add mixed workload

- tests/perf-regression-user-profiles-1.7.yaml
related to:
[https://github.com/scylladb/scylla-qa-internal/pull/23](https://github.com/scylladb/scylla-qa-internal/pull/23)
> added necessary yaml paths to pref-regression-user-profile

- tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- tests/longevity-1TB-7days.yaml
- tests/longevity-50GB-4days-authorization-and-tls-ssl.yaml
- tests/longevity-50GB-4days.yaml
The qa-vpc reduces the effect from public network.
> GCE: use qa-vpc network for longevity

- data_dir/scylla-dash-per-server-nemesis.master.json
> add c-s latency metrics to longevity Dashboard in grafana

- data_dir/scylla-dash-per-server-nemesis.2017.1.json
- sdcm/cluster.py
This PR is for master branch.
There is another branch, which has patches for branch-enterprise: 
https://github.com/amoskong/scylla-cluster-tests/tree/enterprise_metric_for_branch_enterprise
> support nemesis/latency metrics for enterprise

- build_cluster_test.py
- sdcm/cluster_aws.py
- tests/build-cluster-dns.yaml
- tests/dns-cluster-15min.yaml
> a fix for the build_cluster_test. adds the yaml. works with stopped services.

- sdcm/cluster_aws.py
- sdcm/ec2_client.py
support large(more then limit) number of instances
2. code cleanup(duplicated code)
> 1. create cluster from aws spot instances:

- data_dir/scylla-dash-per-server-nemesis.2017.1.json
- data_dir/scylla-dash-per-server-nemesis.master.json
Problem:
Tested the fix locally, looks good.
> remove unused parameters for Y-axes of load latency

- sdcm/cluster_aws.py
Currently we call create_tags() two or three times to add tags to AWS instance, this PR reduce it to once.
> aws: set all tags once

- sdcm/prometheus.py
Currently we randomly choose a port to start prometheus API server,
it has little chance to fail, and it only try once.
This patch tried to start server from default 9389, it's occuried
by us in prometheus wiki. It will try to find a free port from a
range if default port isn't available.
https://github.com/prometheus/prometheus/wiki/Default-port-allocations
> enhance to get a free port for prometheus API server

- sdcm/cluster.py
base class variable was not seen by derived classes
> round robin load fix:

- sdcm/cluster.py
- sdcm/cluster_gce.py
- sdcm/collectd.py
- sdcm/remote.py
Epel installation and yum update have more chance to fail, this patchset changed them to retry in fail. Otherwise, the whole test will be broken by some random network problem.
> retry epel installation and yum update in fail

- sdcm/cluster_gce.py
Reverts scylladb/scylla-cluster-tests#484
> Revert "workaround for scylla issue #3161(yaml-cpp)"

- sdcm/nemesis.py
The new nemesis is used to test abort repair. It starts repair target_node
in background, wait until the repair starts, then try to abort the repair
streaming.
> nemesis: introduce AbortRepair nemesis

- sdcm/nemesis.py
Reverts scylladb/scylla-cluster-tests#481
> Revert "nemesis: introduce AbortRepair nemesis"

- longevity_test.py
- sdcm/cluster.py
- sdcm/tester.py
- tests/longevity-multi-keyspaces.yaml
- tests/longevity-staging.yaml
DO NOT merge yet - require extensive testing
Refactoring test_custom_time to support multi keyspace with round_robin.
> Longevity with multi keyspaces

- sdcm/tester.py
The helper gets size in GB and run list of c-s commands in round robin on all loaders, each loader with its own range
> Adding new helper for faster data population in tests that require some data.

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_gce.py
added wrapper method to use the same code for all node types
> setup nodes: handle exceptions and stop the test in case it failed

- sdcm/tester.py
Currently we always upload a snapshot url to ES, sometimes the snapshot
isn't successfully uploaded, the url is invalid.
Fixes #470
> only report snapshot url to ES when snapshot is uploaded

- sdcm/cluster.py
> fixing replace address in scylla yaml generation

- build_cluster_test.py
- multiple_dc_test.py
- sdcm/cluster.py
- sdcm/nemesis.py
> added start/stop scylla/jmx services to the BaseNode

- sdcm/cluster.py
- sdcm/tester.py
- sdcm/utils.py
> Fixes and improvements

- longevity_test.py
- performance_regression_test.py
- sdcm/cluster.py
- sdcm/db_stats.py
- sdcm/nemesis.py
- sdcm/tester.py
1. isolate test statistics logic from tester
2. performance regression: distinguish latency tests by sub_type
> isolate test statistics logic from tester

- longevity_test.py
- tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- tests/longevity-1TB-7days.yaml
This will make sure that all data was actually written to all nodes while no nemesis run in the background.
> Longevity 1TB enhance

- sdcm/remote.py
> Fixing close method of remote object

- sdcm/cluster.py
- sdcm/nemesis.py
> Node replace aws fix

- sdcm/cluster.py
- sdcm/tester.py
since it exactly duplicates UserRemoteCredentials class
cc: @roydahan @larisau
> Removed GCECredentials class 

- docker/scylla-sct/Dockerfile
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_baremetal.py
- sdcm/cluster_gce.py
- sdcm/cluster_libvirt.py
- sdcm/cluster_openstack.py
- sdcm/docker.py
- sdcm/nemesis.py
- sdcm/tester.py
- sdcm/utils.py
replaced old grafana manual installation by Scylla Grafana Monitoring
@roydahan 
@larisau Since there are a lot of changes let's review together
> Scylla grafana monitoring

- sdcm/microbenchmarking.py
- sdcm/results_analyze.py
- sdcm/results_microbenchmark.html
- sdcm/send_email.py
> Micro benchmarking fixes and improvements

- sdcm/cluster.py
- sdcm/cluster_aws.py
update /ets/sysconfig/scylla-server file.
TODO:
- update existing scylla arg
> config_setup: support to append scylla args

- tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- tests/longevity-1TB-7days.yaml
- tests/longevity-50GB-4days-authorization-and-tls-ssl.yaml
- tests/longevity-50GB-4days.yaml
adds append_scylla_args: '--blocked-reactor-notify-ms 1000' to all longevity
> adds append_scylla_args: '--blocked-reactor-notify-ms 1000' to all longevity

- performance_regression_test.py
- sdcm/tester.py
- tests/perf-regression-mv.100threads.30M-keys-i3.yaml
Change aws subnet and security-group; 
New yaml for performance regression test with MV;
Add assertion message; 
tester.rows_to_list function as staticmethod
> Fixes for mv performance tests

- sdcm/cluster.py
- sdcm/cluster_aws.py
- snitch_test.py
- tests/google-cloud-snitch.yaml
Fixed the seeds setup of multiple datacenters, and add a new test for GoogleCloudSnitch
> add GoogleCloudSnitch test

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/utils.py
> Wait node bootstrap

- sdcm/nemesis.py
New nemesis that restart the node.
> Add new nemesis RestartNodeMonkey

- data_dir/scylla-dash-per-server-nemesis.2.3.json
This PR should be backported to branch-2.3
> add scylla-dash-per-server-nemesis.2.3.json

- tests/dns-cluster-5min.yaml
- tests/rolling-upgrade-gce.yaml
>  destroy instances after rolling upgrade test

- sdcm/cluster.py
- sdcm/cluster_aws.py
changes replace_address to replace_address_first_boot and removes unnecessary clean
> changes replace_address to replace_address_first_boot and removes unnecessary clean

- data_dir/sct_log_formatter
- requirements-python.txt
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/collectd.py
- sdcm/db_stats.py
- sdcm/utils.py
Currently we only support to use centos AMI/gce instance/other backends, we want to test upgrade of other distros (ubuntu14.04/ubuntu16.04/debian8/...).
This PR added support of multi distros in BaseNode, and BaseScyllaCluster, let's try to wrapper distro gaps insider those two class.
Welcome your comments, thanks!
> support multiple distros in SCT

- sdcm/nemesis.py
Need to backport to branch-3.0 and branch-perf-v3.
> fix typo in reboot nemesis

- data_dir/c-s_profile_2mv_2queries.yaml
- data_dir/c-s_profile_2si_2queries.yaml
- data_dir/c-s_profile_3si_5queries.yaml
- data_dir/c-s_profile_4mv_5queries.yaml
- longevity_test.py
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/nemesis.py
- tests/longevity-mv-si-2days.yaml
Few changes:
1. added 4 new user profiles for MV&SI test
2. added new MV&SI test yaml
3. change test_custom_time so that it can run a few commands in the prepare sector and it may be user profiles
4. fix nemesis - able to fetch test keyspaces from the DB and perform actions on keyspaces, that different from "keyspace1"
>  Longevity test for MV and SI

- sdcm/cluster_gce.py
We will safely retry if destroy instance fails. Sometimes, the request is
timeout but the instance is already destroyed. We will touch error 'not found'
in destroying the instance again.
Fixes #673
> gce: skip destroy if instance doesn't exist

- data_dir/c-s_profile_2si_2queries.yaml
- data_dir/c-s_profile_3si_5queries.yaml
Create index with 'IS NOT EXISTS' option to prevent failure on creation
> Create index with 'IS NOT EXISTS' option to prevent failure on creation

- sdcm/cluster.py
> sdcm/cluster: verify RAID setup after scylla_setup

- sdcm/nemesis.py
Need to backport to all branches
> fixing the values for modify_table options

- sdcm/cluster_aws.py
- sdcm/cluster_gce.py
- sdcm/nemesis.py
- sdcm/utils.py
- tests/sample.yaml
1. Some trivial fix of restart nemesis was lost in last PR.
2. fix download permission issue in refresh nemesis by adding user_agent (Fixes #689)
3. ignore cmd error in soft reboot
> fix problem in refresh / restart / soft reboot Nemesis

- sdcm/db_stats.py
- sdcm/es.py
- sdcm/microbenchmarking.py
- sdcm/results_analyze.py
- sdcm/results_performance.html
- sdcm/tester.py
Es module was also improved. 
Tested on http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-perf-regression-latency-temp-roy/label=aws-scylla-qa-builder4,sub_test=test_latency_temp/23/console
Example:
> Promethteus latency stats

- mgmt_cli_test.py
- sdcm/cluster.py
- sdcm/mgmt.py
- sdcm/nemesis.py
- tests/longevity-48h-verify-multiDC.yaml
- tests/manager-regression-multiDC.yaml
> Refactor Manager code and add support for CLI

- sdcm/cluster.py
> don't check deb distro when distro is confirmed to be CentOS/RHEL

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/ec2_client.py
- sdcm/tester.py
- tests/sample.yaml
Also removed redundant AWS instances handling code
cc: @yarongilor
> Monitor root disk name

- sdcm/microbenchmarking.py
- sdcm/results_base.html
- sdcm/results_microbenchmark.html
- Adding new metrics: mad f/s, max f/s, min f/s
- change view of tables to display new non-regression metrics
- change view of tables to display new data for last and
best commits: Value, Commit id, Commit date
- reverse sign for Best and Last diffs
- fix only diff marked with colors.
> Microbenchmark improvements with new metrics, view, data

- sdcm/cluster_aws.py
checking if the target node is spot instance, if it's spot we can't run restart
> don't run restart nemesis on spot instances

- sdcm/cluster_gce.py
Adding new parameter gce_job_timeout to config yaml,
which allow to control timeout gce job when create disk with
size larger than 80GB
> Fix GCE: Timeout to create instance (120G disk)

- sdcm/cluster_aws.py
If Spot instance terminamted by aws, then add to node
journalctl log files message when node will be terminated
> Add spot termination notification

- sdcm/microbenchmarking.py
- sdcm/results_microbenchmark.html
fix parsing new directory structure with datasets.
> Add processing of datasets in microbenchmarking results directory

- tests/aws-grow-cluster-200nodes.yaml
(cherry picked from commit 448646c5a5f1568c5d8bbb32f6fd73901fa40709)
> Fixing scale test yaml

- sdcm/cluster.py
- sdcm/utils.py
- upgrade_test.py
The patchset added verify for scylla repo content, currently we don't know if it downloaded the right & valid scylla repo. And added many retry for yum commands to avoid network problem.
> try to fix yum fail which crashes the whole job

- sdcm/microbenchmarking.py
check if results are empty, after get_results, exit with status code 1
> Fix output of microbenchmark if results are empty

- sdcm/nemesis.py
Adding new nemesis class, which perform actions:
- create snapshot
- list snapshot
- clear snapshot
> Adding nemesis Snapshot list operations

- sdcm/mgmt.py
this workaround fix should resolve: 
sctool task progress fails #856
> Excluded 'TaskStatus.STARTING' from task progress check

- sdcm/tester.py
Zip and save job.log file to s3 bucket
> Save job.log to s3 bucket

- longevity_test.py
- sdcm/cluster.py
- sdcm/tester.py
- tests/sample.yaml
Adding new thread which is run periodically with command
cqlsh -e 'select count(*) from ks.cf'
> Add fullscan to longevity test

- sdcm/microbenchmarking.py
if testset contains more than one dataset, raise exception
> Raise exception if testset contains more datasets

- sdcm/microbenchmarking.py
- sdcm/results_microbenchmark.html
Adding ability to display metrics improvements,
if it is greater than 50 %
> Display metrics improvements over 10%

- sdcm/cluster.py
- tests/manager-regression-multiDC-set-distro.yaml
- tests/sample.yaml
Change monitor branch to 'branch-2.1' to be used as default. and also in Scylla-Manager yaml file.
> Change monitor branch to 'branch-2.1'

- sdcm/microbenchmarking.py
- sdcm/results_microbenchmark.html
before run check regression, find provided test results by test run or
test id, and mark them as excluded and not use in compare for Best and Last
> Exclude test results by test_id or testrun_id

- sdcm/microbenchmarking.py
Check regression is running for test results with
versions.scylla-server.run_date_time > 2019-01-01
> And start date for mbm results analyzing

- sdcm/cluster.py
- sdcm/nemesis.py
Resharding nemesis:
1. Stop the node
2. change murmur3_partitioner_ignore_msb_bits to 15 (default is 12)
3. mark the last log line
4. start the node
5. wait the resharding is completed (by log message)
6. wait 5 minutes
7. set back the murmur3_partitioner_ignore_msb_bits to default value (12)
> Add resharding nemesis

- sdcm/nemesis.py
$ curl http://127.0.0.1:10000/stream_manager/stream_manager/
{"message": "Not found", "code": 404}
$ curl http://127.0.0.1:10000/stream_manager/
[]
> nemesis: fix API url of stream manager

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/db_stats.py
- sdcm/tester.py
- adding checks for console_output and console screenshot
- adding checks for exception upon creating archive
- adding checks for exists dest directories upon creating archive
> Don't fail tests if create archive raise exception

- README.rst
- utils/fetch_and_decode_stalls_from_job_database_logs.sh
- utils/fetch_and_decode_stalls_from_journalctl_logs_all_nodes.sh
- utils/fetch_and_decode_stalls_from_one_journalctl_log.sh
These scripts search in the job log or journalctl logs all stalles, find unique stalles and decode them
> Fetch and decode reactor stalls from job database logs or journalctl logs

- sdcm/cluster_aws.py
- sdcm/ec2_client.py
- sdcm/sct_config.py
This should address #825, but still more issues
> fix spot fleet tags, on fallback to on-demand

- sdcm/tester.py
Change stress* methods to use  get_duration method to set timeout
> Test duration set in one place

- sdcm/ec2_client.py
Reverts scylladb/scylla-cluster-tests#832
> Revert "Fix ec2_client _get_spot_price: search for substring 'Linux/UNIX' instead of equal"

- sdcm/cluster.py
If node is down by nemesis, fullscan could though exception
that node is not reachable. Check that node is up.
> Adding check that dbnode is up for fullscan

- sct.py
- sdcm/cluster_aws.py
- sdcm/utils.py
> AWS reuse_cluster by test_id tag, and not via ip addresses

- sdcm/cluster.py
- sdcm/db_stats.py
- adding method for gather scylla manager log
- refactor gathering and storing db_nodes and monitoring nodes additional data
> gather and store logs for scylla manager

- sdcm/cluster.py
Collect logs of scylla monitoring docker containers
on monitors node
> Collect scylla monitoring stack logs

- sdcm/microbenchmarking.py
- sdcm/results_microbenchmark.html
> Removing Job URL from Microbencmarking

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_libvirt.py
- sdcm/cluster_openstack.py
* Remove as much of the defaulting to seed as node[0]
* move to using node.ip_address(), which is automaticlly selecting public/private ips (based on config or if it's multi-region setup)
> Fix node.is_seed logic

- sct.py
- sdcm/results_analyze.py
example: 
```
hydra perf-regression-report -e bentsi@scylladb.com,roy@scylladb.com -i 20190326-172840-533804
```
> Added perf_regression_report hydra command

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/nemesis.py
- sdcm/tester.py
we tangled the IP_SSH_CONNECTIONS into the node.ip_address,
this cause too much complexity, and confusion all around.
This PR is trying to make it separated.
tested it also GCE (with on region)
> Clear the logic around ip_address

- performance_regression_in_memory_test.py
- sdcm/cluster.py
- sdcm/docker.py
- sdcm/mgmt.py
- sdcm/nemesis.py
- sdcm/remote.py
- sdcm/sct_config.py
- sdcm/tester.py
- tests/sample.yaml
remove process.run and process.CmdError
> Remove the avocado.utils.process from code

- sct.py
- sdcm/cluster.py
- sdcm/db_stats.py
- sdcm/tester.py
- sdcm/utils.py
Adding sct.py investigate groups of commands
- list all logs stored in s3 bucket by test_id
- list link to prometheus snapshot by test_id
> Sct investigate

- data_dir/share_snapshot.js
- sdcm/cluster.py
- sdcm/db_stats.py
- sdcm/remote.py
- sdcm/results_analyze.py
- sdcm/results_performance.html
Save and store on external service interactive grafana snapshots
> Add shared snapshots for grafana

- sdcm/results_analyze.py
- sdcm/results_performance.html
- Support new grafana snapshots
- Support results with empty or one link to grafana snapshot
> Fix some issue for performance regression compare results

- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
- test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
- tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- tests/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
- tests/longevity-50GB-4days-authorization-and-tls-ssl.yaml
- tests/rolling-upgrade-gce.yaml
- tests/sample.yaml
The default RF of system_auth is 1, we might restart nodes during testing.
> change default RF of system_auth to 3

- big_cluster_test.py
- query_limits_test.py
- reduce_cluster_test.py
- sdcm/tester.py
teardown_on_exception is calling tearDown(),
this new decortor should only be used on setUp() functions
> Replace @clean_resources_on_exception with @teardown_on_excetion 

- test-cases/longevity/longevity-100gb-4h.yaml
* it will:
* run for 4 hours
* write 100 GB
* create instances type i3.2xlarge
> Added new longevity test

- defaults/test_default.yaml
- sdcm/cluster.py
Need to backport only 31b2103 to branch-2019.1
> Monitor b2.3

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/sct_events.py
> Split DisruptionEvent into 2, start/end

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/sct_config.py
- test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
- test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
- tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- tests/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
- tests/longevity-50GB-4days-authorization-and-tls-ssl.yaml
- tests/rolling-upgrade-gce.yaml
We want to test Authorization and Authentication together.
> support and enable Authorization in upgrade and some longevity jobs

- data_dir/scylla-dash-per-server-nemesis.2.3.json
- data_dir/scylla-dash-per-server-nemesis.2018.1.json
- data_dir/scylla-dash-per-server-nemesis.2019.1.json
- data_dir/scylla-dash-per-server-nemesis.3.0.json
- data_dir/scylla-dash-per-server-nemesis.master.json
- sdcm/cluster.py
- sdcm/db_stats.py
- sdcm/sct_events.py
- sdcm/utils.py
New dashboard and grafana annotations based on SCT Events information
Annotations are backed in annotations.json file in S3, so we later can put them into grafana when needed:
```bash
./sct.py investigate show-logs b244db2a-346e-424c-8373-c50c3730fe2e
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                Log links for testrun with test id b244db2a-346e-424c-8373-c50c3730fe2e                                                |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| Log type    | Link …
```
>  Sct Events: Prometheus/Grafana Dumper

- docker/env/hydra.sh
- sct.py
- sdcm/cluster.py
- sdcm/tester.py
- sdcm/utils.py
- download snapshot and monitoring stack from S3
- start monitoring stack containers
- return link
> Restore monitoring stack

- sdcm/nemesis.py
> Filtering expected stream error events during abort repair Nemesis

- gemini_test.py
- sdcm/cluster.py
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/gemini/gemini-basic-3h.yaml
- tests/gemini_test.yaml
- integrate json format parse for result output file
> Gemini integration

- gemini_test.py
- sdcm/db_stats.py
- sdcm/results_base.html
- sdcm/results_gemini.html
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/gemini/gemini-basic-3h.yaml
- tests/gemini_test.yaml
- new html template for result mail
- store results of gemini run in elastic
> Add functionlity for gemini result report

- sdcm/tester.py
thanks to @yarongilor for pinpointing this issue.
> Fix Setup.set_multi_region() wasn't called in old configuration

- sdcm/cluster.py
- sdcm/nemesis.py
Tested using staging jobs for MV and not MV longevity.
Passed
> Select not-system keyspace and table for ModifyTable nemesis

- sdcm/cluster.py
- sdcm/utils.py
If gemini_version parameter contains the 'latest' word,
the sct will download lateset version of gemini.
> Adding processing the latest version

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/tester.py
> Improve the nemesis termination

- sdcm/cluster.py
- sdcm/sct_config.py
- test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
- test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
- tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
- tests/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
- tests/longevity-50GB-4days-authorization-and-tls-ssl.yaml
- tests/rolling-upgrade-gce.yaml
- upgrade_test.py
- add comment for commented code in PR #944
- fix authorizer parameter in longevity/upgrade
- reduce test time of sstabledump verify
> additional fix for upgrade_test

- longevity_test.py
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml
- tests/longevity-encryption-at-rest-200GB-6h.yaml
- enable encryption at-rest in longevity test
- add a new nemesis to enable/disable encryption
> add tests of Encryption at-rest

- defaults/gce_config.yaml
- docs/new-test-configuration.md
- sdcm/cluster.py
- sdcm/sct_config.py
- sdcm/utils.py
- test-cases/features/corrupt-then-rebuild.yaml
- test-cases/features/destroy-data-then-repair.yaml
- test-cases/features/dns-cluster-5min.yaml
- test-cases/features/enospc-30mins.yaml
- test-cases/features/gce-multiple-dc-shutdown-30mins.yaml
- test-cases/features/google-cloud-snitch.yaml
- test-cases/features/hinted-handoff.yaml
- test-cases/features/janus-graph.yaml
- test-cases/features/refresh-30mins-100mb.yaml
- test-cases/features/refresh-30mins-120gb.yaml
- test-cases/features/repair-240mins-100G.yaml
- test-cases/manager/manager-regression-multiDC-set-distro.yaml
- test-cases/performance/perf-regression-2mv.yaml
- test-cases/performance/perf-regression-latency-1TB.yaml
- test-cases/performance/perf-regression-latency-500gb-30min.yaml
- test-cases/performance/perf-regression-latency-in-memory.yaml
- test-cases/performance/perf-regression-user-profiles.yaml
- test-cases/performance/perf-regression.100threads.30M-keys.yaml
- test-cases/upgrades/rolling-upgrade.yaml
- unit_tests/test_config.py
@aleksbykov @yarongilor @amoskong @ShlomiBalalis @fgelcer 
Please take a look at test-case you were involved in, to review we didn't dropped anything important.
I've only run `test-cases/manager/manager-regression-multiDC-set-distro.yaml` and it passed provision, and manager installation (failed on non related issue #919)  
while doing so fixes some issues with the new config using multi-region setups
@roydahan, I think we should sit down 1:1 on this like we did last time.
> Port the last test cases into the /test-cases

- sdcm/cluster.py
> Installing Gemini tool anyway

- .github/pull_request_template.md
> Update PR pre-checks

- Jenkinsfile
- jenkins-pipelines/features-janusgraph-integration.jenkinsfile
- jenkins-pipelines/perf-regression-latency-30min.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-30min.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
- sdcm/sct_config.py
- sdcm/sct_events.py
- test-cases/features/corrupt-then-rebuild.yaml
- test-cases/features/destroy-data-then-repair.yaml
- test-cases/features/repair-240mins-100G.yaml
- vars/longevityPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
- vars/rollingUpgradePipeline.groovy
* Added option to check aws_region for longevity
* Fix the rolling upgrades scm checkout
> Fixes to jenkins pipeline

- sdcm/microbenchmarking.py
- sdcm/results_microbenchmark.html
> Replace tracking of aio with avg aio

- sdcm/microbenchmarking.py
- sdcm/results_base.html
- sdcm/results_microbenchmark.html
> Fix regression results for case with missing avg aio

- vars/rollingUpgradePipeline.groovy
> Fix bash escaping in rollingUpgradePipeline.groovy

- Jenkinsfile
> Fix PR configuration check in Jenkinsfile

- sdcm/cluster.py
> Fix the debug output of gemini version which cause Exception

- sdcm/cluster.py
> Fix `append_scylla_args` to support debian/ubuntu

- jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
- upgrade_test.py
- vars/rollingUpgradePipeline.groovy
- vars/supportedUpgradeFromVersions.groovy
> Add `nodetool upgradesstables` to upgrade_test.py

- sdcm/microbenchmarking.py
> Fix empty list for best results searching in max/min function

- sdcm/nemesis.py
- add new flag to mark nemesis which could be run with gemini tool
- refactor the dynamic build of list by flag
> Adding dynamic gemini nemesis list build

- defaults/aws_config.yaml
- sdcm/cluster.py
- sdcm/sct_config.py
- sdcm/tester.py
- Fix issues with update_db_packages
- Support root_disk_size as a parameter for db node
- Increasing default root disk size for db node to 15GB
> Update db packages

- gemini_test.py
- sdcm/results_analyze.py
- sdcm/results_gemini.html
Print errors subsection and only 10 error messages if the
gemini result contain error.
> Add to report only errors messages

- Jenkinsfile
- jenkins-pipelines/longevity-in-memory-36gb-4d.jenkinsfile
- test-cases/longevity/longevity-in-memory-36GB-4days.yaml
> Adding jenkins pipeline for in memory longevity

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/tester.py
> Make sure all thread are being stop and set as daemons

- defaults/test_default.yaml
- sdcm/cluster.py
Not sure why we have 2 defaults but changes them both.
> change default monitor branch to 2.4

- sdcm/cluster.py
- sdcm/cluster_aws.py
> Make sure debuginfo is installed

- sdcm/cluster.py
> Run in thread and log into job.log scylla-manager log

- jenkins-pipelines/longevity-10gb-3h.jenkinsfile
> Enlarge the 3h longevity pipeline timeout

- sdcm/sct_events.py
- sdcm/tester.py
> Handle failure in annotate to grafana (Fixes #960)

- sdcm/cluster.py
> Fix unicode handling in saving annotation to file (fixes #971)

- sdcm/cluster.py
- unit_tests/test_cluster.py
- unit_tests/test_data/database.log
- upgrade_test.py
> Fix upgrade_test `node.search_database_log()`

- sdcm/nemesis.py
> Remove duplicate code for GeminiChaosMonkey

- sdcm/cluster.py
- sdcm/nemesis.py
> Fixing FullScanThread

- refresh_test.py
- sdcm/fill_db_data.py
> Remove a few more Avocado leftovers

- sdcm/cluster.py
> Fail gracefully in  when loader is missing

- test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
> Fix longevity 200gb to not run nemesis on prepare

- jenkins-pipelines/longevity-mv-si-4days.jenkinsfile
> Fix copy'n'paste in longevity mv-si-4day pipeline

- sdcm/cluster.py
- sdcm/tester.py
> Fix scylla-bench runs

- Jenkinsfile
> Fix Jenkinsfile to work on a branches

- sdcm/cluster.py
> Adding database.log file to archive on S3

- sdcm/cluster.py
- sdcm/cluster_aws.py
> Make sure the correct debuginfo is installed

- test-cases/longevity/longevity-100gb-4h.yaml
- test-cases/longevity/longevity-10gb-3h.yaml
* https://github.com/scylladb/scylla-cluster-tests/issues/1112
> removing as a temporary workaround

- jenkins-pipelines/longevity-200gb-48h.jenkinsfile
> Enlarge timeout in `jenkins-pipelines/longevity-200gb-48h.jenkinsfile`

- sdcm/cluster.py
- sdcm/sct_events.py
> Add error processing of FullScan exception

- refresh_test.py
- sdcm/cluster.py
- sdcm/db_stats.py
- sdcm/tester.py
> Fix a few place that was using public address by default

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/sct_events.py
- unit_tests/test_events.py
> Filter db failure events in aws restart on i3/i2

- jenkins-pipelines/scylla-cloud-longevity-10gb-3h.jenkinsfile
- jenkins-pipelines/scylla-cloud-longevity-200gb-48h.jenkinsfile
- mgmt_cli_test.py
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/nemesis.py
- sdcm/sct_config.py
- sdcm/tester.py
- vars/scyllaCloudLongevityPipeline.groovy
> Add Scylla Cloud base longevity pipelines

- Jenkinsfile
- test-cases/PR-provision-test.yaml
> Adding a provision test for PRs

- sdcm/cluster_aws.py
> Change spot_termination notification period after aws termination time

- defaults/test_default.yaml
> Changed scylla-manager default version to 1.4 (+2019.1)

- README.rst
- sdcm/cluster.py
- sdcm/utils.py
> Rename monitoring repo to `scylla-monitoring`

- sdcm/nemesis.py
> Adding new Nemesis - TopPartitions

- data_dir/scylla-dash-per-server-nemesis.3.1.json
- data_dir/scylla-dash-per-server-nemesis.master.json
- gemini_test.py
- sdcm/cluster.py
> Gemini prometheus metricsv2

- sdcm/cluster.py
> Fix issue #1096 check that node dababase log file is exists

- sdcm/cluster.py
> Fxing _resharding_status method

- sdcm/cluster_aws.py
> Catching exceptions during self.wait_ssh_up in spot termination thread

- sdcm/nemesis.py
> Fixing new_node.running_nemesis when exception happens

- sdcm/sct_events.py
- unit_tests/test_events.py
> New options to filter SctEvents by node

- data_dir/share_snapshot.js
- sdcm/cluster.py
Cherry-pick 2 commits from master to support new grafana interfaces
c0ffb808a31ad015faa31a7ccb7dd178906468cc
ed13d5673f070fb61210790ac32f8274ca0d6dc0
fast fix for creating full screenshot.
> Fix creating snapshots and screenshots

- sdcm/cluster.py
This reverts commit 810c5bb5d04425c8c18718cc9e4e51eb61b26a8e.
The commit caused a regression in branch-2019.1. In all upgrade test,
verify_db_data of fill_db_data after upgrade would stuck in executing
`nodetool flush` by SSH.
The commit didn't solve issue #1121 as we expected, and we had fix it by other
PR #1122, which had been backported to branch-2019.1
> Revert "Change `db_log_reader_thread()` and backtrace_thread()` to wait better"

- sdcm/cluster.py
Currently we calculate the files number and assign it in split cmdline by `-n`,
we can just assign file size limit in split cmdline by `-b` without calculation.
- ~[ ] New configuration option are added and documented (in `sdcm/sct_config.py`)~
- ~[ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~
- ~[ ] All new and existing unit tests passed (`hydra unit-tests`)~
- ~[ ] I have updated the Readme/doc folder accordingly (if needed)~
> _try_split_coredump: assign file size limit in split cmdline

- data_dir/scylla-dash-per-server-nemesis.2018.1.json
- data_dir/scylla-dash-per-server-nemesis.2019.1.json
- data_dir/scylla-dash-per-server-nemesis.3.0.json
- data_dir/scylla-dash-per-server-nemesis.3.1.json
- data_dir/scylla-dash-per-server-nemesis.master.json
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/nemesis.py
- sdcm/sct_events.py
- snitch_test.py
- test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
- upgrade_test.py
> Recreate 'Node properties are null in system.peers in some cases (issue #4652)'

- defaults/aws_config.yaml
- jenkins-pipelines/longevity-counters-4days-multidc.jenkinsfile
- sdcm/cluster.py
- sdcm/sct_config.py
- test-cases/longevity/longevity-counters-4days-multidc.yaml
- vars/getJenkinsLabels.groovy
- vars/longevityPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
> Add longevity-counters-4days-multidc.yaml to `/test-cases`

- sdcm/nemesis.py
> Fix  Exception KeyError for Toppartition nemesis

- defaults/test_default.yaml
- docker/env/hydra.sh
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_gce.py
- sdcm/rsyslog_daemon.py
- sdcm/sct_config.py
- sdcm/tester.py
- sdcm/utils.py
- unit_tests/test_cluster.py
(cherry picked from commit 3bbd01a1b5238a9760fbf071fcb68b98806d1fff)
> Start rsyslog in background to bring logs

- sdcm/tester.py
Switch to use the zipfile module, which allow to use the ZIP64
mode to archive large files.
> Fix issue #1151 Add large sct.log(more than 4GB) to zip archive

- README.rst
- sdcm/cluster.py
~~- [ ] All new and existing unit tests passed (`hydra unit-tests`)~~
> Fixed the name of the monitoring repo

- sdcm/cluster.py
As we told with Bentsi, we don't need the info when the validation started and ended. Report when validation failed and that it was done
> Change ClusterHealthValidatorEvent using

- sdcm/utils/common.py
> fix clean_instances_aws() to actully terminate instances

- sdcm/cluster_aws.py
> Fixing reuse cluster following changes to list_instances_aws

- docker/env/hydra.sh
> Fix hydra grep for docker images

- gemini_test.py
- sdcm/cluster.py
- sdcm/gemini_thread.py
- sdcm/sct_events.py
- sdcm/tester.py
Refactor gemini thread code to use
- New class GeminiToolThread for run, verify gemini tool
- Use ThreadPoolExecutor to run gemini command
- remove some methods from BaseLoaderSet for gemini
- Adding new GeminiToolEvent to SctEvents
> Adding GeminiToolThread and same way as c-s stress is running

- sdcm/gemini_thread.py
> Fix import from utils.common

- docker/env/hydra.sh
- sdcm/cluster.py
- sdcm/remote.py
> Email user runbyuser

- sdcm/tester.py
> Add print to log on test failures [fix #1181]

- gemini_test.py
- jenkins-pipelines/gemini-3h-nondisruptive-nemesis.jenkinsfile
- test-cases/gemini/gemini-1tb-10h.yaml
- test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h.yaml
- updated old gemini tests and pipelines with latest gemini settings
- added new gemini pipeline to run gemini with nemesis
> Adding new pipeline and tests to run gemini with nemesis

- vars/scyllaCloudLongevityPipeline.groovy
> Send mail to siren team on failure of scylla-cloud run

- sdcm/cluster.py
- sdcm/tester.py
- ~[ ] New configuration option are added and documented (in `sdcm/sct_config.py`)~
- ~[ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~
- ~[ ] All new and existing unit tests passed (`hydra unit-tests`)~
- ~[ ] I have updated the Readme/doc folder accordingly (if needed)~
> cqlsh: add cql_auth support for rest cqlsh commands

- README.rst
- sdcm/cluster.py
changed the command to upgrade db packages to print its output and added doc on how to use this setting to our README.rst
> Fix upgrade db node print output

- sdcm/cluster.py
- sdcm/sct_events.py
> Improve cluster health check

- longevity_test.py
- sdcm/stress_thread.py
Moving this logic out of longevity_test.py, since more tests needs it
> Added automatic copy c-s user profile to run_stress_thread

- jenkins-pipelines/features-sla-read-throughput-1to5-ratio.jenkinsfile
- jenkins-pipelines/features-sla-read-throughput-vs-latency-cache-and-disk.jenkinsfile
- jenkins-pipelines/features-sla-read-throughput-vs-latency-cache-only.jenkinsfile
- jenkins-pipelines/features-sla-read-throughput-vs-latency-disk-only.jenkinsfile
- sdcm/cluster.py
- sdcm/db_stats.py
- sdcm/tester.py
- sla_per_user_system_test.py
- test-cases/features/system-sla-test.yaml
- test_lib/sla.py
Test flow:
- prefill cluster with 200M rows
- start first test: run load with 2 users with SLA ratio 1:5
- start second test: run 2 loads: 
- user with less preferred SLA run load with high latency
- user with preferred SLA run load with high throughput
Next tests will continue this flow
> Two system tests for feature 'SLA per user'

- unit_tests/test_events.py
- upgrade_test.py
> Filter schema failure known issues in upgrade_test

- sdcm/cluster.py
> Prevent failure in case selected logs_transport ssh

- Jenkinsfile
- utils/lint_test_cases.sh
the output was too much in CI,
and there wasn't easy way to run localy, now there is.
> Refactor the test case linting into it's own bash script

- jenkins-pipelines/scylla-cloud-longevity-200gb-48h.jenkinsfile
increased to 48h(test) + 3h(teardown)
> Increase cloud longevity pipeline timeout

- sct.py
- sdcm/utils/cloud_monitor/__init__.py
- sdcm/utils/cloud_monitor/cloud_monitor.py
- sdcm/utils/cloud_monitor/report.py
- sdcm/utils/cloud_monitor/templates/base.html
- sdcm/utils/cloud_monitor/templates/cloud_resources.html
- sdcm/utils/cloud_monitor/templates/per_user.html
- sdcm/utils/cloud_monitor/templates/per_user_summary.html
- sdcm/utils/common.py
> Implemented Cloud Monitor

- sdcm/nemesis.py
> Increased truncate nemesis timoeout

- sdcm/cluster.py
- sdcm/cluster_aws.py
* added a command to increase the ulimit to 500k open files
* moved the MaxSessions setting to all transports
it is a minor change, and i'm testing it right now.
> changed get_startup_script to run also on SSH

- sdcm/cluster.py
removed a slash after adding a line into a limits file.
> Fixed a type on startup script cluster.py

- sdcm/cluster_aws.py
- sdcm/cluster_baremetal.py
> Fix NodeType for AWS

- janus_graph_test.py
added flags to run Janus graph test with debug printouts
> Added debug flags to Janus Graph test

- sdcm/cluster.py
- sdcm/nemesis.py
Modify table nemesis failed because of bugs in the get_non_system_ks_cf_list function.
We need to merge it ASAP
> Fix get_non_system_ks_cf_list function

- sdcm/cluster.py
3.0 upgrade tests aren't stable, most of issues occurred during setup stage.
Fixed https://github.com/scylladb/scylla-cluster-tests/issues/1244
> GCE: fix yum error and report_uuid issue in setup stage

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/tester.py
- sdcm/utils/common.py
- unit_tests/test_get_non_system_ks_cf_list.py
> Move get_non_system_ks_cf_list function to utils/common and add unit tests

- unit_tests/test_microbenchmarking.py
tests for creating  and verifying email report use check_regression method, which get data from ES. This could cause periodically that regression or enhancement blocks for expected results could appear or disappear from html report ( which could be expected). Added new verification of html report content, based on has_diff and has_improve flags
> Fix unit-tests for microbenchmarking

- sdcm/cluster.py
> backport PR #1245 (GCE fix) to branch-3.0

- defaults/test_default.yaml
- sdcm/cluster.py
and adjusted the monitor node's installtion and configuration to match the new branch
> Changed the default monitor branch to branch-3.0

- data_dir/break_scylla.sh
> Remove files for repair test: change file name template for deletition

- jenkins-pipelines/scylla-cloud-longevity-100gb-48h.jenkinsfile
- test-cases/longevity/longevity-100GB-48h-cloud-CloudLimitedChaosMonkey-tls.yaml
* as the machine being used is a i3.large
* the whole disk size is 475GB and when
* running major compaction, the data could
* increase up to 400GB, making out of space
> Lower the load on cloud longevity to 100GB

- sdcm/utils/common.py
- unit_tests/test_get_non_system_ks_cf_list.py
> If MV does not exists don't return empty result from get_non_system_ks_cf_list

- sdcm/cluster.py
- sdcm/stress_thread.py
- sdcm/tester.py
- sdcm/utils/common.py
- [] New configuration option are added and documented (in `sdcm/sct_config.py`)
> collect logs of loader

- sdcm/tester.py
- sdcm/utils/common.py
Remove copies and archive of log files
> Remove unused logs files and archives

- sdcm/cluster.py
> Print full exception instead of message in Cluster Health Check

- test-cases/longevity/longevity-multi-keyspaces.yaml
* enlarge disk for monitor to 40gb
* disable coredump on bad alloc
> Minor updates to 1000 keyspaces use case

- sdcm/cluster.py
- unit_tests/test_cluster.py
- unit_tests/test_data/database_interlace_stall.log
> Handle interlaced reactor stalls, to avoid backtrace events

- sdcm/nemesis.py
* removed dead code
* increased repair timeout
> Fixes for management repair

- test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
* expect to lower a bit the load
* it is generating too many hints issues
> Setting longevity 1tb job to use round robin

- gemini_test.py
- sdcm/gemini_thread.py
- sdcm/results_gemini.html
> Add full gemini command to email report

- test-cases/gemini/gemini-1tb-10h.yaml
- test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h.yaml
Change number of concurrent threads per table, to prevent the memory  allocation error
> Reconfigure gemini jobs

- test-cases/longevity/longevity-large-partition-4days.yaml
On large partition yaml
~~- [ ] All new and existing unit tests passed (CI)~~
> disabled abort on bad alloc flags

- sdcm/nemesis.py
> Support all file formats in CorruptThenRepiar nemesis

- sdcm/nemesis.py
> Improve the toppartittion nemesis error reporting

- gemini_test.py
- longevity_test.py
- sdcm/cluster.py
- sdcm/gemini_thread.py
- sdcm/results_analyze.py
- sdcm/results_base.html
- sdcm/results_longevity.html
- sdcm/sct_events.py
- sdcm/send_email.py
- sdcm/stress_thread.py
- sdcm/tester.py
- sdcm/utils/common.py
- Move email sending functionality to base ClusterTester class
- Refactoring email send functionality. remove the duplicate code
> Adding email reporting functionality longevity test

- jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
> disable upgrade from 2.3 to 3.1

- sdcm/tester.py
- sdcm/utils/common.py
- sdcm/utils/log.py
Also refactor log configuration into `utils.log`
> Log unhandled exceptions

- sdcm/nemesis.py
Looks like we missed anther type of error in `abort_repair`
> Add more missing filters to abort_repair nemesis

- test-cases/longevity/longevity-large-partition-4days.yaml
~~- [ ] All new and existing unit tests passed (CI)~~
> Restored default scylla_args for large partition

- gemini_test.py
- sdcm/results_gemini.html
- sdcm/send_email.py
- test-cases/gemini/gemini-1tb-10h.yaml
- test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h.yaml
- update config files for gemini tests
- fix gemini email report generating and sending
> improve gemini test config settings

- data_dir/scylla-dash-per-server-nemesis.2.1.json
- data_dir/scylla-dash-per-server-nemesis.2.2.json
- data_dir/scylla-dash-per-server-nemesis.2.3.json
- data_dir/scylla-dash-per-server-nemesis.2017.1.json
- data_dir/scylla-dash-per-server-nemesis.2018.1.json
- data_dir/scylla-dash-per-server-nemesis.2019.1.json
- data_dir/scylla-dash-per-server-nemesis.3.0.json
- data_dir/scylla-dash-per-server-nemesis.3.1.json
- data_dir/scylla-dash-per-server-nemesis.master.json
- data_dir/scylla-dash-per-server.json
- data_dir/scylla-dash-per-server.master.json
- data_dir/scylla-dash-timeout-metrics.json
- data_dir/scylla-dash.json
- data_dir/scylla-dash.master.json
~~- [ ] All new and existing unit tests passed (CI)~~
> Changed the default timezone of monitor to UTC

- sdcm/tester.py
- sdcm/utils/common.py
> Adding availability of ami-id check

- sdcm/sct_events.py
Ignoring timestamp parsing errors of events with broken timestamps
> Journal timestamp not parsed correctly by events

- README.rst
- jenkins-pipelines/byo-longevity.jenkinsfile
- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/sct_config.py
- sdcm/tester.py
- sdcm/utils/common.py
- sdcm/utils/log.py
- unit_tests/test_config.py
- unit_tests/test_utils_common.py
- upgrade_test.py
- vars/byoLongevityPipeline.groovy
> Add BYO pipeline

- sdcm/mgmt.py
HostSsl, HostStatus and HostRestStatus
> Fixed error messages of manager Enum's:

- data_dir/share_snapshot.js
> Fixed the creation of grafana livesnapshots for monitoring v3.0

- sdcm/sct_config.py
> Added support for choices in SCT config

- sdcm/tester.py
> Fixing path of SSL ceritficate

- defaults/test_default.yaml
> Setting default nemesis interval to 5min

- test-cases/gemini/gemini-1tb-10h.yaml
- test-cases/gemini/gemini-3h-with-nemesis.yaml
- test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h.yaml
> Destroy Gemini resources at the end of the test by default

- sdcm/nemesis.py
> Adding processing the empty non system ks.cf list

- defaults/test_default.yaml
- docs/configuration_options.md
- internal_test_data/unknown_param_in_config.yaml
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_libvirt.py
- sdcm/cluster_openstack.py
- sdcm/remote.py
- sdcm/sct_config.py
- sdcm/tester.py
Task description:
Need to add two parameters:
- seeds_num: X  # number of seeds nodes that should be configured in the test. Default value 1
- seeds_selector: one of the following values:
reflector - reflector will select the seed nodes for us, we update the Node 
objects "is_seed" param. 
random  - SCT will randomly select nodes that are seed
first - first "seeds_num" nodes will be configured as seed nodes. First should be default for AWS.
> Seed selection (task #1019)

- sdcm/mgmt.py
> Added log messages in sctool run for debugging

- sdcm/utils/common.py
supporting 2 modes.
if size of uploaded/download object is lager than 1GB,
then multipart upload/download mode will be used,
otherwise, upload/download will be run in single thread
> Adding to S3Storage object upload/download files with multiparts

- sdcm/cluster.py
- sdcm/tester.py
- sdcm/utils/common.py
> Seed selector: support gemini test

- vars/byoLongevityPipeline.groovy
> Add support for BYO on specific repo/branch

- sdcm/results_longevity.html
remove old header "Access log"
> Minor fix of longevity html report template

- sdcm/cluster.py
- unit_tests/test_data/scylla.yaml
- unit_tests/test_seed_selector.py
> Unit tests for seed_selector feature

- gemini_test.py
- longevity_test.py
- sdcm/results_gemini.html
- sdcm/send_email.py
- sdcm/tester.py
- sdcm/utils/common.py
- Adding sct test result to report
- Mark result in report based on gemini and sct critical events
- minor refactor of stop_resources
> Improving gemini result report

- vars/longevityPipeline.groovy
- vars/rollingUpgradePipeline.groovy
The logs can be viewed on Jenkins webpage, it supports to download of
compressed sub directory.
> archive SCT logs to jenkins server

- sdcm/cluster.py
- sdcm/cluster_aws.py
Related ticket: https://trello.com/c/IFtVEXMK/1300-problem-of-replace-nemesis-or-i3-restart
> fix of cleaning replacement node ip

- sdcm/utils/common.py
Set public read access to read s3 objects
which are loaded with new S3Object interface
> Set public read access for uploaded resources

- sct.py
- sdcm/tester.py
- vars/longevityPipeline.groovy
> Adding send email report stage

- configurations/scale-180-200.yaml
- configurations/scale-450-500.yaml
- docs/configuration_options.md
- grow_cluster_test.py
- jenkins-pipelines/features-scale-180-200-cluster-test.jenkinsfile
- jenkins-pipelines/features-scale-450-500-cluster-test.jenkinsfile
- sdcm/cluster.py
- sdcm/remote.py
- sdcm/sct_config.py
- test-cases/features/scale-cluster.yaml
> Configure scale test as a pipeline job

- upgrade_test.py
We only verify data before and after upgrade, this patch added verify during
upgrade. Each verify takes about 4 mins.
> verify data by fill_db_data.py during upgrade

- gemini_test.py
- sct.py
- sdcm/cluster.py
- sdcm/results_gemini.html
- sdcm/tester.py
> Minor fixes for gemini send email functionality and email report

- sdcm/cluster.py
- sdcm/cluster_aws.py
> Fix missing default values in #1424

- sdcm/nemesis.py
> Introduce a way to dynamically skip a nemesis

- test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
> Disabled nemesis_during_prepare in 1TB 7 days

- sdcm/logcollector.py
If some nodes during run were termintated, search in test run local
directory log files and collect them
fix issue #1404 https://github.com/scylladb/scylla-cluster-tests/issues/1404
> Adding support to search and collect data for terminated node #1404

- jenkins-pipelines/gemini-3h-nondisruptive-nemesis.jenkinsfile
- sdcm/nemesis.py
- test-cases/gemini/gemini-1tb-10h.yaml
- test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h.yaml
- update gemini command for latest version's parameters
> Update gemini files

- sdcm/utils/common.py
update builders names and ips for searching
the builder and folder by test-id
> Update builder eu-west names and ips

- sdcm/logcollector.py
> Fix collection PrometheusSnapshot upon various exception

- sdcm/cluster.py
- sdcm/tester.py
- unit_tests/test_seed_selector.py
> Seed selection in case reuse cluster

- longevity_test.py
- sdcm/cluster.py
- sdcm/results_longevity.html
- sdcm/send_email.py
> Delete ES doc-id from longevity email report

- sdcm/remote.py
During node initialization the method start_tasts_thread
start several threads which use wait_ssh_up method to monitor
the node connectivity. This periodically cause race condition
in fabric/invoke/paramiko libs to create ssh tunnel, which lead
to sct stuck.
This commit move checks of node accessablity over ssh to another
thread, and all other threads, wait while flag that node is availabe
is set.
> Fix remote connection stuck on ssh_up stage

- data_dir/scylla-dash-per-server-nemesis.3.1.json
- jenkins-pipelines/features-2mv-backpressure-4days.jenkinsfile
- test-cases/features/2mv-backpressure-4d.yaml
Changes:
1. Rename test yaml (it's feature, not longevity)
2. Rename Jenkins pipeline (it's feature, not longevity)
3. Disable HH for the Scylla (not need for backpressure test)
4. Add "nemesis_interval: 30" to the test_defaults.yaml
> MV backpressure yaml changes

- jenkins-pipelines/longevity-10gb-3h-ipv6.jenkinsfile
- longevity_test.py
- refresh_test.py
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_gce.py
- sdcm/db_stats.py
- sdcm/remote.py
- sdcm/sct_config.py
- sdcm/tester.py
- vars/longevityPipeline.groovy
> Support IPv6 by SCT

- jenkins-pipelines/longevity-5000-tables.jenkinsfile
- vars/byoLongevityPipeline.groovy
- vars/longevityPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
- vars/rollingUpgradePipeline.groovy
- vars/scyllaCloudLongevityPipeline.groovy
seem like there was a typo in the post_behavior, and some params were using post_behaviour, this mismatch caused pipeline jobs to fail to start.
> Fix pipeline post_behavior parameters

- sdcm/cluster_gce.py
- sdcm/results_performance.html
- sdcm/tester.py
- sla_per_user_system_test.py
> Python3 fixes

- test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
since c5 Are more prone to being shut down due to spot termination
> Changed loader type to c4.2xlarge in 50gb

- sdcm/utils/cloud_monitor/cloud_monitor.py
- sdcm/utils/cloud_monitor/report.py
- sdcm/utils/common.py
> Fix cloud report python3

- vars/byoLongevityPipeline.groovy
- vars/longevityPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
- vars/rollingUpgradePipeline.groovy
- vars/scyllaCloudLongevityPipeline.groovy
> Get AWS keys from Jenkins in CI

- Jenkinsfile
> Add AWS keys to Jenkinsfile

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_gce.py
> Feature: GCE add fix reuse cluster feature

- .pre-commit-config.yaml
> Adding a precommit check for AWS Credentials and Private Keys

- jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
- sdcm/cluster_gce.py
- sdcm/tester.py
Branches: master, branch-3.2
For example:
- upgrade from 3.1 to 3.2: supported
- upgrade from 3.0 to 3.2: not supported
> upgrade_test: only support to upgrade from latest release

- vars/perfRegressionParallelPipeline.groovy
- vars/rollingUpgradePipeline.groovy
seem like #1474 didn't cover correctly the parallel pipeline.
thanks for @amoskong for catching this one
> Fix aws cred to be pass down in parallel pipelines

- sdcm/cluster.py
> Added retrying to stop_scylla_server

- sdcm/logcollector.py
For branch-3.2 there is no appropriate dashboards in scylla-monitoring
repo. So sct installs the dashboards for master. This cause and error
that dashboard doesn't exists and screenshots and snapshots doesn't
collected correctly.
Fix added the check, that appropriate dashboard exists in Grafana,
and if not, use 'master' instead of scylla version for dashboard.
Also, code for geting correct screenshot resolution was changed
> Fix issue with mising dashboards for new scylla versions

- sdcm/cluster.py
- sdcm/cluster_gce.py
- sdcm/remote.py
- test-cases/PR-provision-test.yaml
- unit_tests/test_seed_selector.py
> Stabilization of GCE and remoter object

- data_dir/scylla-dash-per-server-nemesis.master.json
- sdcm/cluster.py
Switch from curl uploading to python lib requests
> Fix uploading dashboard json file

- sla_per_user_system_test.py
Trello task: https://trello.com/c/GmRmg7mc/1405-add-missed-not-backported-code-in-sla-test-to-the-branch-20191
This PR should apply the missed code for SLA tests, that wasn't backported.
Also there is one new test, that I am going to add to the master today.
> Add missed code to the branch-2019.1

- sdcm/cluster_aws.py
Was causing `self.public_address` to return None
and failing the cluster setup like that, when trying to initalize
the ssh connection:
```
File "/sct/sdcm/tester.py", line 134, in wrapper
return method(*args, **kwargs)
File "/sct/sdcm/utils/common.py", line 136, in inner
res = func(*args, **kwargs)
File "/sct/sdcm/tester.py", line 258, in setUp
self.init_resources()
File "/sct/sdcm/tester.py", line 797, in init_resources
monitor_info=monitor_info)
File "/sct/sdcm/tester.py", line 618, in get_cluster_aws
self.db_cluster = create_cluster(db_type)
File "/sct/sdcm/tester.py", line 584, in create_cluster
**cl_params)
File "/sct/sdcm/cluster_aws.py", line 780, in __init__
aws_extra_network_interface=params.get('aws_extra_network_interface'))
File …
```
> AWS: move `self._wait_public_ip()` back to before `super()`

- sdcm/cluster.py
> Move the `scylla --version` output into info level log

- sdcm/remote.py
When running remote command with emoter.run and setting  verbose=True and ignore_status=True that will now mean
that nothing will be printed in any case to log. This fixes too much logging issue with coredumpctl command
that returns error when no coredumps found, so we have got a lot of 'error' messages in the log
Task: https://trello.com/c/3bTFObwY/1197-coredumps-check-are-producing-too-much-logging-1194
> Remoter: added ability to compeltely silence the remoter

- defaults/test_default.yaml
- sdcm/cluster.py
- sdcm/sct_config.py
> Adding swap file to loader nodes during setup process #1118

- sdcm/utils/common.py
Static ip addresses are removed from code.
Now all builders will be looked by tag nodetype:builder
on aws and gce
> Search builder by tags on aws and gce

- jenkins-pipelines/scylla-cloud-longevity-100gb-48h.jenkinsfile
- jenkins-pipelines/scylla-cloud-longevity-10gb-3h.jenkinsfile
- vars/scyllaCloudLongevityPipeline.groovy
> Change scylla-cloud pipeline db nodes to i3.xlarge

- sdcm/cluster_aws.py
- sdcm/ec2_client.py
- sdcm/sct_config.py
added a new parameter to instances on AWS to use the instance profile that allows us to access the qa backup S3 buckets.
this is one of the base infrastructures to develop the backup tests
> Added to all AWS instances new instance_profile

- defaults/test_default.yaml
- jenkins-pipelines/manager-sanity.jenkinsfile
- mgmt_cli_test.py
- sdcm/cluster.py
- sdcm/mgmt.py
- sdcm/nemesis.py
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/manager/manager-regression-multiDC-set-distro.yaml
- vars/longevityPipeline.groovy
> Added manager 2.0 installation

- sdcm/cluster_aws.py
- sdcm/ec2_client.py
forgot to update the PR with my actual commit
> Checking if instance_profile is empty before call

- sdcm/mgmt.py
> Basic manager backup task infrastructure

- sdcm/cluster.py
https://trello.com/c/62PDfNPG/1396-improve-error-handling-in-coredump-background-threads
> Coredump handling

- sdcm/nemesis.py
> raise UnsupportedNemesis on non ics supported version

- mgmt_cli_test.py
- sdcm/sct_config.py
- test-cases/manager/manager-regression-multiDC-set-distro.yaml
* basic backup
* backup with multiple KS and tables
> Created first set of backup tests including

- test_lib/compaction.py
> Fixed get_compaction_strategy()

- jenkins-pipelines/gemini-1tb-10h.jenkinsfile
- jenkins-pipelines/gemini-3h-nondisruptive-nemesis.jenkinsfile
- jenkins-pipelines/gemini-3h.jenkinsfile
- test-cases/gemini/gemini-1tb-10h.yaml
- test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h.yaml
- vars/longevityPipeline.groovy
Trello: https://trello.com/c/UAT64VdY
> Fix double email message sent by gemini job

- mgmt_cli_test.py
- sdcm/cluster.py
the function will download the correct files for each node in the cluster, move them to the upload data dir and then run nodetool refresh to add the files (after running truncate in that table) to ensure the only existing data will be the one added from backed up files.
> mgmt_cli_test.py - added verify_backup_success function

- jenkins-pipelines/longevity-ics-toggle-strategy-500gb-24h.jenkinsfile
- jenkins-pipelines/longevity-in-memory-36gb-4d.jenkinsfile
- jenkins-pipelines/longevity-large-partition-4days.jenkinsfile
- longevity_ics_test.py
- longevity_in_memory_test.py
- longevity_large_partition_test.py
> Fixed a typo in the class name

- gemini_test.py
- longevity_test.py
- sdcm/results_gemini.html
- sdcm/results_longevity.html
- sdcm/send_email.py
Trello: https://trello.com/c/VjmInwoc
> Adding username to email reports

- defaults/test_default.yaml
> Move monitor latest release branch-3.1

- mgmt_cli_test.py
there are still other P0 and P1 tests from
test plan to add.
also, once the pipeline PR is merged, then
all the backup tests must be added to it.
> Added more backup tests.

- mgmt_cli_test.py
A small update in the subTest calls, to have more decription.
Added 2 new tests to the test_backup_feature that were already merged to master.
> Updated subtests with new tests + description

- test-cases/gemini/gemini-1tb-10h.yaml
- test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h.yaml
Just update for oracle cluster version for gemini version
> Update oracle cluster version for gemini jobs

- longevity_test.py
> 5000 tables, change num_of_newly_created_tables to 1

- mgmt_cli_test.py
this is an effort to make the sanity and backup feature jobs to pass, as they originally failed with this error
> Backup test add retry cmd

- configurations/2018.1/io.conf
- jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
- sdcm/cluster.py
> fix upgrade test of 2019.1.4

- data_dir/ics_c-s_profile_2mv_2queries.yaml
- data_dir/ics_c-s_profile_2si_2queries.yaml
- data_dir/ics_c-s_profile_3si_5queries.yaml
- data_dir/ics_c-s_profile_4mv_5queries.yaml
- jenkins-pipelines/ics-longevity-mv-si-4days.jenkinsfile
- test-cases/enterprise-features/ics/longevity/ics-longevity-mv-si-4days.yaml
> Added mv/si longevity configuration files for ICS

- defaults/aws_config.yaml
scylla-enterprise-tools-2019.1.4-20191218.c752b991ea.el7.noarch
scylla-enterprise-conf-2019.1.4-0.20191218.b59e92dbd.el7.x86_64
scylla-enterprise-tools-core-2019.1.4-20191218.c752b991ea.el7.noarch
> update scylla-tools packages to support ics

- sdcm/sct_config.py
> Added new param: 'compaction_strategy'

- mgmt_cli_test.py
Also added some logging to be easier to debug.
the DB errors found in log seen during sanity were caused by not filtering out from event log messages sent while updating the cluster to use encryption. During this process the repair is running and we need to restart the whole cluster to apply changes, making many error messages (that triggered critical log events), making the test to fail where there were no issues neither on scylla nor on the manager.
> Added a fix to test_client_encryption

- gemini_test.py
- longevity_test.py
- sct.py
- sdcm/results_gemini.html
- sdcm/results_longevity.html
- sdcm/send_email.py
- sdcm/tester.py
- updated templates.
- added several new functions to work with email data
- changed order of execution in tear_down. Email send action is now last.
- Fixed minor issue for clean-resources methods on tear_down
Trello: https://trello.com/c/wjvvooWW
> Adding to report information about instances left running

- sdcm/utils/common.py
> Fix #1580: setting default region for AWS client

- vars/byoLongevityPipeline.groovy
> Fix email default parameter in vars/byoLongevityPipeline.groovy

- sdcm/auto_ssh.py
- sdcm/cluster.py
- sdcm/cluster_aws.py
> Fix: set hostname for AWS + minor fixes

- vars/byoLongevityPipeline.groovy
- vars/longevityPipeline.groovy
- vars/rollingUpgradePipeline.groovy
- vars/scyllaCloudLongevityPipeline.groovy
> Adding send email stage for RollingUpgrade pipeline

- configurations/scale-180-200.yaml
- grow_cluster_test.py
- jenkins-pipelines/features-scale-180-200-cluster-test.jenkinsfile
- jenkins-pipelines/features-scale-450-500-cluster-test.jenkinsfile
1. Change test duration time for scale-180-200 test. Trello task: [1442](https://trello.com/c/g9oHmtra/1442-the-scale-test-from-180-to-200-nodes-time-should-be-changed-to-10-hours)
2. Destroy DB nodes after scale tests. Trello task: [1436](https://trello.com/c/Lc6V0aAv/1436-scale-longevity-destroy-nodes-always)
I am not sure if we need to backport to 3.1
> Changes for scale tests

- vars/byoLongevityPipeline.groovy
> Fix issues in byo pipeline

- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
> don't test upgrade from 2018.1 to 2019.1 of Ubuntu 18.04

- sdcm/cluster.py
- sdcm/utils/common.py
Trello: https://trello.com/c/coXiAWDy
Screenshots created during updata_test_details will be put to S3 with date_time
> Fix missing data_time for screenshots in update_test_details

- mgmt_cli_test.py
because we weren't waiting for the results
some backup tasks started even before the c-s
created the schema, so the only backed up
schemas were the system ones.
when running the verification, the keyspace1
wasn't in there, then the sanity was failing
after downloading the files uploaded by the
backup task.
Now the test waits for c-s results, and only
then creates a backup task.
> Added a get_results to the c-s on backup tests

- sdcm/nemesis.py
AddDropColumnMonkey
Small fix to change behavior for the case when table with no compact storage is there.
Instead of one Add/Drop column we run it in a cycle same way as it was done for other case
> AddDropColumnMonkey: Fix to add/drop columns in cycle for non-compact-storage case

- sdcm/cluster_aws.py
> Fix aws add_nodes() to handle new type ami

- vars/rollingUpgradePipeline.groovy
> Fix #1616: error handling in rolling upgrade pipeline

- test_lib/compaction.py
> Fix get_compaction_strategy()

- sdcm/fill_db_data.py
- upgrade_test.py
> avoid schema change during the upgrade and workaround list order issue

- sdcm/utils/log.py
> Remove MakeFileHandler, trying to fix #1291

- defaults/test_default.yaml
> Reverting back to monitor branch-3.0 as 3.1 has issues with screenshots

- vars/rollingUpgradePipeline.groovy
For some reason pipeline doesn't definition of email_property.
Fixed.
> Fix several minor issues in pipeline for Rolling upgrade #1634

- test-cases/features/system-sla-test.yaml
> [branch-2019.1] Change instance type and test time (missed #1491 PR)

- sdcm/cluster.py
> Fix coredump download link

- vars/byoLongevityPipeline.groovy
> Remove wrong quotes to use several config files

- defaults/test_default.yaml
- sdcm/cluster.py
- sdcm/sct_config.py
- test-cases/features/scale-cluster.yaml
- test-cases/longevity/longevity-5000-tables.yaml
> Parameter for Cluster health check disabling/enabling

- sdcm/cluster.py
https://trello.com/c/PvnbB8kt/1399-reduce-severity-for-unknown-verb-event-exception-to-error
> Reduce severity to ERROR for 'unknown verb exception'

- sdcm/cluster_aws.py
> Config IPv6 as persistent

- upgrade_test.py
1. Use subTest in order to separte the scenario into steps.
2. Allow each step to fail but continue the full scenario
3. Limit the event filtering to some specific steps.
4. changing some messges from debug to info so we can see them in Jenkins job.
> Refactor rolloing-upgrade-test

- sdcm/cluster_aws.py
> Run IPv6 persistent script for IPv6 test only

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/logcollector.py
> Add support using scylla-cloud-image

- sdcm/cluster_aws.py
> Added RUNTIME_ERROR filter to AWSNode.restart

- sdcm/cluster_aws.py
- sdcm/gemini_thread.py
- sdcm/sct_events.py
- sdcm/utils/common.py
https://trello.com/c/8aR7yLN7/1453-fix-deepcode-issues
> Fixing DeepCode issues

- sdcm/sct_events.py
- sdcm/tester.py
https://trello.com/c/XYUBBoSX/1325-write-errors-during-setup-phase-to-criticallog-file
> Produce event on exception that comes from SetUp

- sdcm/cluster_aws.py
> Fix python3 F-string code

- sdcm/send_email.py
https://trello.com/c/fIYsGEoM/1426-add-size-validation-of-email-report-attached-to-email
> Add email size validation

- sdcm/nemesis.py
- test_lib/cql_types.py
https://github.com/scylladb/scylla-cluster-tests/issues/1651
> Fix to make AddDropColumn nemesis to ignore scylla-bench tables

- sdcm/nemesis.py
https://trello.com/c/hdXhQV4q/1398-extend-and-enhance-networking-nemesis
> Extend and enhance networking nemesis

- Jenkinsfile
- sdcm/cluster_gce.py
- test-cases/PR-provision-test.yaml
- vars/pullRequestContainsLabels.groovy
- vars/pullRequestSetResult.groovy
https://trello.com/c/fqHEngaB/1375-add-gce-backend-check-to-ci
> Add test-provision-gce

- sdcm/cluster.py
- sdcm/prometheus.py
- sdcm/sct_events.py
- sdcm/tester.py
- unit_tests/test_data/test_prometheus/test_alert_manager_listener_artificial_run.yaml
- unit_tests/test_data/test_prometheus/test_alert_manager_listener_real_run.json
- unit_tests/test_prometheus.py
https://trello.com/c/he5eCLA0/1397-alert-detector-to-detect-performance-issues-and-other-things
> Alert manager listener

- defaults/test_default.yaml
> Enable backtrace decoding by default

- sdcm/prometheus.py
> Fix #1682: Removed debug printouts in PrometheusAlertManagerListener

- sdcm/cluster_aws.py
https://trello.com/c/IzL5w35I/1504-support-set-hostname-for-ubuntu-in-aws
> Fix timeout on set_hostname

- sdcm/cluster_aws.py
Fix issue with rsyslogd after hosts is ammended:
rsyslog is not picking up hostname if it is in hosts file
and continue sending messages as localhost
which makes test to fail as following:
13:11:49    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
13:11:49      do = self.iter(retry_state=retry_state)
13:11:49    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 331, in iter
13:11:49      raise retry_exc.reraise()
13:11:49    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 167, in reraise
13:11:49      raise self.last_attempt.result()
13:11:49    File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
13:11:49      return self.__get_result()
13:11:49    File …
> fix set_hostname: Add workaround to rsyslogd problem

- sdcm/cluster.py
https://trello.com/c/TSBXvZVx/1529-reduce-sererity-for-unknown-verb-to-warning
> Reduce severity unknown verb

- Jenkinsfile
- defaults/gce_config.yaml
- docs/configuration_options.md
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_gce.py
- sdcm/prometheus.py
- sdcm/sct_config.py
- sdcm/sct_events.py
- test-cases/PR-provision-test.yaml
- unit_tests/test_events.py
- unit_tests/test_prometheus.py
> Preemtible instances support + fixes to PrometheusAlertManagerListener

- sdcm/nemesis.py
https://trello.com/c/0ZJbdzAS/1519-remove-fallback-logic-for-adddropcolumnnemesis
> Remove fallback logic from AddDropColumn

- sct.py
- sdcm/results_upgrade.html
- sdcm/send_email.py
- upgrade_test.py
Adding basic email report for upgrade tests
added new template, and emailreporter
> Adding short email report for Upgrade tests

- jenkins-pipelines/perf-row-level-repair.jenkinsfile
- longevity_large_partition_test.py
- performance_regression_row_level_repair_test.py
- sdcm/cluster.py
- sdcm/db_stats.py
- sdcm/results_analyze.py
- sdcm/tester.py
- sdcm/utils/common.py
- test-cases/performance/perf-row-level-repair-1TB.yaml
- test_lib/scylla_bench_tools.py
> Added performance_regression_row_level_repair_test.py and its utils

- gemini_test.py
- longevity_test.py
- sdcm/cluster.py
- sdcm/logcollector.py
- sdcm/results_gemini.html
- sdcm/results_longevity.html
- sdcm/sct_events.py
- unit_tests/test_events.py
• now each level has it's own log
• new summary.log with counts of each level
• summery is added to the email reports
> sct_events: cleanup of log levels

- docs/configuration_options.md
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/docker.py
- sdcm/nemesis.py
- sdcm/sct_config.py
- test-cases/longevity/longevity-200GB-48h-network-monkey.yaml
https://trello.com/c/X0WFepNj/1531-refactor-the-code-to-support-additional-network-interface-for-gce
> Move aws_extra_network_interface to baseNode

- sdcm/cluster.py
- sdcm/gemini_thread.py
- sdcm/logcollector.py
Gemini result log file and console output log file collected by log collector.
Trello: https://trello.com/c/9nfNeXU3
> Adding gemini log files to logcollector

- jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
- sdcm/cluster.py
- sdcm/mgmt.py
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/longevity/longevity-2TB-4days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
- test-cases/manager/manager-regression-multiDC-set-distro.yaml
- vars/longevityPipeline.groovy
also, fixed the manager setup on those
> Added pipeline for Ubuntu 16 and 18

- jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
Scylla 3.2 had been released, let's test upgrade from 3.2 to master.
> rolling-upgrade: update base version to 3.2

- Jenkinsfile
- sdcm/cluster.py
https://trello.com/c/Inj0PK6D/1574-remove-post-step-from-provision-test
> Remove post from Jenkins file

- test-cases/manager/manager-regression-multiDC-set-distro.yaml
> Fixed Centos job

- sdcm/remote.py
https://trello.com/c/yKIK9yUc/1413-enhance-remotecmdrunner-to-make-ssh-connection-persisstent
> Move is_up into retry cycle

- data_dir/scylla-dash-per-server-nemesis.2019.1.json
- data_dir/scylla-dash-per-server-nemesis.3.1.json
- data_dir/scylla-dash-per-server-nemesis.3.2.json
- data_dir/scylla-dash-per-server-nemesis.master.json
- jenkins-pipelines/longevity-large-partition-200k-pks-4days.jenkinsfile
- longevity_test.py
- sdcm/cluster.py
- sdcm/sct_events.py
- sdcm/tester.py
- test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
- unit_tests/test_events.py
1. new ScyllaBenchEvent added (with unit test) and add it to the filter on Nemesis Dashboards
2. cause scylla-bench run with round-robin
3. new large partition flow
[Trello task](https://trello.com/c/hDVG6iGx/1305-large-partitions-workload)
> Large partition new flow

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/tester.py
Pre-commit check fails in branch-2019. [Errors](https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/branch-2019.1/127/execution/node/22/log/)
> [branch-2019.1] Fix pylint hook failures on branch-2019.1

- mgmt_cli_test.py
> Added subtest steps to manager sanity

- jenkins-pipelines/gemini-3h-ics-nondisruptive-nemesis.jenkinsfile
- jenkins-pipelines/gemini-3h-ics.jenkinsfile
- test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h-ics.yaml
https://trello.com/c/64STdX66/1537-gemini-ics?menu=filter&filter=member:yarongilor2
> Added gemini command with ics

- data_dir/scylla-dash-per-server-nemesis.2019.1.json
- jenkins-pipelines/longevity-large-partition-200k-pks-4days.jenkinsfile
- longevity_test.py
- sdcm/cluster.py
- sdcm/sct_events.py
- sdcm/tester.py
- test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
- unit_tests/test_events.py
This PR is created instead of backport of [PR 1565](https://github.com/scylladb/scylla-cluster-tests/pull/1565) by Bentsi's request
> [branch-2019.1] Large partition new flow

- sdcm/sct_events.py
- sdcm/utils/common.py
- unit_tests/test_events.py
- unit_tests/test_manual.py
https://trello.com/c/2ncoJCpK/1518-testfilterexpiration-testfilterrepair-and-testfilterupgrade-are-intermitently-failing
> Fix failing tests

- sdcm/auto_ssh.py
Docker name uses ```external_address``` as host name.
Host name is part of the container name.
When test is run with IPv6, IPv6 IP is used for container name.
IPv6 IP includes not allowed character ":". So container couldn't be created.
There are 2 cases when it happens:
1. multiDC test - fatal error. Test can't be run
2. in every test when get RemoteBrowser - test continues
Error like:
```
p:ERROR > docker: Error response from daemon: Invalid container name (awebdriver-2a05:d018:223:f00:11dc:3387:ed6:d19b-autossh), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
```
> Fix container name when run multiDC test with IPv6

- jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
- mgmt_cli_test.py
- sdcm/mgmt.py
- test-cases/manager/manager-regression-ipv6.yaml
> Changed code to support ipv6 on manager sanity

- sdcm/auto_ssh.py
Backport for PR https://github.com/scylladb/scylla-cluster-tests/pull/1747
> [branch-2019.1] Fix container name when run multiDC test with IPv6

- data_dir/scylla-dash-per-server-nemesis.master.json
- jenkins-pipelines/longevity-alternator-3h.jenkinsfile
- sdcm/cluster.py
- sdcm/logcollector.py
* add the alternator metrices to requests dashboards
* add snapshot and screenshot of the alternator dashboard
* send report of altrnator 3h to alternator mailing list
> feature(alternator): make dashboards support alternator

- .pre-commit-config.yaml
- Jenkinsfile
- README.rst
- commitlint.config.js
- install-prereqs.sh
See [conventinal commits](https://www.conventionalcommits.org/en/v1.0.0/) for more inforamtion
on rules and how we can configure it
trello: https://trello.com/c/iqaQIfQQ
> feat(pre-commit-hook): adding commitlint support

- sdcm/cluster.py
- sdcm/remote.py
https://trello.com/c/u9SQ8F4x/1500-run-frequent-or-long-running-commands-in-new-ssh-session
> Add new_session to remoter

- sdcm/auto_ssh.py
Backport for PR https://github.com/scylladb/scylla-cluster-tests/pull/1747
> [branch-3.2] Fix container name when run multiDC test with IPv6

- test-cases/longevity/longevity-alternator-3h.yaml
was decided that we needed to increase from 1 to 3 loaders, to generate
enough load.
also, there was no nemesis, so was decided to add some nemesis, and for
last run, there were no issues with nemesis (the ones that ran), so if
any nemesis has problems, we will either skip it (if alternator then
skip) or to remove it from alternator nemesis list.
> fix(alternator): added chaos monkey nemesis and 2 more loaders

- README.rst
- jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
- jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
- sdcm/cluster.py
- sdcm/mgmt.py
- sdcm/sct_config.py
- sdcm/tester.py
- vars/managerPipeline.groovy
As requested, in this PR the output of versions were set to INFO, to be seen in the job page.
Also, a BYO manager packages capability was added, and documentation was updated accordingly.
On the way to the BYO manager package, general longevity pipeline had manager related fields removed from it.
> Changes requested after meeting with the Manager team, and AI implemented

- sdcm/stress_thread.py
https://trello.com/c/5GAiNOHY/1573-catch-errors-happening-during-stress-command-run-by-creating-an-critical-event
> Catch stress thread errors and generate critical event on em

- data_dir/scylla-dash-per-server-nemesis.3.3.json
Since monitoring version was not changed  based it on 3.2.
(master dashboard is stale)
> improvement(sct-grafana-dashboard): added new 3.3 json

- sdcm/cluster.py
if dashboard file for new version is missing, monitor node setup failed
Adding new property to monitor set class, which handle missing dashboard for
new version and return dashboard for version or master
> fix(class basemonitorset): Fix upload scylla-server-nemesis dashboard methods

- tests/perf-regression.100threads.30M-keys-i3.yaml
Since it's under our responsibility to inspect the master performance tests, I added the entire qa team to the email recipients
> config(perf-regression-throughput): Added qa@scylladb.com to email_recipients

- Jenkinsfile
- sct.py
- sdcm/utils/common.py
- sdcm/utils/monitorstack.py
- Small refactoring
- Added basic checks that monitoring stack is up
- Added basic checks that grafana and prometheus are answered
- Added to Jenkinspipeline for running during test-provision
Trello: https://trello.com/c/joQ8iNZd
> Adding verifing steps to monitoring restore

- .pre-commit-config.yaml
- data_dir/scylla-dash-per-server-nemesis.2019.1.json
- data_dir/scylla-dash-per-server-nemesis.3.1.json
- data_dir/scylla-dash-per-server-nemesis.3.2.json
- data_dir/scylla-dash-per-server-nemesis.master.json
- defaults/aws_config.yaml
- docker/ndbench/Dockerfile
- docker/ndbench/README.md
- docker/ndbench/image
- docker/scylla-sct/entry.sh
- docker/ycsb/Dockerfile
- docker/ycsb/README.md
- docker/ycsb/image
- longevity_test.py
- pylintrc
- sdcm/cluster.py
- sdcm/ndbench_thread.py
- sdcm/remote.py
- sdcm/sct_events.py
- sdcm/tester.py
- sdcm/utils/docker.py
- sdcm/utils/thread.py
- sdcm/ycsb_thread.py
- test-cases/longevity/longevity-alternator-3h.yaml
- unit_tests/conftest.py
- unit_tests/dummy_remote.py
- unit_tests/test_ndbench_thread.py
- unit_tests/test_ycsb_thread.py
> feature(loaders): netflix's ndbench as a new loader tool

- .pre-commit-config.yaml
- docker/alternator-dns/Dockerfile
- docker/alternator-dns/dns_server.py
- docker/alternator-dns/image
- docker/ycsb/Dockerfile
- docker/ycsb/image
- docker/ycsb/java.policy
- jenkins-pipelines/longevity-alternator-3h.jenkinsfile
- longevity_test.py
- sdcm/sct_config.py
- sdcm/utils/alternator.py
- sdcm/utils/docker.py
- sdcm/ycsb_thread.py
- test-cases/longevity/longevity-alternator-3h.yaml
- unit_tests/test_ycsb_thread.py
Using a docker that run with each loader command that act as a dns resolver
that is aware of the live nodes via the /localnodes api
> feature(alternator): using docker dns server

- sdcm/sct_events.py
fix(sdcm/sct_events.py): Stop using socket reuse on guaranteed event sendind due to the having multiple problems around it
https://github.com/scylladb/scylla-cluster-tests/issues/1803
> fix(sdcm/sct_events.py): Stop using socket reuse on guaranteed event

- test-cases/PR-provision-test-docker.yaml
- test-cases/PR-provision-test.yaml
> fix(test-cases/PR-provision-test*): propup scylla version

- sdcm/cluster.py
fix(sdcm/cluster.py): Fix referenced before assignment for screenshot links
To fix following error:
< t:2020-02-14 06:32:49,560 f:longevity_test.py l:492  c:sdcm.tester          p:INFO  > Prepare data for email
< t:2020-02-14 06:32:49,561 f:tester.py       l:1379 c:sdcm.tester          p:ERROR > Exception in finalize_test method local variable 'screenshot_links' referenced before assignment < t:2020-02-14 06:32:49,561 f:tester.py       l:1379 c:sdcm.tester          p:ERROR > Exception in finalize_test method local variable 'screenshot_links' referenced before assignment
< t:2020-02-14 06:32:49,561 f:tester.py       l:1379 c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2020-02-14 06:32:49,561 f:tester.py       l:1379 c:sdcm.tester          p:ERROR >   File …
> fix(sdcm/cluster.py): Fix referenced before assignment for screenshot links

- sdcm/cluster.py
Added sudo privileges to the docker installation command.
> Fix(loader): fixed the docker installation

- jenkins-pipelines/perf-regression-latency-30min.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-30min.jenkinsfile
- performance_regression_test.py
- sdcm/db_stats.py
- sdcm/results_analyze.py
- sdcm/tester.py
- sdcm/utils/common.py
- test-cases/performance/perf-regression-latency-500gb-30min.yaml
- test-cases/performance/perf-regression.100threads.30M-keys.yaml
- vars/perfRegressionParallelPipeline.groovy
- Performance tests rebased on master
- Prepare pipeline for performancetests
- Changed query for ES to search results for old runs and new one
- fixed minor issues
Trello: https://trello.com/c/2rlAdCPP
> refactor(jenkins job): Performance tests run using pipeline

- sdcm/remote.py
We can safely retry the command when it didn't run on remote.
This situation can happen when SSH/channel connection was not
successfully initiated.
Related issues: #1793, #1631, #1815
> improvement(remoter): re-runing command on retriable exceptions

- artifacts_test.py
- docs/artifacts_test.md
- jenkins-pipelines/artifacts-ami.jenkinsfile
- sdcm/cluster_aws.py
- test-cases/artifacts/ami.yaml
- vars/artifactsPipeline.groovy
Trello: https://trello.com/c/AhDYBtIL/1660-migrate-scylla-ami-test-from-scylla-artifacts
> test(artifacts test): AMI artifact test

- test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h-ics.yaml
Gemini tool was updated and have new parameter which allow
to set table propertites.
> fix(gemini ics): Fix gemini ics tests with new parameter

- Jenkinsfile
- docker/env/hydra.sh
- sdcm/cluster.py
- sdcm/docker.py
- sdcm/logcollector.py
- sdcm/utils/remotewebbrowser.py
- test-cases/PR-provision-test-docker.yaml
- vars/getJenkinsLabels.groovy
https://trello.com/c/qmS9onLT/1595-fix-issues-with-docker-backend
> Fix building docker image proccess

- sdcm/utils/common.py
To help debugging issues added debug logging of the execute query
https://trello.com/c/GDBDd3ic/1464-add-debug-messages-to-logs-about-what-cql-query-is-going-to-be-executed
> improvement(scylla-cql-session): log executed query

- sdcm/nemesis.py
To address https://github.com/scylladb/scylla-cluster-tests/issues/1822
> fix(sdcm/nemesis.py): Limit number of columns per table

- sdcm/cluster.py
- sdcm/docker.py
- sdcm/logcollector.py
To make get_grafana_screenshot and get_grafana_snapshot for docker
https://trello.com/c/0hTlUE6b/1610-make-provision-test-work-for-docker-backend
Goes after https://github.com/scylladb/scylla-cluster-tests/pull/1757
> Fix docker grafana

- upgrade_test.py
> [branch-3.2] fix(upgrade-test): remove unused var reload_conf

- artifacts_test.py
- docs/artifacts_test.md
- jenkins-pipelines/artifacts-docker.jenkinsfile
- sdcm/cluster.py
- sdcm/docker.py
- sdcm/results_artifacts.html
- test-cases/artifacts/docker.yaml
- vars/artifactsPipeline.groovy
Trello: https://trello.com/c/sxFyfZuc/1652-docker-artifact-test
> test(artifacts test): Docker image artifact test

- vars/artifactsPipeline.groovy
- vars/rollingUpgradePipeline.groovy
- vars/scyllaCloudLongevityPipeline.groovy
Fixed pipeline stage Clean-resources - removed obsolete parameter
> fix(clean-resources): fix pipeline stage clean-resources

- artifacts_test.py
- sdcm/results_artifacts.html
- sdcm/send_email.py
Trello: https://trello.com/c/GKMTNYYr/1703-improve-artifacts-email-report
> improvement(artifacts test): improve email report

- data_dir/scylla-dash-per-server-nemesis.master.json
- longevity_test.py
- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/sct_events.py
- sdcm/utils/common.py
- sdcm/ycsb_thread.py
- test-cases/longevity/longevity-alternator-3h.yaml
- unit_tests/conftest.py
- unit_tests/test_events.py
now that we have figured the way to use dataintegrity,
and make the code to collect it's stats,
it's about time to start using it
> feature(alternator): dataintegrity=true to the 3h sanity test

- data_dir/large_collections.yaml
- jenkins-pipelines/longevity-large-collections-12h.jekinsfile
- longevity_test.py
- test-cases/longevity/longevity-large-collections-12h.yaml
> Add longevity for Large collections

- sdcm/sct_events.py
Trello: https://trello.com/c/IHoBCFLo/1708-remove-race-condition-between-events-threads
Closes #1879
> fix(sct_events): race condition in EventsDevice

- artifacts_test.py
- sdcm/results_artifacts.html
- sdcm/send_email.py
Backport of #1873 to branch-3.3
> [branch-3.3] improvement(artifacts test): improve email report

- Jenkinsfile
- defaults/docker_config.yaml
- sdcm/cluster.py
- sdcm/cluster_docker.py
- sdcm/logcollector.py
- sdcm/remote.py
- sdcm/sct_config.py
- sdcm/stress_thread.py
- sdcm/tester.py
- sdcm/utils/docker.py
- test-cases/PR-provision-test-docker.yaml
- test-cases/PR-provision-test.yaml
- unit_tests/dummy_remote.py
https://trello.com/c/0hTlUE6b/1610-make-provision-test-work-for-docker-backend
> fix(sdcm/docker.py): fix docker and non-docker teardown proceedure

- sdcm/results_analyze.py
- sdcm/results_performance.html
Adding to Performance result analyzing and performance report
data with comparision current test result with result for latest commit
in version
Trello: https://trello.com/c/W0aWeFhU
Trello: https://trello.com/c/RNVQtVHM
> improvement(perfreport): Adding data with comparision for latest commit

- jenkins-pipelines/longevity-ndbench-100gb-4h.jenkinsfile
- sdcm/ndbench_thread.py
- test-cases/longevity/longevity-ndbench-100gb-4h.yaml
- unit_tests/test_ndbench_thread.py
for able to checkout how ndbench is doing comapred to other stress tools
we are adding a test case and a pipeline for making easy to re-run with ndbench
> feature(ndbench): adding a test case and a pipeline

- sdcm/results_analyze.py
- sdcm/results_performance_baseline.html
some of the missing implementation from Alex work
> fix(results_analyze): few fixes for baseline based analyzer

- sdcm/results_analyze.py
- sdcm/results_base.html
- sdcm/results_performance_baseline.html
Fix result analyze with comparing as source the best result per version
destination as current result, in this case we will see is best result per version
better/worse than current test result
Fix html template
> fix(performance_subtype): Minor fixes for performance test with sub_type

- README.rst
- docker/env/build_n_push.sh
- docker/env/hydra.sh
From now on we'll be building the docker images locally, and push them
to dockerhub.
> feature(hydra): push/pull docker images from dockerhub

- artifacts_test.py
- gemini_test.py
- longevity_test.py
- private_repo_test.py
- sdcm/send_email.py
- sdcm/tester.py
- upgrade_test.py
Trello: https://trello.com/c/a9dNvwWM/1719-duplicate-code-in-privaterepotest-1895
Fixes #1895
> refactor(email): generalize getting email data

- docs/artifacts_test.md
- sdcm/sct_config.py
- unit_tests/test_config.py
Trello: https://trello.com/c/UX7nHf02/1736-artifacts-docker-doesnt-work-in-master-branch-1908
Fixes: #1908
> fix(artifacts test): make docker job run on master branch

- sdcm/send_email.py
> Fix issue with having more than 5 events

- data_dir/scylla-dash-per-server-nemesis.2.3.json
- data_dir/scylla-dash-per-server-nemesis.2018.1.json
- data_dir/scylla-dash-per-server-nemesis.2019.1.json
- data_dir/scylla-dash-per-server-nemesis.3.0.json
- data_dir/scylla-dash-per-server-nemesis.3.1.json
- data_dir/scylla-dash-per-server-nemesis.3.2.json
- data_dir/scylla-dash-per-server-nemesis.3.3.json
- data_dir/scylla-dash-per-server-nemesis.master.json
Trello: https://trello.com/c/1Queemf8/1582-add-warning-severity-to-grafana-dashboard
> improvement(dashboards): add WARNING filter

- defaults/test_default.yaml
> feature(test_defaults): advance monitor_branch to use branch-3.2

- test-cases/longevity/longevity-lwt-basic-3h.yaml
Fix for PR #1926 : fixed AMI for us-west-2
> fix(loader ami for lwt test): dedicated loader ami for us-west-2

- mgmt_cli_test.py
- sdcm/mgmt.py
the restore procedure (for backup verification) now
uses files list manager provides to ensure downloading
only the relevant files. It will also allow better
testing, as we can test multiple backups, and be able
to restore only the correct one, making the verification
process much more accurate (and closer to what user will
do until we have an automatic mechanism to do it).
> improvement(manager backup): restore procedure changes

- jenkins-pipelines/longevity-large-partition-8h.jenkinsfile
- test-cases/longevity/longevity-large-partition-8h.yaml
…th smaller dataset and shorter
Adding a short longevity with large paritions dataset using scylla-bench.
Targeted to run about 8h.
> test(longevity-large-partition): Adding a new large partition test with smaller dataset and shorter

- sdcm/tester.py
since we changed the failure logic to include both critical and error events
the `TestResultEvent` doesn't includ this logic,
this change makes sure this check happens before creating `TestResultEvent`
Ref: [trello item](https://trello.com/c/rqZN32Qu)
> fix(tester.py): move failure logic based on events to one place

- sdcm/cluster.py
since we move to use `scylla-machine-image` the scylla.yml in AMIs is
no longer the orignal one (i.e. it the same but without comments)
so there is not point of using regexs to try to preserve it.
this fix read the yaml with pyyaml, replaces what's needed and build it back.
Trello: https://trello.com/c/jqHnwCtU
> fix(config_setup): stop using regex to replace variables in scylla.yml

- sdcm/nemesis.py
This patch introduced a new nemesis, which try to stop decommission in middle
to trigger some streaming fails, then rebuild the data on the node.
> introduced StreamingError nemesis

- docs/configuration_options.md
- gemini_test.py
- jenkins-pipelines/gemini-3h-cdc-preimage-write.jenkinsfile
- jenkins-pipelines/gemini-3h-cdc-write.jenkinsfile
- sdcm/gemini_thread.py
- sdcm/sct_config.py
- sdcm/sct_events.py
- test-cases/gemini/gemini-3h-cdc-postimage-write.yaml
- test-cases/gemini/gemini-3h-cdc-preimage-write.yaml
- test-cases/gemini/gemini-3h-cdc-write.yaml
Added new feature CDC tests with gemini.
> feature(gemini_cdc): Add gemini write test for cdc

- artifacts_test.py
- sdcm/report_templates/results_artifacts.html
- sdcm/send_email.py
> improvement(artifacts test): add DB instance type to email report

- jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
after 3.3 was released, and now working on branch 4.0, bumping up
the base version to run on 3.3 (last released was 3.3.4).
> fix(rolling upgrade version): bumping version to last OSS

- sdcm/mgmt.py
Due to recent changes in manager, the cluster status command now outputs
the status of SSL as a part of the CQL column, so I changed the code to
extract the status from the cql column accordingly
> fix(manager): fixed ssl status extraction from cluster status

- .github/pull_request_template.md
- removed naming since it is part of the coding best practices
- removed copy-paste check since it is enforced by pre-commit hooks
> improvement(pr-template): removed less relevant checks

- sdcm/send_email.py
- sdcm/tester.py
https://trello.com/c/TLK5Kp9i/1816-improve-test-results-email
Changes:
1. Add limit on total characters displayed in each category, separate limits for attachment and email body
2. Add new logic on cutting report data
3. Add test status into email subject
> fix(sdcm/send_email.py): Improve test result email

- test-cases/artifacts/amazon2.yaml
- test-cases/artifacts/centos7.yaml
Trello: https://trello.com/c/aUOFfMAF/1713-artifact-test-leftovers
> perf(artifacts test): disable backtrace decoding (missed files)

- sdcm/utils/common.py
Trello: https://trello.com/c/Xf9WvybO/1828-if-sct-run-on-a-builder-then-cleanup-docker-containers-on-this-builder-only
> improvement(docker): clean up local Docker only if run on a builder

- artifacts_test.py
- gemini_test.py
- longevity_test.py
- upgrade_test.py
https://trello.com/c/G9LRzyOc/1822-add-instance-type-to-gce-artifacts-longevity-email
> fix(*_test.py): Add GCE instance type to the reports

- sdcm/nemesis.py
> feature(nemesis.py): add new scrub nemesis

- sdcm/cluster.py
- sdcm/logcollector.py
- sdcm/tester.py
- sdcm/utils/common.py
Trello: https://trello.com/c/f5H1U2vB/1845-error-during-collect-logs-attributeerror-collectingnode-object-has-no-attribute-tags
Fixes: #2022
> fix(logcollector): add tags property to CollectingNode

- sdcm/utils/cloud_monitor/cloud_monitor.py
- sdcm/utils/cloud_monitor/report.py
- sdcm/utils/cloud_monitor/templates/per_user.html
- sdcm/utils/cloud_monitor/templates/per_user_summary.html
add keep alive data to the email and to the attached html
email
attached html
> feature(cloud-monitor): added keep alive information

- sdcm/nemesis.py
caused nemesis not to start at all
> fix(#2043): remove temporary lwt printouts

- test-cases/longevity/longevity-lwt-1loader-3h.yaml
- test-cases/longevity/longevity-lwt-basic-24h.yaml
- test-cases/longevity/longevity-lwt-basic-3h.yaml
1. Use new loaders. The loader include a few fixes special for LWT:
- fix NoSuchElementException
- enable control over both consistency levels: regular and serial
- bring shard awareness
2. Change updated consistency level to QUORUM as SERIAL can't be used
for update operations and ALL may cause the not relevant failures
3. Set user_prefix according to the test
> fix(lightweight transaction): few changes in test yamls

- sdcm/nemesis.py
> fix(sdcm/nemesis.py): Fix issue with add drop column table filtering not working on per table basis

- sdcm/logcollector.py
- sdcm/utils/docker.py
Trello: https://trello.com/c/wnDeD5IF/1878-autossh-containers-are-left-after-the-test-finished-suceessfully
> fix(docker): raise events instead of exceptions while destroying containers

- sdcm/cluster_aws.py
- sdcm/cluster_baremetal.py
- sdcm/cluster_gce.py
- sdcm/logcollector.py
- sdcm/utils/docker.py
- unit_tests/test_utils_docker.py
Trello: https://trello.com/c/cYhT7EPA/1882-webdriver-autosssh-container-not-cleaned
Looks like it fixes #2054
> fix(docker): remove event on destroy failures

- jenkins-pipelines/gemini-8h-large-num-columns.jenkinsfile
- test-cases/gemini/gemini-8h-large-num-columns.yaml
Added new test with large number of columns (80-100) per table
Trello: https://trello.com/c/Rl5OtKm0
> test(gemini): New gemini test with large columns number

- longevity_test.py
- sdcm/utils/alternator.py
- sdcm/ycsb_thread.py
- test-cases/longevity/longevity-alternator-3h.yaml
* Adding cassadnra stress for CQL
* alternator table with LWT disabled
> feature(alternator_3h): beef the scenario up

- docs/artifacts_test.md
- vars/artifactsPipeline.groovy
- vars/sctScript.groovy
Trello: https://trello.com/c/wBjgZDbl/1821-support-a-list-of-instancetype-in-ami-test-and-running-in-parallel
> improvement(artifacts test): allow to run against multiple instance types

- defaults/aws_config.yaml
- defaults/docker_config.yaml
- defaults/test_default.yaml
- docs/configuration_options.md
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_docker.py
- sdcm/sct_config.py
- test-cases/artifacts/amazon2.yaml
- test-cases/artifacts/oel76.yaml
Trello: https://trello.com/c/aUOFfMAF/1713-artifact-test-leftovers
> improvement(artifacts test): check if Scylla pre-installed

- sdcm/nemesis.py
After 'nodetool rebuild' is killed, the rebuild task will continue run in
background until complete. We can use force_terminate_repair API to stop the
background rebuild task. Then execute a new 'nodetool rebuild'.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/2004
> fix(streaming_err): stop background repair task by force_terminate_repair API

- sdcm/cluster_gce.py
> fix(gce-node): disable sshguard on gce ubuntu bionic

- defaults/test_default.yaml
- jenkins-pipelines/longevity-alternator-200gb-48h.jenkinsfile
- longevity_test.py
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/sct_config.py
- sdcm/utils/alternator.py
- sdcm/ycsb_thread.py
- test-cases/longevity/longevity-alternator-200GB-48h.yaml
- unit_tests/test_ycsb_thread.py
now that was have the 3h test case up and running with nemesis,
we want have weekly runs with the 48h case.
> feature(alternator): adding an 48h alternator test

- defaults/gce_config.yaml
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/PR-provision-test.yaml
added ability to randomely select availability zone when not provided
https://trello.com/c/ZfJD4QDd/1900-support-random-azs-in-gce
> feature(gce provision): support random zone

- jenkins-pipelines/longevity-5000-tables.jenkinsfile
- test-cases/longevity/longevity-5000-tables.yaml
> 5k tables longer test

- data_dir/cs_lwt_perf_big.yaml
- data_dir/cs_lwt_perf_small.yaml
- docs/configuration_options.md
- jenkins-pipelines/perf-regression-latency-lwt-big.jenkinsfile
- jenkins-pipelines/perf-regression-latency-lwt-small.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-lwt-big.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-lwt-small.jenkinsfile
- performance_regression_lwt_test.py
- performance_regression_test.py
- sdcm/cluster.py
- sdcm/db_stats.py
- sdcm/report_templates/results_base_custom.html
- sdcm/report_templates/results_base_new.html
- sdcm/report_templates/results_performance_multi_baseline.html
- sdcm/report_templates/results_performance_multi_baseline_single_metric.html
- sdcm/results_analyze/__init__.py
- sdcm/results_analyze/base.py
- sdcm/results_analyze/metrics.py
- sdcm/results_analyze/test.py
- sdcm/sct_config.py
- sdcm/sct_events.py
- sdcm/tester.py
- sdcm/utils/es_queries.py
- test-cases/performance/perf-regression-latency-lwt-big.yaml
- test-cases/performance/perf-regression-latency-lwt-small.yaml
- test-cases/performance/perf-regression-throughput-lwt-big.yaml
- test-cases/performance/perf-regression-throughput-lwt-small.yaml
- test_lib/utils.py
- unit_tests/test_lib_utils.py
- vars/byoLongevityPipeline.groovy
https://trello.com/c/GmTtAU4Z/1624-lwt-performance-test
Jenkins jobs:
https://jenkins.scylladb.com/view/Performance/job/Perf-Regression/job/scylla-release-perf-regression-aws-lwt-big-latency/
https://jenkins.scylladb.com/view/Performance/job/Perf-Regression/job/scylla-release-perf-regression-aws-lwt-big-throught/
https://jenkins.scylladb.com/view/Performance/job/Perf-Regression/job/scylla-release-perf-regression-aws-lwt-small-latency/
https://jenkins.scylladb.com/view/Performance/job/Perf-Regression/job/scylla-release-perf-regression-aws-lwt-small-throught/
> perf(performance_regression_lwt_test.py): Add performance tests for lwt

- configurations/scylla_cloud_nemesis.yaml
- jenkins-pipelines/scylla-cloud-longevity-100gb-48h.jenkinsfile
- jenkins-pipelines/scylla-cloud-longevity-100gb-4h.jenkinsfile
- jenkins-pipelines/scylla-cloud-longevity-10gb-4h.jenkinsfile
- vars/scyllaCloudLongevityPipeline.groovy
Adding this so we could easily test more of the nemesis, if they
are suitable for scylla-cloud usage
> refactor(scylla_cloud): change 3h test to be base on 4h 100Gb case

- sdcm/ec2_client.py
- sdcm/utils/cloud_monitor/cloud_monitor.py
- sdcm/utils/cloud_monitor/common.py
- sdcm/utils/cloud_monitor/report.py
- sdcm/utils/cloud_monitor/templates/per_user.html
- sdcm/utils/cloud_monitor/templates/per_user_summary.html
- sdcm/utils/fromisoformat.py
- sdcm/utils/pricing.py
> feature(cloud-monitor): added pricing

- jenkins-pipelines/perf-regression-latency-lwt-big.jenkinsfile
- jenkins-pipelines/perf-regression-latency-lwt-small.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-lwt-big.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-lwt-small.jenkinsfile
> fix(jenkins-pipelines/perf-regression-*): Switch to perfRegressionParallelPipeline

- sdcm/utils/cloud_monitor/cloud_monitor.py
- sdcm/utils/cloud_monitor/common.py
- sdcm/utils/cloud_monitor/report.py
- sdcm/utils/cloud_monitor/resources/__init__.py
- sdcm/utils/cloud_monitor/resources/instances.py
- sdcm/utils/cloud_monitor/resources/static_ips.py
- sdcm/utils/cloud_monitor/templates/cloud_resources.html
- sdcm/utils/cloud_monitor/templates/per_user.html
- sdcm/utils/common.py
Also made a refactor to the code.
Email body
Attached HTML
> feature(cloud-monitor): added static IPs information to the report

- defaults/aws_config.yaml
> fix(defaults/aws_config.yaml): Update loader AMI with new scylla-java-tools

- sct.py
- sdcm/send_email.py
https://trello.com/c/53ZOYGgi/1905-send-email-with-result-should-send-email-even-if-file-with-email-results-data-not-found
> fix(sdcm/send_email.py): Send email even if no email data found

- docker/env/hydra.sh
- sdcm/cluster.py
- sdcm/logcollector.py
- sdcm/tester.py
- sdcm/utils/common.py
- sdcm/utils/get_username.py
Trello: https://trello.com/c/RhCQjafe/1825-tag-hydra-container-as-others
> improvement(tagging): tag hydra container with TestId and RunByUser

- sdcm/sct_events.py
- sdcm/tester.py
- sdcm/utils/common.py
- unit_tests/test_events.py
https://trello.com/c/Qh66ee35/1717-improve-teardown
Purpose of this PR is to make teardown more reliable.
> fix(sdcm/*): Improve teardown

- jenkins-pipelines/perf-regression-cdc-write-60min.jenkinsfile
- jenkins-pipelines/perf-regression-cdc-write-latency-60min.jenkinsfile
- performance_regression_cdc_test.py
- sdcm/db_stats.py
- sdcm/results_analyze/__init__.py
- sdcm/utils/common.py
- sdcm/utils/es_queries.py
- test-cases/performance/perf-regression-write-cdc.yaml
- test-cases/performance/perf-regression-write-latency-cdc.yaml
Added Performance test for CDC feature
> test(new test): Performance tests for CDC

- docker/env/Dockerfile
> fix(hydra): updated url for IUS repo

- defaults/test_default.yaml
- jenkins-pipelines/longevity-alternator-3h-multidc.jenkinsfile
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_docker.py
- sdcm/cluster_gce.py
- sdcm/sct_config.py
- sdcm/tester.py
- sdcm/ycsb_thread.py
- test-cases/longevity/longevity-alternator-3h-multidc.yaml
> Alternator multidc

- sct.py
- vars/longevityPipeline.groovy
https://trello.com/c/Hgy9sdJC/1753-send-longevity-email-in-any-case
Should be merged after https://github.com/scylladb/scylla-cluster-tests/pull/2145
> Jenkins longevity abort callback

- configurations/manager/debian9.yaml
- configurations/manager/ubuntu16.yaml
- configurations/manager/ubuntu18.yaml
- jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
- vars/managerPipeline.groovy
> Separating manager yaml files

- sct.py
- sdcm/cluster.py
Trello: https://trello.com/c/z8tpBBIH/1795-file-logger-for-hydra-commands
> improvement(logging): put log to a file for hydra commands

- vars/longevityPipeline.groovy
> fix(vars/longevityPipeline.groovy): Added send_email flag back

- defaults/test_default.yaml
there was a typo in b9095d599b683e4edc4dd7078b9d37fabc4637a8
> fix(repo_urls): type on the scylla-2019.1 repo url

- sdcm/cluster.py
In one job, I found the `uptime -s` result increased 1 second without real
reboot, it might be caused by normal timedrift. So we should not treat it as
reboot finish if the uptime change is very short.
This patch added a time gap check, it will ignore short uptime change before
real reboot.
Fixes: #2209
> fix(reboot): ignore short uptime change before real reboot

- docs/artifacts_test.md
- jenkins-pipelines/artifacts-amazon2.jenkinsfile
- jenkins-pipelines/artifacts-centos7.jenkinsfile
- jenkins-pipelines/artifacts-centos8.jenkinsfile
- jenkins-pipelines/artifacts-debian10.jenkinsfile
- jenkins-pipelines/artifacts-debian9.jenkinsfile
- jenkins-pipelines/artifacts-oel76.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1604.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
- vars/artifactsPipeline.groovy
Trello: https://trello.com/c/dsfJI1Jw/1512-manager-agent-in-artifacts-tests-for-all-distros
> test(artifacts test): add ability to test Scylla Manager

- jenkins-pipelines/artifacts-amazon2.jenkinsfile
- jenkins-pipelines/artifacts-centos7.jenkinsfile
- jenkins-pipelines/artifacts-centos8.jenkinsfile
- jenkins-pipelines/artifacts-debian10.jenkinsfile
- jenkins-pipelines/artifacts-debian9.jenkinsfile
- jenkins-pipelines/artifacts-oel76.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1604.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
Trello: https://trello.com/c/dsfJI1Jw/1512-manager-agent-in-artifacts-tests-for-all-distros
> [branch-4.1] test(artifacts test): set default values for scylla_mgmt_repo

- Jenkinsfile
- jenkins-pipelines/private-repo.jenkinsfile
- vars/artifactsPipeline.groovy
- vars/byoLongevityPipeline.groovy
- vars/longevityPipeline.groovy
- vars/managerPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
- vars/rollingUpgradePipeline.groovy
> Fix issue missing /sct/latest/test_id

- sdcm/cluster.py
> fix(artifacts test): use apt-get for installing scylla-manager-agent on deb-based distros

- jenkins-pipelines/artifacts-amazon2.jenkinsfile
- jenkins-pipelines/artifacts-centos7.jenkinsfile
- jenkins-pipelines/artifacts-centos8.jenkinsfile
- jenkins-pipelines/artifacts-debian10.jenkinsfile
- jenkins-pipelines/artifacts-debian9.jenkinsfile
- jenkins-pipelines/artifacts-oel76.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1604.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
Trello: https://trello.com/c/wWgNa04b/2003-update-manager-yaml-repo-link-to-latest-master
> test(artifacts test): switch to latest manager repo

- jenkins-pipelines/artifacts-centos7.jenkinsfile
- jenkins-pipelines/artifacts-centos8.jenkinsfile
- jenkins-pipelines/artifacts-debian9.jenkinsfile
- jenkins-pipelines/artifacts-oel76.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1604.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
Trello: https://trello.com/c/dsfJI1Jw/1512-manager-agent-in-artifacts-tests-for-all-distros
> [branch-3.3] test(artifacts test): set default values for scylla_mgmt_repo

- jenkins-pipelines/artifacts-amazon2.jenkinsfile
- jenkins-pipelines/artifacts-centos7.jenkinsfile
- jenkins-pipelines/artifacts-centos8.jenkinsfile
- jenkins-pipelines/artifacts-debian10.jenkinsfile
- jenkins-pipelines/artifacts-debian9.jenkinsfile
- jenkins-pipelines/artifacts-oel76.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1604.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
Trello: https://trello.com/c/dsfJI1Jw/1512-manager-agent-in-artifacts-tests-for-all-distros
> [branch-4.0] test(artifacts test): set default values for scylla_mgmt_repo

- jenkins-pipelines/artifacts-ubuntu1604.jenkinsfile
> [branch-4.1] fix(artifacts test): fix manager repo URL for Ubuntu 16.04

- README.rst
- docs/configuration_options.md
- sdcm/cluster.py
- sdcm/logcollector.py
- sdcm/nemesis.py
- sdcm/prometheus.py
- sdcm/remote.py
- sdcm/sct_config.py
- sdcm/tester.py
- sdcm/utils/profiler.py
- unit_tests/lib/__init__.py
- unit_tests/lib/test_profiler/__init__.py
- unit_tests/lib/test_profiler/lib.py
- unit_tests/lib/test_profiler/lib2.py
- unit_tests/test_profiler.py
https://trello.com/c/bCHQq7k4/1981-enable-python-profiling-for-run-test
> fix(sct.py): add profiling

- README.rst
- sct.py
this command is creating only the enterpraise jobs
> feature(create_jobs): new hydra command to create enterpraise jobs

- jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
> test(rolling upgrade): set base version for branch 2020.1

- jenkins-pipelines/manager/manager-upgrade.jenkinsfile
- mgmt_cli_test.py
- mgmt_upgrade_test.py
- sdcm/cluster.py
- sdcm/mgmt.py
- sdcm/nemesis.py
- sdcm/sct_config.py
- test-cases/upgrades/manager-upgrade.yaml
- vars/managerPipeline.groovy
Created an upgrade test for scylla manager (from manager 2.0)
> test(manager): Added an upgrade test for scylla manager

- sdcm/stress_thread.py
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/2264
> fix(sdcm/stress_thread.py): fix issue with adding -errors suboption

- vars/managerPipeline.groovy
Removed unnecessary monitor-related conditions from the manager pipeline that caused
certain scenarios to fail
> fix(manager): removing unnecessary conditions from pipeline

- defaults/test_default.yaml
> feature(manager): changed the default manager version to 2.1

- mgmt_cli_test.py
- sdcm/report_templates/results_manager.html
- sdcm/send_email.py
> feature(manager): Added a summary email to the manager jobs

- configurations/manager/debian9.yaml
- defaults/aws_config.yaml
- docs/configuration_options.md
- sdcm/cluster.py
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/artifacts/amazon2.yaml
AMI parameters, hence removing this entry from all
sct_config. It applies for DB, loader and monitor
nodes.
> refactor(aws_root_disk_name): info is found in the

- sdcm/nemesis.py
If no monitoring nodes are available, NetworkRandomInterruption simply won't limit the bandwith (but it will still introduce random packet loss etc.)
> Make NetworkRandomInterruption nemesis work without monitoring nodes

- sdcm/cluster_aws.py
https://trello.com/c/w7JcO9OD/1959-scale-test-200-nodes-fails-with-authentication-error-2154
> fix(sdcm/cluster_aws.py): Remove wrong appending to userdata

- sdcm/nemesis.py
> fix(pep8_issue): extra space introduced in #2296

- defaults/test_default.yaml
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/longevity/longevity-5000-tables.yaml
- test-cases/longevity/longevity-multi-keyspaces.yaml
> New SCT YAML parameter: stop_test_on_stress_failure

- sdcm/cluster.py
- sdcm/nemesis.py
* Creating new nemesis to decommission seed node
Trello URL: https://trello.com/c/vqTlKywi/2017-cloud-operations-decommissionseednode-nemesis
> feature(nemesis.py): Creating new DecommissionSeedNode nemesis

- sdcm/cluster.py
- sdcm/db_stats.py
- sdcm/sct_config.py
- sdcm/sct_events.py
- sdcm/send_email.py
- sdcm/tester.py
- sdcm/utils/log.py
- unit_tests/test_events.py
- unit_tests/test_microbenchmarking.py
- unit_tests/test_tester.py
https://trello.com/c/ubYvHzrF/2095-test-reports-error-and-passed
> fix(sdcm/): Create tester tests, and improve final event

- sdcm/nemesis.py
Fix for https://github.com/scylladb/scylla-cluster-tests/issues/1934
> fix(sdcm/nemesis.py): fix possible exeption if number of columns less than 2

- test-cases/upgrades/manager-upgrade.yaml
> fix(manager-upgrade): Disabled ES result storage

- sdcm/nemesis.py
Since now `enable_repair_based_node_ops` is defult to true, we are not running
repairs on the end of `NodeTerminateAndReplace`, hence there are cases
the cluster healthcheck would still see the old node in `nodetool status`
and would fails the test with critical event
Ref: scylladb/scylla-enterprise#1419
> fix(terminate_and_replace): wait for old node to be removed from ring

- sdcm/cluster.py
- sdcm/gemini_thread.py
- sdcm/logcollector.py
- sdcm/ndbench_thread.py
- sdcm/remote.py
- sdcm/sct_events.py
- sdcm/stress_thread.py
- sdcm/tester.py
- sdcm/utils/common.py
- sdcm/utils/profiler.py
- sdcm/ycsb_thread.py
> improvement: Replace all occurrences of makedirs() to os.makedirs()

- sdcm/cluster.py
During recommended cluster initialization or adding nodes to existent
cluster using recommended cluster initialization, race could happened
between scylla-server stop/scylla data clean and scylla image setup.
> fix(node_setup): Fix node setup to avoid stopping scylla image setup

- sdcm/nemesis.py
> test(nemesis.py): Adding kill Scylla monkey nemesis

- full_cluster_stop_start_test.py
- jenkins-pipelines/features-full-cluster-stop-start.jenkinsfile
- test-cases/features/full-cluster-stop-start.yaml
> test(recovery test): test cluster recovery after reboot

- sdcm/nemesis.py
Task https://trello.com/c/llRuLIOJ/2110-add-dbeventfilter-for-nosuchcolumnfamily-error
If this error happens during the first boot with the missing disk this issue is expected
and it's not an issue
> fix(restart_then_repair_node): filter out no_such_column_family error during restart

- cdc_replication_test.py
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/2395.
> CDC replication test: fix pylint warnings

- performance_regression_alternator_test.py
- sdcm/tester.py
- sdcm/utils/alternator/api.py
- unit_tests/test_ycsb_thread.py
* Fix the following tests:
* performance_regression_alternator_test.py
* test_ycsb_thread.py
> fix(alternator): Adding node variable for all Alternator API funcs

- configurations/scylla_cloud_nemesis.yaml
this file is always overridden by sct-plugin of siren,
therefore it should be deleted from SCT.
> fix(scylla_cloud_nemesis.yaml): delete this unneeded file

- docker/env/version
> fix(hydra): change version to 0.75

- defaults/k8s_gce_minikube_config.yaml
- sdcm/cluster_k8s.py
- sdcm/k8s_configs/operator.yaml
- sdcm/tester.py
- sdcm/utils/k8s.py
- vars/operatorPipeline.groovy
Trello: https://trello.com/c/UAr15myY/2151-update-to-scylla-operator-v023
> fix(k8s-gce-minikube): update to Scylla Operator v0.2.3

- unit_tests/test_tester.py
> fix(unit_tests/test_tester.py): add test on error event

- sdcm/send_email.py
https://trello.com/c/xoSS4gBU/2100-maximize-the-limit-of-characters-per-severity-in-the-test-results-emails
This fix introduce last_events_body_limit_total = 70000, a limit of the total size of all events in the report, and set last_events_limit to 10000000 making it unreachable so that only events size limits do matter, also it sets last_events_body_limit_per_severity to half of last_events_body_limit_total.
> fix(sdcm/send_email): Maximaze event number in the report

- jenkins-pipelines/perf-regression-latency-250gb-with-nemesis.jenkinsfile
- performance_regression_test.py
- sdcm/nemesis.py
- test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
> Latency Tests with nemesis support (Performance test during admin operations)

- sdcm/fill_db_data.py
- upgrade_test.py
> Backport: remove subTest from upgrade test

- sdcm/nemesis.py
The new nemesis tries to execute stress-ng to preemt scylla memory,
scylla lock memory is enabled by default, so scylla won't swap allocate
memroy.
> feature(nemesis): introduce MemoryStressMonkey

- jenkins-pipelines/k8s-longevity-10gb-1h.jenkinsfile
- sdcm/cluster_k8s.py
- sdcm/remote/kubernetes_cmd_runner.py
- sdcm/tester.py
- test-cases/k8s/gce-minikube-longevity-10gb-1h.yaml
- utils/lint_test_cases.sh
Trello: https://trello.com/c/rap3kDwM/2137-scylla-operator-tests
> test(operator): 1h longevity with non-disruptive nemeses

- sdcm/utils/common.py
```
New directory created: /home/bentsi/sct-results/20200729-215046-519207-clean-runner-instances
Looking for SCT runner instances...
Going to list aws region "eu-north-1"
Going to list aws region "ap-south-1"
Going to list aws region "eu-west-3"
Going to list aws region "eu-west-2"
Going to list aws region "eu-west-1"
Going to list aws region "ap-northeast-2"
Going to list aws region "ap-northeast-1"
Going to list aws region "sa-east-1"
Going to list aws region "ca-central-1"
Going to list aws region "ap-southeast-1"
Going to list aws region "ap-southeast-2"
Going to list aws region "eu-central-1"
Going to list aws region "us-east-1"
Going to list aws region "us-east-2"
Going to list aws region "us-west-1"
Going to list aws region "us-west-2"
eu-west-2: done [1/16]
us-east-2: done [2/16] …
```
> improvement(sct-runner-cleaner): improved logging

- sdcm/cluster.py
> fix(scylla_setup): only enable swap setup when it's supported

- Jenkinsfile
- vars/cdcReplicationPipeline.groovy
- vars/getJenkinsLabels.groovy
- vars/managerPipeline.groovy
- vars/operatorPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
- vars/rollingUpgradePipeline.groovy
> fix(pipelines): use new builder selection method + fixes

- vars/cdcReplicationPipeline.groovy
Switch in cdcreplication pipeline to use the proper function from vars/
instead of longevityPipeline obj and sct-runner
> fix(cdcrepl_pipeline): Use correct functions in cdcrepl pipeline

- sdcm/sct_runner.py
- sdcm/tester.py
- sdcm/utils/common.py
> feature(sct-runner): increase root disk size to 35 GB

- Jenkinsfile
- docker/env/hydra.sh
- sct.py
- sdcm/group_common_events.py
https://trello.com/c/2RnXYWGw/2197-fix-pre-commit-stage
> fix(sct.py): add pre-commit command and integrate it into pipeline

- sdcm/cluster.py
- sdcm/cluster_k8s.py
- sdcm/remote/remote_base.py
https://trello.com/c/pXuwI3QK/2186-implement-connection-generation-for-remoters
> fix(sdcm/remote/remote_base.py): implement context generation

- sdcm/nemesis.py
- sdcm/tester.py
https://trello.com/c/6mV6VTh3/2194-fix-docker-provision-fail
> fix(sdcm/nemesis): Make nemesis calculate relaible replication factor

- sct.py
- sdcm/report_templates/results_aborted.html
- sdcm/report_templates/results_base.html
- sdcm/send_email.py
https://trello.com/c/fWfG3RWQ/1977-add-a-list-of-resources-that-were-left-when-job-aborted
> add running nodes to aborted email

- mgmt_upgrade_test.py
- sdcm/report_templates/results_manager_upgrade.html
- sdcm/send_email.py
> feature(manager-upgrade): Added a summary email

- sdcm/remote/libssh2_client/__init__.py
- unit_tests/test_remoter.py
https://trello.com/c/UDeMR1sG/2217-libssh2-remoter-doesnt-work-with-ipv6
> fix(sdcm/remote/libssh2_client/__init__.py): make it ipv6 complaint

- sdcm/cluster.py
- sdcm/nemesis.py
> test(remove_node): Adding nodetool removenode as a new nemesis

- sdcm/remote/base.py
- unit_tests/test_remoter.py
It's a part of a bigger task, but it has own value and can be committed separately.
> improvement(remoter): add 'sudo()' and 'run_shell_script()' methods

- sdcm/cluster.py
Depends on #2521 
```shell
$ cat scylla-server
SCYLLA_ARGS="--foo"
SCYLLA_ARGS="--bar"
$ sed -i '/--foo/! s/SCYLLA_ARGS="/&--foo /' scylla-server
$ cat scylla-server
SCYLLA_ARGS="--foo"
SCYLLA_ARGS="--foo --bar"
```
> refactor(config_setup): improve append_scylla_args handling

- sdcm/utils/alternator/api.py
> fix(alternator/api.py): Fixing region_name for Cloud run

- artifacts_test.py
- mgmt_cli_test.py
- mgmt_upgrade_test.py
- sdcm/report_templates/results_base.html
- sdcm/report_templates/results_manager.html
- sdcm/report_templates/results_manager_upgrade.html
- sdcm/send_email.py
- sdcm/tester.py
https://trello.com/c/jynKn7ps/2212-add-region-to-email-template
> fix(reporting): Add backend and region to the email report

- docker/scylla-sct/Dockerfile
- sdcm/cluster.py
- sdcm/cluster_k8s.py
- sdcm/utils/version_utils.py
> improvement(cluster): don't install net-tools, file, and wget packages to DB nodes

- sdcm/cluster.py
- sdcm/sct_config.py
- sdcm/utils/distro.py
follow up PR to fix what #2530 still missed.
> Fix latency perf jobs

- sdcm/utils/file.py
To be able to re iterate result of read_lines_filtered again. 
For example when you read logs in cycle.
> fix(sdcm/utils/file.py): make read_lines_filtered iteration repitable

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/remote/remote_file.py
- sdcm/tester.py
- unit_tests/test_remoter.py
> refactor(cluster): improve scylla.yaml patching

- sdcm/nemesis.py
Trello ticket: https://trello.com/c/rMSCxzit/2168-abort-compactions-more-frequently
Introduced a new truncate nemesis, it truncates a large-partition table,
it's used to cover one improvement of compaction.
The increase frequency of checking abortion is very useful for truncate.
> feature(nemesis): add disrupt_truncate_large_partition

- sdcm/nemesis.py
> fix(nemesis.py): Disabling TerminateAndRemoveNodeMonkey nemesis for Siren cloud

- commitlint.config.js
> improvement(CommitLint): allow case insensitive scope

- defaults/test_default.yaml
- docs/configuration_options.md
- mgmt_cli_test.py
- mgmt_upgrade_test.py
- sdcm/cluster.py
- sdcm/mgmt.py
- sdcm/sct_config.py
- sdcm/utils/prepare_region.py
> Fixing scylla manager master

- cdc_replication_test.py
seem like recently change in this file were missing a few spaces
> fix(cdc_replication_test): autopep8 issues

- defaults/k8s_gce_minikube_config.yaml
- docs/configuration_options.md
- sdcm/cluster.py
- sdcm/cluster_docker.py
- sdcm/cluster_gce.py
- sdcm/cluster_k8s.py
- sdcm/k8s_configs/cluster.yaml
- sdcm/nemesis.py
- sdcm/remote/base.py
- sdcm/remote/kubernetes_cmd_runner.py
- sdcm/sct_config.py
- sdcm/tester.py
- sdcm/utils/k8s.py
- sdcm/utils/remote_logger.py
Trello: https://trello.com/c/rap3kDwM/2137-scylla-operator-tests
> improvement(operator): grow cluster by changing spec

- jenkins-pipelines/longevity-scylla-operator-3h.jenkinsfile
- vars/byoOperatorPipeline.groovy
In addition restricted selecting configuration YAML from the master job
> feature(pipelines): byo pipeline for scylla operator

- sdcm/nemesis.py
https://trello.com/c/v9NsSg1m/2265-k8s-stopstartmonkey
> Enable stop start

- test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml
- test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
- test-cases/performance/perf-regression-latency-1TB.yaml
- test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
- test-cases/performance/perf-regression-latency-500gb-30min.yaml
- test-cases/performance/perf-regression-latency-lwt-big.yaml
- test-cases/performance/perf-regression-latency-lwt-small.yaml
- test-cases/performance/perf-regression-throughput-cdc-mixed-poll-batching.yaml
- test-cases/performance/perf-regression-throughput-lwt-big.yaml
- test-cases/performance/perf-regression-throughput-lwt-small.yaml
- test-cases/performance/perf-regression-write-latency-cdc.yaml
- test-cases/performance/perf-regression-write-throughput-cdc.yaml
- test-cases/performance/perf-regression.100threads.30M-keys.yaml
- test-cases/performance/perf-row-level-repair-1TB.yaml
Since we don't want to skew the results by changing the loader type
- ~~[ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)~~
- ~~[ ] I didn't leave commented-out/debugging code~~
- ~~[ ] I added the relevant `backport` labels~~
- ~~[ ] All new and existing unit tests passed (CI)~~
> revert(instance_type): revert #2566 for the performance cases

- sdcm/cluster.py
Sometimes it fails to connect via SSH on the first attempt on very early stages of the setup.
> improvement(cluster): add retry for distro property

- sdcm/nemesis.py
https://trello.com/c/rEUPev4d/2275-k8s
> fix(sdcm/nemesis.py): enable StopWaitStartMonkey

- jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
- test-cases/upgrades/manager-upgrade.yaml
> fix(manager): changed the default manager in manager tests to 2.1

- sdcm/nemesis.py
https://trello.com/c/dqcecL3j/2288-k8s-truncatemonkey-and-truncatelargeparititionmonkey
> fix(sdcm/nemesis): enable TruncateLargeParititionMonkey and TruncateMonkey for kube

- jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
> fix(manager): missing comma in ubuntu18-manager-sanity.jenkinsfile

- sdcm/nemesis.py
https://trello.com/c/Scqa2lHd/2301-k8s-abortrepairmonkey
> Enable AbortRepairMonkey for kube

- sdcm/gemini_thread.py
- sdcm/sct_events.py
Trello: https://trello.com/c/Xf61zSyh/1837-improve-geminilogevent
> improvement(GeminiLogEvent): parse logs using json.loads() instead of regex

- sdcm/nemesis.py
https://trello.com/c/VGLh1mFs/2287-k8s-nodetoolcleanupmonkey
> fix(sdcm/nemesis.py): enable NodeToolCleanupMonkey for kube

- sdcm/cluster.py
- sdcm/logcollector.py
- sdcm/tester.py
Trello: https://trello.com/c/yMnU9ZeR/1563-add-check-of-create-zip-targz-archive-in-logcollector
> improvement(logcollector): check archives before transfers

- jenkins-pipelines/longevity-scylla-operator-3h.jenkinsfile
> fix(operator-pipeline): fix timeout

- artifacts_test.py
- cdc_replication_test.py
- gemini_test.py
- longevity_test.py
- mgmt_cli_test.py
- mgmt_upgrade_test.py
- sdcm/cluster.py
- sdcm/send_email.py
- sdcm/tester.py
- unit_tests/test_cluster.py
- upgrade_test.py
Trello: https://trello.com/c/ZMSbOopb/2235-add-to-email-report-properties-region-and-scylla-version
> improvement(email report): include more detailed Scylla version

- jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile
- jenkins-pipelines/manager/centos-manager-backup.jenkinsfile
- jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
- jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
- vars/managerPipeline.groovy
> Manager 2.2 add defaults to pipelines

- jenkins-pipelines/feature-cdc-replication-gemini-postimage.jenkinsfile
- jenkins-pipelines/feature-cdc-replication-gemini-preimage.jenkinsfile
- jenkins-pipelines/feature-cdc-replication-gemini.jenkinsfile
- jenkins-pipelines/feature-cdc-replication-longevity.jenkinsfile
- test-cases/cdc/cdc-15m-replication.yaml
- test-cases/cdc/cdc-replication-longevity.yaml
> cdc replication tests: add qa to email, fix duration, fix loader type

- jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
> fix(manager): rectified a few incorrect repo paths

- sdcm/mgmt.py
Since the host, with-host and token-ranges flags were removed from the manager, I removed
those arguments from the task creation methods
> fix(manager): Removed host and token ranges flags

- jenkins-pipelines/longevity-alternator-200gb-48h.jenkinsfile
- jenkins-pipelines/longevity-alternator-3h-multidc.jenkinsfile
- jenkins-pipelines/longevity-alternator-3h.jenkinsfile
- jenkins-pipelines/perf-regression-alternator-latency-30min.jenkinsfile
- jenkins-pipelines/perf-regression-alternator-throughput-30min.jenkinsfile
By Nadav's request remove alternator@scylladb.com from tests email recipients list
> fix(alternator email recipients): remove alternator@scylladb.com from tests email recipients list

- sdcm/cluster_k8s.py
Override wait_for_nodes_up_and_normal for Minikube scylla cluster: set timeout 20 min
I didn't run the test. It will be tested when we will run longevity
> fix(wait_for_nodes_up_and_normal): Override wait_for_nodes_up_and_normal for Minikube scylla cluster

- sdcm/nemesis.py
For running and testing the GCE backup with bigger loads,
we want to be able to run this nemesis on GCE too.
> feature(ManagementBackup): support backup to google storage

- vars/copyLogsFromSctRunner.groovy
- vars/managerPipeline.groovy
* add support for using sct-runner
* add timeout support for each stage on it's own as
in the `longevityPipeline.groovy`
> refactor(manager_pipeline): add sct-runner support

- jenkins-pipelines/longevity-scylla-operator-3h.jenkinsfile
- sct.py
- sdcm/cluster_k8s.py
- sdcm/logcollector.py
- sdcm/tester.py
- sdcm/utils/common.py
- vars/operatorPipeline.groovy
https://trello.com/c/hClzlcrt/2333-scylla-operator-pipeline-fix-collect-logs
> fix(logcollector): fix collecting for scylla-operator

- sdcm/nemesis.py
- sdcm/utils/common.py
From 'listsnapshots' output we can validate that all asked entities are in the snapshot.
For example, if snapshot was run on keyspace, we can check that all tables/MVs are in the snapshot
> improvement(add validation): Improve snapshot nemesis - add snapshot validation

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/prometheus.py
- sdcm/remote/remote_cmd_runner.py
- sdcm/remote/remote_libssh_cmd_runner.py
- sdcm/sct_events.py
- sdcm/sct_events_analyzer.py
- sdcm/tester.py
- sdcm/utils/grafana.py
- sdcm/utils/remote_logger.py
> Fix test staling issue - making threads as daemon

- test-cases/longevity/longevity-counters-multidc.yaml
Config parameters which enable encryption in
longevity-counter-multidc was removed.
Scylla bench was not updated with supporting the client encryption
Scylla bench exit with exit code and error
gocql: unable to create session: unable to discover protocol version: EOF
> fix(counter_multidc): remove encryption config params

- sdcm/cluster_k8s.py
https://trello.com/c/pQFgkrsb/2362-investigate-why-minikube-runs-are-failing-and-fix-it
> fix(sdcm/cluster_k8s): add enabling ip_forwarding at minikube setup

- defaults/k8s_gce_minikube_config.yaml
> improvement(operator): bump version to 0.2.4

- sdcm/utils/version_utils.py
* Closes: #2430
* Trello: https://trello.com/c/StPEq5j3
> fix(version_utils.py): Enabled get Scylla version from private repo

- sdcm/cluster.py
- sdcm/logcollector.py
- sdcm/tester.py
Trello: https://trello.com/c/yMnU9ZeR/1563-add-check-of-create-zip-targz-archive-in-logcollector
Should fix #2634 and #2627
> improvement(logcollector): check arhives before transfers

- test-cases/cdc/cdc-replication-longevity.yaml
Should help debugging failures.
> cdc replication longevity: add a monitor node

- sdcm/utils/common.py
to handle situations when test failed in first hour of the run
we used a logic that was cleaning SCT runner if the runner is
running more than 20 minutes and there are instances left running.
This logic was wrong since it ignored the keep post behavior.
> fix(clean_sct_runners): fixing issue #2661 incorrect cleaning logic

- sdcm/tester.py
> fix(sdcm/tester.py): fix to not show if only main thread here

- sdcm/cluster_k8s/__init__.py
https://trello.com/c/HpgLCRp7/2369-fix-helm-33-issue
> fix(sdcm/cluster_k8s): freeze helm version

- vars/runSctTest.groovy
Trello: https://trello.com/c/hn8PiXrN/2378-byo-longevity-doesnt-work
> fix(runSctTest): assign update_db_packages conditionally

- sdcm/nemesis.py
Trello: https://trello.com/c/YdCFneK3/2380-fix-problem-with-randomly-called-growshrink-disrupt
> improvement(nemesis): join ..GrowShrink.. nemeses

- sdcm/cluster.py
- sdcm/cluster_docker.py
- sdcm/sct_events.py
- sdcm/utils/health_checker.py
- unit_tests/test_utils_health_checker.py
Trello: https://trello.com/c/tSVvqcWH/2122-add-a-retry-to-the-health-validator
> improvement(health_checker): add a retry to health validator

- defaults/aws_config.yaml
https://trello.com/c/kr7qqiaf/2359-handle-c-s-java-crashes
> fix(defaults/aws_config.yaml): set default loader to v12 with java-11 on board

- sct.py
- sdcm/report_templates/results_base.html
- sdcm/send_email.py
> feature(email_reports): include direct links for the logs

- vars/runSctTest.groovy
> fix(vars/runSctTest.groovy): jenkins throws operation not supported

- sdcm/utils/health_checker.py
check_schema_agreement_in_gossip_and_peers - check for None gossip and peers info
> fix(check_schema_agreement_in_gossip_and_peers): check for None gossip and peers info

- vars/perfRegressionParallelPipeline.groovy
> fix(vars/perfRegressionParallelPipeline.groovy): fix provision_type to on_demand

- jenkins-pipelines/perf-regression-latency-30min.jenkinsfile
> fix(perf-regression-latency-30min.jenkinsfile): increase timeout

- test-cases/longevity/longevity-lwt-basic-3h.yaml
> Fix longevity lwt timeout

- jenkins-pipelines/upgrade-scylla-k8s-minikube.jenkinsfile
- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
- sdcm/fill_db_data.py
- sdcm/utils/version_utils.py
- test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml
- upgrade_test.py
https://trello.com/c/sWCQbKAA/2344-scylla-upgrade-rollback-on-kubernetesminikube
> test(upgrade_test.py): implement kubernetes scylla upgrade test

- sdcm/cluster_k8s/__init__.py
Fixes #2746 except cases which requires certificates (tracked by separate issue: #2744)
> improvement(cluster_k8s): limited support for append_scylla_yaml

- vars/byoOperatorPipeline.groovy
- vars/operatorPipeline.groovy
> fix(operator): remove default operator version from jobs

- defaults/test_default.yaml
as part of what agreed, we are moving to the new brach
mainly for the support of manager-2.2
> feature(monitoring): switch to branch-3.5

- sdcm/remote/remote_file.py
- unit_tests/test_remoter.py
will fix:
```
Sep 08 21:55:50 artifacts-gce-image-jenkins-db-node-10cc16f1-0-1 scylla[6051]:  [shard 0] init - Startup failed: std::filesystem::__cxx11::filesystem_error (error system:13, filesystem error: open failed: Permission denied [/etc/scylla/scylla.yaml])
```
> feature(remote_file): add ability to preserve permissions and ownership

- test-cases/longevity/longevity-alternator-3h.yaml
> fix(longevity-alternator-3h.yaml): Add timeout to ycsb

- jenkins-pipelines/longevity-scylla-operator-3h-minikube.jenkinsfile
- jenkins-pipelines/upgrade-scylla-k8s-gke.jenkinsfile
- test-cases/scylla-operator/kubernetes-scylla-upgrade-gke.yaml
- test-cases/scylla-operator/kubernetes-scylla-upgrade-minikube.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-minikube.yaml
> test(operator): update GKE jobs

- sdcm/nemesis.py
> fix(nemesis): to recognize gke as kubernetes

- sdcm/cluster_k8s/__init__.py
> fix(cluster_k8s): increase waiting timeout

- defaults/k8s_gce_minikube_config.yaml
- defaults/k8s_gke_config.yaml
- sdcm/k8s_configs/operator.yaml
Trello: https://trello.com/c/LJbU7UDY/2423-update-cert-manager-version-to-103
> improvement(operator): bump cert-manager version to 1.0.3

- sdcm/nemesis.py
- unit_tests/test_nemesis.py
> fix(nemesis): does not recognize gke as kubernetes

- mgmt_cli_test.py
> fix(manager): turned the throttle value into int

- sdcm/remote/kubernetes_cmd_runner.py
- unit_tests/test_remoter.py
https://trello.com/c/sY1HNzYO/2367-investigate-why-k8s-remoter-is-unstable
> fix(kubernetes_cmd_runner): make it threadsafe

- sdcm/logcollector.py
upgrade to scylla monitoring 3.5 bring new grafana version
and gui changes on pages.
- Updated the css selector to find the correct path to get snapshot
- Added ability to set css selector per page for taking snapshot
> fix(grafana_snapsho): fix dom selector for monitoring 3.5

- jenkins-pipelines/manager/centos-manager-backup-gce-1tb.jenkinsfile
- longevity_test.py
- sct.py
- sdcm/cluster.py
- sdcm/cluster_gce.py
- sdcm/sct_config.py
- test-cases/manager/manager-backup-1TB-gce.yaml
New job for doing initial benchmark on GCE with dataset of 1TB
> feature(manager): adding manager backup job 1TB for GCE

- sdcm/nemesis.py
https://trello.com/c/9Bdugxvt/2438-gke-check-abortrepairmonkey-failure
Stop AbortRepairMokney producing following output during normal run:
```
19:10:17  < t:2020-10-15 12:10:16,354 f:nemesis.py      l:801  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method abort_repair
19:10:17  < t:2020-10-15 12:10:16,354 f:nemesis.py      l:486  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: AbortRepairMonkey
19:10:17  < t:2020-10-15 12:10:16,365 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > 2020-10-15 12:10:16.354: (DisruptionEvent Severity.NORMAL): type=start name=AbortRepairMonkey node=Node longevity-200gb-48h-verify-limited--db-node-5c4eb2dd-4 [54.170.190.142 | 10.0.2.157] (seed: False) duration=None
19:10:27 …
```
> fix(disrupt_abort_repair): make it less confusing

- test-cases/longevity/longevity-lwt-1loader-3h.yaml
- test-cases/longevity/longevity-lwt-24h-multidc.yaml
- test-cases/longevity/longevity-lwt-500G-3d.yaml
- test-cases/longevity/longevity-lwt-basic-24h-1dis-2nondis.yaml
- test-cases/longevity/longevity-lwt-basic-24h.yaml
- test-cases/longevity/longevity-lwt-basic-3h.yaml
- test-cases/performance/perf-regression-latency-lwt-big.yaml
- test-cases/performance/perf-regression-latency-lwt-small.yaml
- test-cases/performance/perf-regression-throughput-lwt-big.yaml
- test-cases/performance/perf-regression-throughput-lwt-small.yaml
> fix(lwt tests): scylla-qa-loader-ami-lwt-v5 image was reloaded to eu-west-1

- defaults/aws_config.yaml
> fix(aws_config): set aws_root_disk_size_db to 30

- jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
- jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
> refactor(rolling-upgrade): Changed the base version to 4.2

- defaults/k8s_gce_minikube_config.yaml
- defaults/k8s_gke_config.yaml
- sdcm/k8s_configs/operator.yaml
* `scyllaArgs` option added (unblock us to support SCYLLA_ARGS for k8s)
* New options added for Scylla Manager: `backups` and `repairs`
* New resource `MutatingWebhookConfiguration` added to operator' configuration
> improvement(operator): bump operator version to v0.3.0

- jenkins-pipelines/upgrade-scylla-k8s-minikube.jenkinsfile
> fix(minikube upgrade test): set correct path to yaml

- mgmt_cli_test.py
```python
In [1]: LooseVersion("2019.1").version[0] == "2019"
Out[1]: False
```
> fix(mgmt_cli_test): compare 2019 as a number

- sdcm/nemesis.py
> fix(nemesis.py): Disabling TruncateMonkeyLargePartition nemesis

- configurations/rolling-upgrade-with-null-inserts.yaml
- data_dir/c-s_null_inserts.yaml
- jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile
- sdcm/sct_config.py
- test-cases/upgrades/generic-rolling-upgrade.yaml
- upgrade_test.py
> Generic upgrade test and null_inserts test

- upgrade_test.py
Since the test could execute the upgradesstable stage before jmx is up,
and as a result, fail, I added a wait for the jmx to be up on all of the nodes
> fix(rolling-upgrade): Added a wait for the jmx to start

- sdcm/utils/common.py
- sdcm/utils/docker_utils.py
> improvement(docker): add the name to a Container str

- sdcm/utils/common.py
- unit_tests/test_config.py
> fix(config_test): make it pass + refactor of get_branched_repo()

- sdcm/cluster_gce.py
May happen that spot instance was preempted during instance creating. This instance won't be
destroyed but stopped and stays with the name in the instances pool. In this case we should
destroy this instance before creating new one
> fix(gce failing spot): GCE failing during setup of spot instances

- defaults/k8s_gke_config.yaml
- docs/configuration_options.md
- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
- sdcm/cluster_k8s/gke.py
- sdcm/cluster_k8s/iptables.py
- sdcm/k8s_configs/gke-loaders.yaml
- sdcm/sct_config.py
- sdcm/tester.py
Trello: https://trello.com/c/3rF5SOb9/2445-run-loader-nodes-inside-k8s
> feature(k8s-gke): put loaders into GKE cluster

- upgrade_test.py
* Change "self.db_cluster.node.check_node_health()" to
"node.check_node_health()"
> fix(upgrade_test.py): Fixing "test_generic_cluster_upgrade"

- defaults/k8s_gce_minikube_config.yaml
- defaults/k8s_gke_config.yaml
> fix(operator): bump default Scylla version to 4.2.1

- artifacts_test.py
Make sure that in the GCE/AMI artifacts test Scylla configuration that was asked in
user-data is read and set.
Check that cluster name is set.
> improvement(ami/gce artifact test): Scylla configuration that was asked in user-data is read and set

- sdcm/results_analyze/__init__.py
> fix(check_regression_multi_baseline): don't raise exception when no test found

- sdcm/nemesis.py
https://trello.com/c/vs8ZCLbK/2319-backup-snapshot-multiple-tables-nemesis-using-manager
> feature(nemesis): new manager nemesis that backs up specific kespaces

- data_dir/cdc_profile_400gb.yaml
- data_dir/cdc_profile_400gb_postimage.yaml
- data_dir/cdc_profile_400gb_preimage.yaml
- data_dir/cdc_profile_400gb_preimage_postimage.yaml
- jenkins-pipelines/longevity-cdc-3d-400gb.jenkinsfile
- test-cases/longevity/longevity-cdc-3d-400gb.yaml
Added new job for testing cdc feature which is ready for GA.
New job will be run for 3d and operate with dataset size 400GB
> test(cdc-400gb-3d): New cdc job 3d 400gb dataset

- sdcm/logcollector.py
- sdcm/tester.py
- sdcm/utils/common.py
https://trello.com/c/bP9GrRRl/2536-gke-make-log-collecting-for-gke-cluster
> fix(logcollector): make GKE logs collected
