scylladb/scylla-cluster-tests

- jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-mulitenant-eks.jenkinsfile
- longevity_operator_multi_tenant_test.py
- sdcm/tester.py
- sdcm/utils/operator/miltitenant_common.py
- test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
- unit_tests/test_config.py
- unit_tests/test_data/test_config/multitenant/same_stress_cmd_for_all_tenants.yaml
- unit_tests/test_data/test_config/multitenant/unique_stress_cmd_per_tenant.yaml
This commit is part of support operator multi-tenant longevity.
Add new multitenant longevity test
> test(mulitenant longevity): add new longevity test

- test-cases/gemini/gemini-3h-with-nemesis.yaml
In 2021.1 maintanence releases no need for updates
of Gemini tool version.
Previous 2021.1 Gemini runs failed with: https://github.com/scylladb/gemini/issues/273
It shouldn't reproduce with 1.7.5.
Trello: https://trello.com/c/PNnpLS8L
> fix(gemini): pin gemini version to the stable one

- data_dir/scylla-dash-per-server-nemesis.master.json
Trello: https://trello.com/c/YEn4IjEa
When several stress tools running in parallel or different operations
of same stress tool running in parallel, it is difficult to see on
latancies panels, what operations trigger latency without disabling
them per  pannel one by one.
Splitting latency panels per tool and operation by modifying
dashboard source file
> Split stress tools latencies panels

- sdcm/provision/common/utils.py
- sdcm/utils/syslogng.py
since we changed in https://github.com/scylladb/scylla-cluster-tests/pull/5026 syslog-ng to use the `syslog` protocol
we need to match the rsyslog configuration to match the
`RFC5424` protocol
we need this since in some cases we still have a fallback that
uses rsyslog, if syslog-ng wasn't installed correctly.
(happens mostly with older scylla images which are centos8 based,
but we need those for upgrades or oracle in gemini tests)
we also need to add the `octet-counted` TCP_Framing, to support
the multiline messages, see [1] for more details
1: https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html#tcp-framing
> fix(rsyslog): change template to RSYSLOG_SyslogProtocol23Format

- docker/cassandra-harry/Dockerfile
- docker/cassandra-harry/README.md
- docker/cassandra-harry/image
- sdcm/cassandra_harry_thread.py
- sdcm/cluster.py
- sdcm/tester.py
- test-cases/longevity/longevity-harry-2h.yaml
- unit_tests/test_cassandra_harry.py
As part of the plan to move all stress tools/loaders into docker
images, we move `cassandra-harry` into a docker image
we'll create/maintine.
there an intergation test for it, but it's not complate, since
we don't yet have a setup to run a docker base cluster for those
integration tests, and harry can't work with one node.
> feature(cassandra-harry): move to run on docker base image

- sdcm/utils/common.py
Currently you needed to prefix the version if you wanted enterpise
```bash
list-images -v enterprise-2022.1
list-images -c gce -r us-west4 -v enterprise-2022.1.rc9
```
now you would be able to call without `enterprise-` prefix:
```bash
list-images -v 2022.2.0.rc0
list-images -c gce -r us-west4 -v 2022.2.0.rc0
```
> fix(list-images): make enterprise version work without prefixing

- configurations/manager/ubuntu22.yaml
- jenkins-pipelines/manager/ubuntu22-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/ubuntu22-manager-upgrade.jenkinsfile
- sdcm/mgmt/cli.py
Since scylla enterprise 2022.1 was released, and with it the support of ubuntu 22,
we can now create manager test scenarios for ubuntu 22
> test(manager): Added ubuntu 22 sanity and upgrade test scenarios

- test-cases/longevity/longevity-10gb-3h.yaml
recently we start getting too much spot termination, an out of
capacity for this job, it was decided to change it to use
`i4i.2xlarge`
data from spot advisor
```
type            cpu     mem   saving    chances for distruption
--------------------------------------------------------------
i3.4xlarge	16	122	57%	>20%
i4i.2xlarge	8	64	70%	<5%
```
> fix(longevity-10gb-3h): switch AWS instance type to `i4i.2xlarge`

- docs/docker-loaders.md
Adding the design for moving to all stress tools to be docker based
> feature(docker-based-loaders): adding the design

- sdcm/cluster.py
- sdcm/logcollector.py
- sdcm/nemesis.py
- sdcm/utils/common.py
The kallsyms map for kernel debug should be collected
dynamically every node boot.
Trello: https://trello.com/c/lokjpJC7
Extending requested support of: https://github.com/scylladb/scylla-cluster-tests/issues/4054#issuecomment-1057300552
> improvement(collect kallsyms): Collect Seastar kallsyms on boot

- defaults/azure_config.yaml
We are having problems with centos repositories - sometimes they fail
and it is breaking tests on preparing loaders/monitor.
Fix is by switching to Ubuntu OS for loaders and monitor.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5060
> fix(azure): use ubuntu for loader and monitor on Azure

- sdcm/nemesis.py
If nemesis call from wrapper fails, print traceback in the log
> improvement(nemesis): print traceback in log

- sdcm/utils/version_utils.py
latest runs of rolling upgrade tests failed due to error:
Wrong url:
The following repository URL "...' is incorrect.
The generated URl contains wrong part of architecture regexp match:
'... /binary-arm64 signed-by=/etc/apt/keyrings/scylladb.gpg/Packages'
where string after space is wrongly added.
Fixing regexp to match only architecture types
Failed job: https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ubuntu18.04-test
> fix(version_utils): improve regexp for architecture part

- defaults/severities.yaml
- sct.py
- sdcm/db_stats.py
- sdcm/sct_events/workload_prioritisation.py
- sla_per_user_system_test.py
- test_lib/sla.py
1. After data preparing wait for compactions finish, before start test
2. Add pass/failed criteria for cache only test.
Event example:
```
2022-08-10 09:51:18.017: (WorkloadPrioritisationEvent Severity.NORMAL) period_type=not-set event_id=beaadf2d-5419-47e2-90f7-be5403833c32: type=SlaTestResult message=Actual improvement is 31.35185185185185 more then 1.8 as expected.
```
Tested with 3 scenarios:
- [features-sla-read-50perc-write-50perc-load-test](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/features-sla-read-50perc-write-50perc-load-test/4/)
- [features-sla-read-throughput-1to5-ratio](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/yulia-sla-read-throughput-1to5-ratio-2021.1/37/)
- [features-sla-read-throughput-vs-latency-cache-only-test](https://jenkins.scy …
> fix(sla test): wait for compactions finish and add pass/failed criteria

- sdcm/fill_db_data.py
The '~' character like in "5.1.0~rc0" was incorrectly parsed
by pkg_resources parse_version
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5164
> fix(fill_db_data.py): Parse scylla version with tilde sign

- sdcm/cluster.py
- sdcm/cluster_azure.py
- sdcm/provision/azure/ip_provider.py
- sdcm/provision/azure/provisioner.py
- sdcm/provision/azure/resource_group_provider.py
- sdcm/provision/azure/virtual_machine_provider.py
- sdcm/provision/azure/virtual_network_provider.py
- sdcm/provision/provisioner.py
- sdcm/sct_provision/instances_provider.py
- sdcm/sct_provision/region_definition_builder.py
- sdcm/sct_runner.py
- sdcm/tester.py
- unit_tests/lib/fake_provisioner.py
- unit_tests/lib/fake_resources.py
- unit_tests/provisioner/conftest.py
- unit_tests/provisioner/test_azure_region_definition_builder.py
- unit_tests/provisioner/test_provision_sct_resources.py
- unit_tests/provisioner/test_provisioner.py
- unit_tests/test_cluster.py
SCT does not support availability zones for Azure backend.
This commit adds handling it for Azure (and unified provisioning).
> feature(azure): handle availability zone

- defaults/test_default.yaml
- sdcm/sct_events/database.py
as part of the effort of reducing latency, reactor
stalls play a very important role in it, so since
we already had some improvements in Scylla side,
we are now reducing the thresholds in SCT as well,
to be able to catch easier anything that will deviate
from the expected.
the minimum threshold (also default in Scylla) is now
25 ms (it will raise `DEBUG` events in SCT), and from
500 ms we will raise `ERROR` events in SCT.
important to remind that every reactor stall event
with `ERROR` level, must be reported as an issue
in ScyllaDB repo.
Refs: scylladb/qa-tasks#366
> improvement(reactor stall): reduce detector and tolerable

- sdcm/nemesis.py
Issue: https://github.com/scylladb/scylla-cluster-tests/issues/5179
When run a few parallel nemesis threads, first thread disruption methods
are wrapped only. In other threads disruption methods are not wrapped.
Revert using wrapped_disruptive_methods list. Need find better solution
> fix(nemesis): revert using wrapped_disruptive_methods list

- .github/auto_assign.yml
- .github/workflows/auto_assign.yaml
Adding action that would automaticlly assign a PR
or issue to the author of it.
Ref: https://github.com/marketplace/actions/auto-assign-action
> feature(github-actions): add auto assign action

- .github/auto_assign.yml
- .github/workflows/auto_assign.yaml
move to action that can handle both PRs and issues
Ref: https://github.com/marketplace/actions/assign-author
> feature(github-actions): switch to different actions for auto assign

- sdcm/sct_runner.py
After recent change for handling availability zone in Azure, SCT fails
when listing sct-runners for tests from old branches where az is not
set.
This commit fixes it.
> fix(azure): fix list instances when missing az

- sdcm/utils/udf.py
- sdcm/utils/udf_scripts/lua_var_length_counter.yaml
- sdcm/utils/udf_scripts/xwasm_fib.yaml
- sdcm/utils/udf_scripts/xwasm_plus.yaml
- unit_tests/test_udf.py
To allow us to use user defined functions in SCT
we need a way to store, load and handle UDFs.
This PR introduces some sample scripts in Lua
and WASM along with the infrastructure for loading,
representing and handling them. The UDF class
allows to represent a UDF and create queries for
creating the UDF in Scylla.
https://github.com/scylladb/qa-tasks/issues/406
> feature(udf): udf class, loader, scripts and unit tests

- defaults/test_default.yaml
- sdcm/sct_config.py
- sdcm/tester.py
- sdcm/utils/aws_utils.py
- test-cases/artifacts/ami.yaml
In order to avoid a specific AWS availability zone instance capacity limitation,
SCT can try all availability zones one by one in order to maximize 
the chances of getting the requested instance capacity.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5119
https://trello.com/c/5rg6tNqD
> improvement(availability zone): Fallback availability zones in AWS instance provisioning

- sdcm/utils/version_utils.py
- unit_tests/test_version_utils.py
Since we can't trust that the lastest image in dockerhub
would have an identical sha versioned image, (since multiple
images of the same git sha can be built in the same day)
we are switching to get the lastest docker tag from the
relocatable latest folder on s3 (same as dtest is doing
to get the latest versions)
only downside that this is before the docker artifact test
is running, and not from the same time an image get promated
into dockerhub.
once we'll have an equvielent location for the docker image
promoation, we could move to that.
> fix(get_specific_tag_of_docker_image): get tag from build info

- jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
- jenkins-pipelines/rolling-upgrade-centos7-ldap-authorization.jenkinsfile
- jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile
same version
we won't support upgrades from 4.3 (it is now deprecated)
but we want to have upgrade from latest of same version
(2021.1), to the current patch being released.
> improvement(upgrade base_version): remove deprecated and add lastest of

- docker/scylla-sct/ubuntu/Dockerfile
- sdcm/cluster_docker.py
- sdcm/utils/docker_remote.py
- sdcm/utils/remotewebbrowser.py
Since we are trying to use only docker for the stress tools,
we need the docker backend loader node to be able to spin up dockers
so we mount the docker socket file, and run the commands with `sudo`
since the `scylla-test` user we use doesn't have premission on the
host docker. right now it mean it won't be working ontop of podman.
later we could consider remove the loader nodes, and run everything
local as we do for the monitoring node
> feature(docker_backend): support running docker based loaders

- sdcm/provision/azure/utils.py
- unit_tests/provisioner/test_azure_get_scylla_images.py
- unit_tests/provisioner/test_data/SCYLLA-IMAGES/azure_images_list.json
Recently there was a change with tag names, they were renamed from
CamelCase to snake_case e.g.`ScyllaVersion` to `scylla_version`.
Azure list images needs to be adapted to this change.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5068
> fix(azure): adapt to scylla version new tag name

- .github/workflows/auto_assign.yaml
Since we are opening PRs from forks, we need a diffrent trigger
so to grant the needed premissions
> fix(github-actions): switch to use `pull_request_target`

- sct.py
- sdcm/sct_runner.py
Allow the users to specify the use the --force flag, which
allows to remove the runner without running any logic for
tag values.
> fix(sct_runner): add force option

- sdcm/sct_events/group_common_events.py
- unit_tests/test_cluster.py
- upgrade_test.py
In one upgraded test, the cdc error (Could not find CDC generation with
timestamp) raised before 9042 is ready, but the SCT event was delayed 3+ mins,
it's after db is up, so it won't be ignored.
This patch tried to extend the time to ignore cdc error, I know it's not
a grace solution.
Fixes: #4451
(cherry picked from commit 4c9a7dd2719fcab8c9da01d051ec0d1368993fa1)
> fix(upgrade test): extend the time to ignore cdc error

- data_dir/scylla-dash-per-server-nemesis.2021.1.json
Group format in 'scylla_scheduler_runtime_ms' metrix has been changed.
Fix the query accordingly
> fix(dashboard): scheduler runtime query

- docker/scylla-bench/Dockerfile
- docker/scylla-bench/README.md
- performance_regression_row_level_repair_test.py
- sdcm/cluster.py
- sdcm/cluster_docker.py
- sdcm/cluster_k8s/__init__.py
- sdcm/scylla_bench_thread.py
- sdcm/tester.py
- unit_tests/test_scylla_bench_thread.py
As part of the plan to move all stress tools/loaders into docker
images, we move `scylla-bench` into a docker image
we'll create/maintine.
* part of the move we removed the `use_single_loader` option
since it's identical to round_robin, for the usage needed
to run stress on one node.
> feature(scylla-bench): move to run on docker base image

- README.rst
- defaults/test_default.yaml
- docs/configuration_options.md
- sct.py
- sdcm/cdclog_reader_thread.py
- sdcm/kcl_thread.py
- sdcm/ndbench_thread.py
- sdcm/nosql_thread.py
- sdcm/sct_config.py
- sdcm/scylla_bench_thread.py
- sdcm/utils/common.py
- sdcm/ycsb_thread.py
- unit_tests/test_config.py
- unit_tests/test_data/stress_image_extra_config.yaml
One level of nesting is now possible to be passed via
environment variables.
```
SCT_STRESS_READ_CMD.0="cassandra_stress"
SCT_STRESS_READ_CMD.1='["cassandra_stress", "cassandra_stress"]'
SCT_STRESS_IMAGE='{"ycsb": "scylladb/something_else"}'
SCT_STRESS_IMAGE.cassandra-stress="scylla-bench"
SCT_STRESS_IMAGE.scylla-bench="scylladb/something"
> feature(sct_config): nested values from environment variables

- sdcm/provision/azure/utils.py
- sdcm/utils/version_utils.py
Due multiple changes in list images function in Azure, backporting
manually all related changes.
> fix(azure): backport list images for Azure

- sdcm/tester.py
- sdcm/ycsb_thread.py
changes 6d99d363fd501dec5292c05725870753cc69b910 had a two
bugs in it, fixing them:
* for scylla-bench make sure params are being passed down to
the thread.
* fix typo in the key value in ycsb
Fix: #5217
> fix(docker-stress): make sure params is passed

- test-cases/artifacts/docker.yaml
this unnecessary parameter was causing collect_logs
stage to fail.
> fix(artifacts_docker): remove unnecessary param

- defaults/k8s_eks_config.yaml
- defaults/k8s_gke_config.yaml
More recent K8S versions are required because the one we use now
is too old and soon will not be supported by EKS and GKE.
Update also cert-manager version because this old version we use
won't work on newer K8S versions due to API changes.
> improvement(EKS,GKE): use more recent K8S and cert manager versions

- sdcm/gemini_thread.py
since we have metrics being read by the monitor directly
from gemini process, we should move to use host networking for
that metric to be working (some upgarde test are using that metric
to understand that the gemini command started)
one note is, that this mean that running multiple gemini commands
on the same loader at the same time, only the first is sending
metrics (it's not related to docker, seem like it always was the
case).
Fixes: #5214
> fix(gemini_thread): enable docker host networking

- defaults/test_default.yaml
- docker/scylla-bench/README.md
* Add possibility to configure retry policy scylladb/scylla-bench#96
* use cluster.Keyspace before connecting to the nodes scylladb/scylla-bench#97
Ref: https://github.com/scylladb/scylla-bench/pull/96
Ref: https://github.com/scylladb/scylla-bench/pull/97
> feature(scylla-bench): move to using `scylla-bench==v0.1.9`

- defaults/test_default.yaml
- docker/gemini/image
- docs/configuration_options.md
- sdcm/cluster.py
- sdcm/gemini_thread.py
- sdcm/sct_config.py
- test-cases/cdc/cdc-15m-replication-gemini.yaml
- test-cases/cdc/cdc-15m-replication-postimage.yaml
- test-cases/cdc/cdc-15m-replication-preimage.yaml
- test-cases/cdc/cdc-replication-longevity.yaml
- test-cases/gemini/gemini-1tb-10h.yaml
- test-cases/gemini/gemini-3h-cdc-postimage-write.yaml
- test-cases/gemini/gemini-3h-cdc-preimage-write.yaml
- test-cases/gemini/gemini-3h-cdc-write.yaml
- test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
- test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-3h-with-nemesis.yaml
- test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-8h-large-num-columns.yaml
- test-cases/gemini/gemini-basic-3h-ics.yaml
- test-cases/gemini/gemini-basic-3h.yaml
- test-cases/upgrades/rolling-upgrade.yaml
- unit_tests/test_config.py
- unit_tests/test_data/test_scylla_yaml_builders/cdc-replication-longevity.yaml
- unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.yaml
Fix for several gemini issues:
https://github.com/scylladb/gemini/issues/273
https://github.com/scylladb/gemini/issues/272
https://github.com/scylladb/gemini/issues/271
Support request and connect timeouts
Ref: https://github.com/scylladb/gemini/pull/274
> feature(gemini): upgrade to version 1.7.7

- sdcm/monitorstack/ui.py
After new panels were added to sct dashboard,
the old size of screenshot is not enough,
because several first panels are scroll out
from view.
refers to: https://github.com/scylladb/scylla-cluster-tests/issues/5224
> fix(SCTDashboard): increase screenshot size

- unit_tests/conftest.py
- unit_tests/lib/alternator_utils.py
- unit_tests/test_alternator_streams_kcl.py
- unit_tests/test_cassandra_harry.py
- unit_tests/test_gemini_thread.py
- unit_tests/test_ndbench_thread.py
- unit_tests/test_scylla_bench_thread.py
- unit_tests/test_ycsb_thread.py
since now all those docker based tests are reading the docker
images from configuration, it should have the default configuration
to get any of the docker images
> test(functional): docker functional test with SctConfiguration

- docker/scylla-sct/ubuntu/Dockerfile
Following https://github.com/scylladb/scylladb/pull/11440 (Scylla docker image to be based on Ubuntu:22.04)
Few modification were needed in SCT side in order to get docker artifact test to pass.
`conllectd` package was removed from Ubuntu repo and was removed
SCT uses ssh for connecting the nodes. and since our keys are RSA we need to make sure RSA is enable in sshd configuration
> fix(docker/scylla-sct/ubuntu/Dockerfile): Add support for ubuntu22.04

- sdcm/fill_db_data.py
Fix in sb: commit e2193213e7eed48f128e55a4b1dbff7ad9e62fe0 require that keyspace have to be created for creating session
Create keyspaces for scylla-bench tool on upgrade tests
> fix(upgrade_test): Create s-b keyspace before run stress

- longevity_test.py
Both #5061, #4684, tried to add the list of nodes to the stress commmand, but both wasn't tested with the actuall test case
so we ened up with python list, and not comma seperated list that is expected:
```
cassandra-stress user profile=/tmp/templated_tables_mvz4no57b5.yaml
cl=QUORUM 'ops(insert=1, read1=5)' duration=55m -rate threads=2 -errors
skip-unsupported-columns ignore -node ['10.4.3.37', '10.4.0.123',
'10.4.2.11', '10.4.0.153', '10.4.2.45', '10.4.0.188']
```
Ref: #5061, #4684
> fix(batched_tests): convert node list into comma separated list

- functional_tests/scylla_operator/libs/helpers.py
- functional_tests/scylla_operator/test_functional.py
- sdcm/cluster_k8s/mini_k8s.py
Add a functional test case that does the same steps as
the `disrupt_nodetool_flush_and_reshard_on_kubernetes` nemesis does to cover the bug [1].
[1] https://github.com/scylladb/scylladb/issues/11353
> test(k8s): add flush and reshard functional test

- sdcm/cluster.py
prometheus stop supporting single dash in parameter. It cause failed to start scylla-monitoring.
fix issue #5250
> fix(scylla_monitoring_start): remove depricated single dash prom flag

- sdcm/utils/data_validator.py
- unit_tests/conftest.py
- unit_tests/test_data/test_data_validator/lwt-basic-3h.yaml
- unit_tests/test_data/test_data_validator/no-validation-views-lwt-basic-3h.yaml
- unit_tests/test_utils_data_validator.py
Add unit test to check list of tuples of correlated view names for
validation of update columns test
> test(unittest): data validator

- jenkins-pipelines/longevity-150gb-asymmetric-cluster-12h.jenkinsfile
- test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml
Now test runs 7 hours instead of 12. Fix it.
@roydahan @fruch 
The data set is about 140GB on every node is created. Should I decrease it or rename the test?
> fix(longevity): adjust assymetric 12h test

- defaults/test_default.yaml
- jenkins-pipelines/longevity-sla-100gb-4h.jenkinsfile
- longevity_sla_test.py
- sdcm/sct_config.py
- test-cases/longevity/longevity-sla-100gb-4h.yaml
- test_lib/sla.py
Configure two SLA roles and run two stress threads with these roles.
This is first basic longevity test. Run different nemeses including disruptive (terminate and replace node, restart scylla server, decommission etc)
Refs https://github.com/scylladb/qa-tasks/issues/387
> test(longevity): add sla basic longevity test

- defaults/test_default.yaml
- unit_tests/conftest.py
- unit_tests/test_scylla_bench_thread.py
* https://github.com/scylladb/scylla-bench/pull/101
fixes errors like the following:
```
Keyspace 'ks_truncate_large_partition' does not exist
```
> fix(scylla-bench): upgrade to version v0.1.10

- defaults/test_default.yaml
PR #5238 wrongly didn't pushed out the correct working docker image hence it was failing to run, casue it hase missing python2 inside the image
> fix(ycsb): upload image that has python2 installed

- jenkins-pipelines/artifacts-amazon2-arm.jenkinsfile
- jenkins-pipelines/artifacts-centos7.jenkinsfile
- jenkins-pipelines/artifacts-centos8-arm.jenkinsfile
- jenkins-pipelines/artifacts-centos8-selinux.jenkinsfile
- jenkins-pipelines/artifacts-centos8-web.jenkinsfile
- jenkins-pipelines/artifacts-centos8.jenkinsfile
- jenkins-pipelines/artifacts-debian10-arm.jenkinsfile
- jenkins-pipelines/artifacts-debian10.jenkinsfile
- jenkins-pipelines/artifacts-debian11.jenkinsfile
- jenkins-pipelines/artifacts-docker.jenkinsfile
- jenkins-pipelines/artifacts-rocky8.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2004-web.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2004.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2204-arm.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2204-web.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-centos8.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-debian10.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-debian11.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-rocky8.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu1804.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2004.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2204.jenkinsfile
while we are witing for a fix for #5247, this
will be a workaround until we have it figured out.
> fix(artifacts): workaround - increase timeout

- test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
Because of the multiple schema changes happening at the same time, this scenario can fail right after the prepare stage. As such, I amended the scenario's yaml config to pre create the schema.
> fix(tls-ssl-1dis-2nondis-nemesis longevity): pre create schema

- sdcm/utils/uda.py
- sdcm/utils/udas/my_avg.yaml
- sdcm/utils/udas/my_counter.yaml
- sdcm/utils/udf.py
- sdcm/utils/udf_scripts/lua_div.yaml
- sdcm/utils/udf_scripts/lua_simple_return.yaml
- sdcm/utils/udf_scripts/lua_var_length_counter_accumulator.yaml
- unit_tests/test_uda.py
- unit_tests/test_udf.py
This commit introduces infrastructure for handling User Defined Aggregations
in SCT. This includes the UDA class, loader new dir for UDA definitions and
unit tests.
As UDAs are basically made up of UDFs - an accumulator UDF for iterating over
the rows, a final UDF for processing the final result and an optional reducer
UDF for doing a map-reduce style distributed aggregation - UDAs can be
defined via a yaml file in /sdcm/utils/udas dir. Example definitions are
included in this commit.
Task: https://github.com/scylladb/qa-tasks/issues/406
> feature(uda): add User Defined Aggregations support

- sdcm/report_templates/results_base.html
- sdcm/report_templates/results_base_custom.html
- sdcm/report_templates/results_issue_template.html
- sdcm/send_email.py
- sdcm/tester.py
- sdcm/utils/version_utils.py
Developers requested for relocatable pkg url in issues.
This commit adds relocatable url into email report and sends this info to Argus as additional package.
refs: https://github.com/scylladb/qa-tasks/issues/356
> feature(issue-template): add relocatable pkg url to report and argus

- sdcm/cluster.py
now the scylla-bench and gemini are running inside docker we don't need to kill them directly, there's a docker kill command that should stop them.
Fixes: #5264
> fix(kill_stress_thread): remove scylla-bench/gemini kills

- defaults/test_default.yaml
scylladb/scylla-bench#103:
Since we want by default to have retries across the board in SCT
we now set the default as: -retry-number 10 -retry-interval 80ms,1s
> fix(scylla-bench): switch to v0.1.11

- jenkins-pipelines/hydra-show-monitor.jenkinsfile
- sct_ssh.py
since we move to close security groups by default we need to create a security group, for the newly monitor node created in this pipeline
> fix(hydra-show-monitor): add call to `hydra attach-test-sg`

- configurations/arm_instance_types/im4gn_2xlarge.yaml
- jenkins-pipelines/rolling-upgrade-ami-arm.jenkinsfile
This PR adds a new instance type for ARM jobs and a pipeline for a rolling upgrade AMI job running on ARM instances.
Task: https://github.com/scylladb/qa-tasks/issues/337
> test(rolling_upgrade): ami test for ARM instances

- longevity_sla_test.py
- sdcm/cluster.py
- sdcm/scan_operation_thread.py
- sdcm/sct_events/database.py
- sdcm/tester.py
- test-cases/longevity/longevity-sla-100gb-4h.yaml
- test_lib/sla.py
Add support running full scan with SLA credentials
Event example:
```
2022-09-14 12:39:06.985: (FullScanEvent Severity.NORMAL) period_type=begin event_id=87b59479-7eab-4a22-937f-446f64acc547 node=longevity-sla-100gb-4h-test-ful-db-node-476e317f-2 select_from=keyspace1.standard1 user=role600_0 password=rolep600
```
Test passed:
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-sla-fullscan-100gb-4h/9/
> Fullscan support in sla longevity

- artifacts_test.py
- sdcm/cluster.py
335432fadc74bd16130fd6428155651d2a665027 introduced a new check of cqlsh to the artifact tests, seem like the offline test weren't installing python2, and started failing like that:
```
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit:
Encountered a bad command exit code!
Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60
-e "desc keyspaces" 10.142.0.29 9042'
Exit code: 1
Stdout:
Stderr:
No appropriate python interpreter found.
```
> fix(offline_artifacts_test): install python2

- sdcm/cluster.py
- sdcm/utils/health_checker.py
- unit_tests/test_utils_health_checker.py
For the moment, if we fail to get the peers info for some reason, then we get 'Schema agreement is not reached' error running the 'ToggleTableIcs' nemesis.
So, detect specific problems and report correct messages not hiding valueable info.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/5265
> fix(schema-agreement): print proper error messages

- defaults/test_default.yaml
- docs/configuration_options.md
- sdcm/sct_config.py
- test-cases/longevity/longevity-counters-multidc.yaml
- test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
- test-cases/longevity/longevity-large-partition-4days.yaml
- test-cases/longevity/longevity-twcs-48h.yaml
Since we move to using docker based scylla-bench, we don't use that configuration option any more, and need to use a docker image to overide to a diffrent scylla-bench version
scylladb/scylla-bench#92 still need to be investigated and bisected regardless of this change.
Ref: scylladb/scylla-bench#92
> fix(sct_config): remove `scylla_bench_version` configuration option

- jenkins-pipelines/longevity-200gb-48h-network-monkey.jenkinsfile
since the move to the new VPC peering setup, the public addresses are not open by default, and this specific test case need to be working with public addresses.
> fix(longevity-network): change default to `ip_ssh_connections: public`

- sdcm/cluster.py
This debug message was not removed mistakenly.
Also if 'auth_provider' is None, it will fail
This debug message was added by https://github.com/scylladb/scylla-cluster-tests/pull/5259/commits/a25333c89c3034f2b2931bd4644a99bfc4575351
> fix(create_session): remove redundant debug message

- sdcm/cluster.py
older ubuntu distros doesn't have `python2` package, they only have `python2.7` one. so we need to play along.
> fix(artifacts_test): install python2.7 for older ubuntu distros

- sdcm/nemesis.py
nemesis disrupt_load_and_stream should be now
running for latest versions, so removing the decorator that controls the versions, as both 2022.2 and 5.1 should support running this nemesis.
> fix(nemesis): remove version control from nemesis

- sdcm/nemesis.py
skipping enospc nemesis until issue
scylladb/scylladb#11245 will be fixed.
> fix(nemesis): skip enospc nemesis

- functional_tests/scylla_operator/conftest.py
- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
Functional Eks test failed with error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'sct-cluster-us-east1-b-us-east1-0/system.log' sdcm/utils/file.py:66: FileNotFoundError
```
Add waiting for the system.log file creation.
Failed test:
https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-eks/12/
Test with fix passed:
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/operator/job/functional-eks/8/
> fix(functional): wait for system.log file exists on every node

- jenkins-pipelines/artifacts-amazon2-arm.jenkinsfile
- jenkins-pipelines/artifacts-centos7.jenkinsfile
- jenkins-pipelines/artifacts-centos8-arm.jenkinsfile
- jenkins-pipelines/artifacts-centos8-selinux.jenkinsfile
- jenkins-pipelines/artifacts-centos8-web.jenkinsfile
- jenkins-pipelines/artifacts-centos8.jenkinsfile
- jenkins-pipelines/artifacts-debian10-arm.jenkinsfile
- jenkins-pipelines/artifacts-debian10.jenkinsfile
- jenkins-pipelines/artifacts-debian11.jenkinsfile
- jenkins-pipelines/artifacts-docker.jenkinsfile
- jenkins-pipelines/artifacts-rocky8.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2004-web.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2004.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2204-arm.jenkinsfile
- jenkins-pipelines/artifacts-ubuntu2204-web.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-centos8.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-debian10.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-debian11.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-rocky8.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu1804.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2004.jenkinsfile
- jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2204.jenkinsfile
This reverts commit 5a7d937145bc44b541f863d00c0b162e1d5449ce. following https://github.com/scylladb/scylla-cluster-tests/issues/5247#issuecomment-1250939839 we should have the test running and passing within the default timeout.
Fixes: #5247
> Revert "fix(artifacts): workaround - increase timeout"

- sdcm/nemesis.py
At certain occurances, due to delays in log collection, it can take a little while for the Reload SSL message to appear. As such, I encreased the timeout when waiting for reload message.
> fix(disrupt_hot_reloading_internode_certificate): boost reload timeout

- Jenkinsfile
- jenkins-pipelines/artifacts-azure-image.jenkinsfile
- jenkins-pipelines/longevity-10gb-3h-azure.jenkinsfile
- sdcm/provision/azure/ip_provider.py
- sdcm/provision/azure/virtual_machine_provider.py
- sdcm/provision/azure/virtual_network_provider.py
Azure struggles with providing spot instances for basic 10gb longevity test when we set availability zone.
Idea is to unset AZ for 10gb 3h longevity and artifact test, so we don't hit provision issue that often. In that case VM's may be created in different AZ's leading to increased costs.
Cost for between zones transfer is 0.01$/GB. Should not apply to artifact test, as it uses just one VM.
> fix(azure): unset az for basic longevity job

- defaults/severities.yaml
- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/sct_events/database.py
- upgrade_test.py
Recent changes to queue management in Seastar (https://github.com/scylladb/seastar/pull/949)
mean that more powerful nodes should be configured to use the sq_split mode rather than mq.
Changes in this commit are designed to make sure we run the scylla_sysconfig_setup script,
which in turn should runs perftune configures the queue values, on node upgrade and rollbacks.
Trello task: https://trello.com/c/xljGRtoW
> improvement(upgrade): scylla_sysconfig_setup on upgrade / rollback

- sdcm/nemesis.py
If standard c-s schema is not created, the method execute c-s to create it, but run from all nodes which could bring to c-s stack. Set round robin to 1, for running single command
The problem appears in job:
https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-cdc-3d-400gb-test/
> fix(_prepare_test_table): execute single c-s thread

- sdcm/cluster.py
- sdcm/remote/libssh2_client/__init__.py
There are 2 reasons of coredump not creating on timeout error when running nodetool (e.g. in upgrade test when we run: `node.run_nodetool("drain", timeout=3600, coredump_on_timeout=True)`:
1. kind of race condition when `SSHReaderThread` got end event (due timeout) but reader didn't acknowledge that it occured yet. This even lead to sometimes freeze of whole ssh command until CriticalError killed ssh connection.
2. wrong exception handling when running nodetool
This commit fixes both problems.
> fix(run_nodetool): fix coredump on timeout

- sdcm/nemesis.py
- sdcm/tester.py
After decommisioning node, multidc keyspace RF was not set to single-datacenter causing errors in other nemesis.
This commit removes decommissioned dc from this keyspace RF and removes keyspace after nemesis completes.
refs:
https://github.com/scylladb/scylla-cluster-tests/issues/5299 
https://github.com/scylladb/scylla-cluster-tests/issues/5236
> fix(nemesis): add_remove_dc keyspace cleanup

- sdcm/argus_test_run.py
if run sct locally with docker backend, argus error reported to cli output
File "/usr/local/lib/python3.10/site-packages/argus/db/testrun.py",
line 723, in _heartbeat_entry
self.argus.session.execute(bound_statement)
File "cassandra/cluster.py", line 2668, in cassandra.cluster.Session.execute
File "cassandra/cluster.py", line 4953, in cassandra.cluster.ResponseFuture.result
cassandra.InvalidRequest: Error from server: code=2200
[Invalid query] message="Key may not be empty"
> fix(argus_test_run): Don't use argus for local runs with docker

- functional_tests/scylla_operator/libs/helpers.py
`functional_tests/scylla_operator/libs/helpers.py` and `sdcm/nemesis.py` 
have one function ported from one place to another and it happens that we get following pylint error:
R0801: Similar lines in 2 files
==functional_tests.scylla_operator.libs.helpers:[226:237]
==sdcm.nemesis:[1232:1243]
So, fix it by changing the code a bit in the `helpers.py` file to make the pylint be happy.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/5312
> fix(pylint): make it not complain with 'R0801: Similar lines in 2 files'

- test-cases/performance/perf-regression-latency-1TB.yaml
- test-cases/performance/perf-regression-latency-500gb-30min.yaml
- test-cases/performance/perf-regression-user-profiles.yaml
because of https://github.com/scylladb/scylladb/issues/10981#issuecomment-1257045821 we are increasing the threshold of these reactor
stalls to 5 ms, to avoid this issue, until
it is fixed.
once it will be fixed, we will want to revert
this change.
> fix(workaround): reactor stall threshold increase

- defaults/test_default.yaml
- docker/scylla-sct/entry_ssl.sh
- sdcm/utils/docker_remote.py
- unit_tests/conftest.py
- unit_tests/dummy_remote.py
- unit_tests/test_scylla_bench_thread.py
ssl seems broken in scylla-bench==0.1.9 and onwards,
gocql update the ssl package, and now the default in
to enable verification of host, we'll need to disable
it on scylla-bench `InsecureSkipVerify: true`
Ref: https://github.com/scylladb/scylla-cluster-tests/issues/5291
> test(scylla-bench): add new integration test for ssl

- sdcm/tester.py
When gce_image_db contains trailing spaces it fails the test. It's easy to copy/paste image url with additional space at the end.
This commit removes trailing spaces from gce image url when used.
> fix(gce): strip image url

- defaults/severities.yaml
- sdcm/logcollector.py
- sdcm/utils/data_validator.py
Now if rows with unexpected data found while the test, it's impossible to investigate why it happens and where is the problem. This commit present analyzing of failed data and save the result into files.
Refs: https://github.com/scylladb/qa-tasks/issues/348
Tests:
1. With missed rows: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-4.1-longevity-lwt-3h/61/
2. no missed rows: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-4.1-longevity-lwt-3h/62/
> improvement(data validator): improve investigation ability

- sdcm/nemesis.py
- upgrade_test.py
In https://github.com/scylladb/scylla-cluster-tests/pull/1912 timeout was introduced to `nodetool drain` command. Timeout value was not discussed in PR and it seems to be too big (1h).
This commit sets `nodetool drain` timeout to 15 minutes. After that time coredump should be created for analysis.
> fix(drain): fix timeout for nodetool drain command

- sdcm/utils/data_validator.py
longevity-lwt-500G-3d-test failed with error:
```
AlreadyExists: Table 'cqlstress_lwt_example.blogposts_update_one_column_lwt_indicator_expect' already exists
```
It happened because of test-cases/longevity/longevity-lwt-500G-3d.yaml runs the same user profile a few times, so list of view names is not unique, like:
```
['blogposts_update_one_column_lwt_indicator', 'blogposts_update_2_columns_lwt_indicator', 'blogposts_update_one_column_lwt_indicator', 'blogposts_update_2_columns_lwt_indicator', 'blogposts_update_one_column_lwt_indicator', 'blogposts_update_2_columns_lwt_indicator']
```
> fix(data validator): list of unique view names with same elements order

- data_dir/scylla-dash-per-server-nemesis.master.json
SLA scheduler runtime panel exists in 2021.1 dashboard but missed in master/2022. Add it
Refs: https://github.com/scylladb/qa-tasks/issues/804
> fix(dashboard): add SLA scheduler runtime panel

- sdcm/sct_events/base.py
- sdcm/sct_events/continuous_event.py
- sdcm/sct_events/loaders.py
- sdcm/sct_events/nemesis.py
- unit_tests/conftest.py
- unit_tests/test_sct_events_base.py
- unit_tests/test_sct_events_continuous_events_registry.py
If an error event happens during nemesis, attach the nemesis information to the event.
Event message example:
```
2022-09-14 08:44:14.893: (FullScanEvent Severity.ERROR) period_type=end event_id=d23078b5-732c-4649-a909-25144eb22af8 during_nemesis=RestartWithResharding duration=7m27s node=longevity-10gb-3h-test-add-db-node-8ca92eee-2 select_from=keyspace1.standard1 message=FullScanThread operation ended successfully
```
in raw event:
```
{"base": "FullScanEvent", "type": null, "subtype": null, "ks_cf": "keyspace1.standard1", "message": "FullScanThread operation ended successfully", "node": "longevity-10gb-3h-test-add-db-node-8ca92eee-2", "shard": null, "event_timestamp": 1663145054.893798, "source_timestamp": null, "severity": "NORMAL", "event_id": "d23078b5-732c-4649-a909-25144eb22af8", …
```
> feature(events): add to event nemesis sub-context

- .pre-commit-config.yaml
- sct.py
- sdcm/cluster_aws.py
- sdcm/cluster_gce.py
- sdcm/sct_events/group_common_events.py
- sdcm/utils/common.py
- unit_tests/test_base_version.py
- unit_tests/test_config.py
- unit_tests/test_utils_common.py
This PR includes a few commits cherry-picked from master and a small fix to imports in order to fix the CI checks on branch-2022.1.
Part of the effort in: https://github.com/scylladb/qa-tasks/issues/813
> fix(unit-tests): fix CI checks

- test-cases/scale/longevity-5000-tables.yaml
We ran into problematic nemesis for 5000 tables test: https://github.com/scylladb/scylla-manager/issues/3237
This commit switch nemesis seed to make this test with different nemesis set.
> test(5000-tables): change seed for 5000 tables test

- sdcm/nemesis.py
The previous timeout of 300 seconds was insufficient for the reboot function, so I lengthened it to 400 seconds.
> fix(start_and_interrupt_rebuild_streaming): Increased timeout to 400

- configurations/operator/perf-regression-latency-and-throughput-multitenant-14-clients.yaml
- configurations/operator/perf-regression-latency-and-throughput-multitenant-2-clients.yaml
- configurations/operator/perf-regression-latency-and-throughput-multitenant-7-clients.yaml
- configurations/operator/perf-regression-latency-multitenant-14-clients.yaml
- configurations/operator/perf-regression-latency-multitenant-2-clients.yaml
- configurations/operator/perf-regression-latency-multitenant-7-clients.yaml
- sdcm/cluster_k8s/__init__.py
Multitenant performance tests on K8S don't allow us to use different commands for multiple loaders of a same Scylla cluster except the 'prepare_write_cmd'.
So, fix the tenant number calculation to consider only lists of lists for any stress cmd.
Such a fix requires update of existing configs for multitenant tests. So, update it to satisfy the new approach.
> fix(k8s-multitenancy): properly calculate number of tenants

- configurations/operator/k8s-upgrade-gke.yaml
- jenkins-pipelines/operator/upgrade/upgrade-platform-k8s-gke.jenkinsfile
- longevity_test.py
- sdcm/cluster_k8s/__init__.py
- sdcm/cluster_k8s/gke.py
- sdcm/utils/loader_utils.py
- test-cases/scylla-operator/kubernetes-platform-upgrade.yaml
- upgrade_test.py
Update the 'upgrade K8S platform' test with the possibility
to pre-load data and run stress commands during the upgrade.
Such an approach is much closer to the real world.
> improvement(k8s-upgrade): run preload and load

- defaults/azure_config.yaml
- vars/createSctRunner.groovy
- vars/provisionResources.groovy
When avaliability zone is not set, sct test on azure fails to create sct-runner instance due wrong command. Later there's a problem with incorrect log param when running without runner provision-resources step. And finally, when az is not set, default is taken from azure_config.yaml which breaks concept of running without az.
This commit fixes all these issues.
> fix(azure): fix running without setting az

- sdcm/k8s_configs/loaders/sts.yaml
60735f3fc4f5d0b70ec7bd616341bb9826d4fa44 splited the loader configuration into 2 files, but dropped the docker mount which is still needed, until we refactor the code to use the dynamic loaders approch.
> fix(k8s_loader): make docker base loader work

- sdcm/k8s_configs/loaders/sts.yaml
> fix(k8s-sts-loaders): add missing 'path' parameter

- test-cases/longevity/longevity-twcs-48h.yaml
there are 100s of failure like this:
```
Operation timed out for scylla_bench.test -
received only 1 responses from 2 CL=QUORUM.
```
and this test case was pinned to old s-b version
trying it with a newer version and with timeouts
> fix(longevity-twcs-48h): add timeout to s-b commands

- defaults/severities.yaml
NoSQLBenchStressLogEvents.ProgressIndicatorRunningEvent added on PR #4015 used severity DEBUG, but it is meant for some specific use, hence moving it to be normal events instead.
> fix(severity.yaml): change nosqlbench severity

- sdcm/nemesis.py
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5285
The method start_and_interrupt_rebuild_streaming() is used to hard reboot a node during the rebuild operation. After the reboot we attempt to rebuild. We waited on ssh_up on the target machine, but that can be true before Scylla finishes it's own restart. This commit introduces a wait for db_up to avoid asking the db for a rebuild before it's up.
> fix(nemesis): wait for db_up in start_and_interrupt_rebuild_streaming()

- sdcm/gemini_thread.py
Sometimes default connect and request timeouts for gocql driver 10s could be not enough. While node was replaced, gemini query failed by timeout for si.
To avoid such errors, increasing request and connect timeouts
Job where issue happened:
https://jenkins.scylladb.com/job/enterprise-2022.1/job/gemini-/job/gemini-3h-with-nemesis-test/
> fix(gemini_thread): Increase request and connect timeouts for gemini

- sdcm/gemini_thread.py
Gemini command incorrectly build with oracle cluster due to mistype when oracle node ip is added to command
> fix(gemini_thread): correctly build gemini comand with oracle

- configurations/azure/azure_rolling_upgrade.yaml
- jenkins-pipelines/rolling-upgrade-azure-image.jenkinsfile
- sdcm/sct_config.py
- vars/createSctRunner.groovy
- vars/getCloudProviderFromBackend.groovy
- vars/rollingUpgradePipeline.groovy
This PR introduces commits related to adding a rolling upgrade job for the Azure backend, i.e. running the rolling upgrade job on Azure, using the Azure machine images. 
An additional commit was added with a small refactor change for the `rollingUpgradePipeline.groovy` script file.
Git task: https://github.com/scylladb/qa-tasks/issues/336
Staging job for testing: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/ru-azure
> Rolling upgrade azure

- longevity_sla_test.py
- sdcm/nemesis.py
- test-cases/longevity/longevity-sla-100gb-4h.yaml
- test_lib/sla.py
Add new nemesis that remove service level while load running connected with this SL
Refs: https://github.com/scylladb/qa-tasks/issues/805
Issue https://github.com/scylladb/scylla-enterprise/issues/2438 was reproduced. Example of run:
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-sla-100gb-4h/50/
```
2022-10-12T07:42:08+00:00 longevity-sla-100gb-4h-test-add-db-node-efcc62e5-4     !INFO | scylla[9871]:  [shard 0] workload prioritization - service level "sl200_0" was deleted.
2022-10-12T07:42:08+00:00 longevity-sla-100gb-4h-test-add-db-node-efcc62e5-4     !INFO | scylla[9871]: Segmentation fault on shard 6.
2022-10-12T07:42:08+00:00 longevity-sla-100gb-4h-test-add-db-node-efcc62e5-4     !INFO | scylla[9871]: Backtrace:
2022-10-12T07:42:08+00:00 …
```
> test(nemesis): remove service level while load

- sdcm/cluster.py
- sdcm/utils/health_checker.py
- unit_tests/test_utils_health_checker.py
For the moment, if we fail to get the peers info for some reason, then we get 'Schema agreement is not reached' error running the 'ToggleTableIcs' nemesis.
So, detect specific problems and report correct messages not hiding valueable info.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/5265
P.S.
First version of this change was merged with 2 bugs in the [1]. And then reverted in the [2].
The problem with v1 was lots of redundant 'gossip' and 'peers' API calls with huge waiting intervals '2m14s' instead of '7s' for each of the DB nodes.
It was caused by the absence of the 'break' statement for the retry loop in case of success and reporting of a failure from previous iterations on the last succeeded, which caused the rerun of the function again.
The side effect of this …
> fix(schema-agreement): print proper error messages. v2

- functional_tests/scylla_operator/libs/helpers.py
It happens that the recreation of a Scylla pod may take more than our current wait timeout.
So, increase the timeout value to be 10 minutes to cover the reality for sure.
> improvement(k8s-functional): increase resharding wait time to 10m

- sdcm/cluster_k8s/__init__.py
- sdcm/cluster_k8s/gke.py
- sdcm/k8s_configs/static-local-volume-provisioner.yaml
- sdcm/tester.py
GKE deploys lots of redundant, for Scylla K8S nodes, pods. So, make it be scheduled elsewhere by setting a taint that will be tolerated by all the expected pods.
> improvement(k8s-gke): use taint for Scylla K8S nodes

- defaults/test_default.yaml
- sdcm/cassandra_harry_thread.py
- sdcm/cdclog_reader_thread.py
- sdcm/gemini_thread.py
- sdcm/kcl_thread.py
- sdcm/ndbench_thread.py
- sdcm/nosql_thread.py
- sdcm/scylla_bench_thread.py
- sdcm/stress_thread.py
- sdcm/utils/docker_remote.py
- sdcm/ycsb_thread.py
- unit_tests/test_config.py
When running scylla-bench for the first time on loader, there's around 3 minutes delay when it's executed for the first time. This is a result of docker image getting pulled. This delay may lead
to errors in tests. E.g. starting s-b in upgrade test happens when node gets drained and returning error.
This commit enforce pulling scylla-bench docker image before returning `ScyllaBenchThread` so test will wait for s-b being downloaded to loaders.
> fix(scylla-bench): fix s-b delay for first run

- docs/configuration_options.md
- functional_tests/scylla_operator/conftest.py
- functional_tests/scylla_operator/test_functional.py
- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
- sdcm/cluster_k8s/mini_k8s.py
- sdcm/sct_config.py
enabling the new feature flag, to start flushing out what else would be need in SCT
Ref: scylladb/scylla-operator#1021
> feature(serverless): enable `AutomaticTLSCertificates=true`

- sdcm/sct_events/base.py
Nemesis subcontext has been added by https://github.com/scylladb/scylla-cluster-tests/pull/5159. But it does not work for LogEvents.
This commit fixes this problem
> fix(events): add subcontext to LogEvent

- sdcm/provision/scylla_yaml/scylla_yaml.py
- unit_tests/test_scylla_yaml.py
`compaction_throughput_mb_per_sec` setting in scylla.yaml was activated by https://github.com/scylladb/scylladb/commit/bfc521ee9c2ba16fc4a15e68c21f68300658f530 Default value was also changed.
This commit reflects default value change for this scylla.yaml parameter.
> fix(scylla.yaml): change default for compaction throughput limit

- configurations/operator/loader-run-type-dynamic.yaml
- jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke.jenkinsfile
This job will be weekly triggered.
So, enable dynamic loader run type for this job to test it in addition to the GKE backend itself.
> ci(k8s-gke): use dynamic loader run type for the longevity-3h job

- sdcm/provision/azure/provisioner.py
When running clean-resources for specific user, resources group list also invalid RG's (with no test_id).
This fix enforces proper discovery of test_id's from RG's names, fixing cleanup for specific user.
refs: https://github.com/scylladb/scylla-cluster-tests/issues/5373
> fix(azure): fix clean resources for user

- sdcm/scylla_bench_thread.py
- sdcm/stress_thread.py
K8S backends do not require preliminary pulling of docker images. 
Then, we get failure using `dynamic` loader run type. 
So, stop calling `docker pull` command in stress thread classes when we run on K8S backends.
> fix(k8s): do not call `docker pull` command in stress thread class

- sdcm/nemesis.py
> fix(k8s-gke): skip flush and reshard nemesis due to the bug

- sct.py
Recent rolling-upgrade-ami jobs have been failing due to the `linux_distro` pipeline param missing. This PR reintroduces it to the jenkinsfile.
Failing master jobs: https://jenkins.scylladb.com/view/master/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/
Staging job with the fix: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/ru-ami/
Staging job using CentOS (provided as the pipelineParam): https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/ru-5.0-centos-8/
> fix(rolling-upgrade): add missing linux_distro param

- sct.py
- sdcm/monitorstack/__init__.py
Add multi-tenant support to 'hydra investigate show-monitor'.
1. Dockers will be run for each cluster (tenant)
2. New parameter '--cluster-name' is added. If cluster name is supplied, the dockers  will be created for needed cluster only
> feature(show monitor): support multi-tenant configuration

- unit_tests/test_scylla_bench_thread.py
remove duplicate code from unittests
> fix(duplicate): remove unused `create_cql_ks_and_table`

- sdcm/nemesis.py
There's an issue with double entry in scylla config file when add_remove_dc nemesis is run in multi dc scenario.
Skipping this nemesis for such scenarios as workaround.
refs: https://github.com/scylladb/scylla-cluster-tests/issues/5369
> fix(add_remove_dc): skip nemesis for multi dc scenario

- sdcm/nemesis.py
since restart with resharding is restarting nodes
alterntor current implmetion might get connection refused at that time, we need to ignore those
Fix: #4738
> fix(nemesis): ignore connection refused error on restart_with_resharding

- pylintrc
Since we still have those checks randomly failing
it's better to disable it, then slow us down on failures that aren't shown in consist fashion
> fix(pylint): remove duplicate-code check

- sdcm/sct_events/group_common_events.py
During node power off upon decommission, scylla report next error to log !ERR | scylla[7945]:  [shard  0] storage_proxy - exception during mutation write to 10.12.0.200:
utils::internal::nested_exception<std::runtime_error>
(Could not write mutation cdc_test:test_table_postimage
(pk{00072b127a257d676c}) to commitlog): seastar::gate_closed_exception (gate closed)
Adding filter to change the severity from error to warning
> fix(ignore_stream_mutation_fragments): filter mutation write error

- upgrade_test.py
This reverts commit 894a1c8c5229b9846321bfdea57373cd729b3d19.
Since some versions can be yanked of repositry (CVE as example) it was decided to stop doing this procudure
> Revert "test(upgrade): add OS package upgrade for AMI test"

- functional_tests/scylla_operator/conftest.py
- sdcm/utils/version_utils.py
Example of the usage:
```
@pytest.mark.requires_scylla_versions(("4.4.4", "4.5"), ("5.1.0", None))
def test_foo(db_cluster):
...
```
> improvement(k8s-functional): support a test skip based on Scylla version

- sdcm/cluster_k8s/mini_k8s.py
For the moment we cache docker images all the time
even running on an already existing cluster having `reuse_cluster=1` option set.
So, skip `docker images caching` operations for reused clusters to reduce time we spend for init test.
> improvement(k8s-local): cache docker images only on fresh setups

- sdcm/k8s_configs/eks/scylla-node-prepare.yaml
Using `i3` nodes we have local NVME disks be attached to the `/dev/md0` path, 
but in the `i4i` ones it is `/dev/nvme0n1p1`. 
So, make the `pv-setup` on EKS consider both cases.
> fix(k8s-eks): make i4i instance types be supported for the Scylla nodes

- sdcm/tester.py
- sdcm/utils/version_utils.py
During job Artifacts-ubuntu-2204, _get_common_email_data failed, because scylla version could not be get from scylla, and attempt to get relocatable packages failed with error and cause failing the the save email data and the send email
```
16:40:44  < t:2022-11-15 09:40:44,170 f:cluster.py      l:2114 c:sdcm.cluster_gce     p:WARNING > Node artifacts-ubuntu2204-jenkins-db-node-1c68b572-0-1 [34.74.229.149 | 10.142.0.37] (seed: True): All attempts to get ScyllaDB version failed. Looks like there is no ScyllaDB installed.
16:40:44  < t:2022-11-15 09:40:44,172 f:tester.py       l:3262 c:ArtifactsTest        p:ERROR > Error while saving email data. Error: argument of type 'NoneType' is not iterable
16:40:44  < t:2022-11-15 09:40:44,172 f:tester.py       l:3262 c:ArtifactsTest        p:ERROR > …
```
> fix(get_relocatable_pkg_url): skip get reloc_pkg if version is none

- test-cases/longevity/longevity-multi-keyspaces.yaml
seems like lot of keyspace started generated much more logs and we are running out of disk space
Fix: #5408
> fix(longevity-multi-keyspaces-60h): enlarge the db root disk size

- defaults/test_default.yaml
- unit_tests/test_config.py
- unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
- unit_tests/test_scylla_yaml_builders.py
Change oracle db version for gemini tests
> fix(test_default): Switch oracle db version for gemini

- defaults/severities.yaml
- sdcm/cluster.py
- sdcm/sct_events/system.py
When run_nodetool command gets an exception it ignored coredump_on_timeout parameter.
This is fixed and also added an event before the actual node kill starts.
Refs: #5418
Fix: #5418
> fix(cluster.py): Generate a scylla core dump according to boolean flag

- sdcm/nemesis.py
While not a show-stopper right now, this shadowing could bring potential issues later as `finally:` block will try to operate on a decomissioned node and not on the intended first node of the cluster
> fix(nemesis.py): Shadowing of a node variable

- sdcm/utils/aws_region.py
Since we start adding CreateBy tag for VMs, to limit the user from cleaning up only resources created by SCT (when using hydra commandline) a user couldn't cleanup his own security groups, that we left over from a job, or manually created by `hydra attach-test-sg` command
this adds the tag to the test_id based security group
> fix(sct-cleanup): add CreatedBy tag to security groups

- functional_tests/scylla_operator/conftest.py
- functional_tests/scylla_operator/pytest.ini
- functional_tests/scylla_operator/test_functional.py
The 'test_nodetool_flush_and_reshard' test fails due to the following bug: 
https://github.com/scylladb/scylla-operator/issues/1077 
So, skip it.
> test(k8s): skip flush and reshard test due to operator's bug

- sdcm/sct_events/setup.py
Per scylladb/scylladb#11969 this error is considered harmless as it happens during shutdown and doesn't affect the user
> fix(sct_events/setup.py): Filter LDAP connection resets

- configurations/rolling-upgrade-with-sla.yaml
- jenkins-pipelines/rolling-upgrade-with-sla.jenkinsfile
- longevity_sla_test.py
- sdcm/utils/loader_utils.py
- test_lib/sla.py
- upgrade_test.py
Add new basic rolling upgrade test with SLA authentication defined and running load with SLA connection while upgrade
Generic rolling upgrade for 2022.2: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/rolling-upgrade-with-sla/10/
Longevity SLA test succeeded to create roles with SL and run load with it: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-sla-100gb-4h/58/
> test(upgrade): run upgrade test with SLA

- defaults/k8s_local_kind_aws_config.yaml
- defaults/k8s_local_kind_gce_config.yaml
- sct.py
- sdcm/sct_config.py
- test-cases/longevity/longevity-multi-keyspaces.yaml
- vars/createSctRunner.groovy
Since we have more and more cases that we found that need specific configuration for sct-runner machine, like stronger machines or bigger disks we are introducing two new test configuration options, that can be configured like that:
```yaml
instance_type_runner: c5.2xlarge
root_disk_size_runner: 120
```
Fix: #5428
> feature(sct-runner): new test configuration for instance/disk

- sdcm/cluster_docker.py
- sdcm/utils/docker_utils.py
- unit_tests/test_utils_docker.py
code was looking for docker instance by prefix, but the api need to have `*` at the end for it to actully find any instances
> fix(docker): fix `reuse_cluster` to find instance

- sdcm/cluster_k8s/mini_k8s.py
- sdcm/k8s_configs/cni-calico.yaml
Seem like since we are trying to upload lots of images
before the CNI network is setup correctly, it's lead to timeouts
on the kube-system pods, and casue restarts that slows down
the uplod of images into kind, and also can end up in
timeout to complate some of the helm charts (for example the
cert-manager, which is the first one we use), cause not
of node aren't in Ready state yet.
> fix(k8s-kind): setup calico CNI plug-in first

- sdcm/remote/kubernetes_cmd_runner.py
when `reuse-cluster` is being used, we might have old pod in complated state, we need to make sure we don't try to use them since they can be modified and would fail the test.
insted we keep incressing the counter until we find "unused" podname.
> fix(dynamic-loader): create new pods on `reuse_cluster`

- sdcm/utils/operator/multitenant_common.py
if `setUp` is failing for some reason, stop resources was failing like the following:
```
File ".../sdcm/utils/operator/multitenant_common.py", line 135, in setUp
super().setUp()
File ".../sdcm/tester.py", line 158, in wrapper
args[0].tearDown()
File ".../sdcm/tester.py", line 2680, in tearDown
self.stop_resources()
File ".../sdcm/utils/operator/multitenant_common.py", line 145, in stop_resources
objects=[[tenant] for tenant in self.tenants],
AttributeError: 'LongevityOperatorMultiTenantTest' object has no attribute 'tenants'
```
> fix(multitanent): `stop_resources when` `setUp` fails

- defaults/test_default.yaml
- docs/configuration_options.md
- sdcm/sct_config.py
- test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml
- test-cases/upgrades/generic-rolling-upgrade.yaml
- test-cases/upgrades/multi-dc-rolling-upgrade.yaml
- test-cases/upgrades/rolling-upgrade.yaml
- unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.yaml
- upgrade_test.py
Commit https://github.com/scylladb/scylla-cluster-tests/pull/981/commits/a5e0d1eaea98c2c197b7685b6f8c2ad99a131330 introduced enable_authorization_after_upgrade parameter for upgrade_test. It was added because old Scylla doesn't support Authorization, so we can't use to enable Authorization before & after upgrade. This change was added in 2019.1. Since all our releases supports authorizer option now, remove it.
> fix(upgrade): remove enable_authorization_after_upgrade parameter

- sdcm/nemesis.py
C-S thread creating keyspaces triggered in `_prepare_test_table` may fail to write data and freeze if the nodes do not get to schema agreement quickly enough (due to Scylla's problem with schema management).
To avoid it we will wait for schema agreement each time after calling `_prepare_test_table`.
This workaround should fix https://github.com/scylladb/scylla-cluster-tests/issues/5413
> fix(disrupt_no_corrupt_repair): wait for schema agreement

- configurations/rolling-upgrade-with-sla.yaml
Increase load time during upgrade/rollback for rolling upgrade SLA test
> fix(upgrade): increase load time during upgrade/rollback

- test-cases/longevity/longevity-twcs-3h.yaml
- test-cases/longevity/longevity-twcs-48h.yaml
Test with TWCS used not optimized configuration   for s-b tool. Wrong configuration parameters cause
tests failed and have throughput drop down even     without nemesis.
After investigation found set of parameters     which allow to have stable throughput during
all test duration.
> fix(twcs-48h-yaml): Tune sb twcs settings

- sdcm/k8s_configs/ingress-controller/10_haproxy-kubernetes-ingress.configmap.yaml
cleanup all the configuration options, since if some are wrong it would keep restarting the haproxy to update them
> fix(k8s-ingress): remove wrong configuration options

- vars/rollingUpgradePipeline.groovy
This commit adds the azure_region_name param to the rolling upgrade pipeline. Without this param the pipeline would use any available builder in Jenkins, which sometimes ends up with us running on cloud team's builders, which are configured differently from ours. This in turn leads to failures of our hydra commands. After the commit we should only run on QA builders.
> fix(rolling_upgrade): add azure region name param to getJenkinsLabels

- sdcm/cassandra_harry_thread.py
- sdcm/cdclog_reader_thread.py
- sdcm/gemini_thread.py
- sdcm/kcl_thread.py
- sdcm/ndbench_thread.py
- sdcm/scylla_bench_thread.py
- sdcm/stress_thread.py
- sdcm/ycsb_thread.py
we never want to retry a stress comamnd, regardless what
the exception was, if we retry midst the stress command
we would start it from begining (which is an outcome we never want)
list of exception we retry is defined in `CommandRunner._is_error_retryable`
Fixes: #5278
> fix(loaders): disable retry on main loader run commands

- jenkins-pipelines/features-per-partition-limit.jenkinsfile
- per_partition_limit_test.py
- test-cases/features/per-partition-limit.yaml
It is now possible to limit read rates and writes rates into a partition with a new WITH per_partition_rate_limit clause for the CREATE TABLE and ALTER TABLE statements. This is useful to prevent hot-partition problems when high rate reads or writes are bogus (for example, arriving from spam bots)
Feature introduced in:
https://github.com/scylladb/scylladb/commit/dab56b82fae5e36f7aa2ca6700d8cfa5baa2b515
Each cql request goes through per-partition limiter creating a risk of latency degradation.
Test scenario is about measuring basic performance metrics (latency, op/s) with and without per-partition-limit set and verifying the impact. Also measure influence of hot-partition scenario on these metrics.
> test(per-partition-limit): added new test

- test-cases/longevity/longevity-counters-multidc.yaml
- test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
- test-cases/longevity/longevity-large-partition-4days.yaml
- test-cases/longevity/longevity-twcs-48h.yaml
It looks that pinning old scylla-bench version is not bringing benefits in large partition tests. Newest version was found passing so we no longer need to pin it in tests.
> fix(s-b): unpin scylla bench version in tests

- test-cases/scale/longevity-5000-tables.yaml
since we have a bit amount of logs generated, cause of the multiple stress command and the multiple tables
Fix: #5234
> fix(5000-tables): enlarge the runner root disk to 120Gb

- sdcm/utils/common.py
Since SCT branch-2021.1 doesn't support ARM yet
we just skip it until it would be backported
> fix(aws-ami): skip arm AMI when listing AMIs

- sdcm/scan_operation_thread.py
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5474
Aggregate fullscan operations create their own random cql queries.
Changes introduced with https://github.com/scylladb/scylla-cluster-tests/pull/5355
missed the USING TIMEOUT part of a query with timeout which led to
CQL errors. This commit adds the missing part of the query.
Staging run with fullscans (1 thread with mixed commands): https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-longevity/job/mc-large-partitions-3h/72/
> Fix fullscan queries

- defaults/manager_versions.yaml
- sdcm/cluster.py
- sdcm/mgmt/common.py
- sdcm/provision/common/utils.py
- sdcm/utils/distro.py
- test-cases/performance/perf-regression-latency-1TB.yaml
- test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
- test-cases/performance/perf-regression.100threads.30M-keys.yaml
Ubuntu 22.04 have disabled ssh rsa and removed rsyslog by default Enable rsa and switch to use ssh logging
> fix(perf-with-nemesis): Support ubuntu 22.04

- sdcm/utils/version_utils.py
- unit_tests/test_version_utils.py
In some runs that are using AMIs which doesn't have corresponding docker images, we've seen this failures, when c-s stress command is running:
```
File "../sdcm/stress_thread.py", line 173, in _run_cs_stress
cassandra_stress = get_docker_image_by_version(
self.node_list[0].get_scylla_binary_version())
File "../sdcm/utils/version_utils.py", line 354, in get_docker_image_by_version
for image in all_tags['results']:
KeyError: 'results'
```
improved `get_docker_image_by_version` to be more robust on handling errors, and melformed responses.
> fix(get_docker_image_by_version): make it more roubst to errors

- sdcm/tester.py
seem like 0122299f90bcc8ecaadfa9bb2a997dcc10d0b9be wrongly change the query for `copy_table_as`
casuing the follwoing error:
```
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query]
message="Undefined name ks_cf in where clause ('unresolved(ks_cf)')"
```
> fix(lwt-datavalidator): wrong query for `copy_table_as`

- configurations/rolling-upgrade-with-sla.yaml
- jenkins-pipelines/rolling-upgrade-with-sla.jenkinsfile
- longevity_sla_test.py
- test_lib/sla.py
- upgrade_test.py
This test was added by https://github.com/scylladb/scylla-cluster-tests/pull/5421 But it's not compatible with branch-2022.2.
Create separate commit
> test(upgrade): run upgrade test with SLA [branch 2022.2]

- sdcm/utils/es_queries.py
Latest performance results using wide query filters documents from ES also from another jobs which are have similar name but have suffix related to another instance type ex. Performance_throughput and Performance_throughput_i4i
this happened because filter query uses wc:
job_name.keyword: performance_throughput*
use explicit job name,ex:
ob_name.keyword: performance_throughput
> fix(es_queries): Use explicit job name instead of wc

- sdcm/cluster.py
- sdcm/utils/version_utils.py
Switch to used json format when available, to avoid
parsing the outout of coredumpctl which keep of changing
Implementation of #5492 
(cherry picked from commit 5a3b46bad5f9fcdd07fb6a496360b835a8031e4c)
> fix(cordump_thread): get coredumpctl output in json format

- artifacts_test.py
- mgmt_upgrade_test.py
- sdcm/cluster_aws.py
- sdcm/cluster_k8s/__init__.py
- sdcm/logcollector.py
- sdcm/nemesis.py
- sdcm/tester.py
this wrong assumption, failed the provision tests and any other test that doesn't use SisyphusMonkey
```
if nemesis_seed := self.tester.params["nemesis_seed"]:
KeyError: 'nemesis_seed'
```
> fix(5499): don't use assume `nemesis_seed` is always define

- Jenkinsfile
- sct.py
- sdcm/cassandra_harry_thread.py
- unit_tests/test_alternator_streams_kcl.py
- unit_tests/test_cassandra_harry.py
- unit_tests/test_cassandra_stress_thread.py
- unit_tests/test_gemini_thread.py
- unit_tests/test_ndbench_thread.py
- unit_tests/test_scylla_bench_thread.py
- unit_tests/test_version_utils.py
since we are not running those tests regulary, they tend to get broken, and also we might miss breakage espesily in our loader docker tests.
for now it's would be enable by using a label on the PR `test-integration`
> feature(integration-tests): enable the longer integration tests

- sdcm/utils/common.py
Following the changes in https://github.com/scylladb/scylla-pkg/pull/3168, we are adding an option to build AMI images with debug packages.
Updating the condition so `hydra` will ignore such an image
> fix(get_branched_ami): set to ignore images built in debug mode

- sdcm/utils/benchmarks.py
Git command was removed from db instances. to run hw bench tools repos from git have to be cloned. Install git to db instance
> fix(install_bench_tool): Install git on db instances

- sdcm/nemesis.py
Since Scylla issue #11245 is now considered as fixed, we would like to enable this nemesis so we can continue testing it.
> fix(disrupt_nodetool_enospc): re-enable enospc nemesis

- sdcm/stress/base.py
- sdcm/stress_thread.py
- sdcm/utils/docker_remote.py
* align cassandra stress thread to pull the image before it's starts it's threads (same as all the other loaders)
* add retries for the image pulling, and the initial creation of the docker instance
if we don't have those, we could something see those failure when trying to pull images on creation, like this:
```
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/":
net/http: request canceled while waiting for connection
(Client.Timeout exceeded while awaiting headers).
```
Fixes: #5464
> fix(cassandra-stress): make sure docker image is pull upfront

- test-cases/performance/perf-regression-latency-500gb-30min.yaml
PR #5477 missed changing this job's configuration
to use SSH as `log_transport`.
> fix(performance): run perf test on Ubuntu22

- vars/perfSearchBestConfigParallelPipeline.groovy
Added new pipeline paremter which set running cs commands
> fix(perfsearch): new pipeline parameter cs commands

- docker/env/hydra.sh
- vars/cdcReplicationPipeline.groovy
- vars/cleanSctRunners.groovy
- vars/copyLogsFromSctRunner.groovy
- vars/createSctRunner.groovy
- vars/createTestJobPipeline.groovy
- vars/managerPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
- vars/perfSearchBestConfigParallelPipeline.groovy
- vars/provisionResources.groovy
- vars/rollingUpgradePipeline.groovy
- vars/runCleanupResource.groovy
- vars/runCollectLogs.groovy
- vars/runSctTest.groovy
- vars/runSendEmail.groovy
Add group ID for Docker container user:
```shell
$ docker run --help
...
-u, --user string                    Username or UID (format: <name|uid>[:<group|gid>])
...
```
This make it to set a proper group for files created by processes inside a container.
Also, to set the shell properly in sh step in Jenkinsfile, the shebang line must be exactly the first line of a script. Otherwise, system shell will be used (with -xe args.)
Despite we live with it from the very beginning it hits us sometimes.
> Shell fixes

- sdcm/argus_test_run.py
- sdcm/tester.py
since we are going to be using operator much more
we should be start sending the versions to argus
so it would be visable for us investigating and for
the email template
Testing:
> feature(k8s): report operator versions to argus

- sdcm/cluster.py
When EBS disks are being use, we need longer timeouts on the `nodetool flush` calls, since they can take more then 60sec
> fix(get_cfstats): enlarge timeouts for EBS case

- sdcm/cluster.py
- sdcm/cluster_docker.py
- sdcm/cluster_k8s/__init__.py
since there are cases they we in general need to have bigger timeouts for this call (i.e. when using EBS disks as one), we are moving this to a property that diffrent backends can apply logic before setting it.
> fix(scylla_start_server): move `verify_up_timeout` default into property

- sdcm/cluster.py
When the exception does not have `.args`, the statement `f"{exc}"` returns nothing, and the reason why `nodetool status` failed is not printed in the log.
Changed printing to display the exception class name together with the `.args`.
> fix(get_nodes_status): print more information about exception

- sdcm/sct_events/base.py
Issue https://github.com/scylladb/scylla-cluster-tests/issues/5544 
Add print out for recognize which event is not initialized. 
Prevent event failure
> fix(events): subcontext is not initialized

- sct.py
Adding raft pipelines folder to the list of groups created automatically in Jenkins.
> feature(raft jobs): Add raft pipelines to list of groups created

- sdcm/sct_events/base.py
- unit_tests/test_sct_events_base.py
- unit_tests/test_sct_events_continuous_events_registry.py
since the `clone` uses pickle that uses the object `__getstate__` we missed adding the subcontext there if empty, and object would be created with it set to None.
Fixes: #5544
> fix(events-subcontext): subcontext was missing when log events cloned

- sdcm/cluster.py
On systems which use systemd-networkd to manage networking interfaces use the provided tool to start an interface, e.g.:
$ networkctl reconfigure eth1
This will fix the problem with stop/start interface network monkey.
Fixes: https://github.com/scylladb/scylladb/issues/11609
> fix(cluster.py): use networkctl to start an interface if possible

- sdcm/remote/kubernetes_cmd_runner.py
in cases like:
```
cmd_runner.send_files('/somedir/fileA.xml', '/tmp/fileB.xml')
```
would be failing the mount, since we configmap was create with `fileA.xml` as key, and the mount would look for `fileB.xml` as the key in the configmap
> fix(k8s-dynamic-loader): stop assuming src/dest filename is identical

- vars/managerPipeline.groovy
Manager pipeline didn't create VM's in proper resource group due missing setting availability_zone variable properly (according to the pipeline settings). Failing that made SCT runner to not be able connect using SSH as created resources belonged to different network causing SSH timeout errors.
This fix makes `availability_zone` to be respected in SCT manager test, fixing proper Azure resources creation location (RG).
> fix(manager-test): fix azure resources creation az

- sdcm/nemesis.py
- test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
For free tier cloud we want to limit disruptions to ones that may actually happen. So we want to skip disruptions for mgmt, topology changes (except ones that may happen due failures) or any other that are unlikely to happen on Scylla Cloud's free tier.
New Monkey `FreeTierSetMonkey` has been created which behaves similar to SisyphusMonkey but on limited set. Disruptions eliglible for free tier are marked with new flag `free_tier_set` in `Nemesis` class so when new nemesis are added it's easier to remember to update `FreeTierSetMonkey`.
refs: https://github.com/scylladb/qa-tasks/issues/910
> test(nemesis): added FreeTierSetMonkey

- data_dir/logback-tools-debug.xml
- docs/configuration_options.md
- sdcm/sct_config.py
- sdcm/stress_thread.py
- unit_tests/test_cassandra_stress_thread.py
add `cs_debug` option to SCT, to enable c-s debug when needed
Note: keep in mind, add it can hurt performence of some use-cases
and running out of sct-runer disk space for some use-cases
> feature(cassandra-stress): add option for enabling debug

- test-cases/longevity/longevity-lwt-500G-3d.yaml
Now the stress duration is defined as '3600m'. It cause to test timeout. Test duration is 74h but real test duration when stress runs 3600m is more then 76h. Decrease it to 3420m (57h instead of 60h)
> fix(longevity): descrease stress duration in longevity-lwt-500G-3d-test

- sdcm/logcollector.py
since getting sct.log is more importent then
trying to collect melformed sstables, we should
first start with the must have collector, and then move to the less frequent used.
since in some cases we've seen the collection of sstables were stack, probably since it trying to read all of the events and it was a 3day job with lots of events.
> fix(logcollector): change order of collection

- sdcm/cluster.py
- sdcm/nemesis.py
fix(nemesis.py): fail nemesis if non-empty table not found
If failed to find non-empty user tables, cannot run any
data deletion operation and should fail nemesis due to table query issues.
Fixes: #5538
https://github.com/scylladb/scylla-cluster-tests/issues/5538
> fix(nemesis.py): fail nemesis if non-empty table not found

- defaults/severities.yaml
- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
- sdcm/nemesis.py
- sdcm/sct_events/system.py
- unit_tests/test_events.py
since in some cases decomission might take as long as adding
a new node to cluster (big data set / slow disks)
until now we didn't timeout on VMs, and had a 30min timeout on k8s
this should align both to wait the same time
for VMs we are going to set it soft_timeout, i.e. we would
only raise error event if it took longer then expected, and
would put a hard timeout.
For k8s we will use the soft_timeout as hard timeout, since
we are not directly calling `nodetool decommission` by
just waiting for that operation by polling.
> feature(decommission): add timeout to cluster.decommission

- test-cases/scale/scale-cluster.yaml
In large clusters where we have many stalls and oversized_allocations, the log if filled up with backtrace decoding.
> fix(scale-cluster): Setting backtrace_decoding to false for scale test

- sdcm/sct_config.py
Since gce_datacenter can be a python list (multi region), I changed its type to str_or_list_or_eval
> fix(gce_datacenter): set its type to str_or_list_or_eval

- unit_tests/test_config.py
seems like recently 3.0.3 and 4.5.2 images from us-east-1 have been deleted, switching to test with newer versions
> fix(unittests): switch away from delete old AMIs

- sdcm/cluster.py
- sdcm/utils/health_checker.py
- unit_tests/test_utils_health_checker.py
since when using cqlsh with cloud bundle, we don't have a guarantee anymore that we'll uses only a specific node, since we are connecting to all of them.
thing like reading `system.peers` should be done now with the python-driver `cql_connection_patient_exclusive` helper function.
> refactor(get_peers_info): switch to use python-driver

- defaults/gce_config.yaml
- test-cases/manager/manager-backup-1TB-gce.yaml
- test-cases/manager/manager-regression-multiDC-gce.yaml
Since we moved to a new gce project, 'sct-project-1', we can't use the bucket from the old project. As such, I switched the bucket name to the one that exists in the new project.
Also, removed the backup_bucket_location setting from test-cases/manager/manager-backup-1TB-gce.yaml and test-cases/manager/manager-regression-multiDC-gce.yaml since they were redundant. Setting it in defaults/gce_config.yaml is enough.
> fix(gce manager backup): updated the bucket name

- add_new_dc_test.py
- sdcm/nemesis.py
In certain cases a non-paged query can fail when not paged.
Like where too many tombstones or large rows exist.
Using a paged-query will eliminate such failures and runs faster.
Refs: https://github.com/scylladb/scylladb/issues/12268
> fix(select queries): use paged queries

- sdcm/cluster.py
c5591e26de2c596af35326c3821620017cdc05ed introduced new code that was failing like:
```
File ".../sdcm/cluster.py", line 4718, in node_setup
node.remote.sudo("ln -sf /usr/lib/jvm/java-1.8.0-openjdk-
amd64/jre/bin/java* /etc/alternatives/java",
AttributeError: 'GCENode' object has no attribute 'remote'
```
> fix(loader): typo in java-8 installation

- install-hydra.sh
- install-prereqs.sh
- sdcm/cluster.py
Sometimes it happens docker cannot be downloaded due to:
```
+ curl -fsSL get.docker.com -o get-docker.sh curl: (56)
Recv failure: Connection reset by peer
```
This commit use retry mechanism of curl to fix it.
> fix(setup): stabilise docker installation

- sdcm/cluster.py
Sometimes it may happen that curl fails to fetch repo file.
This commit adds curl retry on such cases.
Refs.: https://github.com/scylladb/scylla-cluster-tests/issues/5580
> fix(setup): stabilise download repo file

- configurations/perf-loaders-non-shard-aware-config.yaml
- configurations/perf-loaders-shard-aware-config.yaml
- jenkins-pipelines/perf-regression-latency-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-latency-1TB.jenkinsfile
- jenkins-pipelines/perf-regression-latency-250gb-with-nemesis.jenkinsfile
- jenkins-pipelines/perf-regression-latency-non-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-latency-non-shard-aware-1TB.jenkinsfile
- jenkins-pipelines/perf-regression-latency-non-shard-aware-250gb-with-nemesis.jenkinsfile
- jenkins-pipelines/perf-regression-latency-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-latency-shard-aware-1TB.jenkinsfile
- jenkins-pipelines/perf-regression-latency-shard-aware-250gb-with-nemesis.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-non-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-shard-aware-30min.jenkinsfile
Add explicitly loaders ami to performance yamls
qa-task: https://github.com/scylladb/qa-tasks/issues/848
> fix(perf*.yaml): add loaders ami to perf*.yamls

- docker/env/version
- requirements.in
- requirements.txt
Latest, for now, hydra image `v1.28` was built without regards to the changes made as part of the `v1.26` version. 
So, use fixed version of it called `v1.28-fixed-kubectl-version`.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5586
> fix(hydra): use properly built image with actual requirements

- sdcm/utils/remote_logger.py
Recently merged PR https://github.com/scylladb/scylla-cluster-tests/pull/5348 added 2 more context manager objects in the `CassandraStressThread` class.
But the problem is that one of these new objects uses explicitly only SSH-based remoter not allowing to use K8S-based ones. 
So, detect that we use K8S and enable proper remoter for that context manager.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5590
> fix(k8s): make CSHDRFileLogger context manager be compatible with K8S

- defaults/aws_config.yaml
- defaults/azure_config.yaml
- sdcm/cluster_aws.py
- sdcm/sct_config.py
- sdcm/sct_provision/aws/instance_parameters_builder.py
- test-cases/manager/manager-regression-ipv6.yaml
- test-cases/manager/manager-regression-multiDC-set-distro.yaml
- test-cases/upgrades/manager-upgrade.yaml
Split the configuration, so we can select specific profile for each type of node, and not use the same one for all of the nodes.
> fix(aws_instance_profile): split profiles per node type

- jenkins-pipelines/longevity-100gb-4h.jenkinsfile
- test-cases/longevity/longevity-100gb-4h.yaml
Recently longevity 4h job is failing due to lack of spot machines.
This commit adds fallback to `on_demand` for this test. Also to make spot machines probability to last till the end of the test, shorten `test_duration` so it fits into `MAX_SPOT_DURATION_TIME` (which is 360 and spot duration is calulated this way: `test_duration // 60 * 60 + 60`)
> fix(longevity-4h): optimized test stability and cost

- docs/gcp_create_new_project.md
- sdcm/utils/gce_utils.py
* support for running with `local-ssd-latency`
* instructions on what's needed to be done to add new GCP project
> feature(gcp): adding local-ssd-latency project

- sdcm/cluster.py
c5591e26de2c596af35326c3821620017cdc05ed introduced a change that wasn't working correctly on redhat based OSes, and the sybmolic link was broken casuing cassandra-stress to fail to identify the java version
Fix: #5594
> fix(lodaer-install): fix the symbolic link to java

- sdcm/cluster.py
Since we enabled by default the `k8s_enable_tls` the code using the cloud bundle for cqlsh wrongly assumes it's available, and that's not true for released version, since it's just merged to master a week or two ago.
Fixes: #5577
> fix(k8s-functional): use --cloudconf on cqlsh only from scylla 5.2.0

- sdcm/sct_config.py
- unit_tests/test_config.py
Since a recent change in instance profiles, we are doing calls of `params.get(None)`, assuming it would work like a regular dict and would return None, but it was failing like this:
```
File ".../instance_parameters_builder.py", line 74, in IamInstanceProfile
if profile := self.params.get(self._INSTANCE_PROFILE_PARAM_NAME):
File ".../sdcm/sct_config.py", line 1808, in get
if '.' in key:
TypeError: argument of type 'NoneType' is not iterable
```
> fix(sct_config): make .get(None) work

- sdcm/nemesis.py
`disrupt_method_wrapper.warpper` code was catching `UnsupportedNemesis` and not raisng it as it was intend, causing the main nemesis loop to wait again the whole `nemesis_interval` after a skipped nemesis
> fix(nemesis): make UnsupportedNemesis skip to the next nemesis

- sdcm/utils/remotewebbrowser.py
Fix typo in a message in the remotewebbrowser.py
> fix(remotewebbrowser): fix typo in a message

- docs/configuration_options.md
- functional_tests/scylla_operator/test_functional.py
- sdcm/cluster_k8s/__init__.py
- sdcm/sct_config.py
- sdcm/stress_thread.py
- sdcm/tester.py
- sdcm/utils/common.py
- sdcm/utils/k8s/__init__.py
- sdcm/utils/k8s/chaos_mesh.py
- test-cases/scylla-operator/functional.yaml
- unit_tests/test_chaos_mesh.py
- unit_tests/test_stress_thread_functions.py
We want to use chaos-mesh for chaos testing k8s clusters.
This PR adds:
* installation of chaos-mesh in k8s cluster for future use.
* example experiment (pod failure) and functional test using it
> feature(chaos-mesh): added installation of chaos-mesh

- functional_tests/scylla_operator/test_functional.py
since the address we connect to the cluster are diffrent then the addresses used by scylla to publish it's nodes.
we need to whitelist the extrenal addresses we use other wise the driver would remove all the connections, since they are not accessable, and we'll fail with connction refused.
> fix(test_operator_managed_tls): add WhiteList when connecting to cluster

- sdcm/stress_thread.py
ipv6 test cases were failing to connect to ipv6 addresses failing like:
```
java.net.SocketException: Protocol family unavailable
```
changing the docker loader to use the host network, fixes that problem
Fix: #5610
> fix(docker-loader): fix ipv6 support

- sdcm/cluster.py
- unit_tests/test_cluster.py
Since on cases we want all of the tables (i.e. for comparing with snapshots) we also need to include those system tables, and not skip them.
Fixes: #5618
Ref: https://github.com/scylladb/scylladb/issues/7186
Ref: https://github.com/scylladb/scylladb/issues/12239
> fix(get_any_ks_cf_list): skip broken tables when filter_empty_tables

- jenkins-pipelines/longevity-50gb-3days-ebs-gp3.jenkinsfile
seem like our groovy pipeline are not handling correctly `test_config` if it has multiple lines
and that's breaks the test like the following:
```
anyconfig.common.errors.UnknownFileTypeError: No parser found for file: file extension=yaml"]
```
> fix(50gb-3days-ebs-gp3): don't use multi line in test_config

- sdcm/provision/azure/provisioner.py
- sdcm/provision/azure/resource_group_provider.py
- sdcm/provision/azure/virtual_machine_provider.py
- sdcm/utils/cloud_monitor/report.py
- sdcm/utils/cloud_monitor/resources/__init__.py
- sdcm/utils/cloud_monitor/resources/instances.py
- sdcm/utils/cloud_monitor/resources/static_ips.py
- sdcm/utils/pricing.py
- unit_tests/lib/fake_provisioner.py
- unit_tests/provisioner/conftest.py
- unit_tests/provisioner/test_provisioner.py
Currently we don't monitor Azure cloud resources usage. This leads to not needed VM's running without notice and generating costs.
This commit adds Azure backend to cloud usage report.
refs: 
- https://github.com/scylladb/qa-tasks/issues/919
> feature(azure): add azure to cloud report

- sdcm/nemesis.py
since now we raise the `UnsupportedNemesis`, there no need to print it again like this in error level, we have a warning for it
```
...
File ".../sdcm/nemesis.py", line 1647, in execute_disrupt_method
disrupt_method()
File ".../sdcm/nemesis.py", line 3848, in wrapper
File ".../sdcm/nemesis.py", line 2848, in disrupt_network_random_interruptions
raise UnsupportedNemesis("for this nemesis to work,
you need to set `extra_network_interface: True`")
sdcm.nemesis.UnsupportedNemesis: for this nemesis to work,
you need to set `extra_network_interface: True`
```
> fix(nemesis): remove exception prints from `execute_disrupt_method`

- sdcm/cluster.py
- sdcm/utils/common.py
* put a 120s wait time on the `request_all` call
* add debug information - trying to help with invesigating of scylladb/scylladb#12301 we are adding print for execute_async and for it's error callback
Ref: https://github.com/scylladb/scylladb/issues/12301
> fix(page-fetcher): extand the wait time calling `request_all`

- defaults/k8s_local_kind_config.yaml
This version includes Kubernetes 1.25.3 as default and we want to test scylla-operator 1.8 with it.
> feature(k8s-kind): upgrade kind version to v0.17.0

- sdcm/utils/azure_utils.py
Sometimes azure api fails during querying resources with resource graph queries.
This commit adds retries for these queries so it is more stable.
refs: #5543
> fix(azure): add retry to listing resources

- sdcm/tester.py
db_info dict is not used in EKS deployment code.
This commit removes it.
> fix(eks): remove redundant db_info dict

- defaults/k8s_gke_config.yaml
- sdcm/cluster_k8s/gke.py
As part of testing scylla-operator 1.8, we should be move to k8s version v1.25
Ref: https://cloud.google.com/kubernetes-engine/docs/deprecations/docker-containerd
> feature(k8s-gke): update to run with k8s v1.24

- Jenkinsfile
- test-cases/scylla-operator/functional.yaml
- vars/byoOperatorPipeline.groovy
- vars/longevityPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
- vars/rollingOperatorUpgradePipeline.groovy
- vars/runSctTest.groovy
Since we still have old version and operator release we would want to test with enabling the sni_proxy setup by default we now can enable it when needed via the pipeline
> feature(k8s-tls): control `k8s_enable_tls` via pipeline parameters

- defaults/k8s_eks_config.yaml
- defaults/test_default.yaml
- test-cases/scylla-operator/functional.yaml
Since we want to test operator 1.8 with latest versions of k8s, we are switch to use 1.24 which is the latest available in EKS
> feature(k8s-eks): update k8s to verison 1.24

- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
- sdcm/k8s_configs/loaders/sts.yaml
- sdcm/remote/kubernetes_cmd_runner.py
- sdcm/scylla_bench_thread.py
- sdcm/stress/base.py
- sdcm/stress_thread.py
- unit_tests/test_remoter.py
Starting with K8S `v1.24` the docker-shim support was removed. 
So, stop using docker for our static loaders because we are going to switch to new K8S versions.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5636
> fix(k8s): make static loaders work on K8S v1.24+

- sdcm/sct_config.py
For the moment, when we specify `new_version` option value
the `sct_config` module assumes we use common VMs approach and performs checks for it.
But, at first, it is not needed in case of K8S.
And, in second, it fails when we set there too new docker image whose version is not yet covered by AMIs or Scylla repos.
So, add check for `K8S` to avoid following error:
>   File "%path%/sdcm/tester.py", line 610, in _init_params
>     self.params = init_and_verify_sct_config()
>   File "%path%/sdcm/sct_config.py", line 2233, in init_and_verify_sct_config
>     sct_config = SCTConfiguration()
>   File "%path%/sdcm/sct_config.py", line 1710, in __init__
>     self['new_scylla_repo'] = find_scylla_repo(new_scylla_version, dist_type, dist_version)
>   File "%path%/sdcm/utils/common.py", line 1619, …
> fix(k8s): don't check packages repos in sct_config module running on K8S

- Jenkinsfile
- functional_tests/scylla_operator/test_functional.py
Since we moved in EKS to k8s version 1.24, the default EBS based storage isn't working should be resolved in https://github.com/scylladb/qa-tasks/issues/952
meanwhile we'll skip this test for EKS
Fixes: #5641
> test(k8s-functional): skip `deploy_helm_with_default_values` for EKS

- test-cases/scylla-operator/kubernetes-platform-upgrade.yaml
> fix(k8s): make K8S upgrade job create SCT runner with bigger disk

- sdcm/nemesis.py
- sdcm/utils/sstable/load_utils.py
In some cloud runs, the nodes have no public IP, and as such cannot download files from s3, like the sstable tarball that is downloaded in the disrupt_nodetool_refresh nemesis. To amend that, I changed SstableLoadUtils.upload_sstables as such that in cloud runs, the tarball would be first downloaded to the sct runner, and then moved to the node.
> fix(disrupt_nodetool_refresh): download tar to the runner in cloud runs

- sdcm/cluster_aws.py
In order to verify correctness of the instance-create-request.
Refs:  [#5645](https://github.com/scylladb/scylla-cluster-tests/issues/5645)
> fix(cluster_aws.py): Add logging for creating an on demand instance

- test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml
use_mgmt is default True for a long time now
in ee6ff8a6d1cc71f160b8026aa1376cb8a688da1e we disabled manager for EKS since we can't install minio in since k8s v1.23 (not without ebs-csi-driver setup)
this flag on the test was mask our configuration for EKS to disable manager, and prevented us form running this test case.
> fix(longevity-50GB-3days-authorization-and-tls-ssl): remove `use_mgmt`

- jenkins-pipelines/feature-limit-streaming-io.jenkinsfile
- sdcm/provision/scylla_yaml/scylla_yaml.py
- test-cases/features/limit-streaming-io.yaml
- unit_tests/test_scylla_yaml.py
Added stream_io_throughput_mb_per_sec limit to 250gb perf test with nemesis to see the impact on latency and nemesis duration.
> test(limit): perf test for limit streaming

- sdcm/mgmt/cli.py
- sdcm/nemesis.py
- unit_tests/test_sdcm_mgmt_cli.py
Since manager 3.0.1, a task's params are no longer printed in the output of 'sctool progress', but instead in the output of 'sctool info'. I replaced the use of 'sctool progress' in the Nemesis._mgmt_backup
> refactor(manager): use sctool info to get tasks' parameters and history

- sdcm/nemesis.py
Tests with bigger set of data need more time for resharding.
This commit prolongs timeout for resharding from 10m to 30m.
refs: #5652
> fix(OperatorNodetoolFlushAndReshard): prolong resharding timeout

- sct.py
- sdcm/sct_runner.py
- sdcm/utils/cloud_monitor/resources/instances.py
- sdcm/utils/common.py
- sdcm/utils/context_managers.py
leave this enviremnt variables behind, cause us to miss cleaning up some of the GKE cluster, since the code was looking for them in the wrong project
Fixes: #5566
> fix(k8s-gke): fix cleanup to not leave env variaible behind

- test-cases/performance/perf-regression-latency-500gb-30min.yaml
- test-cases/performance/perf-regression-latency-k8s-multitenant.yaml
- test-cases/performance/perf-regression.100threads.30M-keys.yaml
Recently we changed the default loader run type on K8S from 'static' to 'dynamic'. But performance tests must use only static ones because they are more performant.
So, configure it explicitly.
> fix(k8s-perf): explicitly set the static loader run type

- sdcm/remote/kubernetes_cmd_runner.py
For the moment, we allow `300` reconnections to an alive `dynamic loader pod` before we consider the test run failed.
In case of `GKE` may be not enough running `12 hours` because connections there may live just couple of minutes.
So, increase to `600` to cover the `12 hours` jobs.
> improvement(k8s): allow more reconnections to a dynamic loader pod

- defaults/test_default.yaml
- sdcm/cluster_k8s/__init__.py
- sdcm/remote/kubernetes_cmd_runner.py
- unit_tests/test_remoter.py
After removal of the docker dependency for the static loader run type in K8S we are not able anymore to run utility loads of other types. So, add such possibility by detecting different load type in the static loader runner and reuse dynamic one in such cases.
> feature(k8s): run dynamic loader pods in parallel for the static ones

- sdcm/k8s_configs/eks/scylla-node-prepare.yaml
Recently the i4i instance types started having 2 nvme disks and the unexpected one started being picked up by the mount command all the time in the `pv-setup` container.
So, fix it by specifying the needed device explicitly when we use mount command.
> fix(k8s-eks): make i4i instances work great again

- defaults/severities.yaml
- longevity_test.py
- sdcm/sct_config.py
- sdcm/sct_events/database.py
- sdcm/tester.py
- sdcm/tombstone_gc_verification_thread.py
- test-cases/longevity/longevity-lwt-500G-3d.yaml
A thread that verifies correctness of tombstone-gc 'repair' mode.
If a tombstone older than last repair is found in a newer sstable,
it raises an error
Task: https://github.com/scylladb/qa-tasks/issues/434
> feature(Tombstone GC): Add a tombstones verification thread

- sdcm/cluster.py
the correct parameter to use in execute_cmd() should be: 'cql_session'.
> fix(get_any_ks_cf_list): wrong usage of parameter 'session'

- sdcm/nemesis.py
- sdcm/utils/k8s/chaos_mesh.py
- unit_tests/test_chaos_mesh.py
Memory stress nemesis does not work on k8s:
- #5455
This commit adds support for chaos-mesh's memory stress experiment.
Also made some bug fixing: additional experiment failure detection.
Code unification to ease adding new experiments.
> feature(chaos-mesh): use chaos-mesh for memory stress in k8s clusters

- sdcm/tester.py
Removed wait_for_nodes_up_and_normal from def run_stress_thread
Since the issue we had with the c-s selecting a random node to connect with been fixed in c-s
> fix(tester): removed wait_for_nodes_up_and_normal from run_stress_thread

- sdcm/cluster_k8s/__init__.py
Since we have cases we want to be able to run with newer loader image and not the exact version we are testing, we should enable it for k8s as we do for VMs.
example use case, when we need to run c-s with fixes to be able to connect to all nodes, when we run ontop of older releases.
> feature(k8s): select loader based on `stress_image.cassandra-stress`

- sdcm/remote/kubernetes_cmd_runner.py
Fixing 3 issues related `KubernetesPodWatcher`: redundand stderr stream read, and premature killing long running loader commands, missing some log lines when drops connection. See commit messages for more details.
> Fix pod watcher kills healthy execution

- functional_tests/scylla_operator/libs/helpers.py
- functional_tests/scylla_operator/test_functional.py
- sdcm/cluster_k8s/__init__.py
- sdcm/nemesis.py
- upgrade_test.py
This reverts commit bf001fc97afc03aa6b0aaba7fe6d7575c7f5b436.
The reason is that GKE cluster may work about hour after pod IPs change not providing any update to the 'endpoint' resources which we listen to. So, return back the manual IP refreshes due to the GKE's slowliness.
> Revert "improvement(k8s): remove redundant explicit Scylla IP mapping refreshes"

- sdcm/nemesis.py
The `disrupt_nodetool_enospc` nemesis doesn't work on the `GKE` backend due to the following bug: https://github.com/scylladb/scylla-cluster-tests/issues/5671
> fix(k8s-gke): skip 'disrupt_nodetool_enospc' due to bug

- configurations/operator/large-collections-12h.yaml
We face issue with 'nodetool_cleanup' nemesis, where it takes too long (https://github.com/scylladb/scylladb/issues/9917).
Commit switches SisyphusNemesis seed to different, so this disruption is not executed.
> fix(test): fix different seed for k8s large collections test

- mgmt_upgrade_test.py
- sdcm/mgmt/cli.py
- sdcm/mgmt/common.py
Since the interval parameter is no longer officially supported for manager 3.0 and later versions,
I replaced its use in the upgrade test with the cron parameter.
Also enclosed the cron value with apostrophes.
> refactor(mgmt_upgrade_test): replace interval param 

- sdcm/k8s_configs/eks/scylla-node-prepare.yaml
partialy revert c62c8c70cd7ebe05804401868754ec10ab9dab8e, in that change we mounted the same device into multiple paths causing a loop that in turn failed the recycling of PVs and caused failure to almost any case changing topoloy
provisioner.log:
```
Cleanup for pv local-pv-1a671d64 failed. Restarting cleanup
Deleting PV file volume "local-pv-1a671d64" contents at hostpath
"/mnt/raid-disks/disk0/pv-01", mountpath "/mnt/raid-disks/disk0/pv-01"
remove /mnt/raid-disks/disk0/pv-01/pv-01: device or resource busy
Cleanup for pv local-pv-1a671d64 failed. Restarting cleanup
```
> fix(k8s-eks-pv-setup): revert wrong mount command

- sdcm/utils/remote_logger.py
We run a python thread that watches for the K8S events objects updates in the Scylla namespace.
For the moment it doesn't print timestamps which would be very useful for debugging because timing matters.
So, fix it by changing the expected output structure in the API call we use for watching updates.
> improvement(k8s): make K8S events print timestamps

- test-cases/longevity/longevity-large-partition-8h.yaml
> improvement(longevity-large-partition-8h): create mview after prepare

- functional_tests/scylla_operator/libs/helpers.py
- functional_tests/scylla_operator/test_functional.py
- sdcm/cluster_k8s/__init__.py
- sdcm/nemesis.py
- sdcm/utils/k8s/__init__.py
- upgrade_test.py
In the `ScyllaPodsIPChangeTrackerThread` thread we set `read` timeout be equal to `3h`.
And it means that if a stream read hangs for any reason then we get next bunch of info out of it only in 3 hours.
And hanging of this kind of stream happens much faster than 3 hours on GKE backend.
Knowing that in a common case a Scylla pod gets up in 3-4 minutes, make the timeout be about it - 3m.
Mostly, it will lead to the redundant reconnections having alive stream,
but 1 redundant API call in 3 minutes is much better than unpredictable errors caused by the wrong IP mapping.
> fix(k8s): make the Scylla IP change watcher thread be more stable

- sdcm/cluster.py
for a while now this failure is happening on tests (mostly artifacts)
```
2023-01-12 18:26:57.006: (TestFrameworkEvent Severity.ERROR) period_type=one-time
event_id=36c76719-0d23-45ba-ba48-29dd497fb3ab, source=ArtifactsTest.stop_nemesis()
message=stop_nemesis (silenced) failed with:
exception=LoggerAdapter.debug() missing 1 required positional argument: 'msg'
```
this is fixing the failure to the test, not the root casue of loosing connection to argus (which #5482 might address)
> fix(argus): print backtrace correctly on `stop_nemesis`

- test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml
- test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
Switch to use syslog-ng default log transport
> fix(alternator-perf-yaml): switch to use syslog-ng logger

- sdcm/provision/common/utils.py
Use double quotes for sed commands
> fix(configure_sshd_script): use double quoting for sed

- defaults/test_default.yaml
- sdcm/cluster.py
we did update branch 2022.1 and 2022.2, and asymmetric test case was working on them
we want that case back and operational also on 2021.1
> Update branch 2021.1 to use latest s-b by default

- vars/managerPipeline.groovy
Since scylla 5.1 is now promoted, we will use it as the default version in all
manager test scenarios
> improvement(manager tests): using scylla 5.1 instead of 5.0

- sdcm/sct_events/group_common_events.py
eval_filter use re.match, this method start matching from the begining of the string.
Added .* to the begining of regexp to search in any place of string
During job with cdc feature, for DecommissionStreamingError upon decommission interruption , 
next log message happened with error:
```
2023-01-12 21:25:34.108 <2023-01-12 21:25:28.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=0f33a6d7-ee60-4acb-9582-8ed1af825767: type=RUNTIME_ERROR regex=std::runtime_error line_number=54745 node=longevity-cdc-100gb-4h-2022-2-db-node-08d07ba6-5
2023-01-12T21:25:28+00:00 longevity-cdc-100gb-4h-2022-2-db-node-08d07ba6-5      !ERR | scylla[7993]:  [shard 10] storage_proxy - exception during mutation write to 10.12.0.234: utils::internal::nested_exception<std::runtime_error> (Could …
```
> fix(ignore_stream_mutation): match regexp in full string

- defaults/severities.yaml
- sdcm/cluster.py
- sdcm/provision/scylla_yaml/scylla_yaml.py
- sdcm/sct_events/database.py
- unit_tests/test_scylla_yaml.py
- upgrade_test.py
Adds a new flag, `consistent_cluster_management` to the upgraded nodes' scylla.yaml and tidies up the way in which we change scylla.yaml contents in rolling_upgrades. It also removes the legacy `enable_3_1_0_compatibility_mode` flag setting. A new continuous event is added to allow for easier debugging of the scylla.yaml updates.
Staging job with test runs: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/rolling-upgrade-raft/
> test(rolling-upgrade): set yaml entries in upgade procedure for raft

- unit_tests/test_base_version.py
5.2 folder was created, so now `UpgradeBaseVersion` would find it when running on master
> fix(TestBaseVersion): update latest master version

- sdcm/cluster_k8s/__init__.py
- sdcm/remote/kubernetes_cmd_runner.py
For the moment, using `dynamic` loader run type on K8S, we allow to use only the same Scylla image as the test target Scylla one when our stress tool is set to be `cassandra-stress`.
This limitation disallows us to test latest stable Scylla versions with the serverless feature of the `scylla-operator`.
So, fix it by considering the `stress_image.cassandra-stress` option first and only if it is not set then use the test target Scylla version.
> fix(k8s): allow to use custom cassandra-stress image in dynamic loaders

- defaults/k8s_eks_config.yaml
- defaults/k8s_gke_config.yaml
- defaults/k8s_local_kind_config.yaml
Specifying a new enough Scylla image that supports the 'serverless' feature for the 'cassandra-stress' loaders will allow us to test the feature against any Scylla version.
With this configuration we will only need to set 'true' value for the 'k8s_enable_tls' option when we want
to test the 'serverless' feature.
> improvement(k8s): use C-S image with serverless feature support

- defaults/k8s_eks_config.yaml
- defaults/k8s_gke_config.yaml
- defaults/k8s_local_kind_config.yaml
- defaults/test_default.yaml
Update default config files for all K8S backends according to the following statements:
- We should use perf tuning on EKS.
- We can/should not use perf tuning on local K8S.
- We do not plan to test and fix perf issues on GKE in nearest future.
> improvement(k8s): tune K8S performance only running on EKS backend

- defaults/k8s_eks_config.yaml
- sdcm/tester.py
If turned out that existing `2 auxiliary nodes` is not enough when we enable `scylla-manager` and `serverless` features in addition to all other pods which get installed always.
So, make `EKS` use `3 auxiliary nodes` by default to avoid scheduling problems.
> fix(k8s-eks): use 3 auxiliary nodes on EKS by default

- Jenkinsfile
- defaults/aws_config.yaml
- jenkins-pipelines/hydra-clean-runner-instances.jenkinsfile
- jenkins-pipelines/hydra-show-jepsen-results.jenkinsfile
- jenkins-pipelines/hydra-show-monitor.jenkinsfile
- sct.py
- sct_ssh.py
- sdcm/sct_runner.py
- sdcm/utils/aws_builder.py
- test-cases/PR-provision-test-docker.yaml
- test-cases/manager/manager-regression-multiDC-set-distro.yaml
- test-cases/performance/perf-search-best-throughput-config.yaml
- utils/copy_ami_to_all_regions.sh
- utils/create_aws_region_data.py
- vars/byoLongevityPipeline.groovy
- vars/cdcReplicationPipeline.groovy
- vars/getCloudProviderFromBackend.groovy
- vars/getJenkinsLabels.groovy
- vars/longevityPipeline.groovy
- vars/managerPipeline.groovy
- vars/rollingOperatorUpgradePipeline.groovy
- vars/rollingUpgradePipeline.groovy
Since we are not using those builder all the time, we are starting to create them as each time we start a job.
* very small machine that are only use to spin off the test
* in some cases it should be able to run the test (artifact test or SCT CI)
* this is creating the ASGs and launch templates in all regions we operate
* configure those ASGs in jenkins
* switch all monitors to ubuntu jammy, since the old centos images
we use aren't available anymore across all regions
Testing:
> feature(sct-builders): move builder to auto scaling group

- sdcm/nemesis.py
When running memory stress disruption in k8s multitenant setup, tester object has no reference to k8s_cluster causing this nemesis to fail.
Fix is about setting proper parent object (db_cluster) for k8s_cluster instance.
fixes: #5716
> fix(MemoryStress): fix k8_cluster reference for multitenant

- data_dir/nemesis.yml
- data_dir/nemesis_classes.yml
- functional_tests/scylla_operator/conftest.py
- functional_tests/scylla_operator/test_functional.py
- sdcm/cluster_k8s/__init__.py
- sdcm/cluster_k8s/eks.py
- sdcm/cluster_k8s/gke.py
- sdcm/cluster_k8s/mini_k8s.py
- sdcm/nemesis.py
- test-cases/scylla-operator/longevity-scylla-operator-3h-terminate-decommission-add.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-terminate-replace.yaml
- unit_tests/test_nemesis_sisyphus.py
Changes:
- Split `disrupt_terminate_and_replace_node_kubernetes` into following:
- `disrupt_drain_kubernetes_node_then_replace_scylla_node`
- `disrupt_terminate_kubernetes_host_then_replace_scylla_node`
- Split `disrupt_terminate_decommission_add_node_kubernetes` into following:
- `disrupt_drain_kubernetes_node_then_decommission_and_add_scylla_node`
- `disrupt_terminate_kubernetes_host_then_decommission_and_add_scylla_node`
- Rename `disrupt_replace_node_kubernetes` method -> `disrupt_replace_scylla_node_on_kubernetes`.
- Rename `OperatorNodeTerminateAndReplace` class -> `DisruptKubernetesNodeThenReplaceScyllaNode`.
- Rename `OperatorNodeTerminateDecommissionAdd` class -> `DisruptKubernetesNodeThenDecommissionAndAddScyllaNode`.
Reason:
Above is done because we were using 3 different …
> improvement(k8s): split K8S node diruptive nemesis to separate methods

- sdcm/nemesis.py
Currently usage of `_is_chaos_mesh_initialized` is wrong - parentheses are missing. This leads checks always return true regardless of the state.
Fixes by adding proper function invocation.
> fix(chaos-mesh): fix use of is_chaos_mes_initialized method

- sdcm/fill_db_data.py
- sdcm/utils/version_utils.py
- upgrade_test.py
- utils/get_supported_scylla_base_versions.py
the package complains about our Scylla versions
when we have the full version format including
commit hash and date (e.g. `5.2.0~rc0-0.20230119.34ab98e1be2e`)
with tilde or dash.
this change will give to the `parse_version` function
only `major.minor.micro` for the sake of comparisons,
as everything else is ignored anyway.
> improvement(parse_version): align to expected version format 

- test-cases/longevity/longevity-counters-multidc.yaml
We face the issue with disconnecting from cluster after simple table modifications in scylla-bench (counters multidc test): https://github.com/scylladb/scylla-bench/issues/114
It was proven it behaves correctly when s-b is in version 0.1.3. This commit pins s-b for couters multidc test.
> fix(test): pin scylla-bench to fix multidc counter test

- configurations/run_db_node_benchmarks.yaml
- defaults/severities.yaml
- defaults/test_default.yaml
- jenkins-pipelines/perf-regression-latency-non-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-latency-non-shard-aware-1TB.jenkinsfile
- jenkins-pipelines/perf-regression-latency-non-shard-aware-250gb-with-nemesis.jenkinsfile
- jenkins-pipelines/perf-regression-latency-shard-aware-1TB.jenkinsfile
- jenkins-pipelines/perf-regression-latency-shard-aware-250gb-with-nemesis.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-non-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-shard-aware-30min.jenkinsfile
- performance_regression_test.py
- sdcm/cluster.py
- sdcm/report_templates/results_latency_during_ops_short.html
- sdcm/report_templates/results_performance.html
- sdcm/results_analyze/__init__.py
- sdcm/sct_config.py
- sdcm/sct_events/system.py
- sdcm/tester.py
- sdcm/utils/benchmarks.py
- vars/perfRegressionParallelPipeline.groovy
Run and check results of hw performance test before usual performance
test, to be sure that all db nodes have similar performance on hardware
> feature(check_hw_perf): Validate hw performance for performance test

- defaults/test_default.yaml
The Reactor-Stall trace might be less accurate than in kernel traces.
It would be helpfull to analyse reactor-stall issues if these traces
are enabled for all tests by default.
Refs: https://github.com/scylladb/scylladb/issues/12623
> improvement(kernel traces): Enable print_kernel_callstack by default

- sct.py
One of the recent changes (https://github.com/scylladb/scylla-cluster-tests/pull/5721) added new required parameter `test-name` to the `create-sct-runner` command of the `sct.py` module.
It broke backwards compatibility and made the `show-monitor` CI job fail.
So, fix it by making this new parameter be optional because it is not needed in case of the `show-monitor` CI job.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5727
> fix(sct.py): make test-name param be optional for create-sct-runner cmd

- functional_tests/scylla_operator/test_functional.py
- sdcm/nemesis.py
We have `flush and reshard` nemesis and functional K8S test. Both are identical in steps.
One of the steps it so check that all scylla containers didn't have additional restarts and are successful from a first attempt.
It is not correct assumption. We may get 1 or 2 restarts which do not influence a Scylla cluster workability.
From a user point of view he waits about the same time before a new Scylla member becomes up and running.
So, remove redundant logic for checking restart count which will make the logic be more stable.
> fix(k8s): make flush and reshard logic be more stable

- sdcm/nemesis.py
- sdcm/sct_events/group_common_events.py
As mentioned in https://github.com/scylladb/scylladb/issues/11972 when we run MemoryStress we tend to expect very high reactor stall times. As this is not deemed unexpected, this commit lowers the severity for such events to WARNING.
> fix(nemesis): ignore reactor stalls in MemoryStress

- defaults/azure_config.yaml
- docker/env/Dockerfile
- docker/env/version
- sdcm/sct_runner.py
Modern Scylla images built on top of Ubuntu 22.04 and in result we have compatibility problems when try to run Scylla' Docker image on SCT Runner.
For example:
```
$ docker run --entrypoint java scylladb/scylla-nightly -version [0.003s][warning][os,thread] Failed to start thread "GC Thread#0" - pt... 
#
```
This particular problem w/ Java makes it impossible to run c-s on SCT Runner using Scylla' Docker image.
See https://stackoverflow.com/a/72841934
Also, we need to upgrade base image for SCT because of too old sudo package.
> fix(sct_runner): upgrade runner image to Ubuntu 22.04

- jenkins-pipelines/operator/scale/operator-scale-many-clients-4h.jenkinsfile
- test-cases/scylla-operator/longevity-scylla-operator-many-clients-4h.yaml
We want to test how scylla on k8s is working with many clients.
This commit adds k8s test based on many-clients test.
Test works, but SNI Proxy limits throughput to ~17kops and needs further scaling up.
> test(scale-k8s): add many-clients test to k8s

- sdcm/k8s_configs/chaos-mesh/gke-auth-workaround.yaml
- sdcm/utils/k8s/chaos_mesh.py
> fix(chaos-mesh): make admission-controller not block it on GKE

- sdcm/cluster.py
We are trying to harden our machine image by applying CIS rules, and it's recommended to use strict umask setting (see scylladb/scylla-pkg#2953). However, it causes permission error on scylla-housekeeping again, just like we saw on OEL8 AMI (scylladb/scylladb#9683).
This is because the fix (79868771282b89664b6be64d2070331ada0f2afb) was only limited for OEL8, we should apply it on any distributions since we can set strict umask on any distributions.
Fixes scylladb/scylladb#12610
> fix: set permissions to scylla-manager.repo on any distributions

- sdcm/utils/k8s/chaos_mesh.py
looks chaos-mesh does not work on GKE as
chaos-daemons are not deployed.
Added `tolerations` settings for chaos-daemons to use scylla
> fix(chaos-mesh): fix installation for gke

- sdcm/cluster_k8s/__init__.py
- sdcm/k8s_configs/ingress-controller/10_haproxy-kubernetes-ingress.configmap.yaml
Since we added some of the producation configuration to the ingress haproxy, the values for `maxconn` is too high for the local kind setup and fails with the following error:
```
[ALERT]    (286) : config : Cannot compute the automatic maxsslconn because
global.maxconn is already too high for the global.memmax value (31 MB).
The absolute maximum possible value without SSL is 780, but 70000 was found
and SSL is in use.
```
> fix(k8s_local): ingress maxconn value is too high

- defaults/k8s_eks_config.yaml
- defaults/k8s_gke_config.yaml
- defaults/k8s_local_kind_config.yaml
- sdcm/nemesis.py
- sdcm/utils/k8s/chaos_mesh.py
- test-cases/scylla-operator/functional.yaml
On k8s we can make filesystem respond with errors artificially. E.g. instead of filling up disk we can make filesystem respond with ENOSPC error.
This commit adds support for IOChaos from chaos-mesh (https://chaos-mesh.org/docs/simulate-io-chaos-on-kubernetes/). Replaces enospc nemesis logic for k8s - so we don't fill up disks.
> feature(enospc): fake enospc error on k8s with chaos-mesh

- configurations/perf-loaders-non-shard-aware-config.yaml
- configurations/perf-loaders-shard-aware-config.yaml
- defaults/aws_config.yaml
- sct.py
- sdcm/sct_config.py
- sdcm/utils/common.py
- test-cases/performance/perf-regression-latency-lwt-big.yaml
- test-cases/performance/perf-regression-latency-lwt-small.yaml
- test-cases/performance/perf-regression-throughput-lwt-big.yaml
- test-cases/performance/perf-regression-throughput-lwt-small.yaml
- test-cases/performance/perf-search-best-throughput-config.yaml
- unit_tests/test_config.py
- unit_tests/test_scan_operation_thread.py
task: https://github.com/scylladb/qa-tasks/issues/268
added functionality to automaticaly convert image name  to ami_ids per region
added unit tests or converting logic
remove unused logic "assume multi dc by n_db_nodes set size" becuse when run it, "_check_multi_region_params" is fail
> improvement(sct_config): Refer to AMI images by name instead of AMI ID

- unit_tests/conftest.py
- unit_tests/test_scan_operation_thread.py
ignore errors like FileNotFoundError on EventsUtilsMixin teardown in shutil.rmtree 
not  best solution but fix the current error at the end of unit tests
> fix(Unit tests): fix EventsUtilsMixin teardown

- docker/env/version
- requirements.in
- requirements.txt
- sct.py
- utils/.bash_completion
for some time the tab completion we were using wasn't working removed the package that we were using, and switch to using click core tab completion support.
also upgrade fabric/paramiko to get rid of the annying warning, which was part of the breakage of completion as well:
```
CryptographyDeprecationWarning: Blowfish has been deprecated
```
currently we only support bash (even that click supports also zsh and fish, and one can manual setup them if needed)
> fix(hydra): fix tab completion

- data_dir/c-s_profile_3si_5queries.yaml
- data_dir/c-s_profile_4mv_5queries.yaml
for OSS it shouldn't change anything, as STCS is the default, but for enterprise ones, now the default is ICS, hence to have both being tested, this one will be explicitly set to use STCS, while the ICS job does use explicitly ICS in it.
> improvement(mv-si longevity): explicitly set STCS

- configurations/azure/azure_rolling_upgrade.yaml
- defaults/azure_config.yaml
- sdcm/cluster_azure.py
- test-cases/artifacts/azure-image.yaml
- unit_tests/provisioner/azure_default_config.yaml
- unit_tests/provisioner/test_azure_region_definition_builder.py
Due available quotas we switch instance types for Azure tests.
> fix(azure): switch instance types

- configurations/es_mapping/performance_index_mapping.json
- defaults/test_default.yaml
- docs/hydra-create-es-index.md
- performance_regression_test.py
- sct.py
- sdcm/db_stats.py
- sdcm/sct_config.py
- sdcm/tester.py
- sdcm/utils/csrangehistogram.py
- sdcm/utils/es_index.py
- test-cases/performance/perf-regression-latency-125gb.yaml
- test-cases/performance/perf-regression-latency-1TB.yaml
- test-cases/performance/perf-regression-throughput-125gb.yaml
- test-cases/performance/perf-regression.100threads.30M-keys.yaml
Performance tests require new branch based on latest master. such branch should become branch-perf-v14
For that there is a decision to create new index for performance which will store new results including the hdr histograms data 
and new performance results for latest version.
for that new index will be created using  new sct subcommand create-es-index which allow to set up appropriate mappings for field. "test_details.start_time" will now have date type and will allow to build valid dashboards in kibana
Also hdr histogram data will be stored in es documents.
> New performance index

- sdcm/utils/benchmarks.py
Because we ignore exceptions when running benchmarks we don't know what is the reason of failure. Later steps anyway fail the test.
This commit prolongs timeout for benchmarks as we presume they take longer than 300 seconds and stop ignoring exceptions so we have more details when debugging issues.
> fix(benchmarks): prolong benchmark timeout

- sdcm/tester.py
fix bug intrduced in refactor(fullscan) introducing back the Fullscan refactoring, Fixing: #5495 initial change are https://github.com/scylladb/scylla-cluster-tests/pull/5355/files#
@juliayakovlev  found 1 more issue regarding https://github.com/scylladb/scylla-cluster-tests/pull/5355. in copy_table method
there are several non-related to full_scan changes connected with changing literal **table_name** to **ks_cf**
> fix(tester.py): fix copy_table method

- test-cases/enterprise-features/workload-prioritization/longevity/longevity-sla-system-24h.yaml
After https://github.com/scylladb/scylla-cluster-tests/pull/5710 'run_fullscan' parameter have to be list.
> fix(sla system): fix run_fullscan parameter

- vars/longevityPipeline.groovy
- vars/runSctTest.groovy
To run gemini jobs with specified gemini seed also for reproducing issues longevigyPipeline was updated with new pipeline parameter gemini_seed
> fix(longevityPipeline): Add gemini seed to longevityPipeline

- vars/jepsenPipeline.groovy
- vars/longevityPipeline.groovy
- vars/managerPipeline.groovy
- vars/rollingOperatorUpgradePipeline.groovy
seems like 2min isn't enough cause of recent changes to use a weaker meachines for jenkins builders, and addition of more AWS api calls during configuration read (to translate name to ami ids)
> fix(pipelines): enlarge timeout for get duration stage

- sct.py
- sdcm/utils/aws_builder.py
- sdcm/utils/gce_builder.py
- sdcm/utils/gce_region.py
- vars/getJenkinsLabels.groovy
* added `GceBuilder` to create templates and configure them in jenkins
* move the default labels for GCE backend to use those templates
> feature(sct-builders): move to use gcp launch template

- sdcm/utils/benchmarks.py
Fixes: #5751. If any node performance tool doesn't correclty store result in es document, next counting Average() value could lead to exception DivisionByZero, because final list is empty for failed metrics.
use list with single element [0.0] to avoid such collisions.
> fix(node_benchmark): correctly count average if metric is missing

- test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
> ci(k8s): use K8sSetMonkey nemesis for 2clients setup

- sct.py
in the function used to create release Jenkins jobs, we didn't make any filter between artifacts and the offline artifacts, as many of them don't fit the
offline artifacts tests concept, as images and
web install.
this PR is addressing that, excluding few regex
of job names used for the regular artifacts,
to not create them as artifacts offline.
> fix(artifacts offline): remove unecessary jobs

- configurations/es_mapping/performance_index_mapping.json
Change order of date formats to proper detect date format. if epoch_milis is before epoch_seconds, date in seconds parsed as miliseconds and in correctly date used in ES
> fix(es_index_mapping): change order of date formats

- jenkins-pipelines/perf-regression-latency-non-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-latency-non-shard-aware-1TB.jenkinsfile
- jenkins-pipelines/perf-regression-latency-non-shard-aware-250gb-with-nemesis.jenkinsfile
- jenkins-pipelines/perf-regression-latency-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-latency-shard-aware-1TB.jenkinsfile
- jenkins-pipelines/perf-regression-latency-shard-aware-250gb-with-nemesis.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-non-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-shard-aware-125gb.jenkinsfile
- jenkins-pipelines/perf-regression-throughput-shard-aware-30min.jenkinsfile
- sdcm/results_analyze/__init__.py
- vars/perfRegressionParallelPipeline.groovy
New performance jobs use several configuration files to run same test with different attributes: driver(shared/non-shard aware), hardware performance test enabling, etc). Such test when send email report results could be difficult to split.
Add new parameter to pipeline which allow to set email title for specific job.
> fix(performance_email_title): Add email title parameter to pipeline

- sct.py
there was a function skipping few keywords when
creating the jobs for release in Jenkins.
happens that, it had some issues, and didn't really filter out some important ones that should not be
created, and removed some, that we could run without any problems (like `artifacts-amazon2`)
this PR enhances what #5770 already started,
and removed the bogus "filter".
> fix(artifacts offline generator): re-introduce amazon2

- defaults/test_default.yaml
- docker/gemini/image
- unit_tests/test_config.py
New fix for memory leak has been merged and new gemini version released. Let's use it.
> fix(gemini): update gemini version to 1.7.8

- configurations/raft/consistent_cluster_management_off.yaml
- jenkins-pipelines/consistent_cluster_management_disabled/longevity-1tb-7days.jenkinsfile
- jenkins-pipelines/consistent_cluster_management_disabled/longevity-large-collections-12h.jenkinsfile
- jenkins-pipelines/consistent_cluster_management_disabled/longevity-large-partition-8h.jenkinsfile
- jenkins-pipelines/consistent_cluster_management_disabled/longevity-mv-si-4days.jenkinsfile
- jenkins-pipelines/consistent_cluster_management_disabled/longevity-schema-changes-3h-with-raft.jenkinsfile
- sct.py
Disable feature consistent-cluster-management feature (raft group-0)
> feature(consistent-cluster-management): Disable feature for several jobs

- sdcm/utils/csrangehistogram.py
CS could write to hdr.log value for some intervals higher value, than was configured. Python HDR histogram lib doesn't support autorescale feature (like in java lib), which allow to rescale histogram during merging.
Increase max value for HDR Histogram which allow
to store from 1 nanosecnds up to 24 hours
> fix(csrangehistogram): Increase max value for hdr histogram

- docker/env/version
- requirements.in
- requirements.txt
seems like they are causing leftover timers due to https://github.com/pyinvoke/invoke/issues/910
when we are using invoke for local commands
Fixes: #5781
tested it on specific pipeline I've built that would only do the get duration stage:
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/temp_pipeline/12/
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/temp_pipeline/13/
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/temp_pipeline/14/
> revert(invoke): revert fabrio/invoke

- vars/jepsenPipeline.groovy
- vars/longevityPipeline.groovy
- vars/managerPipeline.groovy
- vars/perfSearchBestConfigParallelPipeline.groovy
- vars/rollingOperatorUpgradePipeline.groovy
The stage times out often and its clear that 5 minutes is too short of a timeout. As such, I increased the timeout to 10 minutes across all of the pipelines.
> fix(jenkins pipeline): Increase timeout of the 'Get test duration' stage

- internal_test_data/complex_test_case_with_version.yaml
- unit_tests/test_config.py
some amis are old and were removed, we should
stop using them on the unittest
> fix(unittest): switch to newer amis

- vars/longevityPipeline.groovy
When sct-runner is not created due some error, longevity test continues using builder machine. This causes issues on Azure when builder is located in external network and uses private ips. Also with new builders which are weak are not capable of running longevity.
This commit removes exception catch from `Create SCT Runner` step, failing whole pipeline early.
> fix(pipeline): dont fallback to builder when no sct runner

- sdcm/fill_db_data.py
- sdcm/utils/version_utils.py
- unit_tests/test_version_utils.py
it was failing like:
```
File ".../sdcm/fill_db_data.py", line 3173, in version_non_frozen_udt_support
return self.parsed_scylla_version >= parse_scylla_version(version_with_support)
File ".../sdcm/utils/version_utils.py", line 123, in parse_scylla_version
return parse_version(version_format.search(version_to_parse)[0])
TypeError: 'NoneType' object is not subscriptable
```
since the version passed to is was not matching the regex
```python
NON_FROZEN_SUPPORT_ENTERPRISE_MIN_VERSION = '2020'
```
now it checking it better and rasining clear exception why it was failing
> fix(parse_scylla_version): better check the version

- sdcm/utils/data_validator.py
Fix `sdcm.utils.data_validator.LongevityDataValidator.validate_deleted_rows`. Handle case in validation of deleted rows when rows were not deleted. Print relevant message
> fix(data validator): rows were not deleted

- performance_regression_test.py
- sdcm/utils/csrangehistogram.py
for performance latency test, start time for each sub_test was set incorrectly, and was equal to start_time of the test. This bring not need calculation of histogram for preload period and a lot of empty histograms in results.
Set the valid start time for each subtest based on test_details.start_time and set start_time and end_time parameters as required for build_histogram_by_range to avoid possible case, when histogram intervals could be build infinitely or till sys.maxsize()
> fix(csrangehistogram): skip empty built histogram

- sdcm/fill_db_data.py
- upgrade_test.py
When upgrading a node, the truncate_entries decorator is called. Inside it, we create a cql connection inwhich we expect 'truncate_ks' to have been created by this point. In test_generic_cluster_upgrade, however, we did not create the keyspace beforehand, which caused it to fail. I altered test_generic_cluster_upgrade so that truncate_ks and fill it with data before truncate_entries is called.
> fix(test_generic_cluster_upgrade): Added truncate_ks

- test-cases/scylla-operator/longevity-scylla-operator-3h-add-remove-rack.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-backup.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-cluster-rolling.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-grow-shrink.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-repair.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-replace.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-stop-start.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-terminate-decommission-add.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-terminate-replace.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h.yaml
Having load 2k op/s (2 laoders * 1k op/s) for 3 nodes with i3.4xlarge nodes is too small.
So, increase it to be 5k op/s per loader.
On GKE nodes are slower than on EKS, but must be able to handle 10k op/s too.
> improvement(k8s): increase load in K8S jobs

- defaults/test_default.yaml
- longevity_test.py
- sdcm/sct_config.py
according to improvement
https://github.com/scylladb/scylla-cluster-tests/pull/2823
Remove 'default' parameter from params.get() method
> revert(sct)config): revert added default param for get method

- sdcm/nemesis.py
since we didn't yet test those nemesis in other regular test case we shouldn't yet let them run, only after we'll verify and test them.
> fix(sla): limit SLA nemesis only to sla test cases

- sdcm/nemesis.py
b26acc9530f5629002984b3a1566a2ac18c98164 introduced a 5min timeout of the rebuild command, that won't work on any dataset the same and isn't part of the intended fix, also doing it 3 times doesn't really works any faster.
so timeout and retry are removed.
> fix(decommission_streaming_err): remove timeout/retry from rebuild

- internal_test_data/negative_fullscan_param.yaml
- internal_test_data/positive_fullscan_param.yaml
- sdcm/scan_operation_thread.py
- sdcm/sct_config.py
- test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
- test-cases/longevity/longevity-large-partition-3h.yaml
- test-cases/longevity/longevity-large-partition-4days.yaml
- test-cases/longevity/longevity-large-partition-8h.yaml
- unit_tests/test_config.py
split validation into 2 parts
1) validation logic in sct_cofig contains format validation 
2) validation logic in scan_operation_thead.py contains data validation
3) fix existing miss configurations
must be rebased and merge after https://github.com/scylladb/scylla-cluster-tests/pull/5797
> improvement(run_fullscan): implement param validation functionality

- vars/createSctRunner.groovy
When `test_name` param is empty, toJson coverter converts value to `null`. Better to use empty string instead (e.g. null value is forbidden in Azure tags)
refs: #5819
> fix(pipeline): set empty test_name when not set

- sdcm/provision/azure/virtual_machine_provider.py
- unit_tests/provisioner/test_provisioner.py
Azure does not accept 'null' as tag value. This causes an issue when jenkins param without a value is assigned to some tag - can't create such VM in that case.
This commit makes 'null' values to be replaced with empty string in tags.
fixes: #5819
> fix(Azure): fix when tag value is null

- test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
- test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h-ics.yaml
this version AMIs doesn't exists anymore, and we should be use more recent version to compare with in those test cases
> fix(test_case_lint): remove 2020.1.7 from test configuration

- docs/configuration_options.md
- sdcm/sct_config.py
- sdcm/tester.py
- sdcm/utils/common.py
- unit_tests/test_utils_common.py
- vars/byoLongevityPipeline.groovy
- vars/cdcReplicationPipeline.groovy
- vars/longevityPipeline.groovy
- vars/managerPipeline.groovy
- vars/provisionResources.groovy
- vars/runSctTest.groovy
`tag_ami` was created to tag AMIs with results of tests we never used that idea, and nowdays when we have Argus as a centeral place for release test results, there's no point for this feature stay in the code.
(also it testing was basing on specific AMI that is now deleted)
> revert(tag_ami): remove a `tag_ami` feature that is not in use

- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_docker.py
- sdcm/nemesis.py
- sdcm/provision/scylla_yaml/scylla_yaml.py
- unit_tests/test_scylla_yaml.py
In Scylla 5.2 was added possibility to replace a node by it's host_id. 
It can be done by setting `replace-node-first-boot` Scylla option instead of old `replace-address-first-boot` one.
So, add support for it.
> feature(node): support new 'replace_node_first_boot' Scylla option

- defaults/k8s_local_kind_config.yaml
- test-cases/scylla-operator/functional.yaml
If we do not specify scylla operator version for any local K8S (kind) test run then we get following incompatibility error:
no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
The root cause for it is that we use K8S v1.25 where 'policy/v1beta1' API support was dropped.
So, use latest stable scylla-operator version which won't use this old API.
> fix(K8S): use latest stable scylla-operator v1.8.0

- functional_tests/scylla_operator/test_functional.py
This reverts commit a39d1aa9f23caecaf03c97288ee0b594af4b6d39.
Reason: The support was added in the following PR:
https://github.com/scylladb/scylla-cluster-tests/pull/5658
> Revert "test(k8s-functional): skip `deploy_helm_with_default_values` for EKS"

- sdcm/utils/common.py
list_container_objects method in gce_download_dir returns list of objects in gce bucket. Previously first returned element
was folder itself. Latest run shows that now method return only objects
in bucket. Current implementation could skip first object or if only one object in bucket don't download anything and later fail the job.
Add checks element by name and filter out objects with non-relevant names
> fix(gce_download): Skip first element by name upon download

- utils/get_supported_scylla_base_versions.py
we have a map, of which OSS version relates to an
enterprise, so we could calculate the base version when running rolling upgrade.
up until now, the base version was only 2022.2
> fix(get_supported_scylla_base_versions): adding 2023.1

- functional_tests/scylla_operator/conftest.py
- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
- sdcm/utils/version_utils.py
- unit_tests/test_version_utils.py
In various cases we need to know scylla or scylla-operator version to make some desicions.
The structure of versions differs for GA and dev/rc versions. Also, it differs based on the source of version - binary or docker image.
We used to use `packaging.version.LegacyVersion` class for comparisons. But it got removed from the latest `packaging` package versions.
So, stop using that library and replace it with our own even more improved classes for comparisons of Scylla and Scylla operator versions.
Examples of usage:
ComparableScyllaVersion("5.1.0~rc1") < "5.1.0"
ComparableScyllaVersion("5.1.rc1") > "5.1.0-0.20220922.539a55e35"
ComparableScyllaVersion("5.2.rc1") > "5.2.0-dev-0.20230109.08b3a9c786d9"
The same is done for Scylla Operator
in the ComparableScyllaOperatorVersion class where …
> feature(versions): add classes for scylla versions comparisons

- vars/byoLongevityPipeline.groovy
- vars/cdcReplicationPipeline.groovy
- vars/jepsenPipeline.groovy
- vars/managerPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
- vars/perfSearchBestConfigParallelPipeline.groovy
- vars/rollingOperatorUpgradePipeline.groovy
- vars/rollingUpgradePipeline.groovy
Do the same thing which is done at (https://github.com/scylladb/scylla-cluster-tests/pull/5794) in all the pipelines which try to create SCT runners.
> fix(pipeline): dont fallback to builder when no sct runner. part2

- vars/createSctRunner.groovy
- vars/jepsenPipeline.groovy
- vars/perfRegressionParallelPipeline.groovy
- vars/perfSearchBestConfigParallelPipeline.groovy
- vars/rollingUpgradePipeline.groovy
PR (https://github.com/scylladb/scylla-cluster-tests/pull/5721) added one more required 'param' to the `vars/createSctRunner.groovy` groovy file - `test_name`.
And all the pipelines which do not define this param fail causing the need to create workarounds (https://github.com/scylladb/scylla-cluster-tests/pull/5821).
So, add `test_name` parameter to all the pipelines which do not have it and create SCT runners.
>  fix(sct-runner): add 'test_name' pipeline param for pipelines

- sdcm/nemesis.py
fix fail prepare_start_stop_compaction
in case of no non system ks_cf
initial error:
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4081, in wrapper
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 775, in disrupt_start_stop_validation_compaction
compaction_args = self._prepare_start_stop_compaction()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 615, in _prepare_start_stop_compaction
ks, cf = self._get_random_non_system_ks_cf()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 609, in _get_random_non_system_ks_cf
ks_cf = random.choice(self.cluster.get_non_system_ks_cf_list(
File "/usr/local/lib/python3.10/random.py", line 378, in choice
return …
> fix(nemesis): fix prepare_start_stop_compaction

- sdcm/fill_db_data.py
- sdcm/utils/version_utils.py
- unit_tests/test_version_utils.py
- utils/get_supported_scylla_base_versions.py
Use `ComparableScyllaVersion` instead of the `parse_scylla_version`.
Delete `parse_scylla_version` as unneeded.
It is follow-up for the following PR: https://github.com/scylladb/scylla-cluster-tests/pull/5817
> improvement(versions): Use ComparableScyllaVersion in more places

- jenkins-pipelines/perf-regression-latency-650gb-with-nemesis.jenkinsfile
- sdcm/results_analyze/__init__.py
- test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
following definition of acceptance criteria for this
test, these changes are moving in the direction
to adjust existing test to follow the required
througput, instance type, gaussian STDEV and other
to be able to run the acceptance criteria as defined 
in a document (https://docs.google.com/document/d/1i4Scus4OW4DMfVJGyBSN7dJF0Mb1XPRkXkBzsde4_40/edit?usp=sharing).
the changes were basically:
* changed instance type to i3en as we consider i3 deprecated
* dataset should be 10 * max memory in the cluster, so:
* * 10 * 64GB (as we write with RF=3) = ~650GB
* moved from throttle to fixed, to force get 50% of max throughput
* changed c-s gaussian distribution from `12500000` to `1200000` to
to get ~70% cache hit ratio (previously had ~20%) 
* increased stress and test durations, to fit new …
> improvement(latency with ops): adjust to follow acceptance criteria

- sdcm/sct_events/event_handler.py
- sdcm/sct_events/events_processes.py
- sdcm/tester.py
We face issues with stopping event_handler - it hangs indefinitely. I realized stopping it early is actually redundant.
This commit removes explicit stop of event_handler as it is stopped by `stop_events_device` function at later teardown stage. At later stage sct is less loaded with tasks and maybe it will help solving the issue.
Additionally debug messages on events devices stop were added to have better understanding on which step is hanging exactly in case we still hit the issue.
refs: #5626
> fix(event-handler): remove redundant event handler stop

- defaults/test_default.yaml
- jenkins-pipelines/rolling-upgrade-ubuntu22.04.jenkinsfile
- jenkins-pipelines/upgrade-with-raft/rolling-upgrade-centos8-with-raft.jenkinsfile
- jenkins-pipelines/upgrade-with-raft/rolling-upgrade-debian11-with-raft.jenkinsfile
- jenkins-pipelines/upgrade-with-raft/rolling-upgrade-ubuntu22.04-with-raft.jenkinsfile
- sct.py
- sdcm/sct_config.py
- upgrade_test.py
- vars/rollingUpgradePipeline.groovy
as of now, and since fd6033769560d9b7d1ad693cffc40679b9043de5, all
upgrade jobs have raft enabled on target version.
As this is still not the default option, we want to run part of the
jobs with raft enabled, and all others will be disabled.
and as part of 5.2/2023.1 effort, this PR is introducing
3 new upgrade tests that will run exclusively with raft
enabled.
> test(upgrade_test): enable raft for some upgrade jobs

- sdcm/sct_runner.py
Previously, we increased the sct runner's disk by 40GB if a scenario was at lease 3 days long. However, it seems that even shorter runs require an additional disk space, so I altered instance_root_disk_size so that the additional disk space will be added on every scenario that is longer than 36 hours
> fix(instance_root_disk_size): lower duration requirement for extra space

- longevity_test.py
- mgmt_cli_test.py
- sdcm/mgmt/cli.py
- sdcm/utils/loader_utils.py
```
feature(manager): Added the ability to create a restore task 
New in manager 3.1.
A new task type that will restore the data of a table or even an entire cluster
from a backup
```
``` 
refactor(manager_cli_test): remove duplicated loader functions 
Both '_run_all_stress_cmds' and 'run_prepare_write_cmd' were included in
BackupFunctionsMixIn, when they were copies of the same functions in LoaderUtilsMixin.
So I deleted the functions from BackupFunctionsMixIn and used LoaderUtilsMixin instead.
```
```
improvement(manager): Added stress read function to verify restores 
To confirm that the manager's restore task has indeed successfully restored the backed up data,
I added the run_read_stress to the BackupFunctionsMixIn, so we will be able to run it after a
restore task has ended, and …
```
> feature(manager): Added the ability to create a restore task

- sdcm/report_templates/results_latency_during_ops_short.html
- sdcm/utils/decorators.py
- sdcm/utils/latency.py
Add new column, which contain operation duration in seconds
> fix(perf-nemesis-latency): Add operation duration to report

- sdcm/tester.py
if histogram is empty because provide interval
doesn't contain data in hdr log files, ClusterTester.build_range_histogram method could fail with error: list index out of range.
Check if histogram is empty and return empty dict
> fix(build_range_histogram): return empty dict if histogrma empty

- sdcm/nemesis.py
adding to the truncate command, in the truncate
nemesis the new functionality of adding
`using timeout`, so we can have it running longer, and avoid failing for known issue where truncate
times out.
> improvement(nemesis.py): truncate nemesis using timeout

- sct.py
as of now, RAFT is disabled for all upgrade jobs,
so, to test the RAFT feature on upgrade jobs,
there were few jobs introduced to test it, but their jobs are not yet being created automatically, and
will now have its own group, and jobs, and later,
should be added to the upgrade triggers as well.
> test(create release jobs): upgrade with raft enabled

- sdcm/cluster.py
> Branch 2021.1 revert jdk workaround

- test-cases/longevity/longevity-multi-keyspaces.yaml
In order to avoid previous stress errors.
c-s had errors of:
```
2023-02-17 08:20:06.056: (CassandraStressEvent Severity.ERROR) period_type=end event_id=75a04694-c45f-45f7-9e5b-e172cf7b906c during_nemesis=NodetoolDecommission duration=5h55m10s: node=Node longevity-1000-keyspaces-5-2-loader-node-1886ff81-3 [52.51.85.147 | 10.4.2.16] (seed: False)
stress_cmd=cassandra-stress mixed cl=QUORUM duration=48h -schema 'replication(factor=3)' -mode cql3 native -rate threads=10 -pop seq=1..4000000 -log interval=90 -node 10.4.0.216,10.4.0.95,10.4.1.62,10.4.2.137,10.4.2.19,10.4.3.133
errors:
Stress command completed with bad status 134: WARN  02:25:10,098 Not using advanced port-based shard awareness with /10.4.2.19:9042 because we're
2023-02-17 08:20:07.529: (CassandraStressEvent Severity.ERROR) …
```
> test(multi-keyspace): Use installed stressed tools instead of dockers

- sdcm/cluster_k8s/eks.py
- sdcm/cluster_k8s/gke.py
- sdcm/cluster_k8s/mini_k8s.py
chaos-daemon pods are not in the white list on scylla nodes and causing WRONG_SCHEDULED_PODS event to be raised.
This commit adds chaos-daemon pods to whitelist on scylla k8s nodes.
refs: #5811
> fix(chaos-mesh): whitelist chaos-daemon on scylla nodes

- test-cases/artifacts/amazon2.yaml
- test-cases/artifacts/oel76.yaml
- test-cases/artifacts/oel81.yaml
this feature was enabled only on AMI artifact test, and we habe more artifacts tests running on AWS that needs it.
> fix(artifacts): enable `aws_fallback_to_next_availability_zone`

- sdcm/provision/azure/ip_provider.py
- sdcm/provision/azure/provisioner.py
During clean-resources we hit issue with missing ip address in prepopulated cache. It causes error in cleanup and aborting cleanup.
It is still unknown why cache is not getting populated, so add some log messages that might help us. Because IP addresses are deleted regardless of cache, we ignore this error and just log misbehavior.
refs: #5860
> fix(clean-resources): ignore missing ip in cache

- sdcm/stress_thread.py
Recently c-s changed behavior and for duration workflows: it added warmup iterations. For heavy load, warmup doesn't fit to 10 minutes duration margin we assumed for c-s startup and causes SCT to timeout c-s thread.
This fix removes warmup by appending ` no-warmup` to all c-s cmd's. 
refs: #5767
> fix(stress): fix c-s timeouts

- sdcm/provision/azure/ip_provider.py
- sdcm/provision/azure/provisioner.py
- sdcm/provision/azure/virtual_machine_provider.py
When running cleanup resources according to post behavior we run
`clean_cloud_resources` multiple times. Each time azure provisioner
discover VM's from scratch. Because IP's are deleted quicker than VM's
provisioner sometimes fails to obtain IP address for VM that is pending
delete and failing.
This PR makes instances discovery to skip ones that are pending
deletion. Also reverting previous fix that possibly doesn't work.
> Fix discover vms in azure

- sdcm/nemesis.py
Reverts scylladb/scylla-cluster-tests#5854
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/5874
> Revert "improvement(nemesis.py): truncate nemesis using timeout"

- sct.py
introduced on #5759 the creation of upgrade with
raft disabled, but then, the PR was reverted, but
the jobs creation wasn't.
then on #5836 was added the correct behavior,
so we ended up with duplicated behavior.
this PR is removing the jobs creation of
rolling upgrade with raft disabled,
as this is the default for all rolling upgrade
jobs, and leaving the jobs with raft enabled.
> fix(create release jobs): fix upgrade with raft jobs

- sdcm/cluster.py
not sure what changed, but on job longevity-10gb-3h-gce-test we are seeing failures since last October,
related to the function `install_scylla_bench` failing because `rm -f` on a directory doesn't work, and then `mkdir` fails with file already exists, making the whole installation process to fail.
adding the `-r` flag to the `rm` command will fix it.
> fix(cluster.py): install s-b commands went broken

- functional_tests/scylla_operator/test_functional.py
Local K8S uses kind of `stable` `service IP` addresses for connections.
But it also may be silently recreated getting new IP address.
So, refresh IP address in the `test_operator_managed_tls` test for case target IP address gets changed.
```
E   cassandra.cluster.NoHostAvailable:
('Unable to connect to any servers',
{'10.96.180.204:9142': OSError(None, "Tried connecting to
[('10.96.180.204', 9142)]. Last error: timed out")})
cassandra/cluster.py:3617: NoHostAvailable
```
> fix(k8s-functional): add refresh_ip in def test_operator_managed_tls

- sdcm/nemesis.py
toggle connection nemesis only applies to usage of open-Ldap
and runs against a container, not against MS-AD server.
Fixes an error of:
```
2023-02-23 15:06:38.688: (DisruptionEvent Severity.ERROR) period_type=end event_id=ac7574aa-c4f9-44ab-b56b-969c897226d3 duration=1s: nemesis_name=LdapConnectionToggle target_node=Node longevity-100gb-4h-2023-1-db-node-64dc4bfc-3 [16.170.141.195 | 10.0.0.106] (seed: True) errors=There is no container `ldap' for <sdcm.localhost.LocalHost object at 0x7fc1e890c190>.
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4088, in wrapper
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1114, in disrupt_ldap_connection_toggle …
```
> fix(Ldap nemesis): skip toggle-connection-disrupt if not using open-Ldap

- sdcm/nemesis.py
following work on #5854 and after it was reverted
on #5875, re-introducing this improvement to have
the `truncate` commands running with the
CQL ability to timeout it.
> improvement(nemesis.py): adding `using <timeout>` to truncate

- vars/getJobTimeouts.groovy
CI runs `sct.py output-conf` without specifying region name. This leads to error that some image may not be available for default region and causing error.
Set env variable with region so `output-conf` takes region name into consideration. Also this way is more proper as it is more similar to test execution.
> fix(output-conf): fix missing region setup

- vars/getJobTimeouts.groovy
Recent commit introduced error of missing param and failing `getJobsTimeout.groovy`. This fixes it.
> fix(pipeline): fix broken getJobsTimeout.groovy

- vars/perfRegressionParallelPipeline.groovy
Performance tests could not be run on specific
scylla db packages(patches, dev builds, etc). Adding pipeline parameters and export SCT variable to
run perf tests on special scylla builds
> fix(parallelperfpipeline): Use update_db_packages

- test-cases/manager/manager-regression-azure.yaml
- test-cases/manager/manager-regression-ipv6.yaml
- test-cases/upgrades/manager-upgrade.yaml
In order to make all manager jobs consistent, I changed the default monitor image to be a centos image.
> fix(manager): set monitor image in all manager tests to centos

- vars/getJobTimeouts.groovy
Since in multi dc scenarios the region params (region, gce_datacenter or azure_region_name) value can be a list and not a string, it needs to be converted to json before being exported into an environment variable
> fix(getJobTimeouts.groovy): convert region params to json before export

- mgmt_cli_test.py
- test-cases/manager/manager-regression-azure.yaml
- test-cases/manager/manager-regression-multiDC-gce.yaml
- test-cases/manager/manager-regression-multiDC-set-distro.yaml
Since manager 3.1 now supports restoring backups using restore tasks,
I added a restore task for the backup that is created with test_basic_backup.
I also added a cassandra stress read thread after each of the restorations (both the
manual one and the restore task) to verify that they both of them were completed
successfully.
>  improvement(manager backup feature): Added restoration with restore task

- vars/perfSearchBestConfigParallelPipeline.groovy
Add client encryption to search-best-performance test config file
> fix(search_best_perf): add client encryption

- sdcm/cluster.py
Found internal SCT warnings that such events not published. This was from the introduction of them in https://github.com/scylladb/scylla-cluster-tests/pull/5670
> fix(cluster.py): publish ScyllaYamlUpdateEvent

- jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
To be more aligned with the rest of the manager jobs
> fix(centos-manager-sanity-ipv6): set region to us-east-1

- sdcm/tester.py
> fix(sdcm.tester): Fix incorrect keyword parameter passed to argus

- performance_search_max_throughput_test.py
- sdcm/report_templates/results_search_best_throughput_config.html
- test-cases/performance/perf-search-best-throughput-config.yaml
Improvement report:
- added prepare_command and best_stress command to report
Fixes:
- run with one loader node
- disable argus for test
- choose 1st element if stress template was passed jenkins parameters
> Improvements for search_best_config_performance tests

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/sct_config.py
- sdcm/sla/libs/sla_utils.py
- sdcm/sla/sla_tests.py
- sdcm/tester.py
- test-cases/enterprise-features/workload-prioritization/longevity/longevity-sla-system-24h.yaml
- test-cases/longevity/longevity-sla-100gb-4h.yaml
- test_lib/sla.py
- unit_tests/test_sla_utils.py
1. SLA feature need that cluster will be configured with authenticator. Not all our longevities run with authenticator. So we need to filter out SLA nemeses.
2. Cassandra-stress default table 'keyspace1.standard1' can have different columns definition. SLA nemeses start cassandra-stress load on this table and need to use same columns definition. This commit get columns definition from cassandra-stress command (from test yaml) and run load with correct '-col' parameter.
3. To prevent parmission error 'User roleyyy has no SELECT permission on table ... or any of its parents', create the role as SUPERUSER.
4. Added temporary solution. We do not want to run SLA nemeses during not-SLA test until the feature is stable.
Example here: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/l …
> fix(nemeses): support SLA nemeses for non-SLA tests

- sdcm/cluster.py
get host id from `nodetool info` and not from our `nodetool status` implemetiontion which is much more complex since it's mapping the node based on IP, and we don't need that for getting the host_id
> fix(host_id): get host id from `nodetool info`

- test-cases/features/sl-workloads-test.yaml
- test-cases/features/system-sla-test.yaml
According to https://github.com/scylladb/scylla-docs/issues/1918 and documentation https://docs.scylladb.com/stable/operating-scylla/security/enable-authorization correct value for autorized is 'CassandraAuthorizer', not 'ScyllaAuthorizer'. Change it for SLA tests
> fix(autorizer): change to CassandraAuthorizer

- sdcm/nemesis.py
Several jobs stuck on installation using "apt install iptables" (due to a prompt, we guess).  It's better to switch to a more flexible installation routine.
> fix(nemesis.py): use BaseNode.install_package for iptables installation

- longevity_lwt_test.py
- sdcm/utils/data_validator.py
Test https://jenkins.scylladb.com/job/scylla-master/job/raft/job/longevity-lwt-parallel-schema- changes-with-disruptive-24h-raft-test/8/ failed with error:
```
File /home/ubuntu/scylla-cluster-tests/sdcm/cluster.py, line 3380, in cql_connection return self._create_session(node=node, keyspace=keyspace, user=user, password=password, 
File /home/ubuntu/scylla-cluster-tests/sdcm/cluster.py, line 3364, in _create_session session.set_keyspace(keyspace)
File cassandra/cluster.py, line 3362, in cassandra.cluster.Session.set_keyspace 
File cassandra/metadata.py, line 1599, in cassandra.metadata.protect_name 
File cassandra/metadata.py, line 1626, in cassandra.metadata.maybe_escape_name 
File cassandra/metadata.py, line 1622, in cassandra.metadata.is_valid_name 
TypeError: expected string or …
```
> fix(longevity): keyspace for data validator

- sct.py
- sdcm/test_config.py
- sdcm/utils/argus.py
- sdcm/utils/common.py
This fix handles scenarios where get_argus_client is either provided
nothing or a non-uuid value to the client. Return MagicMock in such a
scenario to replicate previous behaviour
> fix(argus.py): Handle cases where we can't use argus

- docker/env/version
- requirements.in
This client update addresses some of the issues related to backend
exception handling, for example when backend returns a non-standard
exception.
> improvement(hydra): Upgrade argus client to 0.10.2

- data_dir/nemesis.yml
- data_dir/nemesis_classes.yml
- jenkins-pipelines/nemesis/longevity-5gb-1h-CreateIndexNemesis-aws.jenkinsfile
- sdcm/nemesis.py
- sdcm/utils/common.py
- sdcm/utils/nemesis_utils/indexes.py
- test-cases/nemesis/longevity-5gb-1h-CreateIndexNemesis.yaml
- unit_tests/test_nemesis.py
- unit_tests/test_nemesis_sisyphus.py
Currently we test indexes by having some c-s profiles with MV's. Indexes are created along with tables and are populated incrementally. We miss the scenario, where an user decides to create index after some time, when table is full of data.
This commit introduces new nemesis covering this scenario. When executed, gets a table with the most partitions and creates index on some random regular or static column. Waits for creation and verify if index can be used in a query without ALLOW FILTERING option without any issue. Drops index after nemesis to not change schema permanently.
refs: https://github.com/scylladb/qa-tasks/issues/1011
> test(nemesis): added create index nemesis

- sdcm/cluster.py
thanks to @vponomaryov, this commit is to fix
what is still left broken after previous fix
on commit 5759f8e9a20fe61062a07341bd7697beaa51b9ee
giving it a try [here](https://jenkins.scylladb.com/job/enterprise-2021.1/job/longevity/job/longevity-10gb-3h-gce-test/89/)
> fix(cluster.py): install s-b commands still broken

- sdcm/log_archive.sh
- sdcm/logcollector.py
- sdcm/tester.py
Split big SCT files logs(more than 3GB) into multiple s3 objects
task: https://github.com/scylladb/qa-tasks/issues/928
> improvement(logcollector): Implement log rotation

- sla_per_user_system_test.py
According to https://github.com/scylladb/scylla-docs/issues/1918 and documentation https://docs.scylladb.com/stable/operating-scylla/security/enable-authorization correct value for autorized is 'CassandraAuthorizer', not 'ScyllaAuthorizer'. Change it for SLA tests
> fix(autorizer): change authorizer for old SLA tests

- jenkins-pipelines/longevity-large-partition-2days-reversed-queries.jenkinsfile
- sdcm/tester.py
- test-cases/longevity/longevity-large-partition-2days.yaml
The new s-b parameter of select-order-by is added to v0.1.8
So the new reversed-queries implementation of 5.0 can be tested this way.
> improvement(reversed queries): Added select-order-by to scylla-bench

- sdcm/scan_operation_thread.py
To prevent flooding of console with debug prints, change log level to debug
Log info prints added by https://github.com/scylladb/scylla-cluster-tests/pull/5710
> fix(scan operations): change log level to debug

- longevity_lwt_test.py
- sdcm/nemesis.py
1. If test runs with parallel nemesis, do not try get keyspace name from data_validator and do not run the validation. Now the message is got in the log: 
```
sdcm.nemesis.DisruptiveMonkey: Data validator error: expected string or bytes-like object
```
The fix same as https://github.com/scylladb/scylla-cluster-tests/pull/5890
2. Fix few typos
3. Set severity to NORMAL for 'Data Validator is disabled' event
> fix(data validator): ignore data validator for parallel nemeses test

- sdcm/nemesis.py
- sdcm/utils/common.py
- unit_tests/test_parallelobject.py
this branch of the code, just add all of the parallel objects into the exception, and makes the outcome unclear, cause you can't know which part is failing
```
concurrent.futures._base.TimeoutError: when running on: [
functools.partial(<bound method BaseNode.run_nodetool of <...>>, sub_cmd='repair',
warning_event_on_exception=(<class 'Exception'>,), retry=0),
functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <...>>,
log_follower=<...>, disrupt_func=<bound method Nemesis.reboot_node of <...>>,
disrupt_func_kwargs={'target_node': <...>, 'hard': True, 'verify_ssh': True},
delay=1)]
```
Removing this code path, would end up with the regualr exception in the case of failed parallal thread, and would should the backtrace of each it would be a bit more …
> fix(ParallelObject): remove timeout exception

- sdcm/logcollector.py
since #5892 the tarball doesn't have the test_id in it's name, it's a bit annoying when you are looking at multiple jobs at the same time, and it's not match with the test_id as it was before
> fix(sct.log): sct.log tarball is missing the test_id

- Jenkinsfile
Since we are now runnig on sct-runner, and we are running in provision
tests in paralell on the same worker, we need to make sure we run each
parallel on it's own direcotry.
since we could fail on locking when checking out code, or by mistake using
the wrong sct-runner, since it's base on a file with the ip in the working
directory.
> fix(Jenkinsfile): create diffrent directory for each provision test

- sdcm/cluster.py
Seems that recently we remove that call of EPEL install, and since we have image that has EPEL already this might be on connectivity issue, this is a workaround for not building the images without the EPEL.
this is the failure we've seen recently (at least five times)
```
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo yum install -y wget'
Exit code: 1
Stdout:
Loaded plugins: fastestmirror
Determining fastest mirrors
Stderr:
5. Configure the failing repository to be skipped, if it is unavailable.
Note that yum will try to contact the repo. when it runs most commands,
so will have to try and fail each time (and thus. yum will be be much
slower). If it is a very temporary problem though, this is often a nice
compromise: …
```
> fix(loader-setup): install/update epel to avoid install issues

- sdcm/provision/azure/provisioner.py
When cleaning resources after test we trigger cleanup resources multiple time. Each time AzureProvisioner tries to discover instances for given test. When VM is pending delete, additional resources like ip address might be already evicted, causing issue with building provisioner cache.
Catch those cases and show only warning instead of failing cleanup.
fixes: #5860
> fix(azure): fix clean azure resources

- sdcm/cluster.py
- sdcm/nemesis.py
> fix(_destroy_data_and_restart_scylla): fail properly when all non system tables are empty

- defaults/test_default.yaml
- docs/configuration_options.md
- sdcm/sct_config.py
- upgrade_test.py
Since cqlsh is using the same files as scylla-tools was using before, on downgrade it's need to be remove first as long as there it's a downgrade to a version before cqlsh existed.
Fix: https://github.com/scylladb/scylla-cqlsh/issues/23
> fix(upgrade-tests): remove scylla-cqlsh when downgrading

- sdcm/sct_events/group_common_events.py
Since RBNO is enabled, this nemesis is generating those logs:
```
scylla[5576]:  [shard  0] storage_service - decommission[aa9a834d-99b1-4af8-9267-cec699bb5140]:
Operation failed, sync_nodes={10.4.0.45, 10.4.3.213, 10.4.3.145, 10.4.1.131, 10.4.2.77,
10.4.2.119}: std::runtime_error ({shard 0: std::runtime_error (Failed to repair for
keyspace=alternator_usertable, cf=usertable, range=(-7819559552726985616, -7814482230290657926]),
shard 1: std::runtime_error (Failed to repair for keyspace=alternator_usertable, cf=usertable,
range=(-8277937157109075297, -8260575255900646513]), shard 2: std::runtime_error (Failed to
repair for keyspace=alternator_usertable, cf=usertable, range=(-7814091121065622595,
-7810918921443784702]), shard 3: std::runtime_error (Failed to repair for …
```
> fix(disrupt_decommission_streaming_err): skip failure log

- test-cases/nemesis/longevity-5gb-1h-BlockNetworkMonkey.yaml
- test-cases/nemesis/longevity-5gb-1h-RandomInterruptionNetworkMonkey.yaml
- test-cases/nemesis/longevity-5gb-1h-StopStartInterfacesNetworkMonkey.yaml
all these network nemeses required an extra network interface to run, and they were missing from the
default configuration, and this PR is adding this
required extra network interface.
> fix(network nemeses jobs): add right configuration

- upgrade_test.py
Upgrade from 5.1 failed because SLA in OSS does not support "shares" option.
Adapt the upgrade test do not use shares for OSS version.
Test passed:
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/rolling-upgrade-with-sla/24/
> test(upgrade): support upgrade from OSS to Enterprise with SLA

- jenkins-pipelines/features-ldap-authorization-add-remove-role-permissions.jenkinsfile
- sdcm/utils/ldap.py
- test-cases/features/test_add_remove_ldap_role_permission.yaml
- test_add_remove_ldap_role_permission.py
Test adding a new user with Ldap permissions,
and run some load for it.
Then remove permissions and wait for its load to end.
> test(Ldap): Add/remove Ldap role permissions during stress

- sdcm/loader.py
- sdcm/tester.py
- sdcm/utils/csrangehistogram.py
- Create public interfaces (functions) and hide internal logic
previously module usage looks like a call of 2 static functions from 2 different classes : 
```
histogram = CSRangeHistogramBuilder.build_from_log_line(log_line=line,
hst_log_start_time=self.log_start_time)
summary_data = CSRangeHistogramSummary(histogram).get_summary_for_operation(self.stress_operation)[0]
```
now module has only 3 public functions on the module level. all other stuff is internal. usage is just  call of 1 function:
```
summary_data = make_cs_range_histogram_summary_from_log_line(
workload=CSWorkloadTypes(self.stress_operation), log_line=line, hst_log_start_time=self.log_start_time)
```
- Improve performance
during profiling was found that the calling method HdrHistogram.add takes about 90% of the running time …
> refactor(CSRangeHistogram): Refactor csrangehistogram builders

- performance_regression_test.py
- test-cases/performance/perf-regression-throughput-125gb.yaml
- test-cases/performance/perf-regression.100threads.30M-keys.yaml
For the moment in the `test_write`, `test_read` and `test_mixed` throughput performance tests we use hardcoded number of stress threads as `2`.
Reuse the existing `stress_multiplier` config option for it to be able to change the value gracefully.
The need to have different value comes out of the serverless clusters testing where we utilize too few vCPUs and use only 1 loader thread to measure it's perf.
> improvement(thrpt-perf): allow to change the number of stress threads

- defaults/k8s_eks_config.yaml
- defaults/k8s_gke_config.yaml
- docs/configuration_options.md
- sdcm/sct_config.py
- sdcm/tester.py
> improvement(k8s): allow to configure the auxiliary nodes instance type

- data_dir/mv_synchronous_updates.yaml
- data_dir/mv_synchronous_updates_lwt.yaml
- data_dir/mv_synchronous_updates_on_standard.yaml
- jenkins-pipelines/longevity_mv_synchronous_updates-12h.jenkinsfile
- sdcm/stress_thread.py
- sdcm/utils/common.py
- sdcm/utils/data_validator.py
- sdcm/utils/user_profile.py
- test-cases/longevity/longevity-mv-synchronous-updates-12h.yaml
- unit_tests/test_cluster.py
This commit add new basic longevity for MV feature is presented by https://github.com/scylladb/scylladb/commit/cb8a67dc98b60919ac9d5bbb6618e17f7d1602c7
It creates different materialized views. Part of MVs are running in sychronous mode, others in asynchronous mode. Updates/inserts/deletes into MVs perform in parallel with different nemeses, disruptive and non-disruptive
> test(longevity): new longevity for MV running in synchronous mode

- test-cases/enterprise-features/ics/longevity/ics-longevity-toggle-strategy-large-partitions-24h.yaml
Job 'ics-longevity-toggle-strategy-large-partitions-24h.jenkinsfile' should run 24 hours, but run 4d. this happened because job use 2 config yamls, and duration is set in first one.
> fix(ics-toggle-large-partition): Set job running 24h

- docs/configuration_options.md
- functional_tests/scylla_operator/test_functional.py
- sdcm/cluster_k8s/__init__.py
- sdcm/nemesis.py
- sdcm/sct_config.py
Add following new config options:
- k8s_scylla_cpu_limit
- k8s_scylla_memory_limit
Which, when defined, will be applied to each Scylla pod. Also, these options are suitable for multitenant configuration.
Examples:
1) Single tenant:
```
k8s_scylla_cpu_limit: '500m'  # 0.5 vCPU
k8s_scylla_memory_limit: '16384Mi'  # 16Gb
```
2) 2 tenants:
```
k8s_scylla_cpu_limit: ['500m', '1500m']  # 0.5 and 1.5 vCPUs
k8s_scylla_memory_limit: ['4096Mi', '12288Mi']  # 4Gb and 12Gb
```
> improvement(k8s): allow to set cpu and memory limits for Scylla pods

- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
- sdcm/cluster_k8s/mini_k8s.py
Use `node_type` attr of node objects to detect their type instead of using `instance_name` one.
It will allow to avoid following error on K8S backends:
> Traceback (most recent call last):
>   File "%project-path%/sdcm/cluster.py", line 328, in update_shards_in_argus
>     shards = self.scylla_shards if "db-node" in self.instance_name else self.cpu_cores
>   File "%project-path%/sdcm/cluster_k8s/__init__.py", line 2014, in instance_name
>     return self.node_name
>   File "/usr/local/lib/python3.10/functools.py", line 970, in __get__
>     val = self.func(instance)
>   File "%project-path%/sdcm/cluster_k8s/__init__.py", line 2010, in node_name
>     return self._pod.spec.node_name
> AttributeError: 'NoneType' object has no attribute 'spec'
> Encountered an unhandled exception while …
> fix(argus): properly check the node type

- sdcm/utils/common.py
Following the changes made in
https://github.com/scylladb/scylla-pkg/commit/7308e0a56352f96e089d64d203079111309091a3, 
the Hydra search for gce promoted image is wrong
Adjusting the filter so it will support both prefixes (Scylla and Scylladb)
> fix(common.py):set GCE filter for new image name

- configurations/operator/perf-serverless-thrpt-1vcpu.yaml
- configurations/operator/perf-serverless-thrpt-2vcpu.yaml
> ci(serverless): add configs for testing 1 and 2 vcpus Scylla clusters

- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
- sdcm/nemesis.py
- sdcm/sct_events/system.py
- sdcm/utils/adaptive_timeouts/__init__.py
- sdcm/utils/adaptive_timeouts/load_info_store.py
- unit_tests/test_adaptive_timeouts.py
- unit_tests/test_events.py
During testing scenarios with different machine types and load it's
impossible to have one timeout value that fits all. Various operations
take more time when node performance is lower or data load is higher.
Implement `adaptive_timeout` context manager that will calculate right
timeout value for given operation based on node load (performance, data
size, and other factors). It is not raising any exceptions, just returns
timeout value that may be used within context. When context takes longer
duration than it, publish `SoftTimeoutEvent` with `Error` severity.
Because calculating timeout is not straightforward, collect various
'load metrics' to Elasticearch db for future reference and testing.
`SoftTimeoutEvent` has been refactored - dropped the context-manager
related code as it is no …
> feature(adaptive-timeouts): calculate timeouts based on node load

- sdcm/nemesis.py
- test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
We have several exclusive nemesis which disrupt more than 1 Scylla pod from different Scylla clusters. In this case dedicated lock is used to block all other nemesis when the exclusive one gets run. 
But the problem with it is that when we enable cluster health validation it fails with high probability because it is not locked as side nemesis are.
So, fix the exclusive nemesis logic the way that cluster health validation gets lock'ed too.
> fix(k8s): use exclusive nemesis lock for cluster health validation too

- functional_tests/scylla_operator/libs/helpers.py
- sdcm/nemesis.py
Recently merged PR [1] replaced `calculated_memory_limit` attr with the `scylla_memory_limit`.
And the old values were not replaced with the new one in several places. So, replace it.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/5960
> fix(k8s): use proper K8S class attr for getting memory limit value

- sdcm/utils/nemesis_utils/indexes.py
When querying base table column to have value to query by index, result may return None value. This makes query to have 'WHERE = None' which is not correct syntax. Scylla does not support putting 'is null' in where clause either.
Fix is about skipping query by index in that case.
commit 2:
When querying by index value may contain ' sign. In that case it must be
escaped to properly format the query.
Fix is by properly escaping ' character from value in where clause.
> fix(CreateIndexNemesis): skip querying by index if null value

- README.rst
should read: "one of the 2 options". hence the change.
> docs(README): s/on/one/

- sdcm/nemesis.py
- sdcm/utils/sstable/load_utils.py
During disrupt_nodetool_refresh the sstables for refresh may be uploaded into wrong data folder because of bug in the folder searching: the sstables is uploaded into first folder that is returned by 'ls -t'. Not always it will be 'standard1' as it should be.
Refs: https://github.com/scylladb/scylla-cluster-tests/issues/5978
> fix(refresh nemesis): fix folder for sstable uploading

- unit_tests/conftest.py
pytest's capsys just closes the stdout when done with tests. there are issues tracking this problem, see pytest-dev/pytest#5577 . but we adds a handler which redirect the logging messages to stdout. so, once pytest finishes testing, exceptions are raised when writing logging messages, like
```
22:37:20    File "/usr/local/lib/python3.10/logging/__init__.py", line 1101, in emit
22:37:20      stream.write(msg + self.terminator)
22:37:20  ValueError: I/O operation on closed file.
```
so, in this change, `logging.raiseExceptions` is disabled when pytest's session finishes.
Fixes #6000
> fix(unit_test): prevent logging from raising exceptions after tests

- sdcm/cluster.py
we started to use a cqlsh which does not support
python2 anymore since https://github.com/scylladb/scylladb/pull/13328,
and scylla-cqlsh does support relocatable python3 in its `install.sh`,
see
https://github.com/scylladb/scylla-cqlsh/commit/3eef722c8c63f0494bac3c2edcbffeef37477648.
so there is no need to install python2 or python3 for cqlsh
anymore.
> fix(cluster): do not install python for cqlsh

- longevity_sla_test.py
- sdcm/nemesis.py
- test_lib/sla.py
Upgrade test with sla failed, because index pass to function creating Role as str, while it expected int.
It happened because of the https://github.com/scylladb/scylla-cluster-tests/pull/5950 was backported into 2022.2 but https://github.com/scylladb/scylla-cluster-tests/pull/5868 was not backported.
We do not intend to backport https://github.com/scylladb/scylla-cluster-tests/pull/5868 meanwhile. This commit changes 'index' parameter type to 'str'
> fix(sla auth): change function parameter type

- sdcm/cluster.py
the return code of `dpkg-query --show` does not imply if a package is installed. this command fails only when the package is not found.
quote from dpkg-query(1)
```
-W, --show [package-name-pattern...]
Just like the --list option this will list all packages matching the given patterns. However the output can be customized using the
--showformat option.
The default output format gives one line per matching package, each line consisting of the package name and its installed version, separated by
a tab.  The package name will be architecture qualified for packages with a Multi-Arch field with the value same or with a foreign
architecture, which is an architecture that is neither the native one nor all.
-s, --status [package-name...]
Report status of specified packages. This just displays the …
```
> fix(cluster): dpkg -s for checking if a package is installed

- jupyter/functional-test.ipynb
- jupyter/provision-test.ipynb
- jupyter/readme.md
When developing new code for SCT its important to try and test new code on live cluster. But running whole test for each change takes long time and is not efficient.
Provide example jupyter notebooks to enable quick and easy way to interactively play with cluster and try new code in SCT.
> feature(jupyter): added example jupyter notebooks

- sdcm/cluster.py
since we bumped the jre used by scylla-jmx from openjdk-8 to openjdk-11, and we started to check for jre-11. despite that scylla-jmx still works with jre-8, jre-11 is the recommended JRE for running scylla-jmx, let's use openjdk-11 for testing offline installation.
please note, https://github.com/scylladb/scylla-jmx/pull/198 was also created to address this issue. but in the long run, this fix is a better one. as it's always desirable to use a better supported jre in testing.
Refs https://github.com/scylladb/scylla-jmx/issues/127
Fixes https://github.com/scylladb/scylladb/issues/13414
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>
> fix(cluster): install openjdk-11 for offline install

- jenkins-pipelines/longevity-cdc-100gb-4h.jenkinsfile
- jenkins-pipelines/longevity-counters-multidc.jenkinsfile
- jenkins-pipelines/longevity-topology-changes-3h.jenkinsfile
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/cluster_k8s/eks.py
- sdcm/nemesis.py
- sdcm/sct_config.py
- sdcm/tester.py
- sdcm/utils/aws_utils.py
- test-cases/longevity/longevity-cdc-100gb-4h.yaml
- test-cases/longevity/longevity-counters-multidc.yaml
- test-cases/longevity/longevity-topology-changes-3h.yaml
- vars/longevityPipeline.groovy
We need to support multi-az deployments in SCT to be able to cover new
test cases. Especially we aim for grow/shrink cluster tests when working
in multi-rack deployments.
Add support to multi az in AWS provisioning code (old provision). To use
multi-az, specify multiple coma-separated availability zones
(e.g. `a,b,c`).
When multi-az is specified, job's provision step is skipped.
`GrowShrinkClusterNemesis` is able to work with multi-az on AWS
backend. When `rack` is set to `None` in `discrupt_grow_shrink_cluster`,
it will be growing cluster evenly, otherwise grow only in specified rack.
Adapted 3 jobs to use multi-az on AWS.
refs: https://github.com/scylladb/qa-tasks/issues/1070
> feature(aws): add suport to multi az

- defaults/severities.yaml
- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/sct_events/health.py
- sdcm/utils/health_checker.py
Decommission could fail or aborted at moment when all
data was streamed and node was removed from token ring
but stay in raft group0. This could affect on raft group0
avialability because garbage voter stay in group0.
This mostly happened for DecommissionStreamingErrMonkey.
New procedure of 'Handling Cluster Membership Change Failures'
was presented to handle such cases.
To avoid that, compare members of token ring and
group0 and remove from group0 garbage member with
removenode operation. After that node could be
terminated
Issue: https://github.com/scylladb/scylladb/issues/11723
Issue: https://github.com/scylladb/scylladb/issues/13122
Commit: https://github.com/scylladb/scylladb/commit/c2a2996c2b0e11176930d63c419b4fdaa16dd230
> fix(diff_gr0_token_ring): Check group0 and token_ring

- sdcm/sct_provision/aws/cluster.py
- sdcm/sct_provision/aws/instance_parameters_builder.py
Recent merge of multi-az support broke provisioner.
Add basic support for this change in provisioner step.
> fix(provisioner): fix after multi-az

- data_dir/nemesis.yml
- data_dir/nemesis_classes.yml
- sdcm/nemesis.py
- sdcm/utils/nemesis_utils/indexes.py
- test-cases/nemesis/longevity-5gb-1h-AddRemoveMvNemesis.yaml
- unit_tests/test_nemesis.py
- unit_tests/test_nemesis_sisyphus.py
Select an existing user-table and create a materialized-view
when a node is down.
Task: https://github.com/scylladb/qa-tasks/issues/1012
> improvement(Materialized View): Add-remove MV nemesis

- sdcm/cluster.py
Recently merged PR [1] added logic where we compare group0 and token ring members.
And the problem with it is that it fails when 'raft' feature is disabled and group0 is empty.
So, fix it by proper handling of group0 emptyness.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/5928
> fix(raft): make 'get_group0_members' work correctly when raft disabled

- test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml
the `user-profile` command used in this test has
2 wrong placements, one in the prepare, and one in stress command.
the `n=3000000` and `duration=700m` are not supposed to be part of the `-rate` parameter of the c-s command, hence failed in the test.
> fix(parallel topology changes): c-s command is wrong

- jenkins-pipelines/perf-regression-latency-1TB-ebs-gp3-volumes.jenkinsfile
- jenkins-pipelines/perf-regression-latency-1TB-ebs-volumes.jenkinsfile
- jenkins-pipelines/perf-regression-latency-1TB.jenkinsfile
- jenkins-pipelines/perf-regression-latency-non-shard-aware-1TB.jenkinsfile
- jenkins-pipelines/perf-regression-latency-shard-aware-1TB.jenkinsfile
- test-cases/performance/perf-regression-latency-1TB.yaml
Increase test duration for performance latency 1TB tests
> fix(perf-1tb): Increase test duration

- test-cases/gemini/gemini-1tb-10h.yaml
- test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
- test-cases/gemini/gemini-3h-with-nemesis.yaml
- test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h.yaml
since older images were completely removed,
we are failing to run Gemini jobs on this branch
(`branch-2021.1`), hence here, bumping the version to the oldest we still hold in all relevant
regions.
> fix(gemini oracle version): bump oracle version

- test-cases/longevity/longevity-cdc-100gb-4h.yaml
seem like when using only one region, the name of the region is diffrent then in multi region setup, fixing the name in this test configuration
if failed like the following:
```
cassandra.protocol.ConfigurationException: <Error from server: code=2300
[Query invalid because of configuration issue] message="Unrecognized
strategy option {eu-westscylla_node_west} passed to org.apache.cassandra.
locator.NetworkTopologyStrategy for keyspace cdc_test">
```
> fix(longevity-cdc-4h): fix datacenter name

- sdcm/cluster.py
'audit' is a system keyspace that wasn't filtered so
nemesis selected it mistakingly as a user keyspace.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5963
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5963
> fix(get_non_system_ks_cf_list): Filter out 'audit' keyspace

- vars/managerPipeline.groovy
When the spot price is too high, we are resolt to use on demand intances. The thing is that every downstream job that is triggered afterwards by the first build will still use spot by default, and thus fail. To save the time of rebuilding all of said jobs I decided to also transfer the provision_type param in the trigger.
> improvement(managerPipeline): include the provision type in the trigger

- sdcm/tester.py
When running tests where we don't want to store stats (e.g. `features-limit-streaming-io-test`), histogram data generation code fails with error:
```
workload = self._test_index.split("-")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```
It looks that this code is needed only when `self.create_stats` is `True`.
Fix by running histogram generation exec code only when needed.
> fix(check_latency_during_ops): build histogram data ony when needed

- jenkins-pipelines/longevity-large-partition-200k-pks-2days-aws-i4i.jenkinsfile
- test-cases/longevity/longevity-large-partition-200k_pks-2days-i4i.yaml
fix(200k-pk-i4i): Additional capacity to resolve storage shortage
Cluster failed due to lack of disk space, using i4i.4xlarge.
Changing to i4i.8xlarge may solve the issue.
Refs: https://github.com/scylladb/scylladb/issues/12790
Refs: https://github.com/scylladb/scylladb/issues/12790
> fix(200k-pk-i4i): Additional nodes capacity to resolve storage shortage

- artifacts_test.py
- sdcm/cluster.py
Since in nonroot install cqlsh isn't on the path, we need to point to the exact location of it to make it work
Fixes: #6017
> fix(nonroot-artifcat-test): fix the location of cqlsh

- test-cases/artifacts/azure-image.yaml
- vars/getJenkinsLabels.groovy
since we don't really need the jenkins builder todo much we can use AWS ones to spin up an Azure pipeline/job
> feature(sct-builders): use aws ASGs as Azure builders

- sdcm/cluster.py
- unit_tests/test_cluster.py
Create mapping `region  - <datacenter name>`.
Datacenter name can be found from 'nodetool status' output. Receive it is possible for DB node only.
We can use this mapping, for example, when need to find in which datacenter a loader is located. It may be helpfull in multi DC tests
> improvement(cluster): find datacenter according to region

- sdcm/cluster.py
run_cqlsh command could failed during getting group0 members and raised exception failed the nemesis thread during cluster health validation.
Process exception raised in get_group0_members and publish appropriate event
> fix(get_group0_members): catch exception for cql commands

- sdcm/cluster.py
Nemesis thread in the https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/ longevity_mv_synchronous_updates-12h/3/ test failed due to 'get_group0_members' timeout.
Add retry decorator and did not raise exception on 'get_group0_members' and 'get_token_ring_members' during node health check.
> fix(health_events): add retry and did not raise exception

- defaults/test_default.yaml
- vars/perfSearchBestConfigParallelPipeline.groovy
Added 2 new parameters to be configured via pipeline parameters.
- Stress step duration: set duration for step for c-s command in format
- 10m
- 15m
- 1h
- Use predefined loader instance: run c-s as process on loader instance if set as true, if false run c-s command in docker container.
> fix(perf-search-best-config): New parameter to pipeline

- sdcm/cluster.py
for nonroot installation we don't have cqlsh in path. switch to use driver for getting group0 members instead cqlsh
> fix(get_group0_members): Use python-driver instead cqlsh

- sdcm/cluster.py
- sdcm/cluster_aws.py
When running `self.add_nodes` multiple times, the second run does not find provisioned instances because `self.nodes` is not empty anymore. It was not an issue before multi-az support because it was executed just once (except multi-dc, where probably we had this issue before).
When single az is provided, `self.add_nodes` will be called just like it was before. Issue with multidc is not fixed - this will be tackled in separate PR.
fixes: #6041
Second commit:
fix(multi-dc): fix double provision in multi-dc
In multidc scenario `self.add_nodes` is executed once per dc.
`_create_or_find_instances` when executed for second time finds
`self.nodes` is not empty, provisions new instances.
Filter nodes by dc in `_create_or_find_instances` so it tries to detect
instances for each dc before creating …
> fix(provision): fix duplicate provisioning after mult-az intro

- test-cases/longevity/longevity-mv-synchronous-updates-12h.yaml
DB instance type was set to 'i4i.xlarge' mistakenly for longevity-mv-synchronous-updates-12h test. It's too weak for such kind of test. Chnage it to 'i4i.4xlarge
> fix(longevity): change db instance type for MV synch test

- sdcm/cluster.py
- sdcm/stress_thread.py
- unit_tests/dummy_remote.py
- unit_tests/test_cassandra_stress_thread.py
- unit_tests/test_cluster.py
Cassandra-stress load, when is running on multi DC cluster, sends the requests to one DC only, where loader is located.
It happens because the default load balancing policy in scylla-tools-java is DCAwareRoundRobinPolicy which prefers nodes in the local datacenter. Unless all local nodes are tried, it will not send queries to other nodes in remote DC. If a local datacenter name is not provided the policy will default to the datacenter of the first node it is connected to.
We want that the requests will be sent to all nodes in all datacenters evenly. This commit add datacenter parameter to cassandra stress command
Issue: https://github.com/scylladb/java-driver/issues/211
> improvement(stress): add datacenter to c-s command for multi DC test

- upgrade_test.py
since scylladb/scylla-enterprise#2818 is happening on one of our base versions, we need to do this
"manual" removal, so test won't fail.
i expect that, once scylladb/scylla-enterprise#2818 will be fixed, we can revert this commit.
> fix(upgrade_test): shim-signed package removal workaround

- defaults/test_default.yaml
- test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
- test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
- test-cases/gemini/gemini-basic-3h-ics.yaml
- unit_tests/test_config.py
- unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
- unit_tests/test_scylla_yaml_builders.py
right now, older images were deleted, hence we
had to change to use newer images, but the concept of the oracle is to use the oldest version possible to compare the results.
per @roydahan 's request, moving it to use
latest 2021.1 version (that is 2021.1.15).
> fix(oracle version): use latest 2021.1 version

- sdcm/nemesis.py
Added the full task progress string to the assert message when the task did not end successfully, so the reason for the repair failure will be clearer.
> fix(disrupt_mgmt_repair): Add task progress string on task failure

- test-cases/longevity/longevity-counters-multidc.yaml
- test-cases/longevity/longevity-lwt-24h-multidc.yaml
The default load balancing policy in scylla-tools-java is DCAwareRoundRobinPolicy which prefers nodes in the local datacenter. Unless all local nodes are tried, it will not send queries to other nodes in remote DC.
Prevent issue: https://github.com/scylladb/java-driver/issues/211
> fix(multidc tests): create loader in each region

- upgrade_test.py
we are right now running this command to every
upgrade test, but RHEL like distros are not suffering from this problem, so adding a check, and running
it for Ubuntu only.
a try of it is running [here](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/shim-signed/job/upgrade-ubuntu22-shim-signed/2/)
> fix(upgrade_test): workaround for shim-signed for deb only

- sdcm/cluster.py
Since decomission is block for reentrancy, there not point of retring this operation, it would fail with:
```
nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission'
failed: std::runtime_error (Operation decommission is in progress, try again)
```
the sequence to stop decommission, is diffrent and being tested on it's own in a diffrent nemesis.
> fix(decommission): don't retry command on network errors

- defaults/test_default.yaml
- docker/gemini/Dockerfile
- docker/gemini/README.md
- docker/gemini/image
- unit_tests/test_config.py
Currently we use `busybox` for gemini base image. Busybox uses different C standard library implementation and this may lead to some unknown errors.
Switch base image to `minideb` for Gemini so we can exclude this kind of errors from possible culprits of our problems with container segfaults when using Gemini.
> fix(gemini): set gemini base image to debian

- sdcm/cluster_k8s/__init__.py
since recently we enabled `print_kernel_callstack` by default k8s setup need to enable `perf_event_paranoid` in order for it to work correctly.
Close: #6018
> fix(k8s): enable kernel.perf_event_paranoid=0

- sdcm/cluster.py
since 506c0bd353907a1b883e87355593c570c1bed84c azure artifacts are working with public address, but some of SCT around connecting to CQL isn't supporting correctly the public option.
> fix(azure-artifact): support public address in `cql_ip_address`

- sdcm/cluster_aws.py
- sdcm/cluster_k8s/eks.py
- sdcm/sct_config.py
- sdcm/sct_provision/aws/cluster.py
- sdcm/sct_provision/aws/instance_parameters_builder.py
- sdcm/utils/aws_utils.py
- sdcm/utils/common.py
- unit_tests/test_config.py
- vars/longevityPipeline.groovy
Currently provision step is disabled in pipeline when using multi-az
because it is not supporting this feature.
Adapt AWS provision to support multi-az and enable back provision step.
refs: https://github.com/scylladb/qa-tasks/issues/1070
> feature(multi-az): adapt provision step to multi-az

- sdcm/db_log_reader.py
- sdcm/sct_events/file_logger.py
* remove the warning events from being printed in sct.log, we have them in a seperate log if needed
* remove the `abort requested` logs from sct.log, we have too many of them, and they are not helpful for us
Ref: https://github.com/scylladb/scylladb/issues/10447
> fix(sct.log): remove warning event from being printed

- sdcm/sct_events/events_processes.py
those logs are getting printed on each events that is created and they don't add any helpful information, commenting them out.
> fix(events_processes): stop logging on getting the process

- sdcm/cluster_k8s/__init__.py
- sdcm/logcollector.py
- sdcm/utils/remote_logger.py
Since on long runs we might have lots of restart of the haproxy ingress, and at the end of the test we only have partial log.
this change is adding a new thread that would read the logs during the test, so we can collect all the logs from a run.
> feature(k8s-ingress): add logging thread

- sdcm/nemesis.py
we should have retry on rebuild, it wouldn't never work, and would fail like this:
```
Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  rebuild -- us-east "
Exit code: 1
Stdout:
nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild'
failed: std::runtime_error (Operation rebuild is in progress, try again)
See 'nodetool help' or 'nodetool help <command>'.
```
> fix(rebuild): make sure we don't ever retry rebuild

- README.rst
We get argus directly from pypi. 
There is no need to install anything extra.
Just removed the old command from readme file.
> fix(readme): removed old instruction for argus

- sdcm/nemesis.py
Retry adding a new node is problematic.
It caused a failure of grow-shrink-cluster nemesis.
Refs: https://github.com/scylladb/scylla-cluster-tests/issues/5415
Refs: https://github.com/scylladb/scylla-cluster-tests/issues/5415
[ICS Longevity 1TB Argus](https://argus.scylladb.com/test/d0b1d90e-dd6a-4a7c-96c3-3d31a43fc892/runs?additionalRuns[]=0e842a26-6b62-4164-ad08-513974539d88)
> fix(nemesis.py): Remove retry of adding a new node

- sdcm/cluster.py
The retry for this method was introduced in the PR https://github.com/scylladb/scylla-cluster-tests/pull/6039
Since most of the code of `get_group0_members` is placed in `try` block any possible exception is concealed inside the `except` block and does not go outside.
So the `retrying` decorator never has a reason to start retrying.
Added `raise` for the exception to trigger the retry for the method.
> fix(get_group0_members): re-raise the exception to make retry work

- sdcm/nemesis.py
In parallel running of nemesis add_remove_mv nemesis could choose node where another nemesis already running.
Add filtering for choosing node free from running nemesis
> fix(disrupt_add_remove_mv): choose node without running nemesis

- test-cases/longevity/longevity-large-partition-4days.yaml
With current `scylla-bench` configuration in `large partitions 4d` configuration we get constant query timeouts having only up to `25% CPU load` on nodes.
So, we reach IO/net limits with some part of queries and all other just fail.
To avoid it, reduce the number of the concurrent threads.
Also, explicitly configure retries making them be absent in the `read` load and be present in the `prepare write` one.
Fixes: #5940
> fix(large-partitions): update config file for 4days

- sdcm/cluster.py
- sdcm/nemesis.py
- sdcm/tester.py
- sdcm/utils/health_checker.py
- sdcm/utils/raft/__init__.py
- sdcm/utils/raft/common.py
Some jobs for 5.2 could run with raft disabled.
In this case group0 is empty and not need to check consistency of group0 and tokenring
Add new method to get status of raft (is_enabled, is_ready) if raft is disabled, group0_members will be empty, and consistency check will be skipped
Failed jobs: 
- https://jenkins.scylladb.com/job/enterprise-2023.1/job/upgrade-with-raft/job/rolling-upgrade-ubuntu22.04-with-raft-test/4/
- https://jenkins.scylladb.com/job/enterprise-2023.1/job/disabled_raft/job/longevity-1tb-7days-test/3/
> fix(cluster): Add checks for raft disabling

- performance_search_max_throughput_test.py
If configuration parameters set so, that on next step num of loaders become 0, test could be terminated with error Division by 0:
c:sdcm.sct_events.file_logger p:ERROR >
threads = (best_result["total_threads"] // (len(self.loaders.nodes) * stress_num)) - threads_step p:ERROR > ZeroDivisionError: integer division or modulo by zero
when counting number of loaders for next iteration, if num of loaders become 0 or less break the test.
job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Raya/job/perf-search-best-throughput-config-test-copy/7/
> fix(search_max_througput): stop iteration on 0 num of loaders

- sdcm/cluster.py
- sdcm/cluster_k8s/__init__.py
- sdcm/utils/remote_logger.py
Currently we use `kubectl` based pod logger which sometimes causes problems because stops updating logs. This causes various issues, as ScyllaDB logs are needed by nemesis and to detect failures.
Switch to k8s python client based logger as it was proven to be more reliable.
refs: https://github.com/scylladb/qa-tasks/issues/979
> feature(k8s): k8s client based scylla pod logger

- sdcm/nemesis.py
- sdcm/utils/k8s/chaos_mesh.py
With chaos-mesh it is possible to introduce network failures using `NetworkChaos` experiment. We want to use it in K8s tests.
Introduce 4 chaos-mesh failures: packet loss, corruption, network delay and limit bandwidth.
Adapt `RandomInterruptionNetworkMonkey` to use it when on k8s.
> feature(chaos-mesh): added network interruption failures

- sdcm/utils/raft/__init__.py
Due to the K8S specifics we do not use the `ScyllaYaml` class.
So, when common code assumes we use it we get the following error:
'dict' object has no attribute 'consistent_cluster_management'
The reason for it is that we use completely different approach in K8S.
So, fix the newly introduced raft handling code [1] to work with K8S.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/6015
> fix(k8s): make raft checks work on K8S

- configurations/disable_speculative_retry.yaml
For performance tests speculative retry could affect on max throughput. Disable it on scylla server side with new additional config yaml for keyspace1.standard1 table, created by c-s performance tests
> fix(yaml): Add config yaml to disable speculative retry

- defaults/severities.yaml
- sdcm/sct_events/database.py
Due to https://github.com/scylladb/scylladb/issues/12972 SCT test fails. But this issue is not severe and should not cause failure of the test.
Reduce severity of `raft - transfer snapshot error` to `WARNING` as per developers request until issue is fixed.
> fix(event): ignore raft transfer snapshot error

- vars/createTestJobPipeline.groovy
enterprise base name job was wrong, hence all update to new jobs did come automaticlly to enterpise folders also the `is_enterprise` flag wasn't enabled meaning the enterprise specific jobs were not created as
they should.
> fix(createTestJobPipeline): fix enterprise job name

- sdcm/cluster_k8s/__init__.py
Recently we found out that K8S multitenant setup fails due to multiple threads (3-10 out of 14).
And the point of hanging is the `node.init()` method which gets called 42 times in a narrow time range running 14 tenants.
So, make run only 1 at a time using the lock mechanism.
Fixes: #6095
> fix(k8s): run only one 'node.init()' method at once

- jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile
- jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
- jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
- jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
- jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/debian11-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/enterprise-ami-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
- jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Previously, the manager pipeline supported a 'manager' param, but it was removed a while ago. Still, the parameter remained set in all of the manager test scenarios' jenkins files. I removed all of those unnecessary parameter settings.
> fix(manager jenkinfiles): removed outdated 'manager' parameter

- sdcm/utils/nemesis_utils/indexes.py
After dropping an index it is common that some nodes will report errors in logs (https://github.com/scylladb/scylladb/issues/12977) for longer period than we expected it. These errors are not severe, rather expected.
Prolong event filter for this error to 3 minutes so it is not failing the test.
> fix(CreateIndexNemesis): prolong errors filter time after drop

- defaults/aws_config.yaml
Too often we are unable to request spot instances due to high prices. As such, we've decided to increase the maximum price we will pay for a spot instance from 60% of the price of an on demand node to 80%.
> fix(spot price): increase max spot price to 80% of on_demand price

- data_dir/c-s_uda_udf.yaml
- sdcm/utils/udf.py
- sdcm/utils/udf_scripts/wasm_div.yaml
- sdcm/utils/udf_scripts/wasm_div_fin.yaml
- sdcm/utils/udf_scripts/wasm_plus.yaml
- sdcm/utils/udf_scripts/wasm_plus_acc.yaml
- sdcm/utils/udf_scripts/wasm_simple_return_int.yaml
- test-cases/features/uda_udf.yaml
- uda_udf_test.py
- unit_tests/test_uda.py
- unit_tests/test_udf.py
Since 5.3 we use `wasm` instead `xwasm`. And `xwasm` script type does not work anymore.
Replace all `xwasm` occurrences with `wasm`.
> fix(udf): replace xwasm with wasm

- sdcm/nemesis.py
- sdcm/utils/sstable/load_utils.py
- unit_tests/test_utils_common.py
In case `load_and_stream` finish too quickly we get into error when we get ending stream log line when getting lines to verify if it started. In that case wait for ending will fail as `done` line has already been consumed.
Fix is about splitting log follower to 2: one for start and another for done - so waiting for start will not consume lines about stream is done.
> fix(load_and_stream): fix log followers

- defaults/manager_versions.yaml
- defaults/test_default.yaml
manager 3.1 was recently released, and then
we want to start using it in our regular tests.
For it, i added the repository list of manager
3.1, and changed the `test_default.yaml` to
use it.
also, removing 2.6, as we support last 2
versions only.
> fix(manager): bumping manager version

- docs/artifacts_test.md
since #6124 was merged, a small doc update was missing. this commit changes that, so we have now an updated doc with missing Ubuntu22 in place, and removing the deprecated Ubuntu18
> fix(artifacts_test.md): replace ubuntu18 to ubuntu22

- sdcm/sct_config.py
they were wrongly used in sct_config `__init__`,
making us list every image, and "manually" filter
by searching for the version number, while the
function that does that list, has a much better
filtering mechanism.
We are in recent 5.2 upgrade jobs having problem
of the version did not change, as we are finding
the very last release candidate (`5.2.1`) and
starting from it (as a GCE pre-installed image).
we should be checking for last already released
one, and it will give us exactly what we need.
this test (pre-installed images on GCE) was
recently added (this is the 1st version using it).
> fix(sct_config): `get_scylla_gce_images_versions` filters

- defaults/test_default.yaml
- docs/configuration_options.md
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/PR-provision-test-docker.yaml
- test-cases/PR-provision-test.yaml
- test-cases/artifacts/amazon2.yaml
- test-cases/artifacts/ami.yaml
- test-cases/artifacts/azure-image.yaml
- test-cases/artifacts/centos7.yaml
- test-cases/artifacts/centos8-selinux.yaml
- test-cases/artifacts/centos8.yaml
- test-cases/artifacts/debian10.yaml
- test-cases/artifacts/debian11.yaml
- test-cases/artifacts/docker.yaml
- test-cases/artifacts/gce-image-persistent-disk.yaml
- test-cases/artifacts/gce-image.yaml
- test-cases/artifacts/oel76.yaml
- test-cases/artifacts/oel81.yaml
- test-cases/artifacts/rhel7.yaml
- test-cases/artifacts/rhel8.yaml
- test-cases/artifacts/rocky8.yaml
- test-cases/artifacts/rocky9.yaml
- test-cases/artifacts/ubuntu2004.yaml
- test-cases/artifacts/ubuntu2204.yaml
- test-cases/load/admission_control_overload_test.yaml
- unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
- unit_tests/test_data/test_scylla_yaml_builders/artifact_amazon2.yaml
Replication strategy for system_auth should be set for number of nodes in cluster and with appropriate Replication Strategy. See: https://docs.scylladb.com/stable/operating-scylla/security/authentication.html
task: #6084
> fix(tester.py): Set networktopologyreplication for system_auth

- defaults/k8s_eks_config.yaml
- defaults/k8s_gke_config.yaml
- defaults/k8s_local_kind_config.yaml
- docker/env/hydra.sh
- sdcm/cluster_k8s/__init__.py
- sdcm/cluster_k8s/eks.py
- sdcm/cluster_k8s/mini_k8s.py
- sdcm/k8s_configs/eks/scylla-node-prepare.yaml
- sdcm/k8s_configs/node-config-crd.yaml
- sdcm/sct_config.py
- sdcm/tester.py
Following new configuration option is added:
k8s_local_volume_provisioner_type: Literal["static", "dynamic"] = "static"
If it is set to `static` then will be used old approach for Scylla disk setup.
If it is set to `dynamic` then new approach will be used which is added in latest dev operator versions `1.9.0+`
Backend support:
- `EKS` backend is fully supported.
- Local K8S backend (`kind`) is partially supported - only volume provisioner part without disk setup (mocked using `dd`+`mkfs` commands).
- `GKE` backend is not supported.
> feature(k8s): add support for dynamic local volume provisioner

- data_dir/scylla-dash-per-server-nemesis.master.json
Prometheus deployed by Scylla operator uses 2 scrapes on each Scylla pod.
So, filter out second one in the node count dashboards to avoid doubled values.
> improvement(grafana): properly calculate nodes number in K8S's grafana

- sdcm/microbenchmarking.py
Switch to use new index for microbenchmarking tests
> fix(microbenchmarking): Switch to use new index

- sdcm/report_templates/results_latency_during_ops_short.html
- sdcm/results_analyze/__init__.py
Performance report for latency during operations displays only results for current run.
Add to result anylyzer functionality, which search result per version, calculate average per cycle for percentiles [90, 99] and operation duration and add new rows to table with best results per version
> fix(LatencyDuringOperationsPerformanceAnalyzer): Add best version result

- test-cases/longevity/longevity-lwt-24h-multidc.yaml
When test runs with cl=QUORUM, ONE or SERIAL, it does not use multidc environment since it does not use local CLs. DC config is ignored.
LOCAL_QUORUM, LOCAL_ONE and LOCAL_SERIAL should be used instead.
> fix(longevity): use LOCAL consistency level in multiDC tests

- sdcm/cluster_k8s/mini_k8s.py
In local K8S setups we have the step where we load docker images once and then push it into the K8S nodes which are running as docker containers.
But the problem with it is that we run it even when we reuse an existing setup.
At first, it is totally redundant action.
At second, it takes significant time.
So, cache docker images only on newly created setups.
> fix(k8s-local): do not run docker images cache in 'reuse setup' cases

- data_dir/cs_multidc_si_lcs.yaml
- data_dir/cs_mv_si_keyspace1.yaml
- test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml
Job with longevity-multidc-parallel-topology-schema-changes-12h.yaml
failed due c-s command incorrect parameters.
fix query for si in c-s profile with correct usage. before c-s failed
with error request non-existent table
fix operation name for c-s user profile
Decrease dataset size to avoid possible large partition warnings
and c-s failing during parallel nemesis running. Similar errors
were seen in longevity-parallel-topology-schema-changes-12h job
> fix(yaml): Update c-s parametes for multidc schema-topology test

- sdcm/microbenchmarking.py
- unit_tests/test_microbenchmarking.py
After changing es index for microbenchmarking test resutls, unit tests start failing. Unit test try to get response from file and if not it try to get data from ES. But after changing ES index return results are empty.
Add new cli parameter for microbenchmarking to pass ES index name to work with.
unit tests are passed
Fixes: #6144
> fix(microbenchmarking): pass es index as cli parameter

- sdcm/cluster.py
In the `wait_till_tasks_threads_are_stopped` method we check bunch of threads existence but do not check it's `is_alive` status. It leads to the redundant sleeps for each of the DB nodes.
So, check the `is_alive` status first before going to the cycle of checks and sleeps.
> fix(cluster.py): make stop of threads do less redundant sleeps

- sdcm/sct_config.py
- unit_tests/test_config.py
Recently was added check for the numbers of AZs and DB nodes (https://github.com/scylladb/scylla-cluster-tests/pull/6055). 
The K8S backends are different and specifically EKS one requires at least 2 AZs to be configured.
Only the first AZ will be used for node provisioning. 
So, knowing that, skip the AZ num check on K8S backends.
> fix(sct_config): do not check AZ num for K8S

- sdcm/nemesis.py
The 120% allocation causes various failures.
Better to keep the 90% allocation test only.
Fixes:  #6143
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6143
> fix(nemesis.py): Remove the 120% allocation from disrupt_memory_stress

- defaults/test_default.yaml
- docs/configuration_options.md
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/PR-provision-test-docker.yaml
- test-cases/PR-provision-test.yaml
- test-cases/artifacts/amazon2.yaml
- test-cases/artifacts/ami.yaml
- test-cases/artifacts/azure-image.yaml
- test-cases/artifacts/centos7.yaml
- test-cases/artifacts/centos8-selinux.yaml
- test-cases/artifacts/centos8.yaml
- test-cases/artifacts/debian10.yaml
- test-cases/artifacts/debian11.yaml
- test-cases/artifacts/docker.yaml
- test-cases/artifacts/gce-image-persistent-disk.yaml
- test-cases/artifacts/gce-image.yaml
- test-cases/artifacts/oel76.yaml
- test-cases/artifacts/oel81.yaml
- test-cases/artifacts/rhel7.yaml
- test-cases/artifacts/rhel8.yaml
- test-cases/artifacts/rocky8.yaml
- test-cases/artifacts/rocky9.yaml
- test-cases/artifacts/ubuntu2004.yaml
- test-cases/artifacts/ubuntu2204.yaml
- test-cases/load/admission_control_overload_test.yaml
- unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
- unit_tests/test_data/test_scylla_yaml_builders/artifact_amazon2.yaml
We found these commits to cause problems in various tests. E.g. errors:
`<stdin>:1:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=[40.76.197.20:9042](http://40.76.197.20:9042/)`
and for nonroot installs cant find cqlsh
Reverting it so we can proceed with tests and fix it later.
> Revert networktopologyreplication for system auth

- sdcm/utils/replication_strategy_utils.py
- unit_tests/test_replication_strategy_utils.py
Non-root artifacts tests doesn't have cqlsh and failed to apply Alter table query. Also  cqlsh could failed by timeout.
Switch to use python driver for executing queries
> fix(replication_strategy): use python driver for cql command

- test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Performance test-write test latency-with-operations always terminated by timeout and doesn't send results. Set large test duratin to reach end of test and get results
staging job running for 25 hours. Increase job duration to 1700 m
> fix(yaml): Set larget duration for latency-with-ops

- docker/env/version
- requirements.in
This change adds required argus version to the sirenada stable branch
hydra image.
> improvement(hydra): Update argus to 0.11.1 (siren-stable)

- defaults/test_default.yaml
- docs/configuration_options.md
- sdcm/sct_config.py
- sdcm/tester.py
- test-cases/PR-provision-test-docker.yaml
- test-cases/PR-provision-test.yaml
- test-cases/artifacts/amazon2.yaml
- test-cases/artifacts/ami.yaml
- test-cases/artifacts/azure-image.yaml
- test-cases/artifacts/centos7.yaml
- test-cases/artifacts/centos8-selinux.yaml
- test-cases/artifacts/centos8.yaml
- test-cases/artifacts/debian10.yaml
- test-cases/artifacts/debian11.yaml
- test-cases/artifacts/docker.yaml
- test-cases/artifacts/gce-image-persistent-disk.yaml
- test-cases/artifacts/gce-image.yaml
- test-cases/artifacts/oel76.yaml
- test-cases/artifacts/oel81.yaml
- test-cases/artifacts/rhel7.yaml
- test-cases/artifacts/rhel8.yaml
- test-cases/artifacts/rocky8.yaml
- test-cases/artifacts/rocky9.yaml
- test-cases/artifacts/ubuntu2004.yaml
- test-cases/artifacts/ubuntu2204.yaml
- test-cases/load/admission_control_overload_test.yaml
- unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
- unit_tests/test_data/test_scylla_yaml_builders/artifact_amazon2.yaml
Replication strategy for system_auth should be set for number of nodes
in cluster and with appropriate Replication Strategy.
See: https://docs.scylladb.com/stable/operating-scylla/security/authentication.html
removed all system_auth_rf from conf files
> Change auth rf with fix

- sdcm/utils/nemesis_utils/indexes.py
Filtering of `Error applying view update` for short period after dropping index is not working correctly due missing wildcards.
Fix by adding wildcards to begin&end of filter regex.
> fix(indexes.py): fix regex for filter event

- Jenkinsfile
using some 5.0 isn't relevent anymore in most cases, and we want to test latest released version
> feature(Jenkinsfile): scylla 5.2.0 as default in SCT CI

- data_dir/nemesis.yml
- data_dir/nemesis_classes.yml
- sdcm/nemesis.py
Recently we added support of 2 NetworkInterruptions nemesis in kubernetes, but we didn't enebled them in `kubernetes` nemesis filter.
This commit adds 2 network interruption nemesis to `kubernetes` filter.
> feature(SisyphusNemesis): add network interruptions to kubernetes filter

- sct.py
- sdcm/provision/azure/provisioner.py
- sdcm/utils/common.py
- unit_tests/test_clean_cloud_resources_func.py
For the moment each cleanup code does much more API calls than it is really needed.
So, improve the `clean-resources` logic the following ways:
- Run cleanup only on a backend that was used by a test run.
- Use only one GCE project.
- Run K8S cleanup before the VMs one.
- Combine different node types cleanups into one.
> improvement(cleanup): remove redundancy from the 'clean-resources'

- defaults/k8s_eks_config.yaml
- defaults/k8s_gke_config.yaml
- defaults/k8s_local_kind_config.yaml
Update the `scylla_version` option default value to be the most recent stable version `5.2.1`.
Also, update the `stress_image.cassandra-stress` option value to use the same the most recent stable Scylla version.
> improvement(k8s): use latest stable scylla by default in K8S

- test-cases/longevity/longevity-parallel-schema-changes-12h.yaml
Stress commands periodically failed on parallel nemesis testruns.
This happened because used to large partitions and high rate when
some nodes is under disruptive nemesis with topology changes.
Update c-s and s-b command parameters with smaller rate and
partition size
> fix(parallel-schema-chanages): Update stress parameters

- performance_search_max_throughput_test.py
number of threads for c-s command calculated on each iteration when num of loaders or processes is changed. One of edge case,num of threads for next stage could be equal 0 when
when calculated on initial setup and current results.
example one of the run:
Number of Loaders | Number of Processes | Threads per process | Total Threads | Ops(kOps) | Latency 95th | Latency 99th
-- | -- | -- | -- | -- | -- | --
8 | 8 | 75 | 4800 | 214564.0 | 191.32 | 408.62
8 | 8 | 90 | 5760 | 211362.0 | 239.0 | 506.27
8 | 7 | 90 | 5040 | 215340.0 | 202.1 | 432.19
8 | 6 | 90 | 4320 | 217705.0 | 172.74 | 356.76
8 | 5 | 90 | 3600 | 217984.0 | 138.17 | 294.63
8 | 4 | 90 | 2880 | 219265.0 | 102.84 | 219.63
8 | 3 | 90 | 2160 | 218587.0 | 69.82 | 148.78
8 | 2 | 90 | 1440 | 221269.0 | 34.2 | 77.83
8 | 1 | 90 | 720 | …
> fix(perf_search_best_config): use base threads if counted thread is 0

- defaults/k8s_local_kind_config.yaml
- test-cases/scylla-operator/functional.yaml
Because we have another feature enabled by default which is available only in the unreleased scylla-operator versions:
- setup of local disks
> fix(k8s): use latest scylla-operator by default

- sdcm/tester.py
- unit_tests/test_tester.py
This fix corrects an issue where amount of total events submitted to
Argus was amount of events requested from the events device (which would
be a 100). This is now corrected and total amount of events is now
correctly retrieved from event summary log.
Task: scylladb/qa-tasks#929
> fix(tester.py): Submit correct amount of total events to Argus

- sdcm/nemesis.py
- sdcm/utils/sstable/load_utils.py
- sdcm/wait.py
- unit_tests/test_utils_common.py
- unit_tests/test_wait.py
There are situations where ssh connection is dropped while rebuild. This leads to start decommission while rebuild is in progress (e.g. in `add_remove_dc`) - failing decommission and leaving dangling db node.
Workaround ssh issue by explicitly waiting for rebuild to finish, so decommission can be triggered.
To achieve that, new context manager `wait_for_log_lines` was created, where provided db node and regex patterns to wait for (start regex and end pattern can be provided separately). See unit tests for examples.
refs: scylladb/scylladb#14004
> fix(add_remove_dc): wait for rebuild

- sdcm/results_analyze/__init__.py
Each perf test with nemesis uses its own index in ES. Query was hardcoded with index for mixed tests.
Fix query search parameters for getting results perf test with right index.
PR: https://github.com/scylladb/scylla-cluster-tests/pull/4883 was not backported to perf-v14 branch. Backporting it now 
will cause conficts. Easy way is merge to branch-perf-v14 new PR.
PR is only for branch-perf-v14
> fix(LatencyPerfAnalyzer): Fix query search parameter

- test-cases/longevity/longevity-lwt-24h-multidc.yaml
After we start to use LOCAL_QUORUM and LOCAL_SERIAL in the longevity-lwt-24h-multidc the Load became very low - max 15% CPU.
Change DB instance type to smaller type
> improvement(longevity): change DB instance type in lwt-multidc-24h

- sdcm/utils/remote_logger.py
In case stream is closed, stopping logger fails on opening socket as fp is not opened.
Fix is to clear `_stream` when we know it is already closed.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6191
> fix(k8sLogger): fix stop logger when stream is closed

- sdcm/cluster_k8s/__init__.py
On k8s we still don't support multi-dc but we already have some code to setup cassandra-rackdc.properties file with some values that possibly don't work.
Remove redundant code so there's no need to update it on refactor.
> fix(k8s): remove redundant dc setup in node_setup

- defaults/test_default.yaml
- jenkins-pipelines/longevity-cdc-100gb-4h.jenkinsfile
- jenkins-pipelines/longevity-counters-multidc.jenkinsfile
- jenkins-pipelines/longevity-topology-changes-3h.jenkinsfile
- sdcm/cluster.py
- sdcm/cluster_aws.py
- sdcm/nemesis.py
- sdcm/sct_config.py
- sdcm/snitch_configuration.py
- sdcm/utils/properties.py
- test-cases/longevity/longevity-cdc-100gb-4h.yaml
- test-cases/longevity/longevity-counters-multidc.yaml
- test-cases/longevity/longevity-topology-changes-3h.yaml
Tests running in multi-az environments generate additional
network-traffic costs. We can simulate racks with
`GossipingPropertyFileSnitch` snitch and provision instances in
one az to avoid them.
Apply `GossipingPropertyFileSnitch` to the nodes and make provisioning
to provision instances only in one az, but configure nodes snitch to
simulate multi-az environment.
> feature(multi-az): add possibility to simulate racks

- functional_tests/scylla_operator/test_functional.py
In K8S functional tests we use `db_cluster.name` attr for the
`ScyllaDBMonitoring` object name, but in the
`check_kubernetes_monitoring_health` method we automatically pick up
the `db_cluster.scylla_cluster_name`. Both are different in CI.
So, fix the K8S monitoring functional tests to use the same attribute
as the health checker does.
- [c] All new and existing unit tests passed (CI)
> fix(k8s-ci): use the same `cluster_name` in all K8S monitoring methods

- sdcm/cluster.py
- sdcm/snitch_configuration.py
In case we cassandra-rackdc.propertie does not need to be updated skip update of cassandra-rackdc.properties file.
Also removed code related different snitches - as acutally there are only 2 options: Multi-dc and simulated racks situation
> fix(snitch): don't update snitch properties when no need

- configurations/arm/centos8.yaml
- sdcm/utils/common.py
- unit_tests/test_config.py
the image we were using seem to be deprated and don't show on console, and don't have it's metadata available anymore failing like:
```
if not ami_built_by_scylla(ami_id, region_name):
File ".../sdcm/utils/common.py", line 2028, in ami_built_by_scylla
return image.owner_id == SCYLLA_AMI_OWNER_ID
File "../boto3/resources/factory.py", line 386, in property_loader
return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```
updated form a fresh image taken from:
https://www.centos.org/download/aws-images/
> fix(arm-centos8): replace deprecated ARM image

- sdcm/cluster_k8s/__init__.py
The `fix(k8s): make pod waiters use pod selectors` commit in the (https://github.com/scylladb/scylla-cluster-tests/pull/6130) PR made 
the `static` loaders be broken by using wrong selector. 
The common label between `dynamic` and `static` loaders is `loader-cluster-name`
not `loader-name` which exists only in `dynamic` case.
The labels may be checked by looking at the config files located at
the `sdcm/k8s_configs/loaders/` directory and `metadata.labels` field.
So, use proper loaders pod selector which will work in both cases.
> fix(k8s): make static loaders work again

- test-cases/scylla-operator/longevity-scylla-operator-12h-multitenant-14-clients.yaml
In case of 14 tenants setup we should use at most '1/14' of the available storage. Available is 3.5Tb, so, set 249Gb for each of 14 tenants to make it possible to work with reserved storage.
9029b271c61e5c9d6e62b3c6f178516ee1be7fb3 changed this only for the perf tests, and missed the longvities
> fix(k8s): set Scylla storage size in 14 tenants longevity

- defaults/test_default.yaml
- docker/gemini/README.md
- docker/gemini/image
- sdcm/gemini_thread.py
- unit_tests/test_config.py
Recently many changes were added to Gemini.
Update default Gemini version to 1.8.2 and fix releasing process as
docker images are now uploaded automatically upon releasing Gemini.
Because new docker image changed entrypoint and dir structure, some
adaptations were required to the way we run it.
> feature(gemini): update gemini to 1.8.2

- sdcm/utils/adaptive_timeouts/load_info_store.py
`test_id` is not stored in ES because `ESAdaptiveTimeoutStore` is initialized early, before `TestConfig.test_id` is set.
Get valid `test_id` when storing data.
> fix(adaptive_timeouts): fix missing test_id in ES

- tox.ini
The current `tox.ini` config was written for the `3.23.x` versions. It is pretty old versions. Now we have `4.5.x`.
So, update the `tox.ini` config to support both due to the following reason:
- `LTS Ubuntu 22` has `tox` package, but it is of the `3.21.x` version
- We can install any `tox` package version from sources such as `4.5.1`
> fix(tox): use config syntax compatible for 3.x and 4.x versions

- sdcm/sct_provision/aws/cluster.py
We use the same VM size for oracle db for gemini based tests. While oracle db should be bigger to handle load without effort.
Fix param name used to pick VM size for oracle db.
> fix(test): fix oracle instance type for gemini tests

- sdcm/utils/aws_utils.py
- sdcm/utils/common.py
since for reporting purpose, new ScyllaDB images
created by Releng are going to be created under
Releng's sub-account, other than the main account. For this, SCT needs to add support for it, but as
we still have all images up until now created in the main account, we need to continue to support it.
This fix will allow us to use any, new or old
images, in any branch, so we will always have the
ability to run new and old images.
Fixes: #6163
Refs: scylladb/scylla-pkg#3312
> fix(images account): ScyllaDB images are moving account

- sdcm/tester.py
When the replication_factor's type is an int, but is not equal to zero, a NetworkTopologyReplicationStrategy instance is created, but it is not assigned to the replication_strategy param, leaving it empty. This commit amends that.
> fix(create_keyspace): assign value to the replication_strategy variable

- test-cases/longevity/longevity-cdc-100gb-4h.yaml
For the moment the `longevity-cdc-100gb-4h` is configured the way that it works only in `eu-west` regions:
replication = {'class': 'NetworkTopologyStrategy', 'eu-west': '3'}
Since we support more regions than compatible with the configuration we should use region-agnostic configuration like following:
replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': '3'}
So, update the `longevity-cdc-100gb-4h` job because it is used for testing of new patch-releases of the `branch-5.2` Scylla branch.
> fix(cdc-100gb): use any-region compatible replication config

- sdcm/cluster.py
in operator functional test we have cases that `availability_zone` is not defined and an it was failing like this:
```
test_functional.py::test_mgmt_backup[3.0.0]
...
self.racks_count = simulated_racks if (simulated_racks :=
self.params.get("simulated_racks")) else len(
>           self.params.get("availability_zone").split(","))
E       AttributeError: 'NoneType' object has no attribute 'split'
```
fixed the asumption in this case, that `availability_zone` would be defined.
> fix(cluster): support case where `availability_zone` not defined

- test-cases/manager/manager-regression-ipv6.yaml
- test-cases/manager/manager-regression-multiDC-set-distro.yaml
- test-cases/manager/manager-repair-control.yaml
- test-cases/manager/manager-repair-intensity-multiple-repaired-nodes.yaml
- test-cases/manager/manager-repair-intensity-single-repaired-nodes.yaml
Recently, the manager test jobs have been failing consistently due to spot terminations and due to our spot price being too low. Since i4i have a much lower Frequency of interruption than i3 instances (<5% as opposed to >20%) I altered all of the automatically triggered jobs to use i4i (db) instances.
> improvement(manager): Use i4i instances for all aws (small) scenarios

- jenkins-pipelines/nemesis/longevity-5gb-1h-BlockNetworkMonkey-aws.jenkinsfile
- jenkins-pipelines/nemesis/longevity-5gb-1h-BlockNetworkMonkey-azure.jenkinsfile
- jenkins-pipelines/nemesis/longevity-5gb-1h-RandomInterruptionNetworkMonkey-aws.jenkinsfile
- jenkins-pipelines/nemesis/longevity-5gb-1h-RandomInterruptionNetworkMonkey-azure.jenkinsfile
- jenkins-pipelines/nemesis/longevity-5gb-1h-StopStartInterfacesNetworkMonkey-aws.jenkinsfile
- jenkins-pipelines/nemesis/longevity-5gb-1h-StopStartInterfacesNetworkMonkey-azure.jenkinsfile
- test-cases/nemesis/longevity-5gb-1h-BlockNetworkMonkey.yaml
- test-cases/nemesis/longevity-5gb-1h-RandomInterruptionNetworkMonkey.yaml
- test-cases/nemesis/longevity-5gb-1h-StopStartInterfacesNetworkMonkey.yaml
The individual nemesis jobs was introduced in 5.2, but networking nemeses actually not tested because of test misconfiguration (these nemeses require extra NIC)
The first release we actually try to run them is 2023.1 and it failed because of another test misconfiguration: they require public IP SSH connections.
Examples: 
* False positive run (5.2):  https://jenkins.scylladb.com/view/scylla-5.2/job/scylla-5.2/job/nemesis/job/longevity-5gb-1h-BlockNetworkMonkey-aws-test/4/
* Failed run (2023.1): https://jenkins.scylladb.com/view/enterprise-2023.1/job/enterprise-2023.1/job/nemesis/job/longevity-5gb-1h-BlockNetworkMonkey-aws-test/3/
* Fixed and passed run (staging): https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/evgeniy/job/longevity-5gb-1h-BlockNetworkMonkey-aws-test/5/
> fix(test-cases/nemesis): use public IPs when we use extra NIC

- jenkins-pipelines/audit/longevity-100gb-4h.jenkinsfile
- jenkins-pipelines/audit/longevity-schema-changes-3h.jenkinsfile
- sct.py
* as a first step have a few short cases with audit enable
by default
* add support for creating the audit folder in jenkins,
and poplate with those audit tests
> feature(audit): new short longevity with audit enabled

- sdcm/sct_runner.py
as part of 43e4973c375233d2672c4a8a43b4a93ecc6caba0 when libcloud was remove, the `.destory()` call was left in sct_runner, and was failing to clean runners like this:
```
Terminate [gce/us-east1-d] sct-runner-1-6-instance-ffeb15d5,
launched at June 09, 2023, 01:08:40 UTC, keep: 16, keep_action:
terminate, public IPs are ['35.231.187.71']
Exception raised during termination of [gce/us-east1-d] sct-runner-1-6-instance-ffeb15d5,
launched at June 09, 2023, 01:08:40 UTC, keep: 16, keep_action: terminate,
public IPs are ['35.231.187.71']: Unknown field for Instance: destroy
```
replaced it with the correct call for deleting an instance.
> fix(sct-runner): call the correct API for deletion

- upgrade_test.py
Info event prints node python object instead of node name:
```
message=Upgraded Nodes to be rollback are: [<sdcm.cluster_gce.GCENode object at 0x7f413c697dc0>,
<sdcm.cluster_gce.GCENode object at 0x7f413c622110>]
```
> fix(upgrade): fix InfoEvent message in test_generic_cluster_upgrade

- upgrade_test.py
Scylla version of a node is received as output of a shell command 'scylla --version'. The output includes end-line character and that breaks the InfoEvent message to the 2 lines:
:INFO  > : (InfoEvent Severity.NORMAL) message=original scylla-server version is 2023.1.0~rc6
:INFO  > , latest: 5.2.1-0.20230508.f1c45553bc29
As result only part of the message is presented in event.log Strip the output to prevent it.
> fix(upgrade): remove end-line character from stdout

- sct.py
- sdcm/utils/aws_utils.py
- sdcm/utils/common.py
since releng is moving to create the images on another account, we have introduced the changes to list the images regardless general or releng accounts #6167, but we lack during `verify_configuration_urls_validity` the tags, as they are not listed in the general account, but only on releng account, hence we need to impersonate releng account to list the tags (as we need to validate content of `user_data_format_version` to proceed with SCT provision steps.
> fix(images account): new releng account images tags missing

- configurations/operator/perf-regression-latency-and-throughput-multitenant-2-clients.yaml
- configurations/operator/perf-regression-latency-and-throughput-multitenant-7-clients.yaml
- configurations/operator/perf-regression-latency-multitenant-2-clients.yaml
- configurations/operator/perf-regression-latency-multitenant-7-clients.yaml
- defaults/k8s_eks_config.yaml
- test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
Before, when we were using `static local volume provisioner`, the disk usage was not limited and a test run could use whole disk space even if PVCs for Scylla pods were having a lower limit than the real disk capacity.
When we switched to the `dynamic local volume provisioner` the PVC size limit started making the effect not allowing to use storage more than configured.
The default value of 500Gi becomes not enough in some cases. For example the `large collections` one.
So, configure the Scylla pods storage to be `k8s_scylla_disk_gi: 3490` by default which is close to the real disk available capacity (`3.5Tb`). Update the multitenant configurations separately
based on the number of tenants.
It will allow us to avoid the following error:
Compacting of 3 sstables interrupted due to: \ …
> fix(k8s-eks): use proper disk sizes for Scylla pods

- sdcm/utils/common.py
Sine there was one instance of `GkeCleaner` created and used at the same time when multiple k8s clusters where found, and failed like:
```
Going to delete kubernete-scylla-upgrade-master-... GKE cluster from the gcp-sct-project-1 project
Going to delete longev-scylla-operat-3h-master-... GKE cluster from the gcp-sct-project-1 project
409 Client Error for http+docker://localhost/v1.43/containers/create?
name=gke-cleaner-7b6778fe-gcloud: Conflict ("Conflict. The container name
"/gke-cleaner-7b6778fe-gcloud" is already in use by container
"210c7f3f4c27ebc2a8f2a83835fed6648a8291a507a1beea6b84cd056e88918a".
You have to remove (or rename) that container to be able to reuse that name.")
```
Fixes: scylladb/scylla-cluster-tests#5516
> fix(gke-cleanup): create GkeCleaner instance per k8s cluster

- test-cases/longevity/longevity-topology-changes-3h.yaml
fix the yaml that was wrongly introduced in
510c26c17b7d9ff6f6cd811fa5e1513e42464969
match this file as it on master brach now
> fix(longevity-topology-changes-3h): don't specify DC names

- test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Incease test duration and stress write command duration up to 2 days to get email results
> fix(perf-latency-nemesis): Set large test duration

- sdcm/nemesis.py
we are going to introduce uuid_sstable_identifiers_enabled option to scylla. and will enable it by default. when it is enabled the sstable identifier will be represented using a timeuuid instead of an integer. so we should not try to match the identifier with "\d+" anymore.
so, in this change, we just relax the regular expression and use `[^-]+-[^-]-` for matching the sstable file prefix.
See-also: https://github.com/scylladb/scylladb/issues/14283
> fix(nemesis): match non-digit prefix sstable identifier as well

- mgmt_cli_test.py
Since the cluster in the test_backup_feature test scenario contains hundreds of tables (as a result of one of the test functions), trying to restore a backup that contains said tables an extremely long time. As such, the test will now use a keyspace-specific backup when creating a restore task
> fix(test_backup_feature): only backup a specific keyspace for a restore

- sdcm/provision/security.py
since we are using public address for azure artifact test cause we are running it from AWS jenkins worker having this port not open seems to be slowing
cassandra-stress since failing to connect to this port for every extra smp is slowing it even more.
> fix(azure-artifacts): make shard aware port public

- sdcm/sct_events/database.py
SCT incorrectly reports error events for
standard log lines of the libabsl module.
It should be filtered out.
some scylla log prints, like in the case of core dump, generates a line like:
```
Found module libabsl_stacktrace.so.2206.0.0 with build-id: 0c356bbf44c196a8964e52aba16bd6fb494dbd9e
Metadata for module libabsl_stacktrace.so.2206.0.0 owned by FDO found: {
```
As a result, an SCT error message is created:
```
2023-05-18 05:32:17.821: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=59f779b0-60e4-4558-8860-56f615e04d0c: type=STACKTRACE regex=stacktrace line_number=53393 node=longevity-10gb-3h-2023-1-db-node-17516d2f-0-6
Found module libabsl_stacktrace.so.2206.0.0 with build-id: 0c356bbf44c196a8964e52aba16bd6fb494dbd9e
``` …
> fix(event filter): exclude 'libabsl' from stacktrace regex

- defaults/k8s_gke_config.yaml
- jenkins-pipelines/operator/upgrade/upgrade-major-scylla-k8s-eks.jenkinsfile
- jenkins-pipelines/operator/upgrade/upgrade-major-scylla-k8s-gke.jenkinsfile
- jenkins-pipelines/operator/upgrade/upgrade-scylla-k8s-eks.jenkinsfile
- jenkins-pipelines/operator/upgrade/upgrade-scylla-k8s-gke.jenkinsfile
- vars/rollingOperatorUpgradePipeline.groovy
since operartor 1.8 was are testing mainly the enterprise images, and we should change the default of the test to the latest verisons we want to be using.
> fix(k8s-upgrade): change base and target version to enterprise

- test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml
- test-cases/upgrades/generic-rolling-upgrade.yaml
- test-cases/upgrades/multi-dc-rolling-upgrade.yaml
- test-cases/upgrades/rolling-upgrade.yaml
- unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.yaml
set recover_system_tables option to False
due to https://github.com/scylladb/scylladb/issues/11907
> fix(Rollback): disable recover_system_tables

- mgmt_upgrade_test.py
In manager 3.0, the format of 'next run' time of a task from a simple timestamp to a string indicating the time remaining until the next run. Now, in manager 3.1.1, the format seem to have been revereted back. To pervent further confusion, I will now check the format the 'next run' value before parsing it.
> fix(mgmt_upgrade_test): discover the format of next_run before parsing

- configurations/manager/debian10.yaml
Since the previous ami was deprecated, I've replaced it with a newer, supported image
> fix(manager debian 10): update ami id

- test-cases/longevity/longevity-change-cluster-size-by-2-times.yaml
- test-cases/longevity/longevity-multidc-parallel-network-schema-changes-12h.yaml
- test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml
- test-cases/longevity/longevity-parallel-schema-changes-12h.yaml
Some schemachange nemesis are marked as disruptive, becuse change topology by stop/reloading node. This could bring unexpected errors when several nemesis running in parallel like topology-change and schema-change for raft testing.
Add flag to filter out nemesis which has disruptive and schema change flags
> fix(longevity-parallel-nemesis): Add exclude disruptive flag

- sdcm/utils/common.py
since moved to check new releng account for
the images that will be created in there in
the near future, we are experiencing still
exceptions when there are no tags (but for
some reason, there was meta.data), so the
idea is to also check if there are tags, so
we won't try to "list them" whem they don't
exist.
> fix(list images): avoid getting exception

- sdcm/wait.py
`tenacity.RetryError` get a future as parameter, and SCT was passing a string to it's `__init__`
causing this failure in cases of casscading `wait_for` calls:
```
res = retry(func, **kwargs)
except Exception as ex:  # pylint: disable=broad-except
err = f"Wait for: {text or func.__name__}: timeout - {timeout} seconds - expired"
LOGGER.error(err)
>           if hasattr(ex, 'last_attempt') and ex.last_attempt.exception() is not None:
E           AttributeError: 'str' object has no attribute 'exception'
```
> fix(wait_for): stop using `tenacity.RetryError`

- sdcm/report_templates/results_perf_simple_query.html
- sdcm/utils/microbenchmarking/perf_simple_query_reporter.py
remove the last 10 test run results from the perf_simple_query test email report leave only the last 10 Scylla builds dates results
> fix(perf_simple_query): adjust email report

- upgrade_test.py
If `nodetool drain` is stuck and reached its timeout and retrying is initiated, it fails with error:
`Operation drain is in progress, try again`
We do not need to retry drain operation in rolling upgrade test. Example:
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/rolling_upgrade_with_sla/6/
> fix(upgrade test): not retry drain operation

- test-cases/scylla-operator/kubernetes-platform-upgrade.yaml
Latest scylla-operator supports K8S `v1.24+`
So, remove old leftover which was setting the EKS version to be `1.23` for K8S platform upgrade tests.
> fix(k8s): use newer K8S version in K8S platform upgrade tests

- sct.py
- unit_tests/test_base_version.py
- utils/get_supported_scylla_base_versions.py
Since 5.2 and 2023.1 will be the 1st official versions
of Scylla to support Azure (OSS and Enterprise
respectively), we needed a mechanism to add support
for it. It right now gives us a place to add
the initial supported version for different cloud
providers, if they will be added to Scylla.
So let's suppose that, for each OSS we upgrade from
previous version + current version previous released patches.
In case of Azure cloud provider, we will no do that, as
for `5.2` as an example, `5.1` doesn't officially support
Azure images... so we will know how to correctly
filter, in our upgrade jobs, what is the "oldest"
version we should use in these tests.
Relates to https://github.com/scylladb/qa-tasks/issues/1116
> improvement(azure): add feature for cloud_provider initial support.

- test-cases/performance/perf-regression.100threads.30M-keys.yaml
In the K8S throughput tests we use smaller instance type then in all other EKS tests.
So, we should redefine the disk size there which must be smaller than the default value.
Without it the Scylla PVC won't be scheduled breaking Scylla pods provisioning.
> fix(k8s-perf): set correct PVC size for K8S thrpt tests

- sdcm/cluster_k8s/__init__.py
We enable it only on the scylla-operator deployment from scratch. 
But it also must be enabled after it's upgrade.
Without it, we get following error:
```
OSError: [Errno 8] Tried connecting to [('13.49.200.202', 9142)]. \
Last error: EOF occurred in violation of protocol (_ssl.c:997)
```
> fix(k8s): enable alpha TLS feature for operator after upgrade

- sdcm/nemesis.py
During test: longevity-alternator-200gb-48h-gce
Two nemesis where we need to ignore connection_refused
```
[Thread-13] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to alternator:8080 [alternator/10.142.0.26] failed: Connection refused (Connection refused)
```
spotted on:
disrupt_stop_start_scylla_server
disrupt_kill_scylla
> fix(alternator): fix three nemesis with ignore_ycsb_connection_refused

- jenkins-pipelines/jepsen.jenkinsfile
PR (#5721) added one more required 'param' to the vars/createSctRunner.groovy groovy file - `test_name`
and PR (#5831) was trying to align all pipelines to have this but jepsen on didn't had `test_name` in it's pipelineParams so it was failing like the following:
```
06:05:42  Going to run './sct.py  create-runner-instance --cloud-provider gce --region us-east1
--availability-zone a --test-id 2166dec8-3354-4c1e-9aca-b7185cf00761 --duration 905 --test-name '
...
06:05:48  Error: Option '--test-name' requires an argument.
```
> fix(jepsen-pipeline): add `test_name`

- test-cases/longevity/longevity-10gb-3h.yaml
Test failed because it waited for a decommission nemesis.
Increasing test duration can workaround the problem.
(or alternatively decrease both test and stress duration a bit)
Increasing duration from 240 to 255 as in master. still not sure it'll work until tested.
2021.1 release doc:
https://docs.google.com/document/d/1R98ZCheWfKnGl16bZEkiFPX6juvbU-IB-Ontd1nH3q8/edit?disco=AAAAzpgnPTY
Failure:
```
2023-06-21 11:44:48.115: (TestTimeoutEvent Severity.CRITICAL), Test started at 2023-06-21 08:22:03, reached it's timeout (240 minute)
```
> fix(10gb-3h-gce-longevity): Modify test duration to avoid timeout

- ics_space_amplification_goal_test.py
- sdcm/tester.py
- test-cases/features/ics_space_amplification_goal_test.yaml
fix(ICS SAG): 4 loaders + i4i.4xlarge. Added is_compaction_running
In order to put more load on compactions,
the stress now uses 4 loaders instead of 1.
the first test-cycle of no-sag is removed as well.
Added a major compaction between test cycles.
Added an assertion of used-capacity before cycle starts.
> fix(ICS SAG): 4 loaders + i4i.4xlarge. Added is_compaction_running

- configurations/kms-ear.yaml
- jenkins-pipelines/EaR-longevity-kms-200gb-6h.jenkinsfile
- sdcm/cluster.py
- sdcm/provision/scylla_yaml/scylla_yaml.py
- sdcm/remote/remote_file.py
- unit_tests/test_scylla_yaml.py
Scylla added a support for AWS KMS to be used with
the enterprise feature of Encryption-at-Rest.
* adding new test configuration yaml for it
* support it in scylla.yaml
> feature(EaR-KMS): Add tests for EaR AWS KMS service

- sdcm/cluster_k8s/__init__.py
ac8279770a6167feeb1f4142735eaccc6b3ee063 changed `fstrim_scylla_disks` implementation to support `k8s_local_volume_provisioner_type=dynamic` but it's selectors were not quite accurate.
this fixes them, and add support the output of the command to be newline seperated correctly
when it was failing it was failing like this:
```
Running command "kubectl --cache-dir=... --namespace=local-csi-driver
exec -ti  -- sh -c 'fstrim -v /mnt/persistent-volumes'"...
error: pod, type/name or --filename must be specified
```
> fix(k8s): make `fstrim_scylla_disks` work correctly

- sdcm/nemesis.py
The nemesis did not raise an un-supported-nemesis exception.
It only returned, so nemesis is marked as completed successfully.
Fixing it to raise an exception.
[argus](https://argus.scylladb.com/test/32eea484-9fbe-48bd-a0a8-ed9e202706ad/runs?additionalRuns[]=5c106365-f5f1-4d58-b19d-98254b63934b)
> fix(nemesis.py): fix skip toggle-cdc nemesis

- defaults/test_default.yaml
- docs/configuration_options.md
- performance_regression_test.py
- sdcm/sct_config.py
- test-cases/performance/perf-regression.100threads.30M-keys.yaml
Depend on stress workload, number of processes could give different max throughput. Split stress multiplier on 3 w,r,m. This will allow to configure different number of stress process on loader instance for write, read, mixed independently.
> fix(perf_stress): Split stress multiplier by stress workload

- test-cases/longevity/longevity-counters-multidc.yaml
the case was pinned to older s-b cause of: scylladb/scylla-bench#114 but since then we implemented s-b retires that should fix most of the of the timeout observed in 2023.1 run.
Ref: https://github.com/scylladb/scylla-bench/issues/114
> fix(longevity-counters-multidc): unping scylla-bench

- test-cases/artifacts/amazon2.yaml
- test-cases/artifacts/ami.yaml
- test-cases/artifacts/azure-image.yaml
- test-cases/artifacts/centos7.yaml
- test-cases/artifacts/centos8-selinux.yaml
- test-cases/artifacts/centos8.yaml
- test-cases/artifacts/debian10.yaml
- test-cases/artifacts/debian11.yaml
- test-cases/artifacts/docker.yaml
- test-cases/artifacts/gce-image.yaml
- test-cases/artifacts/oel76.yaml
- test-cases/artifacts/oel81.yaml
- test-cases/artifacts/rhel7.yaml
- test-cases/artifacts/rhel8.yaml
- test-cases/artifacts/rocky8.yaml
- test-cases/artifacts/ubuntu2004.yaml
Remove default values for repos and machine images to avoid situations when we run artifacts tests against wrong Scylla version.
By Roy/Israel request.
Fixes #3566
> fix(artifacts): remove defaults for Scylla repos/machine images

- functional_tests/scylla_operator/test_functional.py
- sdcm/cluster_k8s/__init__.py
- sdcm/mgmt/cli.py
- sdcm/mgmt/operator.py
- sdcm/nemesis.py
Some recent changes to backup nemesis are now trying the clear existing tasks, but it wasn't implemented, and failing like:
```
File ".../sdcm/nemesis.py", line 4425, in wrapper
File ".../sdcm/nemesis.py", line 2611, in disrupt_mgmt_backup
self._mgmt_backup(backup_specific_tables=False)
File ".../sdcm/nemesis.py", line 2643, in _mgmt_backup
self._delete_existing_backups(mgr_cluster)
File ".../sdcm/nemesis.py", line 2619, in _delete_existing_backups
mgr_cluster.delete_task(backup_task.id)
File ".../sdcm/mgmt/operator.py", line 391, in delete_task
raise NotImplementedError()
NotImplementedError
```
we now can lookup the cluster spec for those task
and remove them from cluster spec
> fix(k8s-manager): implement `delete_task`

- sdcm/nemesis.py
When using simulated racks we use GossipingPropertyFileSnitch, in that case `dc_suffix` from `cassandra-rackdc.properties` is not used causing AddRemoveDC nemesis to fail.
Detect snitch and use proper parameter in `cassandra-rackdc.properties`.
> fix(add_remove_dc): fix dc name when GossipingPropertyFileSnitch is used

- sdcm/cluster.py
Since the installation command occasionally fails due to the dkpg lock being occupied, I replaced the apt-get command call with the BaseNode.install_package method, that is capable of waiting for the dkpg lock to be released.
> fix(install_scylla): use install_package for software-properties-common

- test-cases/jepsen/jepsen.yaml
- test-cases/jepsen/jepsen_with_raft.yaml
this legecy cluster init doesn't work anymore
and would fail with the following:
```
[shard 0] init - Startup failed: std::runtime_error (Node 10.142.0.39 has
gossip status=UNKNOWN. Try fixing it before adding new node to the cluster.)
```
together with https://github.com/scylladb/jepsen/pull/17, jepsen was passing 
in: https://jenkins.scylladb.com/job/scylla-master/job/jepsen/job/jepsen-test-all/172/
> fix(jepsen-test): remove `use_legacy_cluster_init`

- sdcm/wait.py
If `wait_for_log_lines` function fails to find `end_line_patterns` in logs then it print wrong error message specifying there the `start_line_patterns`.
So, fix it by printing correct info.
> fix(wait.py): make 'wait_for_log_lines' print proper error msgs

- sdcm/nemesis.py
- test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
- test-cases/longevity/longevity-large-partition-3h.yaml
This change adds a random chance to use a "USING TIMESTAMP"
clause instead of normal 50% of the partition, inteded to cover the
usage of both "USING TIMESTAMP" and introduce potential variability into
partition makeup that could potentially reflect on mvs/gsi updates due
to large deletions.
Task: scylladb/qa-tasks#1009
> improvement(nemesis.py): Covering MVs and Indexes and USING TIMESTAMP

- jenkins-pipelines/longevity-topology-changes-3h.jenkinsfile
- test-cases/longevity/longevity-topology-changes-3h.yaml
There's an issue with longevity-topology-changes-3h scenario when
multi-az is set up.
We want to track this issue in master branch so disabling multi-az from
2023.1 release to not causing failures in it.
> test(longevity): remove multi-rack from longevity topology changes

- defaults/test_default.yaml
- unit_tests/test_config.py
Many fixes recently were introduced to Gemini and it was released.
Update default Gemini version to 1.8.4
> feature(gemini): update gemini to 1.8.4

- test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
The reason is that the prepare load almost overloads the Scylla pods and any disruption to any of the Scylla clusters will cause loader failures.
So, to avoid it disable nemesis during the 'prepare' phase which runs only for bunch of minutes.
> fix(k8s): do not run nemesis during prepare in 2 tenants longevity test

- sdcm/nemesis.py
- sdcm/utils/adaptive_timeouts/__init__.py
`add_remove_mv` nemesis fails sometimes with timeout. We would like to know how much time create mv took but still fail if it exceeds 2h.
Added `adaptive_timeout` for this operation with 2h soft timeout and 5h of hard timeout.
Also increased `create_index` hard timeout to 5h.
> feature(add_remove_mv): add soft timeout for create mv

- sct.py
use set_test_id_only instead of set_test_id to do not
touch logging and rewrite "latest" symlink  during
create-argus-test-run and finish-argus-test-run
because it is not SCT run
> fix(Argus): use  set_test_id_only in sct.py

- defaults/k8s_eks_config.yaml
- defaults/k8s_gke_config.yaml
- defaults/k8s_local_kind_config.yaml
- functional_tests/scylla_operator/test_functional.py
* add functional test of manager 3.1
* remove testing of manager 2.6
* default all k8s runs to use manager 3.1
> fix(k8s): switch to use and test manager 3.1

- test-cases/longevity/longevity-topology-changes-3h.yaml
Decrease partition size for stress commands, because job could failed with too many inflight hints
Job: https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-topology-changes-3h-test/
during topology changes.
> fix(topology-change-3h): Decrease partition size for stress

- upgrade_test.py
`-a` is the short form of `--include-all-sstables`, which instruct the tool and in turn scylla to compact *all* sstables no matter if their format version is identical to the latest format version. at the time of writing, it is "me". by default, nodetool does exclude sstables of current version from being compacted.
in https://github.com/scylladb/scylladb/issues/14548, we found that scylla took almost 6 hours to complete this command. and it compacted more than 873GiB data in total. this behavior is expected. but the use case is not very popular. as the whole point of "nodetools upgradesstables" is to upgrade the sstable format from an old one the the latest one supported by scylla.
so, in this change, we just drop the `-a` option from the `nodetool upgradesstables` command line.
Fixes …
> fix(upgrade test): do not specfiy -a when "nodetools upgradesstables"

- unit_tests/test_config.py
it got broken, apparently, because images were
removed (related to Scylla `branch-5.1`).
Fixes: #6325
> fix(test_config): version ami branch unittest

- test-cases/performance/perf-regression.100threads.30M-keys-i4i-enterprise.yaml
- test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
- test-cases/performance/perf-regression.100threads.30M-keys.yaml
Upon preparing new jobs for performance throughputs was used default default reactor-stall-ms notifier setting 25ms
Set valid value: 5
> fix(perf-throughput): set reactor-stall-ms to 5

- sdcm/nemesis.py
major compaction original value of 7200 was
exceeded and took ~ 7600 seconds in multi-keyspace test.
Increasing it to - 8000.
multi keyspace test failed with:
```
2023-06-15 23:47:47.913: (SoftTimeoutEvent Severity.ERROR) period_type=one-time event_id=6851da21-7222-4bc2-8fa8-426405e38520 during_nemesis=MajorCompaction, source=SoftTimeout message=operation 'MAJOR_COMPACT' took 7693.749301671982s and soft-timeout was set to 7200s
File "/usr/local/lib/python3.10/threading.py", line 966, in _bootstrap
self._bootstrap_inner()
File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.10/threading.py", line 946, in run
self._target(*self._args, **self._kwargs)
File …
```
> fix(major compaction nemesis): increase adaptive timeout to 8000

- test-cases/gemini/gemini-3h-with-nemesis.yaml
Since there is a consistent issue using the latest gemini version, we set the version to the one used in the latest stable run, 1.7.8
> fix(gemini-3h-with-nemesis): set gemini version to 1.7.8

- test-cases/upgrades/rolling-upgrade.yaml
Since there is a consistent issue using the latest gemini version, we set the version to the one used in the latest stable run, 1.7.8
> fix(rolling-upgrade.yaml): set gemini version to 1.7.8

- mgmt_cli_test.py
Previously, we installed gsutil with an install script. However, this method is no longer functioning. As such, we replaced it and now use apt-get to install gsutil.
> fix(install_gsutil_dependencies): install gsutil with apt-get

- sdcm/nemesis.py
Problem is with detection - which is based on `scylla.yaml` taken from new node which has default setting - and failing to detect `GossipingPropertyFileSnitch` is used.
Use test param `endpoint_snitch` which should be always valid (even when using simulated racks) for detection of endpoint snitch.
fixes: #6236
> fix(AddRemoveDcNemesis): fix on simulated racks

- sdcm/nemesis.py
Based on task: https://github.com/scylladb/qa-tasks/issues/884 Refactoring nodetool_cleanup to be called by threadPoolExecutor (parallel).
> improvement(nemesis.py): refactor nodetool_cleanup to run in parallel

- configurations/gce/n2-highmem-16.yaml
- configurations/gce/n2-highmem-32.yaml
- configurations/gce/n2-highmem-48.yaml
- configurations/gce/n2-highmem-64.yaml
- configurations/gce/n2-higmem-8.yaml
- jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
- jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
- jenkins-pipelines/rolling-upgrade-debian11.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
- jenkins-pipelines/rolling-upgrade-ubuntu22.04.jenkinsfile
In order to catch more issues with installations and upgrades that are related to instance type sizes (e.g. perftune issues related to amount of cores), this commit spread 5 common instances types in gce with higher amount of disks accordingly.
> refactor(rollin-upgrades): Increase diversity of instance types

- sdcm/cluster_k8s/mini_k8s.py
Recently the helm commands started using local helm installations. 
So, install `helm` package on local K8S to be able to use it with python directly and not only via the `hydra`.
> fix(k8s-local): install helm

- jenkins-pipelines/longevity-150gb-asymmetric-cluster-12h-gce.jenkinsfile
- jenkins-pipelines/longevity-200gb-48h-gce.jenkinsfile
- jenkins-pipelines/longevity-5tb-1day-gce.jenkinsfile
- jenkins-pipelines/longevity-alternator-200gb-48h-gce.jenkinsfile
- jenkins-pipelines/longevity-large-partition-200k-pks-4days-gce.jenkinsfile
- jenkins-pipelines/longevity-large-partition-8h-gce.jenkinsfile
- jenkins-pipelines/longevity-lwt-24h-gce.jenkinsfile
- jenkins-pipelines/longevity-multi-keyspaces-60h-gce.jenkinsfile
- jenkins-pipelines/longevity-mv-si-24h-gce.jenkinsfile
- jenkins-pipelines/longevity-mv-si-4days-gce.jenkinsfile
- jenkins-pipelines/longevity-topology-changes-24h-gce.jenkinsfile
- jenkins-pipelines/longevity-topology-changes-3h-gce.jenkinsfile
- test-cases/longevity/longevity-10gb-3h.yaml
- test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml
- test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml
- test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
- test-cases/longevity/longevity-5TB-1day.yaml
- test-cases/longevity/longevity-alternator-200GB-48h.yaml
- test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
- test-cases/longevity/longevity-large-partition-8h.yaml
- test-cases/longevity/longevity-lwt-basic-24h.yaml
- test-cases/longevity/longevity-multi-keyspaces.yaml
- test-cases/longevity/longevity-mv-si-4days.yaml
- test-cases/longevity/longevity-topology-changes-3h.yaml
Based on task: https://github.com/scylladb/qa-tasks/issues/1134
1. longevity-200gb-48h-gce.jenkinsfile
2. longevity-150gb-asymmetric-cluster-12h-gce.jenkinsfile
3. longevity-large-partition-8h-gce.jenkinsfile
4. longevity-large-partition-200k-pks-2days-aws-i4i-gce.jenkinsfile
5. longevity-alternator-200gb-48h-gce.jenkinsfile
6. longevity-lwt-24h-gce.jenkinsfile
7. longevity-multi-keyspaces-60h-gce.jenkinsfile (Use even 64 cores)
8. longevity-topology-changes-3h-gce.jenkinsfile (Duplicate it and extend it to run 24h also for aws)
9. longevity-topology-changes-24h-gce.jenkinsfile 
10. longevity-mv-si-4days-gce.jenkinsfile (Duplicate it and decrease it to run 24h)
11. longevity-mv-si-24h-gce.jenkinsfile
> Add longevity pipelines to extend GCP coverage

- sdcm/provision/common/utils.py
Since we are running on some cases into disconnection of ssh during some nodetool operation, it was suggested that we'll add this to `sshd_config`:
```
ClientAliveInterval 60
ClientAliveCountMax 10
```
Ref: https://github.com/scylladb/scylladb/issues/14004
> fix(sshd_config): enable keep-alive configuration

- defaults/test_default.yaml
- test-cases/longevity/longevity-100gb-4h.yaml
- test-cases/longevity/longevity-large-collections-12h.yaml
- unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.result.json
- unit_tests/test_data/test_scylla_yaml_builders/artifact_amazon2.result.json
- unit_tests/test_data/test_scylla_yaml_builders/cdc-replication-longevity.result.json
- unit_tests/test_data/test_scylla_yaml_builders/functional.result.json
- unit_tests/test_data/test_scylla_yaml_builders/jepsen.result.json
- unit_tests/test_data/test_scylla_yaml_builders/longevity-10gb-3h.result.json
- unit_tests/test_data/test_scylla_yaml_builders/manager-backup-1TB-gce.result.json
- unit_tests/test_data/test_scylla_yaml_builders/perf-regression.100threads.30M-keys.result.json
- unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.result.json
- unit_tests/test_scylla_yaml_builders.py
The feature is disabled in all cloud clusters and probably in the field. leaving one sanity test to make sure it still works, but disabling for all other scenarios for now.
> refactor(hinted_handoff): Disable hinted_handoff for all tests

- sdcm/sct_config.py
- sdcm/utils/common.py
In PR #5502 filter was introduced to `get_branched_ami` but now seems like we case of release like versions which are debug versions (and doesn't get shared
with our account), and we need to ignroe them as well.
Fixes: #6362
> fix(get_scylla_ami_versions): filter debug versions

- vars/getJobTimeouts.groovy
a76ed862ad99c58012699546822eab08a94b2ea9 introduced a new parameter to the longevity pipeline, but it's was breaking all other pipelines, like:
```
java.lang.NullPointerException: Cannot invoke method toInteger() on null object
```
> fix(pipelines): handle stress_duration correctly

- Jenkinsfile
- vars/getJobTimeouts.groovy
Fix rest (missed) of shebang lines after fixing most of them in https://github.com/scylladb/scylla-cluster-tests/pull/5527
> fix(Jenkins): use correct shebang string

- sdcm/sct_runner.py
`hydra create-runner-image` failed to run on GCP after #6137
The instance type is selected based on test_duration here: https://github.com/scylladb/scylla-cluster-tests/blob/f77e6b3d0bada938c74c7f495fc14c14d57be761/sdcm/sct_runner.py#L405
and doesn't need to be overwritten in the `_create_instance(...)` method
> fix(sct_runner): fix create-runner-image on GCP

- defaults/test_default.yaml
- get-qa-ssh-keys.sh
- sdcm/logcollector.py
- Use correct IP address for SSH connection
- Don't use support user credentials (the SSH key will be provided by siren-tests)
- Small refactoring of `find_and_append_cloud_manager_instance_to_collecting_nodes()`
Need to backport https://github.com/scylladb/scylla-cluster-tests/pull/6381/commits/e1e85b4508b227a6076920152b8d066ce382d4cb to SCT release branches to stop sync support key.
> Rework cloud manager instance discovery

- sdcm/cluster.py
Fixing the changes introduced in https://github.com/scylladb/scylla-cluster-tests/pull/6062 for the case if INTRA_NODE_COMM_PUBLIC is False.
Note, that it's not required to replace second occurrence of  `ip_address` with `external_address`.
> fix(cluster): use external_address in cql_ip_address

- sdcm/utils/common.py
logcollector failed to run for AWS accounts w/o SCT builders deployed in. This PR fixes the problem with `get_builder_by_test_id()` function: `ParallelObject` requeries a non-empty list of arguments.
> fix(logcollector): don't fail if no builders found

- sdcm/remote/remote_cmd_runner.py
Change parameter passed to paramiko Connection from `pkey` to `key_filename`. This allows paramiko to guess the type of a private key.
> fix(remote): allow use non-RSA private keys

- sdcm/report_templates/results_performance.html
This change adjusts the order in which the performance results table is
built, ordering each row by scylla version it was compared to.
Task: scylladb/qa-tasks#1144
> improvement(report_templates): Sort performance results by version

- sdcm/cluster.py
this offline installer test wasn't triggered on master so we missed that it doesn't install java correctly and now scylla is failing to install since java 11 or 8 isn't available
Fix: #6336
> fix(artifacts-amazon2-test): install java 11

- docker/env/version
- requirements.in
- requirements.txt
- sct.py
- sdcm/sct_runner.py
- sdcm/utils/gce_utils.py
The IP pool is a list of pre-allocated IP address tagged with 'sct-runner-pool' tag.
The use of SCT can provide a name of a pool to use (the value of such tag.)
This PR implements such functionality for AWS and GCP. Azure implementation is missed (and not required now.)
> improvement(runner): associate a public IP from a pool

- sdcm/provision/azure/utils.py
in the case we use a version, we must ignore master images, as master has a "version" prefix, but it
is marked with `-dev`, and it must be ignored
in this case.
found by @yaronkaikov
> fix(azure utils): get_scylla_images using version flag

- sdcm/nemesis.py
- sdcm/sct_events/filters.py
A repair stream on node gets an expected error of
"stream id 1 not found" during reboot, so it
has to be filtered out.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5187
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5187
> fix(RepairStreamingErr): filter stream-not-found during reboot

- upgrade_test.py
since scylladb/scylladb/pull/13932 sstable identifier are not numbers, and the regex we were using in upgradesstable procudure assumed they are.
failing like the following:
```
AssertionError: Failed to upgrade the sstable format [False, False, False, False]
```
Ref: https://github.com/scylladb/scylladb/pull/13932
> fix(upgrade_test): handle uuid sstable identifier on upgradesstable

- docs/configuration_options.md
- internal_test_data/complex_test_case_with_version.yaml
- sdcm/sct_config.py
- sdcm/tester.py
The SCT parameter `gce_image` was used in ancient times before we got GCE Scylla machine images to define GCE images once for all types of nodes. But nowadays, it's not used anywhere and doesn't have a default value, causing failures of Scylla Cloud longevities.
> fix(sct_config): remove unused parameter gce_image

- sdcm/logcollector.py
Since the yaml is sometimes required for manager related investigations, I added it to the collected log entities of the monitor log collector
> improvement(MonitorLogCollector): Added scylla-manager.yaml

- docs/faq.md
show how monitor stack create with `hydra investigate show-monitor` can be cleaned (with killing all other running docker instances)
Fixes: #3074
> fix(docs): document how to clear monitoring docker instances

- test-cases/longevity/longevity-large-partition-3h.yaml
Comments are not supported on indices, thus removing this.
Closes #6400
> fix(test-cases): Remove WITH COMMENT from CREATE INDEX query

- docker/env/version
- requirements.in
- unit_tests/provisioner/test_user_data_builder.py
- unit_tests/test_scylla_yaml.py
This PR fixes hydra image building issues, namely it updates PyYAML 
(and relevant dependencies) to prevent build errors with Cython
- fix(hydra): Update PyYAML and awscli
- improvement(hydra): Update hydra image to contain PyYAML==6.0.1
> Fix hydra image build issues

- sdcm/sct_config.py
- sdcm/utils/common.py
- unit_tests/test_config.py
yet again older AMI were removed, and those tests are failing, also move this test to be an integration test so it would be annoying us that often.
> fix(sct_config): 4.6.3 AMIs were removed

- sdcm/report_templates/results_perf_simple_query.html
- sdcm/utils/microbenchmarking/perf_simple_query_reporter.py
fix email regression reporting X per op -> lower is better.
> fix(perf_simple_query): fix email reporting

- test-cases/artifacts/gce-image.yaml
In a recent change in the artifact trigger (https://github.com/scylladb/scylla-pkg/pull/3500/files) a new set of large instance types were added. Some of those instance types require at least 16 local SSDs in order to start at all (described here: https://cloud.google.com/compute/docs/disks/local-ssd#choose_number_local_ssds) As such, I set the number of local SSDs in the GCE artifact job to 16
> fix(artifacts-gce-image): set the number of local SSDs to 16

- sdcm/cluster.py
- sdcm/logcollector.py
- sdcm/remote/libssh2_client/__init__.py
When Scylla freezes on stop, SIGABRT is sent by systemd automatically
creating coredump. It would be informative if `lsof` and `netstat`
output was attached to issue along with core dumps.
In case timeout occures during stopping scylla, collect `lsof` and
`netstat` output. After collection send SIGABRT to Scylla process.
To make this possible, needed to fix our sshlib2 based remoter:
fix(ssh): Fix close session on timeout
When command times out and does not print anything to stdout/stderr,
then timeout error does not appear and command hangs until it quits.
This causes error e.g. when we run `systemctl stop scylla` and there's a
freeze in stopping Scylla's process.
Fix is about ignoring `channel.close()` return code, which in that case
returns `LIBSSH2_ERROR_EAGAIN`. This code in case of …
> feature(node): collect lsof and netstat on scylla stop freeze

- sdcm/nemesis.py
In case no partitions found, delete partition/range of partition nemeses can not be run because they need to delete part or full partition. 
Now error log is printed and nemesis finished like 'successfull'. 
Raise UnsupportedNemesis to mark that nemesis was not run
> fix(nemesis): raise UnsupportedNemesis if no partitions

- data_dir/nemesis.yml
- data_dir/nemesis_classes.yml
- defaults/manager_persistent_snapshots.yaml
- mgmt_cli_test.py
- sdcm/cluster.py
- sdcm/mgmt/cli.py
- sdcm/mgmt/common.py
- sdcm/mgmt/operator.py
- sdcm/nemesis.py
- unit_tests/test_nemesis_sisyphus.py
Since manager 3.1, manager now supports restoring previously created backups. In this PR I added a new manager restore nemesis, that restores data from previously created snapshots (seen in manager_persistent_snapshots.yaml)
> feature(nemesis): Added manager restore nemesis

- mgmt_cli_test.py
- sdcm/cluster.py
- sdcm/mgmt/cli.py
- sdcm/mgmt/operator.py
https://github.com/scylladb/scylla-manager/pull/3496 brought new repair option --single-host-parallelism we need to test it
> feat(repair): enable single-host-parallelism for repairs

- data_dir/nemesis.yml
- data_dir/nemesis_classes.yml
- sdcm/nemesis.py
- sdcm/utils/aws_kms.py
- sdcm/utils/common.py
- unit_tests/test_nemesis_sisyphus.py
New nemesis works when:
- AWS backend is used
- Test uses Scylla version that supports `KMS`+`EaR`+`InstanceProfiles`
- Instance profile, defined in the `aws_instance_profile_name_db`
option, utilizes the `kms_user_policy` policy.
The new code utilizes several existing KMS keys for the creation of KMS key aliases and KMS keys rotation under these aliases.
If keys are absent they get created automatically.
Alias is kept per whole test run and gets cleaned up in the `cleanup` stage.
It is done so to avoid redundant Scylla nodes restarts.
> test(nemesis): add AWS KMS + EaR nemesis

- sdcm/nemesis.py
Change consistency level for delete query. Run with QUORUM instead of ONE
> fix(nemesis): run delete query with CL QUORUM

- test-cases/nemesis/longevity-5gb-1h-SlaDecreaseSharesDuringLoad.yaml
- test-cases/nemesis/longevity-5gb-1h-SlaReplaceUsingDropDuringLoad.yaml
SLA nemesis tests: missed closing apostrophe.
It was added by https://github.com/scylladb/scylla-cluster-tests/pull/6361
> fix(sla tests): missed closing apostrophe

- sdcm/nemesis.py
as we are suffering in mixed workload from really
bad replace node results, we decided that we will
run this operation when the cluster will be larger, reducing the overhead it causes on a 3 nodes cluster, but now doing it on a 6 nodes cluster (between operations `add_node` and `decommission`, so we should get better results for replace node, and not affect any other operations we have currently.
> improvement(perf during ops): change operations order
