scylladb/scylla-cluster-tests

mgmt_cli_test.py
sdcm/mgmt/cli.py

Closes #6436 
Test creates a repair task, does something then enables client ssl, restart scylla nodes and assert repair status is an ERROR.
Since there is a gap between creating a repair task and restarting scylla, it is possible that task is finished before scylla is restarted.
As result test can falsely fail.
Solution - to move repair task creating after scylla is being reconfigured

fix(mgmt_cli_test): address test_client_encryption flakiness

---

sct.py
sdcm/tester.py

now create-argus-test-run creates
a test stub with only Jenkins DATA
test DATA will be populated by SCTtest itself

fix(Argus reporting): fix ussue #6370

---

defaults/test_default.yaml
sdcm/gemini_thread.py
unit_tests/test_config.py

Currently used gemini `1.7.8` is too old for now and started failing with the most recent docker version on the ubuntu.
So, switch to more recent stable enough gemini version which is used in the current SCT master branch - `v1.8.6`.
Also, update the oracle version to the latest `patch` version.
Fixes: #6457

fix(gemini): use newer stable enough gemini version v1.8.6

---

vars/artifactsPipeline.groovy
vars/byoLongevityPipeline.groovy
vars/cdcReplicationPipeline.groovy
vars/longevityPipeline.groovy
vars/managerPipeline.groovy

The current available manager versions are 3.1 and 3.0, so I fixed the parameter's description

fix(pipelines): fix manager_version description

---

test-cases/longevity/longevity-mv-si-4days.yaml

during master tier1 runs, we seen monitor having
some dificulties to show dashboards, for more
than one run, so we here increase the instance
type for the monitor, expecting it to work
better for future runs.

fix(mv si 4d): increase monitor instance type

---

sdcm/cluster.py
sdcm/nemesis.py
sdcm/utils/sstable/sstable_utils.py

We need to increase amount of destoyed SSTables and be able to change this amount randomly.
Few changes are presented in this commit:
- choose one or all files of a table
- destroy files in the specific keyspace and not random only as it works now
- change amount of destoryed SSTable (percent from all existing SSTables of the table) and not 
5 files only as it works now

refactor(sstables): choose sstables and destroy in nemeses

---

upgrade_test.py

cause of new sstable uuid identifer feature the old `sstabledump` can't currently work with those sstables
Ref: https://github.com/scylladb/scylla-tools-java/issues/333

fix(upgrades): replace `sstabledump` with `scylla sstable dump-data`

---

artifacts_test.py
configurations/local-ear.yaml
configurations/longevity-fips-and-encryptions.yaml
jenkins-pipelines/longevity-100gb-4h-fips.jenkinsfile
test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml

FIPS are a set of standards for encryption algorithms (among others). To verify that Scylla complies with all fips completely, I created this scenario which enables every kind of encryption scylla supports, while FIPS is enabled

test(fips): added a 4h 100gb longevity with fips enabled + artifact fixes

---

sdcm/nemesis.py

Commit https://github.com/scylladb/scylla-cluster-tests/pull/6450/commits/ bd9acd9ecb600c72ead5a9e181238ccf1aed7f6c presented common solution for all delete_by_range nemeses - run delete query with CL=QUORUM by using 'SimpleStatement'. 
I missed that 'SimpleStatement' is already used in 'delete_by_range_using_timestamp'. So now it causes to query failure:
```
Executing CQL '<SimpleStatement query=<SimpleStatement query=delete from scylla_bench.test using timestamp 1691403471151446 where pk = 122, 
consistency=Not Set>, consistency=QUORUM>' ...
Error querying host 10.0.3.12:9042 
TypeError: object of type 'SimpleStatement' has no len()
```

fix(nemesis): remove SimpleStatement from delete_by_range_using_timestamp

---

sdcm/provision/azure/utils.py
unit_tests/provisioner/test_azure_get_scylla_images.py

right now, the images we find for Azure are ordered by their creation time, so, we need to reverse this list's order to be able to use the "1st" image in
the list to have the newest image in use, when the list has more than 1 item.
same thing we have for all other cloud providers.

fix(azure get_scylla_images): reverse the list order

---

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml

The 200k-pk run with loader e2-standard-2 experienced an OOM.
It might be resolved using a stronger instance.
Refs: https://github.com/scylladb/scylla-bench/issues/127
Refs: https://github.com/scylladb/scylla-bench/issues/127
[argus](https://argus.scylladb.com/test/917e825f-11f9-4493-acdb-ec5266a3af78/runs?additionalRuns[]=5cd89f45-07f3-4865-8f4a-34c4071e2bdd)

fix(longevity 200k-pk): Increase loader type to e2-standard-4

---

sdcm/nemesis.py

There is no point of retries on this command, since once it started the reties would fail with the following:
```
failed: std::runtime_error (cleanup request failed:
there is an ongoing cleanup on keyspace1.standard1)
```
Ref: https://github.com/scylladb/scylladb/issues/14004

fix(nodetool_cleanup): remove retries from cleanup

---

sct.py

Since FIPS support is an enterprise feature, its jenkins jobs should only be created under an enterprise release. So I added a new directory and filter in create_test_release_jobs_enterprise, so the FIPS jobs will be created under its own directory under SCT_Enterprise_Features in jenkins.

improvement(create_test_release_jobs_enterprise): create folder for FIPS

---

sdcm/cluster_k8s/__init__.py

Recently we bumped to issue with startup failure of scylla-manager due housekeeping service hang. We found we use `4.6.0` for it.
Let's bump Manager's Scylla version along with Manager to test latest versions.

fix(k8s): update scylla manager for k8s tests

---

sdcm/cluster_k8s/eks.py

API K8S EKS logs are billable.
So, enable it only when configured to be so using the `k8s_log_api_calls` config option.
When enabled, the logs can be viewed on the AWS website like following:
https://eu-north-1.console.aws.amazon.com/cloudwatch/home?region=eu-north-1#logsV2:log-groups
It is stored endlessly by default, the retention is not set. 
So, no need to gather it ourselves. Just use web console when logging gets enabled.
Closes: #3859

improvement(k8s-eks): use `k8s_log_api_calls` option to enable API logs

---

sdcm/sct_provision/aws/instance_parameters_builder.py

OracleScyllaInstanceParamsBuilder use wrong name of parameter instance type:
_INSTANCE_TYPE_PARAM_NAME = 'instance_type_db' instead of _INSTANCE_TYPE_PARAM_NAME = 'instance_type_db_oracle'
These is was also a reason why gemini could failed on different tests, because oracle node has too slow instance

fix(DBOraclePlanBuilder): use valid config parameter

---

test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml

This commit changes the default disk size for sct runner to 120 GB in longevity-1TB-5days because we run out of space on the sct runner

fix(longevity): extend root_disk_size_runner to 120 for 1tb-5days

---

sdcm/utils/nemesis_utils/indexes.py

In case test uses parallel nemesis, in case one node is down during create index/view, db throws errors like `Error applying view update`. We want to ignore such errors.
Added EventsFilter during wait for index/view to be built in situations we use parallel nemesis.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6469

fix(wait_for_view_to_be_built): ignore some errors in parallel nemesis

---

sdcm/cluster.py
sdcm/nemesis.py

Accroding to task: https://github.com/scylladb/qa-tasks/issues/1146 
Move the wait_node_fully_start method to BaseNode in cluster.py
Fix the refferences for this method in nemesis.py

improvement(BaseNode): move wait_node_fully_start

---

test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml

Switch c-s commands to use LOCAL_QUORUM instead of QUORUM for multidc job
The change is required to stabilize the mulidc-schema-topology change with parallel
nemesis

fix(schema-topology-multidc): use LOCAL_QUORUM for c-s commands

---

mgmt_cli_test.py
sdcm/cassandra_harry_thread.py
sdcm/cluster.py
sdcm/exceptions.py
sdcm/kcl_thread.py
sdcm/ndbench_thread.py
sdcm/nemesis.py
sdcm/nosql_thread.py
sdcm/sct_events/continuous_event.py
sdcm/scylla_bench_thread.py
sdcm/stress/base.py
sdcm/stress_thread.py
sdcm/utils/common.py
unit_tests/test_events.py

`raise_exception_in_thread` is introduced as a way to force kill a nemesis thread for the following reasons:
a) so we don't wait for 30min at the end of every test (can be
more depend on the nemsis/testcase))
b) so nemesis are depended on the load (ex. SLA), and since we
kill the load before stopping the nemesis, if we are currently
during such a nemesis, it would spit false posisitve events
since it won't find enough load on the cluster as it expects.
Fixes: #6439

feature(nemesis): introduce `raise_exception_in_thread`

---

install-hydra.sh

right now, bash script's command describes a command that doesn't exist, leading newcomers to this mistake and making them to give up in using it.
Fixes: #4781

fix(install-hydra.sh): fix help function to a real command

---

sdcm/nemesis.py

According to task: https://github.com/scylladb/qa-tasks/issues/1400 
This commit changes the "chunk_length_kb" random choice to 128KB instead of 1MB as it is capped to 128KB according to 
https://github.com/scylladb/scylladb/commit/8a9de08510a5e9161daad0292c41d9aabbfe995d

fix(nemesis): change chunk size to 128KB

---

test-cases/artifacts/oel76.yaml
test-cases/artifacts/oel81.yaml

since #6354, all `i3` instances were deprecated
and `i4i` were put in use instead.
It started generating a problem, as OEL apparently doesn't yet support it, so reverting the change
for both OEL versions we currently support,
and we shall revert this PR, once OEL will add
support to `i4i` instances.

fix(oel artifacts): OEL doesn't support i4i instances

---

jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/debian11-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/older-enterprise-ami-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-upgrade.jenkinsfile

Since manager 3.1 is now the latest released manager version, the manager upgrade test should start from it

refactor(manager upgrade): set base version to 3.1

---

test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml

The read stress was under stress_read_cmd which doesn't work with round_robin and there isn't any reason to use this parameter here.

fix(longevity-1tb): Move read stress under stress_cmd

---

mgmt_cli_test.py
sdcm/nemesis.py

Manager 3.2 - no longer initialize a repair after a restore task

---

sdcm/nemesis.py

fix(k8s): make nemesis handling logic be stable in multitenant setups

---

functional_tests/scylla_operator/test_functional.py
sdcm/nemesis.py

fix(k8s): skip empty rack deletion test and nemesis for broken versions

---

unit_tests/test_base_version.py

since 2023.1 was recently released, and Azure
initial support is 5.2 AND 2023.1, unit tests
started to fail, as we received as a valid base
version also 2023.1.

fix(azure base version): add new supported version

---

defaults/manager_versions.yaml
defaults/test_default.yaml

since manager 3.2.0 is being released,
we want all tests to be using it, including
older branches.
In this PR i did not deprecate 3.0 yet,
and we may do it in a follow up PR.

fix(manager): bump manager version to 3.2

---

sdcm/cluster.py

we had a recent issue with `gpg: no valid OpenPGP data found.`.
while investigating this issue, we started thinkin why
it was added at the first place, and since now, we deliver
the jdk we need within our builds, this "workaround"
is not necessary anymore.
ran [here](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/debian_no_gpg_key/job/upgrade-debian11/2/) to confirm it works
example of failures are [this manager job](https://jenkins.scylladb.com/job/manager-3.2/job/debian10-sanity-test/1/) and [this 2023.1 job](https://jenkins.scylladb.com/job/enterprise-2023.1/job/upgrade-with-raft/job/rolling-upgrade-debian11-with-raft-test/7/) among others

fix(debian installation): GPG key for openjdk remove

---

upgrade_test.py

When we use `rc` version like `2023.1.0-rc8` then the Scylla upgrade test fails to match the new Scylla version with the target one. The diff is that the version taken from the Scylla binary has `~` symbol when the target one uses `-`.

fix(upgrade): Make Scylla upgrade checks work when using 'rc' versions

---

test-cases/enterprise-features/workload-prioritization/longevity/longevity-sla-system-24h.yaml
test-cases/longevity/longevity-sla-100gb-4h.yaml

DB instance type has been changed from i3 to i4i by https://github.com/scylladb/scylla-cluster-tests/pull/6354. 
It's because i3 family was depricated in scylla-cloud. 
It caused to load decreasing in SLA longevities. And it is a critical problem for those longevities as we need almost 100% load during the tests.
I revert this change for SLA longevities and open the task [#1455](https://github.com/scylladb/qa-tasks/issues/1455) to adjust the load for i4i DB instance type

revert(instance type): use i3 type for SLA longevity

---

sdcm/tester.py
sdcm/utils/aws_region.py

When using instance type that is not available in all availability zones for given region, provision may fail. This is because we try provision in az's starting from first az. When first az does not support given instance type it fails with error `Spot request cannot be fulfilled due to invalid availability zone.`
Fix is by filtering az's that support provided instance type.
fixes: #6495

fix(provision): fix fallback to next availability zone

---

sdcm/nemesis.py

After finishing `NetworkPacketLossExperiment` SCT verifies if node returned to cluster straight away. This causes errors like: `nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.` for several seconds.
Fix is by giving node several seconds to recover from this disruption and return networking back to normal. This way we should avoid unnecessary nodetool failures.

fix(K8sNetworkBlock): wait for recovery from disruption

---

configurations/operator/perf-regression-throughput.yaml
jenkins-pipelines/operator/performance/perf-regression-throughput-eks.jenkinsfile

Some time ago the `append_scylla_args` option was added to the general config we use for testing throughput on K8S:
```
test-cases/performance/perf-regression.100threads.30M-keys.yaml
```
And it's values are not compatible with the scylla-operator. 
So, redefine that config option to make Scylla work with this config.

fix(k8s): make perf thrpt job be working

---

jenkins-pipelines/perf-simple-query-x86.jenkinsfile
sdcm/sct_config.py
sdcm/utils/aws_utils.py
test-cases/microbenchmarking/amazon_perf_simple_query_ARM.yaml
test-cases/microbenchmarking/amazon_perf_simple_query_x86.yaml

Run perf_simple_query on  x86_64

test(perf_simple_query): x86_64 job

---

sdcm/fill_db_data.py
sdcm/utils/adaptive_timeouts/__init__.py
upgrade_test.py

Read from truncated table fails with timeout (60sec) from time to time in case of mixed cluster (one node upgraded from OSS to 2023.1).
Add 'adaptive_timeout' to insert into and  read from truncated tables to be able to check how long time the query runs.
Also add try .. catch for insert into truncate tables to prevent test stop on timeout.

fix(upgrade): not fail on truncated entries timeouts

---

sdcm/cluster_k8s/__init__.py

scylla-operator `1.10.0-rc.0` runs `cleanup` pods after cluster scale up operation.
And this kind of pods have the same label as scylla pods have -> `scylla/cluster=<scylla-cluster-name>`.
Our pod anti-affinity rules catch it thinking it is Scylla pods and block Scylla pods scheduling.
It is wrong.
So, fix it by updating the `pod anti-affinity` rules to detect exactly Scylla pods.

fix(k8s): allow to schedule scylla and scylla cleanup pods on same nodes

---

defaults/k8s_eks_config.yaml
defaults/k8s_gke_config.yaml
defaults/k8s_local_kind_config.yaml

Use scylla-5.2.7 as default Scylla version and for cassandra-stress load.
It includes the fix [1] for the empty rack removal from the ScyllaCluster K8S objects.
[1] https://github.com/scylladb/scylladb/pull/14893

fix(k8s): use latest 5.2 version -> 5.2.7

---

sdcm/k8s_configs/ingress-controller/10_haproxy-kubernetes-ingress.deploy.yaml

With the scylla-operator-1.10 we started getting HA problems [1] with the `haproxy` service.
So, fix it by using the latest available ingress controller version for haproxy.
[1] https://github.com/scylladb/scylla-operator/issues/1341

fix(k8s-eks): use latest haproxy ingress controller version

---

data_dir/nemesis.yml
data_dir/nemesis_classes.yml
sdcm/nemesis.py
unit_tests/test_nemesis_sisyphus.py

Before we had only one variation - without KMS key rotation.
So, add one more - with KMS key rotation.

improvement(kms): add one more variation of the KMS nemesis

---

configurations/kms-ear.yaml
defaults/aws_config.yaml
defaults/severities.yaml
sdcm/cluster.py
sdcm/sct_config.py
sdcm/sct_events/system.py
sdcm/tester.py

With this change it becomes possible to enable KMS key rotation and dynamic alias creation for a test.
To do it just use `auto` as a value for the `kms_host` key in the value of the `scylla_encryption_options` config option. 
Example:
```
scylla_encryption_options: "{ \
'cipher_algorithm': 'AES/ECB/PKCS5Padding', \
'secret_key_strength' : 128, \
'key_provider': 'KmsKeyProviderFactory', \
'kms_host': 'auto'}"
```
Also, there is no need to specify the `kms_hosts` info in the `append_scylla_yaml` config option as it was before. 
It is allowed and will work if some specific KMS key must be used, but rotation will not be done in this case.
The rotation is done only for the dynamically/automatically created KMS key alias.

feature(KMS): add KMS key rotation on test level

---

longevity_sla_test.py
sdcm/sla/libs/sla_utils.py
sdcm/sla/sla_tests.py
sdcm/utils/adaptive_timeouts/__init__.py
sdcm/utils/adaptive_timeouts/load_info_store.py

Wait for scheduler group is created for a new service level on every node before start the load. Use 'scylla_scheduler_group_shares' prometheus metric for that. Now we wait about 15-30 sec. But if scheduler group was not created, the service level does not receive the resources and the nemesis is failed with 'no recources' error. But it wrong. Correct error - scheduler group  was not created on the node(s)

improvement(sla tests): wait for a service level is propagated to nodes

---

sdcm/scan_operation_thread.py
unit_tests/test_scan_operation_thread.py

PR: https://github.com/scylladb/scylla-cluster-tests/pull/6423 
Implement full aggregation scan verification via prometheus metric: scylla_forward_service_requests_dispatched_to_other_nodes
PR: https://github.com/scylladb/scylla-cluster-tests/pull/6461 
fix test_scan_positive test according to new validation logic in validate_forward_service_requests_dispatched_to_other_nodesi aad new negative test test_negative_prometheus_validation_error

fix(scan_operation_thread): aggregation scan verify

---

sdcm/cluster_gce.py
sdcm/utils/gce_utils.py
unit_tests/test_nemesis_sisyphus.py

Preemptible is deprecated in GCE.
Switch to use SPOT instead.
fixes: https://github.com/scylladb/qa-tasks/issues/306

fix(gce): Use spot instead preemptible in GCE

---

test-cases/jepsen/jepsen.yaml
test-cases/jepsen/jepsen_with_raft.yaml

after merging pr: https://github.com/scylladb/scylla-cluster-tests/pull/6411
jepsen tests start failig by error 'Exception: There is no pre-installed ScyllaDB '
this PR exlisitly set use_preinstalled_scylla: false in jepsen config files

fix(jepsen): fix jepsen yaml configs

---

sdcm/nemesis.py

Since stress-ng snap was taken down by Canonical for some reason this
commit removes the snapd installation and replaces stress-ng install to
main ubuntu repositories.
Closes #6555

fix(nemesis.py): Use apt to install stress-ng on ubuntu

---

sdcm/cluster.py

`scylla_shards` may return string instead of integer value. It cause to failure with error like:
```
TypeError: '>' not supported between instances of 'str' and 'int'
```
This property may receive the shards value from 3 different properties: `cpu_cores`, `smp` or `cpuset`. Every this property is used by different functions. So to decrease the impact of this fix, the shards value will be converted inside `scylla_shards` property, not in every property.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6562

fix(db node): return scylla_shard as int always

---

sdcm/sct_events/events_device.py
unit_tests/test_sct_events_events_analyzer.py

When there's a lot of events coming to events process (e.g. `events_analyzer`) it doesn't verify state of `stop_event`. This makes it to last longer than stop timeout and failing the test usually.
Fix is about verifying state of `stop_event` after each event in `inbound_events` generator - not only when it's silent for 1 second.
fixes: #6232

fix(event_process): fix stop events process under stream of events

---

sdcm/nemesis.py

The support for the `KMS+EaR` feature in the enterprise Scylla is going to be added in the `2023.1.1` version.
So, update the decorator for the appropriate nemesis with the proper version.

fix(kms): allow to run KMS nemesis starting with 2023.1.1 Scylla version

---

jenkins-pipelines/perf-regression-throughput-shard-aware-30min-gce-enterprise.jenkinsfile
test-cases/performance/perf-regression.100threads.30M-keys-i4i-enterprise.yaml
test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml

Adjust perf GCE tests to use same concurrency and load as for i4i tests

test(trougput GCE): increate concurrency

---

configurations/t3_micro_data_volumes.yaml
jenkins-pipelines/artifacts-ami-t3_micro.jenkinsfile
sdcm/cluster.py

Since scylla can't start on t3.micro without developer mode activated, I added a check in scylla_setup to activate developer mode when the instance type is t3.micro

test(artifact): add a t3.micro artifact test

---

artifacts_test.py

Since t3.micro instances don't have any local volume outside of root, t3.micro runs have an additional ebs volume. In such cases, online-discard is not enabled for the mount point, which causes verify_xfs_online_discard_enabled to fail. As such, I skipped the check when using t3.micro

fix(Artifact): skip verify_xfs_online_discard_enabled if using t3.micro

---

vars/createTestJobPipeline.groovy

seems like the cron configuration for the enterprise branch was working, and passing the wrong argument to the pipeline cause no new jobs created on enterprise branch

fix(create-sct-test-jobs): pass right parameters to enterprise case

---

sdcm/nemesis.py

since #6136 we have been testing our clusters
like all nodes are seeds (since Scylla is now
"seedless" for quite some time), but when running
`disrupt_grow_shrink_cluster` for the 5th time,
we start failing with error:
```
AssertionError: We should have at least one selected seed by now
```
this fix will also be fixing all other nemeses
that do add new nodes to the cluster, when running for quite some time, probability of hitting it on
regular replace node operations is smaller, since
this nemesis runs 3 times add new node in each loop iteration.

fix(nemesis): init new nodes must set them as seeds

---

sdcm/nemesis.py

following change proposed on #6581, we missed
another longevity, that does replace node,
as the node cannot be a seed, when it is
replacing a node (see error below):
```
[shard 0:main] init - Bad configuration:
replace-node-first-boot is not allowed for seed nodes
```
moving the `update_seed_provider()` after
we run `clean_replacement_node_options()`,
so it won't conflict.

fix(nemesis): init new node when they are seeds

---

jenkins-pipelines/rolling-upgrade-with-sla-no-shares.jenkinsfile
jenkins-pipelines/rolling-upgrade-with-sla.jenkinsfile

Since we are having issue with coredump creation on centos8,
and that we want the test to be focused on something closer to
scylla formal images.
we are switching those cases off centos8
Closes: #6582

fix(sla-rolling-upgrade): move to run on ubuntu 22.04

---

sdcm/cluster.py
sdcm/nemesis.py

The Scylla enterprise PR [1] was merged which fixed the [2] bug. So, remove the workaround for the `p11-kit` package as unneeded.
[1] scylla-enterprise/pull/3023
[2] scylla-enterprise/issues/2792

improvement(kms): remove workaround for the 'p11-kit' package

---

sdcm/nemesis_publisher.py

up until now, we were saving only Scylla version
and the git sha of the commit, making chart creation less clear or logical, since we didn't have the
commit dates to order the latest entries.
From now, the entries will have commit date,
allowing us to order the chart by commit date,
and showing the last entries, being more
meaningful for chart presentation.
Refs: scylladb/qa-tasks#1489

fix(nemesis publisher): add Scylla commit date to ES

---

sdcm/sct_events/database.py

Azure audit messages include a word 'backtrace' that causes to creating error DatabaseLogEvent and test failure.
This commit present regex change for DatabaseLogEvent.BACKTRACE event that allow to ignore the audit messages that include 'backtrace'.
```
2023-09-10T07:35:58+00:00    !NOTICE | audit: PATH item=3 name='/usr/share/man/man3/
backtrace_symbols_fd.3.gz' inode=41608 dev=08:01 mode=0120777 ouid=0 ogid=0 
rdev=00:00 nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
```

fix(event): ignore Azure audit messages

---

configurations/rf1-non-disruptive.yaml
jenkins-pipelines/longevity-200gb-48h-asymmetric.jenkinsfile
jenkins-pipelines/longevity-200gb-48h-rf1.jenkinsfile
test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml

This change adds new configurations for 200gb-48 longevities and one
low load 4 hour longevity, intended to simulate a low load happening
during repair processes, to cover potential overhead like in
scylladb/scylladb#14093.
Task: scylladb/qa-tasks#1416

feature(test-cases): Add test cases for low and asymmetric loads

---

test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
test-cases/gemini/gemini-basic-3h-ics.yaml

Gemini could generate very complex schemas and this could lead that OOM on loader and not enough resouces on db nodes.
Increase instance types to avoid unpredictable failures

fix(gemini-ics): Increase loader and db instance types

---

sdcm/nemesis.py

Following a nodetool decommission command, SCT waits for a log message like:
`became a group 0 non-voter` before issuing a reboot.
This pattern and some other, may only occur after the decommission RBNO finished.
Thus, the next nemesis step of 'reboot' may take up to decommission-timeout to initialize.
Fixes: scylladb/scylladb#6522 
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6522

fix(DecommissionStreamingErr): Increase timeout waiting for log patterns

---

test-cases/longevity/longevity-mv-si-4days.yaml

since we introduced custom time test, this
test is having too long prepare, hence it
times out... for this improvement, we are
trying to reduce its duration by removing
all reads from prepare, increasing parallelism
and removing nemesis during prepare.

fix(mv_si_4d): improve prepare stress

---

jenkins-pipelines/longevity-cdc-100gb-4h.jenkinsfile
jenkins-pipelines/longevity-counters-multidc.jenkinsfile
jenkins-pipelines/longevity-multidc-schema-topology-changes-12h.jenkinsfile
test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml
test-cases/longevity/longevity-cdc-100gb-4h.yaml
test-cases/longevity/longevity-counters-multidc.yaml
test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml

Because there are bugs found in multidc, multi-az scenarios we want to test some on regular basis.
Enabled multi-az for 2 tier1 tests and reenabled 2 another that was previously switched to simulated racks.

test(multi-az): set multi-az in several tests

---

defaults/test_default.yaml
sdcm/provision/aws/utils.py
sdcm/sct_config.py
sdcm/sct_provision/aws/__init__.py
sdcm/sct_provision/aws/cluster.py
sdcm/sct_provision/aws/instance_parameters_builder.py
sdcm/sct_provision/aws/layout.py
sdcm/utils/common.py
test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
vars/perfRegressionParallelPipeline.groovy

this commit is:
1) Include provision step into the performance pipeline
2) Add the ability to create load and DB instances within one AWS placement group
and config parameter to enable this feature
3) Update i4i Throughput perf test to  use the new feature
4) Update clean_placement_groups_aws functionality
to support --post-behavior flag in sct.py clean-resources command

feature(aws): placement group creation

---

sdcm/nemesis.py

since is_replacement_by_host_id_supported is called  before starting a node, 
and in `use_preinstalled_scylla: false` case scylla is not yet installed, 
we should check other running nodes for version
if we don't, we'll fail with a `None` version:
```
ValueError: Cannot parse provided 'None' scylla_version for the comparison.
Transformed scylla_version:
```
Fix: #6591

fix(Nemesis.add_node): support using `use_preinstalled_scylla: false`

---

sdcm/logcollector.py

We recently added setup scripts debug log on
https://github.com/scylladb/scylladb/pull/10472,
which is generated at /var/tmp/scylla/{scriptname}-{pid}-debug.log. The file contains more detail of traceback with current value of variables, it helps to fix bugs which hard to reproduce.
Since it could be multiple files and should be deleted since we expect /var/tmp/scylla will be empty when we run next test, so we need to iterate on /var/tmp/scylla/*, collect log and then delete it.

feature(log_collector): add scripts debug logs

---

sdcm/nemesis.py

The newly added `MgmtCorruptThenRepair` nemesis
should not have been marked with the `limited = True` flag.
It must have had it as `False` like the `CorruptThenRepair` one does.
Fixes: #6599

fix(nemesis): make MgmtCorruptThenRepair nemesis be out of limited group

---

defaults/test_default.yaml
functional_tests/scylla_operator/test_functional.py
longevity_test.py
sdcm/cassandra_harry_thread.py
sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_k8s/__init__.py
sdcm/ndbench_thread.py
sdcm/nemesis.py
sdcm/nosql_thread.py
sdcm/provision/scylla_yaml/node_builder.py
sdcm/sct_config.py
sdcm/scylla_bench_thread.py
sdcm/stress/base.py
sdcm/stress_thread.py
sdcm/utils/docker_remote.py
sdcm/ycsb_thread.py
test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml
test-cases/longevity/longevity-mini-test-1h.yaml
unit_tests/test_gemini_thread.py
unit_tests/test_scylla_yaml_builders.py
unit_tests/test_seed_selector.py

We want to test if Scylla works with dns names instead of IP addresses.
Adding proper methods and conditions in various places according to test configuration.

feature(sct): add support for using dns names in cluster

---

sdcm/utils/node.py
sdcm/utils/sstable/load_utils.py

since #6601 was introduced, because a function
that checks for token rings started failing
on the `curl` command builder.
this commit aims to fix it.

fix(node utils): health check started failing

---

sdcm/utils/node.py

When silent is set for `build_node_api_command` then `-s` flag is placed in wrong place making curl command to fail.

fix(healthcheck): fix silent flag in curl

---

vars/getJobTimeouts.groovy

since we separated the function that gets the
timeout for each stage, and the random region
resolution was not adapted to it, this commit
aims to fix that.

fix(random region): add region resolution to getJobTimeouts

---

sdcm/cluster_k8s/__init__.py

It doesn't support regex, so, use required substring directly.
Without this fix there are following false negative error SCT events:
```
2023-09-17 01:19:09.355: (DatabaseLogEvent Severity.ERROR) \
period_type=one-time event_id=2babd5ad-8d7a-4477-81d5-df5f95c91cb1: \
type=RUNTIME_ERROR regex=std::runtime_error line_number=9572 \
node=sct-cluster-dc-1-kind-3
E0917 01:19:06.376388  1 sidecar/controller.go:143] \
syncing key 'scylla/sct-cluster-dc-1-kind-3' failed: \
[can't sync the HostID annotation: \
local host ID "65530c5c-58a7-4766-8dbb-e8de64dfea04" not found in \
IP to hostID mapping: map[10.96.118.89:7c4f28f7-3636-4ca1-9178-a3761d11fae6 \
10.96.222.2:8ed17a3d-5626-4708-9ea8-410570d358a2 \
10.96.240.199:95e2dd13-d87a-4403-858b-c4074c797c85], \
can't decommision a node: can't …
```

fix(k8s): fix decommission DB event filter for K8S

---

sdcm/remote/kubernetes_cmd_runner.py
sdcm/utils/common.py

The `test_add_new_node_and_check_old_nodes_are_cleaned_up` K8S functional test has race condition where it may fail with the following error:
```
Command: 'kubectl cp /tmp/tmpj8_823ao.yaml scylla/sct-cluster-dc-1-kind-0:/tmp/tmpj8_823ao.yaml -c scylla'
Exit code: 2
Stderr:
tar: tmpj8_823ao.yaml: Cannot open: File exists
tar: Exiting with failure status due to previous errors
command terminated with exit code 2
```
It is caused by the concurrent `cqlsh` cmd calls to the same Scylla pods. In this test there are about 7 concurrent such calls equal to the number of keyspaces in Scylla.
So, fix it by using lock mechanism per each pod.

fix(k8s): add class providing key based locks and use it for K8S

---

defaults/test_default.yaml
sct.py
sdcm/provision/aws/utils.py
sdcm/sct_config.py
sdcm/sct_provision/aws/__init__.py
sdcm/sct_provision/aws/cluster.py
sdcm/sct_provision/aws/instance_parameters_builder.py
sdcm/sct_provision/aws/layout.py
sdcm/utils/common.py
test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
vars/perfRegressionParallelPipeline.groovy

backport into perf-v14  for  https://github.com/scylladb/scylla-cluster-tests/pull/6594 and https://github.com/scylladb/scylla-cluster-tests/pull/6571
this commit is:
1) Include provision step into the performance pipeline 2) Add the ability to create load and DB instances within one AWS placement group and config parameter to enable this feature
3) Update i4i Throughput perf test to  use the new feature 4) extend sct.py 'list-resources', 'clean-resourses' to support AWS placement groups

[backport]feature(aws): placement group create/list/delete

---

sdcm/sct_runner.py

In Scylla Cloud staging environment, for security's sake, we have an allocated pool of public IPs for the runners.  If we fail to get an IP due to an empty pool then the cleanup script used to fail since it tried to execute a command via SSH using a public IP.

fix(sct_runner): don't call ssh_run_cmd during cleanup if there is no public IP

---

sdcm/nemesis.py

this is kind of cherry-pick from same fix
on master #6557.
original commit message is:
fix(nemesis.py): Use apt to install stress-ng on ubuntu
Since stress-ng snap was taken down by Canonical for some reason this commit removes the snapd installation and replaces stress-ng install to main ubuntu repositories.
Closes scylladb#6555

fix(stress-ng): install the correct way

---

test-cases/performance/perf-regression-latency-1TB.yaml

enable use placement group option for latency performance tests

test(perf): use placement group in latency performance test

---

configurations/disable_cluster_health_check.yaml
jenkins-pipelines/perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
performance_regression_test.py
sdcm/report_templates/results_latency_during_ops_short.html
sdcm/results_analyze/__init__.py
sdcm/send_email.py
sdcm/tester.py
test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
upgrade_test.py
vars/perfRegressionParallelPipeline.groovy

used as base the acceptance criteria latency test,
the latency during operations, with 650GB dataset,
this test will run as the "operations" a rolling upgrade
on all the nodes.
currently it has the default of the base test (3 nodes)
on a single DC and same region. (more to be added).
QA-Task is https://github.com/scylladb/qa-tasks/issues/1191

test(latency during upgrade): based on other latency test

---

functional_tests/scylla_operator/test_functional.py

In the `test_add_new_node_and_check_old_nodes_are_cleaned_up` K8S functional test we use utilitary CQL queries which just create noise in DB logs to make our log reader move on fast enough. And those queries may timeout from time to time.
We don't really care whether they timeout or not while some of them pass.
So, ignore those queries errors.
Also, increase the client timeout from `10` to `60` seconds to reduce number of failed queries.

fix(k8s): make the `cleanup` test be more stable

---

sdcm/cluster_azure.py
sdcm/provision/azure/provisioner.py
sdcm/provision/azure/virtual_machine_provider.py
sdcm/provision/provisioner.py
unit_tests/lib/fake_provisioner.py
unit_tests/provisioner/fake_azure_service.py
unit_tests/provisioner/test_provisioner.py

When triggerring reboot using Azure `begin_restart` SDK it is not rebooted immediately, but rather sheduled for reboot in future. This future for us is too far causing timeouts and broken nemesis logic.
Fix is about running `reboot -f` command instead of `begin_restart` method. This is done by Azure `run_command` API.
Enchanced also provisioner API with running commands possibility as this was required anyway for above change.

fix(azure): fix reboot delay

---

sdcm/cluster.py
unit_tests/test_scylla_yaml_builders.py

In Scylla the support of the `experimental` option was dropped.
But the `scylla-machine-image` project has bug [1] where it always defines that config option.
So, workaround it by explicitly removing that option from the `scylla.yaml`.
[1] https://github.com/scylladb/scylla-machine-image/issues/484

fix(cluster.py): remove 'experimental' config option from scylla.yaml

---

test-cases/artifacts/docker.yaml

Found that we don't have node's logs for Docker artifacts test :( It's not really critical, but it's better to have it.
There is a fix.

fix(artifacts): use default logs_transport for Docker test

---

sdcm/provision/azure/virtual_machine_provider.py

the `_get_scylla_storage_profile` function was overriding the `storage_profile` part, and dropping all the `os_disk` configuration.
it's now defaulting to `StandardSSD_LRS`, since we are standard instances for runners.
Ref: https://learn.microsoft.com/en-us/azure/virtual-machines/disks-types
Fixes: #6614

fix(azure): Creating instances didn't respected `disk_size`

---

sdcm/nemesis.py

When there's very little time (<500ms) from cql to audit message in logs it happens that audit line can be missed.
Added 5 seconds margin to time we start to observe audit messages.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6619

fix(nemesis): fix time skew in reading audit logs

---

sdcm/provision/azure/virtual_machine_provider.py
unit_tests/provisioner/fake_azure_service.py

since those agents are enabling auditd, which in turn spams our logs with information we don't need
Fixes: https://github.com/scylladb/scylla-enterprise-machine-image/issues/63

fix(azure-vm): disable azure agents

---

sdcm/cluster.py

The change is presented in https://github.com/scylladb/scylla-cluster-tests/pull/6566/commits/ e49c4f4bc1c524a348fa888eed84faebd4aeb63a added '--developer-mode' scylla argument for t3.micro artifact test.
But later '--developer-mode' agrument was added to be default by https://github.com/scylladb/scylla-machine-image/pull/482.
As result
https://jenkins.scylladb.com/job/enterprise-2023.1/job/artifacts/job/artifacts-ami-t3_micro-test/ fails with error:
```
scylla[4265]: FATAL: Exception during startup, aborting: boost::wrapexcept<boost::program_options:: multiple_occurrences> (option '--developer-mode' cannot be specified more than once)
```
Remove '--developer-mode' arg.

fix(artifact test): remove 'developer-mode' arg for t3.micro

---

sdcm/nemesis.py
sdcm/tester.py
test_lib/compaction.py

SCT code was abusing the fact scylla wasn't checking, and is passing some parameters regardless if they how supported
now it is fixed for sstable_size_in_mb parameter and get_compaction_random_additional_params function

fix(compaction_params): pass only supported params

---

sdcm/cluster.py
sdcm/nemesis.py
sdcm/sct_events/group_common_events.py
sdcm/utils/raft/__init__.py

Decommission could take different time depend on instance, size of dataset
number of nodes. Decommission streaming error randomly choose log line after
which decommission process should be aborted. Default timeout to wait
log message could be not enough to wait for messages from the end of
decommission.
Split messages for start and end process and return with method
the expected timeout.
Issue #6627
Issue #6181

fix(raft_operation): Timeout for log message depend on appearence in log

---

mgmt_cli_test.py

- [ X] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ X] I didn't leave commented-out/debugging code
- [ X] New configuration option are added and documented (in `sdcm/sct_config.py`)

fix(manager_cli): extend timeout on test_restore_backup_with_task

---

sdcm/tester.py

There are timeouts errors during repair of system_auth when setting system_auth during node setup. Looks like repair freezes (db log hang for 20m on repair roles table).
Because it was never recommended to run this repair in parallel (but should not affect either). Removing parallelism so we can exclude this as a root cause of freezing repair of system_auth table.

fix(set_auth_rf): remove parallelism

---

sdcm/cluster.py
sdcm/cluster_k8s/__init__.py
sdcm/stress_thread.py
sdcm/utils/remote_logger.py

Main driver for this rework are false failures of some nemeses in ScyllaDB Cloud longevities which shutdown nodes. 
Like:
```
File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 69, in wait_for
res = retry(func, **kwargs)
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
do = self.iter(retry_state=retry_state)
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
raise retry_exc.reraise()
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 194, in reraise
raise self
tenacity.RetryError: RetryError[<Future at 0x7f55642bcfa0 state=finished returned bool>]
The above exception was the direct cause of the following exception:
Traceback (most recent call …
```

Fixes for CloudReplaceNonResponsiveNode: improve SSH-based loggers and .terminate_node() method

---

sdcm/utils/syslogng.py

set millisecond resolution
in syslog-ng configuration

fix(syslog): set millisecond resolution

---

sdcm/cluster_k8s/mini_k8s.py

The `1.11.0-rc.0` scylla-operator has new logic for init containers of Scylla pods
which don't work [1] when we cache the scylla-operator's image.
So, do not cache it till the bug [1] gets fixed.
[1] https://github.com/scylladb/scylla-operator/issues/1448

fix(k8s-local): stop caching the scylla-operator docker image

---

defaults/k8s_local_kind_config.yaml

The K8S version we use in the `KinD` tool is pretty old - `v1.25`.
Default `Scylla` and `Scylla-manager` versions are also not the most recent ones.
So, update of it.

improvement(k8s-local): use latest versions for K8S and Scylla

---

sdcm/utils/get_username.py

When `BUILD_USER_ID` contains `[]` (e.g. for dependabot user which is `dependabot[bot]` then creation of EKS cluster fails due to forbidden characters in tags.
Fix by removing `[` and `]` from `user_id` returned by `get_username()` function.
fixes: #6661

fix(user_id): fix tag name when BUILD_USER_ID contains braces

---

sdcm/cluster_azure.py
sdcm/provision/azure/virtual_machine_provider.py
unit_tests/provisioner/fake_azure_service.py

Recently we disabled Azure Extension Operations which is required for
running efficient reboots (using azure agent).
Enabling it back, and workaround `auditd` issue by disabling and masking
it (so it can't be enabled).
fixes: #6656

Enable azure extension operations back

---

test-cases/scylla-operator/kubernetes-platform-upgrade.yaml

for gke platfrom upgrade we should start with a lower version then available (currectly 1.26)

fix(gke-upgrade): configure the correct k8s base version

---

sdcm/nemesis.py

Running `disrupt_drain_kubernetes_node_then_replace_scylla_node` nemesis we get following false error event:
```
2023-10-08 05:09:55.731: (DatabaseLogEvent Severity.ERROR) \
period_type=one-time event_id=<foo-id>: type=DATABASE_ERROR \
regex=(^ERROR|!\s*?ERR).*\[shard.*\] line_number=3869 \
node=sct-cluster-2-us-east1-b-us-east1-1
ERROR 2023-10-08 05:09:54,352 [shard 0:main] \
init - Startup failed: seastar::gate_closed_exception (gate closed)
```
It is expected because we `replace` a Scylla pod which is in the `init` phase after disruption.
So, just filter this error event out in this nemesis.
It is complementary to the following PR: https://github.com/scylladb/scylla-cluster-tests/pull/6533

fix(k8s): make `replace` op after disruption not raise false errors

---

functional_tests/scylla_operator/pytest.ini

Some of the pytest markers we use are absent in the `pytest.ini` config file.
So, update the config with the missing ones to avoid following warnings:
```
PytestUnknownMarkWarning: Unknown pytest.mark.required_operator - is \
this a typo?  You can register custom marks to avoid this warning - for \
details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.required_operator("v1.10.0")
```

fix(k8s-functional): update `pytest.ini` to contain all the markers we use

---

jenkins-pipelines/longevity-100gb-4h.jenkinsfile

last ~10 builds are failing to acquire resources
in the current AZ:
```
An error occurred (InsufficientInstanceCapacity) when calling the
RunInstances operation (reached max retries: 4): We currently do
not have sufficient i4i.4xlarge capacity in the Availability Zone
you requested (us-east-1a)
```
this is a try to have it working using the current trigger mechanism, but changing the AZ to be able to get this test working.

fix(longevity 4h): move default to new AZ

---

sdcm/logcollector.py

It was requested from dev team to support ms precision in db logs.
Adding `-o short-precise` to collection command that does the job.
fixes: #6682

improvement(log-collector): add ms precision to scylla logs

---

test-cases/artifacts/centos8.yaml
test-cases/artifacts/debian10.yaml
test-cases/artifacts/ubuntu2004.yaml
test-cases/artifacts/ubuntu2204.yaml

It happens we don't have capacity in default AZ for arm artifact tests.
Add `aws_fallback_to_next_availability_zone: true` to test configurations.
fixes: #6684

fix(artifact-test): fallback to next az in arm tests

---

jenkins-pipelines/longevity-user-profile-d.jenkinsfile
longevity_sla_test.py
sdcm/sct_config.py
sdcm/stress_thread.py
sdcm/utils/user_profile.py
test-cases/longevity/longevity-user-profile-d.yaml
test_lib/sla.py

Add new longevity with specific custom payload
which allow to reproduce issue scylladb/scylladb#12562
Specific keyspace defined in c-s profile yamls.
C-s run payload run under specific user. Specific
user is added using sla utils. If scylla is OSS, then
just roles will be added and c-s will run with defined
role, if scylla is enterprise, then  full WLP will
be used.
task: https://github.com/scylladb/qa-tasks/issues/974

test(custom_profile_d): Longevity with custom_d profile

---

sdcm/cluster.py

In one of our daily runs, the method failed due to a timeout, which caused the entire run to fail. To prevent it from happening in the future, I added a retry.

fix(is_port_used): Added retry to remote command execution

---

sdcm/cluster_aws.py
sdcm/ec2_client.py
test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml

now if the use_placement_group parameter is true and placement group was created during the provision step all nemesis that does "add node"
will request aws instance
with GroupName parameter
task: https://github.com/scylladb/qa-tasks/issues/1465

test(perfor): add use_placement_group into nemesis

---

jenkins-pipelines/perf-regression-throughput-baremetal-example.jenkinsfile
sdcm/cluster_baremetal.py
sdcm/keystore.py
sdcm/node_exporter_setup.py
sdcm/provision/common/utils.py
sdcm/sct_config.py
sdcm/tester.py
test-cases/performance/perf-regression-throughput-baremetal-5gb.yaml
unit_tests/test_config.py
vars/getCloudProviderFromBackend.groovy

This commit fixes some issues regarding bare metal instances -
specifically it fixes setup for loader and monitor nodes, adds a new
keystore method to retrive bare metal cluster information instead of
storing it in the test case and fixes syslong-ng setup script to make
sure it reinstalls if it's present - to make repeated runs possible as
previously it would just do nothing and syslog-ng would transfer logs to
an old sct runner instead. Some similar fixes for prometheus and
scylla_setup scripts to make sure we can run them multiple times on the
same instance.
Task: scylladb/qa-tasks#1233

improvement(test-cases): Add bare metal performance test

---

unit_tests/test_base_version.py

Recent Scylla got new branch - `5.4`
So, it became `master` version which caused our
`TestBaseVersion.test_master` unit test to fail with the following error:
```
AssertionError: Lists differ: ['5.4'] != ['5.3']
```
So, fix it by making the test expect the `5.4` version.

fix(unit-test): update TestBaseVersion.test_master to be `5.4`

---

sdcm/exceptions.py
sdcm/wait.py
unit_tests/test_wait.py

During prepare new nemesis BootstrapStreaming error, for some case it is need to stop wait_for function ealier and don't wait whole timeout
example when you expect that bootstrap will failed and you can find appropriate error in log, but not need to raise any exception or critical event, wait for db up will continue to wait while port will be available
For such case it will be good to have flag, if it is set, than stop wait_for function
- ~[ ] New configuration option are added and documented (in `sdcm/sct_config.py`)~
- ~[ ] I have updated the Readme/doc folder accordingly (if needed)~

fix(wait_for): Support stop wait_for by event

---

sdcm/provision/common/utils.py

when syslong-ng need to be reinstalled, sometimes it doen't created the syslog-ng.conf as expected
so we need to purge all syslog-ng packages out of system first, not just the main one.
Fixes: #6703

fix(install_syslogng_service): clear all syslog-ng packages

---

sdcm/provision/helpers/certificate.py

since we are using relative path, we might run into the following error, cause some code migt change the current direcotry:
```
Exit code: 1
Stdout:
Stderr:
+ '[' -z '' ']'
+ return
+ case $- in
+ return
+ mkdir -p /home/scyllaadm/.cassandra/
+ cp /tmp/ssl_conf/client/cqlshrc /home/scyllaadm/.cassandra/
cp: cannot stat '/tmp/ssl_conf/client/cqlshrc': No such file or directory
```
to be on the safe side, abspath should be used

fix(install_client_certificate): use absolute path, and not relative

---

utils/get_supported_scylla_base_versions.py

since version 5.3 was skipped, and won't be suppported we shouldn't ever upgrade from it in rolling upgrades
(for some time we we doing upgardes from 5.3-rc1, when we shouldn't have)

fix(rolling-upgrade): don't upgrade from 5.3 versions

---

sdcm/cluster_k8s/__init__.py

This release has the bugfix for the following bug:
https://github.com/scylladb/k8s-local-volume-provisioner/issues/21

improvement(k8s): use `0.2.0-rc.0` for `k8s-local-volume-provisioner`

---

configurations/operator/functional-eks.yaml
jenkins-pipelines/operator/functional/functional-eks.jenkinsfile

We use default value as `i4i.4xlarge`.
It is not needed in case of the functional tests.
So, use much smaller instance type `i4i.xlarge` in this case.

improvement(K8S): use smaller instance type on EKS running func-l tests

---

configurations/disable_cluster_health_check.yaml
configurations/perf-regresssion-upgrade.yaml
jenkins-pipelines/perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
performance_regression_test.py
sdcm/results_analyze/__init__.py
sdcm/tester.py
test-cases/performance/perf-regression-latency-650gb-grow-shrink.yaml
test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml

as other perf test cases, we want some degree of control on the email report subjects, so we can tell between the test cases we have.
now each case can define how the test would be shown in emails

fix(perf-latency): use `email_subject_postfix` for subject

---

defaults/gce_config.yaml
docs/configuration_options.md
sdcm/cluster.py
sdcm/sct_config.py

Use a custom script to replace Scylla perftune.py,
That configures a hybrid RAID-1, using mdadm devices.
This PR is dependant on https://github.com/scylladb/scylla-qa-internal/pull/30
Task: https://github.com/scylladb/qa-tasks/issues/21
[Test plan](https://docs.google.com/document/d/1omGkONrwtm165_8fWf8r8-_gMl9753TW9uII8P4tjDI/edit?usp=sharing)

improvement(node setup): Configure a hybrid RAID on GCE

---

sdcm/microbenchmarking.py

Recently cpu settings were changed for microbenchmark tests: https://github.com/scylladb/scylla-pkg/pull/3618
Because of that, historical perf results are not relevant.
Switch ES index so we make comparisons to results with the same CPU settings.

fix(microbenchmark): switch ES index

---

docker/env/version
requirements.in
sdcm/tester.py

This commit adds a way for SCT to submit gemini results to argus.
The results are collected during email data phase, with information
mirroring that of the email and additionally submitting the gemini seed
used.
Task: scylladb/qa-tasks#1481

feature(argus): Gemini integration

---

test-cases/cdc/cdc-15m-replication-gemini.yaml
test-cases/cdc/cdc-15m-replication-postimage.yaml
test-cases/cdc/cdc-15m-replication-preimage.yaml
test-cases/cdc/cdc-15m-replication.yaml
test-cases/cdc/cdc-replication-longevity.yaml
test-cases/features/dns-cluster-5min.yaml
test-cases/gemini/gemini-1tb-10h.yaml
test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-3h-with-nemesis.yaml
test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-basic-3h-ics.yaml
test-cases/gemini/gemini-basic-3h.yaml
test-cases/performance/ycsb/perf-base.yaml
unit_tests/test_data/test_scylla_yaml_builders/cdc-replication-longevity.yaml

This reverts commit 6e3d34cd1b9fc6533a4e5a3874fd36ad401b9a81.
The reverted commit in question breaks gemini jobs, as the currently used AMI 
for oracle nodes does not support the instance types in question, failing at 
node_setup stage with
```
2023-10-23T11:47:59.434+00:00 gemini-with-nemesis-3h-normal-argus-oracle-db-node-4709e913-1      !ERR | scylla[12015]:  [shard 0] init - Startup failed: std::runtime_error (Bad I/O Scheduler configuration)
```

Revert "improvement(gce): change `instance_type_db_oracle:` for gemini tests"

---

Jenkinsfile
sdcm/sct_config.py
vars/byoLongevityPipeline.groovy
vars/cdcReplicationPipeline.groovy
vars/checkoutQaInternal.groovy
vars/jepsenPipeline.groovy
vars/longevityPipeline.groovy
vars/managerPipeline.groovy

since it gonna be quite easy to have mistakes with this configuration since files it's gonna use span across multiple repos we are adding a validation a the very read of configuration to fail as fast as we can if those are missing.

feature(sct_config): add validation for `scylla_d_overrides_files`

---

functional_tests/scylla_operator/test_functional.py
sdcm/cluster_k8s/__init__.py
sdcm/utils/k8s/chaos_mesh.py

We have bunch of places where we create K8S namespaces. 
So, make a common method that will do it in a safe way and reuse it. 
It will also reduce the code in place of usage where we should check a namespace for existence.

improvement(k8s): add `create_namespace` method to KubernetesCluster

---

sdcm/cluster.py

hybrid disk setup should always go along with the duplex feature otherwise we'll have request timeout, cause the quoue is shared between read and write

fix(gce_setup_hybrid_raid): default to use duplex

---

defaults/manager_persistent_snapshots.yaml
sdcm/nemesis.py

since enterprise has an in-memory feature that
is not avaiable on OSS, we got a restore failing
on `malformed_sstable_exception`:
```
Column in_memory missing in current schema
```
Fixes: scylladb/scylladb#15846

fix(nemesis.py): restore only OSS snapshots on OSS

---

sdcm/cluster_k8s/gke.py

One of the recent PRs (https://github.com/scylladb/scylla-cluster-tests/pull/6731) made the K8S python logic use the `region_name` attribute of the K8S python class.
But it is not set in case of the GKE setups.
As a result, Scylla pods fail to be provisioned due to it.
So, fix it by setting the `region_name` also in the GKE case.

fix(k8s-gke): define missing `region_name` attr

---

sdcm/cluster.py

we saw on few runs of 5.4 that some of the jobs
(offline and regular) artifacts (on debian OSes)
failing while installing dependency packages.
Fixes: scylladb/scylladb#15878

fix(cluster): node setup - install package wait for package manager

---

configurations/arm/debian10.yaml
configurations/arm/ubuntu2004.yaml

since we have multiple issue with stability realted to package installtion, we are update the base images to latest for the arm artifacts tests
Ref: https://github.com/scylladb/scylladb/issues/15878
Ref: https://wiki.debian.org/Cloud/AmazonEC2Image/Buster
Ref: https://cloud-images.ubuntu.com/locator/ec2/

fix(arm-artifacts): update base images

---

sdcm/cluster.py

it is happening on master, and most likely because of the package manager is busy, and since, failing.
we futurely need to hardening it, and change
all calls that install packages to use
the wrap function `node.install_package()`,
as it has built-in a mode to wait for the package
manager, other than lucky.
Refs: https://github.com/scylladb/scylla-cluster-tests/pull/6740#issuecomment-1787088522

fix(cluster): install_scylla failing on debian based OS

---

sdcm/utils/common.py
sdcm/utils/user_profile.py

Search for user profile full path under SCT folder on a runner. It supports to search for SCT local user profiles and scyll-qa-internal profiles

improvement(user profile): change sdcm.utils.get_profile_content

---

vars/perfRegressionParallelPipeline.groovy

when it is not needed.
for now, we are calling it for every test, but when we don't have the `new_scylla_repo` param, we are not passing anything to that function, making it fail
to fulfill its signature.

fix(perfRegression pipeline): don't call supportedUpgradeFromVersions

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py
sdcm/cluster_k8s/gke.py
sdcm/cluster_k8s/mini_k8s.py
sdcm/logcollector.py
sdcm/tester.py
sdcm/utils/common.py
sdcm/utils/gce_utils.py
sdcm/utils/k8s/__init__.py

SCT runner must be able to talk to multiple K8S clusters in the multiDC setups.
So, update the kubectl and helm code to be smart enough to work with separate kubeconfig files.

improvement(k8s): add support of the multiple kubeconfig files

---

sdcm/cluster.py

we need to edit a remote file, an we used a docker image of yq for that.
changing it to use SCT `remote_file` context manager
Fixes: #6743

fix(monitor-setup): stop using `mikefarah/yq` docker

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py
sdcm/cluster_k8s/gke.py
sdcm/cluster_k8s/mini_k8s.py
sdcm/nemesis.py
sdcm/utils/k8s/chaos_mesh.py
sdcm/utils/remote_logger.py
unit_tests/test_chaos_mesh.py

Each pod always has `1:1` mapping with a K8S cluster.
Running in a multiDC environment we need to switch between K8S clusters easily.
So, add `k8s_cluster` attribute to all pod python classes and use it where possible
to minimize further changes adding support for multiDC setups.

improvement(k8s): assign and use `k8s_cluster` attr for node/pod objects

---

sdcm/nemesis.py

`verify_initial_inputs_for_delete_nemesis` wrongly assumes `partitions_attrs` isn't None.
as part of #6576 `partitions_attrs` was introduced, and seems to be test only with cases that have the correct configurations, and not with ones using s-b, and without the configuration realted to range deletes
Ref: #6576

fix(nemesis): fix verify_initial_inputs_for_delete_nemesis

---

sdcm/cluster.py

Since we can have those unattanded services doing things in the background while trying to use apt-get, we also want those disabled on monitor and loader nodes.

fix(monitor): call `disable_daily_triggered_services` on all node types

---

sct.py
sct_ssh.py
sdcm/cluster_gce.py
sdcm/utils/common.py
sdcm/utils/gce_utils.py

with this change we can now the following commands:
```
hydra ssh --user `whoami`
hydra ssh-cmd rolling-upgrade--ubuntu-focal-db-node-6e9857ea-0-3 ls /
hydra tunnel --test-id 1234-1234-1234-1234
```

feature(hydra-ssh): support gce on ssh/tunnel command

---

sdcm/cluster.py

since this is a workaround, and not a proper
fix, it was missing a comment about it,
to futurely allow us to come back to this
change and remove it.
Refs: #6740

fix(cluster): add missing comment to #6740

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py
sdcm/cluster_k8s/gke.py
sdcm/cluster_k8s/mini_k8s.py
sdcm/cluster_k8s/operator_monitoring.py
sdcm/utils/k8s/__init__.py
sdcm/utils/k8s/chaos_mesh.py
unit_tests/test_chaos_mesh.py
unit_tests/test_utils_k8s.py

We have lots of log messages which assume we have just one K8S cluster.
It becomes a problem if we run multiple K8S clusters setup.
So, add `region_name` prefix to bunch of K8S-related loaders to ease debugging.

improvement(k8s): use region_name as label in loggers

---

data_dir/scylla-dash-per-server-nemesis.2021.1.json
data_dir/scylla-dash-per-server-nemesis.master.json
sdcm/db_stats.py

After all nodes in cluster are updated from 2021.1 to 2022.1 and got new Scylla version, requests graph stops to report. It happens due to 'scylla_thrift_served' metric was removed beginnig from 2022.1 as it always is empty.
Remove 'scylla_thrift_served' from 2021.1 and master graph as not relevant

fix(dashboard): remove scylla_thrift_served metric

---

sct.py

jepsen job was not create, apart from the
`jepsen-with-raft`, that resides inside `raft`
folder, but is not relevant for newer releases,
since RAFT is already the default configuration.

fix(sct.py): add jepsen test to release jobs

---

sct_ssh.py

casue of copy-patse error in #6734, `select_instance_group` was returning one item, and not a list as intend.
and failing to get the instance region, since it was giving a key of a dict, and not the whole dict.
Fixes: #6764

fix(sct_ssh): `attach-test-sg` failed to handle one respone

---

sdcm/sct_events/group_common_events.py

During decommission_streaming_err next message could appear if decommission was aborted:
```
Nov 04 22:54:27.378538 longevity-twcs-48h-master-db-node-1e08af7e-3 scylla[39839]:
[shard 0:strm] node_ops - decommission[384e4830-3d66-4c17-853e-8406cd102a31]:
Operation failed, sync_nodes={10.4.11.231, 10.4.8.165, 10.4.8.201, 10.4.9.29}:
seastar::abort_requested_exception (abort requested)
```
Such message is not caught by ignore_stream_mutation_fragments_errors function.
Regexp was widened to catch similar messages.
Latest issue was found in JOB: longevity-twcs-48h-test
TestID: 1e08af7e-a630-460e-8fdd-c71ca75ad92b
Argus: scylla-master/longevity/longevity-twcs-48h-test#93
Issue https://github.com/scylladb/scylladb/issues/15630

fix(group_common_events): Expand regexp to filter more messages

---

sdcm/cluster.py

Reverts scylladb/scylla-cluster-tests#6746
this fix is not yet stable, and causing monitoring stack be wrongly configured
for now until figured out, we'll revert this change
#6757

Revert "fix(monitor-setup): stop using `mikefarah/yq` docker"

---

defaults/manager_persistent_snapshots.yaml
sdcm/nemesis.py

fix(nemesis): mgmt restore timeout
since #6733 we made changes to this nemesis
(because of OSS vs enterprise system under test
and snapshot versions), but the timeout is still
broken, and from the staging jobs, they did
not fully pass.
this last fix is to align the use of the
`wait_for` calls, where step and timeout
should work now.

fix(nemesis): mgmt restore timeout

---

sdcm/cluster.py
sdcm/remote/remote_file.py
unit_tests/test_remoter.py

since in some cases there's a process listing on changes
to this file, doing so with `mv` fails to continue the watch
on those files

fix(remote_file): write inplace into the file

---

sdcm/logcollector.py

For now, we put `cert_manager.log` file and other similar into the single destination dir even if we use multiple K8S. 
So, to avoid the harmful file rewriting, use only `DirLog` classes for log entities.
It becomes useful in multiDC (multi K8S clusters) setups.

fix(k8s): collect all the logs keeping the directories structure

---

unit_tests/dummy_remote.py
unit_tests/test_manual.py

`params` class attribute for `LoaderSetDummy` started to be required (due introduction of dns_names). Missing it is causing some integration tests to fail.
This commit adds `params` attribute to `LoaderSetDummy` class with empty content (as it's not required)

fix(integration-tests): fix LoaderSetDummy class

---

sdcm/provision/common/utils.py

We have problems with missing log lines when there's a flood from scylla log.
Increase buffer sizes so we syslogng survives log bursts.
fixes: #6689

fix(syslogng): increase buffer sizes

---

defaults/test_default.yaml
internal_test_data/cs_user_profile.yaml
jenkins-pipelines/upgrade_custom/rolling-sequential-upgrade-custom_d1.jenkinsfile
jenkins-pipelines/upgrade_custom/rolling-upgrade-custom_d1.jenkinsfile
sdcm/sct_config.py
sdcm/utils/loader_utils.py
test-cases/upgrades/customer-profile/rolling-upgrade-custom-d1.yaml
unit_tests/test_config.py
upgrade_test.py
vars/rollingUpgradePipeline.groovy

Rolling upgrade test for custom_d1. The goal is simulate main customers load and run rolling 
upgrade with it.
Two upgrade flows added:
- upgrade/rollback from one version to another
- sequential upgrade/rollback: 2021.1.23 -> 2022.1.23 -> 2023.1.1. It is temporary hardcoded 
solution. 
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/rolling_upgrade_custom_d1/33/
Failed with Scylla issue https://github.com/scylladb/scylla-enterprise/issues/3533

test(upgrade): custom_d1 rolling upgrade test

---

.pre-commit-config.yaml
utils/decode_kallsyms.py

since we collect kallsyms, and they are sometimes
needed to add valuable informatino to existing issues, i have created this tool to decode kernel callstacks from tests. it is not yet ready to be integrated
with some automatic decoded, but the content is ready to be used, as a standalone script for the now.

improvement(kallsyms decoder): add script that decodes kallsyms

---

jenkins-pipelines/longevity-large-partition-200k-pks-4days.jenkinsfile

since we are failing to run the test because of
lack of resources, and following the error message from EC2:
```
An error occurred (InsufficientInstanceCapacity) when
calling the RunInstances operation (reached max retries: 4):
We currently do not have sufficient c5n.4xlarge capacity in
the Availability Zone you requested (eu-west-1a). Our
system will be working on provisioning additional capacity.
You can currently get c5n.4xlarge capacity by not specifying
an Availability Zone in your request or choosing eu-west-1b,
eu-west-1c.
```
found this when running 5.4 job, and changing the
default AZ would allow the test to run better, without failing with lack of resources again and again.

fix(large-partition-200k-pk): Change default AZ

---

jenkins-pipelines/longevity-alternator-3h.jenkinsfile

since this test is running on `i4i.4xlarge` by default, and the availability for these instances on AZ `a` is minimal, as the following error shows:
```
(InsufficientInstanceCapacity) when calling the RunInstances
operation (reached max retries: 4): We currently do not have
sufficient i4i.4xlarge capacity in the Availability Zone you
requested (us-east-1a). Our system will be working on
provisioning additional capacity. You can currently get
i4i.4xlarge capacity by not specifying an Availability Zone
in your request or choosing us-east-1b, us-east-1c,
us-east-1d, us-east-1f.
```
moving the default to `c` did make the 5.4 job at least start, so sending this PR to change the default, to increase the chance of success.

fix(longevity-alternator-3h): set different default AZ

---

functional_tests/scylla_operator/conftest.py
functional_tests/scylla_operator/test_functional.py
longevity_operator_multi_tenant_test.py
sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py
sdcm/cluster_k8s/gke.py
sdcm/cluster_k8s/mini_k8s.py
sdcm/nemesis.py
sdcm/tester.py
sdcm/utils/operator/multitenant_common.py
unit_tests/test_utils__operator__multitenant_common.py

Do following changes to SCT to support multiple K8S clusters:
- Add new `k8s_clusters` attr to Tester python class.
- Start using that attr in the K8S provisioning methods.
- Add `k8s_clusters` attr to the Scylla cluster python classes.
- Update all the `add_nodes` methods with the possibility to use different `dc_idx` values.
- The `dc_idx` parameter becomes senseful.
- Update the `disrupt_nodetool_flush_and_reshard_on_kubernetes` nemesis to work correctly using the new approach.
- Update various K8S python methods to use new `k8s_clusters` attr.
What it doesn't do and what will be done in further changes:
- Specific K8S backends updates to be able to create 2+ K8S clusters.
- Scylla-manager update.
- Separation of all the K8S logs. For now `scylla-operator`, `scylla-manager`, …

feature(k8s): add general support for multiple K8S clusters

---

sdcm/tester.py

Current logic of region name pick up is following:
- `use "region_name" (aws) if defined else "gce_datacenter" (gce)`
And it gets done so for each of the backends.
So, fix it by using the 'cluster_backend' type for detecting which config option should be used.

fix(email_report): pick up proper region values for all backends

---

sdcm/cluster_k8s/__init__.py

Running a multiDC K8S setups we need to understand which region which loader belongs to as easy as possible.
So, add `region_name` value to the loader pods names.

improvement(k8s): use region_name in the loader pods names

---

sdcm/nemesis.py
sdcm/utils/common.py

`disrupt_snapshot_operations` nemesis fails with error: 'Snapshot content not as expected. ' It happens when the snapshot is taken for list of tables with command qith '-cf- parameter, like: 
`snapshot cqlstress_lwt_example -cf blogposts_update_one_column_lwt_indicator_expect,blogposts`
and the table has view(s).
It happens  after the https://github.com/scylladb/scylladb/commit/ad04f200d3b058a0ee27f0d4920ba02d487564d2 was merged but nemesis was not adjusted.
Now the Scylla automatically takes snapshot of views when snapping the base table. 
This fix adds related MVs to the expected result of snapshot
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6527

fix(nemesis): snapshot expected result should include view(s) of table

---

sdcm/cluster.py
sdcm/sct_config.py

We need to select specific version when using repo url as by default it is using always latest.
Added possibility to specify scylla version after a colon in `scylla_repo` param.
closes: https://github.com/scylladb/scylla-cluster-tests/issues/6722

improvement(installation): enable select version in repo

---

sdcm/nemesis.py
sdcm/sct_events/group_common_events.py

During drop SI in CreateIndexNemesis, next errors could happend on nodes:
```
[shard 11] view - Error applying view update to 10.12.10.61
(view: keyspace1.standard1_c0_nemesis_index, base token: -1446481564018001834,
view token: -1014392873274778199): data_dictionary::no_such_column_family
(Can't find a column family with UUID 4f2d7a10-d151-11ed-b247-2390a99b8089)
```
These errors could be expected as discussed in issue: scylladb/scylladb#12977
Change severity for such issues from Error to Warning.
fix scylladb/scylladb#12977

fix(disrupt_create_index): ignore apply view update errors

---

functional_tests/scylla_operator/test_functional.py

There is race condition which may cause following error:
```
assert pod_names_and_ips
>   assert len(pod_names_and_ips) == 3
E   AssertionError: assert 4 == 3
E    +  where 4 = len([\
'cleanup-t-podip-quasi-multidc-quasi-dc-2-rack-1-1-vd6kn   10.16.218.203', \
't-podip-quasi-multidc-quasi-dc-2-rack-1-0                 10.16.218.71', \
't-podip-quasi-multidc-quasi-dc-2-rack-1-1                 10.16.218.73', \
't-podip-quasi-multidc-quasi-dc-2-rack-1-2                 10.16.0.77'])
functional_tests/scylla_operator/test_functional.py:147: AssertionError
```
It is caused by the fact that `Scylla cleanup pods` also have the `scylla/cluster={cluster_name}` label.
So, fix it by adding one more label that is unique to Scylla pods.

fix(k8s): make quasi-multidc func test be more stable

---

sdcm/sct_events/setup.py

It was agree that those are not high severity, and we can ignore them for now, decided to global ignore those, and not try to apply the filter only the shutdowns.
Ref: scylladb/scylladb#15672

fix(events): ignore error with MV related error in shutdown

---

sdcm/cluster_k8s/__init__.py

Creating Scylla pods in the `add_nodes` method we wait only for the `Running` state of pods.
In this state Scylla pods are running and Scylla is only starting.
It is ok to do so in case of the single region,
because while a last Scylla pod is being bootstrapped we do other stuff
such as package installation and monitoring configuration.
But running the multiDC setup, it is not acceptable, 
because we create next DB members right after the last one is created in the first region.
As of now, we get following error in the multiDC setup:
```
ERROR 2023-11-02 09:56:21,418 [shard 0] init - Startup failed: \
std::runtime_error (Node 10.0.9.215 has gossip status=UNKNOWN. \
Try fixing it before adding new node to the cluster.)
```
So, fix it by waiting for the pod `readiness` in the `add_nodes` …

fix(k8s): wait for pods readiness in `add_nodes` method

---

sdcm/cluster_k8s/eks.py
sdcm/tester.py
sdcm/utils/common.py

List of changes:
- Add new function to the `eks.py` module which should be used for the creation of any new EKS cluster.
- Utilize that new function in the `tester.py` module creating K8S/EKS clusters.
- Use the `params.region_names` attribute of the Tester class instance to define the number of K8S clusters we want to create. It will be equal to the number of configured AWS regions in the `region_name` SCT config option.
- Update the `clean_clusters_eks` function in the `sdcm/utils/common.py` module with the region info.
Do it for ease of debugging.
What this change doesn't:
- CI job configuration. It is planeed to be added separately.

feature(k8s-eks): support multi K8S clusters creation (multiDC) in EKS

---

unit_tests/test_sct_events_file_logger.py

This change fixes an issue where a PR pipeline would randomly fail due
to a low teardown timeout.
Fixes #6747

fix(test_sct_events_file_logger): Increase thread timeout to 3 seconds

---

sdcm/nemesis.py

Make the `_disrupt_kubernetes_then_decommission_and_add_scylla_node` nemesis method
pick the latest Scylla pod in a rack only in the same region as the current target node.
It will allow us to avoid possible confusion in case of the debugging a failure in the multiDC setup.
Also, remove redefinition of the target node
in the `_disrupt_kubernetes_then_replace_scylla_node` nemesis method.

improvement(k8s): handle better the target node change in K8S nemesis

---

sdcm/cluster_k8s/__init__.py
sdcm/microbenchmarking.py
sdcm/remote/remote_base.py

While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [`__init__.py`](https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/cluster_k8s/__init__.py#L2649), there is a method that creates a temporary file using an unsafe API `mktemp`. The use of this method is discouraged in the [Python documentation](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp). iCR suggested that a temporary file should be created using `mkstemp` which is a [safe API](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp). iCR replaced the usage of mktemp with `mkstemp`.
- [POC - Improper Method Call - python - mktemp.mp4](https://drive.google.com/file/d/16YKuKgv7iItWcac2biRyi2Cm8upJ3HP_/view?usp=share_link)
- [MISC - Python - Taking a …

Fixed Improper Method Call: Replaced `mktemp`

---

artifacts_test.py

It was decided to not to set writeback cache setting in perftune, while we specifically verify this setting. This causes artifact test fail.
Idea is to disable this verification temporarily so it does not break artifact tests and enable it back when [the
change](https://github.com/scylladb/scylla-machine-image/pull/394) is merged.

test(artifact): disable writeback cache setting verification

---

test-cases/longevity/longevity-cdc-3d-400gb.yaml

Test duration for cdc 3days test is too short causing test to fail due timeout.
Prolong duration to match prepare + stress duration. From previous run, it was 6h from test start to stress_cmd start, so used 6+1h margin as a base for new duration.

fix(cdc-test): prolong test duration

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_azure.py
sdcm/cluster_baremetal.py
sdcm/cluster_docker.py
sdcm/cluster_gce.py
sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py
sdcm/cluster_k8s/gke.py
sdcm/sct_provision/region_definition_builder.py
unit_tests/test_scylla_yaml_builders.py

So now whom ever is calling the `.add_nodes()` can define a diffrent instance type
note: this change doesn't add any configuration option for holding those types, and doesn't do any check that they would fit the backend being used, that on the caller to select the correct types
Closes: #6796

feature(cluster): add `instance_type` to `add_nodes()` call

---

sdcm/cluster.py

Packages installation fail from time to time during node setup. Decided to add retrying for that.
Refs: https://github.com/scylladb/scylla-cluster-tests/issues/6317

fix(install packages): retry install packages when fail

---

unit_tests/test_base_version.py

test should expact that latest enterpise base version should 2024.1.0-rc0

fix(test_base_versio): 2024.1.0-rc0 is available

---

test-cases/upgrades/rolling-upgrade.yaml

we are still using the c-s inside the loader image, and that is an older version of c-s and java-drivers, so we try again to update it to work with the docker based ones.
after this, we might fix the c-s to a specific docker image of some release, to make sure it's the same version across the whole upgrade

fix(rolling-upgrades): switch to using docker based loaders

---

sdcm/utils/common.py

as part of libcloud removal in #6137 this function was really used, and it was missed it need to be adapted.
when using an old gce project when we have builders other than test runners we see this issue.

fix(get_gce_builders): get public ip correctly

---

sdcm/cluster_k8s/__init__.py
sdcm/logcollector.py

When scylla node is added after decommission on K8s it may get the same name. This leads to system.log being reused and reread by `DbLogReader` which in result duplicates log lines to sct.log and also generates events according to log lines from the past.
Fix is about renaming system.log after decommission so it is not reread. Also need to make log collector to find these decommissioned nodes logs.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6806

fix(decommission): move system.log when decommission

---

sdcm/utils/operator/multitenant_common.py

When creating multitenant cluster, `LongevityTest` init is not executed. This causes missing `validate_large_collections` class attribute for multitenant tester classes.
Fix by adding this param to proper init method.

fix(multitenant): fix missing validate_large_collections attr

---

sdcm/utils/aws_region.py

When running local tests with AWS backend, the driver cannot connect to shard-aware CQL port (19042) since it's not exposed during AWS security groups configuration.
The issue can be reproduced simply with https://github.com/scylladb/scylla-cluster-tests#run-test-locally-with-aws-backend.
NOTE: the reason this test fails may seem to be different, since logs tell us that `ALTER KEYSPACE` query is timed out. What happens is that the driver tries to open connections to shard-aware ports (with default SCT's connection timeout being 100s) which blocks the python driver's worker threads. It's clearly a python driver issue which hopefully will be fixed soon.
- Exposed shard-aware ports (both non-SSL and SSL) in AWS security group.

fix(aws): expose shard-aware ports

---

sdcm/cluster_k8s/__init__.py

Mainly we run K8S CI job with really small load.
Small load allows us to get Scylla pods up and running much faster than when we have big load.
So, increase the K8S pod readiness timeout from '5' to '10' to cover upcoming new CI jobs with bigger load.

improvement(k8s): use bigger K8S pod readiness timeout

---

sdcm/cluster.py

cause of refactoring done, there are some cases we get to this function and `gnupg2` isn't yet install.
we should make sure we install the needed things before using them.

fix(download_scylla_repo): install gnupg2 is before use apt key

---

sdcm/nemesis.py

once the restore nemesis is done, we don't have
any need or interest in keeping the keyspaces
created by this nemesis.
We have seen also in some specific runs, a different nemesis failing, while trying to access a specific keyspace created by this nemesis, and hence,
it should be completely remove.
Refs: #6790

improvement(restore nemesis): remove created keyspaces

---

sdcm/cluster_k8s/__init__.py

Before we were setting/updating the `externalSeeds` field for the `ScyllaCluster` objects of second+ regions each time before adding a new node.
It has following problems:
- At first we get redundant existing pods roll-out be triggered. It happens because podIP are ephemeral and Scylla pods of the first region change it with pretty big probability.
- Running any nemesis where we decommission a node from a second+ region and then add a new node we get LOCAL_QUORUM violation because of the roll-out which happens for 2 existing pods having LOCAL_QUORUM as `2`.
So, to avoid above problems, set the `externalSeeds` field value only spinning up the very first pod in each of the second+ regions. After it unset this value allowing all the following pods use existing local ones as seeds.

fix(k8s): make setting of seeds for K8S multiDC setup work correctly

---

sct.py
sdcm/sct_config.py
sdcm/utils/common.py
sdcm/utils/version_utils.py
utils/get_supported_scylla_base_versions.py

code was hard coded incorrectly, and was working only for master
and not for enterprise, nor releases
all the function related to this function where moved
to `sdcm.utils.version_utils` to avoid cyclic dependency.
we use this function to determinte where to look for docker
images in dockerhub, and now it's works for more options
like:
- master:latest
- enterprise
- enterprise:latest

fix(get_branched_repo): handle OSS/enterprise releases

---

sdcm/sct_config.py

recent change a13612a1a7344d1f93eeb3a40a180f96dfd4bd4e made a few configuration mandatory, but it didn't handle the offline installer case, i.e. when `unified_package` is defined insted of `scylla_repo`

fix(offline-install): don't expect `scylla_repo`

---

jenkins-pipelines/operator/eks/longevity-scylla-operator-multidc-12h-eks.jenkinsfile
jenkins-pipelines/operator/eks/longevity-scylla-operator-multidc-3h-eks.jenkinsfile
test-cases/scylla-operator/longevity-scylla-operator-multidc-12h.yaml
test-cases/scylla-operator/longevity-scylla-operator-multidc-3h.yaml

Add 2 CI jobs:
- 3h  using the `i4i.2xlarge` instance type for DB-specific pods
- 12h using the `i4i.4xlarge` instance type for DB-specific pods

ci(k8s-eks): add CI job configuration for the EKS multiDC setups

---

sdcm/cluster_k8s/__init__.py

Stop wrapping the `wait_for_pods_running` method and just start using proper `scylla-manager` pod selector to filter out all other pods.
It started being required after merge of https://github.com/scylladb/scylla-cluster-tests/pull/6785 where we added usage of the one more method - `wait_for_pods_readiness`.

fix(k8s): make scylla-manager pod waiter work correctly

---

utils/decode_kallsyms.py

new it can be called from commnadline as follow:
```
./utils/decode_kallsyms.py  -i ~/Desktop/system.log -k ~/Desktop/kallsyms_20231114_000857
```

feature(decode_kallsyms): add commandline options

---

sdcm/cluster.py

for older release which depends on python2, we still need to install it, and we keep on installing until it's not available anymore. (centos/rocky 9 and ubutnu 23.04 and above)

fix(offline-installer): bring back the install of python2

---

functional_tests/scylla_operator/conftest.py
functional_tests/scylla_operator/libs/helpers.py
functional_tests/scylla_operator/test_functional.py
sdcm/cluster_k8s/__init__.py
sdcm/tester.py

We use the `scylla_operator_chart_version` attr in lots of places, not only the K8S class instance itself.
So, make it be of the `public` type removing the need to disable the `protected-access` pylint rule.

improvement(k8s): make `scylla_operator_chart_version` attr be public

---

upgrade_test.py

we recently introduced code that does logic based on `node.scylla_version` at the end of the upgrade sequence, and it wasn't working as we expected, returning the base version.
we now in the upgrade sequence clear the cached for scylla_version related functions/attributes
Ref: https://github.com/scylladb/scylladb/issues/16147

fix(upgrade_test): forget the scylla_version after node upgrade

---

sdcm/sct_events/setup.py
unit_tests/test_events.py

PR #6793 introduce an ignore for print like:
```
[shard 3:stat] storage_proxy - exception during mutation write
to 10.12.0.219: std::runtime_error (view update generator not plugged to
push updates)
```
the regex wasn't really catching the print, the change fixes that and intoduce it into the unittest to verify it.
Ref: #6793
Ref: scylladb/scylladb#15672

fix(events-setup): fix regex for ignoring scylladb/scylladb#15672

---

test-cases/upgrades/multi-dc-rolling-upgrade.yaml
test-cases/upgrades/rolling-upgrade.yaml

The rolling upgrades test now runs many stress commands including c-s,s-b and gemini.
It seems that the memory is stressed on the loaders and we need to increase it.

Rolling upgrade fixes

---

upgrade_test.py

the logic to pick the correct sstable tool was branch version and cause of that wasn't covering correctly the release canidate versions

fix(rolling-upgrade): use correctly versions to cover rc versions

---

sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/eks.py
test-cases/scylla-operator/longevity-scylla-operator-multidc-12h.yaml
test-cases/scylla-operator/longevity-scylla-operator-multidc-3h.yaml

To make Scylla-Manager work in MultiDC K8S setups we should do following [1]:
- Install it only in one region
- Make Scylla pods use auth token from that the only scylla-manager.
So, do above changes and update the multiDC config files. Make 3h config write twice less data so the 'mgmt backup' could fit the 3h time range in case one wants to test it using that job.
[1] https://github.com/scylladb/scylla-operator/blob/master/docs/source/multidc/multidc.md#scylla-manager

fix(k8s): make mgmt work in K8S multiDC setup

---

sdcm/cluster_k8s/gke.py
sdcm/sct_config.py
sdcm/tester.py

Changes:
- Create `deploy_k8s_gke_cluster` function in the `gke.py` module that will be able to provision GKE clusters.
- Update the `gcloud` attr of the `GkeCluster` class to use `gce_zone` in the gcloud docker container name to be able to use multiple K8S clusters.
- Create `gce_datacenters` attr for the `params` object which will solve the same needs as `region_names` for AWS/EKS backends.
- Start respecting the `availability_zone` SCT config option. If not set then the `b` will be used as before. If set then apply.

feature(k8s): add MultiDC support to GKE backend

---

configurations/operator/multidc-gke-12h.yaml
configurations/operator/multidc-gke-3h.yaml
jenkins-pipelines/operator/gke/longevity-scylla-operator-multidc-12h-gke.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-multidc-3h-gke.jenkinsfile
test-cases/scylla-operator/longevity-scylla-operator-multidc-12h.yaml
test-cases/scylla-operator/longevity-scylla-operator-multidc-3h.yaml

Add `3h` and `12h` - the same way as we have it for EKS backend.

ci(k8s-gke): add MultiDC CI jobs

---

sdcm/cluster_k8s/__init__.py
sdcm/logcollector.py
sdcm/tester.py
sdcm/utils/k8s/__init__.py

In scylla-operator-v1.11.0 was added possibility to gather K8S logs by using it's binary.
It is required for support requests and bug reports.
So, add it's support here in addition to our main K8S gathering logic and save as a separate archive.

feature(k8s): add support for the `must-gather` operator command

---

test-cases/upgrades/rolling-upgrade.yaml

c6 is a typo it should be c6i, but c7i is more available in terms of spot, newer and has better performance for the same price.

fix(rolling-upgrade): Change rollling upgrades loader to c7i

---

sdcm/cluster.py
sdcm/node_exporter_setup.py

at some point we started using docker for running the node_exporter
on the monitoring machine, but since then we have implemented
installation of node_exporter for loader nodes.
we are switching to that, since the docker based options
seems to be unstable (since 2020 it was failing, and wasn't tracked)
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6861

fix(monitor): install node_exporter instead of using docker

---

data_dir/scylla-dash-per-server-nemesis.master.json
defaults/severities.yaml
defaults/test_default.yaml
docker/latte/Dockerfile
docker/latte/README.md
docker/latte/workloads/workload.rn
jenkins-pipelines/longevity-gce-custom-d1-hybrid-raid.jenkinsfile
sdcm/logcollector.py
sdcm/sct_config.py
sdcm/sct_events/loaders.py
sdcm/stress/latte_thread.py
sdcm/tester.py
test-cases/longevity/longevity-gce-custom-d1-hybrid-raid.yaml
unit_tests/test_config.py
unit_tests/test_latte_thread.py
unit_tests/test_stress_thread_functions.py

latte is a rust base stress tool that works with
scylla rust driver, it's claims to be fast and more effiect then cassandra-stress NoSQLBench, and tlp-stress.
the really nice thing about it is the  embedded scripting language it comes with, that can help make really customized user define loads and profiles
Ref: https://github.com/pkolaczk/latte

feature(loaders): introduce latte as stress command

---

sdcm/cluster.py

After backport of the https://github.com/scylladb/scylla-cluster-tests/pull/6759 PR to the `branch-5.2`
we started getting following error running Azure CI jobs and using the 'branch-5.2' branch:
```
Command: 'sudo docker pull scylladb/scylla:latest'
Exit code: 1
Stdout:
Stderr: sudo: docker: command not found
```
So, fix it by not running the `disable_daily_triggered_services` method when the Azure backend is used.
Fixes: #6859

fix(azure): do not run `disable_daily_triggered_services` on loaders

---

sdcm/cluster_k8s/__init__.py
sdcm/sct_events/setup.py
unit_tests/test_events.py

Since we have issues with doing this correctly on the specific place it might be happening, we'll ignore this one globaly
Ref: scylladb/scylla-cluster-tests#6119

fix(k8s): ignore decomission errors from operator agent logs

---

artifacts_test.py
sdcm/utils/adaptive_timeouts/load_info_store.py

From time to time we upgrade Node exporter, which is in charge of OS metrics from Scylla nodes.
Check that it's not dead on arrival.

improvement(artifact test): add check node exporter liveness

---

sdcm/logcollector.py
sdcm/utils/k8s/__init__.py

After adding of the scylla-operator's `must-gather logs` support (https://github.com/scylladb/scylla-cluster-tests/pull/6855) we started having partial duplication of it's logs in our own collected K8S logs due to the dir names (those which are used for filtering in `logcollector`) overlapping.
So, fix it by renaming the `namespaces` dir to the `namespace-scoped-resources` following the template used for the `cluster scoped` ones.

fix(k8s): make k8s log collectors not overlap in log dir names

---

sdcm/cluster_k8s/__init__.py

After merge of the `support of mgmt for K8S MultiDC setups` (https://github.com/scylladb/scylla-cluster-tests/pull/6844) The non-mgmt K8S setups started failing with following error:
```
File "sdcm/tester.py", line 1666, in get_cluster_k8s_eks
self.db_clusters_multitenant.append(eks.EksScyllaPodCluster(
File "sdcm/cluster_k8s/__init__.py", line 2501, in __init__
kwargs["s3_provider_endpoint"] = k8s_cluster.s3_provider_endpoint
File "sdcm/cluster_k8s/__init__.py", line 1494, in s3_provider_endpoint
return f"http://{self.minio_ip_address}:9000"
File "sdcm/cluster_k8s/__init__.py", line 1490, in minio_ip_address
return self.minio_pod.status.pod_ip
File "sdcm/cluster_k8s/__init__.py", line 1486, in minio_pod
raise RuntimeError("Can't find minio pod")
```
So, fix it by checking the `use_mgmt` …

fix(k8s): make `use_mgmt=false` work again for K8S

---

sdcm/cluster.py
sdcm/exceptions.py
sdcm/provision/scylla_yaml/scylla_yaml.py
sdcm/remote/libssh2_client/__init__.py
sdcm/tester.py
sdcm/utils/sstable/sstable_utils.py
unit_tests/test_scylla_yaml.py

using the feature from scylladb/scylla-enterprise#3389 when we have `scylla_encryption_options` configured with KMS we would enable the `user_info_encryption` and the `system_info_encryption` similar to who it would be working on scylla-cloud
Ref: scylladb/scylla-enterprise#3389

feature(EaR-kms): enable user encryption by default

---

defaults/k8s_gke_config.yaml
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-add-remove-rack.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-backup.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-cluster-rolling.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-grow-shrink.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-nodetool-flush-and-reshard.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-repair.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-replace.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-scylla-enterprise.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-stop-start.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-terminate-decommission-add.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-terminate-replace.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-basic-12h-gke-scylla-enterprise.jenkinsfile
jenkins-pipelines/operator/gke/longevity-scylla-operator-basic-12h-gke.jenkinsfile
jenkins-pipelines/operator/upgrade/upgrade-major-scylla-k8s-gke.jenkinsfile
jenkins-pipelines/operator/upgrade/upgrade-operator-k8s-gke.jenkinsfile
jenkins-pipelines/operator/upgrade/upgrade-platform-k8s-gke.jenkinsfile
jenkins-pipelines/operator/upgrade/upgrade-scylla-k8s-gke.jenkinsfile
vars/rollingOperatorUpgradePipeline.groovy

After merge of the `MultiDC support for GKE backend` PR (https://github.com/scylladb/scylla-cluster-tests/pull/6853) the SCT started respecting the `availability_zone` config option.
It led to the situation that we started getting following error:
```
ERROR: (gcloud.container.clusters.create) ResponseError: \
code=400, \
message=Specified location "us-east1-a" is not a valid zone in the cluster's region "us-east1".
```
It is caused by the fact that the default AZ was `a` and it is absent in the `us-east1` region.
So, fix this situation by explicitly setting the AZ for the GKE jobs.

fix(k8s-gke): set AZ explicitly as non-`a` for the `us-east1` region

---

data_dir/nemesis.yml
jenkins-pipelines/nemesis/longevity-5gb-1h-EndOfQuotaNemesis-aws.jenkinsfile
sdcm/exceptions.py
sdcm/nemesis.py
sdcm/sct_events/group_common_events.py
sdcm/utils/quota.py
test-cases/nemesis/longevity-5gb-1h-EndOfQuotaNemesis.yaml
unit_tests/test_nemesis.py
unit_tests/test_nemesis_sisyphus.py

According to task: https://github.com/scylladb/qa-tasks/issues/1086
This commit adds the possibility to configure quota on a node and adds the EndOfQuotaNemesis
The EndOfQuotaNemesis configures quota with current disk usage + 1GB and waits for `Disk quota exceeded` message in logs. Then the quota is cleared and scylla-server service is restarted.

feature(edquot): Add quota configuration and EndOfQuotaNemesis

---

sdcm/cluster.py
unit_tests/test_run_cqlsh.py

since some keyspace or table names might be with quotes we should escape them, before passing it to the cqlsh command line
Ref: scylladb/scylla-cluster-tests#6790
Fixes: #6878

fix(run_cqlsh): make sure we escape double quotes

---

Jenkinsfile

The priority for this feature got reduced.
So, stop using it for each CI job which covers github PRs.

ci(k8s): disable K8S `SNI/TLS` feature for the github PR testing

---

functional_tests/scylla_operator/test_functional.py

It happens that the deletion of a namespace
in the 'test_deploy_quasi_multidc_db_cluster' K8S functional test may hang and finally return non-zero code as follows:
```
Error executing command: "kubectl delete namespace t-podip-quasi-multidc"; Exit status: -9
STDOUT: namespace "t-podip-quasi-multidc" deleted
```
Logs show that namespaces in such cases really get deleted.
So, skip this kind of errors because it is not an issue for us and only noise.
Also, the namespace deletion in this test, if not hangs, takes about `10-12` seconds.
So, reduce the timeout from the `300s/5m` to `30s` to minimize wasted time.

improvement(k8s): stabilize `test_deploy_quasi_multidc_db_cluster` test

---

sdcm/cluster.py
unit_tests/test_run_cqlsh.py

Recently we merged PR (https://github.com/scylladb/scylla-cluster-tests/pull/6897) which fixed the escape quotes approach.
But it added another problem that if we have new lines of additional spaces
in the beginning or ending of the command then it doesn't filter it out making CQLSH fails with the syntax errors.
So, fix it by removing the redundant symbols calling the `strip()` string method.
Also, cover this change in unit tests.
Fixes: #6916

fix(run_cqlsh): make it work having new line and space symbols in cmd

---

sdcm/nemesis.py

The nemesis currently fails on non aws backends
Added a skip check
SCT issue ref: https://github.com/scylladb/scylla-cluster-tests/issues/6915

fix(quota): skip quota nemesis on not aws backends

---

sdcm/utils/sstable/load_utils.py

This is follow-up fix for the recently merged PRs (https://github.com/scylladb/scylla-cluster-tests/pull/6897) and (https://github.com/scylladb/scylla-cluster-tests/pull/6918).
We should not use multi-line strings defining cql commands, because any new lines in the middle of the string won't be removed and will cause following syntax errors:
```
Command: '/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60 \
-e "CREATE KEYSPACE keyspace1 WITH replication = \
{\'class\': \'NetworkTopologyStrategy\',\\n             \'replication_factor\': 3}"  10.16.254.197 9042'
Exit code: 2
Stdout:
Stderr:
<stdin>:1:Invalid syntax at char 82
<stdin>:1:  CREATE KEYSPACE keyspace1 WITH replication = \
{'class': 'NetworkTopologyStrategy',\n                'replication_factor': 3}; …
```

fix(sstables_utils): do not use multiline string defining cqlsh command

---

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml

validation is keep timing out on this use case, looks like it's reading too much
```
2023-12-02 14:59:58.509: (TestFrameworkEvent Severity.ERROR)
period_type=one-time event_id=9f0498a0-1588-4b5a-9b4d-7e013ada2705,
source=PartitionsValidationAttributes message=Failed to collect partition info.
Error details: Requested pages were not delivered before timeout.
Requested: 1; retrieved: 0; empty retrieved 0
```
for now we'll disable it for this use case, until further investigated as for the root, maybe this case is overloading already.
crashed on a known issue after 9 hours, but didn't see any of the other issue we had with the validation.

fix(large-partition-200k): remove partition validation

---

test-cases/longevity/longevity-large-partition-3h.yaml

Remove MV and SI creation during 'post-prepare-cql' as it may cause to index nemesis failure.
The problem that scylla_bench.test table has few columns for few indexes creation.
So post-prepare-cql or index nemesis (depend how was run first) may fail with error like:
```
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Index si_text is a duplicate of existing index test_v_nemesis"
```
Meanwhile it was decided do not perform full fix of the issue and just remove MV/SI creation from 'post-prepare-cql' section.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6565

fix(longevity): remove MV creation in large partition tests

---

sdcm/cluster.py

Recently merged PR (https://github.com/scylladb/scylla-cluster-tests/pull/6810) made the `install_scylla_debuginfo` node method retry in case of failures instead of using the `try-and-go` approach.
It leads to waste of time by having following timeouts:
```
Wait for: Checking if package manager is free: timeout - 60 seconds - expired
```
Cumulatively it leads to `Functional EKS tests` job timeout because those redundant waits take hours in summary.
The timeouts are caused, on it's turn, by the following error:
```
Running command "lsof /var/lib/dpkg/lock"...
/bin/bash: line 1: lsof: command not found
wait_for: Retrying Checking if package manager is free: attempt 2 ended with: False
```
So, fix it by installing the `lsof` package if absent to avoid redundant retries in case of it's …

fix(install_package): install `lsof` package before using it

---

sdcm/nemesis.py

as part of #6873, one verification thread, that was supposed to be after node decommission, we done after keyspace was dropped putting back the decommission part into the sequence, and that validation thread into the context as well.
Ref: #6873

fix(disrupt_add_remove_dc): put back c-s thread into context

---

sdcm/cluster_k8s/__init__.py

Make it be the latest available version `0.3.0-alpha.1` which also supports ARM processors.

improvement(k8s): bump the local volume provisioner version

---

sdcm/sct_config.py
sdcm/utils/aws_utils.py

replace the hardcoded list we have with actuall calls to ec2 to get the architecture of that instance type we are gonna use.

fix(get_arch_from_instance_type): get the actual architecture from aws

---

functional_tests/scylla_operator/test_functional.py

If something fails in the `test_deploy_helm_with_default_values` K8S functional test then we don't have anything to debug because the namespace gets deleted in any case.
So, fix it by detecting the need to save logs before we delete the namespace.
Use the same approach which we have in other couple of K8S functional tests.

fix(k8s): save logs in `deploy_helm_with_default_values` K8S func test

---

artifacts_test.py
longevity_test.py
performance_regression_row_level_repair_test.py
sdcm/fill_db_data.py
sdcm/utils/loader_utils.py

If a table is created with COMPACT STORAGE option, two 'ghost' columns 'column1' and 'value' are added to the columns' list in the system_schema.columns table. Issue: https://github.com/scylladb/scylladb/issues/16309
COMPACT STORAGE option will be deprecated: https://github.com/scylladb/scylladb/issues/12263
So it was decided that we should test COMPACT STORAGE in system tests, only functional tests. We should also deprecate it in new tables, and think about a migration path.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6680

fix(tables): remove COMPACT STORAGE from code

---

commitlint.config.js
sdcm/utils/aws_utils.py
unit_tests/test_config.py
unit_tests/test_ndbench_thread.py

since we have some tests that was counting on specific AMIs to exist and from time to time those are being depracated.
so we should be pointing to any specific one, we are now gonna query get latest scylla, or latest specific AMIs base on SSM paramters
[1]: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html#systems-manager-permissions
[2]: https://discourse.ubuntu.com/t/finding-ubuntu-images-with-the-aws-ssm-parameter-store/15507

fix(test_config): stop referencing real AMIs

---

sdcm/utils/common.py

currently if no region is defined, the kms cleanup breaks cause of: `raise ValueError("'region_names' parameter cannot be empty")`
adding the need change, so it would be able to work across all regions when needed

fix(sct.py): kms resoruces cleanup with all regions

---

sdcm/cluster_k8s/__init__.py
sdcm/k8s_configs/eks/scylla-node-prepare.yaml
sdcm/k8s_configs/gke/scylla-node-prepare.yaml
sdcm/k8s_configs/static-local-volume-provisioner.yaml

The Custom Resource Definition (CRD) called `NodeConfig` developed by the scylla-operator dev team is used to configure K8S nodes which are going to host Scylla pods.
It is able to configure SSD disks into RAID arrays. We were using it only running the dynamic local volume provisioner, but not the static one.
So, start using it for each of the volume provisioners we have. It will allow us to:
- Simplify existing code
- Stop using redundant pods - `scylla-machine-image` in EKS and `gcr.io/google-containers/startup-script` in GKE.
Also:
- Update the `bitnami/kubectl` image to be `1.26.11` that is the most recent one which supports `x86` and `ARM` architectures.
- Use much newer docker image for the `static local volume provisioner`. It also supports `x86` and `ARM` architectures.
- Update a …

improvement(k8s): reuse operator's `NodeConfig` for static vol provisioner

---

configurations/arm/eks.yaml
configurations/operator/functional-eks-arm.yaml
functional_tests/scylla_operator/test_functional.py
jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-arm.jenkinsfile
jenkins-pipelines/operator/functional/functional-eks-arm.jenkinsfile
sdcm/cluster_k8s/eks.py

Add following CI jobs configurations:
- Longevity K8S EKS 3h, full ARM
- Functional K8S EKS tests, full ARM
Also, update the EKS module by adding detection of the ARM instance types and selecting proper image for VM.

ci(k8s-eks): add ARM CI jobs configurations

---

docker/scylla-sct/ubuntu/Dockerfile

in PR #6888 we introduced the sshd configuration, but remove a part of the code the was ignoring the outcome of the sshd version check, hence when the condition failed, the docker build phase failed

fix(docker): handle correctly older sshd versions

---

test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
test-cases/scylla-operator/longevity-scylla-operator-many-clients-4h.yaml

two cases still had `k8s_enable_tls: true`, even that we don't want to use it until all of it's issues gonna be address

fix(k8s-multitenant): remove `k8s_enable_tls` from cases

---

sdcm/provision/common/utils.py

since we are sending the log directly to the sct-runner we don't need to have them duplicated into `/var/log/system.log` later SCT can take them from `journalctl` as needed.

fix(syslog-ng): remove log to local file

---

sdcm/tester.py

when we introduced enabling EaR KMS for all AWS enterpise runs, it broke running older enterpise versions, since they don't support KMS
scylla would fail like this:
```
[shard 0] init - Startup failed: std::invalid_argument (Unknown provider: KmsKeyProviderFactory)
```

fix(prepare_kms_host): enable kms only for supported versions

---

functional_tests/scylla_operator/test_functional.py

To avoid following false `timeout` errors:
```
Command: 'kubectl delete namespace t-podip-quasi-multidc'
Stdout:
namespace "t-podip-quasi-multidc" deleted
Stderr:
```
Which happen in the `test_deploy_quasi_multidc_db_cluster` K8S func test.

fix(k8s): ignore timeout error deleting quasi-milti-dc ns

---

sdcm/cluster_k8s/__init__.py
upgrade_test.py

Current `scylla-operator upgrade` logic doesn't check that
- The `ScyllaCluster` object gets upgraded right after the `scylla-operator`.
- The `status.conditions` doesn't have errors
- The `init` container of the Scylla pods are of the new version.
It was sleeping for 1 minute and waiting for the rollout to finish.
But if, for any reason, rollout doesn't start, the code picks up the old `rollout` state and moves on with the old `ScyllaCluster` K8S object state.
So, add proper checks to cover problems with the `ScyllaCluster` upgrades:
- Check that scylla pods get new `UID` values meaning they were recreated
- Read ScyllaCluster's `status.conditions` and look for Error's
- Check all the `scylla-operator` images to be of the new version.
Closes: #6943

fix(k8s): fix scylla-operator upgrade test

---

sdcm/tester.py

since the oracle is using older version of scylla, so it won't be supporting EaR KMS, we don't have a seperate configuration for the oracle so we aren't going to enable KMS in that case
Fixes: #6959

fix(prepare_kms_host): skip KMS configuration if there an oracle

---

sdcm/utils/version_utils.py
unit_tests/test_version_utils.py

Make the `ComparableScyllaVersion` support versions like following:
```
2024.2.0.dev.0.20231219.c7cdb16538f2.1
```
Such version structure may come from the GCE images.

improvement(version_utils): support more version options

---

sdcm/nemesis.py
sdcm/sct_events/group_common_events.py
sdcm/sct_events/setup.py
sdcm/utils/nemesis_utils/indexes.py
unit_tests/test_events.py

we had multiple places where we tried to apply a filtering/demoating of view update errors, and they keep popping up in all kind of cases
* cases of parallel nemesis
* cases our log reading slow down, and those pop out of context, since filter is gone
so cause of those issue, and the fact those aren't gonna be fixed any time soon, we'll apply this filter globaly until all of the view update issues would be addressed
Ref: https://github.com/scylladb/scylladb/issues/16206
Ref: https://github.com/scylladb/scylladb/issues/16259
Ref: https://github.com/scylladb/scylladb/issues/15598

fix(MV-errors): skip all view update error globaly

---

sdcm/sct_provision/aws/instance_parameters_builder.py
sdcm/sct_runner.py
sdcm/tester.py
sdcm/utils/aws_utils.py
unit_tests/test_scylla_yaml_builders.py

Cause of cost and prerformence, we rather use gp3 disks across the board, in this change we are changing all aws root disks to be using gp3

fix(aws-root-disk): make sure we are using gp3 for disks in AWS

---

sdcm/utils/version_utils.py
unit_tests/test_version_utils.py

the fix in #6970 wasn't covering case like
```
2024.1.0.rc2.0.20231218.a063c2c16185.1
```
the regex was update to match `a-z` and `0-9` for it to be handled correctly

fix(ComparableScyllaVersion): support version of release canidates

---

sdcm/cluster.py

since in cases we might have failure like the following:
```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64
&repo=os&infra=stock error was
14: curl#7 - "Failed connect to mirrorlist.centos.org:80; Operation now in progress"
```
we wrong assumed this should be enterpise and tried to install enterpise artifacts (which didn't existed)

fix(is_enterprise): check command output applying logic

---

sdcm/cluster.py

seems like since scylladb/scylla-monitoring#2000, cause we are specifying the ports, monitoring is using those also for the agents, and cause all scylla metric to be duplicated
Ref: scylladb/scylla-enterprise#3708

fix(monitoring): don't specify scylla target ports

---

sdcm/utils/common.py

Since we stopped recently a few builders
`get_builder_by_test_id` started failing with this error
```
KeyError: 'PublicIpAddress'
```
stopped instances doesn't have public address, and anyhow we shouldn't be listing them, by default.

fix(get_builder_by_test_id): don't list stopped builders

---

test-cases/features/dns-cluster-5min.yaml

The Scylla server for scylla-manager failed to start on t2.small instance type on the monitoring node in features-dns test. Removed the paramter from thsi test yaml config file.
The test passed in my staging folder with bigger instance for the monitoring node:
https://jenkins.scylladb.com/job/scylla-staging/job/mark/job/features-dns-cluster-5min-test/
https://argus.scylladb.com/workspace?state=WyIxMzBhODk4YS0wMWZlLTQyODQtODg1My05ODE2NmQ5ZGYwOGUiXQ

fix(dns): Change monitor instance type

---

defaults/test_default.yaml
test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-basic-3h-ics.yaml

We would like to use the latest 2021.1 released version to be used as oracle version for gemini tests as it contains all relevant fixes.

fix(oracle_scylla_version): Bump oracle version to 2021.1.23

---

defaults/severities.yaml
defaults/test_default.yaml
sdcm/commit_log_check_thread.py
sdcm/rest/remote_curl_client.py
sdcm/rest/rest_client.py
sdcm/sct_config.py
sdcm/sct_events/database.py
sdcm/tester.py

Checking "free segments" and "commitlog directory" metrics in SCT task: https://github.com/scylladb/qa-tasks/issues/1523
introdus new SCT background thread CommitLogCheckThread
if commitlog-use-hard-size-limit is enabled,
this thread will check the following metrics during the test:
1) commit log directory does not exceed the limit at any stage of the test. if it exceeded - send an error event that fails the test.
2) free segments don't drop to zero at any stage of the test, otherwise, send an error event that fails the test.

feature(commitlog): Checking commitlog in sct

---

sdcm/cluster_k8s/__init__.py

Bump the `k8s-local-volume-provisioner` version to be `0.3.0`, because
- It has the most recent base image security fixes.
- It is non-alpha version as the one we use now.
- It also supports `Arm` arch in addition to the `x86` as the current one does.

improvement(k8s): bump version for `k8s-local-volume-provisioner`

---

configurations/operator/expose-pod-ips.yaml
jenkins-pipelines/operator/upgrade/upgrade-major-scylla-podips-k8s-eks.jenkinsfile
jenkins-pipelines/operator/upgrade/upgrade-major-scylla-podips-k8s-gke.jenkinsfile

It will cover the following fixed scylla-operator bug:
https://github.com/scylladb/scylla-operator/issues/1638

ci(k8s): add scylla upgrade jobs using pod IPs

---

upgrade_test.py

since there a fix not yet backported about the order that `scylla sstable dumps` is looking for the schema, we need to pass it the scylla.yaml for it to be able to read EaR sstables
Ref: https://github.com/scylladb/scylla-enterprise/issues/3702
Ref: https://github.com/scylladb/scylladb/issues/16132

fix(upgrade_test): `scylla sstable dump` verify with scylla.yaml

---

sdcm/nemesis.py

The default connection timeout of 100 isn't enough in some cases after the view building in cases of large partitions.

fix(disrupt_add_remove_mv): Increase session connection timeout

---

sdcm/utils/aws_builder.py

update the launch templates to use gp3 disk,
and introduce code that can create new launch template version and update them to be the default, before this change the only check we did if the launch template existed or not, and never update anything with those templates

fix(aws_builder): change the builders to configure gp3 root disks

---

sdcm/nemesis.py

since we might get into uncontrolled situations with this nemesis see scylladb/scylla-cluster-tests#6928 for more details
Ref: scylladb/scylla-cluster-tests#6928

fix(nemesis): disable `disrupt_memory_stress`

---

sdcm/tester.py

in PR #6980, by mistake the walrus operator was inside a parentheses, and was returning a boolean instead of `scylla_encryption_options` it should have returned.
in turns it was casuing failure like that:
```
<Error from server: code=0000 [Server error] message="Malformed extension">})
```

fix(alter_test_tables_encryption): fix the walrus operation

---

sla_per_user_system_test.py

It is not allowed to create role/service level with name 'batch'. It cause to query failure with error:
```
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message=line 1:26 no viable alternative at input 'batch'
```
This word is reserved for workload type.
**Test:**
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/features-sla-workload-types-test/3/

fix(create role): fix role name in test_workload_types

---

sdcm/nemesis.py

`disrupt_add_drop_column` ignores system keyspace, but should also ignore the audit keyspace, those tables should be modifiable
Fixes: #6736

fix(disrupt_add_drop_column): to not pick audit tables

---

sdcm/nemesis.py

this nemesis is adding and removing a node.
currently from scylla POV it's disruptive, and we
can't do rolling restarts at that time.

fix(disrupt_add_remove_dc): mark as disruptive=True

---

sdcm/nemesis.py

The modify_table nemesis which picks one of the table properties and alter them can choose a very low percentile or value for the speculative_retry which can cause high load of retries that may fail the stress eventually.

fix(modify_table_speculative_retry): Set to reasonable numbers

---

sdcm/cluster.py
sdcm/utils/context_managers.py

since we can be using this node for quite some time, we don't want nemesis to pick it while this check is using it. using a context manager to make sure the node isn't left with the marking

fix(KMS_encryption_check): make the node used as `running_nemesis`

---

sdcm/cluster.py

since in some cases (twcs as example), we have table with lots of tombstones, and our query with limit 10, can come up with no data cause of that, using cfstats would be bit more lengthy but more accurate for figuring if the table has data or not.

feature(get_any_ks_cf_list): get more accurate data if table empty

---

upgrade_test.py

In some cases of large queries in this test like in truncate_ks, the session times out with an error: 'Connection defunct by heartbeat': 'Client request timeout.'
It's possible that it won't solve the issue, but at least it'll eliminate client side connection timeout.

fix(upgrade_test): Extend connection timeout for query session

---

test-cases/longevity/longevity-mv-si-4days.yaml

on run in 2024.1 we are getting into case the runner is running out of disk space, after ~3 days, so we need a bigger one for now
until we could detect it and handle it in some automatic fashion
- no testing is needed for this config change 

fix(longevity-mv-si-4days.yaml): enlarge runner disk

---

sdcm/nemesis.py
sdcm/utils/raft/common.py

NodeBootstrapAbortManager run in parallel two operations with ParallelObject:
1) bootstrap (node_setup)
2) abort_operation (stop_scylla)
ParallelObject has the common timeout for 2 operations equals
`Instance_start + log message wait timeout`
Bootstrap operation has default timeout 3600 ( but operation have to be aborted earlier)
abort_operation (stop_scylla) has wait timeout for log message equals
`Instance_start + log message wait timeout`
Usually abort operation triggered much earlier, when required log message appeared in log and
abort action is going to be executed.
But during job: `longevity-100gb-4h-fips-test`, required log message was not found during
required timeout. Parallel object exited and next steps of nemesis were started,
But because Threads initiated by ParallelObject …

fix(NodeBootstrapAbortManager): use correct timeouts for operations

---

sdcm/cluster.py
sdcm/utils/adaptive_timeouts/__init__.py

since we have seen a few time scylla might take more time to start then we might anticipate:
```
sdcm.remote.libssh2_client.exceptions.CommandTimedOut: Command did not complete within 500 seconds!
Command: 'sudo systemctl start scylla-server.service'
Stdout:
Stderr:
```
we now default to soft timeout of 500s same the timeout before, and hard timeout of 2000s (~30min)

feature(start_scylla_server): add adaptive timeout

---

docker/scylla-sct/ubuntu/Dockerfile

PR #6923 had remove the port cqlsh calls, to be able to test the default cqlshrc is created and used.
since we are using ssh with a different user,
that user didn't got the cqlshrc configuration, and SCT code need to take care of it.

fix(docker): copy cqlshrc as needed

---

configurations/longevity-fips-and-encryptions.yaml

Since this longevity uses a special clean AMI and some nemesis do not handle that well and need to install scylla, this commit suggests a workaround to run only non-disruptive nemesis. There is nothing special with the longevity for fips and in term of coverage it would be better to cover some administrative commands than topology changes or things like that.

fix(longevity-fips): Set the longevity to run non-disruptive nemesis

---

utils/update_field.py

a new script that can be used to change the job-name on specific test_ids
for case we want to exclude wrong/bad results from history
```bash
./utils/update_field.py [index_name] [test_id] [new_job_name]
```

feature(perf_date): script to change job-name of results

---

test-cases/features/system-sla-test.yaml

DB instance type has been changed from i3 to i4i by https://github.com/scylladb/scylla-cluster-tests/pull/6354.
It's because i3 family was depricated in scylla-cloud. It caused to load decreasing in SLA longevities. And it is a critical problem for those longevities as we need almost 100% load during the tests. I revert this change for SLA longevities .
Fixs: https://github.com/scylladb/scylla-enterprise/issues/3693

revert(instance type): use i3 type in SLA feature test

---

sdcm/cluster.py
sdcm/cluster_docker.py
sdcm/cluster_k8s/__init__.py
sdcm/utils/adaptive_timeouts/__init__.py

since we have seen a few time scylla might take more time to start then we might anticipate:
```
sdcm.remote.libssh2_client.exceptions.CommandTimedOut: Command did not complete within 500 seconds!
Command: 'sudo systemctl restart scylla-server.service'
Stdout:
Stderr:
```
we now default to soft timeout of 1800s (900s for stop / 900s for start), and hard timeout of 3600s (~1h)

feature(restart_scylla_server): add adaptive timeout

---

test-cases/longevity/longevity-large-partition-3h.yaml
test-cases/longevity/longevity-large-partition-8h.yaml

Since large partition data validation was introduced and runs after every nemesis, it's impossible to run the nemesis during prepare because it won't find the data or partial data during the validation.

fix(longevity-large-partitions): disable nemesis during prepare

---

test-cases/longevity/longevity-large-partition-8h.yaml

It seems like a copy-paste mistake done when adding data_validation to this test. the number of rows the test writes during the prepare is 5555, then the validation is comparing the number of rows actually written to the "limit_rows_number" (very bad naming for parameter). If the value is less than this parameter, it generates an error saying: "Found missing rows for partitions".

fix(data_validation longevity-large-partition-8h): set correct value

---

test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml

this case seem to be generating lots of logs, and we seen multiple case where the offset of the log reading was more then 15min, we might minimize this offset by using a stronger machine for the runner

fix(longevity-2TB-48h-*-ssl-1dis-2nondis): strong sct runner

---

query_limits_test.py
sdcm/sct_runner.py
test-cases/features/compaction-throughput-limit.yaml
test-cases/features/enospc-30mins.yaml
test-cases/features/per-partition-limit.yaml

those case doesn't need manager installed, and they are fine with having smaller monitor node, that manager (scylla) can't be installed on.

fix(featrues-testcases): disable manager on too small monitor nodes

---

test-cases/scale/scale-cluster.yaml

Current load with the very large blob being used in this test is too heavy for the i3.large nodes and disk can't handle the load.
Reducing the load by 75% reduced the throughput only by 10%, Now compaction bandwidth is around 200MB/s compared to almost 8GB/s previosuly.
We can probably push more, but it's not the intention of the test.

fix(scale-cluster): Reduce load by 75%

---

docker/env/hydra.sh

ac827977 introduce a mount point for /dev/, this seems to be breaking rootless podman support:
```
Error: crun: chown `/dev/pts/1`: Operation not permitted: OCI permission denied
```
we'll move the move to be use only when using docker. (at least until we'll have better option for podman)
Fixes: #7037

fix(hydra): mount /dev/ only when using docker

---

configurations/audit.yaml

since `table` option is problemtic, and can cause some quries to fail cause audit is with CL=ONE. we should be defaulting to `syslog`

fix(audit-test-cases): change audit to use `syslog`

---

sdcm/nemesis.py

since those nemesis might be doing rolling restart to apply KMS configuration, it might trigger those errors in YCSB since we don't have a fully functioning loader balancer for alternantor

fix(nemesis): ignore "ycsb connection refused" in kms nemesis

---

sdcm/cluster.py
unit_tests/test_cluster.py

recent change to some java libraries used by nodetool is causing ipv6 to be presented as rfc5952 section-4 without leading zeros, and SCT was comapring those as string with other places we get addresses from.
now we convert it to the full form, after getting
it from nodetool, and still keep it as string
Ref: https://www.rfc-editor.org/rfc/rfc5952#section-4

fix(get_nodetool_status): convert ipv6 to full format

---

sdcm/sla/sla_tests.py

In this test every service level has name as 'sla<shares>_<auth_entity_name_index>. Fix harcoded name that remained by mistake

fix(service level): fix hardcoded name

---

sdcm/cluster.py
unit_tests/test_cluster.py
unit_tests/test_config.py

recent change in c7a08adaf756d94050cc179da52060f3d5db17f0,
started using `nodetool cfstats`, and we've seen
that it being called multiple for each table, and take quite
some time.
now we first scan the names into set, and then iterate over
that set, to remove those table which doesn't have data in
them.

fix(get_any_ks_cf_list): speed it up

---

.github/workflows/opend-issues-new.yaml

Since we are working mainly with the boards, we want to see SCT issue appear on them once they are created/reopened

feature(github-actions): add all open issues to QA board

---

sdcm/nemesis.py
sdcm/utils/sstable/sstable_utils.py

To avoid those errors, when checking a newly created table:
```
error processing arguments: could not load schema via schema-tables:
std::runtime_error (Failed to find keyspace1.tmp_encrypted_table in schema tables)
```
Fixes: #6825

fix(nemesis): flush system_schema before doing encryption check

---

sdcm/cluster.py
sdcm/tester.py
test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
test-cases/longevity/longevity-lwt-basic-24h-1dis-2nondis.yaml
unit_tests/test_nemesis.py

since most manager task are on the whole cluster, we should limit them to be selected only on one `NonDisruptive` thread. otherwise it would generate lots of nice of failed manager tasks

fix(longevity-2TB-*-1dis-2nondis): limit manager nemesis to on thread

---

sdcm/provision/common/utils.py

seems like for centos8, syslog-ng is available on from EPEL
```
+ yum install -y syslog-ng
No match for argument: syslog-ng
Error: Unable to find a match: syslog-ng
```
Ref: https://www.syslog-ng.com/community/b/blog/posts/state-of-syslog-ng-on-rhel-8-centos-8

fix(centos8): install epel, so syslog-ng would be available

---

sdcm/utils/adaptive_timeouts/__init__.py
unit_tests/test_adaptive_timeouts.py

since in some cases we will want to use that number as a scale for selecting timeouts
so we'll start collecting it now

feature(adaptive_timeouts): collect number of db nodes

---

test_lib/sla.py
unit_tests/test_sla_utils.py

We receive timeouts on service level/roles creation/alter/drop operations from time to time, especially when a node(s) runs heavy operations.
```
cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.4.1.7:9042
```
This commit increases 'session.default_timeout' to wait more time for the answer
Fixes: https://github.com/scylladb/scylla-enterprise/issues/3755

fix(service level): increate session default timeout

---

test-cases/features/compaction-throughput-limit.yaml
throughput_limit_test.py

Seems load is too small to show the benefits of latency improvements when compaction throughput is limited.
Switched to latest generation loader (c7i) should increase the load.

fix(test): increase load for compaction throughput test

---

test-cases/scale/longevity-many-clients-4h.yaml

We want to test many-clients scenario with authentication enabled to see the impact on the performance (and other possible aspects).
Added auth to c-s load for it.
Also increased number of connections, reaching 100k connections per db instance.

test(many-clients): add authenticator

---

defaults/severities.yaml
sdcm/sct_events/loaders.py
unit_tests/test_sct_events_loaders.py

Task: https://github.com/scylladb/qa-tasks/issues/1492
Scylla-bench data validation was fixed by
https://github.com/scylladb/scylla-bench/commit/3eb53d8ce11e5ad26062bcc662edb31dda521ccf. We need to create scylla-bench CRITICAL event if data validation failed.

improvement(scylla-bench): add CRITICAL error on data vaidation failure

---

test-cases/features/per-partition-limit.yaml

Due to better performance of Scylla Enterprise test became unstable as impact was too little.
Increase load by switching to newer loaders c5->c7i.

fix(test): increase load in per partition limit test

---

configurations/operator/50GB-no-tls.yaml

- Set `nemesis_add_node_cnt=1` instead of the `3` for K8S to avoid provisioning failures, because we have only 1 additional K8S Scylla nodes.
- Set `use_dns_names=false` for K8S because it is not supported there.

ci(k8s): Update `50GB-3days-authorization-and-tls-ssl` CI job for K8S

---

sdcm/nemesis.py

Timeout error:
```
cassandra.OperationTimedOut: errors={'10.12.3.55:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.12.3.55:9042
```
while `disrupt_mgmt_restore` and `disrupt_no_corrupt_repair` nemeses. It may happens when the cluster is overloaded

fix(nemesis): increase session timeout for drop queries

---

performance_regression_test.py
sdcm/utils/nemesis_utils/indexes.py

Timeout error:
```
cassandra.OperationTimedOut: errors={'10.12.3.55:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.12.3.55:9042
```
while `disrupt_create_index` and `disrupt_add_remove_mv`  nemeses. It may happens when the cluster is overloaded

fix(nemesis): increase session timeout for drop view queries

---

data_dir/nemesis.yml
data_dir/nemesis_classes.yml
sdcm/nemesis.py
test-cases/enterprise-features/workload-prioritization/longevity/longevity-sla-system-24h.yaml

3 SLA nemeses use binary disable/enable workaround that in a test with parallel nemeses can cause to the errors and failures that is not a problem of Scylla. Mark them as "disruptive" to prevent irrelevant failures.
Should be changed back when the issue https://github.com/scylladb/scylla-enterprise/issues/2572 will be fixed.
Example of such failure here: https://argus.scylladb.com/test/1aebcb86-a767-4ce5-a88a-c977ab077ddc/runs?additionalRuns[]=d38963cd-e9ea-45ae-98ce-fa346afb89b8. The nemesis "disrupt_remove_node_then_add_node" failed because of this

fix(nemesis): mark 3 SLA nemeses as disruptive

---

sdcm/commit_log_check_thread.py

In case there's no Prometheus instance (no monitor) commitlog checker
should not be executed as it will fail.
Fixed skip of starting commitlog checker in when it is known it
will not work.

fix(artifact_test): fix disable commitlog check

---

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml

`scylla-bench` may use much more memory than it is expected, i.e. leak for some period of time.
And if we run too many `scylla-bench` commands on a single loader node then we may get crashes of stress commands.
So, avoid it, add one more loader node to reduce utilization of loader nodes.
Ref: #6992

ci(longevity): add 1 loader to longevity-large-partition-200k_pks-4days

---

sdcm/nemesis.py

In practice we have lots of cases in multiple cases that creation takes more then 2h we setup initial, but still finising in less then 4h and extending the hard timeout to 8h
from the data we have now [1], of one node, there no corrlation to any metric to the time this operation might take.
[1]: https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/8b9466d0-ae41-11ee-81c7-3986d18dafd5

fix(nemesis): enlarge timeout of creating view/indexes

---

sdcm/cluster.py

If a test table was not received while `sdcm.cluster.BaseScyllaCluster.start_kms_key_rotation_thread` due to any reason (a session can not be created, any table was not created yet), send an error that any table was not received.
Now the error 'Failed to check the fact of encryption (KMS) for sstables' message is published with 'IndexError: list index out of range'. It is not clear enough.

fix(kms_key_rotation): add error 'failed to get a table'

---

sdcm/utils/database_query_utils.py

`fetch_all_rows` was passing timeout only to `request_all` call while the inital request of the first page was using the default timeout which isn't always enough, and can lead to the following error:
```
(TestFrameworkEvent Severity.ERROR) period_type=one-time
event_id=e2d16764-de17-4150-bc90-ba2c6f5e5b90,
source=PartitionsValidationAttributes
message=Failed to collect partition info. Error details:
Requested pages were not delivered before timeout. Requested: 1; retrieved: 0; empty retrieved 0
```
in this change we change the session default timeout, assuming this session is used mostly for those calls
- Update the Readme/doc folder relevent to this …

fix(fetch_all_rows): pass down timeout correctly

---

sdcm/nemesis.py

since now there are multiple tools implementing the nodetool commands, help command goes to the scylla-nodetool, and `resetlocalschema` isn't yet implmented there
cause `resetlocalschema` exist for long enough in scylla (since 2019), we can't directly call it assuming it's there and not need to first check the help for existence of the command.
Ref: scylladb/scylladb#16669

fix(disrupt_resetlocalschema): stop calling `nodetool help`

---

README.md
sdcm/monitorstack/__init__.py

* podman now defaults to short-name-mode="enforcing", and the monitor stack doesn't able to pull images when working via socket, it doesn't have tty to offer which repository to alias it, setting short-name-mode="permissive" on ~/.config/containers/registries.conf alleviate this issue
* scylla-monitoring was using DOCKER_HOST inside it's start scripts, hence breaking our ability to use it to point to podman socket, a fix was subbmitted but until then we patch those out of the scripts so older collected monitoring data can be used
Ref: https://github.com/scylladb/scylla-monitoring/pull/2149
Fixes: #7080
- Update the Readme/doc folder relevent to this …

fix(monitorstack): make it work when running hydra via podman

---

sdcm/sla/libs/sla_utils.py

Add info message about possible issue when error SchedulerGroupNotFound received
no need to run hte test

improvement(sla test): issue when scheduler is not created

---

sdcm/nemesis.py

Closes #6842.
Revert of https://github.com/scylladb/scylla-cluster-tests/pull/6791
Restore procedure is built on uploading sstables.
When you drop keyspace after restoring a backup a 'DROP KEYSPACE' is committed with higher timestamp than records from sstables in the backup. 
As result when you upload same sstables second time scylla sees older timestamp and ignores them on second restore.
This is expected behavior on both `s-m` and `scylla` side.

fix(nemesis): make disrupt_mgmt_restore not delete keyspace

---

upgrade_test.py

Increase session.default_timeout for truncate/insert/select while upgrade tests.
Error:
```
cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.4.2.126:9042
```
not run 

fix(upgrade): increase session default_timeout

---

sdcm/nemesis.py
unit_tests/test_wait.py

this code was introduced after RBNO was default for all operations and in branch 2023.1 isn't not yet the cases, and log prints doesn't match.

fix(nemesis): support non RBNO rebuild logging

---

upgrade_test.py

Error:
```
cassandra.OperationTimedOut: errors=ReadTimeout: Operation timed out for truncate_ks.truncate_table0 - received only 0 responses from 1 CL=ONE.
```
Run all queries with QUORUM

fix(upgrade): set default CL = QUORUM

---

sdcm/nemesis.py

the check assumed `user_info_encryption` is always defined, and it's not yet true for 2023.1 branch, and fails like the following:
```
File ".../sdcm/nemesis.py", line 4150, in _enable_disable_table_encryption
user_info_encryption_enabled = scylla_yaml.user_info_encryption.get('enabled', False)
AttributeError: 'NoneType' object has no attribute 'get'
```

fix(nemesis): improve user_info_encryption check on KMS nemesis

---

docker/scylla-sct/ubuntu/Dockerfile

PR #7087 has introduced code, that doesn't work with older branchs of scylla, this commit fixes that, and copy the cqlshrc file from what locations it might be

fix(docker): copy cqlshrc for older scylla branches

---

sdcm/sct_events/setup.py
sdcm/tester.py
unit_tests/lib/events_utils.py

By default audit is disabled by default in in 20223.1 and up by https://github.com/scylladb/scylla-enterprise/pull/3094. But it won't be disabled in 2022.1 and 2022.2.
This message generates too much noise for us. We do not need it will fail the test and create WARNING message, not ERROR.
issue that should be track https://github.com/scylladb/scylla-enterprise/issues/3148

fix(c-s): ignore audit related consistency error

---

sct.py

242d72ac365e575d379a71d7b02d9448d6fb76a3 introduce new hydra command, and added an import to some test code.
that was causing log collection to fail, since it was missing the latest symlink, that wasn't create in the correct place cause of this import

fix(nemesis-list): import test code inline

---

sdcm/logcollector.py
sdcm/scan_operation_thread.py

the check was generating too much output into warning level and chocking the jenkins builder, making it hard to debug jobs using this fullscan thread.
now the diff should be printed into a log file, that later would be upload with the rest of the sct-runner logs
Fixes: #6573
Fixes: #6056

fix(FullPartitionScanOperation): print diff output to log files

---

sdcm/tester.py
sdcm/utils/sstable/sstable_utils.py
upgrade_test.py

code assumed it would be working only from 2023.2 up, but things had changed and now it's supported from 2023.1.3 up.

fix(EaR-KMS): change auto-enable of KMS to start working from 2023.1.3

---

sdcm/nemesis.py

cause of the recent scylla-nodetool warpper script, we are getting this error, when using help, since toppartitions isn't implmented on `scylla nodetool` while `help` command is implmented:
```
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: '/usr/bin/nodetool  help toppartitions'
Exit code: 1
Stdout:
Stderr:
error processing arguments: unknown command toppartitions
```
removing this check that was introduced of scylla 2019.1 we don't support this version any more, and we have other mean of checking which version is used to decide skipping nemesis.
- Update the Readme/doc folder relevent to this …

fix(disrupt_show_toppartitions): stop using `nodetool help`

---

sdcm/stress_thread.py

Increate stress soft timeout to prevent killing cassandra-stress process

fix(stress): prolong stress timeout

---

sdcm/nemesis.py
sdcm/sct_events/filters.py
sdcm/sct_events/group_common_events.py
sdcm/utils/quota.py

Read all the mount options, and look in them for the expected value
Fixes: #6936

fix(end_of_quota_nemesis): parse mounts correctly

---

sdcm/cluster.py
sdcm/utils/cql_utils.py
unit_tests/test_cluster.py

PR #6897 handled calls to cqlsh to keep the quotes, but we do have other places when we supply quoted identifiers and it might break like the following:
```
Executing CQL 'CREATE INDEX standard1_c4_nemesis ON 100gb_sizetiered.standard1("C4")' ...
...
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax
error in CQL query] message="line 1:37 no viable alternative at input '100'">
```
Fixes: #6790

fix(get_any_ks_cf_list): return keyspaces and tables quoted if needed

---

sdcm/sct_events/setup.py
unit_tests/test_events.py

b33d585488b6f0209538327bd11c631828e9211f introduce a filter that wasn't totally working, this commit fixes the regex and introduce a unittest coverage for it

fix(c-s): fix audit related consistency error filter

---

sdcm/nemesis.py

b5808cefa7f91f5202ec65ac2f72694a97b246f7 fix introduced extra parentheses in one of the regex to look for
it was breaking the test like this:
```
File ".../sdcm/nemesis.py", line 5062, in wrapper
File ".../sdcm/nemesis.py", line 4488, in disrupt_add_remove_dc
with wait_for_log_lines(node=new_node,
start_line_patterns=["rebuild.*started with keyspaces=", "Rebuild starts"],
File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
return next(self.gen)
File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 144, in wait_for_log_lines
end_follower = node.follow_system_log(patterns=end_line_patterns)
File ".../sdcm/cluster.py", line 1383, in follow_system_log
regexps.append(re.compile(pattern, …
```

fix(nemesis): fix typo in disrupt_add_remove_dc

---

sct.py
sdcm/cluster.py
sdcm/node_exporter_setup.py
sdcm/sct_runner.py
sdcm/utils/azure_region.py

* create a new version of sct-runner with node exporter baked in
* set it up on the monitoring stack
this would help use collect data about what's going on with the sct-runner, and help us pin point issues with the test code or the need to pick bigger instances/disks from some tests.

feature(sct-runner): collect runner metrics using node_exporter

---

sdcm/utils/gce_builder.py

`keep: alive` was added to metadata, but cleanup scripts are reading the labels, hence were stopping builder in gce after 12 hours.
add needed label, and recreate all instnace templates in all of our gce projects

fix(gce_builder): set `keep: alive` labels

---

sdcm/nemesis.py
sdcm/tester.py

When we run `mgmt_restore` nemesis we may get failed stress commands which get triggered by this nemesis.
And when it fails, nemesis doesn't catch errors and reports 'Success'.
So, fix it by checking the stress commands results.
Related: #7122
- https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-eks-mgmt-restore/10

fix(mgmt-restore): report proper `mgmt-restore` nemesis results

---

sdcm/nemesis.py

It is allowed that compaction strategy has only 'class' defined, and 'compaction_window_size' and 'compaction_window_unit' are not defined. Like:
```
compaction = {'class': 'TimeWindowCompactionStrategy'}
```
In this case the nemesis fails with error:
```
KeyError: 'compaction_window_unit'
```
Example of failed test:
https://argus.scylladb.com/test/079cddb4-4eac-4594-a2f0-8452dab5eb40/runs?additionalRuns[]=73ec8004-3881-4cbb-b37b-11c75c1c1126
It first time from 2022 that this nemesis was run

fix(nemesis): disrupt_modify_table failure

---

sdcm/monitorstack/__init__.py

in cases of port being taken, or other errors
retries are not working as expect since the zero
port were taken out of the list.
those zero port are what enable us to randomly select ports of the diffrent monitoring services
Fixes: #7093

fix(monitoringstack): add zero to the list of ports

---

sdcm/fill_db_data.py

Increase session timeouts for data validation sdcm.fill_db_data.FillDatabaseData.verify_db_data:
```
cassandra.OperationTimedOut: errors={'10.4.3.124:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.4.3.124:9042
```

fix(upgrade): increase session timeouts in verify_db_data

---

sdcm/sct_events/group_common_events.py

we are seeing case that even smallest lag in the logging system of less then 5min, can cause this nemesis to generate error on those log lines, adding 30min to the ignore, should be sufficent.
bigger lag then that in the logging systeam would be addresssed on it's own

fix(ignore_no_space_errors): add 30min to the ignore time

---

docker/cassandra-stress/Dockerfile-src
docker/cassandra-stress/README.md
docker/cassandra-stress/image
jenkins-pipelines/longevity-multi-dc-rack-aware.jenkinsfile
sdcm/cluster.py
sdcm/stress_thread.py
sdcm/utils/docker_remote.py
test-cases/longevity/longevity-multi-dc-rack-aware.yaml
unit_tests/conftest.py
unit_tests/dummy_remote.py
unit_tests/test_cluster.py

`RackAwareRoundRobinPolicy` was introduced in scylladb/java-driver#227 and now we'll support passing it to c-s automatically every time we use multiple racks setup, the loader would be spread on multiple AZs, and we should pass each loader the corresponding rack, similar to how we are doing it for DCs
Ref: https://github.com/scylladb/scylla-tools-java/pull/335
Ref: https://github.com/scylladb/java-driver/pull/227

feature(cassandra-stress): rack aware support

---

sdcm/cluster.py
sdcm/nemesis.py

Check the gossip status and CQL workability in the end of the `disrupt_disable_binary_gossip_execute_major_compaction` nemesis instead of looking for the `gate closed` message in DB logs.
Fixes: #6819
- https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-eks-nodetool-flush-and-reshard/26

fix(nemesis): fix `disable_binary_gossip_execute_major_compaction`

---

jenkins-pipelines/upgrade-with-raft/rolling-upgrade-centos8-with-raft.jenkinsfile
jenkins-pipelines/upgrade-with-raft/rolling-upgrade-debian11-with-raft.jenkinsfile
jenkins-pipelines/upgrade-with-raft/rolling-upgrade-ubuntu22.04-with-raft.jenkinsfile

5.4 and 2023.1 already have Raft enabled by default when starting fresh as base versions. So there's no need to test it in separate job.
Fix by specifying base_version explicitly instead of automatic resolver.

fix(rolling-upgrade): set raft upgrade test only from 2022.2

---

sdcm/cluster_k8s/__init__.py

The most recent dev versions of the scylla operator started looking like the following: `v1.12.0-alpha.1-78-ge5a1c9b-latest` Before it was like following: `v1.12.0-alpha.0-144-g60f7824`.
We were depending on the number of the `-` symbols and it now leads to the filtering out of the new kind of chart versions. 
So, fix it by properly checking helm chart versions.

fix(k8s): make 'latest' tag parsing logic work correctly

---

sdcm/nemesis.py

Timeout for nodetool decommission was set incorrectly for 180sec in DecommissionStreamErr nemesis. Decommission process could run much longer. If decommission should be aborted after log message which expected to be at the end of decommission process, nodetool decommission command will be terminated by timeout too earlier and next logic of nemesis failed because status of decommissioning node will be UL because decommission itself continue to run on the node.
Job which failed: https://argus.scylladb.com/test/a5d1f97b-064a-40ed-a517-70e2092b51c2/runs?additionalRuns%5B%5D=38e1b036-3163-4f2a-92f4-5f66f3b0a116
Set valid waiting timeouts for commands and ParalleObject to correctly abort decommission.
Fix issue #7067 
- [4 hours job master](https://jenkins.scylladb.com/view/staging/job/scylla-st …

fix(decommissionstreamerr): Set valid decommission nodetool timeout

---

sdcm/cluster.py
sdcm/nemesis.py
sdcm/utils/sstable/sstable_utils.py

Also, allow some part of the sstables to fail the encryption check because we care about big picture and not concrete number.

fix(kms): Detect `sstable not found` situation better

---

sdcm/utils/cloud_monitor/cloud_monitor.py

This reverts commit 2d6a2caf524c724014fb23275dfb806d0a1d727a.
It's been 2 years with the random email titles and looks like we became immune to this as well :)
Reverting back to normal email titles.

Revert "feature(notify_by_email): Make the mail subject random"

---

sdcm/db_log_reader.py
sdcm/sct_runner.py

this case is running multiple nemesis threads and
it keeps showing the ssh `Bad packet length` issue
now that we are collecting metrics of runner, it shows we are getting into 100% cpu.
trying this change to see if it help with this issue
Ref: https://github.com/scylladb/scylladb/issues/14004

fix(tier1): longevity-schema-topology-changes-12h bigger runner

---

sdcm/cluster.py
sdcm/provision/helpers/certificate.py
sdcm/provision/scylla_yaml/certificate_builder.py
unit_tests/test_python_driver.py

SCT python driver is using ssl_options when create session and should be switching to use
ssl_context since ssl_options is deprecated (and also broken for scylla-driver==3.26.4 ontop
python 3.12)
Refs: https://github.com/scylladb/python-driver/issues/284

fix(python driver): use 'ssl_context' instead 'ssl_options'

---

defaults/aws_config.yaml

something got this image broken and we can't get it's metadata
```
File ".../sdcm/utils/aws_utils.py", line 360, in ec2_ami_get_root_device_name
if image.root_device_name:
File ".../site-packages/boto3/resources/factory.py", line 386, in property_loader
return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```
replacing it with newer working image

fix(monitor): replace with newer ubuntu image

---

sdcm/cluster.py

The KMS logic we have works fine if we have just one test keyspace.
If we have multiple additional keyspaces then we may get following errors:
```
error processing arguments: could not load schema via schema-tables: \
std::runtime_error (Failed to find keyspace1.standard1 in schema tables)
```
Such additional keyspaces may be added by multiple nemesis such as:
- `disrupt_load_and_stream`
- `disrupt_nodetool_refresh`
- `disrupt_mgmt_restore`
So, fix it by reading 'cfstats' and picking up the keyspace with the biggest number of sstables. It is going to be the keyspace+table generated by the main load/stress commands.
Example of the failure without this fix:
- https://argus.scylladb.com/test/bb28c47f-3f97-4357-b520-8151420427e9/runs?additionalRuns%5B%5D=1eb61c51-3a04-4f1c-9174-00b18402160c …

fix(kms): make KMS logic be stable having multiple test keyspaces

---

sdcm/utils/version_utils.py

we don't need to see at the output, each this this function is not not doing anything, and the rest of the warning are raised as events that would be printed as warning level anyhow
Fixes: #7163

fix(resolve_latest_repo_symlink): remove unneed logging prints

---

functional_tests/scylla_operator/test_functional.py

Scylla master (5.5-dev) started having following kind of messages:
- `api - Keyspace {keyspace} does not require cleanup`
In addition to the following one supported by all other existing Scylla versions:
- `api - force_keyspace_cleanup: keyspace={keyspace} `
So, add support for the new message type to make the `test_add_new_node_and_check_old_nodes_are_cleaned_up` K8S functional test work correctly with any Scylla version.

fix(k8s): support master Scylla version in cleanup messages checks

---

sdcm/nemesis.py

since #7104 introduced quotes for keyspaces and column families, for usage in CQL, but in case like this one, when it's used for comparing with outputs other then CQL, it's was breaking the logic, like the following
```
File ".../sdcm/nemesis.py", line 5059, in wrapper
File ".../sdcm/nemesis.py", line 3200, in disrupt_snapshot_operations
self._validate_snapshot(nodetool_cmd=nodetool_cmd, snapshot_content=snapshot_content)
File ".../sdcm/nemesis.py", line 3098, in _validate_snapshot
raise AssertionError(f"Snapshot content not as expected. \n"
AssertionError: Snapshot content not as expected.
Expected content: [ ... ['system', '"IndexInfo"'], ... ]
Actual snapshot content: [ ... ['system', 'IndexInfo'], ... ]
```
- Add …

fix(snapshot_operations): remove quotes from keyspaces/columnfamilies

---

data_dir/scylla-dash-per-server-nemesis.master.json
sdcm/cluster.py
sdcm/node_exporter_setup.py

so we can track rate/drop of logging, we introduce an exporter for syslog-ng.
example of the metrics we will have:
```
syslog_ng_destination_messages_dropped_total{destination="...",id="remote_sct#0",type="dst.syslog"} 0
syslog_ng_destination_messages_processed_total{destination="...",id="remote_sct#0",type="dst.syslog"} 18137
syslog_ng_destination_messages_stored_total{destination="...",id="remote_sct#0",type="dst.syslog"} 25617
syslog_ng_destination_messages_written_total{destination="...",id="remote_sct#0",type="dst.syslog"} 0
```

feature(syslog-ng): collect syslog-ng stats

---

sdcm/cluster_k8s/eks.py
sdcm/tester.py

After merge of the PR (https://github.com/scylladb/scylla-cluster-tests/pull/7088) with the S3 usage in EKS deployments all our multitenant setups on this backend started failing the following way:
```
Error: failed to create iamserviceaccount(s)
```
It is caused by the fact that there was attempt to create an iamserviceaccount per tenant.
But it must be done only per K8S cluster.
So, fix it by calling the appropriate function just once per K8S cluster.
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-multitenant-eks/61

fix(k8s-eks): fix EKS iamserviceaccout creation on multitenant setups

---

sdcm/sct_events/setup.py

Cause audit is enabled by default in 2022.1/2, we are getting those errors after/during upgrades, and we should ignore them until scylladb/scylla-enterprise#3814 is fixed
Ref: scylladb/scylla-enterprise#3092
Ref: scylladb/scylla-enterprise#3814

fix(rolling-upgrades): ignore audit related log errors

---

jenkins-pipelines/hydra-cleanup-cloud.jenkinsfile
utils/cloud_cleanup/azure/clean_azure.py

We are moving cloud cleanup process to SCT codebase. At first adding Azure support that was not implemented so far.
Introduce external cleaning azure cloud script that based on `creation_time` and `keep` tag deletes VM's or whole ResourceGroup in case all machines from it shall be deleted.
refs: https://github.com/scylladb/qa-tasks/issues/1535

feature(cleanup): added azure cleanup according to keep tag

---

sdcm/cluster_k8s/eks.py

Recently, we started getting following error:
```
failed to create service account kube-system/functional-PR-7174-832d6dde: \
ServiceAccount "functional-PR-7174-832d6dde" is invalid: metadata.name: \
Invalid value: "functional-PR-7174-832d6dde": a lowercase RFC 1123 subdomain \
must consist of lower case alphanumeric characters, '-' or '.', \
and must start and end with an alphanumeric character (e.g. 'example.com', \
regex used for validation is \
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
So, transform all uppercase symbols to the lowercase ones.
Also, add prefix in the same refering to the target resources access - `s3`. …

fix(k8s-eks): properly name the service account with S3 access

---

configurations/rust/cql-stress-100gb-4h.yaml
data_dir/scylla-dash-per-server-nemesis.master.json
defaults/severities.yaml
defaults/test_default.yaml
docker/cql-stress-cassandra-stress/Dockerfile
docker/cql-stress-cassandra-stress/README.md
docker/cql-stress-cassandra-stress/image
jenkins-pipelines/rust/longevity-100gb-4h-cql-stress.jenkinsfile
sdcm/cql_stress_cassandra_stress_thread.py
sdcm/loader.py
sdcm/sct_events/loaders.py
sdcm/stress_thread.py
sdcm/tester.py
unit_tests/test_config.py
unit_tests/test_cql_stress_cassandra_stress_thread.py

Ref: https://github.com/scylladb/cql-stress
cql-stress is a stress tool implemented in Rust. It supports two CLI frontends: scylla-bench and cassandra-stress.
In this commit we introduce a cql-stress-cassandra-stress stress tool to SCT. Currently, the C-S frontend supports 4 basic commands:
- read
- write
- counter_read
- counter_write
- docker
- created docker image definition containing `cql-stress-cassandra-stress` executable
- pushed docker image to registry
- updated `defaults/test_default.yaml` accordingly
- loader
- introduced `CqlStressCassandraStressThread` class deriving from `CassandraStressThread`
- overridden `create_stress_cmd` and `_run_cs_stress` methods
- introduced `CqlStressCassandraStressEvent` with critical default severity
- introduced …

feature(loaders): add cql-stress C-S stress tool

---

sdcm/cluster_k8s/eks.py

It comes out that we may get following error deploying EKS cluster:
```
creating CloudFormation stack "eksctl-longev-scylla-operat-3h-master-\
85a635da-addon-iamserviceaccount-kube-system-s3-sa-for-longev-scylla-\
operat-3h-master-85a635da": operation error CloudFormation: \
CreateStack, https response error StatusCode: 400, \
RequestID: 71e436e2-620f-40b3-a20d-f765c402e503, \
api error ValidationError: Stack name cannot exceed 128 characters
```
So, make the iamserviceaccount dedicated
for providing access to the S3 service have shorter name to avoid described errors.

fix(k8s-eks): make iamserviceaccount for s3 access be shorter

---

sdcm/nemesis.py

this nemesis is doing a full cluster restart, and that can cause YCSB get connection refuse errors, cause of the DNS based load balancer that we currently use.
those errors can be ignored.

fix(alternator): skip YSCB `Connection refused` during restore nemesis

---

test-cases/gemini/gemini-1tb-10h.yaml
test-cases/gemini/gemini-3h-with-nemesis.yaml
test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-8h-large-num-columns.yaml

Currently some of our gemini tests are very flakey failing with read validations due to "missing rows" on the cluster side. Since Gemini is random, some tests can be heavier than others. Looking on failed tests, espcially with dirsuptive nemesis one could easily notice that CPU utlization per core reaches to 100%. In this cases, some of the validations fail with 1-4 attempts until there is a validation that fails all the 5 attempts, mostly due to missing row or several rows on the test cluster. However, connecting to the cluster afterwards, I could see all rows are available.
This change first increase the instances size from i4i.large to 2xlarge. Second, it increases the retries from 5 to 10, same as we have in c-s. …

fix(gemini): Increase instance size and max retries

---

sdcm/cluster.py

when we connect to nodes via public network, we enable reverse tunneling for sending back the logs from the nodes,
as part of 4d68bf52165b54116683184f2a0561a13e3b95f3, we remove this part of the code (since it was labeled as rsyslog), this change it putting it back into the code
- - [x] https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-5gb-1h-BlockNetworkMonkey-aws-test/3/

fix(log-tunnel): enable back log tunnelling

---

jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2-arm.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos7.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos8-arm.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos8-selinux.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos8.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-debian10-arm.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-debian10.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-debian11.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-oel76.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-oel81.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-rocky8.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-rocky9.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2004-arm.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2004.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2204-arm.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2204.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-grow-shrink.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-with-nemesis.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-shard-aware-1TB.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-simple-query-weekly-microbenchmark.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-simple-query-weekly-microbenchmark_x86_64.jenkinsfile

seems like jenkinks doesn't run pipelines which are symlink and fails like the following:
```
09:48:17  org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
09:48:17  WorkflowScript: 1: unexpected token: .. @ line 1, column 1.
09:48:17     ../artifacts/artifacts-centos8.jenkinsfile
09:48:17     ^
09:48:17
09:48:17  1 error
```
so we'll copy all the symlink, until we can figure out a better option for this use case of identical pipelines, we need in multiple locations

fix(pipelines): dereference all symlink

---

sdcm/cluster.py
sdcm/kcl_thread.py
sdcm/nemesis.py
sdcm/utils/context_managers.py

since we run into multiple cases on parallel nemesis that there were multiple nemesis using the same node
we are introducing a lock over the selection of target nodes so we won't be able to pick it multiple times
Fixes: #6553

feature(nemesis): introduce lock for target selection

---

configurations/tablets_supported_nemeses.yaml
data_dir/nemesis.yml
jenkins-pipelines/oss/tablets/longevity-100gb-4h.jenkinsfile
jenkins-pipelines/oss/tablets/longevity-harry-2h.jenkinsfile
jenkins-pipelines/oss/tablets/longevity-large-partition-8h.jenkinsfile
sdcm/nemesis.py

Since scylla bench is required for tablets, I added two scenarios that use scylla bench: longevity-large-partition-200k-pks-4days and longevity-schema-topology-changes-12h. Also, created a folder for tablet-enabled jobs in jenkins

test(tablets): added two tablets enabled longevities

---

docker/env/version
requirements.in
requirements.txt
sct.py
sdcm/provision/azure/utils.py
sdcm/provision/azure/virtual_machine_provider.py
sdcm/sct_config.py

since this is the way to lookup the images our use would use we are switching to this method, without it we can pickup unpromoated images, which can lead to rolling upgrades to fail, since base and target would be identical

fix(azure): find formal images in community gallary

---

sdcm/cluster.py
unit_tests/conftest.py
unit_tests/test_cluster.py

those test were using hard-coded 5.2 develeopment version new we are using newer version, and have ability to select specific docker images per tests.
also fixing an issue with the new docker images, that they were failing to fetch the packages needed for installing iproute package. so `apt-get update` was add before we start calling `is_port_used()`

fix(integration-tests): use latest OSS image

---

vars/perfRegressionParallelPipeline.groovy

We don't look into monitors if perf test failed - anyway we revoke them by hydra command.
Make monitors to be destroyed by default in perf regression tests.

fix(perf): destroy monitors after tests

---

jenkins-pipelines/perf-regression-latency-650gb-grow-shrink-tablets.jenkinsfile

this introduce one pipeline across both OSS/enterprise that would enable tablets on the latency during grow shrink case

feature(tablets): add trigger for one tablets case in weekly runs (branch-perf-v14)

---

sdcm/stress/base.py
sdcm/stress_thread.py

since we are using `SoftTimeoutContext` on the stress command with hard_timeout of 10% more the the time passed to the stress command, `get_results()` and likes should align to that time and let the ssh command itself to timeout first.

fix(cassandra-stress): use `hard_timeout` in `get_results()`

---

docker/env/hydra.sh
unit_tests/test_hydra_sh.py

we don't need to fetch the keys, we can fetch them as needed inside the code, but we should do that inside the hydra docker image, and not outside of it.

fix(hydra): remove the `awscli` dependency

---

jenkins-pipelines/upgrade-with-raft/rolling-upgrade-centos8-with-raft.jenkinsfile
jenkins-pipelines/upgrade-with-raft/rolling-upgrade-debian11-with-raft.jenkinsfile
jenkins-pipelines/upgrade-with-raft/rolling-upgrade-ubuntu22.04-with-raft.jenkinsfile

In commit https://github.com/roydahan/scylla-cluster-tests/commit/ae7c72858034e350637a9d0cdffe593be88ddc61 the trigger was
changed to run only with 2022.2 as a base version. However, the
format that was used is wrong and the tests failed with the error
"couldn't find version". this format works.

Fix base trigger

---

sdcm/nemesis.py

Temporary disable disrupt_end_of_quota_nemesis due to issue https://github.com/scylladb/scylla-enterprise/issues/3736 won't be handle meanwhile

fix(nemesis): disable end_of_quota nemesis

---

sdcm/tester.py
sdcm/utils/nemesis_utils/indexes.py

Those operation on a busy/loaded setup can take longer then the default 60s we have for CQL sessions.
this change is defaulting those operation to 10m timeout

fix(index/mv): enlarge timeout on creation of Indexes/MVs

---

sdcm/utils/common.py

in e592c1ff662c4c7324a7cbef597d57135992e603 sesion timeout was set to 5min in `get_any_ks_cf_list`, but inside `PageFetcher` it was hardcoded 30s wait for the first page.
this change align that wait with the future/session timeout

fix(PageFetcher): wait for first page correctly

---

sdcm/nemesis.py

in PR #7016 there was a change that drop this part from the code without it, we can get into case that nemesis which are calling this function directly, might leave some nodes mark with `running_nemesis` while no cleaup code can figure it out, and would unmark only the current target selected.
Fixes: #7220

fix(nemesis): `set_target_node` should first give up current target

---

sdcm/nemesis.py

the thread running the reapair seems to be retring the command and there no enough verbosity to see if that's really thre case
removing any retries, and add verbose
Ref: #7226

fix(disrupt_abort_repair): enable verbose for repair command

---

sdcm/reporting/tooling_reporter.py
sdcm/stress_thread.py
sdcm/tester.py

This commit adds a helper class and an interface to report versions of
various tools used in SCT test runs. Currently, the example
implementation includes support for reporting scylla's python-driver
version to both log and argus. Each class receives a node and
(optionally) an argus client and then user calls .report() method to
collect the data (tool implementation specific, for other tools the plan
is to use node.remoter to get specific versions and report them as
'node.name/tool_version' to both log and argus.
Task: scylladb/qa-tasks#1543

feature(sdcm/reporting): Initial tooling version reporting

---

sdcm/utils/database_query_utils.py
unit_tests/test_utils_database_query_utils.py

25d8252 introduced getting the timeout of the future been returned from `execute_async`, it was tested and working o.k. except one path that `fetch_all_rows` was given `timeout=None` (which is the default)
then `fetch_all_rows` blindly put the `None` into
`session.default_timeout`, we never want unlimited timeout set.
fix is to not set `default_timeout` with `None`
Fixes: #7232

fix(fetch_all_rows): handle default `timeout=None` correctly

---

jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-grow-shrink-tablets.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-grow-shrink-tablets.jenkinsfile
jenkins-pipelines/performance/scylla-master/weekly-enterprise-performance-trigger.xml
jenkins-pipelines/performance/scylla-master/weekly-master-performance-trigger.xml

this introduce one pipeline across both OSS/enterprise that would enable tablets on the latency during grow shirnk case

feature(tablets): add trigger for one tablets case in weekly runs

---

jenkins-pipelines/operator/functional/weekly-trigger.xml

Updates:
- Make the parameter `k8s_enable_tls` be set to `false` value. Existing `true` is a mistake.
- Use proper CI jobs with `-test` suffix which get generated by SCT.
Doing so stop using CI jobs without that prefix which were created manually.
- Start triggering the `functional-eks-arm-test` weekly because
`Arm` support will be part of the `scylla-operator-v1.12` release.

fix(k8s-ci): make weekly triggers use proper CI jobs and it's parameters

---

sdcm/cluster.py

In the `start_kms_key_rotation_thread` it is possible to face the situation when the `nodetool cfstats` command fails (i.e. during `upgrade` test).
And we do not handle the case when it fails leading to the following error:
```
File "scylla-cluster-tests/sdcm/cluster.py", line 4371, in _rotate_kms_key
cf_stats = target_node._parse_cfstats(res.stdout)
AttributeError: 'NoneType' object has no attribute 'stdout'
```
So, handle the case of the 'None' value as a return value for the call of the `target_node._parse_cfstats` function.
Note that, in good case, we should fix SCT the way that a node that is being upgraded should not be picked up by the KMS encryption checks and node upgrade should wait while the KMS encryption check finishes (several minutes).
- …

improvement(kms): improve KMS enc-on checks when nodetool cfstats fails

---

mgmt_cli_test.py
sdcm/mgmt/cli.py
sdcm/mgmt/operator.py

There is long lasting issue in Scylla https://github.com/scylladb/scylladb/issues/7206#issuecomment-689598343
which causes Scylla to fallback the SSL port to non-SSL one when the encryption on session is enabled, but SSL port is not defined in config.
Manager sanity tests checks if the healthcheck works with encryption enabled, but at the same time, the scylla configuration used for this test, doesn't specify SSL port (so, it fallsback to non-SSL).
See the scylla.yaml from test
```
alternator_enforce_authorization: false
api_address: 127.0.0.1
api_doc_dir: /opt/scylladb/api/api-doc/
api_port: 10000
api_ui_dir: /opt/scylladb/swagger-ui/dist/
audit: table
audit_categories: DCL,DDL,AUTH,ADMIN
auto_bootstrap: true
batch_size_fail_threshold_in_kb: 1024
batch_size_warn_threshold_in_kb: 128 …
```

fix(manager_cli): set --force-non-ssl-session-port if encryption enabled but port not defined

---

functional_tests/scylla_operator/test_functional.py

In the `test_deploy_quasi_multidc_db_cluster` K8S functional test we create 2 additional namespaces and in the end of the test delete it. 
The problem with it is that we can get random command timeouts there still having the expected effect - deleted namespaces.
So, add try-catch block for second namespace too because it also happens to fail.
Also, do use `return None` in the end of the main logic before cleanups to avoid propagation of cleanup exceptions as test results.

improvement(k8s): stabilize namespace deletions in quasi-multidc test

---

docker/env/hydra.sh
sct.py
sdcm/keystore.py
sdcm/utils/aws_utils.py

this would complicate the sisuation once we need
want to use diffent aws profiles, so this move into `sct.py` itself, where we'll be able to even do that selectivly  as needed, or push is down further to places it's gonna be used (i.e. no every command need
validating/downloading those)

fix(hydra): remove call to awscli to download keys

---

configurations/tablets_multidc_multirack.yaml
jenkins-pipelines/master-triggers/tablets_weekly_trigger.xml
jenkins-pipelines/oss/tablets/longevity-multidc-multirack.jenkinsfile

https://argus.scylladb.com/workspace?state=WyJhZjVkYmYyOS0wMjYwLTRmNzktOGNjYS1hZDVhZWUyMWVjM2EiXQ (currently fails)

New trigger for tablets longevities and new multi dc and multi rack tablets longevity

---

sdcm/cluster.py
sdcm/utils/health_checker.py
sdcm/utils/raft/__init__.py
sdcm/utils/raft/common.py
upgrade_test.py

Raft feature is enabled by default starting from
scylla 5.5 (master) and options consistent-cluster-management is
depricated by default.
Added to new checks for scylla version on node. If scylla version
is >= 5.5, always enable raft, otherwise keep old logic based on
consistent-cluster-management flag
scylla version 5.5:
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-100gb-4h-no-raft/6
scylla version 5.4:
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-100gb-4h-no-raft/7
scylla version 5.4 with disabled raft
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-100gb-4h-no-raft/8
All jobs are passed
- …

fix(raft): Raft always enabled

---

sdcm/cluster.py

this call was add long ago for unclear reasons
probably try to make sure we won't be asked questions during apt commands.
recently it's failing like the following:
```
error: Cannot find a question for debconf/frontend
```
while still no causing any issue for any tests,
so we going to remove this call out
Fixes: #6443

fix(update_repo_cache): stop calling `debconf-set-selections`

---

sdcm/cluster.py

Reverts scylladb/scylla-cluster-tests#7246

Revert "fix(update_repo_cache): stop calling `debconf-set-selections`"

---

configurations/raft/enable_raft_experimental.yaml

new raft experimental feature flag name is consistent-topology-changes.
- [longevity-schema-topology-changes-12h-with-raft-test](https://jenkins.scylladb.com/job/scylla-master/job/raft/job/longevity-schema-topology-changes-12h-with-raft-test/3/console) - Passed
- [longevity-mv-si-4days-test](https://jenkins.scylladb.com/job/scylla-master/job/raft/job/longevity-mv-si-4days-test/3/) - Failed by reason not related to fix
- [longevity-100gb-4h-with-raft-test](https://jenkins.scylladb.com/job/scylla-master/job/raft/job/longevity-100gb-4h-with-raft-test/17) - Passed

fix(raft-exp-yaml): rename raft experimetal feature flag

---

defaults/test_default.yaml
docs/configuration_options.md
functional_tests/scylla_operator/test_functional.py
sdcm/cluster_k8s/__init__.py
sdcm/cluster_k8s/mini_k8s.py

Also, stop specifying our own scylla version which gets used as a backend for the scylla-manager. Rely on the default value.
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-functional-eks/71
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-functional-k8s-local-kind-aws/324

improvement(k8s): use newest scylla-manager version - 3.2.6

---

sdcm/utils/get_username.py
vars/artifactsPipeline.groovy
vars/createArgusTestRun.groovy
vars/createSctRunner.groovy
vars/jepsenPipeline.groovy
vars/longevityPipeline.groovy
vars/managerPipeline.groovy
vars/perfRegressionParallelPipeline.groovy
vars/provisionResources.groovy
vars/rollingOperatorUpgradePipeline.groovy
vars/rollingUpgradePipeline.groovy
vars/runSctTest.groovy

This commit adds a new job parameter to job pipelines intended to be
filled by job automation - requested_by_user. This allows SCT to
properly track resources if a job was started by a third party API
call, e.g. through Argus.
Task: scylladb/qa-tasks#1612

improvement(get_username.py): User impersonation for automated builds

---

sdcm/cluster.py
sdcm/remote/remote_file.py
sdcm/utils/docker_utils.py
unit_tests/test_remoter.py

Remove all unneeded sudo usage from the flow of running
a test with docker backend
* mostly from the monitoring stack that we run locally
Ref: https://github.com/scylladb/scylla-cluster-tests/issues/7251

fix(docker-backend): remove all sudo usage from the flow

---

sdcm/audit.py

Error 
`ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to alternator:8080` 
may be received during Scylla restart while `toggle_audit` nemesis.
This is a cosmetic thing, since our alternator setup doesn't a full fledged load balancer. So we will  ignore this error.
The error received in longevity-alternator-3h-test (https://argus.scylladb.com/test/1ebc75a8-1976-412b-8aaa-38fdaecd54b7/runs?additionalRuns[]=66b70923-5a26-42aa-a7fa-97d6d07bec67).

fix(audit): add 'ignore_ycsb_connection_refused' to audit config

---

sdcm/cluster.py

There's an issue with recent ubuntu images that fail on setting `debconf-set-selections`. Remove it and add proper apt settings when installing packages.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6443

fix(install_packages): add proper frontent and options

---

utils/cloud_cleanup/aws/clean_aws.py
utils/cloud_cleanup/azure/clean_azure.py

In case there's no keep_action tag set we stop by default - I suppose we should be terminating instances to avoid growing number of stopped instances.

fix(cleanup): make cleanup terminate by default

---

sdcm/sct_events/setup.py
unit_tests/test_events.py

since scylladb/scylladb#15672 was closed, and the issue long fixed on master, we don't need this filter
and not the test logic testing the filter.
Ref: https://github.com/scylladb/scylladb/issues/15672

fix(test_default_filters): remove unneed log filter

---

sdcm/nemesis.py

Changing the SkipPerIssue that memory_stress nemesis is skipped from the SCT issue to the actual issue that causing the tests to fail. Leaving the comment to refer to the SCT issue where the discussion is held.

fix(disrupt_memory_stress): Change the SkipPerIssue to actual issue

---

sdcm/cluster.py

Due to the K8S specifics, we may lose `apt update` cmd call results after a pod recreation.
So, it means running not recent Scylla docker images we may get errors like following:
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/i/\
iptables/libxtables12_1.8.7-1ubuntu5.1_amd64.deb  404  Not Found [IP: <some-ip>]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
So, do `apt update` in the `install_package` function running on K8S.
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-functional-eks/72

fix(k8s): update pkg info before installing packages inside of K8S pods

---

sdcm/report_templates/results_performance.html
sdcm/report_templates/results_performance_baseline.html
sdcm/results_analyze/__init__.py

Often when analyzing perf results emails, test_id might be needed to e.g. restore monitor.
This adds test_id to email reports.

improvement(perf-report): added test_id to perf regression reports

---

sdcm/cluster.py
unit_tests/test_cluster.py

`get_nodetool_status` method was assuming at least 2 spaces after `host id` field which is not true anymore (or never was).
Fixed regexp for getting nodetool status fields and added new unit test for such caase.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7274

fix(cluster): fix get_nodetool_status

---

sdcm/cluster_k8s/__init__.py

With merge of the (https://github.com/scylladb/scylla-cluster-tests/pull/6773) PR the static loaders became broken with the following error:
```
File "sdcm/cluster_k8s/__init__.py", line 3140, in add_nodes
self.k8s_clusters[current_dc_idx].debug(
AttributeError: 'EksCluster' object has no attribute 'debug'
```
So, fix it by using missing `log` attr.

fix(k8s): make static loaders work

---

jenkins-pipelines/master-triggers/tablets_weekly_trigger.xml

Since one of the scenarios that are triggered is multi dc, we can't pass on the region param. Also chose to use OSS master instead of enterprise and kept db and monitor nodes alive

fix(tablets_weekly_trigger.xml): changed predefined properties

---

sdcm/utils/aws_peering.py
sdcm/utils/aws_region.py

This commit is a next step of a major refactoring (https://github.com/scylladb/scylla-cluster-tests/pull/6575) of how to configure and control an address goes to which interface.
We were doing it for the network nemesis cases, but it complicated the setup, and forced 
us to use public networks, and listen on 0.0.0.0, which wasn't exactly target and not as 
recommended in Scylla.
This commit present changes that allow to create a few subnets in every availability zone
(or region/zone by request). With those subnets we'll be able to create undependent networks 
on the instance and cover more complex networking setup.
Primary and secondary subnets are connected to its own route tables.
All primary subnets of one region are connected to one route table.
All secondary subnets of same region …

improvement(aws region): configure region with few subnets

---

sdcm/nemesis.py

When the current internode_compression value in the scylla.yaml is "none", it is represented as None when being read by python. So, when get_internode_compression_new_value_randomly tries to find the current value of internode_compression in the values list ['dc', 'all', 'none'] it cannot find it, since the none in the list is a string. As a result, the value of the new internode_compression chosen by the nemesis could be 'none' again, and thus it has not changed at all, and the nemesis did not execute its primary function.

fix(RollingConfigChangeInternodeCompression): properly identify None

---

sct_scan_issues.py
sdcm/utils/issues.py

By doing following changes:
- Make it skip scanning files which are located in the virtual environment directories.
- Transform `scylladb/scylla` to `scylladb/scylladb` to avoid automatic redirections which lead to following useless output:
```
nemesis.py:3605: SkipPerIssues(['https://github.com/scylladb/scylla/issues/6522', 'self.tester.params'])
Following Github server redirection from /repos/scylladb/scylla/issues/6522 to /repositories/28449431/issues/6522
Following Github server redirection from /repos/scylladb/scylla/issues/6522 to /repositories/28449431/issues/6522
```
Instead it will look like following:
```
nemesis.py:3605: SkipPerIssues(['https://github.com/scylladb/scylla/issues/6522', 'self.tester.params'])
``` …

fix(sct.py): make `scan-skip-issues` more smart

---

test-cases/microbenchmarking/amazon_perf_simple_query_x86.yaml

since c6i instances didn't had instructions_per_op metric we needed, we are switching to the c7i instances

fix(perf_simple_query_x86): switch to c7i.large

---

sdcm/cluster_k8s/__init__.py

Before we were supporting only 'user/project:version' value structure for operator docker images.
If we provide "sha" part or registry site then it gets incorrectly parsed and we get failures provisioning scylla-operator.
So, fix it by properly splitting input lines.

fix(k8s): allow to specify full registry path for operator images

---

unit_tests/lib/events_utils.py
unit_tests/test_events.py

since this test is depened on github API calls, and we are hitting the rate-limitting for them a bit too often now.
moving this test to integration test, and removeing the event default filter code from the test code,
so non of the test would be using it.

fix(test_default_filters): take it out of unittest

---

configurations/network_config/two_interfaces.yaml
sct.py
sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/provision/network_configuration.py
sdcm/sct_provision/aws/cluster.py
sdcm/sct_provision/aws/instance_parameters_builder.py
sdcm/sct_provision/aws/user_data.py
sdcm/sct_runner.py
sdcm/utils/aws_builder.py
sdcm/utils/aws_utils.py

This PR is a next step of a major refactoring (https://github.com/scylladb/scylla-cluster-tests/pull/6575) .
For this goal the second subnets were created in all supported by SCT regions and each availability zone. [This commit](https://github.com/scylladb/scylla-cluster-tests/pull/7273/commits/71e9e924f72c059d898b86716a79bfe5bcd30dc2) provides availability to configure regions with 2 (for now) subnets in each AZ.
Current PR presents ability to configure the instances (DB nodes, loaders, SCT runner) with two network interfaces on different subnets. This will allow us to cover complex network setups in the tests 
Task: https://github.com/scylladb/qa-tasks/issues/1217 
**This PR is depended by https://github.com/scylladb/scylla-cluster-tests/pull/7273. We need to re-base them together (in …

improvement(cluster): configure and use independent network interfaces in AWS tests

---

test-cases/artifacts/oel81.yaml

the image being used doesn't support the i4i family we are reverting back to i3
Ref: scylladb/scylla-cluster-tests#7271

fix(oel8): revert usage of i4i

---

configurations/rolling-upgrade-alternator.yaml
sdcm/utils/docker_remote.py
sdcm/ycsb_thread.py
test-cases/features/alternator-ttl/longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus.yaml
test-cases/features/alternator-ttl/longevity-alternator-4m-scan-36m-ttl-8m-grace-sisyphus-rewrite-expired-data.yaml
test-cases/features/alternator-ttl/longevity-alternator-4m-scan-36m-ttl-no-lwt-8m-grace-sisyphus.yaml
test-cases/features/alternator-ttl/longevity-alternator-4m-scan-multiple-ttl-8m-grace.yaml
test-cases/features/alternator-ttl/longevity-alternator-disable-enable-ttl.yaml
test-cases/features/alternator-ttl/longevity-alternator-ttl-big-dataset.yaml
test-cases/features/alternator-ttl/longevity-alternator-ttl-large-writes.yaml
test-cases/features/alternator-ttl/longevity-alternator-ttl-lwt.yaml
test-cases/longevity/longevity-alternator-200GB-48h.yaml
test-cases/longevity/longevity-alternator-3h-multidc.yaml
test-cases/longevity/longevity-alternator-3h.yaml
test-cases/longevity/longevity-alternator-streams-100gb-12h.yaml
unit_tests/conftest.py
unit_tests/lib/alternator_utils.py
unit_tests/test_ycsb_thread.py

since moby/moby#47538, dns isn't forward automaticlly into internal networks, and we need to create a specfic network that has a gatway, for it to work as we expect and forward DNS requests out
Fixes: #7302
Ref: https://github.com/moby/moby/pull/47538

fix(alternator-dns): move ycsb runs into it's own docker network

---

sdcm/utils/alternator/api.py
unit_tests/test_ycsb_thread.py

those tests we skipped long time ago, and need
several fixs to be operational again

fix(alternator): enable back the ycsb based tests

---

configurations/nemesis/additional_configs/docker_backend_local.yaml

When trying to execute Nemesis test cases on Docker backend locally, using the default test configuration [longevity-5gb-1h-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ba3f94836b1f6e75e7c3a90b488e312fc83f726f/configurations/nemesis/longevity-5gb-1h-nemesis.yaml), the load eventually kills the local env/laptop, as scylla claims all available HW resources (particularly memory).
The change adds a dedicated test configuration to be able to run individual nemesis test cases on Docker backend  locally, on an average-spec laptop/computer with 32GB of RAM.
The tuned parameters comparing to the default config are:
- reduced data size from 5GB to 1GB
- rate limiting / throttling applied to c-s and s-b stress commands, to keep load per db instance within 50-70% range during a …

improvement(docker-backend): add a dedicated test config for local runs

---

sdcm/sct_runner.py

We no longer need to add `keep-alive` network tag for sct runners on GCE as `keep` metadata with proper value is added anyway. Having `keep-alive` network tag prevents cleanup script from properly and timely cleanup of these runners.

fix(sct-runner): remove keep-alive network tag on GCE

---

configurations/nemesis/additional_configs/docker_backend_local.yaml
sdcm/cluster.py
sdcm/utils/remote_logger.py
sdcm/utils/remotewebbrowser.py

* fix case back to older monitoring stack, cause of https://github.com/scylladb/scylla-monitoring/issues/2246
* rate limit also prepare phase
* disable argus reporting for this case

fix(docker): multiple fixes to docker_backend_local.yaml

---

sdcm/stress/base.py

When we use `round_robin=true` we provide list of one loader node to the stress commands handling code then use `enumerate` func incorrectly providing the index as `0`.
Fix it by switching usage of the `enumerate` func to the `node_index` attribute of loader node objects.
Side effect is that in all `round_robin=false` cases the first index will be `1`, not `0` as has always been.
Fixes: #7277

fix(loaders): use proper loader indexes when `round_robin` is enabled

---

configurations/perf-regression-upgrade.yaml
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
test-cases/performance/perf-regression-upgrade.yaml

In order to stabilise performance upgrade test, increase number of nodes by 3. Doubled c-s throughput limit to adjust cluster load accordingly.
refs: https://github.com/scylladb/scylladb/issues/16189

test(perf): increase n_db_nodes by 3 in perf upgrade test

---

sdcm/cluster.py
sdcm/cluster_azure.py
sdcm/cluster_docker.py
sdcm/cluster_k8s/__init__.py
sdcm/utils/raft/common.py

Before this change we were running `node_setup` methods serially.
In majority of cases the time gap is not critical.
But there are cases such as setting up `hybrid disks` on GCE
where setup of disks on a single DB node takes more than 20 minutes.
And we have setups with 6 nodes.
So, mitigate this waste of time and money by parallelizing the setup of DB nodes
and do serially only startup where we have limitation for bootstrap stage.

improvement(cluster): setup nodes in parallel

---

sdcm/stress_thread.py

This change is addition to the already merged PR (https://github.com/scylladb/scylla-cluster-tests/pull/7326) which fixed only part of loaders.
So, do it for every loader by fixing second place with wrong loader indexes usage.
Fixes: #7277

fix(loaders): use proper loader indexes - part2

---

docker/env/hydra.sh

Used in an error case.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7337

'die' function was missing from hydra.sh

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_k8s/__init__.py
unit_tests/dummy_remote.py
unit_tests/test_cluster.py
unit_tests/test_scylla_yaml_builders.py
unit_tests/test_seed_selector.py
unit_tests/test_utils_common.py

When the test runs in multi DC environment it is helpful to get information
about the node: in which datacenter and rack this node is located.
For this goal update node information the the log. So it is not needed to
search for this through the log
Task: https://github.com/scylladb/qa-tasks/issues/1180
Example:
```
< t:2024-03-31 16:00:58,727 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-03-31 16:00:58.725: (CassandraStressEvent Severity.NORMAL) period_type=end event_id=22a4b06b-d208-4492-99e8-73d0b392d38f duration=22s: 
node=Node lwt-longevity-multi-dc-24h-add-data-loader-node-969d36e8-3 [35.172.234.245 | 10.12.3.80] (dc name: us-east-1)
```
```
< t:2024-03-31 14:20:17,074 f:cluster.py      l:1081 c:sdcm.cluster_aws     p:INFO  > 
Node …
```

improvement(log info): add datacenter and rack info

---

jupyter/provision-test.ipynb

When running test on jupyter using notebook provided in SCT, it fails with circular error.
Quick fix for that by importing `InstanceLifecycle` before SCT does it.

fix(jupyter): fix import problem

---

sdcm/utils/s3_remote_uploader.py

boto3 client `upload_fileobj` method requires file-like object that returns `True` for `readable` method. It started to be required after boto3 lib update.
Made `readable` method to return always `True` for `SshOutAsFile` class.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7344

fix(s3_uploader): fix class for mimicking a file

---

docker/scylla-sct/centos/Dockerfile
docker/scylla-sct/ubuntu/Dockerfile
sdcm/cluster.py
sdcm/utils/sstable/load_utils.py

In docker backend environment the scylla services are controlled by supervisord.
At the moment the scylla services configuration files in Docker images do not have
user attribute specified (opposite to backends where systemd controls the processes -
there the user is explicitly specified in systemd unit files).
As a result the file permissions of data that the services create are of a user
that starts the processes. In the tests it is usually root user.
Some Nemesis scenarios, when are executed for Docker backend, try to update scylla data on behalf
of 'scylla-test' user and fail with 'permission denied' error.
The change sets the user attribute in scylla-sct Docker files, to explicitly run scylla
services on behalf of 'scylla' user.
It also reverts few changes introduced in the past, …

fix(docker-backend): start Scylla server as 'scylla' user

---

docs/docker-backend-nemesis.md

After all individual Nemesis cases are validated on Docker backend we can summarize their status in one place for later reference.
The related task: https://github.com/scylladb/qa-tasks/issues/1636

docs(docker-backend): summary of Nemesis validation on docker backend

---

performance_regression_test.py

When using tablets, splitting them is treated as compaction and may take very long. This causes latency during grow-shrink perf test with tablets to fail.
Fix is by prolonging this timeout so there's enough room for that.

fix(perf): prolong wait for no compactions

---

jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-simple-query-microbenchmark.jenkinsfile
jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-simple-query-microbenchmark_x86_64.jenkinsfile

Each release should run perf-simple-query performance jobs to find regressions in that matter. Especially important for enterprise releases where error in PGO profiles update may cause regressions and these tests find it easily.
refs: https://github.com/scylladb/qa-tasks/issues/1643

test(perf): added perf-simple-query perf jobs to release

---

sdcm/cluster.py

since the path of io.conf is diffrent when using offline installers this print was move around, and now seems to be broken:
```
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo cat /etc/scylla.d/io.conf'
Exit code: 1
Stdout:
Stderr:
cat: /etc/scylla.d/io.conf: No such file or directory
```
this commit introduce using `add_install_prefix` so the path would be correct

fix(offline_installer): print io.conf from correct path

---

sdcm/utils/remotewebbrowser.py

cause of supporting docker backend, we introduce a check of the backend to decide if tunnelling is needed.
this broke the log collection phase, since `CollectingNode` doesn't have `parent_cluster` or access to SCT configuration.
for now we can assume if we don't have `parent_cluster` we should enable tunneling even that tunneling is only needed when working from diffrent regions (or from local env)
Fix #7323

fix(RemoteBrowser): stop assuming `parent_cluster` exists

---

sdcm/remote/base.py
sdcm/remote/remote_base.py

When investigating SCT run, logs often I miss information about node command is executed on.
Adding `<self.hostname>: ` prefix to most log usages in `RemoteCmdRunner` class so it's easier to debug runs.
Example result line:
`<172.17.0.2>: Running command "dpkg -l |grep scylla|awk '{print $2 "-" $3}'"...`

improvement(logging): add hostname info to RemoteCmdRunner

---

sdcm/utils/user_profile.py

For the moment, when we use c-s user profiles in CI jobs we get following error:
```
FileNotFoundError: User profile file templated_tables_mvs3ysgyis.yaml \
not found under /home/ubuntu/scylla-cluster-tests
```
The file that was attempted to be found under the SCT dir has dynamically added suffix `s3ysgyis` and was doomed to be not found.
So, fix it by not trying to find dynamically created files in the `/tmp` dir and return it's path `as-is`.

fix(cs-profiles): use user profiles located at `/tmp` be used `as-is`

---

defaults/aws_config.yaml
defaults/azure_config.yaml
defaults/gce_config.yaml
defaults/k8s_gke_config.yaml
defaults/test_default.yaml
sct_ssh.py
sdcm/sct_config.py
test-cases/manager/manager-backup-1TB-gce.yaml
unit_tests/test_config.py

Centos-7 is EOL.
So, switch our loader and monitor VMs to use `ubuntu` images.
- aws, prepared loaders: [scylla-staging/valerii/vp-longevity-10gb-3h-test#75](https://argus.scylladb.com/test/631c0991-5548-434e-b7a3-f47eb2db8777/runs?additionalRuns[]=bb3d51d9-31d3-4729-95ed-e3a4525405a1)
- aws, docker loaders: [scylla-staging/valerii/vp-longevity-10gb-3h-test#76](https://argus.scylladb.com/test/631c0991-5548-434e-b7a3-f47eb2db8777/runs?additionalRuns[]=ad0b5ecb-d77c-492b-9e12-9c0b0c1d3f3e)
- gce: [scylla-staging/valerii/vp-longevity-10gb-3h-gce-test#16](https://argus.scylladb.com/test/f20862ff-cf95-44cf-8d5a-78da3d9b1f0e/runs?additionalRuns[]=2a74c62e-ae2b-44d6-9c6d-06bf4d6f5b39)
- azure: [scylla-staging/valerii/vp-longevity-10gb-3h-azure-test#19](https://argus.scylladb.com/test/bc3f0da1-8e0 …

improvement(distro): use ubuntu for loader and monitor nodes

---

sdcm/utils/scylla_metrics_ctrl.py

For testing purposes we tried to disable metrics to see performance impact of collecting them. This is the code to disable metrics with api

improvement(metrics): allow to disable node metrics

---

mgmt_cli_test.py
sdcm/mgmt/cli.py

Manager jenkins CI consist of separated flows per different manager version.
https://jenkins.scylladb.com/view/scylla-manager/
In one of the recent commits to manager-3.2 (and master)  675e26fdd7ac91903c960cd62907ff908466adc8 , we introduced manager version check.
Unfortunately, manager on master branch keeps the version "Snapshot", so the code guarded with the version check is not applied on manager master jenkins CI.
This PR addresses this issue.

Support for manager-master jenkins pipeline

---

utils/cloud_cleanup/azure/clean_azure.py

Monitor instances specify `keep_action` as empty value. This is making the script to stop these instances instead of termination.
Set `keep_action` to `terminate` if was empty, so instances are terminated by default.

fix(cloud-cleanup): enforce terminate as default for Azure

---

artifacts_test.py
sdcm/utils/adaptive_timeouts/load_info_store.py

Check node exporter liveness was presented by https://github.com/scylladb/scylla-cluster-tests/ pull/6885/commits/a63b1f1ac31c1bd85385b69968997d1c204b4473 As part of this available memory is validated ('node_memory_MemAvailable_bytes' metric). Later was found that available memory is 0 in centos8-arm test (issue scylladb/scylla-enterprise#3989). The issue was closed and won't be handled. It was decided to replace 'node_memory_MemAvailable_bytes' metric with another - 'node_boot_time_seconds'.
Task: https://github.com/scylladb/qa-tasks/issues/1658

fix(artifact test): check 'node_boot_time_seconds' instead available memory

---

sdcm/provision/common/configuration_script.py
sdcm/sct_provision/aws/user_data.py

Setup script is executed during cloud init phase and later it is run again during resources `init` phase and takes time.
Skip rerunning init script if was already executed by verifying if 'lock' file is present (created at the end of init script).
refs: https://github.com/scylladb/scylla-cluster-tests/issues/7242

improvement(init): skip instance setup script if already ran

---

sdcm/sct_runner.py
sdcm/utils/common.py

Fixes:
- GCE, translate boolean tag value to str with lowercase.
- Azure, use proper API method for setting tags - `update_at_scope`. It will allow us to fix following error:
```
(InvalidRequestContent) The request content was invalid and could not \
be deserialized: 'Could not find member 'operation' on object of type \
'TagsDefinition'. Path 'operation', line 1, position 13.'.
```
- All, make `logs_collected` bool attr have correct value instead of the `false positive` all the time where any non-empty str value was considered to be `True`.
Fixes: #7375
Fixes: #7376
- [scylla-staging/valerii/vp-longevity-10gb-3h-test#79](https://argus.scylladb.com/test/631c0991-5548-434e-b7a3-f47eb2db8777/runs?additionalRuns[]=96d5419b-a234-4fcd-9072-11132090f56a)
- …

fix(set-tags): fix setting of tags onto SCT runners

---

sct.py
sdcm/utils/issues.py

since we are hitting this rate limit quite often, we should assume the issue we are looking for it opened, and not like we return today None, we translated to close / non existing issue
in this way we won't be that much affect from the rate limiting until we can have some work around it (centralized cached of it)

fix(issues): revert logic when hitting github ratelimit

---

configurations/tablets-initial-32.yaml
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-grow-shrink-tablets.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-grow-shrink-tablets.jenkinsfile

Grow-shrink cluster scenario perf test with tablets inserts 650GB of data. This triggers split tablets in steps from 8->16->32->64 or even to
128. Splitting takes time and prolongs the test significantly.
Commit is about increasing initial tablets for ks created by c-s to 32 (8x4) so test is faster and we still can observe splitting to 64 and see effects of this dynamic split during the test.

test(perf): set initial tablets to 32 in perf tests

---

sdcm/utils/raft/__init__.py

Cluster topology consistent means that token ring and group0 doesn't have garbage host ids and host id as non-voter after topology operation done.
Add to check that non-voter nodes stay in cluster.
- [Job passed with BootStreamingErr](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-100gb-4h/91/)

fix(is_cluster_topology_consistent): Make sure non-voters don't remain in the group0.

---

unit_tests/dummy_remote.py

in PR #7326 `node_index` was used in basis of stress object LocalNode was missing that property, hence lots of tests were failing

fix(integration_tests): add node_index to LocalNode

---

configurations/nemesis/longevity-5gb-1h-nemesis.yaml
defaults/severities.yaml
defaults/test_default.yaml
sdcm/cluster.py
sdcm/sct_config.py
sdcm/sct_events/teardown_validators.py
sdcm/teardown_validators/__init__.py
sdcm/teardown_validators/base.py
sdcm/teardown_validators/sstables.py
sdcm/tester.py
sdcm/utils/common.py
test-cases/longevity/longevity-parallel-schema-changes-12h.yaml

We want to validate scylla cluster after longevity test to verify if it's in correct state. Aiming for checks that require no load and/or affect system performance and/or can be done once after the test.
Implemented first validator that verifies if sstables are not corrupted using `nodetool scrub`. In case corruption is found, quarantined by scrub sstables are uploaded to s3 and proper error event is raised with link.
refs: https://github.com/scylladb/qa-tasks/issues/1577

feature(teardown-validators): nodetool scrub validate

---

defaults/aws_config.yaml
defaults/gce_config.yaml
docs/monitoring-images.md
sdcm/cluster.py
sdcm/cluster_docker.py
sdcm/logcollector.py
sdcm/monitorstack/__init__.py
utils/copy_ami_to_all_regions.sh

* change aws to use prepare image for monitoring 4.6.2
* change the code to be able to skip installations of packages and monitor
Ref: scylladb/qa-tasks#993

feature(monitoring): switch to use prepared images

---

defaults/test_default.yaml
docker/latte/Dockerfile
docker/latte/README.md
unit_tests/test_config.py

Using current approach we minimize latte image size as following:
- Compressed variant from `580.71Mb` to `34.96Mb`.
- Not compressed variant from `1.63Gb` to `92.7Mb`.
Also, switch the default latte image to be the latest available latte package version built using the new dockerfile added here.

improvement(loader-latte): build small latte image

---

vars/getJobTimeouts.groovy

This fixes an issue with certain jobs that spend a lot of time on
prepare stress stage / setup stage, as current calculation results in a
way closer timeout to the timeout thread, leading to interruptions
Fixes #7385

fix(getJobTimeouts.groovy): Increase testStartupTimeout to 80 minutes

---

sdcm/utils/common.py

Currently logging scheme confuses about not being able to delete placement groups, while it is working correctly due to retrying.
Fix logging to have less confusing info logs.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6742

fix(logging): improve logging for deleting placement groups

---

sdcm/reporting/tooling_reporter.py
sdcm/stress_thread.py

This commit adds caching for cassandra-stress versions (drivers
included)
Fixes #7276

improvement(tooling_reporter.py): Report cassandra-stress version once

---

sdcm/sct_config.py
sdcm/test_config.py

in order that argus would be able to know what is the target version for a run, as soon as the test start (including the target versions for upgrade), so we can filter better even in the case of error to provision/configure scylla, or failure to start the upgrades.

fix(sct_config): send argus resolved scylla_versions

---

vars/getJobTimeouts.groovy

Reverts scylladb/scylla-cluster-tests#7393

Revert "fix(getJobTimeouts.groovy): Increase testStartupTimeout to 80 minutes"

---

artifacts_test.py
sdcm/cluster.py

Since scylladb/scylladb#18487 scylla-jmx isn't being installed by default, hence we need to be able to run SCT without doing any of the calls to start/stop/wait/configure the JMX service
Closes: #7392
Fixes: #7397

fix(scylla-setup): stop calling scylla-jmx.service if it doesn't exist

---

sdcm/provision/user_data.py
unit_tests/provisioner/test_provision_sct_resources.py
unit_tests/provisioner/test_user_data_builder.py

To mark cloud-init scripts (e.g. configuring syslogng) as executed, we create file in /tmp dir. This is wrong as it may not sustain machine reboots.
Move cloud-init lock file (and other related files) under `/var/lib/sct` so it's kept across reboot.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7342

fix(cloud-init): make cloud init lock file kept across reboot

---

configurations/manager/ubuntu22.yaml
jenkins-pipelines/manager/ubuntu22-manager-sanity-ipv6.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-upgrade.jenkinsfile
test-cases/manager/manager-regression-ipv6.yaml
test-cases/manager/manager-regression-multiDC-set-distro.yaml
test-cases/upgrades/manager-upgrade.yaml

The PR addresses the CentOS7 deprecation changes:
- sanity tests switched to use Ubuntu image instead of centos;
- ipv6 tests switched to Ubuntu as well.
Addresses https://github.com/scylladb/scylla-manager/issues/3840

CentOS7 deprecation adjustments for manager tests

---

configurations/capacity_reservation.yaml
defaults/test_default.yaml
sdcm/cluster_aws.py
sdcm/ec2_client.py
sdcm/exceptions.py
sdcm/provision/aws/capacity_reservation.py
sdcm/provision/aws/provisioner.py
sdcm/sct_config.py
sdcm/sct_provision/aws/layout.py
sdcm/tester.py
sdcm/utils/common.py
test-cases/performance/perf-regression-latency-1TB.yaml
test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
unit_tests/provisioner/test_capacity_reservation.py

Sometimes we get failures due no capacity (also for on_demand instances) and it's hard to trigger a test at all. This is often a problem for performance tests where we use older instance types.
Introducing capacity reservation feature for AWS cloud. It works by first reserving capacity for all instance types used by test for test duration (reserves predicted max number of nodes that test may use based on test config parameters) and during instance creation uses it to spin it. In case given AZ cannot serve requested instances, it fallback to
another one until successful.

feature(provision): enable capacity reservation for aws

---

mgmt_cli_test.py
sdcm/cluster.py

Scylla manager is not immediately being aware about the Scylla node config change.
It picks up for the node configuration periodically.
This PR extends the sleep to be sure that SM is updated with the latest node config.
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/sct/job/manager-ubuntu-22-sanity/7 (PASSED)

fix(manager): wait after Scylla config change to let SM pick up the change

---

defaults/test_default.yaml
test-cases/gemini/gemini-1tb-10h.yaml
test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-3h-with-nemesis.yaml
test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-basic-3h-ics.yaml
test-cases/gemini/gemini-basic-3h.yaml

according to https://github.com/scylladb/qa-tasks/issues/1430 latest gemini jobs with ics start failing because
of timeout upon get results from oracle.
It could be related to slow instance for oracle
this PR switch oracle_scylla_version to 2023.1 and instance_type_db_oracle to i4i.8xlarge

switch oracle cluster to i4i for gemini tests

---

mgmt_cli_test.py
sdcm/cluster.py

Reverts scylladb/scylla-cluster-tests#7412
This change doesn't work with manager 3.2.7, and break all weekly runs

Revert "fix(manager): wait after Scylla config change to let SM pick up the change"

---

utils/scylla_doctor.py

'artifacts-oel81-test' failed to read vitals file that was created with sudo. 
It happened because it try to read with non-root user.
Change to use 'utils.scylla_doctor.ScyllaDoctor.run' function that knows to use correct remoter function, 'sudo' or 'run'.

fix(scylla doctor): read vitals file

---

sdcm/provision/aws/provisioner.py

When CR is not set error `AttributeError: 'NoneType' object has no attribute 'get'` when querying for cr_id. Failing provision step..
Fix by returning dict by default if az is not found in reservations (CR is not used).

fix(provision): fix when capacity reservation is not set

---

docs/bisecting-with-sct.md
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/bisect_test.py

Added bisect decorator that adds bisection functionality to given test. Used by wrapping a test case (e.g. test_write) and by provide `bisect_start_date` and optionally `bisect_end_date` (if not provided, most recent build is used as last).
Idea of the decorator is to first run a test case which should set value for `self.bisect_ref_value` which will be used for evaluation for other Scylla versions to determine regression. Then using bisection algorithm the decorator will be updating Scylla binaries, cleaning up all data and reruning test which should update `self.bisect_result_value`. When test finishes, evaluates if regression happened by comparing `self.bisect_ref_value` >= `self.bisect_result_value`.
Binaries are taken from repo files - currently works only with ubuntu/debian only. …

improvement(bisection): add bisect decorator

---

utils/scylla_doctor.py

Skip 2 collectors because 'perftune.yaml' is missed on AL2 (opened scylladb issue #18631).

fix(scylla doctor): amazon2 tests

---

sdcm/tester.py
sdcm/utils/alternator/api.py
sdcm/ycsb_thread.py

instead of writing directly into system_auth table, gonna use `CREATE ROLE` and read the salted_hash for using with alternator APIs
Fixes: #7405

fix(alternator): use CREATE ROLE for `alternator_enforce_authorization`

---

defaults/test_default.yaml

Recently scylla-tools package is not installed in scylladb docker images. This makes c-s not being installed in docker images we use for loaders.
Workaround by pinning version with c-s installed.
workarounds: https://github.com/scylladb/scylla-cluster-tests/issues/7430

fix(c-s): use 5.4.6 image for c-s

---

sdcm/provision/scylla_yaml/auxiliaries.py

Running multiDC cluster test from local machine failed to setup the cluster. Error:
```
init - Startup failed: std::runtime_error (Use broadcast_address for seeds list)
```
The problem that after presenting of new networking setup (https://github.com/scylladb/scylla-cluster-tests/pull/6575) choosing of endpoint snitch became wrong and should be 'Ec2Snitch'. It was decided to set it 'Ec2Snitch' because we do not have a case when we need to use `Ec2MultiRegionSnitch`.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7381

fix(multidc): run test from local machine

---

jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile
jenkins-pipelines/manager/centos-manager-backup.jenkinsfile
jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile
jenkins-pipelines/manager/debian11-manager-sanity.jenkinsfile
jenkins-pipelines/manager/manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-sanity.jenkinsfile
mgmt_cli_test.py
test-cases/manager/manager-regression-singleDC-set-distro.yaml

Closes https://github.com/scylladb/scylla-manager/issues/3850
Should be merged together with https://github.com/scylladb/scylla-cluster-tests/pull/7365
Since there is an issue with multiDC cluster restore when the EaR is turned on (https://github.com/scylladb/scylla-manager/issues/3829), it was decided to:
- switch them to use single-DC cluster;
- leave one test with multiDC cluster for enterprise version 2022 (no encryption feature implemented).
After https://github.com/scylladb/scylla-manager/issues/3829 resolution, multiDC cluster would be returned back.
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/sct/job/manager-master-versions-update/job/sct-feature-test-backup/
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/sct/job/mana …

Switch manager tests to run on singleDC environment

---

configurations/manager/debian10.yaml
defaults/manager_versions.yaml
defaults/test_default.yaml
unit_tests/test_sdcm_mgmt_common.py
vars/managerPipeline.groovy

Upgraded the version of Scylla used in Manager from 2022.1 (2021 for debian10) to the latest 2024.1 (2023 for debian10).
Should be merged together with https://github.com/scylladb/scylla-cluster-tests/pull/7435

fix(manager): upgrade Scylla version used in Manager to latest

---

configurations/manager/debian10.yaml
configurations/manager/debian11.yaml
configurations/manager/ubuntu20.yaml
sdcm/cluster.py

**Fixes:**
1. The cmd `apt-key add -` should be run as sudo otherwise the error `E: This command can only be used by root.` returns on Debian distro.
```
11:29:40  Command: 'sudo curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -'
11:29:40  Exit code: 1
11:29:40  Stdout:
11:29:40  Stderr:
11:29:40  Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
11:29:40  E: This command can only be used by root.
```
Failed Jenkins job - https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/debian11-sanity-test/210
2. The `monitor_branch` parameter is `null` by default. If another value is not provided in config and image differs from formal (Ubuntu), the monitor installation flow tries to download from monitoring …

Fix Manager installation on Debian

---

configurations/manager/debian10.yaml
configurations/manager/debian11.yaml
configurations/manager/ubuntu20.yaml
jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile
jenkins-pipelines/manager/debian11-manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-sanity-ipv6.jenkinsfile

Currently selected us-west-2 region doesn't contain all required AMI images what results in jobs failure.
`AssertionError: Image 'ami-09a41e26df464c548' details not found in 'us-west-2'`

ci(manager): switch singleDC jobs to us-east-1 region

---

mgmt_cli_test.py
sdcm/cluster.py

`config_cache` parameter was introduced in version 3.2.7-0.20240509, skip the parameter setup part for older versions.
Jenkins pipelines:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/sct/job/manager-master/job/sct-feature-test-backup/
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/sct/job/manager-master/job/ubuntu22-sanity-test/
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/sct/job/manager-master/job/ubuntu22-upgrade-test/

Fix the manager installation process

---

performance_regression_test.py

Performance results json is searched for `Total partitions` and `Total errors` while these don't exist, causing exception raised and full logic of `display_results` method of `PerformanceRegressionTest` class not executed.
Fix is about to select proper (not capitalized) keys: `total partitions` and `total errors`.

fix(perf): fix display_single_result method

---

configurations/manager/debian10.yaml

Closed https://github.com/scylladb/scylla-cluster-tests/issues/7453
The currently used image is outdated and has some issues with apt repos (details https://github.com/scylladb/scylla-cluster-tests/issues/7453). So, this change replaces this image with a more recent one `debian-10-amd64-20240430-1733`.

fix(manager): update debian10 image used in tests

---

sdcm/cluster.py
sdcm/cluster_docker.py
sdcm/utils/remote_logger.py
unit_tests/test_scylla_yaml_builders.py

for long we have it inside the `Distro` class, and there's no need for it on the cluster class

fix(cluster): remove deprecated `system_init` property

---

sdcm/cluster.py
sdcm/cluster_aws.py

The problem was found during IPv6 test.
IPv6 was converted to full format when parse nodetool status result. This change was represented by  https://github.com/scylladb/scylla-cluster-tests/pull/7047
But IPv6 address was not converted when collected info about nodes network interfaces (AWS).
During checking nodes status, we compare between 'nodetool status' output and node address that kept in the network_interfaces object. It fails because the IPv6 address miss leading zeros. As result the test fails with errors 'Failed to find a node in cluster by IP'
Also fix the same problem for peer and gossip output.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7447
- Add unit tests to cover my changes …

fix(cluster): ipv6 address in network_interfaces object

---

sct.py

This change updates the Junit collect stage to submit the resulting xml
file to argus, allowing Argus to store JUnit results
Fixes #7252

improvement(sct.py): Add junit argus client call

---

artifacts_test.py
configurations/arm/ubuntu2404.yaml
defaults/manager_versions.yaml
jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2404-arm.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2404-nonroot.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2404.jenkinsfile
jenkins-pipelines/oss/artifacts/artifacts-ubuntu2404-arm.jenkinsfile
jenkins-pipelines/oss/artifacts/artifacts-ubuntu2404.jenkinsfile
sdcm/mgmt/common.py
sdcm/provision/common/utils.py
sdcm/utils/common.py
sdcm/utils/distro.py
test-cases/artifacts/ubuntu2404.yaml
unit_tests/test_config.py

as part of an effort to start supporting using ubuntu 24.04 as the basis for scylla images, we are introducing a new artifact tests to cover it
Closes: scylladb/scylla-cluster-tests#7410

feature(artifacts-tests): add support for ubuntu 24.04

---

sdcm/cluster.py

failed in https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts-offline-install/job/artifacts-ubuntu2404-test/3 with the following error:
```
11:07:40  Command: 'sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" install -y python2'
```
Since in ubuntu24.04 we don't have python2 package we should skip it

fix(offline ubuntu24.04) skip python2 installation

---

vars/managerPipeline.groovy

for long time we are having this stage for most of the SCT pipelines, and manager is missing that, it could speed things up for how long the test would be taking.
also it would walk the same code paths as other test, and hopfully avoid unique issues to the manager jobs

fix(managerPipeline): add provision stage to pipeline

---

sdcm/cluster.py

We wait 60 seconds between trying cql port is taken. This makes waiting for node to be up a multiply of minute (at least minute).
Speed up by checking up status every 5 seconds.
Also simplified verification of port being used to reduce number of remoter commands run on node.
Moved reporting housekeeping to background thread as we anyway don't care much about result.
refs: https://github.com/scylladb/scylla-cluster-tests/issues/7242

improvement(speed): speed up wait db up

---

configurations/rolling-upgrade-alternator.yaml
sdcm/sct_config.py
sdcm/ycsb_thread.py
test-cases/features/alternator-ttl/longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus.yaml
test-cases/features/alternator-ttl/longevity-alternator-4m-scan-36m-ttl-8m-grace-sisyphus-rewrite-expired-data.yaml
test-cases/features/alternator-ttl/longevity-alternator-4m-scan-36m-ttl-no-lwt-8m-grace-sisyphus.yaml
test-cases/features/alternator-ttl/longevity-alternator-4m-scan-multiple-ttl-8m-grace.yaml
test-cases/features/alternator-ttl/longevity-alternator-disable-enable-ttl.yaml
test-cases/features/alternator-ttl/longevity-alternator-ttl-big-dataset.yaml
test-cases/features/alternator-ttl/longevity-alternator-ttl-large-writes.yaml
test-cases/features/alternator-ttl/longevity-alternator-ttl-lwt.yaml
test-cases/scylla-operator/longevity-scylla-operator-alternator-http-3h.yaml
test-cases/scylla-operator/longevity-scylla-operator-alternator-https-3h.yaml

PR #7422 was merged before validated, and now is failing with the following error:
```
cassandra.Unauthorized: Error from server: code=2100 [Unauthorized]
message="You have to be logged in and not anonymous to perform this request"
```
need to enable `authenticator` and `authorizer` in order to be able to create roles

fix(alternator): use admin user for role creation

---

sdcm/sct_config.py
sdcm/utils/version_utils.py
unit_tests/test_version_utils.py

This change fixes an issue where argus would receive full version
unparsed when the job starts - this leads to issues on the dashboard
page where versions have too much granularity - ignoring the new
`build_version` field inside Argus.

fix(sdcm/sct_config): Submit parsed scylla version to argus

---

unit_tests/test_base_version.py

After branching Scylla to 6.0, unit tests started to fail as recent master version changed.
Fix by update version.

fix(unit-test): fix recent master version

---

sdcm/cluster.py
sdcm/remote/base.py

When investigating parallel commands it's hard to diffirentiate their outputs. Fix to add hostname to each output line.
Also removing dozens of lines of `scylla --help` in sct logs as they don't bring us any benefit.

fix(logging): add hostname to RemoteCommandRunner output watcher

---

artifacts_test.py

since this logic of code retriving the updates from housekeeping is depended on code run by SCT to mark uuid as test.
and since commit 617026aa, this code it run in the background, and not being waited for, so we need to compensate for it here with retries
Fixes: #7487

fix(artifact-tests): retry housekeeping version checks

---

upgrade_test.py

This reverts commit f87e8c7ec371c631f92a1a6b0fad600b0c40f260.
issue scylladb/scylla#7930 was fixed long long time ago and now since scylla-java-tools isn't part of scylla installation anymore, there no `/etc/scylla/cassandra/` direcotry anymore so this hack is breaking upgrade tests
Ref: https://github.com/scylladb/scylla/issues/7930

Revert "fix(nodetool): workaround wrong placement of cassandra-rackdc.properties"

---

configurations/arm/amazon2023.yaml
jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2023-arm.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2023-nonroot.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2023.jenkinsfile
jenkins-pipelines/oss/artifacts/artifacts-amazon2023-arm.jenkinsfile
jenkins-pipelines/oss/artifacts/artifacts-amazon2023.jenkinsfile
sdcm/mgmt/common.py
sdcm/utils/distro.py
test-cases/artifacts/amazon2023.yaml
unit_tests/test_utils_distro.py

Amazon Linux 2 is gonna be deprecated in the upcoming year and we want to start our support of the next version of it
this commit introduces 5 tests:
- x86 based one, and offline installer of it
- arm64 based one, and offline installer of it
- x86 offline install non-root
Closes: scylladb/scylla-cluster-tests#7475

feature(artifact-tests): introduce Amazon Linux 2023 tests

---

mgmt_cli_test.py

Closes https://github.com/scylladb/scylla-manager/issues/3863
Since `google-cloud-cli` started to require additional package to be installed `google-cloud-cli-anthoscli`, the apt install command should come with `-y` option.

fix(manager): add -y to utils gce packages installation cmd

---

sdcm/cluster.py
sdcm/node_exporter_setup.py
sdcm/provision/common/configuration_script.py
sdcm/provision/common/utils.py
sdcm/sct_provision/region_definition_builder.py
sdcm/sct_provision/user_data_objects/syslog_ng.py

It should be faster to install syslogng-exporter during cloud-init. Replaced wget with curl to skip wget installation.
closes: https://github.com/scylladb/qa-tasks/issues/1694

improvement(speed-up): move syslogng-exporter install to cloud-init

---

unit_tests/test_base_version.py

since we run into this again and again, on every new release branch created, we shouldn't pin this test to specific one checking it's greater then current known version it enough

fix(test_base_version): stop hardcoding the current latest branch

---

sdcm/remote/base.py

Sometimes line for output  could contain '%s' or '0.0%' and this break OutputWatcher log function with error:
```
18:42:47      msg = msg % self.args
18:42:47  ValueError: incomplete format
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py",
line 449, in _process_output
watcher.submit_line(data)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py",
line 231, in submit_line
self.log.debug("<%s>: " + line.rstrip('\n'), self.hostname)
Message: '<%s>: Percent Repaired       : 0.0%'
Arguments: ('10.4.0.228',)
```
Change format for log message info
self.log.debug("%s - %s', self.hostname, line)
- Update the Readme/doc …

fix(OutputWatcher): use formatted string in log message

---

test-cases/kafka/longevity-kafka-cdc.yaml

name of a property was changed from `version` to `source` and was missed on one of the configurtion files introduce in #6946
and it started failing on test case linting right after the merge

fix(kafka-localstack): fix broken configuration file

---

configurations/arm/centos8.yaml

the AMI we had was deprecated, hence the metadata
retrvial of it fails like the following:
```
File ".../sdcm/tester.py", line 182, in wrapper
return method(*args, **kwargs)
File ".../sdcm/utils/decorators.py", line 119, in inner
res = func(*args, **kwargs)
File ".../sdcm/tester.py", line 895, in setUp
self.init_resources()
File ".../sdcm/tester.py", line 1846, in init_resources
self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
File ".../sdcm/tester.py", line 1327, in get_cluster_aws
init_db_info_from_params(db_info, params=self.params, regions=regions)
File ".../sdcm/utils/aws_utils.py", line 252, in init_db_info_from_params
root_device = root_device if root_device else ec2_ami_get_root_device_name(
File ".../sdcm/utils/aws_utils.py", line …
```

fix(artifact-centos8-arm): update to lastet AMI

---

sdcm/nemesis.py
sdcm/sct_events/group_common_events.py
sdcm/utils/raft/common.py

Raft topology features bring new error messages, which could appear in logs when any topology operation aborted/failed.
Add common_group_events context manager which will Change event severity of expected error log messages from error to warning when topology operations is failed 
Fixes: #7426, #7425
- [JOb #18](https://argus.scylladb.com/test/3a2ae2f0-dc08-409e-85ba-b28f7ccc456f/runs?additionalRuns[]=08cea091-d408-413c-8f68-796ec271a599) - job failed due to spot termination, but events have changed sererites
- [Job #17](https://argus.scylladb.com/test/3a2ae2f0-dc08-409e-85ba-b28f7ccc456f/runs?additionalRuns[]=3ba35b53-e896-46ca-9c7a-63b756a03a52) - Job is passed …

fix(group_common_events): filter expected raft_topology error messages

---

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml

In order to simplfy this test and have it correctly behaves when
triggering it with a custom stress_duration all stress commands are
refactored as follow:
1. One stress command per loader in each step.
2. All stress commands outside "prepare" stage  have
"-iterations=0 -duration=6420m", which means that it can be replaced
when setting a custom stress duration, but it's also cyclic and it
continues to write continously until it reach the duration goal.
3. All first 1250 partitions are being written with "validate-data"
flag, so later the can be read with a verification.
4. Adjusting the size of instance to be used in AWS and the number
of disks to be used in GCP as it seems like 3-4B should be enough
for this use case.
Fixes: #7147 …

refactor(longevity-large-partition-200k): Refactor stress commands

---

jenkins-pipelines/oss/longevity/longevity-1-rf-test-12h.jenkinsfile
test-cases/longevity/longevity-1-rf-test-12h.yaml

This PR is trying to cover customer issue https://github.com/scylladb/scylladb/issues/16759.
This is from the issue description:
```
After Upgrading Scylla from 5.2.11 via 5.4.0 to 5.4.1, we started observing missing data in Scylla. 
Every once in a while, an INSERT is committed successfully but the inserted values are not visible 
until Scylla is restarted. 
As far as we can tell, version 5.2.11 was not affected while 5.4.1 is. 5.4.0 was not long enough 
in operation to make a reliable statement.
The suspected bug occurs extremely rarely, making it hard for us to reproduce. 
Out of ~800M inserts per day, only a dozen are affected.
```
The load is run on keyspace with RF 1 SCT test. 
We use scylla-bench because its validate data better then in cassandra-stress
- Add New configuration …

test(longevity): add longevity with rf=1

---

sdcm/provision/common/utils.py

Sometimes syslogng fails with installation. Possibly due to requiring terminal which is not available.

fix(cloud-init): stabilise syslogng installation

---

sdcm/cluster.py
sdcm/nemesis.py

In issue https://github.com/scylladb/scylladb/issues/18647 it was found that when a node restart it's insufficient now just to wait for cql port to be up and the safer way is to validate that all nodes are UN.
This commit moves the method wait_all_nodes_un to where it belongs in BaseScyllaCluster.

fix(rolling_restart): Wait all nodes to be UN after each restart

---

mgmt_cli_test.py

The PR fixes the bug introduced in c5a1fb9c78413316a85984aee904ac02db0d664b.
See the discussion for more details https://github.com/scylladb/scylla-cluster-tests/commit/c5a1fb9c78413316a85984aee904ac02db0d664b#comments

fix(manager): fix google-cloud-cli package installation

---

sdcm/logcollector.py

since now we are working as default with private addresses in
gcp and the public addresses can't be used, we now need to use
private addresses for the log collecting
similar fix as in  930c31d926c9d45b444687e1db3e1378890ee6a7 for aws

fix(gce-logcollector): use private addresses as default

---

.github/mergify.yml

Same as scylladb and scylla-dtest, adding backport automation for SCT as well
since SCT doesn't have next process, no need for automatic labeling for PR that reached master, so backport PR would be open right after merge.

feature(mergify): introduce automatic backport process

---

jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile

This Jenkins job fails to start if contains this whitespace. 
It seems like the space symbol is being interpreted as a property name, leading to a groovy.lang.MissingPropertyException.
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/sct/job/manager-master/job/Repair/job/repair-intensity-single-repaired-node/2/
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/sct/job/manager-master/job/Repair/job/repair-intensity-single-repaired-node/3/

fix(manager): remove unnecessary whitespace from repair jenkinsfile

---

artifacts_test.py

Still housekeepingdb is not updated in timely manner. Prolonged the waiting to stabilise test.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7487

fix(artifact-tests): prolong housekeeping verification

---

sdcm/utils/common.py

the tag was remove from scylla-machine-image, and SCT should be assuming it's there, in any name.

fix(hydra-list-images): don't fail on images that don't have `build-id`

---

configurations/network_config/scylla_addresses_on_different_interfaces.yaml
jenkins-pipelines/oss/longevity/longevity-100gb-splitted-networks-4h.jenkinsfile
sdcm/cluster.py
test-cases/longevity/longevity-100gb-4h.yaml

1. Add new network configuration based on the customer network configuration as described in the issue https://github.com/scylladb/scylla-manager/issues/3411.
2. Add longevity test 100g 4 hours test using new configuration
3. Use listen address instead rpc for manager agent
4. Use rpc address instead listen for cqlsh

test(network configuration): add test splitted broadcast and listening addresses

---

jenkins-pipelines/oss/tier1/longevity-multidc-schema-topology-changes-12h.jenkinsfile

Change longevity mulitDC parallel-topology-schema-changes test to be run 
with IPv6 network configuration.
Task: https://github.com/scylladb/qa-tasks/issues/1647

test(longevity): run multiDC test with IPv6 network config

---

sdcm/utils/operator/multitenant_common.py

if we don't have it in `TenantMixin`, we have failure like the following, when the test try to check if we have kafaka_cluster configured:
```
AttributeError: 'TenantForLongevityTest-2' object has no attribute 'kafka_cluster'.
Did you mean: 'k8s_cluster'?
```

fix(k8s-multitenant): add `kafka_cluster` to __init__

---

jenkins-pipelines/oss/tier1/longevity-50gb-3days.jenkinsfile
sdcm/cluster_aws.py
sdcm/provision/network_configuration.py

2 commits:
1. Change 'longevity-50gb-3days' to be run with 2 intefaces:
- Scylla addresses on one interface
- runner on another interface
2. set private_dns_name of right network inteface
Set private_dns_name of correct inteface according to test network
configuration.
The issue is in test with 2 NICs and 'use_dns_names' is True.
In this case seed IP in scylla.yaml should be private host name of second
NIC (according to broadcast_address).
When instance is just created, seed is defined as private host name of first
NIC in the scylla.yaml. It is wrong and Scylla fails to start at first time.
- Update the Readme/doc folder relevant to this change (if …

test(longevity): change 50gb test to be run with 2 interfaces

---

sdcm/utils/alternator/api.py

we introduce the read of `salted_hash` the possible names were `system_auth_v2`, `system_auth`.
now the first one to try out is `system`

fix(alternator): auth_v2 now default to using system keyspace

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_azure.py
sdcm/cluster_baremetal.py
sdcm/cluster_docker.py
sdcm/cluster_gce.py
sdcm/cluster_k8s/__init__.py
sdcm/provision/common/configuration_script.py
sdcm/sct_provision/aws/user_data.py
sdcm/test_config.py
unit_tests/dummy_remote.py
unit_tests/test_scylla_yaml_builders.py
unit_tests/test_sla_utils.py
unit_tests/test_utils_common.py

since one cases we run without provision phase, we might get into `configure_remote_logging`, before cloud-init has finished to installations of packages, and file we use to indicate no need to configure syslog-ng again isn't yet create, and we can run into case we might try to run `apt-get update` at the same time, and fail with what would look like premission issues
this change also remove the hack of disabling ssh at the start and at the end of cloud-init script, since we wait for cloud-init before doing any extra configuration.

fix(configure_remote_logging): wait for cloud-init

---

sdcm/tester.py

Collect and save in Argus Scylla manager version

improvement(manager): save Scylla manager version in Argus

---

sdcm/cluster_aws.py
sdcm/cluster_gce.py

in some artifact test we do have cases the distro isn't installing cloud-init by default, and we should be calling it at all.

fix(wait_for_cloud_init): cases cloud-init isn't installed

---

sdcm/tester.py
unit_tests/test_tester.py

This issue was caused by https://github.com/scylladb/scylla-cluster-tests/pull/7538. 
The monitor node is not created in artifact tests that causes to failure:
```
File sdcm/tester.py, line 508, in argus_collect_manager_version
manager_tool = get_scylla_manager_tool(manager_node=self.monitors.nodes[0])
IndexError: list index out of range
```

fix(scylla-manager): get version if monitor node exists

---

sdcm/provision/helpers/cloud_init.py

in some distros (OEL8) we might have those printed into stderr:
```
/etc/bashrc: line 100: TMOUT: readonly variable
```
the code was checking the stderr of `ls` command, the command succeeded but there was still something in stderr.
changing the code to check first the return code, and if that failed to print out the content of the stdout.

fix(wait_cloud_init_completes): check return code and not stderr

---

.github/workflows/pr-require-backport-label.yaml

we have it on scylla core repo, and we should have it here in SCT as well, so people open PRs would need to specify backport before it can be merged

ci(github-actions): add action to force backport labels

---

sdcm/nemesis.py
sdcm/utils/common.py

If run disrupt_add_remove_dc nemesis in parallel to the disrupt_add_drop_column one then we can get following error:
```
KeyError: 'keyspace_new_dc'
```
It is caused by the concurrency of a new keyspace addition (disrupt_add_remove_dc nemesis) and driver session update in addition to the unsafe coding assuming driver's session (disrupt_add_drop_column nemesis) knows about that newly added keyspace. Another possible problem: new added keyspace was dropped in exacly time when we run describe of the table.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7240

fix(longevity): get table for 'add_drop_column'

---

jenkins-pipelines/manager/debian10-manager-install.jenkinsfile
jenkins-pipelines/manager/debian11-manager-install.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-install.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-install.jenkinsfile
mgmt_cli_test.py
test-cases/manager/manager-installation-set-distro.yaml

Closes https://github.com/scylladb/scylla-manager/issues/3852
The test is designed for execution on non-main OS distributions (for example, debian10) where the main goal is to execute installation test and verify manager + agent are up and running.
The motivation of having such a test:
- We have never faced OS-specific failures in backup/restore/repair functionality. Thus, there is no need to run the sanity test (which includes these functionality verification) against non-main operation systems;
- Installation test takes only 20 minutes in average against ~2 hours for Manager sanity test;
- The Manager sanity is still here and will be executed on the main OS - Ubuntu 22. …

test(manager): introduce Manager installation test on different OS

---

docs/faq.md
sct.py

This commit adds a new `upload` command to the hydra, allowing user to
specify a test id and a file path to upload an arbitrary file to s3 and
link it in Argus. Files ending in .png or .jpg are also added to the
test run screenshot collection inside argus.
Fixes scylladb/qa-tasks#330

feature(sct.py): Add upload hydra command

---

sdcm/cluster.py

we shouldn't try install python on this distro, it doesn't have it.

fix(offline-installer): amazon linux 2023 doesn't have python2

---

unit_tests/test_latte_thread.py

The `--generate-report` was added to the recent latte version and is needed to get latency mean output.
So, add it to make latte integration tests work again.

fix(integration-tests): make latte tests work correctly

---

sdcm/utils/features.py
sdcm/utils/raft/__init__.py

New utils scylla features functions which allow to get supported and enabled scylla features on cluster and check if feature is enabled
These functions is better choice to check new features like tablets and raft consistent topology changes
- [Job with patch](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-100gb-4h/111) Job failed due to error https://github.com/scylladb/scylladb/issues/18843, which was fixed on later build

feature(scylla-features): get available and enabled scylla features

---

mgmt_cli_test.py

No need to keep it since there are no tests executable with Scylla Enterprise version 2019. Moreover, it blocks tests execution on open-source versions because of version parsing issue.

fix(manager): set throttle_per_node independent from Scylla version

---

sdcm/cluster.py
sdcm/remote/remote_file.py

for some reason the path where to install the offline-installer was hard-coded to `/home/scylla-test/scylladb`, which can lead to case where the image has a different default user, which is not name like that.
this commit change it, to dynamically lookup the home directory and build the path on that.

fix(offline-installer): stop hard coding the username

---

docker/env/hydra.sh

cause if we don't, we have some modules in utils which are identical in their names to some builtins, and it would fail like that:
```
File "..././sdcm/utils/get_username.py", line 15, in <module>
import getpass
File ".../3.11.3/lib/python3.11/getpass.py", line 17, in <module>
import contextlib
File ".../3.11.3/lib/python3.11/contextlib.py", line 6, in <module>
from collections import deque
File ".../3.11.3/lib/python3.11/collections/__init__.py", line 36, in <module>
from operator import eq as _eq
ImportError: cannot import name 'eq' from 'operator'
(.../sdcm/utils/operator/__init__.py)
```
this snippet of python code is run before we get into the hydra image hence we don't control the python version being used...
- Add New configuration option and …

fix(hydra): use python3.11 `Don’t prepend a potentially unsafe path to sys.path`

---

sdcm/provision/common/utils.py

Now the the ssh "lock" we have if out, there are few reentrancy issue we need to solve in the syslog-ng installation
script

fix(syslogng-install): fix retries in installation script

---

sdcm/cluster_aws.py
sdcm/cluster_gce.py

`command` command in the context of `sudo` does not work (raising `sudo: command: command not found` error).
Fix by wrapping over `bash -c` .

fix(setup): fix verifying cloud-init command

---

sdcm/tester.py

After merge of the [1] PR the K8S deployments started failing with the following error:
```
Command: 'sudo sctool version'
Exit code: 1
Stdout:
Stderr:
sudo: sctool: command not found
```
It is caused by the fact of using monitoring node which, in case of K8S, doesn't have scylla-manager.
So, make that code be run only in non-k8s cases.
[1] https://github.com/scylladb/scylla-cluster-tests/pull/7538
- https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.13/job/gke/job/longevity-scylla-operator-3h-gke-test/3
- https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.13/job/gke/job/longevity-scylla-operator-3h-gke-repair-test/3
- Update …

fix(k8s): make K8S deployments not fail on mgmt version gatherings

---

jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-regression-latency-shard-aware-1TB.jenkinsfile
jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-regression-throughput-non-shard-aware.jenkinsfile
jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-regression-throughput-shard-aware.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-shard-aware-1TB.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-throughput-non-shard-aware-i4i.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-shard-aware-1TB.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-throughput-non-shard-aware-i4i.jenkinsfile
test-cases/longevity/longevity-10gb-3h.yaml

After examination of test runs, node benchmarks don't bring any valuable information: seems there's no correlation between its results and performance of nodes.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7468

fix(benchmarks): disable node benchmarks

---

sdcm/cluster.py
sdcm/provision/common/configuration_script.py
sdcm/provision/common/utils.py
sdcm/sct_provision/region_definition_builder.py
sdcm/sct_provision/user_data_objects/apt_daily_triggers.py
sdcm/sct_provision/user_data_objects/sshd.py

Apt daily triggers disabling takes time and is quite late in the
proces. This prolongs setup due chance that triggers are fired before
installation of syslog-ng and other packages and makes apt lock to be
awaited. Also doing it with `remoter` class in multiple commands is not
most efficient way of doing it.
Moved disabling apt daily triggers to cloud-init step as the first in
the process.
closes: https://github.com/scylladb/qa-tasks/issues/1695

Move disable auto upgrades to cloud init

---

data_dir/scylla-dash-per-server-nemesis.master.json
sdcm/cluster.py

Before this change we could not filter our nodes with 'dc' filter because all our targets were not having the 'dc' label.
So, start registering targets with labels.
Also, update SLA and syslogng diagrams to be dc-filter compliant.

improvement(monitor): make targets be dc-aware

---

configurations/arm/centos9.yaml
configurations/gce/new_ssh_key.yaml
docker/env/hydra.sh
jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos9-arm.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos9-nonroot.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos9-selinux.jenkinsfile
jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos9.jenkinsfile
jenkins-pipelines/oss/artifacts/artifacts-centos9-arm.jenkinsfile
jenkins-pipelines/oss/artifacts/artifacts-centos9-selinux.jenkinsfile
jenkins-pipelines/oss/artifacts/artifacts-centos9-web.jenkinsfile
jenkins-pipelines/oss/artifacts/artifacts-centos9.jenkinsfile
jenkins-pipelines/oss/rolling-upgrade/rolling-upgrade-centos9.jenkinsfile
sdcm/cluster.py
sdcm/mgmt/common.py
sdcm/utils/distro.py
test-cases/artifacts/centos9-selinux.yaml
test-cases/artifacts/centos9.yaml
unit_tests/test_base_version.py
utils/get_supported_scylla_base_versions.py

now that centos8 is deprecated, we introduce the exact same tests but ontop of centos9
Ref: #7543

feature(artifact-tests): add tests using centos9

---

test-cases/scylla-operator/longevity-scylla-operator-3h-backup.yaml

fix(k8s): use bigger minio storage for GKE backup CI job

---

sdcm/cluster.py

In K8S we widely use dynamic loader pods and when we setup monitoring node we don't have IP addresses for loaders.
So, skip such cases instead of failing when we setup monitoring.

fix(k8s): make monitoring setup not fail when loaders have no IP addrs

---

sdcm/provision/helpers/cloud_init.py
unit_tests/provisioner/test_provision_sct_resources.py

newer versions of cloud-init, report status code 2, if there are warnings, and we should have failures like the:
```
2024-06-15 22:14:22.954: (TestFrameworkEvent Severity.ERROR)
period_type=one-time event_id=..., source=ArtifactsTest.SetUp()
exception=Failed to create node: Encountered a bad command exit code!
Command: 'sudo cloud-init status --wait'
Exit code: 2
Stdout:
status: done
Stderr:
```
in this chaneg we detect the cloud-init version, and adapt the logic we do for identifing if cloud-init failed or not, while showing the extended information json newer version can supply

fix(wait_cloud_init_completes): ignore warnings

---

.github/mergify.yml

Closes https://github.com/scylladb/scylla-cluster-tests/issues/7686.
Since the new manager release branch has been created (manager-3.3), the backport label should be updated in mergify.yml.
The new `backport/manager-3.3` label was created as well:
https://github.com/scylladb/scylla-cluster-tests/labels/backport%2Fmanager-3.3

fix(manager): update manager backporting label to manager-3.3

---

sdcm/cluster_aws.py
sdcm/sct_provision/aws/instance_parameters_builder.py
sdcm/utils/aws_utils.py
unit_tests/test_network_config.py

When trying to run test with multiple az's, provision step fails:
```
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_provision/aws/instance_parameters_builder.py", line 75, in NetworkInterfaces
output.append({'DeviceIndex': index, **self._network_interface_params(interface_index=index)})
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_provision/aws/instance_parameters_builder.py", line 135, in _network_interface_params
'SubnetId': self._ec2_subnet_ids[self.region_id][self.availability_zone + interface_index],
11:21:28  IndexError: list index out of range
```
To fix it collect info about subnet from relevant avalability zones and return it as list.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7432
More issue that this commit will fix: …

fix(cluster): multiple AZ configuration

---

sdcm/cluster.py
sdcm/nemesis.py
sdcm/utils/replication_strategy_utils.py
unit_tests/test_cluster.py
unit_tests/test_replication_strategy_utils.py

There are Scylla operation that cannot be performed on table with RF one. This commit adds filtering out of all keyspaces with RF one to prevent this nemesis run.
The 'toggle_table_gc_mode' nemesis cannot be run on table with RF = 1 and fails with error: ConfigurationException: tombstone_gc option with mode = repair not supported for table with RF one or local replication strategy
If all tables are with RF 1, this nemesis should not be started

improvement(cluster): filter out keyspace by replication factor

---

vars/byoScylladb.groovy
vars/longevityPipeline.groovy
vars/perfRegressionParallelPipeline.groovy
vars/provisionResources.groovy
vars/rollingUpgradePipeline.groovy
vars/runSctTest.groovy

It becomes more and more useful to build custom scylladb images
with unmerged changes to the scylladb repo.
So, add possibility to do it by utilizing the "byo" pipeline available
in the "scylla-pkg" project. This pipeline gets utilized as an existing
Jenkins CI job which must be refered to in the "byo_job_path" parameter
like the following:
```   
./my-custom-scylla-byo-job/
```

ci(pipeline): add possibility to byo scylladb for longevity and upgrades

---

sdcm/cluster.py
sdcm/mgmt/cli.py
sdcm/nemesis.py
sdcm/provision/helpers/certificate.py
sdcm/scylla_bench_thread.py
sdcm/stress/latte_thread.py

After TLS certificates preparation was reworked in SCT, individual TLS certificates are created and distributed for loader and cluster nodes.
The change adds the same logic for creating and distributing certificate/key to a manager node (which is usually a monitor node in the mgmt_cli tests).
Also certificate/key naming in SCT is changed to avoid redefining them in different modules - the names are defined as constants in one place now and re-used where necessary.

fix(tls-certs): fix usage of certs in mgmt_cli test and improve naming of tls artifacts 

---

vars/byoScylladb.groovy
vars/longevityPipeline.groovy
vars/rollingUpgradePipeline.groovy

Currently set default as `./byo` doesn't match any existing jenkins job.
So, set the default one as real one.
It will reduce the need for each separate person to find out the proper job path.
Also, set proper `default` branch that is specific to the `6.0` version.

[branch-6.0] ci(byo): use existing scylla-pkg jenkins job as default

---

vars/byoScylladb.groovy
vars/longevityPipeline.groovy
vars/rollingUpgradePipeline.groovy

Currently set default as `./byo` doesn't match any existing jenkins job.
So, set the default one as real one.
It will reduce the need for each separate person to find out the proper job path.
Also, set proper `default` branch that is specific to the `2024.1` version.

[branch-2024.1] ci(byo): use existing scylla-pkg jenkins job as default

---

vars/byoScylladb.groovy
vars/longevityPipeline.groovy
vars/rollingUpgradePipeline.groovy

Currently set default as `./byo` doesn't match any existing jenkins job.
So, set the default one as real one.
It will reduce the need for each separate person to find out the proper job path.
Also, set proper `default` branch that is specific to the `5.4` version.

[branch-5.4] ci(byo): use existing scylla-pkg jenkins job as default

---

vars/byoScylladb.groovy
vars/longevityPipeline.groovy
vars/rollingUpgradePipeline.groovy

Currently set default as `./byo` doesn't match any existing jenkins job.
So, set the default one as real one.
It will reduce the need for each separate person to find out the proper job path.

ci(byo): use existing scylla-pkg jenkins job as default

---

artifacts_test.py
defaults/test_default.yaml
sdcm/sct_config.py

Disable scylla-doctor because its files that we need to download, dissapeared from S3.

fix(artifact test): disable scylla-doctor

---

.github/workflows/cache-issues.yaml
sdcm/utils/issues.py

Ref: https://github.com/scylladb/qa-tasks/issues/1678

feature(github): cache github issues status in S3

---

sdcm/utils/cdc/options.py

CDC_SETTINGS_NAMES_VALUES['preimage'] uses string values "true" "false" instead of bool True False. This cause assertion error if it was changed
```
AssertionError: CDC extension settings are differs.
Current: {'delta': 'full', 'enabled': True, 'preimage': True, 'postimage': True, 'ttl': '1800'}
expected: {'delta': 'full', 'enabled': True, 'preimage': 'true', 'postimage': True, 'ttl': '1800'}
```
- [Job with fix](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-cdc-100gb-4h-test/12/) - Passed

fix(CDC_OPTIONS): Use boolean value for cdc preimage option

---

sdcm/provision/helpers/certificate.py

recent changes from #7436, seems to have casuing ipv6 cases to break like following:
```
2024-06-22 03:17:22.741: (TestFrameworkEvent Severity.ERROR) period_type=one-time
event_id=47cf9ea7-ecb7-40ba-8a9e-bbb85b289ead, source=LongevityTest.SetUp()
exception=[Node parallel-topology-schema-changes-mu-loader-node-3546ab88-2
[34.253.230.142 | 10.4.11.221 | 2a05:d018:12e3:f002:b483:d673:04af:5c0b] (dc name: eu-west-1)]
NodeSetupFailed: Expected 4 octets in '2a05:d018:12e3:f002:b483:d673:04af:5c0b'
```
this commit change to `ipaddress.ip_address()` that can automaticly return the correct type of ip address
- Update the Readme/doc folder relevant to this …

fix(ipv6): don't limit certificates creation to ipv4

---

configurations/manager/debian10.yaml
configurations/manager/debian11.yaml
configurations/manager/rocky8.yaml
configurations/manager/ubuntu20.yaml
jenkins-pipelines/manager/rocky8-manager-install.jenkinsfile
sdcm/cluster.py
sdcm/mgmt/cli.py

This PR introduces the Manager installation test on Rocky8 distro (https://github.com/scylladb/scylla-manager/issues/3854).
Contains:
- Configuration file for Rocky8 distro;
- jenkinsfile for Rocky installation test;
- some adjustments to monitoring node configuration methods to make installation on Rocky finctuonal.
Test triggers were adjusted as well:
https://github.com/scylladb/scylla-pkg/pull/4137

test(manager): introduce Manager installation test on Rocky8 distribution

---

sdcm/cluster.py

The changes in commit https://github.com/scylladb/scylla-cluster-tests/commit/ aea611d6142a6fb80cca4d7663a419407879ae90 breaks the opportunity to run tests from local developer PC.
The setup fails on wait_manager_agent_up function as tries to access nodes via private ip address. Use curl from DB node when check if manager agent is up instead of send request from runner (local machine).
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7636

fix(local run): check if manager agent is up

---

vars/byoScylladb.groovy
vars/longevityPipeline.groovy
vars/rollingUpgradePipeline.groovy

After branching to the `branch-2024.2` we should update the BYO params default values to make it be proper ones.

[branch-2024.2] fix(byo): use proper default values for BYO scylla params

---

jenkins-pipelines/manager/ubuntu22-manager-vnodes-tablets.jenkinsfile
mgmt_cli_test.py
mgmt_upgrade_test.py
sdcm/tester.py
sdcm/utils/loader_utils.py
sdcm/utils/tablets/common.py
test-cases/upgrades/manager-upgrade.yaml

The PR partially addresses https://github.com/scylladb/scylla-manager/issues/3853.
The PR consists of:
- New test that performs sanity checks on cluster with mixed keyspaces - 1 vnodes keyspace + 1 tablets keyspace;
- .jenkinsfile that handles test execution in CI;
- A few fixes/extensions for some load/stress methods to handle non-default or several keyspace names;
- Fix for system_auth keyspace repair test.
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/manager-master/job/ubuntu22-sanity-test/16/
https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/manager-master/job/ubuntu22-vnodes-tablets-cluster-test/
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/manager-master/job/debian11-sanity-test/2/ …

test(manager): Introduce the sanity test on mixed cluster (vnodes+tablets)

---

unit_tests/test_nemesis_sisyphus.py

Fix expected number of disrupt methods in test_list_all_available_nemesis test.

fix(test_list_all_available_nemesis): fix number of disrupt methods

---

sdcm/teardown_validators/sstables.py

We face issues from time to time with sstable scrub validator, like delayed logs or validating on unbootstrapped node.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7440

fix(validator): fix various issues with sstable scrub validator

---

jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/debian11-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/older-enterprise-ami-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-upgrade.jenkinsfile
vars/artifactsPipeline.groovy
vars/byoLongevityPipeline.groovy
vars/cdcReplicationPipeline.groovy
vars/longevityPipeline.groovy
vars/managerPipeline.groovy

Since Manager 3.3 is about to be released, the upgrade jobs should use Manager version 3.2 as initial.

ci(manager): adjust upgrade jobs to run upgrade from version 3.2

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/nemesis.py

Adding and decommissioning nodes should be run in parallel as this is currently Scylla's default behavior.
Refactored code to support it. Can be disabled if
`parallel_node_operations` param is set to false.

improvement(parallel-operations): grow-shrink cluster

---

sdcm/mgmt/cli.py

Since we stuck with CentOS image on Azure, centos7 should returned back to the list of manager supported distros.

fix(manager): return centos7 back to the list of supported OS

---

sdcm/fill_db_data.py
sdcm/utils/version_utils.py
test-cases/upgrades/rolling-upgrade.yaml
upgrade_test.py

Set of commits which are fix several issues in rolling upgrades from 6.0 to 6.1
[fix(restore-backup): Restore only existent files](https://github.com/scylladb/scylla-cluster-tests/pull/7525/commits/0fec37f69d339ace09f30355a8917c3029b9c7aa) - Fixing script error when try to restore backup config files which could be missing
[fix(fill_db-UP): Temprorary disable cdc for rolling upgrade](https://github.com/scylladb/scylla-cluster-tests/pull/7525/commits/7cae54dc8d86b12abaf16b6a063a13c9bb8f9e51) - Disable creating table with cdc options because it is not supported with tablets
[fix(upgrade_test): Wait while all nodes up after rollback](https://github.com/scylladb/scylla-cluster-tests/pull/7525/commits/4a923f8705b2e9a2e66a1695dc3982c8b2a0d569) - need to wait after node upgrade/rollback that all …

fix(rolling-upgrade): Set of commits to fix rolling upgrade from 6.0-6.1

---

multiple_dc_test.py
pyproject.toml
sdcm/cluster_aws.py
sdcm/mgmt/cli.py
sdcm/sct_config.py

Recently a bug was introduced to parallel nodes bootstrap where simulated_racks was ignored. This could have been prevented if ruff verified unused variables.
Introduced this check (verified whole repo locally) and fixed all the issues (including ignore of simulated racks).

improvement(ruff): enable unused variable check

---

sct_scan_issues.py
sdcm/nemesis.py
sdcm/utils/issues.py

some SkipPerIssue instances were referring to old scylla repo name issue caches is per the new names, hence we need to align those

fix(nemesis): refer to correct scylladb repo

---

sdcm/nemesis.py

PR #7702 introduced changes to nemesis code, that start retruning mutiple nodes back from the refactored `_add_and_init_new_cluster_node` function, some of the places using the function, was expecting exactly one node in return, and not a list.
Fixes: #7780

fix(nemesis): handle fallout from parallel-operations changes

---

jepsen_test.py

jepsen is picky about the location of tcpdump in some version so we'll symlink to where it's expecting

fix(jepsen): hack tcpdump to work as jepsen needs

---

sdcm/nemesis.py

since it didn't passed a list down to `follow_system_log` the validation wasn't really working as expected, and could finish on finding any of the letters from the validation phrase.

fix(hot_reloading): pass correct patterns to `follow_system_log`

---

sdcm/tester.py

Example of the noise in SCT log:
```
03:15:21.196  < t:2024-06-30 21:42:02,263 f:tester.py       l:635  c:JepsenTest           p:WARNING > Error submitting gemini results to argus < t:2024-06-30 21:42:02,263 f:tester.py       l:635  c:JepsenTest           p:WARNING > Error submitting gemini results to argus
03:15:21.196  < t:2024-06-30 21:42:02,263 f:tester.py       l:635  c:JepsenTest           p:WARNING > Traceback (most recent call last):
03:15:21.196  < t:2024-06-30 21:42:02,263 f:tester.py       l:635  c:JepsenTest           p:WARNING >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 596, in argus_collect_gemini_results
03:15:21.196  < t:2024-06-30 21:42:02,263 f:tester.py       l:635  c:JepsenTest           p:WARNING >     if not getattr(self, "gemini_results"): …
```

fix(tester): reduce noise in the logs if there is no gemini_results attribute

---

sct_ssh.py
sdcm/utils/common.py

since we switch diffrent keys, the tunneling can fail picking the a correct bastion, we now filter the the list of bastions to make sure we don't mix, and use diffrent keys from the one configured for an instance.
(those could be coming for older releases,
or people using older branches)

fix(hydra-ssh): tunnel shouldn't pick bastions with other keys

---

defaults/aws_config.yaml

Loader ami used old c-s which didn't have java driver with tablets support.
Created new image with c-s from 2024.2.0-rc0 and updated scylla-bench to 0.1.21.

fix(loader): update loader ami with tablet aware driver

---

jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-regression-latency-shard-aware-1TB.jenkinsfile
jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-regression-throughput-non-shard-aware.jenkinsfile
jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-regression-throughput-shard-aware.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/perf-regression-throughput-shard-aware-gce-z3-enterprise.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-grow-shrink.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-with-nemesis.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-shard-aware-1TB.jenkinsfile
jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-throughput-non-shard-aware-i4i.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-grow-shrink.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-with-nemesis.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-shard-aware-1TB.jenkinsfile
jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-throughput-non-shard-aware-i4i.jenkinsfile

all of the current test should be running without tablets enabled specific case for tablets would be pick and run with it enabled

feature(perf-tests): disable tablets by default

---

defaults/test_default.yaml
docker/cassandra-stress/Dockerfile-deb
docker/cassandra-stress/README.md
sdcm/cluster_k8s/__init__.py
sdcm/remote/kubernetes_cmd_runner.py
sdcm/stress_thread.py
sdcm/utils/version_utils.py
unit_tests/test_version_utils.py

until we'll have an offical release of c-s seperate from scylla core we built this image, base on the version from scylla 6.0 this version should have tablets support (which 5.4.6 didn't had)

fix(c-s): update the docker image we use for c-s

---

defaults/test_default.yaml
docker/cql-stress-cassandra-stress/Dockerfile
docker/cql-stress-cassandra-stress/image
docker/scylla-sct/entry.sh
docker/scylla-sct/entry_ssl.sh
internal_test_data/complex_test_case_with_version.yaml
sdcm/cql_stress_cassandra_stress_thread.py
sdcm/kafka/kafka_cluster.py
sdcm/kafka/kafka_config.py
sdcm/ndbench_thread.py
sdcm/scylla_bench_thread.py
sdcm/stress/latte_thread.py
sdcm/tester.py
sdcm/utils/docker_remote.py
sdcm/ycsb_thread.py
unit_tests/conftest.py
unit_tests/dummy_remote.py
unit_tests/lib/alternator_utils.py
unit_tests/test_alternator_streams_kcl.py
unit_tests/test_cassandra_stress_thread.py
unit_tests/test_cluster.py
unit_tests/test_config.py
unit_tests/test_cql_stress_cassandra_stress_thread.py
unit_tests/test_kafka.py
unit_tests/test_latte_thread.py
unit_tests/test_ndbench_thread.py
unit_tests/test_scylla_bench_thread.py
unit_tests/test_ycsb_thread.py

for covering related auth in alternator tests
we want to enable the integration tests to work
by default with auth enforced.
it flushed out, that we need to fix latte support
and that cql-stress version we have doesn't support auth

fix(integration-tests): enable auth by default

---

defaults/manager_versions.yaml

Since the Manager 3.3 has been released, the manager_versions.yaml is updated to have the links to .repo and .list files for this release.
Together with that, the links for old release 3.0 have been removed.

fix(manager): add links to .list/.repo files for release 3.3

---

sdcm/cluster.py
sdcm/nemesis.py
sdcm/provision/helpers/certificate.py

since the refactor of reloading certs we started
seeing those errors to start new nodes:
```
[shard  0:main] init - Startup failed: std::system_error
(error GnuTLS:-60, The certificate and the given key do not match.)
```
those were happening after `hot_reloading_internode_certificate` was trying to reload the certificates, problem it had an assumption updating certificate once, and sending it to all of the nodes. but now we generate certs per node, and it wasn't copying it from the correct place, hence generated cert that doesn't match the key.
ontop of that seems like the validation in that nemesis was wrongly using `follow_system_log`, cause it to missed looking for the actual line that shows the certs are reloaded (it seems to be broken like that since …

fix(nemesis): `hot_reloading_internode_certificate` to update correct certs

---

test-cases/manager/manager-regression-ipv6.yaml

The PR addresses the following issues:
- Configuration yaml for manager ipv6 test is missing stress_read_cmd parameter. Without it, read verification check is skipped in test.

Manager add stress read cmd into ipv6 config file

---

sdcm/utils/microbenchmarking/perf_simple_query_reporter.py

When new column to perf simple query test is added it breaks the result table.
Fix by getting available columns from current run and create table with all of them. In case there's no result for that column in the past, replace with `N/A`.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7496
tested in staging:

fix(perf-simple-query): fix results table

---

configurations/force-gossip-topology-changes.yaml
sdcm/cluster.py
sdcm/provision/scylla_yaml/scylla_yaml.py
unit_tests/test_scylla_yaml.py

When scylla yaml has `force_gossip_topology_changes` set to `True` then parallel node operations should be disabled.
Added proper handling, configuration and updated `ScyllaYaml` model.

fix(parallel-operations): disable when force gossip

---

docker/cql-stress-cassandra-stress/Dockerfile
docker/cql-stress-cassandra-stress/README.md
unit_tests/test_cql_stress_cassandra_stress_thread.py

we have few issue with the mixed mode, regarding counter related
schema and operations, we need this cover to make sure we don't
waste time on such issues.

test(cql-stress): new test to cover how mixed mode is working

---

sdcm/nemesis.py

quite some time ago the `disrupt_nodetool_cleanup` change to work in parallel, but other nemesis that do the same sequence of running cleanup on all nodes (after topology changes) we still doing that in a sequence
this change align it for all of the places cleanup is used.
Note: for tablet cleanup should be no-op, and it's not really matter, but this change is for backporting into older branches
Closes: scylladb/qa-tasks#1690

fix(nemesis): parallel cleanups in all nemesis using cleanups

---

mgmt_cli_test.py
sdcm/cluster.py
sdcm/provision/helpers/certificate.py
sdcm/tester.py
unit_tests/conftest.py
unit_tests/test_tester.py

There are a couple of error-prone situations when CA cert/key pair is created:
- the CA is created for every test run, even if the configuration under test
doesn't have encryption enabled (hence don't need CA to sign nodes certs)
- in case of artifacts tests there are situations when a Jenkins builder node
hosts several artifacts tests in a row, i.e. the test environment is not cleaned up
between tests. In this case SCT will try to import CA pem certificate to existing
Java truststore and will fail
The change addresses both problems:
- creation of CA is made optional, depending on whether client and/or server encryption
are enabled in the test configuration
- creation of CA is made idempotent between different executions of a test on the
same node - a check is added to CA creation …

fix(artifacts-test): make creation of CA and Java truststore idempotent

---

pyproject.toml
sdcm/cluster_baremetal.py
sdcm/cluster_k8s/__init__.py
sdcm/fill_db_data.py
sdcm/mgmt/__init__.py
sdcm/provision/scylla_yaml/__init__.py
sdcm/sct_provision/__init__.py
sdcm/utils/alternator/__init__.py
sdcm/utils/cdc/__init__.py
sdcm/utils/cloud_monitor/__init__.py
sdcm/utils/k8s/__init__.py
sdcm/utils/raft/__init__.py
unit_tests/lib/alternator_utils.py
unit_tests/test_nemesis.py
unit_tests/test_version_utils.py

we had this check in pylint, and since we missing it on ruff it casue linting errors in backport PRs
this is something we want to keep checked anyhow
Ref: https://docs.astral.sh/ruff/rules/unused-import/

feature(ruff): check for `unused-import (F401)`

---

vars/perfRegressionParallelPipeline.groovy
vars/perfSearchBestConfigParallelPipeline.groovy

seem like in cases we don't define it in the pipeline this is being passed down as `null` into the parallel pipelines

fix(perf-pipeline): handle can of GCP_PROJECT isn't defined

---

sct.py
sdcm/results_analyze/__init__.py
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/es_queries.py
vars/perfRegressionParallelPipeline.groovy

before we have all kind of logic that prevented us from getting results from staging jobs, and from nested folders
as part of refactoring the perf jobs, we do want to be able to have nested folder, and also the ability to run staging job compare to offical jobs, without naming them exactly the same.
so in this change we introduce a new sct configuration `perf_extra_jobs_to_compare`, offical jobs would set it with thier actual location, so every time it would run in staging it would be comapre with the offical run.
this was introduced also to the `hydra perf-regression-report` so we can manually create reports and needed.
- Update the Readme/doc folder …

feature(perf-test): add option for `perf_extra_jobs_to_compare`

---

sdcm/nemesis.py

Reverts scylladb/scylla-cluster-tests#7803
The following error occurs during HotReloadingInternodeCertificate nemesis in longevity-100gb-4h-fips-test scenario, executed on 2024.1.7 release - https://argus.scylladb.com/test/6af3624b-cded-4040-a656-e9246811b687/runs?additionalRuns[]=382b48f4-5dc5-461d-a814-fd64c23fc847 shows:
```
2024-07-04 06:57:38.352: (DisruptionEvent Severity.ERROR) period_type=end event_id=3442750b-bc79-4d1a-9862-fae65ebbbd68 duration=10m11s: nemesis_name=HotReloadingInternodeCertificate target_node=Node longevity-fips-2024-1-db-node-382b48f4-2 [3.252.168.133 | 10.4.3.193] errors=Reload SSL message not found in node log
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5093, in wrapper …
```

Revert "[Backport 2024.1] fix(hot_reloading): pass correct patterns to `follow_system_log`"

---

sdcm/nemesis.py

The nemeses `toggle_table_gc_mode` and `toggle_table_ics` consisntenty fail due to https://github.com/scylladb/scylla-enterprise/issues/4082 and make the noise. Skip those nemeses while this issue is not solved.
Example of failed test:
https://argus.scylladb.com/test/079cddb4-4eac-4594-a2f0-8452dab5eb40/runs?additionalRuns[]=e3e9d046-164c-49aa-b1fb-19a53e1b6566

fix(nemeses): disable `toggle_table` nemeses due to expected issue

---

.github/workflows/cache-issues.yaml
sdcm/utils/issues.py
unit_tests/test_utils_issues.py

in some places we are using PRs and not issue to identify
if we should be skipping something in the test code
we now generate two diffrent cache files on s3 for each repository
one for the issues and one for the pull requests
client code is merging it to once local cache, so it's mentioning
of either one should be working as expect, and read from cache,
not using affecting the hourly rate-limit
Ref: https://github.com/scylladb/qa-tasks/issues/1735

fix(issue_cache): add pull-requests to cache

---

Jenkinsfile

we should be skipping those base on faliures of other stages if it was labeled to run, it should run.
it's holding us back from getting importent feedback quickly in some PRs
* linting error mostly don't affect the those runs
* case linting doesn't affect those runs

fix(Jenkinsfile): integration and provision test should run regardless

---

sdcm/cluster.py
sdcm/utils/common.py

When killing Scylla abruptly, kernel might not to acknowledge port has been released before Scylla get's back to normal operating state. This causes 'wait_db_down` to fail.
Fix by trying to establish dummy connection (without sending data) to scylla cql port - when this is done, kernel updates port state and this method should work properly.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7480

fix(wait-port-down): case for abrupt scylla kill

---

defaults/test_default.yaml
sdcm/sct_config.py
sdcm/tester.py

we enable kms by default since if we use scylla 2023.1.3 and up in some case this introduce machinary we don't really need for a specific test, or for example can affect our performence runs in a way we don't yet want.
in this commit we introduce an escape hatch to disable KMS for enterprise run

feature(kms): sct configuration to disable kms

---

sdcm/nemesis.py

Timeout for decommission is too low and some tests fail due to that.
Increase timeout for decommission to `MAX_TIME_WAIT_FOR_DECOMMISSION`

fix(decommission): increase timeout

---

sdcm/cluster.py

We see problems with audit logs missing. Possibly it's due miss in `open_system_log` method but we can't be sure.
Added log message that will help us investigation in case of issues. refs: https://github.com/scylladb/scylla-cluster-tests/issues/7102

improvement(open_system_log): added debug line

---

vars/longevityPipeline.groovy

Fixes: #7884
- https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-10gb-3h-test/110

improvement(byo): make CI jobs fail fast if BYO fails

---

sdcm/cluster.py
sdcm/cluster_baremetal.py
sdcm/nemesis.py
sdcm/remote/remote_long_running.py
unit_tests/test_remote_long_running.py
upgrade_test.py

cause we have issues with long running ssh commands that we can retry, if node is a bit load at the time of the operation we might get disconnected, and fail the command complectly from SCT end.
in this change we introduce a way to run the command in the background while logging stdout, stderr, and exit code.
and poll for the finish of the process by its pid
in the end we'll collect all the logs, and retry results as if it with a regular remoter execution
Fixes: #7781

feature(remoter): execuation of long running command

---

defaults/test_default.yaml
sdcm/teardown_validators/__init__.py
sdcm/teardown_validators/base.py
sdcm/teardown_validators/events.py
sdcm/teardown_validators/sstables.py
sdcm/tester.py
test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
unit_tests/test_teardown_validator.py

In some cases (e.g. parallel nemeses) we don't want to fail the test based on an error event, but rather look for coredumps or critical level events.
The change introduces a teardown validator, which takes into account only pre-defined error events to make a decision if the test is failed.
The related task: https://github.com/scylladb/qa-tasks/issues/1671

feature(teardown-validators): parallel nemeses error events validator

---

sdcm/tester.py

This commit adds additional logic into argus_finalize_test_run that
checks whether a failed run failed due to test error - e.g.
SpotTerminationEvent, where the framework encountered an environment
issue (not enough capacity) and cannot continue.
Task: scylladb/qa-tasks#1596

improvement(sdcm/tester.py): Add TEST_ERROR Argus status support

---

sdcm/sct_events/group_common_events.py
sdcm/utils/raft/common.py

We should ignore RPC transport error when one node boot is interrupted and Scylla did not start. In this case RPC to a new node was interrupted. We can ignore this error in this specific scenario (https://github.com/scylladb/scylladb/issues/15713#issuecomment-2217376031).
We have this scenario in 'BootstrapStreamingError' nemesis. Example of an error:
```
Transferring snapshot to 5f2e78c failed with: raft::transport_error (Failed to execute virtual future<raft::snapshot_reply> service::raft_rpc::send_snapshot(raft::server_id, const raft::install_snapshot &, seastar::abort_source &) on leader 5f2e78c9-c1b2-47f3-87b4-048fd2589d0d: seastar::rpc::closed_error (connection is closed))
```
- Add unit tests to cover my …

improvement(nemesis): ignore raft transport error

---

vars/byoScylladb.groovy

`scylla-pkg` project expects the `COPY_AMI_TO_REGIONS` param
to accept a string where region names are separated with comma.
So, translate our region(s) value into the expected format using BYO ScyllaDB.
Also, use `release` build mode
- to reduce redundant actions
- to avoid possible bugs related to 'all' case (less tested case).
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-alternator-3h-multidc-test/6

fix(byo): make BYO ScyllaDB work with multidc setups

---

pylintrc

In SCT we always run with debug log thus we don't care about having f-strings in log messages. There's no improvement from having this check turned on and f-string based messages are more readable and more natural to python programmers.
This check is disabled in our `ruff` linter but still we often backport commits to different branches where we still use it.
Disabling this check in .pylintrc.

improvement(pylint): disable f-string-interpolation error

---

.github/search_commits.py
.pre-commit-config.yaml
commitlint.config.js
functional_tests/scylla_operator/test_functional.py
ics_space_amplification_goal_test.py
mgmt_cli_test.py
mgmt_upgrade_test.py
performance_search_max_throughput_test.py
pylintrc
pyproject.toml
sct.py
sdcm/cluster.py
sdcm/mgmt/cli.py
sdcm/nemesis.py
sdcm/remote/remote_long_running.py
sdcm/results_analyze/__init__.py
sdcm/sct_config.py
sdcm/stress_thread.py
sdcm/tester.py
sdcm/utils/bisect_test.py
sdcm/utils/latency.py
sdcm/utils/microbenchmarking/perf_simple_query_reporter.py
upgrade_test.py

PLR016 is needed, since we had similar check in pylint, and we hit it in backport to older branches
also the preview enable this feature for this visual feature for the CLI:
```
sdcm/tester.py:838:13: PLR0916 Too many Boolean expressions (6 > 5)
|
837 |       def prepare_kms_host(self) -> None:
838 |           if (self.params.is_enterprise and ComparableScyllaVersion(self.params.scylla_version) >= '2023.1.3'
|  _____________^
839 | |             and self.params.get('cluster_backend') == 'aws'
840 | |             and not self.params.get('scylla_encryption_options')
841 | |             and not self.params.get('enterprise_disable_kms')
842 | |             and self.params.get("db_type") != "mixed_scylla"  # oracle probably doesn't support KMS
| …
```

feature(ruff): enable PLR0916 and preview mode

---

pylintrc

There's one more check to disable in pylint: logging-not-lazy to fully disable log messages verification.

fix(pylint): disable logging not lazy check

---

vars/rollingUpgradePipeline.groovy

Fixes: #7884
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-rolling-upgrade-ubuntu22.04-test/13 (controlled failure of BYO)
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-rolling-upgrade-ubuntu22.04-test/14 (BYO succeeded)

improvement(upgrade): make upgrade CI jobs fail fast if BYO fails

---

configurations/performance/cassandra-stress-650gb-8-col-i4i-80-percent-throughput-ent.yaml
configurations/performance/cassandra-stress-650gb-8-col-i4i-80-percent-throughput-oss.yaml
configurations/performance/cql-stress-650gb-8-col-i4i-80-percent-throughput-ent.yaml
configurations/performance/cql-stress-650gb-8-col-i4i-80-percent-throughput-oss.yaml
defaults/test_default.yaml
jenkins-pipelines/performance_staging/scylla-master-perf-regression-latency-650gb-elasticity.jenkinsfile
performance_regression_test.py
sdcm/cql_stress_cassandra_stress_thread.py
sdcm/nemesis.py
sdcm/sct_config.py
sdcm/tester.py
test-cases/performance/perf-regression-latency-650gb-elasticity.yaml

After releasing Scylla 6.0 we performed elasticity test which was basically grow-shrink cluster test in single AZ where after grow we double cluster load. It was tested also with cql-stress. We want to keep this test for future reference/rerun.
Adjusted grow-shrink nemesis to double the load for specified duration (in minutes). Configured by new param
`nemesis_double_load_during_grow_shrink_duration`. Also generated bunch of configurations to easily switch between cql-stress and c-s tools and OSS/Enterprise stress configurations.
closes: https://github.com/scylladb/qa-tasks/issues/1699

test(elasticity): grow-shrink cluster perf test with doubling load

---

unit_tests/test_base_version.py
utils/get_supported_scylla_base_versions.py

seems like the upgrade from minor to minor wasn't working as expected and we need to add the minor version anyhow, and count on the RC filter to work as expected
also added the OSS base version for 2024.2

fix(et_supported_scylla_base_versions): make upgrade work for minor version

---

sdcm/provision/azure/utils.py

scylla-machine-image changed/removed the `build-id` tag from images and the code here assumed it's a number, and if not skipped to the next
this cause us to pick the latest image that had a number in `build-id` for couple of months, and not to find images by branch on 2024.2
Fixes: #8022

fix(azure): remove the usage of `build-id` from filtering images

---

sct.py
sdcm/utils/aws_kms.py
sdcm/utils/aws_utils.py
sdcm/utils/common.py
sdcm/utils/gce_utils.py
sdcm/utils/resources_cleanup.py
unit_tests/test_clean_cloud_resources_func.py

improvement(kms): cleanup AWS KMS aliases only if there are no VMs

---

sdcm/tester.py

since we have a problem for now to enable both features we disable file based stream, when ever we enable KMS
all other EaR cases, would need to handle it on their own assuming they would want to enable tablets
Ref: scylladb/scylla-enterprise#4246

fix(kms): disable enterprise file stream

---

jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-grow-shrink.jenkinsfile
jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis.jenkinsfile
jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-grow-shrink.jenkinsfile
jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-with-nemesis.jenkinsfile

some jos was pointing to wrong old job names, which casue the regression check, not to show older versions.

fix(perf-jobs): correct `perf_extra_jobs_to_compare` for ops jobs

---

sdcm/report_templates/results_latency_during_ops_short.html
sdcm/utils/latency.py

for quite some time or latency during ops are below 5ms in both P90/P99, and it was decided to lower the bar (before it was 15ms for P99)
also seems like the results for `replace_node` are not that off and would be using the same bar for it as well

feature(perf-tests): change histogram max bar for P90/P99

---

sdcm/provision/helpers/certificate.py

seems like from some point, if we include empty values into `Subject Alternative Name`, like this:
```
X509v3 extensions:
X509v3 Subject Alternative Name:
DNS:longevity-100gb-4h-master-db-node-f052ae6b-1,
IP Address:10.12.8.241, IP Address:54.172.124.95,
DNS:, DNS:ip-10-12-8-241.ec2.internal
```
we might end up with scylla not booting, when server encrpytion is used
```
scylla[6486]:  [shard  0:main] init - Startup failed: std::system_error
(error GnuTLS:-62, Unknown Subject Alternative name in X.509 certificate.)
```

fix(certificates): don't include empty dns/ip into extensions

---

defaults/test_default.yaml
docker/cql-stress-cassandra-stress/image
unit_tests/test_config.py

Updating cql-stress to latest version.
This version contains the fix for https://github.com/scylladb/cql-stress/pull/86

fix(cql-stress): update cql-stress to latest version

---

sdcm/cluster.py
sdcm/utils/common.py

Reverted previous fix for wait_db_down - it was working for checking db down properly, but still `is_port_used` was not working right for docker backend.
So used this new working approach in `is_port_used` instead.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8031

fix(is_port_used): make it more robust

---

sdcm/cluster.py

update_db_packages procedure executes updating of scylla packages in threads for each node and uses sdcm.utils.decorators.retrying mechanism for retries. Through this decorator it is allowed for UnexpectedExit exception to occur up to the specified number of times, when installing packages, then the UnexpectedExit exception should be reraised.
For some reason reraise doesn't return control back to the caller if update function is running in threading.Thread threads. So if for some reason a thread with packages update is continuously failing and all retries are exhausted, the thread hangs.
The change switches from threading.Thread to concurrent.futures.ThreadPoolExecutor for paralleling packages update on nodes. This approach doesn't have issues with reraising exceptions in threads. …

fix(update_db_packages): fix issues with hanging threads during update

---

sdcm/reporting/tooling_reporter.py

This fixes an issue where a test might stop if we can't report a tooling
version to argus.

fix(sdcm/reporting/tooling_reporting): Add exception handler for Argus

---

sdcm/utils/aws_utils.py
sdcm/utils/common.py
unit_tests/test_config.py

for case, we have only  the owner id, and it's not publish in marketplace, hence we can't use the ssm parameter store.
as an example oracle only supply the owner id, and the AMIs are not visiable in marketplace, and can be found via SSM (as we do for other distro, like ubuntu/debian/amazon)
so now we can specifiy in the configuration something like this:
```yaml
ami_id_db_scylla: 'resolve:owner:131827586825/x86_64/OL8.*'
```
Ref: https://forums.oracle.com/ords/apexds/post/launch-an-oracle-linux-instance-in-aws-9462

feature(aws): introduce way to find images by owners

---

jenkins-pipelines/master-triggers/sct_triggers/weekly-master-rolling-upgrades-trigger.xml

seem like it was forgotten, and was inside SCT code now it need to be update with trigger the centos9 job so introducing it into the code

feature(triggers): add rolling upgrade trigger

---

jenkins-pipelines/qa/hydra-clean-test-resources.jenkinsfile

We want enable easy resources cleanup for Argus users without installing hydra.
Added a job that does the job.
refs: https://github.com/scylladb/qa-tasks/issues/323

improvement(cleanup): job for cleanup test resources

---

sdcm/nemesis.py
sdcm/sct_config.py
sdcm/utils/aws_utils.py
sdcm/utils/azure_utils.py
sdcm/utils/gce_utils.py
unit_tests/test_config.py

the commit introduces `nemesis_grow_shrink_instance_type` so one can select the instance type that would be use during the grow-shrink nemesis
when this option is used, the shrink phase is going to decomission exactly the node that was added, so we will leave the cluster in the same state (number of nodes, and their sizes)
Closes: scylladb/qa-tasks#1738
test with i4i.2xlarge grow with i4i.large, with 1 node, and with 3 nodes

feature(grow-shrink): option to set the instance type for grow-shrink

---

.github/search_commits.py

The current pattern we search for when doign the backport label change matches the `*-x.y`. Updating the pattern to include also `perf-v`
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8118

fix(.github/search_commit.py): backport pattern for perf branches

---

sdcm/provision/scylla_yaml/certificate_builder.py

Cqlshrc config can require update depending on whether client encryption is enabled/disabled in the configuration under test. Until now the update was not safe in terms that it was expected that 'ssl' section is present in the config by default.
The change updates how 'ssl' section is set in the cqlshrc.
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/8113

fix(cqlshrc): safely update cqlshrc

---

sdcm/logcollector.py

Log collection phase of a test run can fail if a failure occurs when collecting logs of a specific type.
Handling of unexpected exceptions is added, when iterating over log collectors, so that it continues with the next collector, instead of failing the whole 
log collection sequence.
Additionally the change adds skipping of jepsen logs collection sequence if no jepsen test was executed during SCT run.
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/7470.

fix(logcollector): do not fail the whole log collection phase on a failure of one collector 

---

sdcm/fill_db_data.py

part of the rolling upgrade we create and test some tables after each step, one of those is `counters_test: Validate counter support` since counter isn't supported by tablets, we need to skip it once tablets is enabled.

fix(upgrade-tests): skip counter test if tablets enabled

---

sdcm/es.py
sdcm/keystore.py
sdcm/nemesis_publisher.py
sdcm/results_analyze/__init__.py
sdcm/results_analyze/test.py
utils/fix_es_mapping.py
utils/migrate_nemesis_data.py
utils/update_field.py

switching form user/password to using api keys (tokens) also switching from using urls to using the elastic cloud_id which is what recommended by elasticsearch cloud, and enable compression.
Ref: https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/connecting.html#connect-ec
Ref: https://github.com/scylladb/qa-tasks/issues/1747

feature(elasticsearch): move to using api key

---

jenkins-pipelines/master-triggers/sct_triggers/nightly-%(sct_branch)s-nemesis-tests-trigger.xml

we disable the trigger long time ago,
but recently fix the job that update all sct jenkins jobs and that enabled it back, we don't need those runs for now.

fix(nemesis-tests-trigger): disable trigger
