artifacts_test.py

retry on the housekeeping check is expecting `AssertionError` but wasn't expecting `TypeError`
so in this change we are asserting the row isn't empty before moving on and trying to read specific things out of it
Fixes: scylladb/scylladb#19875

fix(artifacts_test): assert row isn't empty

---

sdcm/fill_db_data.py

since the status can change after the upgrade itself we should be caching those, and we should calculate them every single time.
also remove udt specific logic form the loop doing the skip condition, it's not needed anythmore, now that we have function calls for doing the logic for each case.

fix(fill_db_data): remove cache form properties

---

cdc_replication_test.py
gemini_test.py
jepsen_test.py
longevity_test.py
performance_scale_up_test.py
sct.py
sdcm/cluster.py
sdcm/db_stats.py
sdcm/report_templates/results_base.html
sdcm/report_templates/results_base_custom.html
sdcm/report_templates/results_base_new.html
sdcm/report_templates/results_performance_multi_baseline.html
sdcm/report_templates/results_performance_multi_baseline_single_metric.html
sdcm/results_analyze/__init__.py
sdcm/results_analyze/test.py
sdcm/send_email.py
sdcm/tester.py
sla_per_user_system_test.py
upgrade_test.py

the reporting to argus was depended on specific logic in each test to take the screenshots, some tests didn't had them.
this change consolidate taking the screenshots, and take them and report to argus for all of the tests, regardless if they have email report or not.
this change also remove the references to grafana_snapshot since we don't generate them anymore.
Fixes: scylladb/scylla-cluster-tests#8032

fix(screenshots): report screenshots to argus from all tests

---

defaults/test_default.yaml
test-cases/artifacts/debian11.yaml
test-cases/artifacts/ubuntu2004.yaml

update to the latest key
remove duplicate of definition of the apt keys
Ref: scylladb/scylla-enterprise#4222

fix(apt-keys): update the apt key for 2024

---

sdcm/tester.py
unit_tests/test_ycsb_thread.py

since scylladb/scylladb#19740 was recently merge, we need to put the `login=true` for using roles with alternator
and when scylladb/scylladb#19762 would be merged
we'll need the `superuesr=true`, or do fine grind permission for any action we need
Ref: scylladb/scylladb#19740
Ref: scylladb/scylladb#19762
Ref: https://github.com/scylladb/scylla-dtest/issues/4697

fix(alternator): create a role with "login" and "superuser" flags

---

upgrade_test.py

Some of the upgrades from 2024.1 to 2024.2 try different frontends
instead of using noninteractive by default:
```
Stderr:
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs
shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
```
The Debian Handbook recommends to add `DEBIAN_FRONTEND=noninteractive` env variable to non-interactive upgrade scripts (as we already do in `sdcm/cluster.py`)
E.g.: https://argus.scylladb.com/test/51d72851-b8d3-4818-a986-404f742f9b03/runs?additionalRuns[]=f3fe515c-3408-4a9 …

fix(upgrade_test): add DEBIAN_FRONTEND=noninteractive to apt-get commands

---

sdcm/scan_operation_thread.py
unit_tests/test_scan_operation_thread.py

rename forward_service to mapreduce_service
according to
https://github.com/scylladb/scylladb/commit/3fc4e23a36aad7a418805797b08370a3f3ddae2b
```
< t:2024-07-29 10:05:48,274 f:db_stats.py     l:229  c:sdcm.db_stats        p:DEBUG > Response from Prometheus server: {'status': 'success', 'data': {'resultType': 'matrix', 'result': [{'metric': {'__name__': 'scylla_mapreduce_service_requests_dispatched_to_other_nodes', 'cluster': 'my-cluster', 'dc': 'eu-west-1', 'in
< t:2024-07-29 10:05:48,274 f:decorators.py   l:72   c:sdcm.utils.decorators p:DEBUG > 'validate_mapreduce_service_requests_dispatched_to_other_nodes': failed with 'Retry([{'metric': {'__name__': 'scylla_mapreduce_service_requests_dispatched_to_other_nodes', 'cluster': 'my-cluster', 'dc': 'eu-west-1', 'instance': '10.4.1.90', …
```

fix(FullScan): rename forward_service to mapreduce_service

---

docker/env/hydra.sh
unit_tests/test_hydra_sh.py

when doing so we can easily break users depends on which python version they are using, we shouldn't assume anything about user env.

fix(hydra): don't running any python code outside hydra image

---

sdcm/cluster.py

As we now verify ports being open from sct runner, we cannot use it for jmx as it listens on localhost.
Fix by verifying JMX being up by verification of log message in scylla-jmx service status.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8183

fix(jmx): fix wait for jmx up

---

jenkins-pipelines/oss/no_tablets/longevity-cdc-100gb-4h-no-tablets.jenkinsfile
jenkins-pipelines/oss/no_tablets/longevity-lwt-3h-no-tablets.jenkinsfile

Configure LWT/CDC new pipelines with tablets-disabled,
so it can be tested in 6.1, where tablets are enabled by default.

test(tablets): new pipelines with disabled-tablets  for unsupported features

---

sct.py
sdcm/sct_config.py

When looking at the test run in Argus (and in general) it's hard to get the idea what test method was used - which is sometimes hard to get for jobs that run tests in parallel (e.g. perf tests with different test methods for each workload: write, read, mixed).
Added new config param `test_method` so it will be visible in sct.log and can be consumed and properly displayed in Argus.
refs: https://github.com/scylladb/argus/issues/375

improvement(investigation): add test_method to config

---

sct.py

In case perf test results are missing we send email to have other test related info anyway. But this confuses the user as it looks in jenkins as everything is fine.
Fix by failing send-email step in such a case.

fix(jenkins): mark send-email step as failed when no results

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml
vars/createTestJobPipeline.groovy

the building of the jobs for v15 wasn't working since we introduced it the pipeline was trying to create regular master jobs and was failing
now it should skip, and and should create the jobs needed

fix(createTestJobPipeline): when build v15 branch, need to skip others

---

sct.py
sct_ssh.py
sdcm/cluster.py
sdcm/remote/base.py
sdcm/remote/remote_base.py
sdcm/remote/remote_cmd_runner.py

The change adds a new hydra command that allows to update DB binaries of the whole cluster or of selected nodes.
This functionality allows for a developer to update scylla version from their developing machine and re-run a test / run another test without the need to re-create a cluster (i.e. using reuse-cluster capability).
[x] :green_circle: (repeated for aws and gce)
- provisioned a cluster: [pr-provision-test](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dimakr/job/sct-pr-provision-test/48/)
- executed the new `update-scylla-packages` command for the test-id in question, selecting 2 DB nodes out of 3 for update and providing local folder as a location of new packages versions:
```
❯ ./sct.py update-scylla-packages --test-id bf149edb-c7b9-42f7-96c2-40c74df3c13b …
```

feature(hydra.sh): add a command to update scylla db packages

---

sdcm/provision/scylla_yaml/scylla_yaml.py
sdcm/utils/features.py
test-cases/upgrades/customer-profile/rolling-upgrade-custom-d1.yaml
upgrade_test.py
vars/supportedUpgradeFromVersions.groovy

this filter was assuming enterprise repo url, would have `enterprise` in them, that is not completly correct, the offical releases urls don't have `enterprise` in them.
regardless the code nowdays return the exact list of version needed for upgrade, and there no need for this filtering. (that was introduce in 2019, by fruch)

fix(rolling-upgrade): remove branch filter

---

sdcm/sct_provision/aws/instance_parameters_builder.py
sdcm/sct_runner.py
sdcm/tester.py
sdcm/utils/aws_utils.py

since we have images available in more then one account, and images are not always set as public, and we can see their metadata we should look them up in all of the account possible

fix(aws): `ec2_ami_get_root_device_name` to look into multiple accounts

---

sdcm/keystore.py

It seems like it's not safe to share clients between threads and we started seeing cases of SCT segfaulting
right at the start, during the `Keystore.sync()`
which run multiple threads to make the process faster but it doesn't help if it also make things unstable
looking at botocore issues, seem like it's documented that botocore isn't threadsafe
Ref: https://github.com/boto/botocore/issues/3164

fix(keystore): stop reusing boto3 clients in multiple threads

---

Jenkinsfile
vars/artifactsPipeline.groovy
vars/createArgusTestRun.groovy
vars/createSctRunner.groovy
vars/jepsenPipeline.groovy
vars/perfRegressionParallelPipeline.groovy
vars/provisionResources.groovy
vars/rollingUpgradePipeline.groovy
vars/runSctTest.groovy

since `requested_by_user` was missing, we ended up with provision tests resources tagged by `null` user
azure test shows it like:
```
Tag 'RunByUser' has value 'null' which is not allowed by Azure API. Replacing with empty string.
```

fix(provision-tests): add `requested_by_user` pipeline parameter

---

sdcm/cluster.py
sdcm/wait.py
unit_tests/test_wait.py

Some times log messages are written to log file with delay, this could cause that scylla already started, but log_follower couldn't find appropriate log messages, because they will be written later. This happened with RestartWIthReshardNemesis.
Scylla was stopped, scylla yaml was updated with new `murmur3_partitioner_ignore_msb_bits` value. Then scylla started and resharding is expected. Resharding is checked by log messages, but if for some reason log messages will be written with delay to log (log_follower will fail the nemesis)
Fixes: scylladb/scylla-cluster-tests#7427
- [Job with master passed](https://argus.scylladb.com/test/dc8131ca-2823-443a-9816-9eae668d6b6d/runs?additionalRuns[]=62cca91b-dc27-47aa-ae6b-ffdc8aa0cd2d)
- [Job with …

fix(restart_with_reshard): wait log messages for 10 minutes

---

defaults/aws_config.yaml
defaults/gce_config.yaml
defaults/test_default.yaml
sdcm/logcollector.py

Set the monitoring image to version 4.8.0

feature(monitoring): set the scylla monitoring image to 4.8.0

---

Jenkinsfile
docs/sct-runners.md
jenkins-pipelines/qa/hydra-clean-runner-instances.jenkinsfile
jenkins-pipelines/qa/hydra-clean-test-resources.jenkinsfile
jenkins-pipelines/qa/hydra-cleanup-cloud.jenkinsfile
jenkins-pipelines/qa/hydra-show-jepsen-results.jenkinsfile
jenkins-pipelines/qa/hydra-show-monitor.jenkinsfile
sct.py
sdcm/keystore.py
sdcm/sct_runner.py
sdcm/utils/aws_builder.py
sdcm/utils/gce_builder.py
vars/getJenkinsLabels.groovy

we are switching all jenkins workers to start using java-21 while we are at it, we are updates the sct-runners images to be based on ubuntu 2404 images

feature(sct-runner): update image to use java-21

---

defaults/severities.yaml
sdcm/sct_events/health.py
sdcm/utils/database_query_utils.py

validate_rows_per_partitions has assertions for the expected number of rows.
These assertions are now caught and generates a corresponding new event:
"PartitionRowsValidationEvent". This prevents failing the nemesis thread.
fixes: #8292
fixes: #8292
- https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/byo-longevity-test-yg/3/
Testing a simulated validation failure passed ok, looking like this:
```
2024-08-11 09:31:34.220: (PartitionRowsValidationEvent Severity.CRITICAL) period_type=one-time event_id=13c498e5-1bbb-4814-b5c8-a5dde28e7206: message=Found missing rows for partitions: {0: 55, 1: 55, 2: 55, 3: 55, 4: 55, 5: 55, 6: 55, 7: 55, 8: 55, 9: 55, 10: 55, 11: 55, 12: 55, 13: 55, 14: 55, 15: 55, 16: 55, 17: 55, 18: 55, 19: 55, 20: 55, 21: 55, 22: 55, 23: 55, 24: 55}
```
- …

fix(validate_rows_per_partitions): use a new validation event

---

defaults/k8s_eks_config.yaml
defaults/k8s_gke_config.yaml
defaults/k8s_local_kind_config.yaml
defaults/test_default.yaml
unit_tests/test_cassandra_stress_thread.py

we are migrating c-s from scylla-tools-java into a new repository, and now it's has it's own docker image and releases in dockerhub, we don't need to pull in scylla old docker images for c-s anymore.
Ref: https://hub.docker.com/r/scylladb/cassandra-stress

feature(c-s): start using c-s docker image from dockerhub

---

jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2404-nonroot.jenkinsfile

by mistake it was pointing 2204 configuration

fix(artifacts-offline): ubuntu 2404 to point to correct configuration

---

sdcm/cluster.py
sdcm/utils/docker_utils.py
unit_tests/test_utils_docker.py

If a cluster is kept running after the test is finished (for later reuse) the containerized autossh hooks associated with cluster DB nodes are not deleted. But
they are no longer associated with existing nodes - the association exists in runtime.
When a new test is started reusing the existing cluster, a new set of autossh containers would be created. But as the leftover autossh containers are still
holding local syslogng ports, which are mapped to remote syslogng ports on DB nodes instances, syslogng initialization for new test is blocked.
Eventually the test with reusing a cluster fails with the error:
```
< t:2024-08-12 21:12:03,798 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: wait for db logs: timeout - 300 seconds - expired
< t:2024-08-12 21:12:03,799 f:wait.py …
```

fix(reuse_cluster): cleanup leftover containers from previous run

---

sdcm/cql_stress_cassandra_stress_thread.py
sdcm/gemini_thread.py
sdcm/ndbench_thread.py
sdcm/scylla_bench_thread.py
sdcm/stress_thread.py

running with all those check enable hurt performence quite badly so far we enable `--network=host` in all docker loaders, but that not enough to make comparable with stress tool running ontop of VM
Ref: https://www.scylladb.com/2018/08/09/cost-containerization-scylla/

fix(docker-loaders): add `--security-opt seccomp=unconfined` to command

---

sdcm/nemesis.py

The decommission operation in nemesis code assigns the `nemesis.target_node` attr with the `None` value.
It leads to the following argus error when nemesis succeeds:
```
> Traceback (most recent call last):
>   File "%path%/sdcm/nemesis.py", line 5151, in argus_finalize_nemesis_info
>     argus_client = nemesis.target_node.test_config.argus_client()
> AttributeError: 'NoneType' object has no attribute 'test_config'
```
So, avoid this problem by getting argus client without target node.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/8341
- [scylla-staging/valerii/vp-longevity-10gb-3h-test#120](https://argus.scylladb.com/test/631c0991-5548-434e-b7a3-f47eb2db8777/runs?additionalRuns[]=af7fcd20-9ce1-4f12-85f7-8e4a61c7b84f) …

fix(nemesis): make argus correctly save end nemesis info after DB shrink

---

jenkins-pipelines/enterprise/artifacts/artifacts-docker-fips.jenkinsfile
sdcm/sct_runner.py
sdcm/utils/aws_builder.py
vars/getCloudProviderFromBackend.groovy
vars/getJenkinsLabels.groovy

in this change we introduce a new AWS ASG for testing
docker artifacts on top of FIPS machines,
it has a separated SCT runner, and ASG and labels in jenkins.
so it would be completely separate from the regular SCT runner images,
and can be updated separately

feature(docker): run docker artifact test ontop of FIPS

---

sdcm/fill_db_data.py
upgrade_test.py

Wrong extention was used upon restore back files for rhl based systems.
Fixes: scylladb/scylladb#19777
Additional commit should fix the logic with skip condition. Because upon create tables, logic of skip condition is reversed, need to set false in skip contition field
related to https://github.com/scylladb/scylla-cluster-tests/commit/19577df303c2c3131029d8f936beab6bfd4e43d7

fix(recover_backup): use correct file ext to restore backupt on rhl

---

sdcm/sct_events/loaders.py

The `invalid` word may easily be printed out by `gocql` driver in some warning.
In this case it should not be taken by the `ParseDistributionError` SCT event.
So, fix it by using more precise templates.
Closes: #7705

fix(events): make S-B distribution failure event filter be more precise

---

sdcm/cluster.py

Example of an error is here: https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-k8s-local-kind-aws-test/65/consoleFull
```
13:18:52  < t:2024-08-23 10:18:51,784 f:decorators.py   l:71   c:sdcm.utils.decorators p:INFO  > \
local-dc-1: Wait for the '3' pod(s) from the 'scylla' namespace with 'jsonpath='{.status.phase}'=Running' condition to be true... [try #1]
13:19:02  < t:2024-08-23 10:19:01,460 f:cluster.py      l:603  c:sdcm.cluster         p:ERROR > \
Failed to get number of cores due to the invalid literal for int() with base 10: \
"cp: can't stat '/etc/scylla/cassandra/logback-tools.xml': No such file or directory\n8\n"
13:19:42  < t:2024-08-23 10:19:36,265 f:decorators.py   l:71   c:sdcm.utils.decorators p:INFO  > \
local-dc-1: Wait …
```

fix(cluster.py): make `cpu_cores` function be resilient to multiline printouts

---

sdcm/stress/base.py

improvement(stress): Report two lines of the error, instead of only 100 characters

---

sdcm/argus_results.py
utils/migrate_latency_results_to_argus.py

Added simple script for migrating latency results data to Argus. Still semi automatic (need to specify job paths manually) but does the job.

improvement(argus): migrate latency results to Argus script

---

sdcm/cluster.py

sdcm.cluster.BaseNode.tags property attribute gets one of tag values from sdcm.cluster.BaseNode.ssh_login_info dict attribute, without checking if the latter has a value (by default ssh_login_info is None).
The commit addresses the problem by adding the corresponding check, to ensure that ssh_login_info has a value.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8404

fix(reuse_cluster): fix reuse_cluster flow for k8s-local-kind backend

---

sdcm/provision/scylla_yaml/scylla_yaml.py
test-cases/longevity/longevity-gce-custom-d1-workload1-hybrid-raid.yaml
test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml
unit_tests/test_scylla_yaml.py

The `reader_concurrency_semaphore_cpu_concurrency` scylla config option was added recently to mitigate one of the Scylla issues - https://github.com/scylladb/scylla-enterprise/issues/4206
So, add it's support to SCT and start using it in the `custom_d1` ones.

improvement(scylla.yaml): support `reader_concurrency_semaphore_cpu_concurrency` option

---

test-cases/longevity/longevity-gce-custom-d1-workload1-hybrid-raid.yaml
test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml

- [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload2-hybrid-raid#32](https://argus.scylladb.com/test/7a8a0e29-e8e2-45c4-9271-ec040095e4a7/runs?additionalRuns[]=e3092f3b-4a0f-4699-91c2-64a35bf5b0c8)

ci(custom_d1): start using deletion functions

---

vars/managerPipeline.groovy

This parameter is not required anymore since the same can be achieved via passing SCT_N_DB_NODES=<N> in extra_environment_variables.
Also, fixed extra_environment_variables parameter description to one more relevant for manager tests.

ci(manager): remove n_db_nodes from job parameters

---

jenkins-pipelines/manager/ubuntu22-manager-backup.jenkinsfile
mgmt_cli_test.py
test-cases/manager/manager-no-delta-backup-set-dataset.yaml

Closes https://github.com/scylladb/scylla-manager/issues/3936
Changes:
- The test that runs two backups one by one, no inserting any data to DB between them, and checks the 2nd backup takes time -> 0 has been added;
- Corresponding config file for 100GB dataset, test-case yaml and .jenkinsfile have been added as well.

test(manager): implement test for no-delta backup

---

sdcm/nemesis.py

before there was two seprate calls to `set_target_node` and to `set_current_disruption` that could end up with `set_target_node` setting None to the `target_node.running_nemesis`
this fix move `set_current_disruption` into `set_target_node` to avoid this problem, and also introduce a new paramter to `set_target_node` so any user of it can set what's the data that would be saved on the target node (it's only for debugging)
Fixes: #8198

fix(nemesis): make sure `set_target_node` always set `current_disruption`

---

defaults/test_default.yaml
vars/artifactsPipeline.groovy
vars/byoLongevityPipeline.groovy
vars/jepsenPipeline.groovy
vars/longevityPipeline.groovy
vars/managerPipeline.groovy
vars/perfRegressionParallelPipeline.groovy
vars/perfSearchBestConfigParallelPipeline.groovy
vars/rollingOperatorUpgradePipeline.groovy

Latest version of cassandra-stress (3.13.0) fixes the issue with snappy compression and changes the base image for Java. (now using JRE instead of JDK for running)

improvement(c-s): use latest cassandra-stress docker image

---

sdcm/mgmt/operator.py

Some of the longevity tests for the Operator (e.g., [longevity-scylla-operator-3h-eks-backup-test](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/gke/job/longevity-scylla-operator-3h-gke-backup-test/)) are failing because they exceed the 300 second timeout set in the get_mgr_backup_task method. After investigation, I noticed that this operation can take up to approximately 8 minutes, so I increased the timeout to 10 minutes. Link to successful run after increasing timeout [here](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/kamil-grzywinski/job/longevity-scylla-operator-3h-eks-backup-test/3/)

fix(operator.py): Increased timeout for get_mgr_backup_task method

---

sdcm/scylla_bench_thread.py

add information to each value in the mapping of it's type so we can correctly convert it, without generating needless warnings.
also adding a few missing value to the mapping
Fixes: #1624

fix(scylla-bench): refator results mapping

---

vars/byoLongevityPipeline.groovy

It used undefined parameter "pipelineParams".
refs: d2236eacd78496bd200583132e5f0ee5d3f73acf
refs: https://github.com/scylladb/scylla-cluster-tests/pull/8268/commits/d2236eacd78496bd200583132e5f0ee5d3f73acf

fix(byoLongevityPipeline): fix defaultValue of extra_environment_variables

---

microbenchmarking_test.py
sdcm/argus_results.py
sdcm/utils/microbenchmarking/perf_simple_query_reporter.py

Sending perf-simple-query results to Argus.
refs: https://github.com/scylladb/qa-tasks/issues/1244

improvement(perf-simple-query): send results to argus

---

sdcm/nemesis.py
sdcm/utils/decorators.py

if there's capacity error during a nemesis, we don't have much we can do about it, so we are gonna skip the nemesis insted just failing the nemesis
this change introduces a new decorator to help doing it on multiple calls in nemesis.py, later it can be extended to handle also other backend capacity issues (GCE/Azure), for now it handles only AWS capacity errors
Fixes: #7531

fix(nemesis): skip nemesis if there is capacity errors

---

configurations/manager/1TB_dataset.yaml
configurations/manager/2TB_dataset.yaml
configurations/manager/500GB_dataset.yaml
configurations/manager/5TB_dataset.yaml
defaults/manager_restore_benchmark_snapshots.yaml
docs/configuration_options.md
jenkins-pipelines/manager/ubuntu22-manager-backup-restore-custom-dataset.jenkinsfile
mgmt_cli_test.py
sdcm/mgmt/common.py
sdcm/sct_config.py
test-cases/manager/manager-backup-restore-set-dataset.yaml
vars/managerPipeline.groovy

Closes https://github.com/scylladb/scylla-manager/issues/3950
So, the PR introduces the new flow for Manager restore benchmark test - adds the option to run restore from pre-created backups - as well as improves the current approach.
The short summary of changes:
- Introduced the test that restores from pre-created backup. At the same time, the existing approach with populating the data, creating the backup from scratch and consecutive restore is kept in place;
- Some fixes to c-s stress cmds to speed up large datasets population process;
- Set rate limit to 0 to speed up backup operation in restore benchmark test;
- Added backup_bucket_location to list of Manager job parameters.
- Add unit tests to cover my …

Manager restore benchmark improvements

---

Jenkinsfile
sdcm/cluster_gce.py
sdcm/provision/common/configuration_script.py
sdcm/provision/common/utils.py
sdcm/sct_provision/user_data_objects/syslog_ng.py

The change makes the reuse-cluster feature testable/guarded, so we can ensure that it works when it is offered to a wider audience for use in their dev work.
Changes made are:
- add an additional checkbox/boolean option and a step to Jenkins longevity pipeline. If option is selected, the pipeline re-executes the test using the reuse_cluster functionality.
- fix syslog-ng startup script, so that it updates the existing service configuration with correct logging destination host/port on existing instances, when a cluster is reused.
- fix cluster initialization for GCE backend when reusing a cluster, so that it properly searches for existing instances.
- …

improvement(reuse-cluster): make reuse_cluster feature testable in CI

---

sdcm/provision/common/configuration_script.py

ConfigurationScriptBuilder should skip syslog-ng setup steps for artifacts tests, which do not use syslog-ng logs transport.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8527

fix(artifacts): skip configuring syslog-ng for artifacts test

---

sdcm/sct_config.py

In case we use Azure or simulated regions node name might get too long and fail to create certificates.
Shorten node names accordingly.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8523

fix(provision): shorten node name when Azure and simulated dc

---

configurations/manager/ubuntu24.yaml
jenkins-pipelines/manager/ubuntu24-manager-install.jenkinsfile
jenkins-pipelines/manager/ubuntu24-manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu24-manager-upgrade.jenkinsfile
sdcm/cluster.py

Closes https://github.com/scylladb/scylla-manager/issues/4001
The PR expands Manager tests (sanity, installation, upgrade) with coverage for Ubuntu24 distribution.
CI triggers added in https://github.com/scylladb/scylla-pkg/pull/4298

[Manager] Run tests on Ubuntu 24

---

sdcm/provision/azure/ip_provider.py
sdcm/provision/azure/network_interface_provider.py
sdcm/provision/azure/provisioner.py
sdcm/provision/provisioner.py
sdcm/sct_config.py
sdcm/sct_provision/instances_provider.py
sdcm/sct_provision/region_definition_builder.py
sdcm/sct_runner.py
unit_tests/provisioner/conftest.py
unit_tests/provisioner/test_provisioner.py

Usually tests don't need public ips as we basically work with private ones only.
Stop provisioning public ips in Azure when not needed.
closes: https://github.com/scylladb/qa-tasks/issues/1572

improvement(azure): skip providing public ip when not needed

---

sdcm/provision/scylla_yaml/scylla_yaml.py
unit_tests/test_scylla_yaml.py

Add support of the `allowed_repair_based_node_ops` scylla option to SCT.
It is useful for workarounding slow bootstraps in multi-dc setups with RBNO.
Example for disabling RBNO for `bootstrap` and `decommission` operations:
```
enable_repair_based_node_ops: true
allowed_repair_based_node_ops: "replace,removenode,rebuild"
```

improvement(scylla.yaml): support `allowed_repair_based_node_ops` option

---

defaults/manager_persistent_snapshots.yaml

Closed scylladb#7318
Since there is an issue with schema restore for old backup snapshots (scylladb#7318), new snapshots have been created (with latest Scylla 2024.2/6.0 version and Manager 3.3) instead of previous one.

test(nemesis): update manager persistent snapshots

---

configurations/manager/nodetool_refresh_las_and_prim_replica.yaml
jenkins-pipelines/manager/ubuntu22-manager-restore-data-outside-of-manager.jenkinsfile
mgmt_cli_test.py
sdcm/mgmt/cli.py
sdcm/sct_config.py
sdcm/utils/time_utils.py
test-cases/manager/manager-restore-outside.yaml

Closes https://github.com/scylladb/scylla-manager/issues/3993
The PR introduces the test that validate restore with L&S outside of Scylla Manager.
In addition to the test, contextmanager class that allows to measure execution time of wrapped function was added.

[Manager] Test to run restore with L&S outside of Manager

---

sdcm/cluster_azure.py

The change adds a method to sdcm.cluster_azure.ScyllaAzureCluster class to call syslog-ng (re)configuration script during reuse_cluster flow.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8520

fix(reuse_cluster): fix reuse_cluster flow for Azure backend

---

sdcm/tester.py
sdcm/utils/alternator/api.py

Tablets feature is currently supported by Alternator, but disabled by default (since LWT is not supported).
It should be explicitly requested by the specified tag.
fixes: #8197
refs: scylladb/scylladb#18068
fixes: #8197
- Test Alternator without LWT and TTL runs with tablets:
- - https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/reproductions/13/
- - - [test](https://argus.scylladb.com/test/dfa0a7dd-68a5-4a6c-8d9c-a1131811fdbe/runs?additionalRuns[]=b18b5cd1-2346-4ab0-8b20-b2fe7382b16b) passed ok
- - - 
```
Aug 07 16:14:34.708495 alternator-no-ttl-1-loaders-no-lwt--db-node-b18b5cd1-1 scylla[6397]:  [shard 0:stmt] migration_manager - Create new Keyspace: KSMetaData{name=alternator_usertable_no_lwt, strategyClass=org.apache.cassandra.locator.NetworkTopologyStrategy, …
```

improvement(Alternator): support creating tablets-enabled tables

---

sdcm/nemesis.py
sdcm/sct_events/group_common_events.py

The change adds a decorator helper that uses SkipPerIssues mechanism and applies (enters) provided contexts to a function if issue in question is open.
Also the new decorator is used to decorate mgmt_backup Nemesis disruption to skip take_snapshot related errors, until issue https://github.com/scylladb/scylla-manager/issues/3389
is resolved.

fix(disrupt_mgr): skip take_snapshot error per issue

---

sct.py

This commit corrects an issue where a test that would previously finish
with test error inside sct stage would get overwritten by jenkins
setting status to failed due to pipeline health
Fixes #8614

fix(sct.py): Ignore TEST_ERROR inside finish_argus_test_run

---

configurations/disable_rbno.yaml
jenkins-pipelines/master-triggers/sct_triggers/tier1-custom-time-trigger.xml
jenkins-pipelines/master-triggers/sct_triggers/tier2-custom-time-trigger.xml
jenkins-pipelines/oss/longevity/longevity-cdc-8h-multi-dc-topology-changes.jenkinsfile
jenkins-pipelines/oss/longevity/longevity-mv-si-4days.jenkinsfile
jenkins-pipelines/oss/sct_triggers/tier1-aws-custom-time-trigger.xml
jenkins-pipelines/oss/tier1/longevity-mv-si-4days-streaming.jenkinsfile
jenkins-pipelines/oss/tier2/longevity-cdc-8h-multi-dc-topology-changes-streaming.jenkinsfile

* Use streaming for one tier1 (`longevity-mv-si-4days`) and one tier2 (`longevity-cdc-8h-multi-dc-topology-changes`) longevity tests
* Are those two tests enough? Should I add more tests from different categories?
* Are those even right tests? 
* How can I verify that it uses streaming?
* For how long do I need to run tests to verify correctness of this PR?
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/8289

Use streaming instead of RBNO for a few longevity tests

---

sdcm/stress_thread.py

When HDR is enabled and expected, output inside the docker container is WORKDIR for c-s (currently /scylla-tools-java), but SCT is expecting it to be in root (/), the quickest way to tackle this issue is to make a working directory of the running docker container /.
This quick-fix is to make sure our mappings are ok and HDR output file is not empty as reported in https://github.com/scylladb/cassandra-stress/issues/23

fix(c-s): working directory for docker running c-s

---

defaults/aws_config.yaml
utils/copy_ami_to_all_regions.sh

seems like the loaders were missing the `PREPARED-LOADER` file, to really stop installing all bunch of unneeded packages, which are already should be in place, and in some cases might lead to errors trying related to identify the correct scylla product

fix(loader): update loader images to `scylla-qa-loader-ami-v22-ubuntu22`

---

sdcm/sct_config.py

since we don't set a default for `user_data_format_version` in case we are using images which are not scylla for the db nodes
we'll be hitting the following error in provision step:
```
pydantic.error_wrappers.ValidationError: 1 validation error for ScyllaUserDataBuilder
user_data_format_version
none is not an allowed value (type=type_error.none.not_allowed)
```
in all other backend we have default for this value, and in AWS we were missing it, it's only affecting once case we have that is running longevity without scylla images.

fix(aws-provision): have a default for `user_data_format_version`

---

sdcm/cluster.py

cause of recent improvement to speeding up test setup, now we can reach to situation monitor stack might spin before first db node is installed (i.e. when not using scylla images).
that in turn might cache the outcome of `is_enterprise` with a None value since no version is yet installed which later would cause the installation to try install scylla oss version.
this change is moving to a logic that check for the existence of both OSS and enterprise version, and if both doesn't exists it don't cache any value, so when eventually we do have a version available it would return the correct answer.
- Update the Readme/doc folder relevant to this change …

fix(is_enterprise): don't cache if no scylla is installed

---

sdcm/sct_provision/region_definition_builder.py
unit_tests/lib/fake_resources.py
unit_tests/provisioner/test_azure_region_definition_builder.py
unit_tests/provisioner/test_provisioner.py
unit_tests/test_log_collector.py
unit_tests/test_utils__operator__multitenant_common.py
utils/cloud_cleanup/__init__.py
utils/cloud_cleanup/aws/clean_aws.py
utils/cloud_cleanup/azure/clean_azure.py
utils/cloud_cleanup/gce/clean_gce.py

improvement(cleanup): update Argus on cloud cleanup
When cleaning instances with cloud cleanup scripts, Argus is not
updated. This makes `Resources` tab in Argus outdated and may mislead
users.
Update Argus when periodical cleanup script is triggering machine
termination/stop.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/8299
fix(azure): fix resources names
Azure instances names differ from `node.name` values. This causes
discrepancy between resources names between Argus-Azure. While in
testing it does not cause problems, updating resources status in Argus
raises error about missing resource name (because cleanup scripts base
on Azure names). …

improvement(cleanup): update Argus on cloud cleanup

---

sdcm/utils/decorators.py

If the decorator is applied dynamically, 'self' argument is not transferred  via 'args' and may be found in bounded function.
This commit allow to use the 'self' parameter of different instance types: ClusterTester, Nemesis. ClusterTester and Nemesis classes have a different naming convention for cluster, monitor and tester params. As result using of latency_calculator_decorator requires adaptation of those names to name them same.

improvement(decorator): adapt latency_calculator_decorator

---

sdcm/reporting/elastic_reporter.py
sdcm/tester.py

This commit adds a simple elastic reporter for the run status of a
particular job. This acts as a replacement to previously used
db_stats.py, notably being much simpler in both the usage and resulting
documents.
Task: scylladb/qa-tasks#1490

feature(sdcm/reporting): Add initial simple elasticsearch reporter

---

sdcm/utils/sstable/sstable_utils.py
upgrade_test.py

since the scylla sstable code doesn't fallback into any other option but reading schema from sstable of system tables, if --scylla-yaml-file is used.
switching to SCYLLA_CONF env variable should make the tool use other fallback options like reading the assuming the schema from the sstable we want to read.
Ref: scylladb/scylla-enterprise#4660

fix(scylla-sstable): switch from `--scylla-yaml-file` to `SCYLLA_CONF` env variable

---

sdcm/utils/replication_strategy_utils.py

In case no keyspace replication-factor value is retrieved in a DC,
A warning is logged and the keyspace is ignored (skipped).
Fixes: #8694

fix(_get_keyspaces_to_decrease_rf): Address a case where no keyspace RF value of DC

---

sdcm/cluster.py

the logic was missed when enabling oel9, and it made the jenkins job to get stuck on trying to connect to the CQL port

fix(oel9): stop/disable iptables and firewalld

---

sdcm/sct_config.py

the assumption in f2c93cc24982c5d63aab47d951b6bfe9a07cb6c1 was wrong and we can't really boot db node, clean with v2 any more.
changing the default back to using v3

fix(aws-provision): set default for `user_data_format_version=3`

---

add_new_dc_test.py
sdcm/nemesis.py
sdcm/tester.py

If consistent topology is enabled then auth-v2 is enabled, and we don't need to change RF or topology for system_auth keyspace.

fix(auth_v2): don't change system_auth

---

sdcm/argus_results.py
sdcm/utils/csrangehistogram.py
sdcm/utils/decorators.py

Collect throughput statistics from HDR file and report in Elasticsearch.
Now only latency is reported in the Report tab for performance tests.
This commit add throughput as well

improvement(hdr stats): collect throughput and report throughput in Result tab

---

sdcm/cluster.py

We need `system.log` to be collected for decommissioned/removed nodes for bugs investigation - this log contain proper timestamps. Also other collected usually files might be useful.
Collect logs like we collect them after tests for terminated VM's.
fixes: #6688

improvement(logs): collect db logs upon VM termination

---

sdcm/utils/net.py

some of the services we are using are a bit buggy
and was returning us ipv6 address, even when we were asking for ipv4 one.
so revising the list of services used, and changing the validation to be more specific and validate it's ipv4.
this was failing docker-artifact housekeeping check, cause addresses wasn't matching, and started out of the blue, without any code changes in that portions of the code (and no change relevant from scylla end as well).

fix(get_my_public_ip): update the list of services

---

configurations/performance/cql-stress-6gb-8-col-i4i-mini-test-throughput.yaml

Sometimes when working on improvement in performance tests it's needed to test it.
Added mini elasticity test configuration to allow such testing and is fast and cheap.

test(elasticity): add mini elasticity test for pre-testing

---

docker/env/hydra.sh

It will allow us to stop using locally installed python packages
which easily may become incompatible with the SCT code.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8639

fix(hydra): overmount "%home%/.local" dir

---

sdcm/report_templates/results_latency_during_ops.html

Full report prints None many time:
```
add_new_nodes
None None None None None None None None None None None None 
```
This is result of list update. Hide this output

fix(email): latency during ops template

---

configurations/performance/cassandra_stress_gradual_load_steps_enterprise.yaml
jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-scylla-gradual-throughput-grow-2.3gb.jenkinsfile
jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-scylla-gradual-throughput-grow-2.3gb.jenkinsfile
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml

Put gradual performance test pipeline to official master and enterprise folders. 
Separate configuration load_steps yaml for enterprise version.
Trigger new gradual enterprise test weekly instead latency and throughput tests

test(trigger): gradual enterprise test

---

sdcm/tester.py

This commit adds a pattern for an Azure allocation event, which is
similar to SpotTerminationEvent, to check_error, which is used to
determine if Argus should set this test's status as TEST_ERROR.

fix(sdcm/tester.py): Handle ZonalAllocationFailed in check_error

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml

Gradual enterprise test job name mistake in the weekly trigger xml

fix(trigger): gradual enterprise test

---

unit_tests/test_config.py

Desided to remove new gradual performance test required parameters validation (`sct_config._check_test_required_params` function). 2 unit test for this function were not removed.
Remove them now

fix(unittest): remove config tests 35 and 36

---

sdcm/wait.py
unit_tests/test_wait.py

We missed waiting time before recreating iterator. This causes unnecessary high cpu utilization.
refs: https://github.com/scylladb/scylla-cluster-tests/issues/8720

fix(wait_for_log_lines): fix saturating cpu when waiting for log lines

---

configurations/aws/new_ssh_key.yaml
jenkins-pipelines/artifacts-oel9.jenkinsfile

`scylla_test_id_ed25519` key is required for accessing the OEL9 instances. This change adds the dedicated configuration with the new key and updates the `artifacts-oel9` job to use the config.
The build is failing, which is expected, as branch-2024.1 requires a backport which is in progress in https://github.com/scylladb/scylla-cluster-tests/pull/8815. But the original issue is fixed by this change - as the test now passes the wait_for_ssh step (i.e. the new key enables ssh-ing to the node) and continues to the scylla-manager installation.

fix(oel9): use the new ssh key for oel9 artifact test

---

jenkins-pipelines/performance_staging/perf-regression-latency-mv-read-concurrency.jenkinsfile
performance_regression_test.py
test-cases/performance/perf-regression-latency-mv-read-concurrency.yaml

the idea is to test the hardest case - modifying a column that is a regular column in the base table, but in the materialized view is one of the primary key columns.
test steps
1 - 3 node cluster with 2  tables
2 - do special prepare CMD for table 1, and use table 2 as for latency PERF TEST (prepare_write_cmd) 3 - start read workload for table 2 - measure latency for table 2 (10min) (stress_cmd_r) 3 - do a special rewrite workload for table 1 to measure latency for table 2 (while changing for table 1 applying )(stress_cmd_no_mv) 4 - create MV, and wait for MV to sync - measure latency for table 2 (while MV is syncing )
5-  do special rewrite workload for table 1  again   - measure latency for table 2  (while changing for table 1 applying ) (stress_cmd_mv)
fixes: …

test(perf): add mv write test that increases latency of regular reads

---

sdcm/cluster.py

python2 doesn't exist in oel9, we shouldn't try installing it.

fix(oel9-offline-installer): don't install python2

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-with-nemesis-tablets.jenkinsfile

The comma is missed after test_email_title It caused to failure: WorkflowScript: 12: expecting ')', found 'perf_extra_jobs_to_compare' @ line 12, column 5. perf_extra_jobs_to_compare: scylla-master/perf-regression/scylla-master-perf-regression-

fix(pipeline): missed comma

---

sdcm/nemesis.py

since there currently no for fix for scylladb/scylladb#18059 we'll be skipping this nemesis until a fix for that issue would be available
Ref: scylladb/scylladb#18059

fix(nemesis): skip `disrupt_no_corrupt_repair` if needed

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml

aws_region is missed in weekly-master-performance-tablets-trigger.xml. As result the perf-regression-latency-650gb-with-nemesis-tablets test fails to start

fix(trigger): set aws_region

---

sdcm/sct_config.py

When user supplies invalid config files setting it causes `anyconfig` to raise problem with parsing `yaml` file - which is misleading.
Fix by verification of existence of config files before proceeding to anyconfig.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8844

fix(config): Raise proper error for missing config file

---

test-cases/performance/perf-regression-predefined-throughput-steps.yaml

Set c-s loader docker version to  'scylladb/cassandra-stress:3.13.0' for perf predefined throughput steps test

improvement(loader): set loader version hardcoded

---

sdcm/tester.py

SkipPerIssues was added for Alternator usage,
but its import is missing in 6.0

fix(tester.py): Add missing import of SkipPerIssue

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml

Master performance tests are triggered in eu-west-1 instead of us-east-1 due to 'region' parameter is missed in the trigger files. Fix it

fix(trigger): set 'region' in perf master triggers

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml

Recently we face out with resouces problem when weekly run performance tests.
To avoid this problem trigger set of tests with difference 9 hours

fix(triggers): run perf tests in defferent time

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml

Trigger of upgrade tablet tests are missed 'new_scylla_repo' param. Create its opwn BuildTriggerConfig for tablet upgrade tests and set this parameter and region

fix(trigger): params for upgrade tablet tests

---

sdcm/cluster.py

When updating multiple nodes db packages, SCT stops all the nodes. This is wrong and causes tests to fail when providing `update_db_packages` param.
Fix by removing broken logic and dropping code for nodes stop ordering.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8551

fix(update-db-packages): stop only updated nodes

---

sdcm/cluster.py

Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8846
- [scylla-staging/valerii/vp-longevity-aws-custom-d2-workload1-multidc#14](https://argus.scylladb.com/test/2c0a3aad-2dc8-4718-923e-af6271930f70/runs?additionalRuns[]=19520099-2f6f-41eb-999e-ebf170baa282)
- :green_circle: [pr-provision-test with client encrypt](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dimakr/job/sct-pr-provision-test/79/)
- :green_circle: [pr-provision-test with server encrypt](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dimakr/job/sct-pr-provision-test/80/)
- :green_circle: [pr-provision-test with server+client encrypt](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dimakr/job/sct-pr-provision-test/82/)
- Add New configuration option and …

fix(client_encrypt): make it work when server encryption is disabled

---

sdcm/nemesis.py
sdcm/sct_events/group_common_events.py
sdcm/utils/raft/__init__.py
sdcm/utils/raft/common.py

With raft topology, node which failed to bootstrap , removed from cluster
and banned. It could be added to cluster but it need to clean all scylla data before rebootstrap.
Depending on log message after which bootstrap is going to be aborted,
Bootstrap process could be finished ealier than command for abort will be executed
and node could be added to cluster.
New:
- Added additinal checks whether bootstrap finished successfull  before it would be aborted
- Added additional changeseverity filters for error messages expected to appear during
bootstrap aborting process
- Added decommission operation monitor, which allow to check whether decommission is running
after command failed for any reason and wait process to be finished.
- [Test passed with single …

fix(nodebootstrapabortmanager): always clean scylla data before rebootstrap

---

jenkins-pipelines/manager/ubuntu22-manager-restore-benchmark.jenkinsfile
mgmt_cli_test.py
sdcm/argus_results.py
sdcm/mgmt/cli.py

Closes https://github.com/scylladb/scylla-manager/issues/4027
Closes https://github.com/scylladb/scylla-manager/issues/4016
The goal is to keep and visualize Manager restore benchmark results in Argus.
Changes:
- Implemented the separate function to send Manager restore benchmark results to Argus. Resulting table consist of three fields: overall restore, download and load&stream and post-restore repair durations;
- Such Argus handler is added into restore benchmark tests;
- New properties were added into Manager cli to return info about version timestamp and post restore repair duration.
- Added jenkinsfile for manager restore benchmark test which will be included into release pipelines. Thus, we will
have the history of restore speed improvements or degradation release after release. …

Report Manager restore results to Argus

---

performance_regression_gradual_grow_throughput.py
sdcm/sct_config.py
test-cases/performance/perf-regression-predefined-throughput-steps.yaml

Warm up cassandra-stress commands should be defined as parameter in the test yaml.

improvement(gradual test): warm up commands as parameter

---

sdcm/cluster.py

Sometimes SM repo file download fails due various reasons.
Adding retrying as other steps that interact with network.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8710

fix(setup): add retrying to download sm repo file

---

sdcm/cluster.py
sdcm/nemesis.py
unit_tests/test_cluster.py

scylla commit https://github.com/scylladb/scylladb/commit/24589cf00cf8f1fae0b19a2ac1bd7b637061301a has stopped creating snapshots for virtual tables. 
hence we need to filter them out when compare tables to snapshot content.
without this change we'll be getting a mismatch between the expect list of tables to the actual tables that got snapshot

fix(disrupt_snapshot_operations): filter out virtual tables as needed

---

sdcm/sct_events/setup.py

Closes: https://github.com/scylladb/scylla-cluster-tests/issues/8693

fix(sct_events): ignore 'aborting on shard' events on rpc errors

---

sdcm/nemesis.py
sdcm/test_config.py

When running locally, all results are still sent to argus to 'local_run' test. We don't see it, we don't use it. It just create more data.
This commit skips creating argus client in case job name is 'local_run' (which maps to argus `test`).
closes: https://github.com/scylladb/scylla-cluster-tests/issues/7361

improvement(argus): disable argus for local runs

---

jenkins-pipelines/oss/artifacts/artifacts-rocky9-selinux.jenkinsfile
test-cases/artifacts/rocky9-selinux.yaml

since there are bugs related centos9 stream that we might not gonna attend to.
adding the test case to work also with rocky9
Ref: https://github.com/scylladb/scylladb/issues/19325

fix(artifacts): add rocky9-selinux

---

sla_per_user_system_test.py

in last enterprise-master(2024.1.3) deviation of workloads was improved and the test started failing with errors like:
"Actual ratio (0.9841362837441976) is not as expected (2.0)"
I assume it was implemented by design to hit such
improvement and adjust tests accordingly.
value comparison_axis was adjuster for version >=2024.3

fix(test_workload_types): adjust workload comparison

---

sdcm/argus_results.py
sdcm/utils/decorators.py
unit_tests/test_argus_results.py
utils/migrate_latency_results_to_argus.py

improvement(results): store cycle's 'start time'

---

test_lib/sla.py

due to implicit servis level creation
by put **cql_result into ```__init__```,
in 2024.3 we start got python exception:
```
"ServiceLevel.__init__() got an unexpected keyword argument"
```
This PR fixes this issue by putting arguments into ```__init__``` explicitly and added additional log message before ```__init__```
```
< t:2024-10-08 11:51:57,846 f:sla.py          l:86   c:test_lib.sla         p:DEBUG > SERVICE_LEVEL row: {'service_level': 'sl200_0', 'timeout': None, 'workload_type': None, 'shares': 200, 'percentage_of_all_service_level_shares': '12.50%'}
< t:2024-10-08 11:51:57,847 f:sla.py          l:86   c:test_lib.sla         p:DEBUG > SERVICE_LEVEL row: {'service_level': 'sl600_0', 'timeout': None, 'workload_type': None, 'shares': 600, 'percentage_of_all_service_level_shares': …
```

fix(sla): explicit ServisLevel creation

---

sdcm/report_templates/results_base.html
sdcm/reporting/elastic_reporter.py

This commit adds links to argus to the elastic search index and email
templates, allowing users to find argus runs quickly from those places.
Fixes scylladb/qa-tasks#1490

improvement(reporting): Add argus links to email template and elastic

---

sdcm/cluster.py
sdcm/tester.py
unit_tests/test_tester.py

Restoring monitor data with `hydra investigate show-monitor` sets default time range to recent 30m. This is unconvinient as requires to find test related time range manually.
This change hardcodes time range in dashboard defaults to range of test duration.
closes: https://github.com/scylladb/scylla-cluster-tests/issues/5045
closes: https://github.com/scylladb/argus/issues/454

improvement(monitoring): restore monitor with test time range

---

sdcm/cluster.py

Following #5101 we can now remove the apt-key refs

feature(cluster): remove apt-key refs

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/nemesis.py
sdcm/provision/network_configuration.py
unit_tests/test_scylla_yaml_builders.py

If test runs with 2 network interfaces configuration, 'disrupt_network_random_interruptions' nemesis fails with error:
```
File '/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py', line 3376, in get_rate_limit_for_network_disruption
return '{}{}'.format(random.randrange(min_limit, max_limit), rate_limit_suffix) ValueError: empty range for randrange() (0, 0, 0)
```
It happened because 'node_network_receive_bytes_total' is reported on device that broadcast_address is configured on it.
Now the device is set hardcoded to 'eth0'.
Failed test: https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=21961db0-285c-4b84-a4da-4d70be149e06 …

fix(nemesis): get bytes total for correct network device

---

performance_regression_gradual_grow_throughput.py

Running of 'post_prepare_cql_cmds' is missed in the perf-regression-predefined-throughput-steps test. It means that speculative retry was not disabled. It may have an impact on stability of the test performance

fix(gradual): run post_prepare_cql_cmds

---

defaults/manager_persistent_snapshots.yaml

10Gb snapshot made on Scylla 2024.2.0-rc1 is replaced by the image from fresher Enterprise version 2024.2.0-rc3.
It fixes the issue with restore of snapshot from rc1 to the latest versions, see for details:
https://github.com/scylladb/scylla-enterprise/issues/4737.
The change fixes frequent nemesis failures related to mgr restore.
Considering this solution as temporary and replacing only one snapshot (10GB) which is in wide use in nemesis. The rest of the snapshots will be replaced when the official 2024.2.0 version is released.

fix(manager): upload new backup snapshot for nemesis

---

performance_regression_gradual_grow_throughput.py

Prepare does not run during write load. So 'keyspace1' keyspace does not exist. It caused to failure of speculative_retry disable script. 
Error: `keyspace keyspace1 does not exist`
Start post_prepare_cql_cmds after prepare load only

fix(gradual): run post_prepare_cql_cmds after prepare

---

sdcm/cluster.py

On docker backend, getting monitor install path requires monitor nodes - which fail in tests without monitor.
Fix by returning early from the `update_default_time_range` method when no monitor nodes are present.

fix(tearown): fix set grafana time range when no monitors

---

performance_regression_gradual_grow_throughput.py

Test keyspace should be created with default compaction strategy as in all performance tests.

fix(gradulal): do not get compaction from default

---

sdcm/cluster.py

Running apt-get install with '--force-confold' and '--force-confdef' options doesn't block the process when the new package version provides a new version of configuration file (old version will be kept).

fix(manager): add --force-conf options to apt cmd for Manager upgrade

---

sdcm/utils/common.py

if stage skipped in test we expect that skip_optional_stage func returns true, but in fact returned false. This pr fix this issue
- Issue was reproduced https://argus.scylladb.com/tests/scylla-cluster-tests/3cee27f8-d6ff-4270-a4bf-d63f31948b5e
- Currently the test running on the same job with the same params (https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/eugene_test_folder/job/longevity-1tb-5days-azure-test/)

fix(util): fix skip_optional_stage logic

---

sla_per_user_system_test.py

adjust change https://github.com/scylladb/scylla-cluster-tests/pull/8922 to work with 2024.2 (https://argus.scylladb.com/tests/scylla-cluster-tests/c4fbed30-dc6d-4eee-b901-d8cb7d3c6519)
and use ComparableScyllaVersion SCT utility as suggested
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8961

fix(test_workload_types): adjust workload comparison for 2024.2

---

sdcm/tester.py

In case `self.monitors` is not defined, sct raises exception upon `update_default_time_range` invocation.
Add protection by checking if `self.monitors` is not `None`.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9023

fix(monitor): don't call monitor method when no monitors

---

sdcm/cluster.py

The AWS-KMS code in DB node python class uses shared dictionary
from the DB cluster class for updating the KMS endpoint region.
It was not a problem when DB nodes setup was serial.
In this case shared object was changed by each node but had proper value in needed time frame.
After implementation of the parallel DB nodes setup (https://github.com/scylladb/scylla-cluster-tests/pull/7383) 
we started getting problems that only one state of that shared object was being applied for all nodes.
In single-dc setups everything was correct just because there was no diff among DB node's region names.
But in multi-dc setups values from DB nodes started being applied to each other.
So, fix it by just deep-copying that shared dictionary to avoid updates of a shared object.
Closes: …

fix(kms): set proper node regions in multi-dc setups

---

sla_per_user_system_test.py
test-cases/features/system-sla-test.yaml

fix 1to5 ratio test for 2024.3
where tablets are enabled by default

fix(SLA) fix 1to5 ratio test for 2024.3

---

sdcm/utils/health_checker.py
sdcm/utils/raft/__init__.py
sdcm/utils/tablets/common.py

the whole idea of putting RAFT into separate module is to remove hundreds of spaghetti lines like:
if not current_node.raft.is_enabled
and put Raft helper functions under
node.raft.<HELPER> to avoid hundreds of helpers imports
it can be exceptions in case of using raft.is_enabled as part of a complex 'if' when code logic depends not only on the Raft feature
```
< t:2024-10-23 10:26:53,705 f:__init__.py     l:293  c:sdcm.utils.raft      p:DEBUG > Check group0 and token ring consistency on node longevity-10gb-3h-wait-for-db-node-73916f48-1 (host_id=01d35667-0e45-465c-81f1-eaefd772a168)...
```
```
< t:2024-10-23 10:36:55,202 f:common.py       l:36   c:sdcm.utils.tablets.common p:INFO  > Tablets are disabled, skipping wait for balance
```
```
< t:2024-10-23 10:49:06,796 f:__init__.py …
```

fix(RAFT) fix wrong raft.is_enabled usage

---

configurations/skip_test_stages.yaml
docs/skip-test-stages.md
performance_regression_alternator_test.py
performance_regression_gradual_grow_throughput.py
performance_regression_row_level_repair_test.py
performance_regression_test.py

Add possibility to skip selected stages of performances.
Closes: https://github.com/scylladb/qa-tasks/issues/1761

improvement(test-stages): add skip test stages option for perf tests

---

sdcm/sct_runner.py

When test fail, often sct-runners are kept for long - especially in perf tests. This is because of broken/unclear logic behind setting sct-runner keep flags.
Fixed that logic to:
- when test timeouted and logs collected, keep sct-runner for another 6 h
- if logs were collected, regardless of test status, terminate sct-runner immediately
- otherwise keep for additional 48h

fix(cleanup): cleanup sct-runner when logs collected

---

jenkins-pipelines/manager/debian11-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-older-enterprise-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-older-enterprise-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-upgrade.jenkinsfile

Some pipelines configuration changes related to Manager 3.4 coming release:
- upgrade pipelines adjusted to run upgrade from version 3.3.* instead of 3.2.*;
- older enterprise test is switched to use the oldest version mentioned (2022.2) in official documentation.

Pipeline configuration changes for Manager release 3.4

---

sdcm/nemesis.py

The nemesis ClusterRollingRestartRandomOrder is wrongly configured as config_change.

fix(nemesis): Remove incorrect definition of config_changes

---

sdcm/scan_operation_thread.py

fetch_result_pages had a "while" loop where a call to result.fetch_next_page() is missing. Adding it back.
Fixes: #8287

fix(full scan thread): Added missing fetch-next-page to fetch_result_pages

---

test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml

Also, increase number of DB nodes by 1 in each of the regions
to be able to support multi-row partitions keeping the current summary query rates.
- [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload2-hybrid-raid#54](https://argus.scylladb.com/tests/scylla-cluster-tests/c84f50a5-74ce-44b0-8c69-bd3d41c86933)

improvement(custom-d1-w2): use multi-row partitions

---

sdcm/sct_events/database.py
unit_tests/test_cluster.py
unit_tests/test_data/system.log

SCT detects the regex "Failed to load schema version" and creates an ERROR event out of it even if the message in scylla is with INFO severity. this behviour raises issues like
"https://github.com/scylladb/scylladb/issues/19093" which gets P3 priority but continue failing SCT tests over and over. Hence, this commit suggests to reduce this message severity.

refactor(SCHEMA_FAILURE): Change default severity of SCHEMA_FAILURE

---

configurations/advanced-rpc-compression.yaml
sdcm/provision/scylla_yaml/scylla_yaml.py
unit_tests/test_scylla_yaml.py

Since scylladb/scylla-enterprise@e951f5d3a7fd69e53fb4c51859ee96cbd5a56ebc, new RPC compression implementation is hidden behind an additional config entry: internode_compression_enable_advanced.
Tests which want to enable new RPC compression should set it to `true`.
I did not test this PR in any way, and I don't know how it could/should be tested.

fix(advanced-rpc-compression): set up internode_compression_enable_advanced

---

unit_tests/test_base_version.py

fix(unit-tests): add `2024.2` scylla version to list of base versions

---

sdcm/cluster.py

As per discussion in https://github.com/scylladb/scylla-cluster-tests/issues/9134, this clause can be removed as the ticket is resolved and doesn't have sct skip label (what could have made it being skipped). At the same, it led to unexpected failures when self.params appeared to be dict type instance instead of SCTConfiguration as expected.

fix(_rotate_kms_key): remove SkipPerIssues since the ticket is resolved

---

jenkins-pipelines/oss/longevity/longevity-large-partitions-with-network-nemesis-1h.jenkinsfile
test-cases/longevity/longevity-large-partitions-with-network-nemesis-1h.yaml

This commit introducing new large partition longevity focusing on disruptive nemesis including network nemesis (by configuring it with 2 network interfaces). The main motivation for this longevity is to be used by scylla gocql driver as an extended CI using scylla-bench.

test(large-partitions-1h): Introduce new short longevity with large partitions

---

mgmt_cli_test.py

Closes https://github.com/scylladb/scylla-manager/issues/4105
Changes:
- break-system-packages allows pip to modify an externally-manager Python installation while installing package on Ubuntu24.
- removed version specifying for the package since of compatibility issues with system-wide installation.

fix(manager): fix awscli installation on Ubuntu24 nodes

---

jenkins-pipelines/oss/longevity/longevity-mv-si-4days.jenkinsfile

~~~
Commit d722f0d38a6d ("test(tier1): Use streaming for
longevity-mv-si-4days.jenkinsfile test", 2024-09-11) intended to do four
things:
(1) create an *unmodified* copy of
"tier1/longevity-mv-si-4days.jenkinsfile" as
"longevity/longevity-mv-si-4days.jenkinsfile";
(2) create a *modified* copy of the same
"tier1/longevity-mv-si-4days.jenkinsfile" as
"tier1/longevity-mv-si-4days-streaming.jenkinsfile", with the
modification being the addition of "configurations/disable_rbno.yaml"
to the test config;
(3) redirect triggers from the original
"tier1/longevity-mv-si-4days.jenkinsfile" to the modified copy created
in (2);
(4) remove the original "tier1/longevity-mv-si-4days.jenkinsfile".
Step (1) was implemented incorrectly. The file created in step (1) is not
an *unmodified* copy; today it is …

fix(longevity): restore contents of "longevity-mv-si-4days.jenkinsfile"

---

artifacts_test.py
defaults/severities.yaml
sdcm/cluster.py
sdcm/sct_events/system.py
sdcm/utils/perftune_validator.py

perftune.py is a script within seastar (which is a part of scylla_setup) that configures several system parameters, like the amount of CPU cores that are designated to handle IRQ, and which are not.
Ref: https://github.com/scylladb/scylla-enterprise/issues/2909
Replacement of #6192

feature(artifact_test): testing the output of perftune.py

---

docs/using-full-scan-and-full-partition-scan-in-longevity.md

The background thread of full-scan or full-partition-scan, is used in Longevities. It's parameters are configured via test yaml file. This doc gives some explanations and usage instructions for that.

docs(full-scan): Add a guide doc for using full-scan and full-partition-scan

---

sdcm/logcollector.py

After switching Azure to use only private IP's we stopped collecting logs properly after the test in 'collect logs' jenkins stage. This is due using public ip for this.
Fix is about to use private ip if public is not available.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9178

fix(azure): fix log collector

---

sdcm/cluster_aws.py

seems like by mistake the code was trying to read SCT configuration from the wrong place, cause capacity_reservation to be ignored when nodes are added during the test.

fix(capacity_reservation): use it when adding nodes in runtime

---

upgrade_test.py

RPM base installation had specific procedure to handle rolling back into version that didn't had scylla-cqlsh,
now for rollback to a version that does have scylla-cqlsh, it was actually downgrading scylla twice, cause of the two downgrade commands.
we are removing this code, since current release doesn't need it anymore.

fix(rolling-upgrades): remove procedure for downgrade cqlsh

---

sdcm/cluster.py

Closes: 
https://github.com/scylladb/scylla-manager/issues/4112
According to [documentation](https://manager.docs.scylladb.com/stable/upgrade/index.html#upgrade-the-scylladb-manager-server-and-client), manager packages should be upgraded via running `sudo apt-get install scylla-manager-server scylla-manager-client -y`. 
`dist-upgrade` is used in current implementation. It may lead to some unexpected issues related to non-manager related packages upgrade. One of such issues is described in [ticket](https://github.com/scylladb/scylla-manager/issues/4112) where docker was upgraded as part of dist-upgrade. It led to stopping of all running containers (all monitoring stack).

fix(manager): fix upgrade flow to use apt install instead dist-upgrade

---

sdcm/nemesis.py

Use correct method to get cluster nodes status in disrupt_add_remove_dc method
Fixes: #9204
- [Individual Nemesis](https://argus.scylladb.com/tests/scylla-cluster-tests/d1e41d11-83c9-4020-8fd8-775158cb7438) - Nemsis passed

fix(add_remove_dc): Use correct method to get cluster status

---

defaults/severities.yaml
sdcm/sct_events/loaders.py
sdcm/stress_thread.py

From time to time we faced out with the problem that HDR file was not collected. But it is not clear if the file was not created or collected. This commit check if the file was not collected and try to collect it. If the file does not exist on the loader - throw error
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8949
Two HDR files were not copied to runner. The problem was recognised, the files were found on the loaders and copied to runner:
```
< t:2024-11-14 12:26:12,418 f:performance_regression_gradual_grow_throughput.py l:227  c:PerformanceRegressionPredefinedStepsTest p:INFO  > Run cs command with rate: 450000 Kops
< t:2024-11-14 12:56:26,262 f:stress_thread.py l:95   c:sdcm.stress_thread   p:DEBUG > '/home/ubuntu/sct-results/20241114-101651-000443/perf-regression-pr …
```

improvement(stress_thread): HDR file collection

---

sdcm/stress/latte_thread.py
unit_tests/test_config_get_version_based_on_conf.py

Two latte tests started failing after we switched to the latest latte version
where output got changed a bit and one of regexes stopped matching.
So, fix this part by supporting both outputs - old and new one.
Also, fix test with check for images presence in Azure backend.

fix(tests): fix integration tests

---

configurations/arm/centos9.yaml

the image we were using is now deleted from AWS, so we are switching to use `resolve:owner` option, so we can get the update centos9 image every time, without changing the hard coded AMIs every time.

fix(artifact-centos9-arm): change fixed AMI to resolve by owner

---

configurations/manager/rocky9.yaml
jenkins-pipelines/manager/rocky9-manager-install.jenkinsfile

Closes https://github.com/scylladb/scylla-manager/issues/3854
Closes https://github.com/scylladb/scylla-cluster-tests/issues/7678
The PR introduces Manager installation test for Rocky9 distribution since we were missing due to https://github.com/scylladb/scylla-cluster-tests/issues/7678.
PR to scylla-pkg to adjust corresponding test triggers:
https://github.com/scylladb/scylla-pkg/pull/4573

Manager installation test for Rocky9 distribution

---

mgmt_cli_test.py
sdcm/argus_results.py
sdcm/mgmt/cli.py

Closes https://github.com/scylladb/scylla-manager/issues/4108
Changes:
- Two restore metrics were added to be reported to Argus Results - `download` and `l&s` bandwidth.
- The PR also includes a fix for post-restore repair time calculation for Manager >= 3.4 - get duration from task summary rather than sum up across all repaired tables.
[Argus](https://argus.scylladb.com/workspace?state=WyJkNmY4OTI1Yy0xYTI2LTQzY2YtODY3NS04ZDQ2NjNkMDJlNmMiXQ) - see graphs and Results tab:
- [run #1](https://argus.scylladb.com/tests/scylla-cluster-tests/a3b84057-e98f-4773-9a21-195135283752) - Manager 3.3, no advanced metrics to be reported; workaround approach to calculate repair duration.
- [run #2](https://argus.scylladb.com/tests/scylla-cluster-tests/b4d77fc5-0cd7-4c71-886d-e2c301280270) - Manager 3.4, …

Improve Manager restore benchmark Argus charts with new restore metrics

---

defaults/test_default.yaml

Set default Manager version to 3.4.
The version was released on 05 Nov 2024 and passed through the standard flow of Manager release testing - [Argus release](https://argus.scylladb.com/dashboard/manager-3.4).

fix(manager): up manager default version to the latest released 3.4

---

unit_tests/test_parallelobject.py

test was casting time into int, and then diffing with expected timeout that was causing cases it might fail, if test was slowed down even by a little bit.
also defined the num_workers, so it won't be automatically set by number of CPU the test machine has, and won't be more deterministic

fix(test_parallelobject): replace `self.assertAlmostEqual` with  `pytest.approx`

---

sdcm/provision/azure/virtual_machine_provider.py
unit_tests/provisioner/fake_azure_service.py

Sometimes we cannot connect to Azure instance after provisioning and we don't know why.
Added debug log after provisioning instance with states info.
closes: https://github.com/scylladb/scylla-cluster-tests/issues/9201
example log line:
```
< t:2024-11-15 11:30:46,488 f:virtual_machine_provider.py l:119  c:sdcm.provision.azure.virtual_machine_provider p:DEBUG > Provisioned VM artifacts-azure-image-jenkins-db-node-3e60f00a-eastus-1 instance state: ProvisioningState/succeeded: Provisioning succeeded, PowerState/running: VM running
```

improvement(azure): add instance state debug log after provision

---

sdcm/utils/raft/__init__.py

After running `gemini` inside SCT
- https://jenkins.scylladb.com/job/scylla-staging/job/dusan/job/gemini/job/gemini-1tb-10h-test/12/
Command for the test never ran and SCT fails with.
TypeError: 'NoneType' object is not iterable'.
With some investigation it came down to
sdcm/utils/raft/__init__.py::NoRaft implementation ignored to implement `Generator`, used `return` with `yield`
Fixes #9176

fix(raft): generator was not correctly implemented in check_group0_to_kenring_consistency

---

sdcm/cluster.py
sdcm/utils/docker_remote.py

There is no any filtering of docker instances, when killing containerized stress threads on loader nodes during teardown of a test. In the case of docker backend this can result in deleting all containers in the system.
The change fixes this by labeling stress thread related docker containers when they are created; and deleting only the labeled containers during the teardown.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9027

fix(stress-threads): kill only labeled docker containers on loaders

---

defaults/aws_config.yaml
vars/longevityPipeline.groovy

Recently we're facing too many provision failures of spot instances, hence we would like to change the default in AWS of instance_provision_fallback_on_demand from false to true which should retry the proviosn with on_demand.

refactor(instance_provision_fallback): Change default to true in AWS

---

defaults/test_default.yaml
docker/latte/README.md

It is needed to be able to use `batch` queries we plan to use for `custom-d1` cases.

ci(latte): bump latte version to `0.28.1-scylladb`

---

jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-tablets.jenkinsfile
jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes.jenkinsfile
jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-write-tablets.jenkinsfile
jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-write-vnodes.jenkinsfile

Results of sub test-write that uses real loaders, not docker are more stable.
Create separate jobs for write subtests

improvement(gradual): run test-write with real loader

---

unit_tests/test_base_version.py

fix(tests): make version unit tests work after release of the Scylla 2024.2

---

sdcm/provision/aws/capacity_reservation.py

multi-dc scenarios are not supported in capacity reservations. Disable it when multi-dc is used to not raise errors.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9274

fix(capacity-reservation): disable for multi-dc

---

sdcm/cluster.py

Even with curl retry mechanism we still get issues with connection reset by peer, failing quickly and breaking test.
Improve retry mechanism by adding `--retry-all-errors` and decreased connection timeout to 10 seconds. Additionally use remoter retry mechanism.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9314

fix(setup): stabilise manager repo file download

---

sdcm/cluster.py

so far the code was using the `/share/cassandra/bin/nodetool` that is the old java based nodetool that depends on JMX
and now it would use the script from `/bin/nodetool` that should default to using `scylla nodetool` command

fix(offline-artifact-tests): use the correct nodetool script

---

sdcm/cluster.py

since this flag is only supported from curl 7.71.0 and up, we should yet be using it.
The warnings on this flag kind of make it a bit less helpful in our case, cause it can end up with multiple data in the output, and break our the repo definition.
Ref: https://curl.se/docs/manpage.html#--retry-all-errors

fix(setup): remove `--retry-all-errors` from manager repo file download

---

sdcm/db_stats.py
sdcm/sla/libs/sla_utils.py
sdcm/sla/sla_tests.py
unit_tests/test_sla_utils.py

change metric that used for SLA resource verification in longevity test cases from scylla_scheduler_runtime_ms to scylla_io_queue_total_operations
because looking into resources/CPU is wrong because 1 operation from low shares user can consume more resources than several operations from height shares user especially when we have a lot of other processes simultaneously(c-s, full_scan, nemesis) and cluster is not loaded to 100%
this PR affects only SLA nemeses. Other tests like  1to5 ratio where we have only 2 C-S loads and high CPU load will continue to work with scylla_scheduler_runtime_ms metric
- Update the Readme/doc folder relevant to this change …

fix(SLA): adjust SLA resources verification

---

sdcm/sct_config.py
unit_tests/test_config.py
unit_tests/test_config_get_version_based_on_conf.py

If scylla-manager is not disabled in a test config when running a test on docker backend, the test will try to install the manager and eventually fail (this is due to the fact that SCT installs scylla-manager server on monitor node and docker backend doesn't support dedicated monitoring node docker instance).
The change adds a check for this situation, to be able to fail fast and do not continue with manager installation on docker backend.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/9028

fix(docker-backend): do not start scylla-manager installation

---

configurations/custom-d1-workload2-repair.yaml
jenkins-pipelines/oss/longevity/longevity-gce-custom-d1-worklod2-hybrid-raid-repair.jenkinsfile
sdcm/sct_config.py
sdcm/stress/latte_thread.py
test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml

Add test that uses `custom-d1/workload2` scenario configuration and add following changes:
- Set `tombstone_gc` mode to be `repair`
- Enable `mgmt_repiar` nemesis
- Enable `hinted_handoff` feature
- Use `logged batch` queries
All of the above will allow to repro following bugs:
Ref: https://github.com/scylladb/scylla-enterprise/issues/4284
Ref: https://github.com/scylladb/scylla-enterprise/issues/4602
Ref: https://github.com/scylladb/scylla-enterprise/issues/4588
- `tombstone_gc=repair`: [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload2-hybrid-raid-repair#4](https://argus.scylladb.com/tests/scylla-cluster-tests/6253464f-945f-47ca-8163-dafaf01a644a)
- `tombstone_gc=disabled`: [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload2-hybrid-raid-repair#5](https://argus.scylladb …

test(custom-d1-w2): `mgmt-repair` + `tombstone_gc=repair` + `HH` + `log_batch`

---

jenkins-pipelines/oss/artifacts/artifacts-docker.jenkinsfile

After https://github.com/scylladb/scylla-cluster-tests/pull/9331 change was introduced the artifacts-docker test started to fail as it has `use_mgmt` config setting enabled by default.
This hot fix sets `SCT_USE_MGMT=false` env variable for the artifacts-docker jenkins job, so that the test can pass the SCT config validation.

fix(docker-artifacts-test): do not install manager by default

---

sdcm/nemesis.py
test-cases/longevity/longevity-multi-dc-rack-aware-with-znode-in-diff_dc.yaml

due to scylladb/scylladb#20356, need to skip nemesis disuprt_truncate_large_partition nemesis, because it use hardcoded scylla-bench command with autoresize rf
Number of nodes in DC increased, this allow to safely
decommission node with tablets feature enabled
- [Job with skipped truncate large partition nemesis](https://argus.scylladb.com/test/bbd702fb-2f87-4b0b-a068-c2c83d74cb77/runs?additionalRuns[]=bee77312-2370-4ea9-9ad7-7733096daa64)

fix(nemesis): skip truncate large partition nemesis with zero node

---

jenkins-pipelines/oss/artifacts/artifacts-docker.jenkinsfile

In https://github.com/scylladb/scylla-cluster-tests/pull/9353 a new parameter was added, but a missing `,` is failing the pipeline
fixing it

fix(docker-artifacts-test): add missing `,` between params

---

Jenkinsfile
longevity_test.py
unit_tests/test_cluster.py
unit_tests/test_longevity.py
unit_tests/test_utils_common.py

seems like we were running into situations we try to add all nodes ips into stress commands, and it's the test code
```
File ".../longevity_test.py", line 300, in test_user_batch_custom_time
self._run_user_stress_in_batches(batch_size=batch_size,
File ".../longevity_test.py", line 336, in _run_user_stress_in_batches
batch_params['stress_cmd'] += [params['stress_cmd'] + nodes_ips]
TypeError: list indices must be integers or slices, not str
```
in this change remove a parentheses that was causing function to return tuple and not string as expected

fix(test_user_batch_custom_time): handle stress command correctly

---

sdcm/sct_config.py

remove any special characters from `user_prefix`, since later it will be used as a part of the instance names and some platform don't support special characters in the instance names (docker, AWS and such)
Fixes: #8919

fix(sct_config): remove special characters from `user_perfix`

---

configurations/manager/100GB_dataset.yaml
mgmt_cli_test.py
sdcm/argus_results.py
sdcm/mgmt/cli.py

Introduce the `test_backup_benchmark` test, which measures backup time under read stress conditions. This test performs multiple actions to consolidate all necessary data into a single table. Initially, it runs and measures the backup process, followed by the read stress test. Finally, it executes both processes asynchronously to observe how the performance of reading and backing up degrades.
More metrics could be added after https://github.com/scylladb/scylla-manager/issues/4123 is completed
Test should be re-ran after https://github.com/scylladb/scylla-manager/issues/4125 is completed
Argus results:
For [100GB run](https://argus.scylladb.com/tests/scylla-cluster-tests/83b4a96b-28bb-4501-8116-01f909250c03)
|  | backup time [s] |
| --- | --- |
| Backup during read stress | 00:18:48 |
| …

Add backup benchmarking under read stress

---

defaults/test_default.yaml
docs/configuration_options.md
sdcm/sct_config.py
upgrade_test.py

During rolling upgrade scenarios the Scylla upgrade cycle starts with the system packages upgrade. The upgrade cycle has to be performed sequentially, a node at a time, but this is not a strict requirement for the step of upgrading system.
The change moves the step of upgrading system packages to the start of the test and parallelizes it across the nodes. This would save up to 65% of time needed for upgrading system on all nodes.
Additionally, a flag is added to the SCT config to indicate whether system upgrade is to be perfomed during rolling upgrade scenarios (enabled by default).
Closes: https://github.com/scylladb/qa-tasks/issues/1773

improvement(upgrade-test): upgrade node system early in the test

---

sdcm/cluster.py
sdcm/logcollector.py
sdcm/tester.py
unit_tests/test_tester.py

Collect `schema` and `system_schema.tables` info and save it on the runner. Add the new logs to the node logs archive.
Task: https://github.com/scylladb/qa-tasks/issues/1813

improvement(logcollector): collect schema info

---

sdcm/sct_events/group_common_events.py
unit_tests/test_cluster.py
upgrade_test.py

The error messages reported in https://github.com/scylladb/scylladb/issues/20754 and https://github.com/scylladb/scylladb/issues/20950 can be ignored till a proper fix is merged, because it's mostly a bad UX.
Need to be reverted when https://github.com/scylladb/scylladb/issues/20754 and https://github.com/scylladb/scylladb/issues/20950 will be fixed.
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/9346

fix(upgrade_test): ignore topology change coordinator errors during upgrades

---

sdcm/utils/raft/__init__.py

Since https://github.com/scylladb/scylladb/commit/36520250623a, scylla does not log "Finished token ring movement". Watching the log for this message would inevitably time out, consequently. Remove this log pattern.
Fixes #9281
The backporting question looks pretty bleak on this one:
- https://github.com/scylladb/scylladb/commit/36520250623a is part of `scylla-5.3.0-rc0` and `scylla-5.4.0` (in other words, even 5.4 *no longer logs* `Finished token ring movement`).
- the log pattern matching this message was first introduced in SCT commit 879fc686c55a, moved around in 607b8ba00a80, duplicated in 9a62d61e0af8, and de-duplicated in 2aa7dc9c5d38. The first of these, commit 879fc686c55a, is part of all the following branches:
- branch-2023.1
- branch-2023.1-future
- branch-2024.1
- …

fix(raft): drop stale log pattern as trigger for interrupting decommission

---

sdcm/logcollector.py
sdcm/utils/s3_remote_uploader.py

In case of corrupted sstables we try to upload all the sstables with limit of 400gb (uncompressed). This found out to be unpractical for two reasons: 1. takes too long to upload, 2. it fails due exhaustion of pages (10000 max, basicly around 80GB).
Fix is about sending all sstables only when they are smaller than 20GB in total, otherwise fallback to specific sstables only (one from error event + several latest ones).
Added also more logging messages for better debug experience.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9304

fix(sstables_upload): skip large sstables upload

---

sdcm/cluster_k8s/eks.py

MonitorSetEKS inherits  AWSCluster. It overrides the _create_instance method. The signature has been updated to include the previously missing argument, is_zero_node.
- [Job with fix](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/upgrade-scylla-k8s-eks-test/3/execution/node/127/log/)

fix(eks.py): use correct signature for method

---

sdcm/nemesis.py

The issue is relevant for parallel nemesis tests.
The node that is created by AddRemoveDc nemesis, may be set as target node by another nemesis. But this node is terminated in the end of nemesis. In this case the second (running in parallel) nemesis fails.
Use 'set_current_running_nemesis' on the new node in AddRemoveDC.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8401

fix(nemesis): new node in add remove dc

---

sdcm/nemesis.py

When this nemesis runs with multidc configuration, disrupt_mgmt_repair and disrupt_terminate_and_replace methods could choose target node from different dc, and _shrink_cluster method periodically failed with error:
```
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4277, in _shrink_cluster
raise Exception(error)
Exception: Not enough nodes for decommission
```
because target_node was chosen from dc where new node was not added by _grow_cluster method.
Additionaly set to run nemesis only for data nodes
- [Job passed](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/longevity-multi-dc-rack-aware-zero-token-dc/47)
- Update …

Fix(run_unique_sequence) with multidc

---

defaults/gce_config.yaml
defaults/k8s_gke_config.yaml
test-cases/scylla-operator/longevity-scylla-operator-multidc-12h.yaml
test-cases/scylla-operator/longevity-scylla-operator-multidc-3h.yaml

since 831116f450065f2d6b8f9d695cd4feadd6821348 changes the default instance type for gce, we need to chaneg the default disk number so we won't run into following error:
```
Number of local SSDs for an instance of type n2-highmem-8 should be one of
[0, 1, 2, 4, 8, 16, 24], while [3] is requested.
```
Ref: https://github.com/scylladb/scylla-cluster-tests/pull/9332

fix(gce): change default number of disks to 4

---

jenkins-pipelines/qa/devops-cloud-resources-report.xml

this report stopped working at Nov 24, cause it was using the v2 scaling group, that was missing java 21 to work with the new version of Jenkins server.

fix(devops-cloud-resources-report): use correct scaling group

---

defaults/test_default.yaml

Recent latte feature implementation missed adding a default parameter, namely:
latte_schema_parameters: {}
causing SCT tests fail with the following error message:
File "/home/ubuntu/scylla-cluster-tests/sdcm/stress/latte_thread.py", line 142, in build_stress_cmd
if latte_schema_parameters := self.params['latte_schema_parameters']:
KeyError: 'latte_schema_parameters'
The patch adds the missing parameter to defaults/test_default.yaml

test_default.yaml: Add missing default latte parameter

---

unit_tests/test_longevity.py
unit_tests/test_tester.py
unit_tests/test_utils_common.py

new introduced test was leaving the argus heartbeat thread running, casuing `test_sct_events_grafana.py::TestGrafana::test_grafana` to fail catching the POST request from the heartbeat, that it didn't expect.
and failing like the following:
```python
set_grafana_url("http://localhost", _registry=self.events_processes_registry)
with unittest.mock.patch("requests.post") as mock:
for runs in range(1, 4):
with self.wait_for_n_events(grafana_annotator, count=10, timeout=1):
for _ in range(10):
self.events_main_device.publish_event(
ClusterHealthValidatorEvent.NodeStatus(severity=Severity.NORMAL))
time.sleep(1)
self.assertEqual(mock.call_count, 0)
AssertionError: 1 != 0
unit_tests/test_sct_events_grafana.py:82: AssertionError
``` …

fix(unit-tests): stop argus heartbeat thread

---

test-cases/gemini/gemini-1tb-10h.yaml
test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-3h-with-nemesis.yaml
test-cases/gemini/gemini-8h-large-num-columns.yaml

As observed in a couple of new gemini runs [#6](https://argus.scylladb.com/tests/scylla-cluster-tests/f0c504cb-4bf5-47d4-a6bb-f0a102ec7fe4) [#7](https://argus.scylladb.com/tests/scylla-cluster-tests/26276989-e33c-40f1-9e94-788a4d824344) [#4](https://argus.scylladb.com/tests/scylla-cluster-tests/193e537e-e025-4857-86db-2156cd870fc3) [#2](https://argus.scylladb.com/tests/scylla-cluster-tests/41d1290a-1998-4bf4-9d15-4b21ad98cff9) Gemini's failures are caused by not having enough nodes in the test DB when cluster in run with Tablets, and by that we cannot establish quorum. This PR increases the number of nodes in the test DB to 4 in all relevant cases with nemesis.

fix(gemini-test-nodes): Increase the number of nodes in the test DB from 3 to 4

---

Jenkinsfile
vars/artifactsPipeline.groovy
vars/byoLongevityPipeline.groovy
vars/dockerLogin.groovy
vars/jepsenPipeline.groovy
vars/longevityPipeline.groovy
vars/managerPipeline.groovy
vars/perfRegressionParallelPipeline.groovy
vars/perfSearchBestConfigParallelPipeline.groovy
vars/rollingOperatorUpgradePipeline.groovy
vars/rollingUpgradePipeline.groovy

we introduce this call on top of the call we having in SCT code so we won't hit the limit while pulling hydra images themselves
Fixes: scylladb/scylla-pkg#4634

fix(pipelines): call docker login on all pipelines

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml

Old tests perf-regression-latency-shard-aware-1TB and perf-regression-throughput-shard-aware-i4i should not be triggered

fix(performance): not trigger old tests

---

jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis-rbno-disabled.jenkinsfile
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml

Add 'scylla-enterprise-perf-regression-latency-650gb-with-nemesis' test with RBNO disabled

test(performance): add latency with nemesis and disable RBNO

---

sdcm/tester.py

There are cases when it is not needed to send error event from silence decorator. It just needs to silence the failure and keed its info in the log

improvement(decorator): not raise error event by silence decorator

---

vars/longevityPipeline.groovy
vars/perfRegressionParallelPipeline.groovy

When provision step fails there's usually no point in progressing to another step as it probably also fail.
fix by stopping catching errors in provision step.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9083

fix(pipeline): fail ci on provision error

---

sdcm/provision/common/utils.py

since in recent release of scylla audit is enabled by default we are filtering it by default for the time being.
in some nemesis code we are doing lots of separate commands which generate too many audit events, that make our logging system out of sync with the test flow, and generate false positives.

improvement(syslog-ng): filter audit prints

---

configurations/t3_micro.yaml
configurations/t3_micro_data_volumes.yaml
jenkins-pipelines/oss/artifacts/artifacts-ami-t3_micro.jenkinsfile

Following https://github.com/scylladb/siren/issues/12513#issuecomment-2531280261, removing the extra disk that we are attaching to this artifact

fix(ami-t3_micro): remove extra disk

---

sdcm/nemesis.py

since this command can take long, and ssh connection might get interrupted we should use the `long_running=True` option, so the command would be executed on the node, and retrieve the output when it finish.
Fixes: #9494

fix(disrupt_remove_node_then_add_node): call `nodetool removenode` as long_running

---

sdcm/nemesis.py

Decorator `disrupt_method_wrapper` rewrites target node pool and always set Nemesis._target_node_pool as data_nodes. This cause that target node is chosen from cluster.data_nodes always. This happemed because we have decorators chain:
disrupt_method_wrapper -> target_(data/zero/all)_nodes -> disrupt_*
Target node is chosen in `disrupt_method_wrapper`, and any changes in target_*_pool does not affect of target node if it is run in complex nemesis as SisyphusMonkey and also has affect in parallel nemesis run
Set method attribute disrupt_*.target_pool for later use in decorator `disrupt_method_wrapper`, allows correctly set target pool for disrupt nemesis
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9448
Used solution from pr: …

fix(nemesis-target-pool): set method attribute for target pool

---

sdcm/coredump.py
sdcm/nemesis.py
sdcm/sct_events/system.py
unit_tests/test_data/test_coredump/filebased/fail_upload_test_remoter.json
unit_tests/test_data/test_coredump/filebased/fail_upload_test_results.json
unit_tests/test_data/test_coredump/filebased/success_test_remoter.json
unit_tests/test_data/test_coredump/filebased/success_test_results.json
unit_tests/test_data/test_coredump/systemd/exceptions_limit_not_reached_test_remoter.json
unit_tests/test_data/test_coredump/systemd/exceptions_limit_not_reached_test_results.json
unit_tests/test_data/test_coredump/systemd/fail_upload_test_remoter.json
unit_tests/test_data/test_coredump/systemd/fail_upload_test_results.json
unit_tests/test_data/test_coredump/systemd/success_test_remoter.json
unit_tests/test_data/test_coredump/systemd/success_test_results.json
unit_tests/test_data/test_coredump/systemd/success_test_systemd_248_remoter.json
unit_tests/test_data/test_coredump/systemd/success_test_systemd_248_results.json

The change adds reducing of coredump event severity during disrupt_network_block disruption, if coredump was triggered by an error in networkd service of
version 255 or lower (the root cause is decribed in https://github.com/scylladb/scylla-cluster-tests/issues/9135).
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9135
The CoreDumpEvent events severity is reduced during the test:
```
❯ grep 'CoreDumpEvent Severity' -rn -A1 sct-runner-events-8e69a961
sct-runner-events-8e69a961/events.log:728:2024-12-10 09:10:06.374: (CoreDumpEvent Severity.WARNING) period_type=one-time event_id=a53eda06-9288-4679-ba76-61781b5cd728 during_nemesis=NetworkBlock node=Node longevity-5gb-1h-BlockNetworkMonkey-db-node-8e69a961-1 [63.33.152.9 | 10.4.20.40] …
```

fix(nemesis): ignore networkd coredumps during BlockNetwork nemesis

---

sdcm/nemesis.py
sdcm/utils/raft/common.py

Raft coordinator could be elected later than
1 second as it happened:
https://argus.scylladb.com/tests/scylla-cluster-tests/174c3e71-e15a-454a-a473-9452c86519ab
- [Passsed job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-100gb-4h/131)

fix(raft): retry search topology coordinator

---

sdcm/nemesis.py
sdcm/sct_events/group_common_events.py

since this issue was declared P4, we'll gonna ignore it for now, since after one or two retries the node does spin up
Ref: scylladb/scylladb#20387

fix(ipv6-reboot): ignore Prometheus failures in node init

---

sdcm/sct_config.py

in case we got empty envirment variable for on of the config option using `str_or_list_or_eval`, we end up with `['']` which maps to True (python truthiness)
in turn it did break azure cleanup logic when `SCT_AZURE_REGION_NAME=` was passed empty, and the cleanup didn't found any resources groups to clean.

fix(sct_config): `str_or_list_or_eval` to better return empty values

---

sdcm/nemesis.py

in ecc2c7e64206a1c4a465873c5c38caa66e2dbde4 `long_running=True` parameter was introduced, but it must come together with `retry=0`, and that was forgotten
Fixes: #9534

fix(nemesis): `disrupt_remove_node_then_add_node` was missing retry=0

---

docs/configuration_options.md
sdcm/sct_config.py

Environmental variable SCT_AWS_ACCOUNT_ID is used in aws_okta.py:
`account_id = os.environ.get('SCT_AWS_ACCOUNT_ID', '797456418907')`
The fact it's not defined in sct_config.py fails SCT test execution for non-default AWS account, ID of which is passed as env variable:
`ValueError: Unsupported environment variables were used: -
SCT_AWS_ACCOUNT_ID=400694452550`
The described above case is relevant for SCT tests with the cluster created in Scylla Cloud.

fix(sct_config): define SCT_AWS_ACCOUNT_ID in SCTConfiguration

---

sdcm/cluster.py
sdcm/logcollector.py
sdcm/tester.py
unit_tests/test_tester.py

This commit brings the few fixes:
1. save schema info on the runner locally and collect it in SCT folder
2. use silence decorator for every run of schema info command. It's to prevent stop info collection on failure
3. collect schema info from one live node

fix(logcollection): save schema info output

---

sdcm/stress_thread.py

cause code assumed HDR to be located on `$HOME`, in some situations like in the intergation tests of c-s, it wasn't finding it and failing like the following:
```
FAILED unit_tests/test_cassandra_stress_thread.py::test_01_cassandra_stress -
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'cp cs-hdr-write-l1-c0-k1-4bf4051d-abc0-4c0d-840d-f0af5c6b6e8a.hdr
/home/ubuntu/scylla-cluster-tests/unit_tests/
cs-hdr-write-l1-c0-k1-4bf4051d-abc0-4c0d-840d-f0af5c6b6e8a.hdr'
Exit code: 1
Stdout:
Stderr:
cp: cannot stat 'cs-hdr-write-l1-c0-k1-4bf4051d-abc0-4c0d-840d-f0af5c6b6e8a.hdr': No such file or directory
```
- Update the …

fix(stress_thread): stop assuming current path

---

unit_tests/test_config.py

the image used in those test isn't available anymore, and this feature it now use by default for loader and monitor images.
hence those test are not needed anymore, and would be removed since it gets covered on a daily basis

fix(integration-tests): remove tests that search AMI by name

---

mgmt_cli_test.py
pyproject.toml
sdcm/argus_results.py
sdcm/sct_config.py
sdcm/tester.py
unit_tests/rest/test_compaction_manager_client.py

since we have this check on older branches using pylint and it's easily fixable checked, we are introducing this one to minimize issues with backporting
Ref: https://docs.astral.sh/ruff/rules/f-string-missing-placeholders/#f-string-missing-placeholders-f541

feature(ruff): add `f-string-missing-placeholders (F541)` to linter

---

docs/configuration_options.md
sdcm/sct_config.py

the table generated into `docs/configuration_options.md` was not very readable and more, and need to be vertical scrolling, that make it hard to work with.
this change is replacing the table with a header list of each configuration and make it a bit more readable and automaticlly linkable with no further tricks.

feature(sct_config): generate markdown as list

---

jenkins-pipelines/enterprise/artifacts/artifacts-docker-fips.jenkinsfile

After https://github.com/scylladb/scylla-cluster-tests/pull/9331 change was introduced the artifacts-docker-fips test should have SCT_USE_MGMT=false set in the pipeline, for SCT to pass config validation.

fix(artifacts-docker-fips-pipeline): do not install manager by default

---

sdcm/tester.py

Various nemesis use `_prepare_test_table` method for creation of
keyspaces and tables if it is absent.
This method uses `reliable_replication_factor` property from the tester module.
The problem with it is the improper replication factor calculation.
It takes maximum nodes amount in a region, reduces by 1, and then uses it as RF.
In test setups which don't have those keyspaces
and have many nodes per each region,
the resulted keyspaces get replicated to much more nodes then it is needed.
Example: `5dcs` with `12` DB nodes each will have `RF=11`.
In summary, it will be `55` DB nodes out of `60`.
So, fix it by using python `min` function which will choose
either "3" or smaller value if DB nodes count requires it.
- …

fix(tester): fix `reliable_replication_factor` method by setting proper RF

---

longevity_test.py
pyproject.toml
sct_ssh.py
sdcm/cluster_k8s/__init__.py
sdcm/coredump.py
sdcm/fill_db_data.py
sdcm/mgmt/cli.py
sdcm/nemesis.py
sdcm/provision/scylla_yaml/scylla_yaml.py
sdcm/scan_operation_thread.py
unit_tests/provisioner/fake_azure_service.py
unit_tests/test_scylla_yaml_builders.py

those lint rule helps removing unneeded code parts
Ref: https://docs.astral.sh/ruff/rules/#flake8-pie-pie

feature(ruff): start lint `flake8-pie` (PIE)

---

sdcm/cluster.py
sdcm/provision/scylla_yaml/node_builder.py
sdcm/provision/scylla_yaml/scylla_yaml.py
unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.result.json
unit_tests/test_data/test_scylla_yaml_builders/functional.result.json
unit_tests/test_data/test_scylla_yaml_builders/jepsen.result.json
unit_tests/test_data/test_scylla_yaml_builders/longevity-10gb-3h.result.json
unit_tests/test_data/test_scylla_yaml_builders/manager-backup-1TB-gce.result.json
unit_tests/test_data/test_scylla_yaml_builders/multi_network_interfaces/cdc-replication-longevity.result.json
unit_tests/test_data/test_scylla_yaml_builders/multi_network_interfaces/longevity-10gb-3h.result.json
unit_tests/test_data/test_scylla_yaml_builders/perf-regression.100threads.30M-keys.result.json
unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.result.json
unit_tests/test_scylla_yaml_builders.py

* configure `listen_interface` in scylla.yaml as needed
* return correct selected interface on `get_nic_devices()`
* run `scylla_sysconfig_setup` again on right network interface

fix(multi-networks): configure scylla correctly with the right interface

---

sdcm/nemesis.py

raft is generating the following errors:
raft_topology - topology change coordinator fiber got error std::runtime_error
when one of the nodes is stopped, it was decided we can safely ignore those errors
fixes: #9031

fix(nemesis): filter raft-topology errors when starting/stopping nodes

---

sdcm/provision/scylla_yaml/scylla_yaml.py

by mistake `listen_interface` was duplicated, and ruff PIE check uncovered it.
this change remove the newly introduced definition

fix(scylla_yaml): remove duplication of `listen_interface`

---

sdcm/logcollector.py

`>&` redirecting syntax has been replaced by `> file 2>&1` to support shells like sh. 
Such a shell is a default on Manager node deployed in Cloud. That makes impossible logs collection there.
In terms of compatibility, `> file 2>&1` should behave consistently across different systems and shells.
Has logs for siren-manager.
Checked that all log files were collected, no regression.

fix(logcollector): fix remote collect cmd to support non-bash shells

---

configurations/performance/latency-decorator-error-thresholds-nemesis-ent-tablets.yaml
configurations/performance/latency-decorator-error-thresholds-nemesis-ent-vnodes.yaml
configurations/performance/latency-decorator-error-thresholds-steps-ent-tablets.yaml
configurations/performance/latency-decorator-error-thresholds-steps-ent-vnodes.yaml
defaults/test_default.yaml
docs/configuration_options.md
jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis-tablets.jenkinsfile
jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis.jenkinsfile
jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes.jenkinsfile
jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-tablets.jenkinsfile
jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes.jenkinsfile
jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-write-tablets.jenkinsfile
jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-write-vnodes.jenkinsfile
sdcm/argus_results.py
sdcm/sct_config.py
sdcm/utils/decorators.py
unit_tests/test_argus_results.py

Added validation rules for results sent by
`latency_calculator_decorator` to Argus.
Each workload and result name (nemesis, predefined step) may set own rules.
Current rules were created based on existing results - to pass typical good results.
closes: https://github.com/scylladb/scylla-cluster-tests/issues/9237

improvement(perf): add validation rules for latency decorator

---

sdcm/sct_config.py

the code handling those config values is only handling int, or string and the function name should mention that.
also remove the fallback to `ast.eval`, since it can produce anything and not just str or int values, which the code would fail on.

fix(sct_config): rename `int_or_list` to `int_or_space_separated_ints`

---

sdcm/utils/common.py

in order to minimize the noise from development images, we should list as offical released images only images labels with `environment=production`

fix(list-images): filter images by `environment=production`

---

jenkins-pipelines/oss/longevity/longevity-aws-custom-d2-workload1-3dcs.jenkinsfile
jenkins-pipelines/oss/longevity/longevity-aws-custom-d2-workload1-5dcs.jenkinsfile
sdcm/provision/scylla_yaml/scylla_yaml.py
test-cases/longevity/longevity-aws-custom-d2-workload1-3dcs.yaml
test-cases/longevity/longevity-aws-custom-d2-workload1-5dcs.yaml
unit_tests/test_scylla_yaml.py
utils/lint_test_cases.sh

First configuration is `small` - 3 DCs, 3 nodes per each.
Second configuration is `big` - 5DCs, 12 nodes per each.
This `big` setup never reached the `Test start` stage
because of the very slow bootstrap process in a multi-dc environment.
Ref: [#19131](https://github.com/scylladb/scylladb/issues/19131)
- Small (Ok): [scylla-staging/valerii/vp-longevity-aws-custom-d2-workload1-multidc#14](https://argus.scylladb.com/test/2c0a3aad-2dc8-4718-923e-af6271930f70/runs?additionalRuns[]=19520099-2f6f-41eb-999e-ebf170baa282)
- Big (Fail): [scylla-staging/valerii/vp-longevity-aws-custom-d2-workload1-multidc-big#5](https://argus.scylladb.com/test/9355434b-2452-4fcd-a4f4-6493c2558433/runs?additionalRuns[]=2aa7296a-806f-4c0d-b2e5-448e96911e82) …

test(customd2): add custom_d2/workload1 test configurations

---

docs/configuration_options.md
sdcm/sct_config.py
unit_tests/test_config.py
unit_tests/test_teardown_validator.py

introduce new option for appending to string or list configuration values
1) strings: can be appended with adding `++` at the begining of the string:
`export SCT_APPEND_SCYLLA_ARGS="++ --overprovisioned 1"`
2) list: can be appended by adding `++` as the first item of the list
`export SCT_SCYLLA_D_OVERRIDES_FILES='["++", "extra_file/scylla.d/io.conf"]'`
Note list would work on every config defiend with `str_or_list_or_eval` with the expection of `config_files`, `region_name`, `gce_datacenter` and `gce_datacenter` which can't be appended, and would need to be overriden completly
Ref: https://github.com/scylladb/scylla-cluster-tests/issues/7653
- Update …

feature(sct_config): appendable configuration values

---

sdcm/cluster.py

Fix changes directory for startup script upload from /tmp to $HOME. 
The change is required for DB nodes deployed in Cloud where /tmp dir is mounted with noexec option what makes script 
execution impossible there.

fix(BaseNode): change directory for startup script upload from /tmp to $HOME.

---

sdcm/argus_results.py

During backport process ValidationRule was unintentionally removed. Fix by adding it back.

fix(argus-results): fix missing import

---

defaults/test_default.yaml
sdcm/sct_config.py
sdcm/utils/decorators.py

`latency_calculator_decorator` requires workload to be set. Up to now it was taken from the test name. This change allows to set it by `workload_name` test parameter, so it can be used in all kind of tests.
Added latency verification for all 'individual nemesis' cases (proposal, anyway need to test with something).
closes: https://github.com/scylladb/scylla-cluster-tests/issues/9627

improvement(latency_calculator): allow use it in longevity tests

---

sdcm/sct_config.py
sdcm/utils/aws_utils.py

fix the code not to do API calls to ec2 when instance type isn't defines, and fallback to assume x86 image is requested.
it was failing during cleanup command where we might not have a full configuration available, but we should still carry on and execute the cleanup (we don't really need instance types for cleanups)
Fixes: #8352

fix(sct_config): don't fail on empty instance type

---

sdcm/cluster.py
sdcm/provision/user_data.py
test-cases/manager/manager-regression-azure.yaml

Closes https://github.com/scylladb/scylla-cluster-tests/issues/9630 https://github.com/scylladb/scylla-cluster-tests/issues/8226
The PR switches Manager tests on Azure from using centos-based to rhel-based.
Together with that, it implements a couple of different fixes to make such node setup possible (see list of commits for details).

Replace out-of-support CentOS distro with RHEL9 for Manager tests on Azure

---

sdcm/sct_runner.py
sdcm/utils/aws_builder.py

cause of issue caused by mismatch of java version between master and sct builder, we are building a new sct runner image that has up-to-date java version
Ref: scylladb/scylla-cluster-tests#9444

feature(sct-runner): version 1.9 with java 21.0.5

---

defaults/manager_versions.yaml
jenkins-pipelines/manager/debian11-manager-install.jenkinsfile
jenkins-pipelines/manager/debian11-manager-sanity.jenkinsfile
jenkins-pipelines/manager/debian11-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-vnodes-tablets-enterprise.jenkinsfile
unit_tests/test_sdcm_mgmt_common.py
vars/managerPipeline.groovy

Default scylla_version is set to 2024.2 instead of 2024.1.
At the same time, to have some coverage for 2024.1 as well, all Debian 11 jobs adjusted to use version 2024.1.

fix(manager): update default Scylla version to 2024.2 for Manager tests

---

sdcm/cluster.py

We face indefinite freezes upon gpg command.
Added timeout and debug-all flags to enable debugging and potentially fix the issue.
refs: https://github.com/scylladb/scylla-cluster-tests/issues/9017

fix(gpg): add timeout and debug

---

sdcm/cassandra_harry_thread.py
sdcm/exceptions.py
sdcm/kcl_thread.py
sdcm/ndbench_thread.py
sdcm/nemesis.py
sdcm/nosql_thread.py
sdcm/scylla_bench_thread.py
sdcm/stress/latte_thread.py
sdcm/ycsb_thread.py

Abort the nemesis flow early when a stress command fails, as continuing it is often invalid due to the cluster being in an unexpected state.
For example, if the _prepare_test_table routine fails, subsequent steps that depend on the test table (or attempt disruptions on top of it) will also fail.
This change adds a check for results of stress command triggered within the nemesis code, ensuring the nemesis halts early if the stress command is unsuccessful.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8722
Executed PR-provision-test configuration for TruncateMonkey nemesis class. As a result the disrupt_truncate disruption was started few times, but interrupted early as the stress command in  _prepare_test_table
was failing:
```
< t:2024-12-20 22:04:24,417 f:file_logger.py …
```

fix(nemesis.py): abort nemesis on stress command failure

---

test-cases/performance/perf-regression-latency-650gb-grow-shrink.yaml

enable hinted handoff for perf-regression-latency-650gb-grow-shrink
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/hints/job/scylla-master-perf-regression-latency-650gb-grow-shrink-v2/
- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/hints/job/scylla-master-perf-regression-latency-650gb-grow-shrink-tablets-v2/

test(latency) enable hinted handoff(grow shrink)

---

sdcm/nemesis.py

Access stress event `errors` attribute directly, no as a dict key, as the stress event object doesn't implement `get` API.
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/9653
Simple `PR-provision-test` run, with a breakpoint inside `stop_nemesis_on_stress_errors` method to check reading `error.events` attribute value:
- with 'broken' stress command, `error.events` holds the list of errors:
```
> event.errors
Out[1]: ['Stress command completed with bad status 1: ']
...
----- LAST ERROR EVENT -------------------------------------------------------
2025-01-05 17:41:12.182: (DisruptionEvent Severity.ERROR) period_type=end event_id=325cd791-4d07-4e1b-bbba-46102c514801 duration=44s: nemesis_name=Truncate target_node=Node PR-provision-test-dmitriy-db-node-4bfa7bae-3 [34.245.136.52 …
```

fix(nemesis.py): fix evaluation of stress command result

---

sdcm/utils/distro.py

for some reason during backporting of old PRs
this was removed, and causing issues for some code that is depened on it

fix(distro): add back ubuntu 24.04 support

---

sdcm/cluster.py

both of those aren't needed anymore, and it just complicates our artifacts test with not real reason.
shouldn't be backported, to any releases.

fix(offline-installer): stop installing python2 and java

---

jenkins-pipelines/manager/rhel-manager-backup-azure.jenkinsfile

Changes:
- Removed scylla version hardcode for Azure job. The image defined in azure_image_db contains Scylla 5.2.1 is outdated. Moreover, there are no restrictions with passing scylla_version directly. With this change, the Azure job will be executed with Scylla 2024.2 which is default for Manager jobs (if any specific doesn't redefine it).
- Renamed jenkinsfile to address recent move from Centos-based image for Azure jobs to RHEL-based (https://github.com/scylladb/scylla-cluster-tests/pull/9631).

fix(manager): update jenkinsfile for Manager Azure tests

---

sdcm/cluster.py

One of the recent PRs (https://github.com/scylladb/scylla-cluster-tests/pull/9652) has removed python2 and java installation on the offline installations.
And the problem is that it also removed installation of the `tar` package which is absent by default in some distros like `OEL8`.
So, add back that package installation to make offline installation work again.

fix(offline-install): return back `tar` pkg installation

---

jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-write-vnodes.jenkinsfile

Add missed double quote. It was presented by
https://github.com/scylladb/scylla-cluster-tests/pull/9295 and cause to job failure.
Failed run: https://jenkins.scylladb.com/job/scylla-enterprise/job/perf-regression/job/scylla-enterprise-perf-regression-predefined-throughput-steps-write-vnodes/17/

fix(pipeline): config params for predefined write test

---

unit_tests/test_config_get_version_based_on_conf.py

some images of older branches aren't available anymore we shouldn't be using that old release in those tests
we should find a better way to stop those test from breaking but for now let just move them to newer versions

fix(integration-tests): update versions used

---

mgmt_cli_test.py

Error message that Manager returns for enospc scenario has been changed to more generic one. So, this change updates expected error message and removes skip per issue since it was closed without resolution.
refs:
https://github.com/scylladb/scylla-manager/issues/4087

fix(manager): update expected error message for enospc restore test

---

docker/env/hydra.sh

since we are might be running multiple hydra commands on the same jenkins builder, and we are running into those kind of error:
```
docker: Error response from daemon: failed to create task for container:
failed to create shim task: OCI runtime create failed: runc create failed:
unable to start container process: error during container init:
error mounting "tmpfs" to rootfs at "/home/jenkins/.local":
create mountpoint for /home/jenkins/.local mount:
mkdirat /var/lib/docker/.../.local: file exists: unknown.
```
we are trying to limit the memory to try to avoid this issue
Fixes: #9645

fix(hydra): limit tmpfs to 256m

---

sdcm/nemesis.py

Access stress event `errors` attribute directly, no as a dict key, as the stress event object doesn't implement `get` API.
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/9653
Simple `PR-provision-test` run, with a breakpoint inside `stop_nemesis_on_stress_errors` method to check reading `error.events` attribute value:
- with 'broken' stress command, `error.events` holds the list of errors:
```
> event.errors
Out[1]: ['Stress command completed with bad status 1: ']
...
----- LAST ERROR EVENT -------------------------------------------------------
2025-01-05 17:41:12.182: (DisruptionEvent Severity.ERROR) period_type=end event_id=325cd791-4d07-4e1b-bbba-46102c514801 duration=44s: nemesis_name=Truncate target_node=Node PR-provision-test-dmitriy-db-node-4bfa7bae-3 [34.245.136.52 …
```

[Backport 2024.1] fix(nemesis.py): fix evaluation of stress command result

---

defaults/severities.yaml
sdcm/report_templates/results_base.html
sdcm/sct_events/loaders.py
sdcm/send_email.py
sdcm/tester.py
unit_tests/test_sct_events_loaders.py

Add RackAwarePolicy cassandra-stress log event when a test runs with multiple availability zone.
```
2025-01-01 09:53:27.896: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=db556fb0-db45-42a1-8068-7abd224b3997: type=RackAwarePolicy regex=Using provided rack name '.+' for RackAwareRoundRobinPolicy line_number=143 node=Node longevity-cdc-100gb-4h-rack-awa-loader-node-82ae1911-1 [34.245.189.8 | 10.4.7.144] (rack: 0)
INFO  [main] 2025-01-01 09:53:27,319 RackAwareRoundRobinPolicy.java:114 - Using provided rack name '1b' for RackAwareRoundRobinPolicy
```
Task: https://github.com/scylladb/qa-tasks/issues/1819
Printed in an email:
```
Test details
Test: longevity_test.LongevityTest.test_custom_time
Build number: 6
Backend: aws: ['eu-west-1']
Kernel version: …
```

improvement(events): add rack aware policy event

---

sdcm/sct_config.py
sdcm/utils/version_utils.py
unit_tests/test_version_utils.py

`ARGUS_VERSION_RE` wasn't covering plain version like `6.3.0~dev` hence not sending it out to Argus.
the change is fixing the regex
this change also fixes `get_branch_version` to be able to return a full version string (including git sha and a date), cause we know Argus would need this data for metrics graphs and perf summaries.
also not having this information, is causing confusion on patch releases, when test are not get to the phase a node is upgrades
Ref: https://github.com/scylladb/argus/issues/533

fix(sct_config): `scylla-server-upgrade-target` wasn't reported to Argus

---

defaults/docker_images/alternator-dns/values_alternator-dns.yaml
defaults/docker_images/cassandra-stress/values_cassandra-stress.yaml
defaults/docker_images/cdc-stresser/values_cdc-stresser.yaml
defaults/docker_images/cql-stress-cassandra-stress/values_cql-stress-cassandra-stress.yaml
defaults/docker_images/gemini/values_gemini.yaml
defaults/docker_images/harry/values_harry.yaml
defaults/docker_images/kcl/values_kcl.yaml
defaults/docker_images/latte/values_latte.yaml
defaults/docker_images/ndbench/values_ndbench.yaml
defaults/docker_images/nosqlbench/values_nosqlbench.yaml
defaults/docker_images/scylla-bench/values_scylla-bench.yaml
defaults/docker_images/ycsb/values_ycsb.yaml

seem like there's a bug in dependabot-docker, and it can't update the configuration if they are using quotes or double quotes in `image`, like:
```
ycsb:
image: 'scylladb/hydra-loaders:ycsb-jdk8-20220918'
```
remove them for all docker configuration files for now

fix(dependabot): remove quotes from docker configurations

---

defaults/manager_persistent_snapshots.yaml

This reverts commit 64fa8b3970156368af1a614985a2cdfddc4f884b.
It was mistakenly backported initially. Backup snapshots with Scylla 2024.2.0~rc1 can't be restored to node with Scylla 2023.1 - system schema in 2023.1 does not match to schema of 2024.2 and system_schema.scylla_tables does not include committed_by_group0  column.

Revert "test(nemesis): update manager persistent snapshots"

---

sct_ssh.py
unit_tests/test_python_driver.py

the new support for Azure we missing some variable definition
and was failing like this:
```
UnboundLocalError: local variable 'azure_vms' referenced before assignment
```
this change is setting this variable upfront with empty list

fix(sct_ssh): fix `UnboundLocalError` in `hydra attach-test-sg`

---

renovate.json

docker so we can update the stress tools, but it's only works if we'll seprate them into thier own repos, and use semver or something similar

chore(renovate.json): enable docker, scan `requirements.in`

---

.github/scripts/auto-backport.py
.github/scripts/search_commits.py
.github/workflows/add-label-when-promoted.yaml

Adding an auto-backport.py script to handle backport automation instead of Mergify.
The rules of backport are as follows:
* Merged PR with any backport/x.y label (one or more) and promoted-to-master label
* Backport PR will be automatically assigned to the original PR author
* All PRs will be open under the `scylladbbot` account - which will allow write access in case of conflicts
* PR with conflicts will open in draft mode.
* Fixing cherry-pick the wrong commit SHA. With the new script, we always take the SHA from the stable branch
**Since the SCT repo is public and GitHub doesn't clone permissions to the public repo (for forks),**
**For the first time only, each PR owner will receive an email**
**with an invite to the `scylladbbot/scylla-cluster-tests` fork**

feature(auto-backport.py): replace Mergify

---

sdcm/node_exporter_setup.py

This PR update node_exporter to v1.8.2 (just like Scylla) and removes the unneeded collectors that are enabled by default (just like Scylla). The only exception is interrupts - which are still enabled by default by Scylla and are not needed here.
- NOT tested.

improvement(node_exporter): upgrade to v1.8.2, remove unneeded collectors

---

sdcm/utils/sstable/sstable_utils.py
upgrade_test.py

rewrite a new util function of get_sstable_dump_command() to be used across sct tests.
refs: https://github.com/scylladb/scylla-cluster-tests/pull/6828
refs: https://github.com/scylladb/scylla-cluster-tests/pull/5737#issuecomment-2520369854
- tombstone gc thread [test](https://argus.scylladb.com/tests/scylla-cluster-tests/1f4ff9fa-bb84-4a99-8a46-ac3db4f6807e)
- [upgrade test](https://argus.scylladb.com/tests/scylla-cluster-tests/23fdaa41-2bbe-4ef2-ae02-cf1ae9ebe698)

fix(sstbale dump): select the suitable sstable-dump command everywhere it is used

---

.github/scripts/auto-backport.py

Auto backport failed while searching for the wrong release branch name (it was looking for `master2024.2` instead of `branch-2024.2`
Fixing it

fix(auto-backport) wrong target branch

---

sdcm/cluster.py

Recently was backported the PR (https://github.com/scylladb/scylla-cluster-tests/pull/9683) that started using the code
which is absent in the `branch-2024.2` SCT branch.
It was never backported from the (https://github.com/scylladb/scylla-cluster-tests/pull/7408).
So, fix the problem by using old code which exists in the target branch.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/9775
- https://jenkins.scylladb.com/job/enterprise-2024.2/job/longevity_tablets/job/longevity-gce-custom-d1-worklod1-hybrid-raid-test/6/consoleFull

fix(mgmt-agent): setup it using the code existing in the branch-2024.2

---

microbenchmarking_test.py
sdcm/argus_results.py

When sending perf_simple_query benchmark results, Argus will validate numbers based on all history (submitted to Argus). Current approach validates only 10 last results.
closes: https://github.com/scylladb/scylla-cluster-tests/issues/9578

improvement(perf_simple_query): add validation rules for Argus

---

artifacts_test.py
defaults/test_default.yaml
docs/configuration_options.md
sdcm/provision/helpers/certificate.py
sdcm/sct_config.py
sdcm/scylla_bench_thread.py
sdcm/stress/latte_thread.py
sdcm/stress_thread.py
unit_tests/conftest.py

Peer verification is now enabled by default for cassandra-stress, scylla-bench, and latte stress tools when client encryption is configured in Scylla. This ensures enhanced security by verifying if peer certificate is signed by the trusted CA and that the hostname/IP of the peer matches SAN specified in the peer's certificate.
Closes: https://github.com/scylladb/qa-tasks/issues/1728

feature(client-encrypt): enable peer verification for stress commands

---

sdcm/nemesis.py

Retrieve `region_name` in a safer way, since in AWS it might not exist or is empty.
Follow-up to #9698.
refs: scylladb#9492, #9698

fix(region_name): improvre retreving `region_name` in nemesis

---

sdcm/cluster.py
sdcm/nemesis.py
unit_tests/test_nemesis.py

Add logging of the following nemesis details in logs of each db node of a cluster under test:
- nemesis start with disruption/nemesis name
- target node for the nemesis
- nemesis end with status
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/6088 
Example of how the start/end is logged in:
- sct.log
```
❯ egrep '>>>>|<<<<.*disruption' -irn sct-6288cf64.log
21138:< t:2025-01-13 16:05:06,583 f:nemesis.py      l:5469 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>> Started disruption disrupt_kill_scylla (KillScylla nemesis) on the target node 'Node PR-provision-test-log-neme-db-node-6288cf64-2 [3.253.12.15 | 10.4.3.181]' >>>>>>>>>>>>
22492:< t:2025-01-13 16:05:30,440 f:nemesis.py      l:5556 c:sdcm.nemesis         p:DEBUG > …
```

fix(nemesis.py): log nemesis start/end on db nodes logs

---

sdcm/fill_db_data.py

as suggested in scylladb/scylladb#22166, we make the truncate commands timeout longer, to compensate on the fact scylla can't support multiple truncate operation in parallel
Ref: scylladb/scylladb#22166
Ref: scylladb/scylladb#21946

fix(upgrade-tests): enlarge timeout for truncate commands

---

defaults/aws_config.yaml
functional_tests/scylla_operator/test_functional.py
mgmt_cli_test.py
sdcm/nemesis.py

since now we are doing backup/restore in the test region and `backup_bucket_region` was remove.
the code for this configuration need to be templated as it was done for restore nemesis
otherwise we fail like the following:
```
23:22:43  Command: 'sudo sctool backup -c a05d9ea2-312c-4c8d-99b0-9f9b57e8cbde
--keyspace scylla_bench,keyspace1  --location s3:manager-backup-tests-us-east-1 '
23:22:43  Exit code: 1
23:22:43  Stdout:
23:22:43  Stderr:
23:22:43  Error: create backup target: location is not accessible
23:22:43  10.4.2.70: agent [HTTP 400] operation put: s3 upload: 301 Moved Permanently:
The bucket you are attempting to access must be addressed using the specified endpoint.
Please send all future requests to this endpoint. (code:PermanentRedirect) - make sure the location
is correct …
```

fix(bucket-locations): add templating to `backup_bucket_location`

---

sdcm/cluster.py

the iotune command was generating only `io-properties.yaml` and not the `io.conf` file that should point to it.
so it was working on supported instance types, but was failing to do it's purpose on unsupported instance types.

fix(force_run_iotune): run `scylla_io_setup` and not directly iotune

---

.github/workflows/auto_assign.yaml

There is no need to assign to backport PRs or `scylladbbot` users, 
let's skip it

fix(auto_assign): skip `scylladbbot` assignment

---

sdcm/utils/common.py
vars/collectBuilderLogs.groovy
vars/runCollectLogs.groovy

we have multiple issue related to builder, and we don't have any logs from their end saved
this commit add code that collect the journalctl logs from builder and upload it to s3 and Argus.

feature(pipelines): collect builders logs

---

unit_tests/test_base_version.py
utils/get_supported_scylla_base_versions.py

Skip this upgrade combination due to a repair during rollback  bug
refs: scylladb/scylla-enterprise#4740

fix(get_supported_scylla_base_version): skip upgrade from 6.0 to 2024.2

---

sdcm/stress_thread.py

Use ThreadPoolExecutor instead of Process in CSHDRFileLogger class.
This change is added due to issue that c-s hdr file is not always
copied from loader to runner. As the root of the problem was not found,
it was decided to use thread.
Add HDRFileMissed warning event when found not copied HDR file.
The issue with not-copied HDR file was not reproduced while testing this commit, but I still keep a few debug log messages for a future.

test(hdr logs): use thread instead process

---

configurations/performance/cassandra_stress_gradual_load_steps.yaml
configurations/performance/cassandra_stress_gradual_load_steps_enterprise.yaml

Change steps for predefined write test from [200,300,400] to [100,200,300]. 
400 step is useless if we can never reach the op/s.
Task: https://github.com/scylladb/qa-tasks/issues/1843

improvement(perf test): change steps for predefined write test

---

test_lib/sla.py

in file sla.py valuse error objects creating but not raised. this PR fix this.

fix(sla.py): raise value error

---

sdcm/tester.py

Due to not backported commit, import Path does not exist in the branch-perf-v15. As result schema info collection failed with 'NameError'
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9818

fix(tester): missed Path import

---

jenkins-pipelines/oss/tier2/scale-5000-tables.jenkinsfile
sdcm/provision/scylla_yaml/scylla_yaml.py
test-cases/scale/longevity-5000-tables.yaml
unit_tests/test_scylla_yaml.py

List of changes:
- Disable per-table metrics due to significant perf impact.
- Enable cluster health checks which work with this case just fine.
- Decrease the nemesis interval from 60 minutes to just 3 keeping in mind that health checks will take some time too.
- Reduce stress time for each of the 5000 commands. Having 20 minutes per cmd we will get about 1.5 days long test runs instead of the 2.5 days.
- Reduce number of loaders from 5 to 3 to use resources more efficiently. In current case the bottleneck is the RAM.
Note that this scenario hits following bug:
- https://github.com/scylladb/scylla-enterprise/issues/5093
If `destroy_data_then_repair` nemesis gets triggered aganst the setup of this scenario.
- [scylla-staging/valerii/vp-scale-5000-tables-test#7](https://argus.scylladb.com/t …

fix(test-case): update 5000 tables test case configuration

---

docker/env/hydra.sh

we are running into case SCT is core dumping during shutdown of the tests we don't have enough information to understand what's going on
hopefully this can add some information that can help us figure it out
Ref: https://docs.python.org/3/library/faulthandler.html

fix(hydra): enable python faulthandler by default

---

sdcm/nemesis.py

Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9853

fix(nemesis): fix typo in the `mgmt_restore` nemesis

---

sdcm/nemesis.py

Disable nemesis CreateIndex from runs with parallel nemesis to stabilze jobs:
- longevity-schema-topology-changes-12h-test
- longevity-multi-dc-rack-aware-zero-token-dc-test
- longevity-multidc-schema-topology-changes-12h-test
After issue scylladb/scylladb#21695 will be fixed, nemesis could be again enabled in parallel running
- [Passed job](https://argus.scylladb.com/tests/scylla-cluster-tests/dc9079ff-d838-4ec5-b3da-6ac49972a905)
- [Passed job](https://argus.scylladb.com/tests/scylla-cluster-tests/3771cd6e-c0a1-42bc-b3a1-f46e93336545)
- [Passed job](https://argus.scylladb.com/tests/scylla-cluster-tests/d9524334-6096-40d6-b303-5660fe81fe14)
- Update …

fix(createindex): Disable nemesis to run in parallel nemesis jobs

---

sdcm/scan_operation_thread.py

The node where scan operations was started could be
used by disruptive nemesis. If node was restarted/stopped
while scan query had been running, the scan operation would
be terminated and error event and message will mark
test as failed.
Add to cql session ExponentialBackoffRetryPolicy
which allow to retry the query, if node was down
and once it back, query will be succesfully finished
Fixes: #9284
- [Test 1 - Passed](https://argus.scylladb.com/tests/scylla-cluster-tests/45a61d6c-7742-4a48-8829-1335dab57f21)
- [Test 2 - Failed](https://argus.scylladb.com/tests/scylla-cluster-tests/6c9df0e5-0ed5-4ac7-b4d3-7c6158828b9a) - failed due to c-s error: `java.io.IOException: Operation x10 on key(s) [32374e4d3230504b3030]: Data returned was not validated`. Errors related to Scan operations are not …

 fix(scan_operations): add retry policy to cql query

---

sdcm/nemesis.py
sdcm/utils/replication_strategy_utils.py
sdcm/utils/tablets/common.py

This function checks if there are no ongoing tablet topology operations. It does not guarantee that tablets become balanced, this language confuses when you read code and events log.
No code changes, testing is not needed.

fix(common): change wait_for_tablets_balanced to represent what it actualy does

---

vars/createArgusTestRun.groovy

This commit makes it so that createArgusTestRun stage of the SCT
pipeline now appends a link to the argus page of the run.
Fixes #9634

feature(createArgusTestRun.groovy): Add argus link

---

configurations/performance/cassandra_stress_gradual_load_steps.yaml
configurations/performance/cassandra_stress_gradual_load_steps_enterprise.yaml

The first run of write predefined steps test with changed steps presented by https://github.com/scylladb/scylla-cluster-tests/pull/9820, demonstrated that 100K step duration is 04:29:02. It caused to test time out. Decided to remove 100K step ate all
(https://argus.scylladb.com/tests/scylla-cluster-tests/86a3a793-d226-4925-acc7-cc1366513f41)

fix(perf test): remove 100K step in write test

---

docs/docker-backend-overview.md

Add a dedicated documentation page for the Docker backend, which describes specifics and limitations of the backend.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/9322

docs(docker-backend): summarize specifics and limitations of backend

---

pyproject.toml
sdcm/cluster_k8s/eks.py
sdcm/remote/kubernetes_cmd_runner.py
sdcm/remote/libssh2_client/session.py
sdcm/sct_events/events_analyzer.py
sdcm/stress_thread.py
sdcm/utils/k8s/__init__.py
sdcm/ycsb_thread.py

we shouldn't let those get into the the code without a very good reason (like memoize/cache)
Ref: https://docs.astral.sh/ruff/rules/mutable-argument-default/

feature(ruff): scan for mutable-argument-default (B006)

---

configurations/enable_views_with_tablets_on_upgrade.yaml
defaults/test_default.yaml
docs/configuration_options.md
sdcm/sct_config.py
upgrade_test.py

We plan to disallow materialized views in tablet keyspaces, until the remaining issues with them
are resolved. For that, we've introduced the "views-with-tablets" experimental feature, so that
they can be enabled regardless, for example for testing. Currently, the feature has no effect,
but we want to prepare the cluster tests to use it, so that they won't start failing when it
starts actually having an effect.
While improving views with tablets, we should make sure that the existing tests keep passing,
so we should run materialized view (and index) tests with tablets using the experimental feature.
The feature doesn't affect tests ran on vnodes. For tablets, the tests would fail without the feature
due to unsupported configuration.
Considering that, we should enable the feature by …

feature(views-with-tablets): enable testing materialized views with tablets

---

Jenkinsfile
vars/getLatestScyllaRelease.groovy

get this by latest version by using:
`https://repositories.scylladb.com/scylla/check_version`
so we don't need to remember updating it manually once in a while (we didn't update since 5.2)

feature(Jenkinsfile): get latest scylla release automaticlly

---

defaults/test_default.yaml
sdcm/sct_config.py
unit_tests/test_config.py

the newly introduced `update_config_based_on_version()` had faulty code that assumed there a default vaule argument
default should be configured in `test_default.yaml`
a new unit test introduce to cover this part of the sct_config.py

fix(sct_config): `param.get()` doesn't accept default argument

---

sdcm/cluster.py

We don't face issue with gpg hang anymore. Removing debug log.
closes: https://github.com/scylladb/scylla-cluster-tests/issues/9017

fix(gpg): remove debug log from gpg command

---

unit_tests/test_config_get_version_based_on_conf.py

test was assuming any version from master wouldn't be with enterprise version scheme, that has change and now master is with 2025.1 and that's expected, the logic of the test has change to expect enterprise like version

fix(get_version_based_on_conf): master is now "enterprise"

---

sdcm/logcollector.py
sdcm/teardown_validators/sstables.py
sdcm/utils/sstable/sstable_utils.py

Error message changed for scrub validation and upload sstables in validator stopped working. Still event handler catched that and uploaded
- but actually should not when scrub validator sends them.
Fix by adjusting to error line (should be more elastic) and adjusted event handler to not send corrupted sstables in context of sstables validator.
Added sstable util to corrupt sstable (just for testing this and possibly may be used in other contexts).
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9854

fix(sstables_validator): fix upload sstables

---

jenkins-pipelines/manager/ubuntu24-manager-upgrade.jenkinsfile

Since we are about to release Manager 3.4.1, updating manager_version to 3.4.0 (the latest patch release) for the upgrade job that verifies upgrades from the latest patch release (ubuntu24-manager-upgrade).
The jobs that check upgrade from minor releases (3.3.*) left unchanged.

test(manager): update version of Manager in upgrade test

---

sdcm/cluster.py
sdcm/utils/health_checker.py

I hope by now it's stable and we can wait less (but retry more to compensate) on the 2 functions that are related to schema agrement. Cut the wait time from 10s to 5s and increased the retry count to 10.
Probably need a similar change in dtest.
BTW, the Python driver sleeps for 0.2s before retrying.

feature(sdcm) wait less for schema agreement

---

test-cases/artifacts/azure-image.yaml
test-cases/artifacts/centos7.yaml
test-cases/artifacts/centos9-selinux.yaml
test-cases/artifacts/centos9.yaml
test-cases/artifacts/debian11.yaml
test-cases/artifacts/debian12.yaml
test-cases/artifacts/gce-image-persistent-disk.yaml
test-cases/artifacts/gce-image.yaml
test-cases/artifacts/rhel7.yaml
test-cases/artifacts/rhel8.yaml
test-cases/artifacts/rocky8.yaml
test-cases/artifacts/rocky9-selinux.yaml
test-cases/artifacts/rocky9.yaml
test-cases/artifacts/ubuntu2004.yaml
test-cases/artifacts/ubuntu2204.yaml
test-cases/artifacts/ubuntu2404.yaml

Seems like we didn't fully tested this on on the jobs not based scylla images
Revering for now
Reverts scylladb/scylla-cluster-tests#9917

Revert "improvement(artifacts): switch to syslog-ng logs transport"

---

unit_tests/test_base_version.py
utils/get_supported_scylla_base_versions.py

* adding 6.2 as a base version for any upgrade into 2025.1
* add unittest to cover the 2025.1 cases

fix(base_versions): add OSS mapping for 2025.1

---

performance_regression_gradual_grow_throughput.py

Add 2 minutes sleep after warm-up and before step start in predefined steps performnace test. This is for let to all background processes to finish. It may have the impact especially in tablet test - to complete tablets rebuild
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9852

fix(performance): add sleep after warm-up

---

sdcm/provision/aws/capacity_reservation.py
sdcm/utils/resources_cleanup.py

When cleaning resources with `clean_cloud_resources` capacity
reservations are not cleaned because not all params are passed
to the command. This causes leakage when test is aborted.
Fix by force fetch CR's from AWS before cancelling.

fix(cleanup): fix capacity reservation in clean resources

---

defaults/docker_images/cql-stress-cassandra-stress/values_cql-stress-cassandra-stress.yaml
docker/cql-stress-cassandra-stress/Dockerfile
docker/cql-stress-cassandra-stress/image

This new version contains following changes compared to the previous one:
- "c-s: Implement insert operation for user profiles" ([PR#93](https://github.com/scylladb/cql-stress/pull/93))
- "cargo: bump rust-driver version to 0.14" ([PR#102](https://github.com/scylladb/cql-stress/pull/102))

ci(cql-stress): use newest cql-stress benchmarking tool

---

sdcm/sct_config.py

The parameters 'perf_gradual_threads' and 'perf_gradual_throttle_steps' are defined with type 'dict'. It prevents dynamicaly changing them in the 'extra_environment_variables' parameter in Jenkins job (if we want to change them while running job, without push commit).
Changing the type to 'dict_or_str' allow us to change those params dynamically
The 'perf_gradual_threads' and 'perf_gradual_throttle_steps' values are according to `extra_environment_variables` and config validation step did not fail

fix(sct_config): change type of perf_gradual_ params

---

sdcm/provision/aws/capacity_reservation.py

For better traceability we want to tag capacity reservations with user and job that run it. 
Reduced duration as provision part is quick. 
refs: https://github.com/scylladb/qa-tasks/issues/1846

improvement(capacity_reservations): add RunByUser and JenkinsJobTag tags

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml
jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml

As the enterprise version does not exist anymore and master now is 2025.x, we need to run all performance tests with 'master:latest' instead of 'enterprise:latest' and disable master trigger

fix(perf trigger): change Scylla version from enterprise to master

---

sdcm/utils/cloud_monitor/cloud_monitor.py
sdcm/utils/cloud_monitor/report.py
sdcm/utils/cloud_monitor/resources/capacity_reservations.py
sdcm/utils/cloud_monitor/templates/per_user_summary.html

We want to monitor active AWS capacity reservations. Enhance cloud usage report to list all active capacity reservations and how are used. In case is not used, mark in red given value. CR section will be visible only if there are active CR's and will include:
user, region, instance type, capacity total, capacity available, start time and id.
refs: https://github.com/scylladb/qa-tasks/issues/1846
Report look (below other tables):

improvement(cloud_usage_report): add capacity reservations

---

test-cases/performance/perf-regression-latency-1TB.yaml
test-cases/performance/perf-regression-latency-650gb-upgrade.yaml
test-cases/performance/perf-regression-predefined-throughput-steps.yaml
test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml

By default `nemesis_add_node_cnt` is set to 1. This number is used to determine required capacity for tests. Some tests don't require it as don't run nemesis.
Reduce `nemesis_add_node_cnt` for these scenarios to 0 to avoid additional unnecessary costs.
refs: https://github.com/scylladb/qa-tasks/issues/1846

fix(capacity_reservation): reduce nemesis_add_node_cnt when not needed

---

sdcm/cluster.py
sdcm/mgmt/cli.py
sdcm/mgmt/operator.py

Closes https://github.com/scylladb/scylla-manager/issues/4206
This PR enhances the ScyllaManagerTool.add_cluster method by introducing the force_non_ssl_session_port parameter, ensuring that the --force-non-ssl-session-port flag is used appropriately in sctool cluster add operations.
This flag will be applied in `sctool cluster add` operation in Nemesis tests if:
- Scylla client encryption is enabled;
- Scylla doesn't utilize native_transport_port_ssl (9142).
Also, PR includes a tiny refactoring for ScyllaManagerTool.add_cluster method:
- Updated docstrings with relevant information;
- Removed unnecessary empty lines and duplicate conditions.

[Manager] Force non ssl session port utilization for Nemesis tests

---

sdcm/cdclog_reader_thread.py
sdcm/tester.py

overwrite run method to avoid wrong loaders calculation 
termination event handling added to avoid uncritical errors during test termination
fixes:9819
fixes: #9819
https://jenkins.scylladb.com/job/scylla-staging/job/eugene_test_folder/job/cdc_stressor_4h/12/
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/eugene_test_folder/job/cdc_stressor_4h/15/
- [ x] I added the relevant `backport` labels
- [x ] I didn't leave commented-out/debugging code

fix(cdc_reader): overwrite "run" method in cdc_reader_thread

---

Jenkinsfile
test-cases/PR-provision-test.yaml
unit_tests/conftest.py
unit_tests/test_cassandra_stress_thread.py

Integration tests may fail with docker rate limiting - added docker login command to avoid that.
Provision tests fail with running counter tests against latest scylla version (tablets enabled by default). Disabled tablets in provision test config

fix(ci-pipeline): fix integration and provision test

---

sdcm/scan_operation_thread.py
unit_tests/test_scan_operation_thread.py

This PR removes try/catch block from FullScanAggregate operations and start using common error handling in FullscanOperationBase.run_scan_event that convert ERROR to WARNING based on error messages or active nemesis
```
2025-02-03 12:43:49.497: (FullScanAggregateEvent Severity.WARNING) period_type=end event_id=76de25b4-0dc6-4859-bc22-3a0a23d42cb0 duration=6m24s node=longevity-10gb-3h-fix-9284-db-node-d67a1bc6-4 select_from=keyspace1.standard1 message=ReadTimeout('Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\' responses] message="Operation failed for keyspace1.standard1 - received 0 responses and 1 failures from 1 CL=ONE." info={\'consistency\': \'ONE\', \'required_responses\': 1, \'received_responses\': 0}')
```
- Add New configuration option and …

fix(FullScanAggregate): use  "warning" severity on some errors

---

sdcm/utils/docker_remote.py
unit_tests/conftest.py
unit_tests/test_cassandra_stress_thread.py

When peer verification is enabled for encrypted communication, the cassandra-stress command checks DNS names in SAN extension of server certificates.
This change fixes integration tests for cassandra-stress thread, by including DNS name of a dummy server node in its certificate.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9988
```
❯ python -m pytest -v -p no:warnings -m integration unit_tests/test_cassandra_stress_thread.py::test_03_cassandra_stress_client_encrypt
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.10.0, pytest-7.2.0, pluggy-1.5.0 -- …
```

fix(integration-test): fix test_03_cassandra_stress_client_encrypt test

---

defaults/docker_images/latte/values_latte.yaml

It includes following main changes:
- Latencies are now calculated with regards to the coordinated omission.
- Added support for streaming the HDR histogram data in real time.
Usage: `--hdrfile /path/to/file`

ci(latte): bump latte version to 0.28.2-scylladb

---

sdcm/cluster.py
sdcm/nemesis.py
unit_tests/dummy_remote.py
unit_tests/test_nemesis.py

Change logging of nemesis start/end from using `scylla-api-client` to the system logger utility. This makes logging these details more stable, as `scylla-api-client` cannot be used when the scylla-server service is not started on DB nodes.
Additionally, add logging of nemesis start/end on loader nodes. This helps with SCT results investigation activities.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9976
loaders nodes log:
```
❯ egrep '(Started|Finished) disruption' -rn loader-set-487cac05/PR-provision-test-fix-db-n-loader-node-487cac05-*/
...
loader-set-487cac05/PR-provision-test-fix-db-n-loader-node-487cac05-1/system.log:10102:Feb 09 18:33:03 PR-provision-test-fix-db-n-loader-node-487cac05-1 scylla[5621]: ============ Started disruption …
```

fix(nemesis.py): use system logger to log nemesis start/end on nodes

---

sdcm/sct_provision/region_definition_builder.py
sdcm/sct_provision/user_data_objects/walinuxagent.py

Linux agent on Scylla instances on Azure is disabled by default. https://github.com/scylladb/scylla-machine-image/pull/627
Add cloud init script that enables it back for testing purposes.

fix(Azure): enable WaLinuxAgent

---

defaults/manager_restore_benchmark_snapshots.yaml
defaults/test_default.yaml
mgmt_cli_test.py
sdcm/argus_results.py
sdcm/sct_config.py
vars/managerPipeline.groovy

refs: 
https://github.com/scylladb/scylla-manager/issues/4190
https://github.com/scylladb/scylla-manager/issues/4208
The PR addresses two main topics:
1. Manager snapshot preparer helper extension
- Dataset parameters (which defined in c-s cmd) aren't hardcoded anymore what gives an opportunity to widely vary its properties (replication, compaction, cl, rf, etc). 
manager_restore_benchmark_snapshots.yaml file with snapshots config for current benchmark tests is extended to include such a parameters. These params are later used on C-S read command generation stage. 
Thus, snapshot preparation test becomes widely customizable with more flexibility to adjust dataset.
- Generated backup snapshot details are sent to Argus Results instead of logging what improves usability.
2. Cloud clusters …

Improve Manager snapshot preparer helper

---

defaults/docker_images/gemini/values_gemini.yaml
sdcm/gemini_thread.py
test-cases/cdc/cdc-15m-replication-gemini.yaml
test-cases/cdc/cdc-15m-replication-postimage.yaml
test-cases/cdc/cdc-15m-replication-preimage.yaml
test-cases/cdc/cdc-replication-longevity.yaml
test-cases/upgrades/rolling-upgrade.yaml
unit_tests/test_data/test_scylla_yaml_builders/multi_network_interfaces/cdc-replication-longevity.yaml
unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.yaml

When gemini_thread.py was refactored, every command in test-cases/gemini was refactored to use the new model of declaring the flags. But it was not anticipated that there were more places where gemini was used e.g. test-cases/cdc and test-cases/upgrades.
Fixes #9850

fix(gemini-cmd): broken gemini commands on upgrades

---

sdcm/stress/latte_thread.py

Recently we switched to the new latte docker image (https://github.com/scylladb/scylla-cluster-tests/pull/10015).
It is built from another Dockerfile which is stored in the latte repo.
And this new image has the latte binary as an entrypoint. Before it was bash.
So, set entrypoint and parameters for it explicitly in the latte code
to make latte container start and run for whole test as it is expected and was before.

fix(latte): run latte docker container setting entrypoint explicitly

---

sdcm/cluster.py
unit_tests/test_cluster.py
unit_tests/test_utils_common.py

We used to verify installed package if is enterprise to determine product.
With 2025.1 being not enterprise package it no longer works as expected.
Fix by comparing scylla version to 6.3 - all versions above are counted as enterprise: this includes all 202x.x versions.

fix(BaseNode): fix is_enterprise property for 2025.1

---

sdcm/cluster.py
sdcm/nemesis.py

Reduce coredump event severity during disrupt_network_random_interruptions disruption, if coredump was triggered by an error in networkd service of version 255 or lower (the root cause is https://github.com/systemd/systemd/issues/32247).
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10053

fix(nemesis.py): ignore networkd coredump in RandomInterruptionNetwork

---

sdcm/utils/raft/__init__.py

new log lines added for aborting the decommission process
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/9501
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/eugene_test_folder/job/decommission_logs_testing/
https://argus.scylladb.com/tests/scylla-cluster-tests/d4151c1d-bce7-4689-91f4-67269dc2ef44

fix(DecommissionStreamingErr): new log lines added

---

performance_regression_gradual_grow_throughput.py
performance_regression_test.py
sdcm/cluster.py
sdcm/loader.py
sdcm/logcollector.py
sdcm/nemesis.py
sdcm/scylla_bench_thread.py
sdcm/stress/base.py
sdcm/stress_thread.py
sdcm/tester.py
sdcm/utils/decorators.py
sdcm/utils/hdrhistogram.py
ycsb_performance_regression_test.py

Current solution for HDR histograms assumes we use only `cassandra-stress`.
We are going to start using one more benchmarking tool that supports HDR histograms - `latte`.
So, refactor it's logic making the hdr tags be provided by the stress thread code which can detect it automatically.
With this refactor, we will be able to add HDR histograms support in SCT not only for `latte`,
but also for other benchmarking tools such as `scylla-bench` or `cql-stress-cassandra-stress`.
- cassandra-stress, regression test: [scylla-staging/valerii/vp-perf-regression-latency-650gb-during-rolling-upgrade#22](https://argus.scylladb.com/tests/scylla-cluster-tests/f3841cb3-dd97-4d0d-b8b4-0cd65dd74a15)
- cassandra-stress, regression test: [scylla-staging/valerii/vp-scylla-master-perf-regression-latency-650gb-w …

refactor(hdrh): support HDR histograms for multiple benchmarking tools

---

sdcm/cluster.py
sdcm/provision/common/configuration_script.py
sdcm/provision/common/utils.py
sdcm/utils/aws_builder.py
sdcm/utils/remote_logger.py
test-cases/artifacts/ami.yaml
test-cases/artifacts/azure-image.yaml
test-cases/artifacts/centos7.yaml
test-cases/artifacts/centos9-selinux.yaml
test-cases/artifacts/centos9.yaml
test-cases/artifacts/debian11.yaml
test-cases/artifacts/debian12.yaml
test-cases/artifacts/gce-image-persistent-disk.yaml
test-cases/artifacts/gce-image.yaml
test-cases/artifacts/oel76.yaml
test-cases/artifacts/oel8.yaml
test-cases/artifacts/oel9.yaml
test-cases/artifacts/rhel7.yaml
test-cases/artifacts/rhel8.yaml
test-cases/artifacts/rocky8.yaml
test-cases/artifacts/rocky9-selinux.yaml
test-cases/artifacts/rocky9.yaml
test-cases/artifacts/ubuntu2004-fips.yaml
test-cases/artifacts/ubuntu2004.yaml
test-cases/artifacts/ubuntu2204.yaml
test-cases/artifacts/ubuntu2404.yaml

Switch artifacts tests from ssh to syslog-ng logs transport.
For most of the artifacts test cases simply changing logs transport from `ssh` to `syslog-ng` is enough.
But there are also few scenarios where additional adjustments were needed:
- AWS backend: the `SCT-sg-2` security group is added to the `aws-sct-builders` launch templates. This change allows syslog-ng communication to pass firewall and send logs
from DB nodes to builder instances.
- nonroot installation of scylla on CentOS/Rocky: syslog-ng configuration is adjusted to read scylla-server logs from file. Also SELinux policies are adjusted to allow
nonroot syslog-ng process to send logs to remote log destination.
- scylla installation with `no-selinux-setup` option: SELinux policy is added to allow syslog-ng to use the port of …

improvement(artifacts): switch to syslog-ng logs transport

---

unit_tests/test_cluster.py

Recently `test_search_cdc_invalid_request` started to be flaky. Increase wait time for event to appear to prevent test from failing randomly.

fix(unit-test): unflake cdc cluster test

---

vars/perfRegressionParallelPipeline.groovy

When base version was added by release trigger, the performance rolling upgrade test started to fail with error:
```
No signature of method: supportedUpgradeFromVersions.call()
```
The problem is **'ArrayList'** missed and **'base_versions_list'** parameted was created as string and not as list, as supportedUpgradeFromVersions.call() function expects.
Fixes: https://github.com/scylladb/qa-tasks/issues/1851

fix(performance): split base versions for rolling upgrade test

---

sdcm/cluster.py
sdcm/fill_db_data.py
sdcm/nemesis.py
sdcm/tester.py
sdcm/utils/features.py
sdcm/utils/loader_utils.py
sdcm/utils/tablets/common.py
sla_per_user_system_test.py

Enabling/disabling tablets was changed. Now we have to check scylla yaml or keystore schema.
For more info see
- https://github.com/scylladb/scylladb/pull/21451
- https://github.com/scylladb/scylladb/pull/21614

fix(LoaderUtilsMixin): table_enabled was allways True as this feature is allways enabled

---

jenkins-pipelines/manager/helpers/prepare-backup-snapshot.jenkinsfile

SCT_BACKUP_BUCKET_REGION configuration parameter is not supported by SCT since https://github.com/scylladb/scylla-cluster-tests/pull/9492/commits/2c574e7e7d4b72301aa362946355e7f864f4bd12. 
Therefore, it should be removed from jenkinsfile, otherwise causing SCT to fail (unsupported parameter).
Testing is not required.

fix(manager): clean up non-supported SCT_BACKUP_BUCKET_REGION var

---

upgrade_test.py

Starting 2025.1 the upgrades from previous enterprise releases will behave like upgrade from OSS and won't require reinstall but just 'update'. However, a rollback during upgrade to 2025.1 will require reinstall. rollback from 2025.1 to OSS won't require reinstall.

refactor(upgrade_test): Support only smooth upgrades for 2025.1 and above

---

sdcm/cluster_k8s/__init__.py
sdcm/nemesis.py
sdcm/provision/network_configuration.py

After merging of https://github.com/scylladb/scylla-cluster-tests/pull/8925 Scylla Operator EKS longevity tests started to fail with error: AttributeError: 'NoneType' object has no attribute 'device'. K8s tests do not support 'node.scylla_network_configuration', it is supported by AWS only. Define 'scylla_network_configuration' for k8s and return hardcoded 'eth0' device name.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10009

fix(kubernetis): get device name for k8s node

---

sdcm/cluster.py
sdcm/utils/version_utils.py
unit_tests/test_version_utils.py

artifacts-centos9-web-test failed with the following error:
```
'curl -sSf get.scylladb.com/server | sudo bash -s -- --scylla-version nightly-2025.1 --scylla-product scylla-enterprise'
Exit code: 1
Stdout:
Installing Scylla version nightly-2025.1 for CentOS ...
The specified scylla-version 'nightly-2025.1' has reached End of Life (EOL) or not available.
• For OSS supported ScyllaDB versions please refer to https://docs.scylladb.com/stable/getting-started/os-support
• For Enterprise supported ScyllaDB versions please refer to \
https://enterprise.docs.scylladb.com/stable/getting-started/os-support
```
modifying web_install to always use `scylla` as the  product …

fix(web_install): always use scylla as product

---

data_dir/nemesis.yml
jenkins-pipelines/oss/features/elasticity/elasticity-90-percent-with-nemesis.jenkinsfile
sdcm/nemesis.py
test-cases/features/elasticity/elasticity-90-percent-with-nemesis.yaml

test supported nemesis with 90 percent
Task: https://github.com/scylladb/scylla-cluster-tests/issues/9155
Full nemesis status details:
please see full details in https://github.com/scylladb/scylla-cluster-tests/issues/9155#issuecomment-2535262107
- [new pipeline test](https://argus.scylladb.com/tests/scylla-cluster-tests/2504ce8f-17b9-4f17-9914-bbf3313bec0f)

test(elacticity with nemesis): test 90 percent with supported nemesis

---

sdcm/cluster.py

When rolling back from Scylla enterprise to oss, `is_enterprise` verification verifies only rc, which is 0 in that scenario.
There were recent change around this logic, where `scylla-enterprise` was asserted to be in the stdout of `apt-cache show scylla-enterprise` command - which this commit brings back.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8841

fix(upgrade-test): fix is_enterprise on rollback to oss

---

sdcm/nemesis.py
sdcm/tester.py

When updating `is_tablets_feature_enabled` session argument was changed to node. This change was not reflected in few places.

fix(Nemesis): is_tablets_feature_enabled wrong keyword argument

---

sdcm/gemini_thread.py
unit_tests/test_gemini_thread.py

Gemini needs to work without an oracle in upgrade tests, there was a bug which failed to run gemini since `Oracle Cluster` is `None`

fix(gemini): make gemini work without oracle passed

---

pyproject.toml

Currently, it is ignored in precommit only, so if running manually it will still complain.

improvement(pyproject.toml): Add Argus client to ignores for Ruff

---

sdcm/utils/decorators.py
unit_tests/test_utils_decorators.py

Closes: https://github.com/scylladb/scylla-cluster-tests/issues/10128
- [scylla-staging/valerii/vp-scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes#7](https://argus.scylladb.com/tests/scylla-cluster-tests/321a60b6-1cc0-4d02-8963-b27c7b1688ab)
- [scylla-staging/valerii/vp-perf-regression-latency-650gb-during-rolling-upgrade#28](https://argus.scylladb.com/tests/scylla-cluster-tests/fe626fe7-91af-43f7-97a3-f7c02c8a5c51)

fix(hdr_tags): fix getting of HDR tags in the perf predefined steps test

---

sdcm/utils/common.py

since images names and they label tags are not identical in the version format, one had to be exact as the version while what visible is the image name
now all of those variants would work regardless:
* 2025.1.0-rc2
* 2025.1.0~rc2
* 2025.1.0.rc2
for both AWS and GCP, Azure doesn't have rc version uploaded into public gallary yet.

fix(list-image): improve handling of rc versions listing

---

test-cases/performance/perf-regression-latency-650gb-elasticity.yaml
test-cases/performance/perf-regression-latency-650gb-upgrade.yaml
test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml

Run the elasticity / operations / upgrade tests with c-s image v3.17.3.

fix(performance): change loader type

---

sdcm/provision/aws/capacity_reservation.py
sdcm/utils/resources_cleanup.py

In case region is not provided we should search all regions for active CR's for given test id instead of failing.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10131

fix(cleanup): fix cleaning CRs when no region provided

---

defaults/test_default.yaml

Feature is enabled for one longevity and perf elasticity case and we didn't face issues around that.
Enabling this feature by default will speed up cluster provisioning and make test scenarios where we add multiple nodes (`nemesis_add_node_cnt`>1) more appropriate for recent Scylla where we test doubling cluster as fast as possible.

improvement(setup): enable parallel node operations by default

---

sdcm/utils/adaptive_timeouts/__init__.py
sdcm/utils/tablets/common.py

`wait_no_tablets_migration_running` function was raising exception in case of timeout. This caused to miss info about added node and failing its decommission in tests.
Fix by applying soft timeout to this function (with hard timeout set much higer) and making it not raising exception, but just error event.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10119

fix(wait_no_tablets_migration_running): add soft timeout

---

upgrade_test.py
utils/get_supported_scylla_base_versions.py

baa8624a648ff3e14bc729be6300d83b12e59929 change the logic of `node.is_enterprise` and missed to update a small part in `upgrade_test` that was counting on the old logic based on packaging
cause of it we failed to configure `reinstall` for the rollback

fix(upgrade_test): use `node.is_product_enterprise`

---

sdcm/cluster.py
sdcm/nemesis.py

Implementation of `get_any_ks_cf_list` returned incorrect table names when
`filter_out_table_with_counter` was True. If such a table contained one
column whose type is not counter, this table would be added to the final
list and returned.
Fixes https://github.com/scylladb/scylla-cluster-tests/issues/9998

fix(modify_table_compaction): filter_out_table_with_counter is not filtering counter tables

---

sdcm/logcollector.py

check existing for tarball compressed with zstd, but not for zstd compressed file (as the case when splitting big sct log)
Fixes: #10167

fix(logcollector): introduce correct check to zstd only file

---

sdcm/utils/replication_strategy_utils.py

code in `_alter_keyspace_rf` was reffering only to one DC in the ALTER command, that lead to RF=0 on other DCs
this complication the situation for scylla, and surface multiple bug in operation that are talking place during this operation also is kind of change is not the intended behavier of this code
so now it would update the DC RF as needed, while leaving the other DCs RF the same as they were
Fix: #10136

fix(DataCenterTopologyRfControl): stop taking region to RF=0

---

sdcm/cluster.py
sdcm/nemesis.py
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/operations_thread.py
test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml

When running parallel nemesis all take the same seed. Sometimes one might specify different ones for each.
This commit allows to specify seeds as a list (or space separated ints) so each nemesis will get own seed.
It works by cycling through nemesis_seed list when defining nemesis arguments.
closes: https://github.com/scylladb/scylla-cluster-tests/issues/9333

improvement(nemesis): allow specify different seeds for parallel nemesis

---

configurations/disable_client_encrypt.yaml
jenkins-pipelines/manager/ubuntu24-manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu24-manager-upgrade.jenkinsfile
mgmt_cli_test.py
mgmt_upgrade_test.py
sdcm/mgmt/cli.py
test-cases/manager/manager-backup-restore-set-dataset.yaml
test-cases/manager/manager-installation-set-distro.yaml
test-cases/manager/manager-no-delta-backup-set-dataset.yaml
test-cases/manager/manager-regression-azure.yaml
test-cases/manager/manager-regression-ipv6.yaml
test-cases/manager/manager-regression-multiDC-gce.yaml
test-cases/manager/manager-regression-multiDC-set-distro.yaml
test-cases/manager/manager-regression-singleDC-set-distro.yaml
test-cases/manager/manager-restore-outside.yaml
test-cases/upgrades/manager-upgrade.yaml

Closes https://github.com/scylladb/scylla-manager/issues/4164
**Changes:**
- Updated `ensure_and_get_cluster` method to apply `--force_non_ssl_session_port` flag in add cluster command if client encryption is enabled. Together with that, updated `add_cluster` method in upgrade and installation tests as well.
- Updated `test_client_encryption` to make it independent of initial cluster state.
- Enabled client encryption for most Manager tests, except of one sanity (ubuntu24-manager-sanity) and one upgrade test (ubuntu24-manager-upgrade).

[Manager] Run Manager tests with enabled client encryption

---

defaults/test_default.yaml
unit_tests/test_scylla_yaml_builders.py

Make it be bigger than the current scylla default '1' to avoid load balance issues.
Ref: https://github.com/scylladb/scylladb/pull/22522

test(default): set 'tablets_initial_scale_factor' scylla config option

---

sdcm/nemesis.py

With the old ammount of data, it was never flushed to disk and because it gets dropped at the end of the nemesis, it looks like nothing was written to the new DC.
By writting more and flushing, we can see it in Grafana.
closes: #9923
Test fails due to a different issue later, it also fails without this, I am creating a different issue for that.

test(add_remove_dc): write more data and flush

---

sdcm/utils/aws_builder.py

those value was introduced in recent java updates, and we suspect them to be breaking connections
to long running jenkins agents.
hopfully disabling them, would make the related issue go away.
Ref: #9444
logs showed it's working:
```
[02/25/25 22:55:13] [SSH] Starting agent process: cd "/tmp/jenkins" && java -Djdk.httpclient.maxLiteralWithIndexing=0 -Djdk.httpclient.maxNonFinalResponses=0 -jar remoting.jar -workDir /tmp/jenkins -jar-cache /tmp/jenkins/remoting/jarCache
```

fix(aws_builder): disable java new http max values

---

defaults/test_default.yaml
jenkins-pipelines/master-triggers/sct_triggers/no_tablets_weekly_trigger.xml
sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_azure.py
sdcm/cluster_gce.py
sdcm/test_config.py
test-cases/PR-provision-test.yaml
test-cases/longevity/longevity-100GB-48h-cloud-CloudLimitedChaosMonkey-tls.yaml
test-cases/manager/manager-backup-and-restore-4TB-single-node.yaml
test-cases/manager/manager-multiple-restores-schema-and-data.yaml
test-cases/manager/manager-regression-azure.yaml
test-cases/manager/manager-regression-ipv6.yaml
test-cases/manager/manager-regression-multiDC-gce.yaml
test-cases/manager/manager-regression-multiDC-set-distro.yaml
test-cases/upgrades/manager-upgrade.yaml
unit_tests/provisioner/test_azure_region_definition_builder.py
unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
unit_tests/test_utils_common.py
vars/artifactsPipeline.groovy
vars/byoLongevityPipeline.groovy
vars/longevityPipeline.groovy
vars/managerPipeline.groovy
vars/perfRegressionParallelPipeline.groovy
vars/perfSearchBestConfigParallelPipeline.groovy

cause we are running into multiple cases of resource left behind unattended, we by default gonna set all pipelines to destroy whom would need to investigate something specific would need to run it with `keep/keep-on-failure`

fix(post_behavior_*): set all of them to `destroy`

---

defaults/aws_config.yaml
defaults/gce_config.yaml
defaults/test_default.yaml

- https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/amnon/job/byo-longevity-test/49
Adding the monitoring 4.9.0 branch and images

Monitoring 4.9.0

---

sdcm/cluster_azure.py
sdcm/cluster_k8s/__init__.py
unit_tests/dummy_remote.py

b8b20a2 introducde changes in as baseclass that didn't included implemetions in all it's users.
that can break the EKS/GKE flows (and pylint was yelling at it in backports to old branches)

fix(NodeBase): add missing `_set_keep_duration` implementations

---

jenkins-pipelines/manager/ubuntu22-manager-sanity.jenkinsfile
mgmt_cli_test.py
sdcm/mgmt/cli.py

Closes https://github.com/scylladb/scylla-manager/issues/3871
**Changes:**
***Extended sctool restore task with dc-mapping flag***
To run a restore task for multiDC cluster with EaR enabled (otherwise fails https://github.com/scylladb/scylla-manager/issues/3871), the special flag has been introduced in Manager (https://github.com/scylladb/scylla-manager/pull/4213) to map backed up DC with DC to restore into, for example, `sctool restore ... --dc-mapping dc1=dc1,dc2=dc2`.
The change introduces this new flag into `create_restore_task` method and makes sure that if Scylla cluster has more than 1 datacenter - the restore task will be triggered with this flag applied.
***Updated configurations to run ubuntu22 sanity test on multiDC cluster***
- ubuntu22-manager-sanity.jenkinsfile
- …

[Manager] Adaptation for Multi DC restore

---

sdcm/cluster_docker.py

b8b20a2 introduced changes in as baseclass that didn't included implementations in all it's users. that can break the docker backend (and even pylint was yelling about it old branches)

fix(cluster_docker): add missing `_set_keep_duration` implementation

---

sdcm/fill_db_data.py
upgrade_test.py

recently that was new addition that was introduced that blocks creation of MV and SI if tablets enabled, so we must drop the usage of indexes in that case.
Fixes: #10169

fix(upgrade_tests): skip user profiles with index if tablets enabled

---

sdcm/nemesis.py
sdcm/utils/raft/__init__.py
sdcm/utils/topology_ops.py

Decommission operation could run longer on different clouds and with enabled/disabled tablets feature.
Nemesis DecommissionStreamingError depend on log messages which could appear in different log places. Increase timeouts to wait log messages and total decommission operation
Fixes: #8855
- [Job passed](https://argus.scylladb.com/tests/scylla-cluster-tests/80b7ae35-b5b1-49ba-a127-a610c8cb41ff)

fix(nemesis): increase wait timeout for decommission operation

---

sdcm/cluster_aws.py

With increase of node count in a test cluster we get significant delays among points in time where SCT triggers a DB node startup. Looks like it happens because we connect to the node a lot of time to receive list of interfaces. The interfaces are not changed during the test so it's not needed to be received so many times.
To prevent unnesessary getting of network interfaces, make this cached.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10217

fix(network interfaces): change network_configuration to be cached

---

sdcm/logcollector.py

8109f84aab95f52f6ff14484105dfd841438b22c add a check, but that check isn't generating and stdout, hence it was failing during checks:
```
Archive `2025_03_01__16_24_19_622.sct-d3da56d3.log.zst' is corrupted:
`zstd -t '2025_03_01__16_24_19_622.sct-d3da56d3.log.zst'' returns 0
```
this commit adds one more command that would output the stats of the zstd compressed file

fix(logcollector): print zstd information that was missing

---

configurations/zerotoken_nodes/zeronodes_num_4.yaml
jenkins-pipelines/oss/longevity/longevity-100gb-4h-with-4-zerotoken-nodes.jenkinsfile
sdcm/nemesis.py

Configure to run most of topology, schema, config nemesises to run on any node (data node or zero token node) and created new job with large number of zero toke nodes
- [Test passed](https://jenkins.scylladb.com/view/master/job/scylla-master/job/ClusterCoreQALongevities/job/longevity-100gb-4h-with-4-zerotoken-nodes-test/3)
- [Test passed](https://jenkins.scylladb.com/view/master/job/scylla-master/job/ClusterCoreQALongevities/job/longevity-100gb-4h-with-4-zerotoken-nodes-test/4)

fix(zeronodes): Job to run cluster with large number of zerotoken nodes

---

test-cases/PR-provision-test-docker.yaml

Tablets are enabled by default and we use most recent Scylla in docker
provision test in CI. Because counters are not supported with tablets it
fails CI with c-s error.
fix by disabling tablets like in cloud based CI.

fix(PR-provision-test): disable tablets in CI docker backend

---

test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml

enable hinted handoff for perf-regression-latency-650gb-with-nemesis
- https://jenkins.scylladb.com/job/scylla-staging/job/artsiom_mishuta/job/hints/job/scylla-master-perf-regression-latency-650gb-with-nemesis/

test(latency): enable hinted handoff(650gb with nemesis)

---

defaults/docker_images/gemini/values_gemini.yaml
sdcm/gemini_thread.py

When gemini is run with --test-statement-log-file and --oracle-statement-log-file, after running the program for a longer periods of time, e.g 3h or 10h case, these files are extremly large, to the point that can kill loader instance in SCT. This sometimes happenes after 10 minutes, as having both of these flags, have identical data in them (same size), thats a double the storage needed.
After this change, everything thats logged in the statements files will be compress while it's being written (power of Go's `io.Writer` magic)
1. Running without log compression
- Log Size: 2.9GB * 2 (Since we have Oracle and Cluster under test statements) 
2. Running with log compression (ZSTD Compression)
- Log Size: 432MB * 2 (Since we have Oracle and Cluster under test statements)
- Add New …

feature(gemini): logs compression by default using ZSTD

---

sdcm/utils/gce_region.py

fix(gce): allow using of the CQL shard-aware ports

---

sct.py

This fixes an issue where logs would not be submitted if link is missing
from the log structure.
Fixes #10244

fix(sct.py): Check for null values in store_logs_in_argus

---

sdcm/cluster_gce.py

cause the fingerprinting of the labels might not be up-to-date we load again the instance information before we label the machine
Fixes: #10228

fix(gce): update instance state before labeling it

---

defaults/aws_config.yaml
defaults/gce_config.yaml
defaults/test_default.yaml

Reverts scylladb/scylla-cluster-tests#10006
seems like we are hitting this issue:
https://github.com/grafana/grafana/issues/82958
at least on GCP
reverting it for now

Revert "Monitoring 4.9.0"

---

configurations/performance/cassandra_stress_gradual_load_reduced_steps_number.yaml
configurations/performance/cassandra_stress_gradual_load_steps.yaml
configurations/performance/cassandra_stress_gradual_load_steps_enterprise.yaml
docs/configuration_options.md
jenkins-pipelines/drivers/java-driver/perf-regression-predefined-throughput-steps-vnodes.jenkinsfile
performance_regression_gradual_grow_throughput.py
sdcm/sct_config.py
test-cases/performance/perf-regression-predefined-throughput-steps.yaml

New predefined steps performance test for java driver.
For performance driver tests we need to run shorter tests. To be able to change
step duration dynamicaly, add 'perf_gradual_step_duration' parameter per load type
Task: https://github.com/scylladb/qa-tasks/issues/1825

test(java driver): performance test

---

test-cases/features/elasticity/elasticity-90-percent-with-nemesis.yaml
test-cases/features/elasticity/longevity-elasticity-many-small-tables.yaml

Added a usage of simulated_racks to the 90%-utilizations tests of nemesis and of many-small-tables.
- [elasticity-90-percent-with-nemesis-simulate-rack](https://argus.scylladb.com/tests/scylla-cluster-tests/fad01b0b-d363-4bb4-9cf2-074b3b22c2cf)
- [scale-elasticity-many-small-tables-simulated-rack](https://argus.scylladb.com/tests/scylla-cluster-tests/782f0151-e35c-4088-99ea-703d0e60c0df)

fix(90% utilization): Use simulated racks

---

longevity_lwt_test.py
longevity_sla_test.py
longevity_tombstone_gc_test.py
performance_regression_alternator_test.py
performance_regression_gradual_grow_throughput.py
sla_per_user_system_test.py
upgrade_test.py
ycsb_performance_regression_test.py

following 32ebb721422788c0978f202c9494669ab3aee101, seems like we didn't changed all of the test classes using this pattern.
this commit cover all of this class that still were using `__init__`
one that did, was failing like the following:
```
AttributeError: 'TombstoneGcLongevityTest' object has no attribute 'params'
```

fix(test_classes): switch from `__init__` to `setUp`

---

sdcm/nemesis.py

DecommissionSeedNode is not supported with high disk utilization. 
It [fails](https://argus.scylladb.com/tests/scylla-cluster-tests/fad01b0b-d363-4bb4-9cf2-074b3b22c2cf) with "Unable to find new replica for tablet".

fix(90% utilization with nemesis): opt out DecommissionSeedNode

---

sdcm/nemesis.py

this commit changes keyspace replication factor to 0 before removing the DC to avoid scylla failures while decommissioning
refer: 9861
fix: #9861 
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/eugene_test_folder/job/add_remove_dc/

fix(nemesis): replication factor set to 0 before decommission

---

sdcm/tester.py

One of the recently merged PRs (https://github.com/scylladb/scylla-cluster-tests/pull/10073) introduced a bug for latte commands.
The bug is if we explicitly define the duration for main latte stress commands
then it gets also applied to the `preload` ones
which have specific number of operations to be performed, not real duration.
So, update the appropriate regex to make it work as expected again.
- [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload1-hybrid-raid#34](https://argus.scylladb.com/tests/scylla-cluster-tests/41569477-eb39-4a12-adcd-fdceafad6e4a)

fix(latte): handle duration update properly

---

sdcm/loader.py

In latte logic we use special class for handling of the detected keyspaces which is needed to share the data among several data exporters - common stress cmd results and HDR histograms data.
The problem was that having `self._value = ''` the condition for emptiness
was always giving us `False` because we were checking the class instance itself for emptiness.
So fix it by adding additional methods to make it behave like string more closely.
- [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload1-hybrid-raid#34](https://argus.scylladb.com/tests/scylla-cluster-tests/41569477-eb39-4a12-adcd-fdceafad6e4a)
- Update the Readme/doc folder relevant to …

fix(latte): detect latte keyspace correctly

---

sdcm/nemesis.py
test_lib/compaction.py

modify_table_twcs_window_size nemesis modified to test twcs strategy in wider borders
modify_table_compaction nemesis modified for the same purposes.
Both collected in single commit due to modify_table_twcs_window_size nemesis depends on modify_table_compaction (ie modify_table_compaction nemesis adds randomness that should affect modify_table_twcs_window_size)
refs: 9361, 9362
fixes: #9361, #9362
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/eugene_test_folder/job/twcs_cluster_without_changes/59/

refactor(nemesis): modified compaction strategies related nemeses

---

unit_tests/test_config_get_version_based_on_conf.py
unit_tests/test_version_utils.py

Drop unit tests for enterprise:latest branch, as after switching to SA the branch support is not needed.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10276

fix(unit-tests): drop tests for enterprise:latest branch

---

performance_regression_test.py

This would allow to set configurations options that cassandara-stress does not support like setting the initial number of tablets.
Similar to what the longevity test does.

test(performance regression): allow pre-creating the test keyspace

---

data_dir/nemesis.yml
data_dir/nemesis_classes.yml
jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithIptableRuleNemesis-aws.jenkinsfile
jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithIptableRuleNemesis-azure.jenkinsfile
jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithIptableRuleNemesis-docker.jenkinsfile
jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithIptableRuleNemesis-gce.jenkinsfile
jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithProcessSignalNemesis-aws.jenkinsfile
jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithProcessSignalNemesis-azure.jenkinsfile
jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithProcessSignalNemesis-docker.jenkinsfile
jenkins-pipelines/oss/nemesis/longevity-5gb-1h-IsolateNodeWithProcessSignalNemesis-gce.jenkinsfile
sdcm/exceptions.py
sdcm/nemesis.py
sdcm/rest/raft_api.py
sdcm/utils/nemesis_utils/node_operations.py
sdcm/utils/raft/__init__.py
unit_tests/test_nemesis.py
unit_tests/test_nemesis_sisyphus.py

New nemesis for raft feature consistent-topology-changes:
ban removed node if it try back to cluster
The new nemesis send signal to scylla process and set it PAUSED
After the node with paused scylla marked as DN, the node is removed
After that signal SIGCONT is send and scylla is backed. but any connection
from that node should be ignored.

fix(nemesis): Add new nemesis for topology changes feature

---

jenkins-pipelines/manager/rocky9-manager-install.jenkinsfile

This .jenkinsfile didn't get an update when the refactoring for Manager test files (classes reorganization, renamings) were done.
Fixing here updating test_name parameter to the valid one.

fix(manager): update path to test for rocky9 installation test

---

sdcm/db_log_reader.py
sdcm/sct_events/__init__.py
sdcm/sct_events/database.py

A new severity level, that would help us stop generating some events we need those events for skipping some log line, so we never generate error or critical events from those.
until now we generated an event for each one, and now we'll be able to skip them since for some cases there are too many of those warnings.

feature(events): introduce Severity.SUPRESS

---

jenkins-pipelines/oss/longevity/longevity-scale-5dcs-cluster-xl.jenkinsfile
longevity_test.py
sdcm/cluster.py
sdcm/sct_config.py
sdcm/utils/cluster_tools.py
test-cases/scale/longevity-scale-5dcs-cluster-xl.yaml

The scale test allows you to add new nodes to reach the target cluster size only when you have a single data center (DC) cluster configuration. However, if you have a multi-DC configuration, you cannot run scale tests with iterations.
The fix introduces a new feature that allows you to configure a multi-DC cluster and set the target size for it. Then, new nodes can be added to each DC in an iterative process until the target size is reached.
Next config params should be configured:
n_db_nodes: '3 3 3 3 3'
cluster_target_size: '25 25 25 25 25'
add_node_cnt: 10
cluster will start with 5 dc with 3 nodes in each
then on each interation 10 nodes will be added to
each dc while target size in each dc 25 nodes will
not be reached.
- [DC: 2, start size: 3 3, add by : 3, finished: 9 …

feature(multidc): scale cluster per dc in multidc config

---

sdcm/argus_results.py

According to Avi, we should not validate cpu_cycles_per_op and fail the test on it. This metrics is not stable

fix(argus): do not validate cpu_cycles_per_op

---

upgrade_test.py

seem like by mistake we left some logic that skip the `reinstall` option for the rollback, hence code would try to do `yum downgrade` and would fail to uninstall the new 2025.1 version during rollback.

fix(upgrade_test): make rollback reinstall option work for centos

---

artifacts_test.py
sdcm/argus_results.py
sdcm/utils/validators/iotune.py

This commits adds a new subtest inside Artifacts test, that does the
check of machine image io_properties.yaml by comparing them to the
actual machine values and showing the deviation. The results are both
printed to console with deviation value and submitted to argus as a 
GenericResultTable.
Fixes scylladb/qa-tasks#1787

feature(ArtifactsTest): IOTune parameters validation

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/cluster_azure.py
sdcm/cluster_docker.py
sdcm/cluster_gce.py
sdcm/cluster_k8s/__init__.py
unit_tests/dummy_remote.py
unit_tests/test_utils_common.py

test duration in SCT is calculated in minutes, while the tags are using hours, updating the implmention to pass hours and rename the functions arguments to match.

fix(keep_duration): pass along the keep:duration tags as hours

---

sdcm/tester.py

If checking regression fails, this makes it easier to debug, especially errors related to the email templates.
For example, if a test does not have `use_hdrhistogram: true`, then the error would be 
> 2025-03-02 13:55:20.759: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=f0a49a5c-6891-43c3-8f99-85b5798e090f, source=PerformanceRegressionTest.check_regression() message=Failed to check regression
exception='NoneType' object is not iterable
which is not useful at all

fix(tester): add traceback logging when checking regressions

---

upgrade_test.py

seem like in one of the backports, this line was dropped and was cause upgrades of centos to fail

fix(upgrade_test): introduce back missing reinstall option

---

performance_regression_test.py

Parameters are not initialized before that and it kept failing on `self.params`
- Failed due to #10360, but passed otherwise. I did not want to edit testcase just for this PR 

fix(performance_regression_test): Move super.setUp() to be called first

---

sdcm/nemesis.py
sdcm/utils/nemesis_utils/indexes.py

This commit disables disrupt_add_remove_mv from using a static column
inside a materialized view by introducing additional flag to both
get_column_names and get_random_column_name to disable selecting
'static' column types.
Fixes #10202

fix(nemesis.py): Prevent static columns for MVs

---

docker/cql-stress-cassandra-stress/Dockerfile
docker/cql-stress-cassandra-stress/image

Recently updated driver to 1.0.0. Publishing new version so it can be used in SCT.
This version also contains cql-stress with `version` argument support.
refs: https://github.com/scylladb/cql-stress/issues/115

improvement(cql-stress): updated to version with driver 1.0.0

---

microbenchmarking_test.py
performance_regression_gradual_grow_throughput.py
performance_search_max_throughput_test.py
sct.py
sdcm/db_stats.py
sdcm/es.py
sdcm/microbenchmarking.py
sdcm/nemesis_publisher.py
sdcm/reporting/elastic_reporter.py
sdcm/results_analyze/__init__.py
sdcm/tester.py
sdcm/utils/benchmarks.py
sdcm/utils/es_index.py
sdcm/utils/microbenchmarking/perf_simple_query_reporter.py
sdcm/utils/operator/multitenant_common.py
sla_per_user_system_test.py
utils/migrate_nemesis_data.py
utils/update_field.py

this argument was removed in v7 of the elasticsearch client we shouldn't use it anymore
fixes: #10308

fix(elastic): remove usage of doc_type

---

requirements.in

Reverts part of scylladb/scylla-cluster-tests#10356, that was just for testing, and shouldn't have merged it

Revert "chore(requirements.in): update of something"

---

.github/workflows/build-docker-image.yaml

this workflow was pushing the changes into the wrong repo i.e. not the repo the PR was coming from

fix(build-docker-image): use the current repository

---

.github/workflows/build-docker-image.yaml

since we are using `pull_request_target` the workflow works in the context of main repo, and not the forked one.
switching to checking out from the fork

fix(workflows/build-docker-image): checkout from the correct repo

---

.github/workflows/build-docker-image.yaml

was using the wrong argument for `actions/checkout` and was checking out the default `master` branch from the fork and not the PR's branch

fix(workflows/build-docker-image): s/branch/ref/ on checkout params

---

mgmt_cli_test.py

**Change Scylla version getting approach for snapshots preparer**
Since `_build_ks_name` method is used when Scylla cluster is deployed, there is no need to get `scylla_version` from configuration. Instead of this, it can be retrieved directly from Scylla node using node object property `scylla_version`.
It makes the method universal - supports both basic and cloud created clusters. The previous approach with getting version from config does not work for Cloud cluster (Siren clusters).
**Fix locations property to support list-type `backup_bucket_location` parameter**
Previous implementation supported only str-type `backup_bucket_location` and failed the test for list-type objects.

Fix cloud snapshot preparer

---

test-cases/longevity/longevity-large-partitions-deletions-and-reversed-queries.yaml

Fix nemesis selector values and set multi nemesis. One with "delete_rows" and the other with "disruptive".
So the test will have intensive deletions while also having disruptive operations.
Fixes: #10256

fix(longevity-large-partitions-deletions-and-reversed-queries.yaml): split to multi nemesis

---

sdcm/nemesis.py

this commit adds decorator for ignoring mutation writes during remove_node_then_add_node nemesis
Ref: https://github.com/scylladb/scylladb/issues/21815
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/eugene_test_folder/job/ignore_mutations/

fix(nemesis): decorator for ignoring mutation errors added

---

upgrade_test.py

Reverts scylladb/scylla-cluster-tests#10330
seems like this is actually needed logic
and the problem was a broken backport, that drop the `reinstall` option

Revert "fix(upgrade_test): make rollback reinstall option work for centos"

---

sdcm/utils/database_query_utils.py

When there is difference test ends with following message:
```
sdcm.sct_events.events_analyzer.TestFailure: Got critical event: (PartitionRowsValidationEvent Severity.CRITICAL) period_type=one-time event_id=318ca98d-c349-4cad-bddc-889918d9f326: message=Row amount in partitions is not same before and after running of nemesis: {0: 5555, 2: 5555, 5: 5555, 7: 5555, 8: 5555, 11: 5555, 12: 5555, 13: 5555, 14: 5555, ....}
```
Which does not tell you what is the difference.
Not tested

fix(database_query_utils): make PartitionRowsValidationEvent contains diff between before and after state

---

test-cases/kafka/longevity-kafka-cdc.yaml

Until CDC is supported with tablets, the kafka cdc connector test should use a test keyspace with tablets disabled.

fix(kafka-cdc-connector): create test keyspace with tablets disabled

---

sdcm/utils/docker_remote.py
sdcm/utils/docker_utils.py

The change adjusts RemoteDocker.pull_image method to log in to Docker hub and pull an image under the same user context.
This prevents a scenario when the login is performed as a regular user, but the image pull is executed under the root user context, leading to an unauthenticated request from Docker hub perspective.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10399
The logging in to Docker hub and pulling the image is now performed under the same user context (root or a regular user) and should prevent from hitting pull rate limit early:
```
❯ grep -i 'docker ' sct-d9b87b0c.log
< t:2025-03-13 20:24:21,786 f:docker_utils.py l:546  c:RemoteLibSSH2CmdRunner p:DEBUG > Login to Docker Hub as `scyllaqatest'
< t:2025-03-13 20:24:21,786 f:remote_base.py  l:560 …
```

fix(docker_remote.py): login to Dockerhub and pull image under the same context

---

defaults/docker_images/latte/values_latte.yaml

Main changes are following:
- Switched to the usage of the newest Scylla rust driver - 1.0.0
- Added support for the Decimal Cql data type

ci(latte): bump latte version to `0.28.3-scylladb`

---

sdcm/cluster.py
sdcm/mgmt/cli.py
sdcm/nemesis.py
sdcm/utils/context_managers.py

improvement(logging): Log SCT actions in system log of cluster nodes
Adds ability to log SCT actions in the system log of cluster nodes.
Some cluster node operations (mainly the disruptive actions of Nemeses) have
been updated to be logged using this feature.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/10051
Example of log entries on nodes:
```
❯ egrep -r 'scylla-cluster-tests' db-cluster-4cf287ea/longevity-5gb-1h-RestartThenRepairN-db-node-4cf287ea-*/
...
db-cluster-4cf287ea/longevity-5gb-1h-RestartThenRepairN-db-node-4cf287ea-1/messages.log:2025-03-05T09:33:52.019+00:00 longevity-5gb-1h-RestartThenRepairN-db-node-4cf287ea-1     !INFO | scylla-cluster-tests[5738]: executing restart node on longevity-5gb-1h-RestartThenRepairN-db-node-4cf287ea-2 [10.4.3.164] …
```

improvement(logging): Log SCT actions in system log of cluster nodes

---

sdcm/cluster.py
sdcm/cluster_aws.py
sdcm/utils/net.py
unit_tests/test_cluster.py

Because scylla logs show it in this format we want to align it with SCT so it's not failing comparisons or eases searching.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/8910

fix(ipv6_format): as string in format of inet_ntop

---

sdcm/cluster.py

to avoid AttributeError: 'NoneType' object has no attribute 'get'
minor fix 
ref: https://github.com/scylladb/scylla-cluster-tests/issues/10314

fix(cluster.py): None type added as returned value in host_id prop

---

utils/scylla_doctor.py

This commit fixes an issue where some distros might have preinstalled
curl with unexpected dependencies, preventing installing curl using the
package manager.
Fixes #10425

fix(scylla_doctor.py): Don't try to reinstall curl

---

defaults/severities.yaml
sdcm/sct_events/database.py

Scylla `2025.1.0` started producing following error in DB logs:
```
Feb 20 21:15:35.887314 long-5000-tables-2025-1-db-node-acc227de-2 scylla[5730]:  \
[shard  0: gms] raft_topology - send_raft_topology_cmd(stream_ranges) failed \
with exception (node state is bootstrapping): raft::request_aborted \
(Request aborted while performing action on leader, \
current leader: fccd43b5-4024-4c2a-853d-88bba7df9fd4, previous leader: unknown)
```
This error is not critical and we should reduce it's severity in SCT while it is not fixed.
Ref: https://github.com/scylladb/scylladb/issues/22980

improvement(events): add DB event type for raft topology sending error

---

utils/scylla_doctor.py

Since we don't use debian as a base for docker image anymore and have
switched to RHEL UBI9 the call to `apt update` is no longer needed.
Fixes #10436

fix(utils/scylla_doctor.py): Remove `apt update` call

---

docker/env/build_n_push.sh

`python-version` doesn't exist in the code, while `.python-version` does...
this commit should fix the ability to build hydra docker images

fix(build_n_push.sh): add a missing dot

---

sdcm/utils/common.py
utils/cloud_cleanup/gce/clean_gce.py

* fix `list_instances_gce` to return stopped instances
* fix gce cleanup to default to `keep_action==terminate`, even if action label is empty

fix(gce_cloud_report): report and handle stopped instances

---

sdcm/sct_provision/aws/cluster.py

the aws pricing model is suffering from cyclic depedecies this change is a workaround avoid it, if we aren't really gonna use the pricing code
(cherry picked from commit a1d4dc9e21545c74e77e25e5190f0ca1974eb2a6)

Backport[perf-v16]: fix(aws-provision): avoid pricing import

---

test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml

List of changes:
- Split existing stress commands into more separate ones based on the read/write type.
- Start using explicit function names instead of the "custom" aggregation one. It will allow the metrics handler correctly map stress commands to "READ" and "WRITE" workload types.
- Increase nemesis interval from 5 to 10 minutes to mitigate not finished operations (compactions) left after impactful nemesis such as "disrupt_destroy_data_then_repair".
- [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload2-hybrid-raid#64](https://argus.scylladb.com/tests/scylla-cluster-tests/5e4b7b4e-b263-4d24-88a3-f40802e817dd)
- Update the Readme/doc folder …

improvement(custom-d1-w2): update configuration

---

sdcm/cluster.py

Ignore failures when executing the remote 'logger' command for logging SCT actions in the system log of DB nodes.
A node may sometimes become unavailable (e.g., after a nemesis decommissions it), so we should avoid raising exceptions for such valid cases.
Instead, we should just try to log SCT actions on remote DB nodes and raise no exceptions if it wasn't successful (otherwise this can affect the thread where this kind of
logging is performed, e.g. a nemesis).
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10424
We should be OK now with attempts to log to nodes and not aborting nemesis thread due to the addressee node is no longer available  - as it is seen from e.g. Jenkins console, there are instances of  errors in logs like below (and these error entries will appear …

fix(cluster.py): ignore status of SCT actions logging on DB nodes

---

configurations/tablets_multidc_multirack.yaml
defaults/test_default.yaml
internal_test_data/multi_region_dc_test_case.yaml
sdcm/sct_config.py
sdcm/stress_thread.py
test-cases/longevity/longevity-alternator-3h-multidc.yaml
test-cases/longevity/longevity-aws-custom-d2-workload1-3dcs.yaml
test-cases/longevity/longevity-aws-custom-d2-workload1-5dcs.yaml
test-cases/longevity/longevity-cdc-100gb-8h-multi-dc-large-cluster.yaml
test-cases/longevity/longevity-cdc-100gb-8h-multi-dc-topology-changes.yaml
test-cases/longevity/longevity-counters-multidc.yaml
test-cases/longevity/longevity-encryption-at-rest-20GB-6h-multidc.yaml
test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml
test-cases/longevity/longevity-lwt-24h-multidc.yaml
test-cases/longevity/longevity-multi-dc-rack-aware-with-znode-in-diff_dc.yaml
test-cases/longevity/longevity-multi-dc-rack-aware.yaml
test-cases/longevity/longevity-multidc-parallel-network-schema-changes-12h.yaml
test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml
test-cases/longevity/longevity-ndbench-12-nodes-multidc-4h.yaml
test-cases/longevity/longevity-ndbench-192-nodes-multidc-4h.yaml
test-cases/manager/manager-regression-multiDC-set-distro.yaml
test-cases/scale/longevity-scale-5dcs-cluster-xl.yaml
test-cases/upgrades/multi-dc-rolling-upgrade.yaml

The rack aware logic of loader should not apply in case of simulated rack (where not enough loaders configured).
It should only apply in case where real multi racks are configured as in multi-dc case.
Fixes: #10402
- [longevity-10gb-3h-azure-test](https://argus.scylladb.com/tests/scylla-cluster-tests/385ef408-7a08-4f19-8d8c-59d0cd430c19)

fix(loader stress): Introduce "rack_aware_loader" parameter

---

sdcm/microbenchmarking.py
unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/no.1.json
unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/yes.1.json
unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/perf_fast_forward_output/small-partition-slicing/small-part/0-256.1.json
unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/perf_fast_forward_output/small-partition-slicing/small-part/500000-4096.1.json
unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/result_obj
unit_tests/test_data/test_microbenchmarking/PFF_with_new_metric/result_obj
unit_tests/test_data/test_microbenchmarking/PFF_without_AVGAIO/result_obj
unit_tests/test_microbenchmarking.py

since `microbenchmarking` index was deleted, this commit switch the unittest to work with the latest index `microbenchmarkingv3`, for that some of the version and names of the host were needed to change

fix(microbenchmarking): point unittest to index `microbenchmarkingv3`

---

microbenchmarking_test.py

New parameter 'perf_simple_query_extra_command' was presented in https://github.com/scylladb/scylla-cluster-tests/pull/10331
If the new parameter is not defined for the test, the 'None' is return by get and causes to test failure:
```
Command: 'scylla perf-simple-query --json-result=perf-simple-query-result.txt --smp 1 -m 1G None' error: too many positional options have been specified on the command line
```
Return empty string instead of 'None'.
Example of failed test: https://argus.scylladb.com/tests/scylla-cluster-tests/a7145188-0f42-4f95-ad91-5ce478a13211

fix(perf-simple-query): handle 'perf_simple_query_extra_command' param

---

.github/workflows/test-hydra-macos.yaml
docker/env/hydra.sh
sdcm/utils/aws_okta.py
sdcm/utils/get_username.py

feature(git-actions): new action to test hydra on macos

---

sdcm/nemesis.py

Makes unselection and then selection an atomic operation in `set_target_node`.
Previously unselection and then selection were performed not in the same lock scope, leading to a potential situation when 2 threads could pick up the same node for parallel nemeses.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10426
The test run was executed on branch-2024.1 as the `disrupt_create_index` nemesis (one of 2 parallel nemeses, which were causing the failure in the original issue) is skipped in SCT master due SkipPerIssues condition.
But the fix is applicable to master as well.

fix(nemesis.py): make node unselection and selection atomic in set_target_node

---

docker/env/hydra.sh

since the cap `^` was dropped, we had situation where the prefix of envs we were looking was in the content of other envirment variables
and that was breaking the hydra command
Fixes: #10480

fix(hydra): bring back the ^ to the regexs

---

artifacts_test.py

since it's currently broken for docker backend,
and we have more work to fix it, we are disable it for now
Fixes: #10449

fix(artifacts-test): skip scylla-doctor check for docker

---

sdcm/cluster.py

Since the scylla issue 18647 is closed, no need to wait for nodes up-normal status after rolling-restart.
refs: https://github.com/scylladb/scylladb/issues/18647
- [50gb-3days](https://argus.scylladb.com/tests/scylla-cluster-tests/e785da10-5beb-4076-944f-077e477bce28)

fix(nemesis.py): don't wait after rolling restart cluster

---

test-cases/longevity/longevity-alternator-3h-multidc.yaml
test-cases/longevity/longevity-aws-custom-d2-workload1-3dcs.yaml
test-cases/longevity/longevity-aws-custom-d2-workload1-5dcs.yaml
test-cases/longevity/longevity-counters-multidc.yaml
test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml
test-cases/longevity/longevity-ndbench-12-nodes-multidc-4h.yaml
test-cases/longevity/longevity-ndbench-192-nodes-multidc-4h.yaml

The rack aware logic only apply to c-s. remove it from yamls that only use other stress tools.

fix(rack_aware_loader): remove from non c-s tests

---

defaults/docker_images/latte/values_latte.yaml

Main changes are following:
- Added support for the `Counter`, `Date`, `Time`, `Duration`, `Varint` and `Tuple` CQL data types.
- Added possibility to get detailed version for latte and Scylla rust driver.

ci(latte): bump latte version to `0.28.4-scylladb`

---

sdcm/nemesis.py

nemesis case was calling `_nemesis_stress_failure_handler` with the wrong arguments, hence failing like:
```
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5688, in wrapper
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4384, in disrupt_grow_shrink_cluster
self._double_cluster_load(duration)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 224, in wrapped
res = func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4370, in _double_cluster_load
self._nemesis_stress_failure_handler(results, errors)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2139, in _nemesis_stress_failure_handler
if len(errors) == …
```

fix(double_cluster): stress command was waited incorrectly

---

test-cases/performance/perf-regression-latency-650gb-elasticity.yaml

The latest c-s version is 3.17.3.
This version is defined for elasticity perf test, but actually the loader is created from prepared AMI and not use latest c-s version. Run loader from docker and use latest c-s version

fix(performance): run elasticity test with loader on docker

---

sdcm/sct_events/event_counter.py
sdcm/sct_events/setup.py

using it as a process is forcing us to use multiprocess sync manager which in turn can leave running processes until the test end
there no real reason for using a process with this one so switching it to the thread base implementation

fix(event_counter): switch to thread base class

---

sdcm/tester.py

We face issues with python coredumping upon SCT shutdown. One of the reason might be running argus heartbeat thread which is not awaited to complete (and it may take up to 30 secs to end).
Fix by quittin it as soon as shutdown is initiated without waiting for sleep to end.
refs: https://github.com/scylladb/scylla-cluster-tests/issues/9784

fix(shutdown): stop argus heartbeat thread quicker

---

test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml
test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml
test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
test-cases/longevity/longevity-mv-si-4days.yaml
test-cases/longevity/longevity-parallel-schema-changes-12h.yaml
test-cases/longevity/longevity-twcs-48h.yaml

Needs to be retuned to increased number of nodes, which will be done after we see it in action.
* Increased number of nodes to multiples of 3
* Left out jobs which already have AZs in the configs
* `longevity-multidc-schema-topology-changes-12h` and `longevity-50gb-3days` already have real AZs in their configuration files, followup PR will be made to run them with AZs weekly (I think they are currently reduced to a single AZ via trigger)
Part of #10241 
* Failed due to https://github.com/scylladb/scylla-cluster-tests/issues/9986, not caused by this PR, ran for 13hours

improvement(tier1): Use virtual racks

---

sdcm/cql_stress_cassandra_stress_thread.py
sdcm/reporting/tooling_reporter.py

New versions of cql-stress support `version` arg.
Started collecting cql-stress-cassandra-stress version to Argus.
refs: https://github.com/scylladb/qa-tasks/issues/1829

improvement(cql-stress): collect cql-stress and driver version

---

artifacts_test.py

since scylladb/field-engineering#2254 was close/fixed, but not on any scylla-doctor version yet, we'll switch the skip to an SCT issue so we can control better when to enable those checks
Ref: scylladb/field-engineering#2254
Ref: scylladb/scylla-cluster-tests#10540

fix(artifact_test): switch the skip issue for scylla-doctor of non-root

---

sdcm/stress/latte_thread.py
unit_tests/test_latte_thread.py

C-S logic adds operation type to the log filenames like following:
```
cassandra-stress-counter_write-l1-c0-k1-624f47b6-c312-4858-97a7-00b95be2dca2.log
cassandra-stress-write-l1-c0-k1-12398f84-08e0-4873-b4b2-6fb0237e03eb.log
```
It allows to distinguish multiple stress logs among each other.
Latte doesn't have such logic.
So, add the following behavior to ease latte logs usage:
- If `--tag foo` param for a latte command is specified then use first tag from all the tags for latte log filenames.
- If no tags are specified then use operation type instead.
Possible values in this case: `write`, `read`, `mixed` and `user`.
- [scylla-staging/valerii/vp-provision-test#12](https://argus.scylladb.com/tests/scylla-cluster-tests/5507c918-b49d-45ef-a81d-39b8026f3113)
- Add New configuration option …

improvement(latte): add tag or operation type to log filenames

---

sdcm/nemesis.py

This commit should fix unexpected python error:
```
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5559, in wrapper
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3027, in disrupt_modify_table
disrupt_func()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2839, in modify_table_default_time_to_live
ttl_to_set = calculate_allowed_twcs_ttl(compaction_properties, default_min_ttl, default_max_ttl)
UnboundLocalError: local variable 'compaction_properties' referenced before assignment
```
https://argus.scylladb.com/tests/scylla-cluster-tests/24ba3271-f770-4512-b72f-e09888871140
- Add unit tests to cover …

fix(nemesis): TTL setter workaround added for non TWCS tables

---

performance_regression_test.py
upgrade_test.py

* Removes duplicate messages, that were around every usage

improvement(upgrade_test): Move InfoEvent message into their respective functions

---

sdcm/tester.py

if we don't close it, there a left thread `QueueFeederThread` at the end of the test, we want to eliminate of the threads/proccess left at the end of the test, to avoid any deadlock of other issue that seem to be coredump the end of the end from time to time
Ref: https://github.com/scylladb/scylla-cluster-tests/issues/9784

fix(tearDown): Close DECODING_QUEUE

---

sdcm/reporting/tooling_reporter.py
sdcm/stress/latte_thread.py
unit_tests/test_latte_thread.py

With this change SCT will send `latte`
and its `scylla rust driver` versions to Argus.
Ref: https://github.com/scylladb/qa-tasks/issues/1829
- [scylla-staging/valerii/vp-provision-test#15](https://argus.scylladb.com/tests/scylla-cluster-tests/1ae98407-1b0d-4a24-9e60-27126071513a)

improvement(latte): collect latte and rust driver versions

---

sdcm/provision/azure/utils.py

cause of the date version of 2025.1, the code was trying to fetch the release from the wrong repository, and fail like:
```
ValueError: Azure Image for scylla_version='2025.1' not found in eastus
```
this commit add the logic to move to the none enterprise repo as needed

fix(azure): fetch offical source-available release correctly

---

configurations/performance/cql-stress-650gb-8-col-i4i-80-percent-throughput-ent.yaml
configurations/performance/cql-stress-650gb-8-col-i4i-80-percent-throughput-oss.yaml
configurations/performance/cql-stress-6gb-8-col-i4i-mini-test-throughput.yaml
defaults/docker_images/cql-stress-cassandra-stress/values_cql-stress-cassandra-stress.yaml
sdcm/cql_stress_cassandra_stress_thread.py
sdcm/loader.py

Since cql-stress now supports hdr histogram, it can be enabled. cqlstress thread will respect `use_hdrhistogram` config param.
refs: https://github.com/scylladb/qa-tasks/issues/1861

feature(cql-stress): add support for hdr histogram

---

sdcm/argus_results.py
sdcm/utils/validators/iotune.py

This fix addresses an issue for jobs that have no argus test created for
them, causing a failure to occur. It also fixes the logger line for
console output of the results.

fix(sdcm/iotune): Do not submit results if test doesn't exist

---

sdcm/tester.py

Recent refactor of the stress threads API renamed public methods to better align with their function.
This change fixes the API usage to ensure stress results are correctly parsed before being pushed to ElasticSearch.
Tested by local run, but also the following job is running

fix(perf-regression-test): parse stress results before pushing to ES

---

sdcm/gemini_thread.py
unit_tests/test_gemini_thread.py

The default flags were wrongly concatenated without a leading space to the gemini command string
Fixes: #10581
- [test table options](https://argus.scylladb.com/tests/scylla-cluster-tests/0029ed86-9610-465a-807c-f860830b25c0)

fix(gemini_thread.py): fix appending of gemini default flags

---

.github/workflows/add-label-when-promoted.yaml

auto backport doesn't trigger when a PR is already closed and the labels are been added after. this is because `pull_request_target` was under push event instead of it's own
Fixing it
(cherry picked from commit 072a599b695d6290534dc7db627ca14270c279bd)

[Backport perf-v16] fix(auto backport): trigger with labeled event

---

.github/workflows/add-label-when-promoted.yaml

auto backport doesn't trigger when a PR is already closed and the labels are been added after. this is because `pull_request_target` was under push event instead of it's own
Fixing it
(cherry picked from commit 072a599b695d6290534dc7db627ca14270c279bd)

[Backport perf-v15] fix(auto backport): trigger with labeled event

---

configurations/performance/latency-decorator-error-thresholds-steps-ent-tablets.yaml
configurations/performance/latency-decorator-error-thresholds-steps-ent-vnodes.yaml

Following discussions with Roy, the P99 read error threshold will be increased for steps 600K and 700K in both vnode and tablet tests.

fix(performance): change error threshold for steps test

---

sdcm/remote/remote_base.py

Scp command behaviour has changed on systems that have newer openssh version (v9.0+,
like in Ubuntu24) compared to older version (e.g. v8.*, Like in Ubuntu22). Newer openssh
versions use SFTP protocol by default. This affected the behavior of RemoteCmdRunner
send_files and receive_files API, where we quote path portion of desctination to be sure
that we can run the command with multiple remote paths.
This change removes single quotes around the destination parameter in scp command.
This helps to avoid improper shell expansion of remote path portion of destination.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10584
- Update the …

fix(RemoteCmdRunner): fix scp destination string

---

test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml

The maximum duration that we got for the perf-regression-latency-650gb-with-nemesis test is 12 hours. Now test duration is 50 hours. It's too much. Decrease it to 14 hours.

fix(performance): decrease nemesis test duration

---

.github/workflows/add-label-when-promoted.yaml

The current implementation doesn't work when there is a need to backport to the perf-v16 branch
Fixing it

fix(add-label-when-promoted): match regex for perf

---

configurations/force-gossip-topology-changes.yaml
configurations/tablets-initial-32.yaml
configurations/tablets_disabled.yaml
docker/scylla-sct/entry.sh
docker/scylla-sct/entry_ssl.sh
sdcm/provision/scylla_yaml/scylla_yaml.py
sdcm/utils/features.py
test-cases/PR-provision-test-docker.yaml
test-cases/PR-provision-test.yaml
test-cases/longevity/longevity-aws-custom-d2-workload1-3dcs.yaml
test-cases/longevity/longevity-aws-custom-d2-workload1-5dcs.yaml
unit_tests/test_scylla_yaml.py
upgrade_test.py

The configuration option was changed in https://github.com/scylladb/scylladb/pull/22273
Causing all SCT runs after it to run without tablets.
e.g. https://argus.scylladb.com/tests/scylla-cluster-tests/a50f6974-da50-4963-b7ea-bbfeac27bdca
2025.1 not affected **yet**, backport was yesterday.
`2025.2.0~dev-20250403.fe8187e5940e`, before the change, keyspace1 has tablets enabled
`2025.2.0~dev-20250407.8d2a41db8231`, after the change, keyspace1 does not have tablets enabled
`2025.2.0~dev-20250407.8d2a41db8231`, after the change, with this fix, keyspace1 has tablets enabled

fix(ScyllaYaml): replace enable_tablets with tablets_mode_for_new_keyspaces

---

sct.py

* update-conf-docs, nemesis-list, create-nemesis-pipelines
* This is a hotfix and it is ugly, but for 3 commands no bigger effort is needed
* All the code was actually suggested and written by @fruch in https://github.com/scylladb/scylla-cluster-tests/issues/10534#issuecomment-2767510477

fix(sct): Dont require Okta for commands which do not need it

---

sdcm/sct_events/setup.py

Error: 'raft_topology - topology change coordinator fiber got error  (connection is closed))' Could appeared in different moment when node/nodes are being restarted. As described in issue: scylladb/scylladb#20950 in comment: https://github.com/scylladb/scylladb/issues/20950#issuecomment-2411387784
the error message could appeared while we have race between raft and gossip. we can ignore this issue while issue will not be fixed on scylla side, gossip mode will be removed from scylla.
- Job https://argus.scylladb.com/tests/scylla-cluster-tests/840673cf-ce9f-4022-95df-a3ad0b7d1d2d currently failed by another issue
- Update the Readme/doc folder relevant …

fix(longevity_test): Set ignore 'raft topology connection close' error globally

---

defaults/manager_persistent_snapshots.yaml

Closes https://github.com/scylladb/scylla-cluster-tests/issues/10602
This reverts commit d28156fd5657488ee45405b83095261d9387d087.
This change has been merged into branch-2024.1 mistakenly.
New backups contain tablets = `{'enabled': false}` property in cql statements used by Manager to restore the schema.
This property is unknown to Scylla 2024.1. That's why the restore in this branch fails with `Unknown property 'tablets'"` error.

Revert "fix(manager): update persistent snapshot used in Nemesis"

---

mgmt_cli_test.py
sdcm/mgmt/cli.py

Manager restore operation flag `--dc-mapping` is applicable for tables restore mode only ([docs](https://manager.docs.scylladb.com/stable/sctool/restore.html#dc-mapping)). 
Thus, should not be applied while restoring the schema.

fix(manager): apply dc-mapping only if restoring tables, not schema

---

sdcm/remote/kubernetes_cmd_runner.py
sdcm/remote/remote_cmd_runner.py
sdcm/remote/remote_libssh_cmd_runner.py

It may happen that `str(exc)` is an empty string, so this logging line will give no info
Example
https://argus.scylladb.com/tests/scylla-cluster-tests/d17288c2-89af-4ee9-8bd4-a04bc30fe6dc
> 2025-04-08 19:15:41.503: (InfoEvent Severity.ERROR) period_type=not-set event_id=12df3c74-5505-4c03-a8d1-ebf2cec5e41c: message=Failed to wait for having no ongoing tablets topology operations. Exception: RetryableNetworkException('')
and in sct log there is only
> < t:2025-04-08 19:15:41,497 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 

fix(remote): add exception info to `_run_on_retryable_exception`

---

sct.py
sdcm/sct_config.py

Currently, both conf-docs and update-conf-docs require AWS due to instantiation of SCTConfiguration class. Make required methods class methods to prevent unnecessary validation. This also speeds up the entire process.

improvement(sct): Do not require AWS for conf-docs and update-conf-docs

---

sdcm/cluster_docker.py

In docker backend we recently started to get WARN messages upon stopping node. Because this warn message is catched by db error regex, it causes docker artifact test to fail and mess Scylla CI. This warn is not considered as error and should be ignored.
This commit makes all warnings during stop/restart to be ignored (for docker backend only).
closes: https://github.com/scylladb/scylla-cluster-tests/issues/10633

fix(docker): ignore warnings during stop

---

sdcm/cluster.py
sdcm/utils/features.py
sdcm/utils/raft/__init__.py
sdcm/utils/raft/common.py

New feature Limited raft voters was merged. Starting from 2025.2 not all nodes are raft voters. Update raft check consistency functionality to not report errors if alive non-voters nodes
for latest sct jobs health validator reported next errors:
```
2025-04-15 03:07:17.267: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=f817d89c-ef15-48cb-8cbc-6c6af699c123: type=Group0TokenRingInconsistency node=longevity-mv-si-4d-master-db-node-15b46631-7 error=Node longevity-mv-si-4d-master-db-node-15b46631-7 has group0 member with host_id 8176f51c-65e6-49f2-9a4a-06d7a5c4a682 with can_vote False and presents in token ring True. Inconsistency between group0: [{'host_id': '13ad363b-506d-4196-ac5b-a83d82955edf', 'voter': True}, {'host_id': '2afaa902-cb64-40fc-8fe5-d123cdf6154d', …
```

fix(limited_voters): validate non-voters as failed for scylla <=2025.1

---

sdcm/utils/raft/__init__.py

In PR: https://github.com/scylladb/scylla-cluster-tests/pull/10636 after switch to use feature name instead of version was used wrong logic in if statement.
Check non voters should be done only if feature GROUP0_LIMITED_VOTERS is not enabled
- [for feature disabled(mising) in 6.2 - Passed](https://argus.scylladb.com/tests/scylla-cluster-tests/255c1fcd-065f-4f9e-910a-a193064bb92a)
- [for feature enabled in 2025.2.dev - Passed](https://argus.scylladb.com/tests/scylla-cluster-tests/e9741367-3fd6-4d05-9a39-a3efce535f4c)
- [for multidc with 2025.2 - passed](https://argus.scylladb.com/tests/scylla-cluster-tests/65f99735-c0ce-41f8-8ba5-1ff132b517d2)
- Update …

fix(search_inconsistent_host_ids): use correct logic

---

artifacts_test.py

Enterprise latest version in housekeeping is no longer relevant and will not be updated anymore, so there is no need to verify the latest for scylla-enterprise

fix(docker): stop checking housekeeping for ent

---

defaults/severities.yaml
sdcm/sct_events/database.py

new everytime we'll have those we'll have an error event for it
```
2025-03-24T12:58:48.953+00:00 rolling-upgrade--ubuntu-focal-db-node-1b73896e-eastus-4  !WARNING |
scylla[13320]:  [shard 0:strm] seastar_memory - oversized allocation: 1409024 bytes.
This is non-fatal, but could lead to latency and/or fragmentation issues.
Please report: at 0x26f152e 0x26f0fc0 0x26f0f98 0x518d2fc 0x176c134 0x15c0a44 0x271fe5c
0x2fb90dd 0x1d3c4c6 0x30d3df7 0x30d2b0c 0x2cb3099 0x2cb2a72 0x29526de
0x295a78d /opt/scylladb/libreloc/libc.so.6+0x2a087 /opt/scylladb/libreloc/libc.so.6+0x2a14a
0x319a844
```
Ref: https://github.com/scylladb/scylladb/issues/23446#issuecomment-2772291495
- Add unit tests to cover my changes (under `unit-test/` …

feature(events): new event for catching oversized allocation

---

sdcm/sct_runner.py

In https://pypi.org/project/azure-mgmt-resource/ a breaking change of: Renamed operation TagsOperations.update_at_scope to TagsOperations.begin_update_at_scope is introduced.
Fixes: #10659
- [longevity 3h azure](https://jenkins.scylladb.com/job/scylla-master/job/reproducers/job/longevity-10gb-3h-azure-test99/2/)

fix(sct_runner.py): rename update_at_scope to begin_update_at_scope

---

configurations/performance/latency-decorator-error-thresholds-steps-ent-tablets.yaml
configurations/performance/latency-decorator-error-thresholds-steps-ent-vnodes.yaml

As discussed with @fruch , we do not want to fail the test on P90 metrix. If P90 read/write is higher then 1 or 3 (as it is defined now), the test still should be passed

fix(performance): not validate P90 metrix

---

jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-regression/_display_name
jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-regression/perf-regression-predefined-throughput-steps-sanity-vnodes.jenkinsfile

Create new job based on java driver throughput short job. The daily execution of this tests will provide early detection of any performance degradation.
Task: https://github.com/scylladb/scylla-cluster-tests/issues/8840

test(performance): add sanity throughput test

---

sdcm/reporting/tooling_reporter.py
sdcm/scylla_bench_thread.py

The change implements scylla-bench and scylla-go-cql driver versions reporter.
Closes: https://github.com/scylladb/qa-tasks/issues/1877
The test run was executed against `scylla-bench:0.2.0 image`, which has the support for getting s-b and scylladb-gocql driver versions info. But due to https://github.com/scylladb/scylla-bench/issues/178 the retrieved version data misses the commit date and sha attributes ('unknown' placeholder is used now instead). Still the versions themselves are retrieved and properly set in argus.

improvement(scylla-bench): report scylla-bench version info in logs

---

jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml

Fix new_scylla_repo param for perf-regression-latency-650gb-during-rolling-upgrade-tablets from 'scylladb_enterprise' to 'scylladb-master' packages.

fix(trigger): new_scylla_repo param for upgrade with tablets

---

sdcm/sct_events/setup.py

Refs: https://github.com/scylladb/scylladb/issues/9862
The fix in https://github.com/scylladb/scylladb/pull/17910 will not be backported so the error should be ignored

fix(sct_event): ignore `auth_service - Unexpected exception` events

---

defaults/docker_config.yaml
sdcm/cluster.py

Ref: https://github.com/scylladb/scylla-cluster-tests/issues/10633

fix(docker): disable `print_kernel_callstack` for docker backend

---

add_new_dc_test.py
admission_control_overload_test.py
performance_regression_alternator_test.py
performance_regression_gradual_grow_throughput.py
performance_regression_operator_multi_tenant_test.py
performance_regression_row_level_repair_test.py
performance_regression_test.py
sdcm/utils/loader_utils.py

For the moment, if we define custom duration for the main stress load
then we get a timeout based on it for every stress command, even preload one.
When it is bigger than duration of the preload command it is ok,
but when it is smaller than we get false negative result.
So, fix it by specifying preload duration in functions designed
to call exactly this type of stress commands.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7327

fix(preload): use proper timeout for preload stress commands

---

data_dir/nemesis.yml
sdcm/nemesis.py
sdcm/nemesis_registry.py
test-cases/features/2mv-backpressure-4d.yaml
unit_tests/test_nemesis.py
unit_tests/test_nemesis_sisyphus.py

Currently, the Nemesis class has too many responsibilities, which causes problems, one of the problems is that it requires parameters to initialize and does a lot of logic in the `init` function and you need to provide those even if you need only part of the class. Problem manifests can be seen in `test_nemesis_sisyphus` which needs to mock Tester, Cluster and Node to filter nemesis, but none of methods used required any of this, we need to provide it because of the aforementioned problem.
Extract Nemesis discovery (i.e. Gathering all disrupt method and matching it with subclasses) to a separate class. While doing so, also reduce the nemesis discovery methods needed. Only one method for filtering is now present (`NemesisRegistry.get_disrupt_methods`) and input is a logical phrase. To …

improvement(nemesis): Rework nemesis discovery

---

sdcm/cluster.py

Today we are using package manager to search if Scylla is installed Since we have in the repo now both `scylla` and
`scylla-enterprise`(which is a virtual package) the current implemntaion will identify as enterprise and will fail with the following error
```
There is no pre-installed ScyllaDB on ...
```
Modifying the logic to check for scylla version instead

fix(is_scylla_installed): stop using package manager

---

sdcm/stress/latte_thread.py
sdcm/utils/remote_logger.py

If we run dozens of latte stress commands then we may hit the race
where we start reading HDR histogram files later then they get populated.
It will lead to the ignoring of line which happened to be written before the reding start time.
So, fix it by starting the HDR histograms file readers earlier
to avoid such a race even on slow SCT runner which have only 2 vCPUs.
- [scylla-staging/valerii/vp-perf-latency-regression-latte#25](https://argus.scylladb.com/tests/scylla-cluster-tests/5fee738b-fb8f-452e-add4-693e10f335e9)

fix(latte): avoid hdrh files reading and stress start race

---

sdcm/utils/gce_utils.py

Fix GCP filter in compute disks list command to collect correct disks for clean up
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10697

fix(gcp_cleanup): Fix gcp filter to collect correct disks for clean up

---

test-cases/performance/perf-regression-latency-650gb-elasticity.yaml
test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml

Disable health checker untile 2 commits won't be backported to the branch \branch-perf-v15':
https://github.com/scylladb/scylla-cluster-tests/pull/10680 
https://github.com/scylladb/scylla-cluster-tests/pull/10681
Now health validation fails and fail the nemesis tests

fix(performance): do not run cluster health validator

---

sdcm/provision/helpers/certificate.py
sdcm/provision/scylla_yaml/certificate_builder.py

This commit allows scylla-doctor to use correct certificates when
checking CQLsh liveliness.
Fixes #10490

fix(certificate_builder): Add ssl factory entrypoint for cqlshrc

---

docker/scylla-sct/centos/Dockerfile
sdcm/cluster.py
utils/scylla_doctor.py

Since we are now using RHEL UBI9 image for our docker backend, add
additional logic to support using `microdnf` inside
BaseNode.install_package
Fixes #10449

fix(sdcm/cluster.py): Use microdnf on rhel-like docker backend

---

defaults/docker_images/scylla-bench/values_scylla-bench.yaml

Main changes are following:
- added possibility of getting s-b and scylladb-gocql driver versions
- scylladb-gocql driver is reverted from v1.14.5 to v1.14.4
This particular test was an indication of problem with scylla-gocql driver v.1.14.5 recently - all test runs with that driver version were failing with
```
Stress command execution failed with: Command did not complete within 43800 seconds!
...
2025/03/24 13:55:34 gocql: unable to dial control conn 10.12.11.39:9042: dial tcp 10.12.11.39:9042: connect: connection refused
```
kind of error.
So this test indicates that the s-b v0.2.3 (that uses driver v1.14.4) is not having that issue.
The test run itself is marked as failed as it has an error event, which is due to known issue …

chore(deps): bump s-b version to 0.2.3

---

sdcm/cluster.py
sdcm/db_log_reader.py
unit_tests/test_cluster.py
unit_tests/test_decode_backtrace.py

Current logic for decoding backtrace was locking db log processing for duration of getting path to scylla debug file. Also it was downloading debug file once - possibly resulting in wrong backtrace decode in upgrade tests.
Moved logic for getting debug file info to decoding queue, so it's not locking db log processing loop. Also downloading debug file to monitor node (where decoding is done) to `/tmp/debug_<build_id>` and skipping download if it's already there.
closes: https://github.com/scylladb/qa-tasks/issues/57

improvement(decode_backtrace): improve logic

---

sdcm/sct_events/group_common_events.py
sdcm/sct_events/setup.py
unit_tests/test_events.py

PR scylladb/scylla-cluster-tests/#10386 filter some expected
raft error messages globally. But this change broke integration
unit test. Issue scylladb/scylla-cluster-tests#10676.
Move DB event Filter from `ignore_topology_change_coordinator_errors`
context manager to `enable_default_filters`. If the event will be
filtered globally, then no need to filter it with cm.
Fixes #10676
- [Executed JOB](https://argus.scylladb.com/tests/scylla-cluster-tests/3fcbd6a7-ab00-4273-a641-eef96526469e) - Job mostly passed, only coredump during decommission. will be investigated

fix(enable_default_filters): move DB event filter for raft error to default filters

---

docker/env/hydra.sh

mounting of tmpfs couldn't be done base on `uid` in podman same it is done in docker, and we need to split it into two distict argument for each.
with out is, podman just fails stright away, with unsupported feature
Fix: #10706

fix(hydra): fix podman support

---

vars/perfRegressionParallelPipeline.groovy

Perf pipeline does not create argus run. Added this step to support linking Argus to job builds and have them even if fails at early stage.

fix(perf-pipeline): add Argus step to pipeline

---

vars/runSendEmail.groovy

For the moment we always send emails after test runs.
Not all of them are needed and they just generate additional noise.
So, allow to avoid 'sending email' action by providing empty value for the recipient email parameter.
- [scylla-staging/valerii/vp-perf-latency-regression-latte#31](https://argus.scylladb.com/tests/scylla-cluster-tests/2d87a0a7-bd91-4f11-8b46-206f98325d5c)

improvement(send_email): don't fail having no recipients

---

.github/actions/run-validation/action.yml

by mistake the action is trying to post comments to the repo the PR is coming from, and not to the one it's targeting

fix(github-actions): generated code validation to post to correct repo

---

defaults/docker_images/scylla-bench/values_scylla-bench.yaml

Reverts scylladb/scylla-cluster-tests#10698
since seems like https://github.com/scylladb/scylla-bench/issues/183 is breaking validation of s-b, we revert it back

Revert "chore(deps): bump s-b version to 0.2.3"

---

microbenchmarking_test.py

'test_perf_simple_query' fails with 'Limit of total fields [1000] has been exceeded'. Attempts to fix it failed.
It was decided to skip update_test_with_errors function in this test

fix(microbanchmark): skip update_test_with_errors

---

sdcm/cluster.py
sdcm/coredump.py
unit_tests/test_data/test_coredump/systemd/exceptions_limit_not_reached_test_remoter.json
unit_tests/test_data/test_coredump/systemd/exceptions_limit_reached_test_remoter.json
unit_tests/test_data/test_coredump/systemd/fail_get_list_test_remoter.json
unit_tests/test_data/test_coredump/systemd/fail_upload_test_remoter.json
unit_tests/test_data/test_coredump/systemd/success_test_remoter.json
unit_tests/test_data/test_coredump/systemd/success_test_systemd_248_remoter.json

Creating coredump may take long (even 13 minutes). During that time test may fail and exit - this prevents from collecting such cores.
Fix by waiting for all services that create cores to complete before getting list of cores. It freezes main loop - so it won't end until it continues (and at next step, adding cores to process, which also prevent from ending coredump thread).
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10748

fix(coredump): wait for active coredumps completion

---

unit_tests/conftest.py

Container's -v paths are missing ':z' option, which might prevent container from starting, when SELinux is enabled.
Fixes #10826

fix(integration): make scylla container have shared volume mounts

---

sdcm/provision/common/configuration_script.py
sdcm/provision/common/utils.py

The change adds a step of updating repo cache before installing syslogng package (similarly to how repo cache is cleaned at the beginning of cluster.py::BaseNode.node_setup sequence).
Additionally, the step of installing epel-release repository in rhel-like distros is wrapped with retries, to make it more error-resilient in case of temporary network or mirror issues.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10815

fix(syslogng): update installation sequence for syslogng

---

defaults/severities.yaml
sdcm/sct_events/system.py
sdcm/utils/adaptive_timeouts/__init__.py
unit_tests/test_adaptive_timeouts.py

Reverts scylladb/scylla-cluster-tests#10786
all offline install test start failing like the following:
```
2025-05-07 05:18:47.757: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=b0de1e16-f971-46d9-8668-786409e8c29b, source=ArtifactsTest.SetUp()
exception=[Node artifacts-al2023-jenkins-db-node-5a7249f7-1 [108.129.146.246 | 10.4.1.5]] NodeSetupFailed: argument of type 'NoneType' is not iterable
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-amazon2023-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 3961, in node_startup
cl_inst.node_startup(_node, **setup_kwargs)
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-amazon2023-nonroot-test/scylla-cluster-tests/sdcm/cluster …
```

Revert "improvement(adaptive_timeout): lower timeout values when using tablets"

---

sdcm/utils/aws_builder.py
sdcm/utils/gce_builder.py

since we are running into multiple issue with builders running out of memory during artifact tests, we are taking this number down from 4 to 1, until we can figure out a better solution for artifact tests (it's own builders ?)

fix(builders): limit executors to one

---

docker/env/hydra.sh

SCT_* env variables were not parsed correctly for the `docker run --env` option, when value of the variable contained `=` characters. The issue was caused by the "greedy" regex that consumed all `=` characters up to the last one, misinterpreting the actual key-value separator.
This change adjusts the regex to correctly parse the values that include `=` characters.
The test failed due to some another existing issue, but parsing and setting custom value for the SCT_PREPARE_WRITE_CMD env var is working as expected now.
Previously setting custom s-b stress commands (or any env. vars with `=` characters in the value) would result in the error:
```
12:00:17  [Pipeline] { (Create Argus Test Run)
...
12:00:19  Going to run './sct.py  create-argus-test-run'...
12:00:19  invalid argument …
```

fix(hydra.sh): correctly parse SCT_* env var values containing `=`

---

sdcm/logcollector.py

The CommandLog.collect method in sdcm/logcollector.py always attempts to copy a log file from a remote node, even when no log was prepared by the command. The change adds a check to ensure that the file is prepared on a remote host, before attempting to copy it.
Refs: https://github.com/scylladb/scylla-cluster-tests/issues/10716
The test itself failed, but due to some other issue. The indication that this fix helps is that there is no such entries in the SCT log (also visible in jenkins build console output):
```
11:19:15  Error occured during collecting of db.crt on host: PR-provision-test-master-db-node-c19e5b97-1
11:19:15  'NoneType' object is not iterable
```
For instance the previous build [#51](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dimakr/job/pr-provision-t …

fix(logcollector): omit copying a non-exisintg remote log file

---

defaults/severities.yaml
sdcm/sct_events/system.py
sdcm/utils/adaptive_timeouts/__init__.py
sdcm/utils/features.py
unit_tests/test_adaptive_timeouts.py

The change adds ability to set low adaptive timeout values for selected operations (like decommission and add node), when using tablets, with added behaviour:
- publish error event when operation takes more than 1 hour
- publish critical event (which stops the test) when operation takes more than 3 hours
The change also updates `sdcm/utils/features.py::is_tablets_feature_enabled` helper, to have a fallback value for `experimental_features` attribute in scylla_yaml object in SCT, in case the attribute holds None value for some reason. This helps to avoid problems like:
```
if "tablets" in scylla_yaml.experimental_features:
TypeError: argument of type 'NoneType' is not iterable
```
that had us to revert the previous attempt to introduce the feature of hard adaptive timeouts.
This test …

improvement(adaptive_timeout): lower timeout values when using tablets

---

renovate.json

we never want to have all of the stress tools get updates in the same PRs each one has it's own review process, and be be reverted/backported on it's own flow.

fix(renovate): stop doing on big PR for all docker chanegs

---

sdcm/mgmt/helpers.py
sdcm/nemesis.py

Sometimes the DC name of a cluster under test and DC name of a backup cluster might be different. In such a case, the regular schema restore using the Manager fails since DC names mismatch.
To work around this issue, the schema might be restored "manually" (or out of Manager) applying cql statements taken from the schema.json file stored in a backup snapshot.

fix(nemesis): enhance disrupt_mgmt_restore to restore schema out of Manager

---

defaults/docker_images/gemini/values_gemini.yaml
jenkins-pipelines/master-triggers/sct_triggers/tier1-custom-time-trigger.xml
jenkins-pipelines/oss/tier1/gemini-1tb-10h.jenkinsfile
sdcm/gemini_thread.py
unit_tests/test_gemini_thread.py

feature(gemini): run latest gemini version as Tier 1 testing tool

---

sdcm/results_analyze/__init__.py

While checking regression, if test is not found in EC by test_id, inclear exception is received: 
```
'NoneType' object is not subscriptable. 
```
Send relevant error message "Cannot find test by id" in this case

fix(result analyze): handle missed doc in EC exception

---

renovate.json

* remove hydra labels from changes to stress docker images
* add label for testing integration tests when change tools

fix(renovate): improve labeling of PRs

---

sdcm/provision/common/configuration_script.py
sdcm/provision/common/utils.py

Update the syslogng installation sequence, replacing hardcoded sleep command arguments with values selected as per simple backoff pattern. This should improve resilience against temporary network or mirror issues.
```
-                    if yum install -y epel-release; then
+                    if [ $n -eq 3 ] && yum install -y epel-release; then
```
the timeout was executed successfully for those 2 iterations, with the expected backoff values:
```
< t:2025-05-13 19:26:28,309 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <34.23.101.75>: + rpm -q syslog-ng
< t:2025-05-13 19:26:28,309 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <34.23.101.75>: + for n in 1 2 3 4 5 6 7 8 9
< t:2025-05-13 19:26:28,309 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > …
```

fix(syslogng): use backoff timeout in retries in installation sequence

---

docs/bisecting-with-sct.md
performance_regression_test.py
sdcm/argus_results.py
sdcm/stress/base.py
sdcm/stress/latte_thread.py
sdcm/stress_thread.py
sdcm/utils/decorators.py
sdcm/utils/hdrhistogram.py
unit_tests/test_argus_results.py
unit_tests/test_data/latency_decorator_result.json

We plan to start running complex stress commands as part of performance
tests for such scenarios as `custom-d1/w1` and `custom-d1/w2`.
Those use dozens of latte/rune functions which use different HDR tags.
So, to be able to test performance, add latency steady state test.
Also, make this test support multiple workload types with multiple HDR tags.
- [scylla-staging/valerii/vp-perf-latency-regression-latte#36](https://argus.scylladb.com/tests/scylla-cluster-tests/b4fd90bf-5825-4b4e-b59e-db5d2b1f6aff)
- [scylla-staging/valerii/vp-scylla-master-perf-regression-latency-650gb-with-nemesis#17](https://argus.scylladb.com/tests/scylla-cluster-tests/baa1e3f7-0704-41a1-b81a-25949cf0690f)
- Add unit tests to cover my changes …

test(perf): add latency steady state test

---

sdcm/logcollector.py

The change adds an option to `tar -cf` command execution during log collection, to suppress `file changed` warnings.
This should help to avoid `tar: <NODE_NAME>: file changed as we read it` errors when creating archives during log collection (and we don't care about changes in logs/log directories after test is finished and log collection step is initiated).
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/10716
Couple of runs to ensure that logs are collected (and that it is OK on different distros):

fix(logcollector): ignore changes in log files when creating archive

---

docker/env/hydra.sh
sct.py
sdcm/utils/docker_remote.py
sdcm/utils/docker_utils.py
unit_tests/conftest.py
unit_tests/test_gemini_thread.py

docker base loader were using sudo for some operations, and we can
run sudo currently under podman, so we need to identify it's podman
we are using, and stop calling sudo
Tested with:
```
HYDRA_TOOL=podman bash -x ./docker/env/hydra.sh python -m pytest unit_tests/test_ycsb_thread.py::test_01_dynamodb_api
HYDRA_TOOL=podman bash -x ./docker/env/hydra.sh integration-tests --test test_ycsb_thread.py::test_01_dynamodb_api
```
Fix: https://github.com/scylladb/scylla-cluster-tests/issues/10766

fix(integration-test): stop using sudo under podman

---

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml

`longevity-large-partition-200k-pks-4days` test is not stable throughout 2024.1 LTS series of releases (and show similar behavior in newer LTS releases), regularly failing with scylla-bench queries timing out.
After reviewing the other existing test configs with scylla-bench workloads, particularly the ones with large partitions, it was noticed that those have retry number/interval values of the s-b command adjusted (compared to default `retry-number=10 retry-interval=80ms,1s` values).
This change also adjusts s-b command retry-number and retry-interval values for main load of this test (`stress_cmd` and `stress_read_cmd` parameters of the test config), which makes the test much more stable.
Refs: https://github.com/scylladb/scylla-cluster-tests/issues/9640
:green_circle: …

fix(large-partition-200k-test): adjust s-b retry number/interval values

---

configurations/performance/latte-perf-regression-latency-steady-state-custom-d1-workload1.yaml
jenkins-pipelines/performance/latte-perf-regression-latency-steady-state-custom-d1-workload1.jenkinsfile
vars/perfRegressionParallelPipeline.groovy

Recently was merged (https://github.com/scylladb/scylla-cluster-tests/pull/10817) new performance test for measuring latency during the steady state of a DB cluster.
So, add config for the first CI job using it - for `custom-d1/workload1` scenario.
- [scylla-staging/valerii/vp-perf-latency-regression-latte#39](https://argus.scylladb.com/tests/scylla-cluster-tests/4ae9e834-79e5-4e85-8299-f4c2eab050bd)

ci(perf): add latency steady state perf test using latte

---

sdcm/exceptions.py
upgrade_test.py

New feature limited voters enabled after all nodes upgrade to >=2025.2. After it was enabled, cluster can have not more than 5 raft voters if cluster size > 5 nodes. Adding new method to validate that feature is enabled on all nodes after upgrade
Also raft topology upgrade procedure was fixed. Previously, `wait_for` function failed with error:
```
< t:2025-05-05 10:46:36,064 f:wait.py         l:83   c:sdcm.wait            p:ERROR > last error: ValueError("could not convert string to float: 'Check feature enabled on node rolling-upgrade-artifacts--ubuntu-n-db-node-621570fc-0-2'")
< t:2025-05-05 10:46:36,067 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: is_features_enabled_on_node: timeout - 60 seconds - expired
< t:2025-05-05 10:46:36,067 f:wait.py         l:83 …
```

Check limited voters feature after upgrade

---

mgmt_cli_test.py

Closes https://github.com/scylladb/scylla-manager/issues/4276
Temporarily skipping this tests since there is no clear understanding on how Manager should behave in such situation.
See details here https://github.com/scylladb/scylla-manager/issues/4276
Should be revisited after [issue](https://github.com/scylladb/scylla-manager/issues/4275) resolution.

fix(manager): skip test_enospc_before_restore if tablets enabled

---

docs/configuration_options.md
sdcm/sct_config.py

scylla-cloud.yaml (which is used as a configuration for SCT longevities) is going to be extended https://github.com/scylladb/siren-tests/pull/1884/commits/5b2315b257fa9ada2c239942fe325bbbb7c3bd13 with new parameter `cloud_cluster_name`.
To keep up with the changes in siren-tests, the same param should be added to SCT to not fail on config validation step.

fix(siren): introduce cloud_cluster_name config parameter

---

configurations/longevity-100gb-2h-rackaware-validation.yaml
defaults/test_default.yaml
docs/configuration_options.md
jenkins-pipelines/oss/longevity/longevity-100gb-2h-rackaware.jenkinsfile
jenkins-pipelines/oss/longevity/longevity-multi-dc-rackaware-validation.jenkinsfile
sdcm/sct_config.py
sdcm/teardown_validators/__init__.py
sdcm/teardown_validators/rackaware.py
sdcm/tester.py
test-cases/longevity/longevity-multi-dc-rackaware-validation.yaml
unit_tests/test_config.py

This PR presents 2 changes:
1. add a new longevity test.
2. Add new validation for rack-aware policy.
Rack-aware validation is enabled under these conditions:
- A rack-aware policy is configured.
- A single loader is employed (due to Scylla rack metric limitation).
- The cluster is deployed across multiple availability zones.
The validation aims to confirm that no coordination traffic is directed to availability zones
where loaders are absent or not more then 10% of non-system traffic. These reads, such as those 
performed by nemeses or non-rack-aware test code, may be routed this way.
Task: https://github.com/scylladb/qa-tasks/issues/1819
```
< t:2025-05-14 15:14:42,607 f:rackaware.py    l:40   c:sdcm.teardown_validators.rackaware p:DEBUG > Nodes in a loader AZ: ['10.12.1.192', …
```

test(longevity): add test for rack-aware policy

---

unit_tests/test_base_version.py

The `TestBaseVersion.test_2025_1_release_centos` requires zstd support.
But it is absent in this branch and we get following error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'zstd'
```
So, skip this test to unblock CI.

fix(unit-test): skip the T`estBaseVersion.test_2025_1_release_centos` test

---

defaults/severities.yaml
sdcm/sct_events/database.py

To remove error events noise from 2025.2 sct jobs, set allocation memory error events as noise

fix(database_events): Set ALLOCATION_MEMERY AS WARNING

---

performance_regression_test.py
sdcm/nemesis.py
sdcm/tester.py
sdcm/utils/cql_utils.py
unit_tests/test_cql_utils.py

Fixed regex in `cql_quote_if_needed`.
| | Before| After|
|--------|--------|--------|
| `cql_quote_if_needed('v')` | `'"v"'`| `'v'`|
| `cql_quote_if_needed('C0')` | `'C0'`| `'"C0"'`|
| `cql_quote_if_needed('1x')` | `'"1x"'`| `'"1x"'`|
| `cql_quote_if_needed('x1')` | `'x1'`| `'x1'`|
| `cql_quote_if_needed('x1T')` | `'"x1T"'`| `'"x1T"'`|
Refactored and fixed `create_materialized_view` to no longer rely on manually quoting column names.
Also, in nemesis, the code only worked on the assumption that the column names required quoting but the primary keys did not.

Fix quoting when creating materialized views

---

sdcm/provision/scylla_yaml/scylla_yaml.py
unit_tests/test_data/test_scylla_yaml_builders/functional.result.json
unit_tests/test_data/test_scylla_yaml_builders/functional.yaml

Previously, the class did not allow it and it would fail on non existing field. Update testcase to verify this
* Use pydantic v2 validation
* This could be extracted to another PR or commit if necessary

fix(scylla_yaml): Allow usage of any option in append_scylla_yaml

---

configurations/compression/lz4_dict_compression.yaml
configurations/compression/zstd_dict_compression.yaml
jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-features/compression/_display_name
jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-features/compression/features-lz4-dict-compression.jenkinsfile
jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-features/compression/features-zstd-dict-compression.jenkinsfile

Create a new job based on PerformanceRegressionPredefinedStepsTest to verify that dict compression won't bring unwanted latency degradation.

test(performance): add lz4 and zstd dict compression test

---

sdcm/utils/raft/__init__.py

Nemesis decommission_streaming_err aborts decommission topology operation Depend on time when it happened and with tablets, New error message which is expected , could appear. Change severity for this message during decommission_streaming_err from error to warning
Job where error 
```
2025-05-30T16:28:33.681+00:00 longevity-10gb-3h-2025-2-db-node-3b34a1b4-0-1      !ERR | scylla[4451]:  [shard  0: gms] raft_topology - tablets draining failed with std::runtime_error (raft topology: exec_global_command(barrier) failed with seastar::rpc::closed_error (connection is closed)). Aborting the topology operation
````
was seen last time: https://argus.scylladb.com/tests/scylla-cluster-tests/3b34a1b4-0a9b-42c8-b803-3def8862fcef
After fix, the message should have warning severity
- Add New …

fix(change_severity_filter): Add new pattern to expected error message

---

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
test-cases/longevity/longevity-large-partition-8h.yaml
test-cases/longevity/longevity-lwt-500G-3d.yaml

Disabled due to https://github.com/scylladb/scylladb/issues/23743, which might take a while to fix.
Prevents unnecessary fails due to a known bug, the feature itself it flawed regardless and the tombstone_gc is not a critical check, nor a check that worked particularly well.

fix(treewide): Disable Tombstone GC for now

---

sdcm/nemesis.py

The time rebuild needs to finish is proportionate to the amount of data streamed.
For example, for 40GB @ 50MB/s it needs 800s.
Fixes errors like https://argus.scylladb.com/tests/scylla-cluster-tests/74aa35ba-9e36-4727-86ba-757897ea5ced
Where rebuild took 12 minutes, but had a timeout of 200 seconds

fix(nemesis): increase rebuild timeout

---

sdcm/tester.py
sdcm/utils/common.py

This reverts commit 4cd351747c8e1bda18be8345e5cb4e6c6f5defe8.
Seems like removing some of the atexit hooks, can cause python to segfault during shutdown, when there a callback coming in from c code of libev (within python-driver).
so we are taking this code part out, assuming we don't have any more libraries that leave any running threads behind (we have code that check that at the very end of test run)
Fixes: #9784

Revert "fix(teardown): clean all exit hooks"

---

sdcm/provision/helpers/cloud_init.py

since version `Cloud-init v. 25.1.2` cloud-init might fail with some transient errors from `cloud-init status --wait`
```
Failed due to systemd unit failure. Ensure all cloud-init services are enabled, and
check 'systemctl' or 'journalctl' for more information.
```
seems like trying more times, after the whole cloud-init process is done, it dissappers. so the funtion doing this call was decoreated with `@retrying`
Fixes: #11049

fix(cloud-init): retry on waiting for it to be done

---

sdcm/nemesis.py

this change add repair at the beggining of disrupt_repair_streaming_err to make this nemesis more safe and avoid c-s data validation errors ref: https://github.com/scylladb/scylladb/issues/21428
fixes: https://github.com/scylladb/scylladb/issues/21428
https://jenkins.scylladb.com/job/scylla-staging/job/eugene_test_folder/job/repair_repair/6/

fix(nemesis): make nemesis more safely by adding repair on all nodes

---

sdcm/sct_config.py

this backend currectly doesn't support it, since we don't generate the files need for it, as in other backends
Ref: https://github.com/scylladb/scylla-cluster-tests/pull/10641

fix(docker): don't use GossipingPropertyFileSnitch for docker

---

sdcm/fill_db_data.py

Now that all of our recent releases contains raft with consistent scehma management, this sleep isn't needed anymore.
Test: rolling upgrades.
Fixes: #9660

improvement(fill_db_data): Remove 30s sleep of waiting for schema agreement

---

sdcm/provision/azure/provisioner.py
sdcm/provision/azure/virtual_machine_provider.py
sdcm/provision/provisioner.py
sdcm/sct_provision/instances_provider.py
unit_tests/provisioner/fake_azure_service.py

When provisioning spot instances it may happen that instance is preempted during creation.
In that case it destroys all related resources like ip's, nic's etc. causing cached values to be invalid. 
Probably it also breaks fallback to `on_demand` due the same.
fix is by detecting preemption errors and recreate cache. 
Used retrying from SCT's utils to allow retry on provision error and skip when there's problem with preemption straight to fallback.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/5198

fix(azure): improved handling of spot instances provision

---

sdcm/nemesis.py

`shuffle_list_of_disruptions` were based on `shuffle` side effect, but was getting wrong list (after multiplication). Effectively making this method not working.
Fix by not relying on side effect, rather returning reshuffled list.

fix(nemesis): fix shuffle list of disruptions

---

sdcm/cluster.py
sdcm/stress_thread.py

by mistake the logic would assume that every multi-dc case has multiple racks, it was counting racks across all regions/datacenters.
this fix introduce a new helper function reshuffle the data into mapping per datacenter, and check if we have more then one rack in any of the datacenters

fix(rack_aware): activate only if more then one rack in a region

---

test-cases/longevity/longevity-cdc-100gb-8h-multi-dc-large-cluster.yaml
test-cases/longevity/longevity-multidc-parallel-network-schema-changes-12h.yaml
test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml

When updating configs recently we dropped `n_monitor_nodes` config from some multidc scenarios.
fix by adding it back.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11073

fix(test): fix missing monitor nodes

---

sdcm/sct_events/group_common_events.py

If a bootstraping node is stopped at just the right time during streaming it is possible to get a Transferring snapshot failure. This can happen in `disrupt_bootstrap_streaming_error.`
Example: 
https://argus.scylladb.com/tests/scylla-cluster-tests/7d3c6475-fa1b-444a-92d9-93f1bdececf6
```
2025-05-30T20:52:21.309+00:00 parallel-topology-schema-changes-mu-db-node-7d3c6475-1     !INFO | scylla[6080]:  [shard 0:main] raft_group_registry - marking Raft server 1b35e114-e421-46ad-a324-9567075e45a1 as alive for raft groups
2025-05-30T20:52:21.309+00:00 parallel-topology-schema-changes-mu-db-node-7d3c6475-1  !WARNING | scylla[6080]:  [shard 0:sl:d] querier - Read 491 live rows and 2238 tombstones for system_schema.columns <partition-range-scan> (-inf, +inf) (see tombstone_warn_threshold) …
```

improvement(nemesis): ignore raft transferring snapshot failure

---

performance_regression_gradual_grow_throughput.py
sdcm/tester.py

In the test_read performance test, we observed that even without any write operations, compactions were occurring. These compactions are a result of tablet splits and can happen several minutes after the wait_no_compactions function has finished.
To address this, we will now verify that no tablet splits or merges are active by checking the system.tablets table. The new condition for system idleness requires the resize_type column to be 'none' for all relevant tablets for a continuous period of three minutes.
Task: https://github.com/scylladb/scylla-cluster-tests/issues/10945
```
< t:2025-05-31 09:55:55,601 f:db_log_reader.py l:123  c:sdcm.db_log_reader   p:DEBUG > 2025-05-31T09:55:55.484+00:00 perf-regression-predefined-steps-ub-db-node-251efad6-1     !INFO | scylla[5166]:  [shard …
```

improvement(performance): wait for no tablets splits

---

data_dir/monitoring-dash-template.json
data_dir/scylla-dash-per-server-nemesis.master.json
sct.py
sdcm/cluster.py
sdcm/localhost.py
sdcm/provision/common/configuration_script.py
sdcm/provision/common/utils.py
sdcm/sct_config.py
sdcm/sct_events/base.py
sdcm/sct_provision/aws/cluster.py
sdcm/sct_provision/aws/user_data.py
sdcm/sct_provision/region_definition_builder.py
sdcm/sct_provision/user_data_objects/vector_dev.py
sdcm/test_config.py
sdcm/tester.py
sdcm/utils/vector_dev.py
test-cases/gemini/gemini-1tb-10h.yaml
test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml
test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml
test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml
test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml
test-cases/longevity/longevity-mv-si-4days.yaml
test-cases/longevity/longevity-twcs-48h.yaml
test_user_data_builders.py

Since we want to align with scylla-cloud, and modernize
our logging setup, we are adding the support of vector
this commmit handles the installtion phase on nodes
and the setup of the aggragator on the sct-runner (test side)
that would collect all logs and put them into files
later we'll work on optimizing it, compression, formatting of logs
of putting into centerilize logs service that can be searched
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/7010

feature(vector): add support for vector.dev logging

---

sdcm/cluster.py

there logic in this function to check first if nodes are operational but it doesn't cover the case of node not yet exists
this commit is using `next(iter(...), None)` to be able to gracefully handle situation we get back empty dict of rack information
Fixes: #11116

fix(node_rack): stop assuming node existing

---

sdcm/cluster.py

seems like this function is retrying for 5min, and then silently giving up the change is doubling the timeout, and making it raise exception when it's timing out
this was causing clusters to start in split-brain, since configuration of seed wasn't updated by the test, and was using the out-of-the-box configuration from SMI that points to itself.
Fixes: #11122

fix(wait_for_machine_image_configured): shouldn't ignore exceptions

---

sdcm/cluster.py

Oracle cluster should not use experimental features.
Remove them upon node setup.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11061

fix(oracle): disable experimental features

---

jenkins-pipelines/master-triggers/sct_triggers/tier1-custom-time-trigger.xml

Trigger rackaware tests in tier1 (master):
- longevity-100gb-2h-rackaware-test
- longevity-multi-dc-rackaware-validation-test
Task: https://github.com/scylladb/qa-tasks/issues/1819

test(rackaware): trigger in master tier1

---

sdcm/utils/aws_utils.py

Adding a node failed with 'The instance ID does not exist', but actually it exists. Instance reload failes with 'botocore.exceptions.ClientErrorInvalidInstanceID.NotFound'. To wait for the instance is ready, we need to retry on this client error.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11124

fix(aws utils): retry on botocore.exceptions.ClientError

---

sdcm/nemesis.py
sdcm/utils/decorators.py

If a skip occurs here, it will leave the cluster in an unbalanced topology, which will cause errors later in other disruptions.
Example failure: https://argus.scylladb.com/tests/scylla-cluster-tests/9e935144-b1de-415b-8d63-b05446ed9c52/nemesis 
```
disrupt_terminate_and_replace_node	longevity-cdc-100gb-4h-2024-2-db-node-9e935144-5	Skipped	2025-06-09 13:05:42	2025-06-09 13:13:38
Nemesis Information
Class: Sisyphus
Name: disrupt_terminate_and_replace_node
Status: Skipped
Skip reason: Capacity Issue
Target Information
Name: longevity-cdc-100gb-4h-2024-2-db-node-9e935144-5
Public IP: 54.160.183.183
Private IP: 10.12.11.25
State: terminated
Shards: 14
```
Then later repairs fail.
- Add unit tests to cover my changes …

fix(nemesis): fail test is capacity issue would break topology

---

sdcm/nemesis.py
sdcm/utils/common.py
unit_tests/test_common_get_db_tables.py
unit_tests/test_data/schema_with_internals.log

When there's a test with many tables (e.g. 5k tables test), add drop column nemesis stuck because fetching table info is done one by one.
Improvement by querying tables info with `DESC SCHEMA WITH INTERNALS` statement, which responds with all keyspaces and tables.
closes: https://github.com/scylladb/scylla-cluster-tests/issues/11062

improvement(add_drop_column): fetch tables data more efficiently

---

unit_tests/test_sdcm_mgmt_cli.py

test was wrongly assinging None or 0, into `mock.PropertyMock`
which in turns yield the following errors, in multiple tests:
```
>       if isinstance(value, PropertyMock):
E       TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

fix(test_sdcm_mgmt_cli): remove assignment to `mock.PropertyMock`

---

sct.py

cause when people are using it locally, it doesn't scan all regions but just the default regions in each cloud
people were leaving lot of AWS resources behind in some resources with them knowning about them.

fix(hydra): clean-resources/list-resources default to scan all regions

---

sdcm/provision/aws/capacity_reservation.py

When reusing cluster there's no point in use of cr's: anyway it's cancelled and we don't want to reserve it again.
Disable capacity reservation feature for reuse_cluster cases.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11180

fix(reuse_cluster): disable capacity reservation when reusing

---

configurations/performance/cassandra_stress_gradual_load_reduced_steps_number.yaml
configurations/performance/cassandra_stress_gradual_load_steps.yaml
configurations/performance/cassandra_stress_gradual_load_steps_enterprise.yaml
docs/configuration_options.md
docs/faq.md
performance_regression_gradual_grow_throughput.py
sdcm/sct_config.py
unit_tests/test_config.py

This commit present support per-step thread count configuration.
Allow specifying a different thread count for each throttle step in gradual load tests.
This change is intended for debugging purposes and helps to find the best test configuration
by enabling fine-grained control over thread allocation per step.
](https://argus.scylladb.com/tests/scylla-cluster-tests/8247c911-bc09-4aba-aaa4-f9fcb125b7cb)

improvement(performance): support different threads amount for every throttle step

---

sdcm/cluster_aws.py

When rack is removed, then `_create_or_find_instances` does not find existing nodes and tries to get instances. When using simulated racks feature, it may find ones and return them instead creating new.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11140

fix(add_node): fix add node in simulated racks

---

sdcm/utils/features.py

one more place we missed (implemented as the time we upgrade pydantic)

fix(pydantic): fix warning about `s/dict/model_dump/`

---

sdcm/cluster_aws.py
sdcm/ec2_client.py
sdcm/provision/aws/provisioner.py
sdcm/provision/aws/utils.py
unit_tests/test_aws_services.py

this change is introducing tags using `TagSpecifications` as part of calls to create instances
since callas are creating multiple instances,
the tag would be update to more accurate ones after creation of instances (for example `Name` or `NodeIndex`)
Closes: #11188

feature(aws): tag ec2 instances at creation

---

sdcm/nemesis.py
sdcm/utils/raft/common.py

Cherrypicked Yulia's commit from hackathon-mcp branch:
Adds structured activity logging to nemesis operations to improve step traceability.
- Injects an actions_log into NodeBootstrapAbortManager and Nemesis, initializing via get_action_logger.
- Wraps key bootstrap, abort, decommission, and repair steps in actions_log.info/error calls and action_scope context managers.

improvement(nemeses): add activity log to nemese

---

artifacts_test.py
sdcm/cluster_docker.py
sdcm/remote/docker_cmd_runner.py
sdcm/utils/docker_utils.py
unit_tests/test_docker_cmd_runner.py

The change drops rebuilding scylladb image as `scylla-sct` image. Instead, scylladb docker image is used as is for the docker backend.
For that purpose the new DockerCmdRunner abstraction was introduced, to allow operating docker based nodes directly using docker API (instead of sshing
into container).
Additionally, artifacts_test was updated to skip subtests/operations for the services, which are no longer supported by scylladb docker image (or are about
to be dropped) - node-exporter and scylla-hosekeeping .
The test was executed against the custom built image (built in the context of work in https://github.com/scylladb/scylladb/pull/22883), that has supervisor dropped
```
❯ SCT_CONFIG_FILES='["test-cases/PR-provision-test-docker.yaml"]' SCT_ENABLE_ARGUS=false …
```

improvement(images): drop supervisor from scylla SCT image

---

defaults/manager_restore_benchmark_snapshots.yaml
mgmt_cli_test.py
sdcm/argus_results.py
sdcm/cluster.py
sdcm/utils/aws_utils.py

The PR introduces Manager 1-1 restore test for Cloud clusters.
Together with that, it enhances the existing snapshots preparation and regular L&S restore tests to support Cloud clusters.

[Manager] 1-1 restore for Cloud clusters

---

unit_tests/test_base_version.py
utils/get_supported_scylla_base_versions.py

from now on, we should be picking the OSS version as bases versions all of the code path and unittest for that are removed.
one can still manually select a specific branh to upgrade from if needed, but we won't be test that by default anymore.

feature(get_supported_scylla_base_versions): stop picking OSS version

---

sdcm/fill_db_data.py

The truncate operation may take several minutes.
Increase the timeout of the truncate itself to prevent the session from retrying the truncate (this is mostly a cosmetic change, but will result in less errors in log).
Increase the timeout of the execute to match that of the truncat to ensure the operation has enough time to finish.
closes: #10677
closes: #4866
See https://github.com/scylladb/scylla-cluster-tests/issues/10677#issuecomment-2949279576 for an example failure.
The same timeout is also set in nemesis, ref: https://github.com/scylladb/scylla-cluster-tests/pull/5879

fix(upgrade_test): increase timeout for truncates

---

.github/workflows/build-docker-image.yaml

by mistke it wasn't enforced on all cases, and we might run and build image, even when wasn't intended

fix(build-docker-image.yaml): should only work if PR is labeled

---

performance_regression_test.py

One of the merged PRs (https://github.com/scylladb/scylla-cluster-tests/pull/10817) broke some of rarely used perf methods
by not complete update of the `workload` var usage.
The `workload` was `enum` and then was transformed into `str`.
But 2 places in the code continued expecting it to be `enum`s.
So, fix it to be expected as `str`.

fix(perf): use `workload` var properly

---

sdcm/utils/distro.py

`Mind22` distro uses `Ubuntu24` as a basis and doesn't require any other
changes except the distro name check.

improvement(distro): allow running on Mint 22 distro

---

sct.py

seems like this was broken for long long time now since we refactored out libcloud.
with this change we can usd hydra list-resources to list EKS cluster

fix(list-resources): use the correct metadata implementation

---

sdcm/cluster_aws.py
sdcm/cluster_azure.py
sdcm/cluster_docker.py
sdcm/cluster_gce.py
sdcm/cluster_k8s/eks.py
sdcm/cluster_k8s/gke.py
sdcm/nemesis.py
sdcm/tester.py
sdcm/utils/nemesis_utils/__init__.py
sdcm/utils/nemesis_utils/node_allocator.py
unit_tests/nemesis/fake_cluster.py
unit_tests/nemesis/test_node_allocator.py
unit_tests/nemesis/test_sisyphus.py

Previously we were adding locked sections in different parts of nemesis.py, to prevent parallel nemeses from selecting the same target node. However, managing these locks across multiple locations became increasingly difficult, but race condition issue appears periodically in new places.
This change introduces a NemesisNodeAllocator entity, which centralizes the logic of selecting and tracking nodes used in nemeses execution. It helpts to ensure synchronization between parallel nemeses.
Some SCT log entries from the new node_allocator module:
```
❯ egrep -i 'node_allocator' sct-f3405cf3.log
< t:2025-06-21 20:16:23,417 f:node_allocator.py l:126  c:sdcm.utils.nemesis_utils.node_allocator p:INFO  > StartStopMajorCompaction-c86c920b: selected target node …
```

feature(nemesis): introduce nemesis node allocator

---

vars/perfRegressionParallelPipeline.groovy

using the jenkins `throttle-concurrents` plugin, we gonna limit the performance test, to not run more then one test per region.
hopefully it would help in both having enough capacity for tests, and improve the situation with test falling into the same hosts as other tests, and interfering with results.
Ref: https://plugins.jenkins.io/throttle-concurrents/

feature(perf-test): throttle/limit performance test per region

---

sdcm/nemesis.py

this commit changes mngmt restore nemesis to  clear its keyspaces
when it's done
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/10201
https://jenkins.scylladb.com/job/scylla-staging/job/eugene_test_folder/job/snapshots/

fix(nemesis): clearing keyspaces after mngmt restore operations

---

test-cases/longevity/longevity-parallel-schema-changes-12h.yaml

They were wrongly decreased in d2c7558. Requested by @temichus.
(Rest of the changes in that commit should be ok :D)

fix(longevity): Increase back node size in longevity-parallel-schema-changes-12h.yaml

---

artifacts_test.py
sdcm/cluster_docker.py
sdcm/remote/docker_cmd_runner.py
sdcm/utils/docker_utils.py
unit_tests/test_docker_cmd_runner.py

Re-applying the PR which was previously reverted due to regression for regular, non-docker, scenario (was visible on regular pr-provision-test):
The change drops rebuilding scylladb image as `scylla-sct` image. Instead, scylladb docker image is used as is for the docker backend. For that purpose the new DockerCmdRunner abstraction was introduced, to allow operating docker based nodes directly using docker API (instead of sshing into container)
Additionally, artifacts_test was updated to skip subtests/operations for the services, which are no longer supported by scylladb docker image (or are about to be dropped) - node-exporter and scylla-hosekeeping . …

improvement(images): do not rebuild scylladb image

---

sdcm/sct_events/setup.py

Refs: scylladb/scylladb#9862
The fix in scylladb/scylladb#17910 will not be backported so the error should be ignored
The error can happen on both table and keyspace, so the regex needs to handle both.
This follows up https://github.com/scylladb/scylla-cluster-tests/pull/10678
See https://argus.scylladb.com/tests/scylla-cluster-tests/a7949092-d50c-4c5f-a592-9170dfb6abfb/events

fix(sct_event): improve ignoring `auth_service - Unexpected exception` events

---

sdcm/utils/docker_remote.py

Previously, the `docker_hub_login` method in `RemoteDocker.pull_image` was incorrectly using `node.is_docker` as a property. Since `is_docker` is implemented as a method, accessing it without parentheses always evaluated to True value.
This change ensures `node.is_docker()` is properly called, so the `docker_hub_login` behaves as intended.

fix(pull_image): correctly check if node is a docker container

---

jenkins-pipelines/oss/sct_triggers/tier1-aws-custom-time-trigger.xml
jenkins-pipelines/oss/sct_triggers/tier1-gce-custom-time-trigger.xml
vars/jepsenPipeline.groovy

Changes:
- Move the `jepsen-all-test` CI job from the AWS to GCE trigger file because it is GCE-only CI job.
- Make the `jepsen-all-test` trigger respect the `gce_image_db` trigger parameter.
- Make the `longevity-multidc-schema-topology-changes-12h-test` CI job use hardcoded `latest` value for release branch.
It is needed because reusing the `scylla_version` or `ami_id` params
we will get only single-dc values, which are not applicable here.
- Remove duplication of the `longevity-multidc-schema-topology-changes-12h-test` config from the
single-dc config block.
-  Add `gce_image_db` pipeline parameter support to the `jepsen` pipeline.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/11415
- Add unit …

fix(ci-triggers): Fix tier1 oss CI triggers

---

sdcm/provision/scylla_yaml/certificate_builder.py
sdcm/tester.py

This change moves updating cqshrc config to ClusterTester.setUp, to have it executed only once, before creation of cluster nodes.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11409

fix(cqlshrc): update cqlshrc only once

---

docs/configuration_options.md
sdcm/nemesis.py
sdcm/sct_config.py
sdcm/utils/cluster_tools.py
sdcm/utils/decorators.py
unit_tests/test_utils_cluster_tools.py

since just skipping to next nemesis on those cases can cause situation we are continuing a test in a very unbalanced way, we should stop the test completely.
before we introduced a decorator that can generate a critcal event to stop the test, and applied it only in one nemesis.
this change is introducing a rack balance check, and if cluster isn't balanced after the capacitry error issue, it would raise critical event and not skip the nemesis
Fixes: #11350

feature(skip_on_capacity_issues): check cluster layout before skipping

---

sct.py
sdcm/logcollector.py
sdcm/utils/common.py

This commit adds a new flag corresponding to whether or not to make file
uploaded to S3 public (default: True). It also updates usage to make log
files private and keep the screenshots public. In addition, the `upload`
command was updated to include an option to set file as public (default:
True).
Task: scylladb/qa-tasks#1874

improvement(sdcm/utils/common.py): Add `public` flag to upload_file

---

defaults/cloud_config.yaml
docs/configuration_options.md
sdcm/cloud_api_client.py
sdcm/cluster.py
sdcm/cluster_cloud.py
sdcm/keystore.py
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/cloud_api_utils.py
sdcm/utils/resources_cleanup.py

This change is a PoC of introducing a new backend for SCT, to be able to provision a cluster in Scylla Cloud with SCT only (i.e. without the need to use siren-tests framework).
The list of implemented items:
- **Scylla cloud API client for SCT**
It covers all the public APIs, as defined in https://cloud.docs.scylladb.com/stable/api.html, but for now only part of them have been used/tested in the scope of this PoC
- **Scylla cloud backend**
It implements the existing approach to defining backends in SCT - defines abstractions for Cloud node, Cloud cluster, Scylla cloud cluster.
Due to the managed nature of cloud backend and inability to access public cloud cluster nodes by SSH, the node_setup, node_init sequences are mainly skipped. Once we have a way to access cloud cluster nodes we can …

feature(cloud_backend): add a new backend for Scylla cloud

---

defaults/docker_images/gemini/values_gemini.yaml
sdcm/gemini_thread.py
test-cases/gemini/gemini-1tb-10h.yaml
test-cases/gemini/gemini-3h-cdc-postimage-write.yaml
test-cases/gemini/gemini-3h-cdc-preimage-write.yaml
test-cases/gemini/gemini-3h-cdc-write.yaml
test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-3h-with-nemesis.yaml
test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
test-cases/gemini/gemini-8h-large-num-columns.yaml
test-cases/gemini/gemini-basic-3h-ics.yaml
test-cases/gemini/gemini-basic-3h.yaml
unit_tests/test_gemini_thread.py

- Enable Statement Logger on all workloads statements are logged now in Oracle Cluster, this removes the problem, performance bottlenck of logging to file and gives us better tracability
- Removing --fail-fast flag, this flag still exists in gemini but is not used for anything, every workload should migrate to --max-errors-to-store flags, which gives better control if and how gemini will fail
- :green_circle: https://argus.scylladb.com/tests/scylla-cluster-tests/e1ea4694-6754-4e1f-9bde-48e987e03e2d (3 Hour Run with Nemesis)
- :green_circle: https://argus.scylladb.com/tests/scylla-cluster-tests/27e79388-87d6-409c-9f07-588eda98b19f (10 Hour Run with Nemesis)
- :green_circle: https://argus.scylladb.com/tests/scylla-cluster-tests/1d07f19a-495c-49e0-8b69-bb2ed0801490 (10 Hour Run with Nemesis …

feature(gemini): use new gemini version 2.0

---

vars/perfRegressionParallelPipelinebyRegion.groovy

Update performance tests trigger groovy module:
- Build downstream jobs asynchronously for improved performance
- Set default value of new_scylla_repo parameter to master:latest
- Change use_job_throttling parameter type from string to boolean

improvement(trigger): few changes and fixes in performance tests trigger module

---

vars/perfRegressionParallelPipelinebyRegion.groovy

Last commit broke the trigger and caused to error: expecting '}', found ''

fix(trigger): missed '{'

---

vars/perfRegressionParallelPipelinebyRegion.groovy

Fix sub-tests names for nemesis/rolling upgrade/elasticity jobs

fix(trigger): sub-tests names

---

vars/perfRegressionParallelPipelinebyRegion.groovy

1. Scylla version in timer is defined with quotes mistakenly. In prevent to trigger the jobs as it can't find master version. Remove the quotes.
2. Define builder

fix(trigger): remove quotes in timer

---

sdcm/utils/remote_logger.py

when `log_trasport: ssh` is used, we are using threds based on `SSHLoggerBase` which recently changed to using thread and not processes.
since threads aren't killed directly, we need to stop the communication at the host end.
this change add a way to capture pid of the command, and use it for killing it on the host as needed.
Fixes: #11496

fix(artifact): prevent teardown race condition

---

sdcm/nemesis.py

minor change that asserts if no user table been found fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11217

fix(nemesis): assertion added for case when no user table found

---

sct.py

Since we don't handle errors that happen during provisioning via the
Event system Argus doesn't really know what happened in case of capacity
issues during provisioning stage. This commit addresses this by setting
Argus status as "TEST ERROR" in case of any error during the
provisioning.
Fixes #11204

improvement(provision_resources): Handle provision errors for Argus

---

docs/configuration_options.md
sct.py
sdcm/sct_runner.py
unit_tests/test_hydra_sh.py
unit_tests/test_sct_clean_commands.py
unit_tests/test_sct_runner.py

Add an option of cleaning SCT runners to clean-resources command. This should improve UX of the chore of test resources cleanup, epsecially peformed locally from dev machine.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/11265
- delete on aws by user:
```
❯ SCT_ENABLE_ARGUS=false ./sct.py create-runner-instance -c aws -r eu-west-1 -z a --instance-type 't3.micro' --root-disk-size-gb 80 -d 30 -t 11223344-1122-1122-2211-665544332211
...
Successfully connected the SCT Runner. Public IP: 3.252.201.231
❯ hydra list-resources --user dmytro.kruglov | grep 11223344
| sct-runner-1.11-instance-11223344 | eu-west-1a | running | 11223344-1122-1122-2211-665544332211 | dmytro.kruglov | Sun Jul 27 17:08:18 2025 |
...
❯ ./sct.py clean-resources --clean-runners --user dmytro.kruglov
...
1 …
```

improvement(sct.py): add SCT-runners cleanup support to clean-resources

---

sdcm/stress/latte_thread.py

Latte docker container was using docker network and `secure computing mode` linux feature.
Both are redundant and decrease overall performance.
We need to have as better perf as possible for performance tests.
Ref: https://github.com/scylladb/qa-tasks/issues/1659
- [scylla-staging/valerii/vp-latte-perf-regression-predefined-throughput-steps-rust-vnodes#2](https://argus.scylladb.com/tests/scylla-cluster-tests/e1972d94-2182-4bf8-b4af-b157d2ce272a)
- [scylla-staging/valerii/vp-latte-perf-regression-predefined-throughput-steps-rust-vnodes#3](https://argus.scylladb.com/tests/scylla-cluster-tests/7d3e44aa-9736-4492-ba00-d21fa7993643)
- [scylla-staging/valerii/vp-latte-perf-regression-predefined-throughput-steps-rust-vnodes#4](https://argus.scylladb.com/tests/scylla-cluster-tests/1696dd29-ad77-42 …

improvement(latte): use host network and disable secure computing mode

---

jenkins-pipelines/master-triggers/sct_triggers/tier1-custom-time-trigger.xml

Replace java driver tests using cassandra-stress with new scylla-bench test in tier1
Task: https://github.com/scylladb/qa-tasks/issues/1915

test(trigger): run scylla-bench with rackaware validation in tier1

---

sdcm/provision/aws/dedicated_host.py

One of the PRs (https://github.com/scylladb/scylla-cluster-tests/pull/9122) that was merged some time ago
added one more resource cleanup function
which was removing the `NodeType` key from the `tags_dict` shared dict object.
And the problem is that after this function SCT uses the same dict object in other cleanup functions such as deletion of AWS KMS key aliases.
Those functions directly depend on the presence of the `NodeType` dict key-value pair.
It's absence led to the skipping of attempts to cleanup resources.
So, fix the `release_by_tags` method of the `SCTDedicatedHosts` class
by not updating the shared dict object and make it use a local copy.
- https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-11576/
- Add New configuration option and document …

fix(cleanup): fix cleanup of AWS KMS key aliases

---

sct.py
sdcm/utils/common.py
vars/perfRegressionParallelPipelinebyRegion.groovy

If scylla_version is 'master:latest', an AMI name must be provided. 
Subtests currently run sequentially, not in parallel. This can lead to inconsistencies where initial subtests use an older AMI while subsequent ones use a newly created AMI (if an update occurs during the first subtest's execution). To ensure all subtests run with the same version, we should send an AMI ID and execute all subtests with that specific version.
Correct Scylla version was started up

improvement(trigger): send ami name instead of scylla_version for master

---

jenkins-pipelines/master-triggers/sct_triggers/tier1-custom-time-trigger.xml

Based on discussion in https://github.com/scylladb/scylla-dtest/issues/6091. We removed cassandra harry from dtest, so lets at least run it regularly in SCT. It is very stable test, should not cause any issues. My team will be responsible for investigation.

improvement(tier1-triggers): Add longevity-harry-2h to weekly runs

---

defaults/test_default.yaml
docs/configuration_options.md
jenkins-pipelines/manager/debian11-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
jenkins-pipelines/manager/ubuntu24-manager-upgrade.jenkinsfile

This PR updates the Scylla Manager version from 3.5.0 to 3.5.1 across the codebase to support the latest Manager release. The change involves updating version references in Jenkins pipeline configurations, documentation, and default configuration files.
- Updates manager version references from 3.5.0 to 3.5.1
- Updates Ubuntu 20 pipeline to use Manager 3.5.0 instead of 3.4.1 for upgrade testing
- Updates Debian 11 pipeline to use Manager 3.4.2 instead of 3.4 for upgrade testing
Not required

Support the latest Manager release 3.5.1

---

sdcm/nemesis.py

Before SCT was dependent on the (https://github.com/scylladb/scylla-enterprise/issues/5461) GH issue which was tracking the situation of not supported MVs with tablets.
And it was closed with assumption that the support will appear in `2025.3` But, it didn't land there.
So, update the skip condition to make it be skipped for any Scylla that is `2025.3` or older and uses tablets.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/11611

fix(nemesis): skip the `remove_mv` nemesis for Scylla versions without support

---

sdcm/tester.py

If tablets are not configurated, it's not needed to wait for no tablets splits. it may cause to test failure.
Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11554

fix(tablets): not wait for no tablets splits

---

vars/perfRegressionParallelPipeline.groovy

Performance test should not be run with 'spot' instances. Change the default instance provision type to 'on_demand'

fix(performance): run all tests with 'on_demand'

---

sdcm/cluster_aws.py
sdcm/utils/common.py

Sometimes when test starts to fast, some instances might not be in running state before sct lists them. This causes that only part of instances are detected and test fails at later stages.
fix by waiting for pending instances to become running and returning them from `list_instances_aws` function.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11555

fix(provision): wait for pending instances

---

sdcm/nemesis.py

A followup of https://github.com/scylladb/scylla-cluster-tests/pull/11612#issuecomment-3154667277.
Before SCT was dependent on the [1] GH issue which was tracking the situation of not supported MVs with tablets.
And it was closed with assumption that the support will appear in 2025.3 But, it didn't land there.
So, update the skip condition to make it be skipped for any Scylla that is 2025.3 or older and uses tablets.
[1] https://github.com/scylladb/scylla-enterprise/issues/5461
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/11611

fix(nemesis): skip CreateIndexNemesis on unsupported Scylla versions

---

test-cases/upgrades/rolling-upgrade.yaml
upgrade_test.py

In 2.0 gemini, more thing were added to `gemini_cql_requests` metrics, mainly the `method` which contained what statement type is executed. This broke the upgrade tests, as in upgrade test the first value returned from prometheus is used to check `> 0`, but the prometheus ordered the metric labels in alphabetical order, making the metric currently checked to be *almost* always zero, thus failing the check and killing gemini thinking it's not running (but it actually is).
Now fetching the `InsertStatement` label makes sure that this check will succeed (maybe not on the first try as it is not yet inserting, but after a couple of try will succeed).
Closing #11534 
- :green_circle: https://argus.scylladb.com/tests/scylla-cluster-tests/bb8ff3e6-cc34-4d4a-ad2c-94e31fb6896b (Previous check of …

fix(gemini): metrics not beining read properly after 2.0

---

sdcm/nemesis.py

in `disrupt_disable_binary_gossip_execute_major_compaction` we are doing `nodetool status` while gossip was disabled
since scylladb/scylladb@e364995, this status can fail, cause the gossip is disabled
it's agree we can ignore the error of that command, while gossip is down.
Ref: scylladb/scylladb#24670

fix(nemesis): ignore error from status while gossip is disabled

---

sdcm/utils/azure_utils.py
sdcm/utils/cloud_monitor/resources/instances.py
sdcm/utils/cloud_monitor/resources/static_ips.py
unit_tests/test_azure_rate_limiting_fix.py

The cloud usage report job fails completely when Azure Resource Graph API returns rate limiting errors (`RateLimiting - Client application has been throttled`), causing the entire report to fail instead of continuing with other cloud providers.
From the July 03 failure:
```
azure.core.exceptions.HttpResponseError: (RateLimiting) Please provide below info when asking for support: timestamp = 2025-07-03T06:41:26.4931393Z, correlationId = 1091dbe2-d4d5-4dde-8108-dfd75850b71e.
Code: RateLimiting
Message: Please provide below info when asking for support: timestamp = 2025-07-03T06:41:26.4931393Z, correlationId = 1091dbe2-d4d5-4dde-8108-dfd75850b71e.
Exception Details:	(RateLimiting) Client application has been throttled and should not attempt to repeat the request until an amount of time has …
```

Fix Azure rate limiting in cloud usage report with exponential backoff and error isolation

---

unit_tests/conftest.py
unit_tests/test_tester.py

By using standardized events system as we do in other tests, we get rid of scenarios where `test_tester` fails due to previous uncleaned tests.
Also small improvements to `events` fixture. Can extract into separate PR if needed

fix(test_tester): Use standardized Events system 

---

sdcm/provision/scylla_yaml/cluster_builder.py
sdcm/stress/latte_thread.py
sdcm/test_config.py
sdcm/tester.py
unit_tests/test_scylla_yaml_builders.py
unit_tests/test_wait.py

Extract fixes from uncovered by #11627 into separate PR.
* Regex without specifying Raw string throws SyntaxWarning
* TestConfig is used in Integration tests and executed as test
* ScyllaYaml and its tests sometimes used bad types
* improve `test_scylla_yaml_builders.py` paralelized runs name
* First argument is used as a name in `@parameterized`
* Instead of full path to file, now it shows only config name

fix(integration_tests): Fix warnings in integration tests

---

data_dir/ssl_conf/client/cqlshrc

when we use cqlsh from SCT we use specific command line timeout options, when scylla-doctor is using cqlsh it wasn't and getting into some cases that it times out on connection to the cluster.
this change is adding the same default we have within SCT, into cqlshrc file, so also the scylla-doctor would be using the same values

fix(doctor): define default timeouts in cqlshrc

---

sdcm/provision/azure/virtual_machine_provider.py
unit_tests/test_azure_vm_provider_reboot.py

When walinuxagent is not installed or disabled on Azure VMs (e.g., when using non-official Scylla images), the current reboot implementation fails. This PR adds a fallback mechanism to Azure SDK's `begin_restart` method.
PR #6628 introduced dependency on walinuxagent for VM reboots to achieve immediate reboots via `run_command`, but didn't account for scenarios where walinuxagent is unavailable:
- Custom/non-official images may not have walinuxagent installed
- walinuxagent may be disabled without ability to enable it
- Network issues may prevent walinuxagent communication
Added graceful fallback to Azure SDK when walinuxagent fails:
```python
try:
flags = "-ff" if hard else "-f"
self.run_command(name, f"reboot {flags}")
LOGGER.debug("Successfully triggered reboot via walinuxagent for …
```

[Azure] Add fallback to SDK for VM reboot when walinuxagent fails

---

sdcm/utils/perftune_validator.py
sdcm/utils/validators/iotune.py

since now there more logic as part of `scylla_io_setup` which is need to get correct results.
also stops using a temp file for the output, with the assumption this is the last phase of the test, and we don't
restart scylla after this point.
Fixes: #11605

fix(artifacts): use `scylla_io_setup` and not iotune directly

---

.github/workflows/build-docker-image.yaml
.github/workflows/check-generated-code-updates.yaml

Ref: https://www.synacktiv.com/publications/github-actions-exploitation-dependabot

fix(github-actions): repalce `github.actor` with `github.event.pull_request.user.login`

---

sdcm/cluster.py
sdcm/nemesis.py

Add support of rackaware for python driver

test(rackaware): add support rackaware for python driver

---

sdcm/cluster.py

Scylla restart timings are stored in Argus. This looks redundant as this process usually is short. Also we don't do it for stopping and starting scylla.
Remove storing in Argus restart_scylla metrics.

refactor(restart_scylla): remove storing metrics in argus

---

sdcm/provision/azure/virtual_network_provider.py

It happens Azure dns servers don't respond properly and fail some nemesis (e.g. `disrupt_load_and_stream` when downloading files from s3).
Fix by providing stable dns servers (google and cloudflare) in network configuration setting.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/11724

fix(azure): set stable dns servers

---

Jenkinsfile
defaults/test_default.yaml
docker/scylla-sct/entry.sh
docs/configuration_options.md
sdcm/cluster_docker.py
sdcm/provision/scylla_yaml/scylla_yaml.py
sdcm/sct_config.py
sdcm/tester.py
sdcm/utils/vector_store_client.py
unit_tests/conftest.py
unit_tests/test_scylla_yaml.py
unit_tests/test_vector_store.py

This change introduces support of vector-store service deployment on docker backend.
A few notes to take into account:
- the feature is not yet merged into scylladb master, so the custom dev build of scylla with support of VS was used for implementation (and its testing).
Once VS is merged we would need to revise this implementation.
- vectore-store service image is not yet published, so the image is built by SCT when VectorStoreSetDocker is initialized.
This is a temporary solution. Once the the image is published we will switch to consuming the released image.
Closes: https://github.com/scylladb/scylla-cluster-tests/issues/11483
- Update the …

feature(vectore-store): add support of VS for docker backend

---

unit_tests/test_utils_common.py

* Solves issue with load_and_stream.log being modified after the test

improvement(test_utils_common): Use temporary system_log

---

sdcm/utils/remote_logger.py

SSHLooger instances use `tail -f` to fetch content of the file over ssh. This might occasionally skip part of the log - if the remote command producing the log starts quickly and outputs a lot of log instanstly running `tail -f` might skip beggining of the log file (as `tail -f` will emit only N last lines and then follow file changes). We add `-c +0` parameter, which tells `tail -f` to start following file from byte 0 counting from beginning.
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/evgeniy/job/perf-regression-alternator/job/scylla-master-perf-regression-alternator-latency-test/336/ (and plenty before) runs with this patch.

Fix skipping part of remote log output

---

defaults/manager_versions.yaml
defaults/test_default.yaml
docs/configuration_options.md
unit_tests/test_sdcm_mgmt_common.py

SM DB version will be updated from 2024.2 to 2025.2 in Cloud. 
So, to keep up with setup in Cloud, the version is updated here as well.

fix(manager): up SM DB version to 2025.2

---

sdcm/cluster.py

This commit ensures that the DC information is correctly parsed and collected, even when it appears after other data like schema, IP, or status. Previously, the parser would miss this information due to its location, but this change fixes that issue.

fix(health checker): collect DC from gossip info

---

artifacts_test.py
sdcm/cluster.py
utils/scylla_doctor.py

This PR changes some configuration options and adjusts PATH settings on nonroot 
installations of artifacts tests, allowing scylla-doctor to run here successfuly.
Some scylla-doctor collectors are disabled because either they require root privileges,
they assume system wide installation, or they depends on those that do. 
- **fix(artifacts_test.py): Remove offline non-root scylla_doctor skip**
- **improvement(sdcm/cluster.py): Add offline install to PATH**
- **improvement(scylla_doctor/nonroot): Disable non-working collectors**
- **improvement(artifacts_test): Run scylla-doctor last**
Closes #10540
Fixes scylladb/qa-tasks#1683
- Update the Readme/doc …

Support scylla-doctor on offline non-root tests

---

test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml

Disable parallel node operations in performance nemesis tests.

fix(performance): disable parallel node operations

---

jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis-rbno-disabled.jenkinsfile

`latency-decorator-error-thresholds-nemesis-ent-vnodes.yaml` is not applied to RBNO disabled test. As result the results validation is missed

fix(performance): add thresholds to RBNO disabled test

---

test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
test-cases/longevity/longevity-large-partition-8h.yaml
test-cases/longevity/longevity-lwt-500G-3d.yaml

This reverts commit 44b0661dca371886052c28f3e89a7b4b1ea097a1.
The SCT memory issue was fixed in https://github.com/scylladb/scylla-cluster-tests/pull/11471. 
Refs: https://github.com/scylladb/scylladb/issues/23743

Revert "fix(treewide): Disable Tombstone GC for now"

---

upgrade_test.py

The latte specifics is that we use unique commands only
and should not duplicates commands as it is done in case of CS.
So, make it use `round_robin=True`
in the `test_cluster_upgrade_latency_regression` test which is latte-based.

fix(upgrade): make latte-based upgrade test use round_robin only

---

jenkins-pipelines/manager/ubuntu22-manager-install.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-sanity.jenkinsfile
jenkins-pipelines/manager/ubuntu22-manager-upgrade.jenkinsfile
vars/managerPipeline.groovy

It's the latest Scylla release, so, should be used by default in Manager pipelines.
At the same time continue to use 2025.2 for some Manager jobs run on Ubuntu to keep testing coverage for this Scylla version

ci(manager): update default ScyllaDB version to 2025.3

---

test-cases/PR-provision-test-docker.yaml
test-cases/PR-provision-test.yaml

counters isn't supported now by tablets, removing those commands
to avoid the complexity of handling the variations around them.
they are not that important for the goal of those tests

fix(provision): remove counter commands from provision tests

---

Jenkinsfile
vars/getJenkinsLabels.groovy

this introce a way to use to validate xcloud support is working on any PR that might be touch related machinary

feature(xcloud): introduce provising test CI

---

vars/perfRegressionParallelPipelinebyRegion.groovy

The change is presented recently in https://github.com/scylladb/scylla-cluster-tests/pull/10927 cause to trigger failure. The comma is missed in the list.

fix(trigger): missed comma in performance trigger

---

sdcm/utils/hdrhistogram.py

The HDR histogram summary build is intermittently freezing, which occasionally leads to test timeouts.
This commit aims to address and fix the issue.
Issue: https://github.com/scylladb/scylla-cluster-tests/issues/10262

fix(hdr analyze): HDR histogram summary

---

defaults/cloud_config.yaml
sdcm/cluster.py
sdcm/cluster_cloud.py
sdcm/localhost.py
sdcm/logcollector.py
sdcm/remote/base.py
sdcm/remote/remote_base.py
sdcm/sct_config.py
sdcm/test_config.py
sdcm/tester.py
sdcm/utils/internal_modules.py

this commit introduce `XCloudConnectivityContainerMixin` that would have the machinery to grant us the access to the db machines that we are working with.
Depends: #11746

feature(scylla-cloud): add support to connect with machines

---

test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml

After the merge of the PR https://github.com/scylladb/scylla-cluster-tests/pull/10641 which made the rack count be `3`
by default in the config for the `custom-d1/workflow2` scenario,
it stopped being balanced from the rack-node relation point of view.
So, fix it by making cluster size be `2*6` instead of the `2*5`.
Also, increase the load numbers to compensate the grown cluster.
- [scylla-staging/valerii/vp-longevity-gce-custom-d1-workload2-hybrid-raid-repair#15](https://argus.scylladb.com/tests/scylla-cluster-tests/cd1b400f-f1ae-4f88-b337-3701d5d819ac)

fix(racks): Increase amount of nodes for `custom-d1/workflow2` config

---

test-cases/longevity/longevity-gce-custom-d1-workload1-hybrid-raid.yaml

After the merge of the PR https://github.com/scylladb/scylla-cluster-tests/pull/10641 which made the rack count be `3`
by default in the config for the `custom-d1/workflow1` scenario,
it stopped being balanced from the rack-node relation point of view.
So, fix it by making cluster size be `1*9` instead of the `1*8`.

fix(racks): Increase amount of nodes for `custom-d1/workflow1` config

---

artifacts_test.py
sdcm/nemesis.py
sdcm/sct_events/base.py
sdcm/tester.py
sdcm/utils/raft/common.py
upgrade_test.py

In order to make investigations easier, added more action logs covering more disruptions.
Also simplified the approach by inlining target and metadata to log lines.
closes: https://github.com/scylladb/qa-tasks/issues/1952

improvement(actions_log): added more actions log lines

---

.pre-commit-config.yaml

in some situations we do want to enable who doesn't have aws credentials to generate commits and able to run precommit (i.e. copilot)
for running tests we do need credentials, but that would be figured solved on it's own.

fix(.pre-commit-config.yaml): disable detect-aws-credentials if no credentials

---

artifacts_test.py
sdcm/cluster.py
utils/scylla_doctor.py

This PR changes some configuration options and adjusts PATH settings on nonroot 
installations of artifacts tests, allowing scylla-doctor to run here successfuly.
Some scylla-doctor collectors are disabled because either they require root privileges,
they assume system wide installation, or they depends on those that do. 
This is the second attempt at this PR as previous one didn't work for Ubuntu-based distros.
It also accounts for new version of Scylla Doctor and disables additional collectors that
don't work on non-root installs.
- **fix(artifacts_test.py): Remove offline non-root scylla_doctor skip**
- **improvement(sdcm/cluster.py): Add offline install to PATH**
- **improvement(scylla_doctor/nonroot): Disable non-working collectors**
- **fix(scylla_doctor): Always use a login session …

Support scylla-doctor on offline non-root tests (Take 2)

---

configurations/disable_simulated_racks.yaml
jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis-rbno-disabled.jenkinsfile
jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis.jenkinsfile

In branch `v17`, the `simulated_racks` setting was applied globally across all tests. 
However, the `v15` performance branch lacks many of the recent developments related to multi-rack 
support (e.g., simulated racks), and has historically been running with a single rack 
configuration.
By enabling multiple racks now, we risk invalidating historical results without a clear benefit. 
In Scylla Cloud, multi-rack has always been the default, but for consistency and comparability 
in performance testing, we’ve decided to:
- Keep vnodes performance under operations tests running with a single rack
- Run tablets tests with 3 racks
This change ensures continuity of results while still aligning with current best practices for 
tablets.
See related Scylla issue: …

fix(performance): disable simulated racks for vnodes operation tests in branch-v17

---

sdcm/utils/hdrhistogram.py

Increase future's timeout, as current is too low for alternator's performance testing.
YCSB produces mutliple files (each with it's own tag), while hdr histogram processing in sct does scan directory for all hdr files and run a different future over each file x tag combination. As a result each hdr histogram from ycsb will be processed 6 times (one for each tag).
This change is temporary.

Increate future timeout

---

sdcm/mgmt/operations.py

Restart Scylla only after schema restoration for versions 2024.1 or lower. For the newest versions of Scylla it's not required.
Docs:
https://manager.docs.scylladb.com/stable/restore/restore-schema.html 
https://manager.docs.scylladb.com/stable/restore/old-restore-schema.html

fix(manager): restart Scylla after schema restoration only for Scylla 2024.1 or lower

---

sdcm/logcollector.py

Sometimes, the contents of the `monitor_version` file can be something like `None:master:latest`, which causes the split to fail. Since that value is only used in the archive file name, it is safe to ignore the last part.
closes: #12092
```
ubuntu@balancer-test-feature--monitor-node-72f249d1-1:~$ cat scylla-grafana-monitoring-scylla-monitoring/monitor_version
None:master
```
vs
```
ubuntu@elasticity-test-feature--monitor-node-f2335597-1:~$ cat scylla-grafana-monitoring-scylla-monitoring/monitor_version
None:master:latest
```

fix(logcollector): fix getting monitoring version

---

sdcm/cluster.py

If `scylla_version` is given as a branch, e.g. `master:latest` or `branch-2025.3:latest` the version should be extracted from that string.

fix(cluster): fix getting monitoring version when scylla_version is a branch
